ManageIQ/manageiq-ui-classic

app/controllers/catalog_controller.rb
app/controllers/service_controller.rb
app/controllers/vm_common.rb
app/helpers/application_helper/dialogs.rb
spec/helpers/application_helper/dialogs_spec.rb

Only for old dialogs -> `Settings.product.old_dialog_user_ui`
Automation -> Automate -> Customization -> Buttons -> add a custom button to VM or Service that has a dialog with date/time pickers(preferably one shows past dates and another doesn't)
Go to Vm/Service summary page and click custom button with dialog - > see date/time pickery
**Before:** all data/time_pickers were  set as last one
*One that is set to show past dates:*
*One that is NOT set to show past dates:*
**After:** it's set one by one
*One that is set to show past dates:*
*One that is NOT set to show past dates:*
@miq-bot add_label wip, bug, gaprindashvili/yes

Move date_start logic from controllers to data/time_tag_options

---

app/controllers/host_controller.rb
app/controllers/mixins/explorer_show.rb
app/helpers/application_helper.rb
app/helpers/gtl_helper.rb
spec/controllers/host_controller_spec.rb
spec/helpers/application_helper_spec.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1516331
Pass @parent to the rendering routine. The variable is missing since #2727
Remove @use_action (see details in the commit message).
The @use_action is set
* for the whole Host controller                                                                  
(HostController.get_session_data)                                                                 
* in init_show_variables in ExplorerShow                                                         
that is called from:                                                                            
* hosts  -- not tested (don't have data)
* users
* groups
* patches -- not tested (don't have data)
* guest_application ("packages")  
I have added some specs. And have manually tested:
host --> …

GTL missing parent fix

---

app/controllers/application_controller.rb

In "My Tasks" grid if job.target_class job.target_id are given, rows
should link to entities. Currently VMs and ContainerImages should work.
Furthermore I am addin a rescue statement around the URL calculation so
that unexpected data in the job.target* fields will result into a row
w/o a link rather than a 500.
@enoodle, @karelhala : please review.
(not yet tested by me, working on it, and I don't have the data to test this on containers, help welcome)

GTL: fix "My Tasks"

---

app/controllers/chargeback_controller.rb

**fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1456825
Fix displaying clusters in _Compute Rate Assignment_ page when selecting
_'Selected Cluster/Deployment Roles'_ in _Assign to_ drop down menu even
when clusters have the same name (and belong to different providers) so
the name of their providers was added to their original names as prefix.
**Before:**
**After:**

Display all clusters in Compute Rate Assignment page

---

app/assets/javascripts/controllers/alerts/alerts_list_controller.js

Currently we show an unnecessary separator at `Monitoring > All Alerts` view - Possibly for more action items? (buttons, drop-downs etc.)
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1513410
_Screenshots_
Before:
After:
cc: @himdel @moolitayer

Fix unnecessary separator at monitoring/all_alerts view

---

app/controllers/ems_infra_controller.rb

This way the dashboard view of a provider's summary will not interfere with the provider list screen.
**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1500779

Force the showtype to nil when displaying the provider list page 🐍

---

app/helpers/application_helper/button/mass_transform_vm_button.rb
app/helpers/application_helper/button/transform_vm_button.rb

Depends-on: https://github.com/ManageIQ/manageiq/pull/16526

Use supports_vm_import? instead of validate_import_vm

---

app/helpers/gtl_helper.rb
spec/controllers/host_controller_spec.rb

There's still one more way to specify records for the GTL grid to
display -- @targets_hash. Adding that + specs for /host/edit.
https://bugzilla.redhat.com/show_bug.cgi?id=1515725

Add @targets_hash as another source of records for GTL.

---

app/helpers/application_helper/toolbar/x_ansible_tower_configured_system_center.rb
app/helpers/application_helper/toolbar/x_automation_manager_configured_system_center.rb

This PR is correcting mixin include for automation manager toolbar.
After selecting a host in automation manager, I was getting error in console:
```log
F, [2017-11-22T14:43:52.340898 #24616] FATAL -- : Error caught: [NameError] uninitialized constant ApplicationHelper::Toolbar::Configu
redSystem::AutomationPolicyMixin
/home/rblanco/devel/manageiq-ui-classic/app/helpers/application_helper/toolbar/x_ansible_tower_configured_system_center.rb:2:in `<clas
s:XAnsibleTowerConfiguredSystemCenter>'
/home/rblanco/devel/manageiq-ui-classic/app/helpers/application_helper/toolbar/x_ansible_tower_configured_system_center.rb:1:in `<top 
(required)>'
```
1) Go to _Automation_ → _Ansible Tower_ → _Explorer_
2) Select _Configured Systems_ accordion
3) …

Corrected mixin include for automation manager toolbar

---

app/views/layouts/_warn_msg.html.haml
app/views/report/_report_list.html.haml

When queuing new report in CI -> reports, and the report is not yet finished it will throw nasty error. This PR fixes such issue and won't allow users to do changes to such report unless it's finished.
https://bugzilla.redhat.com/show_bug.cgi?id=1508152

Do not show record's info when status of record is not completed

---

app/controllers/network_router_controller.rb

Router is not deleted if delete action is not supported and shows error message
Fixes this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1470754

show error message when deleting router

---

app/services/container_topology_service.rb
app/views/container_topology/show.html.haml

**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1516771

Do not display Hosts/VMs on the container topology screen

---

app/views/shared/summary/_textual_multilabel.html.haml

Before:
After:
_Compute_ → _Containers_ → _Container Builds_ → [select a build in GTL]

Corrected CSS class for sortable fields

---

app/assets/javascripts/controllers/live_metrics/util/metrics-parse-url-factroy.js

Compute --> Containers --> Container Nodes -> Monitoring -> Ad-hoc metrics
Attempting to open Ad hoc Metrics for Nodes yields an error message, because we do not have an ajax url defined. This PR adds the missing url, without specifying the tenant.
The backend proxy knows the correct tenant to use for Hawkular.
Notes: 
a. This only fixes the link for Container Nodes using Hawkular metrics.
b. Container Nodes using Prometheus will no longer show the error, but will fail to show node metrics.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1516320
Before
After:

Set initial url for ajax calls when parsing url params (Hawkular part)

---

app/helpers/container_group_helper/textual_summary.rb
app/views/container_project/_show_dashboard.html.haml

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1406741
Status is the term that appears on the provider side so theres no reason for this to be named differently.  
@moolitayer @nimrodshn please review
cc @bazulay

Rename 'phase' to 'status' for container groups summary page

---

app/controllers/mixins/actions/vm_actions/ownership.rb

The broken logic would return `nil` in case the class in question (Service, Vm, Template ...)
doesn't support (respond to) `with_ownership` class method -> this would seem
like the class in question doesn't support ownership change.
https://bugzilla.redhat.com/show_bug.cgi?id=1512644

Fix logic for service ownership

---

app/assets/javascripts/controllers/live_metrics/util/metrics-config-factory.js
app/assets/javascripts/controllers/live_metrics/util/metrics-http-factory.js
app/services/hawkular_proxy_service.rb
app/services/prometheus_proxy_service.rb

Compute --> Containers --> Container Nodes -> Monitoring -> Ad-hoc metrics
Attempting to open Ad hoc Metrics for Nodes on a provider with Prometheus metrics, does not query correctly. This PR translate the Hawakular query to Prometheus query.
Notes: 
a. Add the new `kubernetes-cadvisor` as the default job/tenant in Prometheus view.
b. Fix typo in the tenants list.
c. Only translate labels if we need the translation for the list view o/w leave tags as they are.
d. Remove `job` from the tags list, users should not have access to the jobs in the tags dropdown.
Note II:
Include commit from https://github.com/ManageIQ/manageiq-ui-classic/pull/2824 that fixes the link from node page.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1516320
Before
After

Translate hawkular node labels to prometheus

---

app/controllers/ops_controller/settings/zones.rb

- Queue the ntp settings reload for all servers in the zone.
- Ensure that the zone has an ID before trying to save its settings
https://bugzilla.redhat.com/show_bug.cgi?id=1476365
Depends on https://github.com/ManageIQ/manageiq/pull/16393

Ntp settings

---

app/services/prometheus_proxy_service.rb

Fix typo in function name:
`replace_hawular_tags => replace_hawkular_tags`
See: https://github.com/ManageIQ/manageiq-ui-classic/pull/2826#issuecomment-347234073

fix typo in function name

---

app/assets/javascripts/miq_application.js

The topology screens on IE11 did not display fonticon-based nodes because the `ChildNode.remove()` called in `fontIconChar` fails as it is not supported in IE11. This fix replaces the call with `ChildNode.parentNode.removeChild()` when it's not available.
@miq-bot add_label bug, topology
https://bugzilla.redhat.com/show_bug.cgi?id=1516823

Use parentNode.removeChild in IE11 when determining fonticon char

---

app/controllers/application_controller/buttons.rb
app/controllers/application_controller/dialog_runner.rb
app/controllers/infra_networking_controller.rb
app/controllers/mixins/custom_button_dialog_form_mixin.rb
app/controllers/ops_controller.rb
app/controllers/ops_controller/settings/common.rb
app/views/ops/_all_tabs.html.haml
app/views/ops/_detail_page.html.haml
app/views/ops/_rbac_tenant_details.html.haml
app/views/ops/_rbac_user_details.html.haml
app/views/ops/explorer.html.haml
spec/controllers/application_controller/dialog_runner_spec.rb
spec/controllers/ops_controller_spec.rb

Automate - >Automatization -> Customization -> Buttons -> Add custom button for Switch,User, Tenant, Group that has(!) a dialog
Try it out:
*Switch*
Compute -> Infrastructure -> choose a switch -> click on the button with a dialog
*User, Tenant, Group*
Configuration -> Access Control -> choose user, tenant or group -> click on the button with a dialog
After (example):
A dialog form should be displayed. `Submit/Cancel` should work. 
Setting of calendar is resolved in https://github.com/ManageIQ/manageiq-ui-classic/pull/2775 should be merged before this one.
@miq-bot add_label gaprindashvili/yes, wip
TODO:

Fix custom button with dialog in explorer  

---

app/assets/javascripts/controllers/report_data_controller.js
app/controllers/application_controller.rb
app/controllers/miq_request_controller.rb
spec/controllers/miq_request_controller_spec.rb

1. Services -> Requests
2. Select only Approved, or only Denied requests
3. Press `Apply`
BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1512719
Closes: #2742
@mzazrivec : PTAL
* ~~Looking as some strange stuff in the case statement,~~ will be done in a separate PR.
* ~~looking at what code to remove~~ removed just a bit
* specs
The filters are composed from SQL fragments. So no scopes for now :-(. 
It's handled (statefully) in `/report_data` via the "exceptions". This one is for "MiqRequest" and calls `page_params`.
So we can keep the code that updates the session when form fields are changed. (That needs a rework no soner then when it's redone to client side.)
And all that is really needed is the reload of the GTL grid -- that will reload `/report_data` and apply the changed filter …

Fix Service request filtering

---

app/controllers/mixins/containers_common_mixin.rb
spec/controllers/container_node_controller_spec.rb

We were rendering a blank page after the compliance check for a container node has been initiated. This PR forces the flash rendering as there's always a positive/negative message to be displayed.
https://bugzilla.redhat.com/show_bug.cgi?id=1516864

Render flash when running compliance check for a container node 🐞

---

app/controllers/application_controller/ci_processing.rb
spec/controllers/application_controller/ci_processing_spec.rb

Compute -> Cloud -> Stacks
Check one Orchestration Stack
Configuration -> Remove Orchestration Stack from Inventory 
Check again Orchestration Stack that was deleted
Configuration -> Remove Orchestration Stack from Inventory
Before:
After:
@miq-bot add_label bug, gaprindashvili/yes, blocker
@h-kataria please have a look, thanks :) Maybe you can think about nicer error message.
https://bugzilla.redhat.com/show_bug.cgi?id=1515310

Add flash message when OrchestrationStack delete returns an exception

---

app/assets/javascripts/components/physical_infrastructures/physical-server-toolbar.js
app/helpers/application_helper/toolbar/physical_server_center.rb
app/helpers/application_helper/toolbar/physical_servers_center.rb

This PR contains support for refresh Physical Servers.

add support for refreshing physical servers

---

app/controllers/generic_object_controller.rb
app/helpers/generic_object_helper/textual_summary.rb
app/views/shared/summary/_textual.html.haml
spec/helpers/generic_object_helper/textual_summary_spec.rb

When Generic Object instances do not have `Attributes`, `Associations` or `Methods` defined, the Summary screen explicitly needs to specify that.
For e.g. The GO Summary screen needs to display `No Attributes defined` when there are no `Attributes` defined.
While I'm still waiting for NEEDINFO on the BZ, I think the reason why the BZ was opened was because there was no explicit mention of `Attributes` in the Summary screen, when the `Attributes` were not defined for a GO instance.
Before - GO Summary Screen does not mention missing `Attributes`, `Associations` or `Methods`
After - GO Summary Screen explicitly mentions missing `Attributes`, `Associations` or `Methods`
(For reference) GO Summary screen that shows `Attributes`, `Associations`,  `Methods` when these properties are available - …

Display 'No Attributes defined' in a Generic Object Summary screen when there are no Attributes defined for the GO instance

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller/ops_rbac_spec.rb

Initialize the tags_tree and @group when switching between tabs on group editor.
Links 
-------
https://bugzilla.redhat.com/show_bug.cgi?id=1501346
----------------------------
1. Navigate to add group page
2. Switch to 'Tag based on expression' on 'My company Tags'
3. Select 'Host & Cluster' tab
4. Select 'My company Tags'
5. Switch tag filter to 'Specific Tags'

Tag expression fix for group editor

---

app/views/layouts/angular/_multi_auth_credentials.html.haml

Follow up for https://github.com/ManageIQ/manageiq-ui-classic/pull/2666
https://bugzilla.redhat.com/show_bug.cgi?id=1517061
/cc @jerryk55

Refer `::Settings` value before rendering SmartState docker credentials

---

app/helpers/generic_object_helper/textual_summary.rb
app/views/shared/summary/_textual.html.haml

A follow-up for PR #2846 -
An explicit parameter `:no-value` which will be used in the textual summary haml to skip rendering the value column.

Follow-up for 2846

---

app/helpers/application_helper/button/generic_feature_button.rb

Right now, if a `@record` has a `supports_foo?` method, but calling that method fails with a `NoMethodError`, `GenericFeatureButton#visible?` will try to fall back to `AvailabilityMixin` and fail on missing `is_available?`.
We should only fall back to `is_available?` if the actual `supports_foo?` is missing.
Thus, using `respond_to?` to decide which to call, and not catching any exceptions.
Cc @borod108 
(`gaprindashvili/no` because this does have a subtle difference in behaviour and I'm not sure this won't cause *any* regressions..)

GenericFeatureButton - don't catch NoMethodError

---

app/helpers/application_helper/button/new_cloud_tenant.rb
app/helpers/application_helper/button/new_flavor.rb
app/helpers/application_helper/button/new_host_aggregate.rb
app/helpers/application_helper/toolbar/cloud_tenants_center.rb
app/helpers/application_helper/toolbar/flavors_center.rb
app/helpers/application_helper/toolbar/host_aggregates_center.rb
spec/helpers/application_helper/buttons/new_cloud_tenant_spec.rb
spec/helpers/application_helper/buttons/new_flavor_spec.rb
spec/helpers/application_helper/buttons/new_host_aggregate_spec.rb

There were some cloud-related item buttons that were enabled even when there was no available provider for them:
* Creating a new Flavor
* Creating a new Cloud Tenant
* Creating a new Host Aggregate
These now will be disabled when there is no related provider available. Tests included to make @martinpovolny happy.
https://bugzilla.redhat.com/show_bug.cgi?id=1516877

Disable buttons for adding new cloud items when no provider available 🐛

---

product/views/MiddlewareDeployment.yaml

Add a Middleware Server Group column to Middleware Deployments list.
When the MW deployment is deployed to a server group (to each server there), let's show the group in the deployments list as well.
Resolves: [BUG 1443155](https://bugzilla.redhat.com/show_bug.cgi?id=1443155)

Add column to MW Deployments

---

app/controllers/ops_controller.rb
app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller_spec.rb

1. Create new tenant
2. Create a group and set it to have with new tenant (from step 1) and  `EvmRole-tenant_administrator` role
3. Create new user and set it to have only the new group (from step 2)
4. Logout and login as the created user (from step 3)
5. Navigate to user -> Configuration
**Before:**
*Log:*
```
F, [2017-11-28T13:42:47.420122 #53404] FATAL -- : Error caught: [ActionView::Template::Error] undefined method `>=' for nil:NilClass
ManageIQ/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:366:in `button_class_name'
ManageIQ/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:389:in `get_custom_buttons'
ManageIQ/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:299:in `custom_button_selects' …
```

Set @tree_selected_model when explorer or tree_select is called in OPS

---

spec/support/controller_helper.rb

Tests: `match_gtl_options` should ignore order in `:selected_records`.
This should fix a sporadic test failure in https://github.com/ManageIQ/manageiq-ui-classic/blob/master/spec/controllers/host_controller_spec.rb#L24
https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/308502672
Ping @skateman

Tests: match_gtl_options should ignore order in :selected_records.

---

app/helpers/container_summary_helper.rb

`Containers` link was broken at container provider relationships.
This patch fixes the link.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1515255
cc @himdel @zeari

Containers link broken on container provider relationships

---

app/controllers/vm_remote.rb

Images we added to our HTML5 Console page were blocked by the CSP because of the quotes missing around 'self'.

Fixed CSP for HTML5 Console

---

app/helpers/textual_mixins/textual_devices.rb

On the container textual summary we were showing the sockets and
cores_per_socket even if these were unset.
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1514463

Only show sockets and cores_per_socket if present

---

app/assets/javascripts/components/auth-credentials.js

When adding a new Foreman / Ansible Tower provider, the password input label should
say `Password`. The form should only say `New Password` when changing password of
an existing provider.
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1518720

auth-credentials: fix label for password field when adding new provider

---

app/services/container_topology_service.rb
app/views/container_topology/show.html.haml

These objects should be displayed in the topology, the BZ was invalid.
This reverts commit 4c7389d83020879be09536098caed668114c49d3.
https://bugzilla.redhat.com/show_bug.cgi?id=1516771
@miq-bot add_label gaprindashvili/yes

Revert "Do not display Hosts/VMs on the container topology screen"

---

app/controllers/ansible_credential_controller.rb
app/controllers/ansible_repository_controller.rb
app/controllers/cloud_volume_snapshot_controller.rb
app/controllers/ems_common.rb
app/controllers/ems_physical_infra_controller.rb
app/controllers/generic_object_controller.rb
app/controllers/mixins/generic_show_mixin.rb
app/controllers/service_controller.rb
app/controllers/storage_controller.rb

Changes done:
1. use `ui_lookup(:models => model.to_s)` rather than `ui_lookup(:tables => table_name)`
2. Get rid of the `table_name` parameter, since we can use `ui_lookup(:models => model.to_s)`
@martinpovolny PTAL

GenericShowMixin: simplify nested_list()

---

app/controllers/middleware_datasource_controller.rb

Once the operation of MW datasource is initiated, display a toast which describes what happened more truthfully.
replace: `The selected datasources were removed`
to: `The selected datasources removal was initiated`
related to: https://github.com/ManageIQ/manageiq-providers-hawkular/pull/111
before:
after:

Fix MW Datasource removal toast text

---

bower.json

When opening a SPICE console served by RHEV 4.1 provider, the browser's CPU usage is significantly high. Updating the SPICE-HTML5 client to the latest version fixes the issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1518273

Update SPICE to the latest version

---

app/views/miq_ae_customization/editor.html.haml

This change should enable autofocus on the first required field in the Dialog Editor (_Dialog's name_).
This change was suggested in https://bugzilla.redhat.com/show_bug.cgi?id=1514117#c12 (# 1)
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1514117
Automate → Automation → Customization → Service Dialog → Edit / Add a dialog

Added autofocus on "Dialog's name" field

---

product/views/CloudVolume-based_volumes.yaml
product/views/CloudVolume.yaml
product/views/CloudVolumeBackup-cloud_volume_backups.yaml
product/views/CloudVolumeBackup.yaml
product/views/CloudVolumeSnapshot-cloud_volume_snapshots.yaml
product/views/CloudVolumeSnapshot.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=1455270
Cloud volume list incorrectly labeled the Storage Manager column as Cloud Provider.
This commit also fixes the same problem for Cloud Volume backups and snapshots.

bz 1455270: Fix Storage Manager label for volume lists

---

app/views/layouts/_perf_charts.html.haml

Add "spacer" class div to fix top margin of card area on C & U screen
Old
New

Fix Cap & U card positioning

---

app/controllers/cloud_tenant_controller.rb

Cause flash messages to be rendered when deleting cloud tenants from the list view.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1489394

Render flash messages when deleting cloud tenants from list view

---

app/helpers/vm_helper/textual_summary.rb

For VMs which do not set cpu_sockets or cpu_cores_per_socket we only
want to show cpu_total_cores.  There is a check for this already but
since cpu_sockets has a default value of 1 (assuming for divide-by-zero
issues) and cpu_total_cores is a virtual delegate with a default value
of 1 this is always showing up as ' (1 Socket x 0 Cores)'.
Before:
After:
The behavior was changed by https://github.com/ManageIQ/manageiq/pull/12911 which conceptually changed `cpu_cores_per_socket` from `hardware.nil? ? 0 : hardware.cpu_cores_per_socket` to `hardware.try(:cpu_cores_per_socket) || 0`
https://bugzilla.redhat.com/show_bug.cgi?id=1514463

Fix CPU summary for VMs without cores_per_socket

---

app/controllers/storage_controller.rb
spec/controllers/storage_controller_spec.rb

Compute -> Infra -> Datastores -> [Some Datastore] -> All Managed VM Templates
Before the fix, it would throw an error / exception. With the fix, rendering of the template list
should work.
https://bugzilla.redhat.com/show_bug.cgi?id=1515312

Fix rendering of datastore's list of templates

---

lib/tasks/manageiq/ui_tasks.rake

This was a fix from #1887, except as it is now, it only works when called via `update:ui`, not when `webpack:compile` is being called directly.
Moving to the task implementation. (+ also covering `webpack:clobber` now)
@NickLaMuro Take a look please? :)
I *think* `EvmRakeHelper` should always be available so we don't really need the `defined?` condition do we? Or was there a different reason?

Move with_dummy_database... around the implementation of webpack:compile, not the call

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/controllers/application_controller/buttons.rb
app/controllers/catalog_controller.rb
app/views/shared/dialogs/_dialog_provision.html.haml
app/views/shared/dialogs/_dialog_user.html.haml
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js

As described in https://bugzilla.redhat.com/show_bug.cgi?id=1518430, the message that was being displayed as well as the redirect location were incorrect after ordering a service catalog.
This change passes down a parameter for the redirect location so that other things like custom buttons can then pass down their own "finished with submitting" redirect path if necessary. We can also pass down the message later on if that needs to be changed on a case by case basis as well, but for the purposes of this BZ I've changed it to the original wording.
/cc @gmcculloug 
@miq-bot add_label gaprindashvili/yes, bug, fine/no
@h-kataria Let me know if you think someone else should be assigned.
@d-m-u Can you review please?

Change redirect path and message after ordering service catalog

---

app/views/static/dropdown-menu.html.haml

When the link has `data-remote=""`, downloading a PDF doesn't work. (The request succeeds, the data is returned, but the browser ignores it and doesn't download.)
`data-remote` is used for other things, like minimizing the dashboard.
Thus, changing to use `ng-attr-data-remote`, which will do the same thing as before when the attribute value is provided, but won't add the attr when empty.
Cc @mzazrivec , @ZitaNemeckova 
https://bugzilla.redhat.com/show_bug.cgi?id=1516784

dropdownMenu - don't use data-remote when not provided

---

app/assets/javascripts/controllers/toolbar_controller.js

clicking on a disabled toolbar item doesn't really do anything in `miqToolbarOnClick`, but the `itemClicked` rx message still got sent, causing the paging toolbar to disappear (by calling `ReportDataController#setExtraClasses`).
Changing to only send the event when a visible non-disabled button is clicked.
https://bugzilla.redhat.com/show_bug.cgi?id=1518929
Cc @karelhala

ToolbarController#setClickHandler - don't handle click for disabled toolbar items

---

app/controllers/application_controller.rb
spec/controllers/middleware_server_controller_spec.rb

Adding exceptions is the worst way of fixing this issue, however, after consulting with @epwinchell I did not find any other option. For now a `fonticon` has a higher priority than a `fileicon` which is a problem in the middleware server listview. Eventually we want to swap these priorities, however, we have some legacy `fileicon`s that are PNG based and they should be deleted, but for now the quadicons depend on them. So until we have `fonticon` support in quadicons, we can't swap the priority and adding this exception seemed the simplest possible solution. 
But maybe I'm wrong and @karelhala, @himdel or @martinpovolny could come up with a better idea.
**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1509935

Add an exception for middleware server listicons to prefer fileicon

---

app/views/ops/_settings_cu_collection_tab.html.haml
spec/views/ops/_settings_cu_collection_tab.html.haml_spec.rb

Show a note if there is no data to populate the Clusters and/or Datastore trees on the C/U tab under Configuration.
@miq-bot add_label bug, settings, blocker
https://bugzilla.redhat.com/show_bug.cgi?id=1518087

Check for nil Clusters/Datastores on C/U tab

---

config/routes.rb

How to reproduce
1. Compute -> Cloud -> Cloud Provides -> List of Images  
2. Select image(s) from list
3. Policy -> Policy simulation
This is a fix for fine only. As things are in master, now we use angular to render quadicons
and the fix / problem does not apply there. 
https://bugzilla.redhat.com/show_bug.cgi?id=1482458

[FINE] Fix routing error for image policy simulation

---

app/views/report/explorer.html.haml

When refreshing an Edit Report Menu subpage (see the BZ for reproduction details) the right cell becomes empty because the angular-based tree is not rendered in the time the `ManageIQ.afterOnload` is being :angry: **eval**uated. Together with all the `miqTreeForceActivateNode` calls this is a good victim for :scissors: :toilet: refactoring in the future. In general this `afterOnload` seems to me as a big hack and the simplest way to fix this without making possible breaking changes was to wrap the tree activation in a `setTimeout`. The code seems ancient and as it is included inline in a template with interpolation, I don't think there's a meaningful way to test this.
https://bugzilla.redhat.com/show_bug.cgi?id=1519644

Delay the force node activation call on the edit report menu explorer

---

app/controllers/mixins/ems_common_angular.rb

Adding a new hawkular provider throws this error
**Credential validation was not successful: wrong number of arguments (given 0, expected 6)**
We need to add the hawkular provider.
Fix https://github.com/ManageIQ/manageiq-ui-classic/issues/2572
```ruby
[----] I, [2017-10-31T09:26:25.828095 #29354:3e6c910]  INFO -- : Started GET "/ws/notifications" for 127.0.0.1 at 2017-10-31 09:26:25 +0100
[----] F, [2017-10-31T09:26:25.872112 #29354:3e6c910] FATAL -- :   
[----] F, [2017-10-31T09:26:25.872172 #29354:3e6c910] FATAL -- : ActionController::RoutingError (No route matches [GET] "/ws/notifications"):
[----] F, [2017-10-31T09:26:25.872211 #29354:3e6c910] FATAL -- :   
[----] F, [2017-10-31T09:26:25.872239 #29354:3e6c910] FATAL -- : actionpack (5.0.6) …
```

Fix credential validation in Hawkular provider about number of arguments

---

app/controllers/mixins/ems_common_angular.rb

Do not create incomplete amqp fallback endpoints if there are no
hostnames provided via the input form.
@miq-bot add_label networks

Ignore empty amqp fallback hostnames

---

app/controllers/ops_controller/settings/help_menu.rb
app/presenters/menu/default_menu.rb

The submit button was not disabled under [certain conditions](https://bugzilla.redhat.com/show_bug.cgi?id=1517908#c2) in the settings -> region -> help menu.
Backend part: https://github.com/ManageIQ/manageiq/pull/16549
https://bugzilla.redhat.com/show_bug.cgi?id=1517908

Fix handling default values for help menu settings

---

app/controllers/storage_controller/storage_pod.rb
spec/controllers/storage_controller_spec.rb

Selected records should be passed to get_view only when records cannot be specified using associations or named scopes.
Furthemore this imperfect implementation was broken in during the GTL conversion.
https://bugzilla.redhat.com/show_bug.cgi?id=1501063
Ping @lgalis, @tumido : please, review

Fix for storages under storage pods

---

app/controllers/miq_policy_controller.rb
lib/report_formatter/timeline_message.rb
spec/controllers/miq_policy_controller_spec.rb
spec/lib/report_formater/timeline_spec.rb

The permalinks to assigned policy profiles on a policy event VM timeline have been generated with the wrong GET param. Also the parameter had the old style underscore tree node ID instead of the hyphenated version.
To reproduce this, you need a VM with policy timeline events collected. If you need help, I can provide you a database created by @izapolsk. 
https://bugzilla.redhat.com/show_bug.cgi?id=1500420

Generate the policy profile permalink on the timelines correctly

---

app/controllers/application_controller.rb
spec/controllers/service_controller_spec.rb

`long_id` in report data comes from the `@record.id` field - but Ruby ints can be bigger than JS ints => we 
need a string so that it's not bigger than INT_MAX in JS, for large region numbers.
Cc @karelhala

ReportData - change long_id to string

---

app/controllers/application_controller/miq_request_methods.rb
app/helpers/gtl_helper.rb
spec/controllers/miq_request_controller_spec.rb

Passing of :selected_ids throught get_view(..) is not implemented.
We shall implement that after Gaprindashvili.
For now pass record ids throught an instance variable.
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1513303
* ~~write a spec~~
* ~~create TODO item for passing the selected_records through `get_view`~~

MiqRequest: fix listing of affected items.

---

app/controllers/alerts_list_controller.rb
app/controllers/alerts_most_recent_controller.rb
app/controllers/alerts_overview_controller.rb

* Select anything under Monitor --> Alerts
* observe that the menu section "Alerts" is (not) active
https://bugzilla.redhat.com/show_bug.cgi?id=1501037

Assign proper menu section to alert* controllers.

---

app/controllers/application_controller/miq_request_methods.rb
app/views/miq_request/_pre_prov.html.haml

1. Go to Compute->Infrastructure->Virtual Machines  
2. From Lifecycle-> VM Provision
3. Sort templates by CPUs
4. Observe that sorting does (not) work
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1501053

Provisioning form: "logical_cpus" is called "cpu_total_cores".

---

app/helpers/application_helper/toolbar/flavor_center.rb

Adds delete action to flavor toolbar.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1519236

Add delete action to flavor toolbar

---

spec/controllers/storage_controller_spec.rb

The behavior changed in 716037a305eb462f5ee6a6ae4caadd593f7ee015 and PR https://github.com/ManageIQ/manageiq-ui-classic/pull/2902

The id returned by report_data() is now a string

---

app/helpers/textual_mixins/textual_authentications_status.rb
app/helpers/textual_mixins/textual_metrics_status.rb

Somehow the container PDF report summary generation is different from the other screens. I'm not sure about the fix, @martinpovolny could you please check? 
https://bugzilla.redhat.com/show_bug.cgi?id=1516710

Use record instead of ems instance var in textual authentication status

---

app/services/middleware_topology_service.rb
spec/javascripts/controllers/middleware/middleware_topology_controller_spec.js
spec/javascripts/fixtures/json/middleware_topology_response.json
spec/services/middleware_topology_service_spec.rb

When there are any providers with EAP or Wildfly server monitored, they were not displayed in topology view. This PR fixes such issue
https://bugzilla.redhat.com/show_bug.cgi?id=1512549

Add EAP and Wildfly to allowed types for MW topology

---

app/assets/javascripts/controllers/container_dashboard/container_dashboard_controller.js
app/assets/javascripts/controllers/container_dashboard/container_project_dashboard_controller.js
app/services/container_dashboard_service.rb
app/services/container_project_dashboard_service.rb
app/services/container_service_mixin.rb
app/services/dashboard_service.rb
app/services/ems_infra_dashboard_service.rb
spec/javascripts/fixtures/json/container_dashboard_no_data_response.json
spec/javascripts/fixtures/json/container_dashboard_response.json
spec/javascripts/fixtures/json/container_project_dashboard_response.json
spec/services/container_dashboard_service_spec.rb

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1509956
~~Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/2677~~
Before:
After:
@moolitayer @himdel 
@miq-bot add_label compute/containers, gaprindashvili/yes

Change metric accuracy in container projects dashboard

---

app/services/hawkular_proxy_service.rb

Compute --> Containers --> Container Nodes -> Monitoring -> Ad-hoc metrics
Because of a change in Hawkulars API [1] we need to clean up the strings we get from the /tenant endpoint before using them.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1518538
Before, we have a tenants named `name:hash`, trying to use them will end with error 500.
After ( tenant names are cleaned )
[1] https://issues.jboss.org/browse/HWKMETRICS-745

Clean tenant names

---

app/services/container_service_mixin.rb

~~BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1519530~~ solved by #2762 
followup to https://github.com/ManageIQ/manageiq-ui-classic/pull/2762
EDIT: This doesnt solve the BZ but it still makes the code a little safer
@himdel Please review
@miq-bot add_label bug, providers/containers

handle nil values in dashbaord trend data

---

app/views/catalog/_st_form.html.haml

This PR uses changes from backend in https://github.com/ManageIQ/manageiq/pull/16559 to determine whether options in the drop down should be available or disabled based upon results returned in hash by backend method.
https://bugzilla.redhat.com/show_bug.cgi?id=1515371
before all options were always available:
after:
@mkanoor please test/review.
@dclarizio please review, this PR depends upon core PR https://github.com/ManageIQ/manageiq/pull/16559

UI changes to show options as disabled if those are not supported.

---

app/assets/javascripts/controllers/report_data_controller.js
spec/javascripts/controllers/report_data_controller_spec.js
spec/javascripts/fixtures/json/report_data_response.json

Noticed that `ManageIQ.gridChecks` now contains compressed id's instead of the non-compressed ids (or long ids).
This seems like a recent change...
and has introduced a bug, because newer screens like Physical Servers and Generic Object Definitions, use the id to pass it to the REST API for a Delete operation
Since the API does not recognize the compressed id, it causes a 404 error.
The change in the PR fixes the issue.
Although, I would need @karelhala input here, because we did not need this code before.
@karelhala Any idea what changed? Also should this be fixed some place else (and not here)?

Add `long_id`s (original, uncompressed id's) in ManageIQ.gridChecks

---

app/controllers/ems_common.rb
app/controllers/mixins/ems_common_angular.rb
app/views/shared/views/ems_common/angular/_form.html.haml

Changing regions, changes all the inventory as AWS is very region based
If a user wishes to chnage region, they should create another AWS
provider and remove the original.
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1517076
This also affects Google, and Azure.

Disable editing Region on Cloud Edit Screen

---

app/controllers/mixins/ems_common_angular.rb

Provider forms: pass flash messages throught the session rather than url
https://bugzilla.redhat.com/show_bug.cgi?id=1475303

Provider forms: pass flash messages throught the session rather than url

---

app/helpers/application_helper/toolbar/miq_groups_center.rb

**fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1514723
Display option to _Delete selected Groups_ under _Configuration -> Access Control
EVM Groups_ and enable the option when selecting multiple Groups in the list.
_Delete selected Groups_ button was not visible due to the fact that it was being set to
visible based upon the result from _RbacGroupDelete_ class, which expects `@record`
to be set.
**Before:**
**After:**

Display option Delete selected Groups

---

app/controllers/application_controller.rb

`Containers` link is broken when `state` is nill - this patch fixes this behavior.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1519382
cc: @himdel

Fix broken containers link in container dashboard

---

app/controllers/vm_common.rb
spec/controllers/vm_infra_controller_spec.rb

Include the helper `ProvisionCustomizeHelper` in `VmCommon` in order to make the helper methods accessible in VM controllers.
https://bugzilla.redhat.com/show_bug.cgi?id=1515710

Fix `ProvisionCustomizeHelper` helper method access in VM controllers

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/assets/javascripts/services/dialog_field_refresh_service.js
app/controllers/application_controller/buttons.rb
app/controllers/catalog_controller.rb
app/services/dialog_local_service.rb
app/views/shared/dialogs/_dialog_provision.html.haml
app/views/shared/dialogs/_dialog_user.html.haml
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
spec/javascripts/services/dialog_field_refresh_service_spec.js
spec/services/dialog_local_service_spec.rb

Resource action id, target id, and target type need to be passed in order to establish the context that some dynamic methods may use when going through automate. This corresponds with @jntullo's [API PR here](https://github.com/ManageIQ/manageiq-api/pull/231). 
https://bugzilla.redhat.com/show_bug.cgi?id=1518390
@d-m-u, @jntullo Mind taking a look and making sure I didn't miss something obvious?

Pass additional information to the API when ordering a service catalog

---

app/presenters/widget_presenter.rb
app/views/static/dropdown-menu.html.haml

This makes the "Full Screen" button in Dashboard widgets open the fullscreen version in a new window/tab.
Cc @martinpovolny, @ZitaNemeckova

Dashboard - fullscreen - open in new tab

---

app/views/layouts/listnav/_show_list.html.haml
spec/controllers/ems_cloud_controller_spec.rb

Render 'Set Default' button in listnav only if `@my_searches` is not blank
Before 
`Generic Object Definition` - 'Set Default' button rendered even though `@my_searches` is blank
-------
After
`Generic Object Definition`(`@my_searches` array is blank) - `Set Default` button not rendered -
-------
Other `show_list` screens for reference -
Ems Infra(`@my_searches` array contains value - `Hyper`) with no Default set-
---------------
Ems Cloud(`@my_searches` array contains value - `['Am', 'Az']`)  with `Az` set to Default -
-----------------

Do not render 'Set Default' button in listnav if saved searches don't exist

---

app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

Related to #2562, it is a continuation for other objects. This one will make custom buttons for the following classes go through the new dialog-user ui-component:
`CloudTenant`
`CloudVolume`
`ContainerNode`
`EmsCluster`
`Host`
`InfraManager` (Provider)
`MiqTemplate`
`Storage`
https://www.pivotaltracker.com/story/show/152449649
/cc @gmcculloug 
@d-m-u Can you review, please?
@himdel Can you also review or tag someone to review, please?
@miq-bot add_label gaprindashvili/yes, enhancement, automation/automate

Enable new dialog-user feature for more custom buttons

---

app/controllers/ems_infra_controller.rb

1. Log file should be used for actual application errors, not for logging error flash messages (this would go against what we do in the rest of our application)
2. We cannot put localized messages into a log file, its content needs to be plain English only.
@martinpovolny PTAL

EmsInfraController: do not log error flash messages

---

app/assets/javascripts/components/ops/tenant-component.js
spec/javascripts/components/ops/tenant-component_spec.js

user > Configuration > Access Control - Tenant - add a new tenant with a duplicate name
Don't show the error modal on validation errors - this time in TenantComponent.
https://bugzilla.redhat.com/show_bug.cgi?id=1507852

TenantComponent - don't error modal on validation errors

---

app/controllers/vm_remote.rb
app/views/vm_common/console_webmks.html.haml

The WebMKS connections will be [proxied](https://github.com/ManageIQ/manageiq/pull/16490) through the `WebsocketWorker` similarly to VNC/SPICE. The required motifications in the UI might seem not the most ideal, but I tried to minimize the number of changes for backporting. I am planning to continue @bmclaughlin's effort with the [remote console unification](https://github.com/ManageIQ/manageiq-ui-classic/pull/2662) in a future PR.
https://bugzilla.redhat.com/show_bug.cgi?id=1504299

Adjust the remote console views/controllers for WebMKS proxying

---

app/controllers/report_controller.rb
app/helpers/application_helper.rb
spec/controllers/report_controller_spec.rb

When queuing new report inside CI -> reports and clicking on such newly created report, wrong url is present and user is redirected to some wrong report. This PR fixes such issue by adding `x_node` to url if new report is queued.
https://bugzilla.redhat.com/show_bug.cgi?id=1508151

Return whole x_node if new report is queued in reports tab for CI

---

app/views/shared/buttons/_column_lists.html.haml

Add missing "btn-block" class to button for proper responsive styling
https://bugzilla.redhat.com/show_bug.cgi?id=1516840
Old
New

Custom Button Group Edit styling  fix

---

app/presenters/widget_presenter.rb

1. Go to Cloud Intel -> Dashboard
2. for each and every widget present, try do download its PDF report (if possible). Correct report should be rendered, no error should occur.
3. for each and every widget present, try to go full screen (if possible). Correct report should be rendered, no error should occur.
for `rr_id=...` we need to correctly pass the report result id, not the widget id.
https://bugzilla.redhat.com/show_bug.cgi?id=1518949
https://bugzilla.redhat.com/show_bug.cgi?id=1517059

Fix PDF and full-screen links for dashboard widgets

---

app/helpers/quadicon_helper.rb
spec/helpers/quadicon_helper_spec.rb

Follow-up for #2794
- Fixes the `UrlGenerationError` crash in #2794
- Displays correct quadicon hover url

Follow-up for #2794 (fix the UrlGenerationError crash)

---

app/controllers/report_controller.rb
spec/controllers/report_controller_spec.rb

Go to: Cloud Intel -> Reports -> Import/Export -> Widgets. Make sure the export button is not duplicated and that the export button works correctly.
https://bugzilla.redhat.com/show_bug.cgi?id=1518945

Fix export button in widget export screen

---

app/assets/javascripts/miq_qe.js

When performing call `sendDataWithRx({"action": "get_item", "controller": "reportDataController", "data": ["10r1107"]})` on items without name it would throw error. This PR fixes such issue and enables to call `get_item` with full ID `sendDataWithRx({"action": "get_item", "controller": "reportDataController", "data": [10000000001107]})`

Fix bug where calling getItem without name text would cause error

---

app/views/layouts/_perf_options.html.haml

This PR updates the Cap & U options to use PF "form-horizontal" styling
Old
After

Update Cap & U option styling

---

app/controllers/miq_ae_customization_controller/dialogs.rb

This PR allows to have a hyphen in the Dialog Field's name.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1518600
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1518600
Try to name a Field by a name with hyphen

[FINE] Changed validation of Service Dialog Fields to allow hyphen

---

app/controllers/provider_foreman_controller.rb
spec/controllers/provider_foreman_controller_spec.rb

please read the commit messages
partial fix for: https://github.com/ManageIQ/manageiq-ui-classic/issues/2927

Foreman fixes

---

app/controllers/ops_controller/settings/zones.rb

`@zone` may be `nil` in the else branch and therefore failing to retrieve `.name`. Since the name is not necessary in that flash message, it can be safely removed.
https://bugzilla.redhat.com/show_bug.cgi?id=1520999

Remove an extraneous string format causing errors.

---

app/controllers/ems_infra_controller.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1402867
In the scaling UI, added checks to allow scaling up but not down.
Scale down is handled explicitly via a separate UI action with
validation around maintenance mode on the node and lack of active
VMs.

bz 1402867: Prevent scale down in scaling UI

---

app/views/report/_export_custom_reports.html.haml

`Cloud Intel -> Reports -> Import/Export (accordion) -> Custom Reports (treenode)`
**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1519341
@miq-bot assign @epwinchell 

Unembed Custom Report Export select to hide the unnecessary scrollbar

---

app/controllers/automation_manager_controller.rb

* go to Automation --> Ansible Tower --> Explorer
* switch to grid view
* click on tree notes representing individual records
* observe (in)correct styling of main div
@lgalis, @mzazrivec, please, review.

Remove the "sand" style when displaying individual record in Ansible.

---

app/assets/javascripts/components/generic_object/generic-object-definition-component.js

For more context, this is the data coming from API:
```
"data": {
"allowed_association_types": [
[
"Bottleneck Event",
"BottleneckEvent"
],
[
"Chargeback Container Image",
"ChargebackContainerImage"
],
[
"Cloud Resource Quota",
"CloudResourceQuota"
],
...
"allowed_types": [
[
"Boolean",
"boolean"
],
[
"Date/Time",
"datetime"
],
[
"Float",
"float"
],
...
```
And this is the relevant part of javascript, processing that API data:
```javascript
function getGenericObjectDefinitionOptions(response) {
buildOptionObject(response.data.allowed_association_types, vm.classes);
buildOptionObject(response.data.allowed_types, vm.types);
}
function buildOptionObject(optionData, optionObject) {
_.forEach(optionData, function(item) {
optionObject.push({id: item[1], name: item[0]});
```

Apply gettext on general object definitions strings coming from API

---

app/controllers/application_controller/buttons.rb

Add GenericObject to APPLIES_TO_CLASS_BASE_MODEL
- fixes an error that occurs for custom buttons created in the customization->Buttons for generic objects
Before:
After

Add GenericObject to APPLIES_TO_CLASS_BASE_MODEL

---

spec/helpers/compliance_summary_helper_spec.rb
spec/helpers/ems_cloud_helper/textual_summary_spec.rb
spec/helpers/ems_cotainer_helper/textual_summary_spec.rb

We don't want to use `allow_any_instance_of` unless necessary.
3 textual summary helper specs are using it to mock `role_allows?`, but according to https://github.com/ManageIQ/manageiq-ui-classic/pull/2901#discussion_r155236459 the same can be achieved using `allow(self)`.
Cc @skateman :cookie:

Helper specs - remove allow_any_instance_of

---

app/controllers/service_controller.rb
spec/controllers/service_controller_spec.rb

For some reason `generic_objects` were excluded from being displayed in the Textual Summary screen for Ansible Playbook Services.
-- fixed that.
https://bugzilla.redhat.com/show_bug.cgi?id=1496984
Before -
After -

Display Generic Object instances for Ansible Playbook Services as well

---

app/assets/javascripts/components/generic_object/generic-object-definition-component.js

This is a client change that needs to be done after https://github.com/ManageIQ/manageiq-api/pull/238 is merged.
In essence, we want to send hash over the API, rather than an array, since on the client side we're doing a transformation back to a hash anyway.

The data sent from GO Definition API are hashes, not arrays

---

app/presenters/tree_builder_policy_profile.rb

The action `success` or `failure` icon is not rendered properly for _Policy Profiles_ tree while it works fine for _Policies_ tree. Let's provide the information about `success` and `failure` to _Policy Profiles_ tree nodes as well. 
Code is copy-pasted from [app/presenters/tree_builder_policy.rb](https://github.com/ManageIQ/manageiq-ui-classic/blob/507ad213a8e63af033e953a5c6b4caef014817d3/app/presenters/tree_builder_policy.rb#L127).
_Policy Profiles_ tree:
_Policies_ tree:

Fix wrong icon for action in Policy Profiles

---

app/views/vm_common/_live_migrate.html.haml

Remove erroneous reference to `@record.id` from the submit and cancel buttons that are displayed when viewing the live migrate form outside of an explorer view. IDs of instances to migrate are tracked by `@live_migrate_items`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518436
Obsoletes https://github.com/ManageIQ/manageiq-ui-classic/pull/2877

Remove record.id from live migrate submit and cancel buttons

---

app/controllers/miq_ae_class_controller.rb
spec/controllers/miq_ae_class_controller_spec.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1523379
The form property embedded_methods was not being initialized since
the method type was not initialized.

Initialize embedded_methods property for new Automate methods

---

app/assets/javascripts/miq_application.js
app/assets/javascripts/miq_flash.js
spec/javascripts/miq_flash_spec.js

This hides any previously displayed flash messages from the login screen, see the BZ for details.
https://bugzilla.redhat.com/show_bug.cgi?id=1516734

Clear the flash_msg_div before displaying new flashes during login

---

app/controllers/application_controller/performance.rb

Bugzilla [#1510548](https://bugzilla.redhat.com/show_bug.cgi?id=1510548)
MiddlewareServerEap and MiddlewareServerWildfly was not in the list of types.
cc @abonas

Add MiddlewareServerEap and MiddlewareServerWildfly for Utilization charts

---

app/controllers/application_controller/buttons.rb
app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

After the changes related to https://github.com/ManageIQ/manageiq-ui-classic/pull/2885,  dialogs for custom buttons are no longer displayed.
Fix dialog_id parameter for custom buttons
Create a custom button with a dilaog.
Invoke the button.
Before:
After:

Dialogs for custom buttons are not displayed

---

config/routes.rb
spec/routing/vm_cloud_routing_spec.rb

Fixes the `sort template grid` routing issue encountered while provisioning a cloud instance.
https://bugzilla.redhat.com/show_bug.cgi?id=1454829

Fix routing for `sort template grid` in vm_cloud controller

---

app/helpers/application_helper/button/cockpit_console.rb
spec/controllers/container_node_controller_spec.rb
spec/controllers/vm_cloud_controller/trees_spec.rb
spec/controllers/vm_infra_controller/trees_spec.rb
spec/controllers/vm_infra_controller_spec.rb
spec/helpers/application_helper/buttons/cockpit_console_spec.rb

Reverts commit 67a0f0ae8a3fada5746cd72e119bd8bf8f598dab to re-enable Cockpit console functionality.  There was no Cockpit role in FINE to enable the Web Console button.
@miq-bot add_labels bug, console
https://bugzilla.redhat.com/show_bug.cgi?id=1522951

[FINE] Re-enable Web Console button

---

app/controllers/application_controller/compare.rb

The [`tag`](http://api.rubyonrails.org/v5.0/classes/ActionView/Helpers/TagHelper.html#method-i-tag) helper method in Rails is a little bit inconsistent when it's about self-closing tags. It works well with an `input` field, but it fails to work with an `i` tag that we're using for fonticons. This causes random duplication of tags when displaying a drift history of a host. Forcing the tag to be closed by using an empty [`content_tag`](http://api.rubyonrails.org/v5.0/classes/ActionView/Helpers/TagHelper.html#method-i-content_tag) instead solves the issue.
**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1466402
@miq-bot assign @epwinchell

Fixed invalid HTML markup in drift fonticons

---

app/controllers/application_controller.rb
spec/controllers/ems_middleware_controller_spec.rb

I had to extend the exception for the middleware servers displayed for a single provider.
`Middleware -> Providers (select a provider) -> Relationships (accordion) -> Middleware Servers`
Explanation why am I introducing this exception: https://github.com/ManageIQ/manageiq-ui-classic/pull/2888
@miq-bot add_label bug, gtls, middleware, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1509935

Extend the icon deletion exception for middleware servers

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css
bower.json
manageiq-ui-classic.gemspec

@miq-bot add_label fine/no, gaprindashvili/no
@himdel and @epwinchell please test this :wink: :tada:

Update PatternFly to v3.31.1

---

app/views/ems_infra/_form.html.haml

When adding a vmware infra provider, the VNC start/end port fields aren't displayed. However, when editing the same provider they are there. I don't know the reason behind this inconsistency, but I got a :beetle: for it so here's the fix.
**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1514594
@AparnaKarve could you please review?

Display the VNC start/end port when adding a vmware provider

---

app/controllers/service_controller.rb
app/helpers/application_helper.rb
spec/controllers/service_controller_spec.rb

Fixed the navigation to Services maintab issue reproduced with the steps below -
1. Navigate to Services -> My Services -> Select the Service with the GO instance
2. Click on the GO Instances count in the Summary screen
3. Pick a GO Instance to view in detail
4. Click on the Services maintab on the left
https://bugzilla.redhat.com/show_bug.cgi?id=1523396

Fix the navigation to Services maintab after viewing a Generic Object item via Services Explorer

---

app/helpers/application_helper/toolbar/ansible_repositories_center.rb
app/helpers/application_helper/toolbar/ansible_repository_center.rb
app/helpers/application_helper/toolbar/diagnostics_region_center.rb
app/helpers/application_helper/toolbar/diagnostics_server_center.rb
app/helpers/application_helper/toolbar/diagnostics_zone_center.rb
app/helpers/application_helper/toolbar/ems_cloud_center.rb
app/helpers/application_helper/toolbar/ems_container_center.rb
app/helpers/application_helper/toolbar/ems_containers_center.rb
app/helpers/application_helper/toolbar/ems_datawarehouses_center.rb
app/helpers/application_helper/toolbar/ems_infra_center.rb
app/helpers/application_helper/toolbar/ems_middlewares_center.rb
app/helpers/application_helper/toolbar/ems_network_center.rb
app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
app/helpers/application_helper/toolbar/ems_storage_center.rb
app/helpers/application_helper/toolbar/logs_center.rb
app/helpers/application_helper/toolbar/miq_request_center.rb
app/helpers/application_helper/toolbar/miq_requests_center.rb
app/helpers/application_helper/toolbar/miq_widgets_center.rb
app/helpers/application_helper/toolbar/saved_reports_center.rb
app/helpers/application_helper/toolbar/tasks_center.rb
app/helpers/application_helper/toolbar/vmdb_table_center.rb
app/helpers/application_helper/toolbar/vmdb_tables_center.rb
app/helpers/application_helper/toolbar/x_history.rb
app/views/shared/_topology_header_toolbar.html.haml

This PR standardizes the font icon and hover text for Page Refresh per Issue 1 here: http://talk.manageiq.org/t/ux-feedback-vertical-navigation/2899 
The Diagnostics area was also updated for consistency, but should be reviewed here:
https://github.com/ManageIQ/manageiq-ui-classic/compare/master...epwinchell:refresh?expand=1#diff-74f4eada98cda846759986f1eb35f327 
and here:
https://github.com/ManageIQ/manageiq-ui-classic/compare/master...epwinchell:refresh?expand=1#diff-88ef2e84e3c0a397f32501e06cffe561
Old
New
/cc @dclarizio @ohadlevy  @serenamarie125 @KendraMar @jonnyfiveiq

Standardize 'page refresh' text and font icon

---

app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

Use service template in api_submit_endpoint for service template subclasses, as there are no collections for subclasses
Links
-------
https://bugzilla.redhat.com/show_bug.cgi?id=1523580
Before:
After

Fix ordering an Ansible Playbook catalog items

---

app/controllers/application_controller/policy_support.rb
app/controllers/application_controller/tags.rb
app/controllers/host_controller.rb
app/controllers/mixins/actions/vm_actions/evacuate.rb
app/controllers/mixins/actions/vm_actions/live_migrate.rb
app/controllers/mixins/actions/vm_actions/ownership.rb
app/controllers/mixins/actions/vm_actions/retire.rb
app/controllers/utilization_controller.rb
lib/report_formatter.rb
lib/report_formatter/converter.rb

Move ruport gem dependency from manageiq to ui-classic
`MiqFilter.hashes2table` was just a passthrough to `MiqReportable.hashes2table`
`MiqReportable.records2table` is only used in 1 place.
The git history for these methods can be found
in manageiq: [app/models/miq_reportable.rb](https://github.com/ManageIQ/manageiq/blob/8ec14c859726d9c8936b06f885194d8805c49ec0/app/models/miq_reportable.rb)
Next Steps:
Delete `MiqReportable` and `MiqFilter.hashes2table`
See Also https://github.com/ManageIQ/manageiq/pull/16620

Move MiqReportable methods to ui code

---

app/views/miq_ae_customization/_dialog_import_export.html.haml

Changed CSS class for *Import* button, so both the buttons with action (*Import* / *Export*) are consistent:
Before:
After:
Automate → Automation → Customization → Import/Export accordion
cc/ @epwinchell

Changed CSS class for button

---

app/views/chargeback/_cb_rate_edit_table.html.haml

**fixing** 
Issue with more info: https://github.com/ManageIQ/manageiq-ui-classic/issues/2799
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1517802
Order _Sub Metrics_ of Storage types (under _Rate Details_) in Rate editor
correctly when editing newly created Chargeback Rate in _Cloud Intel ->
Chargeback -> Rates_.
**Details:**
The problem was that Rate Details were not sorted when editing the details after choosing
_Edit this Chargeback Rate_ under _Configuration_ comparing to showing the details where the
details are sorted by group, description and sub metric.
**Solution:**
Adding just sorting the details by group, description and sub metric was not enough. It solved
ordering but then there the problem occurred that after editing the rate and saving the changes,
the changes did not …

Order Sub Metrics of Storage types in Rate editor

---

app/views/layouts/_list_grid.html.haml

This is an ugly but necessary workaround, as https://github.com/ManageIQ/manageiq-ui-classic/pull/2573 can't be backported. 
**Before:**
**After:**
https://bugzilla.redhat.com/show_bug.cgi?id=1515367

[FINE] Prioritize the custom uploaded picture over listicons in GTL grids

---

app/views/miq_ae_customization/editor.html.haml

- Automation -> Automate -> Customization -> Service Dialog -> Create/Edit Service Dialog with enough elements to see a scrollbar on right side
- Drag one element and scroll at the same time
Dragged element is not under mouse cursor. But if dropped it will be added based on cursor location.
**Expected result:**
Dragged element is under mouse cursor (but you have to move the mouse a bit after scroll).
Background for the change :godmode: :
Coordinates of dragged element are changed if there is a scroll action in its `scrollParent`. To be selected as `scrollParent` it cannot have `position: static` (default setting of `#main-content`) so it's overridden in this PR.
@miq-bot add_label gaprindashvili/yes, bug, blocker, automation/automate
@romanblanco here …

Fixes wrong coordinates of draggable element after scrolling in #main-content

---

app/assets/stylesheets/pdf/_patternfly.scss.erb

Fixes broken PDF download caused by asset path change in the upgrade to PatternFly v3.31.1 https://github.com/ManageIQ/manageiq-ui-classic/pull/2989
Before
After

Fix broken asset path for PDF downloads

---

app/views/report/_form_expression_buttons.html.haml

**fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1523271
Display _Filter_ Tab of _Policy Events for the Last 7 Days_, when editing report in _Cloud Intel -> Reports -> Reports_ tab.
The problem was the typo in https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/report/_form_expression_buttons.html.haml#L14 and https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/report/_form_expression_buttons.html.haml#L15, where `expression_key` was renamed to` @expkey`. `expression_key` as parameter or variable does not exist anywhere in _manageiq-ui-classic_ repo.
**Before:**
```
I, [2017-12-12T15:32:21.817790 #14908]  INFO -- :   Rendered /home/hstastna/manageiq/manageiq-ui-classic/app/views/report/_report_list.html.haml (752.4ms)
F, …
```

Display Filter Tab of Policy Events for the Last 7 Days

---

config/routes.rb

Compute -> Cloud -> Availability Zones -> choose one with instances -> click Instances in Relationships -> check one or more Instances -> Policy -> Manage Policies
Before:
*Log:*
```
F, [2017-12-13T14:56:37.062567 #30823] FATAL -- : Error caught: [ActionController::UrlGenerationError] No route matches {:action=>"protect", :controller=>"availability_zone", :db=>VmOrTemplate(id: integer, vendor: string, format: string, version: string, name: string, description: text, location: string, config_xml: string, autostart: string, host_id: integer, last_sync_on: datetime, created_on: datetime, updated_on: datetime, storage_id: integer, guid: string, ems_id: integer, last_scan_on: datetime, last_scan_attempt_on: datetime, uid_ems: string, retires_on: datetime, retired: boolean, boot_time: datetime, …
```

Add missing protect routes to availability_zone

---

app/controllers/ops_controller.rb
spec/controllers/ops_controller_spec.rb
spec/controllers/ops_settings_spec.rb

Configuration -> Access Control -> Users/Group/Role -> Add a User/Group/Role -> fill and save
Before:
Nothing happens on screen.
*Log:*
```
F, [2017-12-13T14:16:22.941154 #29252] FATAL -- : Error caught: [NoMethodError] undefined method `>=' for nil:NilClass
/Users/zita/Desktop/ManageIQ/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:366:in `button_class_name'
/Users/zita/Desktop/ManageIQ/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:389:in `get_custom_buttons'
/Users/zita/Desktop/ManageIQ/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:299:in `custom_button_selects'
/Users/zita/Desktop/ManageIQ/manageiq-ui-classic/app/helpers/application_helper/toolbar_builder.rb:341:in `build_custom_toolbar_class' …
```

Set @tree_selected_model

---

app/helpers/application_helper/toolbar_chooser.rb
spec/helpers/application_helper_spec.rb

Render center toolbar for all Container nested display lists, which resolves the issue of `Policy` button not being rendered in Container Relationship lists
Before (No Policy button)
After (Renders toolbar with Policy button)
https://bugzilla.redhat.com/show_bug.cgi?id=1516766

Display Policy button for all Container Relationship lists

---

app/helpers/service_helper/textual_summary.rb

- And made all credentials values as clickable links.
- Removed VMware Credentials code, as those fall under Cloud Credentials, dont need to show them separately.
https://bugzilla.redhat.com/show_bug.cgi?id=1515561
before:
after:

Made changes to show Cloud credentials on service summary screen

---

app/views/ops/_rbac_group_details.html.haml

`auth_mode_name()` returns localized name of authentication mode and as such its result cannot be used in an if condition (its return value would depend on the current locale being used).
https://bugzilla.redhat.com/show_bug.cgi?id=1495152

Don't use localized name of authentication mode in an if condition

---

app/helpers/application_helper/toolbar/generic_objects_center.rb
spec/helpers/application_helper/toolbar_builder_spec.rb

Fixes the below error -
```
F, [2017-12-12T16:48:11.009175 #26813] FATAL -- : Error caught: [RuntimeError] Can't access selected records
~/manageiq/plugins/manageiq-ui-classic/app/controllers/mixins/checked_id_mixin.rb:127:in `find_records_with_rbac'
~/manageiq/plugins/manageiq-ui-classic/app/controllers/application_controller/tags.rb:87:in `get_tag_items'
~/manageiq/plugins/manageiq-ui-classic/app/controllers/application_controller/tags.rb:268:in `tag'
~/manageiq/plugins/manageiq-ui-classic/app/controllers/generic_object_definition_controller.rb:46:in `button'
```
Pass `:send_checked => true` to the `Edit Tags` button which ensures that `params[miq_grid_checks]` would be defined.

Fix Generic Object tagging

---

app/controllers/ems_common.rb

Dead method scanemss has been deleted from app/controllers/ems_common.rb.  
@himdel @ZitaNemeckova

Deleted dead method scanemss

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js

This fixes an issue where the UI was popping up a modal with the rejected request with errors when it should've been handled gracefully with error flash notifications.
https://bugzilla.redhat.com/show_bug.cgi?id=1518895
Before
After
Thanks @syncrou for the help!
@himdel Can you review?

Show correct validation messages when ordering a service

---

app/services/dialog_field_visibility_service.rb

Only parameters were used inside method, so no further
investigation needed
@ZitaNemeckova @himdel 

Removing unused method

---

app/views/chargeback/_rates_tabs.html.haml

**fixing** https://github.com/ManageIQ/manageiq-ui-classic/issues/2744
Enable to edit _Chargeback rate_ again after clicking on _Reset_ button in _Cloud Intel -> Chargeback -> Rates_ tab.
Before:
After:

Enable to edit Chargeback rate after resetting changes

---

app/controllers/pxe_controller/iso_datastores.rb

I have removed unused method `identify_isd_datastore` in file `iso_datastores.rb`.

Removed dead method identify_isd_datastore

---

app/services/cloud_topology_service.rb
app/services/infra_topology_service.rb
app/services/network_topology_service.rb
app/services/physical_infra_topology_service.rb

When building the JSON for a topology, all the related tags are being fetched. This is a problem as we don't want to expose internal tags in the UI. As a :christmas_tree: :gift: @lpichler [added a new method](https://github.com/ManageIQ/manageiq/pull/16607) into `ActsAsTaggable` that fetches only the tags we need.
**Before:**
**After:**
@miq-bot add_label topology, bug, pending core, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1519457

Display only manually added my company tags on topology screens

---

app/controllers/application_controller/ci_processing.rb

This method was dead and was not calling any other method or creating new objects. I tried these commands: ag owner_changed? ; ag owner_#.* ; ag #.*_changed. Miss Nemeckova confirmed the fact that this method is dead.

Deleted dead owner_changed? method.

---

app/helpers/application_helper/button/mass_transform_vm_button.rb

Show VM transform button for mass transforms only if `vm_transform_mass` permission is set in the permission store. By default, it is visible in ManageIQ, that uses `Null` permission store, and hidden in CFME, if `vm_transform_mass` is not set explicitly in `YAML` permission store.

Show VM transform button only if permitted

---

config/routes.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1444089
Add missing route for _Object Store Objects_ to enable `save_default_search` method, fixing  an error 
occurred when saving a new filter in Adv Search in _Storage -> Object Storage -> Object Store Objects_
page.
**Before:**
**After:**

Add missing route for Object Store Objects

---

spec/javascripts/components/ansible-raw-stdout_spec.js

This is what 496240de3b9c87b5aa2447bf4f73abe13b446127 was supposed to fix, but I didn't know the reason.
Seems like shimmed Promise is behaving quite different from proper Promise (regarding timing) - that's why the error only happens on Travis.
Using $q instead of Promise, hoping for correct behaviour.

ansible-raw-stdout spec - fix timing issue with shimmed Promise

---

app/assets/javascripts/components/widget-report.js

Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/1805
`getTrustedHtml` eats `DoNav` in HTML that is fetched from db so it cannot be used :(
Cloud Intel -> Dashboards -> some report widget like Top Storage Consumers -> try click any Vm/Instance
Before:
*Nothing happens*
After:
*Redirected to Vm/Instance summary page*
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525648
@miq-bot add_label bug, blocker, gaprindashvili/yes, dashboards

Change getTrustedHtml to trustAsHtml in report Dashboard

---

app/assets/javascripts/services/topology_service.js
app/services/topology_service.rb
spec/services/topology_service_spec.rb

The `name` attribute on tags is displaying the full tag URI instead of a human-readable name. The [tags we want to display on topology screens](https://github.com/ManageIQ/manageiq-ui-classic/pull/3007) always provide a related `Classification` object with an appropriate description. This object always has a parent `Classification` also with the description. Using these objects we can build the desired human-readable tag name by joining the two descriptions together.
As the tag name is being displayed on a tooltip with a `Name:` prefix before, I did not wanted to use a second colon for joining the two descriptions. Instead of that I am dropping the prefix for tags.
**Before:**
**After:**
Depends on:
https://github.com/ManageIQ/manageiq/pull/16607 …

Name the tags on the topology screens based on its classifications

---

app/assets/javascripts/services/dialog_field_refresh_service.js
spec/javascripts/services/dialog_field_refresh_service_spec.js

This PR switches out the API call from `miqService.jqueryRequest` to `API.post`. The old way I believe doesn't have the right authentication context when calling to the API and is intended to be used on non-API calls.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525686
@d-m-u Can you review, please?

Fix for Dynamic dialogs triggering HTTP auth popup in classic ui

---

app/helpers/physical_server_helper/textual_summary.rb

Currently, management network details such as IMM IP addresses are displayed in the "Networks" table on the physical server page. This is confusing because the name "Networks" implies that generic network details are displayed in the table; however, this is not the case. This patch renames that title in order to better describes the content of the table.

Rename 'Networks' table title (physical server summary)

---

app/helpers/application_helper/button/new_host_aggregate.rb
spec/helpers/application_helper/buttons/new_host_aggregate_spec.rb

RBAC check to the  toolbar button for New Host Aggregates for create new action:
Compute -> Cloud -> Host Aggregates
after
I am going to do similar thing in more screens, so please review and then I will use it in others screen.
What I am doing here:
- added rbac check
- add disabled message
- added specs
- added spec module to be able simply use restricted user
cc @skateman 
@miq-bot add_label bug, rbac
--------
https://bugzilla.redhat.com/show_bug.cgi?id=1516229 (around 10 % done by this PR)

Add rbac check to toolbar button for New Host Aggregates create new action

---

app/assets/javascripts/angular_modules/module_automate_selector.js
app/assets/javascripts/controllers/miq_ae_class/ae_inline_method_selection_controller.js
app/controllers/miq_ae_class_controller.rb
app/controllers/tree_controller.rb
app/helpers/automate_tree_helper.rb
app/presenters/tree_builder_ae_class.rb
app/presenters/tree_builder_automate.rb
app/presenters/tree_builder_automate_inline_method.rb
app/views/miq_ae_class/_embedded_methods.html.haml
app/views/static/automate-selection-modal.html
config/routes.rb
spec/controllers/tree_controller_spec.rb

The `TreeBuilder` calls are playing too much with the session, I even [failed with a simpler solution](https://github.com/ManageIQ/manageiq-ui-classic/pull/3038). I decided to utilize the same `TreeSelector` component that we're using in the dialog editor for entry point selection. I created a new method into the `TreeController` that retrieves a special automate tree with inline methods only. The most complicated part was the link between the session-based edit form and the angular controller, but I sorted it out by salvaging @pkomanek's code into a new `embedded_methods_add` route. 
I also tried to remove some dead code, but maybe missed a lot ... so this needs future refactoring.
https://bugzilla.redhat.com/show_bug.cgi?id=1512683
ping @martinpovolny @himdel @mkanoor

Display only the inline methods in the embedded methods tree

---

app/controllers/application_controller.rb
app/controllers/miq_policy_controller/alerts.rb
app/views/miq_policy/_alert_details.html.haml
product/views/MiqAlert.yaml
spec/views/miq_policy/_alert_details.html.haml_spec.rb

Reverts #2280 due to some collisions with Prometheus Alerts. It should be added back once all issues with Prometheus Alerts are resolved.
Before:
After:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525036
@miq-bot add_label bug, blocker, gaprindashvili/yes, control

Remove severity from Alerts

---

app/views/miq_request/_prov_dialog_volume_fieldset.html.haml

If the volume fieldset was cloned after focusing a field, the isObserved flag would be true on the original field, causing the clone not to be watched for changes.
Also cleans up IDs that should have been classes to get rid of duplicate node warnings.
Fixes the remaining issue from https://bugzilla.redhat.com/show_bug.cgi?id=1520540, which was not fixed completely by the previous patch.

Fix observation of cloned volume fieldsets

---

app/controllers/miq_policy_controller.rb

Refactor code to use plural forms.
https://bugzilla.redhat.com/show_bug.cgi?id=1508902

Fixes All Policy Profiles page header text

---

app/controllers/application_controller/report_data_additional_options.rb
app/helpers/application_helper.rb
spec/controllers/vm_infra_controller_spec.rb

Added changes to pass in `@in_a_form` so gtl_view does not set advanced search variables in @edit while rendering forms such as Policy Assignment form.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1524862
@dclarizio @martinpovolny please review.

Passing in `@in_a_form` to report_data call

---

app/helpers/application_helper/button/cloud_subnet_new.rb

This is to avoid the following error:
```
Error caught: [ActionView::Template::Error] undefined method `all' for ApplicationHelper::Button::EmsNetwork:Class
app/helpers/application_helper/button/cloud_subnet_new.rb:11:in `disabled?'
app/helpers/application_helper/button/basic.rb:50:in `calculate_properties'
...
```
For some reason, this error would show only in gaprindashvili branch, but I'd much rather have it fixed in both master & gaprindashvili.

CloudSubnetNew button: fix class name

---

app/views/service/explorer.html.haml

* go to "Services" --> "My services"
* click on a service to get it's details displayed (with a GTL grid showing related VMs for example)
* press CTRL-R or reload
* observe that the background of the main content ares is (not) grey.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1517910

Services: fix styling on detail page reload.

---

app/helpers/application_helper/button/vm_webmks_console.rb
spec/helpers/application_helper/buttons/vm_webmks_console_spec.rb

WebMKS is not available when a VM is using a vSphere API less than version 6.
@miq-bot add_labels bug, compute/infrastructure, fine/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1483936

Set minimum vSphere API version for WebMKS consoles

---

app/controllers/ansible_playbook_controller.rb
spec/controllers/ansible_playbook_controller_spec.rb

Remove tag info from playbook summary
Links 
----------
https://bugzilla.redhat.com/show_bug.cgi?id=1525127

Remove tag info from playbook summary

---

app/controllers/ops_controller/ops_rbac.rb

**fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1501242
Make Save button responsive for changing groups in _Configuration -> Access Control_
tab _-> Users_ when editing an existing user, for example if choosing some more groups
in dropdown menu and then removing them so there is no change when editing a user,
_Save_ button changes and is disabled which is a proper behavior.
1. when comparing `@edit[:new]` and `@edit[:current]` to decect if some change is present,
`@edit[:new][:group]` and `@edit[:current][:group]` have different type (_String_ vs. _Array_),
so we cannot simply compare them until we get the same type of these variables.
Normally we get string of group ids when we choose some groups from drop down menu
when adding/editing a user.
The result of this was that even when …

Make Save button responsive for changing groups

---

app/views/miq_ae_class/_angular_inputs_form.html.haml
app/views/miq_ae_class/_inputs.html.haml
app/views/miq_ae_class/_method_inputs.html.haml

After user entered data in Default value field and then switched Data Type drop down value, form resets Default Value field to be empty which was causing confusion. By switching fields around user will first pick data type and then enter data in Default Value field.
To be consistent switched fields on both Ansible/Non-Ansible forms.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525584
before:
after:
@mkanoor please review.

Switched fields around on the form/summary screen.

---

app/controllers/ops_controller/settings/tags.rb

Fixes display of Category Delete action confirmation message. 
https://bugzilla.redhat.com/show_bug.cgi?id=1525929

Display Category Deleted confirmation message

---

app/controllers/service_controller.rb
spec/controllers/service_controller_spec.rb

fixing issue mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1500608
This PR fixes using view selector in _Services -> My Services_ when using _Global/My
Filters_ from accordion. The core of the problem was that `@gtl_type` and another
variables were not set properly before displaying filtered items.
Adding `process_show_list` method solves the problem. Originally, this method was
accessed when applying a filter from _Advanced search_, but not from filters in the tree
in accordion.
Before:
After:

Fix using view selector in My Services page

---

app/controllers/mixins/middleware_deployments_mixin.rb

Deleting dead method parent_entity_name from middleware_deployments_mixin
app -> controllers -> mixins -> middleware_deployements_mixin.rb
Please review @himdel.

Deleting dead method parent_entity_name from middleware_deployments_mixin

---

app/controllers/pxe_controller/pxe_customization_templates.rb

Deleted following dead method: deletetemplates in pxe_controller/pxe_customization_templates.rb

Deleted dead method deletetemplates (pxe controller)

---

app/controllers/report_controller.rb
spec/controllers/report_controller_spec.rb

When you edit the report menus in `Cloud Intel -> Report -> Edit Report Menus`, the customized items arent appearing without this change. Credit goes to @h-kataria, se the BZ for details.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525346

Show custom report menus in Cloud Intel -> Reports -> Reports

---

app/controllers/vm_common.rb

**Unused method found at Mendel University course was deleted.**
**profile_toggle** at app/controllers/**vm_common.rb:658-679**

Deleted unusued method: profile_toggle_vm

---

app/controllers/catalog_controller.rb

Method ot_edit_get_form_vars from app/controllers/catalog_controller.rb on line 972 deleted.
Reason: dead method

deleting ot_edit_get_form_vars - app/controllers/catalog_controller

---

app/controllers/report_controller/reports/editor.rb

Deleted dead method cb_docker_image_labels from report_controller/reports/editor.rb:1459-1460
Review please @lpichler

Removed dead method cb_docker_image_labels

---

app/controllers/ops_controller.rb

Deleted following dead method: change_subtab in controllers/ops_controller.rb

Delete dead method change_subtab (ops_controller)

---

app/assets/javascripts/directives/hostname_validation.js
app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
spec/javascripts/directives/hostname_validation_spec.js

PR based on this discussion:
https://github.com/ManageIQ/manageiq/pull/16220
- validate hostname format in client;
- avoid user to put protocol on hostname field;
- avoid user to put path on hostname field;
- avoid user to put port on hostname field
- show error message to user;

Improving hostname validation

---

config/initializers/assets.rb

These files are no longer need to be precompiled as there are being just required in other files.
@miq-bot add_label refactoring, gaprindashvili/no

Drop unnecessary assets from the precompilation pipeline

---

app/views/layouts/application.html.haml

When displaying a dashboard widget in a new window (full screen option in its kebab), the title was set by the `@layout` instance variable. Instead of this it should set to `@report.title`, so changing it.
TODO: it would be better to move out this `report_only` condition from the `application.html.haml` and create a new layout. It would ease testing and maintainability.
@miq-bot add_label bug, gaprindashvili/yes, cloud intel/dashboard
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1526302

Display the correct report title on full screen widget screens

---

app/controllers/catalog_controller.rb
app/controllers/mixins/service_dialog_creation_mixin.rb
spec/controllers/catalog_controller_spec.rb

Removed redundant method from controller that was not being called and updated method in mixin to set form field values in `@edit[:new]` correctly.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1527026
@dclarizio please review/test

Set all fields in mixin method when form field transaction is sent

---

app/presenters/menu/default_menu.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1526882
Before:
After:

Hide the not implemented recent alerts screen

---

app/views/miq_policy/_alert_details.html.haml

When creating/editing an alert under `Control -> Explorer -> Alerts`, there is a special case when the notification frequency triggers the visibility of some extra items. After each part of the form there's a `<hr>` and the one related to the extra items was not indented properly. 
**Before:**
**After:**
@miq-bot add_label formatting/styling, bug, gaprindashvili/yes
@miq-bot assign @epwinchell 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1523281

Indent <hr> properly for notification frequency when editing alerts

---

app/controllers/miq_policy_controller.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1525466

Translated right cell text for compliance/control policies screen

---

app/views/ops/_settings_cu_collection_tab.html.haml

Updated conditional checking for nil trees to allow 'Collect for all Clusters/Datastores' to be accessible for Cloud Provider CU collection.
@miq-bot add_labels bug, blocker, compute/cloud
https://bugzilla.redhat.com/show_bug.cgi?id=1525296

Re-enable Cloud Provider C&U data collection

---

app/controllers/application_controller/buttons.rb
app/controllers/miq_ae_customization_controller.rb

@miq-bot add_labels "pending core"
Fixes page header text by stripping off parent class name prior to display, see screen shot prior and post code fix below.
Dependent on Core PR: https://github.com/ManageIQ/manageiq/pull/16664
https://bugzilla.redhat.com/show_bug.cgi?id=1516836

Fixes Custom Button Group page header text

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/views/layouts/angular-bootstrap/_auth_credentials_angular_bootstrap.html.haml
app/views/layouts/angular/_form_buttons_verify_angular.html.haml
app/views/layouts/angular/_multi_auth_credentials.html.haml
spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js

Adjustments around the new `SmartState Docker` for EC2.
Includes -
- Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1525515, which enables the Save button
- Removes provider-specific code in `_form_buttons_verify_angular.html.haml`, to keep it generic
- Provisions for a use case where Validation button should not be rendered (like the `SmartState Docker` case)

Enables Save button when the SmartState Docker EC2 form is valid

---

app/assets/javascripts/remote_console.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1523839

Add missing IE11 support for remote console fullscreen

---

spec/views/report/_form_expression_buttons.html.haml_spec.rb

Add spec test for fix in https://github.com/ManageIQ/manageiq-ui-classic/pull/3033, for rendering form expression buttons to display Filter tab properly, when editing report in Cloud Intel -> Reports -> Reports tab.

Add spec test for rendering form expression buttons

---

app/assets/stylesheets/patternfly_overrides.scss
app/views/layouts/_header.html.haml
app/views/static/notification_drawer/notification-drawer.html.haml

Update Notification Drawer markup and styling to take advantage of updates in recent versions of Patternfly (though Patternfly Sass 3.23.1).
This resolves issues 1-3 here: http://talk.manageiq.org/t/ux-feedback-notification-drawer/2928
Without Notifications
With Notifications

Update Notification drawer styling

---

app/controllers/vm_common.rb

Pulling out the presenter update for `custom_buttons`.
Huge thank you to @eclarizio for all the help - in fact I'm just the messenger with this code change
Before: 
After:
Links
* [BZ 1515017](https://bugzilla.redhat.com/show_bug.cgi?id=1515017)
* Possibly related to or partially fixed by https://bugzilla.redhat.com/show_bug.cgi?id=1514593
1. Create an Ansible Playbook Service
2. Set up a custom button pointing to that service.
3. Go to the entity that has the button attached ( the example is using VMs.)
4. Click the button.
5. The resulting button page should look like the _After_ page.

Pull out the presenter update for custom buttons

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/assets/javascripts/miq_flash.js
app/assets/javascripts/services/miq_service.js
app/assets/stylesheets/patternfly_overrides.scss
app/controllers/mixins/ems_common_angular.rb
app/controllers/mixins/generic_form_mixin.rb
spec/javascripts/miq_flash_spec.js

Currently we truncate (after 200 characters) the log error / warning that was received when connecting to a provider - In this patch I purpose a way of dealing with the **full** log error by adding a button to the alert when the alert is too long (above 200 characters).
Summary of scenarios tested:
Short alert:
Long alert:
Very Long alert
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1506718
cc: @cben , @serenamarie125 , @himdel 
Please share thoughts on this 😅  - this is just a proposition 😇

Adding view full log in alerts button

---

app/assets/javascripts/controllers/report_data_controller.js

The pagination was hiding when a button was clicked in the toolbar (e.g: clicking on `Container > Replicatros > Check Compliance`).
This fixes this issue.
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1516871
cc: @himdel

Fix pagination missing when toolbar item is clicked

---

app/assets/javascripts/controllers/report_data_controller.js

Compute -> Infrastructure -> Virtual Machines -> click one of them or any other GTL
Before:
*Redirected without spinner*
After:
*Redirected with a spinner*
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1500506
@miq-bot add_label blocker, gaprindashvili/yes, bug, gtls

Add spinner when item in gtl is clicked and has showUrl

---

app/controllers/application_controller/performance.rb

Fix Display Vm option, when clicking on chart. 
`display_current_top` functions was called with to parameters instead of one and logic used for evaluate result of RBAC check was inverted.
https://bugzilla.redhat.com/show_bug.cgi?id=1527554
GIF
1. Drill any graph select:  'chart' > 'Top VMs on this day' .
2. Now check for display> other/ vm_name

Fix Display Vm option, when clicking on chart

---

app/controllers/application_controller.rb
app/controllers/application_controller/report_downloads.rb
app/views/layouts/application.html.haml
app/views/layouts/report_only.html.haml

During #3104 I noticed this low hanging fruit and moved it out to a separate layout. Hopefully it will ease the readability. Can be triggered/tested from the main dashboard by opening a widget's full screen option from the kebab dropdown.
@miq-bot add_label cloud intel/dashboard, refactoring, gaprindashvili/no

Move the report_only layout from application out to a separate one

---

app/helpers/application_helper.rb

When navigating to reports: CI -> Reports and queueing new shedule correct page is shown, however clicking on refresh breaks it and clicking on new schedule leads to wrong entry. This PR fixes such issue so clicking on refresh and on new record will lead show correct schedule.
https://bugzilla.redhat.com/show_bug.cgi?id=1508152

Use suffix for tree select when in reload action - report data

---

app/controllers/application_controller/ci_processing.rb
app/controllers/application_controller/explorer.rb
app/controllers/mixins/actions/provider_actions/mass_transform.rb
app/controllers/mixins/actions/vm_actions/transform.rb
app/controllers/vm_infra_controller.rb
app/helpers/application_helper/toolbar/vm_infras_center.rb
spec/controllers/ems_infra_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb

Created a separate vm_transform_mass action to handle VM Transform
button clicks in on Providers page and on Compute > Infrastructure >
Virtual Machines page. This action interprets the ID passed to it as
provider ID, while regular vm_transform action interprets it as VM ID.
If provider ID is not passed, the Redhat provider EMS object is used as
target.
Depends on https://github.com/ManageIQ/manageiq/pull/16686
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1514939
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1516497
(See also @mkanoor comments here: https://github.com/ManageIQ/manageiq/pull/16584#pullrequestreview-82004845)

Target for mass VM transformation dialog

---

app/controllers/pxe_controller/pxe_servers.rb

removed dead method pxe_server_tree_select from pxe_servers.rb on line 5-13

removed dead method pxe_server_tree_select

---

app/controllers/pxe_controller/iso_datastores.rb

removed dead method iso_datastore_tree_select from app/controllers/pxe_controller/iso_datastores.rb on line 5-15 (in commit there are written different lines, because it were different in RubyMine)

Removed method iso_datastore_tree_select

---

app/controllers/pxe_controller/pxe_image_types.rb

This commit removes unused method `delete_pxe_image_types` in `app/controllers/pxe_controller/pxe_image_types.rb`

Deleted unused method 'delete_pxe_image_types'

---

app/assets/javascripts/controllers/report_data_controller.js

Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1525909
https://bugzilla.redhat.com/show_bug.cgi?id=1526434
https://bugzilla.redhat.com/show_bug.cgi?id=1526447
https://bugzilla.redhat.com/show_bug.cgi?id=1526518
https://bugzilla.redhat.com/show_bug.cgi?id=1526562

Apply gettext on GTL column headers

---

app/assets/javascripts/miq_api.js
app/assets/javascripts/miq_application.js
app/controllers/dashboard_controller.rb
app/views/dashboard/saml_login.html.haml

sessionStorage is tab-local, so new browser tabs opened from manageiq now immediately log off (since we started logging off on API authentication failures - https://github.com/ManageIQ/manageiq-ui-classic/pull/2715)
To fix this, moving `miq_token` to `localStorage` which is persistent.
(Note: this also means the token won't be forgotten on closing the tab, and may still be used until it expires on the backend, there should be no change in visibility though.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1528326
Cc @martinpovolny, @abellotti 
---
Testing:
1. log in to manageiq
2. open a menu link in a new tab
Before:
the new tab immediately goes to the login screen
After:
the link is opened in the new tab

miq_token - move API auth from sessionStorage to localStorage

---

app/helpers/application_helper/button/ems_refresh.rb
app/helpers/application_helper/toolbar/ems_cloud_center.rb
app/helpers/application_helper/toolbar/ems_container_center.rb
app/helpers/application_helper/toolbar/ems_infra_center.rb
app/helpers/application_helper/toolbar/ems_middleware_center.rb
app/helpers/application_helper/toolbar/ems_network_center.rb
app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
spec/helpers/application_helper/buttons/ems_refresh_spec.rb

Disables Refresh button on Provider summary screen based upon authentication status
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1515798
after screenshots:

Refresh button disabled when credentials are not valid

---

app/helpers/application_helper/button/physical_server_provision.rb
app/helpers/application_helper/toolbar/physical_servers_center.rb
spec/helpers/application_helper/buttons/physical_server_provision_spec.rb

Disables `Provision Physical Server` toolbar button if -
- There are no Physical Infra Providers
- There are no Physical Servers
- There are no Physical Infra Providers that support provisioning
https://bugzilla.redhat.com/show_bug.cgi?id=1525113

Disable Provision Physical Server button for specific cases

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js

This makes region selection mandatory before validation when adding a new Azure provider.
Partially addresses https://bugzilla.redhat.com/show_bug.cgi?id=1515670
There will also be a backend warning added in the Azure provider repo itself.
Thanks go to @AparnaKarve for helping me with this. And by "help" I mean giving me the answer. ;)

[AZURE] Make region selection mandatory before validation

---

app/controllers/application_controller/compare.rb
app/presenters/tree_builder_sections.rb

Before
After
Should be merged with https://github.com/ManageIQ/manageiq/pull/16691
https://bugzilla.redhat.com/show_bug.cgi?id=1495849

Apply gettext on vm compare screen

---

app/controllers/ops_controller/settings/analysis_profiles.rb

Before
After
https://bugzilla.redhat.com/show_bug.cgi?id=1525908

Apply gettext on db attribute in analysis profile error flash message

---

app/controllers/application_controller.rb
app/controllers/provider_foreman_controller.rb
app/helpers/application_helper.rb
spec/controllers/provider_foreman_controller_spec.rb

Fix the Grid View and Tile View for Configuration Profiles
Depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/2984
Links 
--------
Remaining fix for https://github.com/ManageIQ/manageiq-ui-classic/issues/2927
After:

Fix the Grid View and Tile View for Configuration Profiles

---

app/controllers/miq_ae_customization_controller/old_dialogs.rb
app/controllers/mixins/actions/host_actions/misc.rb

@himdel @ZitaNemeckova 
Methods process_host_provide and deletedialogs has been deleted. They were just defined but uncalled anywhere. 

Deleted dead methods process_host_provide and deletedialogs

---

app/controllers/ops_controller/ops_rbac.rb
app/controllers/pxe_controller/iso_datastores.rb

Check project manageiq-ui-classic, where is used method rbac_group_filter_expression. Delete this method from file app/controllers/ops_controller/ops_rbac.rb:445.
Check project manageiq-ui-classic, where is used method deleteisds. Delete this method from file app/controllers/pxe_controller/iso_datastores.rb:249.

Delete unused methods deleteisds, rbac_group_filter_expression

---

lib/report_formatter/timeline_message.rb
spec/lib/report_formater/timeline_message_spec.rb

Formatter is doing too much escaping to the text, leading to extra slashes in the user view.
BEFORE:
AFTER:
(There is a backslash introduced artificially to show the escaping problem)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1511671

Fix timeline text escapings

---

app/services/git_based_domain_import_service.rb
spec/services/git_based_domain_import_service_spec.rb

Automate import no longer allow to import multiple domains from a single git repo. This PR adds a new flash message about that.
Depends On:
https://github.com/ManageIQ/manageiq-automation_engine/pull/124
Based On:
https://bugzilla.redhat.com/show_bug.cgi?id=1497570

ae_import multiple domains

---

app/controllers/mixins/ems_common_angular.rb

Currently, validation on the queue is sending all action controller params to `raw_connect`, which are ending up in the log. We should not be sending all action controller params to the `raw_connect` method.  This update makes them into a hash and excludes the unnecessary parameters. 
Before:
```
[----] I, [2017-12-07T15:58:52.312693 #19968:2b156f45a010]  INFO -- : MIQ(MiqQueue.put) Message id: [109180],  id: [], Zone: [default], Role: [ems_operations], Server: [], Ident: [generic], Target id: [], Instance id: [], Task id: [], Command: [ManageIQ::Providers::Openstack::CloudManager.raw_connect], Timeout: [600], Priority: [100], State: [ready], Deliver On: [], Data: [], Args: ["********", <ActionController::Parameters {"utf8"=>"✓", "authenticity_token"=>"+c/4Y7PVtO==", "button"=>"validate", …
```

Do not pass in all action controller params to raw_connect

---

config/webpack/development.js

this allow the developer to:
- use websockets in development env without apache
- enjoy live reload in the browser when webpack code change
to use, execute:
```NODE_ENV=development ./node_modules/.bin/webpack-dev-server --config config/webpack/development.js```

adds support to using webpack-dev-server

---

app/controllers/ops_controller.rb

Resolves issue with https://github.com/ManageIQ/manageiq-ui-classic/pull/2942
Product feature must be set. Have `ldap_new: true` for `product` in current server Advanced.
Add LDAP authentication for any server.
Restart server.
Configuration -> Settings -> LDAP -> select any Region/Domain -> Configuration -> Delete 
Before:
```
F, [2017-12-22T14:28:10.772374 #39186] FATAL -- : Error caught: [ActionController::RoutingError] invalid button action
/Users/zita/Desktop/ManageIQ/manageiq-ui-
classic/app/controllers/application_controller/explorer.rb:196:in `generic_x_button'
/Users/zita/Desktop/ManageIQ/manageiq-ui-classic/app/controllers/ops_controller.rb:95:in `x_button'
```
After:
cc: @jvlcek (LDAP)
@miq-bot add_label settings, bug

Add missing ldap_region_delete to whitelist in ops_controller

---

app/controllers/application_controller/advanced_search.rb
app/controllers/application_controller/filter.rb

**fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1521055
Fix saving a new filter in Advanced search after deleting another one,
by proper resetting all the necessary fields when deleting a filter.
**The problem was:**
---
**Filter was created** (with the same name as previously deleted filter) even when we did not click on _Save/Cancel_ or any other button in Advanced search, **after first clicking on _Save_** button. The form with the previously deleted filter name was displayed and the filter was already created (and displayed in accordion) even when we did not click on Save button (or any other button) for the second time and even when we did not enter any name of a new filter (it was already there - the name of previously deleted filter, by default, in the form). Shortly, filter …

Fix saving a new filter after deleting another one

---

app/javascript/miq-redux/index.ts

introduced in #2504
causes
```
Uncaught ReferenceError: jasmine is not defined
at eval (index.ts?37df:8)
at Object.<anonymous> (miq-redux-common.js:183)
at __webpack_require__ (miq-redux-common.js:20)
at eval (miq-redux-common.js?4cb0:1)
at Object.<anonymous> (miq-redux-common.js:171)
at __webpack_require__ (miq-redux-common.js:20)
at miq-redux-common.js:63
at miq-redux-common.js:66
```
in the browser console.
Cc @vojtechszocs

Fix ReferenceError: jasmine is not defined

---

app/controllers/application_controller.rb
app/controllers/application_controller/report_data_additional_options.rb
app/controllers/application_controller/tags.rb
app/controllers/ops_controller/ops_rbac.rb
app/helpers/application_helper.rb
app/helpers/gtl_helper.rb
spec/controllers/ems_middleware_controller_spec.rb
spec/controllers/host_controller_spec.rb
spec/controllers/middleware_server_controller_spec.rb
spec/support/controller_helper.rb

This reverts b2f3f83d
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1514426
* ~~https://bugzilla.redhat.com/show_bug.cgi?id=1503076~~
* ~~https://bugzilla.redhat.com/show_bug.cgi?id=1501376~~
Problems in those BZ should have been meanwhile fixed in other ways so reverting b2f3f83d should not cause the breakages any more.
Bottom line: by reverting the previous behavior the BZ is fixed, however
the behavior was not consistend before and is not consistent after this
change. More complex changes and an actual specification on what is the
expected behavior is needed to address all the problems here.
See below the calculation of the `gtl_type`.
```
def get_view_calculate_gtl_type(db_sym)                                                           
gtl_type = settings(:views, db_sym) unless …
```

VMs should be displayed as quadicons in tagging.

---

app/helpers/container_summary_helper.rb
spec/controllers/dashboard_controller_spec.rb

The feature was renamed from `containers` to `container` in https://github.com/ManageIQ/manageiq/pull/16658
Looks like these 3 were missed.
Cc @h-kataria 
---
Fixes fine travis like https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/318220713#L1929
```
1) DashboardController#validate_user returns url for the user with access to only Containers maintab
Failure/Error: children = hash.delete(:children) || []
NoMethodError:
undefined method `delete' for nil:NilClass
```

[FINE] Use container instead of containers for the product feature

---

app/helpers/application_helper.rb
app/helpers/availability_zone_helper.rb
app/views/layouts/_tl_options.html.haml
spec/helpers/availability_zone_helper_spec.rb

As Policy Events are not yet implemented for Availability Zones this hides them until they will be implemented. And it's present in Darga as well.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1523663
Compute -> Cloud -> Availability Zone -> select one that has timelines -> Monitoring -> Timelines 
Before:
*After applying Policy Events*
After:
@miq-bot add_label bug, blocker, compute/cloud, gaprindashvili/yes, euwe/yes, darga/yes

Availability Zone has only Management Events in Timelines

---

app/assets/stylesheets/patternfly_overrides.scss

This PR adjusts the width of font icons in the summary screen tables so that text to the right is properly aligned. It also syncs the alignment of the font icons with the SVGs.
https://bugzilla.redhat.com/show_bug.cgi?id=1528182

 Fix alignment of font icons on summary screens

---

spec/controllers/ops_settings_spec.rb

Update the spec for the zone name uniqueness test after https://github.com/ManageIQ/manageiq/pull/16731

Update message for the zone name uniqueness validation test

---

app/helpers/application_helper/toolbar_builder.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1460968
Compute -> Infrastructure -> Networking -> select a Switch
Before:
After:
@miq-bot add_label wip, bug, gaprindashvili/yes, compute/infrastructure

Add Policy Button to Switch summary page

---

app/controllers/application_controller.rb

Fix typo in `get_view_where_clause`. Chart code is shared for all entities, so it fixes all three BZs.
Title and text in the chart menu is still wrong, but since it is blocker, it could be fixed in separate PR.
https://bugzilla.redhat.com/show_bug.cgi?id=1530208
https://bugzilla.redhat.com/show_bug.cgi?id=1530296
https://bugzilla.redhat.com/show_bug.cgi?id=1530226
Screenshots

Fix typo in get_view_where_clause

---

app/helpers/application_helper/button/button_new_discover_cloud.rb
app/helpers/application_helper/toolbar/ems_clouds_center.rb

We are disabling discovery for Cloud providers, currently the only two that we support anyway are Azure and Amazon.
By not having any Cloud providers discoverable the Discovery page fails.
I propose we change the button (and the page if someone types the url directly) logic that it detects if the number of discoverable providers is more than zero.

Change Discovery button logic for Cloud

---

app/controllers/service_controller.rb
spec/controllers/service_controller_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1528347
Fix displaying _Active_ or _Retired Services_ after removing one of them **from
its details page** by choosing '_Remove Service from inventory_' in _Services_
_-> My Services_ page.
Fix also GTL view which broke after removing a service the same way (after
deleting the service, it was not possible to change the view).
**Before:**
**After:**

Fix displaying Services after removing one of them

---

app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
app/controllers/miq_ae_customization_controller.rb
app/controllers/miq_ae_customization_controller/dialogs.rb
app/helpers/application_helper/toolbar/dialog_center.rb
app/helpers/application_helper/toolbar/dialogs_center.rb
app/helpers/miq_ae_customization_helper.rb
app/views/miq_ae_customization/editor.html.haml
config/routes.rb
spec/routing/miq_ae_customization_routing_spec.rb

The old dialog was showing up instead of the new one. After these changes, the new dialog should be used.
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1518918
Automate → Automation → Customization → Service Dialogs → Copy this Dialog
EDIT:
Needs to be merged together with https://github.com/ManageIQ/manageiq/pull/16623

Make the 'Copy dialog' action work with the new Dialog Editor

---

app/controllers/ems_common.rb

Upstream PR : https://github.com/ManageIQ/manageiq-ui-classic/pull/746
Enabled Attach/Detach Cloud Volume operations when invoked from - 
Storage Manager Summary -> Cloud Volume list
https://bugzilla.redhat.com/show_bug.cgi?id=1459190

[FINE] Enable attach/detach operations to storage manager

---

app/controllers/ops_controller/ops_rbac.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1523214
Enable to add a new Group after first unsuccessful adding of the Group because
of missing Name, in _Administrator > Configuration, Access Control_ tab > _Groups_.
---
**Explanation:**
The two simple conditions were added to prevent the error (see the BZ above), which was caused here:
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/ops_controller/ops_rbac.rb#L1425
`@edit[:new][:filter_expression]` was `nil`, so the error occurred. It was set to `nil` here:
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/ops_controller/ops_rbac.rb#L1252
The method `rbac_group_set_record_vars` is called right after the validation (see …

Enable to add a new Group after first unsuccessful adding

---

app/controllers/network_router_controller.rb

Links
https://bugzilla.redhat.com/show_bug.cgi?id=1520657
For testing can be used RBAC filtering with tagging objects as well.

Add missing RBAC checks to Add New Cloud Router form

---

app/presenters/menu/default_menu.rb
spec/presenters/tree_builder_ops_rbac_features_spec.rb

This has similar effect to ManageIQ/manageiq#16698
Per https://bugzilla.redhat.com/show_bug.cgi?id=1526791

Remove middleware section from the default menu

---

app/controllers/application_controller/ci_processing.rb
app/controllers/mixins/checked_id_mixin.rb
app/controllers/report_controller/schedules.rb
spec/controllers/application_controller_spec.rb
spec/controllers/container_image_controller_spec.rb
spec/controllers/mixins/checked_id_mixin_spec.rb
spec/controllers/ops_settings_spec.rb
spec/controllers/report_controller_spec.rb

Change `find_records_with_rbac(klass, ids, options = {})` method behavior if ids contains nil. Now when you call this method with ids contains nil or empty array, it just returns nil or empty array.
After this change  `find_records_with_rbac(klass, ids, options = {})` will raise exception if ids contains nil value. Because when you want to access record with nil id something is probably wrong and this method shouldn't hide it.
Works analogically for `find_record_with_rbac` which uses `find_records_with_rbac`

find_records_with_rbac raises exception if ids contains nil

---

app/views/miq_request/_prov_field.html.haml

This PR fixes a problem where the bootstrap-select dropdowns were conflicting with the GTL #main_div by setting the data-container to "body."
https://bugzilla.redhat.com/show_bug.cgi?id=1530966
Old
New

Fix cut-off dropdowns on Provisioning screens

---

app/helpers/application_helper/toolbar_chooser.rb

`/ems_container/10000000000017?display=performance`
without this, toolbar builder will use the `#{@display}_center` path, and try looking for the `performance_center` toolbar, which doesn't exist => an exception.
The change fixes the bug and uses a shared performance toolbar.
OTOH it is named *vm* performance, and the only button is visible only with realtime `typ`, which doesn't seem available in containers.
Fixes ManageIQ/manageiq-ui-classic#3145

toolbar_chooser - add ems_container to the list of toolbars using ?display=performance

---

app/controllers/container_project_controller.rb

compute -> containers -> projects
Projects get a `showtype=dashboard` after visiting the dashboard view, this PR reset `showtype=main`, each time we return to main view.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1530610
Target: 5.9.1
**Screeshots**
Before:
After:

Fix project main page showtype

---

app/controllers/application_controller/explorer.rb
app/controllers/application_controller/tags.rb
app/controllers/service_controller.rb
app/helpers/application_helper.rb

**fixing:**
(1) https://bugzilla.redhat.com/show_bug.cgi?id=1445313
(2) https://bugzilla.redhat.com/show_bug.cgi?id=1445303
Fix _Reset_ button for tag page opened from Service item detail page in _Services -> My Services_.
The problem was that _Reset_ button did nothing but produced an error after choosing _Edit Tags_ under _Policy_ , making a change and resetting the change, in Service item detail page in _Services -> My Services_. The action was not set properly for Services which lead to unwanted behavior.
**Before: (1)**
**After: (1)**
**Before: (2)**
**After: (2)**

Fix Reset button for tag page in Services

---

app/controllers/cloud_volume_controller.rb
app/controllers/mixins/generic_button_mixin.rb

* Deduplicate CloudVolumeController buttons using GenericButtonMixin.
* Fixing single_delete behavior and 
* removing dead code.
~~`delete_volumes` is strange.~~
* ~~Part of the logic below `process_cloud_volumes` can never be called because there's always a flash message set.~~ (removed)
* ~~The `@single_delete` logic does not execute (it's meant to execute when deleting an entity while displaying that entity). I don't know if it's broken due to some regression or it never worked and the code is a c-n-p remnant.~~ Fixed the `single_delete` behavior by including it in the `GenericButtonMixin`
* ~~`process_cloud_volumes` seems to be a remnant c-n-ped from somewhere. It only knows 'destroy' so it thould be renamed and simplified.~~
@aufi: can you get someone to review and test this?

Deduplicate CloudVolumeController buttons using GenericButtonMixin.

---

app/controllers/report_controller.rb
app/controllers/report_controller/reports.rb
spec/controllers/report_controller_spec.rb

I started to untangle the code around the reports_menu and after a few :boom: :boom: :boom: found some stuff to clean up. For example setting `@sb[:rpt_menu] and `@sb[:grp_title]` twice`:
```ruby
def reports_menu_in_sb		
@sb[:rpt_menu]  = populate_reports_menu("reports", "menu")		
@sb[:grp_title] = reports_group_title		
end
def populate_reports_menu(tree_type = 'reports', mode = 'menu')
@sb[:rpt_menu] = get_reports_menu(group, tree_type, mode)
end
def get_reports_menu
@sb[:grp_title] = reports_group_title
end
```
After the cleanup the `reports_menu_in_sb` became an alias for `populate_reports_menu` and in its spec was misleading. So I decided to drop the method completely and rename the spec to `#populate_reports_menu` as it is actually testing that method.
@miq-bot add_label refactoring, …

Remove unnecessary, dead and duplicate code around reports_menu

---

app/helpers/application_helper/toolbar/cloud_networks_center.rb
app/helpers/application_helper/toolbar/flavors_center.rb

Adding missed send_check to cloud network toolbars

---

app/controllers/chargeback_controller.rb
app/views/chargeback/_cb_assignments.html.haml

**What This Does**
Makes the label `com.redhat.component`  as default label for docker container images in chargback assignments screen.
**Why**
This makes it easier for customers to leverage RH product labels, instead of scanning through what could be large number of image labels.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1417236
GIF:
cc: @himdel , @zeari

Adding default labels 'com.redhat.component' to chargback assignments

---

app/controllers/application_controller.rb
app/controllers/report_controller.rb
app/controllers/report_controller/reports.rb

The code is nearly unreadable and honestly, I don't see the bigger picture here and have no idea how this `get_reports_menu` should behave. The fix is an ugly hack and it might break everything in cases which I don't even know if exist at all. Writing tests around something I don't understand is IMHO meaningless and it might cause even more problems.
If you go to `Cloud Intel -> Reports (menu) -> Reports (accordion)`, you will see both the custom menus created under the `Edit Report Menus (accordion)` for the current user's group and the custom reports created (if any). Originally the manually edited report menus were not displayed, that has been fixed by #3098, that broke custom reports.
Because of #3187 there will be a merge conflict for `gaprindashvili` so I will create a separate PR …

Add both custom reports and custom report menu items to report menu

---

app/controllers/cloud_subnet_controller.rb
app/controllers/cloud_tenant_controller.rb
app/controllers/flavor_controller.rb
app/controllers/host_aggregate_controller.rb

there were couple places in new cloud form without RBAC filtering and this PRs is adding RBAC here.
Affected screen new form screens:
Host Aggregates,
Tenant,
Flavour,
Subnets
Cloud Network is missing(regard to the description in BZ) but there is already RBAC check.
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1516229
cc @mzazrivec

Add rbac checks for cloud 'new' screens

---

app/controllers/host_controller.rb
app/controllers/mixins/explorer_show.rb
spec/controllers/host_controller_spec.rb

Replace conditions with named scopes.

Replace conditions with named scopes

---

app/assets/javascripts/controllers/topology/network_topology_controller.js
app/views/network_topology/show.html.haml
spec/javascripts/controllers/network/network_topology_controller_spec.js

Convert network_topology_controller to controllerAs

Convert network_topology_controller to controllerAs

---

app/controllers/application_controller/ci_processing.rb
spec/controllers/orchestration_stack_controller_spec.rb

Fix for orchestration stack retirement from the summary page
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1531953
1.Open stack details
2.Retire Now

Fix for orchestration stack retirement from summary page

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js

There's a strange issue where the VMRC fields are required in downstream. @AparnaKarve found out that the problem is that I missed a line, but strangely it works well in upstream. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1526050

[FINE] Do not require the VMRC tab when adding a new vmware provider

---

app/presenters/tree_builder_vat.rb

Only show nodes in the tree that user has access to.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525000
before:
after:

Added RBAC filtering to HAC and VAT tree builder code.

---

app/controllers/cloud_volume_controller.rb
app/helpers/application_helper/button/cloud_volume_new.rb
spec/controllers/cloud_volume_controller_spec.rb

similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/3165
@miq-bot add_label bug, blocker, gaprindashvili/yes
1. Add user without permission list of Cloud Tenant
2. Go To Storage -> Block -> Volume -> Add new volume
3. You will see error.
https://bugzilla.redhat.com/show_bug.cgi?id=1526804
similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/3165
cc @martinpovolny

Require cloud tenant list permission for cloud volume

---

app/assets/images/svg/healthstate-normal.svg

Prior to this update, the icon used to represent the status of a Lenovo host was not displayed properly (Physical Infrastructure Providers > Lenovo xClarity (All Physical Servers) > Select a Lenovo host (Summary)), appearing to be smaller than all other status icons.
This patch updates the icon file, removing the empty space and fixing the problem.
Resolves:
[Red Hat Bugzilla – Bug 1525188](https://bugzilla.redhat.com/show_bug.cgi?id=1525188)

Remove the empty space on the healthstate-normal icon

---

app/assets/javascripts/components/generic_object/generic-object-definition-component.js
app/assets/javascripts/components/generic_object/generic-object-table-component.js
app/assets/javascripts/components/generic_object/main-custom-button-form-component.js
app/views/static/generic_object/generic_object_definition.html.haml
app/views/static/generic_object/generic_object_table.html.haml
app/views/static/generic_object/main_custom_button_form.html.haml

As seen below, the '+' (Add Row) button was moved outside of the table to meet the UI/UX standards.
Before-
After-
The Change is also reflected in the Custom Button Editor screen where the same table component has been used -

Styling changes to the table component in Generic Object Definition screen

---

app/controllers/application_controller/performance.rb

Should be merged after #3131 
Delete  `perf_menu_record_valid` validation method, because its not necessary.
Replace it with direct call of `find_record_with_rbac`.  After #3131 changes `find_record_with_rbac` raises exception instead of returning `[]` or `nil`
Links
#3131

Delete perf_menu_record_valid method

---

app/views/miq_policy/_action_details.html.haml

https://bugzilla.redhat.com/show_bug.cgi?id=1526401

Apply gettext in action details screen

---

app/controllers/cloud_subnet_controller.rb
app/controllers/cloud_volume_controller.rb
app/controllers/ops_controller/settings/schedules.rb

Delete unnecessary X.empty? check after calling `find_record_with_rbac`. After #3131 `find_record_with_rbac` raises exception if it should return empty array.
Links
#3131

Delete unnecessary X.empty? check after calling find_record_with_rbac

---

app/controllers/application_controller/tags.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1517285
Go to any tagging screen like Compute -> Infrastructure -> Virtual Machines -> Policy -> Edit Tags 
At load second dropdown is not correctly populated. After change it's correct.
Before:
After:
IMPORTANT: Make sure that `Classification.categories.select(&:show).min_by(&:description)` and `Classification.categories.select(&:show).min_by(&:name)` are two different instances.
`Classification.categories.select(&:show).sort_by(&:name)[0]` that is used in layout as `@categories` is not equal to `Classification.categories.select(&:show).sort_by(&:name).min_by(&:description)` that is used as `@edit[:cat]` to generate its subcategories.
Replaced `:description` to `:name` to make it equal 😄 
@miq-bot add_label bug, gaprindashvili/yes, …

Fix dropdown in tagging

---

app/assets/javascripts/controllers/report_data_controller.js
app/assets/javascripts/controllers/toolbar_controller.js
app/assets/javascripts/miq_application.js

Class which was still present was `miq-sand-paper` which caused greyed content background. This PR fires new event when click on toolbar is finished and if such event is cought by report data it will check if any grid is present and if so, it will set `miq-sand-paper` back.
https://github.com/ManageIQ/manageiq-ui-classic/pull/3062
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1530939

Fire new event when toolbar click finish

---

app/assets/javascripts/services/topology_service.js

When you go to a provider's (e.g. infra) summary screen and select the topology in the table view, the topology data are not being loaded onto the controller.
The problem was that the condition for building the URL did not cover this way of displaying a topology screen. I updated the condition to make this work, however, some refactoring should be done in the future. The code is too much spaghetti for adding any tests, but after @Hyperkid123 is finished with the refactoring, it should be easy. 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1532404

Add missing condition for retrieving data on the provider topology pages

---

app/controllers/planning_controller.rb
spec/controllers/planning_controller_spec.rb

Removed code to show flash message while options are being selected, should only show flash message for missing options after submit button is pressed.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1531462

Show flash message when "Submit" button is pressed.

---

app/assets/javascripts/services/topology_service.js
spec/javascripts/services/topology_service_spec.js

after the recent topology conversion (#3087) there were a few special cases missed
Accessing topology from infra & cloud summary screens was fixed in #3214.
Access from container summary screen is fixed here.
\+ tests for all the topology screens we can currently test
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533123
Cc @skateman, @Hyperkid123

topologyService (js) - fix and test screen url to data url conversion

---

app/helpers/physical_server_helper/textual_summary.rb

* add information about the physical server's disk capacity

Parsing disk capacity into physical server

---

app/assets/javascripts/controllers/container_dashboard/container_project_dashboard_controller.js

https://bugzilla.redhat.com/show_bug.cgi?id=1525973

Add missing gettext into containerProjectDashboardController

---

app/controllers/ems_common.rb
app/views/ems_infra/_show_dashboard.html.haml
spec/controllers/ems_infra_controller_spec.rb

Navigate to infra / container provider summary, switch to dashboard view, hit 'Check Compliance of Last known Configuration' button.
Previously, the button action would render full page (html). Now the action will render a javascript flash message. 
https://bugzilla.redhat.com/show_bug.cgi?id=1510340

Fix rendering of flash message when running check compliance

---

app/views/ops/_rbac_group_details.html.haml
product/views/MiqGroup.yaml

**fixing** https://github.com/ManageIQ/manageiq-ui-classic/issues/3173
Change `Description` label of the form to `Name` when adding new Group
in _Administrator > Configuration > Access Control_ tab > _Groups_, to achieve
consistency with the table column of the DB.
**Before:**
**After:**

Change Description to Name form label

---

app/helpers/service_helper/textual_summary.rb
spec/helpers/service_helper/textual_summary_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533109
@lgalis please test
before:
after:

Show Cloud credentials only when those were selected.

---

app/views/chargeback/_cb_rate_edit_table.html.haml

**fixing** https://github.com/ManageIQ/manageiq/issues/16699
Fix issues related to adding new or editing existing chargeback rates in _Cloud Intel -> Chargeback
-> Rates_ tab, caused by improper `detail_index` in the chargeback rate edit table.
**Issues:**
- on mouse focus, the whole form/table is highlighted instead of one row, when adding a new chargeback rate
https://user-images.githubusercontent.com/14937244/34208255-0446729a-e58e-11e7-8e4a-ecaadf5b419b.gif
- if a new tier is added (by pressing _Add_ button in the table), the then tier is added to the improper metric
https://user-images.githubusercontent.com/14937244/34208319-56445364-e58e-11e7-803b-d0c4673727ab.gif
**After:**
**Details:**
Simple condition was added to haml, because it is accessed not only if editing chargeback rate, …

Fix issues related to adding, editing Chargeback Rates

---

app/helpers/application_helper/button/cloud_volume_new.rb
spec/controllers/cloud_volume_controller_spec.rb

it looks that it is causing sporadic CI failures because of enabling/disabling handling an exception 
like this https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/327674115
in PR https://github.com/ManageIQ/manageiq-ui-classic/pull/3165
and address comment 
https://github.com/ManageIQ/manageiq-ui-classic/pull/3189/files/e37c91172b2182e7d8ba5d1914ba1b8c52d16af0#diff-7f61832948d751577adfa11885942a16
@miq-bot add_label bug, technical-debt
caused by https://github.com/ManageIQ/manageiq-ui-classic/pull/3189
CI failure https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/327674115

Use bypass_rescue instead of handle_exceptions = false in cloud_volume_controller_spec

---

app/presenters/tree_builder_ops_rbac_features.rb
spec/presenters/tree_builder_ops_rbac_features_spec.rb

Even when section was skipped in x_get_tree_roots method a nil was being added to top_nodes array that was causing undefined method `new' for nil:NilClass
in /app/presenters/tree_node.rb:9. This fix removes any nil elements from array before trying to build RBAC features tree.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533391
@lgalis please test.

Remove nil elements from top_nodes array.

---

app/controllers/application_controller/performance.rb

Send model instead of model name string to find_record_with_rbac on chart click
Screenshots
Before:
After:
* http://documentation.for/library/that/I/am/adding
* [PR relevant issue or pull_request](#123)
If there are any manual steps that you would like the reviewer(s) to take to verify your changes, please describe in detail the steps to reproduce the features added by the pull request, or the bug before and after the change.

Send model instead of model name string to find_record_with_rbac

---

app/views/report/_form_filter_chargeback.html.haml

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1533294
Replace `'Show costs by'` with `'Show usage by'` option under _Filter_ tab for **Metering reports**,
when adding a new Report in _Cloud Intel -> Reports -> Reports_ tab.
**Before:**
**After:**

Replace 'Show costs by' option for Metering reports

---

app/assets/javascripts/controllers/timeline/timeline_options_controller.js
app/views/layouts/_tl_options.html.haml
spec/javascripts/controllers/timeline/timeline_options_controller_spec.js

Convert timeline_options_controller to controllerAs

Convert timeline_options_controller to controllerAs

---

app/controllers/cloud_network_controller.rb
app/controllers/cloud_subnet_controller.rb
app/controllers/network_router_controller.rb
app/helpers/application_helper/button/cloud_network_new.rb
app/helpers/application_helper/button/cloud_subnet_new.rb
app/helpers/application_helper/button/network_router_new.rb
spec/controllers/cloud_network_controller_spec.rb
spec/controllers/cloud_subnet_controller_spec.rb
spec/controllers/network_router_controller_spec.rb

imagine that you are the user without allowed section network providers.
then  when you go to `Network -> Networks|Subnets|Network Routers-> Add new` and select any network provider, it will end with error(there is video in BZ)
so I am adding the assert for this feature and I am adding the method role_allows - it check if user has feature related to Network Providers(ems_network_show_list)
@miq-bot add_label bug, blocker, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1526803

Require privilege network providers and cloud tenants for new cloud network, cloud subnet, network router form

---

app/controllers/application_controller/buttons.rb
spec/controllers/application_controller/buttons_spec.rb

Set the action parameter  replace_right_cell's  on button update and reset
Links 
--------
https://bugzilla.redhat.com/show_bug.cgi?id=1533643
-----------------------------
1. Create a Custom Button in Button Group for Service Template  (Services->Catalogs->All Catalog Items -> Action ... )
2. Edit new Button -> click on 'Define Expression' -> enter some expression
- or press Reset after other changes
Before:
After:

Set the action parameter  replace_right_cell's  on button update and reset

---

app/controllers/miq_policy_controller/alert_profiles.rb
spec/controllers/miq_policy_controller/alert_profiles_spec.rb

alert_profile_edit_load_edit method loads `@edit` that's being used in alert_profile_load method. Issue was introduced during cleanup in https://github.com/ManageIQ/manageiq-ui-classic/pull/2026
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533633
@dclarizio @martinpovolny please review.

Need to call alert_profile_edit_load_edit when cancel is pressed

---

app/views/miq_request/_prov_field.html.haml

After https://github.com/ManageIQ/manageiq-ui-classic/pull/3192 merge, we no longer need the `data-container` setting for the dropdowns.
This fixes -
- The multiselect dropdown linger issue described in the BZ
- Also, does not cut-off dropdowns on Provisioning screens
Related PR - https://github.com/ManageIQ/manageiq-ui-classic/pull/3176
https://bugzilla.redhat.com/show_bug.cgi?id=1533808

Fix multiselect dropdown issue

---

app/controllers/application_controller.rb
app/controllers/dashboard_controller.rb
app/controllers/report_controller.rb
app/controllers/report_controller/menus.rb
app/controllers/report_controller/reports.rb
spec/controllers/report_controller_spec.rb

When on the `CI -> Reports -> Timelines` screen, the `populate_reports_menu` is being called unnecessarily as the `TreeBuilderTimelines` is building the tree without depending on `@sb[:rpt_menu]`. This allows to remove all the logic responsible for timelines in `get_reports_menu` and it will ease its future refactoring.
@miq-bot add_label refactoring, gaprindashvili/no, cloud intel/reporting

Remove dead code from get_reports_menu in application controller

---

app/controllers/ops_controller/ops_rbac.rb

Identificator for selected host in HaC tree uses name of specific class for host but deselection uses just `Host`. So it never finds correct record. This unifies it to use specific class.
https://bugzilla.redhat.com/show_bug.cgi?id=1511528
Configuration -> Access Control -> Groups -> Select one with checked Host as below
Edit the group -> Uncheck a Host -> Save
Before:
Host stays checked
After:
Host is unchecked
@miq-bot add_label bug, gaprindashvili/yes, fine/yes

Fix uncheck of Host in HaC tree

---

app/views/ops/_rbac_user_details.html.haml

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1525122
Unable to select **"\<Choose a Group\>"** as a group from _Available Groups_,
when creating a User in _Configuration -> Access Control -> Users_.
**Before:**
**After:**

Unable to select '<Choose a Group>' and change it to 'Choose one or more Groups'

---

app/assets/javascripts/components/dropdown-menu.js
app/views/dashboard/_widget.html.haml

https://bugzilla.redhat.com/show_bug.cgi?id=1533792
Cloud Intel -> Dashboard -> any dashboard 
Problem is that`button` has `id = "btn_undefined"`. Removing `id` from `dropdown-menu` component because it's not needed and passing id down as `widget-id`.
Before:
After:
@miq-bot add_label bug, dashboards, gaprindashvili/yes, blocker

Fix dashboard widget id

---

app/presenters/tree_builder_alert_profile_obj.rb
app/presenters/tree_builder_belongs_to_hac.rb
spec/presenters/tree_builder_alert_profile_obj_spec.rb
spec/presenters/tree_builder_belongs_to_hac_spec.rb

Embedded Ansible Automation Manager is removed from the alert profile assignment screen 
Npte - this PR will not show the Embedded Ansible in the Alet profile screen. I will open a GH Issue to obtain the filtered list from the model.
Links 
-------
https://bugzilla.redhat.com/show_bug.cgi?id=1533456
Steps for Testing
1. Enable Embedded Ansible role.
2. Navigate to Control/Explorer, expand Alert Profiles accordion.
3. Create a "VM and Instance" alert profile and assign some alert.
4. Click on Configuration/Edit assignments for this Alert Profile.
5. In "Assign To" select "Selected Providers".
Before:
After:

Embedded Ansible Automation Manager should not be shown in alert profile assignment screen 

---

app/controllers/application_controller/explorer.rb
app/controllers/application_controller/tags.rb
app/controllers/service_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/toolbar_chooser.rb
app/views/service/explorer.html.haml
spec/controllers/service_controller_spec.rb

Reverts:
https://github.com/ManageIQ/manageiq-ui-classic/pull/2680
Fixes:
https://github.com/ManageIQ/manageiq-ui-classic/pull/2636
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1528289 
related BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1532354
https://bugzilla.redhat.com/show_bug.cgi?id=1532355
1. c-n-p this gist into the `rails c` https://gist.github.com/martinpovolny/4d960e550a7838a9b04cb4d8396514b0 
1. test services tagging (reset, cancel, save)
1. test display of nested VM (no checkbox)
1. test display of GO (single/list)
1. test tagging of GO (only from the list now)
1. ~~fix the BZs~~
2. tests
3. what about the layout/item ?
1. ~~VMs under a service are displayed with checkboxes (this breaks the tagging when a checkbox is checked)~~
1. ~~tagging button is broken under …

Fix GO under services and fix services tagging

---

app/helpers/application_helper/button/storage_scan.rb
spec/helpers/application_helper/buttons/storage_scan_spec.rb

Remove the requirement for hosts with valid credentials to be able to
run storage smartstate.  The valid unsupported reasons will be moved to
the Storage model.
Depends https://github.com/ManageIQ/manageiq/pull/16743
https://bugzilla.redhat.com/show_bug.cgi?id=1529725

Scan Storage via EMS not Host

---

app/helpers/storage_helper/textual_summary.rb
spec/helpers/storage_helper/textual_summary_spec.rb

@miq-bot add_labels bug, blocker, gaprindashvili/yes, compute/infrastructure
https://bugzilla.redhat.com/show_bug.cgi?id=1529269

Fix 'Managed/Unregistered VMs' count on Datastore summary screen

---

app/assets/javascripts/components/widget-chart.js
app/assets/javascripts/components/widget-menu.js
app/assets/javascripts/components/widget-report.js
app/assets/javascripts/components/widget-rss.js
app/views/dashboard/_widget.html.haml

Use `@` instead of `<`. Never assume id is number, always a string.
Don't use `:id` in component bindings. It's not good practise.
@miq-bot add_label technical debt, dashboards, gaprindashvili/no

Fix ids in widgets

---

spec/support/button_helper.rb

This method is only used in the ui-classic repo
https://github.com/ManageIQ/manageiq/pull/16821

Moving Spec::Support::ButtonHelper from ManageIQ/manageiq

---

app/views/cloud_subnet/new.html.haml

solves https://bugzilla.redhat.com/show_bug.cgi?id=1533011
Steps for Testing/QA [taken from BZ linked above]
1. Add OpenStack provider.
2. Navigate to Network -> Subnets
3. Open add new subnet page
4. Check page UI
Results without patch:
Page is corrupted, network dropdown is missing
Results with patch (expected):
Network drop-down should be present on the page

[FINE] Corrects model and function names in New Subnet form

---

app/controllers/service_controller.rb

1.  Create Ansible catalog item and provision it
2. Navigate to Services -> My Services -> [your service from above]
3. Navigate to Services -> Requests -> Click on some request
4. Navigate to Services -> My Services -> [your service from above should be selected]
5. Click on Provioning tab
6. Click on the ansible credential resource rendered in the textual summary
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1533071

Fix breadcrumb when navigating to service's ansible credential

---

spec/controllers/middleware_domain_controller_spec.rb
spec/controllers/middleware_server_controller_spec.rb

This is to get rid of the following CI failures:
```
Failures:
1) MiddlewareServerController Standalone server operations: stop button operation should create timeline event
Failure/Error: expect(event.ems_id).to eq(ems.id)
NoMethodError:
undefined method `ems_id' for nil:NilClass
2) MiddlewareServerController Standalone server operations: shutdown button operation should create timeline event
Failure/Error: expect(event.ems_id).to eq(ems.id)
NoMethodError:
undefined method `ems_id' for nil:NilClass
3) MiddlewareServerController Standalone server operations: resume dialog operation should create timeline event
Failure/Error: expect(event.ems_id).to eq(ems.id)
NoMethodError:
undefined method `ems_id' for nil:NilClass
4) MiddlewareServerController Standalone server operations: stop dialog …
```

Remove failing middleware tests

---

app/controllers/generic_object_definition_controller.rb
spec/controllers/generic_object_definition_controller_spec.rb

Set the visibility of toolbars to false while rendering forms.
Before (Toolbar visible in the form)
After (Toolbar not displayed in the form)
https://bugzilla.redhat.com/show_bug.cgi?id=1534534

Do not display toolbars in the CustomButton/Custom Group form

---

app/helpers/application_helper/toolbar/diagnostics_server_center.rb

In master https://github.com/ManageIQ/manageiq-ui-classic/pull/2398 changed toolbar button handling from
"send checked items if url_parms matches /_div/" to
"send checked items if send_checked is true".
This is not backported to gaprindashvili, and this particular button didn't have url_parms (because it is no longer needed in master).
Adding. (Not sure we can backport that whole PR without breaking anything else now.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533548
(comment 4)

[GAPRINDASHVILI] Workers - send list of checked items

---

spec/controllers/ems_common_controller_spec.rb
spec/controllers/ems_infra_controller_spec.rb
spec/controllers/ems_physical_infra_controller_spec.rb
spec/helpers/quadicon_helper_spec.rb

@himdel Please review.  Found when looking into https://github.com/ManageIQ/manageiq/pull/16768#issuecomment-357765761

Factories should be referenced by symbol

---

lib/manageiq/ui/classic/engine.rb

In ruby versions less than 2.5.0, it was found that if you have `Pathname` objects in the `$LOAD_PATH` instead of regular strings, it messes with ruby's internals and causes a memory leak.
In most ruby applications, this wouldn't be much of an issue, but there are a significant number of deferred require statements that we do in `manageiq` that cause this to leak overtime.  Further more, this seems to be an issue that presents itself even if the file has been loaded previously (mostly a no-op for `require`).
Replication of this issue can be done using a simple ruby script:
```ruby
require 'pathname'
require 'fileutils'
puts Process.pid
Dir.mkdir("foo") unless Dir.exists?("foo")
$LOAD_PATH.unshift(Pathname.new("foo"))
FileUtils.touch("empty.rb")
1500.times { 1500.times { require "empty" }; …
```

Fix memory leak with ruby/require/autoload_paths

---

app/helpers/host_helper/textual_summary.rb
app/helpers/textual_mixins/vm_common.rb
spec/controllers/vm_infra_controller_spec.rb

This is a master and Gaprindashvili fix. Fine fix: #3272
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535192

Vm display: don't crash on custom attributes with null name.

---

app/helpers/host_helper/textual_summary.rb
app/helpers/vm_helper/textual_summary.rb
spec/controllers/vm_infra_controller_spec.rb

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535192
Backport of #3268

[FINE] Vm display: don't crash on custom attributes with null name.

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller/ops_rbac_spec.rb

**fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1515215
Make _Save_ button responsive properly when deselecting Host in the
tree when assigning filters in _Edit Group page_ under **Hosts & Clusters**.
After adding an appropriate infra provider (if it is not added yet):
1. access _Configuration -> Access Control_ tab, choose _Groups_ from accordion
2. in _Configuration_ in the left upper corner, choose _Add a new Group_
3. fill in some info and assign some filters: choose _Hosts & Clusters_ tab and select some Host in the tree, exactly like this:
4. save the new group
5. then try to edit the group: under _Hosts & Clusters_, try to **deselect the same host** as you have previously selected => and you should see that _Save_ button is active. This is ok.
6. then try to select the same …

Make Save button responsive when editing Host

---

lib/manageiq/ui/classic/engine.rb

Provides comments and info regarding the changes to the `autoload_paths`. Specs to test this is not a problem can be found in the main repo in https://github.com/ManageIQ/manageiq/pull/16847
Links
-----
* https://github.com/ManageIQ/manageiq/pull/16847

Add comment about leak in engine.rb

---

app/controllers/ems_common.rb
app/controllers/ems_common_helper.rb
app/helpers/application_helper/button/ems_capture_metrics.rb
app/helpers/application_helper/toolbar/ems_container_center.rb
app/helpers/application_helper/toolbar/ems_containers_center.rb

Compute -> Containers -> Providers
Add an options to force reading container performance metrics.
Schedules a metrics collection:
- On one container provider 
- On a list of selected container providers
Gray out button if:
- Core support is missing
- Metrics are disabled or not configured.
- Note: when multiple providers are selected, will try to schedule a readings even if none have metrics configured.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1527877
Additional PRs:
ManageIQ/manageiq-providers-kubernetes#206
https://github.com/ManageIQ/manageiq/pull/16763
**Screenshot**
Queue metrics collection for one container:
C&U not enabled:

Add capture metrics feature

---

app/controllers/application_controller/ci_processing.rb

Same (or similar) statement is present few lines above it:
```ruby
@breadcrumbs = []
...
@breadcrumbs.clear()
```

Remove duplicated @breadcrumbs clear

---

spec/support/menu_helper.rb

This doesn't belong in the main repo, so moving it here.

Move Spec::Support::MenuHelper from ManageIQ/manageiq

---

app/controllers/application_controller/advanced_search.rb
app/controllers/mixins/manager_controller_mixin.rb
app/controllers/provider_foreman_controller.rb
app/helpers/application_helper.rb
spec/controllers/application_controller/advanced_search_spec.rb

**fixing:**
https://github.com/ManageIQ/manageiq-ui-classic/issues/2413
https://bugzilla.redhat.com/show_bug.cgi?id=1429519
Rename `build_configuration_manager_tree` method for proper
saving/using filters in Config Mgmt Configured Systems as this
method does not exist and causes error when saving a new filter.
Fix another issues related to Advanced search in this page.
**Before:**
```
I, [2017-11-27T17:10:08.037097 #24419]  INFO -- : Started POST "/provider_foreman/adv_search_button?button=saveit" for ::1 at 2017-11-27 17:10:08 +0100
I, [2017-11-27T17:10:08.076079 #24419]  INFO -- : Processing by ProviderForemanController#adv_search_button as JS
I, [2017-11-27T17:10:08.076182 #24419]  INFO -- :   Parameters: {"button"=>"saveit"}
F, [2017-11-27T17:10:08.303248 #24419] FATAL -- : Error …
```

Fix filters in config mgmt Configured systems 2

---

app/helpers/application_helper/button/smart_state_scan.rb
app/helpers/application_helper/button/vm_instance_template_scan.rb
spec/helpers/application_helper/buttons/vm_instance_template_scan_spec.rb
spec/support/examples_group/shared_examples_for_smart_state_scan_buttons.rb

This removed the call to `super` in the vm_instance_template_scan toolbar button, since the call to `@record.has_active_proxy?` is sufficient to ascertain if smart scan can be invoked. Fixes superclass SmartStateScan button to attempt to match records zone against target server zone if possible
https://bugzilla.redhat.com/show_bug.cgi?id=1513053

resolve issue where vm smart scan option is incorrectly disabled

---

app/assets/javascripts/controllers/report_data_controller.js
app/helpers/gtl_helper.rb
app/views/layouts/_center_div_dashboard_no_listnav.html.haml
app/views/layouts/_center_div_no_listnav.html.haml
app/views/layouts/_center_div_with_listnav.html.haml
app/views/layouts/_content.html.haml

content layout - always creates paging_div, after #main-content
center div with/no listnav - create paging_div conditionally, after #main-content
center div dashboard - no paging_div, but no ajax transitions to other screens either
this updates center div with/without listnav to always create paging_div, hidden if necessary
that way, ReportDataController.prototype.movePagination should always succeed, and the pagination will never appear above GTL.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1501035
(also https://bugzilla.redhat.com/show_bug.cgi?id=1535946 which is marked as a dup)

Layouts - always create paging_div, hidden if needed

---

app/views/static/generic_object/main_custom_button_form.html.haml

The below BZ describes a partial rendering issue in the bootstrap switch when the page is zoomed out.
The real issue however, is that the 'Role Access' dropdown that is at the end of the page, does not have enough room to expand. 
To resolve this, line breaks were added at the end, allowing the dropdown to display it's contents without the user having to zoom out the screen or scroll inside the dropdown.
https://bugzilla.redhat.com/show_bug.cgi?id=1534960
Before (`<By Role>` not visible in the dropdown) -
After (`<By Role>` visible in the dropdown) -

Add line breaks below the Role Access dropdown in the Generic Object Definition CustomButton form

---

app/assets/javascripts/controllers/report_data_controller.js

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1536378
Some rows are clickable, some are not in this GTL. So testing just `showUrl` is not usefull.

GTL: do not sparkle unless we are going to navigate.

---

app/controllers/cloud_network_controller.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1534915
Fix editing Tags for Cloud Subnets when going to _Networks -> Networks_, choosing a network, selecting _Cloud Subnets_ in _Relationships_ table and selecting some subnets by checking the checkboxes in the list and clicking on _Edit Tags_ under _Policy_.
**Before:**
**After:**

Fix editing Tags for Cloud Subnets

---

app/controllers/application_controller.rb
spec/controllers/ems_middleware_controller_spec.rb
spec/controllers/middleware_server_controller_spec.rb

This is a revert of #2994 as we no longer have the middleware code.

Remove the middleware GTL icon exception from view_to_hash

---

app/helpers/application_helper/button/floating_ip_new.rb

Go to `/floating_ip/show_list`
I'm seeing `uninitialized constant ApplicationHelper::Button::FloatingIpNew::EmsNetwork`.
Adding :: to use the right namespace
(I don't see the same problem in gaprindashvili, but the code is the same, YMMV.)
EDIT: this is only happening when reloading in devel mode, `gaprindashvili/no` then

Networks > Floating IPs - fix uninitialized constant ApplicationHelper::Button::FloatingIpNew::EmsNetwork

---

app/controllers/report_controller/widgets.rb

between gaprindashvili and master, `get_reports_menu` changed signature:
gaprindashvili: `get_reports_menu(group = current_group, tree_type = "reports", mode = "menu")`
master: `get_reports_menu(group = current_group, mode = "menu")`
That means https://github.com/ManageIQ/manageiq-ui-classic/pull/3285 only worked in master, not gaprindashvili.
Fixing the signature - this should fix both https://bugzilla.redhat.com/show_bug.cgi?id=1537142 and failing travis.

[GAPRINDASHVILI] Widgets - fix get_reports_menu call to include missing arg

---

app/controllers/mixins/actions/host_actions/misc.rb

Fix typo in Hosts controller misc module preventing Host registration in OSP provider.
Upstream has it fixed already by https://github.com/ManageIQ/manageiq-ui-classic/pull/2945
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536819

[GAPRINDASHVILI] Fix Host provide controller method

---

app/controllers/vm_common.rb
app/services/dialog_local_service.rb
app/views/shared/dialogs/_dialog_user.html.haml
spec/services/dialog_local_service_spec.rb

I had a small oversight where regardless of where the Vm instance was being shown (either on vm_infra or vm_cloud), when clicking on a custom button and then either cancelling or submitting we would be redirecting back to /vm_infra/explorer instead of the appropriate location.
This PR also adds a spinner to the dialog runner while it is loading.
https://bugzilla.redhat.com/show_bug.cgi?id=1536204

Fix for dialog loading issue and wrong redirect

---

app/controllers/service_controller.rb

**Fixing** https://github.com/ManageIQ/manageiq-ui-classic/issues/3252
Fix applying a filter when clicking on _Apply_ button in Advanced
search when filtering services in _Services -> My Services_ page.
**TODO:**[RESOLVED]
- fix selecting the applied filter also in accordion
(this issue is present in most of the explorer screens, for example in _Configuration > Management > Configured Systems_, not sure if this has ever worked. Do we need to fix this here and now?)
**Details:**
The problem is here: https://github.com/hstastna/manageiq-ui-classic/blob/master/app/controllers/application_controller/advanced_search.rb#L144 When `adv_search_button_apply` method is called, `x_node` is changed to _"root"_ node because we are in explorer screen. BUT there is **no root node in _My Services_**! …

Fix applying a filter in My Services from Adv search

---

app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js

Since https://github.com/ManageIQ/ui-components/pull/228 , we're using `name` instead of `id` in `fields_to_refresh`.
Previously, we used the `id` and this bit of code converted the names coming from the API to ids.
That's counter-productive now, removing :)
(This is a two-part fix, https://github.com/ManageIQ/ui-components/pull/238 should go first.)
Testing: go to `/miq_ae_customization/editor`, create a dynamic field and a non-dynamic field.
Edit the non-dynamic field's "Fields to Refresh" to use the dynamic field.
Save the dialog, edit it.
See the non-dynamic field's "Fields to Refresh".
before: empty, now: the value set when creating
Cc: @romanblanco @eclarizio 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536528

DialogEditor - remove code that changes fields to refresh from name to id

---

app/helpers/application_helper/button/vm_console.rb
app/helpers/application_helper/button/vm_vnc_console.rb
app/helpers/application_helper/button/vm_webmks_console.rb
spec/helpers/application_helper/buttons/vm_vnc_console_spec.rb
spec/helpers/application_helper/buttons/vm_webmks_console_spec.rb

This resolves an issue where a VM on a 5.5 Host was not reachable by a VNC console when the Host was in a cluster in vCenter 6.5.
@miq-bot add_labels compute/infrastructure, bug, wip
https://bugzilla.redhat.com/show_bug.cgi?id=1535167

Change VMware console api detection from vCenter to ESXi Host

---

app/views/layouts/application.html.haml
config/webpack/shared.js
spec/javascripts/support/jasmine.yml

This PR enables plugin developers to define their own package.json and to
allow webpack to load those dependencies.
Further, if multiple libraries are defined twice (e.g. in two different
plugins, or core and a plugin), webpack can now de dupe those libraries
into a common 'vendor' pack which will ensure the dependencies are
loaded only once.

Plugins can now use custom defined NPM packages.

---

app/controllers/application_controller.rb
app/controllers/application_controller/performance.rb
app/controllers/mixins/checked_id_mixin.rb

Fix show top VM/Host in C&U chart grouped by some tag. In `chart_top_by_tag` was used variable `typ` but it wasn't defined.
https://bugzilla.redhat.com/show_bug.cgi?id=1531619
https://bugzilla.redhat.com/show_bug.cgi?id=1531615

[FINE] Fix show top VM/Host in C&U chart grouped by some tag

---

config/webpack/shared.js

Since we support current LTS version of Node (currently v 6) we can't use `Object.values`.
https://github.com/ManageIQ/manageiq-ui-classic/pull/2652

Use Object.keys so we don't have to use newer version of node for build

---

app/controllers/mixins/ems_common_angular.rb

@borod108 [discovered](https://gitter.im/ManageIQ/manageiq/ui?at=5a68666fe01412265085e884) that adding a provider fails with a `NameError` due to the removal of the middleware provider.

Drop middleware provider condition from the add provider controller

---

app/assets/javascripts/services/topology_service.js
spec/javascripts/services/topology_service_spec.js

This removes some remaining code related to middleware topology that is not needed anymore.
Related to #3141.
Per BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1526791

Remove more of middleware topology

---

app/controllers/provider_foreman_controller.rb
app/views/provider_foreman/explorer.html.haml

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1536452
Remove _Advanced Search_ from _Configuration > Management > Providers_ page, as it is not supported, it never worked and only _Search_ remains in the page, which works well.
---
**Before:**
Adv search button present but not working properly:
When trying to use Adv search:
After clicking on _Apply_ button:
---
**After:**
Adv Search NOT present, everything works well:

Remove Adv Search from Config mgmt Providers page

---

app/views/vm_common/_reconfigure.html.haml

When the number of cores per sockets is changed in VM reconfigure
a restart of the VM might be required for the change to apply.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1534510

Add note about vm restart for cpu hot plug change

---

app/helpers/quadicon_helper.rb
spec/helpers/quadicon_helper_spec.rb

Having `|` in gettext strings repeatedly causes problems with translators, who confuse this with a `Model|Attribute` string.

Remove vertical lines from gettext strings

---

spec/controllers/container_build_controller_spec.rb
spec/controllers/container_group_controller_spec.rb
spec/controllers/container_image_registry_controller_spec.rb
spec/controllers/container_node_controller_spec.rb
spec/controllers/container_project_controller_spec.rb
spec/controllers/container_replicator_controller_spec.rb
spec/controllers/container_route_controller_spec.rb
spec/controllers/miq_report_controller/reports/editor_spec.rb

Update the container specs to match the core changes:
https://github.com/ManageIQ/manageiq/pull/16765

Update container specs to match the new aliases

---

app/controllers/miq_ae_class_controller.rb
spec/controllers/miq_ae_class_controller_spec.rb

- Fixed name of variable that is being pushed into aeinstances and aemethods arrays respectively. In both occurrences item[1] was being reset by item = find_xxx command.
- Added spec test to verify that both instance and method delete is successful from both list view and detail screens.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532340
@mkanoor please test/review.

Fixed variable name

---

app/controllers/application_controller/buttons.rb
spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb

Custom Button Add/Edit - stay on the Advanced tab when changing the System/Process field
Links 
---------
https://bugzilla.redhat.com/show_bug.cgi?id=1501041
1.Go to Automation->Automate->Customization 
2.Add a new Button->Go to Advanced tab-> In Object Details  section
3.Change the System/Process type

Custom Button Add/Edit - stay on the Advanced tab when changing the System/Process field 

---

app/helpers/ems_container_helper/textual_summary.rb

Fix typo in Container Provider Screen: 'Hakalur' to 'Hawkular'.
Screenshots:
Before:
After:
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1538948
cc: @yaacov @himdel

Fix typo in Container Provider Screen: 'Hakalur' to 'Hawkular'

---

app/assets/javascripts/controllers/ansible_repository/repository_form_controller.js

Fixes confirmation messages when Adding or Editing Ansible Repository.
https://bugzilla.redhat.com/show_bug.cgi?id=1500917
Screen shots post code fix:

Fix Ansible Repo Add and Edit confirmation messages

---

app/controllers/container_group_controller.rb
app/helpers/container_group_helper/textual_summary.rb

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1539370
This table usually doesnt help the user. In most cases its a constant `1/1 running containers` type of information.
Before:
After:
@nimrodshn @yaacov Please review
cc @oourfali 
@miq-bot add_label compute/containers

Remove container statuses table from pod summary page

---

app/helpers/application_helper/toolbar/network_router_center.rb
app/helpers/application_helper/toolbar/network_routers_center.rb
app/helpers/network_router_helper/textual_summary.rb

Depends on:
Displaying amazon network routers
Partially implements:
https://bugzilla.redhat.com/show_bug.cgi?id=1488135
Before:
we were not collecting AWS routers
After:

Displaying amazon network routers

---

app/controllers/cloud_subnet_controller.rb
app/helpers/application_helper/button/cloud_subnet_new.rb
spec/controllers/cloud_subnet_controller_spec.rb

Add role(assert) check for cloud network in subnet new form and for related toolbar.
User needs to have also `cloud_network_show_list` role feature to access this `new subnet screen`
https://bugzilla.redhat.com/show_bug.cgi?id=1520651
This feature has been missed in https://github.com/ManageIQ/manageiq-ui-classic/pull/3165/commits/d68cd786a2b63d5915147c9761fcc08d4dfcc01d
Networks -> Subnet -> add new (it can be hidden if user don't have permission)
cc @mzazrivec @himdel 
@miq-bot add_label bug, blocker

Add role(assert) check for cloud network in subnet new form

---

app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
app/views/static/notification_drawer/notification-subheading.html.haml

The text `0 New` `1 New` `2 New` etc. in notification drawer wasn't being translated.
https://bugzilla.redhat.com/show_bug.cgi?id=1538087

Fix missing i18n in notification drawer

---

app/controllers/ops_controller/diagnostics.rb

This would achieve us being consistent with other screens where we render log file output.
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1540134

Don't break lines in server log output

---

app/helpers/application_helper/toolbar/cloud_networks_center.rb

Network editing is only implemented for OpenStack. So it needs to be
disabled for the general case.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1539723
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label networks

Disable cloud network editing and deletion for list view.

---

app/assets/javascripts/controllers/toolbar_controller.js

When clicking on toolbar items which does not return promise UI console would throw error which was silenced with reload of page. This PR wrap return object in `$q.resolve()` which works for checking if the return value of `miqToolbarOnClick` is really promise like object. If not, `TOOLBAR_CLICK_FINISH` is still sent from toolbarController (it will be sent emediately no need to wait for promise reolve).
none

Add  to providers for toolbar and use it to resolve promise from toolbarClick

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller_spec.rb

Update the User data only if the validation passes
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1537601
1. Create an RBAC user that is assigned to one or more groups
2. Edit the RBAC user and remove them from all of their assigned groups
3. Click Save
4. After receiving the error "A User must be assigned to a Group", navigate away from the user's details page.
5. Select the user in the RBAC accordion to view their details

Update the User data only if the validation passes

---

app/controllers/application_controller/tags.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1517285
Tags are always sorted by `:description`.
Have a Tag that has `:description` that will be the first one in Tags but `:name` that will be not.
Before:
After:
@miq-bot add_label bug, tagging, gaprindashvili/yes

Sort tag by descriptions not by name

---

app/controllers/cloud_network_controller.rb

Fixed code alignment to fix an issue where flash messages were not being displayed at all after Delete Cloud Networks button was pressed from list of Cloud Networks. Noticed a message in log "No template found for CloudNetworkController#button, rendering head :no_content"
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1539718
@bronaghs please test/review. Delete button is not present on Cloud network summary screen when selected Network does not support delete task. This PR fixes an issue where it should show appropriate flash message after one or more Networks are selected to Delete.
after fix:

Render flash message or reload list view after Delete is pressed.

---

app/controllers/application_controller/tags.rb
spec/controllers/application_controller/tags_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1470636
Fix _Reset_ button when tagging VMs, Templates, Instances or Images, in _Compute > Clouds > Instances_ or _Compute > Infrastructure > Virtual Machines_.
Also the spec test was added to this PR to check if `@tagging` was properly set.
**Details:**
`@tagging` was not set properly, it was set to `nil` in `tagging_edit` method in _app/controllers/application_controller/tags.rb_, so then `find_records_with_rbac` method failed when it was called from `get_tag_items` method, which was called from `tagging_edit_tags_reset`, when reaching `"reset", nil` case in `tagging_edit` method. The line https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Reset_button_tag_vms_templates_instances?expand=1#diff-32a1920bfa43ecfb08 …

Fix Reset button when tagging vms, templates, instances, images

---

app/views/layouts/exp_atom/_editor.html.haml
spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb
spec/controllers/ops_controller/ops_rbac_spec.rb

Fixes the expression editor for Group Custom buttons and Group enablement Expression
Links
-----------
https://bugzilla.redhat.com/show_bug.cgi?id=1535063
-----------------------------
- Add a custom button for a Group. The enablement expression will only allow the selection of tags without this PR.
-  With a Group custom button with an enablement expression added, an error occurs when selecting a group in Configuration->Access control
Before:
After:

Fix for available expression fields for groups

---

app/controllers/vm_common.rb

Transform screen still uses old dialog runner, fixed code to show form buttons on transform VMs screen.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1540159
@eclarizio please review/test, i have tried combinations of Settings.product.old_dialog_user_ui setting with old/new dialogs, seems to work for me.
before:
after:

Fixed code to display dialog form buttons when loading old dialog runner

---

app/controllers/application_controller.rb
spec/controllers/ems_block_storage_controller_spec.rb

Fix that on report data request the check on role feauture was skipped
role feature has been inherited from controller and action name and
it leads to check role
for example ems_block_storage_report_data and it should be
ems_block_storage_show_list.
cc @karelhala 

Check role features in report data request

---

app/controllers/application_controller/advanced_search.rb
spec/controllers/application_controller/advanced_search_spec.rb

**Fixes:** 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1539614
Issue with more info: https://github.com/ManageIQ/manageiq-ui-classic/issues/3325
Fix broken tagging in _Compute -> Infrastructure -> Datastores_ which breaks after working with filters or Adv search because of wrong setting of `@edit`. The same for _My Services_ page.
---
**Before:**
```
I, [2018-01-29T17:04:55.688793 #12007]  INFO -- : Started POST "/storage/report_data" for ::1 at 2018-01-29 17:04:55 +0100
I, [2018-01-29T17:04:55.717036 #12007]  INFO -- : Processing by StorageController#report_data as HTML
I, [2018-01-29T17:04:55.717226 #12007]  INFO -- :   Parameters: {"model_name"=>"Storage", "model"=>"Storage", "active_tree"=>"storage_tree", "explorer"=>true, "records[]"=>[10000000000005], …
```

Fix broken tagging in Datastores and My Services page

---

app/controllers/miq_policy_controller/alerts.rb
spec/controllers/miq_policy_controller/alerts_spec.rb

commit ea2f7ec1cf7c3b332f64c7e5a5667e80f58d31ee[1] removed setting of
'notification frequency' after changing what to evaluate. Prometheus
alerts relayed on that behavior and it has become impossible to create
them. alert_default_repeat_time sets the value to zero and the field
is then hidden[2]. Since there is a model validation for the zero value
the alerts can't be created. A similar behavior for "hourly alerts"
changed - their default notification frequency should change to 1 Hour.
[1] https://github.com/ManageIQ/manageiq-ui-classic/pull/2601
[2] :https://github.com/ManageIQ/manageiq-ui-classic/blob/86b535f749a41309ad299015ed03208f6f5c956a/app/views/miq_policy/_alert_details.html.haml#L114

Conditionally update alert repeat times

---

app/views/ops/_rbac_user_details.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1538791
before
after

Increased username maxlength from 50 to 255

---

app/views/network_topology/show.html.haml

Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1541299

Fix cloud network topology icon

---

app/controllers/chargeback_controller.rb
app/helpers/term_of_service_helper.rb

Need to merge and keep all kind of providers under same entry to be able ot save chargeback assignments for different types of providers together.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1505335
before:
after:

Merged Container Providers with all other providers in the list

---

app/controllers/ops_controller/settings/common.rb
app/views/ops/_settings_replication_tab.html.haml

related BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1540688
Issue described in BZ: replication screen throws error if replication on one of remote server was not set-up correctly.
After merging https://github.com/ManageIQ/pg-pglogical/pull/20 corrupted subscription would be shown but without any indication that replication set-up is invalid
This PR adding column `status` to UI which would have value `down` in for not working subscriptions
**BEFORE:**
**AFTER:**
@miq-bot add-label replication, enhancement, gaprindashvili/yes
\cc @carbonin @martinpovolny

Added column 'status' to replication screen

---

app/controllers/application_controller/performance.rb

Disable the group_by option when the @perf_options[:no_daily] is set to true for Datastores performance charts with 'Daily' selection
Links 
------------
https://bugzilla.redhat.com/show_bug.cgi?id=1540129
- make sure there is no daily data
-------------------
1. Navigate to Datastore C&U graphs
2. Select Intervel> Daily
3. check for No daily data available
4. select Group By> any VM tag
Before - error when selecting group_by:
After - Group_by not selectable

Disable group_by options when there is no daily data 

---

app/views/miq_ae_customization/_dialog_sample.html.haml

This is a simple change to the sample page of a dialog (when you click on it in the accordion list and it shows some basic sample of what it's going to look like in the right cell). We're merely taking into account default values that were not being utilized before. The radio button sample was also just completely incorrect and needed to be modified.
This fixes part of https://bugzilla.redhat.com/show_bug.cgi?id=1540273, the fix for the timepicker not showing up in the service-ui will likely be needed in the ui-components repo.
@miq-bot assign @dclarizio

Fix for different behavior of items in regards to default values on dialog sample page

---

app/controllers/application_controller/network.rb

This PR removes infra provider from filtered result, because actions like creating networks, assigning FIP, etc. do not work for OpenStack infra provider.
Not sure if removing from filtered result should be done here or should be moved inside controllers.
ping @lpichler @aufi 
https://github.com/ManageIQ/manageiq-ui-classic/pull/3367/files

Remove openstack infra provider from network actions

---

app/presenters/tree_builder_alert_profile.rb

this fixes missing ContainerProject entry in the switch
by removing the switch, since all those entities have class decorators with the same fonticon
(except for middleware, which is gone).
Cc @epwinchell

TreeBuilderAlertProfile - use class decorators for MiqAlert base_tables icons

---

app/helpers/quadicon_helper.rb

Currently when hovering over a quadicon in the providers screen it is somewhat confusing if the quad is showing an issue due to Authentication Status not "Valid". In this PR we add this information upon mouseover.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1537200
cc: @himdel

Adding Authentication Status to the information given on quadicon

---

app/controllers/vm_common.rb

Added vm_transform button pressed id to the list that uses old dialog runner.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1540159

Added vm_transform button pressed id to the list

---

app/helpers/textual_mixins/textual_devices.rb
spec/helpers/textual_mixins/textual_devices_spec.rb

Fixes display of container hard drive filename and mode descriptions for Azure Instances, as well as other providers. Code now accounts for when values/settings are either nil or blank (text) strings. All hard drive parameters were shifted to display in the right hand column on the page for display consistency and viewing legibility. See screen shots bellow.
https://bugzilla.redhat.com/show_bug.cgi?id=1536681
Screen shot before code fix:
Screen shot of Azure Instance post code fix:
Screen shot of Amazon Instance display post fix:
Screen shot of OpenStack Instance display post code fix, notice 2 hard drives listed:

Fixes Azure Instance container display of file name and mode descriptions

---

app/helpers/application_helper.rb
app/helpers/container_group_helper/textual_summary.rb
app/helpers/container_summary_helper.rb
app/views/container_group/show.html.haml
app/views/layouts/listnav/_container_group.html.haml

Adding UI support for `Pod` to `PersistentVolume` relationship.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1435235
GIF:
cc: @himdel @kbrock @zeari

Adding UI support for Pod to PersistentVolume relationship.

---

lib/report_formatter/c3.rb

Fix tag CU chart when there are not enough daily data.
I think, that source of this problem is hidden in generating reports, but because i think it is related to blocker bz, I just fix consequences and return to it later.
Related(ish) with https://bugzilla.redhat.com/show_bug.cgi?id=1540129
Select host with some C&U data, but not for all day.
Utilization -> Group By (tag) -> Daily
Screenshots
Before:
After:

Fix tag CU chart when there are no daily data

---

app/assets/javascripts/controllers/report_data_controller.js

Depends on https://github.com/ManageIQ/ui-components/pull/230 (merged)
When clicking just outside the checkbox in a GTL list, usually the intent is to click the checkbox, not to open the detail screen.
This is to catch that :).
---
[diff -w](https://github.com/ManageIQ/manageiq-ui-classic/pull/3207/files?w=1) for better diff here :)

GTL onItemClicked - ignore clicks on td with checkbox

---

app/controllers/application_controller.rb
app/controllers/report_controller.rb
app/controllers/report_controller/menus.rb
app/controllers/report_controller/reports.rb
app/controllers/report_controller/schedules.rb
app/controllers/report_controller/widgets.rb
spec/controllers/miq_report_controller/menus_spec.rb
spec/controllers/report_controller_spec.rb

The `get_reports_menu` was implemented in a very unreadable and unmaintainable way. So I went through all the possible outputs of the code and reimplemented it in a much simpler pattern. Firstly I pulled out the `default_reports_menu` method that always returns with the default values for a given user. 
The base for the returned result is usually `group.settings[:report_menus]` and if not defined, it falls back to the `default_reports_menu`. On certain screens this output is concatenated with the custom reports that received its own separate query. There was one single exception under these rules under the `Edit Report Menus` screen when the menu is being reset back to default. I decided to do this step directly using `default_reports_menu`, instead of calling the `populate_reports_menu`. …

Refactor _reports_menu methods in the ApplicationController

---

app/controllers/cloud_network_controller.rb
app/controllers/network_router_controller.rb
app/controllers/security_group_controller.rb
spec/controllers/cloud_network_controller_spec.rb
spec/controllers/network_router_controller_spec.rb
spec/controllers/security_group_controller_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1539584
Fix **_tagging_** **Instances/Network Routers** from their list, accessed through _Networks -> Networks_, opening some network details page and clicking on _Instances/Network Routers_ under _Relationships_ table.
Fix tagging I**nstances/Cloud Subnets** from their list, accessed through _Networks -> Network Routers_, opening network router details page and clicking on _Instances/Cloud Subnets_ under _Relationships_ table.
Fix tagging **Instances/Network Ports** from their list, accessed through _Networks -> Security Groups_, opening security group details page and clicking on _Instances/Network Ports_ under _Relationships_ table.
The spec tests for the fixes above are also added in separate commits.
---
Accessing …

Fix tagging Instances

---

app/controllers/chargeback_controller.rb
spec/controllers/chargeback_controller_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1486658
**Depends on** https://github.com/ManageIQ/manageiq/pull/16792 [MERGED]
Fix deletion of Default Container Image Rate in _Cloud Intel -> Chargeback
-> Rates_ so that the Rate can't be deleted and error message is displayed.
---
**Explanation:**
Originally, checking if the selected rate is default (before its deletion), did not work well only if **deleting rate(s) from a list of the rates**. This was because of missing part of the condition for checking default rates here:
https://github.com/ManageIQ/manageiq/blob/master/app/models/chargeback_rate.rb#L153
Checking if the rate is default, worked only from rate details page. This was because of
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/helpers/application_helpe …

Fix deletion of Default Container Image Rate

---

app/helpers/application_helper/button/vm_webmks_console.rb
spec/helpers/application_helper/buttons/vm_webmks_console_spec.rb

`>` instead of `>=` was disabling the VM Console button on 6.0 Hosts incorrectly.  Updated tests to catch this regression in the future.
@miq-bot add_labels bug, blocker, gaprindashvili/yes, fine/yes, compute/infrastructure
https://bugzilla.redhat.com/show_bug.cgi?id=1543106

Fix logic error preventing WebMKS console access on 6.0 Hosts

---

app/controllers/ems_network_controller.rb
app/controllers/mixins/ems_common_angular.rb
spec/controllers/mixins/ems_common_angular_spec.rb

There were two problems when editing Nuage network provider. If
network that you edited had no event, there would still be AMQP
selected under the Events tab. That made Save button disabled
since hostname must not be empty and everything has to be verified.
Now None is selected in case of no event.
The second problem was that when a network was updated error occurred
while redirecting, since you would only get one argument and
`ems_path` required two. Now `ems_path` works same as
in the cloud provider controller.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1534457

Fix Nuage provider update

---

.bowerrc
.gitignore
.travis.yml
app/assets/javascripts/remote_consoles/spice.js
app/assets/javascripts/remote_consoles/vnc.js
bower.json
config/initializers/assets.rb
lib/tasks/manageiq/ui_tasks.rake
tools/ci/setup_js_env.sh

Railties adds `vendor/assets/*` to asset path - https://github.com/rails/rails/blob/20c91119903f70eb19aed33fe78417789dbf070f/railties/lib/rails/engine/configuration.rb#L65
Engine initializer can't remove it because at the point it's running, the array is empty.
Rails asset pipeline can't differentiate between `vendor/assets/bower_components/foo` and `node_modules/foo` because both are in assets path (what #3343 tried to change).
Being able to differentiate is a necessary step when moving off bower.
---
So.. moving bower_components to a subdirectory to get the right semantics:
* `vendor/assets/bower_components` - old location, will be deleted during `bin/update`
* `vendor/assets/bower/bower_components` - new location

Bower to npm - fix paths to really be able to differentiate between bower and npm packages

---

app/controllers/automation_manager_controller.rb
app/controllers/miq_policy_controller.rb
app/controllers/provider_foreman_controller.rb
app/controllers/service_controller.rb
app/controllers/storage_controller.rb
spec/controllers/automation_manager_controller_spec.rb
spec/controllers/miq_policy_controller_spec.rb
spec/controllers/provider_foreman_controller_spec.rb
spec/controllers/service_controller_spec.rb
spec/controllers/storage_controller_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1540613
Fix title of the page to be updated according to search text in _Compute > Infrastructure > Datastores_ page and in another pages.
**Details** (for _Datastores_):
The title of the page was not updated when searching text in _Datastores_, because it was not implemented in storage controller. In other pages, for example _VMs_, it is implemented in `get_node_info` method (like this: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/vm_common.rb#L1155). The title which was changed according to search text in _Datastores_ page, is stored in `@title` variable, updated in application controller (here: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller.rb#L1199), …

Fix title of the page to be updated when searching text in Datastores and other pages 

---

app/helpers/application_helper/button/instance_attach.rb

Fixes the UI bug in https://bugzilla.redhat.com/show_bug.cgi?id=1544732

 Instances without tenants should not cause navigation to fail on InstanceAttach checks

---

app/assets/javascripts/miq_tree.js

We need a copy of the `node.nodes` to iterate through them with deletion, credit goes to @himdel. For the actual issue and steps to reproduce see the GH issue below.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1544844
Fixes https://github.com/ManageIQ/manageiq/issues/15743

Copy nodes object to fix iteration when adding new tree items

---

app/assets/javascripts/miq_explorer.js

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1441101
Fix folding of accordion after adding or editing a schedule in _Cloud Intel > Reports > Schedules_.
**Before:** (_Schedules_ accordion closes after adding a new schedule)
**After:** (_Schedules_ accordion remains open after adding a new schedule)
@skateman Could you please look at it? Thanks a lot! ;)
Some details:
I've added a condition to check active tree (which is set in explorer presenter) and if we are in the same tree as accordion we want to collapse, it just does not happen.

Fix folding of accordion after adding a schedule

---

app/views/layouts/_footer.html.haml
bower.json
config/initializers/assets.rb

A dev-only library that doesn't appear to be used now.
Introduced in ManageIQ/manageiq#8387.
See #3391 for more details :).

Remove tota11y

---

app/controllers/ops_controller/ops_rbac.rb

Prevents the Add button from remaining active when populating the Name field and then clearing the Name field.
@miq-bot add_labels bug, settings, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1486681

Deactivate Add button when name field is cleared

---

app/views/report/_form_filter_chargeback.html.haml

Add options group by tenant to the highlighted options.
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1541110
* [[backend PR ](https://github.com/ManageIQ/manageiq/pull/17002)- but it can be merged without the backend PR ]

Group by tenant for chargeback|metering Vm reports

---

app/helpers/application_helper/button/ems_network.rb
spec/helpers/application_helper/toolbar/ems_network_center_spec.rb
spec/helpers/application_helper/toolbar/ems_networks_center_spec.rb

With this commit we hide option "Edit this Network Provider" for any other NetworkProvider than Nuage. Editing NetworkProviders was disabled prior integrating Nuage into MIQ when we accidently enabled it for all of them. Well not any more, we hide it back for other providers while keeping it for Nuage.
@AparnaKarve this is the followup PR as promised [here](https://github.com/ManageIQ/manageiq-ui-classic/pull/3337#issuecomment-362512635).
@miq-bot assign @AparnaKarve 

Disable editing of NetworkProviders except Nuage

---

app/views/shared/buttons/_ab_list.html.haml
app/views/shared/buttons/_group_form.html.haml

https://bugzilla.redhat.com/show_bug.cgi?id=1535010
@miq-bot add_labels bug, automation/automate

Fix logic to correctly check 'display on button' checkbox

---

bin/update

right now, only manageiq `bin/update` regenerates UI assets, installs bower & npm deps, etc.
it makes sense to me that ui-classic's `bin/update` should do the same thing (because people tend to use it sometimes and expect it to work :))
@bdunne WDYT?

bin/update: run update_ui

---

app/views/shared/views/_ownership.html.haml
spec/views/shared/views/_ownership.html.haml_spec.rb

Add back the option of 'No User Group' ownership ( No group will default to the tenant group of the root tenant). If the owner group is set to a tenant group, the dropdown will show 'No User Group'.
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1483512
Before:
After:

Allow the ownership to be set to 'No group'

---

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js

The 'Use Existing' Dialog radio button was not cooperating when it should have been checked by default. 
@miq-bot add_labels bug, services
https://bugzilla.redhat.com/show_bug.cgi?id=1543136

Fix logic for selecting radio button on Catalog Item edit screen

---

app/helpers/physical_server_helper/textual_summary.rb
spec/controllers/physical_server_controller_spec.rb

Depends on https://github.com/ManageIQ/manageiq/pull/16833

AssetDetails should be AssetDetail

---

spec/helpers/application_helper/buttons/cloud_subnet_new_spec.rb
spec/helpers/application_helper/buttons/floating_ip_new_spec.rb
spec/helpers/compliance_summary_helper_spec.rb
spec/helpers/quadicon_helper_spec.rb
spec/helpers/textual_summary_helper_spec.rb
spec/spec_helper.rb

without this, running single spec files, many tests fail on not being able to run `url_for_only_path`
~~Reverts f62bb815b855d895d2f514fac621fb94c127a9a7 - now we know why this was there :)~~
EDIT:
Updated to include ApplicationHelper only for view specs (since 44 fail), and added manually to the 5 failing helper specs.
Cc @bdunne

spec_helper - include ApplicationHelper

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js

Currently if the response returned from `validate` in the add/edit provider screen is **not** json (i.e javascript / html) we output a green warning with no description (see screenshot).
In this PR we try and catch this scenario and output a warning to the user.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1541744
Screenshot:
Before:
After:
cc: @himdel

Better handling of responses from validation

---

app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
app/assets/javascripts/services/dialog_editor_http_service.js

I am moving out all the MiQ-related API/HTTP calls to a single service. I also found out that the caching feature is just copy-pasted from [my example](https://github.com/ManageIQ/manageiq-ui-classic/pull/2091) but not being actually used, so deleting that too.
My long-term plan is to have an interface specified for this service that would allow to easily re-use the dialog editor elsewhere.
@miq-bot assign @romanblanco

Extract all API/HTTP calls from dialogEditorController to a service

---

app/assets/javascripts/services/dialog_editor_http_service.js

Continuing the effort started in https://github.com/ManageIQ/ui-components/issues/219 and #3414, @romanblanco found an [API call](https://github.com/ManageIQ/ui-components/blob/f816998ade87ef8a4a018fb4fb84b49ed684535a/src/dialog-editor/components/modal/modalComponent.ts#L100) in `ui-components`.

Extract categories API call from dialog editor into DEHttpService

---

app/controllers/automation_manager_controller.rb
app/controllers/infra_networking_controller.rb
spec/controllers/automation_manager_controller_spec.rb

Closes #1922 
The only way to call a `build_*_tree` method without actually invoking the name is via 
`try_build_tree`, but that one only passes 1 or 0 arguments.
Thus, any `build_*_tree` method which relies on the second argument and is not called directly is not called at all.
By coincidence those are exactly the methods which still use `instance_variable_set(:"@#{name}")` :fire: 
Removing those :)

Remove dead build_*_tree methods

---

app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
app/views/miq_ae_customization/editor.html.haml

There's a lot of spaghetti code in the `dialog_editor_controller.js` that shouldn't even be there. I'm creating a top-level `dialogEditor` component in ui-components that will take over some functionalities from this controller. In the future these methods should be moved down into the related sub-components.
Depends on: https://github.com/ManageIQ/ui-components/pull/257
@miq-bot assign @romanblanco

Use the top-level dialogEditor component and drop unnecessary code

---

app/assets/javascripts/controllers/report_data_controller.js
app/controllers/application_controller.rb
app/controllers/miq_request_controller.rb
spec/controllers/miq_request_controller_spec.rb
spec/support/controller_helper.rb

Change the MiqRequest query builder to use `named_scopes` instead of `filter`.
Depends on: ~https://github.com/ManageIQ/manageiq/pull/16843~
Depends on: https://github.com/ManageIQ/manageiq/pull/16939
Depends on: https://github.com/ManageIQ/manageiq/pull/16950

Add scopes for MiqRequest

---

app/views/shared/buttons/_ab_list.html.haml
app/views/shared/buttons/_group_form.html.haml

This is addressing problem described in https://github.com/ManageIQ/manageiq-ui-classic/pull/3383#issuecomment-366679735 and https://github.com/ManageIQ/manageiq-ui-classic/pull/3424#issuecomment-366688854
1. Add / Edit of a Button Group should not produce error
2. `Display on Button` checkbox should be consistent in both the edit & details screen.
`[true, "1"]` because historically you'll find both in the database.
@himdel

Button Group: Fix 'Display on Button' checkbox visibility

---

app/assets/javascripts/directives/datetimepicker.js

1. have a retired vm
2. go to that vm's details page and hit 'Set retirement date' button
3. click on the input field (it render the datetimepicker widget & clear the input field)
4. Save button should become available
https://bugzilla.redhat.com/show_bug.cgi?id=1534962

Support for vm / orch. stack / instance / service unretire

---

app/controllers/application_controller/buttons.rb

Automation > Automate > Customization, Buttons accordion, select object type, Configuration > Add Button Group
Right now, it's apparently possible to submit the form before all the input changes made it to the server.
This enables server-side validation for the required fields.
Fixing this properly will probably mean an angular/react rewrite of the screen.
(+ a fix for the error message when it goes wrong :))
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536670

Custom button group - validate required fields before enabling buttons

---

app/assets/javascripts/controllers/auth_key_pair_cloud/auth_key_pair_cloud_controller.js
app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/assets/javascripts/controllers/miq_ae_class/ae_method_form_controller.js
app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
app/assets/javascripts/controllers/ops/tenant_quota_form_controller.js
app/assets/javascripts/controllers/ownership/ownership_form_controller.js
app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
app/assets/javascripts/controllers/schedule/schedule_form_controller.js

`setPristine(true)` marks the angular form as pristine, unchanged by the user
this makes sense when clicking Reset (kept)
this *may* make sense when clicking Cancel sometimes (kept)
but for add/save, all this does is make the user unable to submit the form again
In cases where submitting again is needed (temporary errors, changes in other tabs), this breaks - removing.
Closes #3425
Cc @lpichler

Remove setPristine from save/add

---

app/views/layouts/exp_atom/_edit_count.html.haml
app/views/layouts/exp_atom/_edit_field.html.haml
app/views/layouts/exp_atom/_edit_find.html.haml
app/views/layouts/exp_atom/_edit_tag.html.haml

This PR adds vertical spacing between rows containing dropdowns and input fields. It also moves the "Use Alias" checkbox next to the dropdown.
Old
New
Issue # 6 here: http://talk.manageiq.org/t/ux-feedback-expression-editor/2927
and
https://bugzilla.redhat.com/show_bug.cgi?id=1394263

Update Expression Editor Styling

---

app/assets/images/svg/vendor-kubevirt.svg
app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/controllers/ems_container_controller.rb
app/controllers/ems_infra_controller.rb
app/controllers/mixins/ems_common_angular.rb
app/helpers/ems_container_helper/textual_summary.rb
app/services/ui_service_mixin.rb
app/views/ems_container/_form.html.haml
app/views/ems_infra/_form.html.haml
app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
app/views/layouts/angular/_multi_auth_credentials.html.haml
spec/controllers/ems_container_controller_spec.rb
spec/controllers/ems_infra_controller_spec.rb
spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js

kubevirt provider is added as a secondary provider to be
managed by the openshift/kubernetes provider.
It will have also representation as an infrastructure provider, but its
management will be done under  openshift/kubernetes, as it shares the
same endpoint, and might differ only by its token.
The token might be different than the default token in order to allow
the specific virtualization capabilities.
Since kubevirt share the same endpoint as the parent provider,
the 'detection' button will not be shown.
The virtualization label for the kubevirt provider:
The virtualization tab for the kubevirt provider:
Changing token for the virtualization manager:
'Add provider' drop-down list without 'kubevirt':

Add kubevirt provider

---

app/controllers/chargeback_controller.rb
spec/controllers/chargeback_controller_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1532701
Caused by: https://github.com/ManageIQ/manageiq-ui-classic/pull/2347
Fix Chargeback Rates page title in _Cloud Intel > Chargeback > Rates > Rates_ folder.
**Note:**
The BZ is not reproducible the exact way it is written in bugzilla, on master branch, because of https://github.com/ManageIQ/manageiq-ui-classic/pull/3215 (I fixed two "title-plural" issues with that PR, but that PR was not backported to Gaprindashvili yet so the BZ is fully reproducible only in Gaprindashvili). So how to reproduce the bug now on master? Simply:
1. Go to _Cloud Intel > Chargeback > Rates > Rates_ folder
and you will see: _All Chargeback Rate_ in the title of the page, instead of _All Chargeback Rate**s**_,
no need to create/delete any of the rates …

Fix Chargeback Rates page title

---

app/assets/javascripts/application.js
app/assets/javascripts/remote_consoles/spice.js
app/assets/javascripts/remote_consoles/vnc.js
app/views/layouts/remote_console.html.haml
app/views/vm_common/console_vmrc.html.haml
app/views/vm_common/console_webmks.html.haml
bower.json
config/initializers/assets.rb
package.json

Moves jquery from bower to npm. That's it :).
(intentionally not removed from bower resolutions (to prevent it automagically adding >=1.6)
Cc @skateman

jquery - move to npm

---

app/views/layouts/_user_input_filter.html.haml

**Fixes issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/499
Fix closing dialog window when applying a filter after user inputs the value and clicks on _Apply_ button, in _Services > Workloads_ and other explorer screens, where this issue also occurs.
Right before applying a filter if user inputs the value:
**Before:** (filter is applied but dialog window did not close, after clicking on _Apply_ button)
**After:** (dialog window has closed and everything looks good)

Fix closing dialog window when applying filter in Workloads

---

app/assets/javascripts/controllers/schedule/schedule_form_controller.js
app/views/ops/_schedule_form_filter.html.haml
app/views/ops/_schedule_form_timer.html.haml
spec/javascripts/controllers/schedule/schedule_form_controller_spec.js

In preparation for 'schedule_form_controller' refactoring, this change is required for new components which will replace existing partials.
refactoring PR: #2766 
This change cause one minor difference. While adding/saving `automation task` the post form values are different. But the form values are for some reason being send in URL as query parameter and these are exactly same as before. Some further investigation is required, but i suspect  that it won't break anything. 
I also think that sending form data in URL is not good and it should be send via POST

Serializing schedule model instead of values from html while saving.

---

app/controllers/bottlenecks_controller.rb

Fixes Bottlenecks timeline data not available message display from warning to information. 
**Note**: Originating BZ request states that an error message, in red, is being displayed. The message and background appear to be "reddish", but in fact are "yellow" per **Patternfly** use and definition. Message itself has been refactored to be an info type to alleviate any visual confusion. 
https://bugzilla.redhat.com/show_bug.cgi?id=1540695
Screen shot prior to fix:
Screen shot post code fix, note Info message display:

Fix Bottlenecks timeline no data message

---

app/controllers/mixins/actions/vm_actions/evacuate.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1544764
Fix mismatch in param value expectations for handling 'evacuate host'
controller action.
A related fix will be needed in fog-openstack to fix the on_shared_storage==false
use case, but this should handle the 'true' use case.

BZ1544764: Fix evacuate host param handling in controller

---

app/controllers/generic_object_controller.rb
app/controllers/service_controller.rb
app/helpers/generic_object_helper/textual_summary.rb
app/helpers/service_helper/textual_summary.rb
app/views/service/show.html.haml
spec/controllers/service_controller_spec.rb

Render GO summary screen when browsing to that thru list of generic objects from service summary screen
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1515857
before:
after:
@dclarizio please review, this one renders GO textual summary screen to show more information on the screen when browsing to GO object from within Services explorer.

Render GO summary screen in Service Explorer.

---

app/views/network_router/_common_new_edit.haml

This PR changes the tag used for "'Fixed IPs" from H2 to H3
https://bugzilla.redhat.com/show_bug.cgi?id=1547878

[WIP] Fix styling issue on "Add New Network Router" screen

---

app/views/shared/views/_retire.html.haml

The div would produce warnings about duplicate ids.

Remove flash_msg_div from retire screen

---

app/assets/javascripts/controllers/report_data_controller.js

when transitioning from a GTL screen to another,
and the target screen has no records,
the paging toolbar doesn't update and keeps showing the old data.
Hiding on 0 rows.
Cc @karelhala 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1548121

GTL: Hide pagination on no records

---

app/controllers/miq_policy_controller.rb
app/controllers/miq_policy_controller/alert_profiles.rb
app/controllers/miq_policy_controller/alerts.rb
app/controllers/miq_policy_controller/conditions.rb
app/controllers/miq_policy_controller/events.rb
app/controllers/miq_policy_controller/miq_actions.rb
app/controllers/miq_policy_controller/policies.rb
app/controllers/miq_policy_controller/policy_profiles.rb

Go to any accordion under Control > Explorer (all of them),
Configure > Add a new $thing,
Cancel (or sucessfully save)
Before: you will see the Add/Cancel buttons hanging around on the "list" screen
After: no add/cancel buttons
---
Done so explicitly by passing `:remove_form_buttons => true` to `replace_right_cell`.
Not seeing any previous mechanism to handle this in miq_policy, the `handle_bottom_cell` mechanism used elsewhere doesn't work when transitiononing to a non-GTL screen.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1530971

MiqPolicy - remove form buttons when cancelling a form or sucessfully saving/adding

---

app/helpers/miq_ae_class_helper.rb
spec/controllers/miq_ae_class_controller_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1331017
before:
after:

Added text (Disabled) next to disabled domain on the right.

---

app/views/network_router/_common_new_edit.haml

This PR moves the section title out of the form-horizontal div
follow-up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/3464
https://bugzilla.redhat.com/show_bug.cgi?id=1547878

Fix Network Router form styling

---

app/controllers/application_controller.rb
app/controllers/application_controller/policy_support.rb
app/controllers/catalog_controller.rb
app/controllers/ems_common.rb
app/controllers/miq_policy_controller.rb
app/controllers/miq_policy_controller/conditions.rb
app/controllers/miq_request_controller.rb
app/controllers/miq_task_controller.rb
app/controllers/ops_controller/diagnostics.rb
app/controllers/ops_controller/settings/analysis_profiles.rb
app/controllers/ops_controller/settings/tags.rb
app/controllers/report_controller/schedules.rb

Messages that are meant to end up in `audit.log` have to stay in English. Translating them makes no sense.
https://bugzilla.redhat.com/show_bug.cgi?id=1548389

Remove gettext from audit.log messages

---

app/controllers/dashboard_controller.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1548160
Go to Cloud Intel -> Timelines
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/3238
Before:
```
F, [2018-02-26T16:06:41.241759 #5449] FATAL -- : Error caught: [ArgumentError] comparison of NilClass with String failed
/ManageIQ/manageiq-ui-classic/app/presenters/tree_builder_timelines.rb:51:in `sort'
/ManageIQ/manageiq-ui-classic/app/presenters/tree_builder_timelines.rb:51:in `x_get_tree_roots'
/ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:240:in `x_get_tree_objects'
/ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:207:in `x_build_tree'
/ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:141:in `build_tree'
/ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:24:in …
```

Fix nil @title in TreeBuilderTimelines

---

app/controllers/network_router_controller.rb
spec/controllers/network_router_controller_spec.rb

Add RBAC check for subnets in add interface screen
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1547408
Scenario
--------
Network -> Network Router -> Add Interface
see subnets with restricted user and check visibility. 
@miq-bot add_label bug, grapindashvili/yes, blocker

Add RBAC for subnet list

---

app/helpers/flavor_helper/textual_summary.rb
product/views/Flavor.yaml

Add enabled and public fields to flavor text summary
BZ - [1182295](https://bugzilla.redhat.com/show_bug.cgi?id=1182295)
ping @martinpovolny @aufi @mansam

Add enabled and public fields to flavor text summary and show list

---

app/helpers/application_helper.rb

This PR removes `Switch` from disabled quadicon members bacause we want to show quadicon (single quad) for switches.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1546729

Enable quadicon image for switch

---

app/controllers/mixins/actions/vm_actions/reconfigure.rb
app/views/vm_common/_reconfigure.html.haml

oVirt provider -> its VMs -> select a VM -> reconfigure VM

Add missing gettext into vm reconfigure dialog

---

app/views/miq_policy/_alert_list.html.haml

The partial is included from `miq_policy/explorer.html.haml` when rendering the whole page or it is rendered via presenter's update when clicking on the Alerts accordion.

Remove duplicate main_div from alerts list view

---

app/views/miq_policy/_policy_list.html.haml

The partial is either included from `miq_policy/explorer.html.haml` when rendering the whole page or is rendered via presenter when clicking on the nodes of the tree of the Policies accordion.

Remove duplicate main_div from policies list view

---

app/views/miq_policy/_action_list.html.haml

The partial is included from `miq_policy/explorer.html.haml` -- used when rendering the whole page or the partial is rendered via `presenter.update()` when clicking on accordions. In either case, the `main_div` is already there and doesn't need to be rendered again.

Remove duplicate main_div from control action list view

---

app/helpers/quadicon_helper.rb

When item hasn't enabled policies, and displays single quad policy shield is visible. That is incorrect, this PR addresses such issue by checking if item can use function `get_policies`

Policy shield should not be visible for items which have no policies

---

app/controllers/ems_common.rb

If a provider clearly states `:reqion_required?` as false, don't
show the Region dropdown in add provider dialogue.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1433062
Before:
```
ng-if="["ec2","azure","gce"].includes(emsCommonModel.emstype)"
```
After:
```
ng-if="["ec2","azure"].includes(emsCommonModel.emstype)"
```
@miq-bot add_label compute/cloud, bug

Hide region from add provider forms if it's not required

---

app/services/dialog_field_visibility_service.rb
spec/services/dialog_field_visibility_service_spec.rb

Currently the DialogFieldVisibilityService sets several instance variables for the constructor arguments, but does not create accessors for them. This PR adds them and has the internal code reference the methods instead of the instance variables directly.
The current code makes subclassing  a pain, where we may want to define our own service classes, and set the instance ourselves for individual providers.
For example, in https://github.com/ManageIQ/manageiq-providers-azure/pull/210, I am forced to redefine the constructor in order to make it use a subclass of `NumberOfVmsVisibilityService`. Whereas if I had an accessor, I could simply do:
```
d = DialogFieldVisibilityService.new
d.number_of_vms_visibility_service = ManageIQ::Providers::Azure::NumberOfVmsVisibilityService.new
```
As for …

Add accessors for DialogFieldVisibilityService.

---

app/helpers/orchestration_stack_helper/textual_summary.rb

This PR corrects the reference to the FontFabulous "output" icon.
https://bugzilla.redhat.com/show_bug.cgi?id=1549165
Old
New

Fix FontFabulous icon reference

---

app/controllers/automation_manager_controller.rb
app/views/automation_manager/explorer.html.haml

**Fixes issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3433
Remove _Advanced Search_ from _All Ansible Tower Providers_ page in _Automation -> Ansible Tower -> Explorer -> Providers_ accordion, as it is not supported there (see the issue for more info) and only _Search_ remains in the page, which works well.
---
**Before:** (Adv Search present)
**After:** (Adv Search NOT present, everything works well)

Remove Adv Search from Ansible Tower Providers page

---

app/helpers/vmware_console_helper.rb
app/views/shared/_remote_console_footer.haml
app/views/vm_common/console_webmks.html.haml

I looked into the [VMware HTML Console Programming Guide](https://www.vmware.com/support/developer/html-console/html-console-sdk-200-programmer-guide.pdf) and on page 8 found that WebMKS has support for key mapping between a few keyboard types. It is not a universal solution, but solves the problem of special characters if both the VM's and the client's keyboard layout is one of the supported keyboards. 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1545927
@bmclaughlin can you test this please? 
@miq-bot add_label gaprindashvili/yes, fine/yes, bug, consoles

Add keymap support for WebMKS remote consoles

---

app/presenters/menu/item.rb
app/presenters/menu/manager.rb
app/presenters/menu/section.rb
app/presenters/menu/yaml_loader.rb
spec/presenters/menu/custom_loader_spec.rb

Expand menu pluggability:
* items into existing section
* sections into existing sections and 2nd level
Details and examples can be seen in the commit message.
* test coverage

Menu pluggability improvements

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1404207
**More info:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3469
---
Fix Default Views settings for _Services > Catalogs > Service Catalogs_ accordion.
Setting up new Default Views settings for _Service Catalogs_ (tile view):
**Before:** (still list view)
**After:**(tile view as expected)
**Note:**
Changing between views in _Service Catalogs_ now also works properly.

Fix Default Views settings for Service Catalogs

---

app/controllers/miq_policy_controller/conditions.rb

With the right cell being replaced, the control policy description validation appears twice. This removes the replacement of the right cell per h-kataria's suggestion at the review that's at the bottom of this PR. 
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1531469

Remove replacement of whole right cell and instead render flash message div so flash message isn't doubled

---

.babelrc

This doesn't actually change the compiled bundle in any way right now, but we should probably make the list of supported browsers explicit.
(The idea is, babel can change the default list of supported browsers, so we may not necessarily be able to rely on the defaults matching our needs.)
@dclarizio Do we still need IE10 for the hammer release?

babelrc - explicitly mention browser support

---

app/controllers/application_controller.rb
app/controllers/guest_device_controller.rb
app/controllers/physical_server_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/toolbar/guest_device_center.rb
app/helpers/application_helper/toolbar/guest_devices_center.rb
app/helpers/application_helper/toolbar_chooser.rb
app/helpers/guest_device_helper.rb
app/helpers/guest_device_helper/textual_summary.rb
app/helpers/physical_server_helper/textual_summary.rb
app/views/guest_device/show.html.haml
app/views/guest_device/show_list.html.haml
app/views/physical_server/show.html.haml
config/routes.rb
product/views/GuestDevice.yaml
spec/controllers/guest_device_controller_spec.rb
spec/controllers/physical_server_controller_spec.rb

This PR changes the way that network device details are displayed on the physical server summary page. The existing _Network Devices_ table was removed, and a new row named _Network Devices_ was added to the _Properties_ table. In this new row, the number of network devices a server has is displayed, and this row can be clicked on to go to a page displaying all network devices. Clicking on an entry on the network devices page takes the user to the network device summary page for that device.
This PR depends on changes made in https://github.com/ManageIQ/manageiq/pull/16996

Change the way that network device details are displayed

---

app/controllers/ems_common.rb

This reverts commit 34a42833db416d644fa9350eda1162462e100df7.
We figured out the regions are completely useless in GCE and since that's the only place where this flag is used at all, it would be nice of me to clean up the mess I've donated to UI. Sorry
Reverts: https://github.com/ManageIQ/manageiq-ui-classic/pull/3471
Related: https://github.com/ManageIQ/manageiq-providers-google/pull/52
@miq-bot add_label bug, compute/cloud

Revert "Hide region from Cloud provider forms if it's not required"

---

app/controllers/ansible_credential_controller.rb
app/helpers/ansible_credential_helper/textual_summary.rb
app/helpers/application_helper/toolbar/ansible_credential_center.rb
app/helpers/application_helper/toolbar/ansible_credentials_center.rb
config/routes.rb
spec/controllers/ansible_credential_controller_spec.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1526219
**Needs to merge with:** https://github.com/ManageIQ/manageiq/pull/17079
---
**Done:**
- add _Policy_ toolbar button to access tagging in _Automation > Ansible > Credentials_
(_Policy > Edit Tags_)
- add `tagging_edit` and `tag_edit_form_field_changed` to routes to enable tagging for Ansible Credentials or for proper rendering of tagging screen
- add calling `tag` method to `button` method in ansible credential controller and also small refactoring of `button` method, in that controller
- display tags in the table in summary page of any credential
- make tagging work also from summary page of any credential
- check if RBAC works
- spec test for `button` method in ansible credential controller
**Before:**
**After:**
**Note:** …

Add RBAC and Tagging Support to Ansible Credentials

---

app/decorators/manageiq/providers/cloud_manager_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/manageiq/providers/hawkular/middleware_manager_decorator.rb
app/decorators/manageiq/providers/infra_manager_decorator.rb
app/decorators/manageiq/providers/physical_infra_manager_decorator.rb

Code sharing is nice, DRY is even nicer, but not in decorator by a convention. Some provider decorators were inherited from the `ExtManagementSystemDecorator˙ and this was wrong, cleaning it up.

Do not inherit decorators from other than MiqDecorator

---

app/helpers/application_helper/toolbar/ansible_credential_center.rb

Fix tool tip when tagging Ansible Credential from its summary page, in _Automation > Ansible > Credentials._
This little issue was caused by: https://github.com/ManageIQ/manageiq-ui-classic/pull/3507
**Before:**
**After:**

Fix tool tip when tagging Ansible Credential from its summary page

---

app/decorators/manageiq/providers/hawkular/middleware_manager_decorator.rb

We don't need this, so :scissors: :scissors: :toilet: :fire:

Drop middleware decorator quadicon definition

---

app/decorators/ext_management_system_decorator.rb

There is always a `type` and an `authentication_status` in the affected records. Also simplified a `(N || nil) || 0` clause to a `N.to_i`.

Do not use try unnecessarily on EMS decorator type/auth_status

---

app/controllers/ansible_repository_controller.rb
app/helpers/ansible_repository_helper/textual_summary.rb
app/helpers/application_helper/toolbar/ansible_repositories_center.rb
app/helpers/application_helper/toolbar/ansible_repository_center.rb
config/routes.rb
spec/controllers/ansible_repository_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1526217
**Needs to merge with:** [SOLVED/merged]
https://github.com/ManageIQ/manageiq/pull/17083 (tagging support to main MIQ repo)
https://github.com/ManageIQ/manageiq/pull/17091 (RBAC support)
---
**Done:**
- add _Policy_ toolbar button to access tagging in _Automation > Ansible > Repositories_
(_Policy > Edit Tags_)
- add `tagging_edit` and `tag_edit_form_field_changed` to routes to enable tagging for Ansible Repos or for proper rendering of tagging screen
- add calling `tag` method to `button` method in ansible credential controller and also small refactoring of `button` method, in that controller
- display tags in the table in summary page of any credential
- make tagging work also from summary page of any credential
- check if …

Add RBAC and Tagging Support to Ansible Repositories

---

app/controllers/report_controller/reports/editor.rb
app/helpers/report_helper/editor.rb
spec/controllers/miq_report_controller/reports/editor_spec.rb

Needed backend PR:
RBAC setup in `after GIF`
see `owner`
1) in this PR there is moving chargeback related code to one method and then usage of this method and executing when your click on filter tab:
```
Move chargeback code to the method
and then move this method to the building screen
it will refresh `@edit[:cb_users]` and
`@edit[:cb_tenant]`  when tab filter is pressed.
```
2) Allowing listing of users and tenants for restricted user, so there is no case of admin and restricted users, so this old code is transformed to
```ruby
if admin_user?		
@edit[:cb_users] = User.all.each_with_object({}) { |u, h| h[u.userid] = u.name }		
@edit[:cb_tenant] = Tenant.all.each_with_object({}) { |t, h| h[t.id] = t.name }		
else		
@edit[:new][:cb_show_typ] = "owner"		
@edit[:new][:cb_owner_id] = …
```

Access show cost by in chargeback report for restricted user

---

app/decorators/host_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/miq_template_decorator.rb
app/decorators/vm_or_template_decorator.rb
app/helpers/quadicon_helper.rb

The `:state_icon` has been introduced unnecessarily and it is not compatible with the new quadicon component's [input specification](https://github.com/ManageIQ/ui-components/pull/243). So changing it to a normal `:fileicon`.

Use fileicon instead of the newly introduced state_icon in decorators

---

app/controllers/mixins/ems_common_angular.rb
app/controllers/pxe_controller/pxe_servers.rb

Removing dead methods ✂️ ✂️ ✂️ 
`no_blank` was introduced and never used in https://github.com/ManageIQ/manageiq/pull/4189
`deletepxes` is present since init commit.

Delete dead methods

---

spec/controllers/mixins/ems_common_angular_spec.rb

https://github.com/ManageIQ/manageiq-providers-nuage/pull/69 adds default enpoint to `:ems_nuage_network_with_authentication` factory. Removing that default endpoint.
Before:
```
Failures:
1) Mixins::EmsCommonAngular.retrieve_event_stream_selection none when amqp and ceilometer have empty hostnames
Failure/Error: expect(network_controller.send(:retrieve_event_stream_selection)).to eq('none')
expected: "none"
got: "amqp"
2) Mixins::EmsCommonAngular.retrieve_event_stream_selection when ceilometer and amqp has empty hostname
Failure/Error: expect(network_controller.send(:retrieve_event_stream_selection)).to eq('ceilometer')
expected: "ceilometer"
got: "amqp"
3) Mixins::EmsCommonAngular.retrieve_event_stream_selection when none
Failure/Error: …
```

Remove default endpoints for :ems_nuage_network_with_authentication

---

app/controllers/floating_ip_controller.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1549763

Apply RBAC filtering to cloud networks when creating floating ips

---

spec/controllers/ops_controller/ops_rbac_spec.rb
spec/controllers/ops_controller_spec.rb
spec/helpers/application_helper/views_shared_spec.rb
spec/presenters/tree_builder_ops_rbac_spec.rb

We are not using users|groups|role with establishing relations them and we are using for some specs objects created from these models but only in memory, without ids. And it is causing problems.
CI failure:
https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/350401089
Links
* caused by https://github.com/ManageIQ/manageiq/pull/17061
Progress
fixed:

Fix CI specs by adding persistent user|group|role object

---

app/helpers/ems_physical_infra_helper/textual_summary.rb

This PR is a complement of https://github.com/ManageIQ/manageiq-ui-classic/pull/3550 where the pdf button for PhysicalInfraProvider wouldn't work

Solve a bug where a pdf button would't work for PhysicalInfra Provider

---

app/controllers/provider_foreman_controller.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1549488
Enable to add tag for configuration provider from 'All Rad Hat Satellites
Providers', in _Configuration > Management > Providers_ accordion.
**Important:** the problem in the screen occurs right AFTER clicking on _Save_ button in tagging screen, so it means that tagging screen opens without problems, it is possible to edit tags in the screen, but not to save them properly.
---
**Before:** (right after saving tags)
Original screenshot from the BZ, for better understanding/reproducing the problem:
**After:**
**Details:**
If we go to _Configuration > Management > Providers_ accordion, we are normally on `root` node, it is _All Configuration Manager Providers_ node, in the tree. After selecting some provider(s) in the list and …

Enable to add tag for configuration provider

---

app/assets/stylesheets/pdf/_fontawesome.scss.erb
app/assets/stylesheets/pdf/_patternfly.scss.erb

this was overlooked in #3343
bower deps using `asset_data_uri` also need the `bower_components/` prefix now
Fixes #3542 
Cc @hstastna can you test please?
Cc @skateman

asset_data_uri - fix bower_components paths

---

app/controllers/provider_foreman_controller.rb

Fixes #3530
By overriding `list_row_id` in ProviderForeman, it didn't get the `to_s` fix needed when moving from compressed ids to actual ids, making it impossible to actually click a foreman manager in GTL.
Adding :)
Cc @hstastna can you test please? :)

ProviderForeman - fix overriden list_row_id to return string id

---

app/assets/javascripts/miq_angular_application.js
app/assets/javascripts/miq_api.js
app/assets/javascripts/miq_application.js

this just takes the API "redirect to login on 401" functionality
and adds it for $http requests as well
(since we never authenticate using $http, we can omit the special case for skipping the redirect on login-related requests)
Cc @martinpovolny you asked for it :)
But turns out, in most cases, when talking to actual rails controllers, you never get a 401, you'll get a 200 instead with some javascript to replace main_div with an error message. So.. we will need a server-side change to actually get those 401 in that case.

$http - redirect to login on 401, same as API

---

.travis.yml

since `spec:javascript` is currently failing sporadically,
we want to halve the number of PRs where restarting jasmine is needed.
Not running non-ruby tests in each ruby version seems like a way to do that :).
Before:
* Ruby: 2.3.1 ; TEST_SUITE=spec
* Ruby: 2.3.1 ; TEST_SUITE=spec:javascript
* Ruby: 2.3.1 ; TEST_SUITE=spec:compile
* Ruby: 2.3.1 ; TEST_SUITE=spec:jest
* Ruby: 2.4.2 ; TEST_SUITE=spec
* Ruby: 2.4.2 ; TEST_SUITE=spec:javascript
* Ruby: 2.4.2 ; TEST_SUITE=spec:compile
* Ruby: 2.4.2 ; TEST_SUITE=spec:jest
After:
* Ruby: 2.3.1 ; TEST_SUITE=spec
* Ruby: 2.3.1 ; TEST_SUITE=spec:javascript
* Ruby: 2.3.1 ; TEST_SUITE=spec:compile
* Ruby: 2.3.1 ; TEST_SUITE=spec:jest
* Ruby: 2.4.2 ; TEST_SUITE=spec

.travis.yml - only run ruby specs in all ruby versions, js once

---

app/assets/javascripts/components/physical_infrastructures/physical-server-toolbar.js
spec/javascripts/components/physical_infrastructures/physical-server-toolbar_spec.js

Bug fix
=====
This PR fixes a bug while try to perform some physical server action from toolbar.
__now__: Error messages is shown to user;
__fix__: Prevent to execute some action for some MiQ UI event that doesn't explicit the `physicalServerToolbarController` to responde for.
This bug was caused as side effect of this PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/3351
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1552866

Fixing bug while try to perform a physical server action

---

bower-locker.bower.json
bower.json

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1549722
Fix tool tip which displayed html code while setting the ownership
for multiple vm's, in _Compute > Infrastructure > Virtual Machines_.
---
**Note:** The bug was originally fixed for master by updating PatternFly to v3.31.1:https://github.com/ManageIQ/manageiq-ui-classic/pull/2989, and I was told that we did not want to backport the whole PR to Gaprindashvili, so I created this PR with only the changes really needed for the fix.
**Before:**
User dropdown (the same for Group dropdown):
User dropdown - No Owner:
**After:**
User dropdown (the same for Group dropdown):
User dropdown - No Owner:

[GAPRINDASHVILI] Fix tool tip while setting the ownership for vm's

---

jest.config.js

When loading JSX file from JS test it throws error that such file was not loaded. This PR fixes such issue adding JSX and TSX into list of extensions.
**none**
**none**

Enable jsx to be loaded from js tests in jest

---

app/views/dashboard/saml_login.html.haml
app/views/layouts/application.html.haml
app/views/layouts/login.html.haml
app/views/layouts/remote_console.html.haml
app/views/layouts/report_only.html.haml

Asset precompilation on appliances is no longer possible, however, in some cases it is necessary to have custom styling applied on a running appliance. This can only be done by bypassing the asset pipeline and loading a CSS file directly from the `public` folder. To avoid 404 errors an empty CSS file has been created in the core repo.
Depends on: https://github.com/ManageIQ/manageiq/pull/17127
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1553353
@miq-bot add_label pending core

Load the custom.css that bypasses the asset pipeline on every screen

---

Rakefile
app/controllers/static_controller.rb
app/views/static/test_haml.html.haml

right now, /static templates are limited to rails helpers, because ApplicationHelper is not included
if one wants to use, say, `datepicker_input_tag`, you get an ugly error instead.
Adding ApplicationHelper so we can use those.
EDIT: Also updated the /static route in jasmine config to use ApplicationHelper
Testing:
1. have the `test_haml` change in, but not the `static_controller` one
1. access `localhost:3000/static/test_haml.html.haml`
1. see an error screen
1. add the `static_controller` change
1. access `localhost:3000/static/test_haml.html.haml`
1. see text & an empty input

StaticController - add ApplicationHelper for helpers

---

tsconfig.json

`jsx: "react"` is needed when importing a jsx file from typescript, or using tsx
`allowJs: true` is needed when importing a js/jsx file from typescript
Cc @karelhala, @martinpovolny 
Extracted from https://github.com/ManageIQ/manageiq-ui-classic/pull/3517
Needed by https://github.com/ManageIQ/manageiq-ui-classic/pull/3228

tsconfig - enable allowJs, jsx:"react"

---

spec/controllers/ansible_repository_controller_spec.rb

Caused by backporting https://github.com/ManageIQ/manageiq-ui-classic/pull/3513 to gaprindashvili branch.

[GAPRINDASHVILI] Fix Travis failing and ansible repository controller spec

---

app/controllers/application_controller/policy_support.rb
app/decorators/miq_template_decorator.rb
app/decorators/vm_or_template_decorator.rb

When in policy simulation and user changes Policy Profile no status is visible because quadicon is not used in this list.
This PR fixes such issue so when selecting Policy Profiles user sees status of policy simulation. If no policy simulation is visible show number of total snapshots
**No policy profile selected**
**Policiy profile selected, but different policy assigned**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1550503

Show policy status when running policy simulation

---

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
app/assets/javascripts/controllers/playbook-reusable-code-mixin.js

Add a check for the data and stop the spinner when the Reset button is pressed on the Ansible Playbook Catalog Item edit form.
Links
-----------
https://bugzilla.redhat.com/show_bug.cgi?id=1553785
1. Edit a Playbook Catalog Item 
2. Make a change and press Reset 
- infinite spinner before this change

Fix for the infinte spinner on Playbook Catalog Item Edit Form Reset

---

app/controllers/ops_controller/settings/common.rb
app/views/ops/_settings_evm_servers_tab.html.haml
spec/controllers/ops_controller/settings/common_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1553771
before:
after:
@bdunne @chrisarcand please review, fixed to display NTP servers values for a Zone, this issue was introduced by changes in following 2 PRs
https://github.com/ManageIQ/manageiq-ui-classic/pull/2720
https://github.com/ManageIQ/manageiq-ui-classic/pull/2359 (fixes saving of NTP servers from UI)

Fixed code that displays values saved for NTP Servers for selected zone

---

app/controllers/application_controller.rb
app/controllers/report_controller/menus.rb
app/controllers/report_controller/schedules.rb
spec/controllers/miq_report_controller/menus_spec.rb
spec/controllers/miq_report_controller/trees_spec.rb
spec/controllers/report_controller_spec.rb

Fixed code to show Custom reports in Available Reports box in menu editor. Code has been refactored and fixed on Upstream and G release, this is a Fine specific fix.
backported changes from https://github.com/ManageIQ/manageiq-ui-classic/pull/3245 to fix issues in menu editor/reports accordion tree.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1496924
https://bugzilla.redhat.com/show_bug.cgi?id=1545441
https://bugzilla.redhat.com/show_bug.cgi?id=1535023
before:
after:

[FINE] - Show custom reports in menu editor as available reports.

---

app/helpers/application_helper.rb

**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3536
Add view selector to _Automation > Ansible > Repositories_ page,
as the other pages under _Automation > Ansible_ already have it.
**Before:**
**After:**
Grid View:
Tile View:
List View:
**Note:** I've also checked tagging support and it works fine when changing views in the page.

Add view selector to Ansible Repositories

---

app/assets/javascripts/miq_global.js
app/helpers/reactjs_helper.rb
app/javascript/packs/application-common.js

This re-sorts the `ManageIQ` global def, makes sure it is always loaded first (already was), 
and renames `MiqReact` to `ManageIQ.react` as it should be :).
(It even contained a comment `TODO: use ManageIQ object, once race conditions are fixed`.)

ManageIQ global cleanup, use for (old) component registry

---

config/webpacker.yml

removed .vue from webpacker.yml, just because we're not using vue :)
Extracted from https://github.com/ManageIQ/manageiq-ui-classic/pull/3517

webpacker.yml - remove .vue

---

app/helpers/host_helper/textual_summary.rb
product/views/Host.yaml

Solves https://bugzilla.redhat.com/show_bug.cgi?id=1400314
1. Have OS undercloud in ManageIQ as Infra manager
2. Go to COMPUTE > INFRASTRUCTURE > NODES > Any node
3. Detail view should display Hypervisor Hostname
4. Go to COMPUTE > INFRASTRUCTURE > NODES > List view
5. Table should contain Hypervisor Hostname column

Adds hypervisor_hostname to details and list view for OS Infra Host

---

app/views/static/generic_object/custom-image-component.html.haml
app/views/static/generic_object/main_custom_button_form.html.haml

main custom button form contains the actual form, does not get angularForm via bindings, so should not use vm
custom image component *should* use vm, but the function does not actually take args
(noticed these while looking at network controllers, where `vm.angularForm` is never right)
Cc @AparnaKarve

Generic Object - fix extra vm.angularForm and nonused angularForm

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/views/layouts/angular/_multi_auth_credentials.html.haml

The metrics & alerts tabs where partially visible.
Those tabs become more visible if the virtualization manager is
selected.
This PR hides any of the tabs if aren't used in Add/Edit provider.
Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/3498
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1550405

Hide disabled tabs

---

app/assets/javascripts/controllers/network_router/network_router_form_controller.js

the model is on vm, not scope, set a few lines above
angularForm is never on vm unless explicitly set
Cc @ZitaNemeckova

networkRouterFormController - fix bad use/nonuse of $scope

---

app/views/layouts/angular/_multi_auth_credentials.html.haml

Update no longer accurate description in the VMRC Console tab.
https://bugzilla.redhat.com/show_bug.cgi?id=1552147

Update description on VMRC configuration tab

---

app/views/miq_request/_prov_dialog_cloud_quota.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1519496 by indicating on the Properties tab whether automatic placement was selected on the Environment tab.

Provisioning properties tab should reflect that tenant will be chosen automatically

---

app/controllers/vm_remote.rb

Images from the webmks css causes CSP errors in browser console and evm.log
Was already fixed for HTML5 console (https://github.com/ManageIQ/manageiq-ui-classic/pull/2833)

Fixed CSP for webmks Console

---

app/helpers/ops_helper/my_server.rb

[MiqServer.my_server in the model is a cache](https://github.com/ManageIQ/manageiq/blob/f7662924f46afacd1eae42d5cefa06c2a2abba34/app/models/miq_server.rb#L547), we shouldn't need to cache it again here.  I found this while [fixing a zone issue](https://github.com/ManageIQ/manageiq/pull/17139) for https://github.com/ManageIQ/manageiq-ui-classic/pull/3582

Remove caching

---

config/webpack/shared.js

CommonsChunkPlugin defaults to only putting libraries in vendor.js if they are used at least twice.
What we really want instead is to put only external dependencies in vendor.js, regardless of how many times they are used.
This ensures anything under `node_modules` will get in vendor.js
Extracted from https://github.com/ManageIQ/manageiq-ui-classic/pull/3517
([docs](https://webpack.js.org/plugins/commons-chunk-plugin/#passing-the-minchunks-property-a-function))

Webpack - CommonsChunkPlugin - force for node_modules

---

app/decorators/ext_management_system_decorator.rb
app/decorators/host_decorator.rb
app/decorators/manageiq/providers/cloud_manager_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/manageiq/providers/infra_manager_decorator.rb
app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
app/decorators/miq_template_decorator.rb
app/decorators/physical_server_decorator.rb
app/decorators/vm_or_template_decorator.rb
app/helpers/quadicon_helper.rb
app/helpers/quadicon_helper/decorator.rb
lib/miq_decorator.rb

This is a required step for the new quadicons, also we still don't like unnecessary things in decorators. I tried to make self-descriptive commit messages, so please read this commit by commit when reviewing. 
Including the `QuadiconHelper::Decorator` in all decorators is unnecessary as it is being used in only a few places. I changed all the method calls to the static `QuadiconHelper::Decorator.method()` form. Also passing the whole object to these methods is not necessary, so from now on just sending the necessary stuff. Methods that are being called just on a single place have been moved into the place of call.
The policies part is a bit tricky, eventually I would like to get rid of the policy alteration of quadicons from the decorators, so we can have all of them consistent. This can …

Untangling QuadiconHelper::Decorator and its shared methods

---

app/helpers/quadicon_helper.rb
spec/helpers/quadicon_helper_spec.rb

I looked into older versions of ManageIQ and found out that the policy shield is not being displayed on single quads. Also it doesn't even look good, so :scissors: :fire: :wastebasket: 
**Before:**
**After:**
@miq-bot assign @epwinchell 
cc @martinpovolny, @karelhala, @dclarizio

Do not display policy shield on single quads in GTL view

---

spec/controllers/ops_controller/settings/common_spec.rb

Depends on: https://github.com/ManageIQ/manageiq/pull/17139
Based on changes in: https://github.com/ManageIQ/manageiq-ui-classic/pull/3568
- Prefer the IANA reserved domains
- Remove stub for MiqServer.my_server

Remove unnecessary stub

---

app/views/layouts/angular/_multi_auth_credentials.html.haml

Reverts #3529, fixed via BZ1536537
@miq-bot add_labels bug, compute/infrastructure
https://bugzilla.redhat.com/show_bug.cgi?id=1552147

Revert changes to description on VMRC configuration tab

---

app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1554938
- Configuration -> Settings -> Schedules ->Configuration -> Add new Schedule / Edit the selected Schedule
- Select Automation Tasks as Action
- See Request. It's requested only when editing.
Before:
After:
@h-kataria please review, thanks :)

Replace miqrequired with required

---

app/decorators/ext_management_system_decorator.rb
app/decorators/host_decorator.rb
app/decorators/manageiq/providers/cloud_manager_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/manageiq/providers/infra_manager_decorator.rb
app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
app/decorators/physical_server_decorator.rb
app/decorators/storage_decorator.rb
app/helpers/quadicon_helper.rb

Single quadicons will be declared as separate methods for each decorator, so the `_n` argument is not necessary.
@miq-bot add_label cleanup, gtls, gaprindashvili/no

Drop the unnecessary argument from the quadicon decorator methods

---

app/controllers/mixins/custom_button_dialog_form_mixin.rb
app/controllers/ops_controller.rb
app/services/dialog_local_service.rb
spec/controllers/mixins/custom_button_dialog_form_mixin_spec.rb

Related to #2671, this just adds a few more object types that will use the new dialog runner and changes some of the mixin logic these object types go through to handle the extra dialog locals that are getting passed down.
Object types that will use the new dialog-user ui-component after this PR:
`CloudNetwork`
`CloudObjectStoreContainer`
`CloudSubnet`
`MiqGroup`
`Tenant`
`User`
/cc @gmcculloug
@d-m-u @syncrou Can you review, please?
@himdel Can you also review or tag someone to review, please?
If anyone has any good ideas on how to best extract/simplify the big case statement within `#determine_api_endpoints` I'm all ears. Right now it's really simple to add to it, but it is definitely pretty ugly. The main problem I see is that for some of the object types the collection name and the …

Use new dialog-user feature for custom buttons for more object types

---

app/decorators/storage_decorator.rb
spec/helpers/quadicon_helper_spec.rb

These two methods produce inverted results. The `fileicon` was producing an error but as we never noticed it, I think it has been never used. So overwriting the `fileicon` with the `free_space_fileicon`.
@miq-bot add_label gtls, gaprindashvili/no, cleanup
@miq-bot assign @epwinchell

Unify fileicon and free_space_fileicon for StorageDecorator

---

app/assets/stylesheets/pdf/_fontawesome.scss
app/assets/stylesheets/pdf/_patternfly.scss

Using `css.erb` can be forgiven, but `scss.erb` is totally unnecessary as there's an `asset_url` helper in `sass-rails`. Merge after: #3571

Do not use .scss.erb for loading assets as there's asset_url in SASS

---

app/views/layouts/_tag_edit_items.html.haml

Remove duplicate flash message on tag reset
This issue exists only on the Fine branch, it was already fixed upstream. 
Links
-----------
https://bugzilla.redhat.com/show_bug.cgi?id=1533082
Before:
After:

[FINE] Remove duplicate flash message on tag reset

---

app/controllers/cloud_network_controller.rb
spec/controllers/cloud_network_controller_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1549564
after:

Display flash message after Cloud Network delete is initiated.

---

app/controllers/miq_ae_class_controller.rb
app/helpers/miq_ae_class_helper.rb
app/views/miq_ae_class/_instance_fields.html.haml
app/views/miq_ae_class/_instance_form.html.haml

Added Max Retries text field on Instance screen

---

app/decorators/miq_template_decorator.rb
app/decorators/vm_or_template_decorator.rb
app/helpers/quadicon_helper.rb

Decorators should not depend on external data, i.e. should not accept external arguments. For now the decorator was responsible for changing the `bottom_right` quadrant of a vm or template quadicon to the policy simulation result. This PR moves out the feature to the quadicon helper and so removes the need for an argument on the `quadicon` method. 
Steps to test:
* Go to `Compute -> Infrastructure -> Virtual Machines`
* Check at least one VM or template
* In the toolbar open `Policy -> Policy Simulation`
* Select some policies from the dropdown and watch the bottom-right quadrant(s)
@miq-bot add_label refactoring, gaprindashvili/no, GTLs

Move out the policy simulation result logic from the related quads

---

app/helpers/ops_helper/textual_summary.rb
app/presenters/tree_builder_ops_vmdb.rb

Don't store `@sb[:vmdb_tables]`.
It's only used once, that that use is a non-sense as the `rows` --> `row` already includes the `:id`.
Ping @skateman, @lpichler

Ops Database: do not store vmdb_tables in the session.

---

app/controllers/generic_object_definition_controller.rb
spec/controllers/generic_object_definition_controller_spec.rb

Currently, when navigating from the GO Definition list, the GTL buttons are displayed in the GO Definition Summary screen, which is not correct. 
This issue is also visible on other summary screens like Custom Button, Custom Group(non-GTL screens) when the view is reloaded.
Navigating from the tree, however, displays the correct toolbar with no GTL buttons.
The PR fixes this inconsistency.
Before (List navigation shows GTL buttons in Summary screen) -
After (List navigation does not show GTL buttons in Summary screen) -
https://bugzilla.redhat.com/show_bug.cgi?id=1545835

Do not display GTL toolbars on non-GTL screens when navigating from the list

---

app/helpers/chargeback_helper.rb
app/views/chargeback/_tier_first_row.haml

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1521113
**Done:**
- fix displaying _**CPU** Cores_ instead of _Cpu Cores_ under the _Group_ column for
_Allocated CPU Cores_/_Used CPU Cores_, when creating a new chargeback rate
- fix displaying _**CPU**_ instead of _Cpu_ under the _Group_ column for _Allocated CPU Count_/_Used CPU_,
when adding a new `tier` (row under the _CPU_ Group), when creating a new chargeback rate
- similarly for _Disk **I/O**_ (which changes to _Disk Io_ when adding a new tier and we don't want this)
-  similarly for _**Network I/O**_ (->  _Net Io_).
**Note:** I used the same way (and working!) of displaying a group in the table as it is in more other places, for example:
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/chargeback/_cb_rat …

Fix displaying 'CPU' and 'CPU Cores' when creating chargeback rate

---

app/controllers/application_controller.rb
app/controllers/configuration_controller.rb
app/helpers/quadicon_helper.rb
app/views/configuration/_ui_1.html.haml

All 4-view quadicons allow a single icon view and this can be configured per-user under `My Settings`. The physical infrastructure provider doesn't have this feature. However, we :heart: consistency so adding it now!
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1555389
@miq-bot add_label gaprindashvili/yes, bug, gtls

Support single quad for Physical Infrastructure Provider quadicons

---

app/views/configuration/_ui_1.html.haml

When having a user without access to physical servers, it should not see the quadicon switch under `My Settings`.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1555400

Respect RBAC rules for physical server quadicon settings

---

app/views/cloud_subnet/new.html.haml

solves https://bugzilla.redhat.com/show_bug.cgi?id=1535369
1. Add OpenStack provider
2. Networks > Subnets
3. Configuration > Add a new Cloud Subnet
Results without patch:
Form on page has wrong form section captions. Original BZ can describe little different parts b/c https://github.com/ManageIQ/manageiq-ui-classic/pull/3254 got merged in the meantime.
Results with patch (expected):
Form on page has "Network Provider", "Placement" and "Cloud Subnet details" sections.
Backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/3148

[FINE] Corrects sections and their names in New Subnet form

---

app/controllers/ops_controller/diagnostics.rb
app/helpers/application_helper/toolbar/diagnostics_zone_center.rb
app/presenters/tree_builder.rb
app/presenters/tree_builder_roles_by_server.rb
spec/helpers/application_helper/toolbar/diagnostics_zone_center_spec.rb
spec/presenters/tree_builder_roles_by_server_spec.rb

Restore the Delete button for servers in a zone, selected from the right-side "Roles By Servers" tab
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1492216
-----
Before:
After:

Restore the Delete button for servers in a zone

---

app/controllers/application_controller.rb
app/controllers/configuration_controller.rb
app/helpers/quadicon_helper.rb
app/views/configuration/_ui_1.html.haml

Analogous with #3624, adding optional single view for network provider icons.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1556883
@miq-bot add_label bug, gaprindashvili/yes, gtls

Support single quad for Network Provider quadicons

---

app/controllers/storage_controller.rb

Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/996
- Go to Automation > Automate > Customization, Buttons accordion
- pick Datastore in the tree
- create a group, and a custom button
- then go to Compute > Infrastructure > Datastores
- click on a datastore
Before:
After:
It cannot rely on `@lastaction == "show_list"` because it's always `"explorer"`. Introduced in https://github.com/ManageIQ/manageiq/pull/11793
@miq-bot add_label bug, toolbars, gaprindashvili/yes

Fix storage_controller to show custom buttons

---

app/views/ems_infra/_form.html.haml

Keystone v2 can be disabled on newer OpenStack versions, we need allow Keystone v3
auth for EmsInfra. The missing thing was unspecified domain_id parameter.
Adding the keystone_domain_id field to make Keystone v3 auth working on Infra providers.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1554329

Add Keystone Domain to EmsInfra form

---

bower.json

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1549723
**Needs to merge with:** https://github.com/ManageIQ/manageiq/pull/17154
Fix tool tip which displayed html code while setting the ownership
for multiple VMs, in _Compute > Infrastructure > Virtual Machines_.
**Note:** The bug was originally fixed for master by updating PatternFly to v3.31.1:#2989, and I was told that we did not want to backport the whole PR to Fine, so I created this PR with only the changes really needed for the fix.
**Note 2**: run `bower install --save bootstrap-select@1.12.2` (in the UI repo and also in main miq repo)
---
**Before:**
User dropdown (the same for Group dropdown):
**After:**
User dropdown (the same for Group dropdown):

[FINE] Fix tool tip while setting the ownership for VMs

---

app/controllers/report_controller/schedules.rb
app/views/layouts/_edit_email.html.haml
app/views/report/_schedule_form.html.haml

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1394217
The problem was caused by `box_title` variable in haml. If the title is represented the way like https://github.com/ManageIQ/manageiq-ui-classic/pull/3647/files#diff-0f738269de482d765f5a66dd8c9fabe5L7, it is simply not translated and is displayed just as it is set. We could fix this by more possibilities. I chose to remove the variable, also because it is used only in a few places. In the second commit of this PR, I am trying also to keep https://github.com/ManageIQ/manageiq-ui-classic/pull/3647/files#diff-0f738269de482d765f5a66dd8c9fabe5L1 because the haml is not used only for schedules. The second commit also ensures us that `E-mail` will also be translated properly. No need to add anything else anywhere else.
--- …

Fix untranslated entry when adding a new Schedule

---

app/helpers/application_helper/toolbar/physical_server_center.rb
app/helpers/application_helper/toolbar/physical_servers_center.rb

This PR is able to
* Remove the delete button from physical servers, because editing Physical Servers is pointless since all 
info are retrieved from a refresh. So if I delete a physical server, it will be retrieved again in the next 
refresh

Remove delete button for PhysicalServer

---

app/presenters/tree_builder_roles_by_server.rb

Use from_cid when highlighting server in the diagnostics server_by_role tree
- follow up for https://github.com/ManageIQ/manageiq-ui-classic/pull/2213
Links 
Upstream PR https://github.com/ManageIQ/manageiq-ui-classic/pull/2213

[GAPRINDASHVILI] Follow-up to Restore server delete button in Diagnostics

---

app/controllers/application_controller.rb
app/controllers/ems_storage_controller.rb
spec/controllers/ems_storage_controller_spec.rb

User correct role feature check for block|object storage summary page
For summary page of storage manager is used ems_storage controller.
And it fails with automatic inheritance feature role for block and object
storage manager.
This change consider feature role regard to type(block, storage) of manager.
So if user is going on block storage manager summary page
ems_block_storage_show feature role is checked
instead of ems_storage_show.
I have user with this role
but I can't access the storage provider
I think that there should be block|storage related controllers like -  ems_block_storage_controller **also for summary page.** Then we can inherit automatically role check.
cc @himdel 
https://bugzilla.redhat.com/show_bug.cgi?id=1538003

Use correct role feature check for block|object storage summary page

---

app/controllers/application_controller.rb
lib/report_formatter/text.rb
spec/controllers/host_controller_spec.rb

Columns, including headers with MiqReport#col_options[<column_name>][:hidden] = true should not
are included in html, pdf, text output formats and only be included in csv
Depends on https://github.com/ManageIQ/manageiq/pull/17133
/cc @dclarizio

Support for hidden columns in reports and views

---

app/controllers/catalog_controller.rb
app/views/catalog/_sandt_tree_show.html.haml
spec/controllers/catalog_controller_spec.rb

Added check around code to prevent error when editing catalog item with missing Provisioning request, with this change, flash message will be displayed on the screen informing user that they can not proceed with editing selected catalog item because request is missing
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1476949
@lgalis please review/test, to test this, you will need to delete a provisioning request associated with a catalog item manually from your database.

Show message when trying to edit item with missing Provisioning request

---

app/helpers/application_helper.rb
config/routes.rb

**fixing issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3429
Display filters in accordion in _Compute > Clouds > Host Aggregates_ page as there is working _Advanced Search_ in the page, but no filters are shown in accordion.
**Before:**
**After:**

Display filters in accordion in Host Aggregates page

---

app/controllers/report_controller/reports/editor.rb

Need to merge first
Links
* https://github.com/ManageIQ/manageiq/pull/17100 (backend PR)
* https://bugzilla.redhat.com/show_bug.cgi?id=1505115
@miq-bot assign @mzazrivec  
@miq-bot add_label gaprindashvili/yes, enhancement

Allow datetime (existence of Resource) fields in report definition of chargeback for VM/Container/...* report 

---

app/controllers/application_controller/compare.rb
spec/controllers/application_controller/compare_spec.rb

Fix compare and drift field counters

---

app/assets/javascripts/miq_application.js
app/assets/javascripts/miq_global.js
app/javascript/miq-component/component-typings.ts
app/javascript/miq-component/helpers.js
app/javascript/miq-component/miq-component.spec.js
app/javascript/miq-component/react-blueprint.tsx
app/javascript/miq-component/registry.ts
app/javascript/miq-component/utils.ts
app/javascript/packs/application-common.js
app/javascript/typings/globals.d.ts
package.json

Most of the code is taken directly from #3228, with the following changes:
* rebased, split into commits, removed some unnecessary changes
* `ManageIQ.component` is set in the pack, not as part of miq-component
* merged `miq-component` and `miq-component-react` .. this is just one extra file, no need to split into directories
* `blueprint` is now exposed under `ManageIQ.component.reactBlueprint`
* this does *not* remove the other registry yet (I will do a separate PR to make both use the same underlying implementation while keeping the API used in plugins)
* added a simple react component helper so we can add react components easily
All the documentation in https://github.com/ManageIQ/manageiq-ui-classic/pull/3228 is still valid,
except for the simple case, you can do …

Add new JS component API (from #3228)

---

app/decorators/manageiq/providers/container_manager_decorator.rb

Missed this one from #3537
**Before:**
**After:**
@miq-bot add_label bug, gaprindashvili/no, gtls

Use fileicon instead state_icon in container provider powerstate quad

---

lib/tasks/manageiq/ui_tasks.rake
package.json
tools/ci/setup_js_env.sh

This reverts the temporary fix from https://github.com/ManageIQ/manageiq-ui-classic/pull/3523,
to fix the problem with https://github.com/ManageIQ/manageiq-graphql/pull/44.
The `update:ui` task is supposed to find all the engines, run `yarn` in all of them, and then webpack the thing :). 
Except thanks to the magic of engines, running the task from ui-classic will only find ui-classic, and not the others - thus forcing `update:ui` to always run from `Rails.root`.

update:ui - ensure we always see all the js engines

---

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
app/assets/javascripts/controllers/miq_ae_class/ae_method_form_controller.js
app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
app/controllers/catalog_controller.rb
app/controllers/miq_ae_class_controller.rb
app/helpers/service_helper/textual_summary.rb
app/views/catalog/_sandt_tree_show.html.haml
app/views/layouts/angular/_ansible_form_options_angular.html.haml
app/views/miq_ae_class/_method_inputs.html.haml
spec/helpers/service_helper/textual_summary_spec.rb
spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js

Add Vault credentials to the UI for Embedded Ansible 
Dependent on:  https://github.com/ManageIQ/manageiq/pull/17048
Links 
------------
UI changes for https://github.com/ManageIQ/manageiq-providers-ansible_tower/issues/53

Add Vault credentials to the UI for Embedded Ansible 

---

app/helpers/quadicon_helper.rb

When running policySimulation for single quad items error is thrown. This PR fixes such issue by running policy simulation with stored policie's keys.

Use keys for policySimulation when single quad is rendered

---

app/controllers/report_controller/schedules.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1559323
Filter in Schedule form is missing custom `MiqReport`s.
Cloud Intel -> Reports -> Schedules -> Configuration -> Edit/Add
Before:
After:

Allow Schedule to have also custom MiqReport in Filter

---

app/controllers/application_controller/policy_support.rb

When assigning policy for any items table (list) view is visible. This is not correct since we users expect quadicons. This PR fixes such issue adding `@gtl_type` to proctect method, same applies for explorer screens.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1553071

Enable grid as view model for policy assignment screens

---

app/assets/javascripts/miq_api.js
app/javascript/packs/compat-common.js
app/views/layouts/login.html.haml
package.json

This adds 2 npm packages:
* `base64js` - JS implementation of base64 which can deal with arbitrary encodings
* `text-encoder-lite` - a shim for the TextEncoder api, useable for utf8 strings (even in IE)
and replaces the `API.login` use of `window.btoa` with a custom `base64encode` function implemented using the 2 libraries.
This way, users can use passwords with unicode chars.
Note: on modern browsers, this will handle any unicode password, including emoji.
On IE, more modern unicode versions may not be fully supported (czech or japanese chars should be fine, emoji may not).
The difference:
```
btoa('babicka')
"YmFiaWNrYQ=="
base64encode("babicka")
"YmFiaWNrYQ=="
btoa('babička')
VM7832:1 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains …
```

API js - use base64encode which can deal with UTF8 passwords

---

app/views/catalog/_sandt_tree_show.html.haml

Add vault credential display for the playbook retirement tab 
- Follow up to:
https://github.com/ManageIQ/manageiq-ui-classic/pull/3468

Add vault credential display for the playbook retirement tab 

---

app/controllers/application_controller/tags.rb
app/views/layouts/_tag_edit.html.haml

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1556984
**Partially caused by:**
[1] https://github.com/ManageIQ/manageiq/pull/5598
[2] https://github.com/ManageIQ/manageiq/pull/9234
**Done:**
- fix sorting of categories by `:description` for assigning tags so that `downcase` method is added, to sort items of the array properly (not sorting only right before displaying the categories like in [2] because for example `@edit[:cat]` depends on what is in the first position of the array for categories, like here: https://github.com/ManageIQ/manageiq-ui-classic/pull/3644/files#diff-32a1920bfa43ecfb0853173babda0f8aL218)
- fix setting `@edit[:cat]` to first category so that `min_by` method is replaced by `first` method, to really get the first item of the categories' array (see the …

Fix mismatching categories with values when assigning tags

---

config/webpack/shared.js

Add the following fix to ignore graphql .flow.js files for the time being:
https://github.com/graphql/graphql-language-service/issues/128#issuecomment-316343538
Webpack does not support these out of the box and it seems that tag-loader is still buggy.
Corresponding PR in manageiq-graphql:
https://github.com/ManageIQ/manageiq-graphql/pull/49
This enables loading that plugin alongside v2v plugin (currently they cannot be loaded together with the webpack dev server in place)

Graphql lanaguage service / ignore .flow.js files 

---

app/controllers/ping_controller.rb

If you stop the DB server, the `/ping` page will keep returning `pong` until the cache is not invalidated. This is a few minutes of inconsistency and can be solved by calling the `connection.active?`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1553223

Fail with an error on /ping immediately if DB is not accessible

---

app/views/layouts/_vertical_navbar.html.haml

In support of https://github.com/priley86/miq_v2v_ui_plugin/issues/161 but also its a bug. 
cc @ZitaNemeckova  for being awesome and helping me with this 🙇‍♀️ ❤️

vertical_navbar - a element to use exisitng param, href

---

app/controllers/application_controller/ci_processing.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1560530
Fix typo in flash message after refreshing Relationship and Power States of
Ansible Tower Providers in _Automation > Ansible Tower > Explorer > Providers_.
**Before:**
**After:**

Fix typo in flash message after refreshing Ansible Tower Providers

---

app/javascript/packs/compat-common.js
package.json
spec/javascripts/miq_api_spec.js
spec/javascripts/support/jasmine.yml

This fixes a bug in older browsers, introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/3682
#3682 adds code that uses TextEncoder in browsers which support it, and TextEncoderLite in browser which don't.
But text-encoder-lite in version 1.0.1 only ever exports the decoder part.
This was fixed in 1.0.2 .. but that one never got released.
So.. updating to the new version (by commit), and adding a spec that will use the Lite version (because phantomjs doesn't have TextEncoder).
Ping @mzazrivec ;)

Fix TextEncoderLite in old browsers

---

app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml

The partial is used only under specific circumstances,
but using ng-show means all the required fields are always required, even when not visible.
This makes it impossible to create a new schedule when using one of the types which don't show `object_request`.
(Because the form is not valid, but the required field is not visible.)
Changing to ng-if, which will not try to validate invisible fields.
(Introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/3613, cc @ZitaNemeckova)
(Fixes :point_up: [March 27, 2018 8:51 AM](https://gitter.im/ManageIQ/manageiq?at=5aba060d458cbde5577df629), cc @nimrodshn)

AeResolveOptions - use ng-if instead of ng-show

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js

"metrics" tab id was renamed to container_metircs in https://github.com/ManageIQ/manageiq-ui-classic/pull/3511, this inconsistency was causing Validate button to remain disabled on openshift provider add/edit screen on Metrics tab.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1561180
cc @masayag 
before:
after:

Fixed id of currentTab

---

app/assets/javascripts/directives/url_validation.js
app/views/ansible_repository/_repository_form.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1540551
Allows http, https, ssh protocols. Allows ssh without protocol.
Automation -> Ansible -> Repositories -> Configuration -> Add/Edit Repository
Try something like `ssh://git@10.195.101.214:10022/jwong/awesome-pub.git`.
Before:
Only `https://<something>.<something>`, `http://<something>.<something>` and `<user>@<server>:<path>` were allowed.
After:
Allows also `ssh://git@<address>:<port><path>`
@miq-bot add_label bug, gaprindashvili/yes, automation/ansible

Allow scm_url to take ssh with ssh protocol

---

app/controllers/application_controller/advanced_search.rb
app/helpers/application_helper.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1536625
Make filters saved in _Advanced Search_ in _Workloads_ displayed in accordion right after creating them. Make filters saved in Adv Search displayed also in another screens like _My Services, Datastores, VMS, Images,_ etc.
**Before:**
**After:**
---
**Details:**
Actually, `build_accordions_and_trees` and `adv_search_redraw_listnav_and_main` methods in `adv_search_redraw_left_div` https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller/advanced_search.rb#L187 do what we need to properly display the tree and the filters, after saving a new filter (see the changes of this PR). I've tested many screens, fixed all of the screens with `x_active_tree` like …

Make filters saved in Workloads displayed in accordion

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

**Fixing issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3648
**BZ:** https://bugzilla.redhat.com/show_bug.cgi?id=1561920
---
Display missing _Advanced Search_ (next to _Search_ form) in _Storage > Block Storage > Volume Snapshots/Backups_ pages.
**Before:**
No Advanced Search in Volume Snapshots page:
No Advanced Search in Volume Backups page:
**After:**
Advanced Search in Volume Snapshots page:
Opening Advanced Search in Volume Snapshots page:
Advanced Search in Volume Backups page:

Display Adv Search in Volume Snapshots/Backups pages

---

app/controllers/mixins/ems_common_angular.rb

Validation of new Amazon,Azure,Google provider take care of http_proxy settings.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1552114
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1559019
@miq-bot add_label pending core
Cc @agrare
1. Go to Configuration -> Advanced
2. Set 
- http_proxy/ec2/host
- http_proxy/ec2/port
- http_proxy/azure/host
- http_proxy/azure/port
- ... OR
- http_proxy/default/host
- http_proxy/defautl/port
3. Go to Compute -> Clouds -> Providers, click on Configuration/Add a New Cloud Provider
4. Set Amazon or Azure provider data and click validate
If you set correct proxy, it should go through it.
If you set some fake url, it returns error message where is fake url mentioned.

Validation of new provider with http_proxy settings

---

app/controllers/vm_remote.rb
app/helpers/application_helper/button/vm_webmks_console.rb
app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
app/views/vm_common/console_webmks.html.haml
config/routes.rb
spec/helpers/application_helper/buttons/vm_webmks_console_spec.rb

With this commit we bring button "Access -> VM Console" to life. We're able to reuse many good stuff from `Vmware:.InfraManager`, but there are also some vCloud specifics. Namely, the JavaScript SDK needs to be initialized with two extra parameters:
```
VCDProxyHandshakeVmxPath // vmx path of the vm (obtained as part of mks ticket)
enableUint8Utf8          // only uint8utf8 protocol works so we need to enable it
```
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1560517
Video: http://x.k00.fr/console
Related PRs:
https://github.com/ManageIQ/manageiq/pull/17200
https://github.com/ManageIQ/manageiq-providers-vmware/pull/218
/cc @bmclaughlin @gberginc

Enable WebMKS console access for VMware vCloud's VMs

---

app/views/layouts/login.html.haml

My fault, the change comes from #3682 which was backported (as it should have been :)), but this one specific line is only relevant for master, because #2652 was never backported (and not supposed to).
Gaprindashvili compiles included dependencies directly into the pack which includes them.
In master, external dependencies go to a separate vendor pack, hence master needs to require it.
Cc @NickLaMuro thanks for finding this :)

[GAPRINDASHVILI] Remove vendor include which should not have been backported

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/views/shared/dialogs/_dialog_user.html.haml
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558266
Automation -> Automate -> Customization -> Service Dialog -> create/edit one to have some regex limitation (like it must be number)
Service -> Catalog -> Catalog Item -> create/edit one catalog item to have service dialog from previous step
Service -> Catalog -> Service Catalog -> order one from previous step
Try to fill inputs incorrectly
Before:
After:
@miq-bot add_label bug, gaprindashvili/yes, services

Check dialog-user for info on valid inputs

---

app/controllers/vm_common.rb
app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

What was happening before was Template custom buttons were going through the old dialog runner, but we are hiding the submit/cancel buttons because they are *supposed* to go through the new dialog runner. The new dialog runner was looking for `MiqTemplate` class and not `Template`. However, the `target_type` that gets passed to the API still need to be `miq_template`, otherwise it fails.
I also threw in a small method refactoring to `vm_common.rb` but that can be removed if we want.
Note that `#determine_target_type` uses a case statement with only one case (for now) because there is another BZ that will be fixed by adding another case to the statement. [PR link for that here](https://github.com/ManageIQ/manageiq-ui-classic/pull/3713)
Fixes …

Fix for Template Custom Button Dialog Not Displaying Submit or Cancel Buttons

---

app/controllers/vm_common.rb
app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

Similar to [this PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/3712), the `target_type` for `InfraManager` does not follow the same convention as most of the other custom button objects, and thus must be set on a case basis.
This PR is built on the above mentioned PR, so the actual change is very small:
```ruby
def determine_target_type(obj)
case obj.class.name.demodulize
when /Template/
"miq_template"
+   when /InfraManager/
+     "ext_management_system"
else
obj.class.name.demodulize.underscore
end
end
```
(and relevant lines of the spec)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1555331

Fix for 400 error when using a custom button from an infra provider.

---

app/views/report/_report_list.html.haml

1. Make sure you have only one custom report in your application available
2. Delete the last one custom report
Before the fix, flash message informing you of the successful report deletion wouldn't show.
After the fix, the flash message is correctly shown.
https://bugzilla.redhat.com/show_bug.cgi?id=1561779

Render flash partial even for an empty report list

---

app/controllers/ops_controller/ops_rbac.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1562828
Configuration -> Access Control -> Users -> Configuration -> Add a new User -> fill as in image below -> click Add
Before:
After:
Makes sure not to re-introduced bug fixed in https://github.com/ManageIQ/manageiq-ui-classic/pull/3345
Steps to reproduce issue from that PR:
- Create an RBAC user that is assigned to one or more groups
- Edit the RBAC user and remove them from all of their assigned groups
- Click Save
- After receiving the error "A User must be assigned to a Group", navigate away from the user's details page.
- Select the user in the RBAC accordion to view their details
If there's an error make sure it isn't related to https://github.com/ManageIQ/manageiq-ui-classic/pull/3720 fix
@miq-bot add_label bug, …

Get all user form data before validating for errors per field

---

package.json

None of these are used, not by ui-classic, nor v2v or graphql.
If we ever get a angular-based plugin, that plugin can depend on angular by itself.
Closes #3715

package.json - remove Angular 2+ dependencies

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller/ops_rbac_spec.rb

Fix for the feature tree role selection in the Add User Form
There is a disconnect between the selection of the features as shown in the tree and the controller features selection.
pluck does not work on proxy associations for new records. ( feature_identifiers now returns an empty array for new records )
* the alternative to this PR is to revert the backend change for feature_identifiers back to map from pluck
Links 
----------
- caused by this PR
https://github.com/ManageIQ/manageiq/pull/17008
1. Configuration -> Access Control ->  Add Role
2. Unselect a feature from the tree.
3. When trying to save the role, an error message indicates that at least a feature must be selected.

Fix for the feature tree role selection in the Add User Role form

---

app/controllers/miq_ae_class_controller.rb

While adding automate domain / namespace, the title says 'Adding a new Automate Namespace', etc.
1) automation -> automate -> explorer -> datastore -> configuration -> add a new domain
2) select the domain -> add a new namespace
3) select the namespace -> add a new class

Changed title for adding / editing automate class for consistency

---

app/assets/javascripts/application.js
app/assets/javascripts/components/generic_object/generic-object-definition-toolbar.js
app/assets/javascripts/components/physical_infrastructures/physical-server-toolbar.js
app/assets/javascripts/controllers/container_deployment/deploy-provider-controller.js
app/assets/javascripts/controllers/error_modal_controller.js
app/assets/javascripts/controllers/header/header_controller.js
app/assets/javascripts/controllers/middleware_server/middleware_server_controller.js
app/assets/javascripts/controllers/report_data_controller.js
app/assets/javascripts/controllers/toolbar_controller.js
app/assets/javascripts/controllers/topology/network_topology_controller.js
app/assets/javascripts/controllers/tree_view_controller.js
app/assets/javascripts/miq_angular_application.js
app/assets/javascripts/miq_debug.js
app/assets/javascripts/miq_explorer.js
app/assets/javascripts/miq_observable.js
app/assets/javascripts/miq_toolbar.js
app/assets/javascripts/services/event_notifications_service.js
app/assets/javascripts/services/subscription_service.js
app/assets/javascripts/services/topology_service.js
app/javascript/miq_observable.js
app/javascript/packs/application-common.js
bower.json
package.json
spec/javascripts/controllers/toolbar_controller_spec.js
spec/javascripts/services/subscription_service_spec.js

Rx.js got a new major version, compliant with the ES observable spec, Angular 2 will depend on it .. we should upgrade :).
The real incompatibility is really small: onNext vs next, and dispose vs unsubscribe.
But unifying and separating while at it..
(converted from ManageIQ/manageiq#13255)
(converted from ManageIQ/manageiq-ui-classic#18)
Since the original PR, version 6 is about to be released, so upgrading to 5.6 which is the transitional migration release.

Update Rx.js to version 5.6

---

app/views/ops/_rbac_user_details.html.haml

Configuration -> Access Control -> Select User that has no Groups
Before:
```
F, [2018-04-04T16:52:35.609332 #65220] FATAL -- : Error caught: [ActionView::Template::Error] undefined method `[]' for nil:NilClass
/Users/zita/Desktop/ManageIQ/manageiq-ui-classic/app/views/ops/_rbac_user_details.html.haml:134:in `___sers_zita__esktop__anage___manageiq_ui_classic_app_views_ops__rbac_user_details_html_haml___1940073322298559570_70282346906420'
/usr/local/lib/ruby/gems/2.3.0/gems/actionview-5.0.7/lib/action_view/template.rb:159:in `block in render'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/lib/ruby/gems/2.3.0/gems/actionview-5.0.7/lib/action_view/template.rb:354:in `instrument' …
```

Fix displaying user detail page

---

app/assets/stylesheets/patternfly_overrides.scss
app/controllers/mixins/chargeback_preview.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1428536
**PR for main MIQ repo:** https://github.com/ManageIQ/manageiq/pull/17204
---
Improve VM Chargeback Preview Report table formatting by:
- adding `non-breakable` html table class for VM Chargeback Preview Report table
- adding` false` value as an (optional) argument of `report_build_html_table` to achieve unsetting `word-break` css attribute
**Before:**
**After:**

Improve VM Chargeback Preview Report table formatting

---

app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
app/controllers/application_controller/ci_processing.rb
app/controllers/mixins/actions/vm_actions/reconfigure.rb
app/views/miq_request/_reconfigure_show.html.haml
app/views/vm_common/_reconfigure.html.haml
spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js

This PR adds a new feature to the 'Reconfigure VM' webpage: Add / Remove Network Adapters.
This PR is part of a set of PRs:
https://github.com/ManageIQ/vmware_web_service/pull/25
https://github.com/ManageIQ/manageiq-providers-vmware/pull/163
https://github.com/ManageIQ/manageiq/pull/16700
https://github.com/ManageIQ/manageiq-ui-classic/pull/3121
Issue #3119 describes the lack of support for adding or removing network adapters at the Reconfigure VM webpage. There are some screenshots and a link to the four PRs implementing this new functionality.

Reconfigure VM: Add / Remove Network Adapters

---

app/services/container_dashboard_service.rb
app/services/container_service_mixin.rb
spec/services/container_dashboard_service_spec.rb

We need to send chart datapoints as complete timestamps (including timezone info) so that the patternfly component would correctly convert them to `Date()` objects and avoid ugly side-effects when viewing the charts in browsers located in different timezones.
1. Have Container provider with some utilization data collected, let's say your data is being collected every midnight in EST timezone.
2. Check the container provider dashboard in CEST timezone
3. Check the container provider dashboard in EST timezone: `$ TZ='America/New_York' firefox`
You'll notince the datapoints in the EST timezone are shifted by one day back.
Previously, we were sending the datapoints to the angular component as `2018-03-23` strings. The patternfly component would then convert them to `Date()` …

Container dashboard charts: send datapoints as full timestamps

---

app/helpers/security_group_helper/textual_summary.rb
config/initializers/range_formats.rb

Instead of **Port** and **End Port** in Firewall rules table on Security group show sceen, rather display a **Port range**.
Additional parsing for the port range:
- If the protocol does not use ports, display `N/A`
- If the ports are not set, it means the rule is effective for all ports
- If the start and end port are the same, display only one value
- Otherwise display the range the way [how it should be displayed](http://www.thepunctuationguide.com/en-dash.html)
A new range-to-string formatter added.
Related: https://github.com/ManageIQ/manageiq-providers-amazon/pull/427
Partially fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1540283

Fix SecurityGroup -> FirewallRules table port range display

---

app/controllers/support_controller.rb
app/views/support/show.html.haml

The documentation text is visible only for administrators even though the RBAC role can display the menu item for it. In this PR I'm dropping the `is_admin?` calls from the view and introducing an RBAC check in the controller.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1563241

Restrict the Help->Documentation screen based on RBAC rules only

---

app/controllers/physical_server_controller.rb

Splitting the single big column into two for a physical server

Physical server details now has two columns

---

app/services/physical_infra_topology_service.rb
app/services/topology_service.rb
app/services/ui_service_mixin.rb
app/views/physical_infra_topology/show.html.haml

* add a Rack icon into topology graph
Depends on: https://github.com/ManageIQ/manageiq/pull/16853 [ Merged ]

Add a physical rack to the topology

---

app/presenters/menu/default_menu.rb

Update vertical nav font icons for Automate and Optimize. (Depends on upgrade to Patternfly Sass 3.23.1)
Old
New

Update menu icons

---

app/controllers/provider_foreman_controller.rb

**Fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1559422
Fix saving changes (name) after editing Satellite Provider and returning to _All Configuration Manager Providers_ page, under _Configuration > Management > Providers_.
---
**Steps to reproduce the problem:**
1. Go to _Configuration > Management > Providers_, you should see _All Configuration Management Providers_ page
2. Click on any other node in the tree, in accordion (this is very important!)
3. Go back to _All Configuration Management Providers_ page so that you click on _All Configuration Management Providers_ folder in the tree, in accordion
4. Select the provider for editing by checking its checkbox and then, under _Configuration_, choose _Edit Selected item_
5. In the editing page, change provider's name
6. Try to save …

Fix saving changes after editing Satellite Provider

---

app/controllers/chargeback_controller.rb
app/helpers/application_helper/button/chargeback_rate_remove.rb

**Fixing** https://bugzilla.redhat.com/show_bug.cgi?id=1552260
**Depends on** https://github.com/ManageIQ/manageiq/pull/17188
---
**The problem:**
There was a bug, in _Cloud Intel > Chargeback > Rates > Compute Rates_: it was possible to edit _Default Container Image Rate_, from its details page and also from the page with the list of Compute Rates.
**How expected result/solution looks like:**
Working with Default Container Image Rate will work (after merging this PR and another PR in main MIQ repo) the same way as working with _Default Rate_ (under Compute/Storage Rates): when displaying its details page, the button for editing of Default Container Image Rate (under _Configuration_) will be disabled automatically; when displaying list of the rates and checking the checkbox of Default …

Fix editing of Default Container Image Rate

---

app/controllers/mixins/ems_common_angular.rb

This is a followup commit to reflect changes done on VMware vCloud repo where we now actually use API version. Signature of `raw_connect` has changed hence we need to update the GUI as well.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1560517
Merge in one take with: https://github.com/ManageIQ/manageiq-providers-vmware/pull/219
@miq-bot assign @agrare

Include api_version when calling raw_connect for vCloud

---

app/assets/stylesheets/icon_customizations.scss
app/views/static/provider_option_field_input.html.haml
app/views/static/provider_option_section.html.haml

Improving two problems with the per-provider UI:
It seems that without titles it is hard to understand the meaning of each setting and also it is not clear that the help text exits.
This added titles and also a question mark icon for the hover help text.

Improve per provider settings ui

---

app/assets/javascripts/application.js
app/assets/javascripts/miq_api.js
bower.json

This is a fine version of:
* https://github.com/ManageIQ/manageiq-ui-classic/pull/3682 (updated to work in ES5, and dependencies via bower)
* https://github.com/ManageIQ/manageiq-ui-classic/pull/3687 (not really needed because we're using the globals here)
* https://github.com/ManageIQ/manageiq-ui-classic/pull/3709 (gaprindashvili fix removing a vendor mention, not really needed here)
---
`window.btoa("sněhulák")` fails on InvalidCharacterError: String contains an invalid character
because it only expects latin1 chars
We need to base64 encode the login:password pair even when the password uses non-latin1 chars :)
Implementation adapted from https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_%E2%80%93_rewrite_the_DOMs_atob()_and_btoa()_usin …

[FINE] API - use a utf-8 aware btoa implementation (base64encode)

---

app/controllers/dashboard_controller.rb

Only on Fine.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1564454
Go to Cloud Intel -> Timelines
Before:
After:
@miq-bot add_label bug, blocker, cloud intel/timelines

[FINE] Fix params for populate_reports_menu

---

app/helpers/application_helper.rb
app/helpers/application_helper/webpack.rb
app/views/layouts/application.html.haml
app/views/layouts/login.html.haml

This adds a `javascript_common_packs` helper, which takes care of the "include vendor pack and all the common packs" logic.
What changes is that we now also support sorting the packs and putting certain packs or repos first in the order.
This should ensure the following load order:
* `vendor.js` - npm deps go first
* `manageiq-ui-classic/application-common.js` - this one contains all the globals, and needs to go before everything else
* anything else from `manageiq-ui-classic/`, sorted by name - so that the core UI goes before any plugins
* everything else, sorted by name (plugin name then pack name)
This should prevent problems where a random pack could go before `application-common.js`, and fail on missing global dependencies.

Webpack pack priority

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller/ops_rbac_spec.rb

Fix for Role Tree Features check display.
The parent feature for Embedded Ansible is enabled for teh EvmRole-vm_user, but that was not reflected in the display tree or when the role was opened for edit. 
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1531499
https://bugzilla.redhat.com/show_bug.cgi?id=1500951
Before:
After:

[FINE] Fix for Role Tree Features check display

---

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
app/views/cloud_volume/_common_new_edit.html.haml

When creating new CloudVolume from CloudVolumeSnapshot, it has to have the same encrypted property as a choosen snapshot. So if a snapshot, from which volume is made, is encrypted it means a new volume has to be encrypted too.
example video: https://app.koofr.net/links/8246bebf-dad9-46ce-ab56-5ba65697e60e
Reference: https://github.com/ManageIQ/manageiq-ui-classic/pull/1324#issuecomment-304106692

Regulate encryption when creating new volume from snapshot

---

app/views/report/_form_expression_buttons.html.haml
app/views/report/_form_filter.html.haml
spec/views/report/_form_expression_buttons.html.haml_spec.rb

- Fixed alignment of Haml code.
- Passing in a local variable to form_expression_button view to be used as an button action and also to load/display correct primary/secondary filter
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1565171
Issue introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/2040
@epwinchell please review/test.
before:
after:

Fixed Secondary filter to be added/edited correctly.

---

spec/controllers/catalog_controller_spec.rb
spec/controllers/ops_settings_spec.rb
spec/views/shared/views/_ownership.html.haml_spec.rb

This fixes these (currently failing) specs in fine:
* `spec/controllers/catalog_controller_spec.rb:889`: received :process_show_list with unexpected arguments
(from https://github.com/ManageIQ/manageiq-ui-classic/pull/3487, Cc @hstastna)
* `spec/controllers/ops_settings_spec.rb:146`: expected "Name is not unique within region 0" to include "Name has already been taken"
(from https://github.com/ManageIQ/manageiq/pull/16731, Cc @carbonin)
* `spec/views/shared/views/_ownership.html.haml_spec.rb:22`: undefined method `sub_table' for nil:NilClass
(from https://github.com/ManageIQ/manageiq-ui-classic/pull/3404, Cc @lgalis)
(There's a fourth failing spec - `spec/controllers/vm_infra_controller_spec.rb:211`, which will go green once https://github.com/ManageIQ/manageiq/issues/17275 is merged.)
In …

[FINE] Fix failing specs

---

app/views/miq_ae_customization/editor.html.haml

In every other form the *Save* button is the leftmost element on the bottom of the screen. However, the dialog editor somehow has it swapped, so changing it for the sake of consistency.
**Before:**
**After:**

Swap the save/cancel buttons on the dialog editor to be consistent

---

app/assets/javascripts/directives/validation/reset_validation_status.js
spec/javascripts/directives/validation/reset_validation_status_spec.js

Skip re-validation if fields that are not Required are blanked out.
This will fix the below BZ where the Save button is not enabled because a blanked out non-required field enforces re-validation.
Before (Save disabled, re-validation is enforced on a blank non-required field) -
After (Save enabled, re-validation is not enforced on a blank non-required field) -
https://bugzilla.redhat.com/show_bug.cgi?id=1559957

Skip re-validation when non-required fields are cleared

---

app/controllers/service_controller.rb

**issue with more info:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3655
Fix title in service details page in _Services > My Services_ when searching by text and then displaying some service details page (by clicking on a service name). The title contained unnecessary string _"(Names with <search_text>)"_.
---
**Before:**
**After:**
**Note:** 
I've added simple condition for not editing `@right_cell_text` when displaying service details page.

Fix title in service details page when searching text

---

app/controllers/ops_controller/ops_rbac.rb

Don't add anything to `record.miq_groups` as it's instantly saved without validation i.e. `[] `can be saved which is invalid.
So moving it from rbac_user_set_record_vars to if record.valid? && validated && record.save! condition.
*Before:*
Edit User -> Save changes -> Success but nothing changed
*After:*
It works
**Check following bugs aren't re-introduced:**
*Bug with edit fixed in https://github.com/ManageIQ/manageiq-ui-classic/pull/3345:* 
1. Create an RBAC user that is assigned to one or more groups
2. Edit the RBAC user and remove all of their assigned groups
3. Click Save
4. After receiving the error "A User must be assigned to a Group", navigate away from the user's details page.
5. Select the user in the RBAC accordion to view their details
6. User has no Assigned groups
*Bug with …

Fix user edit

---

app/views/report/_form_filter_chargeback.html.haml

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1533284
Remove _'Include C&U metrics'_ option for Metering Reports under _Cloud Intel > Reports > Reports_,
for **Metering for VMs**, as this option is redundant, since, by definition, Metering Reports always
include C&U metrics.
**Before:**
**After:**
**Details:**
I've added this line https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Remove_Include_C?expand=1#diff-1538215b565ccfdafec8a0d650ee5ebeR6 to the haml, as the option 'Include Capacity & Utilization Metrics' still makes sense, for `ChargebackVm` model. The rest is untouched. This means that the second option under _Chargeback Resources_ section is displayed also for `MeteringVm` model, normally.

Remove 'Include C&U metrics' option for Metering Reports

---

app/controllers/miq_ae_customization_controller/dialogs.rb

This fixes an issue, when adding new field and setting that to be a dynamic field it was showing pre-filled value in entry point text box from the previous field and was not enabling "Apply" button on the entry point dialog pop up.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532272

[FINE] - Reset field_entry_point when new field is added.

---

app/controllers/ops_controller/diagnostics.rb
app/helpers/application_helper/toolbar/diagnostics_zone_center.rb
app/presenters/tree_builder_roles_by_server.rb
spec/helpers/application_helper/toolbar/diagnostics_zone_center_spec.rb
spec/presenters/tree_builder_roles_by_server_spec.rb

Restore the Delete button for servers in a zone, selected from the right-side "Roles By Servers" tab
Links
-------
Fine backport for https://github.com/ManageIQ/manageiq-ui-classic/pull/2213
https://bugzilla.redhat.com/show_bug.cgi?id=1566746
After:

[FINE]Restore the Delete button for server in diagnostics

---

app/controllers/catalog_controller.rb
app/views/catalog/_sandt_tree_show.html.haml
spec/controllers/catalog_controller_spec.rb

Added check around code to prevent error when editing catalog item with missing Provisioning request, with this change, flash message will be displayed on the screen informing user that they can not proceed with editing selected catalog item because request is missing
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1560097
(cherry picked from commit 6a24e66)
Backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/3661

[FINE] - Show message when trying to edit item with missing Provisioning request

---

app/controllers/physical_server_controller.rb
app/helpers/application_helper/toolbar/physical_infrastructure/operations_button_group_mixin.rb
app/helpers/application_helper/toolbar/physical_server_center.rb
config/routes.rb

Adds a dropdown with a button in the physical server summary page toolbar for remotely accessing the console for a physical server.
The button kicks a task off for generating a remote console resource for the currently selected physical server and makes the UI wait until the task is finished.
The remote console resource can be one of two types:
* A jnlp file that when opened will start a Java Web Start application that can be used to access the machine console. In this case the UI will open a download dialog so that the user can download this file.
* A URL that can be used to access a HTML 5 based remote console application. In this case the UI will open a new tab in the user's browser targeting this URL.
Screen shot of the physical servers summary page before the change:
After the …

Add button in toolbar for remotely accessing a physical server

---

app/controllers/service_controller.rb
spec/controllers/service_controller_spec.rb

Fixes the generic object show in services
Links 
--------------
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1567214
Before - the first generic object in the list was the one displayed, regardless of which one was clicked.
After:

Fix generic object show in services

---

app/controllers/network_router_controller.rb
spec/controllers/network_router_controller_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1567982
similar fix was made for cloud networks in https://github.com/ManageIQ/manageiq-ui-classic/pull/3626
after fix:

save/render flash message after Network Router delete is initiated.

---

app/decorators/host_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/miq_template_decorator.rb
app/decorators/physical_server_decorator.rb
app/decorators/vm_or_template_decorator.rb
app/helpers/quadicon_helper.rb

Since the new quadicons are in, we can use fonticons in a quadrant. Also the SVG powerstate icons aren't really compatible with this new component.
**Before:**
**After:**
@miq-bot add_reviewer @karelhala 
@miq-bot add_label gaprindashvili/no, GTLs

Use fonticons with color in quadicons' powerstate quadrants

---

app/views/cloud_subnet/_common_new_edit.haml

According to https://developer.openstack.org/api-ref/network/v2/ 'Subnet CIDR' is required when adding a new subnet.
This PR marks the 'Subnet CIDR' ui field as required.
Fixes https://bugzilla.redhat.com/1565019

Mark CloudSubnet.cidr as required

---

app/controllers/miq_policy_controller.rb
spec/controllers/miq_policy_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1563316
Fix Search clear button when searching text under _Control -> Explorer_ screens.
---
Before searching text:
**Before:** (after clicking on clear search button, nothing has happened)
**After:** (after clicking on clear search button, the same as before searching text)
**Details:**
The problem was that after `adv_search_text_clear` method (in application controller) was called, `@search_text` was reset to `nil` BUT then set again to the previous value. This was happening the next way: in `adv_search_text_clear`, `reload` method calls `tree_select` from miq policy controller, where because of calling `get_node_info` method `@search_text` was set again, in `set_search_text` method here: …

Fix Control explorer policies Search clear button

---

app/assets/javascripts/controllers/retirement/retirement_form_controller.js
spec/javascripts/controllers/retirement/retirement_form_controller_spec.js

In case we get to the retirement screen after navigating through bunch of other related items, we need to construct the whole retirement URL.
1. My Services -> Active Services -> Select a service
2. Click on Service's VMs
3. In the VM summary screen, click on Service in Relationship table
4. You should be back at Service's summary screen
5. Test that the retirement functionality works correctly.
6. Make sure retirement of other supported items (vms, instances, stacks) also works correctly.
https://bugzilla.redhat.com/show_bug.cgi?id=1563182

Fix url for service / vm / instance / stack retirement

---

app/controllers/container_image_controller.rb

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1554250
When downloading the openscap result report in html, the filename is not indicative of which image was scanned. If the image was `user/image` this changes the filename to `<image>.html` instead of `openscap_result.html`
@cben @moolitayer @nimrodshn Please review

meaningful openscap report filenames

---

package.json

[Redux 4 is here!](https://github.com/reactjs/redux/releases) and [yarn is broken](https://gist.github.com/bdunne/c58ae9f3c26e6647f29392c6cfba7f2b) :(.
Turns out we only depend on redux indirectly, which means the redux 4.0.0 release broke the webpack build..
ERROR in /home/bdunne/.gem/ruby/2.4.3/bundler/gems/manageiq-ui-classic-8303c278b9c0/node_modules/redux/index.d.ts
(19,27): error TS1005: ',' expected.
(and quite a bit more)
Adding that direct dependency.
Also removed `@types/redux`, since it has been [deprecated](https://www.npmjs.com/package/@types/redux).
Cc @bdunne

Add direct redux npm dependency, redux 4.0.0 breaks

---

app/views/layouts/listnav/_explorer.html.haml
app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml

This fixes an issue with apostrophes in the tree data.
https://bugzilla.redhat.com/show_bug.cgi?id=1568417

Send the tree data for explorer trees as an object instead of JSON

---

app/controllers/ops_controller/settings/label_tag_mapping.rb

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1493041
related: 
* https://github.com/ManageIQ/manageiq/pull/17212
* https://github.com/ManageIQ/manageiq-providers-azure/pull/231
* https://github.com/ManageIQ/manageiq-providers-azure/pull/229

Azure labeling and tagging support

---

spec/controllers/application_controller/ci_processing_spec.rb

Fixes failing travis:
Failures:
1) VmOrTemplateController#vm_button_operation should continue to retire a vm
Failure/Error:
expect(assigns(:flash_array).first[:message]).to \
include("Retirement initiated for 1 VM and Instance from the %{product} Database" % {:product => Vmdb::Appliance.PRODUCT_NAME})
expected "Error during 'retire_now': undefined method `userid' for nil:NilClass" to include "Retirement initiated for 1 VM and Instance from the ManageIQ Database"
2) ServiceController#vm_button_operation should continue to retire a service and does not render flash message 'xxx does not apply xxx'
Failure/Error:
expect(assigns(:flash_array).first[:message]).to \
include("Retirement initiated for 1 Service from the %{product} Database" % {:product => Vmdb::Appliance.PRODUCT_NAME})
expected …

CiProcessing specs - stub user for failing retirement specs

---

app/controllers/service_controller.rb
app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

Also no need to show Save/reset/cancel buttons at the bottom of screen causing double set of buttons on screen, new dialog runner renders it's own form buttons.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1568372
@eclarizio please review/test
before:
Non-Ansible Service
Ansible Service
after:
Non-Ansible Service
Ansible Service

Render new dialog runner for all service types.

---

app/controllers/mixins/playbook_options.rb
spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb

Clear the request field when switching teh button type to 'Default'
Links 
---------
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1501031

Clear the request field when switching the button type to 'Default'

---

app/controllers/ops_controller/ops_rbac.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1525123
---
_Add_ button enabled when entering name etc. into the form:
**Before:**
**After:**
---
**Details:**
The core of the problem was that when user deletes characters from the form, then, for example, `params[:name]` is set to `""` instead of original `nil` value. This is considered as different to what it was before, here: https://github.com/hstastna/manageiq-ui-classic/blob/master/app/controllers/ops_controller/ops_rbac.rb#L759 This is why **Add** button is enabled even when we deleted everything from the forms and so we have nothing to add/create. Using `presence` we simply get back `nil` value from `""`.

Fix enabling/disabling Add button when creating new user

---

app/controllers/physical_server_controller.rb
app/helpers/physical_server_helper/textual_summary.rb
spec/helpers/physical_server_helper/textual_summary_spec.rb

This PR makes the following changes to the Physical Server Summary page:
1. Make the IPv4 address in the Management Networks table a link so that it's clickable.
2. Change the name of the Assets table to Asset Details.

Server summary page changes

---

app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
app/views/layouts/angular/_ansible_form_options_angular.html.haml

Fix the setting for the retirement_remove_resources flag
Links
--------
https://bugzilla.redhat.com/show_bug.cgi?id=1546244
https://bugzilla.redhat.com/show_bug.cgi?id=1568077
1. Open creation screen of Ansible Playbook catalog item.
2. Fill required fields.
3. Open Retirement tab.
4. Fill "Remove resources?" field with "No" value.
5. Press "Save" button.
6. Try to "Edit" the catalog item to change value of "Remove resources?" you might be able to change it and save it but after you save it will still might reflect "Yes" (even if you select "No")

Fix the setting for the retirement_remove_resources flag

---

app/controllers/ems_storage_controller.rb
spec/controllers/ems_storage_controller_spec.rb
spec/views/shared/views/ems_common/_show.html.haml_spec.rb

Issue was introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/3341
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1569020
@dclarizio @mzazrivec please review
before:
after:

Added setting of `@ems` to fix the nilclass error.

---

app/controllers/application_controller/ci_processing.rb
app/controllers/orchestration_stack_controller.rb
app/controllers/service_controller.rb
spec/controllers/application_controller/ci_processing_spec.rb
spec/controllers/orchestration_stack_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb

VM retirement should be a request. This redirects to the request list page after hitting the retire_now option on a VM. 
~~https://github.com/ManageIQ/manageiq-automation_engine/pull/157~~
~~https://github.com/ManageIQ/manageiq-content/pull/262~~
~~https://github.com/ManageIQ/manageiq/pull/16933~~

Add redirect to request show_list page

---

app/views/miq_policy/_alert_profile_folders.html.haml

@epwinchell noticed that [some fileicons](https://github.com/ManageIQ/manageiq-ui-classic/pull/3794#issuecomment-382752700) are still being used on the alert profiles screen. Converting those to fileicons, they are located under `Automate -> Explorer -> Alert Profiles`
@miq-bot add_label graphics, refactoring, gaprindashvili/no

Use fonticons for alert profile folders

---

app/assets/images/svg/currentstate-template-no-host.svg
app/helpers/textual_mixins/textual_power_state.rb

It's a symlink to the `template` and so it's not necessary at all.
@miq-bot add_label refactoring, gaprindashvili/no, graphics

Remove unnecessary template-no-host image and its only reference

---

app/controllers/ops_controller/settings.rb
app/controllers/ops_controller/settings/common.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1512443
---
Fix the title in the _Configuration > Settings_ page when selecting _ManageIQ Region_ (or _CFME Region_) in accordion, to match the name in the accordion.
**Before:**
Editing the region (after clicking on _Region10[10]_ in the list, under the title):
**After:**
Editing the region:
---
**Why I fixed this the way I fixed it:**
See https://github.com/hstastna/manageiq-ui-classic/blob/master/app/presenters/tree_builder_ops_settings.rb#L18, especially the` product`.

Fix title in Config Settings page to match the accordion

---

app/controllers/physical_server_controller.rb
app/helpers/physical_server_helper/textual_summary.rb

In order to keep the conventions, I just renamed a method in the physical server summary page according to the updated label.

Renames network method according to label at physical server summary page

---

app/helpers/physical_server_helper/textual_summary.rb
product/views/PhysicalServer.yaml

**This PR is able to:**
- Make a **refactoring** on Physical Server _Listing_ and _show_ views to avoid confusion about some properties.
**Goal:**
- The properties changed in the code were stored on the _physical_servers_ table. However, a few time ago ([manageiq/manageiq-schema#181](https://github.com/ManageIQ/manageiq-schema/pull/181)) they were moved to the _asset_details_ table. This PR concludes this change on the UI.

Some Physical Servers params should be accessed through asset_detail

---

app/controllers/mixins/actions/vm_actions/ownership.rb
app/views/shared/views/_ownership.html.haml
spec/controllers/vm_cloud_controller_spec.rb

This PR fixes several issues on set ownership screen:
1. An error when settings ownership for several items, one of which doesn't support setting ownership (the problem described in https://github.com/ManageIQ/manageiq-ui-classic/issues/3453)
2. List of user groups in select dropdown, when settings the ownership for more than 1 item
3. The GTL list in set ownership screen would render all selected items as opposed to items which do support settings owhership.
To test:
Navigate to list of instances and test all possible scenarios:
1. settings ownership for 1 item
2. settings ownership for multiple items, where every item supports settings ownership
3. setting ownership for multiple items, where some items don't support settings ownership

Fix bugs on set ownership screen

---

app/assets/javascripts/miq_application.js
app/assets/javascripts/miq_c3.js

When I was researching how to fix the BZ, I found that labels are sometimes bad, but in a different way than it is described in the BZ. The precision sometimes doesn't fit the calculation. It was caused by not updating formating function parameters correctly when recalculating.
Links
DOES NOT FIX THIS BZ,  but it is related
https://bugzilla.redhat.com/show_bug.cgi?id=1564136
Enable C&U data collection in Configuration.
Select some Host/Vm/whatever with C&U data
Monitoring -> Utilization -> Look at charts, hide/show series by clicking on the legend
Repeat for different entity

Fix using old options for calculating

---

app/controllers/application_controller.rb

@simaishi you pinged me a few days ago because of the [failing `fine` branch](https://github.com/ManageIQ/manageiq-ui-classic/pull/3728#issuecomment-382488115). I don't know how the tests and my eyes did not caught this earlier :disappointed: sorry for that. Basically the `gaprindashvili` branch already has this extra argument and without it the RBAC handlig for the help menu just fails with an exception.
https://bugzilla.redhat.com/show_bug.cgi?id=1569171

[FINE] Add an optional argument for handling RBAC based on a boolean value

---

app/views/catalog/_sandt_tree_show.html.haml

Fixes default display of "Custom" Service Catalog Item Subtype when value is not set upon creation/edit.
https://bugzilla.redhat.com/show_bug.cgi?id=1568471

Fixes Service Catalog Item Custom subtype display

---

app/helpers/application_helper/button/instance_check_compare.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1560107
Compute -> Infrastructure -> Vms -> select one or more -> Policy -> Check Compliance of Last Known Configuration
Compute -> Clouds -> Instances -> select one or more -> Policy -> Check Compliance of Last Known Configuration
Before:
After:
@miq-bot add_label gaprindashvili/yes, fine/yes, bug, toolbars, wip

Enable Compilance button for list of VMs

---

app/views/catalog/_form_basic_info.html.haml
app/views/catalog/_sandt_tree_show.html.haml

Needs to be merged with https://github.com/ManageIQ/manageiq/pull/17319

Apply gettext on catalog types & subtypes

---

app/assets/stylesheets/patternfly_overrides.scss

The `disabled` class is being properly added to the treeview when necessary, it was just not backed by any styling. You can find this screen under `Cloud Intelligence -> Reports -> Edit Reports Menu` by selecting a group in the left side treeview and then any element in the right side tree.
**Before:**
**After:**
@miq-bot add_label bug, graphics
https://bugzilla.redhat.com/show_bug.cgi?id=1550641

Fixed disabled report editor treeview styling regression

---

app/controllers/infra_networking_controller.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1428584
---
Remove _Search_ from **Switch summary page** accessed by clicking on some Switch from the list under _Compute > Infra > Networking > Switches_ accordion.
**Before:**
**After:**
**Details:**
The BZ is fixed simply by hiding _Search_, in infra networking controller, when displaying the Switch details page and setting visibility of Search here: https://github.com/ManageIQ/manageiq-ui-classic/pull/3838/files#diff-0e2f6e9cd3d08a0294024651f1726172R576. And `@nodetype` is always set in `get_node_info`, before setting visibility of Search, according to type of the actual node in the tree.

Remove Search from Switch summary page

---

app/views/catalog/_svccat_tree_show.html.haml

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1571614
---
Change Service's _Order_ button to blue color to look active, under _Services > Catalogs > All Services_ > some specific Service.
**Before:**
**After:**

Change Service 'Order' button to blue color to look active

---

app/decorators/vmdb_database_connection_decorator.rb
app/decorators/vmdb_database_setting_decorator.rb

I [compared](https://gist.github.com/skateman/c36c2ee62b21ae45a3383980ac36c5be) the list of models without decorators with the PNG files we have in the `100` folder and found out that those two models are still getting their icons in GTLs using `view.db.underscore`. 
**Before:**
**After:**
Note that testing the `VmdbDatabaseConnection` is blocked by https://github.com/ManageIQ/manageiq/issues/17344, but commenting the affected line works it around.
@miq-bot add_reviewer epwinchell
@miq-bot add_label graphics, gaprindashvili/no, refactoring

Decorator w/fonticon for VmdbDatabaseConnection and VmdbDatabaseSetting

---

app/controllers/ems_common.rb
app/controllers/mixins/ems_common_angular.rb
app/controllers/mixins/more_show_actions.rb
app/helpers/application_helper/toolbar_chooser.rb

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1536097
Changes:
###
* remove one level of nesting in ToolbarChooser (so that we can actually read the condition)
* split method `button` in `EmsCommon` (the method was already a `if/else/case` branching with methods calls, but somehow people started adding in-line code again :cry: :sob:  )
* remove extra code from `timeline_pressed`
* combination of `@layout` and `@last_action` then causes the correct toolbar: `timeline_center` to be rendered.
* make the redirect in `update_ems_button_cancel` more robust (will default to `show` when given action does not exist).
1. Have a provider (tested with vSphere infra)
2. Open the provider's details
3. Select Monitoring/Timelines
4. Inside Timelines, select Configuration/Edit this XYZ provider …

Timeline menu

---

app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
app/assets/javascripts/controllers/ansible_repository/repository_form_controller.js
app/views/ansible_credential/_credential_form.html.haml
app/views/ansible_repository/_repository_form.html.haml

1. Create a new role, new group using that role and a new user using that group
2. Set the group restriction to one specific tag (edit the newly created group, assign filters, select one tag)
3. With the new user, navigate to Automation -> Ansible -> Credentials
4. Click on Add new Credential
Before:
After:
I also disabled the repository inputs for similar case.
@himdel review please?
https://bugzilla.redhat.com/show_bug.cgi?id=1560527

Disable credential / repository form when embedded ansible is unavailable

---

app/views/shared/_quadicon.html.haml

The `miq_bootstrap('miq_quadicon')` is too generic and it doesn't work if there are more than one quadicons on a single screen. For example on the VM compare screen, the second VM's quadicon is not being displayed and a JS error shows up in the console.
**Before:**
**After:**

Add a unique random DOM ID for each quadicon and use it in miq_bootstrap

---

app/helpers/application_helper/toolbar/network_router_center.rb
app/helpers/application_helper/toolbar/network_routers_center.rb

Fine specific PR for changes made in https://github.com/ManageIQ/manageiq-ui-classic/pull/2234
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1544488
@Ladas @martinpovolny please review, PR with only specific changes to remove Edit/Delete etc buttons from Network Router(s) screens.

[FINE] - Removed specific buttons for Network Routers

---

app/assets/javascripts/services/dialog_editor_http_service.js
spec/javascripts/services/dialog_editor_http_service_spec.js

This simply adds the name and id to the category attribute list when requesting the categories from the API for the dialog editor to use in [this ui-components PR](https://github.com/ManageIQ/ui-components/pull/291). The problem is that certain categories have different names than their description, and so sometimes it was failing when trying to choose them to use.
This will need to be merged first, otherwise the ui-components will not have a 'name' field to use properly.
https://bugzilla.redhat.com/show_bug.cgi?id=1570613
/cc @gmcculloug @d-m-u 

Fix for certain tag categories being unable to be saved as dialog field elements

---

app/decorators/vmdb_database_setting_decorator.rb

I set a wrong icon in https://github.com/ManageIQ/manageiq-ui-classic/pull/3851#discussion_r184413333, fixing.
@miq-bot add_label graphics

Change fa-cog to pficon-settings in VmdbDatabaseSettingDecorator

---

app/helpers/vm_helper/textual_summary.rb

Fixes display of UI label with both words capitalized. 
https://bugzilla.redhat.com/show_bug.cgi?id=1518926

Fixes display of VM Retirement State label

---

app/controllers/application_controller/filter.rb
app/views/layouts/exp_atom/_edit_tags.html.haml

Clear tag expression field when editing group tag expression
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1506685

Clear tag expression field when editing group tag expression

---

app/controllers/application_controller/filter/expression.rb

When selected field type id date type field, allow a drop down to be displayed with After/Before etc. options to be selected to form an expression.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1563823
before:
after:
@yrudman cc

Do not force exp_key to be limited to "CONTAINS" for date type fields.

---

app/controllers/application_controller/performance.rb

Remove memory chart for Amazon Availability Zones.
Screenshots
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1441326
Compute -> Cloud -> Availability Zones -> Monitoring -> Utilization -> Test it for Amazon and other types

Remove memory chart for Amazon Availability Zones

---

app/views/report/_schedule_form_timer.html.haml

There's no `:timer_typ` key in `@edit[:new]` so it's aways `nil` and select is set to Hourly as it's the first value.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1564199
Cloud Intel -> Reports -> Dashboard Widgets -> choose one that hasn't timer set to Hourly -> Edit
Cloud Intel -> Reports -> Schedules -> choose one that hasn't timer set to Hourly -> Edit
Configuration -> Settings -> Schedules -> choose one that hasn't timer set to Hourly -> Edit 
Before:
After:
@miq-bot add_label bug, gaprindashvili/yes, cloud intel/reporting

Change @edit[:new][:timer_typ] to @edit[:new][:timer].typ

---

app/controllers/physical_server_controller.rb
app/helpers/physical_server_helper/textual_summary.rb
app/views/physical_server/show.html.haml
spec/controllers/physical_server_controller_spec.rb

This PR adds support for displaying details about storage devices associated with physical servers. A link displaying the number of storage devices associated with a server will be displayed on the Physical Server Summary page. Clicking on this link will take the user to a page that displays a list of a server's storage devices. Clicking on one of these devices takes the user to the Storage Device Summary page for that device.
This PR depends on https://github.com/ManageIQ/manageiq/pull/17332

Add support for displaying storage device details

---

app/controllers/application_controller.rb

The console popup windows update the user session data (session[:tab_url][sid]). This data is used falsely by the dashboard_controller.rb in redirect_to_remembered, method that tries to redirect the console in the main ManageIQ UI. This leads to a exception in the manageiq ui. See #3833.
This PR is a really ugly fix that mitigates the issue for VMWARE WebMKS and HTML5 console. I think this PR must be improved to fix it for all possible popup windows...  Suggestions are welcome.
Links
* Fix for https://github.com/ManageIQ/manageiq-ui-classic/issues/3833

Do not store console popups in session

---

app/controllers/support_controller.rb

The naming of methods/actions inside this controller (its name included) is just horrible and misleading. The RBAC check was improperly introduced in #3728 against the `support` feature, but it should be `documentation`.
ping @simaishi 
@miq-bot add_label bug, gaprindashvili/yes, fine/yes
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1569170

Validate Help->Documentation screen against the documentation feature

---

app/views/layouts/listnav/_compare_sections.html.haml

There was some ancient logic, it has been completely replaced with decorator :scissors: :scissors: :toilet: :fire: 
**Before:**
**After:**
**Please test this against different types of drift screens (host, vm, etc).**

Remove unnecessary code around the quadicon rendering on drift screens

---

app/helpers/application_helper/listnav.rb

We have a duplicated physical_server entry in the ApplicationHelper code for the same string. This change removes one of them.

Remove duplicate physical server entry from ApplicationHelper

---

app/controllers/cloud_volume_controller.rb
app/views/cloud_volume/_common_new_edit.html.haml

https://bugzilla.redhat.com/show_bug.cgi?id=1570570
There are two fixes here:
1) Error handling for cloud volume create/edit was broken. The controller
was improperly handling the return value from the validate method calls.
2) The UI for showing the cloud tenant selection input wasn't handling
the recent classname change for CinderManager

bug 1570570:  cloud volume create fixes

---

product/views/ManageIQ_Providers_PhysicalInfraManager.yaml

- Add authentication status column in the Physical Providers list

Showing authentication status in Physical Provider list

---

app/views/ops/_rbac_group_details.html.haml
spec/views/ops/_rbac_group_details.html.haml_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1440209
Instructions from BZ:
> Group lookup is not supported when using external authentication with SAML.
> Group lookup is also not supported for Amazon. 
Configuration -> Settings -> select Current Server -> Authentication -> Mode -> set to `Amazon`/`Database`/`External` with `SAML` enabled 
Configuration -> Access Control -> Create a new Group
Before:
After:
@miq-bot add_label bug, gaprindashvili/yes, fine/yes, euwe/yes

Disable Look up Group for Amazon, Database and External with SAML

---

app/controllers/application_controller/ci_processing.rb
spec/controllers/application_controller/ci_processing_spec.rb

**The PR should be merged together with the PR to the core repo: https://github.com/ManageIQ/manageiq/pull/17143**
---
Generalized case statement so it responds to the method change in the core
Links
* https://github.com/ManageIQ/manageiq/pull/17143
* ManageIQ/manageiq-providers-amazon#419
cc @miha-plesko

Generalized case statement so it responds to the method change in the core

---

app/assets/javascripts/controllers/configuration/time_profile_form_controller.js
app/controllers/configuration_controller.rb
app/views/configuration/_timeprofile_form.html.haml
spec/javascripts/controllers/configuration/time_profile_form_controller_spec.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1524352
Introduced in https://github.com/ManageIQ/manageiq/pull/10524
My Settings -> Time Profiles -> select one time profile -> Configuration -> Copy
Before:
Form is empty. Nothing pre-filled.
After:
Form is pre-filled.
@miq-bot add_label wip, bug, angular dialogs, gaprindashvili/yes, fine/yes, euwe/yes

Timeprofile copy fix
