ManageIQ/manageiq-ui-classic

app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1574403
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/2671
Automation -> Automate -> Customization -> create a custom button with a dialog for Datastore
Compute -> Infrastructure -> Datastores -> click on one -> click on the custom button with a dialog
Before:
After:
@miq-bot add_label bug, gaprindashvili/yes, automation/automate

Fix Dialog's API call for Datastore

---

app/controllers/guest_device_controller.rb
app/helpers/guest_device_helper/textual_summary.rb

__This PR is able to:__
- Adapt the Network Device (`GuestDevice`) page to the new physical ports relationship;
__Motivation:__
The physical ports information were moved from `GuestDevice.child_devices` to the new model `PhysicalNetworkPorts` accessed as `GuestDevice.physical_network_ports` ([more details here](https://github.com/ManageIQ/manageiq/pull/17268))
__RFE:__
https://bugzilla.redhat.com/show_bug.cgi?id=1573580
__Depends on:__
~https://github.com/ManageIQ/manageiq-schema/pull/185~ - Merged
~https://github.com/ManageIQ/manageiq/pull/17268~ - Merged
~https://github.com/ManageIQ/manageiq-providers-lenovo/pull/152~ - Merged

Adapting the Network Devices page to the new ports relationship

---

app/controllers/mixins/ems_common_angular.rb
spec/controllers/mixins/ems_common_angular_spec.rb

For `VMWare Infra VMRC Console`, correct credential parameters were not being passed while doing the validation on the queue.
Other than the above case that was reported in the BZ, the PR also fixes the following cases -
`OpenStack cloud AMQP`
`OpenStack infra AMQP`
`VMWare cloud AMQP`
https://bugzilla.redhat.com/show_bug.cgi?id=1574000

Pass correct credential parameters depending on the credential type

---

app/assets/javascripts/components/physical_infrastructures/change-password-component.js
app/controllers/ems_common.rb
app/controllers/ems_physical_infra_controller.rb
app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
app/views/ems_physical_infra/change_password.html.haml
app/views/static/ems_physical_infra/change_password.html.haml
config/routes.rb
spec/javascripts/components/physical_infrastructures/change-password-component_spec.js

**This PR is able to:**
- Add a view to change password of a Physical Infra Provider
__ems_physical_infra/show_list__
__ems_physical_infra/change_password/${id}__
__After click in save button__
__The user can follow the change password request status in the tasks page__
**This PR depends on:** 
* ~https://github.com/ManageIQ/manageiq/pull/16883~ - Merged
* ~https://github.com/ManageIQ/manageiq/pull/16895~ - Merged

Implementing change password view

---

app/controllers/catalog_controller.rb

Fix code to check for required Provider and Job Template selections in the drop downs. 
https://bugzilla.redhat.com/show_bug.cgi?id=1491772
Screen shot post code fix, for Ansible Tower catalog item, first check for required Provider in drop down selection, display error: 
Once Provider is selected, then check for Job Template drop down selection, display error:
Record saved when both are present:
====
For Orchestration Catalog Items, order of checks is reversed, first verify that Template has been selected in the drop down:
Then check for Provider to be selected:
Saved Orchestration Catalog Item once both Template and Provider have been selected:

Fix Ansible Tower Service Catalog new item creation

---

app/views/shared/buttons/_column_lists.html.haml

**More info:** https://github.com/ManageIQ/manageiq-ui-classic/pull/1376
See also: https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Column_lists_unnecessary_condition?expand=1#diff-fb2d45f8fceb60d60e1267c1d866e824R2

Delete unnecessary line of the code in column lists haml

---

app/assets/javascripts/miq_application.js

Chart tooltips should match table. It is not 100% fix, but it should work most of the time. And it should help identify broken cases. When values in the table are not consistent within themselves, they can't be consistent with chart tooltip.   
Screenshot
Before:
After:
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1564136
Enable C&U data collection in Configuration.
Select some Host/Vm/whatever with C&U data
Monitoring -> Utilization -> Click on Magnifying glass -> Compare Tooltip value to table
Repeat for different entity

Chart tooltips should match table

---

app/controllers/network_router_controller.rb
spec/controllers/network_router_controller_spec.rb

Replaced depricated function `find_id_with_rbac` with `find_records_with_rbac` in network router controller,
added test for delete_network_routers function
@romanblanco, @lpichler

Replaced deprecated function

---

app/helpers/application_helper/toolbar/physical_servers_center.rb

Keep consistency where toolbar buttons are always enabled and only its operations can be disabled depending on some logic.

Consistency on toolbar buttons for physical server list page

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller/ops_rbac_spec.rb

Refactoring method in ops_rbac.rb to use new RBAC call

---

app/controllers/physical_server_controller.rb
spec/controllers/physical_server_controller_spec.rb

Replaced rbac functions in provision method 
pleas review @KrecekDaniel

Refactoring provision method to use new rbac call

---

app/helpers/application_helper/toolbar/cloud_volumes_center.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1504209
Create backup and restore from backup actions were missing from the
volume list page. They were already on the detail/view page.
This commit adds them.

BZ1504209: Add backup create/restore to volume list actions

---

app/javascript/miq-component/helpers.js
app/javascript/packs/component-definitions-common.js

Component factory for mounting react components.
* Define react component in `app/javascript/packs/component-definitions-common.js`
```
import ComponentName from '../components/ComponentName'; // or other location
// simple definition
ManageIQ.component.addReact('ComponentName', ComponentName);
// with extra props
ManageIQ.component.addReact('ComponentName', props => <ComponentName {...props} />);
```
* Create root element in template and call factory:
```
// explicit props definition
#root-element{data-first-props => "something",
data-second-prop => @rubyObject.property}
//or create props structure from object:
#root-element{:data => {:first-prop => "something", :second-prop => @rubyObject.property}}
javascript:
ManageIQ.component.componentFactory('ComponentName', '#root-element', …
```

Added React component factory.

---

app/controllers/report_controller.rb

When editing folders in a report menu editor, the tree node is being unselected and so it's not clear what is being edited. With this change this will be displayed on the right side, see the screenshots.
**Before:**
**After:**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1550641

Display what is being edited in the report menu editor

---

app/controllers/miq_ae_customization_controller/dialogs.rb

Original fix was made in https://github.com/ManageIQ/manageiq-ui-classic/pull/3766
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532272
@skateman can you please test, instructions to recreate are in BZ, slightly modified see below:
Appliance : https://10.8.199.206/
Edit dialog :dynamic_refresh.
Edit field name: "Location" entry point .Select Location in path.
Now edit field name"What's Inside?" and click on entry point .
Location will be selected and Apply is greyed out .
If you want to select the same path "location" again .
Click on any other entry point like "peek" and then location again and now the "Apply " button is enabled.

[FINE] - Follow up fix to address another condition

---

app/decorators/ext_management_system_decorator.rb
app/decorators/host_decorator.rb
app/decorators/manageiq/providers/cloud_manager_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/manageiq/providers/infra_manager_decorator.rb
app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
app/decorators/miq_template_decorator.rb
app/decorators/physical_server_decorator.rb
app/decorators/vm_or_template_decorator.rb

As each quad has its separate tooltip now, the ones related to the `type` can be properly "translated" using `ui_lookup`.
@miq-bot add_label internationalization, GTLs

Wrap type-based tooltips in quadicons with ui_lookup

---

app/controllers/infra_networking_controller.rb
spec/controllers/infra_networking_controller_spec.rb

Since we introduced the `PhysicalSwitch` class, the good old `Switch` is not behaving on the infra networking screens as before. When clicking on a switch node under `Infrastructure -> Networking` it throws a `uninitialized constant ApplicationHelper::Toolbar::XInfraNetworkingManageiq` error.
By setting the `rec_cls` to the `base_model` of the record's class, this problem disappears.
Depends on: https://github.com/ManageIQ/manageiq/pull/17416
@miq-bot add_label bug, gaprindashvili/no, pending core

Render the correct toolbar for the infra networking switches

---

spec/controllers/ops_controller/ops_rbac_user_spec.rb
spec/support/ops_user_helper.rb

~~Depends on https://github.com/ManageIQ/manageiq/pull/17397~~
Related to #3894, #3767, #3345 and #3714.
There's been too many problems recently with the code to add/edit a user in the UI - I've written specs for each of those problems (including a pending spec for the problem being fixed in #3894).
(Creating a new spec file, since `ops_controller/ops_rbac_spec.rb` is already too long and only deals with tenant, while user/group stuff is either untested or mixed together with the rest in `ops_controller_spec.rb`)
Cc @lgalis , @ZitaNemeckova

OpsRbac - specs for user add/edit

---

app/assets/stylesheets/remote_console.scss
app/views/shared/_remote_console_footer.haml

The `footer` styling for remote consoles is conflicting with the [new login screen](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-social-account-two-column.html) provided by PatternFly. This extra class should solve the problem and unblock @epwinchell.
@miq-bot add_label gaprindashvili/no, formatting/styling

Add an extra .remote-console class on the remote console footer

---

app/helpers/ems_cloud_helper/textual_summary.rb
app/helpers/ems_network_helper/textual_summary.rb

Google provider doesn't have `:description` anymore but may have `provider_region`. Textual summary will try to get `:description` from `@record` and fail.
Introduced by https://github.com/ManageIQ/manageiq-providers-google/pull/52
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1571303
To reproduce:
Make sure you have `ManageIQ::Providers::Google::CloudManager` or `ManageIQ::Providers::Google::NetworkManager` with `provider_region` **not** set to `nil`.
Go to summary page of said provider.
Before:
After:
Fix for master: https://github.com/ManageIQ/manageiq-schema/pull/184
@miq-bot add_label bug, blocker, compute/cloud, networks

[GAPRINDASHVILI] Check @record has description method before using provider_region row

---

app/helpers/application_helper.rb
app/helpers/reactjs_helper.rb
app/views/shared/_quadicon.html.haml

Add a =react helper  …
```
= react 'Foo'
```
creates an empty div, and initializes a react Foo component on it
params can be passed as a hash: `= react 'Foo', {:bar => 5}`
under the hood, this uses `ManageIQ.component.componentFactory`

React helper

---

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
app/views/layouts/angular/_ansible_form_options_angular.html.haml

Selection of a dialog is required for playbook catalog
Links 
-----------
https://bugzilla.redhat.com/show_bug.cgi?id=1574204
Make sure the issue in this BZ is also fixed, as I reverted the changes made in https://github.com/ManageIQ/manageiq-ui-classic/pull/3413.
1. Make sure a dialog is required when adding a Playbook Catalog Item
2. Make sure the radio button for switching between a new and existing dialog is displayed when editing an existing catalog item.
After:

Selection of a dialog is required for a playbook catalog item 

---

app/controllers/application_controller/compare.rb

Change text color to blue for different columns when displaying Drift for VM

---

app/helpers/application_helper.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1558620
---
Add missing **view selector** to Block and Object Storage Managers under _Storage -> Block/Object Storage -> Managers_.
**Before:**
Block Storage Managers, no View Selector:
Object Storage Managers, no View Selector:
**After:**
Block Storage Managers, Grid View:
Block Storage Managers, Tile View:
Block Storage Managers, List View:
Object Storage Managers, Grid View:
Object Storage Managers, Tile View:
Object Storage Managers, List View:

Add view selector to Block/Object Storage Managers

---

app/controllers/ops_controller/settings/label_tag_mapping.rb

Followup to #3697.
`MAPPABLE_ENTITIES` keys were actual model names at some point in the past, but now include arbitrary strings (eg. "Image", "VmAzure").
`MAPPABLE_ENTITIES` values are currently the provider, which helps "compute" 2 things we really need: category prefix, and how to call it in UI — but there are enough exceptions by now that it's cleaner to simply hardcode the actual values than follow the logic...
@miq-bot add-label refactoring

tag mapping UI: Hardcode arbirtrary values instead of "computing" 

---

app/controllers/application_controller.rb
app/controllers/configuration_controller.rb
app/controllers/ems_common.rb
app/controllers/physical_switch_controller.rb
app/decorators/physical_switch_decorator.rb
app/helpers/application_helper.rb
app/helpers/application_helper/listnav.rb
app/helpers/application_helper/toolbar/physical_switch_center.rb
app/helpers/application_helper/toolbar/physical_switches_center.rb
app/helpers/application_helper/toolbar_chooser.rb
app/helpers/ems_physical_infra_helper/textual_summary.rb
app/helpers/physical_switch_helper.rb
app/helpers/physical_switch_helper/textual_summary.rb
app/helpers/quadicon_helper.rb
app/presenters/menu/default_menu.rb
app/services/ui_service_mixin.rb
app/views/configuration/_ui_1.html.haml
app/views/layouts/listnav/_physical_switch.html.haml
app/views/physical_switch/show.html.haml
app/views/physical_switch/show_list.html.haml
config/routes.rb
product/views/PhysicalSwitch.yaml
spec/controllers/physical_switch_controller_spec.rb

Adds the physical switches show page.
**Depends on:**
- ~~[https://github.com/ManageIQ/manageiq/pull/17216](https://github.com/ManageIQ/manageiq/pull/17216)~~

Adding physical switches list and summary pages

---

app/controllers/application_controller/compare.rb

**What:**
Change text for columns (for expanded view) when displaying Compare for VMs/ Templates/Hosts by:
- removing unnecessary tooltip from _compare_add_txt_col_ method
- updating calling the method in other places according to the method's change
- removing bold text style from the columns
---
**Before:**
Comparing three VMs or Templates:
Comparing three Hosts/Nodes:
**After:**
Comparing three VMs or Templates:
Comparing three Hosts/Nodes:
---
**Why:**
- to reach more readable output
- to achieve consistency with displaying Drift for VMs/Hosts:

Change text for columns when displaying Compare for VMs/Templates/Hosts

---

app/decorators/physical_switch_decorator.rb
app/helpers/physical_switch_helper/textual_summary.rb

The way we handle Switches ports has changed in the past weeks in the following PR:
https://github.com/ManageIQ/manageiq/pull/17268
This code updates the UI to properly show Physical Network Ports.

Update switch ports relationship

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

refactoring methods in catalog_controller_spec.rb

---

spec/controllers/ems_block_storage_controller_spec.rb
spec/controllers/ems_object_storage_controller_spec.rb

Add spec tests to check the toolbars to be rendered on Block/Object Storage Managers pages.
See: https://github.com/ManageIQ/manageiq-ui-classic/pull/3871 (Add view selector to Block/Object Storage Managers )

Add spec tests to check rendered toolbars on Block/Object Storage Managers

---

app/controllers/application_controller/filter.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1567416
---
Fix selecting _ALL_ filter and changing it to _Default_ on _Physical Infra_ page
(in _Compute -> Physical Infrastructure -> Servers_), also on _Hosts_ page.
1. Go to 
_Compute -> Physical Infrastructure -> Servers_ or
_Compute -> Infrastructure -> Hosts_
2. In accordion, select a filter **other than** the _ALL (Default)_
3. Click on the _Set Default_ button to set the selected filter as Default
4. Click on the _ALL_ filter again
=> nothing happened, previously selected filter remained applied and it was not possible to set _ALL_ back to _ALL (Default)_
Step 4 from steps to reproduce:
**Before:**
**After:**
---
**Details:**
Removing unnecessary line of the code fixed the bug. The problem was that …

Fix selecting ALL filter and changing it to default on Physical Infra

---

app/controllers/ops_controller/settings/common.rb
app/views/ops/_all_tabs.html.haml
spec/controllers/ops_controller/settings/common_spec.rb

Allow edit of advanced config setting for all servers. Made changes so this code can be used to edit Zone/Region config settings in future.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536524
Dependent on core PR https://github.com/ManageIQ/manageiq/pull/17406 
before no Advanced tab on Remote server level:
after:

Made "Advanced" tab visible for all Server nodes.

---

app/controllers/automation_manager_controller.rb
app/controllers/provider_foreman_controller.rb
app/presenters/tree_builder_automation_manager_providers.rb
app/presenters/tree_builder_configuration_manager.rb

Let's clean up nonsense Rbac requests for `:match_via_descendants` since `ConfiguredSystem::ConfiguredSystem` and `ConfigurationScript::ConfigurationScript` (in one bonus extra case for free) are not valid relations. This only causes `evm.log` warning pollution like:
```
WARN -- : MIQ(Rbac::Filterer#lookup_method_for_descendant_class) could not find method name for ConfiguredSystem::ConfiguredSystem
```
For valid relations, please consult [Rbac's filterer.rb](https://github.com/ManageIQ/manageiq/blob/9d5ed08d602381d407802cde3375ef01261b7931/lib/rbac/filterer.rb#L92)
Partially fixes: [bug 1565266](https://bugzilla.redhat.com/show_bug.cgi?id=1565266)
Related: https://github.com/ManageIQ/manageiq/pull/17430
@miq-bot add_label rbac, bug

Remove :match_via_decendants for ConfiguredSystem::ConfiguredSystem

---

app/helpers/application_helper/title.rb
app/views/layouts/login.html.haml
spec/helpers/application_helper/title_spec.rb

Setting `@page_title` is a mechanism to provide custom `<title>` value. 
For most of ops ui, this is computed from the current `@layout`, but that is not really pluggable and does not make sense for plugins.
So, we have `@page_title` and end up doing `product_title + title` - and calling it as `productized_title(_(": Login"))`.
---
This updates `productized_title` to join the provided title with ": " automatically - so that we don't have to randomly `@page_title = ": #{_('Migration')}"` in v2v.
Instead, the line will be `@page_title = _('Migration')`.
#3963: gaprindashvili yes because we need this for v2v to be able to use manageiq layouts instead of creating its own
Cc @mzazrivec , @martinpovolny

page_title - don't require leading ": " in @page_title

---

spec/controllers/ems_block_storage_controller_spec.rb
spec/controllers/ems_object_storage_controller_spec.rb

This PR updates the spec tests to check the toolbars to be rendered on Block/Object Storage Managers pages.
See: https://github.com/ManageIQ/manageiq-ui-classic/pull/3871 and https://github.com/ManageIQ/manageiq-ui-classic/pull/3948

Update spec tests to check rendered toolbars on Block/Object Storage Managers

---

app/assets/stylesheets/patternfly_overrides.scss
app/views/shared/_compare_header_expanded.html.haml

This PR aligns the quadicons at the bottom of the table header. It also centers them horizontally .
Old
New

Fix alignment of quadicon in Compare View

---

app/assets/javascripts/miq_angular_application.js

This is dependent upon https://github.com/ManageIQ/ui-components/pull/295. With the ui-components PR, the dialog-user component will be using a new custom directive to handle an odd case of when options within a drop-down change but the values do not (ex: [["1", "one"], ["2", "two"]] changing to [["1", "uno"], ["2", "dos"]]).
https://bugzilla.redhat.com/show_bug.cgi?id=1574668
@himdel This is all I need to do for the classic-ui side, yes?

Utilize a new 'miq-select' directive for dialog fields

---

app/javascript/http_api/http.js

introduced in #3662 for the purposes of React code that needs to talk to rails controllers (json, but not API)
`API.*` is not supposed to send cookies (and doesn't),
but `http.*` needs to.
Adding: `credentials: 'include'` to achieve just that.
https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: needed for v2v in gaprindashvili (but not adding gaprindashvili/yes as this can not be directly backported) - will fix once the backport PR is ready

http - send cookie

---

app/views/chargeback/_cb_rate_edit.html.haml

**What:**
After some talk with @lpichler, I am adding **search ability** for _Currencies_ while adding/editing a _Chargeback Rate_. 
**Related task:**
https://bugzilla.redhat.com/show_bug.cgi?id=1498951
**Why:**
There will be at least 20 currencies added in the _Currencies_ drop down so it is good to be able to search through the available currencies.
**Before:**
**After:**

Add Search to Currencies' drop down when adding/editing Chargeback Rate

---

app/controllers/service_controller.rb

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1545296
Make view selector of _All Generic Objects_ page work, when attaching GO to a service
and navigating to _Services > My Services_ > service with GO and clicking on _Instances_
from _Generic Objects_ table (where we can change the view from tile also to grid/list).
Right before changing the view in  _All Generic Objects_ page (now default Tile view):
**Before:** (after clicking on Grid/List view from _All Generic Objects_ page)
**After:**

Make view selector of All Generic Objects page work

---

app/controllers/application_controller/miq_request_methods.rb
app/views/miq_request/_pre_prov.html.haml
app/views/miq_request/_pre_prov_images.html.haml
app/views/miq_request/_prov_vm_grid.html.haml

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1399378
On pre provisioning screen, hide _"Hide Deprecated"_ checkbox and remove _"Deprecated"_ column from the table when user is submitting a provisioning request for **Infrastructure** VM, as those (the checkbox and the column) apply only to **_cloud_** provisioning. Cloud provisioning remains unchanged.
---
**Before:**
**After:**

Hide "Hide Deprecated" checkbox and remove "Deprecated" column when provisioning infra VM

---

app/controllers/ansible_credential_controller.rb
app/controllers/ansible_playbook_controller.rb
app/controllers/ansible_repository_controller.rb
app/helpers/application_helper/toolbar_chooser.rb
spec/controllers/ansible_credential_controller_spec.rb
spec/controllers/ansible_playbook_controller_spec.rb
spec/controllers/ansible_repository_controller_spec.rb
spec/helpers/application_helper/toolbar_chooser_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1560482
---
**Problem:**
Incorrect tag page was opened for tagging Playbooks navigated through Repository summary page (of some repo under _Automation > Ansible > Repositories_) because `params[:pressed]` was not properly set ("ansible_repository_tag" instead of "embedded_configuration_script_payload_tag") and then also wrong parameter went to `tag` method. This was caused by **wrong choosing of toolbar** for the page - this was caused here: https://github.com/hstastna/manageiq-ui-classic/blob/master/app/controllers/ansible_repository_controller.rb#L14
**Solution:**
The right toolbar for Playbooks has to be chosen, when navigating to Playbooks through Repository summary page.
Navigating to Playbooks through Repository summary page: …

Fix opening incorrect tag page, opened for Ansible Playbooks navigated through Repository summary page

---

app/views/report/_column_lists.html.haml

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1498150
---
Add ability to search through the _Available Fields_ while adding/editing report in _Cloud Intel > Reports > Reports_.
**Before:** (needed to scroll through the fields)
**After:** (open the drop down, simply click on the fields you want to select, type what you look for) 
Search form displays above the fields after adding `selectpicker` class and searching works well (then we have multiselect drop down which we already know from other places, for example when choosing multiple Groups of a User).

Add ability to search through the available fields while editing report

---

app/controllers/service_controller.rb
spec/controllers/service_controller_spec.rb

**fixing issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3261
**more info:** https://github.com/ManageIQ/manageiq-ui-classic/pull/3395
Fix displaying services after applying a filter and clicking on an other node in tree (_Active/Retired Services_ folder), in _Services > My Services_ page so that Active/Retired services **without filtering** are displayed.
---
**Details of a problem:**
There is an issue in _My Services_ page, after applying/clicking on some filter from _Global/My Filters_ in accordion: if we click on an other node in tree, for example _Active Services_ (or _Retired Services_), services are not displayed properly: there is inconsistency between displayed services and the title of the page, filter is applied on Active or Retired services, not on all of the …

Fix displaying services after applying a filter (2)

---

app/helpers/quadicon_helper.rb
spec/helpers/quadicon_helper_spec.rb

The [demodulization](https://github.com/ManageIQ/manageiq-ui-classic/pull/3699/files#diff-6525cb9600835fcc2ba062fde39a2292R73) introduced by @saulotoledo breaks the quadicon settings key selection for templates. By restricting the demodulization to the models starting with `Physical` this issue can be solved easily. However, the whole quadicon settings key logic should be refactored in the future.
**Before:**
**After:**
@miq-bot add_label bug, gtls, gaprindashvili/no

 Restrict quadicon class demodulization for Physical* records only

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller/ops_rbac_user_spec.rb

Use update_attributes for saving a user's groups. Alternative for https://github.com/ManageIQ/manageiq-ui-classic/pull/3894
Links 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1574634
Specs here: https://github.com/ManageIQ/manageiq-ui-classic/pull/3916

Use update_attributes for saving a user's groups

---

app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
app/controllers/mixins/actions/vm_actions/reconfigure.rb
app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
app/views/vm_common/_reconfigure.html.haml
spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js

With this commit we add support to reconfigure VM hardware for VMware vCloud provider. Different configuration is needed for VMware vSphere (infra) than for VMware vCloud (cloud) so we cannot rely on `vm.vendor = vmware` attribute anymore, which is common to them both... Instead, we rely on VM class name.
Also, there seems to be a bug in ruby controller which tries to render flash message AFTER redirect was invoked. This results in ugly rails crash. Solved by removing the flash rendering part.
Video: http://x.k00.fr/reconfigure
Depends on: https://github.com/ManageIQ/manageiq-providers-vmware/pull/231
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1572086

Support VM Reconfigure for VMware vCloud provider

---

product/views/Host.yaml

The compliances is an ever growing table, and with how Rbac works, this means that the table is joined and usually has the references applied to it prior the query being executed.  Because there are so many compliance records after a period of time for a given host, this can cause the query to explode because it is executed with a LEFT JOIN on that table, along with the tags table and ext_management_system tables.
This means that even just querying against 20 hosts that has 14000 compliance records associated with them, along with 17000 taggings can end up causing a query with over 2 million rows returned, with 60+ columns per row.  That data returned from postgres ends up being multiple Gigs in size.
For the best performances, there are changes to the `last_compliance_status` (see links …

Remove compliances include from Host.yaml

---

app/assets/stylesheets/patternfly_overrides.scss

when another modal window is visible (like the v2v wizard),
when the error modal appears, it appears under the existing modal - not visible
overriding the z-index value so that the error is always visible
---
Testing: go to Compute > Migration, Create Infrastructure Mapping
In console, run: `sendDataWithRx({ serverError: {} });`
Before - nothing will be visible until you close the wizard modal.
After:
(obviously real errors are not undefined :))
---
https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: needed so that v2v errors don't get ignored when in the wizard

Error modal - ensure visibility over other modals

---

app/controllers/chargeback_controller.rb

**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/3961
Fix _Save_ button which was not responding for **Currencies' changes** while editing Chargeback
Rate, under _Cloud Intel > Chargeback > Rates_ accordion > _Compute/Storage Chargeback Rates_.
Original Chargeback Rate (just started editing; see the Currencies):
The currency was changed and Save button was enabled:
**Before:**
Currency changed back to the original value and Save button still enabled which is wrong:
**After:**
Currency changed back to the original value and Save button was disabled which is right:
1. Go to _Cloud Intel > Chargeback > Rates_ accordion > _Compute/Storage Chargeback Rates_
2. Click on some rate or select it by checking the checkbox
3. Choose _Edit the selected …

Fix Save button which wasn't responding while editing Chargeback Rate

---

app/helpers/ems_network_helper/textual_summary.rb

With this commit we display relation (with object count) at Network Manager details page. Clicking on relation redirects user to a `display=cloud_tenants` page. Find screenshots below.
Screenshot of Network Manager details page:
Screenshot of a page that renders when user clicks on "Cloud Tenants" relation:
Video: http://x.k00.fr/cloudtenants
Related PR (but not blocking): https://github.com/ManageIQ/manageiq-providers-nuage/pull/92
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574903

Display Cloud Tenants relation at Network Manager

---

app/controllers/application_controller/session_size.rb

Replace hard-coded SESSION_LOG_THRESHOLD and SESSION_ELEMENT_THRESHOLD
with settings that can be configured by a user.
For organizations where reports contain potentially thousands of email addresses, overcoming the default 100kb limit is easy, and warning messages are displayed like so for every report:
```
MIQ(report_controller-x_button): Session object size of 182.9 KB exceeds threshold of 100 KB
```
This PR replaces the hard-coded default of 100kb to a configurable parameter (also defaulting at 100kb).  That makes this PR reliant on the configuration change in this PR against the core repo:
https://github.com/ManageIQ/manageiq/pull/17334

Add reporting session threshold options for logging

---

app/controllers/mixins/ems_common_angular.rb

If the user didn't provide a token for kubevirt provider, the previous
token should be kept instead of using the default token.
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/70

Do not override kubevirt token with default token

---

lib/tasks/manageiq/ui_tasks.rake

This better supports the `ActiveSupport::Inflectors` that are set by both the main app and any asset engines that are pulled in by the `webpack` tasks.
The PR creates two new tasks in the `:ui` namespace:
* `rake ui:load_app_inflectors`
* `rake ui:load_asset_engine_inflectors`
The first loads the inflectors from the main application, and the second pulls in any inflectors from the `asset_engines` that are present.  The `asset_engine` inflector task does assume the file lives in the `config/initializers/inflections.rb`, so that is sort of being set as the standard as part of this PR.
Also, minor addition:  The `asset_engines` method is now memoized.  Your welcome.  #smugNickIsSmug
Links
-----
* This PR is to support the `miq_v2v_ui_plugin` rename to `manageiq-v2v`, which is currently in …

Better inflector support for ui rake tasks and asset plugins

---

app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
app/controllers/mixins/actions/vm_actions/reconfigure.rb
app/views/vm_common/_reconfigure.html.haml

With this commit we extend reconfigure UI to support what we need for vCloud: addition/deletion of NICs that are connected to cloud networks.
Current UI assumed that only vLan (i.e. network) has to be picked when creating new NIC. However, for vCloud we also need to specify new NIC index hence we extend the form a little.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1572086
Depends on: https://github.com/ManageIQ/manageiq-providers-vmware/pull/272
Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/3854
Video: http://x.k00.fr/nicreconfigure
@miq-bot add_label enhancement,gaprindashvili/yes,pending core

Network adapter reconfiguration for vCloud provider

---

app/helpers/textual_mixins/textual_devices.rb
spec/helpers/textual_mixins/textual_devices_spec.rb

Display port group for VM instances
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1561609

Display port group for VM instances

---

app/views/ops/_rbac_tenant_details.html.haml

ping @ZitaNemeckova 
* fix a regression causes by the TextualSummary componentization PR
* fix broken formatting
* there are more issues probably related to the use of API and angular in editing tennants. Namely the left tree disappears on {new,edit}/save or edit/cancel. There's a whole page reload, that should not be....

Fix textual summary display in tenants.

---

app/controllers/ops_controller/settings/common.rb
app/helpers/ops_helper.rb
app/views/ops/_all_tabs.html.haml
app/views/ops/_settings_advanced_tab.html.haml
spec/controllers/ops_controller/settings/common_spec.rb

Exposed 'Advanced' tab for Region/Zone nodes.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1082155
Before:
After, Note has been updated on the Server level. Exposed Advanced tab on Region and Zone level:
Dependent upon core PR: Core PR: https://github.com/ManageIQ/manageiq/pull/17458

Ability to see/save Config settings for Region and Zone records.

---

app/assets/javascripts/services/event_notifications_service.js

Somehow the ordering of the notifications was reversed when requesting old ones from the API, fixing it.
https://bugzilla.redhat.com/show_bug.cgi?id=1583821

Render notifications fetched from the API in the correct order

---

app/helpers/textual_mixins/textual_devices.rb
spec/helpers/textual_mixins/textual_devices_spec.rb

Add the VMWare Virtual  Ethernet Card model type to the VM summary
Links 
----------
https://bugzilla.redhat.com/show_bug.cgi?id=1583017

Add the VMWare Virtual  Ethernet Card model type to the VM summary

---

app/helpers/ops_helper.rb
app/views/ops/_settings_advanced_tab.html.haml

- we should not do string interpolation in gettext
- we should not do string concatenation in UI strings
- similar condition was used twice in two routines

String & gettext fixes in advanced tab warning

---

app/decorators/manageiq/providers/container_manager_decorator.rb

The quadicon for container provider introduced some inconsistency compared with other provider quads. The top-right quad displays an icon based on the data collection is suspended for the given provider or not. As we're extending this suspend feature to other providers and planning to use the bottom-right quad for displaying this info on each one, this would cause some redundancy for the container provider quadicons.
So I'm proposing to use the top-right quad for container providers more consistently with the other provider quads and display in it the number of containers for the given provider. Analogously to the infra provider displays the number of VMs in the same quad.
**Before:**
**After:**
@miq-bot add_label gaprindashvili/no, GTLs, compute/containers
@miq-bot add_reviewer …

Display number of containers on the top right quad of container prov

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

Fixes mangeiq-ui-classic master failures
Introduced by https://github.com/ManageIQ/manageiq/pull/17444
Before:
```
1) ReportController#schedule_edit reset rbac testing
Failure/Error: users_in_current_groups = User.with_current_user_groups.distinct.sort_by { |u| u.name.downcase }
NoMethodError:
undefined method `with_current_user_groups' for #<Class:0x000000000a44fa98>
2) MiqPolicyController::Alerts test click on toolbar button alert edit
Failure/Error: expect(response.status).to eq(200)
expected: 200
got: 500
3) MiqPolicyController::Alerts test click on toolbar button alert copy
Failure/Error: expect(response.status).to eq(200)
expected: 200
got: 500
4) MiqPolicyController::Alerts alert edit #alert_build_edit_screen it should select correct record …
```

Use with_groups instead of with_current_user_groups

---

app/assets/javascripts/miq_api.js

This is a gaprindasvhili version of #3662 and #3978.
---
Differences:
The master change lives under `app/javascript`, written in ES6, and refactored so that the http vs API parts are much more separate. For gaprindashvili, leaving in ES5 with the minimal amount of changes to support both.
Additional difference: changes that make the error modal distinguish between API and http requests were not backported, this means `http` access errors will appear as API errors in the error modal - this is just about the modal title, the URL fits.

[GAPRINDASHVILI] API transformRequest support + http service

---

app/controllers/application_controller/ci_processing.rb
app/helpers/application_helper.rb
app/helpers/application_helper/button/generic_feature_button.rb
spec/controllers/application_controller/ci_processing_spec.rb
spec/controllers/vm_infra_controller_spec.rb
spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb

- In this PR I'm introducing a new generic method `generic_button_operation` that should replace all other methods handling button operation in following PRs.
- In this PR, the method `vm_button_operation_internal` is removed with all the related methods as an example

Generalizing methods for button operation handling

---

app/decorators/manageiq/providers/cloud_manager_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb

I probably forgot to delete this, the right way of setting the policy shield is right below the deleted lines.
@miq-bot add_label bug, gaprindashvili/no, GTLs, compute/containers

Fix wrongly displayed policy shield on container & cloud provider quads

---

app/decorators/manageiq/providers/physical_infra_manager_decorator.rb

Missed to clean this up, doing it now :scissors: :toilet: :fire: 
@miq-bot add_label cleanup

Do not inherit physical infra decorator from ems decorator

---

app/decorators/manageiq/providers/network_manager_decorator.rb

There was no separate decorator specified for `Manageiq::Providers::NetworkManager` so it was using its parent's `ExtManagementSystemDecorator`. This caused the top left and right quadrants of their quadicons to be unusable and their single icon to be empty.
To make this more consistent with other provider quadicons, I am proposing to display the **number of cloud networks on the top-left** and the **number of security groups on the top-right** quadrant. Thanks to @himdel I was also able to add tooltips for these quadrants, so this might need a :+1:  from @mzazrivec because of the i18n.
I also changed the single icon to be the fileicon instead of the nonexisting fonticon.
**Before:**
**After:**
@miq-bot add_label bug, gaprindashvili/no, GTLs, networks
@miq-bot add_reviewer @tumido …

Add a separate decorator for Network Providers

---

app/assets/javascripts/dialog_field_refresh.js
spec/javascripts/dialog_field_refresh_spec.js

This is an issue that was solved via https://github.com/ManageIQ/ui-components/pull/295 for Gaprindashvili and later versions, but since Fine does not use the ui-components repo, nor does it use the new dialog-user component, it had to be addressed differently. The `selectpicker('refresh')` line needs to be ran after the values for the dialog field have been updated, not before.
https://bugzilla.redhat.com/show_bug.cgi?id=1581387
@miq-bot add_label bug, blocker
@d-m-u Can you give it a quick 👀?
@h-kataria If you think someone else should be assigned to this instead please let me know!

[FINE] Ensure dropdown gets selectpicker refreshed after values set

---

app/decorators/manageiq/providers/kubernetes/container_manager_decorator.rb
app/decorators/manageiq/providers/openshift/container_manager_decorator.rb

Decorator inheritance has to be destroyed with :fire: :fire: as it is not *The Right Way&trade;*. The icons are already defined using the `image_name` property in `ManageIQ::Providers::ContainerManagerDecorator`.
@miq-bot add_label cleanup, gaprindashvili/no, GTLs

Delete redundant openshift/kubernetes provider decorators

---

app/assets/stylesheets/application.css
app/assets/stylesheets/physical_infra_topology.scss

- Set different colors for different physical components on topology view;
__Goal__
With a great number of components on topology is pretty confuse to distinguish each component type, with different colors we improve the consume of the data on this page.

Setting different colors for physical infra components on topology view

---

app/decorators/vm_decorator.rb

There's a separate `MiqTemplateDecorator` for templates, so :toilet: :droplet: 
@miq-bot add_label GTLs, cleanup, gaprindashvili/no

Rename VmOrTemplateDecorator to VmDecorator

---

app/helpers/cloud_network_helper/textual_summary.rb
app/helpers/ems_network_helper/textual_summary.rb
app/helpers/floating_ip_helper/textual_summary.rb
app/helpers/load_balancer_helper/textual_summary.rb
app/helpers/network_port_helper/textual_summary.rb
app/helpers/security_group_helper/textual_summary.rb

Fixes links and labels for Parent Cloud provider.
Partial fix for https://github.com/ManageIQ/manageiq-ui-classic/issues/4013

Fix parent ems links in textual summaries.

---

app/views/layouts/exp_atom/_edit_tags.html.haml
spec/controllers/ops_controller/ops_rbac_spec.rb

Reload classifications when adding or editing the tag expression for groups
Depends on https://github.com/ManageIQ/manageiq/pull/17465
Links 
--------
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1579867
Use the :no_cache option added in https://github.com/ManageIQ/manageiq/pull/17465 in order for the new tags added to be displayed in the expression drop-down, rather than the cached list of tags.

Reload classifications when adding or editing the tag expression for groups

---

app/decorators/manageiq/providers/infra_manager_decorator.rb

Inheritance is an evil that needs to be banished from the world of decorators.
@miq-bot add_label cleanup, GTLs, gaprindashvili/no, compute/infrastructure

InfraManagerDecorator should not inherit from EMS decorator

---

app/decorators/miq_template_decorator.rb
app/decorators/vm_decorator.rb
app/helpers/quadicon_helper.rb

Instead of using the `svg/os-unknown.svg` we should use the `pficon pficon-uknown` fonticon.

Use pficon-unknown fonticon for unknown Operating Systems in quads

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/controllers/mixins/ems_common_angular.rb
app/views/layouts/angular-bootstrap/_endpoints_for_url.html.haml
app/views/layouts/angular/_multi_auth_credentials.html.haml
spec/controllers/ems_cloud_controller_spec.rb
spec/controllers/mixins/ems_common_angular_spec.rb
spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js

Added a new `Endpoint URL` optional field in AWS endpoints as shown in the screenshot.
Depends on https://github.com/ManageIQ/manageiq-providers-amazon/pull/444
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/3907

Add a new "Endpoint URL" field in AWS endpoints

---

app/decorators/switch_decorator.rb

Fonticon is defined, we don't need the fileicon 

Drop fileicon for NetworkSwitchDecorator

---

app/decorators/service_resource_decorator.rb

There's a fonticon, so :scissors: :scissors: :scissors: :scissors: :scissors: 

Drop fileicon for ServiceResourceDecorator

---

app/assets/images/svg/vendor-cinder.svg
app/assets/images/svg/vendor-swift.svg
app/controllers/application_controller.rb
app/controllers/configuration_controller.rb
app/decorators/manageiq/providers/storage_manager_decorator.rb
app/helpers/quadicon_helper.rb
app/views/configuration/_ui_1.html.haml

The cinder/swift storage managers had no proper fileicons, so I symlinked openstack for both of them. Under `My settings` there was no setting for their quad/single view, so that has been added.
The logic behind the single/quad selection and its administration is getting really out of hand, I am willing to fix this in a followup PR. The plan is to rename the configuration keys to be able to get rid of the big case statement under `QuadiconHelper.settings_key` and integrate better with RBAC.
There was no decorator for storage managers, so the `ExtManagementSystemDecorator` was trying to show the number of hosts in the top left quadrant. I created a decorator where (for now) the top left and top right quadrants are empty. I will need some ideas what to put there, maybe the provider guys can …

Make quadicons consistent and working for Block & Object Storage Providers

---

.travis.yml

followup to #3953
We updated the ruby version, but the travis excludes were not updated.
This means we are running specs on the javascript and others twice per PR.
This is inflating our travis runs from ~1:15hrs to 2:00hrs
Thanks all

travis: only run spec suite 1 time for javascript per PR

---

app/decorators/configuration_profile_decorator.rb

The `image_name` for `ConfigurationProfile` always returns 'configuration_profile' and it's identical to the fonticon, so why not use it directly?

Drop unnecessary fonticon from ConfigurationProfileDecorator

---

app/assets/javascripts/controllers/ems_keypair/ems_keypair_controller.js
app/controllers/mixins/ems_common_angular.rb
app/views/layouts/angular/_multi_auth_credentials.html.haml
spec/controllers/ems_infra_controller_spec.rb
spec/javascripts/controllers/ems_keypair/ems_keypair_controller_spec.js

Add authentication tab fro ssh credentials for rhev provider
This is part of the PRs that close https://bugzilla.redhat.com/show_bug.cgi?id=1561353
depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/251
and: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/256

Add support for ssh key pair credentials to rhv

---

app/decorators/generic_object_decorator.rb

We want to prefer fonticons if possible, and the `generic_object.png` is something we want to get rid of.

Do not use generic object fileicon if no picture specified

---

app/decorators/configured_system_decorator.rb

The `image_name` for `ConfiguredSystem` [always returns](https://github.com/ManageIQ/manageiq/blob/master/app/models/configured_system.rb#L94) `'configured_system'` and it's identical to the `fonticon`, so why not use it directly?

Drop the fileicon in ConfiguredSystemDecorator

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js

Fixes sporadic failures when waiting for API.post would not wait long enough for the flash message to get set.
Adding a return to the tested method so that we can wait for the actual promise.
The failure would look like
```
dialogUserController submitButtonClicked when the API calssages
Expected spy clearFlash to have been called.
stack@http://127.0.0.1:41615/__jasmine__/jasmine.js:1640:
buildExpectationResult@http://127.0.0.1:41615/__jasmine__/jasmine.j
expectationResultFactory@http://127.0.0.1:41615/__jasmine__/jasmine
addExpectationResult@http://127.0.0.1:41615/__jasmine__/jasmine.js:
addExpectationResult@http://127.0.0.1:41615/__jasmine__/jasmine.js:
http://127.0.0.1:41615/__jasmine__/jasmine.js:1564:32
http://127.0.0.1:41615/__spec__/controllers/dialog_user/dialog_user:53
```
or
``` …
```

dialogUser spec - fix sporadic spec failures

---

app/presenters/tree_builder_vms_and_templates.rb

Passing a class as a value in an Active Record query does not work when I test it in the console.
But debugging this code it seems to work fine with both values.
Just feel better fixing the deprecated parameter for this method.
/cc @ZitaNemeckova I remember you and I worked on this original BZ.

fix deprecated passing class to AR notification

---

app/decorators/ext_management_system_decorator.rb

All the providers have their own decorators with their quadicon definitions, so here it is longer necessary :toilet: :scissors: :fire: 
@miq-bot add_label cleanup, gaprindashvili/no, GTLs

Remove the quadicon definition from the ExtManagementSystemDecorator

---

app/decorators/manageiq/providers/ansible_tower/automation_manager/job_decorator.rb

No longer needed, fonticon makes it obsolete :scissors: 

Drop fileicon for ansible jobs

---

app/decorators/manageiq/providers/ansible_tower/automation_manager/configuration_script_decorator.rb

Fileicon is no longer needed as we got a fonticon :scissors: 

Drop fileicon for configuration script decorator

---

app/decorators/lan_decorator.rb

There's a fonticon defined, we don't need the fileicon :scissors: 

Drop fileicon for LanDecorator

---

app/controllers/application_controller/ci_processing.rb

Continuation of changes done in https://github.com/ManageIQ/manageiq-ui-classic/pull/3660
Removing method `cluster_button_operation`, replaced by `generic_button_operation` mentioned in the PR above.
Links
* https://github.com/ManageIQ/manageiq-ui-classic/pull/3660

Removing obsolete method for cluster button action handling

---

app/decorators/manageiq/providers/automation_manager/authentication_decorator.rb
app/decorators/manageiq/providers/embedded_automation_manager/authentication_decorator.rb

No longer needed, fonticon replaces it completely :scissors: 

Drop fileicon from authentication decorators

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/assets/javascripts/services/miq_service.js
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
spec/javascripts/services/miq_service_spec.js

I'm unsure on why this is happening on 5.9.x versions, as I cannot reproduce the issue locally (screenshots from a 5.9.3 appliance), but this will fix it. Basically when a dialog loads, the values aren't showing up, and it looks something like this:
This is purely a UI problem, because the data that is coming from the backend is correct, and in the HTML the `<select>` tags all have the correct data and `<option>`s selected correctly.
After doing a `$('select').selectpicker('refresh')`, the values are shown correctly, and it looks something like this:
So, this just forces that refresh after the initialization stage. I also changed the `$onInit` method to no longer return a promise, but it doesn't matter because angular doesn't officially support returning a promise from the `$onInit` …

Force selectpicker refresh after dialog-user component initialization

---

app/decorators/configured_system_decorator.rb

Under `Configuration -> Management -> Configured Systems` the icons were missing from the grid view.
**Before:**
**After:**
@miq-bot add_label bug, gaprindashvili/no, GTLs, configuration management

Add missing single_quad definition for ConfiguredSystemDecorator

---

app/decorators/host_decorator.rb
app/decorators/manageiq/providers/cloud_manager_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/manageiq/providers/infra_manager_decorator.rb
app/decorators/manageiq/providers/network_manager_decorator.rb
app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
app/decorators/manageiq/providers/storage_manager_decorator.rb
app/decorators/miq_template_decorator.rb
app/decorators/physical_server_decorator.rb
app/decorators/vm_decorator.rb
app/helpers/quadicon_helper.rb

I'm getting rid of the `100/shield.png` references and also moving the shield definition into the `QuadiconHelper` as a constant so we will have it only on a single location.
**Before:**
**After:**
@miq-bot add_label refactoring, graphics, gaprindashvili/no

Pull out policy shield icon to a constant and replace with fonticon

---

app/helpers/quadicon_helper.rb

Some methods are being used only from inside, so making them non-singleton.

Do not expose unnecessary QuadiconHelper methods as singleton methods

---

config/webpack/shared.js

because we no longer use angular 2+,
no need to have a workaround for it either.

Remove angular2+ webpack workaround

---

app/decorators/physical_server_decorator.rb
app/decorators/physical_switch_decorator.rb
app/helpers/quadicon_helper.rb

Shared code needs to go to the `QuadiconHelper` so we don't need to maintain it at two places. I am still looking into joining this together with the `machine_state` or `status_icon`. This change will allow us to replace fileicons with fonticons.
@miq-bot add_label gaprindashvili/no, compute/physical infrastructure, refactoring

Pull out health_state from physical infra decorators to the helper

---

app/decorators/configuration_profile_decorator.rb

Add single_quad definition for configuration profiles

---

app/assets/images/svg/vendor-redfish.svg
app/assets/images/svg/vendor-redfish_ph_infra.svg
app/controllers/ems_common.rb
app/controllers/mixins/ems_common_angular.rb
app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
app/views/layouts/angular/_multi_auth_credentials.html.haml

This pull requests contains UI modifications that are needed in order to be able to create new Redfish provider from the MIQ web UI.
/cc @gberginc @gtanzillo @Fryguy

Add Redfish provider creation dialog

---

app/helpers/service_helper/textual_summary.rb

We don't like PNG files anymore and there's a fonticon alternative for this.
@miq-bot add_label textual summaries, graphics, gaprindashvili/no

Replace orchestration-stack.png with its icon in textual summaries

---

app/decorators/miq_provision_decorator.rb

The `100/miq_request.png` is a big question mark, practically the same as `pficon-unknown`, so replacing.
@miq-bot add_label graphics, gaprindashvili/no

Replace miq_request.png with pficon-unknown in MiqProvisionDecorator

---

app/decorators/host_decorator.rb
app/decorators/manageiq/providers/cloud_manager_decorator.rb
app/decorators/manageiq/providers/container_manager_decorator.rb
app/decorators/manageiq/providers/infra_manager_decorator.rb
app/decorators/manageiq/providers/network_manager_decorator.rb
app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
app/decorators/manageiq/providers/storage_manager_decorator.rb
app/helpers/quadicon_helper.rb

After consulting with UX we decided to use the bottom-right quadrant of each provider quadicon to display the suspended status. For now this quadrant is being used to display the authentication status, however, when suspended this information is meaningless so we can safely reuse the same quadrant.
There's some inconsistency in container provider quads that would cause redundant displaying the same information in multiple quadrans, but that's [being addressed in a separate PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/4015).
First I had to generalize the `QuadiconHelper.status_img` method to return a hash instead of a string. This way it is possible to handle both fonticons and fileicons simultaneously. Then I added the condition for displaying the suspended icon (without a …

Display providers' suspended status in their quadicon

---

app/helpers/application_helper/button/ems_network.rb
spec/helpers/application_helper/toolbar/ems_networks_center_spec.rb

Nuage is somewhat special in a way it allows adding NetworkManager directly, without CloudManager. For all other providers such behavior is not feasible, therefore "Add New Network Manager" button should be hidden.
With this commit we make sure that the button is hidden unless config/permissions.yaml file contains entry allowing user to use Nuage provider:
```yaml
- ems-type:nuage_network
```
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1577888
@miq-bot assign @blomquisg 
/cc @djberg96

Hide "Add New Network Manager" unless Nuage is enabled

---

package.json

`patternfly-react` is a shared package across various plugins like v2v and now react-ui-components
Adding it here ensures that Classic UI is the single point of control for `patternfly-react` 
The `patternfly-react` entry in other repos is overridden with this change -- which is exactly what we want, as it resolves version difference nightmares.
Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/363

Add patternfly-react in ui-classic

---

app/decorators/registry_item_decorator.rb
manageiq-ui-classic.gemspec

We needed a new version of font-fabulous with the `ff-file-bin-o` icon, and this is a next fileicon to :scissors: 
@miq-bot add_label graphics, gaprindashvili/no

Use fonticons instead of fileicons in the RegistryItemDecorator

---

app/decorators/generic_object_definition_decorator.rb

Unnecessary image, there's a fileicon, so :scissors: :toilet: :fire: 
@miq-bot add_label graphics, gaprindashvili/no

Don't use generic object definition fileicon if no picture present

---

app/presenters/tree_node/node.rb

There are no more `png` images under `app/presenters/tree_node` and the ones in decorators are already prepended with `100/`.
@miq-bot add_label cleanup, gaprindashvili/no, trees

Do not try to prepend TreeNode images with 100/

---

app/views/catalog/_confirmation_modal.html.haml

When editing an Ansible `Catalog item`, on the `Retirement` tab there's a `Copy from Provisioning` button that opens a modal with a warning sign. The UX is just awful and it should be fixed, but now I'm only replacing the warning triangle PNG with a fonticon.

Use fonticon for the warning in catalog edit provision confirm modal

---

app/presenters/tree_builder_automate_simulation_results.rb
spec/presenters/tree_builder_automate_simulation_results_spec.rb

They're identical, but we no longer love PNGs.

Replace q.png with vendor-redhat.svg in the automate simulation tree

---

app/helpers/quadicon_helper.rb

Probably missed this when I was refactoring something in the area, it is completely replaced by the `policy_sim` method.

Remove unused compliance_img singleton method from QuadiconHelper

---

app/controllers/application_controller.rb
app/controllers/application_controller/current_user.rb
app/controllers/chargeback_controller.rb
app/controllers/configuration_controller.rb
app/controllers/report_controller.rb
app/controllers/report_controller/menus.rb
app/controllers/report_controller/saved_reports.rb
app/helpers/application_helper/button/miq_request_delete.rb
app/presenters/tree_builder_report_saved_reports.rb
app/views/layouts/_adv_search_body.html.haml
app/views/layouts/_adv_search_footer.html.haml
spec/controllers/report_controller/widget_spec.rb
spec/helpers/application_helper/buttons/miq_request_delete_spec.rb

The current ui code displays components based upon `admin_user?`
But in truth, it is hiding/showing reporting components.
So changing this over to `report_admin_user?` states the actual intent.
The dependent PR https://github.com/ManageIQ/manageiq/pull/17444 introduces a `miq_product_feature` for a report admin, so this could be asked (and so we could have less hardcoded admin checks)  
There is also one check for `request` admin checks - there are more of those over in the api code.
The depends upon:
- https://github.com/ManageIQ/manageiq/pull/17444
Targeting:
- https://bugzilla.redhat.com/show_bug.cgi?id=1090627
- https://bugzilla.redhat.com/show_bug.cgi?id=1545401

Use {report,request}_admin_user?

---

app/controllers/ops_controller/settings/common.rb
spec/controllers/ops_controller/settings/common_spec.rb

Default server never returns its zone in get_config so it has to be checked and set correctly.
Introduced by https://github.com/ManageIQ/manageiq/pull/17140 which is `gaprindashvili/no`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1584851
Administrator -> Configuration -> Settings -> Zones
Have a zone that has name alphabetically before `default`. This bug is only for `Zone.name == "default"` (see pics below).
Displays wrong zone (first one in dropdown)
Save button isn't active after changing zone
Displays correct zone
Save button is active after changing zone
@miq-bot add_label bug,  wip

Make sure @edit[:current].config[:server][:zone] is set

---

app/controllers/miq_request_controller.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1584172
Data was never copied from session to @options when miq_request/prov_field_changed?tab_id=* request was fired
Services -> Catalogs -> Catalog Items -> choose any item with Request Info -> click Request Info -> click any tab in Request Info
Before:
Console:
```
FATAL -- : Error caught: [NoMethodError] undefined method `[]=' for nil:NilClass
/manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:16:in `prov_field_changed'
/usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.7/lib/abstract_controller/base.rb:188:in `process_action'
```
After:
@miq-bot add_label bug, services

Fix Request Info for Catalog Items

---

app/assets/stylesheets/icon_customizations.scss

* Convert `content: <utf-8>` to `@extend <icon class>`
* Removed unnecessary spaces
* Comments moved closer to their reference

Clean up SASS rules for icon customizations

---

app/helpers/quadicon_helper.rb

All the SVG/PNG icons have a matching fonticon, so getting rid of them :scissors: :toilet: 

Convert health state and provider status quadrant icons to fonticons

---

app/helpers/application_helper.rb
app/helpers/ems_physical_infra_helper/textual_summary.rb
app/views/layouts/listnav/_ems_physical_infra.html.haml

- Enable PhysicalSwitches listing in Physical Infra Provider
- Display Physical Switches in Physical Infra Provider 'Relationships' field
The problems:
When trying to list the Physical Switches from a Physical Infra Provider (`/ems_physical_infra/:id?display=physical_switches`)
An error is returned
This happens because the application controller from the UI calls `paged_view_search`, which is a method from Search class inside ManageIQ core that, internally, uses the base model for the class passed. The result is that, instead of `PhysicalSwitch`, its parent `Switch` is called.

Fixing Provider PhysicalSwitches page summary show

---

package.json

`angular-mocks` has same version as other `angular` packages.
@miq-bot add_label test, gaprindashvili/no

Fix js spec related to widgets

---

app/assets/javascripts/services/alerts_center_service.js
app/views/cloud_topology/show.html.haml
app/views/container_topology/show.html.haml
app/views/infra_topology/show.html.haml
app/views/layouts/_tabs.html.haml
app/views/network_topology/show.html.haml
app/views/physical_infra_topology/show.html.haml
app/views/shared/views/_alerts_list.html.haml
app/views/shared/views/_show_alerts_overview.html.haml
app/views/static/deploy_containers_provider/deploy-provider-details-existing-vms.html.haml
app/views/static/deploy_containers_provider/deploy-provider-details-no-provider.html.haml
app/views/static/notification_drawer/notification-body.html.haml
app/views/static/wizard.html.haml

Prefixing all the things, based on [this guide](https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes) so we can update to the latest angular-bootstrap.

Prefix all angular-bootstrap directives with uib-

---

app/helpers/host_helper/textual_summary.rb
app/helpers/physical_server_helper/textual_summary.rb
app/helpers/physical_switch_helper/textual_summary.rb
app/helpers/textual_mixins/textual_power_state.rb
app/helpers/vm_cloud_helper/textual_summary.rb
app/helpers/vm_helper/textual_summary.rb

Unify the display of power state in textual summaries (detail screens).
Display a power state icon.
ping @terezanovotna, @Loicavenel

TextualSummary: unify power stated.

---

app/helpers/quadicon_helper.rb

Bad hash keys, sorry for that :cry: 
@miq-bot add_label bug, GTLs

Fix missing bottom-right fonticons on provider quadicons

---

app/decorators/container_service_decorator.rb

My bad, displaying something that doesn't exist...fixing.
**Before:**
**After:**
@miq-bot add_label bug, GTLs, gaprindashvili/no

Fix missing single_quad for container services

---

app/controllers/container_node_controller.rb
app/controllers/vm_remote.rb

When opening a cockpit console to a VM or a Container Node, it stores it as a lastaction in the session. When navigating to certain pages, this can cause unwanted exceptions. It's analogous with https://github.com/ManageIQ/manageiq-ui-classic/pull/3842
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1585569
@miq-bot add_reviewer @bmclaughlin

Do not store cockpit popups in session

---

app/assets/stylesheets/physical_infra_topology.scss
app/services/physical_infra_topology_service.rb
app/services/ui_service_mixin.rb
app/views/physical_infra_topology/show.html.haml

- Add the `PhysicalSwitch` component to Physical Infra topology page;
- Change the `PhysicalSwitch` icon on topology view to use the same of the Physical Switch page.

Adding Physical Switches to Physical Infra topology page

---

app/helpers/application_helper/import_export_helper.rb
app/views/miq_ae_customization/_dialog_import_export.html.haml
app/views/report/_export_widgets.html.haml
spec/helpers/application_helper/import_export_helper_spec.rb

There was a `pficon-ok` class that's identical to the `100/checkmark.png`, however, the `equal-green` doesn't exist in the icon set. As it represents duplication, I replaced it with `pficon pficon-blueprint` which looks the same as a duplicated item icon. Also the icons were swapped, the OK was shown for the duplicity and the equals for the importable items, so fixing that too.

Use fonticons for dialog/widget import status identificaiton

---

app/helpers/quadicon_helper.rb

The policy simulation results are always being displayed in the bottom right quadrant on a policy simulation screen. I'm changing all the old PNG fileicons to be fonticons and also updating the tooltips to be more descriptive.
@miq-bot add_label technical debt, graphics, gaprindashvili/no

Use fonticons and proper tooltips in policy simulation quadrants

---

app/helpers/quadicon_helper.rb

There is a vm state - powering-up for which there is no icon in general vm view.
This PR fixes this issue by reusing existing svg.
Now when a vm is powering-up it looks like this:

Missing icon for powering-up state

---

app/decorators/storage_decorator.rb

Some of the PNGs weren't even there, something could be converted to fonticons, the rest will go with SVGs.
Related to: https://github.com/ManageIQ/manageiq/pull/17551/files
@miq-bot add_label graphics, gaprindashvili/no, technical debt

Use svg/fonticons for store types in the storage decorator

---

app/controllers/application_controller/filter.rb

This is some pretty old code that's no longer necessary, the ˙#adv_search_img` div got removed way before the UI split.
@miq_bot add_label gaprindashvili/no, cleanup

Remove JS calls that operate with the nonexistent #adv_search_img

---

app/assets/stylesheets/print.scss
app/controllers/application_controller/report_downloads.rb
app/presenters/widget_presenter.rb
app/views/layouts/print/report.html.haml

After the [great success](https://github.com/ManageIQ/manageiq-ui-classic/pull/3998) with the summary screens, I'm replacing the print/PDF feature for the dashboard widgets.
The code changes are minimal, however, the report's table rows are generated by the model and that needs to be addressed in the future.
@miq-bot add_label gaprindashvili/no, reporting, enhancement
@miq-bot add_reviewer @dclarizio 
Related issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/4113
Depends on: https://github.com/ManageIQ/manageiq/pull/17569
https://bugzilla.redhat.com/show_bug.cgi?id=1588072

Client-side print/export to PDF for dashboard widgets

---

app/controllers/security_group_controller.rb
spec/controllers/security_group_controller_spec.rb

RBAC function calls replaced.
Review please @CZJanRichter

RBAC refactor - security_group_controller

---

app/views/catalog/_form_resources_info.html.haml
app/views/miq_ae_class/_class_fields.html.haml
app/views/miq_ae_class/_inputs.html.haml

There were 3 places where PNGs were used:
* Editing a catalog bundle's resources
* Editing a schema of an automate class
* Editing the inputs of an builtin automate method

Use fonticons for embedded items in automate and catalogs

---

app/controllers/report_controller/reports.rb

This is probably a leftover from the old timelines, it is only in the report editor. When you create/edit a report with at least a single time field and go to the timeline tab, you will see that the timeline is being rendered correctly with or without this reference to the image.

Remove unnecessary ref to 16/blue-circle.png from report timelines

---

app/helpers/ems_physical_infra_helper/textual_summary.rb
product/views/ManageIQ_Providers_PhysicalInfraManager.yaml

- Removes the column **Discovered IP Address** from the Physical Infra Providers list page;
- Removes the table row **Discovered IP Adress** from the Physical Infra Provider details page;
**Reason:**
- This column is *equal to*/*computed from* the **Host Name** provided by the user. The computation and update of the `ipaddress` is prone to errors:
1. The user types an **IP** when creating the provider;
2. We resolve the **IP** to a real `hostname`;
3. We save the **IP** in the `ipaddress` field;
4. The DNS query for `hostname` starts to return a new *IP*, different from the initial **IP**;
5. We resolv the `ipaddress` to the new *IP* and update the field. (**Now, we don't have the single source of truth given by the user**).
For this reason, we are not going to show …

Remove Discovered IP Address field from Physical Infra Provider

---

app/helpers/quadicon_helper.rb

Analogous with https://github.com/ManageIQ/manageiq-ui-classic/pull/4101

Add the missing powering_down quadrant machine state

---

spec/controllers/automation_manager_controller_spec.rb

Given this was already changed from position `0` to `1` in https://github.com/ManageIQ/manageiq-ui-classic/pull/1082  and in `Gaprindashvili` it needs to be `0` again... So now it gets provider directly and not blindly from array as this test was never meant to check if providers are sorted correctly.
Gaprindashvili failure:
```
1) AutomationManagerController constructs the ansible tower job templates tree node
Failure/Error: expect(objects).to include(@ans_job_template1)
expected [#<ManageIQ::Providers::AnsibleTower::AutomationManager::ConfigurationScript id: 10000000000174, mana...:Providers::AnsibleTower::AutomationManag...", parent_id: nil, configuration_script_source_id: nil>] to include #<ManageIQ::Providers::AnsibleTower::AutomationManager::ConfigurationScript id: 10000000000173, …
```

Don't get right provider based on position in array

---

package.json

react-ui-components depends on react-select, the compiled JS ends up with a `require('react-select')` statement that ui-classic attempts to resolve.
Unfortunately this only works if react-select was installed in a flat structure, under `node_modules/react-select`.
Instead, it ends up being installed in `node_modules/@manageiq/react-ui-components/node_modules/react-select` .. that is a correct path but one we've lost support for with #2652.
But undoing that change makes the rest of plugins fail :).
So, for now, just adding react-select as a direct dependency.
The long-term fix will depend on #3776 and re-enable resolving nested node_modules.
---
Fixes missing react-select when runnign webpack.
Cc @karelhala , @lpichler

Depend on react-select to fix nested dependencies

---

app/presenters/tree_builder_default_filters.rb

With https://github.com/ManageIQ/manageiq-ui-classic/pull/4116 in place, navigate to: My Settings → Default Filters, you'll witness the following error:
```
F, [2018-06-12T16:20:12.505321 #10918] FATAL -- : Error caught: [ArgumentError] comparison of Array with Array failed
manageiq-ui-classic/app/presenters/tree_builder_default_filters.rb:21:in `sort_by'
manageiq-ui-classic/app/presenters/tree_builder_default_filters.rb:21:in `prepare_data'
manageiq-ui-classic/app/presenters/tree_builder_default_filters.rb:30:in `initialize'
manageiq-ui-classic/app/controllers/configuration_controller.rb:511:in `new'
manageiq-ui-classic/app/controllers/configuration_controller.rb:511:in `set_form_vars'
manageiq-ui-classic/app/controllers/configuration_controller.rb:64:in `edit' …
```

Fix error on default filters page

---

app/controllers/application_controller/ci_processing.rb
app/controllers/ems_common.rb
app/controllers/host_controller.rb
app/controllers/storage_controller.rb

Continuation of changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/3660
Removing method `storage_button_operation`, replaced by `generic_button_operation` mentioned in the PR above.
I couldn't find a way to test this in UI with a successful result, but the behaviour seems to be the same as in master.
Links
* https://github.com/ManageIQ/manageiq-ui-classic/pull/3660

Removing obsolete method for storage button action handling

---

app/decorators/disk_decorator.rb
app/decorators/guest_device_decorator.rb
app/helpers/textual_mixins/textual_devices.rb
app/views/host/_config.html.haml
app/views/vm_common/_config.html.haml
manageiq-ui-classic.gemspec
spec/helpers/textual_mixins/textual_devices_spec.rb
spec/presenters/tree_node/guest_device_spec.rb

I added a new decorator for disks, it needs some extra review if the icons are correct. I'm sure that the network devices are displaying other type of devices as the code only excludes `GuestDevice` records that have `storage` as `device_type` and I found some other types in our DB. Therefore, I also updated the `GuestDeviceDecorator` with some fonticons based on the `device_type`. Then I was able to drop the references to the `100/hardware-*.png`.
Types found in the DB:
```ruby
Hardware.all.map(&:ports).reject(&:empty?).flatten.map(&:device_type).uniq
=> ["ethernet", "cdrom", "management", "physical_port"]
```
Types that have PNG icons:
```
cdrom
disk
ethernet
floppy
memory
parallel
processor
scsi
serial
sound
usb
```
@miq-bot add_label graphics, gaprindashvili/no …

Use fonticons for host/vm hardware peripherals on the devices screns

---

app/decorators/manageiq/providers/network_manager_decorator.rb

Followup after @loicavenel's [request](https://github.com/ManageIQ/manageiq-ui-classic/pull/4025#issuecomment-394719408), networking provider quadicons will display the number of cloud subnets.
@miq-bot add_label gaprindashvili/no, GTLs, networks
cc @Ladas & @tumido

Display cloud subnets in the top-right quadrant of network providers

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/controllers/service_controller.rb
app/services/dialog_local_service.rb
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
spec/services/dialog_local_service_spec.rb

When reconfiguring a service, the UI was attempting to use the old dialog-user component, and therefore wasn't displaying properly. This change ensures the reconfiguration dialog goes through the new dialog-user component and submits to the correct 'reconfigure' API endpoint.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1580987

Ensure new dialog user component is used for service reconfiguration

---

app/decorators/resource_pool_decorator.rb

The `resource_pool.png` is obsolete, the `pficon pficon-resource-pool` fully replaces it, but I haven't found any alternative for the `vapp.png`.

Prefer fonticon for resource pool if it's not vapp

---

config/routes.rb
spec/routing/availability_zone_routing_spec.rb
spec/routing/cloud_tenant_routing_spec.rb
spec/routing/ems_cloud_routing_spec.rb
spec/routing/ems_infra_routing_spec.rb
spec/routing/ems_physical_infra_routing_spec.rb
spec/routing/ems_storage_routing_spec.rb
spec/routing/flavor_routing_spec.rb
spec/routing/resource_pool_routing_spec.rb
spec/routing/security_group_routing_spec.rb
spec/routing/storage_routing_spec.rb

Consequences of copy-pasting things ... :scissors: :scissors: :scissors: there are just a few places where the compare routes should be set:
```
ag "Compare Selected items" app/helpers/application_helper/toolbar
app/helpers/application_helper/toolbar/vm_clouds_center.rb
35:          N_('Compare Selected items'),
app/helpers/application_helper/toolbar/vms_center.rb
24:          N_('Compare Selected items'),
app/helpers/application_helper/toolbar/ems_clusters_center.rb
25:          N_('Compare Selected items'),
app/helpers/application_helper/toolbar/hosts_center.rb
33:          N_('Compare Selected items'),
app/helpers/application_helper/toolbar/vm_infras_center.rb
45:          N_('Compare Selected items'),
app/helpers/application_helper/toolbar/template_clouds_center.rb
35: …
```

Remove unnecessary compare routes

---

app/controllers/application_controller/compare.rb

We removed the PNG images that are still being used for comparing clusters. To fix this we should display the fonticon for them, and it's more safe to do so with decorators, for all cases.
**Before:**
**After:**
@miq-bot add_label bug, gaprindashvili/no, graphics

Use decorators for icons/images in the compressed compare view

---

app/controllers/mixins/actions/vm_actions/reconfigure.rb

Get Network adapters reconfigure data only when the reconfigure is supported 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1591606.
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1591606
https://github.com/ManageIQ/manageiq-providers-vmware/pull/283
Related PRs:
https://github.com/ManageIQ/manageiq-ui-classic/issues/3972
-----------
After:

Get Network adapters reconfigure data only when the reconfigure is supported 

---

app/helpers/textual_multilabel.rb

__This PR fixes__
https://github.com/ManageIQ/manageiq-ui-classic/issues/4147
__Before this PR__
The `TextualSummaryWrapper` sends this error while trying to process the payload:
`Warning: Failed prop type: The prop 'rows' is marked as required in 'SimpleTable', but its value is 'undefined'.`
__After this PR__
The `TextualMultilabel` struct sets the `:rows` value using the `:values`
This approach was adopted to provider a compatibility with all summaries that uses the TextualMultilabel, but, another approach is to parse the `:rows` value with the value of `options[:rows]`, but this way we must update all the files that uses TextualMultilabel

Fixing textual summary payload mount for multilabel components

---

app/decorators/miq_event_definition_decorator.rb

Part of https://github.com/ManageIQ/manageiq/pull/17578.
https://bugzilla.redhat.com/show_bug.cgi?id=1495265
@miq-bot add_label enhancement, gaprindashvili/no

Add icon for host_failure event.

---

app/controllers/application_controller.rb
app/controllers/miq_request_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/button/miq_request.rb
app/helpers/application_helper/button/miq_request_approval.rb
app/helpers/application_helper/button/miq_request_delete.rb
app/helpers/application_helper/button/miq_request_reload.rb
app/helpers/application_helper/toolbar/miq_request_center.rb
app/helpers/application_helper/toolbar/miq_requests_center.rb
app/presenters/menu/default_menu.rb
spec/helpers/application_helper/buttons/miq_request_approval_spec.rb
spec/helpers/application_helper/buttons/miq_request_delete_spec.rb

Separated features for each "Requests" sub tab under Automation/Automate/Requests & Compute/Infrastructure/Requests to provide users with capability to allow access to each type individually. Currently there was only features for Service/Requests user was forced to have access to Service/Requests features to be able to see Automation or Host Provisioning requests.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1508490
Also fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1526495
Depends on https://github.com/ManageIQ/manageiq/pull/17524

Added separate features for Requests subtabs

---

app/decorators/storage_decorator.rb

Fix Datastore decorator format string.
Before this fix - selecting the Infrastructure-> Datastore menu will cause this error:
After:

Fix Datastore decorator format string 

---

app/controllers/chargeback_controller.rb
app/controllers/mixins/saved_report_paging.rb
app/controllers/report_controller/saved_reports.rb
app/helpers/application_helper/button/report_download_choice.rb
app/helpers/application_helper/button/report_only.rb
spec/controllers/chargeback_controller_spec.rb
spec/controllers/miq_report_controller/trees_spec.rb
spec/controllers/report_controller_spec.rb

Merge after https://github.com/ManageIQ/manageiq/pull/17590
This makes both the `ChargebackController` and `ReportController::SavedReports` actions for viewing reports signficantly faster by:
* avoiding loading the `binary_blob` data entirely (avoids massive YAML deserialization).  This uses methods provided by https://github.com/ManageIQ/manageiq/pull/17590 to accomplish this.
* Fix button helpers to use `.exists?` instead of `.length > 0`, which prevents needing to fetch all of the report result row records, which were then thrown away and never used.
Benchmarks
----------
This is displaying a `MiqReportResult` index page that has 23k+ rows associated with it.  Showing the first page, paginated by 20 records.
**Before**
|   ms | queries | query (ms) |  rows |
| ---: |    ---: | …

Faster report result index pages

---

app/controllers/ops_controller/settings/common.rb

For worker memory threshold, we should be saving numbers, not translated strings (e.g. en: "500 MB" -> fr: "500 Mo")
1. Navigate to Settings -> [Your server] -> Workers tab
2. Change your locale to French
3. Change the any of the memory threshold settings on that screen
Without this fix, you'd get an error. With this fix in place, the screen will be working correctly.
https://bugzilla.redhat.com/show_bug.cgi?id=1589122

Fix error on localized worker settings screen

---

bower.json

https://github.com/ManageIQ/ui-components/pull/304 ([BZ 1592852](https://bugzilla.redhat.com/show_bug.cgi?id=1592852))
https://github.com/ManageIQ/ui-components/pull/303 ([BZ 1591425](https://bugzilla.redhat.com/show_bug.cgi?id=1591425))
https://github.com/ManageIQ/ui-components/pull/302 ([BZ 1590353](https://bugzilla.redhat.com/show_bug.cgi?id=1590353))
https://github.com/ManageIQ/ui-components/pull/296 ([BZ 1591425](https://bugzilla.redhat.com/show_bug.cgi?id=1591425))

[GAPRINDASHVILI] Update ui-components to 1.0.29 for Gaprindashvili

---

app/controllers/ansible_repository_controller.rb
spec/controllers/ansible_repository_controller_spec.rb

The refresh page button is no longer present on Ansible Repository Playbooks subpage. Because of that it is no longer necessary to handle pressing this button on this subpage. Remove this handling and related spec examples.
1. Open an Ansible Repository show page.
2. Press the leftmost _Refresh_ button.
Now, https://github.com/ManageIQ/manageiq-ui-classic/blob/29856637524202c4bac5a756bd019086e738dcf2/app/controllers/ansible_repository_controller.rb#L43 is executed, even though this is no longer necessary. This line was useful only for refreshing the Playbooks subpage.
Fixes #4160. Helps #3762.
@miq-bot add_reviewer @hstastna

Remove unused Ansible Repository page refresh

---

app/views/shared/buttons/_ab_form.html.haml

Removed the PNGs but forgot to replace all the references, this fixes a 404 error when creating/editing a custom button.
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/4051
@miq-bot add_label bug, gaprindashvili/no, graphics

Change the paste image with a fonticon in custom button forms

---

app/services/git_based_domain_import_service.rb
spec/services/git_based_domain_import_service_spec.rb

Changed import from git repository from system to current user.
Updated test.
This will make the git repository import consistent with other imports.
https://bugzilla.redhat.com/show_bug.cgi?id=1591809

Fixed Automate import domain from git repository to use current user.

---

app/views/layouts/exp_atom/_edit_field.html.haml
app/views/layouts/exp_atom/_edit_find.html.haml

Since I [removed](https://github.com/ManageIQ/manageiq-ui-classic/pull/4151) the toolbar PNG files, the expression editor produces 404 errors for the date buttons. This PR fixes these issues by replacing the images with fonticons.
@miq-bot add_label bug, gaprindashvili/no, graphics
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/4051

Use fonticons for relative/specific date selection in exp editor

---

package.json

`redux-devtools-extension` v2.13.3 is broken and `bin/webpack` isn't working
@himdel opened issue https://github.com/zalmoxisus/redux-devtools-extension/issues/519
Run `bin/webpack`
Before:
```
ERROR in [at-loader] ./node_modules/redux-devtools-extension/index.d.ts:159:60 
TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).
ERROR in [at-loader] ./node_modules/redux-devtools-extension/index.d.ts:161:61 
TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).
```
After:
It works again.
@miq-bot add_label bug, dependencies

Enforce version 2.13.2 of redux-devtools-extension

---

app/controllers/application_controller/report_downloads.rb
app/helpers/application_helper/toolbar/chargeback_center.rb
app/helpers/application_helper/toolbar/compare_view.rb
app/helpers/application_helper/toolbar/drift_view.rb
app/helpers/application_helper/toolbar/gtl_view.rb
app/helpers/application_helper/toolbar/miq_capacity_view.rb
app/helpers/application_helper/toolbar/x_gtl_view.rb
spec/helpers/application_helper/toolbar_builder_spec.rb

Most cases of PDF generation were very similar to the way [we do it with the widgets](https://github.com/ManageIQ/manageiq-ui-classic/pull/4114) so I am generalizing the feature more. Hovewer, the saved report PDFs are generated by the backend as an asynchronous task, so they aren't covered by this PR.
@miq-bot add_label gaprindashvili/no, reporting, enhancement
Related issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/4113
https://bugzilla.redhat.com/show_bug.cgi?id=1588072

Use the client-side printing for reports where the PDF was generated synchronously

---

app/controllers/ems_common.rb
app/controllers/ems_network_controller.rb
spec/controllers/ems_common_controller_spec.rb

1. Network -> Providers
2. From the list of network providers, select a network provider, which doesn't support editing (e.g. Amazon, Azure, Google)
3. Hit Configuration -> Edit
4. From the list of network providers, select a network provider, which supports editing (currently only Nuage)
5. Hit Configuration -> Edit
With my fix in place, for network provider, that doesn't support editing, you'll get a flash message saying so. If the network provider does support edit, you'll get to the editing screen.
https://bugzilla.redhat.com/show_bug.cgi?id=1577888

Don't allow network manager edit if the network manager doesn't support it

---

app/controllers/application_controller/ci_processing.rb
app/controllers/miq_policy_controller.rb

Show meaningful policy name in audit.log when adding/deleting policy.
https://bugzilla.redhat.com/show_bug.cgi?id=1434762
1. In UI, Control->Policies, add or delete a policy;
2. `[policy_name] Record added [deleted]` should show in the audit.log
Related PR:
https://github.com/ManageIQ/manageiq/pull/17504

Fix to show meaningful policy name when add/delete it in audit.log

---

app/helpers/application_helper/button/new_flavor.rb
spec/helpers/application_helper/buttons/new_flavor_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1584158
**Before:**
Compute -> Cloud -> Providers -> choose one with flavors -> click Flavors in chosen provider summary screen -> Configuration
Compute -> Cloud -> Flavors -> Configuration
**After:**
Compute -> Cloud -> Providers -> choose one with flavors -> click Flavors in chosen provider summary screen -> Configuration
Compute -> Cloud -> Flavors -> Configuration 
*No change!*
`ApplicationHelper::Button::ButtonNewDiscover` handles `visible?` for buttons that may appear on sublist view screen and on list view screen.
@romanblanco @PanSpagetka Please review, thanks :)
@miq-bot add_label bug, gaprindashvili/yes, fine/yes, toolbars

Don't show Add Flavor in sublist view

---

app/assets/stylesheets/patternfly_overrides.scss
app/controllers/application_controller/policy_support.rb
app/controllers/application_controller/tags.rb
app/helpers/gtl_helper.rb
spec/controllers/storage_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb

On the policy simulation, policy assignment and tagging screens the quadicons should not be clickable. The solution is to pass the `:clickable => false` argument to the related `get_db_view` methods.
I also made the `miq_tile_view` method a little bit more consistent with the `miq_data_table` by setting the `no-action` class on it if `showUrl` is set to `false` in the controller. This parameter is being set by the 
`clickable` from above. @karelhala please validate this approach.
Then I edited the CSS overrides by disabling the hand cursor on links under `.no-action`, @epwinchell please take a look.
@miq-bot add_label bug, gtls, gaprindashvili/yes
Fixes: #4175
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1593394

Make policy assignment, simulation and tagging quads non-clickable

---

bower.json
lib/manageiq/ui/classic/engine.rb
manageiq-ui-classic.gemspec

we're still on lodash3, required via bower (in application.js).
but looks like at some point we've lost the explicit bower dependency
and now, something started depending on lodash4, breaking the UI:
```
angular.self-4d4ad11…a00bb8370c.js:14801 TypeError: _.contains is not a function
at ToolbarController (toolbar_controller.s…fd6b619fb5f82.js:66)
at Object.invoke (angular.self-4d4ad11…2a00bb8370c.js:5107)
at $controllerInit (angular.self-4d4ad11…a00bb8370c.js:11077)
at nodeLinkFn (angular.self-4d4ad11…2a00bb8370c.js:9940)
at compositeLinkFn (angular.self-4d4ad11…2a00bb8370c.js:9249)
at publicLinkFn (angular.self-4d4ad11…2a00bb8370c.js:9114)
at angular.self-4d4ad11…2a00bb8370c.js:1961
at Scope.$eval (angular.self-4d4ad11…a00bb8370c.js:18543)
at Scope.$apply …
```

Ensure lodash 3 is available via bower

---

app/helpers/application_helper/toolbar/physical_switch_center.rb
app/helpers/application_helper/toolbar/physical_switches_center.rb
app/javascript/miq_observable.js
app/javascript/packs/toolbar-actions.js
app/javascript/toolbar-actions/refresh.js
app/javascript/toolbar-actions/restart.js
app/views/physical_switch/show.html.haml
app/views/physical_switch/show_list.html.haml

- Add the `Power` button in Physical Switches summary and detail pages with the `restart` action.
- Refactor the `refresh` action routine to the new structure introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/3436
__Depends on__
- ~https://github.com/ManageIQ/manageiq-api/pull/392~ - Merged

Adding power operation in physical switch pages

---

app/views/layouts/angular/_ansible_form_options_angular.html.haml

Increase maxlength for playbooks' host option field nd change it to a textarea
Links
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594426
1. Enable the Embedded Ansible provider and add a repository with a playbook
2. Navigate to Automation -> Automate -> Explorer
3. Create a Method of type playbook
4. Click the "Specify host values" checkbox for the Host
5. Attempt to enter more than 50 characters.
Before:

Increase maxlength for playbooks' host option field

---

package.json

Before release of `v2.13.5` there was following error:
```
ERROR in [at-loader] ./node_modules/redux-devtools-extension/index.d.ts:159:60
TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).
ERROR in [at-loader] ./node_modules/redux-devtools-extension/index.d.ts:161:61
TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).
```
That was [fixed](https://github.com/ManageIQ/manageiq-ui-classic/pull/4174) by enforcing `v2.13.2`. But we don't need that change anymore so getting back to original :)
Run `bin/webpack`
@miq-bot add_label gaprindashvili/yes, dependencies

Don't enforce  v2.13.2 of redux-devtools-extension

---

spec/decorators/miq_decorator_spec.rb

Code sharing by inheritance in decorators is something we don't want. Every decorator has to be inherited from the `MiqDecorator`, otherwise this test fails. This test only checks decorators that are defined in the `ui-classic`, on other places such as providers we want to allow inheritance.
@miq-bot add_label tests, gaprindashvili/no, developer

Add spec to fail on indirect inheritance of MiqDecorator

---

app/assets/javascripts/controllers/vm_cloud/vm_cloud_resize_form_controller.js
app/controllers/mixins/actions/vm_actions/resize.rb
app/views/vm_common/_resize.html.haml

TODO:
Commit: https://github.com/ManageIQ/manageiq-ui-classic/pull/4182/commits/d5e4ad7cbc1626be1dcaac2b0702ab999943adf0
Commit: https://github.com/ManageIQ/manageiq-ui-classic/pull/4182/commits/c4595a1fbe61a9e7d5de7fd1ff881e94a08f76aa
Commits: https://github.com/ManageIQ/manageiq-ui-classic/pull/4182/commits/8b1dc95b9d63b71c4a25edce1705058cd619556a https://github.com/ManageIQ/manageiq-ui-classic/pull/4182/commits/6128f848f8c9c90d691a69582f35fbb17b7818ec
```diff
-recs = find_checked_items
+ recs = checked_or_params
```
It's ok :)
Before:
```
recs = find_checked_items
[some code]
recs = [params[:id].to_i] if recs.blank?
```
After:
```diff
-recs = find_checked_items
+ recs = checked_or_params
[some code]
- recs = [params[:id].to_i] if recs.blank?
```
So just removing extra `recs = …

Fix issues in Reconfigure/Resize

---

lib/tasks/manageiq/ui_tasks.rake

this was working when run as part of `webpack:compile`
but running `webpack:paths` by itself would fail to generate `config/webpack/paths.json` with `manageiq-v2v`, using `manageiq-v2_v` instead
@NickLaMuro please review :)

webpack:paths - always load inflectors

---

app/views/catalog/_sandt_tree_show.html.haml
app/views/layouts/_policy_sim.html.haml
app/views/miq_ae_tools/_import_export.html.haml
app/views/ops/_diagnostics_savedreports.html.haml
app/views/ops/_ldap_forest_entries.html.haml

There were some remaining references to PNG images from the `toolbars` folder.
When removing orphaned data from diagnostics:
Importing/exporting stuff from Automate:
When displaying a service template:
I was not able to display the LDAP forest entries page in the UI. I could render it with a hack, but that's not really doable without changing some conditions in the code.
@miq-bot add_label cleanup, graphics, gaprindashvili/no

Remove remaining references to toolbar images

---

app/controllers/chargeback_controller.rb
app/controllers/mixins/saved_report_paging.rb
app/controllers/report_controller/saved_reports.rb
app/helpers/application_helper/button/report_download_choice.rb
app/helpers/application_helper/button/report_only.rb
spec/controllers/chargeback_controller_spec.rb
spec/controllers/miq_report_controller/trees_spec.rb
spec/controllers/report_controller_spec.rb

This is the Gaprindashvili port of #4143.  Original PR message below.
* * *
Merge after https://github.com/ManageIQ/manageiq/pull/17590  (**NOTE:** Not relavent, this is already backported)
This makes both the `ChargebackController` and `ReportController::SavedReports` actions for viewing reports signficantly faster by:
* avoiding loading the `binary_blob` data entirely (avoids massive YAML deserialization).  This uses methods provided by https://github.com/ManageIQ/manageiq/pull/17590 to accomplish this.
* Fix button helpers to use `.exists?` instead of `.length > 0`, which prevents needing to fetch all of the report result row records, which were then thrown away and never used.
Benchmarks
----------
This is displaying a `MiqReportResult` index page that has 23k+ rows associated with …

[GAPRINDASHVILI] Faster report result index pages

---

app/controllers/application_controller.rb
app/controllers/chargeback_controller.rb
app/controllers/report_controller/saved_reports.rb
app/helpers/application_helper/button/report_download_choice.rb
app/helpers/application_helper/button/report_only.rb
spec/controllers/chargeback_controller_spec.rb
spec/controllers/miq_report_controller/trees_spec.rb

This is the Fine port of #4143.  Original PR message below.
* * *
Merge after https://github.com/ManageIQ/manageiq/pull/17590  (**NOTE:** Not relavent, this is already backported)
This makes both the `ChargebackController` and `ReportController::SavedReports` actions for viewing reports signficantly faster by:
* avoiding loading the `binary_blob` data entirely (avoids massive YAML deserialization).  This uses methods provided by https://github.com/ManageIQ/manageiq/pull/17590 to accomplish this.
* Fix button helpers to use `.exists?` instead of `.length > 0`, which prevents needing to fetch all of the report result row records, which were then thrown away and never used.
Benchmarks
----------
This is displaying a `MiqReportResult` index page that has 23k+ rows associated with it.  Showing …

[FINE] Faster report result index pages

---

app/helpers/number_helper.rb
spec/helpers/number_helper_spec.rb

After https://github.com/ManageIQ/manageiq-ui-classic/pull/4156 `rails_method_to_human_size` method is never used.

Remove dead methods from NumberHelper

---

app/controllers/application_controller.rb

The `has_listicon` is only set to `false` if the view to display is `MiqAeClass` or `MiqAeInstance`. I was clicking through the automate as much as possible, but haven't found any GTL screen and in the table views both these item types have listicons. From this I assume that the `has_listicon` variable is not necessary and every row should have one icon, so removing the unncesessary code :scissors: :toilet: :droplet: 
@miq-bot add_label refactoring, gaprindashvili/no, GTLs
@miq-bot add_reviewer @pkomanek 
@miq-bot add_reviewer @karelhala

Remove the exception to not show listicons in GTLs

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

When both a `fonticon` and a `fileicon` is defined for an item, the preferred one was the `fonticon`, except of some special cases when there's a `picture` attribute available. This was unnecessarily complicated and as all the unnecessary PNG files and their references [have been removed](https://github.com/ManageIQ/manageiq-ui-classic/issues/4051), we can simplify this a little.
So I'm proposing the same preference as we have for treeviews: `fileicon` over `fonticon` and also dropping the `picture` attribute. 
UI components PR: https://github.com/ManageIQ/ui-components/pull/308
@miq-bot add_reviewer @karelhala 
@miq-bot add_labels gaprindashvili/no, GTLs, graphics

Reprioritize icons and images for GTLs, prefer images first

---

app/assets/javascripts/import.js
app/views/ops/_settings_advanced_tab.html.haml
spec/javascripts/import_spec.js

From discussion in https://github.com/ManageIQ/manageiq-ui-classic/pull/4224...
We have a bunch of places using `pficon-error-octagon`. This does not exist in current patternfly, and doesn't seem to exist in 3.3 (ancient version) either.
According to https://www.patternfly.org/styles/icons/, the right icon to use is `pficon-error-circle-o`.
---
So, using that error icon for the import error message.
But for Advanced settings in ops, the message is a warning, is called a warning in code, so it should not be using error styling.
Updated to use the proper warning style instead:

Fix nonexistent pficon-error-octagon

---

app/presenters/menu/default_menu.rb

Fixes default menu definition for Automate => Generic Objects to match Product Features yaml definition.
https://bugzilla.redhat.com/show_bug.cgi?id=1331399
See screen shots in:  https://github.com/ManageIQ/manageiq/pull/17630

Fix Generic Objects default menu definition

---

product/views/OpenscapRuleResult.yaml

Display new added title and CVEs information in Openscap rule results page.
https://bugzilla.redhat.com/show_bug.cgi?id=1561959
Depends on: 
https://github.com/ManageIQ/manageiq-schema/pull/214
https://github.com/ManageIQ/manageiq/pull/17219

Display two new added columns in Openscap rule results page

---

app/presenters/tree_builder.rb

Those two items may contain characters which would make javascript fail later down the road (apostrophes for example).
1. Simulate a situation where the root of some tree builder would contain `:text` or `:tooltip` with an apostrophe.
2. Navigate to the screen containing the tree
Before:
After:
This problem would show for example on Generic Objects list screen in French locale. The following error would be shown in JS console:
```
angular.self-7e0b2baf4553bcd25cbb45cbe35556b3c2fbcb170db636503b5bee55a75e7b9b.js:14701 Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 342-342 [é] in expression [vm.initData('generic_object_definitions_tree', '[{"key":"root","nodes":[{"key":"god-10r1","text":"123","icon":"fa …
```

Escape special chars in tooltip & text of TreeBuilder's root

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/assets/javascripts/controllers/dialog_user/dialog_user_reconfigure_controller.js
app/assets/javascripts/services/dialog_user_submit_error_handler_service.js
app/controllers/application_controller/dialog_runner.rb
app/controllers/service_controller.rb
app/services/dialog_local_service.rb
app/views/shared/dialogs/_reconfigure_dialog.html.haml
spec/controllers/service_controller_spec.rb
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
spec/services/dialog_local_service_spec.rb

This PR is the UI counterpart to the [backend PR found here](https://github.com/ManageIQ/manageiq/pull/17647). I decided to write a new javascript controller and haml file corresponding to the reconfigure action instead of reusing `dialogUserController` because there were enough differences that I felt it would be much cleaner and easier to understand this way.
Essentially, when clicking on the reconfigure button, it now will make an API call to get the reconfigure dialog, which will return the dialog with the correct "default" values (they are not actually the default values, they are the values which the service was originally configured with).
https://bugzilla.redhat.com/show_bug.cgi?id=1591484
/cc @gmcculloug @tinaafitz 
@d-m-u Can …

Change reconfigure setup to include values configured with originally

---

app/controllers/application_controller.rb
app/controllers/application_controller/report_data_additional_options.rb
app/controllers/automation_manager_controller.rb
app/controllers/chargeback_controller.rb
app/controllers/configuration_job_controller.rb
app/controllers/container_image_controller.rb
app/controllers/host_controller.rb
app/controllers/infra_networking_controller.rb
app/controllers/miq_request_controller.rb
app/controllers/mixins/explorer_show.rb
app/controllers/orchestration_stack_controller.rb
app/controllers/storage_controller.rb
app/controllers/vm_common.rb
app/helpers/application_helper.rb
spec/support/controller_helper.rb

There were two places where the `@listicon` was used to generate the `@gtl_url`. After looking into this I found out that the `@gtl_url` is being only used in GTL view type selection (the 3 icons on the right side) that is not available on any screens related to the remaining references. Therefore, I think it is safe to remove this evilness and simplify our codebase :scissors: :toilet: :fire: 
@miq-bot add_reviewer @karelhala 
@miq-bot add_label GTLs, refactoring, gaprindashvili/no

Remove all references to the unnecessary listicon instance variable

---

app/controllers/application_controller/report_downloads.rb
app/helpers/application_helper/button/pdf.rb
app/helpers/application_helper/button/render_report_pdf.rb
app/helpers/application_helper/toolbar/report_view.rb
app/views/layouts/print/report.html.haml
spec/helpers/application_helper/buttons/render_report_pdf_spec.rb

Saved report PDFs are being generated asynchronously due to their size, the most time-consuming operation (except of the PDF generation itself) was the joining the sub-reports together. As we're moving the PDF generation to the client, I modified the asynchronous task to return with the `html_rows` only. This is later being used in the rendering the print view using the `@data` instance variable.
To have a new window for printing, the `:popup => true` was not effective due to the `wait_for_task` so I also had to add an exception for opening PDF reports in a new window. I know that the code is ugly, but it is now consistent with the other printing views in the UI. I will refactor this in the future in a separate PR.
@miq-bot add_label pending core, gaprindashvili/no, reporting, enhancement …

Use the browser's native printing for asynchronously generated saved reports

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/assets/javascripts/controllers/dialog_user/dialog_user_reconfigure_controller.js
app/assets/javascripts/services/dialog_user_submit_error_handler_service.js
app/controllers/application_controller/dialog_runner.rb
app/controllers/service_controller.rb
app/services/dialog_local_service.rb
app/views/shared/dialogs/_reconfigure_dialog.html.haml
spec/controllers/service_controller_spec.rb
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
spec/javascripts/services/dialog_user_submit_error_handling_service_spec.js
spec/services/dialog_local_service_spec.rb

This is a manual backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/4226 since as @simaishi pointed out, we need to take into account compressed ids and the spec surely would have broken.
There was also another small conflict in the javascript spec regarding calling `setTimeout` whereas the master PR does not do that, so I've fixed that as well.
https://bugzilla.redhat.com/show_bug.cgi?id=1591484 is the Gaprindashvili BZ, the original BZ is https://bugzilla.redhat.com/show_bug.cgi?id=1580987.
@simaishi Please let me know if there is anything else I need to change about this PR/commits. Thanks!

[GAPRINDASHVILI] Change reconfigure setup to include values configured with originally

---

app/controllers/report_controller/schedules.rb

Schedule was already created in `schedule_new` but code is trying to create/load it again in `schedule_edit`
https://bugzilla.redhat.com/show_bug.cgi?id=1595132
1. Navigate to Cloud Intel/Reports.
2. Expand Schedules accordion.
3. Click Configuration "Add a new Schedule".

Don't create create schedule if already created

---

spec/javascripts/services/dialog_user_submit_error_handling_service.spec.js

I forgot to add this to #4226. It's a spec for the logic I refactored out, but the specs were mostly transferred over from the old spec logic (just without the need to be called async).
Figured out I forgot to add it when I made the Gaprindashvili manual backport after #4226 was already merged. Oops 😢 

Add spec for dialogUserSubmitErrorHandlingService

---

app/decorators/ext_management_system_decorator.rb

This decorator is only being used as a fallback to not have scary errors if someone creates a new EMS type. As the `fonticon` is set to `nil`, it would always return with an empty quad, so I'm setting the `single_quad` to return with `fileicon` instead.
@miq-bot add_label gaprindashvili/no, GTLs

Fix the EMS fallback decorator's single_quad definition

---

app/controllers/ops_controller/settings/common.rb
spec/controllers/ops_controller/settings/common_spec.rb

Show and allow the server name to be saved in the settings/server screen
Links 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1595377
Before  -the server name entered in the Appliance Name field was not saved. The value in the config file was saved instead on the first save ( when other fields were also changed). The save button was only enabled when fields other than Appliance name were modified.
After:
The Save button is enbabled when only the server name is changed, and the name is changed to the new value.

Show and allow the server name to be saved in the settings/server screen

---

app/decorators/manageiq/providers/embedded_automation_manager/authentication_decorator.rb

When going to `Automation -> Ansible -> Credentials` the quadicons were missing, fixing it.
**Before:**
**After:**
@miq-bot add_label gaprindashvili/no, bug
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594824

Add single_quad definition for embedded ansible credentials

---

app/controllers/application_controller/buttons.rb
app/controllers/miq_ae_customization_controller/custom_buttons.rb

**Automation** :arrow_right: **Automate** :arrow_right: **Customization**
Toolbar for **Buttons** accord is not displayed, console shows a pretty traceback.
```ruby
FATAL -- : Error caught: [NoMethodError] undefined method `each' for nil:NilClass
.../manageiq-ui-classic/app/controllers/miq_ae_customization_controller/custom_buttons.rb:24:in `ab_get_node_info'
.../manageiq-ui-classic/app/controllers/miq_ae_customization_controller.rb:252:in `get_specific_node_info'
...
```
Probably caused by empty database and session on my setup or something like that.
Same happens for the **Add a new Button** action in the **Buttons** toolbar, fixing that as well.
Before:
_Showing previously used toolbar_
After:
_Correct toobar_
cc @martinpovolny

Fix toolbar switching for Buttons accord and Add a new Button action 

---

app/helpers/application_helper/button/embedded_ansible.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1560535
Enable Embedded Ansible
Create a Group that is restricted to some tags
Create a User that is in the Group
Add tag that isn't in the Group to Embedded Ansible Provider via console 
```
Classification.bulk_reassignment(:model => "ManageIQ::Providers::EmbeddedAnsible::AutomationManager", :object_ids => [<id of Embedded Ansible Automation Manager>], :add_ids => [<id(s) of tag(s)>])
```
Go to Automation -> Ansible -> Repositories -> Configuration -> Add a new Repository
Before:
After:
@miq-bot add_label bug, gaprindashvili/yes,  automation/ansible, toolbars
@romanblanco @PanSpagetka please review, thanks :)

Don't allow user to create a repository if he has no rights to EA provider

---

app/helpers/application_helper/button/topology_feature_button.rb

Removing the topology icon from Physical Infra dashboard page as decided here https://github.com/ManageIQ/manageiq-ui-classic/pull/4158

Teporarily removing the topology icon from physical infra view

---

app/controllers/ansible_credential_controller.rb
app/controllers/ansible_playbook_controller.rb
app/controllers/ansible_repository_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/toolbar_chooser.rb
spec/controllers/ansible_credential_controller_spec.rb
spec/controllers/ansible_playbook_controller_spec.rb
spec/controllers/ansible_repository_controller_spec.rb
spec/helpers/application_helper/toolbar_chooser_spec.rb

**Related (older) PR:** https://github.com/ManageIQ/manageiq-ui-classic/pull/3721
**What:**
Move setting toolbar filename to Ansible Playbook/Repository/Credential controllers, by using new controller's method `toolbar_filename` to set toolbar filename properly.
**Why:**
Avoid defining various ugly methods in toolbar chooser for setting toolbar filename.

Move setting toolbar filename to Ansible Playbook/Repository/Credential controllers

---

app/controllers/report_controller/widgets.rb

Fixes all confirmation message for uniformity to match Delete action message display. Uses same common method now to set message text in order of preference: description, title, name, record id. For Widgets .name does not exist, thus a fix to Cancel action message display. 
https://bugzilla.redhat.com/show_bug.cgi?id=1539118
Screen shot, for Widget Add, post code fix:
Screen shot for Widget Edit, post code fix:
Screen shot for Widget Edit Cancel action, post code fix:
Screen shot for Widget Delete, matching other confirmation messages:

Fixes confirmation messages for Widgets Add/Edit/Cancel actions.

---

app/helpers/ops_helper.rb
app/views/ops/_settings_advanced_tab.html.haml

For https://bugzilla.redhat.com/show_bug.cgi?id=1576984, we've added "magic word" `<<reset>>` support to the AdvancedSettings to allow resetting values to inherit from the parent, or in the case of a key added by a user (say, through a typo), to delete that key.  We are added some info text, because without it, there is no way a user would know they can set this value.
~~https://user-images.githubusercontent.com/52120/41993112-5e99255c-7a18-11e8-8537-006358172069.png~~
~~WIP because I need help on
~~ - how to substitute the parent string and still maintain i18n rules.  `_()` doesn't seem to take a second parameter, so I'm not sure what to do.  @himdel or @mzazrivec ?~~
~~ - wording for the info box, and also placement (should it be above or below the error warning already there?) …

Add guidance text for new <<reset>> magic word

---

app/controllers/mixins/generic_list_mixin.rb

- Fix the listnav issue;
__Steps to Reproduce__
- Access a physical provider dashboard view (need to confirm if it happens in other providers);
- Access the `show_list` page of physical providers;
- See that the `listnav` is not shown:
This issue is due to `@showtype` value that remains as `"dashboad"` which removes the `listnav` according to the logic inside `app/helpers/application_helper/page_layouts.rb#layout_uses_listnav?`

Fixing showtype error

---

app/assets/javascripts/controllers/topology/cloud_topology_controller.js
app/assets/javascripts/controllers/topology/container_topology_controller.js
app/assets/javascripts/controllers/topology/infra_topology_controller.js
app/assets/javascripts/controllers/topology/network_topology_controller.js
app/assets/javascripts/controllers/topology/physical_infra_topology_controller.js
app/assets/javascripts/services/topology_service.js
app/views/container_topology/show.html.haml
app/views/network_topology/show.html.haml
spec/javascripts/controllers/containers/container_topology_controller_spec.js
spec/javascripts/services/topology_service_spec.js

Moving common code to topology service from all topology controllers.
- `miqHideSeachClearButton()`
- refresh setup
- context menu setup
- icon loading
- tooltip setup
Also the `/container_project_topology/data` and `/container_topology/data` URL decision was removed from topology service. Container topology controller is now picking the right URL based on the `topologyDetail` parameter (Once there is a component for topology URL will be parameter anyway...).

Move common initialization steps of topologies to topology service

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Fixed condition to pass in ids correctly to find_records_with_rbac method.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596136
@lgalis please review/test. Fixed tagging for a Catalog Item from summary screen.

Pass in id of selected record correctly.

---

app/helpers/persistent_volume_helper/textual_summary.rb

Passing capacity hash to values broke the PV summary screen - table rows are expected to be an array.
cc: @cben @himdel @martinpovolny @oourfali 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1594567
Before:
After:

Passing capacity hash to values broke PV screen

---

app/assets/javascripts/controllers/alerts/alerts_list_controller.js
app/assets/javascripts/services/alerts_center_service.js
app/controllers/alerts_list_controller.rb
app/views/shared/views/_alerts_list.html.haml

Fixed missing images in alerts. Now using fonticons instead of fileicons.
http://localhost:3000/alerts_list/show
should replace #4243

Replaced fileicons with fonticons in alerts.

---

app/assets/stylesheets/topology.css
app/services/physical_infra_topology_service.rb

__This PR is able to:__
- Add the connections between physical servers and physical switches on topology;
- In order to distinguish a "contains" relationship from "connection" relationship the line color was setted to green and the style was setted to a dashed line.
__Depends on:__
- ~https://github.com/ManageIQ/manageiq/pull/17311~ Merged
- ~https://github.com/ManageIQ/manageiq-ui-classic/pull/4068~ Merged

Adding connections between servers and switches on topology page

---

app/assets/javascripts/miq_ujs_bindings.js

Firefox on **MacOS** doesn't fire `onfocus` when radio button is clicked. And it's by design as seen [here](https://bugzilla.mozilla.org/show_bug.cgi?id=577316) [here](https://bugzilla.mozilla.org/show_bug.cgi?id=643968) [here](https://bugzilla.mozilla.org/show_bug.cgi?id=756028) so adding `onchange` to do the same as `onfocus`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594714
1. Using Firefox, create a new custom button of type "Ansible Playbook". Select "Target Machine" as the inventory type. Complete the remaining button details and save.
2. Observe that the Target has been set to "localhost"
3. Try to edit the button. Observe that changing the "Inventory" radio button value does not enable the 'Save' button. 
4. Change the button name (which does re-enable …

Use onchange as well as onfocus for radio buttons

---

app/controllers/vm_common.rb

Fixes incorrect action value passed when building page header text for Cloud Networks list view.
https://bugzilla.redhat.com/show_bug.cgi?id=1588326

Fixes page header when displaying Cloud Networks list

---

app/helpers/application_helper/button/miq_request.rb

Issue was introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/4062
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1598701
before
after

Fixed to make Reload button visible on list view.

---

app/controllers/physical_network_port_controller.rb
app/controllers/physical_switch_controller.rb
app/decorators/physical_network_port_decorator.rb
app/helpers/application_helper/page_layouts.rb
app/helpers/physical_network_port_helper.rb
app/helpers/physical_network_port_helper/textual_summary.rb
app/helpers/physical_switch_helper/textual_summary.rb
app/views/physical_network_port/show.html.haml
app/views/physical_switch/show.html.haml
config/routes.rb
product/views/PhysicalNetworkPort.yaml

The goal of this PR is to extract the ports table from a `PhysicalSwitch` to another page.
Depends on: ~https://github.com/ManageIQ/manageiq/pull/17593~
**BEFORE**:
**AFTER**:
The goal of this PR is to extract the `port` table from switch summary view, so the switch summary view won't be so polluted.

Extracting physical ports of a switch to a new page

---

app/javascript/components/vm-snapshot-form-component.jsx
package.json

Removed unnecessary translated strings from VmSnapshotFormComponent, because I18n is now supported inside react components(dependency version had to be updated).

Removed labels props from vm-snapshot-form-component.

---

app/decorators/manageiq/providers/ansible_tower/automation_manager/job_decorator.rb

Navigate to: Automation -> Ansible Tower -> Jobs -> select any job
**Before:**
**Afer:**
@miq-bot add_label graphics, gaprindashvili/no, bug

Add single_quad definition for ansible tower jobs

---

config/webpack/loaders.js
config/webpack/shared.js
package.json

Without it, css will get compiled into js packs, but actually works.
Pretty much taken from https://github.com/ManageIQ/manageiq-ui-classic/pull/3776/commits/c73158dde55c53fcbf5894dd23f6e698b634353d (#3776 Webpack 4)
Cc @martinpovolny 
Because we can do this now, and then css in ui plugins is as simple as importing the css in the component definition.
(Needed by https://github.com/ManageIQ/manageiq-providers-amazon/pull/462)

Remove extract-text-plugin

---

app/controllers/application_controller/performance.rb

When filter which chart should be displayed, use more safer way, which doesn't raise an exception.
https://bugzilla.redhat.com/show_bug.cgi?id=1597640
(1. Add provider I added VirtualCenter-65
2. Enabled C&U on appliance also ordered data with gap collection)
Or just have a datastore with C&U data,
3. Navigate to Datastore and wait for Utilization Enable (Datastore > Monitoring > Utilization)
4. Click on Utilization you will get an error
@romanblanco could you please review

Use safer way when filter charts

---

app/controllers/ems_common.rb
spec/controllers/ems_common_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1530259
---
**What:**
Fix _Manage policies_ button for _Container Images_ which was "not yet implemented" even if this functionality is implemented and working if not accessing Container Images through Contaier provider's summary page but directly (_Compute > Containers > Container Images_).
Fix the same problem also for _Container Replicators, Container Pods, Container Nodes_.
Fix the same "Button not yet implemented" problem for Container Replicators, Pods, Nodes and Images also for _Check Compliance of Last Known Configuration_ button.
1. Go to _Compute > Containers > Providers_
2. Choose some provider, display its summary screen
3. Under Relationships, click on _Container Images_
4. Choose some Container …

Fix Manage policies and Check compliance buttons for Container Images and others

---

app/controllers/ems_physical_infra_controller.rb

Redfish physical infra provider uses security protocol as an input to
determine how connection to the Redfish endpoint should be
established. This information is entered into the form at provider
instance creation time.
But because this information is not returned when we edit existing
provider, security protocol dropdown is initialized to an empty value.
This commit adds default_security_protocol field to the for data that
is used to populate the edit form.
This resolves the issue #4271 
/cc @matejart

Add security protocol to physical infra form data

---

app/javascript/miq-component/component-typings.ts
app/javascript/miq-component/helpers.js
app/javascript/miq-component/react-blueprint.tsx
app/javascript/packs/provider-dialogs-common.js
app/javascript/provider-dialogs/modal.js

This is a simpler version of #4231 - provider dialogs for toolbar buttons.
Only react components are supported now,
the toolbar button needs to provide (in `javascript_data`):
* `component_name` - the name of the react component, registered via `ManageIQ.component.addReact`
* `modal_title` - a N_ string, used in the title of that dialog
* (and `controller = "provider-dialogs"`)

Provider dialogs - React

---

app/views/vm_common/_snap.html.haml
package.json

Big fix for https://bugzilla.redhat.com/show_bug.cgi?id=1599661. Memory snapshot switch is now visible only when `@show_snapshot_memory_checkbox` is true.
Actual component fix is here: https://github.com/ManageIQ/react-ui-components/issues/56
@h-kataria

Fixed visible memory switch while adding snapshot for turned off vm.

---

app/views/report/_form_filter_chargeback.html.haml

This enables running daily report for a calendar month as opposed to 28 days (4 weeks)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1591217

Increase upper limit of the range for daily chargeback report to 5 weeks

---

app/assets/stylesheets/print.scss

When precompiling assets, somehow sprockets goes crazy because of this line and skips everything after. This caused issues with remote consoles that are dependent on jQuery.
Closes #4251
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1597352
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600139

Fix asset pipeline for remote consoles when loading jquery

---

app/helpers/vm_cloud_helper/textual_summary.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1583754
---
**Before:**
**After:**

Remove Snapshot field from EC2 Instance summary screen

---

app/views/shared/dialogs/_dialog_field_date_and_date_time_control.html.haml

Found this while I was testing for https://github.com/ManageIQ/ui-components/pull/317, but basically when the user submits a date/time, the request screen was simply showing the current date/time instead of the selected date/time.
This is not necessary to fix the linked BZ, but it is related and thus linked for posterity.
Related to https://github.com/ManageIQ/ui-components/pull/317
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1583177
@d-m-u Can you review, please? I changed the view to use `.value` instead of `.refresh_json_value` since now that the other backend pieces have changed, `.value` should make more sense. (Also, `.refresh_json_value` doesn't really make sense if the field isn't dynamic)

Fix date/time display on request screen

---

app/controllers/application_controller.rb
app/controllers/dashboard_controller.rb
app/controllers/ops_controller/settings/common.rb
app/views/dashboard/login.html.haml
app/views/dashboard/oidc_login.html.haml
app/views/ops/_settings_authentication_tab.html.haml
config/routes.rb
spec/controllers/dashboard_controller_spec.rb

https://www.pivotaltracker.com/n/projects/1610127/stories/121849185
The changes introduced by this PR will provide support for enabling OpenID-Connect
authentication.
This PR depends on [PR16495](https://github.com/ManageIQ/manageiq/pull/16495)
1. Install and configure Identity and Access Management server, such as [Keycloak](http://www.keycloak.org/), for the OpenID-Connect provider type
2. Install and configure the Apache module: mod_auth_openidc on the ManageIQ appliance to point to the  Identity and Access Management server configured in step 1
3. Log into the appliance as _**admin**_ and configure authentication for OpenId-Connect by checking the _**Provider Type:**_ button  **_Enable OpenID-Connect_**
4. Log out and …

Add OpenID-Connect authentication support

---

app/assets/javascripts/services/topology_service.js
app/services/physical_infra_topology_service.rb

- Set the status of the PhysicalServers and PhysicalSwitches nodes in the topology view to be relative to the entity's `health_state`.
As the picture shows, the nodes get borders in one of this colors:
- Gray: `Unknown` Health State status;
- Green: `Valid` Health State status;
- Yellow: `Warning` Health State status;
- Red: `Critical` Health State status;

Set Status of Physical Servers and Physical Switches in Topology View

---

app/helpers/application_helper/toolbar/base.rb
app/helpers/application_helper/toolbar/basic.rb
app/helpers/application_helper/toolbar/override.rb
app/helpers/application_helper/toolbar_builder.rb

We want to allow the provider authors to extend ManageIQ UI with Ansible playbooks and roles. ManageIQ core provides the capability to execute an Asible playbook from the provider repository. The ManageIQ UI provides a way to call that playbook from a toolbar. Before calling the playbook additional parameters can be collected using a custom dialog.
Related UI PRs:
* https://github.com/ManageIQ/manageiq-ui-classic/pull/4267
* https://github.com/ManageIQ/manageiq-ui-classic/pull/4231
This allows providers to extend existing toolbars by creating classes such as:
`app/helpers/manageiq/providers/amazon/toolbar_overrides/ems_cloud_center.rb` in the `manageiq-providers-amazon` repo.
```ruby
module ManageIQ
module Providers
module Amazon
module ToolbarOverrides
class EmsCloudCenter < …
```

Implement toolbar extension mechanism for providers

---

app/helpers/automation_manager_helper.rb
app/helpers/configuration_job_helper/textual_summary.rb
app/helpers/container_group_helper/textual_summary.rb
app/helpers/container_node_helper/textual_summary.rb
app/helpers/provider_configuration_manager_helper.rb
app/helpers/provider_foreman_helper.rb
app/helpers/textual_mixins/textual_vmm_info.rb
app/helpers/vm_helper/textual_summary.rb

Decorators should be the single source of truth everywhere across the UI, so let's use them in textual summaries a little bit more.
@miq-bot add_label gaprindashvili/no, refactoring, textual summaries

Replace vendor SVG references in textual summaries with decorators

---

app/presenters/tree_builder_vat.rb
spec/presenters/tree_builder_vat_spec.rb

When rendering the VMs and Templates tree for a specific provider, the root icon (provider type) is statically set as an SVG file. This can be replaced with a call to the related decorator.
@miq-bot add_label gaprindashvili/no, cleanup

Use decorator to determine the root node icon in a provider tree

---

app/decorators/manageiq/providers/automation_manager_decorator.rb

**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1601540

Add missing single_quad definition for ansible tower provider

---

app/controllers/ems_common.rb
app/controllers/physical_chassis_controller.rb
app/decorators/physical_chassis_decorator.rb
app/helpers/application_helper.rb
app/helpers/application_helper/listnav.rb
app/helpers/ems_physical_infra_helper/textual_summary.rb
app/helpers/physical_chassis_helper.rb
app/helpers/physical_chassis_helper/textual_summary.rb
app/helpers/physical_rack_helper/textual_summary.rb
app/helpers/physical_server_helper/textual_summary.rb
app/presenters/menu/default_menu.rb
app/views/layouts/listnav/_physical_chassis.html.haml
app/views/physical_chassis/show.html.haml
app/views/physical_chassis/show_list.html.haml
config/routes.rb
product/views/PhysicalChassis.yaml
spec/controllers/physical_chassis_controller_spec.rb
spec/helpers/physical_chassis_helper/textual_summary_spec.rb

- Add to the Left Menu _Compute_ > _Physical Infrastructure_ > **Chassis**;
- Add a **Physical Chassis** list page;
- Add a **Physical Chassis** details page;
- Adds the references to **Physical Chassis** in **Providers** Details page, **Physical Server** Page, and **Physical Rack** Page.
**Depends on:**
- ~[ManageIQ/manageiq#17523](https://github.com/ManageIQ/manageiq/pull/17523)~ [MERGED]

Adds Physical Chassis List & Details pages

---

app/helpers/reactjs_helper.rb

The `tag` method sometimes behaves weird (maybe a rails bug) and doesn't close the tags. This can break the whole DOM and e.g. hide the left side tree when creating a tenant.
Closes #4273
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1593152

Make sure that react helper always closes the div tag

---

app/helpers/textual_mixins/textual_region.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1602095
1.) Configure an appliance in region 0 as a remote appliance and an appliance in region 99 as the global appliance.
2.) Add an infrastructure provider to the remote appliance.
3.) View one of the provider's VM's in the global appliance's web UI.
Or a little hack in code:
```diff
--- a/app/helpers/textual_mixins/textual_region.rb
+++ b/app/helpers/textual_mixins/textual_region.rb
module TextualMixins::TextualRegion
def textual_region
-    return nil if @record.region_number == MiqRegion.my_region_number
+    #return nil if @record.region_number == MiqRegion.my_region_number
h = {:label => _("Region")}
reg = @record.miq_region
-    url = reg.remote_ui_url
+    url = "reg.remote_ui_url"
```
Click at `Region` and …

Fix link in textual_region

---

app/assets/javascripts/controllers/network_router/network_router_form_controller.js
app/controllers/network_router_controller.rb
app/views/network_router/_common_new_edit.haml
config/routes.rb
spec/controllers/network_router_controller_spec.rb

Networks > Network Routers
Replaces http calls in RoR controller by API calls 
See https://github.com/ManageIQ/manageiq-ui-classic/issues/737
Also:
* Filtering only external network and subsequently better proper subnet (floating IPs) handling.
* External gateway displays only when external management provider id has been selected
* Changes source NAT field position as it depends on the network id
* Adds administrative state field
Before:
Now:

Network Router: Use API; Fix fixed IPs subnet

---

app/javascript/forms/form-buttons-redux.jsx
app/javascript/forms/form-buttons.jsx
app/javascript/forms/miq-button.jsx
app/javascript/packs/component-definitions-common.js
app/javascript/provider-dialogs/modal.js
package.json

This is in preparation of having React forms in ui-classic, and adds several components:
* `MiqButton` - a react reimplementation of our angular miqButton (1:1 except `alt` is implied when `title` is set) - shows a button with enabled/disabled, titles, and actions
* `FormButtons` - a react implementation of our angular `generic_form_buttons` partial - does not deal with finding out the form state but when it gets it, it renders the buttons
* `FormButtonsRedux` - a wrapper for FormButtons which uses Redux for state management (so that we can trigger actions from anywhere, including angular forms)
---
The idea is that `FormButtonsRedux` will live in the "paging" toolbar, and the forms will be sending redux actions to tell the buttons what to show, and those buttons will be sending back …

FormButtons component, with redux

---

app/assets/javascripts/application.js
app/assets/javascripts/gettextCatalog.js
app/assets/javascripts/miq_angular_application.js
package.json

This PR:
* adds `angular-gettext` into ManageIQ
* adds overrides for `gettextCatalog`: an internal mechanism of angular-gettext to retrieve i18n strings from catalogs. For our purposes (read: `ui-components`) we want to use `__()` and `n__()` instead of angular-gettext's native catalog / strings mechanism.
This needs to go into gaprindashvili as well, as it supports other i18n work in ui-components.
@himdel review please?
https://bugzilla.redhat.com/show_bug.cgi?id=1592571

Add angular gettext and make translation directive working

---

app/controllers/report_controller/reports/editor.rb
app/views/report/_form_filter_chargeback.html.haml

**Related RFE:** https://bugzilla.redhat.com/show_bug.cgi?id=1584018
This PR adds a new _Cumulative Rate Calculation_ checkbox to Report editing screen under _Cloud Intel > Reports > Reports_.
---
**Before:**
Choosing _Chargeback for Images/Projects_ as Report base:
Choosing _Chargeback for Vms_ as Report base:
**After:**
Choosing _Chargeback for Images/Projects_ as Report base:
Choosing _Chargeback for Vms_ as Report base:
---
**Note:**
When choosing other Report base, no change for adding/editing a Report.

Add new Cumulative Rate Calculation checkbox to Report editing screen

---

app/controllers/miq_policy_controller/alerts.rb
app/views/miq_policy/_alert_details.html.haml
spec/controllers/miq_policy_controller/alerts_spec.rb

As per https://bugzilla.redhat.com/show_bug.cgi?id=1578115#c26 in BZ removed an option to be able to set/display 'Driving Event' field when adding/editing an Alert that's based on 'Container Node' or 'Container Project' models.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1578115
before:
after:

Hide Driving Event field for Containers.

---

app/controllers/provider_foreman_controller.rb

I'm doing stuff in the GTL area ant this call seems unused and unnecessary. All these things go through the `report_data` call and it's always a separate request. @AparnaKarve could you please verify?
@miq-bot add_reviewer @AparnaKarve 
@miq-bot add_label celanup, gaprindashvili/no, GTLs, configuration management

Remove the unnecessary view_to_hash call from Foreman controller

---

app/views/layouts/remote_console.html.haml
app/views/vm_common/console_vmrc.html.haml
app/views/vm_common/console_webmks.html.haml
config/initializers/assets.rb

After examining the `public/assets/.sprockets-manifest.json` file on an appliance, I deduced that this might fix the missing jquery issue for remote consoles.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600139
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1597352

Fix path to jQuery when loading it separately for remote consoles

---

app/assets/javascripts/controllers/ems_infra_dashboard/utilization_trend_chart_controller.js

related to: https://github.com/ManageIQ/manageiq-ui-classic/pull/3837#discussion-diff-204454125R1

Fix a wrong paramenter being inject into infra dashboard

---

app/controllers/application_controller.rb
spec/controllers/flavor_controller_spec.rb

This fix is to make sure `@search_text` is not rendered on non-gtl screens.
1. Navitage to Cloud -> Flavors
2. Enter quick search text
3. Navigate to Cloud -> [a cloud provider] -> Flavors -> [a flavor]
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1579753

Fix search text on non gtl screens

---

app/views/generic_mailer/policy_action_email.html.haml
app/views/generic_mailer/policy_action_email.text.haml

Part of https://github.com/ManageIQ/manageiq/pull/17673
This allows extra details to be part of notification emails

Event Details for notification emails

---

app/controllers/network_router_controller.rb
app/helpers/floating_ip_helper/textual_summary.rb
app/helpers/network_router_helper/textual_summary.rb
app/views/network_router/show.html.haml

With this commit we enhance UI with relation between NetworkRouter and FloatingIp (and vice versa):
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574922

Display "FloatingIp belongs to NetworkRouter" relation

---

app/controllers/cloud_tenant_controller.rb
app/helpers/cloud_tenant_helper/textual_summary.rb

With this commit we add **Properties** group where Name and Description are visible to user:
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574903

Make name and description visible on CloudTenant details page

---

app/controllers/physical_chassis_controller.rb
app/controllers/physical_rack_controller.rb

Wrong list of components is shown when click on link in summary table.
If we take this physical chassis as example, we can see only one physical server inside this component:
__Current result__
10 physical servers are shown
__After this PR__
Only the right physical server is shown
This error also occurs in physical rack page.

Fixing display of subcollections of physical components

---

app/assets/javascripts/application.js

Analogous with https://github.com/ManageIQ/manageiq-ui-classic/pull/4329, this is needed if we want to load it properly from npm.

Fix path to jQuery in application.js

---

app/controllers/ems_common.rb
app/controllers/physical_chassis_controller.rb
app/controllers/physical_rack_controller.rb
app/controllers/physical_storage_controller.rb
app/decorators/physical_storage_decorator.rb
app/helpers/application_helper.rb
app/helpers/application_helper/listnav.rb
app/helpers/application_helper/toolbar/physical_storage_center.rb
app/helpers/application_helper/toolbar/physical_storages_center.rb
app/helpers/application_helper/toolbar_chooser.rb
app/helpers/ems_physical_infra_helper/textual_summary.rb
app/helpers/physical_rack_helper/textual_summary.rb
app/helpers/physical_storage_helper.rb
app/helpers/physical_storage_helper/textual_summary.rb
app/presenters/menu/default_menu.rb
app/services/ems_physical_infra_dashboard_service.rb
app/services/ui_service_mixin.rb
app/views/layouts/listnav/_ems_physical_infra.html.haml
app/views/layouts/listnav/_physical_storage.html.haml
app/views/physical_rack/show.html.haml
app/views/physical_storage/show.html.haml
app/views/physical_storage/show_list.html.haml
config/routes.rb
product/views/PhysicalStorage.yaml
spec/controllers/physical_storage_controller_spec.rb
spec/helpers/physical_storage_helper/textual_summary_spec.rb

- Add PhysicalStorages to dashboard view
- Add PhysicalStorages list page
- Add PhysicalStorages summary page
Depends on:
- ~[ManageIQ/manageiq-schema#224](https://github.com/ManageIQ/manageiq-schema/pull/224)~ [Merged]
- ~[ManageIQ/manageiq#17616](https://github.com/ManageIQ/manageiq/pull/17616)~ [Merged]
- ~[ManageIQ/manageiq-providers-lenovo#201](https://github.com/ManageIQ/manageiq-providers-lenovo/pull/201)~ [Merged]
- ~[ManageIQ/manageiq#17586](https://github.com/ManageIQ/manageiq/pull/17586)~ [Merged]
- ~[ManageIQ/manageiq-api#397](https://github.com/ManageIQ/manageiq-api/pull/397)~ [Merged]
- ~[ManageIQ/manageiq-ui-classic#4065](https://github.com/ManageIQ/manageiq-ui-classic/pull/4065)~ [Merged]
**Storage Menu:**
**Storage On Physical Infra Provider …

Adding PhysicalStorages list and summary pages

---

app/controllers/application_controller/buttons.rb
spec/controllers/application_controller/buttons_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1603080
Make sure that for no Dialog `@edit[:new][:dialog_id]` is set to `nil` and `0` or `""`
1.Navigate to Automation -> Automate -> Customization
2. Click on Buttons and select any Object Types.
3. Click on configuration and select 'Add a new button'.
4. Fill in details, BUT don't select any `Dialog`.
5. Click on `Add`.
Try to Edit any button to not to have Dialog as well.
Before:
```
Error caught: [ActiveRecord::RecordNotFound] Couldn't find Dialog with 'id'=0
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.7/lib/active_record/core.rb:173:in `find'
/Users/zita/Desktop/ManageIQ/manageiq-ui-classic/app/controllers/application_controller/buttons.rb:932:in `button_set_resource_action' …
```

Fix custom button without dialog

---

app/views/layouts/exp_atom/_edit_find.html.haml

https://bugzilla.redhat.com/show_bug.cgi?id=1607361
1. Navigate to Control/Explorer.
2. Expand Conditions tab.
3. Start to create a condition.
4. In "Edit Selected Element" choose "Find" from the dropdown.
Before
After
introduced by #4171 
@miq-bot add_label gaprindashvili/no, bug

Fix find in expression editor

---

app/controllers/cloud_subnet_controller.rb
app/helpers/cloud_subnet_helper/textual_summary.rb
app/views/cloud_subnet/show.html.haml

With this commit we provide the missing link on CloudSubnet details page:
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574927

Display "CloudSubnet has many NetworkPorts" relation

---

app/helpers/physical_switch_helper/textual_summary.rb

Fix the link for Physical Network Ports of Physical Switch summary page.
@miq-bot add_label compute/physical infrastructure

Fixing link for physical switches ports

---

app/services/physical_infra_topology_service.rb

- Set the status of the PhysicalChassis and PhysicalStorage nodes in the topology view to be relative to the entity's `health_state`;
- Set the status of the Hosts nodes in the topology view to be relative to the entity's `state`;
- Set the status of the Vms nodes in the topology view to be relative to the entity's `power_state`.
Note: Physical Chassis and Physical Storage were added because as soon as they are added to the topology, the status border will work for them.
As the picture shows, the nodes get borders in one of this colors:
- Gray => `Unknown` Health State status (Chassis/Storage) or Power State status (Host/VM);
- Green => `Valid` or `On`;
- Yellow => `Warning`;
- Red => `Critical`;

Set the Status of some topology nodes

---

app/controllers/cloud_network_controller.rb
app/helpers/cloud_network_helper/textual_summary.rb
app/helpers/floating_ip_helper/textual_summary.rb
app/views/cloud_network/show.html.haml

With this commit we enhance CloudNetwork details page with "Floating Ips" relation as well as FloatingIp's details page with "Cloud Network" relation.
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574922

Display "FloatingIp belongs to CloudNetwork" relation

---

app/helpers/quadicon_helper.rb

*  Fix the health state quadicon not shown the warning icon and unknown icon when a resource have one these states

Fix the health_state quadicon

---

app/assets/javascripts/components/cloud_subnet/cloud-subnet-form.js
app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
app/assets/javascripts/controllers/cloud_tenant/cloud_tenant_form_controller.js
app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
app/assets/javascripts/controllers/cloud_volume_backup/cloud_volume_backup_form_controller.js
app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-details-no-provider-controller.js
app/assets/javascripts/controllers/container_deployment/deploy_provider/deploy-provider-master-nodes-controller.js
app/assets/javascripts/controllers/ems_infra_dashboard/heatmap_controller.js
app/assets/javascripts/controllers/ems_infra_dashboard/utilization_trend_chart_controller.js
app/assets/javascripts/controllers/ems_physical_infra_dashboard/server_health_pie_chart_controller.js
app/assets/javascripts/controllers/host_aggregate/host_aggregate_form_controller.js
app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
app/assets/javascripts/controllers/security_group/security_group_form_controller.js
app/assets/javascripts/controllers/vm_cloud/vm_cloud_attach_form_controller.js
app/assets/javascripts/controllers/vm_cloud/vm_cloud_detach_form_controller.js

https://bugzilla.redhat.com/show_bug.cgi?id=1523326

Add missing gettext into angular controllers

---

spec/controllers/mixins/ems_common_angular_spec.rb

Fix the broken spec as a result of the backport in https://github.com/ManageIQ/manageiq-ui-classic/pull/3913

[GAPRINDASHVILI] remove `use_broker` expectations to fix the spec

---

app/helpers/application_helper/listnav.rb
spec/views/layouts/listnav/_floating_ip.html.haml_spec.rb

Instead of `record.class.name.demodulize.titleize` we need to use `ui_lookup()`, which would return proper model's display name (plus we get i18n with it).

Use ui lookup for model name in listnav

---

app/helpers/application_helper/toolbar/vm_infras_center.rb
app/helpers/application_helper/toolbar/x_vm_center.rb

Remove 'Transform tagged VMs to RHV' and 'Transform this VM to RHV' from
the toolbar.
Partially fixes https://bugzilla.redhat.com/show_bug.cgi?id=1585452

Remove VM Transform buttons

---

app/assets/javascripts/application.js
app/javascript/packs/application-common.js
config/webpack/shared.js

When running in production, there is a warning in the console:
```
You are currently using minified code outside of NODE_ENV === 'production'.
This means that you are running a slower development build of Redux.
You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify
or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) 
to ensure you have the correct code for your production build.
```
That warning is present in both redux and ng-redux, but appears only because we're using the pre-built version of ng-redux, which was built with the development environment.
So... moving ng-redux to webpack so that we compile our own environment-dependnent version.
---
Also changed how we expose the environment - previously, for some reason we would take all …

Remove Redux environment warning in production

---

.scrutinizer.yml

`ruby-scrutinizer-run` runs too long for some reason and Scrutinizer times out after a while.
So skipping `ruby-scrutinizer-run` for now.

Disable ruby-scrutinizer-run to prevent time out of Scrutinizer

---

app/javascript/miq-component/helpers.js
app/javascript/miq-component/helpers.spec.jsx
app/javascript/miq-component/react-blueprint.tsx

When page is reloaded using ajax, and part of the DOM, in which was some react component is changed, the component will remain in virtual DOM and can sometimes break the UI (if you are using some RxJS or Redux features).
I have added a simple function, that will clear all component instances, which don't have their mounting element in DOM.
(I have also changed the import statements in helpers, because linter was driving me mad)

Added helper that clears all unused react components from virtual DOM.

---

app/controllers/service_controller.rb
app/helpers/service_helper/textual_summary.rb
app/views/layouts/_textual_groups_tabs.html.haml
app/views/service/_svcs_show.html.haml

Make the service layout same for AnsibleTower as it is for EmbeddedAnsible - UI
- **FIX**: There happen to be duplicate IDs when `layout/textual_groups_tabs` is used for multiple times (or along with `layouts/textual_groups_generic`).
- Make the _Details_ tab the same for both service types
- Add a new tab called _Job_ which displays as much of the same info as the EmbeddedAnsible shows on _Provisioning_ or _Retirement_ tabs
Depends on (merge in this order):  https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/108 https://github.com/ManageIQ/manageiq/pull/17712
Fixes: [BUG 1590840](https://bugzilla.redhat.com/show_bug.cgi?id=1590840) [BUG 1590844](https://bugzilla.redhat.com/show_bug.cgi?id=1590844)
Before:
After:

Service AnsibleTower and EmbeddedAnsible UI parity

---

app/decorators/storage_decorator.rb

Location: `Compute` -> `Infrastructure` -> `Datastores`
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1608461
@miq-bot add_label bug, gaprindashvili/no, graphics

Display the correct quadicon for NTFS datastore entities

---

app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb

Offers only floating IPs which are not used by a VM 
https://bugzilla.redhat.com/show_bug.cgi?id=1595767

VM: associate only unused floating IPs

---

app/controllers/ansible_repository_controller.rb
app/helpers/ansible_repository_helper/textual_summary.rb
app/views/ansible_repository/_output.html.haml
app/views/ansible_repository/show.html.haml
spec/controllers/ansible_repository_controller_spec.rb

Create a custom display mode for Ansible Repository show page with last refresh output capture. If an Ansible Tower Repository has this capture from its last failed refresh, the Status row becomes a link to this subpage.
Presenting this information is a workaround for cloning repositories from HTTPS servers with untrusted SSL certificates. Tower API does not offer an option to disable SSL check, so with the stdout user can at least see, why the cloning actually failed.
Along with RSpec examples for this feature, refactor a bit other tests related to the page refresh button:
* Increase test coverage of the AJAX content replacement used
* Test Playbooks nested list subpage
* Rename examples with rather misleading titles
https://bugzilla.redhat.com/show_bug.cgi?id=1513616
Prior merging this …

Add Ansible Repository refresh output page

---

jest.config.js

with jsDom 11.12, jest starts failing with
Test suite failed to run
SecurityError: localStorage is not available for opaque origins
at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
at Array.forEach (<anonymous>)
Looks like jsdom is just trying to follow the browser behaviour more closely, and without `testURL` jest defaults to assuming "about:blank".
Providing a sane url fixes it.
https://github.com/facebook/jest/issues/6766
https://github.com/jsdom/jsdom/issues/2304#issuecomment-408320484

Jest - fix "SecurityError: localStorage is not available for opaque origins"

---

app/views/ops/_rbac_group_details.html.haml
spec/views/ops/_rbac_group_details.html.haml_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1609321
This PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/2855 added support
for OpenID-Connect to the manageiq-ui-classic.
The "Lookup Groups" is not supported with OIDC. This PR ensures the Lookup
Groups checkbox is not displayed when OIDC is enabled.
* This PR is similar to this one: https://github.com/ManageIQ/manageiq-ui-classic/pull/3881 and is needed now that OIDC support has been added to the UI 
Configuration -> Settings -> select Current Server -> Authentication -> Mode -> set to Amazon/Database/External with OIDC enabled
Navigate to
Configuration -> Access Control -> Create a new Group
Ensure the "(Look up External …

Ensure Look up groups checkbox is not shown when OIDC is enabled.

---

app/helpers/physical_chassis_helper/textual_summary.rb
app/views/physical_chassis/show.html.haml
spec/helpers/physical_chassis_helper/textual_summary_spec.rb

- Add Physical Storages reference to Physical Chassis summary page

Adding Physical Storages to Physical Chassis summary page

---

app/assets/javascripts/controllers/timeline/timeline_options_controller.js
app/assets/javascripts/miq_timeline.js
app/controllers/application_controller/timelines.rb
app/controllers/application_controller/timelines/options.rb
app/views/layouts/_tl_options.html.haml
lib/report_formatter/timeline.rb
spec/controllers/application_controller/timelines_spec.rb
spec/lib/report_formater/timeline_spec.rb

* Refactor the timeline page to support filter events using the group_levels
* Color the event accordingly the severity
* Color the `Group Level` information accordingly the severity
Depends_on:  [~PR 17611~](https://github.com/ManageIQ/manageiq/pull/17611) - MERGED
Depends_on: [~PR 17702~](https://github.com/ManageIQ/manageiq/pull/17702) - MERGED

adding support to filter events by new group levels

---

package.json

3.53 started depending on newer version of node than we can build with
forcing the dependency to 3.52 so that we can build
this is a temporary fix pending the resolution of https://github.com/patternfly/patternfly/issues/1113
Cc @simaishi

Depend on patternfly 3.52.3 - do not upgrade

---

app/controllers/vm_common.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1610466
---
**What:**
_Save_ button in editing screen of VM is not responsive: it remains enabled even if no change was made (of if there is nothing to save).
**Why:**
The problem was that if `changed` variable was set to `false`, no update for _Save_ button visibility was made. That's ok BUT what if _Save_ button was enabled before and needs to be disabled now? This situation was not implemented in the code and it is simply fixed by removing condition `if changed` which is unnecessary and caused the bug.
1. Go to _Compute > Infra > VMs_ (or to any page with VMs list screen)
2. Click on some VM or check the checkbox
3. _Configuration > Edit Selected item/Edit this VM_
4. Make some change(s) in _Basic …

Fix unresponsive Save button while editing VM

---

app/services/physical_infra_topology_service.rb
app/services/topology_service.rb
app/services/ui_service_mixin.rb
app/views/physical_infra_topology/show.html.haml
spec/services/physical_infra_topology_service_spec.rb

- Add Chassis nodes to Physical Infra topology page.

Add Physical Chassis nodes to Physical Infra Topology

---

app/assets/javascripts/components/ansible-raw-stdout.js

The "JS ids can't be numbers in region >9006" is here again, this is the same fix as https://github.com/ManageIQ/manageiq-ui-classic/pull/3243, but for `ansible-raw-stdout`.
https://bugzilla.redhat.com/show_bug.cgi?id=1610353

ansible-raw-stdout: parse task id as string, not number

---

app/controllers/application_controller/tags.rb
app/controllers/automation_manager_controller.rb
app/controllers/catalog_controller.rb
app/controllers/mixins/manager_controller_mixin.rb
app/decorators/configuration_script_decorator.rb
app/decorators/manageiq/providers/ansible_tower/automation_manager/configuration_workflow_decorator.rb
app/helpers/application_helper.rb
app/helpers/application_helper/toolbar/configuration_script_center.rb
app/helpers/application_helper/toolbar/x_configuration_script_center.rb
app/presenters/tree_builder.rb
app/presenters/tree_builder_automation_manager_configuration_scripts.rb
app/presenters/tree_node/configuration_script_base.rb
app/views/automation_manager/explorer.html.haml
app/views/catalog/_form_basic_info.html.haml
app/views/catalog/_sandt_tree_show.html.haml
app/views/layouts/print/textual_summary.html.haml
product/views/ConfigurationScript.yaml
product/views/ConfigurationScriptBase.yaml
spec/controllers/automation_manager_controller_spec.rb
spec/presenters/tree_node/configuration_script_base_spec.rb

Changes to show list of Job Templates and Configuration Workflows in existing UI under Automation/Ansible Tower/Explorer in Templates Accordion.
https://bugzilla.redhat.com/show_bug.cgi?id=1590441
before:
after:
Depends on https://github.com/ManageIQ/manageiq/pull/17720

Show Configuration Workflows in UI

---

app/javascript/miq-redux/middleware.ts
app/javascript/miq-redux/store.js

the actual problem was that composeEnhancers is only supposed to work with enhancers, not middleware (even though the vanilla redux composer function seems to work)
and applyMiddleware is the function to convert one or more middlewares into an enhancer
---
Testing:
* have the redux-devtools-extension (http://extension.remotedev.io/) installed in the browser
* load manageiq
* look at `ManageIQ.redux.store.dispatch`
Before:
Since https://github.com/ManageIQ/manageiq-ui-classic/pull/4380, `store.dispatch` was **not** a function but an object containing a dispatch function.
After:
`ManageIQ.redux.store.dispatch` is a function
---
Cc @karelhala 
Cc @martinpovolny - this should fix the problems you've seen in https://github.com/ManageIQ/manageiq-ui-classic/pull/4315

Redux - fix store.dispatch not being a function

---

app/controllers/application_controller.rb
app/controllers/application_controller/report_data_additional_options.rb
app/controllers/infra_networking_controller.rb
app/controllers/vm_common.rb
spec/controllers/host_controller_spec.rb
spec/controllers/service_controller_spec.rb
spec/controllers/storage_controller_spec.rb

Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/3243 and https://github.com/ManageIQ/manageiq-ui-classic/pull/4397 and https://github.com/ManageIQ/manageiq-ui-classic/pull/2902.
Trying to make sure `parent_id` always ends up as a string in JS, not a number.
https://bugzilla.redhat.com/show_bug.cgi?id=1610353
Cc @skateman

Fix parent_id being a number, not string in JS

---

app/assets/javascripts/services/topology_service.js
spec/javascripts/services/topology_service_spec.js

Since https://github.com/ManageIQ/manageiq-ui-classic/pull/4284, our urls can end with a hash + a route.
But the topology "where am I" url parsing code failed to take that into account, resulting in gets for undefined urls:
angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:14962 Error: [$http:badreq] Http request configuration url must be a string or a $sce trusted object.  Received: undefined
https://errors.angularjs.org/1.6.10/$http/badreq?p0=undefined
at angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:126
at $http (angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:12345)
at Function.$http.(anonymous function) [as get] (http://localhost:3000/assets/angular/angular.self-f52e96200e93eab5e5989b1cf …

Topology screens - fix parseUrl to deal with hash router

---

app/helpers/application_helper/button/generic_feature_button_with_disable.rb
spec/helpers/application_helper/buttons/generic_feature_button_with_disable_spec.rb

**Make some disabled toolbar buttons visible** which weren't visible but
they should be. The core of the problem was class inheritance.
For many toolbar buttons found under _app/helpers/application_helper/toolbar_, there is
`:klass   => ApplicationHelper::Button::GenericFeatureButtonWithDisable,`.
We would expect that if a feature was not supported, the button would be just disabled - but this is not true. The button was not visible at all. This PR fixes this problem the simle way.
**Before:**
**After:**

Fix visibility of toolbar buttons

---

app/controllers/physical_chassis_controller.rb
app/helpers/application_helper/toolbar/physical_chassis_list_center.rb
app/helpers/application_helper/toolbar/physical_chassis_summary_center.rb

- Add Location LED actions for Physical Chassis:
- blink_loc_led;
- turn_on_loc_led;
- turn_off_loc_led.
__Depends on__
~https://github.com/ManageIQ/manageiq/pull/17668~ - Merged
~https://github.com/ManageIQ/manageiq-ui-classic/pull/4065~ - Merged
~https://github.com/ManageIQ/manageiq-api/pull/410~ - Merged

Adding Physical Chassis Location LED actions

---

app/controllers/dashboard_controller.rb
config/routes.rb
package.json
spec/controllers/dashboard_controller_spec.rb

Increase version of react-ui-components (needed for demo).
Implement `/dashboars/dialog_definition` with tests.
Extracted from https://github.com/ManageIQ/manageiq-ui-classic/pull/4315 with added specs.

Towards provider plugins: dialog definition action

---

app/javascript/miq-redux/middleware.ts
app/javascript/packs/application-common.js
package.json

This is related to https://github.com/ManageIQ/manageiq-ui-classic/pull/4361#issuecomment-409544861. In order to merge our stores and routing, we need to add this middleware to enable v2v async redux actions. Fortunately it does not break our async actions :).

Added promise middleware, to enable v2v redux-actions.

---

app/controllers/chargeback_controller.rb
app/views/chargeback/_cb_assignments.html.haml
spec/controllers/chargeback_controller_spec.rb

Behaviour:
**Before:**
It was possible to save just assignment for **Tagged VMs and Instances** only for **ONE** Tag Category 
**After:**
It is possible to save it also for multiple categories:
**Implementation details**
`@edit[:cb_assign][:tags]` as you can see in
code(`@edit[:cb_assign][cb_assign_key]`) is bringing
selected chargeback rates for tags in selected tag category which is
stored in `@edit[:new][:cbtag_cat]`
to keep selected chargeback rates for any count of tag categories
we need to extend `@edit[:cb_assign][:tags]`  to
`@edit[:cb_assign][:tags] [category_id]`  and this hash can
keep multiple chargeback rates across any count of
tag categories.
we need to update code when chargeback rate is
selected (  in method `cb_assign_params_to_edit` called by
controller action …

Allow to save multiple tag categories in chargeback controller

---

app/assets/javascripts/application.js
app/javascript/packs/application-common.js
bower.json
config/jest.setup.js
package.json

we're using https://github.com/alexei/sprintf.js
upgrading from 1.0.3 to 1.1.1 and moving to npm
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/3734

bower to npm: sprintf

---

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
app/views/catalog/_st_angular_form.html.haml
spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js

https://bugzilla.redhat.com/show_bug.cgi?id=1482905
Description of problem:
Unable to add Long Description for Playbook based Catalog Items 
1. look at the service catalog, there's a line that says "long description"
2. go to the catalog item and try to edit it
3. there is a now way how to edit it
Before/After
Before
After

Add long_description field into Ansible Playbook catalog item form

---

app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

An extension of https://github.com/ManageIQ/manageiq-ui-classic/pull/4404, this adds all the `Service` class's descendants to the list of object types that are supported by custom buttons.
https://bugzilla.redhat.com/show_bug.cgi?id=1611527
@miq-bot add_label gaprindashvili/yes, bug, blocker, services, angular dialogs
/cc @tinaafitz

Support all service types for dialog buttons

---

app/controllers/physical_switch_controller.rb
app/helpers/physical_switch_helper/textual_summary.rb
app/views/physical_switch/show.html.haml
spec/helpers/physical_switch_helper/textual_summary_spec.rb

- Add a new table to physical switch page to list the connected components;
- Add the list of connected physical servers (that are the unique component that we track the connections, for now);
__Depends on__
~https://github.com/ManageIQ/manageiq/pull/17735~ - Merged

Adding connected physical servers to physical switches page

---

app/views/ops/_settings_import_tags_tab.html.haml

Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1538109

Fix text truncation issue on tags import screen

---

app/views/miq_ae_customization/_dialog_sample.html.haml

Dialog sample screen: apply selectpicker class to dropdown select

---

app/views/miq_ae_class/_ns_details.html.haml

Don't render table header for empty automate domain and namespace

---

app/controllers/application_controller.rb

If a cockpit worker is running, the redirection to the proxy URL is being handled by the dashboard controller. The reason behind this is unknown, but I found out that the `handle_remember_tab` is being called with the `cockpit_redirect` action. This causes the session to store this action for the next time the user clicks on the cloud intel in the menu.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1585569

Do not store cockpit_redirect when remembering tabs on dashboard

---

app/assets/javascripts/remote_consoles/spice.js
bower.json
package.json

this is our spice-html5-rails fork for bower + npm - https://github.com/himdel/spice-html5-bower
Still using the asset pipeline for this one, only changing the download tool.
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/3734

bower to npm - spice-html5-bower

---

app/helpers/textual_multilabel.rb
spec/helpers/textual_multilabel.rb

Fixes https://github.com/ManageIQ/manageiq-ui-classic/pull/4111#issuecomment-410827292 + a test.

TextualMultilabel: fix: s/values/rows.

---

app/helpers/reactjs_helper.rb

Sometimes it might be required to add some additional attributes to react mounting html tag (like `class` for instance)

Added option to add additional attributes react html tag.

---

app/javascript/packs/component-definitions-common.js

Sometimes when using imported `addReact` instead of the public interface `ManageIQ.component.addReact`, webpack will create separate instances and of component registry, and they will not be rendered in UI.
Using the public registry fixes the issue.

Use public interface for registering react components.

---

app/helpers/textual_mixins/textual_devices.rb
spec/helpers/textual_mixins/textual_devices_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536711
Disk size formatting was lost in https://github.com/ManageIQ/manageiq-ui-classic/pull/752. Code was changed from 
https://github.com/ManageIQ/manageiq-ui-classic/pull/752/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eL1243
to https://github.com/ManageIQ/manageiq-ui-classic/pull/752/files#diff-0477435a7227f32a30f48f81a7b52afcR43
before:
after:

Fixed format of Disk size for a VM

---

app/views/ops/_settings_authentication_tab.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1475891
This is a very simple PR that will clarify what is being retrieved when a checkbox is activated.
The wording of the authorization checkbox titled: _Get Roles from Home Forest_ is confusing
for a couple of reasons.
1. It causes _Groups_ not _Roles_ to be retrieved.
2. The term _Forest_, although a bit misleading to AD purists, was likely chosen initially due to the similarity to the functionality for LDAP and AD. Since  the term _Forest_ has been used generically here it will stay.
The term _Roles_ is not correct and will be changed to _Groups_
Navigate to Configuration->Authentication and select mode **LDAP** or **LDAPS**
Check the box _Get User Groups from LDAP_
Note the wording …

Reword Get Roles to Get Groups from Home Forest.

---

app/views/ops/_settings_evm_servers_tab.html.haml
app/views/ops/_settings_smartproxy_affinity_tab.html.haml
app/views/ops/_zone_form.html.haml

`settings_smartproxy_affinity_tab` and `settings_evm_servers_tab` are included only from `app/views/ops/_all_tabs.html.haml` and that already has the `flash_msg` div in that context.
`zone_form` is only called from `app/controllers/ops_controller.rb` `settings_replace_right_cell` and in that context the `replace_right_cell` replaces `flash_msg_div` separately.

Fix duplicate DOM id in Settings Zone and Server

---

app/assets/javascripts/services/event_notifications_service.js
spec/javascripts/services/event_notifications_service_spec.js

This has never been used and there is no suitable backend to display anything here, so hiding it.
@miq-bot add_label gaprindashvili/yes, fine/yes
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1612002

Hide tasks from the notification drawer

---

app/controllers/chargeback_controller.rb
spec/controllers/chargeback_controller_spec.rb

Move condition inside method in ChargebackController
follow up of https://github.com/ManageIQ/manageiq-ui-classic/pull/4311
to make sure that @edit[:cb_assign][:docker_label_values] is initialized.
It was causing other error log
and
**Fix saving labels in Chargeback assigments for multiple categories**
Similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/4310 but this is for containers labels.
Fix saving labels for mutliple label categories
add new array @edit[:cb_assign][:docker_label_values_saved]
to keep selected categories.
**After:**
Links
* https://github.com/ManageIQ/manageiq-ui-classic/pull/4311
* https://bugzilla.redhat.com/show_bug.cgi?id=1612889

Fix saving of multiple container images label in Chargeback assignments

---

config/webpack/shared.js

without this, when the same file is included from multiple packs (webpack entrypoints), it will get run separately for each
this is because each bundle has its own copy of the webpack runtime, which deals with this "has it run yet" logic
this change causes the webpack runtime to only be emitted once, and shared by the other packs
thus, multiple imports of the same package should run it only once again, regardless of whether this happens within one pack or accross multiple packs
Caused by & more info in: https://github.com/ManageIQ/manageiq-ui-classic/pull/3776 (from https://github.com/ManageIQ/manageiq-ui-classic/pull/3776#issuecomment-411060992 on, https://github.com/ManageIQ/manageiq-ui-classic/pull/3776#issuecomment-411368111 specifically)
Cc @Hyperkid123

Webpack4 - emit webpack runtime chunk only in the vendor bundle, not in every one

---

app/views/chargeback/_cb_assignments.html.haml

Depends on (needs to be merged first)
-------------
HELP with visibility, what is saved for this task:
https://bugzilla.redhat.com/show_bug.cgi?id=1612889 

Show saved tag and label in chargeback assigments

---

app/controllers/orchestration_stack_controller.rb
spec/controllers/orchestration_stack_controller_spec.rb

Before, we'd be mistakenly rendering name of it's stack.
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1601523

Correctly render orchestration template's name

---

app/controllers/miq_policy_controller/alerts.rb

This minimalistic patch makes sure that any empty event group levels can be left out of the configuration file instead of requiring an empty array in that place.

Allow skipping empty event group levels

---

app/views/static/ae_resolve_options/ae-resolve-options-component.html.haml

This PR fixes a problem where the bootstrap-select dropdown was being hidden under the toolbar by setting the data-container to "body."
https://bugzilla.redhat.com/show_bug.cgi?id=1613934
Old
New

Fix Object Attribute Type dropdown

---

app/services/ems_dashboard_service.rb

Vastly improves the `/ems_cloud_dashboard/aggregate_status_data/:id` route.
Benchmarks
----------
**Before**
```
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 12581ms
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 11285ms
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 11794ms
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 11783ms
```
**After**
```
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 921ms
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 481ms
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 273ms
GET    '/ems_cloud_dashboard/aggregate_status_data/:id' 390ms
```
Data run with a DB on my local machine using a small Amazon provider with ~77k images (most of them probably public images).
Background
----------
`.length` on …

Use .count, not .length, for better performance

---

app/assets/javascripts/application.js
app/assets/javascripts/miq_application.js
app/javascript/packs/application-common.js
bower.json
package.json

spin.js is used by `miqSpinner` and `miqSearchSpinner` to render the ..spinner.
Moving to npm, except this time, the version that supports npm is the version that drops jquery support.
=> updating to use the current API and thus the newest version
testing: `miqSparkleOn(); miqSparkleOff(); miqSparkleOn();`
Issue: #3734

bower to npm - spin.js

---

app/controllers/application_controller.rb
spec/controllers/dashboard_controller_spec.rb

`csp_report()` is meant to report policy violation, it should not be touching session data at all (othewise it would cause ugly side-effects, such as deleting the whole session).
@martinpovolny review please?

Don't run set_global_session_data() for csp_report()

---

app/assets/javascripts/components/miq_ae_class/namespace-form.js

Also, there's no need to escape double quotes in single quote js strings, such as: `'abc \"def\" ghi'`
Also, removed `url` variable (used only once).

Avoid using string math in flash messages

---

app/controllers/application_controller.rb
app/controllers/vm_common.rb
spec/controllers/vm_common_spec.rb
spec/shared/controllers/shared_example_for_download_summary_pdf.rb

When downloading Template summary to PDF code was passing in incorrct class to find_records_with_rbac mthod, class was being passed in as ManageIQ::Providers::InfraManager::Vm this was causing code to raise an error that was displaye don screen as well as in evm.log. Changed download_summary_pdf method to pass in class from vm_common.
Added spec test to verify that code does not raise any errors.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1544317
@martinpovolny please review

Fixed to pass in correct class for Template summary screen pdf download

---

app/controllers/cloud_volume_controller.rb

This fixes a typo in `detach_volume` which was leading to an exception being thrown when a volume was unavailable for detach. Fixes one of the symptoms present in https://bugzilla.redhat.com/show_bug.cgi?id=1544344

Fix typo in detach_volume error handling

---

app/helpers/application_helper/toolbar/physical_servers_center.rb

If no physical server is selected in the physical servers page, the provision button is still active, causing an error if it's clicked. This PR fixes it by setting the button to only activate when 1 or more physical server is selected.

Fix Physical Server provision button

---

.bowerrc

Use new registry even for older bower versions.
[source](https://bower.herokuapp.com/)
@himdel @Hyperkid123

Use new registry even for older bower versions

---

config/webpack/shared.js

I have found another issue with multiple copies of react. This time it was affecting the `react-select` component (specifically the multi select variant). Issues are described in #4430.
Adding alias to react package in webpack resolved the issue. Webpack will now always use react package installed in ui-classic node_modules.

Added alias to react package.

---

app/javascript/miq-redux/redux-router-actions.js
app/javascript/miq-redux/redux-router-actions.test.js
app/javascript/packs/application-common.js
package.json

Added routing actions to ManageIQ.redux interface. These should be called only outside of react components if you need to do some react routing (miqTreeController for example).

Expose redux routing actions

---

app/assets/stylesheets/physical_infra_topology.scss

This PR changes the colors of all physical infrastructure components icons to black. This decision was made on [ManageIQ/manageiq-ui-classic#4396](https://github.com/ManageIQ/manageiq-ui-classic/pull/4396) discussion.

Changing Topology icons colors to black

---

app/controllers/catalog_controller.rb

Added 'public_service_templates' scope when fetching right side list for unassigned folder node
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594408
before:
after:
@hsong-rh @bzwei please review

Added missing 'public_service_templates' scope

---

app/services/ansible_tower_job_template_dialog_service.rb
spec/services/ansible_tower_job_template_dialog_service_spec.rb

The dialog code for Ansible Tower job template can be used for workflow template as well.
- Add Service Name field in Options group so the dialog would have at least one box.
- Limit option is supported only by Ansible Job Template. Ansible Workflow Template seems does not support it.
Depends on https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/103.
https://bugzilla.redhat.com/show_bug.cgi?id=1590975
Before:
After:
New dialog for workflow job template:

Changes to AnsibleTowerJobTemplateDialogService to support both job and workflow template.

---

app/views/miq_policy/_policy_folders.html.haml

There are no models behind the control/compliance policies, so there are no decorators and for now there's no better way to solve this. I added the `fa-fw` class on both icons as the shield was looking bad without it.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1615814

Do not rely on decorators when displaying top-level policy folders

---

app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
app/helpers/application_helper/toolbar/x_vm_cloud_center.rb

The `button_group('vm_access')` defined in `x_vm_cloud_center.rb` overrides the same group created in the `InstanceOperationsButtonGroupMixin` that is being included just before. Therefore, the remote console button for OpenStack instances is missing. By moving the webmks console to the `InstanceOperationsButtonGroupMixin` and dropping the `button_group` the issue is fixed.
**Before:**
**After:**
@miq-bot add_label bug, toolbars
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1615796

Move webmks console button to instance operations button mixin

---

app/assets/javascripts/miq_application.js
app/controllers/ops_controller.rb
app/views/layouts/_auth_credentials2.html.haml
app/views/layouts/_x_edit_buttons.html.haml

Ops (Configuration) > Settings, select Region, tab Red Hat Updates
Edit Registration - fill out inputs too quickly and hit Register
clicking the Register button too fast would mean the attempt to save the form happened before the last input changed
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532201

RHSM form - use observe queue for submit

---

app/helpers/service_helper/textual_summary.rb
app/views/service/_svcs_show.html.haml

Added a check in code to not try to show "Plays" section and load standard output for workflow template type services.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/4444
Ansible Playbook Service details
Workflow Template Service details
@lfu please review/test

Worflow Templates do not have job_plays and raw_stdout_via_worker

---

app/controllers/catalog_controller.rb
app/views/catalog/_form_resources_info.html.haml

Using old leftover UJS observers on the drop downs was causing form to send up multipe transaction when a selection was made in drop downs, causing other issues in the form.
convert id to_i to make sure the comparison of is between same types
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1615853
@dclarizio Attached a video in the BZ that verifies the fix.
@lgalis can you please review/verify fix.

Fixed to use bootstrap select event instead of UJS observer

---

app/helpers/application_helper/button/miq_request_delete.rb

correcting 1 line from #3993
related: https://github.com/ManageIQ/manageiq/pull/17849
This uses a helper method instead of calling out the the `miq_request_approval` role.
(yes, if you notice, this change will effectively change the feature from `miq_request_superadmin` to
`miq_request_approval` - since that feature was erroneously introduced.
https://bugzilla.redhat.com/show_bug.cgi?id=1608554

use request_admin_user

---

app/assets/javascripts/services/event_notifications_service.js

The notification mark/delete would might work without this, but it's better to have the same full `href` for the items as it would come from the API. I am not sure about the `window.location.origin`, maybe there's a better way, so pinging some JS-people for review.
Depends on: https://github.com/ManageIQ/manageiq/pull/17875
@miq-bot add_reviewer @karelhala 
@miq-bot add_label pending core, bug
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618705

Set the href for notifications emitted through WS the same as in API

---

app/controllers/application_controller.rb
app/controllers/application_controller/miq_request_methods.rb
app/controllers/host_controller.rb
spec/controllers/application_controller/miq_request_methods_spec.rb
spec/controllers/application_controller_spec.rb
spec/controllers/host_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1428003
---
**What:**
Fix returning wrong template class in `get_template_kls` method due to redirecting and different controller set while provisioning VMs through Provider's details page. The right templates are rendered while provisioning VMs which are accessed through _Compute > Infrastructure > Virtual Machines_.
**Exact steps to reproduce:**
1. Go to _Compute > Infrastructure > Providers_ and select some provider
2. Display the VMs through provider's details page or under _Relationships_ in accordion (there are more ways)
3. Under _Lifecycle_, select _Provision VMs_
---
Provisioning VMs accessed through _Compute > Infrastructure > Virtual Machines_:
**Before:** (all the available templates)
**After:**
---
**Note:**
_Continue_ …

Fix returning wrong template class while provisioning VMs

---

app/assets/stylesheets/about_modal_background.scss
app/helpers/application_helper.rb
app/views/layouts/_about_modal.html.haml

Depends on the work done in PR https://github.com/ManageIQ/manageiq/pull/17755
https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/422
https://bugzilla.redhat.com/show_bug.cgi?id=1594348

Display Plugin commit hashes in the About Modal

---

package.json

react-bootstrap 0.32.2+ depends on @babel/runtime
..specifically on @babel/runtime 7.0.0-beta.42
7.0.0-rc.1 doesn't work because of different paths
So, this is a very temporary fix to get travis green, just adding the missing dependency.

Fix travis by adding beta version of @babel/runtime because react-bootstrap is special

---

app/controllers/application_controller/timelines.rb
app/controllers/application_controller/timelines/options.rb
lib/report_formatter/timeline.rb
spec/controllers/application_controller/timelines_spec.rb
spec/lib/report_formater/timeline_spec.rb

Up until now, in order to register event type to the timeline, we needed to list all of the event types in settings yaml.
This commit adds another option: specify event type to group/level mapping using regular expressions, which should make mapping definitions much shorter for providers with many different event types
that follow a certain pattern.
Changes were made in two areas: in database querying and in event to category assignment.
When creating database condition for events, we now use three sources:
1. a set of event types that should be included in result,
2. a set of event types that should not be present in result and
3. a set of regular expressions that event types can match.
An event is part of the result if its type is in include set or matches any of the regular expressions …

Allow registering events to timelines using regexes

---

spec/controllers/mixins/actions/vm_actions/rename_spec.rb

In this PR, I am adding specs for methods `rename_save, rename_cancel, rename_reset` in `Rename` module. Related PRs: https://github.com/ManageIQ/manageiq-ui-classic/pull/4477, https://github.com/ManageIQ/manageiq-ui-classic/pull/4351

Add specs for some methods in new Rename module for renaming VMs

---

bin/setup

Since ManageIQ/manageiq#17663, there is no manageiq/log directory by default.
That breaks travis with 
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/travis/build/ManageIQ/manageiq-ui-classic/spec/manageiq/log/audit.log
/home/travis/build/ManageIQ/manageiq-ui-classic/vendor/bundle/bundler/gems/manageiq-gems-pending-f74f387d9e36/lib/gems/pending/util/vmdb-logger.rb:11:in `initialize'
```
Creating the log file.
Closes #4501 
@kbrock I took the liberty of replicating your PR with the log creation happening before `setup_js_env.sh` which seems to need it :)

travis - create manageiq/log manually

---

app/views/layouts/_tag_edit.html.haml

miqSelectPickerEvent is being called to observe botstrap dropdowns, having both observers causes double transactions to be sent upto server and causes an issue in UI randomly.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1601915
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614437
@himdel do you know why all of a sudden we are seeing these type of issues in UI with double transactions beings sent on drop downs, i recently fixed another one https://github.com/ManageIQ/manageiq-ui-classic/pull/4488
This issue does not happen always, but something to do with timings of transactions

Removed `data-miq_observe` from drop down

---

bin/setup

This reverts commit 2840e7ccd483a23b5a2987c278a2962b4b28631c (#4502)
Because the change is no longer needed, as it was fixed in https://github.com/ManageIQ/manageiq/pull/17886

Revert "travis - create manageiq/log manually"

---

tools/ci/after_install.sh

whenever there's a breakage caused by JS dependencies, it's useful to be able to get the last working configuration
we're already doing the same with Gemfile.lock (https://github.com/ManageIQ/manageiq-ui-classic/pull/263)

Travis - output yarn.lock

---

app/controllers/application_controller/miq_request_methods.rb

Physical server provisioning was being impossible due to an error blowing when accessing it.
Thanks to @h-kataria it's fully working now.

Fix physical server provision page

---

app/views/ops/_label_tag_mapping_form.html.haml

This is to address the duplicate div warning shown on Settings -> [Region] -> Tags -> Map Tags -> Add
Both `main_div` and `flash_msg_div` are already present in the tree. The partial is only rendered from presenter in ops controller (i.e. it doesn't seem to be included from anywhere).

Remove main_div and flash_msg_div from label_tag_mapping_form

---

app/controllers/orchestration_stack_controller.rb

Compute ➛ Cloud ➛ Stacks ➛ Find a stack with child stacks ➛ In summary, click on child stacks
Before, the action would give the following error:
```
Error caught: [NameError] uninitialized constant Child
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:268:in `const_get'
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:268:in `block in constantize'
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:266:in `each'
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:266:in `inject'
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7/lib/active_support/inf …
```

Fix rendering of child orchestration stacks

---

app/controllers/automation_manager_controller.rb
app/controllers/mixins/manager_controller_mixin.rb

Reload the automation manager trees on provider updates
Links
-------
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1560552
Add a Tower provider - even after reload, the new provider will not be displayed in the tree.
For both Foreman and Tower  - when removing an existing provider, without this fix, it will not be removed from the tree until an accordion or controller switch.

Reload the automation manager trees on provider updates

---

app/controllers/report_controller/dashboards.rb
spec/controllers/miq_report_controller/dashboards_spec.rb

Fixed condition, Only need a check for tab title uniqueness within a group for selected dashboard
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614872
@yrudman cc
@skateman please review, condition that is being fixed always returns true. This is difficult to recreate, i had to make changes in the database table to be able to recreate. Ping me on gitter, I can help you with that.

There is no need to check for tab title uniqueness for default dashboard

---

app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

Fixing issue in Services
Service -> Catalogs -> Service Catalog -> order one
Before:
```
FATAL -- : Error caught: [ActionView::Template::Error] undefined local variable or method `open_url' for #<#<Class:0x00007fb698ba9e78>:0x00007fb698ba3a78>
Did you mean?  ops_url
app/views/shared/dialogs/_dialog_provision.html.haml:45:in 
```
After: It works
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/4334
@romanblanco please review. Check #4334 works as well.

Set open_url to be false by default 

---

app/controllers/chargeback_controller.rb
spec/controllers/chargeback_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1614982
Fix enabled _Save_ button while viewing Chargeback Rates assigned to **multiple Tag Categories**,
under _Cloud Intel > Chargeback > Assignments_ accordion.
---
1. Go to _Cloud Intel > Chargeback > Assignments_ accordion and choose _Compute_ or _Storage_ Assignments
2. Assign Rates to (at least) two different _Tag Categories_ (if thery are not assigned yet; for _Assign To_ choose  _Tagged Datastores/Tagged VMs and Instances/Tagged Container Images_ ) and save the assignments (then you should see them under _Saved Items_ in the same page)
3. View the saved assignments: change the _Tag Category_ to the second one which was saved before
=> _Save_ button enables immediately, even when no change was made …

Fix enabled Save button while viewing Chargeback Rate Assignments

---

package.json

this solves the problem of 4.5.* not having any pre-built binaries for node8+
(https://github.com/sass/node-sass/releases?after=v4.6.0 vs https://github.com/sass/node-sass/releases (51 [means](https://github.com/sass/node-sass/blob/master/lib/extensions.js#L74) node 7, 57 node 8, 64 node 10))
@GregP I really hope this helps the problems you've been seeing with node-sass.

Upgrade node-sass to a current version

---

app/javascript/http_api/fetch.js

I've stumbled upon a small bug in `fetch.js`. The console was using `warning` method instead of `warn`.

Fixed console warning method in fetch.

---

app/controllers/storage_controller.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1615826
**What:**
There is a bug in Datastores screen: previous basic search is not erased for last selected filter (node in the tree) before applying another basic search. This happens because basic search text is saved for each node in the tree, not for actual explorer screen.
**Details:**
Code should remember search text/string per explorer, not for each node/filter selected in the tree. I tried the same steps to reproduce in other explorer screens and I was not able to reproduce the behavior. It seems to be working correctly in other screens, search string is only being remembered per explorer. The behavior implemented in Datastores screen is a bug. The right search string is always set by calling `process_show_list` method here …

Fix basic search for Datastores

---

app/controllers/application_controller/tags.rb
app/views/layouts/_tag_edit_cat_tags.html.haml

Stop spinner after transaction is complete, when switching between values too quickly sometimes it leaves drop down open and unresponsive. Removed `data-miq_observe` from drop down value as well similar to what was done for Categories drop down, miqSelectPickerEvent is being called to observe bootstrap dropdowns.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614437
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1601915
@dclarizio made similar changes that were made to Category drop down to second drop down that allows users to select tag values on tagging screen. Was able to recreate the issue on slow server where i could change second drop down values quickly while the table was pulsating with the change made in previous transaction.

Added spinner after Value is selected on tagging screen

---

app/services/ems_dashboard_service.rb

The addition of `EmsDashboardService#recent_records` in https://github.com/ManageIQ/manageiq-ui-classic/pull/3427 causes an N+1, and seems to choke on the amazon provider because of the vast number of public images (`MiqTemplate` records) that are pulled in from a refresh.
This change provides a single query method for accomplishing the same task.  It is somewhat slow on a larger table (was testing with something around the size of 180k `MiqTemplate` records), but avoids any memory bloat entirely as we are only getting the counts.
Benchmarks
----------
Prior to this change, the `/ems_cloud_dashboard/recent_images_data/:id` route would not even complete a request on my machine.  This was running against a small Amazon provider that had ~77k images (most of which were probably just public …

Stop N+1 with EmsDashboardService#recent_records

---

app/assets/stylesheets/application.css
app/helpers/textual_mixins/textual_power_state.rb
package.json

For now we were using SVG icons for powerstate, however, in the quadicons we already changed this to a fonticon+background combo. This PR brings the same thing for textual summaries :tada: 
Note that there might be a floating point issue on certain linux-based browsers (maybe even CPU family related, not sure), however, if you zoom in on the image, it will be perfectly centered.
@miq-bot add_label graphics, textual summaries, gaprindashvili/no

Use fonticon+background for powerstate icons in textual summaries

---

app/helpers/ems_cloud_helper/textual_summary.rb
spec/helpers/ems_cloud_helper/textual_summary_spec.rb

Fixes an apparent copy-paste error that resulted in the EmsCloud description field being labeled as "Region" and using an erroneous display condition.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1392342

Fix mislabeled Description field on the EmsCloud summary view

---

app/views/host/_form.html.haml

https://bugzilla.redhat.com/show_bug.cgi?id=1618359#c2
**Description of problem**
When navigating to Host edit page, after about 1 or 2 seconds the first text field 'Name' is focused.
This is especially annoying when you get to the page with the intention to validate credentials and you end up writing username to the 'Name' field instead. 
**Steps to Reproduce**
1. go to Host edit page
2. start immediately typing withing 1 or 2 seconds to some text field except the first one
3. wait for changing of focus on name field
@miq-bot add_label gaprindashvili/no, bug

Fix focus of text field changes 1 or 2 seconds after host edit page is loaded

---

app/controllers/ops_controller/settings/common.rb

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1616371
Options for Event Monitor, Refresh Worker, and Connection Broker select fields were missing actual integer values. Instead of `['Option label', 123456]` it was only the label. The change request was sending something like `200%MB`  instead of the actual value and the change did not save.

Fixed missing threshold values from worker options.

---

app/helpers/application_helper/toolbar/miq_ae_domains_center.rb

Refactored wording for toolbar Configuration selection and hover text when editing a Domain.  
https://bugzilla.redhat.com/show_bug.cgi?id=1618743
Screen shot prior to code fix, plural form:
Screen shot post code fix, singular form:

Refactor Edit Domain toolbar selection wording

---

app/assets/javascripts/miq_qe.js

When running action to check if item is present in GTL, but such item is not found error is thrown which will break every other action for GTL.

Add check if found item is defined for is_displayed action on GTL

---

app/views/report/_form_filter_chargeback.html.haml

BackEnd PR https://github.com/ManageIQ/manageiq/pull/17893:
Highlighted options is the new one.
Links
* part of https://bugzilla.redhat.com/show_bug.cgi?id=1530221
* related (without depedency) PR https://github.com/ManageIQ/manageiq-ui-classic/pull/4517
cc @gtanzillo 
@miq-bot add_label chargeback, gapridashvili/yes

Add option Date Only for chargeback grouping

---

app/views/layouts/_flash_msg.html.haml

`display: none` seems to have been the intent :)
(Comes from https://github.com/ManageIQ/manageiq-ui-classic/pull/3731.)

Fix display_none typo

---

app/controllers/application_controller/buttons.rb
spec/controllers/application_controller/buttons_spec.rb

When `CustomButton` is invoked - and corresponding `CustomEvent` is being emited, let's propagate the source.
Design: [GDoc](https://docs.google.com/document/d/1wtgC3fQLLoR-g2jVMzINgYAeoojB0FkzQQR3pyv5Cns/edit)
RFE: [BUGZILLA 1511126](https://bugzilla.redhat.com/show_bug.cgi?id=1511126)
Depends on: https://github.com/ManageIQ/manageiq/pull/17764

Add a source definition when invoking CustomButton

---

bin/webpack
bin/webpack-dev-server

We were getting following error unless increasing memory available to Node:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: node::Abort() [node]
2: 0x8c21ec [node]
3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
6: 0xd4b133 [node]
7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
8: 0x66f38042fd
Aborted (core dumped)
```
Reverting previous approach with WEBPACK_BIN because setting NODE_OPTIONS seems to resolve the issue as well and is more readable.

Increase memory available to webpacker

---

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
app/controllers/catalog_controller.rb
app/views/catalog/_form_basic_info.html.haml
app/views/catalog/_st_angular_form.html.haml
spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
spec/views/catalog/_form.html.haml_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1451300
---
1. Enable Ansible Embedded role (not sure if this is required)
2. Add multiple (child) Tenants (_Configuration > Access Control > Tenants_), each Tenant has one super admin user which then creates Catalog with name 'catalog' (under _Services > Catalogs > Catalogs_)
3. Add Ansible Credentials and Repo (not sure if this is required)
4. Try to add new catalog item of _Ansible Playbook_ type  ( _Services > Catalogs > Catalog Items_ )
(or also any other type, but the BZ is mainly about Ansible Playbook type)
**Before:** (multiple Catalogs with the same name in the dropdown)
Adding a new Service Catalog Item:
Editing an existing Catalog Item - similar problem as the picture above
**After:**
Adding a new …

Fix displaying multiple Catalogs with the same name in the dropdown while creating a Catalog Item

---

app/views/report/_form_filter_chargeback.html.haml

**Reason**: It has identical behaviour, it is grouping by [same key](https://github.com/lpichler/manageiq/blob/ccee53b05b4b06ab037ab53e5597d53202158749/app/models/chargeback.rb#L72) for those both options 
**before** 
**after**
Links
* part of https://bugzilla.redhat.com/show_bug.cgi?id=1530221
cc @gtanzillo 

Unify grouping option date and vm in chargeback filter tab

---

app/controllers/ems_common.rb
app/controllers/flavor_controller.rb
app/controllers/host_aggregate_controller.rb
config/routes.rb

**Fixes BZ:** https://bugzilla.redhat.com/show_bug.cgi?id=1600678
There is a bug, in many pages under _Compute > Clouds_: when viewing **Instances list** (nested list) from _Relationships_ table, many toolbar buttons don't work. For Instances of some _Flavor_ (BZ above), none of the buttons work!
**Steps to reproduce:** (one of possible scenarios)
1. Go to _Compute > Clouds > Flavors_
2. Choose any Flavor, display its details page
3. In _Relationships_ table, click on _Instances_
4. Select some Instances (check the checkboxes)
5. Click on some available toolbar buttons, for example _Policy > Edit Tags_
=> nothing happens; log:
```
I, [2018-07-16T18:48:13.977565 #21925]  INFO -- : No template found for FlavorController#button, rendering head :no_content
Session:	 Hash of Size 7981, …
```

Make toolbar buttons work when viewing Instances

---

app/controllers/storage_controller.rb
spec/controllers/storage_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1620745
There is a small bug related to Datastores: incorrect title is displayed while displaying Datastore details page: unnecessary 'Names with.. ' and/or 'Filtered by..' is added to the title (right cell text), if any filtering (basic or advanced search) was applied on the list of datastores, before displaying datastore's details page.
1. Go to _Compute > Infra > Datastores_ (you need some Datastores here!)
2. Search for some text using basic search and/or apply some filter
(click on some filter in accordion or use _Advanced Search_)
3. Click on some datastore to display its details page
---
**Before:**
**After:**
---
**Note:**
The fix was inspired by service controller …

Fix incorrect title while displaying Datastore details page

---

app/controllers/alert_controller.rb
config/routes.rb
spec/routing/alert_routing_spec.rb

This PR:
* removes remnants of removed `start_rss()` routine (removed in 252bea13402808b9d704d04675908dc886b83840)
* removes arguments from `rss()` route. The `rss()` routine was invoked from `start_rss()` only, which has been removed a while ago. Hence, `rss()` doesn't need any parameters of its own.

Remove start_rss()

---

app/controllers/alert_controller.rb

The argument has been removed from the backend routine.
Backend PR: https://github.com/ManageIQ/manageiq/pull/17922
This fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/4559
@martinpovolny

Don't pass local argument to RssFeed.generate()

---

app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
app/controllers/mixins/actions/vm_actions/reconfigure.rb
app/views/vm_common/_reconfigure.html.haml
spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js

Use device_name for cdrom reconfiguration request.
Remove duplicate of updateCDRomsConnectDisconnect.
Links 
-----------
https://bugzilla.redhat.com/show_bug.cgi?id=1533728
Follow up for https://github.com/ManageIQ/manageiq-ui-classic/pull/3956

Use device_name for cdrom reconfiguration request

---

app/assets/javascripts/services/alerts_center_service.js

An alert can point to an invalid resource if the resource is deleted
We tend to avoid this, but in one case, `Container Replicators` can go away
If there is another way to solve this on the ruby end, please let me know

Handle Alerts with no resources

---

app/assets/javascripts/application.js
app/helpers/application_helper/webpack.rb
app/javascript/packs/application-common.js
app/javascript/packs/globals.js
spec/javascripts/support/jasmine.yml

Right now, any global dependencies (like jquery, angular, etc.) are either in the asset pipeline, or in application-common.js, which happens right after.
But for some packages, that's not enough as they have to go through webpack, but are depended on by code in asset pipeline.
---
Also moving jquery (to make sure this works, but also because jQuery should really go before any of the other non-shim dependencies) and sprintf from their respective places to the new pack.
(Depended on by #4442 - numeral is the case where moving from bower to npm means webpack, but ui-components code is trying to use numeral sooner than it would be available from application-common.)
Issue #3734

Add globals pack - before asset pipeline, after vendor

---

app/controllers/ops_controller/settings/analysis_profiles.rb

Cleaning up the code by replacing obsolete methods for record fetching with RBAC
Links
* https://github.com/ManageIQ/manageiq-ui-classic/issues/1134
1) go to Top menu - Configuration - Settings (accordion) - Analysis Profiles
2) try to remove / copy Analysis Profiles

Replaced obsolete method for record fetching with RBAC in ops controller

---

app/services/network_topology_service.rb

With this commit we let NetworkManager's topology view render CloudTenants with basic entities beneath them in order for Nuage provider to display a meaningful topology view.
Since Nuage provider subclasses CloudSubnets into
```
ManageIQ::Providers::Nuage::NetworkManager::CloudSubnet::L2
ManageIQ::Providers::Nuage::NetworkManager::CloudSubnet::L3
```
we also make sure those get appropriate class name assigned (i.e. base class name) or else nothing is shown.
Amazon provider:
Nuage provider:
Amazon provider (proof that nothing has changed):
Nuage provider:
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/4316

Show CloudTenants in network manager's topology view

---

app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
app/assets/javascripts/services/event_notifications_service.js
app/controllers/restful_redirect_controller.rb
app/views/static/notification_drawer/notification-body.html.haml

The angular-patternfly has a new notification-body template example for the [notification drawer](https://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfNotificationDrawer) that displays a kebab on the right side of a notification with all the available actions inside.
For now we supported just two actions: marking a notification as read (by clicking on it) and removing the notification (by clicking on the `x`). However, the plan is to support at least one extra action to redirect the user to a page where the user can see more details.
After the changes it will have the three actions inside the kebab, where the new View Details should redirect to the subject's screen:
For the toasts, it will have an extra `View details` link that does the same: …

Add support for links to a details page in the notification drawer

---

app/controllers/cloud_subnet_controller.rb
app/controllers/network_router_controller.rb
app/controllers/security_group_controller.rb
app/helpers/cloud_subnet_helper/textual_summary.rb
app/helpers/network_router_helper/textual_summary.rb
app/helpers/security_group_helper/textual_summary.rb
app/views/cloud_subnet/show.html.haml
app/views/network_router/show.html.haml
spec/helpers/cloud_subnet_helper/textual_summary_spec.rb
spec/helpers/network_router_helper/textual_summary_spec.rb
spec/helpers/security_group_helper/textual_summary_spec.rb

Two foreign keys have been added to the SecurityGroup model recently:
```
security_group.network_router
security_group.cloud_subnet
```
With this commit we show them both on UI (in both directions).
SecurityGroup view:
NetworkRouter view:
CloudSubnet view:
Depends on: https://github.com/ManageIQ/manageiq/pull/17900

Show relation "security group belongs to router and subnet"

---

app/assets/javascripts/controllers/playbook-reusable-code-mixin.js

There is an error while creating _Catalog Item_ of _Ansible Playbook_ type. It is not possible to create catalog item of this type. Introduced by: https://github.com/ManageIQ/manageiq-ui-classic/pull/4278
1. Go to _Services > Catalogs > Catalog Items_
2. _Configuration > Add a New Catalog Item_
3.  For _Catalog Item Type_, choose _Ansible Playbook_
=> error!
---
**Before:**
**After:**

Fix error while creating Catalog Item of Ansible Playbook type

---

app/services/ems_physical_infra_dashboard_service.rb
app/views/static/pf_charts/aggregate-status-card.html.haml

This pr is able to:
* Remove the redundant number if all components are healthy.
**Before**
**After**
* Add a tooltip in the health state icon in the provider dasborad

Add a tooltip to health state of the cards in the physical infra dashboard

---

bower.json
spec/javascripts/support/jasmine.yml

Looks like at some point we lost the jasmine<2 limitation, so the bind polyfill may no longer be needed.
Trying to see if the tests pass when we remove it.
If not, need to move it to npm (https://github.com/ManageIQ/manageiq-ui-classic/issues/3734).
(Polyfill introduced in https://github.com/ManageIQ/manageiq/pull/8421,
phantomjs version restriction in https://github.com/ManageIQ/manageiq/pull/6716,
removed in https://github.com/ManageIQ/manageiq/pull/11834,
and let travis use whatever version it has in https://github.com/ManageIQ/manageiq/pull/11929 (currently 2.1.1 is always used [it seems](https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/423024220#L340)))

Remove phantomjs bind polyfill

---

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
app/views/cloud_volume/attach.html.haml
app/views/cloud_volume/backup_new.html.haml
app/views/cloud_volume/backup_select.html.haml
app/views/cloud_volume/detach.html.haml
app/views/cloud_volume/edit.html.haml
app/views/cloud_volume/new.html.haml
app/views/cloud_volume/snapshot_new.html.haml

When creating a new volume user has to pick what StorageManager is volume supposed to be created with, hence we perform API request to fetch those. Problem is we share angular controller with other volume operations (attach, detach) that don't need this list of all managers and fetching those anyway results in permission denied error due to fine-grained permission setting.
For example if we give user only permission to attach/detach volume, but not to view StorageManagers:
then we must not perform the API call as it results in 403 with red popup:
With this commit we refactor controller so that it now only performs the API call "fetch storage managers" when we're creating a new volume, and not just always by default. Attaching/detaching volume therefore doesn't trigger the problematic API …

Lazy load StorageManagers upon volume creation

---

app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js

A simple single underscore vs double underscore typo :).

aggregate_status_card - fix i18n typo

---

app/assets/javascripts/application.js
app/assets/javascripts/components/generic_object/generic-object-table-component.js
app/assets/javascripts/components/generic_object/main-custom-button-form-component.js
app/assets/javascripts/components/generic_object/main-custom-button-group-form-component.js
app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
app/assets/javascripts/controllers/floating_ip/floating_ip_form_controller.js
app/assets/javascripts/controllers/toolbar_controller.js
app/assets/javascripts/directives/form_changed.js
app/assets/javascripts/miq_application.js
app/assets/javascripts/miq_c3.js
app/assets/javascripts/services/event_notifications_service.js
app/javascript/packs/globals.js
bower.json
package.json
spec/javascripts/controllers/toolbar_controller_spec.js

This moves all lodash to npm - that means we no longer have lodash 3 available anywhere, and are always using lodash 4.
Following https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings to fix any incompatibilities.
Issue #3734

lodash - move to npm, upgrade to lodash 4

---

app/controllers/report_controller/widgets.rb
app/views/report/_widget_form_rss.html.haml

1. Cloud Intel ➛ Reports ➛ Dashboard Widgets ➛ RSS Feeds ➛ Add a New Widget
2. Fill in Name & Description, leave other fields untouched (i.e. feed type: internal)
3. Add
Click on the created widget: you'll see the widget shows as external.
The problem was caused by the fact that we were passing `nil` as `rss_feed_id` to the `set_rss_properties()` routine.

Fix creation of internal rss widget

---

app/decorators/physical_chassis_decorator.rb
app/helpers/ems_physical_infra_helper/textual_summary.rb
app/views/layouts/listnav/_ems_physical_infra.html.haml
spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb

* Add a chassis to PhysicalInfra provider dashboard
* Add both chassis and rack to PhysicalInfra provider listnav

Add Chassis to PhysicalInfra dashboard and listnav

---

app/views/shared/buttons/_ab_form.html.haml
spec/views/shared/buttons/_ab_form.html.haml_spec.rb

Correction of https://github.com/ManageIQ/manageiq-ui-classic/pull/4513#discussion_r213379575
As @h-kataria mentioned, the buttons is supposed to be disabled, if the copied target class differs from the current target class.
This PR corrects the behaviour
Links
*    https://github.com/ManageIQ/manageiq-ui-classic/pull/175#discussion_r102018852
*    #4189
*    https://bugzilla.redhat.com/show_bug.cgi?id=1426390

Enable 'Paste' button only if the copied and selected target class are the same

---

app/controllers/ops_controller.rb
app/views/ops/_zone_form.html.haml
spec/views/ops/_zone_form.html.haml_spec.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1623912
**Description of problem:**
No error message when creating duplicate zone in the same region
1. Create a domain and a namespace
2. Create a class (1) within the namespace that has both name and display name
3. Create an another class (2) within the same namespace, this time only with name and NO display name
4. Copy the class only with name (2) within the same domain and namespace, just give it a new name (3), safest way to do it right is to lock all domains except the one you work with right now.
1. There's no error message when trying to add zone with empty name.
Should be "Name can't be blank".
2. There's no error message when trying to add zone with empty description.
Should be "Description is required". …

Fix missing flash_msg_div in ops/settings/zone_form

---

app/controllers/restful_redirect_controller.rb

This is an addition to a really bad antipattern that allows us to redirect the user to an URL based on a record type and an ID. However, for now there's no other way to do this, but I will actively think on a [better solution](http://media.ifunny.com/results/2018/03/29/482i5kkucz.jpg) in the future.
@AparnaKarve stated that it's 100% sure that the `ServiceTemplateTransformationPlanRequest` is not used for anything else than V2V and I believed her, so any request coming with this model will be redirected to the `migration` controller defined in V2V. As they're using hash routes, I had to use the `:anchor` parameter of the `redirect_to` method.
Related drawer modifications: https://github.com/ManageIQ/manageiq-ui-classic/pull/4492
Related issue: …

Add restful redirect rule for notifications arriving from V2V

---

app/controllers/chargeback_controller.rb
app/views/chargeback/_cb_rate_edit_table.html.haml
app/views/chargeback/_cb_rate_show.html.haml

Report column name added to rate editor
Reason: We are using different names in report and in report editor and it is confusing. 
cc @gtanzillo 
@miq-bot chargeback, enhancement
**After** - highlighted are new ones

Describe better chargeback metric in Rate Editor

---

app/assets/stylesheets/about_modal_background.scss
app/views/layouts/_about_modal.html.haml

This PR makes the plugin section expandable and also increases the scrollable area to 10 lines.
This is a follow-up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/4423

Update 'About Modal' plugin section styling

---

app/controllers/cloud_network_controller.rb
app/controllers/cloud_subnet_controller.rb
app/controllers/cloud_tenant_controller.rb
app/controllers/cloud_volume_backup_controller.rb
app/controllers/floating_ip_controller.rb
app/controllers/host_aggregate_controller.rb
app/controllers/mixins/actions/vm_actions/rename.rb
app/controllers/network_router_controller.rb
app/controllers/physical_server_controller.rb
app/controllers/security_group_controller.rb
app/controllers/vm_remote.rb
spec/controllers/mixins/actions/vm_actions/rename_spec.rb

In several places in our code we use the following logic:
```ruby
task_id = ems.create_some_kind_of_queue(session[:userid], options)
unless task_id.kind_of?(Integer)
add_flash(_("Some kind of creation failed: Task start failed: ID [%{id}]") % {:id => task_id.to_s}, :error)
end
```
This is obviously incorrect: since task creation failed, `task_id` is not an integer and we cannot treat it as integer in the flash error message.
@martinpovolny

Fix error flash messages when creating tasks

---

app/assets/javascripts/miq_application.js
app/javascript/http_api/api.js

Cc @jvlcek 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1468252

Login with Service Unavailable - show a flash message instead of generic error popup

---

app/controllers/miq_ae_class_controller.rb

This bug was caused by not properly setting environment for treebuilder, resulting in treebulder not build only shallow version of the tree and focused element was not included in rendered tree, so it couldn't be selected.
https://bugzilla.redhat.com/show_bug.cgi?id=1611969
1. Navigate to Automate/Explorer.
2. Add a domain, a namespace.
3. Add a class.

Update open_nodes when creating new element

---

app/controllers/miq_ae_class_controller.rb

A class is still included in the tree after deletion
**Solution**
The tree was not properly updated after copying, so it can not be refreshed.
1. Go to Automation -> Automate -> Explorer
2. Create a namespace, create a domain
3. Create a class (1) with a name and a display name
4. Create a class (2) with a name (without a display name)
5. Copy the second class 
6. Delete the copy
7. Repeat 5.+6.
8. You will see the duplicate in the tree
**Before** 
**After**

Fix duplicate in tree after class deletion in miq_ae_class_controller

---

app/controllers/ops_controller/settings/common.rb
app/controllers/ops_controller/settings/upload.rb
app/views/dashboard/login.html.haml
app/views/layouts/_header.html.haml
app/views/ops/_settings_custom_logos_tab.html.haml
config/routes.rb

This PR creates a brand image upload feature under the custom logo tab, eliminating the need to manually change the html, css, and drop images into the public folder. The image appears on the login screen and the main header. The code in the area was awful, so I also did a little refactoring. 
@miq-bot add_label pending core
Depends on: https://github.com/ManageIQ/manageiq/pull/17773
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1471301

[RFE] Allow to upload and display a custom brand image on login/header

---

app/controllers/application_controller.rb

~~Merge together with https://github.com/ManageIQ/manageiq/pull/17943~~
Links
* #1134
* Clone a VM

Replaced obsolete method for record fetching with RBAC in application controller

---

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
app/views/cloud_volume/attach.html.haml
app/views/cloud_volume/backup_new.html.haml
app/views/cloud_volume/backup_select.html.haml
app/views/cloud_volume/detach.html.haml
app/views/cloud_volume/edit.html.haml
app/views/cloud_volume/new.html.haml
app/views/cloud_volume/snapshot_new.html.haml

Same as https://github.com/ManageIQ/manageiq-ui-classic/pull/4549 but with merge conflicts resolved.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1625250
@miq-bot add_label bug,fine/yes,gaprindashvili/no
/cc @AparnaKarve @simaishi

[FINE] Lazy load StorageManagers upon volume creation

---

app/assets/javascripts/services/alerts_center_service.js

Monitor > Alerts > Overview
the code going through all the alerts can handle severity being undefined
but that never happens, since it comes from the server as null :)
this leads to an ugly error in the console when opnening Monitor > Alerts > Overview (and nothing showing up)
fixed - any falsy value is wrong and will be rewritten to `info` now

Alerts - fix bug when severity null

---

app/assets/javascripts/application.js
app/assets/javascripts/miq_application.js
bower.json

this was only used by the `queryParam` function
..which is useful, but the last use was removed in https://github.com/ManageIQ/manageiq-ui-classic/pull/426
removing, we may want to consider just wrapping the new URL standard,
(the package was https://github.com/nire0510/qs , and is available on npm under the name qs-parser)
Issue #3734

bower: remove QS

---

app/services/container_project_dashboard_service.rb
app/services/ems_dashboard_service.rb
app/services/ems_physical_infra_dashboard_service.rb
app/services/hawkular_proxy_service.rb

I am guessing this mixin got copy-pasted from the first container dashboard but it seems that it is not being used in most of the cases. All related dashboards seem working with this change, but I'd ask for a review from some people who did review on this.
@miq-bot add_reviewer @felipedf 

Do not include UiServiceMixin in services where it is not being used

---

app/assets/javascripts/miq_explorer.js
app/controllers/report_controller.rb
app/controllers/report_controller/schedules.rb
spec/controllers/report_controller/schedules_spec.rb

Only need to set params[:accord] when add button is pressed from Reports accordion, setting of acord parameter causes acoridon to be swapped to Schedule accordion by Explorer presenter code. Undid code changes made in https://github.com/ManageIQ/manageiq-ui-classic/pull/3399 this was causing issues when adding a schedule from Reports accordion.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1624248
@hstastna please test/review.
before:
after:

Fixed Schedules accordion swapping logic.

---

app/helpers/textual_mixins/textual_data_collection_state.rb

Leverage the `QuadiconHelper.machine_state` similarly to the textual power states. It is currently available on container provider summary screens only.

Use fonticon + background for data collection in textual summaries

---

app/controllers/application_controller/filter/expression.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1627284
before:
after:

Fixed a typo in parameter name

---

app/javascript/packs/globals.js
app/views/vm_common/console_webmks.html.haml
config/initializers/assets.rb

Moving jquery-ui to npm (#4617) caused us to only include the core, with no widgets.
From what I can tell, we only need 3 widgets:
* draggable & droppable - used by ui-components, dialog-editor
* sortable - used for configuring dashboard layout
including just the 3.
Also removing the `jquery-ui` require in webmks console, introduced in #410 - doesn't seem to have been needed, @skateman do you know if we still need jquery-ui there? (the view doesn't use it)
(Related to #3734)

Fix jquery-ui includes

---

app/services/physical_infra_topology_service.rb
spec/services/physical_infra_topology_service_spec.rb

This change teaches topology creation process about chassis nesting
that can be produced by Redfish physical infrastructure provider.
~~Depends on #4593~~
~~Depends on https://github.com/ManageIQ/manageiq/pull/17940~~

Allow nesting physical chassis

---

app/assets/javascripts/application.js
app/javascript/packs/globals.js
bower.json
package.json

2 angular libraries not directly used by ui-classic but depended on by ui-components.
Both in same version.
testing
```
angular.element('.ng-scope').injector().get('ngDragDropService')
angular.element('.ng-scope').injector().get('uiSortableConfig')
```
Issue #3734

bower to npm: angular-dragdrop & angular-ui-sortable

---

app/helpers/physical_chassis_helper/textual_summary.rb
app/helpers/physical_server_helper/textual_summary.rb
product/views/PhysicalChassis.yaml
product/views/PhysicalServer.yaml
spec/helpers/physical_chassis_helper/textual_summary_spec.rb

- Adapt the physical server pages to retrieve `loc_led_state` from the new place (`asset_detail.location_led_state`);
- Add location LED state to physical chassis pages;
__Depends on__
- ~https://github.com/ManageIQ/manageiq-schema/pull/262~
- ~https://github.com/ManageIQ/manageiq-providers-lenovo/pull/222~

Showing Location LED state for physical chassis

---

app/views/shared/buttons/_ab_options_form.html.haml

This will make the dropdowns to look more consistent with the other ones on the screen for editing a custom button under automate - customization.
**Before:**
**After:**
@miq-bot add_label bug, graphics

Enable selectpicker on all dropdowns when editing a custom button

---

app/controllers/physical_network_port_controller.rb

- Fix method call in PhysicalNetworkPortController;
__Before this PR__
__After this PR__
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1628288

Fixing Physical Network Port page

---

app/controllers/application_controller/advanced_search.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1626579
There is a problem in _Workloads Templates & Images_ screen: new created filter is not displayed until Workloads page is refreshed.
1. Go to _Services > Workloads > Templates & Images_ accordion
2. Open _Advanced Search_ and create a new expression, commit it
3. Name and save a new filter
=> the new filter is not displayed in accordion in _Global/My Filters_ folder! (need to refresh the page)
---
**Before:**
**After:**
---
**Notes:**
In `adv_search_redraw_left_div` method, we need `tree_for_building_accordions?` to return `true` to display the new filter in accordion properly, immediately after its creation, because we are in explorer screen. No need to refresh the page.

Make filters saved in Templates & Images screen displayed in accordion

---

app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
app/views/static/notification_drawer/notification-body.html.haml

When clicking on a disabled `View Details` link in the notification drawer, it displays an error. By preferring the `notification.actionCallback` over `customScope.viewSubjectDetails` this problem is gone as the `actionCallback` is only set when the link is enabled. This makes the `viewSubjectDetails` function obsolete.
Fixes #4648

Do not invoke view details callback on notifications without links

---

app/controllers/application_controller/advanced_search.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1627078
There is a problem in _My Services_ page while applying filter from _Advanced Search_: error occurs and the filter is not applied.
1. Go to _Services > My Services_ page
2. Open _Advanced Search_ and create some new expression, commit it
3. Apply the expression, no need to save it. If you save the filter before applying it, apply the filter using Advanced Search, too.
=> error:
```
[----] F, [2018-09-11T18:00:16.007675 #29073:2b18a138e138] FATAL -- : Error caught: [RuntimeError] operator 'token' is not supported
/home/hstastna/manageiq/manageiq/lib/miq_expression.rb:1435:in `to_arel'
/home/hstastna/manageiq/manageiq/lib/miq_expression.rb:289:in `to_sql' …
```

Fix applying filter from Advanced Search in My Services

---

app/helpers/ems_cloud_helper/textual_summary.rb
spec/helpers/ems_cloud_helper/textual_summary_spec.rb
spec/shared/helpers/textual_summary_helper_methods.rb

Since `:description` is not a required method for `ExtManagementSystem` instance, this may break summary screen for some providers (resulting into 500). For example Google. Adding a fallback to class method.
Regression brought by: https://github.com/ManageIQ/manageiq-ui-classic/pull/4532
Possibly reopening: https://bugzilla.redhat.com/show_bug.cgi?id=1563600 ?
cc @himdel, @bronaghs, @ZitaNemeckova 
@miq-bot add_label bug, gaprindashvili/yes, compute/cloud

Fix ems_cloud description textual summary

---

app/controllers/application_controller.rb

When displaying custom button events for a record, the listicon had a `View Details` tooltip even if the table wasn't even clickable. Through the `params` in `view_to_hash` it is possible to determine if it's clickable, so the tooltip can be hidden based on this boolean.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1628245

Do not show tooltip on listicons in GTLs when they're not clickable

---

app/controllers/ops_controller/settings/common.rb
spec/controllers/ops_controller/settings/common_spec.rb

Queue operations for pglogical replication set-up
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1562956
depends on https://github.com/ManageIQ/manageiq/pull/17956
**BEFORE:** Page was locked (and ui worker occupied) for the duration of save operation
**AFTER:** Request to save queued and page unlocked

Queue operations for pglogical replication set-up

---

app/views/pxe/_pxe_server_details.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1626983
Missed in https://github.com/ManageIQ/manageiq-ui-classic/pull/3420
- Go to Compute -> Infrastructure -> PXE
- If there's no PXE server with images create some in console
```
PxeServer.create!(:name => 'PXE Server', :uri => "http://test.example.com/pxe_server_112211")
PxeImage.create!(:name => 'Pxe Image', :pxe_server_id => PxeServer.first.id, :description => 'Pxe Image from Hell', :kernel => 'ubuntu-10.10-desktop-i386/vmlinuz', :kernel_options => "vga=788 -- quiet")
WindowsImage.create!(:name => "Window Image", :description => "Window Image", :pxe_server_id => PxeServer.first.id)
```
- click on Pxe Image and Windows Image
Before:
```
Error caught: [ActionView::Template::Error] Missing partial …
```

Add React textual summary for PXE images

---

app/javascript/packs/globals.js
package.json

angular.validators only works correctly when loaded in a browser-like environment - https://github.com/gkaimakas/angular.validators/issues/3
if `module`, `exports` or `define` are defined, the `nodeValidator` service ends up becoming an empty object and an attempt at exporting what would have been the service is made
this is to ensure that no such vars are defined for `angular.validators`
Fixes #4660 (introduced in #4622)
@djberg96 can you confirm this fixes the issue for you please? :)

angular.validators - work around nodeValidator=={}

---

app/controllers/alert_controller.rb
app/controllers/alerts_list_controller.rb
app/controllers/alerts_most_recent_controller.rb
app/controllers/alerts_overview_controller.rb
app/controllers/ansible_credential_controller.rb
app/controllers/ansible_repository_controller.rb
app/controllers/auth_key_pair_cloud_controller.rb

This PR contains some additional rubocop fixes that I skipped before (in previously merged PRs), mainly addition of parentheses for method calls with arguments.

Additional fixes for rubocop warnings

---

spec/controllers/application_controller/ci_processing_spec.rb
spec/controllers/application_controller/performance_spec.rb
spec/controllers/ems_cloud_controller_spec.rb
spec/controllers/mixins/actions/vm_actions/rename_spec.rb
spec/controllers/pxe_controller_spec.rb
spec/views/shared/views/ems_common/_show.html.haml_spec.rb

Fixing failures introduced by https://github.com/ManageIQ/manageiq/pull/17987

Use existing Zone not 'default' for MiqServer.my_zone or in request

---

app/controllers/ops_controller/settings/common.rb

Saving the memory threshold value as a string would prevent the value to be read / used correctly later by the worker itself.
See https://bugzilla.redhat.com/show_bug.cgi?id=1624431#c6
https://bugzilla.redhat.com/show_bug.cgi?id=1624431

Worker Settings: save memory threshold as an integer

---

app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js
app/controllers/container_dashboard_controller.rb
app/services/container_dashboard_service.rb
app/services/ems_dashboard_service.rb
app/views/container_dashboard/show.html.haml
app/views/static/pf_charts/aggregate-status-card.html.haml

- Red crosses were added as part of https://github.com/ManageIQ/manageiq-ui-classic/pull/4453 that caused them to show up on all aggregate status cards on all provider dashboards, fixed the condition and removed setting of redundant notification hash for providers when it is not needed.
- Show status icon under Alerts in aggregate card if Alerts are configured for a container provider, otherwise show "No data available" empty pf card.
- On Containers Overview dashboard, Fixed to not show provider icon in Provider status aggregate card, it should only show count of providers with a link to list view to Container Providers show list.
- Added a title on Container Overview dashboard screen, since that's the only screen on that subtab there are no breadcrumbs on the screen.
Fixes …

Fixed some inconsistencies on provider dashboards.

---

app/assets/javascripts/miq_angular_application.js
app/javascript/packs/globals.js
package.json

we had a workaround (#4667) for loading angular.validators in a browser-like context to prevent the validator service becoming empty (#4660)
this is needed when using angular.validators < 4.4.3 with webpack
but 4.4.3 just got released (https://github.com/gkaimakas/angular.validators/issues/7), removing the workaround
4.4.3 contains the following changes from 4.4.2:
* https://github.com/gkaimakas/angular.validators/pull/4 - removed export/global boilerplate (the fix)
* https://github.com/gkaimakas/angular.validators/pull/5 - a README fix
* https://github.com/gkaimakas/angular.validators/pull/6 - allow `require('angular.validators')` (added index.js)
---
This essentially reverts https://github.com/ManageIQ/manageiq-ui-classic/pull/4667, but it does *not* remove `imports-loader` beause it is …

angular.validators - update and remove imports-loader workaround

---

app/controllers/miq_ae_class_controller.rb

Replacing obsolete RBAC test
Links
* #1134 
* go to Automate - Explorer
* select an instance
* Remove the selected instance

Replaced obsolete RBAC test while removing automate instances

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb
spec/views/catalog/_form.html.haml_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1628384
Introduced in: https://github.com/ManageIQ/manageiq-ui-classic/pull/4278
Fix displaying the dropdown which was not displayed after setting some
_Orchestration Template_, while creating a new Orchestration _Catalog Item_.
2. _Configuration > Add a New Catalog Item_
3. For _Catalog Item Type_, choose _Orchestration_
4. Fill in the _Name_, choose some _Catalog, Dialog_ and _Orchestration Template_
=> after making a selection in _Orchestration Template_ drop down, _Provider_ drop down is not displayed and it should display; after clicking on _Save_ button, error occurs but no _Provider_ drop down in the screen, no possibility to select any from the …

Display Provider dropdown while creating Orchestration Catalog Item

---

app/assets/javascripts/controllers/ems_container_dashboard/aggregate_status_card_controller.js

Fixed to show 0 Provider in aggregate status card when there are Providers available in db
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1628726
before:
after:

Fixed to show 0 Provider in aggregate status card

---

spec/controllers/application_controller/advanced_search_spec.rb

This PR add simple specs related to the fix in _Advanced Search_: https://github.com/ManageIQ/manageiq-ui-classic/pull/4649

Add specs related to Adv Search and filters saved in Templates & Images screen

---

app/controllers/ops_controller/settings/common.rb
spec/controllers/ops_controller/settings/common_spec.rb

Encrypt replication subscription's password before queuing save operation
This PR is follow-up to https://github.com/ManageIQ/manageiq-ui-classic/pull/4628
There is no need to change model side since encrypted password will be decrypted if needed here: https://github.com/ManageIQ/manageiq/blob/156cd6b949e5bc4837edd1d76e47e643d9250040/app/models/pglogical_subscription.rb#L242
@miq-bot add-label  technical debt
https://bugzilla.redhat.com/show_bug.cgi?id=1562956

Encrypt replication subscription's password before queuing save operation

---

app/controllers/ems_common.rb
app/controllers/host_aggregate_controller.rb
spec/controllers/host_aggregate_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1625274
There is a problem with toolbar buttons: they don't work for Hosts' list displayed thru Host Aggregate's details page.
TODO:
- fix failing specs (builds edit and create screen)
---
1. Go to _Compute > Clouds > Host Aggregates_
2. Display some Host Aggregate's details page
3. In _Relationships_ table, click on _Hosts_ (display nested list of hosts)
4. Check the checkboxes of some Host(s)
5. Click on some button under _Configuration/Policy/Power_
=> Nothing happens, buttons don't work, the screen does not change
**Before:** (for example tagging of some host - nothing happens)
**After:**(tagging screen displayed and everything works well)
**Note:**
I added `include EmsCommon` to host aggregate controller …

Fix toolbar buttons for Hosts displayed thru Host Aggregate's details page

---

app/controllers/mixins/ems_common_angular.rb

This was initially created to address credential validation for OpenStack (BZ#1593663) which is now  directly handled in raw_connect.
Meanwhile the cosmetic change is still relevant as it makes `get_task_args`a bit more readable.

Makes get_task_args a bit more readable

---

app/services/customize_fields_visibility_service.rb
app/views/miq_request/_prov_field.html.haml
app/views/shared/views/_prov_dialog.html.haml
spec/services/customize_fields_visibility_service_spec.rb

Add sysprep specification support for vm provisioning from template
for the oVirt provider.
Depends on: https://github.com/ManageIQ/manageiq/pull/17636
Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/275
Implements: https://bugzilla.redhat.com/show_bug.cgi?id=1553833

Add sysprep support for ovirt

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1630385
https://bugzilla.redhat.com/show_bug.cgi?id=1631035
There was a problem while adding a new _Service Catalog Item_: nothing happened in the UI, no change, Catalog Item was not saved; no error message; error in log occurred.
2. _Configuration > Add a New Catalog Item_
3. Choose some _Catalog Item Type_ (for example _Generic_)
4. Fill in the _Name_, choose some _Dialog_ (yes, you need to create some Dialog before these steps if there are no ones)
5. Click on _Add_ button
=> error:
```
[----] I, [2018-09-19T15:23:20.118597 #15419:2ac596b87b54]  INFO -- : Started POST "/catalog/servicetemplate_edit?button=add" for ::1 at 2018-09-19 15:23:20 +0200 …
```

Fix adding a new Service Catalog Item

---

app/assets/javascripts/controllers/notifications/notifications_drawer_controller.js
app/views/static/notification_drawer/notification-body.html.haml

I missed this, my bad :cry: this function in the controller is necessary for the notifications retrieved via API.
Fixes #4686
@miq-bot add_reviewer @AparnaKarve 

Fix the view details link on notifications that were retrieved via API

---

spec/controllers/miq_report_controller/dashboards_spec.rb
spec/controllers/ops_controller/settings/common_spec.rb

```
rspec ./spec/controllers/ops_controller/settings/common_spec.rb:236 # OpsController OpsController::Settings::Common #settings_get_info zone node sets ntp server info for display
rspec ./spec/controllers/miq_report_controller/dashboards_spec.rb:54 # ReportController::Dashboards #db_fields_validation No flash message set when tab title is unique within a group
rspec ./spec/controllers/miq_report_controller/dashboards_spec.rb:63 # ReportController::Dashboards #db_fields_validation No flash message set when tab title is changed for Default Dashboard
rspec ./spec/controllers/miq_report_controller/dashboards_spec.rb:45 # ReportController::Dashboards #db_fields_validation display flash message for uniqueness of tab title of dashboard within a group
```
and 
sporadic failure
```
1) …
```

[GAPRINDASHVILI] Fix spec failures

---

app/controllers/application_controller/ci_processing.rb
app/controllers/mixins/checked_id_mixin.rb
spec/controllers/application_controller/ci_processing_spec.rb
spec/controllers/cloud_network_controller_spec.rb
spec/controllers/cloud_object_store_container_spec.rb
spec/controllers/cloud_object_store_object_spec.rb
spec/controllers/network_router_controller_spec.rb

This PR removes the last bits of obsolete methods `find_checked_ids_with_rbac` and `find_id_with_rbac`.
Marking this as _WIP_ until PRs #4598 and #4601 are merged.
Links
* #1134
Delete a Datastore

Replaced obsolete method for record fetching with RBAC in ci_processing

---

app/controllers/application_controller/ci_processing.rb

This issue was introduced with cleanup changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/4604 . Fixed to pass in item ids in sorted order to fix test failures.
fixing test failures https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/433516834

Fixed code to get tests to pass

---

app/controllers/report_controller/reports/editor.rb
spec/controllers/miq_report_controller/reports/editor_spec.rb

Previously it was always checking for "miq_report_edit" feature when adding a report or changing between tabs in report editor. Fixed to check for correct feature id.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1631892
@skateman please review/test.

Fixed code to check for correct RBAC feature when adding/editing report

---

app/views/ops/_db_summary.html.haml

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1623091
Wrong variable name was assigned to the component props, that is why it was not showing the summary screen.
Also the JS errors were caused by extra semicolon in props JSON definition.

Fix variable name and extra semicolon in VMDB summary view

---

app/assets/stylesheets/patternfly_overrides.scss

This is a small fix for the switch card on `PhysicalInfra` dashboard view, not sure why the `pficon` is required for it to work properly.
After adding the `pficon` on `PhysicalSwitchDecorator` all other physical switch across the application seems ok.
Caused by https://github.com/ManageIQ/manageiq-ui-classic/pull/4571/files#diff-56332bbfcf2fe957b5164fc8d340288fL41
/cc @mzazrivec @skateman

Fix the way that switch card is being displayed on the dashboard

---

spec/controllers/cloud_object_store_object_spec.rb

Replaces mocking of `Classification` with **FactoryGirl tagging**
**Let variables** are used instead of `@variables`
Same process as #4634 #4676 #4683

Refactored cloud_object_store_object_spec with using let variables and removing classification mocking

---

spec/controllers/cloud_network_controller_spec.rb

Replaces mocking of `Classification` with **FactoryGirl tagging**
**Let variables** are used instead of `@variables`
Same process as #4634 #4676

Refactored cloud_network_controller_spec with using let variables and removing classification mocking

---

spec/controllers/cloud_subnet_controller_spec.rb

Replaces mocking of `Classification` with **FactoryGirl tagging**
**Let variables** are used instead of `@variables`
Same process as #4634 #4676 #4683
@skateman Can you please review it? :pray: It is very similar to #4683

Refactored cloud_subnet_controller_spec with using let variables and removing classification mocking

---

spec/controllers/cloud_tenant_controller_spec.rb

- Replaces mocking of `Classification` with **FactoryGirl tagging**
- **Let variables** are used instead of `@variables`
Same process as #4634 #4676 #4683 #4683
---

Refactored cloud_tenant_controller_spec with using let variables and removing classification mocking

---

app/controllers/miq_policy_controller/conditions.rb

condition modifier was removed from models in https://github.com/ManageIQ/manageiq/pull/16213
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1633606
@gtanzillo @lfu @dclarizio please review.

Removed reference to condition modifier

---

spec/controllers/cloud_volume_backup_controller_spec.rb

- Replaces mocking of `Classification` with **FactoryGirl tagging**
- **Let variables** are used instead of `@variables`
Same process as #4634 #4676 #4683 #4683
---

Refactored cloud_volume_backup_controller_spec with using let variables and removing classification mocking

---

app/assets/stylesheets/patternfly_overrides.scss

This PR fixes a bug where the bootstrap switches wrapped on some screens.
Old
New
https://bugzilla.redhat.com/show_bug.cgi?id=1549076

Fix wrapping switch

---

app/helpers/textual_mixins/textual_power_state.rb

The `normalized_state` method should be used for full consistency with quadicons.
**Before:**
**After:**
@miq-bot add_label bug, gaprindashvili/no, hammer/yes

Pass normalized_state into textual summaries for consistency

---

spec/controllers/auth_key_pair_cloud_controller_spec.rb

Replaces mocking of `Classification` with **FactoryGirl tagging**
**Let variables are used** instead of `@variables`
Same process as #4634 
@miq-bot add_label gaprindashvili/no, refactoring

Refactored auth_key_pair_cloud_controller_spec with using let variables and removing classification mocking

---

app/controllers/application_controller/miq_request_methods.rb

1. Compute ➛ Infra ➛ Virtual Machines ➛ select a VM you can migrate ➛ Lifecycle ➛ Migrate Selected Items
2. Switch tabs in the rendered form
Before, the following error would show:
```
FATAL -- : Error caught: [ActiveRecord::RecordNotFound] Couldn't find MiqTemplate without an ID.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/relation/finder_methods.rb:66:in `find'
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/querying.rb:3:in `find'
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7/lib/active_record/core.rb:151:in `find' …
```

Fix UI error when migrating virtual machine

---

app/controllers/application_controller.rb
app/controllers/report_controller/reports/editor.rb
app/helpers/vm_helper/textual_summary.rb

As mentioned in https://github.com/ManageIQ/manageiq-ui-classic/pull/4658#discussion_r218052458

Don't use if/unless inside a string interpolation

---

app/presenters/menu/default_menu.rb

- Add `Chassis` link into `Compute > Physical Infrastructure`
__Before this PR__
__After this PR__
@miq-bot add_label hammer/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1633186

Add Physical Chassis link to default menu

---

app/presenters/tree_builder_archived.rb
spec/presenters/tree_builder_archived_spec.rb
spec/presenters/tree_builder_images_spec.rb
spec/presenters/tree_builder_instances_spec.rb

This will make the tree nodes fully consistent with the quads.
**Before:**
**After:**
@miq-bot add_label gaprindashvili/no, hammer/yes, graphics

Put background under archived/orphaned tree node icons in VMs

---

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
app/controllers/cloud_volume_controller.rb
app/views/cloud_volume/_common_new_edit.html.haml
spec/controllers/cloud_volume_controller_spec.rb

Allows selecting an optional Volume Type when creating an Openstack cloud volume. Generalizes the existing AWS volume type code in the new volume form wherever possible.
Implements https://bugzilla.redhat.com/show_bug.cgi?id=1550008

Allow selecting an optional volume type when creating an Openstack cloud volume

---

app/presenters/tree_builder_infra_networking.rb

Compute -> Infrastructure -> Networking -> select a switch in summary of another node like root
(You need to have some `Switch` with `shared` set to `true`.)
**Before:**
Switch node isn't selected but summary of the switch is displayed
**After:**
Summary and selected node match each other.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1460992

Remove full_ids from infra networking tree to fix error in selection

---

app/controllers/ops_controller/settings.rb
app/controllers/ops_controller/settings/common.rb
app/controllers/ops_controller/settings/help_menu.rb
app/views/ops/_settings_workers_tab.html.haml
spec/controllers/miq_request_controller_spec.rb
spec/controllers/ops_controller/settings/common_spec.rb
spec/controllers/ops_controller_spec.rb
spec/controllers/ops_settings_spec.rb

This pull request removes all traces of deprecated `VMDB::Config` class usage from the UI repo.
~~Depends on: https://github.com/ManageIQ/manageiq/pull/18024~~

Remove deprecated VMDB::Config class

---

app/controllers/application_controller/wait_for_task.rb

while waiting for a task, we sometimes want to show a flash indicating the UI is waiting fro the task to finish
this allows us to use something like..
```
add_flash(_("Task queued"))
initiate_wait_work_task(..., :flash => true)
```
and expect a flash message to be shown under the spinner
Comes from a discussion in https://github.com/ManageIQ/manageiq-ui-classic/pull/4628, cc @yrudman 
Note this will eat any queued flash messages (which is probably ok, since any success/error messages should come from the `:action`).

initiate_wait_for_task - support :flash => true to flash while waiting

---

app/helpers/application_helper/toolbar/saved_reports_center.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1632630
**Additional Issue** https://github.com/ManageIQ/manageiq-ui-classic/issues/4733 (the show fullscreen report still won't work properly, but that is a different issue)
1. Queue 2-3 reports. Make sure at least one of them is non-empty.
2. Go to 'Saved Reports' Accordian.
3. Select one of the reports(non-empty report) from the table. 
4. Click on 'Configuration' and check if 'Show full screen report' is enabled/active.
It should be enabled, but it isn't.
@miq-bot add_label gaprindashvili/no, hammer/yes, bug, cloud intel/reporting
**Credits**
It was solved by help of @romanblanco

Fixes disabled 'Show full screen report' button on Saved Reports page

---

app/helpers/vm_helper/textual_summary.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1627673
before
after

Fixed CPU value display on VM summary

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/javascript/packs/globals.js
bower.json
package.json
spec/javascripts/globals_pack_spec.js

~~Depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/4641~~
With patternfly-timeline, we need to use a commit version, as 1.0.7 is impossible to install,
and the fix (https://github.com/patternfly/patternfly-timeline/pull/42) was never released (issue https://github.com/patternfly/patternfly-timeline/issues/52).
So, using the current master tip for now.
Issue: #3734

bower to npm: patternfly-timeline (@pf3/timeline)

---

app/controllers/application_controller/miq_request_methods.rb
app/views/miq_request/_request.html.haml
app/views/miq_request/_service_retire_show.html.haml
spec/controllers/miq_request_controller_spec.rb

With this commit we make sure correct VMs are shown as part of service retirement request. Talking about "Affected VMs" section that now looks like:
Prior to this commit there was always only a single VM displayed in there, and it was not the right one. Happened to see AWS EC2 VM on a vCloud vApp retirement request details!
The reason for all this was that
```
@miq_request.options[:src_ids]
```
was treated as it's a list of VM ids whereas it infact was a list of Service ids. If we were lucky enough, some Service id collided with random VM id and BUUUM, wrong VM was shown.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1632239
Related PRs:
- https://github.com/ManageIQ/manageiq/pull/18023
- https://github.com/ManageIQ/manageiq-content/pull/432
- …

Show correct VMs upon Service retirement

---

app/services/ems_cloud_dashboard_service.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1636160
before:
after:

Fixed links for vm/templates to instances/images on cloud dashboard

---

app/helpers/host_helper/textual_summary.rb

Added conditions, validating if `cloud_networks` and `cloud_subnets` are present for infra host
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1635126

Add validation for cloud_networks and subnets

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/assets/stylesheets/print.scss
bower.json
package.json
tools/ci/setup_js_env.sh

Issue #3734 
Depends on #4690
Moves ui-components to npm.

bower to npm: manageiq-ui-components

---

app/assets/javascripts/services/miq_db_backup_service.js
app/views/ops/_log_collection.html.haml

Configuration ➛ Diagnostics ➛ click on a server ➛ Collect Logs ➛ Edit ➛ Add / edit FTP depot
Without this fix, credentials (username & password) for the ftp depot wouldn't show.
https://bugzilla.redhat.com/show_bug.cgi?id=1627273

Fix FTP credentials for log depot

---

app/helpers/application_helper/toolbar/saved_reports_center.rb

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1632630
Closes: https://github.com/ManageIQ/manageiq-ui-classic/issues/4733
response to my comment https://github.com/ManageIQ/manageiq-ui-classic/pull/4734#issuecomment-427394095.
Rather than modifying the button so it's never visible for the list view it's better to remove it completely from the toolbar
Links
* https://github.com/ManageIQ/manageiq-ui-classic/issues/4733
* https://bugzilla.redhat.com/show_bug.cgi?id=1632630
Cloud Intel - Reports - Saved Reports accordion
* the "Show full screen Report" will only be available on the detail of the report

Removing button for showing fullscreen report from list view

---

app/controllers/catalog_controller.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1630385
**What:**
There was a problem while adding a new Service Catalog Item for _Vmware_ Catalog Item Type: nothing happened in the UI, no change, Catalog Item was not saved; no error message; error in log occurred.
2. _Configuration > Add a New Catalog Item_
3. Choose _Catalog Item Type_: _VMware_
4. Fill in the _Name_, choose some _Dialog_ (yes, you need to create some Dialog before these steps if there are no ones), no matter if you choose some _Catalog_ or not
5. Click on _Add_ button
=> error:
```
[1] pry(#<ManageIQ::Providers::Vmware::InfraManager::ProvisionWorkflow>)> 
[----] F, [2018-10-09T16:17:08.243588 #18459:2b22530a6b6c] FATAL -- : Error …
```

Fix adding a new Service Catalog Item for Vmware Catalog Item Type

---

app/presenters/menu/default_menu.rb

previously there were a lot of Menu::Item instances using an url like `/container`.
This is OK, but it means a redirect to `/container/show_list` every time that menu item is accessed.
Updating to make all menu items use the default redirect URL.
This means the only non-external urls remaining without a method part are: `/bottlenecks`, `/graphql_explorer`, `/planning` and `/utilization` - all of these work without a redirect.
https://bugzilla.redhat.com/show_bug.cgi?id=1571223

Default menu - fix all menu items to use full url

---

spec/controllers/application_controller/ci_processing_spec.rb

Fixes following specs:
```
rspec ./spec/controllers/application_controller/ci_processing_spec.rb:865 # ServiceController#vm_button_operation should continue to retire a service and does not render flash message 'xxx does not apply xxx' 
rspec ./spec/controllers/application_controller/ci_processing_spec.rb:934 # VmOrTemplateController#vm_button_operation should continue to retire a vm
```
Related to `Zone` changes in https://github.com/ManageIQ/manageiq/pull/17987
cc @simaishi 
@skateman please have a look, thanks :)

[GAPRINDASHVILI] Fix failing specs

---

app/controllers/orchestration_stack_controller.rb

This is an additional fix for gaprindashvili branch for backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/4464
Without this fix, the following error would show when clicking on child orchestration stacks:
```
FATAL -- : Error caught: [ArgumentError] wrong number of arguments (given 4, expected 5..7)
/opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-52fa82a4ed63/app/controllers/mixins/explorer_show.rb:11:in `show_association'
/opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-52fa82a4ed63/app/controllers/orchestration_stack_controller.rb:28:in `display_children'
/opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-52fa82a4ed63/app/controllers/mixins/generic_show_mixin.rb:137:in `public_send'
/opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-52fa82a4ed63/app/controllers/mixins/generic …
```

[GAPRINDASHVILI] Add listicon parameter for child stack display

---

.travis.yml

This changes the version of postgresql we're using on travis to 9.5.
Matches core: https://github.com/ManageIQ/manageiq/pull/15994
This fixes the current travis breakage:
```
PG::UndefinedFunction: ERROR:  function array_position(bigint[], bigint) does not exist
```
(introduced in https://github.com/ManageIQ/manageiq/pull/18060, but only because we no longer support 9.4).
Discussion in https://github.com/ManageIQ/manageiq/pull/18060
(more changes to clean up 9.4 mentions will follow in separate PRs)

Travis - change postgresql to 9.5

---

app/views/miq_ae_customization/_dialog_sample.html.haml

The issue states that there was an infinite spinner when clicking on the dialog to edit in the Automate -> Customization section, which uses the sample page to initially show the dialog.  However, the sample page has no reason to call the offending method `initializeDialogSelectPicker` since that method sets up the field to call to a url and/or trigger refreshes which make no sense on the sample page. Thus, we should simply use `miqInitSelectPicker` to give us the patternfly styling we want without the unnecessary setup.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1638420

Fix for javascript error when attempting to edit a service dialog based on orchestration template

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js

In a multi-tab form, when user hits the Enter key (and not the "Validate" button), the credential type passed down to the backend is always `default`, which leads to incorrect validation if the active tab is not "default", as described in the BZ
To fix this, we need to always refer to the `currentTab` value that accurately gives us the actual credential type for the currently active tab.
https://bugzilla.redhat.com/show_bug.cgi?id=1609735

Fix multi-tab endpoint credential validation by passing the right credential type when user hits "Enter"

---

app/controllers/application_controller.rb
spec/controllers/application_controller/report_data_spec.rb

Reports on Save Report screen, should use default item count per page which is set in My Settings for Reports. `@gtl_type` variable used from deriving the per page count only can be `grid`, `tile` or `list`
https://bugzilla.redhat.com/show_bug.cgi?id=1616201
1. Go to My Settings > Visual.
2. Inside 'Default Items Per Page', set 'Reports' limit to anything except 20.
3. Go to Cloud Intel > Reports > Saved Reports > All Saved Reports.
4. If there aren't any saved reports, queue a report.
5. On the `All Saved Reports`, check the paginator - value remains 20.

Use report default options for Report screens

---

app/controllers/cloud_tenant_controller.rb
app/controllers/cloud_tenant_dashboard_controller.rb
app/helpers/application_helper/toolbar/cloud_tenant_center.rb
app/services/cloud_tenant_dashboard_service.rb
app/services/ems_cloud_dashboard_service.rb
app/services/ems_dashboard_service.rb
app/views/cloud_tenant/_recent-images-line-chart.html.haml
app/views/cloud_tenant/_recent-instances-line-chart.html.haml
app/views/cloud_tenant/_show_dashboard.html.haml
app/views/cloud_tenant/show_dashboard.html.haml
config/routes.rb
spec/controllers/cloud_tenant_controller_spec.rb

This PR adds the dashboard for Cloud Tenants. This dashboard is the same as the EmsCloud has.
https://bugzilla.redhat.com/show_bug.cgi?id=1487178
@himdel 
@terezanovotna 
@aufi 
@alexander-demichev

Add dashboard for cloud tenant

---

app/assets/javascripts/components/cloud_network/cloud-network-form.js
app/views/static/cloud_network/cloud-network-form.html.haml

Physical Network field is visible for all types of  RHOS networks, but it makes sanse only for Flat network.
https://bugzilla.redhat.com/show_bug.cgi?id=1540684

Make physical network visible only for FLAT and VLAN

---

app/controllers/application_controller/buttons.rb
app/views/shared/buttons/_ab_options_form.html.haml
spec/controllers/application_controller/buttons_spec.rb

It's possible to create a custom button with an Open URL for entities that don't support it. This will prevent it. Only entity that allows it is VM (checked with @pkomanek).
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1635797 but fix for that error is https://github.com/ManageIQ/manageiq-ui-classic/pull/4745 .
**Before:**
User could create a custom button with Open URL for any entity. After clicking the button it kinda failed.
**After:**
User isn't allowed to create a custom button with Open URL for entity that doesn't support `remote_console_url` (only VM does) with `Display for` not set to `Single`. Like this for Datastore.
@miq-bot add_label enhancement, hammer/no, automation/automate, ux/review
@terezanovotna please check it from UX point of view, thanks :)

Disable Open URL for all models that don't have remote_console_url

---

app/controllers/physical_switch_controller.rb
app/helpers/physical_switch_helper/textual_summary.rb
spec/helpers/physical_switch_helper/textual_summary_spec.rb

This PR moves the connected physical servers from the Connected Components table on the Switch Summary page to the Relationships table. Also this PR removes the Connected Components table since it is now empty and no longer used.

Move connected physical servers to the Relationships table

---

app/views/layouts/angular/_ansible_form_options_angular.html.haml

This PR fixes a problem with the "Variables & Default Values" fields, where the "Required" message did not appear under the appropriate field.
Old
New
https://bugzilla.redhat.com/show_bug.cgi?id=1640608

 Fix Ansible Playbook 'New Catalog Item' styling issue

---

app/views/static/notification_drawer/notification-body.html.haml

**Before:**
**After:**
@miq-bot add_label bug, gaprindashvili/no, hammer/yes
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640144

Display notifications in the expanded notification drawer

---

app/controllers/ops_controller/settings/common.rb
spec/controllers/ops_controller/settings/common_spec.rb

Current server never returns its zone in get_configso it has to be checked and set correctly. Gaprindashvili backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/4072
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639877

[Gaprindashvili] - Make sure @edit[:current].config[:server][:zone] is set

---

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
app/controllers/application_controller/buttons.rb
app/views/shared/dialogs/_dialog_provision.html.haml
spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js

- Add open_url to local_options for non-explorer screens
- Fix error handling when Automate does not return url
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1574403
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1635797
Create custom button with dialog but without Open URL for Datastore with `Display for` set to `Single`.
Automation -> Automate -> Customization -> Buttons
Go to Datastore summary page and click the new button.
Before:
```
FATAL -- : Error caught: [ActionView::Template::Error] undefined local variable or method `open_url' for #<#<Class:0x00007fab97d529e8>:0x00007fab89690820>
Did you mean?  ops_url
manageiq-ui-classic/app/views/shared/dialogs/_dialog_provision.html.haml:45:in `__anage___manageiq_ui_classic_app_views_shared_dialogs__dialog_provision_html_haml__11010569 …
```

Fix error for Datastore custom button

---

app/assets/javascripts/controllers/report_data_controller.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639213
1. Add infra or cloud provider
2. Navigate to **Compute -> Infrastructure -> Virtual Machines**
or **Compute -> Clouds -> Instances**
3. Click on **Lifecycle -> Provision VMs**
or **Lifecycle -> Provision Instances**
4. Click **Cancel**
Two success messages appear, one without text
One success message appears
- This is a just a a suggestion how to solve it. I would appreciate any help!
The `oneMessage.msg` ( [here](https://github.com/karelhala/manageiq-ui-classic/blob/bf4f5803149b4e7393452acec2b4f3899858e793/app/assets/javascripts/controllers/report_data_controller.js#L496) , introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/1245 ) is undefined, so it's causing empty messages. It should be `oneMessage.message`, but …

Remove catching flash messages in report_data_controller.js

---

app/controllers/application_controller/performance.rb
app/controllers/application_controller/performance/options.rb

reaction on https://github.com/ManageIQ/manageiq-ui-classic/pull/652#discussion_r226995650
instance variable `@compare_vm_chart_data` is not used anywhere in the codebase anymore

Removed dead code in performance controller

---

app/assets/javascripts/services/alerts_center_service.js
app/controllers/restful_redirect_controller.rb
spec/controllers/restful_redirect_controller_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1637609

Fixed links to point to correct provider controller based upon type.

---

app/javascript/components/miq-about-modal.jsx

The `region_href` and `zone_href` attributes from the `server_info` have been used in two consecutive API requests to retrieve the required extra data. Maybe I'm not doing the assignments *The Right Way&trade;*, but IMO there's no such thing in the JS world, so I'll just let @Hyperkid123 review this.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1402112

[RFE] Display current zone name and region number in the about modal

---

app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

There are `Template` objects that are available to have custom buttons attached to them on the Compute -> Clouds -> Instances -> Images screen, which corresponds to `vm_cloud/explorer` in the url, but the code was incorrectly assuming all templates would be nested under `vm_or_template/explorer`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640592
@miq-bot add_label bug, gaprindashvili/yes, hammer/yes

Fix vm_cloud image custom button return and cancel endpoints

---

app/controllers/application_controller/ci_processing.rb

**Issue**: in multiregion environment attempt to retire service replicated to Global region will fail with "The selected Service is not in the current region"
**This PR:**  allow `retire_now` task to be processed via Centralized Administration for `Service` and `OrchestrationStack`
**BEFORE**:
**AFTER**:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1633142
@miq-bot add-label bug, gaprindashvili/yes, hammer/yes

Allow Service retirement over Centralized Administration

---

app/views/static/notification_drawer/_notification-body.html.haml

This is a regression caused by https://github.com/ManageIQ/manageiq-ui-classic/pull/4057 and a bug in `angular-bootstrap` as it does not behave for all prefixes as it should.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1635597

Fix bottom tooltip placement for notifications in the drawer

---

app/controllers/report_controller/reports/editor.rb

Only update report name for user's group menu when editing an existing report. Since report are saved by name in user's group record for menus, updating report name while copying a report was causing an issue of showing incorrect reports in user created custom folders. Newly added and copied reports by default get added into My Company/Custom folder.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641771

Only update report name in group reports menu when editing a report

---

app/controllers/catalog_controller.rb

Need to set `@in_a_form` for the code to go thru correct path and hide paging bar when ordering a catalog from list view screen.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1642595
before
after

Setting `@in_a_form`

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1639557
1. Go to _Services -> Catalogs -> Catalog Items_ accordion
2. Add two _Catalog Items_ (if there are none; under _Configuration -> Add a New Catalog Item_)
3. Add a new _Catalog Bundle_ (_Configuration -> Add a New Catalog Bundle_)
4. Edit the bundle from the previous step (_Configuration -> Edit Selected/this Item_)
5. Go to _Resources_ tab and try to remove one of the resources
=> error:
```
[----] I, [2018-10-24T16:16:47.118861 #8111:2ae71328083c]  INFO -- : Started POST "/catalog/resource_delete/60?grp_id=0&rec_id=120" for ::1 at 2018-10-24 16:16:47 +0200
[----] I, [2018-10-24T16:16:47.178274 #8111:2ae71328083c]  INFO -- : Processing by CatalogController#resource_delete as JS
[----] I, …
```

Fix removing catalog items from Catalog Bundle resource list

---

app/controllers/physical_server_controller.rb
app/helpers/physical_server_helper/textual_summary.rb
app/views/physical_server/show.html.haml
spec/helpers/physical_server_helper/textual_summary_spec.rb

This PR adds the physical switches relationship to the Relationships table on the Physical Server Summary page.

Add physical switches to the Physical Server page Relationships table

---

app/controllers/ops_controller.rb

Load custom buttons toolbar when returning or refreshing list view for User/Tenant/Groups in Access Control accordion
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1642939
before
after

Load correct Mixins::CustomButtons::Result when browser is refreshed

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/controllers/mixins/ems_common_angular.rb
app/views/layouts/angular/_multi_auth_credentials.html.haml
spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js

Adjusted Container Provider tab names so that they are consistent with what's specified in the haml and the value passed to the angular controller when Validate is clicked.
This is also a continuation of work for this PR - https://github.com/ManageIQ/manageiq-ui-classic/pull/4768
https://bugzilla.redhat.com/show_bug.cgi?id=1609735
https://bugzilla.redhat.com/show_bug.cgi?id=1640304

Rename tabs in the haml to match current tab in the controller scope

---

app/javascript/forms/form-buttons-redux.jsx

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1643436
**The bug is reproducible only in production ENV.** It was causing infinite loop in react component inside the modal. I am not sure why.
Once i've moved redux initialization out of the FormButtonsRedux component, the problem was gone. This is probably due to a small difference in how are reducers registered. Before new reducer was added to the redux store only after some action was dispatched. Now it is visible immediately after registering. This probably cause state updates before the component is mounted and that may cause constant rendering and infinite loop. Probably some magic in PF3 Modal component, but again i am not 100% sure.

Move reducer initialization out of the buttons component.

---

app/controllers/application_controller/tags.rb
spec/controllers/application_controller/tags_spec.rb

Code was checking for feature id as ems_infra_tag when trying to tag selected storages thru Provider relationship screen. This was causing an issue when user did not have access to ems_infra_tag feature but had access to storage_tag feature. Fixed code to check if `@display` is set to use that when setting feature id to check for.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610957

Fixed feature id when checking assert_privileges.

---

app/assets/javascripts/controllers/report_data_controller.js

`scrollElement` is only ever assigned to, never used (in ui-classic or in ui-components) => removing.
also removes a typo `MAIN_CONTETN_ID`, replaced by searchable `#main-content`
and cleaned up the function a bit :).

ReportDataController - remove dead scrollElement

---

app/views/layouts/exp_atom/_editor.html.haml

some actions in the advanced search modal would previously only trigger the big sparkle, which happens under the model
this makes the commit & discard buttons use the search spinner, which happens over the modal
https://bugzilla.redhat.com/show_bug.cgi?id=1469151

Advanced search - use the right spinner

---

app/controllers/application_controller.rb
app/controllers/application_controller/buttons.rb
app/controllers/mixins/custom_buttons.rb
app/helpers/application_helper/toolbar/mixins/custom_button_toolbar_mixin.rb
app/helpers/application_helper/toolbar_builder.rb
spec/controllers/ems_cloud_controller_spec.rb
spec/controllers/ems_container_controller_spec.rb
spec/controllers/ems_infra_controller_spec.rb
spec/controllers/ems_network_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb
spec/shared/controllers/shared_example_for_custom_buttons.rb

The code displays the custom buttons if the previous screen was a
provider screen (`@record`) and displayed item (`@display`) is from the list
of classes supported by custom buttons (`APPLIES_TO_CLASS_BASE_MODELS`)
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1635738
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1635738
* #4772
*  Create a custom button for any entity
*  Navigate to the entity through the provider relationship screen
*  Custom button should be visible

Display custom buttons after comming from relationship table

---

app/views/catalog/_form_resources_info.html.haml

Backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/4488 broke the observer for Action order drop down. In https://github.com/ManageIQ/manageiq-ui-classic/pull/2482 use of compressed ids was removed from https://github.com/ManageIQ/manageiq-ui-classic/pull/2482/files#diff-10a8b10a2fee4a8ed7444f35479d9444L66 causing the observer and field name to not match.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618836

[GAPRINDASHVILI] Fixed action order field name to be consistent with observer

---

app/controllers/miq_task_controller.rb
spec/controllers/miq_task_controller_spec.rb

**Issue**: not rescued Runtime Error shown in UI when not permitted signal sent to Smart State Analysis state machine.
Bug was introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/242
**Fix**: `rescue` error raised by state machine
**Before:**
**After:**
@miq-bot add-label bug, blocker, hammer/yes, gaprindashvili/yes
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640704
\cc @h-kataria

Rescue error when canceling job

---

spec/controllers/miq_ae_customization_controller/dialogs_spec.rb

https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/448783132 caused by https://github.com/ManageIQ/manageiq/pull/18102
We need `MiqProductFeature.seed` to create product tenant features which are part of autorisation process.
Not if this should be labled as blocker.

Fix CI After Dynamic Product Features

---

product/views/ManageIQ_Providers_CloudManager_Vm-all_vms_and_templates.yaml
product/views/ManageIQ_Providers_CloudManager_Vm-vms.yaml
product/views/ManageIQ_Providers_CloudManager_Vm.yaml
product/views/ManageIQ_Providers_InfraManager_Vm.yaml
product/views/Vm-all_vms.yaml
product/views/Vm.yaml
product/views/VmOrTemplate-all_vms_and_templates.yaml
product/views/VmOrTemplate.yaml
product/views/Vm__restricted.yaml
spec/controllers/application_controller/report_data_spec.rb

I looked for all the yaml reports containing `Vm` in their filename:
```
$ find product/views | grep Vm
product/views/VmdbIndex.yaml - irrelevant
product/views/ManageIQ_Providers_CloudManager_Vm-vms.yaml
product/views/VmdbDatabaseSetting.yaml - irrelevant
product/views/Vm.yaml
product/views/ManageIQ_Providers_CloudManager_Vm-all_vms_and_templates.yaml
product/views/Vm-all_vms.yaml
product/views/ManageIQ_Providers_Vmware_CloudManager_OrchestrationTemplate.yaml - irrelevant
product/views/VmOrTemplate.yaml
product/views/ManageIQ_Providers_InfraManager_Vm.yaml
product/views/VmOrTemplate-all_vms_and_templates.yaml
product/views/VmdbTableEvm.yaml - irrelevant
product/views/VmdbDatabaseConnection.yaml - irrelevant
product/views/VmOrTemplate-all_orphaned.yaml - orphaned is a power state …
```

[RFE] Display Vm power state in the related grid views

---

app/controllers/ops_controller/ops_rbac.rb
spec/controllers/ops_controller/ops_rbac_spec.rb

Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/4720
- Have a bunch of tenants
- If you have all tenants in one region `Tenant.count == Tenant.in_my_region.count` set `id` of one of tenants to something outside current region(multiple its `id` by 3 or something)
- Go to Configuration -> Access Control -> click a region
In this case `cloudusers` tenant is not in `Tenant.in_my_region`
Before:
After:
@miq-bot add_label bug, hammer/no,

Filter tenants and groups in Access Control by current region

---

app/javascript/spec/dashboards/widget-empty.spec.js
app/javascript/spec/dashboards/widget-wrapper.spec.js

Fixes code climate warnings left from #4842.
An else after return, and old-style mulitline strings.

dashboard widget specs - fix codeclimate issues

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643458
In order to recreate, Go to List of Hosts and select one of the default filters on the left and set it as default filter.  Then try to apply tags to one or more hosts, when trying to make selection on tagging screen, it should throw an error because call to `load_default_search` method corrupts `@edit` hash.

No need to load default search when user is on tagging screen.

---

app/controllers/ops_controller/diagnostics.rb

Closes #4719 .
Have two Regions each with one or more servers.
Configuration -> Diagnostics -> select Region -> select Servers tab -> see that number of servers in tree and in GTL isn't same
Before:
After:

Show only servers in current region in Diagnostics

---

app/assets/javascripts/controllers/report_data_controller.js
app/assets/javascripts/miq_application.js
app/helpers/gtl_helper.rb

this changes the GTL spinner code to show the ManageIQ spinner when the content is loading
this should prevent timing issues when trying to switch views (tree_select) when a GTL view is being loaded
using `ManageIQ.gtl.loading` in `miqSparkleOff` is ...sub-optimal,
but I'm currently seeing no way not to do that without the spinner disappearing and reapearring when the ajax request finishes but before the angular gtl code finishes initializing
Probably needs quite some testing :).
https://bugzilla.redhat.com/show_bug.cgi?id=1626627

GTL - use miqSparkle-style spinner when loading

---

app/controllers/application_controller/buttons.rb

Problem is, that if the 'Open URL' is checked, and 'Display for' is changed to anything else than `Single`, the 'Open URL' checkbox gets disabled and it's not possible to uncheck it.
After these changes, the checkbox is automatically unchecked, if the button is supposed to be displayed for a list.
Also the checkbox will only be visible for a VM and Instance buttons, as it can only be applied there.
1) Automation - Automate - Customization - Buttons
2) add a Custom Button to a VM and Instance model

 Turn off 'open_url' if the button is to be displayed for a list

---

app/presenters/menu/default_menu.rb
spec/presenters/menu/default_menu_spec.rb

depending on:
part of issue https://github.com/ManageIQ/manageiq/issues/18100
display menu Customization if any product feature is checked 
and now is enough just to have checked Dialogs 
Links
------
*https://bugzilla.redhat.com/show_bug.cgi?id=1297415
* https://github.com/ManageIQ/manageiq/issues/18100

Add any product product feature for Customization in menu

---

app/controllers/application_controller/buttons.rb
app/views/shared/buttons/_ab_options_form.html.haml

Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/4142
Go to Automate -> Automation -> Custumization -> Buttons -> create/edit one -> set Dialog to something -> set `Display for` to `List` or `Single and List`-> save it
Before:
After:
Also sets Dialog to `nil` when `List` or `Single and List` is selected.
@romanblanco please review, thanks :)

Enable Dialog only for "Display for" set to "Single"

---

app/controllers/auth_key_pair_cloud_controller.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1444520

Stop spinner from spinning forever when creating a new key pair

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/views/layouts/angular/_multi_auth_credentials.html.haml

Gaprindashvili Backport commit from:
#3511 
Original SHA:
486e30ac49d8796d010c718b0a5a44688cda46c7
The metrics & alerts tabs where partially visible.
This PR hides any of the tabs if aren't used in Add/Edit provider.
Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/3498
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1550405
Backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/3511

[GAPRINDASHVILI] Hide disabled tabs

---

spec/controllers/ops_controller/settings/common_spec.rb

Updated spec for setting the server name in the settings form after backport for #4232
Links 
https://github.com/ManageIQ/manageiq-ui-classic/pull/4232

[GAPRINDASHVILI] Updated spec for setting the server name in the settings form

---

app/controllers/mixins/manager_controller_mixin.rb
app/helpers/automation_manager_helper.rb
app/views/automation_manager/_configuration_script.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1645704
before
after

Display Tags info on Job Template summary view.

---

app/views/catalog/_form_basic_info.html.haml

Trying to use grouped_options_for_select for a drop down that does not have grouping was causing an error in the log and preventing from saving manager_id and template_id fields when adding a Catalog Item type of 'Openshift Template'
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1645676
Without the fix it blows up after Provider is selected
```
[----] I, [2018-11-05T15:51:17.919049 #5616:7e9e394]  INFO -- : Started POST "/catalog/atomic_form_field_changed/new?manager_id=10000000000024" for ::1 at 2018-11-05 15:51:17 -0500
[----] I, [2018-11-05T15:51:17.957088 #5616:7e9e394]  INFO -- : Processing by CatalogController#atomic_form_field_changed as JS
[----] I, [2018-11-05T15:51:17.957210 #5616:7e9e394]  INFO -- :   Parameters: {"manager_id"=>"10000000000024", "id"=>"new"}
[----] I, …
```

Fixed to show grouping in drop down only for Ansible Tower type item.

---

app/assets/stylesheets/graphql_explorer.scss
app/views/graphql_explorer/index.html.haml

Replace older mounting mechanism for React components with the new one.
This affects graphlql pluggin and should be merge alongside with https://github.com/ManageIQ/manageiq-graphql/pull/62

Replace grapql explorer react mounter with react macro.

---

app/javascript/spec/.eslintrc.json
app/javascript/spec/helpers/getJSONFixtures.js
config/jest.setup.js
jest.config.js

Added helper that will load contents of json files to jest. It mimics getJSONFixture from jasmine.
@himdel i have added the current fixtures path. That should probably change to jest specific location. But i don't know if some fixtures are shared in multiple spec files and if moving them is feasible right now.

Add getJSONFixture helper to jest config.

---

app/assets/javascripts/components/auth-credentials.js

Added condition that checks protocol value. When you change auth protocol, password field is enabled by default.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1647013

Enabled password editing if log protocol has changed.

---

app/services/dialog_local_service.rb
spec/services/dialog_local_service_spec.rb

Cherry-pick from https://github.com/ManageIQ/manageiq-ui-classic/pull/4795 while fixing the conflicts.
There are `Template` objects that are available to have custom buttons attached to them on the Compute -> Clouds -> Instances -> Images screen, which corresponds to `vm_cloud/explorer` in the url, but the code was incorrectly assuming all templates would be nested under `vm_or_template/explorer`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643263
@miq-bot assign @simaishi 

[GAPRINDASHVILI] Fix vm_cloud image custom button return and cancel endpoints

---

config/webpack/shared.js

Apparently the current set of shims is not enough for IE11, making it impossible to load Switch from patternfly-react.
Adding babel-polyfill fixes that.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1646362

Add babel-polyfill

---

app/helpers/application_helper/toolbar_builder.rb

Reaction to @himdel's https://github.com/ManageIQ/manageiq-ui-classic/pull/4775#issuecomment-436239378
The condition was moved to a correct place (`cb_send_checked_list` method)
Links
* https://github.com/ManageIQ/manageiq-ui-classic/pull/4775
*  Create a custom button for any entity
*  Navigate to the entity through the provider relationship screen
*  Custom button should be visible
(from: https://github.com/ManageIQ/manageiq-ui-classic/pull/4775#issue-222983728)

Corrected logic for rendering custom buttons

---

app/controllers/application_controller/performance.rb

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1647625
caused by: https://github.com/ManageIQ/manageiq-ui-classic/commit/94c979604d207a4f55e8fad51588dbb5ff8a2b79#diff-d2a308103ffc3499b94de33a362bfc74
`daily` and `hourly` attributes were replaced by `end_date` in Timeline::Options. But they were not replaced in Performance controller.
Edit: i think it may also fix https://bugzilla.redhat.com/show_bug.cgi?id=1647632, it seems to me that these are duplicate BZ's. But maybe i've misunderstood the description.

Replaced missing timeline attributes in performance controller.

---

app/views/shared/dialogs/_dialog_user.html.haml

1. create a custom button with a dialog, name it so that it contains an apostrophe in its name, such as: `Button l'Muf`
2. click on the custom button (in the place where the custom button shows)
Without this fix, the following javascript error would show:
```
miq_debug.self-aedfe7fb00583f1da479517ffd299e68803b26c55f81d74f9d992127b311a1f9.js?body=1:29 SyntaxError: missing ) after argument list
at eval (<anonymous>)
at Function.globalEval (jquery.js:343)
at domManip (jquery.js:5291)
at jQuery.fn.init.append (jquery.js:5431)
at jQuery.fn.init.<anonymous> (jquery.js:5525)
at access (jquery.js:3614)
at jQuery.fn.init.html (jquery.js:5492)
at miq_explorer.self-6b27f1944493f686bd5c589f4f733a8d6a1d0aa627bbfd17545cde40c904044f.js?body=1:113
at lodash.js:4925
at baseForOwn (lodash.js:3010)
``` …

Allow apostrophes in custom button names

---

app/controllers/application_controller.rb

1. Navigate to Compute ➛ Infrastructure ➛ Providers ➛ choose a provider ➛ provider summary page
2. Clear memcached
3. On the provider summary page, click on refresh
Before, the failed CSRF token validation would render an exception.
With this fix in place, failed CSRF token validation will void the session and redirect user to login screen.
https://bugzilla.redhat.com/show_bug.cgi?id=1642948

Reset session on failed CSRF token verification

---

app/assets/javascripts/miq_timeline.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1648450
before:
after:
Issue introduced with changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/4217
cc @CharlleDaniel

Fixed JS error, bottlenecks timeline does not have group levels.

---

app/services/cloud_topology_service.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1502857
Openstack CloudManagers often show up with status 'null' and grey rings on the topology view. This is because the CloudTopologyService chooses the first item from the `authentications` list, which is frequently an arbitrary keypair instead of the provider credentials. This PR changes CloudTopologyService to use `authentication_for_providers` like the EmsCloud summary screen, which fixes the problem.

Use EmsCloud.authentication_for_providers to determine topology view status

---

app/controllers/bottlenecks_controller.rb
app/controllers/planning_controller.rb
app/helpers/application_helper/button/utilization_download.rb
app/helpers/application_helper/toolbar_chooser.rb
app/helpers/optimize_helper.rb
app/views/bottlenecks/_bottlenecks_tabs.html.haml
config/routes.rb
spec/helpers/application_helper/buttons/utilization_download_spec.rb
spec/helpers/application_helper/toolbar_chooser_spec.rb
spec/routing/bottlenecks_routing_spec.rb

multiple issues fixed:
1 Download button toolbar was not being rendered for Bottlenecks explorer
2 `change_tab` transaction was not working because the tab id being passed in miq_tabs_init had typo, also fixed typo in method name `bottleneck_get_node_info` it should be `get_node_info`
3 download button was always disabled, added condition to enable download buttons on report tab
4 added missing routes for `change_tab` and `report_download`
5 `report_download` method was missing in controller
Issue was introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/1966
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1648500
before
after

Fixed code to show Bottlenecks report download buttons.

---

app/controllers/application_controller.rb
app/controllers/application_controller/buttons.rb
app/controllers/mixins/custom_buttons.rb
app/helpers/application_helper/toolbar/mixins/custom_button_toolbar_mixin.rb
app/helpers/application_helper/toolbar_builder.rb
spec/controllers/ems_cloud_controller_spec.rb
spec/controllers/ems_container_controller_spec.rb
spec/controllers/ems_infra_controller_spec.rb
spec/controllers/ems_network_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb
spec/shared/controllers/shared_example_for_custom_buttons.rb

@himdel please review this is resolve conflict with a backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/4775 , tested in Gaprindashvili.

[GAPRINDASHVILI] - Custom button thru relationships

---

app/views/ops/_settings_workers_tab.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649799
Value was getting saved properly but need to point to right key in the hash while reading it back to populate the drop down with correct saved value

Fixed reading of ems_refresh_threshold memory_threshold value

---

app/controllers/ops_controller/diagnostics.rb

The list of log collection types is currently built by pulling in all valid FileDepot types.
Unfortunately, while AWS S3 and OpenStack Swift were added as FileDepots for Database backups,
no work was done for Log Collection via these depots.  When the list of valid types is built in the
UI therefore, these two need to be removed.
Before:
After:
@h-kataria please review and merge when appropriate.  Feel free to add other reviewers as necessary.  Thanks.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643966
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1643966

Remove S3 and Swift From List of Log Collection Types

---

app/controllers/application_controller/tags.rb
spec/controllers/application_controller/tags_spec.rb

**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1648658
**What:**
Fix editing tags for VMs, Hosts and others (Clusters... see the BZ) by fixing the string of a feature name for `assert_privileges` method while editing tags.
Error:
```
I, [2018-11-14T16:27:05.394595 #19669]  INFO -- : Started POST "/vm_infra/x_button?pressed=vm_tag" for ::1 at 2018-11-14 16:27:05 +0100
I, [2018-11-14T16:27:05.431705 #19669]  INFO -- : Processing by VmInfraController#x_button as JS
I, [2018-11-14T16:27:05.431827 #19669]  INFO -- :   Parameters: {"miq_grid_checks"=>"26", "pressed"=>"vm_tag"}
F, [2018-11-14T16:27:05.448036 #19669] FATAL -- : Error caught: [MiqException::RbacPrivilegeException] The user is not authorized for this task or item.
/home/hstastna/manageiq/manageiq-ui-classic/app/controllers/a …
```

[GAPRINDASHVILI] Fix editing tags for VMs, Hosts and others

---

app/javascript/forms/form-buttons-reducer.js
app/javascript/forms/form-buttons-redux.jsx
app/javascript/packs/application-common.js

As discussed in https://github.com/ManageIQ/manageiq-ui-classic/pull/4840, i've moved the reducer to separate file.
I've also created constants for action types and exposed them to `ManageIQ.redux` interface. This should prevent any bugs, if we need to change these constants in the future (if consumers will use them instead of strings)

Move form buttons reducer to separate file.

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/controllers/mixins/ems_common_angular.rb
spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js

The GCE provider form does not follow the recommended tab naming convention of naming the first tab as "default" -- instead it calls it's one and only tab as `service_account`. 
As a result, the `currentTab` value in the JS which is "default" (and is correct), is not being honored and this specific use case for GCE has to be explicitly handled.
https://bugzilla.redhat.com/show_bug.cgi?id=1649806

Fix GCE validation

---

spec/helpers/compliance_summary_helper_spec.rb

ManageIQ/manageiq#17475 changed how last_compliance_* methods work,
now, the changes to .compliances need to be saved in the db for these methods to work
Cc @NickLaMuro  ... I hope this makes sense :)

Fix compliance travis - save records after changing compliances

---

app/views/layouts/exp_atom/_editor.html.haml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649057
Having two observers was sending up transaction twice when selecting a value in drop down.

Removed an extra observer from  Edit Selected Element type drop down

---

app/helpers/application_helper/button/utilization_download.rb
spec/helpers/application_helper/buttons/utilization_download_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649945
before
after

Fixed to enable the download buttons on Utilization Report tab

---

app/controllers/mixins/actions/vm_actions/retire.rb

**Issue:**
There is not rescued exception for error raised on backend during execution of retire operation.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1579017
@miq-bot add-label gaprindashvili/yes,  hammer/yes, services, bug
**BEFORE**: there is no any confirmation or error messages when saving new retirement date
**AFTER:**  (if remote server is down)

Rescue error messages when executing retire action

---

spec/helpers/application_helper_spec.rb

This PR removes calls to `allow_message_expectations_on_nil` and unnecessary calls to `allow_any_instance_of` as well as does some cleanup of unnecessary contexts and before blocks.
/cc @skateman I noticed this shiny object when looking at your PR to fix the zone issue earlier today.

Remove allow_message_expectations_on_nil

---

app/decorators/host_decorator.rb

Instead of using `vms.size`, use `v_total_vms`, which will do the same thing, unless the attribute exists on the model, in which it will avoid making a call to the database.
This also means that the call for the size can be done in a single query for an entire collection, instead of a N+1 manner.  This is already done in views like `Host.yaml`, where `v_total_vms` is already in the `cols`.
Metrics
-------
An example set of runs I had with a 47 `Host` provider:
**Before**
`/ems_infra/report_data`
|   ms | queries | query (ms) | rows |
| ---: |    ---: |       ---: | ---: |
| 2993 |     154 |     1853.6 | 3644 |
| 2471 |     154 |     1759.1 | 3644 |
| 1869 |     154 |     1780.7 | 3644 |
**After**
`/ems_infra/report_data`
|   ms | queries | query (ms) | rows |
| ---: |    ---: |       ---: …

Use v_total_vms for HostDecorator

---

app/javascript/components/vm-snapshot-form-component.jsx
app/views/vm_common/_snap.html.haml

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1647916

Fixed required description for snapshot if vendor is openstack.

---

app/controllers/mixins/checked_id_mixin.rb

The ActionController#params method return ActionController::Parameter objects which do not respond to all hash methods.
Reimplement each_with_object using each.
rails PR: #20868
Fixes the following warning that happens a lot when testing `spec/controllers/vm_infra_controller_spec.rb`
```
DEPRECATION WARNING: Method each_with_object is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash. Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.7/classes/ActionController/Parameters.html (called from …
```

Rails 5.1:  each_with_object was deprecated / removed on params

---

spec/controllers/dashboard_controller_spec.rb

https://github.com/rails/rails/commit/98b8309569a326910a723f521911e54994b112fb
Previously, if you passed non-keyword argument String to post, it was
treated as the body of the request.  We need to make this explicit now.
Fixes the following warning on the dashboard_controller_spec on rails
5.0:
```
DEPRECATION WARNING: Using positional arguments in functional tests has been deprecated,
in favor of keyword arguments, and will be removed in Rails 5.1.
Deprecated style:
get :show, { id: 1 }, nil, { notice: "This is a flash message" }
New keyword style:
get :show, params: { id: 1 }, flash: { notice: "This is a flash message" },
session: nil # Can safely be omitted.
(called from block (3 levels) in <top (required)> at /Users/joerafaniello/Code/manageiq-ui-classic/spec/controllers/dashboard_cont …
```

Rails 5.1: Non-kwargs support in AC::TestCase#post is gone

---

app/controllers/mixins/actions/vm_actions/reconfigure.rb

We already have the object we're finding, so use it.
Fixes warning in seen in spec/controllers/vm_infra_controller_spec.rb:
```
DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base
to `find`. Please pass the id of the object by calling `.id`. (called
from reconfigure at
/Users/joerafaniello/Code/manageiq-ui-classic/app/controllers/mixins/actions/vm_actions/reconfigure.rb:21)
```

Rails 5.1: find using AR::Base instance was deprecated/removed

---

app/decorators/miq_action_decorator.rb
app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
app/helpers/application_helper/toolbar/container_project_view.rb
app/helpers/application_helper/toolbar/dashboard_summary_toggle_view.rb
app/helpers/application_helper/toolbar/ems_container_center.rb
app/helpers/application_helper/toolbar/ems_containers_center.rb
app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
app/helpers/application_helper/toolbar/physical_server_center.rb
app/helpers/application_helper/toolbar/stack_orchestration_template_center.rb
app/helpers/application_helper/toolbar/x_vm_center.rb
app/views/layouts/_header.html.haml
app/views/layouts/_user_options.html.haml

Several PF font icons  were using the "fa" class instead of "pficon" for some reason. It works fine on master but is broken when doing PF4 testing.  This PR corrects that.

fix icon font family class

---

app/assets/stylesheets/print.scss

This is a production-only issue, the SASS `@import` doesn't have the yarn packages in its load path. By calling the `require` this is solved. To reproduce it, click on the printer icon on any VM's summary screen.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1651194

Load ui-components for printing with asset pipeline require

---

app/controllers/vm_common.rb
app/helpers/application_helper/toolbar_chooser.rb

The toolbar on vm cloud and infra screens was behaving differently when doing a full page reload and a `replace_right_cell` call. Basically the full page reload did not display the printer icon. However, when doing a `replace_right_cell` the printer icon was rendered on the wrong location.
**Before:**
Full page reload:
Calling `replace_right_cell`:
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649881
@miq-bot add_reviewer @mzazrivec, @epwinchell

Make print button consistent on VM infra and cloud screens

---

app/decorators/generic_object_definition_decorator.rb

You can find this under Automate -> Generic Objects.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650146
@miq-bot add_label bug, gaprindashvili/yes, hammer/yes

Add missing quadicon definition for generic object definitions

---

app/views/configuration/_ui_1.html.haml

without `miqSelectPickerEvent`, any change in `quad_truncate` never gets propagated to the backend
=> adding `miqSelectPickerEvent`
introdued in https://github.com/ManageIQ/manageiq-ui-classic/pull/4034
Also made sure that indent of the javascript always matches the indent of the select itself,
fixed style issues (double quotes to single quotes, added semicolons),
removed useless gettext around field names (not descriptions),
and made sure `miqInitSelectPicker` ends up getting called exactly once.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650461
Cc @skateman

Configuration - notify backend when `quad_truncate` gets changed

---

app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb

Fix drop down list of floating IPs.
Using `where` to return a list versus `find_by` which return only one item 
https://bugzilla.redhat.com/show_bug.cgi?id=1595767
https://bugzilla.redhat.com/show_bug.cgi?id=1623562

VM CLoud: floating ips to associate must be a list

---

product/views/Host.yaml

This depends on changes in:  https://github.com/ManageIQ/manageiq/pull/18196
When `authentication_status` is changed to a `virtual_delegate`, we are able to pre-fetch the values as part of the original query, and avoid an N+1.
Links
-----
* https://github.com/ManageIQ/manageiq/pull/18196
Testing for this can be see in the `manageiq` PR, https://github.com/ManageIQ/manageiq/pull/18196, along with some metrics.

Adds authentication_status to Host.yaml

---

app/views/layouts/application.html.haml

in situations where IE11 fails to detect the "document mode" correctly,
this header should ensure that IE uses the "edge" mode.
(this probably doesn't help in any case where IE11 is set to force IE7 mode)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1648338
---
But see the comments in the BZ, ~~I'm almost sure this is useless, because the problem is not on our side. It won't hurt though, and will fix the problem if I'm wrong :)~~
EDIT: confirmed in the BZ that this header will indeed override group policy settings

Add X-UA-Compatible header

---

app/controllers/application_controller/ci_processing.rb
app/controllers/flavor_controller.rb
spec/controllers/application_controller/ci_processing_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650107
Go to Compute -> Cloud -> Providers -> summary page of a provider -> click Flavors -> select one or more Flavors -> Configuration -> Remove Selected Flavors
Make sure it works from Flavor list view as well: Compute -> Cloud -> Flavors -> select one or more Flavors -> Configuration -> Remove Selected Flavors
Before:
```
FATAL -- : Error caught: [NameError] undefined local variable or method `delete_flavors' for #<EmsCloudController:0x00007faacabca1c0>
Did you mean?  deletevms
/manageiq-ui-classic/app/controllers/ems_common.rb:242:in `button'
```
After:
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/4301
@miq-bot add_label bug, hammer/yes, gaprindashvili/yes

Add delete_flavors method to EmsCloudController

---

app/controllers/miq_policy_controller/alerts.rb
app/controllers/report_controller/schedules.rb
spec/controllers/miq_policy_controller/alerts_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1651241
**Description of the issue**
Emails fields are missing the pattern validation.
1. Navigate to `Cloud Intel` > `Reports`.
2. Click on Schedules Accordion, then on `Configuration` and select `Add a new Schedule`.
3. Check `Send an Email` and fill any non-email pattern in the `Add (enter manually)` field, say `XYZ` and click on plus icon.
Same thing can be reproduced with Alert Add/Edit forms.
**Before**
**After**
@miq-bot add_label hammer/yes, bug

Adds email validation for schedule and alerts forms

---

app/controllers/application_controller/buttons.rb
spec/controllers/application_controller/buttons_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650090
before:
after:

Fixed saving of custom button role visibility

---

product/views/GuestDevice.yaml
product/views/PhysicalNetworkPort.yaml
product/views/ServiceTemplate.yaml

`Picture` has no association `binary_blob` - removed from ServiceTemplates
`PhysicalNetworkPort` has no association `ext_management_system`
`GuestDevice` has no association `ext_management_system`
Updated views to remove the bad `includes()`
@miq-bot add_label rails51

Remove include pointing in invalid

---

app/helpers/application_helper/button/cockpit_console.rb

There was a little confusion around web console, after a discussion with @aufi he stated that it needs to be visible for OpenStack instances as well, so removing the piece of code that hides it.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650470
@miq-bot add_label gaprindashvili/no, hammer/yes, bug

Display the web console for OpenStack instances

---

spec/controllers/ems_cloud_controller_spec.rb

Instead of stubbing a HTTP call expect on a backend method.
The speedup is 30s.

EmsCloudController test speed.

---

app/controllers/application_controller.rb

After ~exporting to PDF~ printing a textual summary of a VM or instance, the ~export to PDF~ printing screen gets remembered as the last action for that particular menu hierarchy. This causes issues when navigating away from the summary screen and then navigating back.
The solution is simple: we should not store the ~export to PDF~ printing screen in the menu hierarchy, but the implementation is ugly and I know it. @martinpovolny I'm terribly sorry for this solution and I promise I will fix it in a followup PR.
My long term solution would be to split up the `get_global_session_data` and `set_global_session_data` methods into smaller [`before_action`](https://guides.rubyonrails.org/action_controller_overview.html#filters) methods and use `skip_before_action` in controllers that behave …

Do not store download_summary_pdf using remember tab

---

spec/controllers/miq_ae_customization_controller/dialogs_spec.rb
spec/controllers/ops_controller/ops_rbac_user_spec.rb

@lpichler : reverting your change from https://github.com/ManageIQ/manageiq-ui-classic/pull/4858
The test is passing for me even after `db:reset`. Trying travis...
Also: if seeding is really needed, can we either seed only what is needed or seed once for all tests?

Spec: Do not call MiqProductFeature.seed - speedup of 1m

---

lib/report_formatter/timeline.rb
spec/lib/report_formater/timeline_spec.rb

before:
```
Finished in 12.19 seconds (files took 7.11 seconds to load)
18 examples, 0 failures
```
after:
```
Finished in 3.49 seconds (files took 7.23 seconds to load)
18 examples, 0 failures
```
There are still some DB writes in the test, but most are avoided.

Timeline spec speedup

---

app/controllers/ems_common_helper.rb
app/controllers/ops_controller.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1548389

Don't translate audit messages

---

.travis.yml

Sometimes there's not enough time to zip & upload the cache, increasing this number should speed up the bundle installs in general.

Increase caching timeout for travis to speed up env setup

---

spec/controllers/ansible_repository_controller_spec.rb

Speed up AnsibleRepositoryController tests:
* do not recreate `:embedded_ansible_configuration_script_source` for each test.
* do not run test 2x just to test the http_code
Generally I don't see why one should re-create DB entities and re-render a page to test trivial individual properties of the page one by one.
By the way **testing just the HTTP code makes a test pointless** because w/o `bypass_rescue` you get a `200 OK` even when an exception is raised.
Before:
```
Finished in 4.3 seconds (files took 9.26 seconds to load)
18 examples, 0 failures
```
After:
```
Finished in 2.33 seconds (files took 9.2 seconds to load)
14 examples, 0 failures
```

AnsibleRepositoryController: speed up tests.

---

config/initializers/webpacker.rb
lib/tasks/manageiq/ui_tasks.rake

Depends on https://github.com/ManageIQ/manageiq/pull/18228
For ruby specs, we don't need to spend time compiling webpack assets just to ignore them.
So... we override `javascript_pack_tag` for specs, to prevent `Can't modify frozen Array` when run with a pack that was not compiled.
And change `webpack:compile` to not run `TEST_SUITE=spec`.

Don't webpack:compile for TEST_SUITE=spec

---

.travis.yml

see https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration for details,
the gist is, we should remove it because Travis says so :).
Also related: https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

Travis - remove sudo:false

---

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
app/controllers/cloud_volume_controller.rb
app/controllers/ems_common.rb
app/helpers/application_helper/button/cloud_volume_backup_create.rb
app/helpers/application_helper/button/cloud_volume_backup_restore.rb
app/helpers/application_helper/button/cloud_volume_new.rb
app/views/cloud_volume/_common_new_edit.html.haml
app/views/cloud_volume/new.html.haml
spec/controllers/cloud_volume_controller_spec.rb

Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1644310
* CloudVolume create: Need to turn off the spinner in both if/else branches.
* Fix a crash when there is a CloudManager that does not have a CloudVolume. Such as Azure.
* Fix the storage manager is not being loaded when creating a new Volume (and therefor `emstype` (and possibly other) parameters where missing) . Therefor the case when adding a new volume w/o selecting a storage manager did not work.
Part of the problems seem to be coming from 771e97f7251c33d900fa1f244aa6ae294f7995bf .
Populate volume types for EBS. Fixing:
https://bugzilla.redhat.com/show_bug.cgi?id=1644306
I have issues with understanding what are all the possible situations here and what is the expected behavior. Review and more testing is very welcome. Ping …

Cloud Volume creation fixes

---

app/controllers/ops_controller/diagnostics.rb
app/controllers/ops_controller/settings/schedules.rb
app/controllers/report_controller/reports.rb
app/controllers/report_controller/schedules.rb
app/controllers/report_controller/widgets.rb
app/presenters/tree_builder_report_schedules.rb
app/services/widget_import_service.rb
app/views/ops/_schedule_show.html.haml
spec/controllers/ops_controller_spec.rb
spec/controllers/ops_settings_spec.rb
spec/services/widget_import_service_spec.rb

The `towhat` attribute became [deprecated](https://github.com/ManageIQ/manageiq/blob/8829e85ee709b029332a05281bd257d61e9fa9cb/app/models/miq_schedule.rb#L3) for MiqSchedule model, renaming it everywhere to `resource_type`.

Rename deprecated towhat attribute to resource_type in miq schedules

---

lib/tasks/manageiq/ui_tasks.rake

Not necessary, we do not serve, compile or use assets in Ruby tests ...

Do not run yarn install for ruby tests

---

app/assets/javascripts/components/generic_object/main-custom-button-form-component.js
app/views/static/generic_object/main_custom_button_form.html.haml

`open_url` is implemented only for VMs so it's not needed here. Trying to prevent people getting confused it's not working :D And keep this form in sync with the original https://github.com/ManageIQ/manageiq-ui-classic/pull/4773
Before:
After:
@miq-bot add_label technical debt, hammer/no, automation/automate
@AparnaKarve please have a look, thanks :)

Remove open_url from GOD's custom buttons

---

Rakefile

these were necessary before #4991,
but serve no useful purpose now.
Leaving only `spec:setup` in, as that's what people should be using locally.
Removing `spec:javascript:setup`, `spec:compile:setup` and `spec:jest:setup`.

Rakefile - drop unused spec:*:setup tasks

---

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
app/views/layouts/angular/_multi_auth_credentials.html.haml

Replace `virtualization_tab` references with `kubevirt_tab` -- this was missed in 583d776
Before (shows the tiny and almost invisible tab) -
---------------
After (no tiny/invisible tabs) -
With `Virtualization` disabled -
With `Virtualization` set to `Kubevirt` -

Replace `virtualization_tab` references with `kubevirt_tab`

---

app/controllers/application_controller/filter.rb
spec/controllers/application_controller/filter_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650483
before:
after:

Reset `exp_tag` key when discard button is pressed.

---

app/controllers/storage_controller.rb

When accessing the datastores of a given provider as a user of the EvmGroup-operator group, the RBAC check fails because it is invalid. Testing against the top level feature for a non-admin will always return `nil` and also it doesn't even describe the operation properly. The correct feature to test against is `storage_show`, so I'm replacing it. cc @PanSpagetka this was implemented by you
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653709

When redirecting to a specific storage, RBAC check storage_show

---

app/controllers/report_controller.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653796
**BEFORE:**
**AFTER:**

Show widget's title as page title when editing widget

---

spec/javascripts/.eslintrc.json
spec/javascripts/controllers/report_data_controller_spec.js
spec/javascripts/controllers/toolbar_controller_spec.js

Noticed when reviewing https://github.com/ManageIQ/manageiq-ui-classic/pull/4986,
the toolbar and report specs had over a hundred eslint warning, mostly about weird indentation.
Fixing :)
cc @ZitaNemeckova 
(The change to .eslintrc adds `getJSONFixture` (provided by jasmine) and `module` (angular-mocks) to the list of allowed globals in specs.)

spec - fix eslint warnings in report & toolbar specs

---

app/controllers/vm_common.rb
app/views/miq_request/_prov_field.html.haml
spec/controllers/vm_common_spec.rb
spec/controllers/vm_infra_controller_spec.rb

Rubocop seems to prefer `request.referer` to the `request.referrer` alias,
and while "referrer" is the correct spelling in real world,
"referer" is the HTTP spelling.
Consistency.
(Addresses https://github.com/ManageIQ/manageiq-ui-classic/pull/5002#discussion_r237480626 )

Fix referrer -> referer

---

app/controllers/ops_controller/settings/common.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1654287
changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/4876 caused the issue because Gaprindashvili branch was missing following line of code `return unless @sb[:active_tab] == "settings_server" && @edit[:new][:server]`

[GAPRINDASHVILI] - Check for Appliance name only when validating settings tab.

---

app/controllers/flavor_controller.rb
app/controllers/physical_server_controller.rb
app/helpers/application_helper/button/new_flavor.rb
spec/helpers/application_helper/buttons/new_flavor_spec.rb
spec/services/dialog_local_service_spec.rb

These toplevel constants now just return with a warning but in Ruby 2.5 it will raise an exception.
https://blog.bigbinary.com/2017/10/18/ruby-2.5-has-removed-top-level-constant-lookup.html
@miq-bot add_label gaprindashvili/no, hammer/no

Remove deprecated toplevel constants from the codebase

---

app/javascript/forms/data-driven-form.jsx
app/javascript/spec/service-form/service-form.spec.js

fixes
```
✕ should enable submit button and call submit callback (30ms)
● Cloud tenant form component › should enable submit button and call submit callback
expect(jest.fn()).toHaveBeenCalledWith(expected)
Expected mock function to have been called with:
{"description": "bar", "name": "foo"} as argument 2, but it was called with {"description": "bar", "name": "bar"}.
```
Introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/4985.
Cc @Hyperkid123 , @martinpovolny

ServiceForm spec - fix by disabling disableSubmit and making sure the validator can pass

---

bin/webpack
bin/webpack-dev-server

I think there's something seriously wrong with the whole thing if we need 4GB of memory to compile our JS code to JS :laughing: :rofl: :trollface: but this is what @himdel suggested and it works.
@AlexanderZagaynov can you please verify if it fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/4857?

Increase memory limit for NodeJS to 4G

---

app/views/catalog/_svccat_tree_show.html.haml

The Service Catalog Order screen was showing "pficon-template" as the default icon rather than "fa-cube." This PR corrects that and also resizes the icon.
Old
New
https://bugzilla.redhat.com/show_bug.cgi?id=1518867

Service catalog  icon fix

---

app/decorators/manageiq/providers/storage_manager_decorator.rb
spec/decorators/manageiq/providers/storage_manager_decorator_spec.rb

There's no separate STI class for block & object storage managers, so I had to do this ugly hack while adding the missing information to the quadrants.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650086
@miq-bot add_label GTLs, hammer/yes, bug

Add top row information into the storage manager quadicons

---

app/javascript/packs/globals.js
app/views/report/_column_lists.html.haml
config/webpack/shared.js
package.json

this replaces bootstrap-select 1.12.2 with 1.12.5,
except that 1.12.5 comes from my fork, as upstream is nonresponsive
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1648115
EDIT: 1.12.6, 5 had bad paths in dist/
---
The practical difference should be https://github.com/himdel/bootstrap-select/pull/1 :
multiselect with search should not scroll up to the search bar whenever an item is chosen in the dropdown, when data-live-search-focus is set to false.
---
This also sets `data-live-search-focus` to false for available fields in the Report form, fixing the BZ :).

select: use @pf3/select instead of bootstrap-select

---

product/views/SecurityGroup.yaml

Accessible through `Networks -> Security Groups` and the view type should be `list`.
**Before:**
**Afer:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1516912
@miq-bot add_label GTLs

Include cloud tenant name column in Security Group list view

---

app/controllers/catalog_controller.rb

1. create & order a catalog item
2. delete the template used in the above catalog item
3. Services ➛ Catalogs ➛ Service Catalogs
4. In the tree view click on the created catalog item
5. In the rendered GTL click on the created catalog item
Clicking in the GTL view would render the catalogs item summary screen correctly.
Clicking in the tree view would render just list of VMs. 
https://bugzilla.redhat.com/show_bug.cgi?id=1652858

Fix CatalogItem tree_select()

---

app/controllers/report_controller/widgets.rb

Use widget's title in flash messages
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656413
**BEFORE:**
**AFTER:**
@miq-bot add-label bug, cloud intel/reporting

Use widget's title in flash messages

---

app/decorators/configuration_script_source_decorator.rb
app/decorators/manageiq/providers/ansible_tower/automation_manager/configuration_script_decorator.rb
app/decorators/manageiq/providers/ansible_tower/automation_manager/playbook_decorator.rb
app/decorators/manageiq/providers/automation_manager/inventory_group_decorator.rb
app/decorators/manageiq/providers/automation_manager/inventory_root_group_decorator.rb
app/decorators/manageiq/providers/embedded_ansible/automation_manager/playbook_decorator.rb
app/decorators/manageiq/providers/embedded_automation_manager/configuration_script_source_decorator.rb

**Before:** imagine no quadicons
**After:**
@miq-bot add_label GTLs, hammer/yes, bug
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656534

Add missing single_quad definitions for ansible-related entities

---

app/views/shared/views/_show_alerts_overview.html.haml

**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656990
@miq-bot add_label bug, gaprindashvili/yes, hammer/yes

Do not try to display icon as image on Monitoring -> Alerts cards

---

app/controllers/miq_task_controller.rb

This is a regression caused by the angular-bootstrap prefixing, the new parameter includes the `uib-` prefix, but the controller was looking for the `tab` parameter.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1655749

Use the uib-tab parameter for switching tabs on the tasks screen

---

app/assets/stylesheets/patternfly_overrides.scss

This makes sure we can have multiline tooltips that actually show the line breaks.
This should not affect any tooltips which are just one line, but makes it possible for multiline tooltips to look properly:
before:
after:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1655977

uib-tooltip - respect newlines in tooltips

---

app/helpers/vm_helper.rb

Before:
After:
@agrare Would this be correct fix for the linked bz? Thanks.
https://bugzilla.redhat.com/show_bug.cgi?id=1650501

Fix rendering of VMware floppy drive

---

.babelrc.js

Not sure how much this helps, but we definitely don't need IE10 here.

Drop support for IE10 when transpiling javascript using babel

---

app/javascript/http_api/fetch.js

After https://github.com/ManageIQ/manageiq-ui-classic/pull/5027, thete were an issue, that lodash was not available in tests.
```diff
- window._ = require('lodash');
```
I've imported lodash functions directly to the fetch file (it was using it from window).
This probably gonna get resolved in https://github.com/ManageIQ/manageiq-ui-classic/pull/4988/files, but i think its better idea not to use globals if we don't need to.

Added import of lodash for fetch.

---

app/javascript/http_api/fetch.js
app/javascript/packs/provider-dialogs-common.js
app/javascript/provider-dialogs/modal.js
app/javascript/react/textual_summary_click.js

We should not use jQuery under the `app/javscripts` folder as it should be modern javascript only and modern means without using jQuery :wink: 
@miq-bot add_label refactoring, hammer/no

Drop jQuery calls from the webpack-compiled JS codebase

---

app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
app/javascript/spec/service-form/service-form.spec.js
app/javascript/spec/set-service-ownership-form/set-service-ownership-form.spec.js
config/jest.setup.js

Fixes..
```
FAIL  app/javascript/spec/set-service-ownership-form/set-service-ownership-form.spec.js
Set service ownership form component
✕ encountered a declaration exception (3ms)
● Set service ownership form component › encountered a declaration exception
Cannot spy the miqAjaxButton property because it is not a function; undefined given instead
```
Caused by https://github.com/ManageIQ/manageiq-ui-classic/pull/5046 + https://github.com/ManageIQ/manageiq-ui-classic/pull/5027.
(The latter moved some requires, and the first PR never reran travis after the second was merged.)
CC @ZitaNemeckova @Hyperkid123

Fix travis - jest

---

app/controllers/mixins/actions/vm_actions/ownership.rb
spec/controllers/vm_infra_controller_spec.rb

Since #1578, when doing Set Ownership over multiple items:
* set user to a User, set group to dont-change
... user gets set to User, and group gets reset to nil
* set group to a Group, set user to dont-change
... group gets set to Group, and user gets reset to nil
This makes sure we don't reset groups or users unless asked to.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1657260
---
The difference is that...
`Vm.set_ownership([123], {:user => (User)}` only changes user,
but `Vm.set_ownership([123], {:user => (User), :group => nil}` updates both.

Fix multi-target Set Ownership

---

app/assets/javascripts/controllers/alerts/alerts_list_controller.js
app/assets/javascripts/controllers/alerts/alerts_most_recent_controller.js
app/assets/javascripts/controllers/alerts/alerts_overview_controller.js
app/assets/javascripts/services/alerts_center_service.js

Monitoring > Alerts > (each section):
Added a spinner that starts spinning when angular loads, and stops when the screen has loaded all the data.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1507011
---
the other 2 commits just fix eslint warnings in the code

Monitoring > Alerts - sparkle when loading

---

app/controllers/miq_policy_controller/alerts.rb
spec/controllers/miq_policy_controller/alerts_spec.rb

**Fixes BZ:**
https://bugzilla.redhat.com/show_bug.cgi?id=1654896
Related PR:
https://github.com/ManageIQ/manageiq-ui-classic/pull/4947
**What:**
This PR fixes failing creating a new _Alert_ in _Control > Explorer_ page. 
1. Go to _Control > Explorer > Alerts_ accordion _> All Alerts_
2. Select _Configuration > Add new alert_
3. Fill in some info (_Description_ and _Driving Event_ are required),
check the _Show on Timeline_ checkbox, in _Timeline Event_ section instead of _Send an E-mail_, for example
4. Click on _Add_ button
=> error:
```
[----] I, [2018-12-06T17:22:47.963847 #3514:2abc52c6f44c]  INFO -- : Started POST "/miq_policy/alert_edit?button=add" for ::1 at 2018-12-06 17:22:47 +0100
[----] I, [2018-12-06T17:22:48.011375 #3514:2abc52c6f44c]  INFO -- : …
```

Fix failing creating new Alert in Control > Explorer

---

app/javascript/packs/globals.js
app/views/report/_column_lists.html.haml
config/webpack/shared.js
package.json
yarn.lock

This is a hammer version of #5029 
---
this replaces bootstrap-select 1.12.2 with 1.12.5,
except that 1.12.5 comes from my fork, as upstream is nonresponsive
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1648115
EDIT: 1.12.6, 5 had bad paths in dist/
---
The practical difference should be https://github.com/himdel/bootstrap-select/pull/1 :
multiselect with search should not scroll up to the search bar whenever an item is chosen in the dropdown, when data-live-search-focus is set to false.
---
This also sets `data-live-search-focus` to false for available fields in the Report form, fixing the BZ :).

[HAMMER] select: use @pf3/select instead of bootstrap-select

---

app/assets/javascripts/components/generic_object/main-custom-button-form-component.js
spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650085
Go to Automation -> Automate -> Generic Object Definition -> create/edit a button -> give it same name/description that some other button already has
Before:
After: 
@miq-bot add_label wip, automation/automate, bug, hammer/yes

Catch 400 error and display it in flash message in GOD

---

app/javascript/forms/data-driven-form.jsx
package.json

Added validators translation config for data-driven-forms. Every validator has its default message. So far, we are using only `Required` validation in forms. But that will soon change.

Added i18n form data-driven-forms default validation messages.

---

spec/spec_helper.rb

It's commented out, but anyway.
The core change comes from ManageIQ/manageiq#18279.

spec_helper - fix filename after FactoryBot rename

---

config/webpack/shared.js

moment 2.23.0 came out yesterday,
moment-strftime does `require('moment')`,
but its package.json lists moment (^2.11) as a dependency, not peerDependency.
So, the new version gets added in `node_modules/moment-strftime/node_modules/moment`,
instead of just using the older `node_modules/moment`.
Aliasing moment so that doesn't happen.
---
Fixes (during `spec:javascript`):
```
ManageIQ.charts.formatters .datetime Date (M/D/YYYY)
TypeError: undefined is not a function (evaluating 'val.strftime(options.format)') in http://127.0.0.1:43021/assets/miq_formatters.self-ce4b8e42c62955443827c716d1072357a04813393bcd6af7f5a0445144012fc1.js?body=1?body=true (line 203)
datetime@http://127.0.0.1:43021/assets/miq_formatters.self-ce4b8e42c62955443827c716d1072357a04813393bcd6af7f5a0445144012fc1.js?body=1?bod …
```

Alias moment to fix moment-strftime dependency

---

.codeclimate.yml
app/javascript/.eslintrc.json
app/javascript/components/miq-about-modal.jsx
app/javascript/components/service-form/index.jsx
app/javascript/forms/form-buttons-redux.jsx
app/javascript/forms/form-buttons.jsx
app/javascript/forms/miq-button.jsx
app/javascript/react/generic_group_wrapper.jsx
app/javascript/react/textual_summary_wrapper.jsx
package.json

Eslint can lint jsx files just fine, but does not do so by default (https://github.com/eslint/eslint/pull/8515 and related).
So.. enabling jsx linting on code climate (cc @Hyperkid123) ([docs](https://docs.codeclimate.com/docs/eslint#section-extensions)),
and fixing the old `lint` task to do the same.
(The lint task currently fails because of changes to configfile locations in https://github.com/ManageIQ/manageiq-ui-classic/pull/5023.)

Enable JSX for eslint - codeclimate & yarn run lint

---

app/controllers/mixins/menu_update_mixin.rb
spec/controllers/mixins/menu_update_mixin_spec.rb

The `MenuUpdateMixin` will be included by `MigrationController` from `manageiq-v2v`. It's aim is to update `session[:tab_url]` whenever we navigate from one v2v menu section to another without doing a proper page reload.
Part of https://github.com/ManageIQ/manageiq-v2v/pull/822

Add MenuUpdateMixin

---

app/controllers/report_controller.rb
app/views/report/_export_custom_reports.html.haml

and delete commented out code. 
Saw that some ugly code was used as reference for new one so it has to go.
**MERGE AFTER** https://github.com/ManageIQ/manageiq-ui-classic/pull/5060 to prevent backport pain.
@miq-bot add_label refactoring, hammer/no

Don't assign bool value to variable that already has it

---

app/assets/javascripts/miq_ujs_bindings.js

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656003
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/4252
@miq-bot add_label gaprindashvili/yes, hammer/yes, bug

Use onchange only for radio buttons

---

app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
app/views/ops/_settings_replication_tab.html.haml

(admin) > Configuration > CFME Region > Replication
when replication type is already set to Remote,
the code mirror component renders too soon and thus renders without data
(this does not happen when the user explicitly changes to Remote)
adding an explicit [ui-refresh](https://github.com/angular-ui/ui-codemirror#ui-refresh-directive), to trigger a refresh once the data is loaded
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656066

Region Replication - refresh code mirror after load

---

config/webpack/loaders.js
config/webpack/shared.js

This removes these kinds of warnings from webpack:
```
[BABEL] Note: The code generator has deoptimised the styling of "/home/dberger/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/manageiq-ui-classic-615df016338b/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
```
(coming from babel, when trying to [compact](https://babeljs.io/docs/en/options#compact) big files, removing means a bit larger bundle, but only by whitespace (so presumably compressible))
and
￼
```
WARNING in jquery
Multiple versions of jquery found:
2.2.4 ./~/jquery from ./app/javascript/packs/globals.js
3.3.1 ./~/bootstrap-datepicker/~/jquery from ./~/bootstrap-datepicker/dist/js/bootstrap-datepicker.js
```
(coming from `DuplicatePackageCheckerPlugin` - used to get warned about duplicate deps)
Both …

add WEBPACK_VERBOSE (default off), only output some warnings when enabled

---

app/assets/javascripts/components/ops/tenant-component.js
app/controllers/ops_controller/ops_rbac.rb
config/routes.rb
spec/controllers/ops_controller/ops_rbac_spec.rb
spec/javascripts/components/ops/tenant-component_spec.js

CUD - create, update, delete
**Issue**
MiqProductFeature is using cache for some queries. MiqProductFeatures are tied to Tenants. Where we are adding/updating/delete tenant we need update this cache to reflect changes in UI. 
But it doesn't work when cache is cleaned out at model's callbacks because UI is different process.
**Reproducer**
https://user-images.githubusercontent.com/14937244/50166079-8c3c3380-02e6-11e9-8a53-a39dddcb9cab.gif
Thanks to the @gtanzillo's [idea](https://github.com/ManageIQ/manageiq-ui-classic/pull/5101#issuecomment-448279251 ) and @skateman's [research](https://github.com/ManageIQ/manageiq-ui-classic/pull/5101#issuecomment-448324700) we confirmed that if you clean the cache from the API(on instantiated classes), it doesn't reflects the changes in the UI probably …

Clean out cache of MiqProductFeature at CUD tenant actions in UI process

---

.travis.yml

missed in https://github.com/ManageIQ/manageiq-ui-classic/pull/5104,
we explicitly exclude all non-ruby jobs on the newer ruby version
(no point in running javascript specs twice)
so, updating the excluded ruby version to match the new one we're using
(Drops the number of travis jobs from 8 back to 5.)

Update travis excludes for new ruby version

---

app/controllers/mixins/actions/vm_actions/ownership.rb

Right now, clicking the Set Ownership button on a nested list of images under a cloud provider redirects to `/vm/ownership`.
But image is not a vm, it's a template, so the url should be `/miq_template/ownership`.
The difference causes 2 bugs:
* ~~no form buttons are shown~~ (only in hammer, https://github.com/ManageIQ/manageiq-ui-classic/pull/5046 replaced it on master) (=> https://github.com/ManageIQ/manageiq-ui-classic/pull/5112)
* affected items shows No records found
Fixing to use miq_template.
(related to https://bugzilla.redhat.com/show_bug.cgi?id=1650507, but the BZ only talks about the form buttons)
---
1. go to Compute -> Cloud -> Providers
1. click on a provider
1. click on Images in the provider detail/overview screen (like /ems_cloud/3?display=images)
1. select an image via …

set_ownership - use miq_template (not vm) for images

---

product/views/PhysicalChassis.yaml
product/views/PhysicalRack.yaml
product/views/PhysicalServer.yaml

I'm not totally sure how compliances work.
But these models do not have a `has_many compliances`
`has_many :compliances` comes in via `include ComplianceMixin`
And this mixin is only used in ems/vms/hosts or some containers.
But not `PhysicalChassis`, `PhysicalRack`, and `PhysicalServer`. 
I believe they are invalid `includes()` references.
The older version of rails was more lenient with `includes()` that references invalid relationships.
@bzwei or @lfu Could you verify that these references don't make sense?
Thanks
@miq-bot add_label rails51

Remove invalid compliances references

---

app/controllers/miq_ae_class_controller.rb

Stop spinner after rendering flash message when editing a namespace/domain. Similar fix was made to fix the issue when adding a namespace/domain in https://github.com/ManageIQ/manageiq-ui-classic/pull/4990
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650071
before:
after:

Stop spinner after rednering flash message
