- app/controllers/ops_controller/settings/common.rb
- app/helpers/ops_helper.rb
- app/views/ops/_settings_server_tab.html.haml
Small code cleanups done while hunting down https://github.com/ManageIQ/manageiq-ui-classic/issues/4004
ping @slemrmartin 
@mzazrivec : please, review
> OPS: server settings cleanup

- app/decorators/manageiq/providers/automation_manager/inventory_group_decorator.rb
- app/decorators/manageiq/providers/automation_manager/inventory_root_group_decorator.rb
> Remove fileicon from InventoryGroupDecorators

- lib/tasks/manageiq/ui_tasks.rake
- tools/ci/setup_js_env.sh
This is a backport of #2810, with gaprindashvili-specific changes to address https://github.com/ManageIQ/manageiq-ui-classic/pull/2810#discussion_r153015574, and #3538, with conflicts resolved.
https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: Together with https://github.com/ManageIQ/manageiq-ui-classic/pull/4059, this should bring gaprindashvili close to the current build support
---
(These were already IN gaprindashvili:
* https://github.com/ManageIQ/manageiq-ui-classic/pull/1849
* https://github.com/ManageIQ/manageiq-ui-classic/pull/1856
* https://github.com/ManageIQ/manageiq-ui-classic/pull/1860
)
> [GAPRINDASHVILI] Rake task changes for update:ui

- app/controllers/physical_infra_topology_controller.rb
fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/4066
> Fix menu selection when on physical infra topology view

- app/controllers/security_group_controller.rb
- spec/controllers/security_group_controller_spec.rb
#3889
RBAC function calls replaced.
Parent issue: #1134
> Updated PR#3889 refactoring RBAC in Security Group controller

- app/decorators/host_decorator.rb
- app/decorators/manageiq/providers/cloud_manager_decorator.rb
- app/decorators/manageiq/providers/container_manager_decorator.rb
- app/decorators/manageiq/providers/infra_manager_decorator.rb
- app/decorators/manageiq/providers/physical_infra_manager_decorator.rb
- app/decorators/storage_decorator.rb
- app/decorators/vm_decorator.rb
Some tooltips were missing from the quadicons, so I'm adding them with internationalization.
@miq-bot add_label gaprindashvili/no, GTLs
> Added missing tooltips for some quadicon quadrants

- config/routes.rb
> Remove all middleware routes as they're obsolete

- app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
- app/controllers/application_controller/ci_processing.rb
- app/controllers/mixins/actions/vm_actions/reconfigure.rb
- app/views/vm_common/_reconfigure.html.haml
- spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js
UI to allow the option to attach ISO files to existing virtual CD/DVD drives.
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1533728
> Add to the reconfigure screen the ability to attach ISOs to CDRoms  (VMware)

- app/helpers/automate_tree_helper.rb
This feature has been accidentally removed, fixing it...
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1592581
> Fix include domain prefix behavior for catalog entrypoint selection

- bower-locker.bower.json
- bower.json
https://github.com/ManageIQ/ui-components/pull/307
> [GAPRINDASHVILI] Update ui-components to 1.0.30 for gaprindashvili

- manageiq-ui-classic.gemspec
> Update patternfly-sass to 3.51.1

- package.json
corresponding PR to #4203 for patternfly-react update
cc: @himdel @karelhala @AllenBW
> update patternfly-react dependency  to 2.10.1

- bower.json
Related PRs:
https://github.com/ManageIQ/ui-components/pull/310
https://github.com/ManageIQ/ui-components/pull/309
@miq-bot add_label dependencies
> [GAPRINDASHVILI] Update ui-components to 1.0.31

- app/views/miq_request/_prov_vm_migrate_dialog.html.haml
Part of https://github.com/ManageIQ/manageiq/pull/17519.
https://bugzilla.redhat.com/show_bug.cgi?id=1090957
@miq-bot add_label gaprindashvili/no, enhancement
> Add folder dropdown to VM Migrate.

- app/helpers/vm_helper/textual_summary.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1474511
Depends on https://github.com/ManageIQ/manageiq/pull/17614
> NOR to use right values

- app/services/ems_physical_infra_dashboard_service.rb
> Adding physical switches card to physical infra dashboard

- app/helpers/application_helper/toolbar/physical_rack_center.rb
- app/helpers/application_helper/toolbar/physical_racks_center.rb
- app/helpers/application_helper/toolbar_chooser.rb
- app/views/physical_rack/show.html.haml
Compute > Physical Infrastructure > Racks
* Create a toolbar for a PhysicalRack
Depends on: ~https://github.com/ManageIQ/manageiq-ui-classic/pull/3503~ and ~https://github.com/ManageIQ/manageiq-api/pull/349~
> Rack page toolbar

- spec/helpers/persistent_volume_helper/textual_summary_spec.rb
- spec/helpers/security_group_helper/textual_summary_spec.rb
* add a test for https://github.com/ManageIQ/manageiq-ui-classic/pull/4245
* fix SecurityGroup test
> Textual summary spec

- app/controllers/report_controller/menus.rb
> Report menu style fixes.

- app/views/miq_ae_tools/_import_export.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1575407
> Makes Git URL field bigger

- manageiq-ui-classic.gemspec
Includes datetimepicker styling
@miq-bot add_label dependencies
> Update patternfly-sass to 3.52.0

- app/controllers/application_controller/buttons.rb
- app/controllers/catalog_controller.rb
(Mostly) simple style fixes.
Please note that
* `find_by_id` where existence of record is assumed later in the code are replaced with `find()` (exception would be raised)
* `finx_by_id` where the existence of the record seems not to be assumed are replaced with `find_by(:id => ...)` (no exception)
> Style fixes.

- app/views/static/ems_physical_infra/aggregate-status-card.html.haml
__Current result:__
__After this PR:__
> Adjusting the grid definitions for physical infra provider dashboard

- app/controllers/pxe_controller.rb
- spec/controllers/pxe_controller_spec.rb
@PanSpagetka please review, thanks :)
> add GenericSessionMixin to PXE Controller

- spec/controllers/report_controller_spec.rb
> add GeneralMixin test to reportcontroller

- spec/helpers/ansible_repository_helper/textual_summary_spec.rb
- spec/shared/helpers/textual_summaty_helper_methods.rb
Example of test that textual summary has all expected methods.
@skateman please review, thanks :)
@miq-bot add_label gaprindashvili/yes, test
> Add shared example that tests textual summary has given methods

- app/controllers/application_controller/policy_support.rb
- spec/controllers/application_controller/policy_support_spec.rb
Finishing changes done in PR https://github.com/ManageIQ/manageiq-ui-classic/pull/3886
> Refactoring method in policy_support.rb to use new RBAC call

- app/helpers/physical_server_helper/textual_summary.rb
- app/helpers/textual_multilabel.rb
- app/javascript/react/textual_summary_click.js
- spec/helpers/physical_server_helper/textual_summary_spec.rb
* Remove extra argument after https://github.com/ManageIQ/manageiq-ui-classic/pull/4148
* Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/4086
2 more problems in containers:
* container build and container project have a table in summary that has too many columns. Wraps in an ugly way, does not fit in column.
> Textual summary fixes

- app/assets/javascripts/components/pf_charts/group-chart.component.js
- app/assets/javascripts/components/pf_charts/pie-chart.component.js
- app/assets/javascripts/controllers/ems_common/charts-mixin.js
- app/assets/javascripts/controllers/ems_physical_infra_dashboard/server_health_pie_chart_controller.js
- app/controllers/ems_physical_infra_dashboard_controller.rb
- app/services/ems_physical_infra_dashboard_service.rb
- app/views/ems_physical_infra/_aggregate-status-card.html.haml
- app/views/ems_physical_infra/_donut-pct-chart.html.haml
- app/views/ems_physical_infra/_group-chart.html.haml
- app/views/ems_physical_infra/_show_dashboard.html.haml
- app/views/static/pf_charts/group-chart.html.haml
- config/routes.rb
- spec/javascripts/controllers/ems_physical_infra/server_health_pie_chart_spec.js
The Goal of this PR is to add pie charts for the Physical infra provider, in order to do this I had to create a pie chart component and a component to group 2 pie charts.
Depends on: ~https://github.com/ManageIQ/manageiq-ui-classic/pull/3806~
> Physical Infrastructure dashboard charts

- app/assets/javascripts/components/cloud_subnet/cloud-subnet-form.js
- app/controllers/cloud_subnet_controller.rb
- spec/javascripts/components/cloud_subnet/cloud_subnet_form_spec.js
Fixes minor issues from #2828 so it should be merged together.
https://github.com/ManageIQ/manageiq-ui-classic/pull/2828#discussion_r194667251 Missing `fetch_path`
https://github.com/ManageIQ/manageiq-ui-classic/pull/2828#issuecomment-401016770 Cutting out unwanted data
@miq-bot add_label gaprindashvili/no, networks, refactoring
> Minor fixes in Cloud Subnet

- bower-locker.bower.json
- bower.json
https://github.com/ManageIQ/ui-components/pull/316
> [GAPRINDASHVILI] ui-components 1.0.32

- app/controllers/chargeback_controller.rb
- spec/controllers/chargeback_controller_spec.rb
> add GenericSessionMixin to Chargeback Controller

- app/controllers/ems_cluster_controller.rb
- spec/controllers/ems_cluster_controller_spec.rb
> add GenericSessionMixin to ems cluster controller

- app/controllers/guest_device_controller.rb
- spec/controllers/guest_device_controller_spec.rb
> add Generic Session Mixin to guest device controller

- app/controllers/miq_policy_controller.rb
- spec/controllers/miq_policy_controller_spec.rb
> Add GenericSessionMixin to  Miq_policy controller

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596136
> Fixed rbac feature id being passed in to assert_privileges method

- app/controllers/miq_ae_class_controller.rb
> Corrected typo in miqSparkle function name

- app/controllers/ops_controller/ops_rbac.rb
The strings extractor wouldn't be able to extract the gettext strings in the previous setup.
https://bugzilla.redhat.com/show_bug.cgi?id=1530756
> New Group Screen: use variable for placeholder texts

- app/views/miq_request/_prov_iso_img_grid.html.haml
Coming from 3954540f0266c3a5a13b2e647add65c5b696d490
> Fix indentation in prov_iso_img_grid

- spec/helpers/ansible_credential_helper/textual_summary_spec.rb
- spec/helpers/ansible_playbook_helper/textual_summary_spec.rb
- spec/helpers/ansible_repository_helper/textual_summary_spec.rb
- spec/helpers/auth_key_pair_cloud_helper/textual_summary_spec.rb
- spec/helpers/availability_zone_helper/textual_summary_spec.rb
- spec/helpers/cloud_network_helper/textual_summary_spec.rb
- spec/helpers/cloud_object_store_container_helper/textual_summary_spec.rb
- spec/helpers/cloud_object_store_object_helper/textual_summary_spec.rb
- spec/helpers/cloud_subnet_helper/textual_summary_spec.rb
- spec/helpers/cloud_tenant_helper/textual_summary_spec.rb
- spec/helpers/cloud_volume_backup_helper/textual_summary_spec.rb
- spec/helpers/cloud_volume_helper/textual_summary_spec.rb
- spec/helpers/cloud_volume_snapshot_helper/textual_summary_spec.rb
- spec/helpers/configuration_job_helper/textual_summary_spec.rb
- spec/helpers/container_build_helper/textual_summary_spec.rb
- spec/helpers/container_group_helper/textual_summary_spec.rb
- spec/helpers/container_helper/textual_summary_spec.rb
- spec/helpers/container_image_helper/textual_summary_spec.rb
- spec/helpers/container_image_registry_helper/textual_summary_spec.rb
- spec/helpers/container_node_helper/textual_summary_spec.rb
- spec/helpers/container_project_helper/textual_summary_spec.rb
- spec/helpers/container_replicator_helper/textual_summary_spec.rb
- spec/helpers/container_route_helper/textual_summary_spec.rb
- spec/helpers/container_template_helper/textual_summary_spec.rb
- spec/helpers/ems_cloud_helper/textual_summary_spec.rb
- spec/helpers/ems_cluster_helper/textual_summary_spec.rb
- spec/helpers/ems_cotainer_helper/textual_summary_spec.rb
- spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb
- spec/shared/helpers/textual_summary_helper_methods.rb
- spec/shared/helpers/textual_summaty_helper_methods.rb
Added shared_examples methods for testing textual_summary/textual_groups methods + tests for some textual_summaries
> Add shared_examples tests for helpers/textual_summary

- app/assets/javascripts/controllers/mixins/charts-mixin.js
Adding back some configs that were lost during some refactor.
Some references to those missing configs
https://github.com/ManageIQ/manageiq-ui-classic/pull/3427/files#diff-88dce6f7f34946e4d4050ab3dc11ed86R75
https://github.com/ManageIQ/manageiq-ui-classic/pull/3806/files#diff-bf4502b053393556452682f417a75342R97
https://github.com/ManageIQ/manageiq-ui-classic/pull/3837/files#diff-88dce6f7f34946e4d4050ab3dc11ed86R108
> Adding some required config to charts-mixin

- manageiq-ui-classic.gemspec
- package.json
with https://github.com/patternfly/patternfly/issues/1113 fixed
Cc @skateman @simaishi
> Update patternfly to 3.54.1

- bower-locker.bower.json
- bower.json
Related PRs:
https://github.com/ManageIQ/ui-components/pull/315
https://github.com/ManageIQ/ui-components/pull/320
https://github.com/ManageIQ/ui-components/pull/322
https://github.com/ManageIQ/ui-components/pull/323
https://github.com/ManageIQ/ui-components/pull/317
https://github.com/ManageIQ/ui-components/pull/325
https://github.com/ManageIQ/ui-components/pull/326
https://github.com/ManageIQ/ui-components/pull/328
https://github.com/ManageIQ/ui-components/pull/318
https://github.com/ManageIQ/ui-components/pull/329
https://github.com/ManageIQ/ui-components/pull/319
https://github.com/ManageIQ/ui-components/pull/332
@miq-bot add_label dependencies
> [GAPRINDASHVILI] Update ui-components to v1.0.33

- app/services/ems_cloud_dashboard_service.rb
- app/services/ems_dashboard_service.rb
- app/services/ems_infra_dashboard_service.rb
Add ems type as argument for generating url, should fix bug with accessing infra provider's records.
https://bugzilla.redhat.com/show_bug.cgi?id=1609682
> Add ems type as argument for generating url

- app/services/dialog_local_service.rb
- spec/services/dialog_local_service_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1611527
@eclarizio please review.
before:
after
> Load new dialog for ServiceContainerTemplate type services

- app/assets/javascripts/components/miq_ae_class/namespace-form.js
- app/controllers/miq_ae_class_controller.rb
- app/views/miq_ae_class/_ns_list.html.haml
- app/views/static/miq_ae_class/namespace_form.html.haml
- config/routes.rb
- spec/controllers/miq_ae_class_controller_spec.rb
- spec/javascripts/components/miq_ae_class/namespace_form_spec.js
- spec/routing/miq_ae_class_routing_spec.rb
- spec/views/miq_ae_class/_ns_list.html.haml_spec.rb
Automation -> Automate -> Explorer -> select some namespace/domain -> Edit it
Automation -> Automate -> Explorer -> select some namespace/domain -> Add it
https://bugzilla.redhat.com/show_bug.cgi?id=1537493
Before/After: Has to be same in UI
@miq-bot add_label wip, angular dialogs, bug, automation/automate
> Convert namespace form

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/javascript/packs/application-common.js
- bower.json
- package.json
used in Automate > Simulation - XML View
(from https://github.com/himdel/xml_display)
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/3734
> bower to npm - xml_display

- app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
- app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
- app/views/miq_ae_customization/_dialog_sample.html.haml
The fix consists of:
* fix in dialog editor component (for cases when the dialog is being edited)
* fix in dialog use component (for cases when the dialog is being run)
* fix in dialog sample (for cases when the dialog is rendered as a preview in the right cell of explorer screen for)
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1592573
> Service Dialog: Apply gettext on initial values

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
Follow up fix for changes requested in https://github.com/ManageIQ/manageiq-ui-classic/pull/4138#pullrequestreview-142958559
@bzwei @jameswnl addressed your comments on https://github.com/ManageIQ/manageiq-ui-classic/pull/4138#pullrequestreview-142958559 please review.
https://bugzilla.redhat.com/show_bug.cgi?id=1590441
> Fixed Templates drop down in catalog item editor

- app/controllers/application_controller/miq_request_methods.rb
- app/views/miq_request/_prov_dialog_volume_fieldset.html.haml
- spec/controllers/application_controller/miq_request_methods_spec.rb
Compute->Clouds->Instances, select instance, click Lifecycle->Provision Instances, choose one, Continue
This PR add placeholder for volume size in instance provisioning.
https://bugzilla.redhat.com/show_bug.cgi?id=1417215
> Add placeholder for volume size

- app/helpers/term_of_service_helper.rb
- app/presenters/tree_builder.rb
- app/presenters/tree_node/physical_server.rb
- spec/helpers/term_of_service_helper_spec.rb
- spec/presenters/tree_node/physical_server_spec.rb
This PR updates the UI to support a new physical server alert.
The new alert is in https://github.com/ManageIQ/manageiq/pull/17728
> Add UI support for a new physical server alert

- spec/services/dialog_local_service_spec.rb
Manual backport for https://github.com/ManageIQ/manageiq-ui-classic/pull/4418.
https://bugzilla.redhat.com/show_bug.cgi?id=1611527
> [GAPRINDASHVILI] Support all service types for dialog buttons

- app/helpers/application_helper/toolbar/physical_servers_center.rb
> Fix Physical Server provision page

- app/controllers/ops_controller/settings/label_tag_mapping.rb
see also: https://github.com/ManageIQ/manageiq-providers-openstack/pull/325
> Allow Openstack Tag Mapping

- app/javascript/packs/provider-dialogs-common.js
What remained after parts where merged in other PRs.
To be used with https://github.com/ManageIQ/manageiq-providers-amazon/pull/468
The simple API call variant is very similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/3756 . Possibly reconsider?
Uses code from https://github.com/ManageIQ/manageiq-ui-classic/pull/4231
> Pluggable provider button actions

- app/controllers/application_controller/tags.rb
- app/views/layouts/_tag_edit.html.haml
Stop spinner after transaction is complete.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614437
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1601915
before after fix video attached to BZ https://bugzilla.redhat.com/show_bug.cgi?id=1601915
> Added spinner after Category is selected on tagging screen

- app/assets/javascripts/controllers/ops/diagnostics_database_form_controller.js
- app/assets/javascripts/controllers/schedule/schedule_form_controller.js
- app/assets/javascripts/services/miq_db_backup_service.js
- app/controllers/ops_controller/diagnostics.rb
- app/controllers/ops_controller/settings/schedules.rb
- app/controllers/pxe_controller/pxe_servers.rb
- app/views/ops/_diagnostics_database_tab.html.haml
- app/views/ops/_schedule_form_filter.html.haml
- spec/javascripts/controllers/schedule/schedule_form_controller_spec.js
Add support for Database Backups to be run and stored on AWS S3.
Similar to existing support for NFS and Samba.  Requires AWS credentials.
This PR is one of several required for the RFE described in BZ https://bugzilla.redhat.com/show_bug.cgi?id=1513520
@h-kataria @roliveri @carbonin please review  (but especially @h-kataria)
@NickLaMuro FYI
Requires the below  PRs to function correctly. 
Links 
* https://bugzilla.redhat.com/show_bug.cgi?id=1513520
* https://github.com/ManageIQ/manageiq-gems-pending/pull/355
* https://github.com/ManageIQ/manageiq-schema/pull/227
* https://github.com/ManageIQ/manageiq/pull/17689
* https://github.com/ManageIQ/manageiq/pull/17803
> AWS S3 Database Backups

- app/controllers/ops_controller/settings/common.rb
> OpsController: simplify logical expression

- lib/tasks/manageiq/ui_tasks.rake
This overrides `webpacker:compile` task (coming from webpacker) with our own version:
Instead of using `popen3` to capture stdout & stderr, and outputting those only sometimes,
we now run `system('bin/webpack')`, leaving the output intact.
This is to catch the instances where webpacker output during bin/update looks like this, with no clear indication of the actual error:
```
[Webpacker] Compiling assets 🎉
[Webpacker] Compilation Failed
```
> webpacker:compile - override for better error reporting

- app/controllers/mixins/actions/vm_actions/rename.rb
This small refactoring PR was made due to a number of codeclimate issues introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/4351
> Refactoring of new Rename module in Mixins

- app/controllers/cloud_network_controller.rb
- spec/controllers/cloud_network_controller_spec.rb
finishing changes from PR #3892
Closes: #3892
> Refactoring method cloud_network_controller.rb to use new RBAC call

- app/helpers/application_helper/page_layouts.rb
> Simplify layout_uses_tabs?()

- app/controllers/planning_controller.rb
> Simplify condition in PlanningController

- app/controllers/ops_controller/settings/rhn.rb
- app/views/ops/rhn/_info_subscribed.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1463169
before:
after:
> Added HTTP Proxy info on RHN screen

- app/controllers/ops_controller/settings/analysis_profiles.rb
> Simplify condition in analysis_profiles.rb: ap_edit()

- app/javascript/tests/toolbar-actions-delete.test.js
- app/javascript/toolbar-actions/delete.js
Noticed a bit late that #4438 had a couple of fixable codeclimate issues.
Fixing here, cc @karelhala
> Fix cc issues from #4438

- app/assets/stylesheets/about_modal_background.scss
- app/views/layouts/_about_modal.html.haml
> Ensure that the webkit scrollbars are applied to About modal only

- app/controllers/application_controller.rb
- app/controllers/cloud_volume_type_controller.rb
- app/controllers/ems_common.rb
- app/decorators/cloud_volume_type_decorator.rb
- app/helpers/application_helper.rb
- app/helpers/application_helper/listnav.rb
- app/helpers/application_helper/page_layouts.rb
- app/helpers/application_helper/toolbar/cloud_volume_type_center.rb
- app/helpers/application_helper/toolbar/cloud_volume_types_center.rb
- app/helpers/application_helper/toolbar_chooser.rb
- app/helpers/cloud_volume_type_helper.rb
- app/helpers/cloud_volume_type_helper/textual_summary.rb
- app/helpers/ems_storage_helper/textual_summary.rb
- app/presenters/menu/default_menu.rb
- app/views/cloud_volume_type/show.html.haml
- app/views/cloud_volume_type/show_list.html.haml
- app/views/layouts/listnav/_cloud_volume_type.html.haml
- config/routes.rb
- product/views/CloudVolumeType.yaml
- spec/controllers/cloud_volume_type_controller_spec.rb
- spec/helpers/cloud_volume_type_helper/textual_summary_spec.rb
- spec/helpers/ems_storage_helper/textual_summary_spec.rb
- spec/presenters/menu/default_menu_spec.rb
Implements views for CloudVolumeTypes in order to satisfy https://bugzilla.redhat.com/show_bug.cgi?id=1592898
> Add CloudVolumeType views

- app/views/report/_widget_show.html.haml
> RSS Widget details: render rss feed title rather thank cryptic name

- app/controllers/provider_foreman_controller.rb
Links
* #1134
* Configuration - Management
* add a Foreman provider
* Provision Configured Systems
> Replaced obsolete method for record fetching with RBAC for Foreman provider provisioning

- app/controllers/ems_common.rb
Links
* #1134
* Infra - Providers
* select a provider
* Check Compliance of Last Known Configuration
> Replaced obsolete method for record fetching with RBAC in ems_common controller

- app/controllers/alert_controller.rb
- app/views/alert/_rss_list.html.haml
* apply gettext on `<All>` dropdown text
* allow submission of explicit values only
* use bootstrap selectpicker for dropdown select + split the dropdown box out of the table
Before:
After:
> AlertController: misc fixes

- app/controllers/catalog_controller.rb
+ get rid of `level` variable
+ avoid conversion of string to symbol
> Don't use string arithmetic in gettext strings

- app/controllers/pxe_controller/pxe_image_types.rb
Links
* #1134
* Infra - PXE - System Image Types accordion
* select a System Image Type
* Remove System Image Types
> Replaced obsolete method for record fetching with RBAC in PXE controller

- app/views/report/_form_filter_chargeback.html.haml
Fine version of 
https://github.com/ManageIQ/manageiq-ui-classic/pull/4523
https://github.com/ManageIQ/manageiq-ui-classic/pull/4517
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1530221
cc @simaishi
> [FINE] Add date only options for chargeback grouping fine and 4517

- app/controllers/mixins/containers_common_mixin.rb
- spec/controllers/container_image_controller_spec.rb
Links
* #1134
* Compute - Containers - Overview - Images
* select an image
* Check Compliance of Last Known Configuration / Perform SmartState Analysis
> Replaced obsolete method for record fetching with RBAC in container_common_mixin

- app/helpers/application_helper/button/network_router_new.rb
https://github.com/ManageIQ/manageiq-providers-openstack/pull/56
https://bugzilla.redhat.com/show_bug.cgi?id=1593349
https://bugzilla.redhat.com/show_bug.cgi?id=1593353
> [FINE] NetworkRouter: Fix button support for create

- app/assets/javascripts/application.js
- app/javascript/packs/globals.js
- bower.json
- package.json
(jquery.observe_field is our npm package)
Testing:
ujs: `%a{:href => 'https://google.com', 'data-confirm' => 'Really?'}Foo`
observe_field: `$.fn.observe_field` is present
Issue: #3734
> bower to npm - jquery-ujs & jquery.observe_field

- bower.json
- package.json
- spec/javascripts/support/jasmine.yml
only used in tests, adding as devDependency
Issue: #3734
> bower to npm - jasmine-jquery

- app/assets/javascripts/application.js
- app/javascript/packs/globals.js
- bower.json
- package.json
we're not using any css, just the js, likely only drag&drop
Issue: #3734
> bower to npm: jquery ui

- app/services/physical_infra_topology_service.rb
Original algorithm relied on hash keys being returned in the same
order they were written in the source code (which is fine, since ruby
gives us that guarantee) and graph-building algorithm internals to
always produce same edge order (which is a bit less reasonable
assumption).
Updated algorithm distances itself from those two assumptions and
introduces the concept of kind priorities that allows us to
reconstruct the original tree structure of resources.
Immediate benefit of this change is that relationship description can
now be vastly simplified (all duplicated data can be removed from
@included_relations), since the final resource linking is now
decoupled from the linking specification that graph building algorithm
uses.
> Fix physical infra topology tree building algorithm

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/javascript/packs/globals.js
- bower.json
- package.json
same version, just npm :)
Testing:
```
$.fn.treeview
```
Issue #3734
> bower to npm - patternfly-bootstrap-treeview

- app/controllers/host_controller.rb
- app/helpers/host_helper/textual_summary.rb
- app/views/host/show.html.haml
- spec/helpers/host_helper/textual_summary_spec.rb
According to https://bugzilla.redhat.com/show_bug.cgi?id=1394799#c13 added fields of networks and subnets to infra nodes view.
> Add links to networks and subnets for infra nodes

- app/assets/javascripts/components/pf_charts/aggregate-status-card.component.js
- app/assets/javascripts/components/pf_charts/group-chart.component.js
- app/assets/javascripts/controllers/ems_common/aggregate_status_card_controller.js
- app/assets/javascripts/controllers/ems_physical_infra_dashboard/recent_servers_line_chart_controller.js
- app/assets/javascripts/controllers/ems_physical_infra_dashboard/server_health_pie_chart_controller.js
- app/controllers/ems_physical_infra_dashboard_controller.rb
- app/controllers/physical_infra_overview_controller.rb
- app/helpers/application_helper/page_layouts.rb
- app/presenters/menu/default_menu.rb
- app/services/dashboard_service.rb
- app/services/ems_physical_infra_dashboard_service.rb
- app/views/ems_physical_infra/_aggregate-status-card.html.haml
- app/views/ems_physical_infra/_recent-servers-line-chart.html.haml
- app/views/physical_infra_overview/show.html.haml
- app/views/static/ems_common/aggregate-status-card.html.haml
- app/views/static/ems_physical_infra/aggregate-status-card.html.haml
- app/views/static/ems_physical_infra/group-chart.html.haml
- app/views/static/ems_physical_infra/recent-servers-line-chart.html.haml
- config/routes.rb
- spec/javascripts/controllers/ems_physical_infra/server_health_pie_chart_spec.js
- spec/services/ems_physical_infra_dashboard_service_spec.rb
Depends on: ~https://github.com/ManageIQ/manageiq/pull/17770~
> Creating an overview page for physical infra providers

- bower.json
Update ui-components to 1.0.35 for gaprindashvili
Changes since last:
https://github.com/ManageIQ/ui-components/pull/230
https://github.com/ManageIQ/ui-components/pull/338
> [GAPRINDASHVILI] Update ui-components to 1.0.35 for gaprindashvili

- app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
- app/controllers/application_controller/buttons.rb
- app/services/dialog_local_service.rb
- app/views/shared/dialogs/_dialog_provision.html.haml
- app/views/shared/dialogs/_dialog_user.html.haml
- config/routes.rb
- spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
- spec/services/dialog_local_service_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618800
This is mix of PRs related to fixing Open URL #4036 , #4334 and #4521 for Gaprindashvili branch.
see #4334 
@miq-bot add_label bug, blocker, automation/automate
@romanblanco please try it out, thanks :)
> [GAPRINDASHVILI] Fix open url

- app/controllers/application_controller/compare.rb
Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/116
Move `Missing` and `Found` from conditions so they can be translated.
How to test:
- Compute -> Infrastructure -> Virtual Machines
- select two or more
- Configuration -> Compare selected items
- see it works correctly for compressed and decompressed versions (option in toolbar)
Before/After: Have to be same.
@miq-bot add_label wip, gaprindashvili/no, internationalization
> Use bool instead of a string that needs to be translated

- app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
- spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js
After submitting a dialog in custom button.
Before:
After:
@romanblanco @epwinchell 
@miq-bot add_label gaprindashvili/no, angular dialogs
> Change flash after submit to have green color

- app/views/vm_common/_reconfigure.html.haml
Before:
After:
Infra -> Virtual Machines -> Reconfigure a VM
> Removed extra horizontal line

- app/views/miq_request/show_list.html.haml
- app/views/static/miq-request-options.html.haml
Moved the partial rendering from angular components template
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1632782
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1632782
Steps for Testing/QA (from the BZ ticket)
1. Have a infra provider (tested with RHV) and a VM on that provider.
2. Go to VM's detail view, click Configuration -> Reconfigure this VM.
3. Change something, e.g. VM's memory. Click Submit button.
> Corrected flash message rendering after submitting VM reconfigure request

- app/controllers/report_controller/widgets.rb
response to @martinpovolny's comment https://github.com/ManageIQ/manageiq-ui-classic/pull/4579#discussion_r214727220
* Remove a Dashboard Widget
> Cleaned up logic of deleting a Widget 

- app/controllers/application_controller.rb
- app/controllers/cloud_tenant_controller.rb
- app/controllers/mixins/checked_id_mixin.rb
- app/controllers/ops_controller/ops_rbac.rb
- app/controllers/report_controller/schedules.rb
- spec/controllers/vm_infra_controller_spec.rb
Closes: #1134 
Closes: #3921
Links
* #1134
* migrate a VM
> Replaced obsolete 'find_checked_records_with_rbac' method 

- spec/helpers/application_helper/toolbar_builder_spec.rb
Use working translation string
> Fix delayed translation test

- bower.json
Changes since 1.0.35:
* https://github.com/ManageIQ/ui-components/pull/347
> [GAPRINDASHVILI] Update ui-components to 1.0.36 for gaprindashvili

- app/controllers/application_controller/buttons.rb
- app/controllers/miq_ae_customization_controller/custom_buttons.rb
> Remove code that is commented out

- package.json
Pretty much just these updates from [spice-html5 upstream](https://github.com/freedesktop/spice-html5):
* freedesktop/spice-html5@969fe1f
* freedesktop/spice-html5@f9f700e
Cc @skateman (consoles :))
> Upgrade spice-html5-bower to 1.7.3

- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ops_controller/settings/common_spec.rb
Also fixed the check that compares previously saved value against the value from miq_server record instead of checking `@update.config[:server][:name]` server/name key did not exist in settings.yml so the condition always returned true.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1634518
(cherry picked from commit 96809410e76cb4fe4b37efaf8edba412a20593bf)
Gaprindashvili PR for https://github.com/ManageIQ/manageiq-ui-classic/pull/4730
> [GAPRINDASHVILI] - Made changes to save server name only if it is not blank

- CHANGELOG.md
> [Changelog] Update for Sprint 98, H-B2, and G6

- app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
Links
https://github.com/ManageIQ/manageiq-ui-classic/pull/4860#discussion_r231024974
> Added missing gettext into Dialog Editor controller

- spec/helpers/application_helper/buttons/vm_instance_template_scan_spec.rb
- spec/helpers/application_helper/buttons/zone_delete_spec.rb
- spec/helpers/application_helper/toolbar_builder_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/support/examples_group/shared_examples_for_smart_state_scan_buttons.rb
https://github.com/ManageIQ/manageiq/pull/18187
> Fix seeding of MiqServer in specs by using EvmSpecHelper

- manageiq-ui-classic.gemspec
Contains https://github.com/patternfly/patternfly/pull/1151
Related PR https://github.com/ManageIQ/manageiq-ui-classic/pull/4841
@miq-bot add_label hammer/no
> Update PatternFly to v3.57

- app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
Fixes - https://bugzilla.redhat.com/show_bug.cgi?id=1647489
> [GAPRINDASHVILI] Use a valid tab name for the Metrics tab in the Container form

- app/assets/javascripts/controllers/host/host_form_controller.js
- spec/javascripts/controllers/host/host_form_controller_spec.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649918
before
after
> Fixed if condition to prevent undefined js error

- app/assets/javascripts/components/auth-credentials.js
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1647013
> Fixed disabled password input.

- bower-locker.bower.json
- bower.json
https://github.com/ManageIQ/ui-components/pull/341
> [GAPRINDASHVILI] Update ui-components to 1.0.37 for gaprindashvili

- spec/controllers/ems_infra_controller_spec.rb
Expect on a backend method.
The speedup is 30s.
> EmsInfraController test speed.

- spec/requests/restful_redirect_spec.rb
Speed up by not seeding all dialogs.
> Restful redirect: test speedup by not seeding all dialogs.

- app/presenters/tree_builder_ops_rbac_features.rb
- spec/controllers/ops_controller_spec.rb
Speedup OpsController spec by removing MiqProductFeature.seed.
Saving ~ 6.5s
> Speedup OpsController spec by removing MiqProductFeature.seed.

- spec/controllers/vm_cloud_controller_spec.rb
Before:
```
Finished in 31.25 seconds (files took 9.39 seconds to load)                         
133 examples, 0 failures  
```
After:
```
Finished in 20.98 seconds (files took 9.53 seconds to load)                              
133 examples, 0 failures  
```
> VmCloudController spec speedup.

- app/controllers/ops_controller/settings/common.rb
Issue introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/4876
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1646571
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639364
> [GAPRINDASHVILI] - Fixed an issue introduced in cherry-pick conflict

- app/assets/javascripts/components/generic_object/generic-object-definition-toolbar.js
Fixed the Delete message to display  "Generic Object Class"
Before -
After -
https://bugzilla.redhat.com/show_bug.cgi?id=1644658
> Fix Delete message to display the entity type - "Generic Object Class"

- app/controllers/miq_ae_class_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650071
> Stop spinner after rendering flash message

- app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
- spec/javascripts/controllers/ops/pglogical_replication_form_controller_spec.js
1. Configuration ➛ Region ➛ Replication
2. Switch Type to `Remote`
3. Hit `Save` button
4. Navigate away from the form (e.g. click on `My Settings`)
Without this fix, the `Abandon changes?` pop-up dialog would show.
https://bugzilla.redhat.com/show_bug.cgi?id=1650447
> Fix save in region replication form

- spec/javascripts/components/verify-button_spec.js
- spec/javascripts/controllers/containers/container_project_dashboard_controller_spec.js
- spec/javascripts/controllers/ems_infra/aggregate_status_card_controller_spec.js
- spec/javascripts/controllers/toolbar_controller_spec.js
- spec/javascripts/fixtures/json/toolbar_middleware_server_list.json
`container_project_dashboard_controller_spec` - remove empty  `it`
`aggregate_status_card_controller_spec` - `setTimeout` + looking at correct attribute
`toolbar_controller_spec` - add item to toolbar_middleware_server_list.json that has id that starts with view_ so there's something in `$controller.dataViews`
TODO: verify-button_spec
Before:
`localhost:8888`
See yellow dots (nevermind the red one it's a local problem with time)
Switch to Spec List
After: 
No yellow dots (nevermind the red one it's a local problem with time)
No ` SPEC HAS NO EXPECTATIONS` in Spec List
@miq-bot add_label wip, hammer/no, test
> Fix js tests that have SPEC HAS NO EXPECTATIONS

- app/assets/javascripts/controllers/report_data_controller.js
Don't use map when not returning anything, fix indentation.
Fixes a bunch of style issues from https://github.com/ManageIQ/manageiq-ui-classic/pull/4509.
Cc @PanSpagetka
> ReportDataController - fix a few style issues

- app/helpers/application_helper.rb
- app/javascript/components/cloud-tenant-form/cloud-tenant-form.jsx
- app/javascript/packs/component-definitions-common.js
- app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
- app/views/cloud_tenant/edit.html.haml
- app/views/cloud_tenant/new.html.haml
Mostly a typo from #4895 .
Cc @Hyperkid123
> CloudTennant -> CloudTenant

- app/javascript/forms/data-driven-form.jsx
- package.json
Added list of form states, when should be submit button disabled for react data driven forms.
Based on https://github.com/ManageIQ/manageiq-ui-classic/pull/5018 form submit issue.
> Data driven form submit button disable config.

- app/views/layouts/_vertical_navbar.html.haml
This change is to be able to select the menu items in client code (javascript, Angular, React, ...).
@himdel
> Add IDs to vertical menu leaf items

- package.json
- yarn.lock
https://github.com/ManageIQ/ui-components/pull/358
> [HAMMER] Update ui-components to 1.1.19 for hammer

- app/controllers/report_controller/widgets.rb
- spec/controllers/report_controller/widget_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1660163
before:
after:
> Fixed saving of role/group visibility for a widget

- app/views/layouts/_exp_editor.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1653800
> Add missing gettext into exp_editor.html.haml

- app/views/miq_task/_tasks_options.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1653787
> Add missing gettext to zone dropdown in My Tasks screen

- app/helpers/ems_cluster_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1653772
> Cluster textual summary: add translatable label

- app/helpers/host_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1653779
> Add translatable labels to Host textual summary

- manageiq-ui-classic.gemspec
- package.json
> Update patternfly to 3.59.1

- app/assets/stylesheets/miq_tree.scss
- app/assets/stylesheets/patternfly_overrides.scss
This PR removes some old IE-specific CSS properties that are no longer relevant (pre-IE11)
> remove outdated IE properties

- app/views/miq_policy/_export.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1655562
> Make policy export strings fully translatable

- app/helpers/auth_key_pair_cloud_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1653821
> Add translatable label to auth key pair textual summary

- app/helpers/orchestration_stack_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1653815
> Add translatable labels to orchestration stack textual summary

- app/helpers/host_helper/textual_summary.rb
Fixed issue introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/5116
@GregP please verify the fix
> Fixed labels that should not be links

- app/helpers/cloud_volume_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1655554
> Cloud Volume textual summary: add translatable labels

- manageiq-ui-classic.gemspec
- tools/ci/after_install.sh
the package is deprecated,
and codeclimate no longer has a free tier
> Remove codeclimate-test-reported

- app/controllers/mixins/ems_common/core.rb
ref: https://github.com/ManageIQ/manageiq-ui-classic/pull/5173
ping @skateman
> Split method process_emss.

- package.json
Updates ui-components, changes:
ManageIQ/ui-components#361
ManageIQ/ui-components#368
ManageIQ/ui-components#367
ManageIQ/ui-components#366
ManageIQ/ui-components#369
ManageIQ/ui-components#365
BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1553846
https://bugzilla.redhat.com/show_bug.cgi?id=1669533
> Update ui-components to 1.2.2

- package.json
- yarn.lock
PRs:
https://github.com/ManageIQ/ui-components/pull/362
https://github.com/ManageIQ/ui-components/pull/365
BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1686038
> [HAMMER] Update ui-components to 1.1.20 for hammer

- .travis.yml
- product/views/VmdbDatabaseConnection.yaml
These columns changed in Postgres 10.
> Update the database connection report to use new columns

- app/controllers/application_controller.rb
- app/controllers/application_controller/feature.rb
- app/controllers/miq_ae_class_controller.rb
- app/controllers/miq_ae_customization_controller.rb
- app/controllers/mixins/sandbox.rb
- app/controllers/mixins/vm_show_mixin.rb
- app/controllers/ops_controller.rb
- app/controllers/report_controller.rb
- spec/controllers/application_controller/feature_spec.rb
I'm dropping redundant and unnecessary members of this structure so it's easier to work with it in the future. Please read this commit by commit, there's explanation where it is necessary.
@miq-bot add_label trees, hammer/no, explorers, refactoring
> Clean up the ApplicationController::Features structure a little

- package.json
Upgrade version of react-ui-components to latest
@Hyperkid123 @himdel
> Upgrade version of react-ui-components

- app/controllers/automation_manager_controller.rb
- app/controllers/bottlenecks_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/chargeback_controller.rb
- app/controllers/infra_networking_controller.rb
- app/controllers/miq_ae_class_controller.rb
- app/controllers/miq_ae_customization_controller.rb
- app/controllers/ops_controller.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/pxe_controller.rb
- app/controllers/report_controller.rb
- app/controllers/service_controller.rb
- app/controllers/storage_controller.rb
- app/controllers/utilization_controller.rb
- app/controllers/vm_cloud_controller.rb
- app/controllers/vm_infra_controller.rb
- app/controllers/vm_or_template_controller.rb
Code styling unification so we can work better with the features hashes in the future.
@miq-bot add_label refactoring, hammer/no
> Unify the code style of features hashes in controllers

- app/controllers/mixins/checked_id_mixin.rb
> Delete unused method find_or_new

- app/helpers/host_helper/textual_summary.rb
- app/helpers/vm_helper/textual_summary.rb
> Add missing fonticons in the host and vm summary screens

- app/helpers/container_node_helper/textual_summary.rb
- app/helpers/container_replicator_helper/textual_summary.rb
- app/helpers/ems_container_helper/textual_summary.rb
> Add missing fonticons in the containers area summary screens

- product/views/EmsCluster.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1692853
> Add Provider to Clusters tile, list views

- app/controllers/application_controller/tags.rb
- app/helpers/application_helper.rb
More ✂️ ✂️ ✂️ of dead code.
@romanblanco please have a look.
> Remove more dead code

- package.json
- yarn.lock
https://github.com/ManageIQ/ui-components/pull/381
https://github.com/ManageIQ/ui-components/pull/375 (tests only)
https://bugzilla.redhat.com/show_bug.cgi?id=1698586
> [HAMMER] Update ui-components to 1.1.21 for hammer

- package.json
https://github.com/ManageIQ/ui-components/pull/381
https://github.com/ManageIQ/ui-components/pull/382
https://bugzilla.redhat.com/show_bug.cgi?id=1698586
> Update ui-components to 1.2.4

- app/controllers/host_controller.rb
- app/controllers/mixins/manager_controller_mixin.rb
- app/helpers/application_helper.rb
- app/helpers/application_helper/page_layouts.rb
- spec/helpers/application_helper_spec.rb
✂️ ✂️ ✂️ 
@romanblanco please have a 👀 , thanks :)
> Remove dead methods 

- package.json
- yarn.lock
https://github.com/ManageIQ/ui-components/pull/382
https://bugzilla.redhat.com/show_bug.cgi?id=1698586
> [HAMMER] Update ui-components to 1.1.22 for hammer

- package.json
- yarn.lock
ManageIQ/ui-components#377
ManageIQ/ui-components#378
ManageIQ/ui-components#368
https://bugzilla.redhat.com/show_bug.cgi?id=1702063
https://bugzilla.redhat.com/show_bug.cgi?id=1702064
> [HAMMER] Update ui-components to 1.1.23 for hammer

- app/controllers/miq_ae_class_controller.rb
- app/helpers/application_helper.rb
- app/helpers/miq_ae_tools_helper.rb
- app/services/prometheus_proxy_service.rb
- spec/helpers/miq_ae_tools_spec.rb
✂️ ✂️ ✂️ 
A little clean up of methods noone needs :)
@romanblanco please have a look. Hope commit messages are to your liking :)
> Delete dead methods

- package.json
- yarn.lock
https://github.com/ManageIQ/ui-components/pull/380
https://bugzilla.redhat.com/show_bug.cgi?id=1692980
> [HAMMER] Update ui-components to 1.1.24 for hammer

- app/controllers/miq_policy_controller/alerts.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1705139
@mzazrivec please review.
> Fixed a typo introduced in e788bd7fac48704d6637c0e5aa7ef71f68ba663a

- package.json
- yarn.lock
https://github.com/ManageIQ/ui-components/pull/372
https://bugzilla.redhat.com/show_bug.cgi?id=1705141
> [HAMMER] Update ui-components to 1.1.25 for hammer

- app/javascript/components/taggingWrapper.jsx
- app/javascript/react/textual_summary_click.js
It's nice if we mark old-world stuff in the new codebase :wink: 
@miq-bot add_label developer, hammer/no
> Add FIXME comments in the modern JS that uses jQuery

- app/assets/javascripts/miq_explorer.js
- app/controllers/miq_policy_controller/rsop.rb
- app/controllers/vm_common.rb
- app/presenters/explorer_presenter.rb
- app/views/miq_policy/_rsop_results.html.haml
- app/views/vm_common/_policies.html.haml
- spec/controllers/vm_common_spec.rb
Tree now collapses when clicking the button and the button's title has been updated as well.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1690572
> Fix squash button functionality on Policy Sim tree

- app/presenters/tree_node/datacenter.rb
- app/presenters/tree_node/ems_folder.rb
- app/presenters/tree_node/node.rb
- spec/presenters/tree_node/datacenter_spec.rb
- spec/presenters/tree_node/ems_folder_spec.rb
- spec/presenters/tree_node_spec.rb
The logic here is too complex, we can split it up between two classes. 
>  Extract TreeNode::Datacenter from TreeNode::EmsFolder

- lib/manageiq/ui/classic/engine.rb
Change plugin common methods to class methods
> Change plugin common methods to class methods

- app/controllers/catalog_controller.rb
- app/controllers/mixins/actions/vm_actions/ownership.rb
- app/helpers/application_helper/toolbar/servicetemplate_center.rb
- app/helpers/application_helper/toolbar/servicetemplates_center.rb
- config/routes.rb
- spec/controllers/catalog_controller_spec.rb
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1641905
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1641905
1. Services -> Catalog
2. Catalog Items accordion -> Add a New Catalog Item
3. Select the created Catalog Item -> Set Ownership
> Added option to change group ownership for Service Catalog Items

- package.json
ManageIQ/ui-components#386
ManageIQ/ui-components#384
ManageIQ/ui-components#385
https://bugzilla.redhat.com/show_bug.cgi?id=1706693
> Update ui-components to 1.2.5

- app/helpers/application_helper/button/embedded_ansible.rb
- spec/controllers/container_controller_spec.rb
- spec/controllers/container_image_controller_spec.rb
- spec/controllers/container_project_controller_spec.rb
- spec/controllers/container_replicator_controller_spec.rb
- spec/controllers/miq_report_controller/dashboards_spec.rb
- spec/helpers/application_helper/buttons/embedded_ansible_spec.rb
- spec/presenters/tree_node/miq_product_feature_spec.rb
- spec/services/widget_import_service_spec.rb
Found these while testing another PR
> Misc. cleanup

- app/controllers/application_controller/miq_request_methods.rb
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1356086
After https://github.com/ManageIQ/manageiq-ui-classic/pull/5488, provisioning from Template does not work (Infra - Template - Provision - Catalog tab) 
The condition is swapped.
> Corrected condition after fix for BZ1356086

- app/javascript/forms/data-driven-form.jsx
Adds new class to `form` tags for data driven forms. This class will be used to limit the form width and possibly some other styling for the wrapper.
> Added .form-react class to data driven forms form tag.

- app/presenters/tree_node/ems_folder.rb
- spec/presenters/tree_node/ems_folder_spec.rb
Sorry, two PRs got merged that together killed travis :disappointed: 
https://github.com/ManageIQ/manageiq-ui-classic/pull/5623
https://github.com/ManageIQ/manageiq-ui-classic/pull/5639
@miq-bot add_label trees, hammer/no, tests
> Adjust TreeNode::EmsFolder to the deleted TreeBuilderVat

- app/javascript/components/vm-server-relationship-form/index.jsx
- app/javascript/spec/vm-server-relationship-form/vm-server-relationship-form.spec.js
Comes from #5233, cc @rvsia :)
> Fix hardcoded localhost:3000 in api call

- app/javascript/components/automate-import-export-form/import-datastore-via-git.jsx
> Fixed header alignment in import datastore via git forms.

- package.json
ManageIQ/ui-components#389
ManageIQ/ui-components#390
ManageIQ/ui-components#388
ManageIQ/ui-components#387
https://bugzilla.redhat.com/show_bug.cgi?id=1707961
https://bugzilla.redhat.com/show_bug.cgi?id=1705013
> Update ui-components to 1.2.6

- app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1707961
The dialog's content is saved into `sessionStorage` while the editor is getting initialized.
Every change should update the content of the saved dialog.
In the `sessionStorage` the dialog is stored under key `service_dialog-new` or `service_dialog-{id}`.
The dialog is removed from the `sessionStorage` if the dialog is submitted, of user confirms he want's to abandon the changes.
In case the user gets unintentionally redirected, an option to restore the changes will be offered.
This PR contains initialization and cleaning of `sessionStorage`.
Links
* https://github.com/ManageIQ/ui-components/pull/387/
* https://bugzilla.redhat.com/show_bug.cgi?id=1707961
1. …
> Use sessionStorage to avoid loss of unsaved dialog

- app/assets/javascripts/application.js
- app/javascript/packs/globals.js
**Depends on https://github.com/ManageIQ/ui-components/pull/386** => https://github.com/ManageIQ/manageiq-ui-classic/pull/5604
**Depends on https://github.com/ManageIQ/ui-components/pull/389** => https://github.com/ManageIQ/manageiq-ui-classic/pull/5666
@miq-bot add_label pending core, technical debt, test, hammer/no, changelog/no
> Move ui-components from asset pipeline to webpack

- app/assets/stylesheets/application.css
- app/stylesheet/application-webpack.scss
Move ui-components CSS to webpack
@miq-bot add_label hammer/no, dependencies, technical debt, changelog/no
@himdel ping
> Move ui-components CSS to webpack

- app/views/layouts/_policy_sim.html.haml
needed for automated testing
https://bugzilla.redhat.com/show_bug.cgi?id=1717539
> Update markup for title on policy simulation page

- package.json
- yarn.lock
ManageIQ/ui-components#388
ManageIQ/ui-components#361
https://bugzilla.redhat.com/show_bug.cgi?id=1717704
> [HAMMER] Update ui-components to 1.1.27 for hammer

- app/controllers/vm_common.rb
- app/helpers/textual_mixins/textual_region.rb
- app/helpers/vm_helper/textual_summary.rb
Before:
After:
Depends on https://github.com/ManageIQ/react-ui-components/pull/121
https://bugzilla.redhat.com/show_bug.cgi?id=1678142
Older design (keeping just for posterity):
> Add button for opening virtual machine in its region

- package.json
This is to bring in changes from https://github.com/ManageIQ/react-ui-components/pull/121
https://bugzilla.redhat.com/show_bug.cgi?id=1678142
> Update react-ui-components to 0.11.23

- package.json
- yarn.lock
ManageIQ/ui-components#393
https://bugzilla.redhat.com/show_bug.cgi?id=1721122
> [HAMMER] Update ui-components to 1.1.28 for hammer

- app/controllers/ops_controller/ops_rbac.rb
- spec/controllers/ops_controller/ops_rbac_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1720273
> Fix: allow deletion of custom super_admin users

- package.json
Update version of react-ui-components.
@martinpovolny
> Update version of react-ui-components

- app/controllers/catalog_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1722497
was introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/5626
> Rebuild list of zones when deleting a resource from Catalog bundle

- app/assets/javascripts/controllers/tree_view_controller.js
You should not code Ruby in Javascript :man_facepalming: sorry :man_facepalming: 
@miq-bot add_label bug, trees, hammer/no
> Fix temporary tree data deletion in angular explorer trees

- package.json
This is to include https://github.com/ManageIQ/react-ui-components/pull/125
> Update react-ui-components to 0.11.25

- spec/controllers/automation_manager_controller_spec.rb
There's a few places where we're setting these attributes and don't need to.
> This is done by the factory, we don't need it

- spec/controllers/ops_controller/settings/common_spec.rb
The factory handles the name and I need a PR for the day.
> Let factories handle names and zone creation

- spec/controllers/application_controller/buttons_spec.rb
We don't need to do this and I need github points for today.
> The factory sets these attributes

- app/javascript/packs/component-definitions-common.js
Only small changes to fix linting issues in `component-definitions-common.js` file.
> Fixed linting errors in component definitions.

- spec/controllers/application_controller/ci_processing_spec.rb
We don't need to set the description or name in specs here.
> The factory sets the name and description

- app/controllers/miq_ae_customization_controller.rb
- spec/controllers/miq_ae_customization_controller_spec.rb
- spec/helpers/ems_cloud_helper/textual_summary_spec.rb
- spec/views/shared/views/ems_common/_show.html.haml_spec.rb
Ems leafs in tests got merged recently in main. 
https://github.com/ManageIQ/manageiq/pull/18922 broke three UI specs.
Also the error handling changes to https://github.com/ManageIQ/manageiq/pull/18890 mean this repo needs updating.
> Fix failing specs from recent main repo changes

- app/views/shared/views/_prov_dialog.html.haml
@miq-bot add_labels bug, requests
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1720640
> Fix error viewing Customize tab on Requests

- spec/controllers/application_controller/compare_spec.rb
We don't need to set the vm name with FactoryBot.
> The factory handles this

- spec/controllers/auth_key_pair_cloud_controller_spec.rb
The factory sets these, we don't need to here. 
@bdunne moooooar easy github points?
> These are all unnecessary

- spec/controllers/application_controller/explorer_spec.rb
- spec/controllers/application_controller/tags_spec.rb
We don't need to do any of this since the factory itself sets these, again
> Removing more of the extra attributes set by factories

- package.json
- yarn.lock
ManageIQ/ui-components#392
ManageIQ/ui-components#394
ManageIQ/ui-components#397
ManageIQ/ui-components#399
https://bugzilla.redhat.com/show_bug.cgi?id=1702497
https://bugzilla.redhat.com/show_bug.cgi?id=1726388
https://bugzilla.redhat.com/show_bug.cgi?id=1726438
https://bugzilla.redhat.com/show_bug.cgi?id=1727989
https://bugzilla.redhat.com/show_bug.cgi?id=1727990
> [HAMMER] Update ui-components to 1.1.29 for hammer

- package.json
ManageIQ/ui-components#391
ManageIQ/ui-components#392
ManageIQ/ui-components#393
ManageIQ/ui-components#394
ManageIQ/ui-components#395
ManageIQ/ui-components#397
ManageIQ/ui-components#399
> Update ui-components to 1.2.7

- app/javascript/components/taggingWrapper.jsx
- package.json
Add missing gettexts to Tagging.
https://bugzilla.redhat.com/show_bug.cgi?id=1725081
> Add missing gettexts to Tagging

- spec/controllers/automation_manager_controller_spec.rb
Removing more of the things we don't need in specs.
> Names and zones are set by the factory

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- lib/gtl_formatter.rb
- product/views/ServiceTemplate.yaml
- spec/controllers/catalog_controller_spec.rb
I am adding mechanism how to hide columns in GTL lists based on true/false methods in controllers.
https://bugzilla.redhat.com/show_bug.cgi?id=1678122
https://github.com/ManageIQ/manageiq-ui-classic/pull/5575
> Hide columns in GTL lists for non-admin users(not only)

- package.json
> Update ui-components to 1.2.8

- app/controllers/tree_controller.rb
If the domain prefix is included in the automate entrypoint for a dynamic dialog element, it is possible to [select](https://github.com/ManageIQ/ui-components/pull/400) it as there's only one available. However, for that first we have to expand the node properly.
Unfortunately, there's no method in automate that tells us if the domain prefix is included or not, so I am determining it using a trick. If the `automate_find_hierarchy` method returns a `nil`, we fall back to the old way of expanding all the homonymic methods.
@miq-bot add_label hammer/no, bug, trees
cc @pkomanek 
https://bugzilla.redhat.com/show_bug.cgi?id=1553846ü
> Expand the node in DialogEditor/TreeSelector with prefix included

- app/views/catalog/_form_basic_info.html.haml
- app/views/catalog/_sandt_tree_show.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1728309
before
after
> Removed Zone selection from bundle add/edit/details screen

- product/views/MiqRequest.yaml
Move the "Reason" 3 left in the "My Requests" view.
> Request columns order

- package.json
- yarn.lock
ManageIQ/ui-components#402
https://bugzilla.redhat.com/show_bug.cgi?id=1729594
> [HAMMER] Update ui-components to 1.1.30 for hammer

- package.json
ManageIQ/ui-components#402
https://bugzilla.redhat.com/show_bug.cgi?id=1729594
> Update ui-components to 1.2.9

- app/views/ops/_settings_server_tab.html.haml
This PR depends on: https://github.com/ManageIQ/manageiq/pull/18956
@miq-bot add_labels bug, settings, internationalization
https://bugzilla.redhat.com/show_bug.cgi?id=1724575
> Mark items for translation on Settings Server tab

- spec/controllers/application_controller/build_audit_spec.rb
So we don't need to do this here. 
> The factory sets name and description.

- package.json
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1730021
There was a bug in data driven forms in minified version of consumer apps so it slipped through the library testing. Select was not properly setting form context value.
This was fixed in new version of library.
> Fixed select component in forms

- app/javascript/components/simple-table/simple-table.jsx
- app/javascript/spec/simple-table/__snapshots__/simple-table.spec.js.snap
- app/javascript/spec/simple-table/simple-table.spec.js
Added styled react table component and added component which renders table from data.
> Added styled table react components and data driven variant.

- manageiq-ui-classic.gemspec
Update Font Fabulous to 1.0.5 that includes https://github.com/ManageIQ/font-fabulous/pull/56
@skateman
> Update Font Fabulous to 1.0.5

- spec/controllers/automation_manager_controller_spec.rb
We don't need to set them here.
> The factory sets all these again

- package.json
https://github.com/ManageIQ/ui-components/pull/401
https://bugzilla.redhat.com/show_bug.cgi?id=1728600
> Update ui-components to 1.2.10

- app/javascript/components/miq-about-modal.jsx
https://bugzilla.redhat.com/show_bug.cgi?id=1546108
Requires https://github.com/ManageIQ/manageiq-api/pull/628
> Add release info to About screen title

- app/controllers/application_controller/buttons.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1659452
> Fix custom button group `Display on Button` option

- spec/helpers/application_helper_spec.rb
Broken in https://github.com/ManageIQ/manageiq/pull/19053
> Permission store: fix specs.

- spec/controllers/cloud_object_store_object_spec.rb
Once again more things we don't need to do in tests.
> These are set by the factory, again

- spec/controllers/cloud_subnet_controller_spec.rb
We don't need names or descriptions in these again. 
@miq-bot add_label hammer/no, refactoring, test, changelog/no, ivanchuk/no
> These are all set by the factory again

- package.json
- yarn.lock
ManageIQ/ui-components#401
https://bugzilla.redhat.com/show_bug.cgi?id=1731991
> [HAMMER] Update ui-components to 1.1.31 for hammer

- .travis.yml
Only ruby >= 2.5.3, < 2.6.0 is supported on ivanchuk
https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/563996946
> [IVANCHUK] Update travis.yml for ivanchuk

- app/controllers/application_controller/compare.rb
- spec/controllers/application_controller/compare_spec.rb
- Fixed variable name introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/4688
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1734150
> Added missing argument in function definition

- app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1726752
before
after
> Filter out Maintenance zone from the drop down

- app/assets/javascripts/components/ops/log-collection-form.js
- app/assets/javascripts/services/miq_db_backup_service.js
- app/controllers/ops_controller/diagnostics.rb
- app/views/static/ops/log_collection/log_collection.html.haml
@miq-bot add_labels bug, settings
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1706903
> Add '<No Depot>' option to Collect Logs form

- app/controllers/vm_common.rb
We're no longer displaying VMs in the related trees and `open_parent_nodes` doesn't make much sense. Even if it would, the branch where it's being called is kinda dead as neither the `vandt_tree` and the `instances_tree` are allowed to jump in. Also it excepts any `filter_tree` and as far as I know we don't have any other tree in the controllers where the `VmCommon` mixin is included.
However, if this is a bug and we should open the nodes for the closest folder without highlighting anything :sweat: well, I'd like to ask the reviewer to create a BZ where it's specified how this thing should behave and get a PM approval. Anyway, this code is a copy-pasted :spaghetti:, the condition that runs it is even more :spaghetti: :spaghetti:  and I'd like to get rid of it if possible. I'm planning on …
> Drop the VmCommon#open_parent_nodes as we no longer display VMs

- CHANGELOG.md
> [Changelog] Update Ivanchuk Beta2

- package.json
- yarn.lock
PRs from 0.11.27:
https://github.com/ManageIQ/react-ui-components/pull/129
https://github.com/ManageIQ/react-ui-components/pull/134
https://github.com/ManageIQ/react-ui-components/pull/135
https://github.com/ManageIQ/react-ui-components/pull/133
https://github.com/ManageIQ/react-ui-components/pull/119
https://github.com/ManageIQ/react-ui-components/pull/131
https://github.com/ManageIQ/react-ui-components/pull/136
https://github.com/ManageIQ/react-ui-components/pull/137
https://github.com/ManageIQ/react-ui-components/pull/139
https://github.com/ManageIQ/react-ui-components/pull/140
master PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/5979
> [IVANCHUK] Bump version of react-ui-components to 0.11.37

- package.json
PRs: https://github.com/ManageIQ/react-ui-components/pull/139 and https://github.com/ManageIQ/react-ui-components/pull/140
@himdel
> Update react-ui-compoennts to 0.11.37

- app/controllers/catalog_controller.rb
- app/controllers/chargeback_controller.rb
- app/controllers/miq_ae_class_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/miq_policy_controller/alert_profiles.rb
:scissors: :scissors: dead methods 
@miq-bot add_label ivanchuk/no, changelog/no, technical debt, wip
> Remove dead methods

- app/presenters/full_tree_builder.rb
- app/presenters/tree_builder.rb
Not necessary, so :scissors: :scissors: :deciduous_tree: 
@miq-bot add_label hammer/no, ivanchuk/no, trees, cleanup
> Drop the options argument from TreeBuilder#x_build_single_node

- yarn.lock
Update yarn.lock after backports.
Just #5975 this time.
> [IVANCHUK] Update yarn.lock after backports

- app/javascript/components/report-data-table.jsx
After filtering go to page 1.
Related BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1739737
Force default cursor over table cells:
https://bugzilla.redhat.com/show_bug.cgi?id=1739266
> Report results: Multiple fixes.

- package.json
- yarn.lock
https://github.com/ManageIQ/ui-components/pull/405
https://github.com/ManageIQ/ui-components/pull/407
https://bugzilla.redhat.com/show_bug.cgi?id=1729265
https://bugzilla.redhat.com/show_bug.cgi?id=1728964
> [IVANCHUK] Update ui-components to 1.2.13 for ivanchuk

- spec/services/dialog_local_service_spec.rb
> [HAMMER] Fixes network manager dialog local spec failure on h

- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/report_controller.rb
- app/helpers/application_helper.rb
- app/presenters/explorer_presenter.rb
- app/views/layouts/_content.html.haml
- app/views/layouts/_policy_sim.html.haml
- app/views/layouts/_tabs.html.haml
Please, read explanations in the commit messages.
Please, review with care.
Ping @mzazrivec, @himdel 
Ping @terezanovotna
> Allow setting of fancy page titles (right_cell_text). Use it in Reports.

- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Updates Breadcrumb spec to match master, otherwise it will cause a lot of issues with the newest PRs.
@miq-bot add_label ivanchuk/yes
> [IVANCHUK] Update breadcrumbs spec to match master

- app/views/layouts/print/report.html.haml
@skateman review please? Thank you.
https://bugzilla.redhat.com/show_bug.cgi?id=1740810
> Add translated report headers to PDF reports

- app/helpers/application_helper/toolbar/automation_manager_provider_center.rb
- app/helpers/application_helper/toolbar/automation_manager_providers_center.rb
- app/helpers/application_helper/toolbar/configuration_manager_provider_center.rb
- app/helpers/application_helper/toolbar/configuration_manager_providers_center.rb
- app/helpers/application_helper/toolbar/ems_cloud_center.rb
- app/helpers/application_helper/toolbar/ems_clouds_center.rb
- app/helpers/application_helper/toolbar/ems_container_center.rb
- app/helpers/application_helper/toolbar/ems_containers_center.rb
- app/helpers/application_helper/toolbar/ems_infra_center.rb
- app/helpers/application_helper/toolbar/ems_infras_center.rb
- app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
- app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
Removed these buttons until issue is resolved to provide user more feedback on paused Providers to prevent further actions on such providers.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1743276
> Removed Pause & Resume Provider buttons from UI.

- app/views/automation_manager/explorer.html.haml
- app/views/ems_cloud/show_list.html.haml
- app/views/ems_container/show_list.html.haml
- app/views/ems_infra/show_list.html.haml
- app/views/ems_network/show_list.html.haml
- app/views/ems_physical_infra/show_list.html.haml
- app/views/provider_foreman/explorer.html.haml
- config/settings.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1741030
> Create docs section in settings for documentation links

- app/controllers/vm_common.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1655516
> VmCommon: no string math in right_cell_text

- product/views/Service.yaml
Back to enabling turbo mode for services
https://bugzilla.redhat.com/show_bug.cgi?id=1741327
@miq-bot add_label ivanchuck/yes bug services
> Turbo mode for services

- app/views/layouts/_ae_resolve_options.html.haml
This PR reworks the form in the left column to be properly responsive.
Follow-up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6027
Old
New
> Automate Sim responsiveness fix

- package.json
- yarn.lock
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1729940
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1732501
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1727920
This fixes wrong position of dropdown select in production env.
Also fixes overriding asynchronous select options.
Master PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/6118
> [IVANCHUK] Update version of data driven forms to v1.15.6

- CHANGELOG.md
> [Changelog] Update for Hammer-11

- locale/zanata.xml
> Remove zanata.xml

- app/controllers/application_controller/performance.rb
- lib/report_formatter/c3.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1725095
> Add translated vmdb database chart labels

- app/controllers/application_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1747545
@skateman pls review
> Exclude compare and drift download actions when remembering last tab

- package.json
- yarn.lock
ManageIQ/ui-components#410
https://bugzilla.redhat.com/show_bug.cgi?id=1748455
> [IVANCHUK] Update ui-components to 1.2.14 for ivanchuk

- package.json
- yarn.lock
ManageIQ/ui-components#410
https://bugzilla.redhat.com/show_bug.cgi?id=1748455
> [HAMMER] Update ui-components to 1.1.33 for hammer

- package.json
ManageIQ/ui-components#410
ManageIQ/ui-components#413
https://bugzilla.redhat.com/show_bug.cgi?id=1748455
> Update ui-components to 1.3.1

- package.json
- yarn.lock
ManageIQ/ui-components#412
ManageIQ/ui-components#414
https://bugzilla.redhat.com/show_bug.cgi?id=1749061
> [HAMMER] Update ui-components to 1.1.34 for hammer

- app/views/layouts/_adv_search_footer.html.haml
- app/views/layouts/_exp_editor.html.haml
Expanded on #6051 for several other buttons in the Advanced Search modal. 
@miq-bot add_labels bug, configuration management
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740239
> Fix spinner behavior with various buttons on the Adv Search modal

- app/controllers/cloud_network_controller.rb
Removed commented code from cloud network controller
> Removed commented code

- app/javascript/packs/component-definitions-common.js
- app/stylesheet/application-webpack.scss
- package.json
Fixes failing travis js tasks.
> Updated to latest version of react-u-components.

- app/views/ops/_settings_rhn_tab.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1750350
> Added missing gettext for "Red Hat Software Updates"

- spec/presenters/tree_node/iso_image_spec.rb
Caused by https://github.com/ManageIQ/manageiq-decorators/pull/19
> Adjust specs for the IsoImage fonticon change in the decorator

- app/controllers/application_controller/advanced_search.rb
- app/controllers/application_controller/filter.rb
- app/controllers/application_controller/filter/expression.rb
- app/controllers/catalog_controller.rb
- app/controllers/configuration_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/ops_controller/diagnostics.rb
- app/controllers/ops_controller/ops_rbac.rb
- app/controllers/ops_controller/settings/rhn.rb
- app/services/git_repository_service.rb
- app/services/widget_import_service.rb
- spec/controllers/application_controller/buttons_spec.rb
- spec/controllers/catalog_controller_spec.rb
- spec/controllers/dashboard_controller_spec.rb
- spec/controllers/miq_report_controller/trees_spec.rb
- spec/controllers/miq_request_controller_spec.rb
- spec/controllers/ops_controller/diagnostics_spec.rb
- spec/controllers/service_controller_spec.rb
- spec/services/cloud_topology_service_spec.rb
- spec/services/container_topology_service_spec.rb
- spec/services/network_topology_service_spec.rb
update_attributes was in Rails 2.3.8 and is just update now, see
https://apidock.com/rails/ActiveRecord/Base/update_attributes
> update_attributes has been deprecated

- app/controllers/picture_controller.rb
Use standard rails methods to serve up photos
- Don't fetch the photo from the db if it is the wrong extension
- fresh_when could calculate the etags for us, but used our md5 instead
I was running into caching issues locally, but turned out to be my own bug.
So if you'd prefer not to make any changes, I'm good with that, too.
I just thought this read better
@miq-bot add_label refactor, technical_debt
> Use standard rails methods to serve up photos

- app/controllers/generic_object_controller.rb
- app/helpers/generic_object_helper/textual_summary.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1507802
before
after
> Show Smart Management box on details view

- app/helpers/availability_zone_helper/textual_summary.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746367
@miq-bot add_label bug, internationalization
> add i18n at Totals for Availability Zone

- app/javascript/angular/dashboard/widget-footer.js
Changing "Updated" to "Updated On" for dashboard charts
1. go to Dashboard
> Changed wording for consistency

- app/presenters/tree_builder_utilization.rb
To be honest, I don't remember when I did this, but I found it among my branches and it seems working. I have no idea why I haven't opened a PR yet, so now fixing this. It's the same old story, dropping redundant hash nodes.
**Before:**
**After:**
@miq-bot add_label trees, refactoring, technical debt, ivanchuk/no
> Get rid of Clusters hash node folders from Utilization tree

- app/assets/stylesheets/application.css
- app/assets/stylesheets/schedule_editor.scss
> remove outdated schedule editor styling

- app/controllers/ops_controller/ops_rbac.rb
- spec/controllers/ops_controller/ops_rbac_spec.rb
Links 
------
* related to https://github.com/ManageIQ/manageiq-ui-classic/pull/6244
> RBAC filter for access tenant detail page

- CHANGELOG.md
> [Changelog] Add missing PRs from Sprint 121

- app/controllers/miq_ae_customization_controller/old_dialogs.rb
- app/presenters/tree_builder_provisioning_dialogs.rb
- app/views/miq_ae_customization/_old_dialogs_form.html.haml
Front-end change for https://github.com/ManageIQ/manageiq/pull/19347
> Correctly apply gettext to MiqDialog::DIALOG_TYPES

- app/controllers/report_controller/reports/editor.rb
- app/views/report/_form_sort.html.haml
UI change for https://github.com/ManageIQ/manageiq/pull/19372
> Apply gettext to MiqReport::Generator model constant

- app/controllers/vm_common.rb
Split the method to make the logic & flow more readable.
> VmCommon: split get_node_info.

- app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
- app/helpers/application_helper/toolbar/diagnostics_server_center.rb
- app/helpers/application_helper/toolbar/ems_cloud_center.rb
- app/helpers/application_helper/toolbar/ems_clouds_center.rb
- app/helpers/application_helper/toolbar/ems_container_center.rb
- app/helpers/application_helper/toolbar/ems_containers_center.rb
- app/helpers/application_helper/toolbar/ems_infra_center.rb
- app/helpers/application_helper/toolbar/ems_infras_center.rb
- app/helpers/application_helper/toolbar/ems_physical_infra_center.rb
- app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
- app/helpers/application_helper/toolbar/firmware_registries_center.rb
- app/helpers/application_helper/toolbar/firmware_registry_center.rb
- app/helpers/application_helper/toolbar/physical_servers_center.rb
- app/helpers/application_helper/toolbar/physical_switch_center.rb
- app/helpers/application_helper/toolbar/physical_switches_center.rb
- app/helpers/application_helper/toolbar/tasks_center.rb
- app/helpers/application_helper/toolbar/template_clouds_center.rb
This is a follow-up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6290 more to follow in other repos.
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/5937
> Toolbar Simplification follow-up

- app/javascript/components/topology_toolbar.jsx
- app/javascript/spec/toolbar/__snapshots__/topology_toolbar.spec.jsx.snap
Remove text from the Refresh button
follow-up to: #6290 
Issue: #5937
> Toolbar update - topology

- app/javascript/components/miq-toolbar.jsx
Fix of my last week's fix: https://github.com/ManageIQ/manageiq-ui-classic/pull/6306
The error analysis was correct, but the implementation was wrong. I messed up toolbar from state and toolbar from props. Now fixing that. Sorry :-(
> Fix toolbar initialization.

- package.json
v1.3.2
ManageIQ/ui-components#373
ManageIQ/ui-components#412
ManageIQ/ui-components#414
ManageIQ/ui-components#415
ManageIQ/ui-components#417
ManageIQ/ui-components#418
ManageIQ/ui-components#421
ManageIQ/ui-components#423
https://bugzilla.redhat.com/show_bug.cgi?id=1686077
https://bugzilla.redhat.com/show_bug.cgi?id=1729379
> Update ui-components to 1.3.2

- app/views/static/ops/log_collection/log_collection.html.haml
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1720142
> Dropbox removed, in exchange for using support tool

- app/views/static/ops/log_collection/log_collection.html.haml
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1720142
https://bugzilla.redhat.com/show_bug.cgi?id=1660143
> Re adding RH dropbox support, and making it readonly along with support

- app/views/ops/_log_collection.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1765635
☹️
> [HAMMER] Fix typo in #6341

- app/controllers/utilization_controller.rb
Obvious piece of deduplication.
Preparatory work for https://bugzilla.redhat.com/show_bug.cgi?id=1750305
> Report download: deduplication.

- app/controllers/dashboard_controller.rb
Probably my not-finished refactoring O:)
This handles if Dashboard widget is minimized in Overview -> Dashboard
@miq-bot add_label technical debt, ivanchuk/no
> Use widget_minimized? method to de-duplicate code

- app/views/static/ops/log_collection/log_collection.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1765635
> Fix typo in #6341

- app/controllers/application_controller/filter/expression.rb
- app/controllers/report_controller/reports/editor.rb
- app/helpers/exp_atom_helper.rb
- app/views/layouts/exp_atom/_edit_field.html.haml
- app/views/layouts/exp_atom/_edit_tag.html.haml
- app/views/layouts/exp_atom/_editor.html.haml
- app/views/report/_form_filter.html.haml
- spec/controllers/miq_report_controller/reports/editor_spec.rb
- spec/helpers/atom_helper_spec.rb
this part is effort for new expression editor and API for it.
it is possible that this method will be moved somewhere to core repo.
> Extract expression types

- package.json
v1.3.3
* ManageIQ/ui-components#422
* ManageIQ/ui-components#424
https://bugzilla.redhat.com/show_bug.cgi?id=1744413
> Update ui-components to 1.3.3

- package.json
- yarn.lock
v1.2.15
* ManageIQ/ui-components#412
* ManageIQ/ui-components#414
* ManageIQ/ui-components#422
* https://bugzilla.redhat.com/show_bug.cgi?id=1767836
* https://bugzilla.redhat.com/show_bug.cgi?id=1768456
> [IVANCHUK] Update ui-components to 1.2.15 for ivanchuk

- .travis.yml
Test with ruby 2.5.5, see: https://github.com/ManageIQ/manageiq/pull/19468
> [IVANCHUK] Test with ruby 2.5.5, see: https://github.com/ManageIQ/manageiq/pull/194

- spec/controllers/ping_controller_spec.rb
Follow up to https://github.com/ManageIQ/manageiq-ui-classic/pull/6399
now that https://github.com/ManageIQ/manageiq-api/issues/708 is
resolved.
> Uncomment PingController spec

- package.json
- yarn.lock
https://github.com/ManageIQ/ui-components/pull/422
https://bugzilla.redhat.com/show_bug.cgi?id=1768457
> [HAMMER] Update ui-components to 1.1.35 for hammer

- app/assets/stylesheets/patternfly_overrides.scss
- app/views/catalog/_svccat_tree_show.html.haml
- app/views/ops/_selected_by_servers.html.haml
Follow-up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6404
> Remove control-labelimage class

- CHANGELOG.md
Using "*" for bullets
Update CHANGELOG.md
[skip ci]
Thank you for a new Pull Request!
Please, make reviewers work easier by checking, if you are not introducing any technical debt:
https://github.com/ManageIQ/guides/blob/master/reviewers_guidelines.md#manageiqmanageiq-ui-classic
Describe the rationale and use case for this pull request.  Provide any background, examples, and images that provide further information to accurately describe what it is that you are adding to the repo.  Add subsections as necessary to organize and feel free to link and reference other PRs as necessary, but also include them in the links section below as a quick reference.
Guidelines:
* Keep Pull Request titles short and to the point, ideally under 72 characters
* Provide as much context/info in the description …
> Sprints 122,123, and 124

- package.json
- yarn.lock
v1.1.36
ManageIQ/ui-components#428
https://bugzilla.redhat.com/show_bug.cgi?id=1773626
> [HAMMER] Update ui-components to 1.1.36 for hammer

- app/assets/stylesheets/patternfly_overrides.scss
The PR removes duplicates of #notification, #search_notification, #blocker_div and #spinner_div
> Remove duplicate styling

- app/controllers/application_controller.rb
- spec/controllers/miq_ae_class_controller_spec.rb
- spec/controllers/miq_ae_customization_controller/old_dialogs_spec.rb
- spec/controllers/ops_controller/settings/analysis_profiles_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1765107
> Prefer item name over item description

- app/assets/stylesheets/patternfly_overrides.scss
- app/views/report/_form_styling.html.haml
> Remove old "widthed" form class

- app/views/catalog/_form_basic_info.html.haml
- app/views/chargeback/_cb_rate_edit.html.haml
> Rename ChargebackRateDetailCurrency to Currency in haml

- spec/controllers/ops_controller/settings/common_spec.rb
Depends:
Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/33
> Update specs for storage belonging to an EMS

- CHANGELOG.md
PRs with labels of bug or enhancement
[skip ci]
Thank you for a new Pull Request!
Please, make reviewers work easier by checking, if you are not introducing any technical debt:
https://github.com/ManageIQ/guides/blob/master/reviewers_guidelines.md#manageiqmanageiq-ui-classic
Describe the rationale and use case for this pull request.  Provide any background, examples, and images that provide further information to accurately describe what it is that you are adding to the repo.  Add subsections as necessary to organize and feel free to link and reference other PRs as necessary, but also include them in the links section below as a quick reference.
Guidelines:
* Keep Pull Request titles short and to the point, ideally under 72 characters
* Provide as much context/info in the description as …
> Updates for Ivanchuk-2

- CHANGELOG.md
> Changelog for sprint 125 and 126

- app/assets/stylesheets/application.css
- app/assets/stylesheets/masthead.scss
- app/assets/stylesheets/notifications.scss
- app/assets/stylesheets/patternfly_overrides.scss
The PR consolidates the  masthead styling in its own file.
> Split out masthead styling

- app/assets/stylesheets/masthead.scss
Follow-up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6560
> masthead styling cleanup

- package.json
- yarn.lock
v1.1.37
ManageIQ/ui-components#430
https://bugzilla.redhat.com/show_bug.cgi?id=1783377
> [HAMMER] Update ui-components to 1.1.37 for hammer

- spec/controllers/cloud_subnet_controller_spec.rb
Regarding the [comment](https://github.com/ManageIQ/manageiq-ui-classic/pull/6488#discussion_r359035085) about usefulness of some of the tests for _Cloud Subnets_, I am adding new examples and deleting useless one.
> Improve specs regarding creating new Cloud Subnet

- app/assets/stylesheets/application.css
- app/assets/stylesheets/login.scss
- app/assets/stylesheets/patternfly_overrides.scss
The PR consolidates the login screen styling in its own file.
> Split out login styling

- app/controllers/miq_request_controller.rb
- app/controllers/mixins/actions/vm_actions/reconfigure.rb
- app/helpers/application_helper/button/vm_reconfigure.rb
- app/helpers/application_helper/button/vm_reconfigure_multiple.rb
- app/helpers/application_helper/toolbar/template_clouds_center.rb
- app/helpers/application_helper/toolbar/vm_infras_center.rb
- app/helpers/application_helper/toolbar/x_template_cloud_center.rb
- app/views/vm_common/_reconfigure.html.haml
- spec/helpers/application_helper/buttons/vm_reconfigure_spec.rb
- spec/shared/helpers/application_helper_buttons.rb
backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/6469
To go with https://github.com/ManageIQ/manageiq/pull/19566
Needs testing (working on it)
fyi: @simaishi
> [IVANCHUK] Reconfigure: use detailed RBAC features

- app/controllers/mixins/actions/vm_actions/reconfigure.rb
> VM reconfigure: fix code indentation.

- package.json
- yarn.lock
v1.2.16
ManageIQ/ui-components#428
ManageIQ/ui-components#430
https://bugzilla.redhat.com/show_bug.cgi?id=1773627
https://bugzilla.redhat.com/show_bug.cgi?id=1783375
> [IVANCHUK] Update ui-components to 1.2.16 for ivanchuk

- app/controllers/mixins/actions/vm_actions/retire.rb
1. Services > Workloads
2. VMs & Instances
3. Select a VM or an Instance
4. Hit `Lifecycle` > `Set Retirement Date`
Before, the following traceback would show:
```
[----] I, [2020-01-06T13:26:49.959412 #21839:13948b4]  INFO -- : Started GET "/vm_or_template/retirement_info/101000000004915" for 127.0.0.1 at 2020-01-06 13:26:49 +0100
[----] I, [2020-01-06T13:26:49.962052 #21839:13948b4]  INFO -- : Processing by VmOrTemplateController#retirement_info as HTML
[----] I, [2020-01-06T13:26:49.962103 #21839:13948b4]  INFO -- :   Parameters: {"id"=>"101000000004915"}
[----] F, [2020-01-06T13:26:49.974786 #21839:13948b4] FATAL -- : Error caught: [NoMethodError] undefined method `find_by' for nil:NilClass
/opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-2d87743f9ffa/app/controllers/mixins/actions/vm_ …
```
> Fix Vm & Instance retirement from workflow screen

- app/controllers/mixins/actions/vm_actions/retire.rb
As discussed in https://github.com/ManageIQ/manageiq-ui-classic/pull/6585#issuecomment-572612895
@himdel
> Use find_record_with_rbac() instead of find_by()

- CHANGELOG.md
Thank you for a new Pull Request!
Please, make reviewers work easier by checking, if you are not introducing any technical debt:
https://github.com/ManageIQ/guides/blob/master/reviewers_guidelines.md#manageiqmanageiq-ui-classic
Describe the rationale and use case for this pull request.  Provide any background, examples, and images that provide further information to accurately describe what it is that you are adding to the repo.  Add subsections as necessary to organize and feel free to link and reference other PRs as necessary, but also include them in the links section below as a quick reference.
Guidelines:
* Keep Pull Request titles short and to the point, ideally under 72 characters
* Provide as much context/info in the description as necessary to get the reviewer up to the same …
> Changelog for sprint 127

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/patternfly_overrides.scss
This PR removes unused variables from main.scss
> Remove outdated variables

- app/controllers/miq_request_controller.rb
- app/controllers/mixins/actions/vm_actions/reconfigure.rb
- app/helpers/application_helper/button/vm_reconfigure.rb
- app/helpers/application_helper/button/vm_reconfigure_multiple.rb
- app/helpers/application_helper/toolbar/template_clouds_center.rb
- app/helpers/application_helper/toolbar/vm_infras_center.rb
- app/helpers/application_helper/toolbar/x_template_cloud_center.rb
- app/views/vm_common/_reconfigure.html.haml
- spec/helpers/application_helper/buttons/vm_reconfigure_spec.rb
- spec/shared/helpers/application_helper_buttons.rb
backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/6469
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1788564
fyi: @simaishi
> [HAMMER] Reconfigure: use detailed RBAC features

- app/assets/javascripts/components/recent-resource.js
https://bugzilla.redhat.com/show_bug.cgi?id=1802131
before
after
> Fixed code to show title on empty line chart.

- app/assets/javascripts/controllers/tree_view_controller.js
- app/controllers/automation_manager_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/service_controller.rb
- app/controllers/storage_controller.rb
- app/controllers/vm_cloud_controller.rb
- app/controllers/vm_infra_controller.rb
- app/controllers/vm_or_template_controller.rb
- app/javascript/components/breadcrumbs/on-click-functions.js
- app/javascript/spec/breadcrumbs/on-click-functions.spec.js
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
- spec/controllers/vm_infra_controller_spec.rb
Port of https://github.com/ManageIQ/manageiq-ui-classic/pull/6073
Fixes 
https://bugzilla.redhat.com/show_bug.cgi?id=1740839
https://bugzilla.redhat.com/show_bug.cgi?id=1741250
https://bugzilla.redhat.com/show_bug.cgi?id=1741222
https://bugzilla.redhat.com/show_bug.cgi?id=1740719
https://bugzilla.redhat.com/show_bug.cgi?id=1741241
https://bugzilla.redhat.com/show_bug.cgi?id=1778848
@miq-bot add_label breadcrumbs
> [IVANCHUK] Remove tree breadcrumbs

- app/presenters/tree_builder_services.rb
Fixes #6180
This is the only reference i found for `display` attribute related to a Service in UI and API repo.
> Replaced attribute 'display' to 'visible'

- Rakefile
Fixes:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
> Fix Travis Jest failure

- spec/controllers/automation_manager_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/helpers/application_helper_spec.rb
- Ensure that the default zone exists
- Pass in the zone when not using factories
For: https://github.com/ManageIQ/manageiq/pull/18218
Cross-repo tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/71
> An ExtManagementSystem requires a zone

- CHANGELOG.md
> [IVANCHUK] Update CHANGELOG.md for Ivanchuk-3

- cypress/integration/ui/gtl.spec.js
- cypress/integration/ui/searchbox.spec.js
- cypress/support/commands.js
Add:
- GTL helper for no data, error and rendered GTL
- Searchbox is visible/hidden
> GTL SearchBox Helpers for Cypress tests

- cypress/integration/ui/login.spec.js
Let's not skip semicolons in js 😄 
@miq-bot add_label test, technical debt
> Clean up login test a bit

- cypress/README.md
- cypress/integration/ui/gtl.spec.js
- cypress/integration/ui/settings.spec.js
- cypress/support/commands.js
@miq-bot add_label wip, test, cypress
> Make GTL helpers more generic and update README

- app/assets/stylesheets/data_driven_forms_overrides.scss
- app/javascript/components/catalog-form/catalog-form.schema.js
- app/javascript/components/cloud-network-form/cloud-network-form.schema.js
- app/javascript/components/copy-dashboard-form/copy-dashboard-form.schema.js
- app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
- app/javascript/forms/mappers/formFieldsMapper.jsx
- app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js
- app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
- app/javascript/spec/catalog-form/catalog-form.spec.js
- app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
- app/javascript/spec/copy-catalog-form/copy-catalog-form.spec.js
- app/javascript/spec/copy-dashboard-form/copy-dashboard-form.spec.js
- app/javascript/spec/flavor-form/flavor-form.spec.js
- app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
- app/javascript/spec/forms/input-with-dynamic-prefix.spec.js
- app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js
- app/javascript/spec/orchestration-template/orchestration-template-form.spec.js
- app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
- app/javascript/spec/pxe-servers-form/pxe-server-form.spec.js
- app/javascript/spec/service-dialog-from-form/service-dialog-from-form.spec.js
- app/javascript/spec/service-form/service-form.spec.js
- app/javascript/spec/set-ownership-form/set-ownership-form.spec.js
- app/javascript/spec/workers-form/workers-form.spec.js
- package.json
This latest version fixes an issue with initial value loading priorities, but there are some changes in the CSS prefixing, so I had to adjust the override to keep https://bugzilla.redhat.com/show_bug.cgi?id=1757328 fixed.
Related issue: https://github.com/ManageIQ/manageiq/issues/18818
> Update DDF to the latest 1.30.0 version

- config/settings.yml
Depends on https://github.com/ManageIQ/manageiq/pull/20010
- Use the docs settings from core
- Switch from string key to symbol key so that it is properly merged
- Alphabetize
- Switch from HTTP to HTTPS
> Move core settings from ui

- app/javascript/components/remove-catalog-item-modal.jsx
- app/javascript/components/remove-generic-item-modal.jsx
- app/javascript/spec/remove-catalog-item-modal/__snapshots__/remove-catalog-item-modal.spec.js.snap
- app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js
- config/jest.setup.js
1. Go to catalog items list view
2. select few items
3. with the above items selected, hit `Select All`
4. launch the dialog modal to remove selected catalog items
Before:
After:
> Fix duplicates in removal dialogs

- app/javascript/spec/remove-catalog-item-modal/__snapshots__/remove-catalog-item-modal.spec.js.snap
Looks like we missed one failing snapshot in https://github.com/ManageIQ/manageiq-ui-classic/pull/6807, somehow.
Now master is red, fixing.
Cc @mzazrivec
> Fix jest snapshot error

- spec/helpers/application_helper_spec.rb
@himdel Please review.
This is needed because in a core PR I am planning on dropping the configure and initialize methods.  This stubbing technique is used elsewhere in the specs in this repo.
cc @chessbyte
> Prefer stubbing permissions over modifying the backend

- .github/CODEOWNERS
I noticed that we have some people in the CODEOWNERS file who might no longer want to get review assignments anymore. Please each of you ACK this PR if you'd like to be removed from the file.
@miq-bot add_reviewer @PanSpagetka
> Remove obsolete lines from CODEOWNERS

- app/controllers/host_controller.rb
to go with https://github.com/ManageIQ/manageiq/pull/19843
> Use Net::SSH:HostKeyMistmatch instead of MiqSshUtilHostKeyMismatch

- app/controllers/application_controller/ci_processing.rb
- app/controllers/ems_cluster_controller.rb
- app/controllers/host_controller.rb
- app/controllers/resource_pool_controller.rb
- app/helpers/application_helper/toolbar/vm_clouds_center.rb
- app/helpers/application_helper/toolbar/vm_infras_center.rb
- spec/controllers/auth_key_pair_cloud_controller_spec.rb
- spec/controllers/availability_zone_controller_spec.rb
- spec/controllers/cloud_tenant_controller_spec.rb
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_cluster_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/controllers/flavor_controller_spec.rb
- spec/controllers/host_aggregate_controller_spec.rb
- spec/controllers/host_controller_spec.rb
- spec/controllers/resource_pool_controller_spec.rb
- spec/controllers/storage_controller_spec.rb
- spec/controllers/vm_cloud_controller_spec.rb
- spec/controllers/vm_infra_controller_spec.rb
Ivanchuk specific PR to backport changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/6426
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6378
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1824811
Enable the action also for the list of Instances
> [IVANCHUK] - Enable Check Compliance toolbar button for nested list of VMs and make it work

- app/controllers/ems_container_controller.rb
The connect method was failing on openshift v4 because the api_group
wasn't being passed.  This method should be in the provider anyway.
Depends: https://github.com/ManageIQ/manageiq-providers-openshift/pull/172
Cross Repo Test: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/120
Fixes: https://github.com/ManageIQ/manageiq/issues/20155
> Move the openshift metrics hostname detection

- bin/update
sorry not sorry, I can't stand this one
> Fixed typo

- app/javascript/components/async-credentials/password-field.jsx
- app/javascript/components/automate-import-export-form/datastore-via-git.schema.js
- app/javascript/components/catalog-form/catalog-form.schema.js
- app/javascript/components/cloud-network-form/cloud-network-form.schema.js
- app/javascript/components/copy-catalog-form/copy-catalog-form.schema.js
- app/javascript/components/copy-dashboard-form/copy-dashboard-form.schema.js
- app/javascript/components/firmware-registry/firmware-registry-form.schema.js
- app/javascript/components/flavor-form/flavor-form.schema.js
- app/javascript/components/ops-tenant-form/ops-tenant-form.schema.js
- app/javascript/components/orchestration-template/orchestration-template-form.schema.js
- app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
- app/javascript/components/region-form/region-form.schema.js
- app/javascript/components/service-dialog-from-form/service-dialog-from.schema.js
- app/javascript/components/set-ownership-form/ownership-form.schema.js
- app/javascript/components/vm-server-relationship-form/vm-server-relationship-form.schema.js
- app/javascript/components/vm-snapshot-form/vm-snapshot-form.schema.js
- app/javascript/components/workers-form/workers.schema.js
- app/javascript/spec/forms/data-driven-form.spec.js
- app/javascript/spec/helpers/fieldProvider.js
Since we [have](https://github.com/ManageIQ/manageiq-ui-classic/pull/7005) the `@@ddf` global, let's use it everywhere possible.
> Import componentTypes and validatorTypes from the global `@@ddf`

- package.json
ManageIQ/ui-components#439
ManageIQ/ui-components#440
> Update ui-components to 1.4.1

- package.json
- yarn.lock
> [JANSA] Update ui components to 1.3.5

- app/javascript/forms/mappers/formsFieldsMapper.jsx
Cherry-picked from https://github.com/ManageIQ/manageiq-ui-classic/pull/7084
> [JANSA] Globally set the default placeholder for select fields in DDF

- app/javascript/forms/mappers/formFieldsMapper.jsx
Probably introduced by a rebase (there were some) in the area.
> Remove duplicated FieldArray component from the component mapper

- app/controllers/application_controller/performance.rb
Fix for https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8690
> I18N for strings on Utilization screen

- config/routes.rb
- spec/routing/miq_request_routing_spec.rb
Route prov_show_option does not exist.
cc @skateman
> Remove not existing route prov_show_option

- cypress/README.md
- package.json
> Add Firefox cypress helper

- app/views/layouts/_tag_edit.html.haml
- config/routes.rb
- spec/routing/catalog_routing_spec.rb
> Remove unused routes for catalog controller

- config/routes.rb
- spec/helpers/application_helper_spec.rb
- spec/routing/host_routing_spec.rb
- spec/routing/shared_examples/crud_examples.rb
Remove host routes that don't exist any more.
cc @skateman
> Clean up non-existing host routes.

- app/views/miq_policy/_alert_builtin_exp.html.haml
- app/views/miq_policy/_alert_details.html.haml
Fix for https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/9525
before
after
> Fix to translate string in UI

- config/routes.rb
- spec/routing/dashboard_routing_spec.rb
These routes don't exist.
@miq-bot add_label cleanup
> Clean up dashboard routes.

- app/javascript/menu/username.jsx
- app/stylesheet/menu-colors.scss
- app/stylesheet/menu.scss
replace initials with user avatar icon,
and fix group icon color when collapsed
Before:
After:
> Menu - update collapsed user icon

- vendor/assets/stylesheets/brand.scss
Not relevant since https://github.com/ManageIQ/manageiq-ui-classic/pull/6963
> Remove old navbar styling from brand.scss

- app/controllers/chargeback_rate_controller.rb
This fixes an issue when user tries to change Rate type on a Add Chargeback Rate form, with the fix it should reload form to show Storage/Compute fields when type is changed.
before
after
> Moved common code to a method to reset tier details when switching Type.

- app/controllers/application_controller/compare.rb
unused since https://github.com/ManageIQ/manageiq/pull/7321
> Remove unused grid_rows_json, grid_cols_json

- app/helpers/application_helper/toolbar_chooser.rb
Fixed an issue where PXE/Customization Templates list screen was loading toolbar for summary screen, causing an error when trying to edit/delete selected record(s) from list.
> Fixed code to load correct toolbar on list/summary screens.

- app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
This seemed like an easy one to change, since it was just a local variable.
> Rename term to disabled_types for clarity

- config/routes.rb
> Added missing `download_summary_pdf` route for physical chasis/racks

- config/routes.rb
Fixes #7150
Opened new PR in favor of https://github.com/ManageIQ/manageiq-ui-classic/pull/7178, something went wrong on that PR can not get it to re-open
> Deleted dead routes

- package.json
- yarn.lock
Includes
* https://github.com/ManageIQ/ui-components/pull/442
> [IVANCHUK] Update ui components to 1.2.19

- package.json
Includes:
* https://github.com/ManageIQ/ui-components/pull/441
* https://github.com/ManageIQ/ui-components/pull/442
* https://github.com/ManageIQ/ui-components/pull/443
* https://github.com/ManageIQ/ui-components/pull/444
> Update ui-components to 1.4.2

- package.json
- yarn.lock
Includes:
* https://github.com/ManageIQ/ui-components/pull/438
* https://github.com/ManageIQ/ui-components/pull/443
* https://github.com/ManageIQ/ui-components/pull/444
* https://github.com/ManageIQ/ui-components/pull/442
> [JANSA] Update ui-components to 1.3.6

- app/assets/javascripts/components/retirement-form.js
Texts for `Set Retirement Date` can't be translated.
> Fix to retirement date in retirement form.

- app/javascript/menu/first-level.jsx
- app/javascript/menu/second-level.jsx
> Fixed to translate menu titles in Navbar

- app/javascript/components/main-menu/second-level.jsx
- app/javascript/components/main-menu/third-level.jsx
- app/javascript/components/main-menu/top-level.jsx
Jansa specific PR for https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/9119
Upstream PR - https://github.com/ManageIQ/manageiq-ui-classic/pull/7204
> [JANSA] Fixed to translate menu titles in Navbar

- config/routes.rb
> Added missing route

- app/javascript/forms/data-driven-form.jsx
adjusted cherry-pick of a0175ca8618f3eadaf34801e0fa5fa6ec4080856
https://github.com/ManageIQ/manageiq-ui-classic/pull/7003
> [JANSA] Merge default button labels properly with the custom ones in DDF

- app/controllers/application_controller/filter/expression.rb
- app/controllers/ops_controller/settings/common.rb
- app/controllers/report_controller.rb
- app/controllers/report_controller/menus.rb
- app/views/miq_request/_prov_field.html.haml
For https://github.com/ManageIQ/manageiq-gems-pending/pull/483
cc @jrafanie
> Prefer Array.wrap over #to_miq_a

- app/javascript/components/remove-generic-item-modal.jsx
@miq-bot add_label bug, jansa/yes, internationalization
> Fix a string typo

- app/javascript/components/orchestration-template/orchestration-template-form.schema.js
@miq-bot add_label bug, jansa/yes, internationalization
> Add I18N support to Orchestration Template string Draft.

- package.json
- yarn.lock
Includes:
* https://github.com/ManageIQ/ui-components/pull/415
* https://github.com/ManageIQ/ui-components/pull/431
> [IVANCHUK] Update ui components to 1.2.20

- app/controllers/vm_common.rb
- app/helpers/textual_summary_helper.rb
- app/helpers/vm_helper/textual_summary.rb
- app/views/layouts/_textual_groups_generic.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1572649
> Add flash message about required restart to VM summary screen

- package.json
- yarn.lock
Includes:
* https://github.com/ManageIQ/ui-components/pull/446
> [IVANCHUK] Update ui components to 1.2.21

- app/views/miq_request/_request.html.haml
- app/views/miq_request/_request_dialog_details.html.haml
- app/views/miq_request/_st_prov_show.html.haml
Before.
After.
@miq-bot add_label bug, internationalization, jansa/yes
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8696
> Enable I18N translation to service requests.

- cypress/integration/ui/toolbar.spec.js
"Fixes" by skipping the test for "VMs & Templates" since database seeding, factories, and database cleaning needs to be supported before this is testable.
Links
-----
* Example run on CI here:  https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/150
> "Fix" toolbar.spec.js

- spec/controllers/miq_policy_controller/alert_profiles_spec.rb
- spec/controllers/miq_policy_controller/alerts_spec.rb
- spec/controllers/miq_policy_controller/miq_actions_spec.rb
Gave specific feature access to logged in user.
Fixing failures in https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/371421807
> [HAMMER] - Fixing spec test failures on Hammer

- app/controllers/tree_controller.rb
- spec/controllers/tree_controller_spec.rb
depends on:
This PR fixes the tree lookups in the tree controller. It was throwing errors before.
This fixes the problem and performs fewer queries
fixes https://github.com/ManageIQ/manageiq-ui-classic/pull/7249
> Fixes TreeController issue

- app/helpers/configured_system_helper/textual_summary.rb
Implementation for https://github.com/ManageIQ/manageiq-ui-classic/issues/7284
> Display relationship between Configured System and VM.

- package.json
Includes:
* https://github.com/ManageIQ/ui-components/pull/445
* https://github.com/ManageIQ/ui-components/pull/447
> Update ui-components to 1.4.3

- package.json
- yarn.lock
Includes:
* https://github.com/ManageIQ/ui-components/pull/373
* https://github.com/ManageIQ/ui-components/pull/408
* https://github.com/ManageIQ/ui-components/pull/443
* https://github.com/ManageIQ/ui-components/pull/444
* https://github.com/ManageIQ/ui-components/pull/447
* https://github.com/ManageIQ/ui-components/pull/448
> [IVANCHUK] Update ui-components to 1.2.22

- package.json
- yarn.lock
Includes:
* https://github.com/ManageIQ/ui-components/pull/445
* https://github.com/ManageIQ/ui-components/pull/447
* https://github.com/ManageIQ/ui-components/pull/448
> [JANSA] Update ui components to 1.3.7

- .gitignore
cc @kavyanekkalapu this should prevent anyone from checking that file into the repo in the future
> Add .DS_Store to the .gitignore

- app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
Fixes: [#8654](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8654)
Before: 
After:
> Translated Credential type list

- app/controllers/miq_ae_customization_controller/custom_buttons.rb
Located in Automation->Automate->Customization->Buttons.
Preview:
> Set String "Unassigned Buttons" to be Translated

- app/javascript/components/breadcrumbs/notifications-toggle.jsx
- app/javascript/menu/first-level.jsx
- app/javascript/menu/group-switcher.jsx
- app/javascript/menu/history.js
- app/javascript/menu/icon.jsx
- app/javascript/menu/item-type.js
- app/javascript/menu/main-menu.jsx
- app/javascript/menu/menu-collapse.jsx
- app/javascript/menu/miq-logo.jsx
- app/javascript/menu/navbar.jsx
- app/javascript/menu/search-results.jsx
- app/javascript/menu/search.jsx
- app/javascript/menu/second-level.jsx
- app/javascript/menu/side-nav-menu-link.jsx
- app/javascript/menu/username.jsx
- app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
* Added propTypes everywhere where I could
* Removed redundant parentheses from arrow functions
* Squashed unnecessary line breaks in components with <4 attributes
* Added parentheses around multiline return values
* Exporting/importing single components as default
> Make eslint happier about the menu

- package.json
- yarn.lock
Includes:
* https://github.com/ManageIQ/ui-components/pull/450
* https://github.com/ManageIQ/ui-components/pull/451
> [IVANCHUK] Update ui-components to 1.2.23

- package.json
Includes:
* https://github.com/ManageIQ/ui-components/pull/449
* https://github.com/ManageIQ/ui-components/pull/450
* https://github.com/ManageIQ/ui-components/pull/451
* https://github.com/ManageIQ/ui-components/pull/452
> Update ui-components to 1.4.4

- app/javascript/spec/select/__snapshots__/select.spec.js.snap
- app/javascript/spec/select/select.spec.js
Added two tests for the Select component:
- Snapshot test
- Select component's onChange function gets called.
> Added tests for the Select component

- app/helpers/configured_system_helper/textual_summary.rb
Add Icons for configured system vendor
Related Changes:
- https://github.com/ManageIQ/manageiq-decorators/pull/37
- https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/39
> Add Icons for configured system vendor

- app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap
- app/javascript/spec/tree-view/__snapshots__/selector.spec.js.snap
- package.json
This should fix the broken date(time)picker field  https://github.com/data-driven-forms/react-forms/issues/838
> Update DDF version to 2.14.0

- .codeclimate.yml
- .rubocop.yml
- .rubocop_cc.yml
- manageiq-ui-classic.gemspec
Depends on: https://github.com/ManageIQ/miq_bot/pull/506
> Use manageiq-style

- spec/controllers/catalog_controller_spec.rb
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/presenters/tree_builder_report_reports_spec.rb
- spec/presenters/tree_node/miq_product_feature_spec.rb
- spec/services/ems_infra_dashboard_service_spec.rb
we have just a handful of these left
> change factorygirl to factorybot

- app/helpers/application_helper/button/security_policy_new.rb
- app/helpers/application_helper/button/security_policy_rule_new.rb
- app/helpers/application_helper/toolbar/security_policy_rule_center.rb
* Fix for switched Security Policy (Rule) new buttons checks
* Fix for Security Policy Rule toolbar
> Fixes for Security Policy (Rule) buttons

- app/views/shared/buttons/_ab_options_form.html.haml
Found in Automation -> Automate -> Customization -> Buttons -> (Select one of the Button Groups) -> Add a new Button
Related to: https://github.com/ManageIQ/manageiq/pull/20762
Fixes: [#10515](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10515)
Preview:
> Marked Strings for Translation in Automation -> Automate -> Customization

- app/controllers/cloud_volume_controller.rb
- spec/controllers/cloud_volume_controller_spec.rb
- spec/services/dialog_local_service_spec.rb
Broken by https://github.com/ManageIQ/manageiq-providers-openstack/pull/664
Depends on https://github.com/ManageIQ/manageiq-providers-openstack/pull/666
> Adjust specs to the remodulized CloudVolume classes under OpenStack

- app/controllers/catalog_controller.rb
* no string arithmetic
* better looking translations
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1751107
> Fix right cell text for root nodes in CatalogController

- app/views/report/_form_sort.html.haml
Found in: Overview -> Reports -> Add a new Report -> Summary
Preview:
> Marked "Check Option" String for Translation

- app/controllers/container_dashboard_controller.rb
- config/routes.rb
fixes https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/15393
after fix
> Added missing `show` route for container_dashboard

- app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
- app/javascript/spec/provider-form/__snapshots__/protocol-selector.spec.js.snap
- app/javascript/spec/select/__snapshots__/select.spec.js.snap
- package.json
Should fix some bugs with lazily loaded multiselects
> Update DDF to its latest version, adjust snapshots

- app/views/report/_form_sort.html.haml
Found in: Overview -> Reports -> Add a new Report -> Summary
Relies on: https://github.com/ManageIQ/manageiq/pull/20867
Preview:
> Modified HAML File to Reflect Changes Made to MiqReport::GROUPINGS

- app/views/report/_widget_show.html.haml
Found in: Overview -> Reports -> Dashboard Widgets
Related to: https://github.com/ManageIQ/manageiq/pull/20843
See core PR for details
Preview:
> Marked String for Translation in HAML File

- app/javascript/components/async-credentials/async-credentials.jsx
Issue described in https://github.com/ManageIQ/manageiq-ui-classic/issues/7545 and introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/7540
It's a little bit ugly, but it does the job, @llivne can you please verify if it fixes the issue? @himdel @h-kataria can you please help me checking if it doesn't break anything else?
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7545
> DDF: fixing the endless render of async dropdowns in provider forms

- app/controllers/application_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/miq_policy_log_controller.rb
- app/presenters/menu/default_menu.rb
- app/views/layouts/_log_viewer.html.haml
- app/views/miq_policy/show.html.haml
- app/views/miq_policy_log/index.html.haml
- config/routes.rb
- spec/config/routes.pending.yml
- spec/controllers/miq_policy_controller_spec.rb
- spec/controllers/miq_policy_log_controller_spec.rb
- spec/routing/miq_policy_log_routing_spec.rb
- spec/routing/miq_policy_routing_spec.rb
Split Control/Log sub menu code from Policy Controller into it's own controller for simplicity
Pending Core PR https://github.com/ManageIQ/manageiq/pull/20934
Data migration PR https://github.com/ManageIQ/manageiq-schema/pull/545
@skateman please review.
> Split policy log

- app/presenters/tree_builder_protect.rb
Found in Network -> Providers -> Manage Policies
Fixes: [#9668](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/9668)
Preview:
> Marked Strings for Translation in Network -> Providers

- app/controllers/catalog_controller.rb
- app/controllers/host_aggregate_controller.rb
- app/controllers/miq_event_controller.rb
- spec/controllers/automation_manager_controller_spec.rb
- spec/controllers/ops_settings_spec.rb
- spec/helpers/application_helper/buttons/instance_attach_spec.rb
> remove unused variables

- app/javascript/components/toolbar/ToolbarList.jsx
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7541
In this pr, fixed focus breaks when switching between toolbar dropdowns
> Fix toolbar focus bug

- app/controllers/ops_controller/settings/common.rb
When this form was converted to react, this became dead code that is not called.
@h-kataria Please review.
> Remove old settings_workers code

- spec/config/routes.pending.yml
https://github.com/ManageIQ/manageiq/pull/20948/files#diff-cdcd147fb85ef58d008a4ad0cfa3ddfea649382cb062407e2342aff07362b6cfR1924-R1936
> Remove ConditionController#report_data from RBAC false positives

- app/controllers/volume_mapping_controller.rb
- app/helpers/ems_storage_helper/textual_summary.rb
- app/helpers/volume_mapping_helper.rb
- app/helpers/volume_mapping_helper/textual_summary.rb
- app/presenters/menu/default_menu.rb
- app/services/ems_storage_dashboard_service.rb
- app/views/volume_mapping/show.html.haml
- app/views/volume_mapping/show_list.html.haml
- config/routes.rb
- product/views/VolumeMapping.yaml
- spec/config/routes.pending.yml
- spec/helpers/ems_storage_helper/textual_summary_spec.rb
- spec/presenters/menu/default_menu_spec.rb
Part of https://github.com/ManageIQ/manageiq/issues/21018
> Introduced volume mapping

- app/controllers/mixins/ems_common.rb
- app/controllers/volume_mapping_controller.rb
- app/helpers/application_helper/toolbar/volume_mapping_center.rb
- app/helpers/application_helper/toolbar/volume_mappings_center.rb
- app/javascript/components/volume-mapping-form/index.jsx
- app/javascript/components/volume-mapping-form/volume-mapping-form.schema.js
- app/javascript/packs/component-definitions-common.js
- app/views/volume_mapping/new.html.haml
- config/routes.rb
This PR continues https://github.com/ManageIQ/manageiq-ui-classic/pull/7621 by allowing creation of volume-mappings.
Needs to be done after https://github.com/ManageIQ/manageiq-ui-classic/pull/7621 and https://github.com/ManageIQ/manageiq-api/pull/1006
> Creating volume mapping

- app/controllers/miq_ae_tools_controller.rb
All logs will have an initial log line showing when the log was created,
even if the log is actually empty.  Since we are using an empty check to
determine if it's possible to fetch the log, we should ignore this
initial log line.
@kavyanekkalapu  Please review.
> Fix checking for blank log contents

- app/presenters/menu/default_menu.rb
- spec/presenters/tree_builder_ops_rbac_features_spec.rb
> Rearranged Configuration/Automation menus

- app/stylesheet/ddf_override.scss
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/7633
**Before:**
**After:**
> Fix ddf components style issues

- app/javascript/components/performance-charts/areaChart.js
- app/javascript/components/performance-charts/index.jsx
- app/views/layouts/_perf_chart_js.html.haml
- spec/views/layouts/perf_charts_js_spec.rb
**Issue:** Some of the c&u charts are not converted carbon, Fixed in this pr.
**Before:**
**After:**
> Convert C&U charts to carbon

- app/controllers/miq_policy_controller.rb
- app/controllers/miq_policy_set_controller.rb
- spec/controllers/miq_policy_controller_spec.rb
- spec/controllers/miq_policy_set_controller_spec.rb
Follow-up for https://github.com/ManageIQ/manageiq-ui-classic/pull/7696
@miq-bot assign @chessbyte , @Fryguy 
@miq-bot add_reviewer @chessbyte , @Fryguy
> Fix testcases and breadcrumb for policies

- app/javascript/components/visual-settings-form/index.jsx
- app/javascript/components/visual-settings-form/visual-settings-form.schema.js
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/7686
> Modified "My Settings" to Prevent Invalid Argument Error

- app/views/miq_policy/_form.html.haml
Found in Control->Policy
Depends On: https://github.com/ManageIQ/manageiq/pull/21140
Preview:
> Translated Strings in Control->Policy

- app/controllers/report_controller/reports/editor.rb
Fixes https://github.com/ManageIQ/manageiq/issues/21148
**Before:**
**After:**
@miq-bot add_reviewer @DavidResende0 , @Fryguy
> Fix chargeback report tag and group by tag bug

- app/controllers/report_controller/reports/editor.rb
> Fixed Wrong Element Type Error When Trying to Create Chargeback Report

- app/javascript/oldjs/controllers/cloud_volume/cloud_volume_form_controller.js
**Issue:**: In Cloud Volumes--> Select any available Cloud Volume--> Attach Cloud Volume
**Description**: This form initially doesn't have any api calls, so we don't need promise here.
**Before**
**After**
> Fix Attach Cloud Volume form

- app/javascript/components/breadcrumbs/notifications-toggle.jsx
- app/javascript/components/notification-drawer/helpers.js
- app/javascript/components/notification-drawer/notification-drawer.jsx
- app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
- app/javascript/spec/notification-drawer/__snapshots__/notification-drawer.spec.js.snap
- app/javascript/spec/notification-drawer/notification-drawer.spec.js
- app/stylesheet/notifications.scss
- app/views/layouts/_header.html.haml
- app/views/layouts/_searchbar.html.haml
Issue : https://github.com/ManageIQ/manageiq-ui-classic/issues/7367
Here, converted notification drawer to carbon and fixed accessibility.
**Before:**
Keyboard focus is not at all going to either Notifications toggle button or into Notification drawer.
**After:**
@miq-bot add_reviewer @DavidResende0 , @Fryguy
> change notification drawer to carbon and fix A11y

- app/controllers/cloud_volume_controller.rb
> Replace CloudVolume#validate_update_volume with supports?(:update)

- app/controllers/dashboard_controller.rb
- spec/controllers/dashboard_controller_spec.rb
Depends on ManageIQ/manageiq#21171
> Handle Unicode characters in httpd auth headers

- app/controllers/ops_controller/ops_rbac.rb
https://github.com/ManageIQ/manageiq-style/pull/23#issuecomment-827591066
> Fix negated if/else rubocop error

- app/javascript/oldjs/services/alerts_center_service.js
@kavyanekkalapu Please review.  I'm not sure how to test this directly as I have no data - perhaps @agrare can help?
master PR for #7721
> Monitor > alerts > all alert bug fixed

- app/controllers/chargeback_rate_controller.rb
- spec/controllers/chargeback_rate_controller_spec.rb
Previously, you'll get a permission error when trying to "save" or "reset" when
adding or editing a chargeback rate.
chargeback_rates_edit is not yet chargeback_rate_edit
and chargeback_rates_new is not yet chargeback_rate_new.
It looks like this was broken in 968c4657af3b414e262ad5499dbdaf345445ed5d
where the "new" renamed features were used in a few places but the product
feature has not yet been renamed.
Changed the tests to use these features instead of blindly getting all features
in order to recreate the problem.
Note:  You'll need to use a non-adminstrator user to recreate this issue.
Links
* [Current product features in the relevant chargeback area](https://github.com/ManageIQ/manageiq/blob/2b1b2cb0ce4760e38ad2a837dd8b1119a9544b48/db/fixtures/miq_product_features.y …
> Fix not yet renamed chargeback_rates features

- spec/controllers/miq_alert_controller_spec.rb
@jrafanie Please review
Part of ManageIQ/manageiq#21216
> Fix invalid feature in spec

- app/javascript/components/aggregate_status_card.jsx
**Before**
**After**
@miq-bot add_reviewer @Fryguy , @DavidResende0 
@miq_bot add-label bug
> Fix console error in tenant dashboard

- spec/controllers/ops_controller/ops_rbac_spec.rb
Needed for https://github.com/ManageIQ/manageiq/pull/21250, which now
depends on this value to be accurate.
@kbrock Please review.  This can be merged ahead of https://github.com/ManageIQ/manageiq/pull/21250
> Fix issue where test setup is inaccurate

- app/javascript/components/gtl/DataTable.jsx
Running linter on code before apply changes for issue.
> Applying ESLint changes in gtl/table react component.

- app/javascript/components/remove-generic-item-modal.jsx
Fixed the error in Control-> Action page, cannot delete an action
**Before:** 
**After:** 
@miq-bot add_reviewer @kavyanekkalapu 
> Fix Action Form Delete Button

- app/javascript/components/ansible-credentials-form/ansible-credentials-form.schema.js
- app/javascript/components/async-credentials/password-field.jsx
- app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
- app/javascript/components/flavor-form/flavor-form.schema.js
- app/javascript/components/host-initiator-form/host-initiator-form.schema.js
- app/javascript/components/physical-storage-form/physical-storage-form.schema.js
- app/javascript/components/provider-form/protocol-selector.jsx
- app/javascript/components/quadicon/Quaditem.jsx
- app/javascript/components/remove-catalog-item-modal.jsx
- app/javascript/components/remove-generic-item-modal.jsx
- app/javascript/components/retirement-form/index.jsx
- app/javascript/components/select/index.jsx
- app/javascript/components/tree-view/redux.jsx
- app/javascript/components/visual-settings-form/index.jsx
- app/javascript/components/visual-settings-form/visual-settings-form.schema.js
- app/javascript/forms/data-driven-form.jsx
- app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
- app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap
- app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js
- app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap
- app/views/cloud_tenant/edit.html.haml
Fixed react prop and label text/value console errors.
Error Examples:
> Fixed react props and label text console errors

- app/assets/javascripts/controllers/buttons/button_group_controller.js
- app/javascript/components/tree-view/redux.jsx
Builds are failing for Kasparov branch https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/builds/232633443 , fixing it in this pr
> [KASPAROV] Reverting ES6 fixes to fix test cases in kasparov branch

- app/controllers/miq_ae_class_controller.rb
- app/controllers/miq_ae_customization_controller/old_dialogs.rb
- app/controllers/ops_controller/ops_rbac.rb
See individual commits
- Use exists? with an :id key over passing params directly
- Prefer permit with actual columns over permit!
- Move YAML load into the model layer
> Various refactorings to handle brakeman issues

- app/javascript/components/subnet-form/subnet-form.schema.js
Fixed an issue with the subnet form that prevented users from logging in.
> Fix subnet form issue

- app/javascript/components/settings-tasks-form/index.jsx
- app/javascript/components/settings-tasks-form/settings-tasks-form.schema.js
- app/javascript/spec/settings-tasks_form/__snapshots__/settings-tasks-form.spec.js.snap
Fixed missing string translation on Tasks form.
Before:
After:
> Fixed missing string translation

- app/assets/stylesheets/fonticon_picker.scss
- app/javascript/components/fonticon-picker/icon-list.jsx
- app/javascript/components/fonticon-picker/icon-modal.jsx
> Convert font-icon-picker modal from pattern-fly to carbon

- app/presenters/menu/default_menu.rb
- spec/presenters/tree_builder_ops_rbac_features_spec.rb
Morphy pr for https://github.com/ManageIQ/manageiq-ui-classic/pull/7667
> [Morphy] reconfigure menus for Morphy.

- app/javascript/components/service-request-default/index.jsx
Apply button is broken, clicking on it will empty the data table instead of showing the rows of data. 
https://user-images.githubusercontent.com/29209973/134062964-3dfeff3c-f169-4a37-a872-e15b5184d8f4.mov
https://user-images.githubusercontent.com/29209973/134062854-31cdd10c-b1d6-4493-bdaa-3c297709bcfc.mov
@miq-bot assign @MelsHyrule
@miq-bot add-reviewer @mengxiwuu
> Apply button fix in requests page.

- app/controllers/miq_request_controller.rb
- app/javascript/components/miq-toolbar.jsx
- app/javascript/components/service-request-default/index.jsx
- app/javascript/toolbar-actions/util.js
- app/javascript/toolbar-actions/util.spec.js
- app/views/miq_request/show_list.html.haml
Fixes [#7855](https://github.com/ManageIQ/manageiq-ui-classic/issues/7855). 
https://user-images.githubusercontent.com/29209973/133300045-2ffe1ade-4a21-4bb5-9ca6-2b8521820b9b.mov
> Refresh services requests

- app/javascript/components/toast-list/toast-list.jsx
- app/javascript/spec/toast-list/__snapshots__/toast-list.spec.js.snap
- app/javascript/spec/toast-list/toast-list.spec.js
- app/stylesheet/notifications.scss
Fixes [#7850](https://github.com/ManageIQ/manageiq-ui-classic/issues/7850)
@miq-bot assign @MelsHyrule
> Converting PF toast notification to  Carbon Toast Notification.

- app/javascript/toolbar-actions/util.js
This is introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/7861
> Fix ConvertMultParamstoRailsParams console error

- app/controllers/cloud_volume_controller.rb
- app/controllers/vm_cloud_controller.rb
- app/helpers/application_helper/button/volume_attach.rb
- spec/helpers/application_helper/buttons/volume_attach_spec.rb
Part of https://github.com/ManageIQ/manageiq/pull/21393
> Convert cloud volume operations to SupportsFeatureMixin

- app/assets/stylesheets/about_modal_background.scss
- app/javascript/components/miq-about-modal/miq-about-modal.jsx
- app/javascript/components/miq-about-modal/modal-item.jsx
- app/javascript/packs/component-definitions-common.js
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7851
Converted AboutModal component from pattern-fly to carbon.
Before:
After:
> Converted AboutModal component from pattern-fly to carbon

- app/helpers/application_helper/button/auth_key_pair_cloud_create.rb
- spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb
Goes with https://github.com/ManageIQ/manageiq/pull/21457
> Convert AuthKey operations to SupportsFeatureMixin

- app/helpers/application_helper/button/volume_detach.rb
- spec/helpers/application_helper/buttons/volume_detach_spec.rb
Followup to https://github.com/ManageIQ/manageiq-ui-classic/pull/7839
> Convert detach_volume to SupportsFeatureMixin

- app/stylesheet/legacy/topology.scss
- app/stylesheet/notifications.scss
- app/stylesheet/toolbar.scss
Fixes the following stylelint issues:
- declaration-block-no-duplicate-properties
- font-family-no-duplicate-names
@kavyanekkalapu Please review.
> Fix duplication issues in style sheets

- package.json
- yarn.lock
https://github.com/ManageIQ/manageiq-ui-classic/pull/7931
Bumps jquery-ui from 1.12.1 to 1.13.0.
> Update Jquery-ui version

- app/controllers/host_aggregate_controller.rb
- app/helpers/application_helper/button/auth_key_pair_cloud_create.rb
- app/helpers/application_helper/button/new_host_aggregate.rb
- app/helpers/application_helper/toolbar/host_aggregate_center.rb
- spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb
Required for:
* https://github.com/ManageIQ/manageiq-api/pull/1098
Depends on:
> Use standard CRUD features for AuthKeyPair and HostAggregate

- app/controllers/cloud_object_store_container_controller.rb
Renamed in parent PR ManageIQ/manageiq#21556
@agrare @kbrock Please review.
> Rename supported_subclasses to permitted_subclasses

- app/controllers/ops_controller.rb
- app/controllers/ops_controller/diagnostics.rb
Part of https://github.com/ManageIQ/manageiq/pull/21558
> Remove unnecessary caller to VMDBLogger#filename

- app/controllers/miq_ae_tools_controller.rb
- app/controllers/miq_policy_log_controller.rb
- app/controllers/ops_controller/diagnostics.rb
Part of https://github.com/ManageIQ/manageiq/pull/21558
Depends on
> Replace VMDBLogger#contents with Vmdb::Loggers.contents

- app/controllers/host_controller.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7961
**Before**
**After**
> Fix hosts network page tree view

- app/views/layouts/_searchbar.html.haml
> Remove search from forms

- app/controllers/host_aggregate_controller.rb
**Before**
**After**
@miq_bot add_reviewer @agrare
> Fix host aggregates create form

- config/webpack/shared.js
- package.json
- yarn.lock
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7844
This pr removes patternfly-react package from package.json.
@miq-bot add-label cleanup
> Remove PF react package

- app/controllers/ems_network_controller.rb
- app/controllers/mixins/storage_common_mixin.rb
- app/helpers/application_helper/button/ems_network.rb
part of ManageIQ/manageiq#21573
> renaming supports :ems_network_new to update

- app/controllers/host_initiator_group_controller.rb
- app/helpers/application_helper/button/host_initiator_group_new.rb
- app/helpers/application_helper/toolbar/host_initiator_groups_center.rb
- app/javascript/components/host-initiator-group-form/host-initiator-group-form.schema.js
- app/javascript/components/host-initiator-group-form/index.jsx
- app/javascript/packs/component-definitions-common.js
- app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
- app/javascript/spec/host-initiator-group-form/host-initiator-group.spec.js
- app/views/host_initiator_group/new.html.haml
- config/routes.rb
In this set of PRs we will allow users to create new host-initiator-groups on their storage systems through MIQ.
Part of https://github.com/ManageIQ/manageiq-providers-autosde/issues/108
Needs to be merged after https://github.com/ManageIQ/manageiq-api/pull/1105
> Creation of host initiator group

- app/javascript/components/miq-data-table/miq-table-cell.jsx
Fixed console errors for clicking on non clickable table rows.
> Fixed console error for non clickable table rows

- app/javascript/components/miq_debug/index.jsx
- app/javascript/components/miq_debug/toast-item.jsx
- app/javascript/components/miq_debug/toast-wrapper.jsx
- app/javascript/oldjs/application.js
- app/javascript/oldjs/miq_debug.js
Converting `miq_debug.js` to use javascript and react components. 
> miq_debug: rewrite angular parts to react

- app/helpers/miq_policy_helper.rb
- app/javascript/components/miq-structured-list/helpers.js
- app/javascript/components/miq-structured-list/index.jsx
- app/views/miq_policy/show.html.haml
Basic Information, Scope, Notes were converted to new ui design.
Before
After
> Policies Form list conversion

- app/helpers/charting_helper.rb
- app/stylesheet/charts.scss
- app/views/layouts/_perf_chart_js.html.haml
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/7976
**Before:** 
1. Right x-axis is cut off:
2. Magnifier does not work, left x-axis cut off:
**After:** 
1. Fixed cut off
2. Deleted magnifier and fixed left x-axis cut off
> Fix provider dashboard chart layout

- app/controllers/cloud_volume_controller.rb
- app/controllers/host_initiator_group_controller.rb
- app/helpers/cloud_volume_helper/textual_summary.rb
- app/helpers/host_initiator_group_helper/textual_summary.rb
- app/helpers/host_initiator_helper/textual_summary.rb
- app/helpers/volume_mapping_helper/textual_summary.rb
- product/views/HostInitiatorGroup.yaml
- product/views/VolumeMapping.yaml
Part of https://github.com/ManageIQ/manageiq-providers-autosde/issues/83
PR set
https://github.com/ManageIQ/manageiq/pull/21640
https://github.com/ManageIQ/manageiq-ui-classic/pull/8007
https://github.com/ManageIQ/manageiq-providers-autosde/pull/125
> Improving UI representation of host-initiator-groups and volume-mappings

- app/helpers/volume_mapping_helper/textual_summary.rb
@kavyanekkalapu Please review
cc @gregoryb-at-ibm @agrare 
As per https://github.com/ManageIQ/guides/blob/master/i18n.md#string-interpolation
> Fix i18n on Host Initiator Group title

- package.json
- yarn.lock
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8026
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8028
**After**
> Update webpack-dev-server for CVE

- package.json
- yarn.lock
Update precss version
**Issue**: https://github.com/ManageIQ/manageiq-ui-classic/issues/8039
> update precss version

- package.json
- yarn.lock
issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/8050
> Update compress-webpack-plugin version

- package.json
- yarn.lock
issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/8083
> update webpack dev server

- .github/workflows/ci.yaml
> Remove fail-fast now that GHA are working

- app/assets/stylesheets/about_modal_background.scss
Followup of https://github.com/ManageIQ/manageiq-ui-classic/pull/7992
> [MORPHY] Fix about modal BG image

- .github/workflows/ci.yaml
- package.json
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
> update node version

- app/controllers/dashboard_controller.rb
- app/controllers/report_controller/dashboards.rb
- app/helpers/dashboard_helper.rb
- app/stylesheet/application-webpack.scss
- app/stylesheet/dashboard.scss
- app/views/dashboard/show.html.haml
- app/views/report/_db_widgets.html.haml
Converting the dashboard page from 3 columns to 2 column design
**Dashboard**
Before
After
**Sample Dashboard**
Before
After
> Make dashboard two column design

- app/controllers/pxe_controller/iso_datastores.rb
- app/helpers/application_helper/button/iso_datastore_new.rb
SupportsFeature .supporting() now checks instance level supports as well
https://github.com/ManageIQ/manageiq/pull/21729
> Cleanup IsoDatastore supporting()

- app/javascript/components/ansible-repository-form/ansible-repository-form.schema.js
- app/javascript/components/ansible-repository-form/helpers.jsx
- app/javascript/components/ansible-repository-form/index.jsx
- app/javascript/spec/ansible-repository-form/helpers.spec.js
- package.json
- yarn.lock
Fixes https://github.com/ManageIQ/manageiq/issues/21700
> Allows for SSH GitHub Repo

- .github/workflows/ci.yaml
- package.json
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
@miq_bot assign @fryguy
@miq_bot add_reviewer @fryguy
@miq_bot add-label dependencies, najdorf/yes?
> Downgrade node version to 14

- app/controllers/ops_controller/diagnostics.rb
Aim to fix the issue https://github.com/ManageIQ/manageiq-ui-classic/issues/8143
Before
After
> Log depot edit:  undefined variable bug fix

- app/javascript/components/auth-key-pair-cloud/auth-key-pair-cloud-form.schema.js
- app/javascript/spec/auth-key-pair-cloud/__snapshots__/ansible-credentials-form.spec.js.snap
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8163
**Before**
**After**
> Update keypair schema to fix validation

- app/controllers/cloud_volume_controller.rb
> Fix attach and detach cloud volume notification

- app/controllers/cloud_volume_controller.rb
- app/helpers/application_helper/toolbar/cloud_volume_center.rb
- app/helpers/application_helper/toolbar/cloud_volumes_center.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8166
**Before**
**After**
> Update validation for edit cloud volume button

- app/javascript/oldjs/miq_tree.js
> Fix genealogy tree selection

- app/helpers/condition_helper.rb
- app/javascript/spec/miq-condition/miq-condition-spec.js
- app/javascript/spec/miq-condition/miq-condition.data.js
- app/views/condition/show.html.haml
Control / Condition
Before
After
> Converting control condition list

- app/helpers/miq_alert_set_helper.rb
- app/javascript/spec/miq-alert-set/__snapshots__/miq-alert-set.spec.js.snap
- app/javascript/spec/miq-alert-set/miq-alert-set.data.js
- app/javascript/spec/miq-alert-set/miq-alert-set.spec.js
- app/views/miq_alert_set/show.html.haml
> Converting control alert-profiles list

- app/helpers/miq_event_definition_helper.rb
- app/javascript/spec/miq-event-definition/__snapshots__/miq-event-definition.spec.js.snap
- app/javascript/spec/miq-event-definition/miq-event-definition.data.js
- app/javascript/spec/miq-event-definition/miq-event-definition.spec.js
- app/views/miq_event_definition/show.html.haml
> Converting control events list

- app/javascript/components/performance-charts/areaChart.js
- app/javascript/components/performance-charts/helpers.js
- app/javascript/components/performance-charts/lineChart.js
Morphy pr for https://github.com/ManageIQ/manageiq-ui-classic/pull/8196
> [Morphy] Fix performance charts for pods

- bin/before_install
Core issue: https://github.com/ManageIQ/manageiq/pull/21843
> Update apt-cache before running apt-get install

- app/controllers/vm_cloud_controller.rb
- app/helpers/application_helper/button/volume_attach.rb
- app/helpers/application_helper/button/volume_detach.rb
- spec/helpers/application_helper/buttons/volume_attach_spec.rb
- spec/helpers/application_helper/buttons/volume_detach_spec.rb
part of https://github.com/ManageIQ/manageiq/pull/21841
> rename CloudVolume#attach_volume to attach

- spec/helpers/application_helper/buttons/volume_attach_spec.rb
Just put in a PR and missed these strange parens in the `let()`.
Wanted to fix this before I forgot
Not sure why they irk me so much but... here we are
> fixed cops

- package.json
- yarn.lock
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/8225
> Upgrade webpack-dev-server to 4.9.0

- package.json
- yarn.lock
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/8225
> [NAJDORF] Upgrade webpack dev server to 4.9.0 on najdorf

- package.json
- yarn.lock
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/8224
> Upgrade moment package to 2.29.2

- spec/controllers/catalog_controller_spec.rb
model update_attributes is deprecated
> convert update_attributes to update

- app/helpers/ops_helper.rb
- app/javascript/components/ansible-repository-form/index.jsx
- app/javascript/components/button-group/index.jsx
- app/javascript/components/cloud-object-store-container-form/index.jsx
- app/javascript/components/container-projects/chart-card.jsx
- app/javascript/components/dashboard-widgets/widget-wrapper/helper.jsx
- app/javascript/components/generic-objects-form/custom-button-form/index.jsx
- app/javascript/components/miq-pagination.jsx
- app/javascript/components/network-security-groups-form/index.jsx
- app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
- app/javascript/components/remove-generic-item-modal.jsx
- app/javascript/components/retirement-form/index.jsx
- app/javascript/components/routers-form/index.jsx
- app/javascript/components/vm-cloud-add-remove-security-group-form/index.jsx
- app/javascript/components/workers-form/helpers.jsx
- app/javascript/menu/group-switcher.jsx
- app/javascript/menu/search-results.jsx
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8289
Removes interpolation across various sections of code as these are not conductive to i18n, leading to problems with translation. 
EDIT: Also fixes "cannot modify frozen String" errors due to mo files being parsed into frozen strings that we were modifying in place
> Removing Interpolation across code (i18n) 

- app/helpers/ops_helper.rb
- app/javascript/components/ansible-repository-form/index.jsx
- app/javascript/components/miq-pagination.jsx
- app/javascript/components/network-security-groups-form/index.jsx
- app/javascript/components/retirement-form/index.jsx
- app/javascript/components/routers-form/index.jsx
- app/javascript/components/workers-form/helpers.jsx
- app/javascript/menu/group-switcher.jsx
- app/javascript/menu/search-results.jsx
Manual backport of #8293 to najdorf
Fixed conflicts from angular conversion that occurred on master but not on
najdorf
> [NAJDORF] Removing Interpolation across code (i18n) 

- app/javascript/components/generic-objects-form/custom-button-form/custom-button-form.schema.js
- app/javascript/components/generic-objects-form/custom-button-form/helper.js
- app/javascript/spec/custom-buttom-form/__snapshots__/custom-button-form.spec.js.snap
Refactored custom button form to use simple value for the isSearchable field to simplify submission code.
> Refactored custom button form

- app/views/miq_request/_request_dialog_details.html.haml
Links 
* https://github.com/ManageIQ/manageiq-automation_engine/issues/501
Before
------------
After
---------
> Multiselect option display issue

- spec/controllers/application_controller/ci_processing_spec.rb
- spec/controllers/application_controller/dialog_runner_spec.rb
- spec/controllers/catalog_controller_spec.rb
- spec/controllers/ops_controller/ops_rbac_spec.rb
- spec/controllers/vm_common_spec.rb
- spec/services/automate_import_service_spec.rb
https://github.com/rspec/rspec-mocks/issues 1460
> ruby 3 support: rspec-mocks 3.10.3 requires "with" to be explicit with hashes vs. kwargs

- app/controllers/cloud_network_controller.rb
- app/controllers/floating_ip_controller.rb
- app/controllers/security_group_controller.rb
- app/helpers/application_helper/button/cloud_network_new.rb
- app/helpers/application_helper/button/cloud_subnet_new.rb
- app/helpers/application_helper/button/floating_ip_new.rb
- app/helpers/application_helper/button/network_router_new.rb
- app/helpers/application_helper/button/network_service_entry_new.rb
- app/helpers/application_helper/button/network_service_new.rb
- app/helpers/application_helper/button/security_group_new.rb
- app/helpers/application_helper/button/security_policy_new.rb
- app/helpers/application_helper/button/security_policy_rule_new.rb
Only call supports? on non-nil objects.
> Handle nil return from class_by_ems

- app/javascript/components/physical-storage-form/validate-storage-credentials.jsx
- `app/models/miq_task.task_results` returns `nil` even when validation succeeds, since physical storage validation tasks don't get a `binary_blob` for some reason (while validate provider tasks do, for instance).
- `validateStorage` in `app/javascript/components/physical-storage-form/validate-storage-credentials.jsx` checked `task_result` and not `status` or `message`, and a comment explained this was because "the wait_for_task request can succeed with valid or invalid credentials with the message that the task is completed successfully. Based on the task_results we resolve() or reject() with an unknown error."
- this comment was copied from another object validation code (probably from validate provider), but it is not correct: invalid credentials or valid credentials for an already …
> Unknown error at physical storage validation:

- package.json
- yarn.lock
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/pull/8491
> Updating terser to 4.8.1

- package.json
- yarn.lock
Fixes https://github.com/ManageIQ/manageiq-ui-classic/pull/8490
> Updating d3-color

- app/javascript/components/host-initiator-form/host-initiator-form.schema.js
> Capitalize Field Title in Host Initiator Form

- app/helpers/catalog_helper.rb
- app/javascript/components/miq-custom-tab/index.jsx
- app/javascript/spec/miq-custom-tab/__snapshots__/miq-custom-tab.spec.js.snap
- app/javascript/spec/miq-custom-tab/miq-custom-tab.spec.js
- app/views/catalog/_form.html.haml
- app/views/catalog/_form_basic_info.html.haml
- app/views/catalog/_st_angular_form.html.haml
- app/views/layouts/angular/_multi_tab_ansible_form_options.html.haml
> Catalog edit page tabs convertion from HAML to react

- app/javascript/components/vm-resize-form/vm-resize-form.jsx
@miq-bot add-reviewer @alizapeikes 
@miq-bot add-label internationalization
> Exporting strings to be translated - Resize page

- app/helpers/vm_cloud_helper.rb
- app/helpers/vm_helper.rb
```
[----] D, [2022-11-07T15:40:18.135567 #21155:59678] DEBUG -- :   ExtManagementSystem Inst Including Associations (0.3ms - 1rows)
[----] D, [2022-11-07T15:40:18.136901 #21155:59678] DEBUG -- :   Rendered manageiq-ui-classic/app/views/layouts/_flash_msg.html.haml (Duration: 0.0ms | Allocations: 15)
[----] D, [2022-11-07T15:40:18.185347 #21155:59678] DEBUG -- :   Rendered manageiq-ui-classic/app/views/miq_request/_prov_wf.html.haml (Duration: 48.3ms | Allocations: 10654)
[----] D, [2022-11-07T15:40:18.185550 #21155:59678] DEBUG -- :   Rendered manageiq-ui-classic/app/views/miq_request/_prov_edit.html.haml (Duration: 48.8ms | Allocations: 10834)
[----] F, [2022-11-07T15:40:18.185699 #21155:59678] FATAL -- : Error caught: [ActionView::Template::Error] undefined method …
```
> Fix undefined method when publishing vm to template

- package.json
- yarn.lock
Adding onto https://github.com/ManageIQ/manageiq-ui-classic/pull/8516
> Bump minimatch from 3.0.4 to 3.1.2

- app/helpers/catalog_helper.rb
- app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
- app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
- app/javascript/spec/textual_summary/data/catalog_list.js
> Remove escape characters from Catalog helper

- app/javascript/spec/textual_summary/data/catalog_list.js
- app/javascript/spec/textual_summary/data/diagnostic_settings_list.js
- app/javascript/spec/textual_summary/data/miq_ae_class_list.js
- app/javascript/spec/textual_summary/data/miq_ae_policy_list.js
- app/javascript/spec/textual_summary/data/miq_alert_list.js
- app/javascript/spec/textual_summary/data/miq_policy_set_list.js
- app/javascript/spec/textual_summary/data/report_dashboard_list.js
Fixing space issues for the recently created PRs.
> Fix lint errors from data files

- app/javascript/oldjs/miq_application.js
- app/javascript/oldjs/miq_timeline.js
This pr  fixes a large number of eslint errors in some of the old .js files.
> Fixed Eslint Issues in Old JS Code

- app/controllers/dashboard_controller.rb
- app/controllers/report_controller.rb
- app/controllers/report_controller/reports.rb
- app/controllers/report_controller/saved_reports.rb
- app/helpers/dashboard_helper.rb
- app/helpers/data_table_helper.rb
- app/helpers/report_helper.rb
- app/stylesheet/legacy/miq_table_pdf.scss
- app/stylesheet/miq-data-table.scss
- app/views/layouts/_content.html.haml
- app/views/layouts/_report_html.html.haml
**List**
Before
Total values were not printed.
After
Total values can be seen now. 
But the pagination design had to be reverted to old design for now.
**Preview**
Before
After
**PDF Preview**
After
> Fix chargeback rates missing rows

- package.json
> Alphabetize the resolutions for better diffs

- README.md
> Update the copyright date

- app/javascript/components/dashboard-widgets/widget-wrapper/index.jsx
- app/javascript/components/dashboard_toolbar.jsx
- app/javascript/menu/first-level.jsx
- app/javascript/menu/group-switcher.jsx
- app/javascript/menu/menu-collapse.jsx
- app/javascript/menu/search.jsx
- app/javascript/menu/side-nav-menu-link.jsx
- app/javascript/menu/username.jsx
- app/javascript/spec/toolbar/__snapshots__/dashboard_toolbar.spec.jsx.snap
- app/javascript/spec/widget-wrapper/__snapshots__/widget-wrapper.spec.js.snap
- app/stylesheet/menu.scss
- app/views/layouts/_center_div_dashboard_no_listnav.html.haml
- app/views/layouts/_tabs.html.haml
Dashboard Page
**Before**
**After**
> Fix dashboard accessibility check violations

- app/views/shared/views/_prov_dialog.html.haml
- spec/controllers/application_controller/ci_processing_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/mixins/ems_common_spec.rb
- spec/presenters/tree_node/ext_management_system_spec.rb
- spec/presenters/tree_node/host_spec.rb
- spec/presenters/tree_node/vm_or_template_spec.rb
Related:
* https://github.com/ManageIQ/manageiq/pull/22279
> Drop SCVMM provider

- app/javascript/components/diagnostics-collect-log-form/schema.js
> Fix translation for settings collect log form title

- app/controllers/application_controller.rb
- app/controllers/mixins/actions/vm_actions/reconfigure.rb
- app/controllers/mixins/actions/vm_actions/resize.rb
- spec/controllers/application_controller_spec.rb
Include HTTP method, request id and PATH in the audit logs along with the original username and role name.
Some locations were redirecting but not logging and in many situations success was not logged at all.
This is what it looks like with the current code demonstrating logon failures, other requests that are successful and ones that are not due to missing product features.  Additionally, stale session is also shown:
```
[----] W, [2023-01-27T10:02:29.500256 #17089:5a398]  WARN -- audit: <AuditFailure> Username [blah], from: [Base.audit_failure], Authentication failed for userid blah
[----] I, [2023-01-27T10:02:36.633339 #17089:5a5dc]  INFO -- audit: <AuditSuccess> Username [admin], from: [Base.audit_success], User admin successfully validated by EVM
[----] I, [2023-01-27T10:02:36.636510 …
```
> Ensure success and failure audit logs are cut

- app/javascript/components/filter-dropdown/index.js
- app/javascript/components/miq-data-table/index.jsx
- app/javascript/components/miq-data-table/miq-table-cell.jsx
- app/javascript/components/miq-pagination.jsx
- app/javascript/menu/search.jsx
- app/javascript/spec/filter-dropdown/__snapshots__/filter-dropdown.spec.js.snap
- app/stylesheet/data-table.scss
- app/stylesheet/ddf_override.scss
- app/views/layouts/_center_div_with_listnav.html.haml
> Fix Services accessibility violations

- app/controllers/storage_resource_controller.rb
- app/helpers/storage_resource_helper/textual_summary.rb
- config/routes.rb
- spec/config/routes.pending.yml
> enhanced storage resource textual summary page

- app/javascript/packs/globals.js
- spec/javascripts/globals_pack_spec.js
Removing missed d3 require checks that were missed during https://github.com/ManageIQ/manageiq-ui-classic/pull/8562#issuecomment-1426466402
> Removing missed d3 require checks

- app/helpers/ops_helper.rb
- app/helpers/zones_helper.rb
- app/javascript/components/settings-zone/index.jsx
- app/javascript/packs/component-definitions-common.js
- app/stylesheet/miq-data-table.scss
- app/views/ops/_settings_list_tab.html.haml
> Settings zone list conversion from HAML to React

- app/javascript/components/schedule-form/schedule-form-fields.js
- app/javascript/spec/schedule-form/__snapshots__/schedule-form.spec.js.snap
> Fixing a Typo

- app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
- app/javascript/spec/cloud-object-store-container-form/__snapshots__/cloud-object-store-container-form.spec.js.snap
- app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
- app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
- app/javascript/spec/vm-floating-ips-form/__snapshots__/vm-floating-ips-form.spec.js.snap
- yarn.lock
@miq-bot add_reviewer @DavidResende0
@miq-bot add_reviewer @akhilkr128
> Regenerated yarn.lock file

- app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
- after completing issue https://github.com/ManageIQ/manageiq-ui-classic/issues/8616, a user will be able to create a service without attaching it to resources (a service-resource-attachment field will be added to service create in the future, but might not be mandatory). 
- in volume create basic mode, a user might then choose this resource-less service and request to create a new volume for it. 
- this will raise an error in the backend, and so better be blocked in the frontend. 
- this PR is based on changes from PR: #8623 and requires completion of issue https://github.com/ManageIQ/manageiq-providers-autosde/issues/202, because currently storage-service-resource-attachments are not collected, and so all storage services return an empty array from their `storage_resources` api …
> volume create basic mode: validate chosen service has attached resources

- app/controllers/application_controller.rb
**Before**
While visiting the below URL's which do not have proper authorization, we get an error like below -
```
1. /utilization#/
2. /optimization/show_list#/
3. /catalog/explorer#/
4. /ansible_playbook/show_list#/
5. /ansible_repository/show_list#/
6. /ansible_credential/show_list#/
7. /miq_ae_tools/resolve#/
8. /miq_ae_tools/import_export#/
9. /miq_policy_rsop#/
10. /miq_policy_export#/
11. /miq_policy_log#/
12. /configuration/index#/ RBAC bug
13. /miq_task/index?jobs_tab=tasks#/
```
**After**
> Fix forbidden pages notification

- app/javascript/components/schedule-form/helper.js
- app/javascript/components/schedule-form/index.jsx
- app/javascript/components/schedule-form/schedule-form-fields.js
- app/javascript/spec/schedule-form/__snapshots__/schedule-form.spec.js.snap
Before
--------------
https://user-images.githubusercontent.com/16753936/224530513-0092d414-9cd1-4646-9178-731336979885.mov
After
---------------
https://user-images.githubusercontent.com/16753936/224530551-fdaca35f-c93e-42bd-b7f7-c9e3c032ba73.mov
Links
* [Parent PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/8606) 
Settings -> Application Setttings -> Schedules from explorer
> Fixed bug in schedule form

- .github/workflows/ci.yaml
- Rakefile
> Try to catch ui classic security issues before they're merged

- app/javascript/menu/main-menu.jsx
Before
https://user-images.githubusercontent.com/87487049/226815203-0bce583a-a14e-4969-898e-73e66554d429.mov
After
https://user-images.githubusercontent.com/87487049/226814565-1784761e-1feb-49bf-bd07-e6ef86e6353a.mov
> Toggle primary nav menu item

- app/helpers/miq_template_helper.rb
- app/helpers/miq_template_helper/textual_summary.rb
- app/helpers/placement_group.rb
Remove empty, duplicated, or incorrectly split up files.
These were all detected using the zeitwerk loader but are fully backward compatible with our current loader.
> Remove empty, duplicated, or incorrectly split up files.

- app/controllers/host_initiator_group_controller.rb
- app/controllers/mixins/ems_common.rb
- app/helpers/application_helper/listnav.rb
- app/helpers/application_helper/toolbar/host_initiator_group_center.rb
- app/helpers/application_helper/toolbar/host_initiator_groups_center.rb
- app/helpers/application_helper/toolbar/storage_services_center.rb
- app/javascript/components/host-initiator-group-form/editing-context.js
- app/javascript/components/host-initiator-group-form/host-initiator-group-form.schema.js
- app/javascript/components/host-initiator-group-form/index.jsx
- app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
- app/views/host_initiator_group/edit.html.haml
- config/routes.rb
see issue https://github.com/ManageIQ/manageiq-ui-classic/issues/8640
Before changes:
After changes:
> add delete and update to host initiator groups

- app/controllers/storage_resource_controller.rb
- app/controllers/storage_service_controller.rb
Marks Page Label Strings for Translation in the Storage Services and Storage Resources Pages
Before:
After:
> Marked Strings For Translation in Storage Services/Resources Pages

- app/helpers/ops_helper.rb
- app/helpers/settings_zone_list_helper.rb
- app/views/ops/_diagnostics_zones_tab.html.haml
Before :
After:
Here I've reused the components of SettingsZoneListHelper for diagnostics zone list, since both are same.
> diagnostics zone list conversion from HAML to React

- app/controllers/mixins/ems_common.rb
- app/controllers/storage_service_controller.rb
- app/helpers/application_helper/toolbar/storage_service_center.rb
- app/helpers/application_helper/toolbar/storage_services_center.rb
- app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
- app/javascript/components/storage-service-form/index.jsx
- app/javascript/components/storage-service-form/storage-service-form.schema.js
- app/views/storage_service/edit.html.haml
- config/routes.rb
belongs to issue: #8728
adds editing/update to storage service form with required changes to helpers and controllers
https://user-images.githubusercontent.com/106743023/228462944-52cad07c-60e6-4942-8c4e-3d4a8aa8fb28.mov
> Storage service update

- app/javascript/spec/helpers/miq_formatters_helper.js
- app/javascript/spec/helpers/old_js_file_require_helper.js
- app/javascript/spec/helpers/set_fixtures_helper.js
- app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js
- app/javascript/spec/remove-generic-item-modal/remove-generic-item-modal.spec.js
> Fix for failing specs after the node upgrade

- app/helpers/ops_helper.rb
- app/helpers/ops_helper/role_rbac_details_helper.rb
- app/views/ops/_rbac_role_details.html.haml
> Role rbac summary conversion

- app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
- app/javascript/spec/textual_summary/data/table_list_view.js
- app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
- app/javascript/spec/textual_summary/tests/table_list_view.test.js
Fixing snapshots for the the TableListView component's test cases.
Related PR - https://github.com/ManageIQ/manageiq-ui-classic/pull/8779
> Fix snapshots for TableListView component

- app/helpers/ops_helper/textual_summary.rb
- app/javascript/components/miq-structured-list/index.jsx
- app/javascript/components/textual_summary/table_list_view.jsx
- app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
- app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
- app/javascript/spec/textual_summary/data/table_list_view.js
- app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
- app/views/ops/_rbac_tenant_details.html.haml
The PR fixes the snapshot for TableListView component for `Petrosian`
Related PR
- https://github.com/ManageIQ/manageiq-ui-classic/pull/8779
- https://github.com/ManageIQ/manageiq-ui-classic/pull/8785
> [PETROSIAN] Fixing snapshots for TableListView component

- app/javascript/components/search-bar/index.jsx
- app/javascript/spec/search-bar/__snapshots__/search-bar.spec.js.snap
**Before**
Sometimes, the results were not populated as expected when we search items from the `SearchBar` component
Note: Couldn't really replicate the issue in local env, but had replicated (rarely) in the reported environment.
**After**
Had refactored the code to fix this problem.
> Fix for timing issues in search bar component

- app/controllers/application_controller.rb
part of https://github.com/ManageIQ/manageiq/pull/22520
> drop Vmdb::GlobalMethod#column_type

- app/views/layouts/_tabs.html.haml
- cypress.json
- cypress/integration/ui/gtl.spec.js
- cypress/integration/ui/login.spec.js
- cypress/integration/ui/menu.spec.js
- cypress/integration/ui/searchbox.spec.js
- cypress/integration/ui/settings.spec.js
- cypress/integration/ui/toolbar.spec.js
- cypress/support/assertions/expect_title.js
- cypress/support/commands/explorer.js
- cypress/support/commands/gtl.js
- cypress/support/commands/login.js
- cypress/support/commands/menu.js
- cypress/support/commands/search.js
- cypress/support/commands/toolbar.js
- spec/controllers/orchestration_stack_controller_spec.rb
Fixed cypress lint issues and menu tests.
> Initial cypress fix

- app/views/layouts/_tabs.html.haml
- cypress.config.js
- cypress/e2e/ui/menu.cy.js
Added menu item cypress tests for all menu items to ensure that they all lead to non error screens.
> Added menu item tests to check for non error screens

- app/javascript/components/provider-form/index.jsx
This change fixes an issue introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/8719 by simply rearranging some of the provider form code so that the `validateName` function can take advantage of the `providerId`. This ensures that the form only checks for duplicate provider names when adding a new provider and not during an edit which prevented you from saving the form.
> Fixed Provider Edit Form Preventing You From Saving Without Changing The Name

- cypress/e2e/ui/menu.cy.js
Fixes the broken/missing menu item test cases and addresses the feedback in pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8813
> Fixed missing menu tests

- cypress/e2e/ui/searchbox.cy.js
- cypress/support/commands/search.js
Fixed the current searchbox cypress tests and added some new searchbox cypress tests.
> Fix searchbox cypress tests

- cypress/e2e/ui/login.cy.js
> Add logout cypress test

- cypress/e2e/ui/searchbox.cy.js
Updated searchbox tests for consistent naming style and fixed the failing menu search test.
> Update searchbox tests

- app/javascript/components/miq-data-table/miq-table-cell.jsx
- app/stylesheet/miq-data-table.scss
Followup to https://github.com/ManageIQ/manageiq-ui-classic/pull/8825
Catalog Items
Before
After
Container Images
Before
After
Containers
Before
After
Vms and Templates
Before
After
Automation Providers
Before
After
DataStores
Before
After
> Enhance data tables to fix minor alignments issues

- app/controllers/ops_controller/ops_rbac.rb
- app/helpers/ops_helper/role_rbac_details_helper.rb
- app/views/ops/_rbac_role_details.html.haml
Related to:
- ManageIQ/manageiq#22573
- ManageIQ/manageiq#22613
- ManageIQ/manageiq-schema#697
> Separate role access restrictions for catalog items

- cypress/e2e/ui/Overview/dashboard.cy.js
Added tests for the Overview > Dashboard page. Tests check if page loads correctly, all default widgets load, reset to default widgets works, add a widget works, minimize, zoom in, refresh buttons work and the remove widget button works. All tests passing on Chrome, Edge and Firefox.
> Added Overview > Dashboard Cypress tests

- package.json
- yarn.lock
Updated cypress version to latest version.
> Update cypress version

- cypress/e2e/ui/Overview/dashboard.cy.js
Fixed failing dashboard tests and refactored tests to make them less dependent on each other.
> Fixed dashboard tests

- app/views/chargeback_assignment/_form.html.haml
> Fix overview->assignments accessibility check violation

- .github/workflows/cypress.yaml
- Rakefile
- bin/before_install
- bin/setup
> Add Cypress to GitHub Actions

- app/javascript/components/carbon-charts/helpers.js
- app/javascript/components/performance-charts/areaChart.js
- app/javascript/components/performance-charts/lineChart.js
Same change as https://github.com/ManageIQ/manageiq-ui-classic/pull/8802 but for Morphy. Resolves the morphy/conflict that was occurring in the master pr.
> [MORPHY] Fix Data/X-Axis Display Issue in Performance Charts

- .github/workflows/ci.yaml
- .github/workflows/cypress.yaml
Update GitHub Actions versions
> Update GitHub Actions versions

- lib/tasks/manageiq/ui_tasks.rake
- package.json
- yarn.lock
Related to https://github.com/ManageIQ/manageiq-rpm_build/pull/409
> Lock down es-abstract to avoid build issues on s390x

- app/helpers/miq_ae_class_helper.rb
- app/views/miq_ae_class/_method_inputs.html.haml
Before:
After:
The code mirror conversion will be carried out in a separate PR
> Automate first user summary conversion from Haml to React

- cypress/e2e/ui/Overview/Chargeback/rates.cy.js
- cypress/support/assertions/expect_text.js
- cypress/support/e2e.js
Added Cypress tests for the chargeback rates page.
> Add chargeback rates cypress tests

- app/helpers/miq_ae_class_helper.rb
- app/views/miq_ae_class/_method_inputs.html.haml
Automate first_user_summary method has been renamed to method_details
no notable ui changes
> Renamed first_user_summary to method_details

- app/stylesheet/miq-structured-list.scss
> Enhance smart management presentation

- .github/workflows/ci.yaml
- .github/workflows/cypress.yaml
Update actions/checkout version to v4
> Update actions/checkout version to v4

- lib/tasks/manageiq/ui_tasks.rake
> Remove the s390x hack now that we are on yarn4

- app/javascript/components/ansible-playbook-workflow/index.jsx
- app/javascript/spec/ansible-playbook-workflow/__snapshots__/ansible-playbook-workflow.spec.js.snap
- app/javascript/spec/ansible-playbook-workflow/ansible-playbook-workflow.data.js
This PR refactors the test cases and corrects a typo in https://github.com/ManageIQ/manageiq-ui-classic/pull/8938
> Refactoring the test cases for the ansible-playbook-workflow

- app/controllers/miq_task_controller.rb
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8977
Before:
After:
> Fix tasks permission issue

- app/javascript/components/reconfigure-vm-form/reconfigure-form-fields.js
- app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
> Fix multiple vm reconfigure schema error

- app/javascript/spec/workflow-credential-mapping-form/__snapshots__/workflow-credential-mapping-form.spec.js.snap
Fixed failing Quinteros snapshot specs.
> [Quinteros] Fix failing snapshot specs

- app/controllers/application_controller.rb
- app/stylesheet/carbon.scss
- app/views/layouts/application.html.haml
Fix morphy charts download as jpg and png.
Based on this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8227.
Depends on: https://github.com/ManageIQ/manageiq/pull/22812
> [MORPHY] Fix morphy charts download

- app/helpers/miq_ae_class_helper.rb
- app/javascript/components/miq-structured-list/miq-structured-list-body/value-types/miq-structured-list-array.jsx
- app/views/miq_ae_class/_embedded_methods.html.haml
> Embedded methods list conversion from HAML to React

- manageiq-ui-classic.gemspec
> Allow rails 7 gems in gemspec

- cypress/README.md
- cypress/e2e/ui/Overview/Chargeback/rates.cy.js
- cypress/e2e/ui/Overview/dashboard.cy.js
- cypress/support/commands/toolbar.js
Fixed the Cypress Toolbar helper functions and updated the documentation for these functions. Also implemented these functions in the rates and dashboard tests where needed.
> Fix cypress toolbar helper functions

- .github/workflows/ci.yaml
- .github/workflows/cypress.yaml
- .github/workflows/yarn_lock.yaml
> Update GHA versions

- app/javascript/components/notification-drawer/notification-drawer.jsx
- app/javascript/spec/notification-drawer/__snapshots__/notification-drawer.spec.js.snap
- app/stylesheet/notifications.scss
> Beautify the NotificationDrawer component

- app/presenters/widget_presenter.rb
Add noopener noreferrer to blank targets
(cherry picked from commit faa1b8bf2ff491da387bc19cade3ad3ca9d2202e)
Manual backport of #9068 
@DavidResende0 or @GilbertCherrie Please review.
> [MORPHY] Add noopener noreferrer to blank targets

- app/javascript/oldjs/controllers/live_metrics/util/metrics-parse-url-factroy.js
@DavidResende0 Please review.
This code is deleted since najdorf, so this just removes the unnecessary regex.
> [MORPHY] Remove unnecessary regex

- app/controllers/catalog_controller.rb
- app/controllers/mixins/automation_mixin.rb
- app/javascript/oldjs/miq_application.js
- config/routes.rb
- product/views/ManageIQ_Providers_Workflows_AutomationManager_Workflow.yaml
- spec/config/routes.pending.yml
Noticed a typo while looking at other embedded automation_managers
Related:
* https://github.com/ManageIQ/ui-components/pull/488
> Fix Embededded Typos

- app/controllers/condition_controller.rb
- app/controllers/miq_action_controller.rb
- app/controllers/miq_alert_controller.rb
- app/controllers/miq_alert_set_controller.rb
- app/controllers/miq_event_definition_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/miq_policy_set_controller.rb
Added search bars to the control list pages.
Before:
After:
> Added search bars to control pages

- package.json
- yarn.lock
> Update ui components to 1.6.0

- app/javascript/components/workers-form/workers-form.jsx
- app/javascript/components/workers-form/workers.schema.js
- app/javascript/components/workers-form/workers.style.scss
> Fix workers form style

- app/javascript/components/data-tables/optimization/helper.js
- app/javascript/helpers/custom-click-handler.js
Before
https://github.com/ManageIQ/manageiq-ui-classic/assets/87487049/b3a28df2-56ba-4e63-a51f-90f7ab779272
After
> Fix Optimization Queue Report

- app/javascript/spec/c-and-u-collections-form/__snapshots__/c-and-u-collections-form.spec.js.snap
- app/javascript/spec/c-and-u-collections-form/c-and-u-collections-form.spec.js
`yarn run jest -t 'DiagnosticsCURepairForm' --testPathPattern app/javascript/spec/c-and-u-collections-form/c-and-u-collections-form.spec.js`
Before
```
PASS  app/javascript/spec/c-and-u-collections-form/c-and-u-collections-form.spec.js
DiagnosticsCURepairForm Component
✓ Should render a new DiagnosticsCURepair form (59ms)
✓ Should add a record from DiagnosticsCURepair form (102ms)
Warning: An update to DiagnosticsCURepairForm inside a test was not wrapped in act(...).
act(() => {
});
This ensures that you're testing the behavior the user would see in the browser. Learn more at …
```
> Fix DiagnosticsCURepairForm test

- app/javascript/components/vm-resize-form/vm-resize-form.jsx
- app/javascript/spec/vm-resize-form/vm-resize-form.spec.js
> Cleanup VmResize component and fix lint errors

- app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
- app/javascript/spec/host-initiator-group-form/host-initiator-group.spec.js
`yarn run jest -t 'Host Initiator Group Form' --testPathPattern app/javascript/spec/host-initiator-group-form/host-initiator-group.spec.js`
Before
```
PASS  app/javascript/spec/host-initiator-group-form/host-initiator-group.spec.js
Host Initiator Group Form 
✓ Loads data and renders  (241ms)
✓ Calls miqRedirectBack when canceling create form (43ms)
console.warn node_modules/fetch-mock/src/lib/fetch-handler.js:96
Unmatched GET to /api/host_initiator_groups?expand=resources&attributes=name
Warning: An update to FormSpy inside a test was not wrapped in act(...).
act(() => {
}); …
```
> Fix HostInitiatorGroupForm test

- spec/config/routes.pending.yml
Fix failing embedded terraform rbac specs.
> Fix failing terraform rbac specs

- package.json
- yarn.lock
Updated lodash version to 4.17.21.
> Update lodash to 4.17.21

- package.json
- yarn.lock
> Update moment to 2.29.2 through resolution

- spec/controllers/application_controller/automate_spec.rb
> Fix automate specs

- .yarnrc.yml
cc @GilbertCherrie 
Needed before merge of https://github.com/ManageIQ/manageiq/pull/23098
> Add known pending package security issues to a pending list

- package.json
- yarn.lock
Pint minimist to version 1.2.6.
> [Morphy] Update minimist

- package.json
- yarn.lock
Pin tough-cookie package to 4.1.3.
> [Morphy] Upgrade tough cookie to 4.1.3

- app/javascript/components/AeInlineMethod/NamespaceSelector.jsx
- app/javascript/components/AeInlineMethod/index.jsx
Fixed translation issues found in this pr: https://github.com/ManageIQ/manageiq/pull/23055
> Fix translation issues

- app/controllers/miq_ae_class_controller.rb
Fixed a bug with the AE Method Summary screen for Ansible Workflow Templates where the summary page and edit method screen did not show the selected Provider and Ansible Workflow Template values.
Before:
After:
> Fix ae method workflow template summary page

- spec/controllers/dashboard_controller_spec.rb
Follow up to #9295. If we revert that PR's changes, and run these tests they fail when it tries to Marshal.dump the params internal IO object.
Note that the actual failure in test is slightly different from prod. In test we get `TypeError: no _dump_data is defined for class StringIO` because the TestRequest has a StringIO internally. In prod we get `can't dump IO` because the real request has a real IO object internally. Even so, this test still demonstrates the Marshal issue, while also providing an end-to-end test for external auth login.
Note that this new test is exercising a previously untested path, and thus adds a new warning to CI that we hadn't seen before (but which did show up in production):
``` …
```
> Add external auth spec

- .yarnrc.yml
- Rakefile
> Update the npmAuditExcludePackages due to package updates

- package.json
- yarn.lock
> [Morphy] Update lodash to 4.7.21

- package.json
- yarn.lock
Update babel/traverse to ~7.26.7
> [Morphy] Update babel/traverse

- package.json
- yarn.lock
Update moment through resolutions similar to this pr on master: https://github.com/ManageIQ/manageiq-ui-classic/pull/8259. Moment is being pulled in from angular-patternfly which we can not update so we need to update moment through the resolutions.
> [Morphy] Update moment

- package.json
- yarn.lock
> [Morphy] Update jquery UI

- yarn.lock
Update ua-parser-js package in yarn.lock.
> [Morphy] Update ua_parser_js

- .gitattributes
Provide instructions to install and enable gron for human friendly json differences.
I used gron to review #9366 and found it easy to setup and use.
[skip ci]
> Update json differ to use gron

- .gitattributes
Speed up repeated diffs using caching
See https://git-scm.com/docs/gitattributes
[skip ci]
> Add cachetextconv to instructions

- app/javascript/components/search-bar/index.jsx
- app/javascript/spec/search-bar/__snapshots__/search-bar.spec.js.snap
Fix issue with searchbar formtoken.
> Fix searchbar formtoken issue

- package.json
- yarn.lock
Update lodash to 4.7.21
@miq-bot add-label dependencies
> Update lodash to 4.7.21

- app/helpers/catalog_helper/textual_summary.rb
Fix display issue for multi-select tags on the catalog item page.
Before:
After:
> Fix catalog item tags

- app/controllers/application_controller.rb
Did an org-wide search and it's not used: https://github.com/search?q=org%3AManageIQ+local_request+NOT+repo%3AManageIQ%2Frails&type=code
> Remove unused method

- app/services/cloud_tenant_dashboard_service.rb
- app/services/ems_dashboard_service.rb
Minor change...
Just wanted to use https://github.com/rails/rails/blob/main/activerecord/lib/arel.rb#L52
> Use Arel.sql to statically cast sql

- .github/workflows/ci.yaml
- package.json
Part of https://github.com/ManageIQ/manageiq/issues/23425
Update minimum node version to 20.19.1
> Update minimum node version to 20.19.1

- app/helpers/configuration_script_helper.rb
If not all properties of a `configuration_script` were present this page was throwing an exception.
> Fix configuration_script/show record with missing values

- cypress/e2e/ui/Automation/Embedded-Automate/Explorer/class.cy.js
> Fix cypress tests to reflect new FQ name format

- app/controllers/catalog_controller.rb
Depends on:
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/9430
> Use ServiceTemplate.available_managers for AWX/Ansible Tower

- app/controllers/vm_common.rb
- app/helpers/js_helper.rb
cc @jrafanie 
org wide search for callers: https://github.com/search?q=org%3AManageIQ%20partial_replace&type=code
> Inline a singly-used helper into vm_common

- spec/controllers/catalog_controller_spec.rb
Add test coverage that would have caught https://github.com/ManageIQ/manageiq/pull/23448
> Add tests for CatalogController#set_form_vars

- app/controllers/catalog_controller.rb
- app/views/catalog/_form_basic_info.html.haml
Depends on:
Cross-repo tests:
* https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/961
> Add terraform enterprise catalog support

- cypress/e2e/ui/Overview/reports.cy.js
> Fix report cypress tests

- cypress.config.js
When developing and testing, any failures should fail and not be retried.
> Don't run with retries in cypress open mode

- cypress/e2e/ui/Settings/Application-Settings/edit_collect_logs.cy.js
CP4AIOPS-16166
Pr that adds cypress tests for Collect logs edit form which is present in 2 flows:
1) Settings > Application Settings > Diagnostics > Manage IQ Region > Zone > Server > Collect logs > Edit
2) Settings > Application Settings > Diagnostics > Manage IQ Region > Zone > Collect logs > Edit
- Validates cancel button behaviour
- Validates reset button behaviour
- Validates save button behaviour
Tests executed across browsers:
@miq-bot assign @GilbertCherrie @jrafanie 
> Added automated tests with cypress for Collect-logs edit form

- yarn.lock
Update semver packages in yarn.lock
> [Morphy] Update semver packages

- package.json
- yarn.lock
Updated minimatch to ~5.1.6 using resolutions like on master in these 2 prs, https://github.com/ManageIQ/manageiq-ui-classic/pull/8524 and https://github.com/ManageIQ/manageiq-ui-classic/pull/9488.
> [Morphy] Update minimatch

- package.json
- yarn.lock
> [Morphy] Update ip

- package.json
- yarn.lock
Use resolutions to update form-data package to ~3.0.4
> [Morphy] Update form-data

- yarn.lock
Update got package using yarn.lock
> [Morphy] Update got

- package.json
- yarn.lock
Update bootstrap using resolutions to ~3.4.1
> [Morphy] Update bootstrap morphy
