- spec/services/physical_infra_topology_service_spec.rb
This changed because of https://github.com/ManageIQ/manageiq/pull/18266,
just making sure the tests are green again.
Fixes red travis: (tracking issue https://github.com/ManageIQ/manageiq-ui-classic/issues/4921#issuecomment-451129620)
https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/474623058
```
1) PhysicalInfraTopologyService#build_topology topology contains the expected structure and content
Failure/Error:
expect(subject[:items]).to eq(
"PhysicalInfraManager" + ems.id.to_s  => {
:name         => ems.name,
:kind         => "PhysicalInfraManager",
:miq_id       => ems.id,
:status       => nil,
:display_kind => "Lenovo",
:model        => ems.class.name,
:key          => "PhysicalInfraManager" + ems.id.to_s
},
expected: {"PhysicalInfraManager96000000000077"=>{:name=>"LXCA", …
```
> PhysicalInfraTopologyService spec - expect manager to have Valid status, not nil

- app/controllers/service_controller.rb
- spec/controllers/service_controller_spec.rb
Updated right cell header to be consistent with tree node and Service summary screen
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1658906
before:
after:
> Updated right cell header

- app/controllers/mixins/actions/vm_actions/ownership.rb
Right now, clicking the Set Ownership button on a nested list of images under a cloud provider redirects to `/vm/ownership`.
But image is not a vm, it's a template, so the url should be `/miq_template/ownership`.
The difference causes 2 bugs:
* no form buttons are shown
* affected items shows No records found
Fixing to use miq_template.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650507
---
Looks like this was a bug, because in the nearest `elsif`, we're already checking whether `params[:display]` matches `images`, so it was probably *also* in the vm list by mistake.
> [HAMMER] set_ownership - use miq_template (not vm) for images

- app/javascript/components/cloud-tenant-form/create-form-schema.js
- app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650484
The prior version of this labeled the field "Cloud Provider", but the
actual field content includes both cloud providers and cloud tenants
within the provider, to support hierarchical cloud tenants.
This commit updates the field label to be more accurate.
> Bug 1650484: Update misleading form label for new Cloud Tenant form

- app/controllers/report_controller/schedules.rb
Sorry, my cut-n-paste was probably bad when I was renaming the deprecated `towhat` stuff. This is a partial revert that fixes the issue.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5131
> Fixed regression on schedules screen due to bad towhat refactoring

- app/views/miq_request/_request_dialog_details.html.haml
- app/views/miq_request/_st_prov_show.html.haml
This PR simplifies the `st_prov_show.html.haml` from going into `dialog_provision.html.haml` which further down does a bunch of calculations based on the dialog and then can sometimes run automate depending on the field. All it really needs to do is display the values that the user picked during ordering.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1663049
/cc @tinaafitz 
@miq-bot add_label bug, hammer/yes, gaprindashvili/yes
> Remove logic for request screen dialogs

- spec/helpers/application_helper/buttons/basic_spec.rb
cover behaviour for the button introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/5123
> Add spec for button tenant manage quota in OpsController

- app/helpers/ems_infra_helper.rb
- app/views/ems_infra/scaling.html.haml
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1480819
This commit changes the labels on the Scale Infrastructure Provider form
from the user-unfriendly parameter names (i.e. "ControllerCount") to
more descriptive labels (i.e. "Number of Controller Hosts").
> Bug 1480819: Fix labels for Scale Infrastructure Provider form

- app/javascript/components/dual-list-select/helpers.jsx
- app/javascript/components/dual-list-select/index.jsx
- app/javascript/components/dual-list-select/list.jsx
- app/javascript/forms/data-driven-form.jsx
- app/javascript/forms/mappers/formsFieldsMapper.jsx
- app/javascript/spec/dual-list-select/__snapshots__/dual-list-select.spec.js.snap
- app/javascript/spec/dual-list-select/dual-list-select.spec.js
- app/javascript/spec/dual-list-select/helpers.spec.js
- app/javascript/spec/helpers/fieldProvider.js
**What**
**A React component** which will take place in all **react data-driven forms**, where dual list select is used.
(eg.: Services/Catalogs/Catalogs/Add a new catalog, Workloads/VM/Edit, etc.)
**Before**
**After**
Customization: 
- Move all to right/left buttons
- Titles of buttons
- Headers of lists
- IDs, etc.
**Checklist**
(Should be added to guides? And I think we should create some kind of guide for converting old forms to data-driven format.)
**Props**
| Props  | Type | Default |  Decription |
| ------------- | ------------- | ------------- | ------------- |
| leftId  | string  | undefined  | ID passed to left select  |
| rightId  | string  | undefined  | ID passed to right select  |
| leftTitle  | string  | undefined  | Title above left select  |
| rightTitle  | string  | …
> Adds dual list react component

- app/controllers/ops_controller/ops_rbac.rb
- spec/helpers/application_helper/buttons/basic_spec.rb
fix displaying menu "Manage Tenant Quota" from https://github.com/ManageIQ/manageiq-ui-classic/pull/5123
`params[:id]` has format `"tn-ID"` **(not `"tn_ID"`)**
method 
`TreeBuilder.extract_node_model_and_id(params[:id].to_s)`
returns `id` in second element:
`TreeBuilder.extract_node_model_and_id("tn-33333")`
returns
`[nil,"33333", "tn"]`
and we had case written with `'_'` in [specs](https://github.com/ManageIQ/manageiq-ui-classic/pull/5129) 
Links
-----
* https://github.com/ManageIQ/manageiq-ui-classic/pull/5129
* https://github.com/ManageIQ/manageiq-ui-classic/pull/5123
* https://bugzilla.redhat.com/show_bug.cgi?id=1468795
> Fix usage of TreeBuilder.extract_node_model_and_id in OpcControler

- app/assets/javascripts/components/generic_object/main-custom-button-group-form.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1534539
Automation -> Automate -> Generic Object -> select a button group with button(s) in tree-> Edit it -> Save -> see what happens to the tree after saving the group
Make sure that button group has buttons in the tree before editing. Once ordering is lost during editing it's lost for good.
Before:
After:
@miq-bot add_label bug, hammer/yes, gaprindashvili/yes, automation/automate, generic objects
> Send button_order via API

- app/controllers/application_controller/miq_request_methods.rb
Compute -> clouds -> providers -> select cloud_provider(Openstack/Amazon) -> instances -> lifecycle -> provision instances
(or go to `/miq_request/pre_prov?template_klass=cloud` directly)
there is a GTL with a list of templates,
but thanks to `@in_a_form = true` (and `center_div_no_listnav` checking both `layout_uses_paging? && !@in_a_form`),
that means no paging toolbar.
That was correct when this was not using the GTL component but no longer, removing.
(The screen was converted to use GTL in https://github.com/ManageIQ/manageiq-ui-classic/pull/4509, adding hammer/yes.)
Cc @PanSpagetka 
Cc @Pratik1Awchat
(A workaround for this is running `$('#paging_div').show(); miqInitMainContent()` in the browser console on that screen.)
> Fix missing paging in provisioning template selection

- app/views/generic_object_definition/_show_actions.html.haml
- app/views/generic_object_definition/_show_custom_button_group.html.haml
- app/views/generic_object_definition/_table_button.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1665031
Automate -> Automation -> Generic Object
**See that sort in tree and table is different.**
For ButtonGroup you may need to change it's `set_data[:button_order]` to see difference.
For Action add few unassigned button and last one that you add should be with name that should be at the start of the list.
Before:
After:
@miq-bot add_label bug, generic objects, automate/automation, hammer/yes, gaprindashvili/yes, bugzilla needed
> Unify sorting in GOD page

- app/controllers/application_controller/performance.rb
- app/controllers/host_controller.rb
- app/controllers/vm_controller.rb
- app/helpers/application_helper.rb
Don't show `Check All` checkbox when navigating to VM list from chart
https://bugzilla.redhat.com/show_bug.cgi?id=1647230
1.Manage an infra provider.Enable C&U for the provider.
2.Navigate to the summary page of a host.Click Monitoring, click Utilization.
3.Drill into any of the charts(memory, cpu etc), by clicking on a data point.
4.Select 'Display' menu, click 'VMs that were running'
> Dont show gtl checkbox when display list from chart click

- app/controllers/ops_controller/settings/common.rb
- app/views/ops/_settings_workers_tab.html.haml
Parent issue: https://github.com/ManageIQ/manageiq/issues/18300
Core PR: https://github.com/ManageIQ/manageiq/pull/18337
Schema: https://github.com/ManageIQ/manageiq-schema/pull/319
@miq-bot add_label hammer/no, pending core
> Rename WebsocketWorker to RemoteConsoleWorker

- app/controllers/pxe_controller.rb
Commit 635e85fa3a1cd2bc9ceeb8e7ca943d325aabb3e1 replaced @pages[:item] == 0 with @pages[:item].zero? on line 194 as suggested by Rubocop, but unfortunately those two snippets are not functionally equal if the @pages does not have an :items key.
This commit just ensures that the missing key scenario is properly handled.
> Properly handle non-existent hash key

- app/controllers/report_controller.rb
- app/views/report/_export_custom_reports.html.haml
**Before:** 
We unconditionally overrided `user_id` and `miq_group_id` fields of imported report with value for user who is doing import. 
**After:** 
`Preserver owner?` checkbox is controlling if we need to work in old way (override) or preserve `user_id` and `miq_group_id` from imported report
Depends on https://github.com/ManageIQ/manageiq/pull/18270
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1638533
@miq-bot add-label enhancement , cloud intel/reporting, pending core
\cc @gtanzillo
> Added "Preserve owner?" checkbox on Import report screen 

- app/controllers/dashboard_controller.rb
- app/controllers/report_controller.rb
- app/controllers/report_controller/dashboards.rb
- app/helpers/application_helper.rb
- app/helpers/application_helper/button/dashboard_delete.rb
- app/helpers/application_helper/toolbar/miq_widget_set_center.rb
- app/helpers/application_helper/toolbar_chooser.rb
- app/views/report/_db_form.html.haml
- app/views/report/_db_list.html.haml
- app/views/report/_db_widget_remove.html.haml
- app/views/report/_db_widgets.html.haml
- spec/controllers/miq_report_controller/dashboards_spec.rb
- spec/helpers/application_helper/buttons/dashboard_delete_spec.rb
- spec/views/report/_db_widget_remove.html.haml_spec.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5153
Go to CI > Reports > accordion Schedules
switch to accordion Dashboards (without going through schedules, I can't reproduce it consistently),
click on a dashboard
At some point, the right side will start rendering nonsense - for example "Choose a Schedule to view from the menus on the left." (even when we're in the dashboard accordion), and there will be an exception:
```
FATAL -- : Error caught: [NoMethodError] undefined method `read_only' for nil:NilClass
```
(or possibly `Error caught: [NoMethodError] undefined method ``first' for nil:NilClass` but I can't reproduce that one)
That's caused by the toolbar button depending on `@db` being set to a specific dashboard instance, whcih is not true when the tree root is …
> Dashboard (under Reports) - fix broken accordion_select; use @dashboard, not @db

- app/controllers/ems_cloud_controller.rb
- app/controllers/ems_container_controller.rb
- app/controllers/ems_infra_controller.rb
- spec/controllers/ems_infra_controller_spec.rb
When redirect from another (e.g. Alert) controller provider dashboards have no breadcrumbs. In `GenericShowMixin`  `show_dashboard` method is dropping breadcrumb, but only for the showed record (one concrete Provider, like Amazon or Openshift instance). Not the upper level of hierarchy (Cloud/Container provider). So there are no breadcrumbs showed. 
This PR adds the base of breadcrumbs fro providers.
https://bugzilla.redhat.com/show_bug.cgi?id=1655114
1. Configure an appliance with a provider (e.g. infra)
2. Setup an alert to fire against that provider
3. Navigate to Monitor->Alerts->All Alerts
4. Click on the providers name in the list-view of the provider
> Show breadcrumbs when redirected from another controller

- app/helpers/cloud_volume_helper/textual_summary.rb
- spec/helpers/cloud_volume_helper/textual_summary_spec.rb
In list View there is displayed `Status` column for Cloud Volumes, but for the detail view of single Cloud Volume, there is no such thing.
https://bugzilla.redhat.com/show_bug.cgi?id=1650294
Navigate to Storage => Block Storage => Volumes => <Select some Volume>
> Add Status Attribute to Cloud Volume Detail screen

- app/controllers/application_controller/tags.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1665284
**What:**
This PR fixes error while editing tags from Container provider details' page. It was not possible to edit tags. Tagging from the list of container providers worked well, but just because `@display` variable was set to `"main"` (here https://github.com/ManageIQ/manageiq-ui-classic/blob/gaprindashvili/app/controllers/mixins/generic_show_mixin.rb#L110) and `feature_name` method was already prepared for this (https://github.com/ManageIQ/manageiq-ui-classic/blob/gaprindashvili/app/controllers/application_controller/tags.rb#L70). See the changes.
1. Go to _Compute > Containers > Providers_
2. Add some provider if there is no one
3. Click on the provider in the list, display its details page
4. …
> [GAPRINDASHVILI] Fix editing tags from container provider page

- spec/services/dialog_local_service_spec.rb
Fix for change from https://github.com/ManageIQ/manageiq-ui-classic/pull/3893
Failure:
```
1) DialogLocalService#determine_dialog_locals_for_custom_button when the object is a Storage returns a hash with the proper parameters
Failure/Error:
expect(service.determine_dialog_locals_for_custom_button(obj, button_name, resource_action, display_options))
.to eq(
:resource_action_id     => 321,
:target_id              => 123,
:target_type            => target_type,
:dialog_id              => 654,
:force_old_dialog_use   => false,
:api_submit_endpoint    => "/api/#{collection_name}/123",
:api_action             => "custom-button-name",
:finish_submit_endpoint => finish_endpoint,
expected: {:resource_action_id=>321, :target_id=>123, :target_type=>"storage", :dialog_id=>654, …
```
> [GAPRINDASHVILI] [WIP] Change datastores to data_stores

- app/assets/javascripts/controllers/miq_ae_class/ae_inline_method_selection_controller.js
- app/controllers/miq_ae_class_controller.rb
- app/views/miq_ae_class/_embedded_methods.html.haml
- spec/controllers/miq_ae_class_controller_spec.rb
Thanks to the `selectable` attribute of the `miq-tree-selector` component, it is possible to prevent to select a specific embedded method(s) in the tree. I am building here a regular expression from all the homonymic methods so the same method in an other domain cannot be selected.
@miq-bot add_reviewer @pkomanek 
https://bugzilla.redhat.com/show_bug.cgi?id=1633815
> Do not allow to embed a method into itself in automate

- lib/tasks/manageiq/ui_tasks.rake
Example run:
```
$ rake yarn:clobber
Removing yarn.lock and node_modules in...
ManageIQ::GraphQL::Engine (/home/himdel/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/manageiq-graphql-82fdd9385bdd)
ManageIQ::Providers::Lenovo::Engine (/home/himdel/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-lenovo-10d8f40ba15c)
ManageIQ::Providers::Nuage::Engine (/home/himdel/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/manageiq-providers-nuage-ee21a2e6e9e2)
ManageIQ::UI::Classic::Engine (/home/himdel/manageiq-ui-classic)
ManageIQ::V2V::Engine (/home/himdel/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/manageiq-v2v-dad48b06c823)
```
Useful after upgrading node, or just generally when it breaks :).
Cc @jerryk55
> rake yarn:clobber - an easy way to remove node_modules & yarn.lock from all engines

- app/controllers/application_controller/filter/expression.rb
- spec/controllers/application_controller/filter/expression_spec.rb
Previous change was still forcing exp_key to be limited to "CONTAINS" for date type fields when switching fields because value of `self[:val1][:type]` is updated after changed code block in `prefill_val_types` method. Fixed a change made in https://github.com/ManageIQ/manageiq-ui-classic/pull/3879 with a call to backend method to return the type of field based upon selected column
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1563823
before
after
@mzazrivec please review/test
> Fixed check in if condition

- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ops_controller/settings/common_spec.rb
Fixed couple of scenarios
- Worker memory threshold of 1 GB or above was not reflected on Workers tab because https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/ops_controller/settings/common.rb#L997 value of variable `x` needs to be converted to integer value from a float so value can be selected correctly in the drop down.
- If a value in yaml config file is set to as 600.megabytes, it is being returned as a string, so need to evaluate/convert the value so it can be correctly selected in the drop down.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656873
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1658373
before
after
@mzazrivec please review/test, in order to recreate, change Advanced config YAML and enter follwoing in there
```
:generic_worker: …
```
> Fixed display of worker memory threshold settings

- app/services/container_dashboard_service.rb
- spec/services/container_dashboard_service_spec.rb
Added missing unit label for Container CPU and Memory heatmap tooltips.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656877
@mzazrivec please review
before
after
> Added missing unit label

- app/views/ops/_ldap_auth_users.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594497
Go to Configuration -> Settings -> select current Server and set it like picture below
Go to Configuration -> Access Control -> Groups -> Configuration -> Add a new Group -> Check the "Look up External Authentication Groups" checkbox -> **if you have it set** just fill `LDAP Group Lookup` and Retrive **else** use following diff to mock data and then just fill `LDAP Group Lookup` and Retrive
```diff
diff --git a/app/controllers/ops_controller/ops_rbac.rb b/app/controllers/ops_controller/ops_rbac.rb
index 757f757..3e47784 100644
--- a/app/controllers/ops_controller/ops_rbac.rb
+++ b/app/controllers/ops_controller/ops_rbac.rb
@@ -497,7 +497,7 @@ module OpsController::OpsRbac
@edit[:new][:user_pwd])
end
rescue => bang
- …
```
> Make LDAP Users searchable

- package.json
react-bootstrap-typeahead 3.3.0 came out, and it requires create-react-context without depending on it, causing...
ERROR in ./node_modules/react-bootstrap-typeahead/lib/TypeaheadContext.js
Module not found: Error: Can't resolve 'create-react-context' in '/home/himdel/manageiq-ui-classic/node_modules/react-bootstrap-typeahead/lib'
resolve 'create-react-context' in '/home/himdel/manageiq-ui-classic/node_modules/react-bootstrap-typeahead/lib'
Parsed request is a module
using description file: /home/himdel/manageiq-ui-classic/node_modules/react-bootstrap-typeahead/package.json (relative path: ./lib)
Field 'browser' doesn't contain a valid alias configuration
@ ./node_modules/react-bootstrap-typeahead/lib/TypeaheadContext.js 12:49-80
@ …
> Add create-react-context dependency to fix react-bootstrap-typeahead failure

- app/controllers/vm_remote.rb
Somehow the CSP implementation in MS Edge forbids images coming from WebMKS remote consoles due policy violation. By adding the `blob:` to the `img-src` this works as in other browsers.
@miq-bot add_label providers/console, bug
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1668437
> Allow `blob:` type in img-src CSP for WebMKS remote consoles

- app/controllers/ops_controller/settings/common.rb
- app/controllers/ops_controller/settings/upload.rb
- app/helpers/application_helper.rb
- app/views/dashboard/oidc_login.html.haml
- app/views/dashboard/saml_login.html.haml
- app/views/layouts/application.html.haml
- app/views/layouts/login.html.haml
- app/views/layouts/print.html.haml
- app/views/layouts/remote_console.html.haml
- app/views/layouts/report_only.html.haml
- app/views/ops/_settings_custom_logos_tab.html.haml
- app/views/vm_common/console_vmrc.html.haml
- config/routes.rb
I created a wrapper around the `favicon_link_tag` helper to be able to set a custom favicon if the related configuration parameter is set to true. The icon upload code is awfully copy-pasted and I'm willing to fix it in a follow-up PR as this one might be backported.
https://bugzilla.redhat.com/show_bug.cgi?id=1578076
@miq-bot add_label graphics
> Allow the user to upload a custom favicon image in Custom Logos

- spec/requests/restful_redirect_spec.rb
Dialog seeding was refactored in https://github.com/ManageIQ/manageiq/pull/18366, and in doing so the simpler `seed_dialog` is put in place as an alternative to `sync_from_file`.  This PR removes the last caller of `sync_from_file`, so it can be removed from core after this is merged.
See the comment here: https://github.com/ManageIQ/manageiq/pull/18366/files#diff-4662619cda7219ae1605ab55f1e2f2bcR28
> sync_from_file is deprecated in favor of seed_dialog

- spec/services/topology_service_spec.rb
Travis failure caused by https://github.com/ManageIQ/manageiq/pull/18378
@miq-bot add-label bug, test
> Fix travis failure caused by ManageIQ/manageiq#18378

- app/views/layouts/_user_input_filter.html.haml
This PR adds the missing bootstrap select styling from the user input filter modal
https://bugzilla.redhat.com/show_bug.cgi?id=1670458
Before
After
>  Add missing styling to user input filter modal

- app/controllers/dashboard_controller.rb
- spec/controllers/dashboard_controller_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1666712
**What:**
Fix displaying the dashboard, in _Cloud Intel > Dashboards_.
1. Create at least 2 dashboards in the _EvmGroup-super_administrator_ group:
go to _Cloud Intel > Reports > Dashboards_ accordion,
click on the _EvmGroup-super_administrator_ group,
then _Configuration > Add a new Dashboard_
2. Go to _Cloud Intel > Dashboard_ and you should see dashboards from step 1
3. Click on another tab/Choose some another dashboard
=> nothing happens, the original dashboard remains displayed, the other one not, no errors in log
---
**Before:** (after clicking on another tab _New_dashboard2_, nothing happens, we still see _New_dashboard_)
**After:** (after clicking on another tab _New_dashboard2_, the dashboard …
> Fix displaying selected dashboard while clicking on its tab

- app/controllers/mixins/ems_common_angular.rb
- app/helpers/application_helper/button/ems_infra_scale.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1664888
Supports the openstack-specific changes by:
1) displaying validation message, if one exists, even on success
2) Hide scaling/scaledown actions if there are no hosts registered with the provider
> Bug 1664888: Allow OpenStack infra providers without ironic

- app/controllers/report_controller/menus.rb
- spec/controllers/miq_report_controller/menus_spec.rb
When setting a report menu to default under `Cloud Intel -> Reports -> Edit report menus`, the wrong hash key was deleted. The group's settings is indexed by strings and not symbols, so when resetting & saving a menu nothing happened. For more details see the BZ.
@miq-bot add_label bug, gaprindashvili/yes, hammer/yes, cloud intel/reports
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1670293
> Delete the "report_menus" instead of :report_menus when resetting

- app/services/topology_service.rb
- spec/services/infra_topology_service_spec.rb
This never worked.  The argument passed to uniq/distinct is used to
either add or remove the 'distinct' constraint. Fortunately, the bug just
caused it to be inefficient.
Since AR::QueryMethods uniq is deprecated in 5.0 and removed in 5.1 and we
want the Array#uniq method, we need to convert the relation to an array.
> AR::QueryMethods uniq/distinct takes no block

- app/services/dialog_local_service.rb
- spec/services/dialog_local_service_spec.rb
CustomButtons run on Hosts return "HostEsx" with demodulize, and CloudNetworks when demodulized return "public" or "private", which means that for four or so different object types we're not running the custom buttons currently cause we can't find the right target_type for the API endpoint.
However, the check that was in was temporary and used to determine if the object could use the new dialogs. Erik confirmed that all objects that needed to do now, so this check can be removed. To anyone who doesn't like it, the alternatives are adding a buncha models to the NEW_DIALOG_USERS list, or moving all that logic to the respective models, neither of which is particularly palatable, so boooooya. (https://github.com/ManageIQ/manageiq-ui-classic/commit/a64c119f5403d8a7a0ee4071cfe459ee7a31d920 and …
> Use base_model name instead of demodulize

- app/helpers/application_helper/listnav.rb
- spec/controllers/availability_zone_controller_spec.rb
- spec/controllers/container_controller_spec.rb
- spec/controllers/container_group_controller_spec.rb
- spec/controllers/container_node_controller_spec.rb
- spec/controllers/container_project_controller_spec.rb
- spec/controllers/container_replicator_controller_spec.rb
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_cluster_controller_spec.rb
- spec/controllers/ems_container_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/controllers/host_controller_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1670550
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/3827 so this PR **can not** reintroduce toolbar with Configuration,...
Steps to test:
- make sure Cloud Intel -> Timeline still has a timeline tree in listnav
- for Availability Zones, Containers, Container Groups, Container Nodes, Container Pods, Container Projects, Clusters/Deployment Roles, Hosts/Nodes, Cloud Providers, Infra Providers, Container Providers select one of items and go to its summary page and Monitoring -> Timelines -> see that listnav is the same as in summary page and toolbar has only Back button
- all things in listnav redirects correctly after clicking
Before:
After:
Having [this …
> Use timeline listnav only for dashboard controller

- app/controllers/report_controller/reports/editor.rb
- spec/controllers/miq_report_controller/reports/editor_spec.rb
there is bunch of refactoring but also I am using one error message for Time tab - when one time field is required (last commit)
this is needed for https://github.com/ManageIQ/manageiq-ui-classic/pull/5210
> Report editor titles's tab unification

- app/views/report/_form_filter_chargeback.html.haml
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1650117
> Report editor: add livesearch to timezone dropdown

- app/controllers/ops_controller/diagnostics.rb
- spec/controllers/ops_controller/diagnostics_spec.rb
The server diagnostics page under settings was not displaying checkboxes, so it was not possible to restart the workers using the toolbar button. Setting the correct instance variable to true fixes the issue, specs are added to keep @martinpovolny happy.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1672758
> Display missing checkboxes for workers under Diagnostics

- app/controllers/application_controller/buttons.rb
Refactor flash messages to use "launch" instead of "execute" when launching Ansible jobs. 
https://bugzilla.redhat.com/show_bug.cgi?id=1669578
Screen shot prior to fix:
Screen shot post fix:
> Ansible job launch confirmation message fix

- app/views/configuration_manager/_shared_form.html.haml
Automation > Ansible Tower > Explorer, Configuration > Add a New Provider
When there are no visible zones, the UI looks like this:
The same happens with only 1 zone, but then, the input is filled out.
When multiple zones are found, there's a select instead.
To prevent confusion from a readonly "Zone" input, with nothing in it, adding an explicit message about no visible zones:
> Ansible Tower & Foreman edit - explicitly warn when Zone.visible.empty?

- app/controllers/ansible_credential_controller.rb
- app/controllers/ansible_playbook_controller.rb
- app/controllers/ansible_repository_controller.rb
- app/controllers/mixins/listnav_mixin.rb
- app/views/layouts/listnav/_ansible_credential.html.haml
- app/views/layouts/listnav/_ansible_playbook.html.haml
- app/views/layouts/listnav/_ansible_repository.html.haml
- spec/controllers/ansible_credential_controller_spec.rb
- spec/controllers/ansible_playbook_controller_spec.rb
- spec/controllers/ansible_repository_controller_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1672689
Before:
After:
TODO:
@miq-bot add_label bugzilla needed, wip, automation/ansible
> Add listnav to Embedded Ansible pages

- app/controllers/application_controller.rb
- app/views/layouts/_show_report.html.haml
- app/views/layouts/report_only.html.haml
- spec/controllers/application_controller_spec.rb
backend
dashboard
full screen
Links
-----
* https://bugzilla.redhat.com/show_bug.cgi?id=1650418
@miq-bot add_label pending backend, bug
> Display widget's title in full screen of widget result

- app/assets/javascripts/controllers/report_data_controller.js
This PR adds back the options for 200, 500 in "Items per page"
https://bugzilla.redhat.com/show_bug.cgi?id=1515952
> Add back paging options

- app/assets/javascripts/components/pf_charts/line-chart.component.js
- app/assets/javascripts/controllers/ems_container_dashboard/utilization_trend_chart_controller.js
- app/services/container_dashboard_service.rb
Compute > Containers > Providers > pick a provider, dashboard view
---
When there **is** daily utilization data, there is no bug.
When no daily data is available, we get console errors:
```
TypeError: Cannot set property 'tooltipFn' of undefined
in app/assets/javascripts/controllers/ems_container_dashboard/utilization_trend_chart_controller.js:70
TypeError: Cannot read property 'layout' of undefined
in app/assets/javascripts/components/pf_charts/trends-chart.component.js:27
```
When no *hourly* data is available, the fallback to realtime or empty (`... || realtime_utilization || empty_utilization_trend_data`) would never get called, because `hourly_utilization` always returned data.
---
=> made sure hourly returns no data when empty, allowing the realtime fallback
=> fix the JS error by …
> Container dashboard utilization metrics - fix hourly metrics

- app/views/miq_ae_class/_fields_seq_form.html.haml
Automate Explorer datastore schema edit reset button click fixed to display only one confirmation message.
https://bugzilla.redhat.com/show_bug.cgi?id=1525835
Screen shot prior to code fix, double confirmation messages displayed:
Screen shot post code fix, single message:
> Automate Datastore Schema Edit reset click message

- app/controllers/ops_controller/db.rb
The AR method #order doesn't take a block.
This was changed in 08c83427a6
Currently this fails with:
```
[----] F, [2019-02-11T10:16:52.236114 #14890:2b28dbfe56a8] FATAL -- : Error caught: [ArgumentError] The method .order() must contain arguments.
/home/ncarboni/.gem/ruby/2.4.3/gems/activerecord-5.0.7.1/lib/active_record/relation/query_methods.rb:1214:in `check_if_method_has_arguments!'
/home/ncarboni/.gem/ruby/2.4.3/gems/activerecord-5.0.7.1/lib/active_record/relation/query_methods.rb:338:in `order'
/home/ncarboni/.gem/ruby/2.4.3/bundler/gems/manageiq-ui-classic-2e054446e056/app/controllers/ops_controller/db.rb:29:in `db_list'
/home/ncarboni/.gem/ruby/2.4.3/bundler/gems/manageiq-ui-classic-2e054446e056/app/controllers/ops_controller/db.rb:111:in `db_get_info' …
```
> Fix database connections page

- app/views/ems_container/_show_dashboard.html.haml
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1667980
**What:**
Fix the missing flash message (or better missing flash message div) for re-checking authentication status (and another actions) for selected Container Provider, under _Compute > Containers > Providers_.
1. Have some Openshift Provider and go to _Compute > Containers >Providers_ 
2. Choose some provider, click on it, display its details page
3. On the Dashboard view, select _Authentication > Re-check Authentication Status_
=> nothing is displayed, just error about missing flash message div, in the right upper corner
---
**Before:** (no flash message, error)
**After:** (flash message appears also for another actions/operations)
> Fix missing flash message for Re-check Authentication Status

- app/controllers/application_controller/buttons.rb
Solves https://github.com/ManageIQ/manageiq-ui-classic/issues/5238
Go to Automation -> Automate ->Customization -> Buttons -> try to save/add one that has type Ansible Playbook without  Playbook Catalog Item
Before:
"Nothing" happens
with error in log
```
: Error caught: [ActiveRecord::RecordNotFound] Couldn't find ServiceTemplate without an ID
/Users/zita/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.1/lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
/Users/zita/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.1/lib/active_record/relation/finder_methods.rb:66:in `find'
/Users/zita/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.1/lib/active_record/querying.rb:3:in `find' …
```
> Check button's inputs before looking for records

- app/controllers/application_controller/buttons.rb
- app/views/static/generic_object/main_custom_button_form.html.haml
Just removing stuff that doesn't work because of a typo/not being complete. Saving myself some time in the future :)
Go to Automation -> Automate -> Generic Objects -> Add/Edit Custom button
Before/After:
Has to be same.
Only four inputs are red/required.
@miq-bot add_label technical debt, hammer/no
> Remove not working stuff

- app/assets/javascripts/miq_application.js
On a button's summary page under `Automate -> Customization -> Buttons`, there's a `Simulate` option in the `Configuration` toolbar dropdown. If clicked, a spinner shows up and immediately gets hidden. However, the page redirect might happen with a delay, that might suggest the user that nothing happened. By adding an exception into the toolbar request handling code, the spinner keeps spinning until the redirect actually happens.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1535215
> Do not hide the spinner before the custom button simulate redirect

- app/controllers/security_group_controller.rb
Fixes:
DEPRECATION WARNING: Method each_value is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash. Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.7.1/classes/ActionController/Parameters.html (called from update at /Users/joerafaniello/Code/manageiq-ui-classic/app/controllers/security_group_controller.rb:179
Extracted from: https://github.com/ManageIQ/manageiq-ui-classic/pull/5076
> AC::Parameters doesn't have each_value, use each

- app/views/ops/_rbac_user_details.html.haml
This PR changes the "Change stored password" link to a button and cleans up some of the styling.
https://bugzilla.redhat.com/show_bug.cgi?id=1469035
Before
After
> User Edit screen - link to button

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1671522
> Don't allow adding another svc bundle into an existing bundle

- app/views/miq_ae_tools/_import_export.html.haml
Based on https://github.com/ManageIQ/manageiq-ui-classic/pull/5180#discussion_r257185517, it turned out that the `ImportSetup.listenForGitPostMessages()` should not have been removed from template, because its not related to migrated form.
Its related to upload from file and injects new UI to this element: https://github.com/ManageIQ/manageiq-ui-classic/blob/8fd1d8edfc91f62f7218d8d5e7b3b11a903c26c6/app/views/miq_ae_tools/_import_export.html.haml#L110
Now i don't really like how it works and we should probably change it soon. But i will first have to find out what its doing.
> Add ImportSetup listener back to import/export template.

- app/assets/stylesheets/dual_list.scss
- app/assets/stylesheets/main.scss
- app/javascript/.eslintrc.json
- app/javascript/components/dual-list-select/index.jsx
- app/javascript/components/dual-list-select/list.jsx
- app/javascript/spec/dual-list-select/__snapshots__/dual-list-select.spec.js.snap
- app/javascript/spec/dual-list-select/dual-list-select.spec.js
Dual list was not proplely updating form state, specifically `pristine`/`dirty` states. This was cause due to react refs and async nature of executing events via refs. Proposed solution which adds `timeout` to manually trigger `onBlur` and `onFocus` events is future proof and will probably result in more bugs down the line.
Now  the component uses purely React state without any refs which will ensure synchronous behavior.
> Rework dual list

- spec/javascripts/support/jasmine.yml
the helper was removed in https://github.com/ManageIQ/manageiq-ui-classic/pull/5203 but I left a reference to it in jasmine config
fixes
GET http://localhost:8888/__spec__/helpers/toolbar.js net::ERR_ABORTED 404 (Not Found)
> Fix error during jasmine

- app/controllers/application_controller/ci_processing.rb
- spec/controllers/application_controller/ci_processing_spec.rb
- spec/controllers/vm_infra_controller_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1634713
https://bugzilla.redhat.com/show_bug.cgi?id=1655477
**What:**
This PR fixes the problem about the Power operations which were enabled for a template. And Power operations don't make sense for a template. They should be enabled only for VMs.
1. Go to _Compute > Infrastructure > VMs > VMs & Templates_ accordion > _All VMs & Templates_
2. Select some template (not VM!) by checking its checkbox
3. In the toolbar, choose _Power > Power On_ or any other Power action
=> flash message about the start (for example) which was initiated successfully appears and it shouldn't
---
**Before:**
**After:**
**Note:**
I've removed appropriate power actions from untestable actions array in `testable_action` method which …
> Fix enabling Power operations for a template

- app/views/layouts/exp_atom/_edit_tag.html.haml
Ensure that Bootstrap SelectPicker is only invoked once when selecting from dropdowns.
NOTE: this fixes 2 similar BZ tickets, listed below.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1664852
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1664886
Screen shots post code fix:
> Fix Expression Builder to load page display only once per dropdown pick

- app/helpers/ems_infra_helper/textual_summary.rb
If label is not set on a textual, it will be generated from the record class. For the details, see the BZ.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1668691
> Fix the label of Custom Button Events for infra providers

- app/views/ops/_settings_custom_logos_tab.html.haml
The brand image is show on the LEFT side, fixed the description under `Settings -> Custom Logos`.
> Fixed explanation of brand image positioning under Custom Logos

- app/controllers/vm_common.rb
- app/javascript/components/vm-server-relationship-form/index.jsx
- app/javascript/components/vm-server-relationship-form/vm-server-relationship-form.schema.js
- app/javascript/packs/component-definitions-common.js
- app/javascript/spec/vm-server-relationship-form/vm-server-relationship-form.spec.js
- app/views/vm_common/_evm_relationship.html.haml
- package.json
- Converted `Services > Workloads > Select One and go to his show page > Configuration > Edit Management Engine Relationship` form to DDR
(The length of the select field was discussed with @terezanovotna and it will be changed in PF3-mapper library.)
> Converts server relationship form to DDR

- app/controllers/vm_common.rb
- app/helpers/application_helper/toolbar/right_size_view.rb
- app/views/vm_common/_right_size.html.haml
- config/routes.rb
Right size recommendations can be accessed from a VM's summary screen under the `Configuration` dropdown in the toolbar.
I created a new toolbar on this page with the print button and a new route that displays the printing dialog. However, it is a little weird to have the button completely on the left side of the toolbar. I don't feel it as consistent, but as far as I see, it is always aligned to the left, but on other pages there are multiple buttons pushing it more to the right.
The printing follows the same logic as on summary screens, a new window with the printing dialog opened. If you close the printing dialog, the window will close with it so you can get back to the previous page.
https://bugzilla.redhat.com/show_bug.cgi?id=1430159
> Allow to print (export to PDF) the right size recommendations of a VM

- app/controllers/application_controller/performance.rb
Add Memory Chart for Amazon Availability Zones which was removed by https://github.com/ManageIQ/manageiq-ui-classic/pull/3836
https://bugzilla.redhat.com/show_bug.cgi?id=1677406
> Add Memory for Amazon Availability Zones

- lib/report_formatter/text.rb
- spec/lib/report_formater/text_formatter_spec.rb
- spec/support/report_helper.rb
Text based reports ignore line widths.  Performing manual padding was
causing a "negative argument" error if a line exceeded the normal
report's line width.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1677839
> Use ljust to left justify and pad strings

- app/helpers/service_helper/textual_summary.rb
- spec/helpers/service_helper/textual_summary_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1660803
**What:**
Fix wrong displayed elapsed time in the service. When running a ansible-playbook service, at the end of the run in the service entry you can see the elapsed time for provisioning.  If this time is more than 60 minutes, it shows hours, however, the minutes counter still displays a value over 60.
**Note:**
The BZ is for 5.9. but we need the same fix also in master, hammer.
**Before:**
**After:**
> Fix wrong displayed elapsed time in the service

- app/helpers/application_helper/button/summary_reload.rb
- spec/helpers/application_helper/buttons/summary_reload_spec.rb
Compute -> Infrastructure -> VMs -> go to summary page of one -> Monitoring -> Utilization/Timelines/Chargeback
Compute -> Clouds -> Instances -> go to summary page of one -> Monitoring -> Utilization/Timelines/Chargeback
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1547081
**Before:**
After clicking Refresh button
**After:**
No Refresh button and no weird redirect
@miq-bot add_label bug, hammer/yes, gaprindashvili/yes, toolbars
> Do not show Refresh button on Monitoring page

- package.json
Broken by https://www.npmjs.com/package/@types/enzyme/v/3.9.0
Issue is described here:
https://github.com/Microsoft/TypeScript/issues/15972
Fixes:
```
ERROR in [at-loader] ./node_modules/@types/enzyme/index.d.ts:367:40 
TS2370: A rest parameter must be of an array type.
ERROR in [at-loader] ./node_modules/@types/enzyme/index.d.ts:457:60 
TS2370: A rest parameter must be of an array type.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Webpacker] Compilation Failed
```
@miq-bot add_label build, hammer/no
> Downgrade types/enzyme to fix Travis

- app/presenters/tree_builder_buttons.rb
Calling `ui_lookup(:model => klass)` on these is giving the same result as the hardcoded strings.
@miq-bot add_label cleanup, hammer/no
> Remove unnecessary cases from Custom Button tree node name generation

- app/controllers/application_controller.rb
- app/controllers/application_controller/tree_support.rb
- config/routes.rb
- spec/routing/ems_cloud_routing_spec.rb
- spec/routing/ems_container_routing_spec.rb
- spec/routing/ems_infra_routing_spec.rb
- spec/routing/ems_physical_infra_routing_spec.rb
- spec/routing/host_routing_spec.rb
- spec/routing/shared_examples/vm_common_examples.rb
- spec/routing/vm_or_template_routing_spec.rb
As far as I see this method was used for the old trees that supported the expand/colleapse all on doubleclick. We no longer have this feature, so dropping the route and the methods behind it.
@miq-bot add_label cleanup, hammer/no
> Remove the unused squash_toggle method/route from TreeSupport

- package.json
Downgrade from `3.1.18` to `3.1.17`.
Fixes error:
`TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).`
Related issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33048
@miq-bot add_label hammer/no, test
@himdel ping
> Use @types/enzyme v3.1.17 to prevent error TS2314

- app/controllers/ops_controller/diagnostics.rb
- app/presenters/tree_builder_diagnostics.rb
- spec/presenters/tree_builder_servers_by_role_spec.rb
These two variables are accessible through a parameter, so no need for them. The test was invalid, as the sandbox variables haven't been set properly so it was adjusted.
@miq-bot add_label cleanup, trees
> Remove sandbox variables from the trees on the diagnostics screens

- config/webpack/shared.js
Opening a file in vim will not trigger a rebuild when using `webpack --watch`.
(And in ui-components: https://github.com/ManageIQ/ui-components/pull/370/)
> Webpack - add watchOptions to ignore vim swapfiles

- app/views/cloud_network/show.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1680525
1. Create Custom button Group on "Cloud Network" object type.
2. Create on simple custom button under group (no dialog)
3. Navigate to cloud network entity... [Networks-> Network]
4. Go to Summary page of any Cloud Network
5. Execute custom button 1+ times...
6. Refresh browser
7. Relationship table will show you custom button event counts 
8. Now navigate to event page by clicking on custom button events
9. You will not see any events
Before:
After:
@miq-bot add_label gaprindashvili/yes, hammer/yes, networks, bug
> Add All Custom Button Events page to Cloud Network

- app/presenters/tree_builder_infra_networking.rb
Removes a bunch of `hash[:foo => 'bar']` accesses.
Those should probably have been...
```
item[:load_children] = true
item[:selectable] = false
```
but:
a) not seeing any difference,
b) it never worked that way in this tree
c) there is no `load_children` or `selectable` property on `Lan` instances.
Removing.
(
comes from ManageIQ/manageiq#10753
see ManageIQ/manageiq#10753 (comment)
)
> TreeBuilderInfraNetworking - remove dead code, fix style

- app/controllers/application_controller/automate.rb
- app/controllers/application_controller/buttons.rb
- app/controllers/miq_ae_customization_controller/custom_buttons.rb
- app/helpers/custom_button_helper.rb
- app/presenters/tree_builder_buttons.rb
- app/presenters/tree_builder_catalog_items.rb
- app/views/layouts/_ae_resolve_options.html.haml
- app/views/shared/buttons/_ab_form.html.haml
- app/views/shared/buttons/_ab_list.html.haml
- spec/controllers/application_controller/automate_spec.rb
- spec/controllers/application_controller/buttons_spec.rb
- spec/controllers/miq_ae_customization_controller/custom_buttons_spec.rb
- spec/views/shared/buttons/_ab_form.html.haml_spec.rb
Initially I just wanted to drop the `target_classes` from the Custom Buttons treebuilder, but I found the hydra and started to cut it down :snake: by :snake:. The PR will make sense if you read it commit by commit, also it will require a lot of clicking and testing...
@miq-bot add_label refactoring, hammer/no, trees, automation/automate
> Clean up some sandbox variables on the Custom Buttons screen

- spec/controllers/chargeback_controller_spec.rb
caused by https://github.com/ManageIQ/manageiq/pull/18486 - we started to use `ChargebackRateDetailCurrency#code` instead of `ChargebackRateDetailCurrency#name`
Links
------
https://github.com/ManageIQ/manageiq/pull/18486
> Fix specs to use ChargebackRateDetailCurrency#code

- app/controllers/infra_networking_controller.rb
- app/controllers/storage_controller.rb
All of these (`tree_record`, `leaf_record`) are used in different controllers, but not here.
`storage_scan` only looks dead, it's called by `x_button` from `explorer.rb`, because `#{model}_#{action}`
> InfraNetworking & Storage - remove dead methods

- app/controllers/miq_policy_controller/miq_actions.rb
When you navigate `Control -> Explorer -> Actions -> Configuration -> Add a new action` you get following error:
```
[----] F, [2019-02-27T14:40:55.173928 #11193:2ae5cbf9b8e4] FATAL -- : Error caught: [IndexError] string not matched
/home/rknaur/manageiq-ui-classic/app/controllers/miq_policy_controller/miq_actions.rb:308:in `[]='
/home/rknaur/manageiq-ui-classic/app/controllers/miq_policy_controller/miq_actions.rb:308:in `block in action_build_alert_choices'
/home/rknaur/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.1/lib/active_record/relation/delegation.rb:38:in `each'
/home/rknaur/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.1/lib/active_record/relation/delegation.rb:38:in `each'
/home/rknaur/manageiq-ui-classic/app/controllers/miq_policy_control …
```
> Fix add new action

- app/controllers/mixins/ems_common/angular.rb
- app/controllers/mixins/ems_common_angular.rb
- app/views/layouts/angular-bootstrap/_endpoints_for_url.html.haml
- app/views/layouts/angular/_multi_auth_credentials.html.haml
- app/views/shared/views/ems_common/angular/_form.html.haml
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/mixins/ems_common/angular_spec.rb
- spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Adds `Endpoint URL` for Azure
Depends on https://github.com/ManageIQ/manageiq-providers-azure/pull/274
https://bugzilla.redhat.com/show_bug.cgi?id=1594381
> Add endpoint url for azure

- app/controllers/application_controller/advanced_search.rb
1. Advanced search
2. Commit search expression
3. Hit `Save` button
4. Watch `log/evm.log`
Before:
```
ERROR -- : MIQ(vm_infra_controller-adv_search_button): Search Name is required
```
After: no unnecessary error log
https://bugzilla.redhat.com/show_bug.cgi?id=1670472
> Advanced Search Save: don't create unnecessary flash message

- app/assets/javascripts/controllers/host/host_form_controller.js
- app/views/layouts/angular/_multi_auth_credentials.html.haml
- spec/javascripts/controllers/host/host_form_controller_spec.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1634794
**Description of problem:**
When 2 or more hosts are selected and edited, Alert 'Abandon changes' is displayed even when no changes are made by the user.
1. Have CFME appliance with added provider with some hosts
2. Go to Compute -> Infrastructure -> Hosts
3. Select 2 or more hosts and click Configuration -> Edit selected items 
4. Leave the page without making any changes
Alert asking whether to abandon changes is displayed
If no changes are made, no 'Abandon changes' alert should be displayed
* validation_id was **nil** in template and **blank** in controller
* => changed to null everywhere
* it caused dirty state on the form (because the model and the copy was …
> Fixes value of validate_id in host form

- app/controllers/catalog_controller.rb
- app/views/catalog/explorer.html.haml
1. create a catalog item
2. delete the provider template used in the above catalog item
3. Services ➛ Catalogs ➛ Service Catalogs
4. In the tree view click on the created catalog item (also try refresh, full page reload, item edit, ...)
5. In the rendered GTL click on the created catalog item
Clicking in the GTL view would render the catalogs item summary screen correctly.
Clicking in the tree view would render just list of VMs.
This fix removes `@view` from the `record_showing` test, since it would confuse the code to render GTL instead of catalog item summary screen. 
https://bugzilla.redhat.com/show_bug.cgi?id=1652858
> Fix sumary screen for catalog item with deleted provider template

- app/presenters/tree_builder_alert_profile_obj.rb
- spec/presenters/tree_builder_alert_profile_obj_spec.rb
When editing alert profile assignments, the tree building params were a little off. You can open the screen for reproducing under `Control -> Explorer -> Alert Profiles`, select a profile click as below:
There's an unknown keyword error in master, here I'm fixing it - specs included.
@miq-bot add_label bug, hammer/no, trees
cc @ZitaNemeckova
>  Fixed wrong keyword for selected nodes in TreeBuilderAlertProfileObj

- product/views/VmOrTemplate.yaml
Over time, the `compliances` table will get quiet large, and when paired with the rest of the tables in this report, you end up getting a query executed that looks like this:
```SQL
SELECT "vms"."id" AS t0_r0, ..., "vms"."memory_hot_add_increment" AS t0_r75,
"hosts"."id" AS t1_r0, ..., "hosts"."physical_server_id" AS t1_r36,
"storages"."id" AS t2_r0, ..., "storages"."storage_domain_type" AS t2_r18,
"ext_management_systems"."id" AS t3_r0, ..., "ext_management_systems"."tenant_mapping_enabled" AS t3_r23,
"snapshots"."id" AS t4_r0, ..., "snapshots"."ems_ref" AS t4_r16,
"compliances"."id" AS t5_r0, ..., "compliances"."event_type" AS t5_r6,
"operating_systems"."id" AS t6_r0, ..., "operating_systems"."kernel_version" AS t6_r25,
"hardwares"."id" AS t7_r0, ..., "hardwares"."provision_state" AS …
```
> [Performance] Remove compliance from VmOrTemplate includes

- app/assets/javascripts/components/generic_object/custom-image.js
- app/views/static/generic_object/custom-image.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650104
Go to Automation -> Automate -> Generic Objects -> Configuration -> Add a new Generic Object Class -> DO NOT chose a file for Custom Image -> click chosen image
**Before:**
Nothing happens
**After:**
There's error message and the input is read with a hint what's wrong (based on https://github.com/ManageIQ/manageiq-ui-classic/pull/5139#issuecomment-466010379)
@miq-bot add_label bug, hammer/yes, generic objects, automation/automate
> Add error when clicking upload image without selecting a file

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_alert_profile.rb
- app/presenters/tree_builder_condition.rb
- app/presenters/tree_builder_policy.rb
- app/presenters/tree_builder_report_dashboards.rb
It is an obsolete method that was being used to verify if some methods have been called in the correct TreeBuilders. If the assertion fails, it raises an exception so it's something we don't want to have...
> Remove the obsolete assert_type method from TreeBuilder

- app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
- app/assets/javascripts/services/dialog_editor_http_service.js
- app/views/miq_ae_customization/editor.html.haml
Automation > Automate > Customization, add/edit a dialog
https://bugzilla.redhat.com/show_bug.cgi?id=1553846
When editing dynamic field details in the dialog editor, the tree gets loaded before any field data is available, so it can't expand the active node, because it doesn't know it.
This, along with https://github.com/ManageIQ/ui-components/pull/369 makes it possible to delay the tree initialization until the tree gets displayed.
Depends on https://github.com/ManageIQ/ui-components/pull/369 and will need (a @skateman PR adding `?fqdn` support to `/tree/automate_entrypoint`) for the preselection to work.
(Feel free to merge https://github.com/ManageIQ/manageiq-ui-classic/pull/5267 + https://github.com/ManageIQ/ui-components/pull/369 together, the endpoint PR can be separate.)
Cc …
> Dialog Editor - rework tree params, *don't* pre-initialize the tree

- app/helpers/application_helper/button/miq_request.rb
- app/helpers/application_helper/toolbar/miq_request_center.rb
- spec/helpers/application_helper/buttons/miq_request_approval_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1676910
**What:**
This PR fixes the problem that Approver user was not able to deny the request, only to approve it.
Of course, this makes no sense, the user should have permissions also to deny the request. 
The button for denying the request was missing in the toolbar - 
**Details:**
The problem was that `miq_request_deny` does not exist, there aren't two different features - for approving and denying the request. It is the one - `miq_request_approval`, and the two buttons for appropriate actions.
Check also https://github.com/hstastna/manageiq/blob/master/db/fixtures/miq_product_features.yml#L162,
there is `Approve and Deny` feature, not the two ones.
**How to test:**
You can try the db provided by the reporter of this bug and just …
> Allow Approver user to deny the request

- app/assets/javascripts/miq_tree.js
- app/presenters/tree_builder_menu_roles.rb
- spec/presenters/tree_builder_menu_roles_spec.rb
The report menu editor's onclick handler is being called `miqOnCheckMenuRoles` which is weird, so renaming it to `miqOnClickMenuRoles`. Also the test for the node's ID prefix is unnecessary as the reports in the nodes aren't clickable, so it's not possible to trigger an onclick event from them anyway.
@miq-bot add_reviewer @brumik
> Rename and refactor miqOnCheckMenuRoles in miq_tree.js

- app/presenters/tree_builder_catalog_items.rb
- app/presenters/tree_builder_catalogs_class.rb
It's better to use super + 1 at the only place where it is being used.
> Catalog trees: move the unassigned node add into the ServiceCatalogs

- app/presenters/tree_builder_chargeback.rb
- app/presenters/tree_builder_chargeback_assignments.rb
- app/presenters/tree_builder_chargeback_rates.rb
Moving the common parts of the `TreeBuilderChargebackAssignments` and `TreeBuilderChargebackRates` into a common `TreeBuilderChargeback` and keeping the changes only. I also looked into the `x_get_tree_roots` method and cleaned it up a little, so it no longer depends on the tree type.
@miq-bot add_reviewer @himdel  
> Move common parts of CBA and CBR trees into TreeBuilderChargeback

- app/presenters/tree_builder_iso_datastores.rb
- app/presenters/tree_builder_ops_vmdb.rb
- app/presenters/tree_builder_pxe_servers.rb
- app/presenters/tree_builder_report_reports.rb
It's nicer if we don't touch the `@tree_state` instance variable from the classes inherited from `TreeBuilder`, as they are already available through `options`. Just have to pass the param to each `get_kids` method that operates with `open_nodes`.
> Operate with open_nodes through options instead of TreeState

- app/assets/javascripts/miq_tree.js
- app/presenters/tree_builder.rb
I went through all the `TreeBuilder` classes and the `miqOnClickSelectTreeNode` was used only by left-side trees on explorer screens. Since we angularized all of those, this function is no longer used anywhere. All the other trees have a custom onclick function, or non-clickable nodes.
> Drop the default onclick handler from TreeBuilder as it's not used

- app/views/vm_common/_form.html.haml
Add missing form-control on vm parent dropdown
Before
After
> styling fix for vm edit screen

- app/controllers/application_controller/buttons.rb
- app/controllers/generic_object_definition_controller.rb
Depends on https://github.com/ManageIQ/manageiq/pull/18368
The idea is, we shold not try to manipulate both `button_order` and `members` for CustomButtons,
`members` should always follow `button_order`.
The core PR adds an `after_save` to `CustomButtonSet` that always updates the set of children to match `button_order`.
This PR removes all code which updates members/children, and makes sure `button_order` gets updated instead.
---
This probably needs some testing,
I'm not quite sure what..
```
org_mems = @custom_button_set.members # clean up existing members
org_mems.each do |m|
uri = CustomButton.find(m.id)
uri.save
end
```
(used twice)
was supposed to achieve, `find+save` sound like a no-op.
> CustomButtonSet - don't touch children/members directly, set button_order

- app/controllers/miq_policy_controller/conditions.rb
- spec/controllers/miq_policy_controller/conditions_spec.rb
- spec/controllers/miq_policy_controller_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1683697
**What:**
Fix highlighting condition in accordion right after creating it: the newly created condition was not highlighted in accordion as expected, instead of that, _All Conditions_ node was highlighted. Everything else regarding adding new conditions seems to work.
1. Navigate to _Control > Explorer_, then _Conditions > Replicator Conditions_ ,or any other conditions
2. Create a new condition: choose _Configuration > Add a New Container Replicator Condition_ or any other type of condition (depends on step 1)
3. Fill in required fields (description and expression), values are not important
4. Click on _Add_ button
=>  _All Conditions_ node highlighted instead of newly created condition
TODO: _(done)_
- …
> Fix highlighting the condition in accordion after creating it

- app/assets/javascripts/miq_tree.js
The original scrolling code created by @bmclaughlin was able to scroll only completely to the top or to the bottom and it was used in the RBAC tree only. I enhanced the scrolling functionality and extended its usage to both tree node activation functions.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1630040T
@miq-bot add_label trees, bug
> When activating a tree node, make it visible by scrolling onto it

- app/controllers/infra_networking_controller.rb
- spec/controllers/infra_networking_controller_spec.rb
**Related BZ**: https://bugzilla.redhat.com/show_bug.cgi?id=1428584
**Related PR:** https://github.com/ManageIQ/manageiq-ui-classic/pull/3838
**What:**
Remove the unused `@infra_networking_record` variable and use `@record` instead to update solution for removing _Search_ from Switch summary page (under _Compute > Infra > Networking > Switches_ accordion.)
> Remove unused variable from infra networking controller

- app/views/ems_container/_trends-chart.html.haml
Compute > Containers > Overview or Compute > Containers > Providers > pick one, dashboard view
This fixes a 
```
TypeError: Cannot read property 'layout' of undefined
at trendsChartController.e.updateAll (application-d966831b…581bed47155710.js:3)
at trendsChartController.e.$onChanges (application-d966831b…581bed47155710.js:3)
```
when the JSON endpoints are taking longer to respond. (Longer = angular manages to do the first render before any data arrives.)
The controller already has a concept of `loadingDone`, used to display a spinner.
But it was never used to prevent rendering of the `pf-trends-chart` component, which fails when config is undefined.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1684226
(related to but not the same problem as in …
> Container trends chart - wait for loadingDone before displaying pf-trends-chart

- spec/helpers/application_helper/toolbar_builder_spec.rb
Likely related to https://github.com/ManageIQ/manageiq/pull/18368
Using `Rbac.filtered` needs user's timezone, and for that, settings have to be stubbed, or MiqServer.my_server set.
Since creating a custom button set now needs Rbac.filtered, adding...
Should prevent:
```
Failures:
1) ApplicationHelper::ToolbarBuilder custom_buttons for VM behaves like with custom buttons #get_custom_buttons
Failure/Error: MiqServer.my_server.server_timezone
NoMethodError:
undefined method `server_timezone' for nil:NilClass
Shared Example Group: "with custom buttons" called from ./spec/helpers/application_helper/toolbar_builder_spec.rb:144
2) ApplicationHelper::ToolbarBuilder custom_buttons for VM behaves like with custom buttons #custom_button_selects
Failure/Error: MiqServer.my_server.server_timezone …
```
> Fix failing travis - stub my_server when dealing with custom button sets

- app/javascript/components/catalog-form/catalog-form.jsx
Adds missing catch blocks to promises in Catalog form.
It caused error messages is tests.
**Before**
```
(node:27486) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'resources' of undefined
(node:27486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:27486) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**After**
```
```
> Fix unhandled promise catch in catalog form

- config/webpack/shared.js
comes from packages using `dependencies` and getting their own copy of angular to load,
the change forces the topmost angular for all packages,
thus angular loads only once
Cc @kbrock
> Fix 'Tried to load angular more than once'

- app/services/automate_import_service.rb
Description
Fixing the broken datastore import inside the automate import service from #4912. 
**before:** Domain was imported without selected namespaces.
**after:**  Domain is imported with all selected namespaces.
> Automate import service fix.

- app/javascript/components/catalog-form/catalog-form.schema.js
- app/javascript/helpers/promise-debounce.js
- app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
- app/javascript/spec/catalog-form/validator.spec.js
- package.json
- tsconfig.json
* Adds [library](https://github.com/slorber/awesome-debounce-promise) for debouncing promises
* Adds 'proof of concept' validation to Catalog form `Services > Catalogs > Catalogs > Configuration > New/Edit` (it controlls if name is available)
* Updates data-driven-form renderer to suppor function validators
* **Updates Typescript to latest and allowed synthetic default export** (to support the library)
**Before**
**After**
@terezanovotna
> Added promise debounce library (with updated typescript) and async validation in Catalog form

- app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
- app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
Solves: https://bugzilla.redhat.com/show_bug.cgi?id=1595558
Adds two new fallback text fields for hostname.
@h-kataria @alexander-demichev  do you know what labels should be assigned to these fields? Field names in model have been assigned based on this: https://github.com/ManageIQ/manageiq-providers-openstack/pull/394/files#diff-6f9b687ce51fd31aa102fa9305ef2501R148
@himdel @martinpovolny I would like to go and start converting this form into react data driven forms. Even though this was a small and relatively "safe" change i am afraid it introduces another technical debt and further diminishes maintainability. Your thoughts?
> Added hostname fallback fields for openstack amqp events.

- package.json
Currently travis is failing  on jest specs. Caused by: https://github.com/airbnb/enzyme/issues/2046
I've temporarily locked version of enzyme-adapter-react-16 to latest working.
example of failing job: https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/505693381
> Lock enzyme adapter version to stop failing travis.

- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ops_controller/settings/common_spec.rb
Fixed couple of scenarios
- Updated code to use `get_worker_setting` method
- Worker memory threshold of 1 GB or above was not reflected on Workers tab because https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/ops_controller/settings/common.rb#L997 value of variable `x` needs to be converted to integer value from a float so value can be selected correctly in the drop down.
- If a value in yaml config file is set to as 600.megabytes, it is being returned as a string, so need to evaluate/convert the value so it can be correctly selected in the drop down.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656873
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1658373
(cherry picked from commit 6a20b57e7b6268ff14c43f778b48ced5387568bf)
backport of …
> [HAMMER] - Fixed display of worker memory threshold settings

- app/views/layouts/_tree.html.haml
As we discussed it here: https://github.com/ManageIQ/manageiq-ui-classic/pull/5290#issuecomment-469290530 (merge this only after that's in)
> Make hakiri stop complaining about the controller param in trees

- app/presenters/tree_builder_services.rb
- spec/presenters/tree_builder_services_spec.rb
The `Services - My Services` screen can be super slow if having too many services. The left side tree always displays all the services, but the right side GTL has pagination and search. So the nodes on the left side can cause a performance problem and they are also redundant.
I'm doing basically the same thing as we did with the VMs and Templates, but not making it optional. The reason for this is my plan to replace this and other "flat" trees with similar redundancy with a listnav. Having listnavs instead of trees is way easier to maintain or rewrite if we want to get rid of the explorers.
If @kbrock says so, this PR replaces https://github.com/ManageIQ/manageiq-ui-classic/pull/5328
I already talked with @terezanovotna about the listnavs, and she said OK, but adding the UX review label. …
> Hide services from the Services tree as its redundant and slow

- app/controllers/application_controller/automate.rb
- app/controllers/miq_policy_controller/rsop.rb
- app/controllers/planning_controller.rb
There were some controllers that were setting the `@accords` instance variable for screens that not even have accordions. These are unnecessary as the only place we iterate through the `@accords` is when we're rendering left side explorer trees. Anyway, we should not set the variable explicitly as it is being generated from the `features` using `build_accordions_and_trees`.
@miq-bot add_label cleanup, technical debt, trees, explorers, hammer/no
> Drop the unnecessary accords instance variable from some controllers

- app/presenters/tree_builder_services.rb
before #5290, `allow_reselect` needs to live in `set_locals_for_render`, not `tree_init_options`
This fixes the hammer backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/5335 to do just that.
https://bugzilla.redhat.com/show_bug.cgi?id=1686433
> [HAMMER] TreeBuilderServices - move allow_reselect to `set_locals_for_render`

- app/controllers/report_controller/reports/editor.rb
those constants were moved to the core 
https://github.com/ManageIQ/manageiq/pull/18561
https://bugzilla.redhat.com/show_bug.cgi?id=1545445 (second part)
https://github.com/ManageIQ/manageiq/pull/18561
> Remove constants ALLOWED_FIELD_SUFFIXES from Reports::Editor

- app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
The Openstack and Amazon providers both theoretically support resizing volumes, but currently detection of this feature is done in the UI via a conditional on the class name of the provider. This PR allows the field to be enabled via feature detection.
Depends on https://github.com/ManageIQ/manageiq/pull/18560
See also ManageIQ/manageiq-providers-openstack#448
> Use supports_volume_resizing? to toggle the Volume size field

- app/presenters/tree_builder_alert_profile_obj.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_smartproxy_affinity.rb
- app/presenters/tree_builder_tags.rb
- spec/presenters/tree_builder_belongs_to_hac_spec.rb
- spec/presenters/tree_builder_belongs_to_vat_spec.rb
- spec/presenters/tree_builder_smartproxy_affinity_spec.rb
Since #5304, there's no default `onclick` handler for treebuilders, therefore, overriding it to `false` is totally unnecessary.
> Remove unnecessary `:onclick => false` local from TreeBuilders

- app/presenters/tree_builder_network.rb
- app/presenters/tree_builder_storage_adapters.rb
The `miqOnClickHostNet` function doesn't use the `click_url` local at all, so it is totally unnecessary to set it.
> Drop the click_url from TreeBuilder locals for miqOnClickHostNet

- app/controllers/mixins/ems_common/angular.rb
- app/controllers/mixins/ems_common_angular.rb
- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ops_controller/settings/common_spec.rb
- spec/spec_helper.rb
@himdel @jrafanie Please review.  This gets us one step closer to removing MiqPassword from manageiq-gems-pending
> Remove references to MiqPassword

- app/controllers/ops_controller/ops_rbac.rb
**Fixes issue:**
https://github.com/ManageIQ/manageiq-ui-classic/issues/5140
**What:**
Fix creating a group (_Configuration > Access Control > Groups_) for the second time, after a validation message like '...already exists' appears.
1. Go to _Configuration > Access Control > Groups_ accordion
2. _Configuration > Add a new Group_ and create a group
3. Try to create another group with the same name as from step 2
=> error flash message occurs
4. Follow the message and change the name of the new group, press _Add_ button
=> nothing happens in the UI + error in log:
```
[----] I, [2019-03-19T17:28:55.994747 #11522:2ad94de6c2f0]  INFO -- : Started POST "/ops/rbac_group_edit?button=add" for ::1 at 2019-03-19 17:28:55 +0100
[----] I, [2019-03-19T17:28:56.033217 …
```
> Fix creating a group after validation message 'already exists'

- app/controllers/application_controller/miq_request_methods.rb
In #3928 was added tooltip for Volume tab in provision form. However, this sometimes causes problems when Template is not found and breaks the form. Because Provision form is used for multiple usecases (Provision, Clone, Publish,...?) and it is not clear when it could fail I think safest solution is just wrap it in try-catch block. I am not very satisfied with this, but it fixes the issue and it doesn't add to much complexity.
https://bugzilla.redhat.com/show_bug.cgi?id=1687946
Related PRs:
https://github.com/ManageIQ/manageiq-ui-classic/pull/3928
https://github.com/ManageIQ/manageiq-ui-classic/pull/4511
Try to Provision, Clone, Publish VM
ping @skateman
> Don't throw exception when template is not found in Provisioning

- app/controllers/miq_policy_controller.rb
The RBAC roles were not set in the `features` hash under `Control -> Explorer`. First I added the missing roles and then replaced the accordion/tree building with the common method used in all other explorer screens.
@miq-bot add_label refactoring, rbac, control, hammer/no
cc @lpichler to take a look as it is related to :lock: **RBAC** :zipper_mouth_face:
> Enforce RBAC roles on Control -> Explorer accordions consistently with other explorers

- app/assets/javascripts/miq_tree.js
- app/presenters/tree_builder.rb
- app/presenters/tree_builder_clusters.rb
- app/presenters/tree_builder_datastores.rb
- app/presenters/tree_builder_sections.rb
- app/views/layouts/_tree.html.haml
- spec/presenters/tree_builder_clusters_spec.rb
- spec/presenters/tree_builder_datastores_spec.rb
- spec/presenters/tree_builder_sections_spec.rb
We were using two different locals for handling checkboxes in trees. Some of the trees were using `oncheck` and others `onselect`. Hereby I am merging these two into `oncheck` and also unifying the method signatures for handling these events.
The affected trees are on the compare and capacity and utilization collection screens.
> Unify onselect with oncheck across trees with checkboxes

- app/views/shared/views/ems_common/angular/_form.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1519359
`Compute` > `Clouds` > `Providers` > `Edit selected` (Azure) / `Add a new Cloud Provider` 
**Expected results**
Subscription ID should be 
* required field when adding an Azure Provider 
* a read only field when edititng existing Azure provider.
**Before**
**After**
> Subscription ID is required when adding, readOnly when editing (Azure)

- app/controllers/application_controller/tags.rb
- spec/controllers/application_controller/tags_spec.rb
Fixed condition to use correct feature id when goign to tagging from summary screen directly. https://github.com/ManageIQ/manageiq-ui-classic/pull/4843 did not cover all scenarios.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1684472
@hstastna can you please test/review.
> Fixed condition to use correct feature id

- spec/controllers/ops_controller/ops_rbac_spec.rb
**PR:** https://github.com/ManageIQ/manageiq-ui-classic/pull/5354
**Original issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/5140
This PR just adds missing spec for the fix for creating group for the second time, after a validation message like 'Description is not unique...' appears, also adds little improvements of some other specs there (`context` vs. `describe` etc.).
@miq-bot add_reviewer @skateman
> Add spec for the fix for creating group after validation message

- package.json
This reverts 8e7b987 (https://github.com/ManageIQ/manageiq-ui-classic/pull/4495),
because now the old version of `@babel/runtime` is causing an issue with react-transition-group 2.7.0 (not 2.6.1):
ERROR in ./node_modules/react-bootstrap/node_modules/react-transition-group/esm/Transition.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/inheritsLoose' in '/Users/gpiatigorski/dev/manageiq/plugins/manageiq-ui-classic/node_modules/react-bootstrap/node_modules/react-transition-group/esm'
A current version of `@babel/runtime` works, and doesn't break `react-bootstrap` (0.32.4) anymore,
and we still don't depend on it directly, so removing the dependency.
> Remove @babel/runtime dependency workaround

- product/views/Service.yaml
This will use an inline view for the services page.
This cuts back on the amount of virtual attribute work the database
performs.
We are slowly rolling this out to reduce testing efforts / introducing
regressions
This depends upon https://github.com/ManageIQ/manageiq/pull/18543
but it can be merged before that PR, as it will be a NOP
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1686433
For one customer in particular, these 2 PRs speeds up the `/services/report_data` a bit:
|         ms |     bytes |   objects |query |    qry ms |     rows |`comments`
|        ---:|       ---:|       ---:|  ---:|       ---:|      ---:| ---
|  445,306.4 | 1,694,049 |    10,177 |    6 | 445,251.6 |       25 |`before-7-attributes`
|    1,252.4 | 1,754,293 |    10,984 |    6 |   1,197.6 |       25 …
> Services use turbo button

- app/controllers/miq_policy_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
See https://github.com/ManageIQ/manageiq-ui-classic/pull/5369
Changes which happened during the review and merge process affected the breadcrumb mixin
> [Failing Travis - Breadcrumbs] Fix container > role and x_active_tree in breadcrumbs

- app/services/network_topology_service.rb
If VM doesn't have ExtManagemntSystem UI blows up, so I have added safeguard for that. However I am not sure if it should be possible to get into such state.
https://bugzilla.redhat.com/show_bug.cgi?id=1684649
Have a VM that doesn't  belong to ExtManagemntSystem
Go to Network -> Topology
> Add safeguard for VMs without ext_management_system

- app/controllers/ops_controller/settings/schedules.rb
- app/helpers/application_helper/toolbar/miq_report_schedule_center.rb
- app/helpers/application_helper/toolbar/miq_schedule_center.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1559335
Go to:
- Configuration -> Settings -> Schedules -> click on one -> Configuration -> Enable/Disable this Schedule
- Cloud Intel -> Reports -> Schedules -> click on one -> Configuration -> Enable/Disable this Schedule
Before:
After:
@miq-bot add_label wip, bug
> Add Enable/Disable button to Schedule summary page

- app/assets/javascripts/components/cloud_network/cloud-network-form.js
- app/views/static/cloud_network/cloud-network-form.html.haml
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1649280
`Networks > Networks > Configuration > Add a new Cloud Network` 
| type  | physical_network | segmentation_id    |
|-------|------------------|--------------------|
| flat  | required         |                    |
| gre   |                  | required (GRE ID)  |
| vlan  | required         | required (VLAN ID) |
| vxlan |                  |                    |
As you can see in the table, some fields should be required, but they are not.
FLAT -> segmentation_id not needed
GRE -> segmentation_id is GRE ID
VLAN -> segmentation_id is VLAN ID
VXLAN -> segmentation_id not needed
Physical network:
It isn't required for VXLAN and GRE
But VLAN and Flat do require it. In which case the value is provided by a logical name (mapping to a …
> Fixes segmentation_id and physical_network required (in Cloud Network form)

- app/controllers/vm_common.rb
Missed the initialization call of this tree in #5309, fixing.
https://bugzilla.redhat.com/show_bug.cgi?id=1692537
> Fix missed argument change for compliance history tree

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_alert_profile_obj.rb
- app/presenters/tree_builder_automate.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_clusters.rb
- app/presenters/tree_builder_datacenter.rb
- app/presenters/tree_builder_datastores.rb
- app/presenters/tree_builder_default_filters.rb
- app/presenters/tree_builder_diagnostics.rb
- app/presenters/tree_builder_genealogy.rb
- app/presenters/tree_builder_menu_roles.rb
- app/presenters/tree_builder_miq_action_category.rb
- app/presenters/tree_builder_network.rb
- app/presenters/tree_builder_ops_rbac_features.rb
- app/presenters/tree_builder_protect.rb
- app/presenters/tree_builder_sections.rb
- app/presenters/tree_builder_smartproxy_affinity.rb
- app/presenters/tree_builder_snapshots.rb
- app/presenters/tree_builder_storage_adapters.rb
- app/presenters/tree_builder_tags.rb
- spec/presenters/tree_builder_alert_profile_obj_spec.rb
- spec/presenters/tree_builder_belongs_to_hac_spec.rb
- spec/presenters/tree_builder_belongs_to_vat_spec.rb
- spec/presenters/tree_builder_clusters_spec.rb
- spec/presenters/tree_builder_datastores_spec.rb
- spec/presenters/tree_builder_genealogy_spec.rb
- spec/presenters/tree_builder_protect_spec.rb
- spec/presenters/tree_builder_sections_spec.rb
- spec/presenters/tree_builder_smartproxy_affinity_spec.rb
- spec/presenters/tree_builder_tags_spec.rb
This last move makes the `set_locals_for_render` redefinitions empty, so removing them completely.
@miq-bot add_label trees, hammer/no, refactoring
> Move event handling settings from locals to options in TreeBuilder

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_clusters.rb
- app/presenters/tree_builder_datastores.rb
- app/presenters/tree_builder_default_filters.rb
- app/presenters/tree_builder_protect.rb
- app/presenters/tree_builder_tags.rb
- app/views/layouts/_tree.html.haml
- spec/presenters/tree_builder_belongs_to_hac_spec.rb
- spec/presenters/tree_builder_belongs_to_vat_spec.rb
- spec/presenters/tree_builder_clusters_spec.rb
- spec/presenters/tree_builder_datastores_spec.rb
- spec/presenters/tree_builder_protect_spec.rb
- spec/presenters/tree_builder_tags_spec.rb
Some trees with checkboxes highlighted the nodes that have been changed by the user in the current session. I think we should be consistent with this and have it for each tree or none. This would also allow us to drop a parameter from the options in `TreeBuilder` classes.
So the question is to have or not have this globally ...
@miq-bot add_label question, trees, ux/review, hammer/no
cc @terezanovotna as this is UX-related
> Highlight changes from default on all trees with checkboxes

- app/controllers/application_controller.rb
- app/controllers/configuration_controller.rb
- app/controllers/vm_common.rb
- app/controllers/vm_infra_controller.rb
- app/presenters/tree_builder.rb
- app/presenters/tree_builder_archived.rb
- app/presenters/tree_builder_images.rb
- app/presenters/tree_builder_instances.rb
- app/presenters/tree_builder_vandt.rb
- app/presenters/tree_builder_vms_and_templates.rb
- app/views/configuration/_ui_2.html.haml
- spec/controllers/vm_common_spec.rb
- spec/presenters/tree_builder_archived_spec.rb
- spec/presenters/tree_builder_images_spec.rb
- spec/presenters/tree_builder_instances_spec.rb
- spec/presenters/tree_builder_spec.rb
- spec/presenters/tree_builder_vms_and_templates_spec.rb
@ZitaNemeckova introduced a feature a few years ago to increase the performance of some trees by hiding the VM nodes. This optional feature could be still turned off under `My settings`, so it's optionally still possible to cause performance problems. As I've discussed with @lavenel and @dmetzger57 I am proposing to make this setting permanent, not exposing the setting to the user.
This would allow us to delete a lof of logic and so making our codebase a little bit simpler.
> Permanently hide the VMs where it was possible to optionally display them

- app/assets/javascripts/miq_application.js
We missed this when the new breadcrumbs were merged...
**Before:**
**After:**
> Adjust accordion height calculation hack to the new breadcrumbs

- app/views/miq_request/_prov_field.html.haml
- app/views/shared/views/_prov_dialog.html.haml
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1614567
Allow user to select Network Port or Cloud Network when provisioning
an OpenStack cloud instance.
This PR also relates to associated manageiq (https://github.com/ManageIQ/manageiq/pull/18303 ) and manageiq-providers-openstack (https://github.com/ManageIQ/manageiq-providers-openstack/pull/416 ) PRs,
but this PR can be pushed before the others -- it shouldn't depend on their code for the build to pass.
> bug 1614567: Allow user to select Network Port for provisioning

- app/presenters/tree_builder_servers_by_role.rb
- spec/presenters/tree_builder_servers_by_role_spec.rb
This is as inconsistent behavior, there should be a preselected node with its details shown on the right side. The right side data was all there, however, the appropriate node was not highlighted. Now when you navigate to the page, it should preselect the node. 
> Fix preselect node in servers by roles tree under diagnostics

- app/controllers/application_controller/policy_support.rb
- app/views/layouts/_policy_sim.html.haml
- app/views/layouts/_x_edit_buttons.html.haml
- config/routes.rb
- spec/controllers/application_controller/policy_support_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1659088
https://bugzilla.redhat.com/show_bug.cgi?id=1686617
**What:**
Add the missing button to the page for policy simulation of VMs/Instances which were displayed as a nested list (displayed from Relationships table of for example selected infra/cloud provider).
**Steps to reproduce:** (one of possible scenarios)
1. Go to _Compute > Infra > Providers_ and click on some provider
2. Display VMs/Templates from _Relationships_ table (or click on VMs/Templates from dashboard)
2. Choose some of the items, check their checkboxes (at least one item)
3. Choose _Policy > Policy Simulation_
=> no _Cancel_ button, not able to cancel policy simulation!
**Note:**
Cancel button is present and not missing, if we access VMs/Instances directly, thru …
> Add Cancel button to policy simulation page

- app/helpers/physical_server_helper/textual_summary.rb
- app/helpers/physical_storage_helper/textual_summary.rb
- spec/helpers/physical_server_helper/textual_summary_spec.rb
- spec/helpers/physical_storage_helper/textual_summary_spec.rb
Code responsible for retrieving the room data used the invalid room_id key. This commit changes the key and associated display fields accordingly.
> Fix room display in physical infra summary views

- app/assets/javascripts/miq_tree.js
- app/views/service/_svcs_show.html.haml
When I hid the services in #5335 we didn't count with the fact that services might be nested into each other. Unfortunately, the child service access is only doable through the `tree_select` route and it has been accessed by `miqTreeActivateNode`. Without the node actually being in the tree, this function did nothing and so the child services weren't accessible.
I'm proposing a workaround to call the `tree_select` directly from the `miqTreeSelect` function. This is not a permanent solution, these areas where we access items exclusively through `tree_select` should be refactored.
Navigating back to the parent service in hammer can be done using the toolbar's back button, in upstream we should also update the breadcrumb generation logic to contain the hierarchy. 
@miq-bot add_label bug, …
> Fix the access to child services from parents under My Services

- app/assets/javascripts/miq_tree.js
- app/controllers/ops_controller/diagnostics.rb
- app/presenters/tree_builder.rb
- app/presenters/tree_builder_diagnostics.rb
- app/presenters/tree_builder_roles_by_server.rb
- app/presenters/tree_builder_servers_by_role.rb
- app/views/layouts/_tree.html.haml
- spec/presenters/tree_builder_roles_by_server_spec.rb
- spec/presenters/tree_builder_servers_by_role_spec.rb
The `Servers by Roles` and `Roles by Servers` trees under the `Settings -> Diagnostics` screen were setting and accessing the `@sb[:diag_selected_id]` and `@sb[:diag_selected_model]` variables from the session. These variables are used to determine what should be rendered on the right side from the tree, i.e. the details of the selected node. If there was no node selected, it has been also used for highlighting the first node.
Inside the tree this can be substituted with the `:selected_node` key from the `TreeState` which already includes the first node if nothing is selected. So instead of setting these variables inside the tree, I'm retrieving the node from the tree's state after the `TreeBuilder` has done its work. To be able to still highlight the right node, I leveraged the …
> Extract the sandbox variables from the Roles/Servers TreeBuilders under Diagnostics

- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ops_controller/settings/common_spec.rb
Memory Threshold value of C & U Data Collectors, Refresh, VM Analysis Collectors workers on fresh appliance was not showing correctly.
- Changed range calculation in the .step that sets the values for the drop down, to fix the issue where in rails the default config value of 2.gigabytes is converted to 2147483648 but the calculations in the .step method was generating that as 2147483644 causing the values to not match and not display the right one selected in the drop down.
- Fixed the fetching of worker setting for MiqEmsMetricsCollectorWorker worker to be the same format as other workers.
- Added additional value in VM Analysis Collectors drop down, because default for that in config is set to 2.gigabytes and drop down did not have that value present.
Fixes …
> Fixed display of default memory threshold correctly on new appliance

- app/controllers/vm_common.rb
- app/presenters/tree_builder_snapshots.rb
- app/views/vm_common/_snapshots_tree.html.haml
- spec/presenters/tree_builder_snapshots_spec.rb
Removing some :spaghetti: from the `TreeBuilderSnapshots` around the highlighted last node. The logic responsible for selecting the node has been moved into the redefinition of `active_node_set`. Instead of the instance variable, the tree state is ~~ab~~used to store the active node. This allows us to use the `silent_activate` parameter and to drop some javascript too.
> Select the latest snapshot using x_node and with silent_activate

- app/controllers/miq_ae_class_controller.rb
Solves https://github.com/ManageIQ/manageiq-ui-classic/issues/5391
**How to reproduce**
1. Go to `Automation` > `Automate` > `Explorer`
2. Choose some method
3. Look on breadcrumbs (they are OK)
4. Do some action on selected method (eg. edit) and cancel it
5. Look on breadcrumbs again (there is one more)
When Breadcrumb mixin creates explorer controller's breadcrumbs and if `@sb[:action]` is not null it appends a breadcrumb item with the header title. So, when a user cancel the action, the action is still preserved in the `@sb` variable.
**Solution**
Clear this variable after save/cancel actions properly.
@miq-bot add_label bug, hammer/no, automation/automate
> Cancel and save buttons clear @sb[:action] in miq_ae_class

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/miq_ae_class_controller.rb
- app/helpers/automate_tree_helper.rb
- app/presenters/tree_builder_ae_class.rb
- app/presenters/tree_builder_automate.rb
- spec/controllers/catalog_controller_spec.rb
- spec/controllers/miq_ae_class_controller_spec.rb
- spec/presenters/tree_builder_ae_class_spec.rb
- spec/presenters/tree_builder_automate_spec.rb
There are four levels of inheritance for automate trees:
* `TreeBuilderAeClass` - used on the left side on `Automate -> Explorer`
* `TreeBuilderAutomate` - used for catalog entrypoing selection and copying stuff in the automate explorer
* `TreeBuilderAutomateEntrypoint` - used in `TreeController` for entrypoint selection in the dialog editor
* `TreeBuilderAutomateInlineMethod` - used in `TreeController` for embedded methods selection
The rebuilding of `TreeBuilderAeClass` was called inconsistently compared to the other controllers, so I leveraged the `build_replaced_trees` helper method. The `build_ae_tree` was calling both the `TreeBuilderAeClass` and `TreeBuilderAutomate`, so I extracted the `build_automate_tree` from it. I also found some logic in the `TreeBuilderAeClass` that has been …
> Clean up and move logic between the TreeBuilder classes for automate

- app/controllers/vm_common.rb
- app/presenters/tree_builder_genealogy.rb
- spec/presenters/tree_builder_genealogy_spec.rb
Fixes #5401 as we discussed there with @terezanovotna, the information in the parentheses (parent/selected) is redundant and it can be removed. I also cleaned up the selected node detection and highlighting so the `override` method could be dropped completely.
**Before:**
**After:**
@miq-bot add_label trees, refactoring, ux/review, hammer/no
> Remove redundant information from the genealogy tree, refactor the code a little

- app/presenters/tree_builder_catalog_items.rb
The `:svvcat` is definitely a typo of `:svccat`, but the tree type is `sandt` so the conditional would be `false` anyway.
> Drop always false tertiary conditional from TreeBuilderCatalogItems

- app/presenters/tree_builder_datacenter.rb
This argument is not used at all, therefore no need of it :scissors: :fire: :toilet: 
@miq-bot add_label cleanup, hammer/no, trees
> Drop the unnecessary type argument inject from TreeBuilderDatacenter

- app/presenters/tree_builder_vat.rb
It isn't needed at all on the last call, so not necessary to send it.
@miq-bot add_label cleanup, hammer/no, trees
> Drop the unnecessary type argument injection from TreeBuilderVat

- app/presenters/tree_builder_utilization.rb
The `@type` here will be always `bottlenecks` or `utilization`, therefore, the conditional is always `true`. 
> Drop always true conditional on TreeBuilderUtilization

- app/presenters/tree_builder_ops.rb
- app/presenters/tree_builder_ops_vmdb.rb
The only common method has a condition for the `vmdb` tree, it can be moved over.
> Do not inherit the TreeBuilderOpsVmdb from TreeBuilderOps

- app/views/miq_policy/_action_details.html.haml
Add missing "form-control-static" class to Action Details screen
Old
New
> Action Details screen styling fix

- app/presenters/tree_builder_utilization.rb
The tree always has one of these types, so no need for the test.
> Drop always true condition from TreeBuilderUtilization

- app/controllers/application_controller.rb
- app/helpers/vm_helper/textual_summary.rb
- app/views/ops/_rbac_group_details.html.haml
- app/views/ops/_rbac_role_details.html.haml
- app/views/ops/_rbac_user_details.html.haml
- app/views/report/_report_info.html.haml
- product/views/MiqReportResult-all.yaml
- product/views/MiqReportResult.yaml
- product/views/MiqWidget.yaml
- spec/helpers/vm_helper/textual_summary_spec.rb
Description of problem
When used with Service Now Portal, CFME is communicating over API with IDs of VMs, Reports, Report results, etc. When something is needed to be troubleshooted, or checked, the user needs also to go to the API and drill for the names. This makes troubleshooting efforts difficult and slow.
Actual results
No item IDs visible in the GUI.
Expected results
Item IDs visible in the GUI.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1638245
Additional info
BZ targets CloudForms 4.6 so if merge PR need to be backport to 4.6 as well
@martinpovolny opened up a new PR with changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/4791 with a fix for your comment https://github.com/ManageIQ/manageiq-ui-classic/pull/4791#discussion_r236382928
Please take a look.
> Display IDs of VMs,Reports,Result,... 

- app/javascript/components/breadcrumbs/index.js
- app/javascript/components/catalog-form/catalog-form.jsx
- app/javascript/components/flavor-form/flavor-form.jsx
- app/javascript/components/service-form/index.jsx
- app/javascript/components/set-service-ownership-form/index.jsx
- app/javascript/components/vm-server-relationship-form/index.jsx
- app/javascript/miq-component/registry.ts
- app/javascript/spec/miq-component/miq-component.spec.js
Due to an async nature of React mounting/unmounting components from VirtualDOM, @martinpovolny has found and issue when the component was not cleared properly even if the cleanViertualDOM function was called. This caused component being unmounted after the new one was registered which caused overriding component ID and old component not cleared from virtualDOM.
This happens if the clean method is not called in constructor - in any functional component. Creating classes for every component just to call clean method is not convenient.
Also calling this function manually is not efficient.
There are several places where we could run this autimatically
- `ManageIQ.explorer.processReplaceRightCell` - there is no clear place where tu put this one. Clean method must be called after the React …
> Added automatic virtual DOM clean up.

- app/assets/javascripts/miq_application.js
- app/assets/javascripts/miq_tree.js
Compute > Infrastructure > VMs
pick a VM with a parent/child (`vm.add_parent(other_vm); vm.save!`)
click Genealogy in textual summary
check 2 checkboxes
the compare toolbar button should work now
miqSetButtons is not only called for toolbars, but also fake toolbars,
so, we can't always update the toolbar count when nonzero.
But for specific cases we can - so splitting the functionality into miqSetToolbarCount,
which will always set the count for toolbars.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1694712
Fixes #64
> miqSetToolbarCount - fix setting toolbar counts

- app/assets/javascripts/miq_tree.js
- app/controllers/catalog_controller.rb
- app/controllers/miq_ae_class_controller.rb
- app/controllers/mixins/sandbox.rb
- app/helpers/automate_tree_helper.rb
- app/presenters/tree_builder_automate.rb
- app/presenters/tree_builder_automate_catalog.rb
- app/presenters/tree_builder_automate_entrypoint.rb
- spec/presenters/tree_builder_automate_catalog_spec.rb
- spec/presenters/tree_builder_automate_spec.rb
As far as I was able to determine, the `TreeBuilderAutomate` is being used in the automate explorer when you try to copy a method/instance/class to a custom destination AND for automate entrypoint selection in catalog items. The `name` of the tree is always the same, but the `type` is different based on where it is being used. However, we do a lot of checks against this type and also against other session variables that aren't shared between the two controllers.
To avoid these checks, I've extracted the `TreeBuilderAutomateCatalog` tree and removed all the aforementioned logic. The `build_automate_tree` method has been adjusted to take an extra argument that decides which tree should be built. This will allow us to get rid of the redundancy between the tree name and tree type by dropping …
> Extract the catalog entrypoint selection from TreeBuilderAutomate

- app/assets/javascripts/components/cloud_subnet/cloud-subnet-form.js
- app/controllers/cloud_subnet_controller.rb
- app/helpers/cloud_subnet_helper/textual_summary.rb
- app/views/static/cloud_subnet/cloud-subnet-form.html.haml
- spec/controllers/cloud_subnet_controller_spec.rb
- spec/helpers/cloud_subnet_helper/textual_summary_spec.rb
- spec/javascripts/components/cloud_subnet/cloud_subnet_form_spec.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650396
Allocation pools, DNS Nameserver, Host Routes to Subnet CRUD were
included in Subnet show view, but were missing in the create
and update forms.
This commit adds those fields.
> BZ1650396: Add Allocation pools, Nameserver, Host Routes to Subnet UI

- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/ops_controller.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
- spec/controllers/ops_settings_spec.rb
- spec/controllers/pxe_controller_spec.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5375
1. Configuration ➛ Settings ➛ Schedules
2. Select a schedule from the list view
3. Configuration ➛ Enable / Disable this schedule
4. See the messed up breadcrumbs
* replaces the breadcrumbs condition to recognize when mixin is in explorer controller (after enabling/disabling the mixin is confused and thinks it is in a not-explorer controller)
* features should always define if the controller is explorer/not-explorer
* plus clears `@sb[:action]` when `tree_select` in `ops_controller`
* plus clearing specs of removed show_list_title option
* plus checks if `@right_cell_text` and `accord_title` exist before calling them
**Before**
**After**
> Fixes breadcrumb when disabling/enabling schedules

- app/controllers/ops_controller/settings/common.rb
Issue: 
When settings value added on root level (without category) attempt to execute `copy_hash(hashin)` will raise  ` [NoMethodError] undefined method 'deep_clone'...`
Example:
execute `curl --user admin:smartvm -i -X PATCH -d '{"some_key": false}' http://<host>/api/servers/3/settings` will add `:some_key: false` settings on the top level
BEFORE:
AFTER:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695566
> Fix: error loading configuration screen when key/value settings exists on top level

- app/controllers/application_controller/tags.rb
There were present two form buttons groups, one from Tagging component, second from `x_edit_buttons.html.haml`
This PR deletes the second one.
#5419
Screenshot from 2019-04-02 14-44-54
Go to Compute > Infrastructure > Datastore > Select One > Edit Tags
Go to Service > Catalogs > Catalogs item > Select One > Edit Tags
Configuration > Management > Providers
> Don't show x_edit_buttons for tagging screen

- .travis.yml
- Rakefile
- config/initializers/assets.rb
- manageiq-ui-classic.gemspec
- spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
- spec/javascripts/support/jasmine.yml
- spec/javascripts/support/jasmine_helper.rb
Right now, it looks like 9 out of the last 17 travis runs on master failed on spec:javascript:
```
* Listening on tcp://0.0.0.0:41063
Use Ctrl-C to stop
Waiting for jasmine server on 41063...
jasmine server started
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
Attempting to fix that.
The actual failure comes from phantomjs sometimes not managing to load the page, failing with:
```
ReferenceError: Can't find variable: SAFE_CLOSING
undefined:18 in exports
```
(details in …
> Jasmine - upgrade to 3.4.0, use chrome headless backend

- app/controllers/catalog_controller.rb
Remove form old buttons from Catalog Items -> Edit Tags screen.
This PR should fix the last remaining part of the issue.
#5383
Go to Service > Catalogs > Catalogs item > Select One > Edit Tags
@rvsia
> Remove x_edit_buttons from Catalog Edit Tags

- app/assets/javascripts/controllers/alerts/alerts_overview_controller.js
- app/assets/javascripts/controllers/container_dashboard/container_project_dashboard_controller.js
- app/assets/stylesheets/alerts.scss
- app/assets/stylesheets/patternfly_overrides.scss
- app/views/layouts/_center_div_no_listnav.html.haml
- app/views/shared/views/_show_alerts_overview.html.haml
This PR removes the unnecessary "miq-body" class from the Projects dashboard and Alerts Overview. The class created a  gray background behind the new breadcrumb.
Old
New
> Container Projects Dashboard & Alerts Overview fix

- app/controllers/report_controller/reports/editor.rb
- app/views/report/_form_columns.html.haml
- spec/controllers/miq_report_controller/reports/editor_spec.rb
- spec/helpers/report_helper_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1581817
**What:**
When choosing _Chargeback for Images/Projects/Vms_ under Configure Report Columns section while adding a new/editing an existing Report under _Cloud Intel > Reports > Reports_, some of the fields are not available. This is ok but there was a misunderstanding that those fields were missing there. This is why I am adding note about which fields are not supported to the Report editing screen.
1. Go to _Cloud Intel > Reports > Reports_ accordion
2. In toolbar, choose _Configuration > Add a new Report_ (or you can also edit an existing report)
3. Under _Configure Report Columns_, for _Base the report on_ choose one of _Chargeback for Images/Projects/Vms_
=> some of the fields are not available, for …
> Display info about unavailable fields while adding/editing report

- app/javascript/components/catalog-form/catalog-form.jsx
- app/javascript/components/catalog-form/catalog-form.schema.js
- app/javascript/helpers/promise-debounce.js
- app/javascript/spec/catalog-form/catalog-form.spec.js
- app/javascript/spec/catalog-form/validator.spec.js
- app/views/catalog/_stcat_form.html.haml
- package.json
`Services > Catalogs > Catalogs > Configuration > New/Edit`
- When editing the validation checks if the name already exists, but it did not check if the name already exists on the same catalog => now, it checks ids too
- updates data-driven-forms to latest
- adds options to debouncePromise to resolve all promises (this prevented submitting the form, because the unresolved promises was stuck and the form was still validating)
@miq-bot add_label hammer/no, services, react
@miq-bot add_reviewer @Hyperkid123
> Fix async validation in catalog form

- .travis.yml
Travis [announced](https://changelog.travis-ci.com/upcoming-python-default-version-update-96873) a switch to python 3 as default will happen on Apr 16th, 2019.
node-gyp relies on python 2.7 ([ref](https://github.com/nodejs/node-gyp#on-unix)), without node-gyp, `yarn` can fail installing a JS dependency (`node-sass` and `fs-ext` both have a `bindings.gyp`).
=> forcing default python version to 2.7 on travis
> Travis - force default python to 2.7

- config/routes.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1686619
1. Add some infra provider, if you don't have any
2. _Compute > Infra > Providers_
3. Choose some provider, click on it to display its dashboard or summary page
4. Click on _VMs_ in dashboard or summary page of the selected provider
5. Choose some VM(s), check the checkbox(es)
6. In the toolbar, choose _Policy > Policy Simulation_
7. Choose some policy profile
8.  Click on the quadicon of the VM
=> "The page you were looking for doesn't exist." Error!
In log:
```
[----] F, [2019-03-13T17:07:46.085981 #30030:44f7b90] FATAL -- : ActionController::RoutingError (No route matches [GET] "/vm_or_template/policies/3031")
```
**How reproducible:**
not always, try to add/remove more policy profiles or clicking on …
> Fix error while clicking quadicon after running policy simulation

- app/controllers/application_controller.rb
- app/controllers/mixins/more_show_actions.rb
- app/controllers/vm_common.rb
These session variables aren't used anywhere and the `tree_nodes` instance variable is obsolete, so removing...
@miq-bot add_label hammer/no, cleanup, trees
> Do not store JSON trees in the session

- app/controllers/utilization_controller.rb
- app/presenters/menu/default_menu.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1678196
> Menu Simplification: move Utilization from Optimize to Cloud Intel

- app/controllers/application_controller/miq_request_methods.rb
- app/controllers/mixins/more_show_actions.rb
- app/controllers/vm_common.rb
- app/views/host/_network_tree.html.haml
The following session variables are no longer used anywhere:
* `squash_open`
* `tree`
* `tree_name`
There was one single usage of the `tree_name`, but on that screen it was always set to nil, so :fire: 
@miq-bot add_label cleanup, technical debt, hammer/no
> Clean up some unnecessarily set session variables

- app/controllers/vm_common.rb
- spec/controllers/vm_common_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1688359
**What:**
Fix changing the title in Cloud Instance Policy Simulation page, after clicking on any quadicon (explorer screens).
1. Go to _Compute > Clouds > Instances_
2. Select some instance(s), check the checkbox(es)
3. In the toolbar, choose _Policy > Policy Simulation_
4. Select some Policy Profile from the drop down
=> check the title of the page (_Instance Policy Simulation_)
5. Click on a quadicon of the instance
=> the title has been changed! (_Virtual Machine Policy Simulation_)
6. Click on the _Back_ button
=> the title remains wrong, different to the title in step 4 !
_Notes:_
- for VMs, the title does not change
- sometimes it may lead to error, when clicking on quadicon (step 5), but that's …
> Fix changing title after clicking quadicon in Instance Policy sim page

- spec/presenters/tree_node/miq_product_feature_spec.rb
NOTE: original intention of this PR was not useful - so I removed it but we at least I added some specs.
> Add specs for tenant product feature in tree node

- app/helpers/application_helper/page_layouts.rb
- app/views/layouts/_center_div_no_listnav.html.haml
This PR adds a method to insure that Edit screens (reached from Angular dashboards) do not use a gray background.
Issue: #5438
Old
New
> Fix  Edit screen backgrounds

- app/helpers/application_helper/page_layouts.rb
This PR corrects a problem where Edit screens accessed from dashboards (as opposed to summary screens) do not display a title.
Issue: #5438
Old
New
> Fix missing Edit screen titles

- app/views/layouts/angular/_multi_auth_credentials.html.haml
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1543007
There was an issue with 'linering' validation status after tab change from RHV provider to VMWare provider.
Validation was enforced on VMRC Console tab event thought its required. After input change the validation corrected it self.
I've erplaced `ng-if` with `ng-show` which will place the tab always into DOM (but hide it) ainstead of completely remove it from DOM(like ng-if does). This will initialize the tab correctly and prevents lingering  validation.
I am still not sure what was causing the error but after 3 hours of debugging this is the only thing that actually worked.
> Swap ng-if with ng-show on VMRC Console in ems common.

- app/assets/javascripts/components/cloud_volume_backup/cloud-volume-backup-form.js
- app/controllers/cloud_volume_backup_controller.rb
- app/views/static/cloud_volume_backup/volume_select.html.haml
- spec/javascripts/components/cloud_volume_backup/cloud_volume_backup_form_spec.js
Allows choosing to restore a volume backup to a newly created volume, and adds a field for optionally naming that volume.
Partially implements https://bugzilla.redhat.com/show_bug.cgi?id=1514970
Depends on core and openstack provider PRs, as well as a new fog-openstack release.
> Allow restoring backups to new volumes

- app/views/miq_ae_customization/_dialog_sample.html.haml
Displays correct date&time if there is a default value set.
If no default time is set, current date will be displayed.
Links
* https://github.com/ManageIQ/ui-components/pull/373
* https://bugzilla.redhat.com/show_bug.cgi?id=1686077
> Showing default value for date/time picker in service dialog preview

- app/controllers/application_controller/explorer.rb
- app/controllers/automation_manager_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/miq_ae_customization_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/miq_policy_controller/alert_profiles.rb
- app/controllers/miq_policy_controller/alerts.rb
- app/controllers/miq_policy_controller/conditions.rb
- app/controllers/miq_policy_controller/events.rb
- app/controllers/miq_policy_controller/miq_actions.rb
- app/controllers/miq_policy_controller/policies.rb
- app/controllers/miq_policy_controller/policy_profiles.rb
- app/controllers/miq_template_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/mixins/manager_controller_mixin.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/service_controller.rb
- app/controllers/vm_cloud_controller.rb
- app/controllers/vm_common.rb
- app/controllers/vm_controller.rb
- app/controllers/vm_infra_controller.rb
- app/controllers/vm_or_template_controller.rb
- app/javascript/components/breadcrumbs/index.js
- app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
- spec/controllers/miq_policy_controller/conditions_spec.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5397
* **clears** `@sb[:action]` after saving/cancelling actions (this caused that there were additional breadcrumbs on non-action pages - the mixin thought that he is still on an action page and because of that, generated a breadcrumb with header)
* adds **two additional options** for breadcrumb options:
`hide_special_item` - use on controller, which contains all nodes in the tree and uses tagging (or other policies screens). Because there is the final node (the item which is tagged by user, etc.), the breadcrumb of the item has been already generated from the tree path, so there is no need to generate the tagged item breadcrumb anymore.
`show_header` - use on controllers, which do not contain all nodes in the …
> Fixing breadcrumbs issues in explorer controllers

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
When editing an existing catalog bundle, the entry points in the form are being set to the default. This was caused by a missing condition to test if the catalog bundle object is an unsaved one without an ID or an already existing that doesn't need the default entrypoints.
@miq-bot add_label bug, hammer/yes, services
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1698431
> Do not reset entrypoints when editing an existing catalog bundle

- app/helpers/ems_storage_helper/textual_summary.rb
- spec/helpers/ems_storage_helper/textual_summary_spec.rb
Remove Cloud Volume Types from summary page of non-OpenStack storage providers
or OpenStack Swift Provider
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650082
Storage -> Block Storage -> Managers -> click on non-Openstack storage provider or OpenStack Swift Provider
Before there's Cloud Volume Types in Relationships (last line):
After there's no Cloud Volume Types in Relationships:
For OpenStack Cinder Manager:
Before/After:
If you have no `CloudVolumeType` for OpenStack. Do this in console:
```
ems_id = ManageIQ::Providers::StorageManager::CinderManager.first.id
cvt = CloudVolumeType.create(:name => "name", :description => "description", :ems_id => ems_id)
cvt.save!
```
@miq-bot add_label wip, bug, hammer/yes, storage
> Hide CloudVolumeTypes for non-OpenStack storage providers

- app/controllers/application_controller/miq_request_methods.rb
- app/views/miq_request/_physical_server_provision_show.html.haml
- app/views/miq_request/_request.html.haml
- spec/controllers/miq_request_controller_spec.rb
Currently, PhysicalServerProvision details page was trying to fetch and display affected VMs (with given src_ids), instead PhysicalServers. With this commit we make sure it displays the correct model, see screenshot below:
(assigning @mzazrivec since he merged a very similar PR some time ago when we were fixing it for service retirement, see https://github.com/ManageIQ/manageiq-ui-classic/pull/4710)
> Show affected servers on PhysicalServerProvisionRequest details

- app/presenters/menu/default_menu.rb
- app/views/layouts/_user_options.html.haml
- spec/controllers/dashboard_controller_spec.rb
**Before:**
**After:**
According to @h-kataria the related failing specs aren't valid anymore, so deleting them :scissors: 
@miq-bot add_label enhancement, hammer/no, ux/review
Maybe the size of the `fa-cog` isn't the best, @epwinchell any ideas? Also cc @terezanovotna @loicavenel...
https://bugzilla.redhat.com/show_bug.cgi?id=1678196
> Menu Simplification: extract Configuration into the top-right bar

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_automation_manager_configured_systems.rb
- app/presenters/tree_builder_configuration_manager_configured_systems.rb
- app/presenters/tree_builder_configured_systems.rb
- app/presenters/tree_builder_images.rb
- app/presenters/tree_builder_images_filter.rb
- app/presenters/tree_builder_instances.rb
- app/presenters/tree_builder_instances_filter.rb
- app/presenters/tree_builder_template_filter.rb
- app/presenters/tree_builder_templates_images_filter.rb
- app/presenters/tree_builder_vandt.rb
- app/presenters/tree_builder_vms_filter.rb
- app/presenters/tree_builder_vms_instances_filter.rb
- spec/presenters/tree_builder_ae_customization_spec.rb
- spec/presenters/tree_builder_images_spec.rb
- spec/presenters/tree_builder_instances_spec.rb
It is totally unnecessary to make the `:leaf` option wander through the `TreeState` and back to the `TreeBuilder`, moving it into the `@root_class` instance variable.
> Remove the leaf option from TreeBuilders, replace it with @root_class

- app/services/git_based_domain_import_service.rb
- spec/services/git_based_domain_import_service_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1600961
This PR, along with a PR [manageiq-api/571](https://github.com/ManageIQ/manageiq-api/pull/571) will provide the support to allow the
API to be used to create a Git backed automation domain.
To fully support this new feature additional options are, sometime but not always
needed. If access to the GIT repo requires authentication credentials these
credentials need to be passed to the underlying automation engine.
This PR provides support to allow for passing additional optional arguments.
I purposely do not validate the additional optional arguments here, instead relying on
the underlying automation engine code to do so. This will avoid validating them multiple
times and allow for future enhancement to the automation engine to not …
> Add support for passing custom options for import_git_url

- app/controllers/ops_controller/settings/automate_schedules.rb
- spec/controllers/ops_controller/settings/automate_schedules_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1686762
**What:**
Creating schedule with _EVM Group_ and _Tenant_ under _Automation Tasks_ was giving internal server error. This PR fixes it.
For _EVM Group_, there was only _description_ column, instead of _name_.
For _Tenant_, there was a different problem:
```
ActiveModel::MissingAttributeError: missing attribute: use_config_for_attributes
from /home/hstastna/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.0.7.1/lib/active_record/attribute_methods/read.rb:66:in `block in _read_attribute'
```
I've tested all other options(types) and it worked well.
1. Go to _Configuration > Settings > Schedules_
2. _Configuration > Add a new Schedule_
3. For _Action_, choose _Automation Tasks_
4. For _Type_, …
> Fix internal server error while creating schedule with EVM Group/Tenant option

- app/controllers/cloud_network_controller.rb
Adds missing missing breadcrumb in 
`Networks` > `Networks` > `Cloud Networks` > select one which is editable > `Configuration` > `Edit`
**Before**
**After**
> Adds missing breadcrumb in cloud network edit form

- app/presenters/tree_builder_automate_inline_method.rb
This argument is not necessary and causes and exception as the `has_kids_for` definition doesn't emit the type.
@miq-bot add_label bug, trees, cleanup, hammer/no
> Drop unnecessary optional argument from TreeBuilderAutomateInlineMethod

- app/controllers/application_controller/tree_support.rb
This line is no longer necessary since there are two separate trees for catalog entrypoint selection and automate copying.
@miq-bot add_label trees, hammer/no, cleanup
> Do not modify the tree type on catalog entrypoint lazy load

- spec/controllers/report_controller/schedules_spec.rb
Fixes:
Failures:
1) ReportController#schedule_edit reset rbac testing
Failure/Error: expect(expected_id).to eq(schedule.id)
expected: 66000000000038
got: 66000000000039
this is happening because resetting a form means calling `checked_or_params` to get the id of the schedule being editted, but the function was mocked to always give all the schedules.
So the sporadic failure was happening when the right schedule was second in the list, instead of first :).
Cc @CZJanRichter (only if you're still interested :) )
`hammer/yes` because this came in https://github.com/ManageIQ/manageiq-ui-classic/pull/3884
> Schedules spec - fix sporadic failure

- app/views/ems_container/_show_dashboard.html.haml
- app/views/ems_container/show_dashboard.html.haml
**Fixes BZ:**
https://bugzilla.redhat.com/show_bug.cgi?id=1667178
**What:**
This PR fixes/enables displaying missing flash messages for tagging in Container Provider Dashboard view.
1. Add an Openshift provider, if you don't have any
2. Navigate to _Compute > Containers > Providers_ and select some Openshift provider
3. Choose _Policy -> Edit Tags_
4. Add a tag and click on _Save_ or _Cancel_ button
=> no flash message on the dashboard!
**Additional info:**
No need to set and save any tag (step 4), you can just click on _Cancel_ button.
Flash message about canceling tagging should be displayed, and it was not displayed.
For Infra and Cloud providers, this works well.
---
**Before:** (canceling or editing tags - no flash message being displayed)
**After:** …
> Display missing flash messages for tagging in Container Provider Dashboard

- app/javascript/components/flavor-form/flavor-form.jsx
- app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap
- app/javascript/spec/flavor-form/flavor-form.spec.js
`Compute` > `Clouds` > `Flavors` > `Configuration` > `Add a new Flavor`
Missing loading state causes that the first select gets an empty array instead of fetched options.
**Before**
**After**
@miq-bot add_label hammer/no, compute/cloud, react, bug
@miq-bot add_reviewer @Hyperkid123
> Adds loading state to flavor form

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_catalogs_class.rb
- app/presenters/tree_builder_configuration_manager.rb
When lazy-loading the tree, there is necessary to have an object for `x_get_child_nodes` which will allow us to expand its children. However, the unassigned groups aren't real objects in the DB and in catalog/foreman trees they're added via a hack. I'm moving this hack from the main tree builder to the subclasses and so dropping some extra conditions.
> Move the conditional node-to-model into the treebuilder subclasses

- app/assets/javascripts/miq_application.js
- app/views/report/_column_lists.html.haml
CI > Reports > Reports accordion, Configuration > Add a New Report; Columns tab
Right now, opening the "Available fields" select in report editor takes time:
It *looks* like a big chunk of that time is spent in `setSize`, which computes the size of the opened dropdown.
This PR makes it skip the computation for that one select, meaning it always opens all the options when expanded, but opens them right away.
The idea being that it's probably acceptable to do that if it saves multiple seconds when opening.
(The underlying cause is that we're talking 4000 `<option>` elements in that one select, while the data for those options is clearly hierarchical (under 350 nodes per level). This should be replaced by a tree or something similar when redesigning.)
Cc @epwinchell , @terezanovotna
> Report editor - available fields - make opening faster

- app/controllers/catalog_controller.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1702343
**What:**
This simple PR fixes issue about displaying Catalog Item's info (also Catalog Bundle's), when clicking on the Catalog Item from the list. In our case, `nil` is a valid value so we prefer using `find_by_id` instead of using `find`.
2. _Configuration > Add a New Catalog Item_, choose some _Catalog Item type_
3. Fill in the required info and click on _Add_ button
4. After successful saving the Catalog Item, click on the same Catalog Item in the list,
in _All Service Catalog Items screen_, to view its details
=> clicking on a newly created Catalog Item in the list throws an error, nothing happens in the UI, Catalog Item's summary screen is …
> Fix error when clicking on created Catalog Item in the list

- app/controllers/automation_manager_controller.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/storage_controller.rb
- app/helpers/application_helper.rb
- app/presenters/tree_builder.rb
- spec/controllers/storage_controller_spec.rb
- spec/presenters/tree_builder_ae_customization_spec.rb
I'd like to get rid of the `type` vs `name` duality in `TreeBuilder` and for that we should not reference the `type` in the sandbox at all. Since https://github.com/ManageIQ/manageiq-ui-classic/pull/5426 the `name` and `type` differs from each other in the `_tree` suffix only. Therefore, it's now possible to add the suffix to every check that works with `x_tree[:type]` and replace it with `x_tree[:name]`.
> Replace x_tree[:type] with x_tree[:name] and remove type from sandbox

- app/presenters/menu/default_menu.rb
- spec/presenters/tree_builder_ops_rbac_features_spec.rb
As `Utilization` [went](https://github.com/ManageIQ/manageiq-ui-classic/pull/5448) into the `Cloud Intel` and the remaining two items under `Optimize` will also [go away](https://github.com/ManageIQ/manageiq-ui-classic/pull/5430), I am dropping the menu section completely. Sorry @GregP for the caused merge conflicts, we got these colliding RFEs, but it's just deletion, so probably easy to rebase.
**Before:**
**After:**
@miq-bot add_label ux/review, hammer/no
https://bugzilla.redhat.com/show_bug.cgi?id=1678196
> Menu Simplification: Drop the Optimize section

- app/presenters/tree_builder_storage_pod.rb
It should be `_options` instead of `_type` and it's anyway unused.
@miq-bot add_label technical debt, trees, hammer/no
> Correct argument in TreeBuilderStoragePods#x_get_tree_custom_kids

- app/controllers/application_controller/policy_support.rb
- app/views/layouts/_policy_sim.html.haml
- spec/controllers/application_controller/policy_support_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1688370
**What:**
Fix missing title in Policy Simulation page, for items (VMs, Instances) displayed as a nested list (non explorer).
1. Go to _Compute > Cloud/Infrastructure > Providers_
2. Choose some provider, click on it to display its dashboard or summary page
3. Click on VMs/Instances
4. Check the checkbox(es) of some VM(s)/Instance(s)
5. In the toolbar, choose _Policy > Policy Simulation_
=> there is no title in this page
---
**Before:**
**After:** (for both VMs and also Instances)
---
**Note:**
I've also added missing https://github.com/ManageIQ/manageiq-ui-classic/pull/5429/commits/a17b053279f70a9e1b566a0e4d66c1bfb6aa1b7a#diff-dcf973c55609c594de2b7f1c5471d434R117
which should be set, as we are still in …
> Fix missing title in Policy Simulation page 

- app/presenters/tree_builder_automation_manager_configured_systems.rb
- app/presenters/tree_builder_configuration_manager_configured_systems.rb
- app/presenters/tree_builder_images_filter.rb
- app/presenters/tree_builder_instances_filter.rb
- app/presenters/tree_builder_template_filter.rb
- app/presenters/tree_builder_templates_images_filter.rb
- app/presenters/tree_builder_vms_filter.rb
- app/presenters/tree_builder_vms_instances_filter.rb
Rails doesn't like to pass the `:db` argument as a class, it says it's better as a string:
```
DEPRECATION WARNING: Passing a class as a value in an Active Record query is deprecated and
will be removed. Pass a string instead. (called from x_get_global_filter_search_results at ...)
```
@miq-bot add_label technical debt, trees, hammer/no
@miq-bot add_reviewer @PanSpagetka
> Fix deprecation warnings in TreeBuilder root_class instance vars

- app/controllers/application_controller.rb
Using the `MiqReport.for_user` method is not necessary for the `default_reports_menu` at all, as it only requests the `Default` reports regardless of the current user. I also expanded the code to more lines with some comments to make it easier to read.
Retrieving the custom reports in `get_reports_menu` can be also simplified by dropping the `MiqReport.for_user` and just asking for the reports for that one given group, instead of all groups of the user and then filtering. If the user have global access to all custom reports, the `group_id` is simply not passed to the `where` hash.
Ideally I'd like to extract these things into named scopes or at least class methods into the `MiqGroup` or `MiqReport` models, but first let's simplify them.
@miq-bot add_label refactoring, hammer/no, reporting …
> Make some _reports_menu methods a little more readable

- app/controllers/application_controller/filter/expression.rb
- spec/controllers/application_controller/filter/expression_spec.rb
Fixes a bug where Expression Editor was comparing integer fields with 'Contains' rather than using a numeric comparison.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1698168
> Use numeric comparison for IDs

- app/views/ops/_ap_form_nteventlog.html.haml
Incorrect tag was causing the automated tests to fail, although the screen looked fine to the user.
Old
New (no difference)
https://bugzilla.redhat.com/show_bug.cgi?id=1703141
> fix event log entry markup

- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/service_controller.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
- Display the ancestry hiearchy in breadcrumbs (Service controller)
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5390
**Before**
**After**
@miq-bot add_label hammer/no, enhancement, services
@miq-bot add_reviewer @skateman
> Add ancestry parents to breadcrumbs

- app/presenters/menu/default_menu.rb
Related to, but doesn't depend on https://github.com/ManageIQ/manageiq-ui-classic/pull/5507
**Before:**
**After:**
Discussed this with @loicavenel, it's a little bit more meaningful.
@miq-bot add_label rbac, hammer/no
> Rename Settings to User Settings in the RBAC tree

- app/presenters/tree_builder_ops_rbac_features.rb
After the [extraction](https://github.com/ManageIQ/manageiq-ui-classic/pull/5453) of the `Configuration` from `Settings` the RBAC role tree was not updated with the new structure. The incomplete tree caused a side-effect that is described in the BZ below.
**Before:**
**After:**
As there would be two `Configuration` node on the same level in the tree, I'm renaming the latter one to `Main Configuration` in a [depending core PR](https://github.com/ManageIQ/manageiq/pull/18707).
@miq-bot add_label bug, rbac, hammer/no
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1704163
> Display the missing Main Configuration in the RBAC roles tree

- app/presenters/tree_builder_policy.rb
Fixes mismatched displays between accordion nodes for Policy Physical Servers Compliance node description and that of page Header and toolbar Configuration drop down menu.  
https://bugzilla.redhat.com/show_bug.cgi?id=1700070
> Fixes display text for Policy Server Compliance accordion nodes

- package.json
bootstrap-switch 3.3.5 breaks initial state, forcing all switches to false (issue: https://github.com/Bttstrp/bootstrap-switch/issues/703)
(and 3.4.0 is using boostrap 4, so we can't use it)
Locking to 3.3.4 for now, will relax it if 3.3.6 comes out fixed.
(Hammer should not be affected because of [yarn.lock](https://github.com/ManageIQ/manageiq-ui-classic/blob/hammer/yarn.lock#L2090))
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1704337
> Lock bootstrap-switch to 3.3.4

- app/controllers/application_controller.rb
- app/helpers/report_helper.rb
The helper is already included in all the places these methods are being called, so there's no reason to keep this in `ApplicationController`. Also I would like to to [get rid](https://github.com/ManageIQ/manageiq-ui-classic/pull/5499) of the `build_*_tree` methods and to do so I have to run the `populate_reports_menu` from the `TreeBuilder` at some point, which is easier from a helper.
@miq-bot add_label trees, cloud intel/reporting, refactoring, hammer/no,
> Move methods related to report menu editing into a ReportHelper

- app/controllers/report_controller/menus.rb
- app/controllers/report_controller/reports/editor.rb
- app/controllers/report_controller/saved_reports.rb
- app/helpers/report_helper.rb
- app/views/report/_report_list.html.haml
The `@sb[:grp_title]` is being generated by `ReportHelper#reports_group_title` and it's basically cached in the sandbox. However, the method itself isn't that expensive that it would worth to store it in such an evil place, so :scissors: :toilet: :fire: 
@miq-bot add_label cloud intel/reporting, technical debt, hammer/no
> Eliminate the grp_title sandbox variable used in report menus

- app/helpers/application_helper/page_layouts.rb
- app/views/automation_manager/explorer.html.haml
- app/views/ems_cloud/show_list.html.haml
- app/views/ems_container/show_list.html.haml
- app/views/ems_infra/show_list.html.haml
- app/views/ems_network/show_list.html.haml
- app/views/ems_physical_infra/show_list.html.haml
- app/views/layouts/_empty.html.haml
- app/views/provider_foreman/explorer.html.haml
- config/routes.rb
- spec/controllers/ems_cloud_controller_spec.rb
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1678190
Before:
After:
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1678190
* Login with an empty database
> Adding a welcoming page prompting to add a Provider

- app/presenters/tree_builder_report_reports.rb
- spec/presenters/tree_builder_report_reports_spec.rb
I forgot to stage this change into #5518, so caused a bug :see_no_evil:. It's under `Cloud Intel -> Reports -> Reports`, the last 2nd level node should be blue.
**Before:**
**After:**
@miq-bot add_label bug, trees, cloud intel/reporting, hammer/no
> Make the custom reports tree node blue again

- app/views/miq_request/_request_dialog_details.html.haml
- app/views/miq_request/_st_prov_show.html.haml
- app/views/shared/dialogs/_dialog_field.html.haml
Checking if the Classification is `nil` prior to accessing it's description.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1696697
> Validate Classification before accessing description

- app/controllers/miq_policy_controller/miq_actions.rb
- Navigate to Control > Explorer, then Actions accordion
- Configuration > Add a new Action
Blocked by https://github.com/ManageIQ/manageiq-ui-classic/pull/5525 (it fixes an error that shows before this one)
Before:
```
[----] F, [2019-05-03T16:24:33.276198 #87988:3ff37ae5051c] FATAL -- : Error caught: [ArgumentError] wrong number of arguments (given 4, expected 2..3)
/ManageIQ/manageiq-ui-classic/app/presenters/tree_builder_miq_action_category.rb:13:in `initialize'
/ManageIQ/manageiq-ui-classic/app/controllers/miq_policy_controller/miq_actions.rb:313:in `new'
/ManageIQ/manageiq-ui-classic/app/controllers/miq_policy_controller/miq_actions.rb:313:in `action_build_cat_tree'
/ManageIQ/manageiq-ui-classic/app/controllers/miq_policy_controller/miq_actions.rb:183:in …
```
> Fix fourth param to be Hash for TreeBuilderMiqActionCategory call

- app/controllers/miq_policy_controller/miq_actions.rb
The code changed from `reduce` to `each_with_object` in https://github.com/ManageIQ/manageiq-ui-classic/pull/5286, (cc @PanSpagetka)
but while `reduce` puts the memo object first,
`each_with_object` puts it last.
Fixes #5523, cc @hstastna
> action_build_alert_choices - fix wrong argument order

- app/controllers/ops_controller/ops_rbac.rb
- app/javascript/components/taggingWrapper.jsx
- app/javascript/miq-redux/middleware.js
- app/javascript/packs/component-definitions-common.js
- app/javascript/spec/miq-redux/middleware.spec.js
- app/views/layouts/_x_edit_buttons.html.haml
- app/views/ops/rbac_group/_customer_tags.html.haml
- package.json
- spec/controllers/ops_controller/ops_rbac_spec.rb
Add new Tagging instead of RBAC tree for groups
https://github.com/ManageIQ/react-ui-components/pull/105
Go to Ops -> Account Settings -> Groups
Old:
New:
@skateman
> Add new Tagging instead of RBAC tree for groups

- app/javascript/packs/component-definitions-common.js
too many merge conficts are happening because everybody is adding stuff at the end of component definitons.
Let's keep it sorted.
Imports: Putting react first, external repos second, ours third.
addReact: sort by component name
Cc @Hyperkid123 , @rvsia, @PanSpagetka
> component definitions - sort import and components

- spec/spec_helper.rb
prevents
$ rspec spec/controllers/ops_controller/settings/common_spec.rb:141
...
uninitialized constant OpsController::Settings::RHN::MiqHashStruct
when running standalone tests which require [MiqHashStruct](https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/util/miq-hash_struct.rb).
> spec_helper - load MiqHashStruct

- app/controllers/miq_policy_controller/alert_profiles.rb
- spec/controllers/miq_policy_controller/alert_profiles_spec.rb
Fixed 2 issues
- Fixed `wrong number of arguments (given 4, expected 3)` error, removed 'type' argument that was being passed in to tree builder code, was introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/5495
- Fixed `comparison of Integer with String failed` error for `@assign[:new][:objects].sort!`, changed to push integer into objects array to fix comparison error on the sort when selecting nodes in the tree in 'Selections' box.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1707871
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1707886
> Removed 'type' argument passed to the tree builder

- app/controllers/application_controller/buttons.rb
- spec/controllers/application_controller/buttons_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1706900
Go to Automate -> Automation -> Customization -> Custom Buttons -> Create a new button under Vm and Instance
`Open URL` should be ENABLED for `Vm and Instance` when `Display For` is set to `Single Entity`
Before:
After:
@miq-bot add_label bug, automation/automate, hammer/no, changelog/no, blocker
> Fix for open_url in CustomButton

- app/presenters/tree_builder_condition.rb
**Fixes BZ:**
https://bugzilla.redhat.com/show_bug.cgi?id=1704380
**What:**
This PR fixes highlighting the condition in accordion right after editing it: the edited condition was not highlighted in accordion as expected, instead of that, _All Conditions_ node was highlighted. Everything else regarding editing conditions seems to work.
This is little bit tricky, don't follow the original steps in the BZ, otherwise you will not be able to reproduce, or just rarely. Follow these steps instead:
1. Navigate to _Control > Explorer_, then _Conditions_ accordion 
2. Choose some type of conditions where there is no condition created yet (important!), click on it
3. Create a new condition: choose _Configuration > Add a New Container Replicator Condition_ or any other type of …
> Fix highlighting the condition in accordion after editing it

- app/controllers/ops_controller/ops_rbac.rb
- app/views/ops/_rbac_group_details.html.haml
- spec/controllers/ops_controller/ops_rbac_spec.rb
Belongsto filters refer to objects(ExtManagementSystem, Host, Datacenters, Clusters,... ) but if this object is deleted, reference in belongsto filters is still present - it is ok that the reference is still present - but user needs to have way how to be informed about it and how to remove this outdated filters.
**Displaying outdated filters in detail of group.**
**Displaying outdated filters in detail of group when edit.** (Save is active - because when you click on it these outdated filter will be removed)
**Message after saving a group and removing outdated filters**
There is GIF with everything together:
@miq-bot add_label changelog/yes, enhancement
Links
-----
* https://github.com/ManageIQ/manageiq/pull/18651
* …
> Inform user about outdates belongsto filters

- app/assets/stylesheets/patternfly_overrides.scss
- app/javascript/packs/application-common.js
- app/stylesheet/application-webpack.scss
- package.json
To avoid collisions with the old world, the new version is loaded through webpack instead of the asset pipeline. Reopen of #4841 as I accidentally deleted the branch.
@miq-bot add_label hammer/no, changelog/yes, graphics
> Add support for PF4 styling through webpack

- app/controllers/ops_controller/settings/rhn.rb
- spec/controllers/ops_controller/settings/common_spec.rb
When setting up updates under the region config (see screenshot) the *Organization*, the Satellite option supports having multiple organizations. However, the dropdown for selecting the organizations is not mandatory which causes further issues in the registration process. With my change the field becomes mandatory if the Satellite server has more than one organization.
@miq-bot add_label hammer/yes, bug
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1687086
> Make Organization required on RHN updates upon 1+ available orgs

- app/controllers/application_controller/buttons.rb
- spec/controllers/application_controller/buttons_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703588
- Go to Service -> Catalogs -> Catalog Items -> select any button -> Configuration -> Edit this button
- Advanced tab -> Role Access -> Show -> select `<By Role>` -> Add Role(s) to this button  -> Save
- Edit this button again adding Role(s) -> Save
- Role(s) from first saving are present
Make sure https://bugzilla.redhat.com/show_bug.cgi?id=1650090 isn't reintroduced.
- Go to Service -> Catalogs -> Catalog Items -> select any button -> Configuration -> Edit this button
- Advanced tab -> Role Access -> Show -> select `<By Role>` -> Add Role(s) to this button  -> Save
- Roles have to be showing on summary page
@miq-bot add_label hammer/yes, bug
@h-kataria please have a look, thanks :)
> Remove wrong and redundant check

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_iso_datastores.rb
- app/presenters/tree_builder_ops_vmdb.rb
- app/presenters/tree_builder_pxe_servers.rb
- app/presenters/tree_builder_report_reports.rb
- app/presenters/tree_kids.rb
The `TreeBuilder#open_node` method already implements `options[:open_nodes].push`, therefore, it should be used across all the `TreeBuilder` classes. By making this change, the `options` argument for fetching tree kids becomes unnecessary, so it can be also deleted.
@miq-bot add_label refactoring, trees, hammer/no, changelog/yes
> Remove the need for the options argument when fetching node kids in TreeBuilder

- app/controllers/miq_request_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- app/javascript/components/breadcrumbs/index.js
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5490
go to `/miq_request/show/[id]`
- Miq_report_controller is used at two places in MiQ so there is a (probably) wrong condition how to get know which place it is (it is asking for params)
- That means on Request page it doesn't know where the page is (so menu breadcrumbs are missing)
- The React component gets an empty array and tries to render a title of the last item in the empty array... and it fails. :ghost:
**Before**
**After**
TO-DO
> Fix breadcrumbs on request page

- app/controllers/application_controller/policy_support.rb
- app/controllers/vm_common.rb
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1704424 https://github.com/ManageIQ/manageiq-ui-classic/issues/5378
1. Compute > Cloud > Instances
click on some instance => its summary page
2. Policy > Policy Simulation
select some Policy Profile from the drop down
=> check the breadcrumbs
3. click on a quadicon of the instance
=> breadcrumbs changed!
4. click on Back button
=> breadcrumbs remain unchanged (the same asi in step 5) but different to the ones in step 4!
VM controllers are using shared methods and when they are doing it, the breadcrumbs do not know which controller is used.
**Solution**
Breadcrumbs are not re-rendered when clicking in policy simulation screen, so they remain the same.
**Before** (pleease, ignore the VSCode window …
> Do not refresh breadcrumbs when clicking in policy_sim

- app/controllers/vm_common.rb
Fiexs https://bugzilla.redhat.com/show_bug.cgi?id=1705611
1. Add a provider (tested with RHV 4.3)
2. Navigate to VMs from provider's dashboard
3. Select any VM
4. Configuration -> Edit Selected item
- When user go to `vm_controller` from **provider** screen, he is redirected to nonexplorer screen and breadcrumbs are missing the **gtl_url** method for generating a link to the item.
- All VM controllers are using explorer screen, so this method should not mess them up.
**Before**
```ruby
[----] F, [2019-05-03T10:38:49.852856 #15071:557b110] FATAL -- : ActionView::Template::Error (undefined local variable or method `gtl_url' for #<VmController:0x00007f843bcecab8>):
[----] F, [2019-05-03T10:38:49.852966 #15071:557b110] FATAL -- :     1: = …
```
> Fix vm_edit when entering from providers screen

- app/presenters/tree_builder.rb
- app/presenters/tree_node/miq_server.rb
- app/presenters/tree_node/zone.rb
- spec/presenters/tree_node/miq_server_spec.rb
- spec/presenters/tree_node/zone_spec.rb
When building trees with servers and/or zones, the appliance's current server and/or zone is marked with a `current` suffix. This logic has been added globally into the `TreeBuilder#x_build_node` but it's very specific for only `TreeNode::Zone` and `TreeNode::MiqServer` objects.
@miq-bot add_reviewer @martinpovolny  
> Evaluate the current server/zone in the TreeNode instead of globally

- app/controllers/miq_policy_controller.rb
- app/controllers/miq_policy_controller/conditions.rb
**What:**
This PR is just about some small refactoring for miq policy controller and conditions.
**Note:**
I've found that the code can be simplified while fixing BZ https://bugzilla.redhat.com/show_bug.cgi?id=1704380 (fixing that BZ does not depend on this PR)
See also the line https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Refactoring_miq_policy_conditions?expand=1#diff-4b771fc8b6101d357855d3d10d79ba8aR33 and you will understand this little refactoring easily.
> Small refactoring for miq policy controller and conditions

- app/helpers/application_helper/title.rb
- app/views/ops/_rbac_group_details.html.haml
discussed with @terezanovotna 
before
after
Links
-----
https://bugzilla.redhat.com/show_bug.cgi?id=1679027#c14
@miq-bot add_label changelog/no, enhancement
> Update tab name for belongsto filters (Assigned Filters)

- app/views/static/ae_resolve_options/ae-resolve-options.html.haml
Also removed entry <choose> from the drop down that was always disabled so dont really need it there.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1705970
before:
after:
> fixed to show "Required" text for Selection field

- app/views/miq_request/_prov_vm_grid.html.haml
We can derive number of table columns from `@edit[:vm_headers]`: it will work for various catalog item types.
Before:
After:
> prov_vm_grid: fix first row length

- app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
- app/controllers/ops_controller/settings/common.rb
- app/views/ops/_settings_replication_tab.html.haml
- spec/controllers/ops_controller/settings/common_spec.rb
- spec/javascripts/controllers/ops/pglogical_replication_form_controller_spec.js
With the new backend replication technology, making a new set of
excluded tables take effect requires action on both the remote and
global regions. Because of this the user experience would be much
worse for a feature that is not really necessary.
Requires https://github.com/ManageIQ/manageiq/pull/18686
@miq-bot add_label wip, hammer/no, pending core
---------------------------------------
Before:
After:
> Remove the replication exclude tables

- app/controllers/miq_ae_class_controller.rb
Changing value of Expression Object field in UI was causing value of `@edit[:new][:location]` to be reset to "inline" causing incorrect partial to render on screen.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1705587
To recreate add a new Expression type method, and change value of Expression Object in the drop down.
before:
after:
> Only initialize value of `@edit[:new][:location]` when it's not set

- app/controllers/miq_ae_class_controller.rb
`@edit[:default_verify_status]` was not being set when method type was 'builtin', causing validate button to always remain disabled.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1708203
This issue is recreatable on master after fixing issue in https://github.com/ManageIQ/manageiq-ui-classic/pull/5555 , currently on master since value of `@edit[:new][:location]` always gets reset to "inline" validate button gets enabled when transaction is sent up to the server.
before:
after:
> Enable validate button when data is entered for builtin method type

- app/views/ops/_ldap_forest_entries.html.haml
When setting authentication to LDAP under the server settings, it is possible to map the LDAP's user groups to our groups. This enables the trusted forest settings, which has a button that fires two events instead of one.
Also, when you try to add the second trusted forest, you get an exception from the server about a comparison between `nil` and a string. This is because the new forest's `ldaphost` is implicitly set to `nil` and we're trying to sort all the forests. The solution is simple, force-convert the values into string while sorting...
https://bugzilla.redhat.com/show_bug.cgi?id=1706764
> Fix adding new trusted forests for LDAP authentication

- app/views/generic_object_definition/_show_actions.html.haml
GOD tree sorts Button Groups by their name. Fixing table to have same sort as tree.
Go to Automation -> Automate -> Generic Objects -> Add few Button Groups with names that go from Z to A (so their chronological and alphabetical orders are different!) -> see tree and table orders are different
Before:
After:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1665031
https://github.com/ManageIQ/manageiq-ui-classic/pull/5146 didn't fix the problem completely.
@miq-bot add_label bug, generic objects, automate/automation, hammer/yes, gaprindashvili/yes, bugzilla needed
> Unify sorting in GOD of Button Groups

- app/controllers/report_controller/reports/editor.rb
- spec/controllers/miq_report_controller/reports/editor_spec.rb
Goal ⚽️ : remove usage of `MiqReport.get_col_type`
I did also some simplification in second commit.
> Replace MiqReport.get_col_type with parse_field_or_tag

- app/controllers/miq_policy_controller/miq_actions.rb
Reverting a change made in https://github.com/ManageIQ/manageiq-ui-classic/commit/1b4c63bd357c8dd9a0ca0cd5df68bf821ff7978a#diff-2ea3e6bb74ba2e128638b610176feeddR302, this change is causing Save/Reset button to be enabled on initial load of edit form.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1708434
before
after
> Only need to set `@edit[:current][:add]` for new record

- app/presenters/tree_node/ems_folder.rb
- spec/presenters/tree_node/ems_folder_spec.rb
Regression caused by #5495 and also mentioned in #5565, the folder icons should be blue.
**Before:**
**After:**
@miq-bot add_label bug, trees, hammer/no
> Test against tree name and not type in TreeNode::EmsFolder

- app/helpers/application_helper.rb
This method is not used, as the UI code that shows the about screen uses the API. See also https://github.com/ManageIQ/manageiq-api/pull/587
@AparnaKarve Please review.
> Remove unused plugin_name method

- spec/controllers/ems_physical_infra_controller_spec.rb
- spec/controllers/physical_chassis_controller_spec.rb
- spec/controllers/physical_rack_controller_spec.rb
- spec/controllers/physical_server_controller_spec.rb
- spec/controllers/physical_storage_controller_spec.rb
- spec/controllers/physical_switch_controller_spec.rb
Physical Infra Manager doesn't have assets as it's a pseudo abstract
class.
Fixes rails 5.1 deprecations such as:
```
DEPRECATION WARNING: The asset "svg/vendor-physical_infra_manager.svg" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
(called from quadrant_output at /Users/joerafaniello/.gem/ruby/2.4.6/bundler/gems/manageiq-decorators-fbb4695da1fb/app/helpers/quadicon_helper.rb:98)
```
```
DEPRECATION WARNING: The asset "svg/vendor-physical_infra_manager.svg" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be …
```
> Use leaf subclasses with assets

- app/views/vm_common/_right_size.html.haml
I saw this in the test suite while looking at rails 5.1 test output.
I'm able to recreate and verify this fix on rails 5.0 with ruby 2.4 using:
`bundle exec rspec `git grep -l right_size spec`
> Fix warning: found = in conditional, should be ==

- app/controllers/application_controller/miq_request_methods.rb
1. Create catalog item (VMware for example), remember the selected provisioning template
2. Delete the provisioning template chosen in step 1
3. Try to edit the catalog item from step 1
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1356086
> Correctly highlight <None> row when provisioning template deleted

- app/controllers/application_controller.rb
- app/controllers/application_controller/performance.rb
- app/controllers/miq_ae_customization_controller.rb
- app/controllers/vm_common.rb
- app/presenters/tree_builder.rb
- spec/controllers/vm_common_spec.rb
- spec/presenters/tree_builder_spec.rb
These two methods are doing the same, however, the `build_node_cid` can handle both a record and an id + type. Unifying them can allow us to drop some code :scissors: 
@miq-bot add_label refactoring, hammer/no, trees
> Replace TreeBuilder.build_node_cid calls with build_node_id

- app/presenters/tree_node/custom_button_set.rb
- spec/presenters/tree_node/custom_button_set_spec.rb
**Before:**
**After:**
Fixes #5565 
@miq-bot add_label bug, hammer/no, trees
> Test against tree name and not type in TreeNode::CustomButtonSet

- app/helpers/application_helper/toolbar/generic_object_definition_button_group_center.rb
Before:
After:
in Automate - Automation - Generic Objects:
1) add Custom Button Set
2) edit Custom Button Set
> Corrected icon for editing Custom Button Group

- app/controllers/ops_controller/ops_rbac.rb
After discussion with @lpichler we agreed, that should be possible to select multiple tags for all tags. Some of them have set `single_value` restriction, but that should not apply to this screen but only to page where the tags are applied to entities. Before changes #5482 was also possible to select multiple values.
Links
#5482
#5515
Click on Cog wheel at right corner of the screen => Access Control => Groups => Add/Edit group
It should be possible to select multiple values for all categories.
> Enable Multivalue selection for all Ops RBAC Tags

- app/controllers/ops_controller/settings/schedules.rb
Since we give users the option to disable certain regions in the configs, using the `Amazon::Regions.regions` method instead of the `REGIONS` constant will make sure that this reflects what is desired as allowable AWS regions.
Links
-----
* PR Originally adding this: https://github.com/ManageIQ/manageiq-ui-classic/pull/4300
* BZ:  Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710599
> [OpsController] Use .regions method not REGIONS

- app/controllers/miq_ae_tools_controller.rb
- spec/controllers/miq_ae_tools_controller_spec.rb
This PR contains a new flash message for import datastore with the invalid playbook method and it depends on the second PR inside the automation_engine(link bellow).
* Depends on https://github.com/ManageIQ/manageiq-automation_engine/pull/303
* Based on https://bugzilla.redhat.com/show_bug.cgi?id=1677575
> Flash message for import ae_datastore with invalid playbook method.

- app/assets/javascripts/components/tree.js
- app/assets/javascripts/miq_angular_application.js
- app/views/layouts/_tree.html.haml
- app/views/shared/_tree.html.haml
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/vm_infra_controller_spec.rb
- spec/shared/controllers/shared_examples_for_ems_network_controller.rb
- spec/shared/controllers/shared_examples_for_ems_storage_controller.rb
An angular tree in a form is needed for #5445.
The current tree mostly works in angular, except `miqInitTree` needs to happen after angular is finished.
* added a `miq-tree` angular component, which pretty much just calls `miqInitTree` at the right time
* added a `layouts/tree` angular path, which uses `miq-tree` instead of calling `miqInitTree` directly.
@miq-bot add_reviewer @skateman
Cc @hstastna
> Allow angular in layouts/tree

- .travis.yml
- spec/other/travis_spec.rb
missed in #5572,
we explicitly exclude all non-ruby jobs on the newer ruby version
(no point in running javascript specs twice)
so, updating the excluded ruby version to match the new one we're using
(Drops the number of travis jobs from 8 back to 5.)
(similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/5111)
> Update travis excludes for 2.4.6

- app/assets/javascripts/application.js
- app/javascript/packs/globals.js
- lib/manageiq/ui/classic/engine.rb
- manageiq-ui-classic.gemspec
- package.json
- spec/javascripts/globals_pack_spec.js
Steps to verify:
- `bin/webpack` runs without error
- Compute -> Containers -> Providers -> add new one -> click verify (or any other screen with spinner that will spin forever)-> ctrl+shift+x -> spinner stops
@miq-bot add_label dependencies, hammer/no, changelog/no, test, technical debt
> Move jquery.hotkeys from assets pipeline to webpack

- app/controllers/ops_controller/ops_rbac.rb
When adding new group UI breaks when switching Specific tags to Expression.
#5515
Cog Wheel => Access Control => Groups => Add new group => Switch from Specific tags to Tags based on Expression and back.
@lpichler
> Fix Specific tags/Expression switch for new group

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/javascript/packs/globals.js
- app/stylesheet/application-webpack.scss
- spec/javascripts/globals_pack_spec.js
Steps to verify:
- `bin/webpack` runs without error
- Compute -> Containers -> Providers -> select one -> switch to Topology view -> it looks same as before
@miq-bot add_label dependencies, hammer/no, changelog/no, test, technical debt
> Move kubernetes-topology-graph from assets pipeline to webpack

- app/controllers/application_controller/miq_request_methods.rb
- app/controllers/application_controller/report_data_additional_options.rb
Due to absence of `@in_a_form` setting, code was trying to load advanced search data on pre-provisioning screen and throwing a `nil` error.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710097
@ZitaNemeckova @himdel please review/test
> Do not load advanced search on pre-provisioning screen.

- app/views/catalog/_svccat_tree_show.html.haml
This info was already being set, only needed to be displayed in view.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1461487
before
after
> Added Dialog name info on the Catalog Item summary screen

- spec/controllers/miq_ae_class_controller_spec.rb
My change yesterday that removed the ```allows_nil => false``` broke https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/533531882#L2681, so this should fix that. 
thanks, sorry @himdel
> Fix specs for validation of embedded methods

- app/controllers/mixins/actions/vm_actions/policy_simulation.rb
- config/routes.rb
- spec/controllers/vm_infra_controller_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1670456
**What:**
If you try to cancel a policy simulation on a Cloud Instance (or also VM) after carrying out the steps below (especially after using _Back_ button), the _Cancel_ button doesn't work, nothing happens in the UI. This PR fixes the problem.
1. Add a cloud/infra provider if you don't have any (you need at least 1 VM or Instance)
2. _Compute > Clouds/Infra > Providers_, select a provider and navigate to its Instances/VMs
3. Choose some Instance/VM and _Policy > Policy Simulation_
**Note**: if you don't go to the Summary page of an Instance/VM but check the checkbox, the bug will not occur because there is missing _Back_ button (after step 5, and this is another BZ)
4. Choose any Policy from the …
> Fix problem with canceling policy sim if clicking on Back before Cancel

- app/views/ops/rbac_group/_hosts_clusters.html.haml
- app/views/ops/rbac_group/_vms_templates.html.haml
I think that those message are just for non-super admin users.
**before** 
tab **Clusters, Datastores, Hosts, Managers & Providers** 
tab **VMs & Templates**
**after**
tab **Clusters, Datastores, Hosts, Managers & Providers** 
tab **VMs & Templates**
> Remove messages for superadmins in group's detail

- app/controllers/ems_cluster_controller.rb
- app/controllers/host_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1705643
`Compute` > `Infrastructure` > `Clusters / Deployment Roles` || `Hosts / Nodes`
`ems_cluster` and `host` controllers are using dynamic titles in their layouts depending on the content of their pages (`node_types` = `:non_openstack` or `:openstack` or `:mixed_xxx`). 
Breadcrumbs will look on this title and if it is different from the last menu item, it will append the title to breadcrumbs and make last item in breadcrumbs linked to `controller_url`.
> Use right title in breadcrumbs in ems_cluster and host controllers

- app/presenters/tree_builder_services.rb
- spec/presenters/tree_builder_services_spec.rb
Due to performance reasons, the services [have been set](https://github.com/ManageIQ/manageiq-ui-classic/pull/5335) not to be displayed in the services tree. This caused to lose some information about the service hierarchy in the case of having services nested into each other. To have the good from both worlds, I implemented lazy loading for the child services. This way we get the hierarchy back and until a user doesn't try to expand all the nodes, there will be no performance issues on the frontend.
I created some specs that deal with retired and non-retired services nested into each other. However, this might need some extra testing. The easiest way to create some services is to create a generic service catalog, order it a few times and set the hierarchy of the services from a `rails …
> [HAMMER] Display the services tree hierarchy using lazy loading

- app/controllers/ops_controller/settings/schedules.rb
When adding a new schedule under OPS, there's an option to store DB backups on AWS S3. The region selector for this option is inconsistent with the AWS region selection for adding providers. With a small change I am making this consistent, having the human-readable form on this screen.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710623
> Make AWS region dropdown under schedules consistent with add provider

- app/controllers/application_controller/filter/expression.rb
other step of effort to remove get_col_type.
(previous PR https://github.com/ManageIQ/manageiq-ui-classic/pull/5210 )
cc @kbrock 
1. open expression editor (in report for example)
2. Edit Selected Element of expression
3. select `Field`
4.  select any concrete Field
> Remove get_col_type from filter/expression.rb

- app/controllers/application_controller/advanced_search.rb
- app/controllers/application_controller/explorer.rb
- app/controllers/automation_manager_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/miq_ae_class_controller.rb
- app/controllers/miq_ae_customization_controller.rb
- app/controllers/ops_controller/db.rb
- app/controllers/ops_controller/diagnostics.rb
- app/controllers/ops_controller/ops_rbac.rb
- app/controllers/ops_controller/settings/common.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/pxe_controller/iso_datastores.rb
- app/controllers/pxe_controller/pxe_customization_templates.rb
- app/controllers/pxe_controller/pxe_image_types.rb
- app/controllers/pxe_controller/pxe_servers.rb
- app/controllers/report_controller.rb
- app/controllers/report_controller/dashboards.rb
- app/controllers/report_controller/reports.rb
- app/controllers/report_controller/saved_reports.rb
- app/controllers/report_controller/schedules.rb
- app/controllers/report_controller/widgets.rb
- app/controllers/service_controller.rb
- app/controllers/storage_controller/storage_d.rb
- app/controllers/storage_controller/storage_pod.rb
- spec/controllers/application_controller/advanced_search_spec.rb
- spec/controllers/provider_foreman_controller_spec.rb
Right now we use a `build*tree` method for each explorer tree reload, usually for adding/editing/deleting nodes. When the tree is being built for other purposes, we use the `Feature#build_tree` method. They are *kinda redundant* but the latter one is a little bit cleaner and needs less code.
The `build_reports_tree` is a little special, as it relies on a session parameter set by `populate_reports_menu` which has to run before building the tree. The idea is to not use the session in such way, I'm discussing with @kbrock about the alternatives and their performance issues. Until this is solved, there's an `if` 🦛 marked with a FIXME :evergreen_tree: that runs the old code. For the other trees we can use the new stuff.
I'm pretty sure @martinpovolny will :heart: these changes :wink: 
@miq-bot …
> Use the Feature#build_tree instead of the individual build*tree methods in explorers

- app/assets/javascripts/services/dialog_editor_http_service.js
- app/controllers/tree_controller.rb
- app/presenters/tree_builder.rb
- spec/controllers/tree_controller_spec.rb
The dialog editor has an option to set a field dynamic, if this is enable there's an entry point selection tree available under the *Options* tab. If you're editing an already existing field with an entry point selected, the tree nodes to the entry point aren't expanded.
However, the entry point doesn't include a domain prefix, it is possible that the same entry point is available under a different domain. We discussed this with the automate folks and the only solution is to expand all the homonymic nodes under all possible automate domain prefixes. 
I added an optional block evaluation to the `TreeController#fetch_tree` method that runs before the tree is being build. By passing a block to this method, we can easily define different behavior for certain trees without defining extra …
> Open the homonymic tree nodes for dialog editor entrypoint selection

- app/controllers/application_controller.rb
- app/controllers/miq_request_controller.rb
- app/helpers/application_helper.rb
- lib/gtl_formatter.rb
It's not enough to decide in [this switch](https://github.com/ManageIQ/manageiq-ui-classic/blob/3f609dab512cf49350cb10545d2a80ca9b343a0d/app/controllers/application_controller.rb#L989-L1012) only by column name. It will be more stable if check for "report name" is added. Based on https://github.com/ManageIQ/manageiq-ui-classic/pull/5326#discussion_r266374434
Related to https://github.com/ManageIQ/manageiq/pull/18588 (merged)
@miq-bot add_label hammer/no, technical debt, pending core, wip
> Rewrite column modification to be more stable

- app/controllers/dashboard_controller.rb
- app/controllers/report_controller/dashboards.rb
- app/views/report/_db_form.html.haml
- app/views/report/_db_show.html.haml
- spec/controllers/dashboard_controller_spec.rb
Added a new checkbox "Reset Dashboard upon login" on Group Dashboard add/edit form, if that's set to true when user logs in, their dashboard will be reset and they will loose any changes(i.e add/remove widgets) they have made during their previous session and dashboard will be reset to user's group dashboard. This resolves a case where Admin has edited a group's dashboard and would like the changes to take effect without relying on the user to issue a reset of their dashboard.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1295839
after:
Log in as admin, and verify the user's group dasboard has 'Reset dashboard upon login' set to false
Now login as a user that's part of the group you verified above, verify dashboard looks same as the screenshot above
Now make some changes to dashboard, …
> Reset user's dashboard upon login

- app/presenters/menu/manager.rb
- app/presenters/tree_builder.rb
- app/presenters/tree_builder_ops_rbac_features.rb
- app/presenters/tree_node/menu/item.rb
- app/presenters/tree_node/menu/node.rb
- app/presenters/tree_node/menu/section.rb
- app/presenters/tree_node/miq_product_feature.rb
Well, this is long, :beers: for anyone who reviews it :laughing: 
* I moved the retrieval of some specific options from the tree state to the tree object instead
* The node enumeration has been simplified, some conditions were unnecessary
* Counting the nodes for selecting parents is unnecessary, `post_check` does it for free
* The method overriding all_vm_options doesn't do anything useful so deleted
* Cached root_feature/root_details is no longer shared between methods, no need for caching
* The helper methods in the `TreeNode::Menu::Item` were unnecessary, moved them into the blocks
* We got rid of 3 additional options from `tree_init_options` :trophy: 
> Clean up the RBAC features tree

- app/stylesheet/application-webpack.scss
- package.json
we never depended on the -next version (deprecated), except via react-ui-components
and we now updated react-ui-components to use the current patternfly package
So, fixing here too :)
This fixes travis breaking with..
```
ERROR in ./app/stylesheet/application-webpack.scss (./node_modules/css-loader??ref--8-1!./node_modules/postcss-loader/lib??ref--8-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--8-4!./app/stylesheet/application-webpack.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
@import '~@patternfly/patternfly-next/patternfly.scss';
^
File to import not found or unreadable: ~@patternfly/patternfly-next/patternfly.scss.
```
Caused by https://github.com/ManageIQ/react-ui-components/pull/117 (because it removed …
> Remove @patternfly/patternfly-next references

- app/stylesheet/application-webpack.scss
- package.json
The repo folder has been renamed from `patternfly-next` to `patternfly` probably in a patch version. This is something we should try to avoid, because it can break tests without us doing any changes :cry: 
Anyway, I'm updating PF4 to the latest and updating the path...
@miq-bot add_label bug, dependencies, hammer/no
> Fix the path to the PF stylesheets as it was renamed

- app/controllers/application_controller/miq_request_methods.rb
- app/controllers/miq_ae_class_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/miq_policy_controller/policies.rb
- app/controllers/mixins/actions/vm_actions/reconfigure.rb
- app/controllers/ops_controller/settings/tags.rb
Similar to: https://github.com/ManageIQ/manageiq-ui-classic/pull/5244
Some of these were seen in the QE test suite, prefixed with the
frequency:
```
11 WARN -- : DEPRECATION WARNING: Method each_key is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash. Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.7.2/classes/ActionController/Parameters.html (called from ce_created_audit at /opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-75776f82ef11/app/controllers/ops_controller/settings/tags.rb:258) …
```
> AC Parameters each_key is deprecated use each

- app/presenters/tree_node/assigned_server_role.rb
- app/presenters/tree_node/custom_button_set.rb
- app/presenters/tree_node/ems_folder.rb
- app/presenters/tree_node/miq_action.rb
- app/presenters/tree_node/miq_policy.rb
- app/presenters/tree_node/miq_server.rb
- spec/presenters/tree_node/custom_button_set_spec.rb
- spec/presenters/tree_node/ems_folder_spec.rb
- spec/presenters/tree_node/miq_action_spec.rb
The `options` is coming from the `TreeState` that's coming from the session, let's not rely on it where possible. We have access to the whole tree instead...
> Do not rely on the tree name from options in TreeNode subclasses

- app/views/layouts/_exp_editor.html.haml
Without adblock, this does absolutely nothing. `fa-share` and `fa-mail-forward` are the same (fontawesome 4) icon.
But, adblock removes `fa-share`, presumably because it gets interpreted as a facebook sharing button:
(the forward button is missing an icon ^)
Fixing to also work with adblock :).
Fixes #5643
> Replace fa-share with fa-mail-forward alias - adblock fix

- app/presenters/tree_builder_diagnostics.rb
- app/presenters/tree_node/assigned_server_role.rb
- app/presenters/tree_node/server_role.rb
- spec/presenters/tree_node/assigned_server_role_spec.rb
Instead of using the `options`, passing the data through the `@tree` object when building `TreeNode` subclasses.
@miq-bot add_label refactoring, hammer/no, trees
> Get rid of the parent_kls/parent_name options in TreeBuilderDiagnostics

- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ops_controller/settings/common_spec.rb
After updating a worker's count or memory threshold the Save button was not clickable upon selecting the previous setting until refreshing the page.
@miq-bot add_labels bug, settings
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1704351
> Update Workers Settings form data in @edit after saving

- app/presenters/tree_node/miq_report_result.rb
The `@options[:open_all]` already sets the node as expanded in `x_build_node`, so there's no need for this attribute.
> Do not set the expand attribute of MiqReportResult, it's redundant

- app/presenters/tree_builder.rb
No need for OR-ing the variable with itself if `||=` is available + added some comments that explain what's happening here.
> Simplify the logic that determines if a node should be expanded

- app/presenters/tree_node/node.rb
The `hide_checkbox` isn't a valid attribute of the `@options` hash, therefore, the value will be always false.
> Do not set the hide_checkbox attribute on TreeNodes from options

- app/assets/stylesheets/patternfly_overrides.scss
This PR adjusts the width of react data driven forms based on existing breakpoints.
Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/5649
50% width
75% width
100% width
100% width (mobile)
> make react forms responsive

- app/controllers/mixins/breadcrumbs_mixin.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703744
1. Go to Compute > Infrastructure > Providers
2. Select one (look on breadcrumbs)
3. Switch Summary/Dashboard view (look again on breadcrumbs)
Initially, I designed breadcrumbs to not contain header of show pages, because they contain titles (ex. `(Summary)`, `(Dashboard)`), which are lost after getting deeper in the hierarchy. However, after UX discussion, this behavior is not bad.
So from now the breadcrumbs on show pages will include the whole header (includes `summary`, etc.) and when getting deeper, only name of the record will be used.
Please see [breadcrumbs documentation](https://github.com/ManageIQ/manageiq-ui-classic/wiki/Breadcrumbs)
**Before**
Show page
Edit action
**After**
Show …
> Show whole header in show page breadcrumbs

- app/helpers/application_helper/listnav.rb
We no longer have timelines under cloud intel, so this is not necessary...
> Drop the timeline listnav decision logic for dashboard/timelines

- app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
- app/controllers/cloud_volume_controller.rb
- app/views/cloud_volume/_common_new_edit.html.haml
- spec/controllers/cloud_volume_controller_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1549128
This PR is part of the implementation to allow choosing an availability zone when creating a new Openstack Cinder volume. It makes the existing AWS-specific AZ selection code generic, and allows it to be enabled by checking the `supports_volume_availability_zones` feature. Depends on the core PR which adds `supports_volume_availability_zones`.
> Use feature detection to determine whether AZ should be selectable

- app/assets/stylesheets/patternfly_overrides.scss
- app/stylesheet/application-webpack.scss
- config/webpack/shared.js
- package.json
The decision is to support patternfly 4 only in J-release, not Ivanchuk.
(IE11 support is still going away in Ivanchuk.)
So, reverting #5537, except for introduction of `app/stylesheet/application-webpack.scss`.
And adding guards to prevent accidental requires of patternfly 4 styling from plugins or depedencies.
Cc @skateman @epwinchell @mturley
> Drop patternfly 4 support again

- spec/controllers/cloud_tenant_controller_spec.rb
This is to reflect changes in https://github.com/ManageIQ/manageiq/pull/18827
The above changes caused the following failure:
```
1) CloudTenantController#create queues the create action
Failure/Error: MiqTask.generic_action_with_callback(task_opts, queue_opts)
#<MiqTask(id: integer, name: string, state: string, status: string, message: text, userid: string, created_on: datetime, updated_on: datetime, pct_complete: integer, context_data: text, results: text, miq_server_id: integer, identifier: string, started_on: datetime, zone: string, href_slug: string, region_number: integer, region_description: string, state_or_status: string) (class)> received :generic_action_with_callback with unexpected arguments
expected: ({:action=>"creating Cloud Tenant for user user2897", :userid=>"user2897"}, …
```
> Fix failing cloud_tenant_controller_spec

- app/presenters/tree_builder_vms_filter.rb
setting `@root_class` here was causing incorrect filters to load for Instances/Images Accordions in Cloud/Instances explorer.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1715462
before
after
> set `@root_class` only if it is not already set by subclass

- app/controllers/ops_controller/diagnostics.rb
When building a server/roles tree, it is not necessary to reinitialize the `@record` variable from the tree state. This is just a quick fix to make the bug disappear, I'm refactoring stuff in the area so please forgive me for the ugliness here :pray: 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1715466
> Do not reinitalize the @record when building Server/Roles trees

- app/presenters/tree_node/node.rb
- spec/presenters/tree_node/node_spec.rb
We're never setting the `@options[:expand]` parameter, therefore, this line is always false.
@miq-bot add_label technical debt, trees, hammer/no
> Drop useless expand attribute setting from TreeNode::Node

- app/views/catalog/_sandt_tree_show.html.haml
Responding https://github.com/ManageIQ/manageiq-ui-classic/pull/5592#issuecomment-496655751 by adding ownership information visible on detail screen of Service Catalog Item
Links
* https://github.com/ManageIQ/manageiq-ui-classic/pull/5592#issuecomment-496655751
* https://bugzilla.redhat.com/show_bug.cgi?id=1641905
1. Services -> Catalog
2. Catalog Items accordion -> Add a New Catalog Item
3. Select the created Catalog Item -> Set Ownership
4. Ownership is expected to be visible
Before:
After:
> Make Service Catalog Item ownership visible on detail screen

- app/controllers/ops_controller.rb
Remove redundant tagging buttons for Group Tag edit.
https://bugzilla.redhat.com/show_bug.cgi?id=1710736
Configuration -> Group -> Policy -> Edit Tags
Screenshots
Before:
After:
> Remove redundant tagging buttons for Group Tag edit

- app/controllers/miq_ae_customization_controller.rb
happens when importing a dialog exported in a newer version of manageiq... introduced in https://github.com/ManageIQ/manageiq/pull/18645.
(Doesn't really depend on https://github.com/ManageIQ/manageiq/pull/18645, just doesn't do anything without it.)
Related to
https://bugzilla.redhat.com/show_bug.cgi?id=1684575
https://bugzilla.redhat.com/show_bug.cgi?id=1684567
> Dialog import - add an error message for DialogImportValidator::InvalidDialogVersionError

- app/presenters/tree_builder.rb
The idea is to get rid of the `options` that is coming from the `TreeState` and depend only on the `tree_init_options` instead.
> Do not depend on the TreeState options param in TreeBuilder

- app/services/ansible_tower_job_template_dialog_service.rb
- spec/services/ansible_tower_job_template_dialog_service_spec.rb
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1707614
These changes correct the behaviour of generating default value while creating Service Dialog from Ansible Job Template with a survey
Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1707614
1. have an Ansible Tower provider with a created Job Template with a survey
2. go to Automation - Ansible Tower - Explorer
3. select the Job Template from Templates accordion
4. push Create Service Dialog from this Template button
according to type of field in the survey (multiselect / singleselect), the default value should be set corectly in the generated Service Dialog (Automate - Customization)
> Correct multiselect default value for Ansible Job template survey

- package.json
there was a security warning for the older versions, updating.
We're using this to parse config/webpacker.yml, should probably switch to json, updating for now.
> Update js-yaml to 3.13.1

- app/controllers/application_controller/advanced_search.rb
- app/controllers/application_controller/explorer.rb
- app/controllers/application_controller/filter.rb
- app/controllers/automation_manager_controller.rb
- app/controllers/infra_networking_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/mixins/manager_controller_mixin.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/storage_controller.rb
- app/controllers/vm_common.rb
- app/views/layouts/_adv_search.html.haml
- app/views/layouts/_adv_search_body.html.haml
- app/views/layouts/_adv_search_footer.html.haml
- app/views/layouts/_searchbar.html.haml
- app/views/layouts/_x_adv_searchbox.html.haml
- spec/controllers/vm_common_spec.rb
Currently the advanced search **modal** (`layouts/_adv_search`) is rendered twice on most screens:
* from `layouts/_footer`, unconditionally called from application layout
* from `layouts/_x_adv_searchbox` called from explorer controller explorer views
* from `layouts/_searchbar` called from the `center_div_with_listnav` layout
And the inside of the modal contains logic asking for `show_adv_search?` and `@edit[@expkey]`,
to deteremine whether to render the inside of the modal too.
**But**, all the ajax transition logic assumes the modal is always there, hidden, and tries to replace the inner divs' content (`#adv_search_body`, `#adv_search_footer`), failing when missing.
---
So.. this PR:
* removes any advanced search modal rendering from anywhere but the footer
* this does not affect …
> Advanced search modal - only render once, always, hidden

- app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
- app/assets/javascripts/miq_tree.js
- app/controllers/catalog_controller.rb
- app/presenters/tree_builder_tenants.rb
- app/views/catalog/_form_basic_info.html.haml
- app/views/catalog/_sandt_tree_show.html.haml
- app/views/catalog/_st_angular_form.html.haml
- app/views/catalog/_tenants_tree_show.html.haml
- spec/controllers/catalog_controller_spec.rb
- spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
- spec/views/catalog/_form.html.haml_spec.rb
- spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
**RFE:**
https://bugzilla.redhat.com/show_bug.cgi?id=1678123
**Tracking issue:**
https://github.com/ManageIQ/manageiq/issues/18553
**How to test:**
2. _Configuration > Add a new Catalog Item_
or
select some Item from the list and _Configuration > Edit Selected Item_
3. Choose some _Catalog Item Type_ from the drop down if you are creating a new Catalog Item
=> Catalog Item Edit page is displayed, with the new _Additional Tenants_ option
**TODO:**
- ~~all PRs in https://github.com/ManageIQ/manageiq/issues/18553 need to be merged/finished~~
- ~~generate the proper tree with just Tenants + checkboxes~~
- ~~add angular support for saving selected Tenants (_Ansible Playbook_ Catalog Item type)~~
- ~~solve saving selected Tenants:~~
- …
> Add Tenants tree to Catalog Item Edit page

- app/services/widget_import_service.rb
- spec/services/widget_import_service_spec.rb
When widget is imported, there is related schedule also created.
Schedule(`MiqSchedule`) contains filter (`MiqExpression`) with filter for `MiqWidget` and widget's id (`MiqWidget-id =id of MiqWidget`)
yaml of MiqWidget:
```yaml
- MiqWidget:
guid: 9fd5b5e0-3a89-4247-9601-966c045f9131
description: vms2
MiqSchedule:
name: vms1
description: vms1
sched_action:
:method: generate_widget
filter: !ruby/object:MiqExpression
exp:
"=":
field: MiqWidget-id
value: 500
context_type: 
resource_type: MiqWidget
...
```
see`filter` part.
but when it was created after import than filter was using the origin widget id and it was causing that widget have not been generated. 
This fix updates this filter (`MiqExpression`) when new widget is created and it adds id of newly created widget to filter …
> Fix filter of schedules in widget imports in WidgetImportService

- app/javascript/provider-dialogs/modal.js
The div ID will be derived from component's name: should the component be called `RemoveCatalogItemModal`, the ID assigned to the modal div will be `remove-catalog-item-modal`.
@himdel review please?
https://bugzilla.redhat.com/show_bug.cgi?id=1711046
> Add identifier to provider dialog modal's div

- app/assets/javascripts/components/ops/log-collection-form.js
- app/views/ops/_log_collection.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1717902
1. Configuration -> Diagnostics
2. Select server -> "Collect Logs" tab
3. Click "Edit"
Before:
After:
@miq-bot hammer/no, blocker, bug
@h-kataria please review, thanks :)
> Add missing title to edit of Log Depot Settings

- app/controllers/application_controller/wait_for_task.rb
- app/controllers/mixins/ems_common/angular.rb
- app/controllers/ops_controller/ops_rbac.rb
- spec/controllers/mixins/ems_common/angular_spec.rb
- spec/controllers/ops_controller/ops_rbac_spec.rb
Note, there's no longer a need to ivar set on @_params.  They have a
setter method we should be using as it will initialize the new
ActionController::Parameters object that is the default with rails 5.1:
https://github.com/rails/rails/blob/v5.0.7.2/actionpack/lib/action_controller/metal/strong_parameters.rb#L1059
Fixes:
```
4 WARN -- : DEPRECATION WARNING: #to_hash unexpectedly ignores parameter filtering, and will change to enforce it in Rails 5.1. Enable `raise_on_unfiltered_parameters` to respect parameter filtering, which is the default in new applications. For the existing deprecated behaviour, call #to_unsafe_h instead. (called from get_task_args at /opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-75776f82ef11/app/controllers/mixins/ems_common/angular.rb:134)
1 WARN -- : DEPRECATION …
```
> Fix to_hash 5.1 deprecations

- app/assets/javascripts/components/generic_object/custom-image.js
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1650104
Introduced by #5265
Go to Automation -> Automate -> Generic Objects -> Configuration -> Add a new Generic Object Class -> DO NOT chose a file for Custom Image -> click chosen image
Before:
After:
@miq-bot add_label bug, hammer/yes, generic objects, automation/automate
> Don't repeat error message

- app/views/ops/_category_form.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1717695
before
after
@loicavenel
> Increased size of Description field

- app/assets/stylesheets/about_modal_background.scss
- app/assets/stylesheets/main.scss
- app/views/layouts/application.html.haml
- app/views/layouts/login.html.haml
This is an ugly hack that adds a class on each page's body element that will trigger the custom background image on the about modal. Eventually we would like to have a [feature](https://github.com/patternfly/patternfly-react/issues/2185) in PF for this.
@miq-bot add_label bug, graphics
https://bugzilla.redhat.com/show_bug.cgi?id=1717116
> Display the custom login logo on the about modal

- app/javascript/components/code-editor/index.js
- app/javascript/spec/code-editor/__snapshots__/code-editor.spec.js.snap
Code editor component for react was not rendering correctly if it contained long string. This was happening on first mount and if you copied long text into it.
Fixed by triggering refresh after component mount and also on the onChange event.
> Trigger react code editor refresh after change and after mount.

- app/controllers/tree_controller.rb
Description:
----------------------
Fix broken automate treepicker in dialog editor.
--------------------------------
1) Create automate dialog
2) Add dynamic field with selected `ae_instance`(Options tab)
3) Save the field from step 2
4) Edit field from step 2
5) Go to Options tab and try to change the seleceted `ae_instance`
**old result:** Error and no tree
**new result:** automate tree
**Before:**
**After:**
> Fix for broken automate tree picker in dialog editor.

- app/assets/javascripts/miq_application.js
Services > Catalogs > Orchestration Templates,
see a template detail screen
There is a read only code mirror view of the template .. with a blinking cursor.
This fixes the read only mode to disable cursor in the editor (https://codemirror.net/doc/manual.html#option_readOnly), and not focus the editor when read only.
(This was likely caused by updating the code mirror in https://github.com/ManageIQ/manageiq-ui-classic/pull/5672.)
> Codemirror - :read_only => true didn't imply no cursor

- app/views/catalog/_ot_tree_show.html.haml
We're rendering codemirror only sometimes,
so we can't refresh it when not rendering it.
Moving the refresh call inside the condition.
---
Services > Catalogs > Orchestration Templates,
see a template detail screen, reload the page
there will be an error in the console without this change
> Orchestration templates - fix Cannot read property refresh of null

- app/javascript/components/taggingWrapper.jsx
Disable Save/Reset tagging buttons when there are no changes.
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1719184
1. Go to configuration > access control > groups > click on any group and select 'Edit My Company Tags for this group' from policy dropdown
2. See the buttons Save and Reset
> Disable Save/Reset tagging buttons when there are no changes

- app/views/dashboard/login.html.haml
In case you have configured replication on your ManageIQ appliance, this change will render type of region you're logging into (global or remote) on login screen.
https://bugzilla.redhat.com/show_bug.cgi?id=1678142
> Show replication type on login screen

- app/javascript/components/remove-catalog-item-modal.jsx
1. Create catalog item
2. Order the catalog item several times
3. Try to delete the catalog item
Before:
After:
I personally do not have a problem with showing multiple services with the same name, but I'll leave it for broader audience to decide.
https://bugzilla.redhat.com/show_bug.cgi?id=1706863
> Catalog item delete: don't show duplicate service names

- app/helpers/ems_cloud_helper/textual_summary.rb
- app/helpers/ems_infra_helper/textual_summary.rb
- app/views/catalog/_sandt_tree_show.html.haml
- app/views/miq_ae_class/_ns_list.html.haml
- product/views/ManageIQ_Providers_CloudManager.yaml
- product/views/ManageIQ_Providers_InfraManager.yaml
- spec/helpers/ems_cloud_helper/textual_summary_spec.rb
- spec/helpers/ems_infra_helper/textual_summary_spec.rb
- spec/shared/helpers/textual_summary_helper_methods.rb
- spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
- spec/views/miq_ae_class/_ns_list.html.haml_spec.rb
**RFE:**
https://bugzilla.redhat.com/show_bug.cgi?id=1678122
More:
https://docs.google.com/document/d/1rpgBQA_MAfqZY00dnbRLMiOzqhbrB60UdnvSgg7X--Y/edit
**What:**
This PR adds displaying Tenant name in _Providers, Automate Domain_ and _Services_. Tenant name will be displayed with this PR in _Summary View_ of cloud or infra provider, in _Relationships_ table. Also a new column with the Tenant name will be displayed in the _List view_ of a Provider, Automate Domain or a Service Catalog Item/Catalog Bundle (it will not be included in: _Grid View, Tile View, Dashboard view_).
**How to test:**
- For providers:
_Compute -> Infrastructure/Clouds -> Provider_
and choose some provider if you want to check the Summary view
- For Automate Domain:
_Automation -> Automate -> Explorer_
- For Services: …
> Add Tenant relationship in Providers, Automate Domain and Services

- spec/controllers/application_controller/ci_processing_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_common_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/controllers/ems_physical_infra_controller_spec.rb
- spec/controllers/ems_storage_controller_spec.rb
- spec/controllers/ops_controller/settings/common_spec.rb
- spec/controllers/ops_controller/settings/schedules_spec.rb
- spec/controllers/orchestration_stack_controller_spec.rb
- spec/controllers/vm_common_spec.rb
- spec/helpers/application_helper/buttons/ems_refresh_spec.rb
- spec/helpers/application_helper/buttons/ems_storage_timeline_spec.rb
- spec/helpers/application_helper/buttons/physical_server_provision_spec.rb
- spec/helpers/application_helper/buttons/set_ownership_spec.rb
- spec/helpers/application_helper/buttons/zone_delete_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/ems_cloud_helper/textual_summary_spec.rb
- spec/helpers/ems_infra_helper/textual_summary_spec.rb
- spec/helpers/ems_network_helper/textual_summary_spec.rb
- spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb
- spec/helpers/ems_storage_helper/textual_summary_spec.rb
- spec/helpers/generic_object_helper/textual_summary_spec.rb
- spec/helpers/report_helper/editor_spec.rb
- spec/presenters/tree_builder_smartproxy_affinity_spec.rb
- spec/presenters/tree_node/ext_management_system_spec.rb
- spec/services/ems_cloud_dashboard_service_spec.rb
- spec/services/ems_infra_dashboard_service_spec.rb
- spec/services/topology_service_spec.rb
- spec/views/shared/views/ems_common/_show.html.haml_spec.rb
This fixes a bunch of specs that aren't creating leaf subclasses for emses.
The original ticket is to remove GCE provider downstream but in order to do this, we have to validate that the provider being added is of a type that's supported. Which means that everywhere we have specs with providers without types, those tests will now 🐡
for https://github.com/ManageIQ/manageiq/pull/18842 but since it's just test cleanup could get in before that PR without any issues
> Test emses with actual leaf subclasses

- app/controllers/application_controller/filter.rb
This PR fixes a bug where the 'NOT' element could not be deleted in the Expression Editor.
https://bugzilla.redhat.com/show_bug.cgi?id=1720216
Old
New
>  Expression Editor fix

- app/controllers/application_controller/explorer.rb
- app/controllers/service_controller.rb
The services tree has no special option related to the node id generation, therefore, the argument of `generic_x_show` is obsolete. This also allows to completely get rid of the optional argument.
> Drop obsolete argument of generic_x_show

- app/controllers/ops_controller/settings/common.rb
- spec/services/infra_topology_service_spec.rb
Extracted from #5676 
* Use a general path that works for compiled/uncompiled assets
* 5.1 AC::Parameters doesn't have each_value, use each
> Fix rails 5-1 issues

- app/services/dialog_local_service.rb
- spec/services/dialog_local_service_spec.rb
Running a custom button on a storage manager should return you to the page of storage managers, not infra emses. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710350
> Storage managers should have target types of storage, not ems_infra

- app/controllers/ops_controller/ops_rbac.rb
- spec/controllers/ops_controller/ops_rbac_spec.rb
Note, permit doesn't permit non-scaler values by default and since
:quotas is a subhash, we need to permit the entire hash.
See also:
https://edgeguides.rubyonrails.org/action_controller_overview.html#permitted-scalar-values
Also, the code expects symbol keys so we need to keep them as symbols.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1721130
The change for rails 5.1 AC::Parameters not being a hash was added in:
cd71601#diff-8078c760e06b820719715450b2a112e0R158
> Require and permit the :quotas subhash

- spec/controllers/application_controller/ci_processing_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_common_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/controllers/ems_physical_infra_controller_spec.rb
- spec/controllers/ems_storage_controller_spec.rb
- spec/controllers/ops_controller/settings/common_spec.rb
- spec/controllers/ops_controller/settings/schedules_spec.rb
- spec/controllers/orchestration_stack_controller_spec.rb
- spec/controllers/vm_common_spec.rb
- spec/helpers/application_helper/buttons/ems_refresh_spec.rb
- spec/helpers/application_helper/buttons/ems_storage_timeline_spec.rb
- spec/helpers/application_helper/buttons/physical_server_provision_spec.rb
- spec/helpers/application_helper/buttons/set_ownership_spec.rb
- spec/helpers/application_helper/buttons/zone_delete_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/ems_cloud_helper/textual_summary_spec.rb
- spec/helpers/ems_infra_helper/textual_summary_spec.rb
- spec/helpers/ems_network_helper/textual_summary_spec.rb
- spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb
- spec/helpers/ems_storage_helper/textual_summary_spec.rb
- spec/helpers/generic_object_helper/textual_summary_spec.rb
- spec/helpers/report_helper/editor_spec.rb
- spec/presenters/tree_builder_smartproxy_affinity_spec.rb
- spec/presenters/tree_node/ext_management_system_spec.rb
- spec/services/ems_infra_dashboard_service_spec.rb
- spec/services/topology_service_spec.rb
- spec/views/shared/views/ems_common/_show.html.haml_spec.rb
The Seal of Approval was revoked on my nice try of changing tests to use only leaf ext management classes so this reverts those few specs that I conned MartinH into changing.
Mea maxima culpa. 
Jason doesn't like https://github.com/ManageIQ/manageiq-ui-classic/pull/5705, see https://github.com/ManageIQ/manageiq/pull/18842#issuecomment-502261340, so it required this revert.
> Revoke spec changes to use only leaf classes of emses

- app/views/ops/_settings_server_tab.html.haml
The PR adds a data-container target of "body" to bootstrap select to prevent dropdown from being cut off.
https://bugzilla.redhat.com/show_bug.cgi?id=1718834
Old
New
> Server Settings Timezone dropdown fix

- app/presenters/tree_builder_belongs_to_hac.rb
I was trying to wrap my head around this for an hour and I think this top-level `if` is not necessary. Maybe I am wrong, but even if it would break stuff, we should not feed data to the trees that we're not using inside. Therefore, if my changes break something, I'd rather move the conditional outside of the tree when we're building the `selected_nodes`.
> Simplify the condition for checking nodes in TreeBuilderBelongsTo*

- app/assets/javascripts/miq_angular_application.js
- app/controllers/generic_object_definition_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/mixins/sandbox.rb
- app/views/generic_object_definition/_generic_object_definition_form.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1719889
Go to Automate -> Automation -> Generic Objects -> click different items in a tree
I'm pretty sure that GOD controller was missing `features` method and was going the wrong way in `data_for_breadcrumbs`. I looked at Automate -> Automation -> Customization -> Custom buttons for reference on how a breadcrumb should look like.
**Known issue**: If you Edit Generic Object Definition and click on breadcrumbs it will redirect you to `show_list` with `All Generic Object Classes`. It can be fixed by rewriting the whole controller :D
Before:
After:
@miq-bot add_label bug, hammer/no, changelog/no, generic objects
cc: @rvsia @martinpovolny
> Fix GOD breadcrumbs

- app/assets/stylesheets/print.scss
- app/javascript/packs/print.js
- app/views/layouts/print.html.haml
We're running the `spec` spec without yarn -> no node_modules/@manageiq/ui-components .
Since https://github.com/ManageIQ/manageiq/pull/18869 (Rails 5.1 preparations), tests are failing because the print.scss file started failing when the file is missing.
https://github.com/ManageIQ/manageiq-ui-classic/pull/5679 is moving all of app/assets/stylesheets to webpack,
but is not ready yet.
=> created a "print" webpack pack,
included in the print layout,
and moved the ui-components css include there.
(Any subsequent cleanup will happen as part of https://github.com/ManageIQ/manageiq-ui-classic/pull/5679 , need this quickly in to fix travis.)
> Add a "print" webpack pack, move ui-components css there

- spec/javascripts/support/jasmine_helper.rb
we're using hamlit everywhere else,
and recently https://github.com/ManageIQ/manageiq/pull/18886 was merged,
dropping the haml_lint dependency, but also the implied haml dependency.
=> Replacing with an equivalent hamlit invocation
> Jasmine - use hamlit instead of haml

- app/presenters/tree_builder_belongs_to_hac.rb
- spec/presenters/tree_builder_belongs_to_hac_spec.rb
As discussed with @lfu and @lgalis, the policy profile assignment and RBAC host and cluster trees should consistently not display the embedded Ansible provider.
@miq-bot add_reviewer @lfu 
@miq-bot add_reviewer @lgalis 
@miq-bot add_reviewer @kbrock 
> Make root node fetching for BelongsTo* trees consistent

- app/controllers/static_controller.rb
- app/helpers/application_helper.rb
- config/routes.rb
Fixes `ActionController::RoutingError (No route matches [GET] "/favicon.ico")`
happening whenever the browsers tries to load a favicon without parsing the html layout first.
We just redirect to the right image path.
(In `StaticController` because that one does not require login.)
Cc @djberg96 :)
> Add /favicon.ico route to redirect to the right miq_favicon_path

- app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
- app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
- app/assets/javascripts/controllers/schedule/schedule_form_controller.js
- app/controllers/catalog_controller.rb
- app/controllers/ops_controller/settings/schedules.rb
- app/views/catalog/_form_basic_info.html.haml
- app/views/catalog/_sandt_tree_show.html.haml
- app/views/catalog/_st_angular_form.html.haml
- app/views/ops/_schedule_form_filter.html.haml
- spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
- spec/views/catalog/_form.html.haml_spec.rb
This commit adds a zone drop down to angular and non-angular catalog item add/edit forms.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1415106
Non- Angular form
Angular form
Details screen
Automation Task Schedule edit screen
Automation Task Schedule details
> Added Zone drop down to angular and non-angular catalog item editor & Automate Task Schedules

- app/presenters/tree_builder_belongs_to_vat.rb
The conditions were a little messy, the point is that only the blue folders should have checkboxes.
@miq-bot add_label refactoring, hammer/no, trees
> Simplify the override conditions in TreeBuilderBelongsToVat

- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_belongs_to_vat.rb
These methods are a little complex, even after the refactoring, but it's getting better :wink: 
@miq-bot add_label refactoring, hammer/no, trees
> Clean up datastore fetching in TreeBuilderBelongsTo* trees

- app/views/layouts/_policy_sim.html.haml
This PR is a followup to https://github.com/ManageIQ/manageiq-ui-classic/pull/5681, where my fix caused a double title when navigating via a VM summary screen.
https://bugzilla.redhat.com/show_bug.cgi?id=1717539
Old
New
> Policy Sim title fix

- app/assets/javascripts/controllers/tree_view_controller.js
- app/assets/javascripts/miq_global.js
- app/views/layouts/listnav/_explorer.html.haml
- app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml
I did some profiling around the TreeView with 5 thousand nodes and I realized that the bottleneck is in Angular and not the TreeView code. I asked @himdel about the problem and we realized that this was caused by a [bugfix](https://github.com/ManageIQ/manageiq-ui-classic/pull/3785) that started sending the tree data as an object instead of a string. The object is being parsed by angular and if it is 5MB, well :turtle: :snail: happens.
The solution is to get the data into the component in an alternative way, so preventing Angular from unnecessarily parsing it. Ideally this could be solved by having separate (UI-)API endpoints for trees, but we're not there yet. So our solution was to utilize the `ManageIQ.trees` global object by temporarily saving the data into it until the component gets …
> Do not let angular parse the treeview data as it can be 🐢 HUGE 🐌

- app/presenters/menu/item.rb
- app/presenters/menu/manager.rb
- app/presenters/menu/settings_loader.rb
- app/presenters/menu/yaml_loader.rb
- app/presenters/tree_builder_ops_rbac_features.rb
- app/views/layouts/_vertical_navbar.html.haml
- config/settings.yml
- spec/presenters/menu/menu_manager_spec.rb
- spec/presenters/menu/settings_loader_spec.rb
- spec/support/menu_helper.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1678151
* only allow top-level items
* only at the bottom of the menu
* only allow items (not sections)
Example (under Server settings, Advanced settings):
```
:ui:
:custom_menu:
- :type: item
:icon: fa fa-bug
:id: custom_i1
:name: Custom Item 1
:href: https://www.redhat.com
:rbac: vm_explorer
- :type: item
:icon: pficon pficon-help
:id: custom_i2
:name: Custom Item 2
:href: https://www.hmpf.cz
:rbac: vm_explorer
```
list of supported icons:
* https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/icons.html
* https://manageiq.github.io/font-fabulous/
* https://fontawesome.com/v4.7.0/icons/
based on the source of the icon the specification is either `fa fa-bug` (where fa-bug is the font awesome icon) of `pf pficon-help` (where …
> Menu item adding through settings

- app/assets/javascripts/components/generic_object/main-custom-button-form.js
- app/controllers/generic_object_definition_controller.rb
- app/views/static/generic_object/main_custom_button_form.html.haml
- config/routes.rb
- spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650559
Go to Automation -> Automate -> Generic Object -> create or edit a button -> select Button type to be Ansible Playbook
Depends on https://github.com/ManageIQ/manageiq/pull/18379
Before:
After:
Ansible Catalog Item is required!
@miq-bot add_label wip, bug, hammer/yes, gaprindashvili/yes, generic objects, automation/
automate
> Add Ansible related inputs to GOD haml

- app/helpers/application_helper.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1722487
@himdel please review, prior to changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/5629 Advanced search was not visible in Automation Manager explorer which in itself was a bug but no one noticed that, after changes in above mentioned PR, model is being passed in an empty string from https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/automation_manager_controller.rb#L64 
Causing an error 
```
[----] F, [2019-06-20T11:47:52.978663 #6136:4f8de4c] FATAL -- : Error caught: [ActionView::Template::Error] undefined method `name' for nil:NilClass
/home/hkataria/dev/manageiq/lib/miq_expression.rb:935:in `build_relats'
/home/hkataria/dev/manageiq/lib/miq_expression.rb:890:in `get_relats' …
```
> Added missing Model name to return that is used to load advanced search

- app/controllers/catalog_controller.rb
This bug has been indtroduced by #5445 and it's reproducible if you try to navigate to the catalog of a service from the service's summary screen. The problem is in `build_tenants_tree` where the existence of `@edit[:key]` is not tested properly before using its value.
This is just a simple fix to work around the issue, probably not the final solution as the whole implementation is a little messy. I am willing to do some cleanup, but I have other stuff to do right now and I. won't be available most of next week. Until then, this can work as a temporary solution.
@miq-bot add_label bug, hammer/no, services
https://bugzilla.redhat.com/show_bug.cgi?id=1722478
> Test if the @edit[:key] is set to prevent exceptions in Catalogs

- app/presenters/tree_builder_belongs_to_hac.rb
Scopes are better as @kbrock said, we should not refer to DB objects in the UI when possible.
@miq-bot add_label trees, hammer/no, pending core
Depends on: https://github.com/ManageIQ/manageiq/pull/18903
> Use a named scope for loading assignable EMSes in BelongsToHac 🌳

- app/helpers/service_helper/textual_summary.rb
- spec/helpers/service_helper/textual_summary_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1677571
@tinaafitz review.
> Display Lifecycle State on Service details screen

- app/controllers/miq_policy_controller/alert_profiles.rb
- spec/controllers/miq_policy_controller/alert_profiles_spec.rb
When saving `Notes` field value, it was setting `Description` to blank, causing flash error on screen
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1723815
before
after
> Fixed issue introduced in c7536077b36b56ebbaa9fe9ec6bbcf22aab32248

- spec/controllers/application_controller/ci_processing_spec.rb
- spec/controllers/generic_object_controller_spec.rb
- spec/controllers/generic_object_definition_controller_spec.rb
- spec/controllers/guest_device_controller_spec.rb
- spec/controllers/mixins/actions/vm_actions/rename_spec.rb
- spec/controllers/physical_chassis_controller_spec.rb
- spec/controllers/physical_rack_controller_spec.rb
- spec/controllers/physical_server_controller_spec.rb
- spec/controllers/physical_storage_controller_spec.rb
- spec/controllers/physical_switch_controller_spec.rb
- spec/controllers/pxe_controller_spec.rb
- spec/views/shared/views/ems_common/_show.html.haml_spec.rb
No need to set the zone if it isn't used somewhere else in the spec.  The factory for `:miq_server` will create a zone for you.
> EvmSpecHelper.local_miq_server already creates a zone

- app/helpers/application_helper/toolbar/basic.rb
- spec/helpers/application_helper/toolbar/basic_spec.rb
Newly any plugin can add content to to toolbars. Not only providers.
Plugged-in toolbars should implement class method:
```
def self.record_valid?(record)
...
end
```
that decides if the toolbar is to be displayed for a particular record.
Example display only for vmWare VMs:
```
def self.record_valid?(record)
record.kind_of?(ManageIQ::Providers::Vmware::InfraManager::Vm)
end
```
Please note that such level of control is only available for the
toolbars on the detail pages. Not for the toolbars on the listing pages.
Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1678194
Example:
https://github.com/martinpovolny/miq_plugin_example/pull/10
The below should actually be already done. Just I am not sure how well it is documented.
* backend changes: need something like …
> Extend toolbar pluggability to all plugins.

- app/controllers/application_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1723899
Apply named search 
before
after
> Do not filter records when loading Pre Provisioning screen.

- app/controllers/mixins/breadcrumbs_mixin.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Solves https://github.com/ManageIQ/manageiq-ui-classic/issues/5698
`Configuration` > `Access Control` > Select a group > `Policy` > `Edit tags...`
When `special_breadcrumb` method (used for obtaining title when tagging, ownership, etc.) is empty, it returns `nil` instead of `{:title => nil}`. Nil is removed when breadcrumbs array is compacted.
**Before**
**After**
@miq-bot add_label bug, breadcrumbs, hammer/no
> Return nil when special breadcrumb title is empty

- app/controllers/miq_ae_customization_controller.rb
- spec/controllers/miq_ae_customization_controller_spec.rb
The dialog field circular reference checker got refactored (https://github.com/ManageIQ/manageiq/pull/18890) and backported to hammer and this fixes the specs broken by that and changes the error inheritance to be correct. 
Related master PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/5755
> [HAMMER] Rescue the right kind of error from the dialog field circular reference checker

- app/assets/stylesheets/patternfly_overrides.scss
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1724496
> Fix overrided color for disabled Timelines link

- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ops_controller/settings/common_spec.rb
Fixes issue caused by https://github.com/ManageIQ/manageiq/pull/18578  Psst, @djberg96...
Before:
After:
@miq-bot add_labels bug, settings
https://bugzilla.redhat.com/show_bug.cgi?id=1726306
> Ensure replication related flash messages show task name

- app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
- app/assets/javascripts/controllers/playbook-reusable-code-mixin.js
- app/controllers/catalog_controller.rb
- app/views/catalog/_form_basic_info.html.haml
- app/views/catalog/_sandt_tree_show.html.haml
- app/views/catalog/_st_angular_form.html.haml
- app/views/catalog/_svccat_tree_show.html.haml
- spec/controllers/catalog_controller_spec.rb
- spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
Added Currency drop down and Price text field to Angular and non-angular Catalog Item editors. And update Catalog Item details screen t show the price information.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1602072
Angular Version Catalog Item editor
Non- Angular version Catalog Item editor
Catalog Item summary screen
Price info on Catalog Service detail screen
Service that has no pricing info saved
Catalog Item edit, show price as required field when Currency has been selected.
> Added Price to Catalog Items.

- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_common_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/controllers/guest_device_controller_spec.rb
- spec/controllers/miq_ae_tools_controller_spec.rb
- spec/controllers/miq_policy_controller_spec.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
- spec/controllers/ops_controller/diagnostics_spec.rb
- spec/controllers/ops_controller/settings/automate_schedules_spec.rb
- spec/controllers/ops_controller/settings/schedules_spec.rb
- spec/controllers/physical_chassis_controller_spec.rb
- spec/controllers/physical_rack_controller_spec.rb
- spec/controllers/physical_server_controller_spec.rb
- spec/controllers/physical_storage_controller_spec.rb
- spec/controllers/physical_switch_controller_spec.rb
- spec/controllers/picture_controller_spec.rb
- spec/helpers/compliance_summary_helper_spec.rb
- spec/helpers/vm_helper/textual_summary_spec.rb
- spec/helpers/vm_helper_spec.rb
- spec/presenters/tree_builder_datastores_spec.rb
- spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
- spec/views/layouts/list_grid.html.haml_spec.rb
Don't set `id`, `name` and other things that are sequenced in tests unless it needs to be set.  `id` is particularly bad because our tests need to be region aware.
Unfortunately there are more... `git grep ":id\s*=>\s*[0-9]"`
> Ids in specs

- app/helpers/ansible_credential_helper/textual_summary.rb
- spec/helpers/ansible_credential_helper/textual_summary_spec.rb
The options field for ansible credentials can be nil as the options column in the authentications table is nullable.
This PR fixes the ansible credential textual summary helper to handle situations where we attempt to display fields that could be in options and are not and adds tests for these situations.
Gist of an example failure => https://gist.github.com/carbonin/06148fb88ccba952a2f4f43d332b3d20
This happens when navigating to the credential details page for a machine credential with a `nil` `options` column.
> Handle nil options and missing keys in ansible credentials

- app/controllers/ops_controller/ops_rbac.rb
Before upgrading rails to `5.1` it was permitted to pass ```ActiveRecord::Base```  ```find``` method. After upgrade:
```
FATAL -- : Error caught: [ArgumentError] You are passing an instance of ActiveRecord::Baseto `find`. Please pass the id of the object by calling `.id`.
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:451:in `find_one'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:440:in `find_with_ids'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:66:in `find'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/querying.rb:3:in `find'
/opt/rh/cfme-gemset/gems/activerecord-5.1.7/lib/active_record/core.rb:178:in `find' …
```
> Fixed  deleting users

- app/controllers/ops_controller/diagnostics.rb
- app/presenters/tree_builder_diagnostics.rb
- app/presenters/tree_builder_roles_by_server.rb
- app/presenters/tree_builder_servers_by_role.rb
- spec/presenters/tree_builder_roles_by_server_spec.rb
- spec/presenters/tree_builder_servers_by_role_spec.rb
These two issues with diagnostics (server by roles and roles by server) trees under configuration have been introduced by #5389 and #5661. As some parts of the first PR are being used elsewhere, I reverted the related commits only.
We will need more tests in the area trying to refactor this for the second run. Setting a sandbox variable inside a `TreeBuilder` is a bad practice and we should avoid it, but here it created a technical debt so complex that the refactoring is painful (as you see the bugs).
@miq-bot add_label bug, trees, hammer/no
* Revert "Do not reinitalize the @record when building Server/Roles trees"
This reverts commit 452a00f6db3315bf7d6aad202fd434bd0bcf6dc8.
* Revert "Extract the sandbox variables from the Server/Roles tree builders"
This …
> Revert the sandbox variable refactoring on Settings/Diagnostics trees

- app/javascript/components/remove-catalog-item-modal.jsx
1. Create catalog item `catalog01`
2. Create catalog bundle `bundle01` with `catalog01` in it
3. Try to delete `catalog01` in UI
Previously, the UI would report successful deletion, although in truth no deletion would take place. In this particular case, for the delete request the API returns `http/200` and the following JSON:
```json
{"success":false,"message":"Cannot delete a service that is the child of another service."}
```
so we need to adjust our code accordingly.
With the proposed fix in place:
https://bugzilla.redhat.com/show_bug.cgi?id=1356086
> Fix catalog item delete when part of catalog bundle

- app/controllers/report_controller/saved_reports.rb
- spec/controllers/report_controller_spec.rb
The accordion name got an extra prefix (guessing since the angular-bootstrap update) but a test for fetching a saved report hasn't been adjusted to that.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724209
> Adjust the test against the accordion name at saved reports

- product/views/Service.yaml
We were able to speed up the services page, but we lost sorting and proper pagination. So we are temporarily reverting #5366
This reverts commit 3f609dab512cf49350cb10545d2a80ca9b343a0d, reversing
changes made to 2f31e65a702754ef962432a3f1e10bd4ff8b1b55.
Fixes:  https://bugzilla.redhat.com/show_bug.cgi?id=1722491
NOTE: This page is now slow again. This change and other code fixes will need to be introduced again in another PR.
@miq-bot add_label bug, hammer/yes, services
> Revert faster services PR 5366 

- app/controllers/service_controller.rb
Remove duplicate tagging edit buttons for Services
Screenshots
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1722480
1.Provision the service 
2.Go to My service page-> Go to Active service details page 
3.From Policy click on Edit Tags
> Remove duplicate tagging edit buttons for Services

- product/views/MiqTask.yaml
In report.yaml file, `conditions:` contain an MiqExpression or null
It should not contain a hash.
No other reports or views contain a hash
This PR changes the conditions to a null
@miq-bot add_label hammer/no, technical debt, automation/ansible tower, changelog/no
> fix miq task conditions

- app/controllers/application_controller/miq_request_methods.rb
- app/views/miq_request/_request.html.haml
Same as https://github.com/ManageIQ/manageiq-ui-classic/pull/5461, but for firmware update instead provisioning.
> Show affected servers on PhysicalServerFirmwareUpdateRequest

- spec/controllers/vm_common_spec.rb
https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/555818466:
```
Failures:
1) VmOrTemplateController#reload  sets params[:id] to hidden vm if its summary is displayed
Failure/Error: expect(controller.params[:id]).to eq("v-#{@vm.id}")
expected: "v-33000000000001"
got: "f-33000000000001"
```
The [controller code](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/vm_common.rb#L81-L85) is probably subtly wrong, but I'm not sure *how*:
* If the id param should always win, maybe `params[:id].present? ? "v-#{params[:id]}" : x_node` would be the best solution in `reload`.
* If `x_node` should win, it's not clear when.
But, when both the folder id and the vm id are the same, the code does not behave as expected.
Fixing in test for now.
(seed to …
> vm_common#reload spec - prevent sporadic failure when folder id matches vm id

- app/controllers/catalog_controller.rb
- app/javascript/components/orchestration-template/service-dialog-from-ot.jsx
- app/javascript/components/orchestration-template/service-dialog-from-ot.schema.js
- app/javascript/packs/component-definitions-common.js
- app/javascript/spec/orchestration-template/service-dialog-from-ot.spec.js
- app/views/catalog/_service_dialog_from_ot.html.haml
- config/routes.rb
- spec/controllers/catalog_controller_spec.rb
- spec/routing/catalog_routing_spec.rb
Form is at `Service > Catalogs >  Orchestration Templates tab > select template > open Configuration dropdown > Create service Dialog from orchestration template`
waiting for: ~https://github.com/ManageIQ/manageiq-api/pull/596~ and ~#5552~
> Migrate service dialog from orchestration template from to data driven forms

- app/controllers/ops_controller/settings/analysis_profiles.rb
- spec/controllers/ops_controller/settings/analysis_profiles_spec.rb
When a category is unchecked in the UI, correct data was not being set to be deleted from saved version of data.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1727929
after
> Set value of hash to be deleted from saved data.

- app/presenters/tree_builder_services.rb
- spec/presenters/tree_builder_services_spec.rb
Same fix as I did for [hammer](https://github.com/ManageIQ/manageiq-ui-classic/pull/5530), just adjusted to the latest master. This isn't the complete fix, I'm also working on a way to stop the tree from rendering if the number of nodes exceeds a threshold.
To avoid an N+1, the whole tree is being cached in an instance variable, so we can leverage the same data in `x_get_tree_nested_services` without additional querying. The method is being called for all nodes, to determine if it has any children, i.e. it is lazily loadable or not so this is a big help. cc @kbrock 
@miq-bot add_label trees, bug, hammer/no, services …
> Restore the service tree hiearachy and implement lazy loading for nested services

- app/helpers/miq_ae_tools_helper.rb
- app/views/miq_ae_tools/_import_export.html.haml
- spec/helpers/miq_ae_tools_spec.rb
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1714493
We need to do some major changes to both UI and backed in order to refactor the import/export feature. There is some strange showing/hiding the UI parts, API(ui-classic) polling which locks up the UI nad no UX.
This will take more effort so until then we just revert the breaking UI changes.
> Reverted changes to git import form.

- app/helpers/application_helper/toolbar/tasks_center.rb
Fix inconsistend wording label vs tooltip vs rest of the UI.
> Fix the wording Job -> Task.

- spec/controllers/catalog_controller_spec.rb
The factory sets name and description, we don't need to do this in specs.
> Don't set unnecessary attributes with FactoryBot in specs

- spec/controllers/cloud_network_controller_spec.rb
We don't need to do this, the factory sets these.
> Don't set name and description of tags in specs

- app/services/user_validation_service.rb
- spec/controllers/dashboard_controller_spec.rb
**Fixes BZ:**
https://bugzilla.redhat.com/show_bug.cgi?id=1726721
**What:**
The core of the problem is that, newly, new provider was added (Embedded Ansible) and it is preinstalled on MIQ by default, so after user (super admin) logs in, it behaves according to the code => Default dashboard is displayed, instead of expected 'Add a Provider' page, as it was in the past. So the code needs to be updated according to the new circumstance. However, there are more options to solve the situation. I decided to fix this in the same place where the problem takes shape. Feel free to add comments, ideas.
**Note:**
I was able to reproduce the BZ locally. I've tested the fix with empty and non-empty DB, and it works.
**Before:**
**After:**
> Fix displaying 'Add a Provider' page on a fresh appliance

- app/controllers/miq_ae_tools_controller.rb
- app/controllers/ops_controller/settings/automate_schedules.rb
- app/helpers/application_helper.rb
- spec/controllers/miq_ae_tools_controller_spec.rb
**Fixes BZ:**
https://bugzilla.redhat.com/show_bug.cgi?id=1719322
**What:**
When selecting `Group` or `Tenant` _Type_ for _Object Attribute_ for Automation Simulation, errors occurred. This PR fixes them.
For EVM Group, there was only `description` column, instead of `name`.
For Tenant, `use_config_for_attributes` was missing.
**Details:**
The problem occurred here: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/miq_ae_tools_controller.rb#L439
The same problem was fixed here: https://github.com/ManageIQ/manageiq-ui-classic/pull/5321 so I moved the method to application helper, available for different controllers, so then scenario from https://github.com/ManageIQ/manageiq-ui-classic/pull/5321 remains working. Please, let me know if you think the method should …
> Fix Object Attribute Type selection for Group and Tenant

- app/presenters/tree_node/menu/item.rb
The fratures tree under RBAC/roles displayed wrong node titles because of a typo in `set_attributes` made it `set_attribute` which can't handle the array as the return value in its block.
**Before:**
**After:**
@miq-bot add_label bug, hammer/no, trees
> Fix the title/tooltip attribute setting for TreeNode::Menu::Item

- app/controllers/ems_cloud_controller.rb
- app/controllers/ems_infra_controller.rb
- product/views/ManageIQ_Providers_CloudManager.yaml
- product/views/ManageIQ_Providers_InfraManager.yaml
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
Non admin(=super-admin) logged:
👀 look on Tenant column.
before
CLOUD provider list
INFRA provider list
**after**
CLOUD provider list
INFRA provider list
hiding mechanism has been implemented and used here for service templates: 
https://github.com/ManageIQ/manageiq-ui-classic/pull/5616
https://bugzilla.redhat.com/show_bug.cgi?id=1678122
> Hide Tenant Name for Infra and Cloud providers in list views for non-admin users

- app/controllers/report_controller/saved_reports.rb
Followup on https://github.com/ManageIQ/manageiq-ui-classic/pull/5779, somehow missed it.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724209
> Adjust the test against accordion name in saved reports (part 2)

- app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml
```
$ be rake locale:plugin:find[ManageIQ::UI::Classic]
** override_gem("manageiq-ui-classic", :path=>"/home/milan/src/manage-iq/manageiq-ui-classic") at /home/milan/src/manage-iq/manageiq/bundler.d/pry.rb:5
** Using session_store: ActionDispatch::Session::MemCacheStore
** ManageIQ master, codename: Ivanchuk
Error parsing /home/milan/src/manage-iq/manageiq-ui-classic/app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml
rake aborted!
Haml::InvalidAttributeNameError: Invalid attribute name 'miq-select ' was rendered
/home/milan/src/manage-iq/manageiq/lib/tasks/locale.rake:210:in `block (2 levels) in <top (required)>'
/home/milan/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/home/milan/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
Tasks: TOP => gettext:po:update => …
```
> Remove whitespace from attribute name

- app/controllers/chargeback_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/report_controller.rb
- app/presenters/menu/default_menu.rb
- app/presenters/tree_builder.rb
- spec/presenters/menu/custom_loader_spec.rb
By @terezanovotna's suggestion, we're renaming the menu item.
**Before:**
**Afer:**
Resolves https://github.com/ManageIQ/manageiq-ui-classic/issues/5808
https://bugzilla.redhat.com/show_bug.cgi?id=1678196
@miq-bot add_reviewer @PanSpagetka 
@miq-bot add_label enhancement, hammer/no, ux/review
> Rename the "Cloud Intel" menu item to "Overview"

- app/controllers/ems_physical_infra_controller.rb
- app/controllers/ops_controller/settings/upload.rb
- app/controllers/security_group_controller.rb
We must not use string interpolation with `#{}` in gettext strings: http://manageiq.org/docs/guides/i18n#string-interpolation
Strings that come out of string interpolation with `#{}` are in fact new strings, which are not present in the catalog. We must use `%{}` instead.
> Don't use string interpolation inside gettext strings

- app/controllers/firmware_binary_controller.rb
- app/controllers/firmware_registry_controller.rb
- app/controllers/firmware_target_controller.rb
- app/helpers/application_helper/toolbar/firmware_registry_center.rb
- app/helpers/firmware_binary_helper.rb
- app/helpers/firmware_binary_helper/textual_summary.rb
- app/helpers/firmware_registry_helper.rb
- app/helpers/firmware_registry_helper/textual_summary.rb
- app/helpers/firmware_target_helper.rb
- app/helpers/firmware_target_helper/textual_summary.rb
- app/presenters/menu/default_menu.rb
- app/views/firmware_binary/show.html.haml
- app/views/firmware_registry/show.html.haml
- app/views/firmware_registry/show_list.html.haml
- app/views/firmware_target/show.html.haml
- app/views/layouts/listnav/_firmware_binary.html.haml
- app/views/layouts/listnav/_firmware_registry.html.haml
- app/views/layouts/listnav/_firmware_target.html.haml
- app/views/miq_request/_physical_server_firmware_update_show.html.haml
- app/views/miq_request/_request.html.haml
- config/routes.rb
- product/views/FirmwareBinary.yaml
- product/views/FirmwareRegistry.yaml
- product/views/FirmwareTarget.yaml
- spec/presenters/menu/default_menu_spec.rb
With this commit we add following pages to support firmware repository browsing:
```
- firmware registry list
- firmware registry details
+ display firmware_binaries
- firmware binary details
+ display firmware constraints
- firmware contstraint details
+ display firmware binaries
```
> Read-only pages for browsing firmware repository

- app/views/ops/_settings_server_tab.html.haml
@hstastna found out that the OPS/settings screen is broken with an `undefined method` exception. The reason is @bmclaughlin's https://github.com/ManageIQ/manageiq-ui-classic/pull/5763 that has been probably tested without https://github.com/ManageIQ/manageiq/pull/18956.
Dropping the `collect` (a.k.a. `map`) from the code fixes it :wink: :wrench: 
@miq-bot add_reviewer @bmclaughlin
> Do not call map unnecessarily on the OPS/settings SSL auth modes

- app/controllers/vm_common.rb
- app/presenters/tree_builder_archived.rb
- spec/presenters/tree_builder_archived_spec.rb
- spec/presenters/tree_builder_images_spec.rb
- spec/presenters/tree_builder_instances_spec.rb
Add scopes for filtering Archived/Orphaned VMs based on RBAC. All VMs & Templates should display Orphaned and Archived only if user has right to display it.
https://github.com/ManageIQ/manageiq/pull/18546 Add RBAC features and named_scopes definitions .
https://bugzilla.redhat.com/show_bug.cgi?id=1545942
https://github.com/ManageIQ/manageiq/pull/18546
Go to Configuration -> Access Control -> Have the `user` in the `group` with `role` which has unchecked Access rules for all VMs -> View -> (List archived/Orphaned)
Compute -> Infrastructure -> Virtual Machines -> All VM &  Templates
> Add scopes for filtering Archived/Orphaned VMs based on RBAC

- spec/controllers/ansible_repository_controller_spec.rb
Scripts and Playbooks don't need the names set here. 
> The factory sets the names

- app/controllers/miq_ae_customization_controller.rb
- spec/controllers/miq_ae_customization_controller_spec.rb
Uploading a blank file as a dialog import should raise a UI message. 
See https://github.com/ManageIQ/manageiq/pull/18951.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1720611
@miq-bot add_reviewer @eclarizio 
@tinaafitz
> Raise flash message for blank dialog import 

- app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
- app/controllers/mixins/ems_common.rb
- app/controllers/mixins/ems_common/angular.rb
- app/views/layouts/angular-bootstrap/_endpoints_angular.html.haml
- app/views/layouts/angular/_multi_auth_credentials.html.haml
- app/views/shared/views/ems_common/angular/_form.html.haml
- spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
With this commit we support basic CRUD operations for Azure Stack cloud provider:
- add a new provider
- open provider details
- update provider credentials
- destroy provider
Below please find some screenshots:
Depends on:
/cc @Fryguy @chessbyte
> Introduce AzureStack cloud provider

- app/assets/stylesheets/application.css
If the `main.scss` file is required using a relative path (i.e. `./main.scss`), it's not possible to load it from outside the repository which breaks productization. This relative path has been [introduced](https://github.com/ManageIQ/manageiq-ui-classic/pull/5636/files#diff-fb7484bc2f56c263954da6fc44982eeaR2) for a better webpack support, but we have to go back to the old way.
Maybe for forcing to load using webpack, we should have a special preprocessor defined in sprockets. After 3 hours of debugging the asset pipeline I think I'm able to create it :laughing: 
https://bugzilla.redhat.com/show_bug.cgi?id=1712933
> Allow loading of main.scss from outside this repository

- app/controllers/mixins/ems_common.rb
- app/controllers/vm_common.rb
- app/helpers/application_helper/toolbar_chooser.rb
- app/helpers/ems_network_helper/textual_summary.rb
- app/helpers/vm_helper/textual_summary.rb
- app/services/network_topology_service.rb
- config/routes.rb
- spec/helpers/ems_network_helper/textual_summary_spec.rb
- spec/helpers/vm_helper/textual_summary_spec.rb
Remove additional/remaining code for the display of Load Balancers in UI.
https://bugzilla.redhat.com/show_bug.cgi?id=1672949
Screen shot showing Load Balancers relationships in Instance by Provider page prior to code removal:
Screen shot post code fix sans Load Balancers relationship display in **Instance by Provider** page:
Screen shot post code fix sans Load Balancers relationship in **Network Manager** page:
> Remove additional deprecated Load Balancers code in UI

- app/controllers/catalog_controller.rb
- app/helpers/application_helper/button/catalog_item_copy_button.rb
- app/helpers/application_helper/toolbar/servicetemplate_center.rb
- app/helpers/application_helper/toolbar/servicetemplates_center.rb
- app/javascript/components/copy-catalog-form/copy-catalog-form.jsx
- app/javascript/components/copy-catalog-form/copy-catalog-form.schema.js
- app/javascript/packs/component-definitions-common.js
- app/views/catalog/_copy_catalog.html.haml
- config/routes.rb
Go to Services -> Catalogs -> Catalog Items -> select one -> Configuration -> Copy this Item
Backend PR(merged) https://github.com/ManageIQ/manageiq/pull/18464 . Only valid and non-`ServiceTemplateAnsiblePlaybook` items can be copied. 
Not all attributes are copied. Tracked in https://github.com/ManageIQ/manageiq/issues/18949
It's not possible to copy a copy with custom buttons. Tracked in https://github.com/ManageIQ/manageiq/issues/18954 => Fixed in https://github.com/ManageIQ/manageiq/pull/18960
Toolbar:
Form:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1678149
> Add Copy option to Catalog Item/Bundle

- app/controllers/ops_controller/settings/label_tag_mapping.rb
- app/views/ops/_label_tag_mapping_form.html.haml
Fixes display of delete Map Tag delete action confirmation messages when successful. Also, changes wording on the Add Map tag page to say "Enter category for text box (as opposed to prior "Choose..." implying more than one selection. 
https://bugzilla.redhat.com/show_bug.cgi?id=1707328
Screen shot of Add Map Tag page with "Choose..." wording prior to code fix:
No "delete successful" confirmation message displayed prior to code fix, notice message from prior action of Add still displayed:
Add new Map Tag page post code fix with "Enter..." for category text box:
Delete Map Tag confirmation message displayed post code fix:
> Display container Map Tag delete confirmation message

- app/controllers/miq_request_controller.rb
- spec/controllers/miq_request_controller_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1726741
Breadcrumb with item description was missing on Edit/Copy pages.
1. Create provision service that needs approval, order it (A standard lifecycle provisioning request that exceeds default quotas (number of vms > 1) will need to be approved, and can then be edited.)
_Compute > Cloud > Instances > Lifecycle > provision requests...._
2. View request details, edit request
3. Note breadcrumb
**Expected results**
The breadcrumb includes: Services > Requests > Provision from [<temp>] to [<vm>] > Edit VM Provision
**Before**
**After**
@miq-bot add_label hammer/no, changelog/no, breadcrumbs, requests
> Show item's description when edit/copy in Requests

- spec/controllers/application_controller/build_audit_spec.rb
We don't need to set names or descriptions for classifications, the factory will do that. 
> These are set by the factory

- app/views/ems_container/show_list.html.haml
- app/views/layouts/_empty.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1713504
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/5434
Go to Compute -> Containers-> Providers -> make sure you have no provider! -> add a new provider (see Bz for details) -> wait to be redirected back -> see there's no success/error message
Before:
After:
Go to Compute -> Containers-> Providers -> make sure you have no provider! -> Configuration -> Add a new Container Provider -> cancel -> see there's no "Canceled by user" message
Fixed for all providers.
Before:
After:
@miq-bot add_label hammer/no, bug
cc: @romanblanco
> Fix missing flash message when adding first Container Provider 

- app/services/dialog_local_service.rb
- spec/services/dialog_local_service_spec.rb
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1729903
There was missing branch for ContainerVolume dialog submission.
> Added determine_api_endpoints for ContainerVolume

- spec/controllers/cloud_object_store_container_spec.rb
```:description => "D    epartment"```
⬆️ 🤣 
The factory sets all these things, we don't need to here.
> We don't need these

- app/controllers/miq_ae_class_controller.rb
- app/views/layouts/angular/_ansible_form_options_angular.html.haml
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1678150
https://bugzilla.redhat.com/show_bug.cgi?id=1729999
also fixes a regression when editing automate methods:
```
[----] I, [2019-07-22T13:02:30.442810 #23250:57bee40]  INFO -- :   Rendered /home/martin/Projects/manageiq-ui-classic/app/views/miq_ae_class/_all_tabs.html.haml (235.7ms)                                         
[----] F, [2019-07-22T13:02:30.444149 #23250:57bee40] FATAL -- : Error caught: [ActionView::Template::Error] undefined method `[]' for nil:NilClass                                                               
/home/martin/Projects/manageiq-ui-classic/app/views/layouts/angular/_ansible_form_options_angular.html.haml:36:in `__home_martin__rojects_manageiq_ui_classic_app_views_layouts_angular__ansible_form_options_angu …
```
> Automate method editing bugz

- app/controllers/catalog_controller.rb
- app/helpers/application_helper/toolbar_chooser.rb
- app/javascript/components/orchestration-template/orchestration-template-form.schema.js
- app/presenters/tree_builder.rb
- app/presenters/tree_builder_orchestration_templates.rb
- product/views/ManageIQ_Providers_AzureStack_CloudManager_OrchestrationTemplate.yaml
- spec/controllers/catalog_controller_spec.rb
With this commit we allow for yet another provider to perform OrchestrationStack template provisioning. The process is as follows:
- at `Services > Catalogs > Orchestration Templates` create a new   orchestration template of type "Azure Stack" and provide a   JSON specification
- click on that new Orchestration Template and generate Dialog   out of it
- create Item of type "Orchestration" and connect it to Template   and Dialog
- as a user, order it. Doing so, user is offered to input parameters   as specified in JSON secification
/cc @bzwei @agrare
> AzureStack orchestration template provisioning

- app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js
- app/assets/javascripts/services/dialog_field_refresh_service.js
- app/controllers/application_controller/buttons.rb
- app/controllers/application_controller/wait_for_task.rb
- app/services/dialog_local_service.rb
- app/views/shared/buttons/_ab_options_form.html.haml
- app/views/shared/dialogs/_dialog_provision.html.haml
- app/views/shared/dialogs/_dialog_user.html.haml
- spec/javascripts/controllers/dialog_user/dialog_user_controller_spec.js
- spec/services/dialog_local_service_spec.rb
RFE BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1550002
Requires: 
* https://github.com/ManageIQ/manageiq/pull/18849 (merged)
* https://github.com/ManageIQ/manageiq-automation_engine/pull/328 (merged)
* https://github.com/ManageIQ/manageiq-schema/pull/380 (merged)
Doc PR: https://github.com/ManageIQ/guides/pull/355
* specs (existing specs are updated, but more tests would be good, will do that in a follow-up PR)
* ~~pass the targetClass though the form,~~ (needs to be checked)
* ~~allow the `OpenURL` checkbox when editing custom buttons for all relevant classes.~~
* ~~update the documentation (from here: https://github.com/ManageIQ/manageiq-ui-classic/pull/4334) and put it to guides~~
```
$evm.log(:info, "Current user_id #{$evm.root['user_id']}")
object = …
```
> Opening URLs through automate

- app/assets/javascripts/controllers/ansible_repository/repository_form_controller.js
- app/controllers/mixins/embedded_ansible_refresh_mixin.rb
- app/helpers/ansible_repository_helper/textual_summary.rb
- app/views/ansible_repository/_repository_form.html.haml
- spec/helpers/ansible_repository_helper/textual_summary_spec.rb
- spec/javascripts/controllers/ansible_repository/ansible_repository_form_controller_spec.js
@h-kataria Please review
cc @NickLaMuro @carbonin
> Remove Embedded Ansible repository unsused attributes

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_chargeback_reports.rb
- spec/presenters/tree_builder_spec.rb
`count_only_or_object` currently works with ordered query:
Typically, when the order is passed into `count_only_or_object` as the 3rd param,
the order is not passed to the count queries. So it works.
But when the order is part of the query itself, it becomes part of the count
query, and this causes problems. (aka blows up)
The fix is to remove the order from the count query. The value returned is the
same, but the query is faster and has fewer problems.
`responds_to?` is used to keep working when arrays are passed in.
https://bugzilla.redhat.com/show_bug.cgi?id=1726790
> Fix Chargeback tree for report

- app/assets/stylesheets/patternfly_overrides.scss
After updates in build process, patternfly styles are loaded earlier than c3 styles, that results in white text on white background -> broken tooltips. Adding more specific css class should fix this.
https://bugzilla.redhat.com/show_bug.cgi?id=1729236
> Override pf class for chart tooltip background

- app/presenters/tree_builder_services.rb
This is a partial backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/5686 as the lazy loading has been already backported via https://github.com/ManageIQ/manageiq-ui-classic/pull/5530.
Please test and merge this first: https://github.com/ManageIQ/manageiq-ui-classic/pull/5686
@miq-bot assign @simaishi 
@miq-bot add_label bug, trees, performance
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1727443
> [HAMMER] Improve the performance the lazy-loading of services tree by caching

- app/services/dialog_local_service.rb
- spec/services/dialog_local_service_spec.rb
Just like it says on the tin. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1732436
@miq-bot add_label hammer/no, bug
@miq-bot add_reviewer @eclarizio 
@miq-bot add_reviewer @tinaafitz 
Yes I know, it needs refactoring desperately. 
Network manager managing, it me.
> Handle network managers in the dialog local service

- spec/controllers/cloud_tenant_controller_spec.rb
Again, we don't need to do this in specs.
>  These are set by the factory

- app/presenters/tree_node/menu/item.rb
- app/presenters/tree_node/miq_product_feature.rb
This is a regression possibly caused by the refactoring of the rbac features tree. Basically when all features are checked, there's no list of features, instead we use `everything` and the checked state of the nodes was not universal for this meta-feature.
@miq-bot add_label bug, ivanchuk/yes, hammer/no, trees, rbac
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1732576
> Select the features tree items when 'everything' is allowed

- app/controllers/application_controller/tags.rb
- app/views/layouts/_tag_edit.html.haml
When you have 10000+ entries under single tag, object became too big to be stored in session and user get signed off. BZ said 1000 is enough to brake it, but for me it worked fine with 1000 entries.
https://bugzilla.redhat.com/show_bug.cgi?id=1726313
Have a Tag with 10000+ entries, try to tag a VM with one of those.
I have reproduce it with something like this in rails console (not very efficient, it took few minutes):
```
10000.times { |i| Classification.first.add_entry(:name => i.to_s, :description => i.to_s)}
```
@h-kataria
> [HAMMER] Don't store Classification AR object in session

- app/controllers/miq_ae_class_controller.rb
When adding an inline method to an automate method, we're building a regular expression that prevents the inline method tree select to add the inline the same method as the current method being edited. However, this fails when a new automate method is being created as it has no fqname and we can't build the regular expression.
This causes not to render the list of selected methods in the editor. The fix is to not build the regex when the fqname is not available.
@miq-bot add_label bug, hammer/yes, ivanchuk/yes, automation/automate
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1718495
> Do not build the regex for embedded method when there's no fqname

- app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
When copying a dialog, we load the original, allow the user to change it, and save that data as a new dialog.
But, the API just saves the fields, groups and tabs, then saves the dialog, and only after that updates those tabs to point to the new dialog. No transactions.
Which means that when dialog validation fails, all the copied tabs still point to the original dialog, leading to duplicate tabs appearing in the original.
This does not fix the API bug or attempt to wrap it in a transaction,
this just makes sure the UI won't send any obsolete ids when copying,
thus limiting the impact of the API bug to extra unused tabs remaining in the db.
(And created https://github.com/ManageIQ/manageiq-api/issues/630.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1713100
> Dialog copy - remove ids pointing to the original dialog 

- app/controllers/automation_manager_controller.rb
- app/controllers/mixins/manager_controller_mixin.rb
- app/views/automation_manager/_configscript_service_dialog.html.haml
- config/routes.rb
- spec/controllers/automation_manager_controller_spec.rb
~~Waiting for https://github.com/ManageIQ/manageiq-ui-classic/pull/5842~~ (merged)
Use React component form for creating service dialog from ansible tower job template
`Automation` > `Ansible Tower` > `Explorer` > `Templates` > Select One > `Configuration` >` Create a service dialog
`
**Before**
**After**
@miq-bot add_label hammer/no, react, changelog/no
> Use React component to create service dialog from ansible tower

- spec/controllers/automation_manager_controller_spec.rb
We don't need to set names with FactoryBot.  
> These are all set by the factory

- app/services/dialog_local_service.rb
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1732489
After submit/cancel container provider dialog triggered with custom button, user was redirected to infra provider screen. He should have been redirected back from where the dialog was open (container provider detail)
- missing branch for `ContainerManager` class
- added extra case for `ContainerManager` class in `determine_api_endpoints` method.
> Fixed container provider custom button dialog redirect.

- app/controllers/mixins/actions/vm_actions/policy_simulation.rb
- app/views/layouts/_x_edit_buttons.html.haml
- config/routes.rb
- spec/controllers/vm_infra_controller_spec.rb
- spec/views/layouts/_x_edit_buttons.html.haml_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1717495
When clicking on quadion of a VM or Template while running policy simulation, the actual controller was changed to `VmOrTemplate`. After clicking on _Back_ button, it remained the same. This was causing unexpected behavior later in the next steps, many variables not set properly, not able to cancel policy sim properly... To prevent this controller's 'change' https://github.com/ManageIQ/manageiq-ui-classic/pull/5580 was created. 
The solution worked well except the case that user chose some items from the list which were both VMs AND Templates, for policy sim, in _Compute > Infra > Virtual Machines > **VMs & Templates**_ accordion. The problem was missing quadicon(s) of Template in policy simulation.
So little bit different …
> Allow returning back to the previous controller, after clicking on Back button and to cancel policy sim properly

- app/views/miq_request/_request.html.haml
If used, Request ID is copied to be used to search, in such case, we don't want to include delimiters
1. Order a service
2. Go to Requests
> Remove delimiter for Request ID

- app/assets/stylesheets/patternfly_overrides.scss
This PR fixes a problem where the screen resizer was blocking the "select all" checkbox (and possibly other  elements) in the paging bar.
https://bugzilla.redhat.com/show_bug.cgi?id=1729894
Old
New
>  Fix resizer blocking paginator elements

- app/views/ops/_ap_form_set.html.haml
We don't want to pass translated labels as a value for `check_box_tag`
To get the partial rendered, go to:
1. Configuration (top) - Settings - Analysis Profiles
2. Add / Edit VM Analysis Profile
/cc @martinpovolny
> Removed gettext changing value for Analysis Profiles

- app/controllers/mixins/breadcrumbs_mixin.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1720714
Go Compute -> Infrastructure -> VMs -> check two or more VMs -> Policy -> Edit Tags/Policy Simulation/Manage Policies -> see breadcrumbs
Before:
After:
There's no change when doing the same from a VM Summary page.
Following [guides for breadcrumbs](https://github.com/ManageIQ/manageiq-ui-classic/wiki/Breadcrumbs) **Tagging/Ownership/etc.**
@rvsia please have a look, thanks :)
> Fix Policy breadcrumbs when coming from GTL page

- .travis.yml
broken in https://github.com/ManageIQ/manageiq-ui-classic/pull/5408
dropping the last version should have dropped the excludes too.
Since then, we've been only running `spec` on hammer, no JS tests.
Adding back :).
Cc @juliancheal @simaishi @mzazrivec 
(similar fix for ivanchuk in https://github.com/ManageIQ/manageiq-ui-classic/pull/5882)
> [HAMMER] Add spec:jest, spec:javascript and spec:compile back

- app/controllers/report_controller/saved_reports.rb
- spec/controllers/report_controller_spec.rb
QE kept coming up with new and new edge cases after https://github.com/ManageIQ/manageiq-ui-classic/pull/5803 and https://github.com/ManageIQ/manageiq-ui-classic/pull/5779 and I had to come up with a more general solution for testing the existence of an accordion switch in `params[:id]`. I went directly to the source and asked QE to test all the edge cases on an appliance that has this fix.
Of course *The Right Way&trade;* would be to not use the same param for both selecting a node and loading an accordion. I will look into the possibilities of how can we split these two params up as we have in on other explorers.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724209
> Generalized check for accordion in params when selecting (saved)reports

- app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
- cause https://github.com/ManageIQ/manageiq-ui-classic/pull/5614
- older PR had a snapshot with old dependency versions which is no longer mangling class/function names in minified build.
> Fixed JS snapshot test mismatch.

- app/controllers/pxe_controller/pxe_servers.rb
Follow up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/5614#issuecomment-515385838
> Fixed rubocop standard error warning in pxe_servers.rb

- spec/other/travis_spec.rb
This PR:
* makes the original test run for travis variant with multiple ruby versions
* adds a test for travis variant with single ruby version. In this test we want to make sure that no testsuite is excluded from running.
@himdel
> Update travis spec for corner cases

- app/assets/javascripts/miq_application.js
- app/controllers/application_controller/filter.rb
- app/views/layouts/_user_input_filter.html.haml
Go to Advanced search in an explorer controller (Compute > Infrastructure > VMs, accordion VMs),
add a filter which uses user input (say, VM power state == user input),
apply the filter,
(watch the Network tab,)
click Apply on the user input modal (after filling something in).
Before: you'll see requests to both quick_search?button=apply and quick_search?button=cancel.
After: no cancel, just apply
---
Since #3444 (which fixed the user input filter modal to hide after Apply, closing https://github.com/ManageIQ/manageiq-ui-classic/issues/499):
* clicking the apply button triggers a ?button=apply request
* but, thanks to data-dismiss="modal", it also closes the modal
* BUT, closing the modal this way triggers a ?button=cancel request
Thus, clicking apply triggers apply & cancel, in random …
> user_input_filter - don't send Cancel on Apply

- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Specs for `BreadcrumbsMixin` make super hard to work on https://github.com/ManageIQ/manageiq-ui-classic/pull/5889, so I decided to clean up all the antipatterns:
* method (re)definitions for mocking
* unnecessary variable alterations instead of contexts `mixin` and `mixin_explorer`
* unnecessary mocks and variables
* confusing naming in the features hash
* wrongly used tree definition
* presence of `when` in `context`
@miq-bot add_label ivanchuk/no, hammer/no, test, technical debt
> Removed antipatterns from the spec for BreadcrumbsMixin

- app/controllers/mixins/breadcrumbs_mixin.rb
- app/presenters/tree_builder.rb
- app/presenters/tree_builder_automation_manager_configuration_scripts.rb
- app/presenters/tree_builder_configured_systems.rb
- spec/controllers/automation_manager_controller_spec.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
- spec/controllers/provider_foreman_controller_spec.rb
- spec/presenters/tree_builder_ae_class_spec.rb
- spec/presenters/tree_builder_automate_catalog_spec.rb
- spec/presenters/tree_builder_automate_spec.rb
- spec/presenters/tree_builder_chargeback_assignments_spec.rb
- spec/presenters/tree_builder_chargeback_rates_spec.rb
- spec/presenters/tree_builder_menu_roles_spec.rb
- spec/presenters/tree_builder_ops_rbac_spec.rb
- spec/presenters/tree_builder_report_roles_spec.rb
- spec/presenters/tree_builder_report_saved_reports_spec.rb
- spec/presenters/tree_builder_spec.rb
The `TreeBuilder` stores the nodes both as legacy dynatree JSON and as bs-treeview compatible JSON. The first one is used by tests only, so I'm dropping it and using its instance variable for storing the nodes as objects. This way we can avoid the unnecessary JSON parsing in specs and when building breadcrumbs.
@miq-bot add_label refactoring, trees, hammer/no, ivanchuk/no, changelog/yes
> Store the nodes as objects in the TreeBuilder instead of JSON

- app/controllers/application_controller/miq_request_methods.rb
- spec/controllers/miq_request_controller_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1733521
1. Add a provider (tested with RHV43)
2. Compute -> Infrastructure -> Providers
3. Click on the provider
4. Click on the VMs
5. Select any VM by clicking on the checkbox
6. Lifecycle -> Publish selected VM to a Template
Breadcrumb has "Add VM Provision"
Breadcrumb has "Publish Virtual Machine"
When request is type of `clone_to_template` it has set generic 'add' title and breadcrumbs take it.
**Before**
**After**
@miq-bot add_label requests, ivanchuk/yes, compute/infrastructure, changelog/no
> Add title for clone_to_template edit action

- app/views/report/_db_show.html.haml
- Changed to show Yes/No values for better readability
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1733555
before
after
> Show value of Locked/Reset fields when value is false or not set.

- app/controllers/vm_common.rb
- app/views/vm_common/_right_size.html.haml
- spec/controllers/vm_controller_spec.rb
Multiple issues fixed with back button on non-explorer version of VM Right Size recommendations screen
- fixed a typo it should be `@record.id`
- fixed call to javascript_prologue, method does not expect argument
- added code to redirect back to previous screen when back button is pressed
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1733207
Note: This is only an issue when drilling down to list of VMs thru relationships and selecting a VM from a list view to view it's right size recommendations.
Please review @hstastna @skateman
> Fixed issues with 'Back' button on right size screen

- app/controllers/catalog_controller.rb
- app/helpers/params_helper.rb
- spec/controllers/catalog_controller_spec.rb
**Fixes BZ:**
https://bugzilla.redhat.com/show_bug.cgi?id=1728774
**Issue:**
https://github.com/ManageIQ/manageiq-ui-classic/issues/5469
**What:**
Add button is already (always) enabled while adding a new Service Catalog Item, even when there is nothing to add, because we haven't filled in anything. This behavior is not consistent with other screens. We want _Add_ button to properly response on changes, as in other screens.
**How:**
When user fills in some form, the text for the appropriate form is stored in `@edit[:new]` where the original values are usually set to `nil`. The same values are copied to `@edit[:current]` in the beginning. If the user deletes the text from the form, the variable is set to `""` which is different to the original value, so the `changed` variable stilll …
> Make Add button respond properly on changes while adding Catalog Item

- spec/controllers/automation_manager_controller_spec.rb
Provider ansible tower specs don't need the urls afaik. 
@miq-bot add_label hammer/no, refactoring, test, changelog/no, ivanchuk/no
> We don't need to set urls here

- app/assets/javascripts/miq_application.js
Instead of [`readOnly`](https://codemirror.net/doc/manual.html#option_readOnly) option I'd prefer to use [`cursorBlinkRate`](https://codemirror.net/doc/manual.html#option_cursorBlinkRate) to disable cursor in 'read only' CodeMirror instance.
Setting `nocursor` for [`readOnly`](https://codemirror.net/doc/manual.html#option_readOnly) option makes it impossible to copy from CodeMirror, which is annoying (e.g. if you need to copy Automate methods) and it has been an issue before.
According to the CodeMirror manual, setting negative value for [`cursorBlinkRate`](https://codemirror.net/doc/manual.html#option_cursorBlinkRate) hides the cursor.
Therefore I'm setting either `-1` or `530` (default CodeMirror value) as possible values.
Links
* …
> Allow to copy from 'read only' CodeMirror editor

- app/controllers/cloud_volume_backup_controller.rb
Go to: Storage -> Block Storage -> Volume Backups -> Select one -> Configuration -> Restore Backup to Cloud Volume
Before:
After: 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1729981
> Fixed Error in Restore Cloud Volume Backup

- app/controllers/ops_controller/settings/rhn.rb
When you try to add your credentials for *Red Hat Subscription Manager* under `Settings -> Region -> Red Hat Updates`, the workflow breaks on a type conversion error which has been introduced to support organization for *Satellite*. The fix is to use `try` and convert the data to number so the comparison never fails.
@miq-bot add_label bug, hammer/yes, ivanchuk/yes
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1731962
> Make the check against Satellite organization safe to fix RHSM issues

- app/controllers/ops_controller/settings/automate_schedules.rb
- spec/controllers/ops_controller/settings/automate_schedules_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1730750
While editing an existing _Schedule_ (_Configuration > Settings > Schedules_) with **_EVM Group_** or **_Tenant_** _Object Attribute Type_ , internal server error occurred. This PR fixes it.
**Details:**
For _EVM Group_, there is only `description` column, instead of `name`:
```
=> [----] I, [2019-07-17T15:56:35.346480 #19795:2ad8f888c54c]  INFO -- : Started GET "/ops/schedule_form_fields/121" for ::1 at 2019-07-17 15:56:35 +0200
[----] I, [2019-07-17T15:56:35.402769 #19795:2ad8f888c54c]  INFO -- : Processing by OpsController#schedule_form_fields as HTML
[----] I, [2019-07-17T15:56:35.402952 #19795:2ad8f888c54c]  INFO -- :   Parameters: {"id"=>"121"}
[----] F, [2019-07-17T15:56:35.841908 #19795:2ad8f888c54c] FATAL -- : Error …
```
> Make editing schedule with EVM Group/Tenant type work

- app/controllers/infra_networking_controller.rb
- app/presenters/tree_builder_infra_networking.rb
The GTL on the `Compute > Infrastructure -> Networking` displays the same switches all the time, doesn't matter which node you are selecting. The problem is that the `selected_ids` param is no longer propagated into the GTLs. Even if I would try to propagate it, an empty array would fall back to the current behavior (possibly because of a `compact` on the params somewhere). 
*The Right Way&trade;* is to send the parent record into the `options` passed further to the GTL and it will automagically call the `switches` method on it. Of course this requires to have the `switches` method on every model we're touching and it's [missing](https://github.com/ManageIQ/manageiq/pull/19076) from the `EmsCluster`.
Also found out that the `Lan` nodes under switches should not be clickable, we lost this …
> Propagate parent model into GTLs on InfraNetwork switches 🖵 🐞

- app/views/layouts/listnav/_show_list.html.haml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1429540 
header "Filters" renamed to "Global Filters"
Before:
After:
> Filters header renamed to Global Filters

- app/views/layouts/_user_input_filter.html.haml
Compute > Infra > VMs > VMs accordion,
add an advanced search like "VM.active" "=" "\<user input\>" - the field needs to be a boolean,
try to use it.
Before: there would be a Choose / True / False select, but chosing anything would just show Choose
Now: you should be able to chose a value.
(And field types other than bool should still have the input autofocused.)
--- 
The user input filter autofocuses the first input element,
but pf-select hides the select element and creates its own div.
That div never changes the text inside when chosing options, if the original select is focused.
Making sure we don't autofocus select elements.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5896
https://bugzilla.redhat.com/show_bug.cgi?id=1677258
> user_input_filter: Don't autofocus selects

- app/views/layouts/_adv_search_footer.html.haml
When applying a boolean advanced search the modal is not hidden resulting in an unclickable screen.
Reproduced via:
Compute - Cloud - Instances - All Instances
Advanced search consisting of: Field: Instance : Active = "true"
@miq-bot add_labels bug, compute/cloud
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1725838
> Clear modal after Applying advanced search

- app/helpers/ansible_credential_helper/textual_summary.rb
- spec/helpers/ansible_credential_helper/textual_summary_spec.rb
This removes the need for masking passwords. Also add specs to
ensure that #textual_group_options doesn't return any fields
marked as a password type
Here's a before and after of the credentials details page
Before:
After:
---------------------------------------
Marking this as WIP initially as it builds on #5770
> Remove password fields from ansible credentials details page

- app/views/layouts/_searchbar.html.haml
- app/views/layouts/_x_adv_searchbox.html.haml
- app/views/layouts/angular/_ansible_form_options_angular.html.haml
comes from the first example in https://getbootstrap.com/docs/3.4/javascript/#modals-related-target
not really used on our side :)
> Drop random data-whatever from modals

- product/views/ManageIQ_Providers_CloudManager_Template-all_vms_and_templates.yaml
- product/views/MiqTemplate.yaml
- product/views/ProvisionCloudTemplates.yaml
- product/views/Vm-all_vms.yaml
- product/views/VmOrTemplate-all_archived.yaml
For some databases, this brings back way too many records.
It is unnecessary. And if it were necessary, the includes would get added automatically anyway.
See also https://github.com/ManageIQ/manageiq-ui-classic/pull/5283
https://bugzilla.redhat.com/show_bug.cgi?id=1733351
> views: remove unneeded compliances join

- app/presenters/tree_builder_generic_object_definition.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1665031
Go to Automation -> Automate -> Generic Objects ->  click Actions in a tree-> Add some custom button sets that start with UpperCase letter and some that start with LowerCase letter -> see different order in tree and GTL
Look at `annabelle` custom button set
Before:
After:
@romanblanco please have a look, thanks
@miq-bot add_label hammer/yes, ivanchuc/yes, bug, generic objects
> Fix button sets order in tree

- spec/controllers/catalog_controller_spec.rb
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/ems_infra_controller_spec.rb
- spec/shared/controllers/shared_examples_for_hiding_column_non_admin.rb
Similar parts of spec code refracted into the shared example. @lpichler
>  Refactor spec for hiding tenant column for non admin users

- app/javascript/components/remove-catalog-item-modal.jsx
- app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js
1. Go to catalog items, have many of them available
2. Select all of them at once (or at lest 5-6 items)
3. Hit delete catalog items
Previously, the rendered modal would have delete button initialy enabled. Hitting the delete button before the modal would be filled by data would not delete anything at all, it would just show spinner indefinitely.
With this fix in place, the delete button will be enabled only after the API data is fetched and the modal is filled with appropriate data. The modal will also render a spinner before the data is
completely loaded.
https://bugzilla.redhat.com/show_bug.cgi?id=1713399
@himdel
> Catalog item removal modal: disable delete button if API data incomplete

- app/views/network_topology/show.html.haml
- config/routes.rb
Remove Load Balancer link/button from the Network Topology page.
https://bugzilla.redhat.com/show_bug.cgi?id=1672949
> Remove Load Balancer button from Network Topology page

- app/controllers/automation_manager_controller.rb
- product/views/ManageIQ_Providers_AnsibleTower_AutomationManager_ConfigurationScript.yaml
- spec/controllers/automation_manager_controller_spec.rb
previously code was passing in model as `ConfigurationScript` that returns all Tower templates, Changed to use `ManageIQ::Providers::AnsibleTower::AutomationManager::ConfigurationScript` so that embedded ansible templates are excluded from the list
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656734
before
after
> Changed model name when showing list of Tower Templates.

- product/views/InstanceOrImage.yaml
- product/views/ManageIQ_Providers_CloudManager_Template.yaml
- product/views/ManageIQ_Providers_CloudManager_Vm-all_vms_and_templates.yaml
- product/views/ManageIQ_Providers_CloudManager_Vm-vms.yaml
- product/views/ManageIQ_Providers_CloudManager_Vm.yaml
- product/views/ManageIQ_Providers_InfraManager_Template.yaml
- product/views/ManageIQ_Providers_InfraManager_Vm.yaml
- product/views/MiqTemplate-all_miq_templates.yaml
- product/views/ProvisionInfraTemplates.yaml
- product/views/Vm.yaml
- product/views/VmOrTemplate-all_orphaned.yaml
- product/views/VmOrTemplate-all_vms_and_templates.yaml
Follow up to https://github.com/ManageIQ/manageiq-ui-classic/pull/5919
having `include_for_find: :compliances` forces a join
and too many records are coming back.
We removed a few of these in https://github.com/ManageIQ/manageiq-ui-classic/pull/5919, but this PR circles back and removes them from the other views, too.
https://bugzilla.redhat.com/show_bug.cgi?id=1733351
> Circling back and removing compliance join for all

- app/views/miq_policy/_policy_folders.html.haml
Fix display of missing name for Container Policy Compliance. 
https://bugzilla.redhat.com/show_bug.cgi?id=1728740
Screen shot showing name displayed post code fix:
> Fix display of Container Project Compliance Policies

- app/assets/javascripts/components/generic_object/assign-buttons.js
- app/assets/javascripts/components/generic_object/main-custom-button-group-form.js
- app/assets/javascripts/directives/form_changed.js
- app/assets/javascripts/miq_global.js
- app/controllers/generic_object_definition_controller.rb
- app/javascript/helpers/move.js
- app/javascript/packs/application-common.js
- app/javascript/packs/globals.js
- app/views/static/generic_object/assign-buttons.html.haml
- app/views/static/generic_object/main_custom_button_group_form.html.haml
- config/routes.rb
- spec/javascripts/components/generic_object_definition/assign-buttons_spec.js
Before:
After:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1534529
@miq-bot add_label bug, wip
> GOD's button group can have buttons assign/unassign during create/edit

- app/assets/javascripts/automate_import_export.js
- app/assets/javascripts/git_import.js
- app/controllers/miq_ae_tools_controller.rb
- spec/javascripts/git_import_spec.js
this affects the Content-Type, which in turn affects how the response is parsed client side
for `format.js`, the response is parsed as javascript, and must contain the `throw "error"` thing
for `format.json`, the response is parsed as json, so no need to `JSON.parse`
Fixes a surprising "Uncaught SyntaxError: Unexpected token import",
when datastore import succeeds, because we were trying to eval "Datastore import" as javascript.
(Automation > Automate > Import / Export, import a zip, "fails" on the Commit step, *after* successfully importing)
Cc @eclarizio
> Automate import - use format.json, not format.js when doing render :json

- app/helpers/application_helper/button/view_ght.rb
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/5916
ping @lpichler
> Report results: fix toolbar button display when in "filter".

- app/javascript/components/report-data-table.jsx
- app/javascript/spec/report-data-table.spec.js
Add styling to report data filter display.
After:
Requires: https://github.com/ManageIQ/manageiq/pull/18938 (merged)
> Add formatting to report data filter display.

- app/views/generic_object_definition/_show_list.html.haml
After two and half days of seeing this warning I had to fix it 😸 
Go to Automation -> Automate -> Generic Objects -> see console log
Before:
After:
No warnings 
@miq-bot add_label technical debt, changelog/no, ivanchuk/no
> Fix double id in GOD

- app/assets/javascripts/components/auth-credentials.js
- app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
- app/views/configuration_manager/_shared_form.html.haml
- app/views/layouts/angular-bootstrap/_auth_credentials_angular_bootstrap.html.haml
- app/views/layouts/angular/_multi_auth_credentials.html.haml
- app/views/static/auth-credentials.html.haml
Compute > * > Providers - add/edit
Problems:
* a black "Required. \<a note\>" pops up on some provider edit screens, but not near the Username field
* => removing Required, as the field itself can already handle it
* => moving the rest of the message to the username notes section
* the whole condition is partly evaluated server side, and only the result gets evaluated client side
* => restoring the conditions that were eaten by `string1 && string2 && string3` becoming `string3`
https://bugzilla.redhat.com/show_bug.cgi?id=1528984
> Provider edit - move message about a username near the field, fix everything

- app/controllers/application_controller/ci_processing.rb
- spec/controllers/application_controller/ci_processing_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1729953
For operations like _Refresh Relationships and Power States_,  _Perform SSA_, _Extract Running Processes_, and some others (Power operations, some others on VMs displayed as a nested list), error encountered:
```
[----] F, [2019-07-24T17:14:26.520402 #24911:2ac557646cc4] FATAL -- : Error caught: [ActiveRecord::RecordNotFound] Can't access selected records
/home/hstastna/manageiq/manageiq-ui-classic/app/controllers/mixins/checked_id_mixin.rb:60:in `find_records_with_rbac'
```
Selected VMs are not accessible. This is because of getting wrong record class (`Storage`) in `get_rec_cls` method while identifying selected records [here](https://github.com/hstastna/manageiq-ui-classic/blob/master/app/controllers/application_controller/c …
> Get proper record class while performing operations on Managed VMs of a chosen Datastore

- app/assets/javascripts/miq_tree.js
- app/controllers/application_controller/miq_request_methods.rb
- app/controllers/vm_common.rb
- app/javascript/components/taggingWrapper.jsx
- app/javascript/miq-redux/middleware.js
- app/javascript/spec/miq-redux/middleware.spec.js
- app/views/miq_request/_prov_edit.html.haml
- app/views/miq_request/_prov_field.html.haml
- package.json
Replace provision Tagging tree with a new component
https://github.com/ManageIQ/manageiq-ui-classic/issues/5515
Screenshot
Provision VM/Instance -> Purpose tab
> Replace provision Tagging tree by component

- app/controllers/ops_controller/settings/schedules.rb
1. Under Settings, add a new schedule
2. Cancel the addition (i.e. no save)
The following error will show in rails console:
```
FATAL -- : Error caught: [ActiveRecord::RecordNotFound] Couldn't find MiqSchedule with 'id'=new
~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.7/lib/active_record/core.rb:189:in `find'
manageiq-ui-classic/app/controllers/ops_controller/settings/schedules.rb:39:in `schedule_edit'
...
```
> Fix error when canceling addition of new schedule

- app/presenters/tree_builder_alert_profile.rb
- app/presenters/tree_builder_automation_manager_configuration_scripts.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_condition.rb
- app/presenters/tree_builder_policy.rb
- app/presenters/tree_builder_report_dashboards.rb
- app/presenters/tree_builder_storage.rb
The goal is to get rid of this variable completely, but the first step is to mark all of the occurrences so I can see where it is still being used.
@miq-bot add_label trees, technical debt, hammer/no, ivanchuk/no
> Mark the options argument in TreeBuilder methods unnecessary with _

- app/controllers/report_controller/schedules.rb
1. Create a new report schedule
2. Choose some starting date in the future
3. Change `Run` between `Hourly` and something else
4. Watch the start date changing to either today or tomorrow
5. Open the datepicker (by clicking on the input field)
Without this fix, the datepicker would not reflect the change of the starting date.
https://bugzilla.redhat.com/show_bug.cgi?id=1729882
> Update datepicker when start date changed

- app/controllers/application_controller/ci_processing.rb
- spec/controllers/application_controller/ci_processing_spec.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1732370
This PR fixes the same problem as it was fixed [here](https://github.com/ManageIQ/manageiq-ui-classic/pull/5867).
After discussion with @skateman, we've decided to fix the problem the same way and later to refactor the code to avoid not very nice block of cases in `get_rec_cls` and adding extra conditions for each controller as it is in this PR. I've created an issue for this: https://github.com/ManageIQ/manageiq-ui-classic/issues/5924
---
**Before:**
**After:**
> Get record class while performing operations on VMs of chosen Cluster

- app/controllers/mixins/actions/vm_actions/reconfigure.rb
- spec/controllers/mixins/actions/vm_actions/reconfigure_spec.rb
Issue was introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/3956, in commit 6df12d1079d09dd23fea2e1627b0ee3399d911ca code that builds Host file drop down was changed `vm.try(:available_iso_names)` was removed and new method `get_iso_options` was added to build the list. Changed to get all storages that the vm's host is attached to instead of all of the vm's storages
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1689369
before
after
cc @agrare
> Fixed call that build list of Storages to build Host file drop down

- app/controllers/application_controller/tags.rb
When you select multiple values from on category, save it and load it again. Category is there multiple times. I have no idea how could nobody (especially me) notice this earlier. Since last changes in this area was quite a long time ago.
Screenshots
Before:
After:
* http://documentation.for/library/that/I/am/adding
* [PR relevant issue or pull_request](#123)
Compute -> Infra -> VMs -> Policy -> Edit Tags -> Add multiple values to single category -> Save -> Edit again
> Fix load tags with multiple values in one category

- app/controllers/miq_policy_controller.rb
This method is not being used anywhere in the policies as there's no way to access lower levels of the hierarchy by clicking on the right side.
:scissors: :toilet: :fire: :droplet: 
@miq-bot add_label cleanup, hammer/no, ivanchuk/no, trees, explorers, control
> Drop the MiqPolicyController#open_parent_nodes as it's never used

- app/controllers/generic_object_definition_controller.rb
- app/views/generic_object_definition/_list.html.haml
- app/views/generic_object_definition/_show_actions.html.haml
- app/views/generic_object_definition/_show_custom_button.html.haml
- app/views/generic_object_definition/_show_custom_button_group.html.haml
- app/views/generic_object_definition/_show_god.html.haml
- app/views/generic_object_definition/show.html.haml
- app/views/generic_object_definition/show_list.html.haml
Based on https://github.com/ManageIQ/manageiq-ui-classic/pull/5931#issuecomment-518266538 here's a cleaner fix for my favourite controller.
Go to Automation -> Automate -> Generic Objects -> see console log -> try `document.getElementById("main_div")`
For all forms/pages of GOD there should be exactly one `<div id="main_div">...</div>`. 
Before:
After:
No warnings 
@miq-bot add_label technical debt, changelog/no, ivanchuk/no
> Fix main_div double id withour getting rid of <div id=main_div>

- app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
- app/views/ops/_settings_replication_tab.html.haml
1. Setup ManageIQ with one global region and multiple remote region appliances
2. Configuration ➛ Settings ➛ Select Global Region ➛ Replication
This PR contains several fixes:
1. Before submitting form with edited values, we need to remove non-edited (non-changed) items from the model so that we submit only things that changed. We cannot modify the orignal model though, since that would be reflected in the replication screen (i.e. the non-edited items would disappear from the screen after hitting Save).
2. Fix styling of `Cancel Delete` button
3. Disable kebab popup button when `Cancel Delete` button is active
https://bugzilla.redhat.com/show_bug.cgi?id=1726249
> Don't modify original model value for form submission

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_alert_profile_obj.rb
- app/presenters/tree_builder_automate.rb
- app/presenters/tree_builder_automate_catalog.rb
- app/presenters/tree_builder_automate_entrypoint.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_belongs_to_vat.rb
- app/presenters/tree_builder_compliance_history.rb
- app/presenters/tree_builder_infra_networking.rb
- app/presenters/tree_builder_network.rb
- app/presenters/tree_builder_roles_by_server.rb
- app/presenters/tree_builder_servers_by_role.rb
- app/presenters/tree_builder_smartproxy_affinity.rb
- app/presenters/tree_builder_tenants.rb
- app/presenters/tree_builder_utilization.rb
- spec/presenters/tree_builder_alert_profile_obj_spec.rb
Sorry for the early :alarm_clock: PR, I can't :sleeping: and I'm creative :smiley: 
This is removing the two arguments from the `override` methods as they are no longer used in any of them.
@miq-bot add_label cleanup, hammer/no, ivanchuk/no, trees
> Drop the unnecessary _pid and _options args from TreeBuilder#override

- app/controllers/miq_policy_controller/alert_profiles.rb
- app/presenters/tree_builder_alert_profile_assign.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_ems_folders.rb
- app/presenters/tree_builder_resource_pools.rb
- spec/presenters/tree_builder_ems_folders_spec.rb
- spec/presenters/tree_builder_resource_pools_spec.rb
The logic between the two behaviors in both `TreeBuilderBelongsTo` classes has been split up based on testing a parameter multiple times. This is an 🦛 antipattern 🦛 that caused a lot of :spaghetti: :spaghetti: and also in the Alert Profiles we do not need most of the rendered nodes like providers without any assignable items as children. We even had some checkboxes where it was not necessary.
The `TreeBuilderBelongsToHac` has been used for:
* assigning hosts and clusters when editing an RBAC group in access control (2nd tab)
* assigning resource pools to VM Alert Profiles in control/explorer (edit assignments)
The `TreeBuilderBelongsToVat` has been used for:
* assigning vms and templates when editing an RBAC group in access control (3rd tab)
* assigning ems folders to VM Alert Profiles in …
> Do not use the same 🌳🌳 for assignments for Alert Profiles and RBAC groups

- package.json
Changing version to 1.3.0 now that ivanchuk is cut, 1.2.* will be ivanchuk from now on.
Also, since 1.2.10:
https://github.com/ManageIQ/ui-components/pull/405
https://github.com/ManageIQ/ui-components/pull/407
https://github.com/ManageIQ/ui-components/pull/408
https://github.com/ManageIQ/ui-components/pull/409
https://github.com/ManageIQ/ui-components/pull/404
> Update ui-components to 1.3.0

- app/assets/javascripts/controllers/report_data_controller.js
- app/assets/javascripts/miq_explorer.js
- app/controllers/automation_manager_controller.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/service_controller.rb
- app/helpers/application_helper/page_layouts.rb
- app/presenters/explorer_presenter.rb
- app/views/layouts/_center_div_no_listnav.html.haml
- app/views/service/explorer.html.haml
This PR removes all of the code added to ensure that the gray background used in Tile and Grid views was rendered correctly.
Depends on  https://github.com/ManageIQ/ui-components/pull/409
Issue: https://github.com/ManageIQ/ui-components/issues/406
> Remove sandpaper styling around GTLs

- app/controllers/report_controller/reports.rb
- spec/controllers/miq_report_controller/reports_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1731017
At the moment, deleting a report doesn't delete the report name from the settings hash of the group. 
This shouldn't be in the UI, any of it, but refactoring a [five level deep nested hash of settings](https://github.com/ManageIQ/manageiq-ui-classic/pull/5950/files#diff-a31349b4cac8623f48847e8d969ecbeaL199) is not a hill I'm willing to die on. So instead this. @jrafanie helped me with it and I know he'd like to review this. It's still bad. Just consistently bad.
> Remove report names from group settings hash when reports are deleted

- app/controllers/application_controller/buttons.rb
- app/views/shared/buttons/_ab_advanced_form.html.haml
- spec/controllers/application_controller/buttons_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1717843
Go to Automation -> Automate -> Customization -> Buttons -> Configuration -> Add/Edit a Button -> make sure Request in Advanced tab is empty and Text, Hover Text, Icon in Options are set -> click Add/Save
First commit fixes the bug, other commits just clean around a bit.
Before:
After:
@miq-bot add_label bug, automation/automate, ivanchuk/yes, hammer/yes
@h-kataria please have a look, thanks :)
> Switch to Advanced tab when only error is "Request is required"

- app/views/ops/_rbac_group_details.html.haml
- spec/views/ops/_rbac_group_details.html.haml_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1730402
Unexpected error occurs if we choose _< Choose a Role >_ option in the drop down for specifying some Role while adding a new Group (after we had some Role already chosen). With disabling this option, we prevent occurring errors and we also bring more consistency because it is not possible to choose _<Choose a Project/Tenant>_ option, too, for specifying a Project or Tenant.
With disabling _<Choose a Role>_ option, we also prevent saving group with _<Choose a Role>_ in the drop down.
Note:
Name, Role and Project or Tenant are required to specify for adding new Group.
---
**Before:**
**After:**
> Disable <Choose a Role> option to prevent error while adding Group

- app/helpers/service_helper/textual_summary.rb
- spec/helpers/service_helper/textual_summary_spec.rb
Before:
After:
@miq-bot add_labels enhancement, services
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1504293
> Add 'Service ID' to Service detail page

- app/presenters/tree_builder_ems_folders.rb
- app/presenters/tree_builder_resource_pools.rb
When you try to assign a vm alert profile to a resource pool or a folder, it fails with the following error:
```
Error caught: [ArgumentError] wrong number of arguments (given 2, expected 4)
..ManageIQ/manageiq-ui-classic/app/presenters/tree_builder_resource_pools.rb:4:in `override'
..ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:274:in `x_build_single_node'
..ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:240:in `x_build_node'
..ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:280:in `x_build_node_tree'
..ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:200:in `block in x_build_tree'
..ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:195:in `each'
..ManageIQ/manageiq-ui-classic/app/presenters/tree_builder.rb:195:in `map' …
```
> Drop the pid/options arguments from AssignTo trees' override 🐞

- app/services/dialog_local_service.rb
- spec/services/dialog_local_service_spec.rb
The ems_network endpoint is singular. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1732436
@miq-bot add_label bug, ivanchuk/yes
@martinpovolny sorry, my mistake
> The dialog ems_network endpoint is wrong

- app/controllers/application_controller/explorer.rb
- app/controllers/catalog_controller.rb
The only place the param would be used is `TreeNode#key`, but there is an extra conditional next to it which is always `nil` when calling `x_build_node`. After cleaning this param up, the second argument is no longer necessary.
```ruby
"#{@options[:full_ids] && @parent_id.present? ? "#{@parent_id}_" : ''}#{prefix}-#{cid}"
```
@miq-bot add_label cleanup, hammer/no, ivanchuk/no, trees
> Drop the obsolete :full_ids from x_build_node_id in CatalogController

- app/controllers/vm_remote.rb
- app/views/vm_common/console_vmrc.html.haml
This is a side-advantage of implementing [the URL building in the provider](https://github.com/ManageIQ/manageiq-providers-vmware/pull/429) for [VMRC support in SUI](https://github.com/ManageIQ/manageiq/issues/18718). The `build_vmrc_uri` and the rest of the params are no longer necessary as the URL is being shipped in the task result.
@miq-bot add_label pending/core, technical debt, cleanup, hammer/no
Depends on: https://github.com/ManageIQ/manageiq-providers-vmware/pull/429
> Consume the URL for VMRC from the task result instead of building it

- app/controllers/application_controller.rb
Extended change made in https://github.com/ManageIQ/manageiq-ui-classic/pull/4945
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1738664
> Do not remember tab when downloading report from list view.

- app/presenters/tree_builder_roles_by_server.rb
The node highlighting in the `TreeBuilderRolesByServer` went a little off after some refactoring because the model has not been calculated into the selected node's prefix generation. Therefore, only servers could be highlighted after a tree reload. If there was no server with the same ID as the role, no node has been selected after suspending/resuming a server role.
This code is :spaghetti: bad :spaghetti: and I am working on a followup refactoring PR, but it touches too many pieces of session, so it takes me some time to make right all the wrongs. For more info about the reproducing, please see the BZ.
@miq-bot add_label bug, hammer/no, ivanchuk/yes, trees
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1734393
> Build the selected node key from the session stored model in RBS 🌳🐞

- app/controllers/automation_manager_controller.rb
- app/helpers/application_helper/toolbar/configuration_scripts_center.rb
- app/helpers/application_helper/toolbar/x_configuration_scripts_center.rb
This is one of the explorer-nonexplorer screens, so there are two toolbars depending on some kind of :spaghetti: :sparkles: magic :sparkles: and both of them can be rendered. This is an awful fix and the whole screen/toolbar selection should be refactored.
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1382635
> Add the configuration toolbar button on Ansible/Templates screen

- app/controllers/network_router_controller.rb
- spec/controllers/network_router_controller_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724114
The NetworkRouter form was updated quite some time ago to submit the cloud tenant id as an `id` key in a `cloud_tenant` object rather than as a field named `cloud_tenant_id`. This updates the NetworkRouterController's `form_params` method to reflect that.
> NetworkRouter form_params should get tenant id from nested hash

- app/presenters/tree_builder_compliance_history.rb
Removing some duplicated code in :deciduous_tree: :deciduous_tree: for retrieving a record from a node's key.
@miq-bot add_label refactoring, trees, hammer/no, ivanchuk/no
> Use the TreeBuilder#node_by_tree_id in compliance history 🌳

- app/presenters/tree_builder_storage_adapters.rb
The tree is accessible from the `Infra -> Hosts` summary screen. This variable is not being used anywhere else, not even during lazyloading.
@miq-bot add_label trees, technical debt, hammer/no, ivanchuk/no
> Drop the unnecessary sandbox variable in storage adapters 🌳✂️✂️

- app/presenters/tree_builder_compliance_history.rb
Avaialble on any entity that has compliance (assignable policies) support through its summary screen. The tree is not lazy and it always comes in with a root node.
@miq-bot add_label technical debt, hammer/no, ivanchuk/no, trees, cleanup
> Do not rely on the obsolete sandbox variable in ComplianceHistory🌳

- app/presenters/tree_builder_network.rb
The tree is accessible from the Infra -> Hosts summary screen. This variable is not being used anywhere else, not even during lazyloading.
@miq-bot add_label trees, technical debt, hammer/no, ivanchuk/no, cleanup
> Do not rely on the obsolete sandbox variable in Networks 🌳

- app/presenters/tree_builder.rb
- spec/controllers/automation_manager_controller_spec.rb
- spec/presenters/tree_builder_network_spec.rb
- spec/presenters/tree_builder_storage_adapters_spec.rb
This argument is no longer necessary and has been marked as unused anyway, so deleting it.
@miq-bot add_label hammer/no, ivanchuk/no, cleanup, technical debt, trees
> Drop the unused options argument from TreeBuilder#x_get_tree_objects

- app/controllers/application_controller/policy_support.rb
A policy simulation screen has a GTL with the list of affected entities.
When a policy simulation happens in an explorer screen, whenever `@explorer`=true and `@in_a_form`=false,
`get_view` calls `adv_search_build` to build advanced search.
Policy simulation should have no advanced search.
This can fail with an exception, when the `session[:adv_search]` hash has an entry for the model class
(but currently policy simulation seems to get `VmOrTemplate` whereas infra VMs get `ManageIQ::Providers::InfraManager::Vm`).
(That happens because when `adv_search_build` finds an entry, it assumes a corresponding entry in `@edit` exists, but `@edit` gets cleared for policy simulation.)
So, making sure `adv_search_build` never happens, by setting `@in_a_form` early, in `policy_sim`.
Fixes …
> policy_sim - set @in_a_form to prevent adv_search_build

- app/assets/stylesheets/about_modal_background.scss
- app/javascript/components/miq-about-modal.jsx
- app/views/layouts/_header.html.haml
- app/views/layouts/application.html.haml
This way we don't have to hack the document's body, but we can pass a class directly to the about modal to show a custom background image. There is be no visual change, just lower semantical complexity of the HTML layout.
Resolves https://github.com/patternfly/patternfly-react/issues/2185
@miq-bot add_label technical debt, hammer/no, ivanchuk/no, react
> Pass the conditional class to the About Modal instead of HTML body

- app/assets/javascripts/miq_tree.js
- app/presenters/tree_builder_network.rb
- app/presenters/tree_builder_storage_adapters.rb
Under a host's summary screen, there's a tree for the network devices and the storage adapters. They have been both using the same JS function to handle clicks. However, there was some mistakenly commented code in the networks tree that allowed only VMs to be clickable. As the code was commented out, none of the nodes were actually clickable, making the JS function to be never called. On the other hand, the JS function handling the clicks doesn't know how to deal with the nodes in the storage trees. 
Based on these facts, my proposal is to make the storage tree not clickable at all and make the VMs clickable on the networks tree.
@miq-bot add_label bug, trees, hammer/no, ivanchuk/no
> Switch the clickability between networks and storage trees

- app/presenters/tree_builder.rb
There's absolutely no need for this argument anymore, so :scissors: :toilet: :fire: 
@miq-bot add_label cleanup, technical debt, hammer/no, ivanchuk/no, trees
> Completely get rid of the options argument from all TreeBuilder methods

- product/views/ServiceTemplate.yaml
Due to enhancement made in https://github.com/ManageIQ/manageiq-ui-classic/pull/5445 , Now list of tenant can be lot of tenant names and may not fit properly on the list view, so removing the column from list view as this information is available in a nice tree view on the details view of a Catalog Item.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740172
before
after
> Removed `Tenant` column from list view.

- app/presenters/tree_builder.rb
None of these options are being set/used anymore so I'm removing them :scissors: 
@miq-bot add_label trees, cleanup, hammer/no, ivanchuk/no
> Drop the conversion of legacy options from TreeBuilder#convert_bs_tree

- app/assets/javascripts/miq_tree.js
- app/presenters/tree_builder_network.rb
The `Vm` class is being resolved as `TreeNode::Vm` but during my code reload it has been properly resolved as `Vm`. The solution is to force it to the top-level by using the `::` prefix. Also the 🌳 can display templates as well, so I'm extending the behavior to the `VmOrTemplate` model and updating the URL for redirections.
See also: https://github.com/ManageIQ/manageiq-ui-classic/pull/5990
> Fix onclick setting for VMs on host/networks🌳 extend it to templates

- app/controllers/application_controller/miq_request_methods.rb
- app/controllers/miq_request_controller.rb
We're no longer building a 🌳 for tags, just create a structure that holds all of them, so I'm renaming this misleading method. 
@miq-bot add_reviewer @PanSpagetka 
@miq-bot add_label technical debt, hammer/no, ivanchuk/no
> Rename build_tags_tree to build_tags_for_provisioning

- app/controllers/auth_key_pair_cloud_controller.rb
- app/controllers/mixins/actions/vm_actions/ownership.rb
- app/helpers/application_helper/toolbar/auth_key_pair_cloud_center.rb
- app/helpers/application_helper/toolbar/auth_key_pair_clouds_center.rb
- app/helpers/auth_key_pair_cloud_helper/textual_summary.rb
- app/views/auth_key_pair_cloud/show.html.haml
- config/routes.rb
Master version of #5967
#5967
https://bugzilla.redhat.com/show_bug.cgi?id=1589766
https://bugzilla.redhat.com/show_bug.cgi?id=1730066
ManageIQ/manageiq#19124
Screenshots
> Add Set Ownership to Key Pairs

- app/controllers/ops_controller.rb
- app/controllers/ops_controller/settings/schedules.rb
- app/controllers/report_controller/schedules.rb
- spec/controllers/ops_controller/settings/schedules_spec.rb
The functionality of schedule_run_now added.
It adds choose Schedule/s to the MiqQueue. After adding, flash messega appears and checked boxes are unchecked.
It tests adding 1 Schedule and multiple Schedules.
Simulate checking Schedule/s and expect correct flash message.
Then control if the Schedule/s are in MiqQueue
Before:
After:
Is it okay like that? Can I start writing specs? @himdel 
@lpichler
> Queue up schedule/s to run now

- app/assets/javascripts/controllers/host/host_form_controller.js
- app/controllers/host_controller.rb
- app/controllers/mixins/actions/host_actions/discover.rb
- app/helpers/application_helper/toolbar/hosts_center.rb
- app/views/host/_form.html.haml
- app/views/host/discover.html.haml
- app/views/host/new.html.haml
- spec/controllers/application_controller_spec.rb
- spec/controllers/host_controller_spec.rb
- spec/javascripts/controllers/host/host_form_controller_spec.js
Removes the Discover and Add buttons from the Hosts screen. 
Related PRs:
https://github.com/ManageIQ/manageiq/pull/19116 (removes related user roles)
https://github.com/ManageIQ/manageiq/pull/19107
@miq-bot add_labels bug, compute/infrastructure
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1733294
> Remove Host Discover and Add buttons

- app/presenters/tree_builder_belongs_to_vat.rb
- app/presenters/tree_builder_ems_folders.rb
We were determining the blueness of a VMware folder via a recursive method and it was a little ineffective. Thanks to @agrare now we can use a [direct call](https://github.com/ManageIQ/manageiq/pull/19112) on the `EmsFolder` record. There are two trees that use this feature:
* Settings -> RBAC -> Group -> Last tab
* Control -> Explorer -> Alert Profiles -> VM alert profile -> Edit Assignments -> Select folder
@miq-bot add_label technical debt, trees, hammer/no, ivanchuk/no
> Determine if EmsFolder is a blue folder using a model method

- package.json
Fixes #5589
The problem with node 12 was that we need a newer version of node-sass (4.12.0), and that there was no new version of fs-ext or ttembed-js which depends on it, but fortunately we could drop ttembed-js completely, in https://github.com/ManageIQ/react-ui-components/pull/141
So, this brings us to compatibility with node 12.
(@simaishi should we ivanchuk/yes this? Any change we will need to build ivanchuk with node 12 at some point?)
> Support node 12

- app/presenters/tree_builder_automation_manager_configured_systems.rb
- app/presenters/tree_builder_configuration_manager_configured_systems.rb
- app/presenters/tree_builder_configured_systems.rb
There's no need for the (probably copy-pasted) lazy-loading setting for `Configured Systems` trees in Automation/Ansible Tower and Configuration/Management. The trees are just 2 levels deep and no additional data is being loaded.
@miq-bot add_label hammer/no, ivanchuk/no, trees, technical debt
> Drop the laziness of the Foreman/Ansible configured systems 🌳🌳

- app/views/report/_savedreports_list.html.haml
This is an ugly implementation of the solution and I'm not proud of it, however, without proper refactorings in the area, I cannot do better here :disappointed: 
We display either the flash messages or the original *choose a report* message based on the availability of the `@flash_array`.
**Before:**
**After:**
@miq-bot add_label bug, hammer/no, ivanchuk/yes,cloud intel/reporting
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740686
> Display flash messages for report that has no data available

- app/helpers/application_helper/title.rb
Fix code to display text for My Tasks/All Tasks browser tabs in runtime language.
https://bugzilla.redhat.com/show_bug.cgi?id=1740777
Screen shot in Japanese runtime showing text in English prior to code fix, for All Tasks:
Screen shot in Japanese runtime showing text in English prior to code fix, for My Tasks:
Screen shot post code fix for Japanese language runtime, for All Tasks:
Screen shot post code fix for Japanese language runtime, for My Tasks:
Screen shot post code fix for Chinese language runtime
Screen shot post code fix for French language runtime:
> Fix browser tabs for My/All Tasks text display in runtime language

- config/routes.rb
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1733120
This PR adds missing routes to enable ability to compare Managed VMs of a Datastore (selected VMs, displayed in a nested list from Relationships table of a chosen Datastore).
**Note:**
missing _Cancel_ button will be fixed via https://bugzilla.redhat.com/show_bug.cgi?id=1733295
**Before:**
**Actually:**
> Add missing routes to compare managed VMs of a Datastore

- app/controllers/chargeback_controller.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1740408
There is a typo in Chargeback breadcrumbs options
@miq-bot add_label bug, ivanchuk/yes, breadcrumbs
> Fix typo in chargeback breadcrumbs options

- app/presenters/tree_builder_configuration_manager.rb
- spec/controllers/provider_foreman_controller_spec.rb
Under `Configuration -> Management -> Providers` the 🌳 has an unnecessary `Foreman Providers` node that remained after the extraction of Ansible Tower to `Automation`. The stuff on the right side doesn't really match what's written on that folder node. Also we have no other provider types in the area and even if we would have, we don't have this behavior elsewhere. So making it consistend and also getting rid of the `load_children` option.
**Before:**
**After:**
@miq-bot add_label hammer/no, ivanchuk/no, ux/review, trees, technical debt, cleanup
@terezanovotna please take a look at the screenshots
> Flatten the ConfigManagerProvider🌳 by dropping the single type

- app/controllers/pxe_controller.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1740405
Another BZ, another typo
`Networking` should be `PXE`
@miq-bot add_label bug, breadcrumbs, ivanchuk/yes
> Fix typo in PXE breadcrumbs_options

- app/controllers/ems_block_storage_controller.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1740843
Typo in menu breadcrumbs title
(the last breadcrumb will be resolved by https://github.com/ManageIQ/manageiq-ui-classic/pull/5904 )
**Before**
**After**
@miq-bot add_label breadcrumbs, ivanchuk/no, storage, bug
> Fix manager typo in menu breadcrumbs

- app/controllers/ops_controller.rb
- app/views/layouts/_auth_credentials2.html.haml
There's no need to enter the password twice, because it's not a password setting, but a login. Also the identity of the two fields isn't even being checked.
**Before:**
**After:**
@miq-bot add_label bug, technical debt, hammer/no, ivanchuk/yes
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740696
> Do not require password verification for RHN subscription

- app/javascript/components/cloud-tenant-form/create-form.schema.js
- app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap
https://bugzilla.redhat.com/show_bug.cgi?id=1732501
Select in the cloud tenant form is heading upwards in the production version and because of it, a lot of options are hidden. This change make it always to head bottom, until we do a proper investigation (in DDF repo) why it happens. 
@lpichler
@miq-bot add_label bug, ivanchuk/yes, changelog/yes
> Make select in new cloud tenant always headed to bottom

- app/controllers/miq_policy_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- spec/controllers/miq_policy_controller_spec.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1740290
Bad breadcrumbs on non-explorer control pages
- fixes breadcrumbs in control section (all pages are one controller and the controller is using features for generating trees...)
- also adds a new option to breadcrumb mixin how to manually disable tree branch
**Before**
export
log
**After**
export
log
TODO
@miq-bot add_label bug, breadcrumbs, ivanchuk/yes, control
> Fix breadcrumbs in control section

- app/controllers/miq_ae_tools_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- spec/controllers/miq_ae_tools_controller_spec.rb
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1740761
- Automate  .... log, import/export, simulation are one controller. It makes some issues to get a correct path in the simulation page.
- Also added an option for controllers to control when to show `@title` breadcrumb in non-explorer screens
**Before**
**After**
Simulation
@miq-bot add_label bug, ivanchuk/yes, breadcrumbs, automation/automate, changelog/yes
> Fix automate/simulation breadcrumbs

- app/javascript/components/breadcrumbs/index.js
- app/javascript/components/breadcrumbs/on-click-functions.js
- app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
- app/javascript/spec/breadcrumbs/breadcrumbs.spec.js
- app/javascript/spec/breadcrumbs/on-click-functions.spec.js
https://bugzilla.redhat.com/show_bug.cgi?id=1725927
- adds miqCheckForChanges in breadcrumbs
**Steps to test:**
1. Go to any form (not DDF)
2. Change something
3. Click on breadcrumbs
**Before**
**After**
@miq-bot add_label bug, breadcrumbs, changelog/yes, ivanchuk/no
@miq-bot add_reviewer @Hyperkid123
> Call miqCheckForChanges in breadcrumbs

- app/controllers/auth_key_pair_cloud_controller.rb
- app/controllers/mixins/actions/vm_actions/ownership.rb
- app/helpers/application_helper/toolbar/auth_key_pair_cloud_center.rb
- app/helpers/application_helper/toolbar/auth_key_pair_clouds_center.rb
- app/helpers/auth_key_pair_cloud_helper/textual_summary.rb
- app/views/auth_key_pair_cloud/show.html.haml
- app/views/shared/views/_ownership.html.haml
- config/routes.rb
Add Set Ownership to Auth Key Pairs for Hammer. 
Master PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/5973
https://bugzilla.redhat.com/show_bug.cgi?id=1589766
https://bugzilla.redhat.com/show_bug.cgi?id=1730066
ManageIQ/manageiq#19124
Screenshots
> [HAMMER] Add Set Ownership to Auth Key Pairs

- app/javascript/components/code-editor/index.js
- app/javascript/spec/code-editor/__snapshots__/code-editor.spec.js.snap
- app/javascript/spec/code-editor/code-editor.spec.js
- app/javascript/spec/orchestration-template/orchestration-template-form.spec.js
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1740753
Trying to use different event handlers to make QE testing easier.
> Use react-codemirror onChange event instead of onBeforeChange.

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/report-data-table.scss
- app/javascript/components/report-data-table.jsx
- app/javascript/spec/report-data-table.spec.js
The active filter display allows one click clearing of the filters as
requested by a BZ.
https://bugzilla.redhat.com/show_bug.cgi?id=1739264
The display of active filter is partly ready for the multi-criteria
filtering, once it's available in the API.
When there are no records, no grid and no paginator is displayed.
Instead an empty state component with a message is displayed.
https://bugzilla.redhat.com/show_bug.cgi?id=1740055
ping @himdel 
After:
> Report data: add display of active filter. Add empty state.

- app/controllers/cloud_tenant_dashboard_controller.rb
- app/services/cloud_tenant_dashboard_service.rb
- app/services/dashboard_service.rb
- Fixed to use CloudTenant record to get counts of relationships for Cloud Tenant dashboard, prior to changes in this PR, code was using a Provider record to get counts and was also passing in an incorrect controller to the CloudTenantDashboardService module.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1731735
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1487178
before
after
> Fixed correct setting of record to get counts of relationships

- app/controllers/utilization_controller.rb
- spec/controllers/utilization_controller_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1741188
This controller was missing breadcrumbs.. because it doesn't work in my version, so I skipped it and I forgot to check it later. :disappointed: 
**Before**
**After**
@miq-bot add_label bug, ivanchuk/yes, breadcrumbs
> Introduce breadcrumbs to utilization controller

- app/controllers/cloud_network_controller.rb
- app/controllers/network_router_controller.rb
- spec/controllers/cloud_network_controller_spec.rb
- spec/controllers/network_router_controller_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740891
Go to Networks > Network Routers > click the router > click Floating IPs > select an IP > Policy > Edit Tags
Go to Networks > Cloud Network > click the network > click Floating IPs > select an IP > Policy > Edit Tags
Notes:
Network with Floating Ips `ext` or find one in console ` CloudNetwork.find{ |cn| cn.floating_ips.present? }`
Network Router with Floating Ips `kocsisrouter` or find one in console `NetworkRouter.find{ |cn| cn.floating_ips.present? }`
Before:
Nothing happens
After:
Tagging screen for Floating Ip appears
@miq-bot add_label bug, tagging, ivanchuk/yes, changelog/no
cc @hstastna
> Allow Tagging for Floating Ip from CloudNetwork/NetworkRouter

- app/controllers/application_controller/buttons.rb
- config/routes.rb
Fixes for:
https://bugzilla.redhat.com/show_bug.cgi?id=1550002
* "Provider" is really an "ExtManagementSystem",
* `wait_for_task` route missing in Service controller.
~~For "Provider" testing also https://github.com/ManageIQ/manageiq/pull/19157 is needed.~~ (merged)
```
provider = $evm.root['ext_management_system']
provider.external_url = "https://www.redhat.com"
```
```
service = $evm.root['service']
service.external_url = "https://www.redhat.com"
```
```
t = $evm.root['cloud_tenant']
$evm.log(:info, "cloud_tenant: #{t.inspect}")
t.external_url = "https://www.redhat.com"
```
~~Requires automation engine PR: https://github.com/ManageIQ/manageiq-automation_engine/pull/350~~ (merged)
```
$evm.log(:info, $evm.root['vmdb_object_type'])
$evm.log(:info, "tenant_id: #{$evm.root['tenant_id']}")
t …
```
> Automate url open fixes

- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/optimization_controller.rb
- spec/controllers/optimization_controller_spec.rb
Breadcrumbs deduplicate breadcrumbs with identical titles,
but for Optimization, the "saved reports under report" can have the same title as the "saved report detail" screen,
because the names of the saved reports are generated from the name of the report definition.
Adding a (failing) spec to make sure these don't get deduplicated in those conditions.
And overridden `data_for_breadcrumbs` with a version that just returns the defined breadcrumbs 
Cc @rvsia 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741203
> Optimization - don't deduplicate breadcrumbs when report definition and saved report have the same name

- app/controllers/application_controller/buttons.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1687289
Go to Services -> Catalogs -> Catalog Items -> have a Catalog Item with just one Button Group -> delete it
Before:
After:
@miq-bot add_label bug, ivanchuk/yes, hammer/yes
> Do not highlight Action node when deleting last Button Group

- app/views/catalog/_form_basic_info.html.haml
- app/views/catalog/_sandt_tree_show.html.haml
- app/views/catalog/_st_angular_form.html.haml
- spec/views/catalog/_form_basic_info.html.haml_spec.rb
- spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
- spec/views/catalog/_st_angular_form.html.haml_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1741075
Related RFE: https://github.com/ManageIQ/manageiq-ui-classic/pull/5445
User needs to have permission to see Tenants (_Configuration -> Access Control -> Tenants -> View_), and it means that also _Additional Tenants_  in Catalog Item details page (Additional Tenants are still Tenants). However, _Additional Tenants_ field was always present. So with this PR, I am hiding it if user's role doesn't have this permission.
---
Note:
If you are a super admin, you can see all Tenants in Additional Tenants tree, for Catalog Item.
If you log in as a user, you can see Tenants according to your role's permissions:
---
**Before:**
**After:**
No _Additional Tenants_ section in Catalog Item details page:
No _Additional Tenants_ section in …
> Hide Additional Tenants of Catalog Item if role does not allow displaying them

- app/helpers/application_helper/toolbar_builder.rb
Make sure you have a `Service` that has a `ServiceTemplate`/`Generic Object` with Unassigned `Custom Button(s)`.
Go to Services -> My Services -> click on that `Service` -> see buttons in toolbar
Before: There are some unassigned buttons
After: Only `CustomButtonSet(s)` are in toolbar
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1709870
TODO: Fix it in SUI as well.
Cc: @himdel @h-kataria
> Do not show unassigned buttons in My Service page

- app/controllers/service_controller.rb
- app/services/dialog_local_service.rb
Need to pass in correct parent record id and generic_object id to build endpoint url correctly when pressing a GO custom button from list view or details view.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1729341
In favor of https://github.com/ManageIQ/manageiq-ui-classic/pull/6049
@tinaafitz @pkomanek please review/test. Please test pressing custom button from List view and details view.
> Fixed API endpoint for GO object custom button dialogs.

- app/helpers/application_helper/toolbar_builder.rb
Fixing linter error from https://github.com/ManageIQ/manageiq-ui-classic/pull/6053
@miq-bot add_label ivanchuk/no, cleanup
> Fix missing whitespace

- app/presenters/tree_builder_ops_vmdb.rb
- app/presenters/tree_node/hash.rb
On the `OPS -> Database` screen each DB node in the left side tree has an `Indexes` node that contains all the node's indexes. This node is automatically expanded by altering the tree state using `open_node` and its children are preloaded using the `load_children` attribute. However, the exact same functionality can be achieved by setting the `expand` attribute which is much simpler and it might allow us to get rid of the `load_children` completely in the future.
@miq-bot add_label refactoring, hammer/no, ivanchuk/no, trees
> Mark the Indexes node as expanded instead of altering it in 🌳state

- app/presenters/tree_builder_services.rb
Totally unnecessary, it is anyway the active node which is always being expanded/loaded. If it would be really necessary, we can just set the `expand` attribute on it.
@miq-bot add_label technical debt, cleanup, hammer/no, ivanchuk/no, trees
> Do not set load_children on the Active Services in the Services🌳

- app/presenters/tree_builder_storage_pod.rb
- app/views/storage/_storage_pod_folders.html.haml
The 🌳 under `Infrastructure -> Datastores -> Datastore Clusters` is lazy and it has `EmsFolder` records converted to `Hash` so the `load_children` attribute can be set on them. I'm removing this complexity by making the tree non-lazy :hammer_and_wrench:
Note that there are no clusters in the DB we're using for development, you need to add the vc60 provider to test this.
@miq-bot add_label refactoring, hammer/no, ivanchuk/no, trees
> Make the Datastore Clusters 🌳  non-lazy as always loads its 🧒🧒

- app/presenters/tree_builder.rb
After merging https://github.com/ManageIQ/manageiq-ui-classic/pull/6020, https://github.com/ManageIQ/manageiq-ui-classic/pull/6019, https://github.com/ManageIQ/manageiq-ui-classic/pull/6017 and https://github.com/ManageIQ/manageiq-ui-classic/pull/6021 the `load_children` becomes obsolete. The only other place where it si being used is the roles tree in RBAC, but there's no difference after removing it.
@miq-bot add_label hammer/no, ivanchuk/no, trees, cleanup, pending core
> Drop the load_children from 🌳Builder as it is no longer used

- app/controllers/service_controller.rb
comes from https://github.com/ManageIQ/manageiq-ui-classic/pull/6052
Just a cosmetic detail, this should be doing exactly the same thing as before :)
Cc @h-kataria
> Service - use x_node instead of accessing tree internals via @sb

- app/views/layouts/_exp_editor.html.haml
The spinner was appearing below the modal when clicking 'Undo previous change' or 'Redo previous change' arrow buttons on Advanced Search, while the original issue noted in the BZ was fixed by https://github.com/ManageIQ/manageiq-ui-classic/pull/4847.  
@miq-bot add_labels bug, "configuration management" 
@miq-bot add_reviewer himdel
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740239
> Fix spinner behavior when clicking redo/undo change buttons in Adv Search

- app/helpers/application_helper/button/miq_widget_set_copy.rb
- app/helpers/application_helper/toolbar/miq_widget_set_center.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1314875
- Log in as a user that has no SuperAdmin rights but can see Overview -> Reports
- Go to Overview -> Reports -> Dashboards-> select one -> Configuration -> Copy Selected Dashboard
**Before:**
*After clicking*
**After:**
@miq-bot add_label bug, ivanchuk/yes, blocker
> Hide Copy Widget for non-SuperAdmin users

- app/assets/javascripts/miq_application.js
- app/assets/javascripts/miq_global.js
- app/views/layouts/_user_options.html.haml
When logging out via the Logout button,
when there are multiple HTTP requests happening,
the logout can cause API requests to fail with a 401 before the browser redirects to the login screen,
causing the response handler to call redirectLogin, to redirec to the login screen with a "session timed out" message.
We should not be claiming a timeout *during* logout, adding a check for that.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741283
> Prevent login redirect with ?timeout during logout

- app/views/shared/views/_alerts_list.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653427
Adding info about offending VM/ContainerNode/... to All Alerts Overview
Go to Monitor -> Alerts -> All Alerts
Before:
After:
@miq-bot add_label enhancement, ivanchuk/yes, wip
> Add offending Vm/Container Node/... to All Alerts Overview

- app/helpers/application_helper/toolbar_builder.rb
- spec/helpers/application_helper/toolbar_builder_spec.rb
This reverts commit f1c64661b9b27ade886f94bd7af81fd68f620068.
Because https://github.com/ManageIQ/manageiq-ui-classic/pull/6053 sounds ok but it's not. Correct behaviour described in https://github.com/ManageIQ/manageiq-ui-classic/issues/6062
> Revert "Do not show unassigned buttons"

- app/controllers/mixins/actions/vm_actions/reconfigure.rb
- spec/controllers/mixins/actions/vm_actions/reconfigure_spec.rb
Added nil check to fix `undefined method `storages' for nil:NilClass` error
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1743529
To recreate: try to reconfigure an archived VM
> Fix nilClass error

- app/views/miq_ae_customization/editor.html.haml
this changes the dialog editor save/cancel buttons to use miq-button
the difference is that disabled buttons don't display title,
but non-enabled miq-buttons do display disabledTitle
(related to https://bugzilla.redhat.com/show_bug.cgi?id=1729265 )
Cc @romanblanco 
(the idea is - let's first make sure we display the message, and then we can deal with more explicit ways of displaying it, other than a tooltip, in https://github.com/ManageIQ/manageiq-ui-classic/pull/5922)
> Dialog Editor - show validation title when button is disabled

- app/controllers/report_controller.rb
- app/controllers/report_controller/saved_reports.rb
- spec/controllers/report_controller_spec.rb
I noticed that the new nice titles for reports where only available under the report results tree.
Looking into that I found 2 code paths doing basically the same.
By unifying those 2 there are now the same titles in both places (under both trees).
> Report cleanup

- app/controllers/miq_ae_customization_controller.rb
- spec/controllers/miq_ae_customization_controller_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1741241
Service dialog editor do not have specific titles, so they cannot be displayed in the breadcrumbs.
This PR only adds titles, https://github.com/ManageIQ/manageiq-ui-classic/pull/6073 will show them in breadcrumbs.
**Before**
Edit/Add
**After**
Add
Editing
@miq-bot add_label bug, ivanchuk/yes, changelog/yes
> Add titles for editor of service dialogs

- app/controllers/mixins/actions/vm_actions/reconfigure.rb
Convert hash coming from params to notmal hash. Following Rails 5.1
upgrade.
https://bugzilla.redhat.com/show_bug.cgi?id=1740628
ping @h-kataria
> VmReconfigure: convert ActionController::Parameters to hash.

- app/controllers/application_controller/buttons.rb
Catalog controller `replace_right_cell` method expects `action` to be passed in to display form buttons on reorder buttons form.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744459
before
after
> Needed to pass in `action` to fix form button display in form

- app/controllers/optimization_controller.rb
- app/controllers/report_controller/saved_reports.rb
- spec/controllers/optimization_controller_spec.rb
Overview > Optimization - click on a report with results, click on a report result
similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/6035 and https://github.com/ManageIQ/manageiq-ui-classic/pull/6076,
this is the 3rd place we're showing saved reports in, all should have consistent titles :).
Before:
After:
Cc @martinpovolny
> Optimization - html title for saved reports

- app/controllers/catalog_controller.rb
- spec/controllers/catalog_controller_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1743492
Bug introduced in: https://github.com/ManageIQ/manageiq-ui-classic/pull/5472
This PR adds necessary condition to catalog controller which was removed recently.
`if params[:display]` is needed because after checking _Display in Catalog_ checkbox and then adding a Resource in _Resources_ tab, while adding/editing some _Catalog Bundle_, `params[:display]` is set to `nil` (obviously, because we did not make any change about displaying in Catalog, we just added some Resource) but `@edit[:new][:display] = params[:display] == "1"` is executed anyway - and this leads to the unwanted behavior: `@edit[:new][:display]` is reset from `true` to `false` - and this leads to the fact that _Display in Catalog_ checkbox becomes unchecked. …
> Allow Display in Catalog to stay checked for Catalog Bundle

- app/presenters/tree_builder_alert_profile_obj.rb
All the nodes have their own definition of `text`, so there's no need for overriding. You can find these :deciduous_tree: :deciduous_tree: under `Control -> Explorer -> Alert Profiles` when you try to edit the assignments of an existing alert profile. Also dropping the unnecessary `hideCheckbox` override as it's by default alwas `false`.
@miq-bot add_label cleanup, ivanchuk/no, trees
> Drop the node text override from AlertProfile assignment 🌳🌳

- app/presenters/tree_builder_automation_manager_configuration_scripts.rb
- app/presenters/tree_builder_configured_systems.rb
- app/presenters/tree_builder_filters_mixin.rb
- app/presenters/tree_builder_services.rb
- app/presenters/tree_builder_storage.rb
- app/presenters/tree_builder_vms_filter.rb
I pulled out the definition of filters into constants and built a hash from this constant. I know that the hash seems an overkill in the current codebase (as we're calling just `#values` on it), but it will be useful when reverse building tree hierarchies for breadcrumbs. I also created a new method for fetching the child nodes and now we're using it across all the trees.
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/5620
@miq-bot add_label hammer/no, ivanchuk/no, refactoring, trees
> Clean up the building of my/global filters in TreeBuilders that contain them

- app/controllers/report_controller.rb
- app/presenters/tree_builder_report_saved_reports.rb
- spec/presenters/tree_builder_report_saved_reports_spec.rb
Hash nodes are evil as we can work much better with nodes that are mapped from objects. In the `Saved Reports` under `Overview -> Reports` the explorer tree unnecessarily uses hash nodes for `MiqReport` records. I had to tweak the `get_node_info` a little so it can handle the new prefix, but as it is a prefix that has not been used in the tree before, it should be safe.
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/5620
@miq-bot add_label hammer/no, ivanchuk/no, trees, refactoring, technical debt
> Do not use hash nodes for MiqReport records in Saved Reports 🌳

- app/presenters/tree_node/ext_management_system.rb
- app/presenters/tree_node/generic_object_definition.rb
- app/presenters/tree_node/miq_ae_domain.rb
- app/presenters/tree_node/miq_ae_method.rb
- app/presenters/tree_node/node.rb
- app/presenters/tree_node/service.rb
- app/presenters/tree_node/service_template.rb
- app/presenters/tree_node/windows_image.rb
As we're always using decorators for setting the node images and they always have a higher priority than icons, we can simplify the codebase a little. The `TreeNode::Node` class already derived the `icon` attribute from the decorators, so I did the same for images.
Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/6093
@miq-bot add_label pending core, ivanchuk/no, trees, cleanup
> Simplify TreeNode image definition by always using the decorators

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_roles_by_server.rb
- app/presenters/tree_builder_servers_by_role.rb
There are two trees setting the `highlighted` attribute in their `override` method. This attribute is being converted to the bootstrap-treeview format in `TreeBuilder.convert_bs_tree`. The trees are accessible under Ops/Diagnostics in the first two tabs when selecting a Zone. Instead of the conversion, we can set the value directly to the desired in these two places. 
@miq-bot add_label refactoring, ivanchuk/no, trees
> Set the node as selected using the state hash directly

- app/presenters/tree_builder.rb
- app/presenters/tree_node/node.rb
- spec/controllers/application_controller/explorer_spec.rb
- spec/controllers/miq_ae_class_controller_spec.rb
- spec/presenters/tree_builder_roles_by_server_spec.rb
- spec/presenters/tree_builder_servers_by_role_spec.rb
- spec/presenters/tree_builder_spec.rb
Lazy loading is being set using the `:lazyLoad` attribute on a single place in `TreeBuilder#x_build_node`. The legacy `:isLazy` attribute is no longer used, so it's safe to drop it from the `convert_bs_tree` method.
The `addClass` attribute has been used only on a single place in `TreeNode#to_h` and then converted to `:class` in `convert_bs_tree`. Instead of this conversion, we can set it directly, which lets us delete a few extra lines from the conversion code.
@miq-bot add_label ivanchuk/no, trees, refactoring, cleanup
> Remove some legacy 🌳node conversion code for CSS classes and lazy loading

- app/assets/javascripts/components/retirement-form.js
Setting saveable state only when 1 item is selected for retirement was causing Save button to remain disabled when multiple items were selected for retirement.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1745984
before
after
> Fixed to set saveable state regardless of number of items selected.

- app/controllers/application_controller.rb
- app/controllers/cloud_volume_controller.rb
- spec/controllers/application_controller_spec.rb
When trying to delete a Cloud Volume that has instances attached to it from its summary view, need to stay on the summary screen and show warning flash message on the same screen. Previous code was redirecting to list view after pressing delete button even tho the Cloud Volume deletion was not successful and was showing warning flash message as green message.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1745989
In this case when deleting a single item from it's summary screen in absence of flash error message, code just assumes that delete was successful and redirects user to the list view. Made changes to check for warning message as well in the `@flash_array`
before
after
> Fixed to show a warning flash message.

- app/presenters/tree_builder_snapshots.rb
We don't need to manipulate the tree state in the snapshots tree for opening all nodes as there's already an `:open_all` option that expands the whole tree. Thanks to this I can :scissors: :fire: some lines of code.
@miq-bot add_label ivanchuk/no, trees, cleanup
> Expand the snapshots 🌳 with open_all instead of changing its state

- app/views/chargeback/_cb_rate_show.html.haml
This PR moves the text as an explanation for a second column for _Rate Details_ table to the right place: under the _Description_, in the table.
**Where:**
_Overview > Chargeback > Rates_ accordion > click on some Rate and check the _Rate Details_ table
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/5259
**Related PR:** https://github.com/ManageIQ/manageiq-ui-classic/pull/4596
---
**Before:**
**After:**
**Note:**
While editing a rate, this text is already in the right place:
> Move text under Description to Chargeback Rate Details table

- package.json
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1729940
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1732501
Select dropdown menu was opening always to the top in production version of manageIQ. This was fixed in newer version of data-driven-forms.
Updateting from v1.13.3 to v1.15.x will resolve the issues.
- turn on production compilation in webpack dev config.
```diff
diff --git a/config/webpack/development.js b/config/webpack/development.js
index 5cf7aa720..c6417d14a 100644
--- a/config/webpack/development.js
+++ b/config/webpack/development.js
@@ -1,22 +1,36 @@
// Note: You must restart bin/webpack-dev-server for changes to take effect
-const merge = require('webpack-merge')
-const sharedConfig = require('./shared.js')
-const { settings, output } = …
```
> Update data driven forms to v1.15.6

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_alert_profile_obj.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_belongs_to_vat.rb
- app/presenters/tree_builder_clusters.rb
- app/presenters/tree_builder_datastores.rb
- app/presenters/tree_builder_default_filters.rb
- app/presenters/tree_builder_ems_folders.rb
- app/presenters/tree_builder_protect.rb
- app/presenters/tree_builder_resource_pools.rb
- app/presenters/tree_builder_sections.rb
- app/presenters/tree_builder_smartproxy_affinity.rb
- app/presenters/tree_builder_tenants.rb
- app/presenters/tree_node/hash.rb
- app/presenters/tree_node/menu/item.rb
- app/presenters/tree_node/miq_product_feature.rb
- app/presenters/tree_node/node.rb
- spec/presenters/tree_builder_alert_profile_obj_spec.rb
- spec/presenters/tree_builder_clusters_spec.rb
- spec/presenters/tree_builder_default_filters_spec.rb
- spec/presenters/tree_builder_protect_spec.rb
- spec/presenters/tree_builder_sections_spec.rb
- spec/presenters/tree_builder_smartproxy_affinity_spec.rb
There was a naming issue with the `select` and `selected` attributes in `TreeNode` as they have been used for setting the checkbox. So to make things right first, I'm renaming it to `checked` to make a little more sense. Then I'm moving the conversion of the `checked` attribute from `TreeBuilder.convert_bs_tree` to the `TreeNode#to_h` so we can get rid of one more line from this evil method.
@miq-bot add_label ivanchuk/no, trees, cleanup, technical debt
> Replace select attribute in tree nodes with the state/checked

- app/presenters/tree_builder.rb
- app/presenters/tree_builder_automate.rb
- app/presenters/tree_builder_automate_catalog.rb
- app/presenters/tree_builder_belongs_to_hac.rb
- app/presenters/tree_builder_belongs_to_vat.rb
- app/presenters/tree_builder_compliance_history.rb
- app/presenters/tree_builder_ems_folders.rb
- app/presenters/tree_builder_infra_networking.rb
- app/presenters/tree_builder_network.rb
- app/presenters/tree_builder_resource_pools.rb
- app/presenters/tree_builder_smartproxy_affinity.rb
- app/presenters/tree_builder_storage_adapters.rb
- app/presenters/tree_builder_utilization.rb
- app/presenters/tree_node/node.rb
Moving the css class setting straight to the `TreeNode`, I'm trying to get rid of the `convert_bs_tree` method. The best to test is on the automate/explorer tree and the services tree's last 2 nodes.
As we're doing overrides to the `selectable` attribute after the node has been converted to hash, I had to add a method to explicitly set the `class` attribute in all affected `override` methods. It is just a temporary thing and shortly after the `convert_bs_tree` method is dropped, we can do the hash conversion of the trees AFTER we override stuff. 
@miq-bot add_label ivanchuk/no, trees, technical debt
> Move the CSS class setting to TreeNode from the BS tree conversion

- app/controllers/ops_controller/ops_rbac.rb
- app/controllers/ops_controller/settings/label_tag_mapping.rb
- app/controllers/ops_controller/settings/tags.rb
- app/controllers/ops_controller/settings/zones.rb
- spec/controllers/ops_controller/ops_rbac_spec.rb
**Depends on:** (merged)
https://github.com/ManageIQ/manageiq-ui-classic/pull/5472
This PR is simply updated solution from https://github.com/ManageIQ/manageiq-ui-classic/pull/3771. The problem there was that `""` vs `nil` was not the same value so then `changed` variable was set wrong (especially when writing something in the field and then deleting it all), and _Add_ button was not responding properly to the changes made in the fields while adding a new User.
No need to use `copy_params_if_present` for `params[:chosen_group]` because `""` vs `nil` issue is already solved in other place.
Using `copy_params_if_present` also in `rbac_group_get_form_vars` also simplifies the code little bit.
> Small refactoring in ops rbac

- app/presenters/tree_node/node.rb
The `image_path` works well with custom uploaded images as well with defined fileicons, so there's no more need for the complicated logic anymore.
@miq-bot add_label ivanchuk/no, trees, cleanup
> Simplify the logic around the TreeNode#image attribute generation

- app/presenters/tree_builder_alert_profile_obj.rb
- app/presenters/tree_builder_ops_rbac_features.rb
- spec/presenters/tree_builder_alert_profile_obj_spec.rb
The root node is [always expanded](https://github.com/ManageIQ/manageiq-ui-classic/blob/c5b9371e779bca82dce927ae47fdb32e47719d7d/app/presenters/tree_builder.rb#L197) when set via `root_options`, so there's no need to set it explicitly expanded one more time. The alert profile assign tree and the RBAC role features tree were affected and cleaned up.
@miq-bot add_label cleanup, ivanchuk/no, trees
> Do not set the :expand attribute on tree roots as it is redundant

- app/controllers/ops_controller/settings/tags.rb
While adding small changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/5815 , @romanblanco pointed out that I should also delete some unnecessary comments in one of the files I was changing. So I am doing this in this PR.
> Remove unnecessary comments in ops_controller/settings/tags.rb

- app/controllers/application_controller/tree_support.rb
- app/controllers/tree_controller.rb
- app/presenters/tree_builder.rb
After a couple of years, we're finally able to get rid of the "temporary" `convert_bs_tree` method that has been introduced into the `TreeBuilder` and `TreeNode` world to convert the tree from the old dynatree format into the new bootstrap treeview. All the conversions have been moved in previous PRs straight to the `TreeNode` attribute definitions.
There's a tiny little catch with the `TreeBuilder#override` methods, where the same format is being used as well. These calls will be standardized on the `TreeNode` objects and the overriding eventually will happen before we convert the nodes into hash format.
@miq-bot add_label cleanup, technical debt, ivanchuk/no, trees
@miq-bot …
> Drop the TreeBuilder.convert_bs_tree as it is no longer necessary

- app/presenters/tree_builder.rb
As I was cleaning up the `TreeBuilder`, the `x_build_node_tree` method became just a simple wrapper around `x_build_node`. Therefore it is safe to rename & remove :scissors: :fire: :toilet: :droplet: 
@miq-bot add_label cleanup, ivanchuk/no, trees
> Replace x_build_node_tree with x_build_node in TreeBuilder

- app/controllers/application_controller/buttons.rb
- app/helpers/application_helper/toolbar_chooser.rb
Missed some off-by-one indexes after [removing](https://github.com/ManageIQ/manageiq-ui-classic/pull/6080) the `Actions` in the Catalog Items tree.
**Before:**
**After:**
@miq-bot add_label bug, ivanchuk/no
> Fix off-by-one errors in Custom Buttons for Catalog Items

- app/controllers/chargeback_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740411
Core PR that fixes display of currency value on summary screen https://github.com/ManageIQ/manageiq/pull/19207
before
after
> Show selected currency value consistent with a drop down on edit screen

- app/presenters/tree_builder.rb
This method is no longer being used anywhere, so :scissors: :toilet: :fire: also removing the `resolve_object_lambdas` as it is being used only in this method.
@miq-bot add_label cleanup, ivanchuk/no, trees
> Remove the obsolete TreeBuilder#count_only_or_many_objects ✂️✂️

- spec/controllers/cloud_volume_controller_spec.rb
It's just cleanup for these tests cause the factories set names and things. 
Sorry for the silly changes, but I need a PR for the day, so. 
@miq-bot add_label hammer/no, refactoring, test, changelog/no, ivanchuk/no
> The factory sets names and descriptions so we don't need to in specs

- app/controllers/miq_ae_class_controller.rb
Description
-----------------
Fixing the silent UI errors for automate domain git refresh. If the automate domain at git is invalid, there is no error message output and no redirection from tag/branch choose page bellow. 
New error message output:
-----------------
Links
* related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1696396
* Steps are included in the BZ above.
> Add error message output for git domain refresh.

- app/controllers/host_controller.rb
In case of a HostKeyMismatch with an host not previously validated
credentials should be serialized to be available for the second
credentials verification.
This should fix https://bugzilla.redhat.com/show_bug.cgi?id=1624700
> Credentials parameters need to be serialized

- app/helpers/application_helper/toolbar_builder.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744440
1. In Automate -> Automation -> Customization -> create an unassigned button for Services 
2. In Services -> Catalogs -> Catalog Items -> create a Catalog Item with custom button(s) or custom button group with button(s)
3. Go to Services -> Service Catalogs -> Order a created Catalog Item
4. Go to Services -> My Services and click on the ordered Service
5. See buttons in the toolbar
Before:
*`Unassigned` button belongs to `Service`*
After:
@miq-bot add_label bug, services
> Do not show custom buttons of children of GO/ServiceTemplate in toolbar

- tools/ci/after_install.sh
`bin/setup` clones manageiq head to `spec/manageiq`,
but you can't tell which commit from the logs after.
Adding next to the lockfile output.
> Travis after_install - log manageiq commit

- app/controllers/cloud_network_controller.rb
- app/controllers/cloud_subnet_controller.rb
- app/controllers/floating_ip_controller.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6105
We can use new `copy_params_if_present` method in many places in the code and to improve functionality (remove `""` vs `nil` issues and bad response of `Add/Save` buttons), to simplify the code.
**Related PRs/changes:**
https://github.com/ManageIQ/manageiq-ui-classic/pull/5815
https://github.com/ManageIQ/manageiq-ui-classic/pull/5472/commits/d3c3878c7cde6f682c6e25928b7c90a4c01b664f#diff-956e46b33fb5307990c4e1a4b5fd86ccR1267
> Use copy_params_if_present in cloud network/subnet and floating ip controllers

- app/controllers/mixins/actions/vm_actions/ownership.rb
- spec/controllers/mixins/actions/vm_actions/ownership_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1741109
This PR makes items (VMs, Catalog Items, ...) on the Ownership screen not clickable to prevent interruption of setting ownership other than clicking on _Cancel_. The reason is achieving better consistency, for example while managing policies or policy simulation of VMs: there is also _Affected Items_ section (same as for setting ownership) and items (quadicons) there are NOT clickable (or some info is displayed after clicking on them also with _Back_ button so the operation is not interrupted).
---
**Before:** After clicking on the quadicon, setting ownership is over and textual summary of a chosen item is displayed
**After:** Quadicon is not clickable, user can cancel the operation normally by clicking on _Cancel_ button
> Make items on the Ownership screen not clickable

- app/presenters/tree_builder.rb
- app/presenters/tree_node/root.rb
- spec/presenters/tree_builder_spec.rb
- spec/presenters/tree_node/root.rb
- spec/presenters/tree_node_spec.rb
The logic responsible for adding a root node when necessary has been in two places. First when we build the tree, we create an empty root node if the `root_options` method is defined. Then after the tree is built, we call the `add_root_node` which overrides this empty node with options from the `root_options` method. 
Instead of this :spaghetti: I created a `TreeNode::Root` class which is inherited from `TreeNode::Hash` but this might [change](https://github.com/ManageIQ/manageiq-ui-classic/pull/6092) in the future. This makes the `add_root_node` method obsolete as it is being instantiated with `root_options`.
@miq-bot add_label refactoring, ivanchuk/no, trees
> Replaced add_root_node logic with a TreeNode::Root object

- spec/controllers/generic_object_definition_controller_spec.rb
I need a PR for the day, and we don't need to do this in tests, again. 
@miq-bot add_label hammer/no, refactoring, test, changelog/no, ivanchuk/no
> Names and descriptions are set by the factory

- app/javascript/components/orchestration-template/orcherstration-template-form.js
1. create an orchestration template
2. create another orchestration template with exactly the same content
Without this fix, a modal window showing an odd looking api error would be shown.
With this fix, a nice flash message with an error is rendered.
https://bugzilla.redhat.com/show_bug.cgi?id=1745884
> Correctly catch & handle API errors when creating orchestration template

- app/controllers/automation_manager_controller.rb
- product/views/ManageIQ_Providers_ExternalAutomationManager_ConfigurationScript.yaml
- spec/controllers/automation_manager_controller_spec.rb
Fixed class name that was changed in https://github.com/ManageIQ/manageiq-ui-classic/pull/5925, previously made change was excluding Workflow Templates in UI.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1747589
@tinaafitz pls review/verify.
> Using class that includes both Job and Workflow templates

- app/controllers/application_controller/miq_request_methods.rb
- app/controllers/mixins/manager_controller_mixin.rb
- app/controllers/vm_common.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6105
We can use `copy_params_if_present` method in some more places/controllers and to improve functionality (remove `""` vs `nil` issues and bad response of _Add/Save_ buttons) or to simplify the code.
Related PRs/changes:
https://github.com/ManageIQ/manageiq-ui-classic/pull/6139
#5815
https://github.com/ManageIQ/manageiq-ui-classic/commit/d3c3878c7cde6f682c6e25928b7c90a4c01b664f#diff-956e46b33fb5307990c4e1a4b5fd86ccR1267
> Use copy_params_if_present in vm_common, manager_controller_mixin and miq_request_methods

- app/controllers/application_controller/tags.rb
- app/controllers/ops_controller/ops_rbac.rb
- app/javascript/components/taggingWrapper.jsx
- app/javascript/miq-redux/middleware.js
- app/javascript/spec/miq-redux/middleware.spec.js
Send only string ids to Tagging. Due to the limitation of MAX_SAFE_INTEGER in JS  #1405, we need to consistently treat any database id as a string in JS.
In second commit I am fixing the issue with deleting on Group Tagging page.
https://github.com/ManageIQ/manageiq-ui-classic/issues/5946
#1405
#5946
> Send only string ids to Tagging

- spec/helpers/application_helper/toolbar_builder_spec.rb
Add specs for https://github.com/ManageIQ/manageiq-ui-classic/pull/6063
> Specs for Do not show custom buttons of children of GO/ServiceTemplate in toolbar

- app/presenters/tree_builder_snapshots.rb
In the snapshots tree for VMs the last tree node is not always the active snapshot. Therefore, I had to alter the logic of the selected node evaluation to select the active snapshot instead of the last one. It's testing the node's text for the `(Active)` suffix, which is not ideal. However, this is a fix to be backported and a more cleaner change would require a lot of risky changes in the codebase.
@miq-bot add_label bug, trees, ivanchuk/yes
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1745065
> Select active snapshot instead of the last one in the snapshots 🌳

- app/controllers/application_controller/ci_processing.rb
- app/controllers/cloud_network_controller.rb
- app/controllers/cloud_subnet_controller.rb
- app/controllers/network_router_controller.rb
- app/controllers/security_group_controller.rb
- app/controllers/storage_controller.rb
- config/routes.rb
- spec/controllers/cloud_network_controller_spec.rb
- spec/controllers/cloud_subnet_controller_spec.rb
- spec/controllers/network_router_controller_spec.rb
- spec/controllers/security_group_controller_spec.rb
- spec/controllers/storage_controller_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1741122
**Related PR with more info:** https://github.com/ManageIQ/manageiq-ui-classic/pull/5876
It was not possible to compare VMs/Instances/Hosts displayed in a nested list due to missing routes and/or missing `comparemiq` method in some controllers. You clicked on "Compare Selected items" and nothing happened in the UI or error message about missing route appeared. 
Adding missing routes and `comparemiq` calls in appropriate controllers fixes the problem. I am also adding `unless performed?` to prevent multiple calls of `javascript_flash` method, for example in storage controller - this can happen for some operations because of [this](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller/ …
> Allow comparing Hosts and VMs/Instances displayed as a nested list

- app/controllers/application_controller/policy_support.rb
- app/views/vm_common/_policies.html.haml
- spec/controllers/application_controller/policy_support_spec.rb
- spec/views/vm_common/_policies.html.haml_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1704395
_Back_ button was missing in policy simulation screen while checking details of selected item. This is related only to non-explorer screens, for example for list of VMs displayed thru provider's details page. For explorer ones, the button was there (see [this](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/layouts/_x_edit_buttons.html.haml#L163)).
I am also adding another change `session[:edit] = @edit`. First, `@edit` with details of policy simulation is set in `policy_sim_build_screen` [method](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller/policy_support.rb#L218) and then forgotten, for non-explorer screens. This caused problems with rendering the …
> Add Back button to policy simulation page for non-explorer

- app/controllers/miq_ae_tools_controller.rb
- app/controllers/miq_policy_controller/alerts.rb
- app/controllers/miq_policy_controller/miq_actions.rb
- app/controllers/miq_task_controller.rb
- app/controllers/pxe_controller/pxe_customization_templates.rb
- app/controllers/pxe_controller/pxe_image_types.rb
- app/controllers/report_controller/dashboards.rb
- app/controllers/report_controller/menus.rb
- app/controllers/report_controller/reports/editor.rb
- app/controllers/report_controller/schedules.rb
- spec/controllers/miq_ae_tools_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6105
This is another PR with use of `copy_params_if_present` method in some controllers.
With `copy_params_if_present`, we improve functionality (remove `""` vs `nil` issues and bad response of _Add/Save_ buttons) or we simplify the code.
Similar PRs/changes:
https://github.com/ManageIQ/manageiq-ui-classic/pull/6152
#6139
#5815
https://github.com/ManageIQ/manageiq-ui-classic/commit/d3c3878c7cde6f682c6e25928b7c90a4c01b664f#diff-956e46b33fb5307990c4e1a4b5fd86ccR1267
> Use copy_params_if_present in report, miq_policy and pxe controllers

- app/presenters/tree_builder.rb
The optimize menu item has been removed, from that the utilization has been moved to overview. The generic object definitions has been added into the wrong place and mapped to a treebuilder that has nothing to do with it. :hamster: 
@miq-bot add_label ivanchuk/no, trees, technical debt
> Reorganize the TreeBuilder tree name mapping to the actual state

- app/controllers/mixins/more_show_actions.rb
- app/views/layouts/_tl_show.html.haml
- spec/controllers/ems_infra_controller_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1732517
1. Add infra provider
2. Navigate to Timelines page of the infra provider
No title on the page
Should be a title on the page
- adds `@title` to timeline template
- sets specific `title` to be consistent with timelines in VM/instance controllers
**Before**
**After**
@miq-bot add_label bug, ivanchuk/yes, hammer/no, changelog/yes
> Timelines title

- app/controllers/catalog_controller.rb
- app/javascript/components/copy-catalog-form/copy-catalog-form.jsx
- app/javascript/components/copy-catalog-form/copy-catalog-form.schema.js
- app/javascript/spec/copy-catalog-form/copy-catalog-form.spec.js
When catalog item is copied, the default behavior does
not copy tags. This PR adds an option of copying tags.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1740399
Depends on #19206
@miq-bot add_label enhancement, ivanchuk/yes, changelog/yes
> Add option of copying tags

- app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js
- app/controllers/mixins/ems_common/angular.rb
- app/views/layouts/angular/_multi_auth_credentials.html.haml
- spec/controllers/ems_cloud_controller_spec.rb
- spec/controllers/mixins/ems_common/angular_spec.rb
- spec/javascripts/controllers/ems_common/ems_common_form_controller_spec.js
Finishing work from https://github.com/ManageIQ/manageiq-ui-classic/pull/5621
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1631845
---
This is support PR for AWS Security Token Service's "[assume role](https://stackoverflow.com/a/50083442/4393476)" feature.
Basically, it's just a new field on form, and related validation and saving code changes.
Here is the primary PR with technical info: https://github.com/ManageIQ/manageiq-providers-amazon/pull/538
Related core repo PR: https://github.com/ManageIQ/manageiq/pull/18810
---
Changes since https://github.com/ManageIQ/manageiq-ui-classic/pull/5621:
* renamed `service_account` to `assume_role` to prevent collisions with GCE `service_account`,
* reordered commits to get rid of past experiments,
* added `{}` around hash in an array
> Amazon - support Assume Role ARN

- app/javascript/packs/component-definitions-common.js
- app/stylesheet/application-webpack.scss
- package.json
~~Depends on https://github.com/ManageIQ/react-ui-components/pull/145~~
In https://github.com/ManageIQ/react-ui-components/pull/132, we removed some styles which were still needed to create `dist/tagging.css` in react-ui-components, causing a travis failure here.
A temporary fix removing the need for that css was merged in https://github.com/ManageIQ/manageiq-ui-classic/pull/6171,
this PR reverts that (reintroduces `dist/tagging.css`),
and updates react-ui-components version to the one with https://github.com/ManageIQ/react-ui-components/pull/145.
Cc @Hyperkid123 , @karelhala
> Fix tagging css

- app/controllers/ops_controller/settings/common.rb
- spec/controllers/ops_controller/settings/common_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1749841
_Save_ button did not respond properly on changes in _NTP Servers_ section while editing an existing _Zone_. Let me explain the fix. [Here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/ops_controller/settings/common.rb#L20), the same as in other screens, values of `@edit[:new]` and `@edit[:current]` are crucial for detecting changes in the fields and response of _Add/Save_ buttons. In our case, we need to take care of `@edit[:new][:ntp]` and `@edit[:current][:ntp]`.
Beginning of editing a Zone: 
```
[18] pry(#<OpsController>)> @edit[:new][:ntp]
=> {:server=>["0.pool.ntp.org", "1.pool.ntp.org", "2.pool.ntp.org"]}
[19] pry(#<OpsController>)> @edit[:current][:ntp]
=> {:server=>["0.pool.ntp.org", …
```
> Make Save button respond properly on changes in NTP Servers section while editing a Zone

- app/helpers/ems_storage_helper/textual_summary.rb
This way it catches ManageIQ::Providers::Openstack::StorageManager::CinderManager and ManageIQ::Providers::StorageManager::CinderManager. Not just the later.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650082
Storage -> Block Storage -> Managers -> click on non-Openstack storage provider or OpenStack Swift Provider
Before there's Cloud Volume Types in Relationships (last line):
After there's no Cloud Volume Types in Relationships:
For OpenStack Cinder Manager:
Before/After:
*Zone is missing because this Provider was added via console and it's missing some stuff like a zone*
If you have no `CloudVolumeType` for OpenStack. Do this in console:
```
ems_id = ManageIQ::Providers::OpenStack::StorageManager::CinderManager.first.id
cvt = CloudVolumeType.create(:name => "name", :description …
```
> Use kind_of? instead of String comparison

- app/controllers/miq_request_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746386
Create a Role that has Automate/Requests checked in feature tree but NOT  Services/Request. Create a group with this Role. Create a User with this group. Switch to this user. Go to Automation -> Automate -> Requests.
Before:
After:
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/4752 . After that change it never went through `index` (that is always allowed because `miq_request_index` is not a feature) sets `@request_tab` correctly before another `check_privileges`. The tab (`?typ=host`) that would have the same problem was removed in https://github.com/ManageIQ/manageiq-ui-classic/pull/4169 .
@miq-bot add_label wip, bug, blocker
> Set typ of tab before checking privilegies

- app/controllers/pxe_controller/iso_datastores.rb
- app/presenters/tree_builder_iso_datastores.rb
Analogously with the other trees, getting rid of redundant nodes. In the ISO datastore tree I think there's no need for the ISO images folder that has not siblings and only the ISO images as children. Also there's no extra functionality when it is selected, it just displays the same info as the datastore parent. The icon is being replaced to represent the ISO image much better in https://github.com/ManageIQ/manageiq-decorators/pull/19
**Before:**
**After:**
@terezanovotna can you please take a look
@miq-bot add_label ivanchuk/no, technical debt, trees, ux/review
> Drop the unnecessary ISO images hash folder from the ISO tree

- app/controllers/miq_request_controller.rb
In https://github.com/ManageIQ/manageiq-ui-classic/pull/4169 tab menu Infrastructure/Requests was removed. This PR removes few bits that were left behind.
@miq-bot add_label technical debt, ivanchuk/no, wip
> Remove options for host that has been removed

- spec/presenters/tree_node/pxe_image_type_spec.rb
Fixing travis after https://github.com/ManageIQ/manageiq-decorators/pull/20
@miq-bot add_label tests, ivanchuk/no
> Adjust spec for TreeNode::PxeImageType after the decorator icon change

- app/helpers/report_helper/editor.rb
on multi region DB we are not displaying tenant from other regions.
(1) and this PR fixes this in report editor of chargeback in filter tab.
it is possible because you can import chargeback report from other region with tenant filter with the other region - (2) in this case I am displaying ten from other region with info about region.
**before**
**after**
on pictures:
tenants from current region:
TENIS
tenants from other region (71): 
XXXXA
XXXXB
XXXXD
Links
-----
* related to https://bugzilla.redhat.com/show_bug.cgi?id=1750800
cc @gtanzillo
> Display tenant only from current region

- app/controllers/report_controller/reports/editor.rb
> Display tag  better with missing category in report editor

- app/assets/javascripts/controllers/tree_view_controller.js
- app/controllers/automation_manager_controller.rb
- app/controllers/miq_policy_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/provider_foreman_controller.rb
- app/controllers/service_controller.rb
- app/controllers/storage_controller.rb
- app/controllers/vm_cloud_controller.rb
- app/controllers/vm_infra_controller.rb
- app/controllers/vm_or_template_controller.rb
- app/javascript/components/breadcrumbs/on-click-functions.js
- app/javascript/spec/breadcrumbs/on-click-functions.spec.js
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
- spec/controllers/vm_infra_controller_spec.rb
As we decided in https://github.com/ManageIQ/manageiq-ui-classic/issues/5620#issuecomment-522948905
This PR is onholding https://github.com/ManageIQ/manageiq-ui-classic/pull/5776, https://github.com/ManageIQ/manageiq-ui-classic/pull/6056
- Removes the tree path from breadcrumbs
- Only selected item is shown
- Accordion serves as a link to root
- Removes all obsolete options for breadcrumbs
New breadcrumb structure
`[MENU]` > `[ACCORDION (root link)]` > `[ITEM (tree node text, name, etc.)]`
When some action
`[MENU]` > `[ACCORDION]` > `[ITEM]` >` [ACTION (right_cell_text, title)] `
**How it works**
1. First visit of the page
The tree is built, the selected node is found and its text is used.
2. Clicking in breadcrumbs/tree
`tree_select` receives ID of the node and TEXT, the …
> Remove tree path from breadcrumbs

- app/views/vm_common/_reconfigure.html.haml
This PR fixes some UI inconsistencies in the reconfigure screen:
- Validation for add disk / resize disk was diffentent. For the add disk no size validation was available. Now the validation is in sync with de resize disk. (1 MB - 2 TB) Also changing the unit (GB/MB) now updates the size
- removed unused change events (no JS functions are available `vm.hdChanged()`)
- move add disk to bottom of table to be inline with add NIC. Also when a new disk is added it will appear on the bottom.
See screenshot of the changed validation:
> Reconfigure: Fix UI inconsistentsies add disk

- app/controllers/mixins/breadcrumbs_mixin.rb
- app/controllers/optimization_controller.rb
- app/controllers/pxe_controller.rb
- app/views/layouts/_breadcrumbs.html.haml
- spec/controllers/mixins/breadcrumbs_mixin_spec.rb
- fixes breadcrumbs after pressing cancel and selecting in trees - breadcrumbs won't show headers of action after the cancel, save, add or selecting in a tree, there is no need to clear `sb :action` anymore
- fixes breadcrumbs in PXE menu section - breadcrumb mixin accepts 'right_cell_text' as a local parameter from presenter
**Before**
**After**
@miq-bot add_label breadcrumbs, changelog/no, hammer/no, compute/infrastructure, bug
> Fix cancel, save and select_tree actions in breadcrumbs and title in PXE menu section

- app/helpers/application_helper/toolbar/x_vm_center.rb
- app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
Before:
After:
@miq-bot add_label enhancement, compute/infrastructure
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1506716
> Added Snapshot button to Configuration menu

- app/controllers/catalog_controller.rb
- app/controllers/mixins/breadcrumbs_mixin.rb
Because of reworked breadcrumbs (https://github.com/ManageIQ/manageiq-ui-classic/pull/6073, https://github.com/ManageIQ/manageiq-ui-classic/pull/6193), this option is not needed anymore.
**How to test it**
1. `Services` > `Catalog` > `Catalog Items`
2. Select one
3. `Policy` > `Edit tags`
4. You will see breadcrumbs like ```Services Catalogs > Catalog Items > Create RDS Instance > Editing My Company Tags for "Service Catalog Items"```
@miq-bot add_label technical debt, ivanchuk/yes, breadcrumbs
> Remove :hide_special_item from breadcrumbs

- app/controllers/report_controller.rb
- app/controllers/report_controller/dashboards.rb
- app/presenters/tree_builder.rb
- app/presenters/tree_builder_report_dashboards.rb
- app/presenters/tree_node/miq_widget_set.rb
- app/views/report/_db_list.html.haml
- spec/controllers/miq_report_controller/trees_spec.rb
- spec/presenters/tree_node/miq_widget_set_spec.rb
Except of the root node and the virtual folder for `All Groups` all nodes have a matchine record. First of all, the `MiqWidgetSet` prefix has been added to the `TreeBuilder::X_TREE_NODE_PREFIXES`. To avoid errors, the `get_node_info` logic has been altered accordingly. Then I was able to convert the default dashboard hash node to a mapped record node with some additional alterations in the `get_node_info`. 
The area in general is a big :spaghetti:, it relies a lot on the `@sb[:nodes]` and it would need additional refactoring, but that's out of the scope of my current work in https://github.com/ManageIQ/manageiq-ui-classic/issues/5620
Depends on: https://github.com/ManageIQ/manageiq/pull/19180
@miq-bot add_label …
> Eliminate unnecessary hash nodes in the TreeBuilderReportDashboards

- app/assets/javascripts/miq_application.js
- spec/javascripts/miq_application_spec.js
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1725927
Tagging pages do not trigger the abandon changes popup, when leaving the page. 
- adds a condition which checks if values in tagging reducer are changed
**Before**
**After**
@miq-bot add_label bug, ivanchuk/yes, tagging
> Add abandon changes popup to tagging pages

- app/controllers/miq_request_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1749953
Introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/3534
1. go to Services -> Requests
2. click on the Requester dropdown
Before: NOT sorted alphabetically 
After: sorted alphabetically 
Note:
I boosted number of requesters by
```diff
--- a/app/controllers/miq_request_controller.rb
+++ b/app/controllers/miq_request_controller.rb
@@ -368,7 +368,7 @@ class MiqRequestController < ApplicationController
def requesters_in_30_days
Rbac::Filterer.filtered(MiqRequest.where(:type       => MiqRequest::MODEL_REQUEST_TYPES[model_request_type_from_layout].keys,
-                                             :created_on => (30.days.ago.utc)..(Time.now.utc))).each_with_object({}) do |r, h|
+ …
```
> Sort Requester dropdown by label
