app/assets/javascripts/miq_explorer.js, app/controllers/mixins/breadcrumbs_mixin.rb, app/controllers/mixins/generic_show_mixin.rb, app/controllers/ops_controller.rb, app/helpers/ops_helper/textual_summary.rb, app/presenters/explorer_presenter.rb, app/presenters/tree_builder_ops_rbac.rb, app/views/ops/_rbac_tenant_details.html.haml, config/routes.rb, product/views/ExtManagementSystem-nested_providers.yaml, product/views/MiqAeDomain-nested_ae_namespaces.yaml, product/views/ServiceTemplate-nested_service_templates.yaml, spec/controllers/mixins/generic_show_mixin_spec.rb, spec/controllers/ops_controller_spec.rb, spec/helpers/ops_helper/textual_summary_spec.rb, spec/views/ops/_rbac_tenant_details.html.haml_spec.rb
**RFE:** https://bugzilla.redhat.com/show_bug.cgi?id=1678124
Details about some changes: https://github.com/ManageIQ/manageiq-ui-classic/pull/6060
Tracking issue: https://github.com/ManageIQ/manageiq/issues/18734
**Depends on:** (all merged)
https://github.com/ManageIQ/manageiq/pull/18733
https://github.com/ManageIQ/manageiq/pull/18735
https://github.com/ManageIQ/manageiq-automation_engine/pull/318
https://github.com/ManageIQ/react-ui-components/pull/129
https://github.com/ManageIQ/manageiq/pull/19071
This PR includes converting Tenants details page to **textual summary** page. We need this to be able easily to add _Relationships_ table with related _Services, Automate Domain_ and _Providers_ info. This PR also adds this.
**Where:**
_Configuration :wheel_of_dharma: > Access Control_ …
=> Convert Tenants details page to textual summary and add Relationships with Services, Automate Domain and Providers

app/presenters/tree_builder_automate_entrypoint.rb, app/presenters/tree_node/miq_ae_node.rb, spec/controllers/miq_ae_class_controller_spec.rb
I'm trying to clean up our `TreeBuilder#override` methods a little and this is bothering me a lot. The fqname is a crucial part of any automate node and I'd rather set it globally. 
@miq-bot add_label refactoring, technical debt, ivancuk/no, automation/automate
This affects the entry point selection in the dialog editor and also the embedded method selection in the automate explorer so I'd like to ask @romanblanco and @pkomanek to test it thoroughly.
=> Include fqname in automate 🌳nodes globally instead of overriding

app/presenters/tree_node/node.rb
Instead of the dynamically defined accessor methods inside `set_attribute`, we can define them statically with `attr_accessor`. As the `icon` and `image` attributes have implicit dynamic values, their reader method has to stay custom and the `attr_writer` can be used instead of an explicit writer method. After this change the methods can be dropped and if they contain a static value, they can be moved into `set_attribute` calls.
This allows us to use these writer methods in the `TreeBuilder#override` definitions in the future when we are no longer dealing with hashes when overriding.
@miq-bot add_label ivanchuk/no, refactoring, trees, enhancement
=> Replace implicit TreeNode::Node methods with accessors/writers

app/assets/javascripts/services/event_notifications_service.js
When having a storm of notifications, they can take over a significant amount of the screen. This change throttles the amount of toasts by maximizing one toast in 0.5 second and also doesn't allow displaying more than 3 toasts by always removing the oldest one.
@miq-bot add_reviever @martinpovolny 
@miq-bot add_reviever @himdel 
@miq-bot add_label hammer/yes, ivanchuk/yes, bug, ux/review
@terezanovotna this will need some testing from you on a real setup with some fake notifications that can be created by:
```ruby
Notification.take(10).each { |n| n.dup.save; sleep 0.25 }
```
**Before:**
**After:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639473
=> Throttle notification toast messages and display only 3 at most

app/controllers/cloud_volume_controller.rb, app/helpers/application_helper/button/volume_attach.rb, app/helpers/application_helper/toolbar/cloud_volume_center.rb, spec/helpers/application_helper/buttons/volume_attach_spec.rb
This PR fixes the Cloud Volume detail toolbar so that the Attach Volume button accounts for the volume status and greys out for unavailable volumes. It also fixes the Cloud Volume list toolbar so that selecting an unavailable volume flashes a message rather than continuing on to the attachment form.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653062
=> Improve volume attachment user experience

app/controllers/ops_controller/settings/common.rb, spec/controllers/ops_controller/settings/common_spec.rb
Allows custom Worker threshold values being entered in Advanced Settings to be correctly displayed in the Workers tab drop downs.
Prior to this pull request the first value of the drop down was selected.
Screenshot:
@miq-bot add_labels bug, settings, hammer
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1715633
=> [HAMMER] Fix Worker threshold drop downs when using custom values

app/presenters/tree_node/node.rb
Missed this one from https://github.com/ManageIQ/manageiq-ui-classic/pull/6208, the change is harmless as the `selected` attribute is never being set yby the node itself. However, it will be significant when the `TreeBuilder#override` methods will [start](https://github.com/ManageIQ/manageiq-ui-classic/pull/6220) using it. Also the `delete_if` is no longer necessary in `to_h` as we have the `compact`. 
@miq-bot add_label enhancement, technical debt, ivanchuk/no, trees
=> Add the selected accessor to TreeNode::Node and clean up its to_h

app/controllers/ops_controller/ops_rbac.rb, spec/controllers/ops_controller/ops_rbac_spec.rb
This PR removes unnecessary code related to **adding/editing a Group or Role** because in older fields like in our cases and validation is usually provided AFTER clicking on _Add/Save_ button - the same as in other screens => more consistency. _Add/Save_ button respond now on any changes, and not also on the information if all the required fields are set.
This PR also fixes displaying extra flash message (_Description can't be blank_) which accidentally appears if we fill in only Description and click on _Add_ button, while adding new Group. Caused by: https://github.com/ManageIQ/manageiq-ui-classic/pull/3164 The solution is setting Description, Role and/or Tenant (if it was chosen) even if `rbac_group_validate?` was not `true`. This issue is reproducible after applying the first commit …
=> Remove unnecessary validation before clicking on Add/Save while adding/editing a Group or Role

app/assets/javascripts/miq_application.js, app/assets/javascripts/miq_explorer.js, app/javascript/components/taggingWrapper.jsx, app/javascript/forms/data-driven-form.jsx, app/javascript/miq-redux/form-reducer.js, app/javascript/miq-redux/store.js, app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js, app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap, app/javascript/spec/catalog-form/catalog-form.spec.js, app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap, app/javascript/spec/cloud-network-form/cloud-network-form.spec.js, app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap, app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js, app/javascript/spec/copy-catalog-form/copy-catalog-form.spec.js, app/javascript/spec/copy-dashboard-form/copy-dashboard-form.spec.js, app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap, app/javascript/spec/flavor-form/flavor-form.spec.js, app/javascript/spec/forms/data-driven-form.spec.js, app/javascript/spec/helpers/mountForm.jsx, app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js, app/javascript/spec/orchestration-template/orchestration-template-form.spec.js, app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap, app/javascript/spec/pxe-servers-form/pxe-server-form.spec.js, app/javascript/spec/service-dialog-from-form/service-dialog-from-form.spec.js, app/javascript/spec/service-form/service-form.spec.js, app/javascript/spec/set-ownership-form/set-ownership-form.spec.js, app/javascript/spec/vm-server-relationship-form/vm-server-relationship-form.spec.js, app/javascript/spec/workers-form/workers-form.spec.js, config/jest.setup.js
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1725927
DDF components are missing a option to tell the Abandon changes popup to show up. This PR connects all Data driven forms to redux and store pristine of the form in its store.
The same thing should be done for Tag component.
**Before**
**After**
@miq-bot add_label bug, ivanchuk/yes, react
=> Add abandon changes popup to data driven forms components

app/views/static/generic_object/generic_object_table.html.haml
This PR replaces a div with a button tag for Delete buttons so that tabbing works properly
https://bugzilla.redhat.com/show_bug.cgi?id=1519494
=> Add button tag to generic object form

app/controllers/infra_networking_controller.rb
This BZ didn't have a 'needinfo' on it for me so it kinda slipped through the cracks until I was directly notified by Dennis. This simple change should at least get past the `ArgumentError` that the BZ reports, but I currently don't have a full stable environment to test if the options sent in would be correct or not for actually displaying the dialog. @himdel Can you take a look please?
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1685555
~@miq-bot add_reviewer @himdel @h-kataria~ 
@miq-bot add_label bug, ivanchuk/yes
=> Fix ArgumentError with set_custom_button_dialog_presenter

app/presenters/tree_builder.rb, app/presenters/tree_builder_alert_profile_obj.rb, app/presenters/tree_builder_automate.rb, app/presenters/tree_builder_automate_catalog.rb, app/presenters/tree_builder_automate_entrypoint.rb, app/presenters/tree_builder_belongs_to_hac.rb, app/presenters/tree_builder_belongs_to_vat.rb, app/presenters/tree_builder_compliance_history.rb, app/presenters/tree_builder_ems_folders.rb, app/presenters/tree_builder_infra_networking.rb, app/presenters/tree_builder_network.rb, app/presenters/tree_builder_resource_pools.rb, app/presenters/tree_builder_roles_by_server.rb, app/presenters/tree_builder_servers_by_role.rb, app/presenters/tree_builder_smartproxy_affinity.rb, app/presenters/tree_builder_storage_adapters.rb, app/presenters/tree_builder_tenants.rb, app/presenters/tree_builder_utilization.rb, spec/presenters/tree_builder_alert_profile_obj_spec.rb
There's a controversial `TreeBuilder#override` method that is intended to change nodes after they are being built. This method has been called from `TreeBuilder#x_build_single_node` on individual hashes that come out from `TreeNode::Node#to_h`.
The final result of the `x_build_single_node` has been not changed, so the method still produces the same output. However, the `override` method is now being called on the `TreeNode::Node` object directly and it is being converted to a hash AFTER this. This allows us to have a cleaner dataflow and eventually the hash conversion can be pushed up to the highest level, leaving us with a pure object tree.
As the `override` happened after the conversion, the resulted node had to comply with the JSON specification of the tree. This forced us to …
=> Call TreeBuilder#override on TreeNode objects instead of hashes

app/controllers/mixins/generic_button_mixin.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6234
This PR fixes error while performing Power operations on Instances of a key Pair (see the issue).
In `handle_vm_buttons` method, called in `button` [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/generic_button_mixin.rb#L56), `process_vm_buttons` is [called](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/generic_button_mixin.rb#L9). And if we chose _Start_ operation on a selected Instance, `startvms` is [called](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller/ci_processing.rb#L932), obviously. In this method, `generic_button_operation` is called. If the selected feature/operation is not …
=> Avoid calling render multiple times for Power operations on Instances of a Key Pair

app/views/security_group/new.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1740647
1. Navigate to 'Networks -> Security Groups -> Add New Security Group'
2. Check the main entities Network Management Provider, Security Group Information and Placement
3. 'Placement' entity is not aligned
Before:
After:
=> Fixed placement alignment.

app/controllers/service_controller.rb, spec/controllers/service_controller_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1741050
1. Create a Generic object associated with services
2. Navigate to Service > My Services > Generic [Instance] 
3. breadcrumb will show like `Services > My services > Services> Active Services > service_22`
4. Click on Active Services
Link is broken unable to navigate with breadcrumb
it should nav to all active services.
- Explorer controller behaves like non-explorer when service is going to `generic_objects instances` list
**Before**
**After**
@miq-bot add_label bug, ivanchuk/yes, breadcrumbs, services
=> Fix breadcrumbs on service/generic_objects

app/assets/stylesheets/application.css, app/assets/stylesheets/service_dialogs.css, app/views/miq_ae_customization/_dialog_import_export.html.haml
This PR removes the unneeded custom styling  on the service dialog import/export screen
Old
New
=> remove custom styling from svc dialog import/export

app/assets/stylesheets/angular.css
The PR consolidates styling used in angular forms
=> angular form css cleanup

app/assets/javascripts/components/generic_object/generic-object-definition-toolbar.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744478
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1753289
Go to Automation -> Automate -> Generic Objects -> delete a custom button (delete a custom button group to make sure it works as well)
Before:
or
After:
if you see 404 error during deleting it's related to this https://bugzilla.redhat.com/show_bug.cgi?id=1753388 and will be fixed in separated PR #6230 .
@miq-bot add_lable wip, bug, generic objects, ivanchuk/yes
=> Fix missing name of deleted GOD Button/ButtonGroup

app/presenters/tree_builder_ops_rbac.rb, spec/presenters/tree_builder_ops_rbac_spec.rb
Issue can happen when user is using tag filtering but tenant is not tagged.
=> Add RBAC filter for tenant tree

app/controllers/service_controller.rb, app/javascript/components/service-form/service-form.schema.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746367
1. Create any Catalog Item and assign it to some Catalog
2. Order it
3. Go to Services->My Services
4. Choose Configuration->Edit this Service
5. Click Cancel button
Before:
After:
=> Make service edit description field not required

app/controllers/mixins/actions/vm_actions/reconfigure.rb
When I add or edit a vlan in Reconfigure Network Adapter, the results are unorganized. I suggest to sort these vlans alphabetically for clarity.
=> Sort vlans in reconfigure network adapters

app/helpers/application_helper/toolbar/firmware_registries_center.rb, app/helpers/application_helper/toolbar/firmware_registry_center.rb
JS generated by ruby does not get compiled by webpack,
so toolbars using an arrow function will only work in browsers supporting arrow functions.
Introduced in #5929 , adding ivanchuk/yes.
Cc @miha-plesko
=> Firmware toolbar - don't use arrow functions in non-compiled JS

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js, app/controllers/miq_request_controller.rb, app/helpers/application_helper/button/miq_request_copy.rb, app/views/miq_request/prov_edit.html.haml, app/views/shared/dialogs/_dialog_user.html.haml, config/routes.rb, spec/javascripts/controllers/dialog_user/dialog_user_controller_spec.js, spec/routing/catalog_routing_spec.rb
Enable Copy feature for ServiceRequests.
When buttons is pressed it shows new dialog, but without values filled in the request. It uses default values from automate. 
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1689642
You need https://github.com/ManageIQ/manageiq/pull/18859
1. Make a Service request
Go to Services -> Requests -> Select Service Request -> Copy Service
=> Enable Copy feature for ServiceRequests

app/presenters/tree_builder.rb, app/presenters/tree_node/node.rb
Added a readable `nodes` attribute to `TreeNode::Node#node` that is able to store the children of a given node. Also implemented the `lazy` attribute that transforms to the `lazyLoad` key when converting to hash. These two attributes allow us to directly modify the `TreeNode::Node` object in ˙TreeBuilder#x_build_node` and to get rid of `TreeBuilder#x_build_single_node`. Also the final conversion to hash can now happen as the very last thing.
@miq-bot add_label ivanchuk/no, trees, refactoring
=> Operate with the TreeNode::Node in TreeBuilder#x_build_node

app/javascript/components/code-editor/index.js
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1754543
The issue here was with passing anonymous function to `FieldProvide`. It did not have any reference to it and was creating new instance of that component instead of updating its props. That caused loosing the focus of the field. By wrapping the children and naming the component the issue is fixed.
I also removed the value from state and let parent component handle it.
=> Fixed lost focus on code editor after first state update.

app/controllers/vm_common.rb
why:
-  we are using syntax `with` rather with parameter `with_PARAMETER(PARAMETER)`
- we have already existing and more readable scope for it : `active`
removal with_ems from core https://github.com/ManageIQ/manageiq/pull/19345
=> Use active scope for vms in VmCommon

app/controllers/application_controller/current_user.rb, app/controllers/application_controller/miq_request_methods.rb, app/controllers/application_controller/performance.rb, app/controllers/miq_ae_class_controller.rb, app/controllers/miq_policy_controller/miq_actions.rb, app/controllers/ops_controller/settings/label_tag_mapping.rb, app/controllers/ops_controller/settings/tags.rb, app/controllers/report_controller/reports/editor.rb, app/controllers/report_controller/schedules.rb, app/services/user_validation_service.rb, spec/controllers/application_controller/performance_spec.rb, spec/controllers/report_controller_spec.rb
The find_by_* methods defined in manageiq repo has conflicts with
rails dynamic finding and now they have been changed to lookup_by_*.
Switching the callers in this repo to the lookup_by_* methods.
Depend on https://github.com/ManageIQ/manageiq/pull/19313
@miq-bot add_label ivanchuk/no, refactoring
=> Switch find_by_* to lookup_by_*

app/controllers/mixins/ems_common/angular.rb, spec/controllers/ems_cloud_controller_spec.rb
validation via the queue was added in https://github.com/ManageIQ/manageiq-ui-classic/issues/1580,
but explicitly left some cases to try connecting directly.
This is not really desirable as the UiWorker is not guaranteed to be able to do that in general.
we only talked about this with @agrare and @gprocunier on gitter [September 24, 2019 8:30 PM](https://gitter.im/ManageIQ/manageiq/ui?at=5d8a7cdda38dae3a63afba5a),
I have not actually tested this with any (or all) providers.
=> Provider validate - don't attempt to directly connect from the UI

app/controllers/ops_controller/settings/zones.rb, spec/controllers/ops_controller/settings/zones_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1749834
This PR simply 'moves' validation of _Password_ and _Verify Password_ fields while editing Zone to be provided AFTER clicking on _Save_ button => more consistency with other screens.
This PR also allows us to be able to reset ANY change (while editing Zone), also changes in  _Password_ and _Verify Password_ fields - this was not possible because with [this](https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Reset_changes_editing_Zone_pwd_verifypwd?expand=1#diff-46d9c2a2602cc981686abc11859bed16L96) and [this](https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Reset_changes_editing_Zone_pwd_verifypwd?expand=1#diff-46d9c2a2602cc981686abc11859bed16L100) _Save_ and _Reset_ buttons were …
=> Allow resetting changes while editing Zone's Password or Verify Password fields

app/controllers/application_controller.rb, app/controllers/configuration_controller.rb, app/helpers/configuration_helper.rb, app/views/configuration/_ui_1.html.haml, spec/controllers/ems_cloud_controller_spec.rb, spec/controllers/ems_container_controller_spec.rb, spec/controllers/host_controller_spec.rb
As discussed in https://github.com/ManageIQ/manageiq-ui-classic/issues/6069 and removed in https://github.com/ManageIQ/manageiq-decorators/pull/21, these settings now don't make sense, so they can be removed.
**Before:**
**After:**
Depends on: https://github.com/ManageIQ/manageiq-decorators/pull/21
Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/6252
@miq-bot add_label ivanchuk/no, cleanup, pending core
@miq-bot add_reviewer @martinpovolny
=> Remove the possibility to chose of quadicon/single quad in GTLs

app/views/ops/_rbac_role_details.html.haml
this option `Access Restriction` works with model which have `OwnershipMixin` included so I am updating the label according to current state.
before
after
=> Update Access Restriction to current state in role detail

app/controllers/mixins/breadcrumbs_mixin.rb, app/controllers/optimization_controller.rb, spec/controllers/mixins/breadcrumbs_mixin_spec.rb, spec/controllers/optimization_controller_spec.rb
Refactores `optimization_controller` to use default breadcrumbs methods
The optimization_controller overrides the whole breadcrumbs logic and uses its own. That creates inconsistency. 
However, there is no need to do it. The only difference within this controller is the structure:
**Standard**
`SHOW_LIST > SHOW > ACTION`
**Optimization**
`SHOW_LIST > SHOW_LIST > SHOW`
Breadcrumbs mixin do not show specific breadcrumbs when a user is on `SHOW` action, because all info it needs is in `@title`, so It doesn't use info provided in `:record_info` (= `@record` or whatever is set to be used.)
So, I provided an option to `breadcrumb_mixin` which can enforce to use `:record_info`, the option is already used in explorer controller to do the same things: `:include_record`
=> Refactor optimization_controller to use default breadcrumbs methods

app/services/ems_dashboard_service.rb, spec/services/ems_dashboard_service_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1632750
=> Fix error on Cloud Provider Dashboard

app/assets/stylesheets/application.css, app/assets/stylesheets/data_driven_forms_overrides.scss, app/javascript/forms/mappers/formsFieldsMapper.jsx
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1757328
Default z-index value on select menu was to low for certain elements.
- added className prefix form miq select component
- added style override for select menu z-index
=> Fixed low z-index on ddf select menu.

app/controllers/application_controller/policy_support.rb, app/controllers/application_controller/tags.rb, app/controllers/host_controller.rb, app/controllers/mixins/actions/vm_actions/evacuate.rb, app/controllers/mixins/actions/vm_actions/live_migrate.rb, app/controllers/mixins/actions/vm_actions/ownership.rb, app/controllers/mixins/actions/vm_actions/retire.rb, lib/report_formatter/converter.rb
The result of the `records2table` is never used as we fetch the GTL contents in a separate `report_data` request. Therefore, this method generates data that's never used, throttling the performance of the rendered page. I found this while I was trying to smuggle in some extra information from the policy simulation results to the report data, but failed.
@miq-bot add_reviewer @lpichler 
@miq-bot add_reviewer @kbrock 
@miq-bot add_label cleanup, technical debt, ivanchuk/no, cloud intel/reporting
=> Completely remove the records2table method as its obsolete

app/controllers/mixins/actions/vm_actions/evacuate.rb, app/controllers/mixins/actions/vm_actions/live_migrate.rb, app/controllers/mixins/actions/vm_actions/retire.rb
These 3 screens have list view unlike the other ones with grid view. We probably forgot about these when converting to `report_data`, so making them consistent now. You can access all three features (set retirement date, evacuate, migrate) on the `Cloud -> Instances` screen under `Lifecycle` when selecting at least two of them. 
Depends on: https://github.com/ManageIQ/manageiq-ui-classic/pull/6269
@terezanovotna please approve
@miq-bot add_label technical debt, ivanchuk/no, ux/review
=> Set grid type in GTLs on migrate, retire and evacuate screens

app/javascript/spec/automate-import-export-form/__snapshots__/import-datastore-via-git.spec.js.snap, app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js, app/javascript/spec/catalog-form/catalog-form.spec.js, app/javascript/spec/cloud-network-form/cloud-network-form.spec.js, app/javascript/spec/cloud-tenant-form/cloud-tenant-form.spec.js, app/javascript/spec/flavor-form/flavor-form.spec.js, app/javascript/spec/pxe-servers-form/pxe-server-form.spec.js
Thanks to changes in react-redux shallow renders do not need redux-store. Component also no longer triggers render inside redux store Provider.
After https://github.com/ManageIQ/manageiq-ui-classic/pull/6176 snapshots wrapped in redux provider did break.
Using normal shallow render from enzyme does fix the issue.
=> Fixed jest tests after React update

app/javascript/components/report-data-table.jsx, app/javascript/spec/async-credentials/async-credentials.spec.js, app/javascript/spec/copy-dashboard-form/copy-dashboard-form.spec.js, app/javascript/spec/flavor-form/flavor-form.spec.js, app/javascript/spec/forms/input-with-dynamic-prefix.spec.js, app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js, app/javascript/spec/orchestration-template/orchestration-template-form.spec.js, app/javascript/spec/pxe-servers-form/pxe-server-form.spec.js, app/javascript/spec/report-data-table.spec.js, app/javascript/spec/set-ownership-form/set-ownership-form.spec.js, app/javascript/spec/workers-form/workers-form.spec.js, config/jest.setup.js
closes #6271 
depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/6274
Uses async act wrapper around functional components state updates to remove this error from console:
```
Warning: An update to WorkersForm inside a test was not wrapped in act(...).
act(() => {
});
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
```
=> Async jest tests

app/helpers/network_port_helper/textual_summary.rb, spec/shared/controllers/shared_network_manager_context.rb
When Network Port has a device of type LoadBalancer, loading of details screen throws a missing route error because LoadBalancer views no longer exist in UI. This change shows LoadBalancer information as a static name instead of a link.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1758593
before
after
=> Fix loading of Network Port details screen

app/controllers/miq_ae_class_controller.rb, spec/controllers/miq_ae_class_controller_spec.rb
* do not pass an array when just one element is used
* better var names
* extract 2 more methods for readability and consistence
=> Automate explorer: split get_node_info, make variables more readable.

app/controllers/chargeback_controller.rb
@miq-bot add_label bug, ivanchuk/yes
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1759302
=> Test against the right accor when switching to chargeback reports

app/controllers/automation_manager_controller.rb, app/controllers/miq_ae_class_controller.rb, app/controllers/ops_controller.rb, app/controllers/provider_foreman_controller.rb, app/controllers/restful_redirect_controller.rb, app/helpers/application_helper.rb, app/views/miq_ae_class/show.html.haml, app/views/provider_foreman/show.html.haml, config/routes.rb, spec/controllers/automation_manager_controller_spec.rb, spec/controllers/miq_ae_class_controller_spec.rb, spec/controllers/ops_controller_spec.rb, spec/controllers/provider_foreman_controller_spec.rb, spec/controllers/restful_redirect_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/views/miq_ae_class/show.html.haml_spec.rb, spec/views/provider_foreman/show.html.haml_spec.rb
**RFE:** https://bugzilla.redhat.com/show_bug.cgi?id=1678124
**Depends on:** https://github.com/ManageIQ/manageiq-ui-classic/pull/5675 (merged)
Tracking issue: ManageIQ/manageiq#18734
---
This is a continuation of an RFE about converting Tenants details page to textual summary and adding _Relationships_ with _Services, Automate Domains_ and _Providers_. Specifically, this PR **makes Automate Domains and Providers clickable from the list** displayed thru Relationships table of Tenant's textual summary. After clicking on any Automate Domain or a Provider, we are redirected to the appropriate controller and details about the selected item are displayed.
For Automate Domains, I had to add new `show` method to `miq_ae_class` controller and to add a condition in application helper for choosing …
=> Make Automate Domains and Providers clickable from the list displayed through Tenant's Relationships

app/controllers/application_controller/compare.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6263
This PR fixes issue with displaying two _Cancel_ buttons after making changes in _Comparison Sections_ for Compare action. The core of the problem was that `@explorer` variable, which is needed [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/layouts/_compare.html.haml#L21), was not always properly set . The place where I put the condition was chosen the way that no matter which changes we make while comparing items, `@explorer` is properly set.
Note:
I've tested also other screens (explorer and non-explorer ones) under _Compute > Infra_ and also _Compte > Clouds_ and the changes work for them well.
---
**Before:**
**After:**
=> Display only one Cancel button for Compare action

app/controllers/application_controller/miq_request_methods.rb, app/controllers/ops_controller/ops_rbac.rb, app/javascript/components/taggingWrapper.jsx, package.json
Because of changes in https://github.com/ManageIQ/react-ui-components/pull/132 tagging wasn't working properly for Edit Group and Provisioning screens.
https://github.com/ManageIQ/react-ui-components/pull/132
https://github.com/ManageIQ/react-ui-components/pull/152 NEEDED TO BE MERGED FIRST
https://github.com/ManageIQ/manageiq-ui-classic/issues/5946
Compute -> Cloud -> Instance -> Lifecycle -> Provision -> Purpose tab
Cog wheel in the right corner -> Access Control -> Groups -> Edit some group
=> Fix tagging for Edit Group and Provisioning screens

product/views/Host.yaml, product/views/Storage.yaml
Hosts before:
Hosts after:
Datastores before:
Datastores after:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1573503
=> Add Provider to List view of Infra/Hosts and Infra/Datastores

app/controllers/ops_controller.rb, spec/controllers/ops_controller_spec.rb
Breadcrumbs are being generated when changing tabs in ops controller, that is unnecessary and it creates a redundant breadcrumb.
**Before**
**After**
@miq-bot add_label bug, breadcrumbs
=> Do not update breadcrumbs when ops/change_tab

app/controllers/network_router_controller.rb, app/helpers/application_helper/toolbar/base.rb, app/helpers/application_helper/toolbar/firmware_registries_center.rb, app/helpers/application_helper/toolbar/firmware_registry_center.rb, app/helpers/application_helper/toolbar/generic_object_definition_center.rb, app/helpers/application_helper/toolbar/generic_object_definitions_center.rb, app/helpers/application_helper/toolbar/network_router_center.rb, app/helpers/application_helper/toolbar/network_routers_center.rb, app/helpers/application_helper/toolbar/optimizations_center.rb, app/helpers/application_helper/toolbar/physical_storage_center.rb, app/helpers/application_helper/toolbar/physical_storages_center.rb, app/helpers/application_helper/toolbar/servicetemplate_center.rb, app/helpers/application_helper/toolbar/servicetemplates_center.rb, app/javascript/components/miq-toolbar.jsx, spec/controllers/network_router_controller_spec.rb
Buttons with `data` will either not work or run through old code that was left behind. Not calling API.
Introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/5997
One example is Network -> Network Routers -> summary or GTL page -> Configuration -> Delete
Before:
It works with "wrong" request on Networks Routers summary page
Or it doesn't work on Network Routers with GTL
After:
API is called and button works as expected
TODO:
@miq-bot add_label wip, ivanchuk/no, toolbars
=> Fix toolbar button with function

app/controllers/ops_controller/settings/common.rb
it is possible situation when saving subscription invoked but there is no any subscription to save and  params[:subscriptions] is nil, this lead to 
```FATAL -- : Error caught: [NoMethodError] undefined method prepare_subscriptions_for_saving'```
as described in BZ https://bugzilla.redhat.com/show_bug.cgi?id=1759511#c7
=> Fixed error when saving replication subscription with params[:subscriptions]been nil

app/controllers/configuration_job_controller.rb, app/helpers/application_helper/toolbar/configuration_jobs_center.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1749098
Go to Automation -> Ansible Tower -> Jobs
Before:
After:
- go to Automation -> Ansible Tower -> Jobs
- add some Jobs via console `ManageIQ::Providers::AnsibleTower::AutomationManager::Job.create!(:name => "name")`
- click Refresh
@miq-bot add_label ivanchuk/no, enhancement, changelog/no, toolbars
=> Add Refresh button to Ansible Tower Jobs page

app/javascript/components/miq-toolbar.jsx
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/6289
When clicking a button without `button.data.function` which is majority of buttons it explodes... 
Before:
After:
It works
@himdel please have a look. Thanks
@miq-bot add_label toolbars,
=> Check button.data isn't null

app/controllers/application_controller/compare.rb, app/views/layouts/listnav/_compare_sections.html.haml, spec/controllers/application_controller/compare_spec.rb, spec/views/layouts/listnav/_compare_sections.html.haml_spec.rb
Apply button should only be enabled when atleast one section is selected to compare/drift.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740406
before
after
This PR disabled Apply button if user deselects the last checked item on the screen, forces user to select at least one section to compare.
@hstastna please review/test
=> Disable "Apply" button when all sections are deselected.

app/views/shared/buttons/_ab_show.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740119
Go to Services -> Catalogs -> Catalog Items -> click on a Button
Object Attribute - Type is different for Show(first pic) and Edit(second pic). 
Before:
After:
@miq-bot add_label ivanchuk/yes, bug
=> Add missing ui-lookup to make Object Attribute consistent

app/presenters/tree_builder.rb, app/presenters/tree_node/hash.rb, app/presenters/tree_node/node.rb
Right now, the `TreeBuilder#x_build_node` is responsible for evaluating the expandedness of a given node. There's a way to predefine this in the `TreeNode::Node` using `set_attribute`, but it's not used to its full potential.
Here I'm extracting the expandedness evaluation based on the tree options/state into `TreeBuilder#expand_node?`. As this method is public, it's possible to call it from the `TreeNode::Node` in the `set_attribute(:expanded)`.
@miq-bot add_label refactoring, trees, ivanchuk/no
=> Move node expandedness evaluation into TreeNode::Node

app/assets/javascripts/components/generic_object/generic-object-definition.js, app/controllers/generic_object_definition_controller.rb, app/helpers/application_helper/toolbar/generic_object_definition_center.rb, app/helpers/application_helper/toolbar/generic_object_definitions_center.rb, app/presenters/tree_builder_generic_object_definition.rb, app/views/generic_object_definition/_show_god.html.haml, app/views/generic_object_definition/_show_list.html.haml, app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml, product/views/GenericObjectDefinition.yaml, spec/helpers/application_helper/toolbar_builder_spec.rb
In UI, except of the name _'Generic Object Definitions'_ we are also often using _'Generic Object Classes'_ for the same entity.
In code the entity is usually referred as _'Generic Object Definitions'_.
I'd prefer to have them united, therefore suggesting the changes.
If _'Class'_ does make more sense from the users point of view, let's unite at least the UI labels.
=> Renamed 'Generic Object Classes' to 'Generic Object Definitions'

app/controllers/host_aggregate_controller.rb, app/controllers/mixins/ems_common.rb, config/routes.rb, spec/controllers/host_aggregate_controller_spec.rb, spec/controllers/mixins/ems_common_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6227
---
Various errors occurred after displaying Host Aggregates from Relationships table of a Cloud Provider and providing selected **actions on a selected Host Aggregate**. Only tagging and Download worked for selected Host Aggregates. The same problems occurred for actions of Host Aggregates displayed in a list directly thru _Compute > Clouds > Host Aggregates_ and also actions provided from details page of a Host Aggregate. This PR fixes errors and allows us to provide selected actions.
**Editing Host Aggregate:**
The DoubleRenderError regarding editing a Host Aggregate was fixed by removing an extra unnecessary code [here](https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Actions_Cloud_Providers …
=> Allow editing and other actions on selected Host Aggregate

app/controllers/chargeback_controller.rb, app/views/chargeback/_tier_first_row.haml
Frontend change for https://github.com/ManageIQ/manageiq/pull/19382
=> ChargebackRateDetail: Apply gettext to model constants

app/helpers/application_helper/toolbar_builder.rb
The hard-coded exceptions for keeping the spinner up when buttons are
pressed where removed in the React rewrite. The behavior is now driven
by the keepSpinner option on a button. However this option was not
passed from the toolbar definition to the component. Fixing that now.
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/6295
=> Toolbar: pass keepSpinner to the toolbar.

app/assets/javascripts/components/generic_object/main-custom-button-form.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1753237
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/5166
1. Go to Automation -> Automate -> Generic Objects 
2. Create a custom button that has the "Request" as "ca", leave the "Message" as "create", the other fields are not as important
3. Edit the custom button request to "call_instance" 
4. Click to edit the custom button again
Before:
After:
@miq-bot add_label bug, generic objects, ivanchuk/yes
=> Fix edit of GOD custom button

app/assets/javascripts/miq_application.js, app/assets/javascripts/miq_global.js, app/views/layouts/_user_options.html.haml
Similar to #6065 (that one is during logout),
when changing group, ongoing requests can fail because their credentials are no longer valid.
Using the `logoutInProgress` mechanism introduced in #6065 to prevent redirects to the login screen during group change as well.
* also renamed the "Change to this Group" onclick handler from `miqToggleUserOptions` to `miqChangeGroup`, changed the group id from number to string, and enabled sparkle
* also removing `storeUserFeatures` (`localStorage.userFeatures`) - comes from https://github.com/ManageIQ/manageiq-ui-classic/pull/4756 - was postponed, no longer happening on login since https://github.com/ManageIQ/manageiq-ui-classic/pull/5164, and I'm changing the last caller now, so removing.
https://bugzilla.redhat.com/show_bug.cgi?id=1759291
=> Fix logout on group change

app/assets/javascripts/components/generic_object/generic-object-definition-toolbar.js, app/helpers/application_helper/button/basic.rb, app/helpers/application_helper/button/generic_object_definition_button_button_delete.rb, app/helpers/application_helper/button/generic_object_definition_button_button_group_delete.rb, app/helpers/application_helper/toolbar/generic_object_definition_button_center.rb, app/helpers/application_helper/toolbar/generic_object_definition_button_group_center.rb, app/helpers/application_helper/toolbar_builder.rb, app/javascript/toolbar-actions/delete.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1753388
Go to Automation -> Automate -> Generic Objects - > delete a custom button(with or without Custom Button Group it shouldn't matter)
Actual result:
There's an error popup and message for a sec.  See Before pic.
Expected result:
No error message/popup. See After pic.
According to the BZ it happens in 70%. 
This fix should work for all possible delete actions on Generic Object Definition page. 
Before:
After:
@miq-bot add_label bug, generic objects, ivanchuk/yes, changelog/no, wip
Depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/6289
=> Change toolbar delete buttons for Button and Button Group to use generic code

app/controllers/application_controller/compare.rb, app/controllers/application_controller/explorer.rb, app/controllers/catalog_controller.rb, app/controllers/generic_object_definition_controller.rb, app/controllers/infra_networking_controller.rb, app/controllers/miq_ae_class_controller.rb, app/controllers/miq_ae_customization_controller.rb, app/controllers/miq_policy_controller.rb, app/controllers/mixins/manager_controller_mixin.rb, app/controllers/pxe_controller.rb, app/controllers/report_controller.rb, app/controllers/service_controller.rb, app/controllers/storage_controller.rb, app/controllers/vm_common.rb, app/helpers/application_helper.rb, app/helpers/application_helper/toolbar_chooser.rb
Cleaning up some missed history toolbar remnants and fixing the broken cancel buttons (Compare, Policy Simulation) caused by #6050.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6222
=> Fix cancel buttons and some history cleanup

app/controllers/vm_common.rb, spec/controllers/vm_common_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6263#issuecomment-543140001
This PR fixes issue with displaying two _Back_ buttons after making changes during Policy simulation. The core of the problem was that `@explorer` variable was not set and it should be set (to `true`) because we were in explorer screen. But still, why is knowing that we are in explorer screen so important? For our case mainly because we don't want to display 'other' _Back_ button which is usually displayed for non-explorer screens during Policy simulation. There's a check for this [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/vm_common/_policies.html.haml#L15). So if `@explorer` is not properly set, another _Back_ button is displayed.
I am fixing the issue by adding …
=> Display only one Back button for Policy simulation

app/views/ops/_rbac_user_details.html.haml
And one trailing whitespace fix.
Before:
After:
=> Fix password input length

app/javascript/components/miq-toolbar.jsx
In the Angular implementation the 'views' part of the toolbar is sent in 2x. Once separately and once together with the rest.
That logic was kept in the React implementation but now I am separating the two to simplify the logic inside the Toolbar component.
This is part of the work that is needed to fix: https://github.com/ManageIQ/manageiq-ui-classic/issues/6312
The problem is that exceptional handling of the `view_*` buttons later leads to the empty group. So I will be removing the exception from the `Toolbar` component in react-ui-component and move the special handling of view buttons closer to the source of the data.
To go before https://github.com/ManageIQ/react-ui-components/pull/155 (This PR can be merged separately, not the one to the react-ui-components).
~~To be rebased after …
=> Toolbar view separation

app/views/ops/_log_collection.html.haml
Manual backport of #6330 and #6341
Make both red hat dropbox and support tool read-only
https://bugzilla.redhat.com/show_bug.cgi?id=1765635
Note, there's still test files referencing the changed dropbox strings but #6330 passed tests and didn't include them.  If needed, we can do another upstream PR for master/hammer to get them:
```
02:38:05 ~/Code/manageiq-ui-classic (hammer_backport_6330_dropbox_out_support_tool_in) (2.6.5) - git grep "Red Hat Dropbox"
spec/javascripts/controllers/ops/log_collection_form_controller_spec.js:        depot_name: 'Red Hat Dropbox',
spec/javascripts/controllers/ops/log_collection_form_controller_spec.js:        vm.logCollectionModel.log_protocol = 'Red Hat Dropbox';
spec/javascripts/controllers/ops/log_collection_form_controller_spec.js: …
```
=> [HAMMER] Dropbox removed, in exchange for using support tool

app/views/ops/_log_collection.html.haml
Fix hammer/master difference problem with backport of #6330 and #6341
Note, master/ivanchuk uses ng-readonly not ng_readonly: https://github.com/ManageIQ/manageiq-ui-classic/pull/6341/files#diff-039cb5ab2b2ceac9b344828ef12bdd0aR33
=> [HAMMER] Fix hammer/master difference problem with backport of #6330 and #6341

app/controllers/application_controller/ci_processing.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6241
There was an issue with Datastores and SSA: The selected Datastore was not accessible while performing SSA from the list of Datastores of selected Datastore Cluster.
**Details:**
In `generic_button_operation` method, called by `scanstorage` after clicking on _Perform SmartState Analysis_ toolbar button, `screen_redirection` is called. However, in this method, logic for `@lastaction` different than `"show_list"` is missing ([see](https://github.com/hstastna/manageiq-ui-classic/blob/master/app/controllers/application_controller/ci_processing.rb#L679)). The result is that it calls `show` instead of `show_list` [here](https://github.com/hstastna/manageiq-ui-classic/blob/master/app/controllers/application_controller/ci_proce …
=> Allow performing SSA on Datastores in Datastore Clusters accordion

app/javascript/spec/toolbar/__snapshots__/miq-toolbar.spec.jsx.snap
Fixes travis failure
~~Probably just cached `yarn.lock` file, or~~ some dependency's update -> It comes from ManageIQ/react-ui-components#157
In UI toolbars seems OK.
@martinpovolny
=> Update toolbar snapshots

.eslintrc.json, app/javascript/.eslintrc.json, package.json
I eagerly removed babel-eslint as unused in https://github.com/ManageIQ/manageiq-ui-classic/pull/6211,
but turns out that running `yarn run lint` (or any other `eslint` invocation) fails on missing `babel-eslint`.
Adding back :)
Turns out we can't use babel-eslint newer than 8.1*, 9.0 and newer fail with ` TypeError: Cannot read property 'range' of null`  (probably related to our version of eslint itself), so using 8.1 for now.
Also fixed some indentation issues in `.eslintrc.json` and a added back a few missing rules in the es6 eslintrc.json.
=> Fix eslint

app/views/shared/views/_ownership.html.haml
This fixes a `undefined method `tenant_group?' for nil:NilClass` error when selected KeyPair's group didnt exist
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1747179
@mzazrivec pls review, this issue does not exist on upstream. It has been fixe don upstream by changes in https://github.com/ManageIQ/manageiq-ui-classic/pull/5863
=> [IVANCHUK] Added a nil check.

spec/presenters/tree_node/availability_zone_spec.rb, spec/presenters/tree_node/configured_system_spec.rb, spec/presenters/tree_node/container_spec.rb, spec/presenters/tree_node/customization_template_spec.rb, spec/presenters/tree_node/ems_cluster_spec.rb, spec/presenters/tree_node/ems_folder_spec.rb, spec/presenters/tree_node/ext_management_system_spec.rb, spec/presenters/tree_node/host_spec.rb, spec/presenters/tree_node/pxe_image_spec.rb, spec/presenters/tree_node/vm_or_template_spec.rb
I'm getting a bunch of
DEPRECATION WARNING: factory_by_name is deprecated and will be removed from factory_bot 6.0 (called from block (2 levels) in <top (required)> at /home/travis/build/ManageIQ/manageiq-ui-classic/spec/presenters/tree_node/availability_zone_spec.rb:12)
during travis, it seems like all of those come from the tree node specs (from https://github.com/ManageIQ/manageiq/pull/12458),
and with one exception, only serve to set the context name
that one exception later creates an actual object from the factory, so we can get the klass that way
Cc @skateman , WDYT?
=> Remove deprecated factory_by_name

config/webpack/loaders.js
By default, babel loader doesn't do any caching,
but we can enable it, and `bin/webpack` goes from 25 seconds to 17 on my machine, the second time (once cached).
So, enabling the cache,
and adding a way to override the location from the default `node_modules/.cache/babel-loader` by providing a different location via BABEL_CACHE_DIR env.
=> Enable babel-loader caching

app/controllers/miq_ae_class_controller.rb
So this is crazy, the node ID generation was wrongly implemented and it was ont possible that it ever worked. Of course there's no way that we could see this visually as the `open_parent_nodes` usually gets triggered by a node activation on the last level. However, the tests were failing just sometimes if the record identifiers for the `MiqAeMethod` and `MiqAeClass` were the same, which in testing on a clear database is in most of the cases true.
Closes https://github.com/ManageIQ/manageiq-ui-classic/pull/6370
=> Fix node ID generation for MiqAeClassController#open_parent_nodes

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js, app/assets/javascripts/controllers/dialog_user/dialog_user_reconfigure_controller.js, app/assets/javascripts/services/dialog_field_refresh_service.js, spec/javascripts/controllers/dialog_user/dialog_user_controller_spec.js, spec/javascripts/services/dialog_field_refresh_service_spec.js
Depends on https://github.com/ManageIQ/ui-components/pull/422
Right now, when submitting a service dialog,
we simply take the dialogData object, convert to JSON and send to the API.
To allow for output conversions, adding a DialogData.outputConversion method,
which should return the dialogData in a suitable format.
(Right now, all this really means is that it converts Dates to strings before JSON stringification.)
And the same needs to happen in `refreshField` for dynamic fields.
https://bugzilla.redhat.com/show_bug.cgi?id=1744413
@miq-bot add_label bug, ivanchuk/yes
=> DialogUser - use DialogData.outputConversion before submit and refresh

app/controllers/application_controller/report_downloads.rb, app/views/layouts/print/report.html.haml
* render_pdf is used as a method and also as an action, separate that
* use less instance variables to make the data flow more explicit
Preparatory work for https://bugzilla.redhat.com/show_bug.cgi?id=1750305
=> More report cleanup

app/controllers/ops_controller/ops_rbac.rb
We have an issue where a custom role has "Access Restriction for Services, VM and Templates" set to something, the user can still see the full list of users, and when set to none, you only see the previous user logged in the tree from when there was a restriction set.
User.current_user is still using the incorrect group setting because we never reload it. 
Forcing a reload makes us load the right group with the right permissions here and the accordion changes when the users and group visibility changes as it should.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1766756
=> Force user group reload after changing permissions so tree is correct

app/helpers/application_helper/toolbar/configured_system/automation/policy_mixin.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6361
There was an issue with Configured Systems' list and the toolbar button: it was possible to click on _Edit Tags_ without selecting any Configured System in the list. This led to an error, and nothing happened in the UI.
This PR fixes the issue by setting `:onwhen` attribute for the appropriate toolbar button which makes the button enabled if at least one item is selected in the list.
This PR fixes the issue for Configured Systems in _Automation > Ansible Tower > Explorer > Configured Systems_ accordion and also for Configured Systems displayed through selected Ansible Tower Provider's Inventory Group (_Configured Systems_ tab).
---
**Before:**
**After:**
=> Disable clicking on Edit Tags without selecting Configured Systems

app/controllers/catalog_controller.rb, app/javascript/components/catalog-form/catalog-form.jsx, app/javascript/spec/catalog-form/catalog-form.spec.js
https://bugzilla.redhat.com/show_bug.cgi?id=1766276
1.Go to Services -> Catalogs -> Catalogs accordion
2.Add or Update a catalog 
3.View the success message
Catalog was saved
Catalog "{catalog_name}" was saved
**Before**
**After**
@miq-bot add_label bug, ivanchuk/yes, changelog/yes
@h-kataria
=> Show name in success catalog form messages

app/controllers/application_controller/ci_processing.rb, app/controllers/cloud_object_store_container_controller.rb, app/controllers/cloud_object_store_object_controller.rb, app/controllers/ems_cluster_controller.rb, app/controllers/ems_infra_controller.rb, app/controllers/ems_storage_controller.rb, app/controllers/host_controller.rb, app/controllers/miq_template_controller.rb, app/controllers/orchestration_stack_controller.rb, app/controllers/resource_pool_controller.rb, app/controllers/service_controller.rb, app/controllers/storage_controller.rb, app/controllers/vm_common.rb, spec/controllers/application_controller/ci_processing_spec.rb, spec/controllers/cloud_object_store_container_spec.rb, spec/controllers/ems_cluster_controller_spec.rb, spec/controllers/ems_infra_controller_spec.rb, spec/controllers/ems_storage_controller_spec.rb, spec/controllers/host_controller_spec.rb, spec/controllers/miq_template_controller_spec.rb, spec/controllers/orchestration_stack_controller_spec.rb, spec/controllers/resource_pool_controller_spec.rb, spec/controllers/service_controller_spec.rb, spec/controllers/storage_controller_spec.rb, spec/controllers/vm_common_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/5924
We want to get rid of going through so many cases in `get_rec_cls` which is not very efficient. This PR addresses the solution. I've created a new method `record_class` which returns `VmOrTemplate` by default. No need to define this method in each controller.
I've also added some more special cases in some controllers in `record_class` which were missing in the original `get_rec_cls` method.
**Note:**
The following controllers need just the default `record_class` method:
- auth_key_pair_cloud
- availability_zone
- cloud_tenant
- cloud_volume
- ems_cloud
- flavor
- host_aggregate
- vm_cloud 
- vm_infra
- vm_or_template
Note2:
You will probably not be able to test some actions, scenarios because of various issues, for …
=> Refactor get_rec_cls to get proper record class for various items

app/helpers/application_helper/button/cloud_volume_new.rb
Somehow Travis started to fail on `Module.const_defined?` for the openstack providers `CloudVolume` with Ruby 2.6. First I thought it's the new top-level constant lookup change, but I was not able to reproduce it locally. So I am changing the code to a little safer approach by using `safe_constantize` and `try`.
@miq-bot add_label bug, ivanchuk/no
=> Fix CloudVolume constantization issues by using try/safe_constantize

app/presenters/tree_builder_alert_profile_obj.rb
When assigning an alert profile to a tag category, it wasn't showing checkboxes due some previous refactoring. Also some nodes were unnecessarily selectable in the assignments tree, when there are checkboxes only.
**Before:**
**After:**
@miq-bot add_reviewer @brumik 
@miq-bot add_label bug, trees, ivanchuk/no
=> Fix TreeNode selectability and checkboxes for alert profile assign

app/javascript/components/tree-view/hierarchical-tree-view.jsx, app/javascript/packs/component-definitions-common.js, app/javascript/spec/tree-view/tree-view.spec.js
React tree view wrapper now uses the redux tree version with redux store. The name of the store is always the name of the rendered tree, so it shouldn't have problems with multiple trees rendered on the same page, as long as they have different names. 
This update also applies fixes on the tree: #6011 #6010 
Depends on: https://github.com/ManageIQ/react-ui-components/pull/153
@miq-bot add_reviewer @skateman 
=> React tree view with redux store

app/assets/javascripts/miq_global.js, app/javascript/optimization/transform.js, app/views/layouts/application.html.haml
Overview > Optimization,
in the show_list views (`/optimization/show_list` and `/optimization/show_list/123`), we convert iso dates to the user representation in JS. 
But, for saved report views (both in Optimization and in Reports), we use the formatted value provided by the API (`/api/results/20892?expand_value_format=true&hash_attribute=result_set`).
Before, the show_list value was formatted as "07/22/2019 9:44:50 am", in browser-local timezone.
Now, the show_list value is formatted as "07/22/2019 09:44:50 UTC", in the timezone set in user settings.
This also exposes the current user timezone (`session[:user_tz]`) to JS (`ManageIQ.timezone`), in the `Europe/London` / `Etc/UTC`... format.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1769333
=> Optimization - consistent date formats

app/javascript/components/report-data-table.jsx
when you try to load a saved report that's still being generated,
`GET /api/results/20893`, the response will contain
```
result_set: []
report: null
last_run_on: null
```
because all those fields are only set when the report is done generating.
That leads to infinispinner and
```
report-data-table.jsx:74 Uncaught TypeError: Cannot read property 'col_order' of null
at parseReportColumns (report-data-table.jsx:74)
at reduceLoadedData (report-data-table.jsx:86)
at reducer (report-data-table.jsx:112)
at updateReducer (react-dom.development.js:15444)
at Object.useReducer (react-dom.development.js:16060)
at useReducer (react.development.js:1567)
at ReportDataTable (report-data-table.jsx:188)
at renderWithHooks (react-dom.development.js:15108)
at updateFunctionComponent …
```
=> ReportDataTable - fix error when data.report is null

app/views/catalog/_svccat_tree_show.html.haml
When opening a service catalog's detail page, there's a missing route error in the order button's URL generation. However, the order button from the list view of all catalogs works as it should without any error. So I decided that instead of further debugging, I will just unify the two approaches and start using the `miqOrderService` in the single view the same way as it is being used in the list view.
```
Error caught: [ActionView::Template::Error] No route matches {:action=>"svc_catalog_provision", :button=>"order", :controller=>"catalog", :id=>54}
```
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6350
@miq-bot add_label bug, ivanchuk/no, services
=> Unify the service catalog order button handling on list/single views

app/assets/javascripts/miq_change_stored_password.js, app/views/ops/_rbac_user_details.html.haml
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1762791
There was a bug regarding responding of _Save_ button (_Save_ and _Reset_ buttons are together enabled or disabled like one) on changes of User's password: after clicking on _Cancel_ button for canceling editing the password (not canceling editing User's info!), _Save_ button was still enabled even when there wasn't any change in the User's info, and after clicking on _Save_ error occurred.
The core of the problem is `value` vs. `placeholder` attribute of `password_field_tag`. Because of that, string with dots _'●●●●●●●●'_ appeared in `params[:password]` after clicking on _Cancel_ button, so then this value was copied to `@edit[:new][:password]` (which was `nil` originally, at the beginning of editing User's info) and …
=> Make Save button disabled after canceling User's password changes

app/views/layouts/angular/_ansible_form_options_angular.html.haml
@miq-bot add_label wip, cleanup, ivanchuk/no
Fix following error in spec log:
```
app/views/layouts/angular/_ansible_form_options_angular.html.haml:133:
warning: key "ng-if" is duplicated and overwritten on line 135
```
Places to check it works:
Services -> Catalogs -> Catalog Items -> create/edit -> Hosts show only for Ansible Playbook
Automation -> Automate -> Explorer -> create/edit a method -> Hosts show only for Ansible Playbook
Hosts pic:
Remove check `"#{ng_model}.#{prefix}_inventory!==undefined"` as it's always set for Ansible Playbook and `"#{ng_model}.location==='playbook'"` makes sure it's not shown for other methods/catalog items.
=> Fix double ng-if

app/controllers/ping_controller.rb, spec/controllers/ping_controller_spec.rb
With `render :text`, this fails with the following error:
Error caught: [ActionView::MissingTemplate] Missing template ping/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :haml, :rjs]}.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1771044
---
@himdel Please review.
=> Ping controller fix

app/assets/stylesheets/patternfly_overrides.scss
This PR removes the custom "form-control-static" class. The class in now part of Bootstrap: https://github.com/twbs/bootstrap/pull/15699
=> Remove old  class

app/controllers/miq_policy_controller.rb
Trying to help with https://github.com/ManageIQ/manageiq-ui-classic/issues/6329
* `@trees` has to be an array (set it `app/controllers/application_controller.rb`)
* handle tree building the same way other controllers do (via `build_replaced_trees`)
* remove dead code
Ping @himdel, @rvsia
=> Policy: simplify handling of @trees, make in an array.

app/helpers/application_helper/title.rb
Custom menu items (added throught settings) do not have a nice page title (html `<TITLE>` tag).
The current one is calculated from the ID of the section (`@layout`).
Fixing that to use the menu item's `name` instead.
Ping @himdel
=> Add page title for custom menu items.

app/controllers/report_controller/menus.rb
To be honest, I have no idea about how this piece of code works and looking at it I have a feeling that it needs some :fire: before touching it in the future. Anyway, it seems to fix the problem, but I need some clickety-testing.
@miq-bot add_label ivanchuk/yes, hammer/yes, bug
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1762363
=> Set empty report submenus to empty arrays instead of empty strings

app/helpers/network_port_helper/textual_summary.rb, spec/helpers/network_port_helper/textual_summary_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6311
There was `[object Object]` displayed for the **Host in Network Port's Relationships table**, in textual summary. Adding `name` to `@record.device` for the _value_ parameter simply solves this issue.
**Before:**
**After:**
=> Display name instead of [object Object] for the Host in Network Port's Relationships table

app/views/catalog/_svccat_tree_show.html.haml
This PR adjusts the columns on the Service Catalog order screen to prevent the text and image from overlapping.
Old
New
=> Service Catalog styling fix

app/controllers/automation_manager_controller.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6375
Relatively recently the _Configuration_ toolbar button was added to Ansible Tower Templates screen, with possibility to create Service Dialog from a selected Template in the list. However, this button appeared also on the screen with the list of Templates related to selected node in accordion, for example related to _Ansible Tower Automation Manager_. While being in such a screen, creating Service Dialog did not work, nothing happened in the UI, and error occurred.
The problem is exactly [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/automation_manager_controller.rb#L447). It's easy to achieve the situation when both `params[:id]` and `params[:miq_grid_checks]` are set, so we are …
=> Allow create Service Dialog from Template on Ansible/Templates screen, depending on navigation steps

spec/controllers/miq_report_controller/dashboards_spec.rb
We previously expected a duplicate dashboard name to raise an error and it no
longer is a problem as of https://github.com/ManageIQ/manageiq/pull/19491
=> Try to create a dashboard without needed fields

app/javascript/spec/toolbar/__snapshots__/miq-toolbar.spec.jsx.snap, package.json
and update to that version specifically
the change in https://github.com/ManageIQ/react-ui-components/pull/158
was picked up by travis and started breaking ui jest tests, fixing.
(Failure: https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/612037181#L2994)
=> Update toolbar snapshots for react-ui-components 0.11.56, fix jest on travis

app/controllers/infra_networking_controller.rb, app/controllers/vm_common.rb, app/helpers/miq_ae_customization_helper.rb, app/presenters/explorer_presenter.rb, spec/presenters/explorer_presenter_spec.rb
for regions > 9006, our bigint ids become floats in javascript, and can be off-by-one. (Original issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/1405)
This makes sure the dialog editor works in those regions:
* the `dialog_id_action` change fixes the result of the `requestDialogId` dialog editor controller method, controlling where to load the dialog data from
* the `ExplorerPresenter` change fixes the toolbar (Edit) button failing (becuase it uses `ManageIQ.record.recordId`, which was set to a number otherwise)
* (the infra_networking & vm_common change only remove the now extra `to_s` because it's handled in ExplorerPresenter now)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1769968
=> Dialog Editor, ExplorerPresenter - make sure all ids are strings in javascript

app/controllers/miq_request_controller.rb, spec/controllers/miq_request_controller_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1765691
After clicking on _Lookup_ button, the LDAP user's info was not displayed in the form as expected, while provisioning VM. The page was not properly updated, after clicking on the button. A simple change in `retrieve_email` method fixes the problem.
While going to the other tab and going back (as mentioned in the BZ), `prov_field_changed` method was called. In this method, `render` is called to update the page according to the changes on the provision form, and it works fine. This is why going to the other tab and going back 'solves' the missing info in the fields, after clicking on _Lookup_. The page is updated properly especially because of this [line](https://github.com/hstastna/manageiq-ui-classic/blob/master/app/controllers …
=> Display user info after clicking on Lookup while provisioning VM

lib/tasks/manageiq/ui_tasks.rake
A handful of times I've had to look at this list and it's hard to read as a single line.  This PR changes it to pretty print for better readability.
Now:
```text
[Webpacker] Compiled digests for all packs in /Users/jfrey/dev/manageiq-ui-classic/app/javascript/packs:
{"manageiq-providers-lenovo/component-definitions-common.js"=>
"/packs/manageiq-providers-lenovo/component-definitions-common-834f716388d45ec8b228.js",
"manageiq-providers-nuage/component-definitions-common.js"=>
"/packs/manageiq-providers-nuage/component-definitions-common-ab780fac00d877a46d0a.js",
"manageiq-providers-redfish/component-definition-common.js"=>
"/packs/manageiq-providers-redfish/component-definition-common-688b7778ac4f1ba2afea.js",
"manageiq-ui-classic/angular-common.js"=> …
```
=> Pretty print the webpack list

app/controllers/dashboard_controller.rb
Clicking on a section when the user (his role) has that section allowed but does not have any items under it enabled:
Newly there's a fallback to redirect to users initial page, so no further crash.
=> Add fallback for clicking on a section w/o permissions.

app/controllers/application_controller.rb
I don't really know what was the idea behind this one line, but as we discussed in https://github.com/ManageIQ/manageiq-ui-classic/issues/6313, we want to minimize the exceptions in our codebase.
**Before:**
**After:**
@miq-bot add_label bug, GTLs
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6313
=> Display icons in GTLs on PXE screens

app/assets/javascripts/controllers/dialog_user/dialog_user_controller.js, app/assets/javascripts/controllers/dialog_user/dialog_user_reconfigure_controller.js, app/assets/javascripts/services/dialog_field_refresh_service.js, spec/javascripts/controllers/dialog_user/dialog_user_controller.spec.js, spec/javascripts/helpers/object.values.js, spec/javascripts/services/dialog_field_refresh_service_spec.js, spec/javascripts/support/jasmine.yml
This is a hammer version of https://github.com/ManageIQ/manageiq-ui-classic/pull/6291
~~Depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/6408 (merged and rebased)~~
(there was a conflict with dependency injection in dialog_user - there is no `dialogReplaceData` in hammer)
---
Depends on ManageIQ/ui-components#422
Right now, when submitting a service dialog,
we simply take the dialogData object, convert to JSON and send to the API.
To allow for output conversions, adding a DialogData.outputConversion method,
which should return the dialogData in a suitable format.
(Right now, all this really means is that it converts Dates to strings before JSON stringification.)
And the same needs to happen in refreshField for dynamic fields. …
=> [HAMMER] DialogUser - use DialogData.outputConversion before submit and refresh

app/controllers/application_controller/miq_request_methods.rb
First commit fixes issue I have encountered before I could get to the BZ itself. Problem is that `@edit[:new][:src_vm_id]` is very unsure about its identity. Sometimes it is array, sometimes it is integer, it depends...When it comes from `params` or it is stored in `session/@edit` after being loaded from `params` it is integer. However when it comes from `workflow` it is an Array `[id, name]` this is common pattern in workflows. Why we have two values associated under one key is beyond my understanding. 
Because different provisioning screen have slightly different interactions it is challenging to keep it together.  `@edit[:new]` is modified in workflow constructor `miq_request_methods.rb:989` that complicate things even more.
Second commit fixes the actual BZ.
Screenshot [Optional] …
=> Catalog Item RHEV provision fix

app/views/layouts/_compare.html.haml
This PR fixes a bug introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/6012, where an indent caused the treegrid not to be rendered for Explorer-based compare screens.
Old
New
=> Compare Treegrid fix

spec/controllers/application_controller/ci_processing_spec.rb, spec/controllers/vm_infra_controller_spec.rb, spec/helpers/application_helper/buttons/vm_reconfigure_spec.rb
Without an EMS a VM doesn't support reconfigure.
Broken by:
https://github.com/ManageIQ/manageiq-providers-vmware/pull/467
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/421
=> Fix VmInfra Reconfigure specs

app/controllers/ems_infra_controller.rb, spec/controllers/ems_infra_controller_spec.rb
The ems_ref_obj attribute is (soon to be was) used by VMware to store the full VIM class.  Most providers just set this to be equal to the ems_ref.
We are deleting this ems_ref_obj attribute because it is a serialized yaml column and requires us to have the VimBroker required in core.
Core issue: https://github.com/ManageIQ/manageiq/pull/19430
=> Remove ems_ref_obj

app/controllers/mixins/ems_common.rb, spec/controllers/mixins/ems_common_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6303
There was an issue regarding Container Replicators, Pods, Nodes, Images displayed in a nested list: `Button not yet implemented` occurred after trying to tag or manage policies of selected items, **if _Check Compliance of Last Known Configuration_ was initiated before other policy actions**.
---
**Details:**
The issue is caused [here](https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Button_not_implement_ContainerReplicators_Pods_Nodes_Imgs?expand=1#diff-c32dcaa7dedd2b85b7ee0ce6036b3f54L490). The problem was that `@lastaction` was set to `"show"` but this fact was not checked at all, in `check_compliance_nested`, and calling `show_list` method was the one and only option. You can compare this …
=> Allow tagging or managing policies for Replicators, Pods, Nodes, Images

app/controllers/application_controller/compare.rb
I found this by accident, looked it and my intern said :potato: so :scissors: 
@miq-bot add_label technical debt, cleanup, ivanchuk/no
=> Remove unnecessary one-liner alias functions from Compare/Drift

app/controllers/dashboard_controller.rb, app/javascript/angular/dashboard/dropdown-menu.js, app/javascript/angular/dashboard/widget-wrapper.js, app/javascript/spec/dashboard/widget-empty.spec.js, app/javascript/spec/dashboard/widget-wrapper.spec.js, app/presenters/widget_presenter.rb, app/views/dashboard/_widget.html.haml, config/routes.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703068
This applies to all Dashboard Widgets except Menu ones.
Go to Overview -> Dashboard
Before:
After:
@miq-bot add_label enhancement, ivanchuk/no, cloud intel/dashboard, wip, core pending
TODO:
=> Add Refresh button to individual Dashboard Widget

app/controllers/ops_controller/settings/cap_and_u.rb
Saving the changes under `C&U Collection` under `Settings -> Region` was not possible as the tree names were not adjusted with the `_tree` suffix. It has been probably caused by the tree name/id unification and it might affect the ivanchuk release.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6430
=> Fix cancel/reset buttons' reaction to C&U collection checkboxes

app/assets/javascripts/miq_application.js, app/views/miq_request/_prov_wf.html.haml, app/views/ops/_ap_form.html.haml
This will force user to save any unsaved changes in the form before changing the tab.
Issue #6213
Prompts user if they want to abandon changes after they have made changes to the form and trying to change the tabs in Configuration explorer. Tested this on several screens in OPS explorer, tried several other screens with tabs, seems to be working fine now. @hstastna please test
=> Call `miqCheckForChanges` before changing tabs.

app/assets/stylesheets/patternfly_overrides.scss, app/views/ops/_settings_help_menu_tab.html.haml
This PR replaces the custom "no-border" class with the standard Bootstrap "table-borderless" class.
=> Remove custom "no-border" class

app/assets/javascripts/controllers/topology/cloud_topology_controller.js, app/assets/javascripts/controllers/topology/infra_topology_controller.js, app/assets/javascripts/controllers/topology/network_topology_controller.js, app/assets/javascripts/controllers/topology/physical_infra_topology_controller.js, app/assets/javascripts/services/topology_service.js, app/services/cloud_topology_service.rb, app/services/infra_topology_service.rb, app/services/network_topology_service.rb, app/services/physical_infra_topology_service.rb, app/services/topology_service.rb, app/views/cloud_topology/show.html.haml, app/views/infra_topology/show.html.haml, app/views/network_topology/show.html.haml, app/views/physical_infra_topology/show.html.haml, spec/services/topology_service_spec.rb
**RFE:** https://bugzilla.redhat.com/show_bug.cgi?id=1529718
This PR completely removes _Tags_ from all of the Topology Views.
Related PRs:
https://github.com/ManageIQ/manageiq/pull/7931
---
**Before:** (_Networks > Topology_)
**After:**
=> Remove Tags from Network Topology View and others

app/controllers/application_controller/ci_processing.rb, spec/controllers/application_controller/ci_processing_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6338
There is an issue with Clusters and SSA: The selected Cluster is not accessible while performing SSA from the list of Clusters of selected Infrastructure Provider (It works well from textual summary of a Cluster). This PR together with already merged https://github.com/ManageIQ/manageiq-ui-classic/pull/6224 fixes the issue.
**Details:**
There are two problems which cause the issue:
1. wrong record is being set in `generic_button_operation` [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller/ci_processing.rb#L611), we get the actual provider instead of the selected Cluster
- https://github.com/ManageIQ/manageiq-ui-classic/pull/6224 fixes it [MERGED]
2. …
=> Allow performing SSA on Clusters of Infra provider

app/assets/stylesheets/icon_customizations.scss, app/assets/stylesheets/patternfly_overrides.scss, app/controllers/miq_policy_controller.rb, app/views/miq_policy/import.html.haml
This PR moves the color settings for Policy import icons and the quads  into the icon customizations file. It also cleans up the icons customizations.
=> Customized fonticon cleanup

app/controllers/storage_controller/storage_pod.rb, app/presenters/tree_builder_storage_pod.rb
This will break as we subclass models per-provider e.g.
ManageIQ::Providers::Vmware::InfraManager::StorageCluster
Related: https://github.com/ManageIQ/manageiq/pull/19534
=> Don't query for an exact type

app/controllers/catalog_controller.rb, app/controllers/chargeback_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/chargeback_controller_spec.rb
we renamed model(and related tables, ...) ChargebackRateDetailCurrency to Currency
~~at this moment: backend is pending: https://github.com/ManageIQ/manageiq/pull/19538~~
at this moment: backend is merged:https://github.com/ManageIQ/manageiq/pull/19350
@miq-bot add_label backend pending, technical debt
=> Rename usage ChargebackRateDetailCurrency to Currency

app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
We need to be able correctly handle ansible credential resources, which have options hash set to `nil` / `null`.
1. Create a machine credential, set username & password, nothing else!
2. Try to edit the credential
3. Observe the following javascript error:
```
angular.js:14961 TypeError: Cannot read property 'userid' of null
at ansible_credentials_form_controller.self-d9df03bc8f1484db2a02d83c534e63b7e78fa04f4ba970174ce3945bb8a3fda3.js?body=1:122
at Array.forEach (<anonymous>)
at ansible_credentials_form_controller.self-d9df03bc8f1484db2a02d83c534e63b7e78fa04f4ba970174ce3945bb8a3fda3.js?body=1:114
at processQueue (angular.js:17330)
at angular.js:17378
at Scope.$digest (angular.js:18515)
at angular.js:18835
at completeOutstandingRequest (angular.js:6439)
at angular.js:6718 "Possibly …
```
=> Machine Credential: don't access options hash when null

spec/controllers/cloud_volume_controller_spec.rb
Generalize the matching to ignore extra keys.
Fix failing specs (probably broken from core):
```
...
Diff:
@@ -8,6 +8,7 @@
:size=>1}],
:class_name=>"CloudVolume",
:method_name=>"create_volume",
+  :queue_name=>nil,
:role=>"ems_operations",
:zone=>"Zone 40"}]
...
```
```
Failed examples:
2269 rspec ./spec/controllers/cloud_volume_controller_spec.rb[1:7:2:1:1:2] # CloudVolumeController#create_volume in Amazon EBS for volume type 'gp2' behaves like queue create volume task queues the create cloud volume action form OpenStack
2270 rspec ./spec/controllers/cloud_volume_controller_spec.rb[1:7:2:2:1:2] # CloudVolumeController#create_volume in Amazon EBS for volume type 'io1' behaves like queue create volume task queues the create cloud volume action form OpenStack
2271 rspec …
```
=> Generalize queue matching.

app/controllers/ops_controller/ops_rbac.rb, app/views/ops/_rbac_group_selected.html.haml, spec/controllers/ops_controller/ops_rbac_spec.rb, spec/views/ops/_rbac_group_selected.html.haml_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6364
In User's editing screen, _Save_ button wasn't responding properly on changes in _Available Groups_ section, especially if there were more groups selected in the drop down.
Another issue was improper order of groups in _Selected Groups_ section while adding/editing User. It was inconsistent with the User's details screen where the _Groups_ are properly ordered (by description).
This PR fixes both issues, together with fixing two improper comments in the code.
**Details:**
The improper response of _Save_ butto on changes in User's _Available Groups_ was caused by sorting the Groups' ids represented by [array of strings](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/ops_controller/ops_rbac.rb …
=> Make Save button respond properly on changes in User's Available Groups

app/controllers/miq_request_controller.rb, app/controllers/mixins/actions/vm_actions/reconfigure.rb, app/helpers/application_helper/button/vm_reconfigure.rb, app/helpers/application_helper/button/vm_reconfigure_multiple.rb, app/helpers/application_helper/toolbar/template_clouds_center.rb, app/helpers/application_helper/toolbar/vm_infras_center.rb, app/helpers/application_helper/toolbar/x_template_cloud_center.rb, app/views/vm_common/_reconfigure.html.haml, spec/helpers/application_helper/buttons/vm_reconfigure_spec.rb, spec/shared/helpers/application_helper_buttons.rb
Alternative to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6409
Depends on: https://github.com/ManageIQ/manageiq/pull/19566 (see that one for a detailed description)
closes: https://bugzilla.redhat.com/show_bug.cgi?id=1770022
closes: https://github.com/ManageIQ/manageiq-ui-classic/issues/6422
1. A separate feature is added for each of memory cpu network disks cdroms 
-- https://github.com/ManageIQ/manageiq/pull/19566
1. a new `:hidden` feature is added to replace the current `vm_reconfigure` (more on that below)
1. a new feature is added `vm_reconfigure_all` that is a parent feature of the features from 1
`vm_reconfigure` cannot be a direct parent of the new features because both
* a) the logic for checking permissions when displaying a button and
* b) (more importantly) the …
=> Reconfigure: use detailed RBAC features.

spec/presenters/tree_builder_services_spec.rb
We're calling factories with `:display =>` when we should be calling with `:visible =>`
```
DEPRECATION WARNING: display= is deprecated and will be removed from ManageIQ K-release (visible=)
```
=> fixes service#display deprecation msg

app/assets/stylesheets/patternfly_overrides.scss
This PR removes a couple of old compare/drift related selectors missed in the previous PRs.
This is a follow-up to:   https://github.com/ManageIQ/manageiq-ui-classic/pull/6424 and  https://github.com/ManageIQ/manageiq-ui-classic/pull/6436
=> compare cleanup follow-up

app/assets/javascripts/controllers/ops/pglogical_replication_form_controller.js
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1757800
Fix responding _Save/Reset_ buttons after discarding changes for Subscriptions if there is no change in Subscriptions. Fix also responding the buttons after clicking on _Accept_ button. Setting the form as pristine solves the problems.
The second commit fixes error about undefined variable:
You can get this error if you create a new Subscription and before saving it, you decide to make changes so you click on _Update_ and make some change but then you click on _Discard_ because you've changed your mind.
---
**Before:**
**After:**
=> Disable Save/Reset buttons after discarding changes for Subscription

app/controllers/miq_policy_controller/miq_actions.rb, spec/controllers/miq_policy_controller/miq_actions_spec.rb
- when editing existing attribute/values, they were getting added to the array instead of updating existing value.
- when user removed attr/value in the UI, existing code was not deleting attribute/value pair from the record.
- fixed edit of description field on existing record was not working
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1779140
@hstastna please review/test
=> Multiple issues fixed on action edit screen

spec/controllers/cloud_object_store_container_spec.rb, spec/controllers/cloud_tenant_controller_spec.rb
Fix the cloud_object_store and cloud_tenant tests expecting
queue_options to be an exact hash.
=> Fix cloud_object_store and cloud_tenant queue_opts

app/assets/javascripts/miq_qe.js
when using `_.debounce`, the debounced function has 2 extra methods (described in https://github.com/lodash/lodash/blob/master/debounce.js#L7-L9):
* `cancel()` - cancels the call
* `flush()` - triggers the call if it was pending
but the QE wrapper is currently not returning either of these.
Fixing :).
`cancel` needs to clean the debounce registry becuase the function will never get called.
`flush` doesn't, because the function does get called.
Cc @skateman
=> miq_qe - support debounced.cancel, debounced.flush

spec/controllers/cloud_network_controller_spec.rb, spec/controllers/cloud_subnet_controller_spec.rb, spec/controllers/cloud_volume_controller_spec.rb, spec/controllers/cloud_volume_snapshot_controller_spec.rb, spec/controllers/floating_ip_controller_spec.rb, spec/controllers/host_aggregate_controller_spec.rb, spec/controllers/network_router_controller_spec.rb, spec/controllers/security_group_controller_spec.rb, spec/services/git_based_domain_import_service_spec.rb
Only need to test for the values that are relevent to the tests (e.g.
instance_id, method_name, args).
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/6504
=> Don't test exact queue_options when testing operations

app/assets/stylesheets/patternfly_overrides.scss
The PR restores the styling required for the entry point modal to be properly formatted.
Issue: #6494
Old
New
=> Entry Point modal styling fix

app/assets/stylesheets/patternfly_overrides.scss
The PR removes the old custom "table-borderless" class in favor of the standard BS "table-borderless" class.
Follow-up to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6437
=> Remove custom "table-borderless" class

app/controllers/generic_object_definition_controller.rb
`.each {|i| {:name => i}}` was used in an empty context here.
=> Remove unnecessary code from GenericObjectDefinitionController

app/assets/javascripts/components/cloud_volume_backup/cloud-volume-backup-form.js
`foundVolumes()` is a one-liner and is being used in one place only.
=> Remove unnecessary one-liner from cloudVolumeBackupForm

app/controllers/application_controller/ci_processing.rb, app/controllers/orchestration_stack_controller.rb, spec/controllers/cloud_tenant_controller_spec.rb, spec/controllers/mixins/ems_common_spec.rb, spec/controllers/orchestration_stack_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6489
_Shelve Offload_ power operation on Instances displayed in a **nested list** did not work: nothing happened in the UI. The issue was present in `process_vm_buttons` method where `shelveoffloadvms` should have been called, and it didn't. The method simply didn't correspond to what's in `params[:pressed]`, after clicking on `Shelve Offload` in the toolbar.
In this PR, I am also adding specs for `button` method for controllers 'under' _Compute > Clouds_. For `orchestration_stack` controller, I am also fixing _DoubleRender_ error by adding `unless performed?` [here](https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:Shelve_Offload_Instances_nested_list?expand=1#diff-c825546e2b4be699311249312a23bd63R12 …
=> Allow performing Shelve Offload operation for Instances in a nested list

app/controllers/dashboard_controller.rb
generate_ui_api_token was removed in f161abde29c273761a77113ef14652a9935f0d10
but this reference was left.
This behavior is still required for cockpit so the contents of the
removed method are now baked into #cockpit_redirect
https://bugzilla.redhat.com/show_bug.cgi?id=1779988
@miq-bot add_label bug, blocker, ivanchuk/yes
@miq-bot assign @skateman
=> Reimplement token generation for cockpit webconsole proxy

config/webpack/RailsEnginesPlugin.js, config/webpack/shared.js, package.json
Right now, we have 2 ways of saying "I only want 1 version of this package" in webpack config:
* `sharedPackages` - a list of packages, used by `RailsEnginesPlugin` to ensure any require(pkg) from a plugin goes to our version of the package, not the plugin's version
* `resolve.alias` - mapping from package name to an explicit root/node_modules/package location, to use the root version instead of another version coming as a dependency of a dependency
Both are similar concepts (identical if we start treating plugins as npm dependencies),
and there is no situation where we'd want 1 version for all the plugins but not other packages,
nor a situation where we'd want 1 version in ui-classic and another in plugins,
so we can merge the 2.
=> moving all those packages to `sharedPackages`, leaving …
=> webpack - merge sharedPackages and resolve.alias

app/views/layouts/angular/_ansible_form_options_angular.html.haml, app/views/miq_ae_class/_angular_inputs_form.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1757190
Adding:
* Inputs and Hosts for Ansible Job Template 
* Inputs for Ansible Workflow Template
=> Automate Ansible: host+input params for playbooks, input params for workflows

app/helpers/application_helper.rb, app/javascript/components/miq-toolbar.jsx, app/javascript/spec/toolbar/miq-toolbar.spec.jsx, app/views/layouts/_center_div_dashboard_no_listnav.html.haml, app/views/layouts/_center_div_no_listnav.html.haml, app/views/layouts/_center_div_with_listnav.html.haml, app/views/layouts/_content.html.haml, config/settings.yml, package.json
To be used with 
https://github.com/ManageIQ/react-ui-components/pull/162
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1683703
depends on: https://github.com/ManageIQ/react-ui-components/pull/162
=> Toolbars: use kebabLimit to set number of visible custom buttons.

app/assets/stylesheets/patternfly_overrides.scss, app/views/chargeback/_cb_rate_edit_table.html.haml, app/views/chargeback/_tier_first_row.haml, app/views/chargeback/_tier_row.haml
This PR replaces the custom "action" class used for styling buttons inside table cells in Chargeback with the "action-cell" class used elsewhere in the UI. There's also some reorg of "action cell" and "list-inline" selectors.
Old
New
=> Replace "action" class in Chargeback with "action-cell"

app/controllers/miq_policy_controller/policies.rb
When clicking on a Policy node in Policy Profiles accordion, right cell title was not displaying the model and mode of Policy in the title similar to how it is displayed in the tree node on the left.
Fixes #3114
before
after
=> Fixed right cell title to show missing info for Policy record.

app/assets/javascripts/components/generic_object/main-custom-button-form.js, spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js
When creating a new GO Playbook custom button, code expects service_template to be included in the ae_attributes hash in order to save the value correctly inside uri_attributes.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1753338
@d-m-u cc
@ZitaNemeckova i am not sure if the spec test changes in this PR are correct, can you please review/help
=> Fixed code to pass in `service_template` in ae_attributes hash

app/controllers/application_controller/ci_processing.rb, app/controllers/ems_cluster_controller.rb, app/controllers/host_controller.rb, app/controllers/resource_pool_controller.rb, app/helpers/application_helper/toolbar/vm_clouds_center.rb, app/helpers/application_helper/toolbar/vm_infras_center.rb, spec/controllers/auth_key_pair_cloud_controller_spec.rb, spec/controllers/availability_zone_controller_spec.rb, spec/controllers/cloud_tenant_controller_spec.rb, spec/controllers/ems_cloud_controller_spec.rb, spec/controllers/ems_cluster_controller_spec.rb, spec/controllers/ems_infra_controller_spec.rb, spec/controllers/flavor_controller_spec.rb, spec/controllers/host_aggregate_controller_spec.rb, spec/controllers/host_controller_spec.rb, spec/controllers/resource_pool_controller_spec.rb, spec/controllers/storage_controller_spec.rb, spec/controllers/vm_cloud_controller_spec.rb, spec/controllers/vm_infra_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6378
Related PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/3810
**This PR:**
- enables _Check Compliance..._ toolbar button also for nested list of VMs/Instances, to achieve more consistent behavior in MIQ, only for items in _Compute > Infra > VMs_ and in _Compute > Clouds > Instances_)
- makes the action work for the items displayed through _Relationships_ of Infra provider, Cluster, Host, Resource Pool, Datastore, Cloud provider, Availability Zone, Host Aggregate, Cloud Tenant, Flavor, Key Pair (nothing was needed to do for Orchestration Stack's Instances because the button is not present in the list view, only in summary screen)
- _Note_: `check_compliance_queue` is not testable by SupportsFeatureMixin nor …
=> Enable Check Compliance toolbar button for nested list of VMs and make it work

app/controllers/cloud_network_controller.rb, config/routes.rb, spec/controllers/cloud_network_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6309
This PR fixes the issue regarding _Instances_ displayed through a _Cloud Network's_ _Relationships_: **nothing happened in the UI for almost all of the operations in the toolbar**, for some operations error `No template found for CloudNetworkController#button` occurred.
The logic for operations on nested list of Instances was missing, in `cloud_network` controller. I'm adding appropriate logic by using `button` method from _GenericButtonMixin_.
In this PR, I'm also adding missing routes for managing policies of selected Instances.
Also **_Check Compliance of Last Known Configuration_** action will be fixed after merging this PR together with https://github.com/ManageIQ/manageiq-ui-classic/pull/6426 (MERGED).
---
**This …
=> Allow performing operations on Instances of a chosen Cloud Network

app/controllers/application_controller/ci_processing.rb, app/controllers/network_router_controller.rb, config/routes.rb, spec/controllers/network_router_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6309
This PR fixes the issue regarding _Instances_ displayed through a _Network Router's_ _Relationships_: **nothing happened in the UI for almost all of the operations in the toolbar** (tagging and comparing Instances worked).
The logic for operations on nested list of Instances was missing, in `network_router` controller. I'm adding appropriate logic by using `button` method from _GenericButtonMixin_.
In this PR, I'm also adding missing routes for managing policies of selected Instances.
Also **_Check Compliance of Last Known Configuration_** on Instances of a chosen Network Router will be working after merging this PR together with https://github.com/ManageIQ/manageiq-ui-classic/pull/6426 (MERGED).
---
**What else needs …
=> Allow performing operations on Instances of a chosen Network Router

app/helpers/application_helper/toolbar/compare_center.rb, app/helpers/application_helper/toolbar/drift_center.rb
The variable is being `eval`ed and it does not exist.
* Get rid of the unnecessary variable
* Limit the need for `eval` as required in https://github.com/ManageIQ/manageiq-ui-classic/issues/2049
=> Toolbars: remove unused variable.

app/controllers/application_controller/ci_processing.rb, app/controllers/security_group_controller.rb, config/routes.rb, spec/controllers/security_group_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6309
This PR fixes the issue regarding _Instances_ displayed through a _Security Group's_ _Relationships_: **nothing happened in the UI for almost all of the operations in the toolbar** (tagging and comparing Instances worked).
The logic for operations on nested list of Instances was missing, in `security_group` controller. I'm adding appropriate logic by using `button` method from _GenericButtonMixin_.
In this PR, I'm also adding missing routes for managing policies of selected Instances.
Also **_Check Compliance of Last Known Configuration_** on Instances of a Security Group will be working after merging this PR together with https://github.com/ManageIQ/manageiq-ui-classic/pull/6426 (MERGED).
---
**What else needs to be …
=> Allow performing operations on Instances of a chosen Security Group

app/controllers/infra_networking_controller.rb, app/views/infra_networking/explorer.html.haml, spec/controllers/infra_networking_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6519
This PR fixes two issues in Infra Networking page regarding Search box:
- **displaying the Search box** when accessing the page for the first time:
div with id `adv_searchbox_div`, containing _Search_ box and button for _Advanced Search_, is [ usually not displayed](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/layouts/_x_adv_searchbox.html.haml#L4) (see its style in the haml). I made the element displayed by [this](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/helpers/js_helper.rb#L37) method, through `javascript_show_if_exists` in the haml for [infra networking explorer](https://github.com/ManageIQ/manageiq-ui-classic/compare/master...hstastna:No_Searchbox_Infra_Networking?exp …
=> Display Search box in Infra Networking page

app/controllers/application_controller/ci_processing.rb, app/controllers/cloud_subnet_controller.rb, config/routes.rb, spec/controllers/cloud_subnet_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6309
This PR fixes the issue regarding _Instances_ displayed through a _Cloud Subnet's_ _Relationships_: **nothing happened in the UI for almost all of the operations in the toolbar**, for some operations error `No template found for CloudSubnetController#button` occurred.
The logic for operations on nested list of Instances was missing, in `cloud_subnet` controller. I'm adding appropriate logic by using `button` method from _GenericButtonMixin_.
In this PR, I'm also adding missing routes for managing policies of selected Instances.
Also **_Check Compliance of Last Known Configuration_** action will be working after merging this PR together with https://github.com/ManageIQ/manageiq-ui-classic/pull/6426 (MERGED).
In this PR, …
=> Allow performing operations on Instances of a chosen Cloud Subnet

app/views/ops/_rbac_group_details.html.haml
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/2316
This PR solves the specific situation in LDAP user lookup form: **DOM ID** `"user"` was there **twice**. This was caused by https://github.com/ManageIQ/manageiq/pull/4042. The exactly [same field with the same id](https://github.com/ManageIQ/manageiq/pull/4042/files#diff-dbe0fddf5aa74616c8f3f2f52c376abaR116), that was [already there](https://github.com/ManageIQ/manageiq/pull/4042/files#diff-dbe0fddf5aa74616c8f3f2f52c376abaR138), was added in the haml, together with the [javascript for showing/hiding](https://github.com/ManageIQ/manageiq/pull/4042/files#diff-dbe0fddf5aa74616c8f3f2f52c376abaR241) the divs with the appropriate fields. This (not the best) solution was implemented for displaying/hiding …
=> Prevent rendering User to Look Up form field twice and with same id

app/helpers/application_helper/toolbar/container_build_center.rb, app/helpers/application_helper/toolbar/container_builds_center.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6300
In this PR, I am removing toolbar button for _SmartState Analysis_ of _Container Builds_ because it does not make sense, it never worked ("A successful build generates a new image, that could be scanned of course").
**Before:**
List view:
Textual summary screen:
**After:**
=> Remove useless toolbar button for Container Build scan (SSA)

app/controllers/application_controller/compare.rb, spec/controllers/application_controller/compare_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6481
_Cancel_ button "disappeared" after applying changes in _Comparison Sections_ while comparing selected items displayed in a non-explorer screen. This happened because `@explorer` was accidentaly set to `true`.
The problem was that `%w[VMs Templates].include?(session[:db_title])` condition in `sections_field_changed` was simply not enough to set `@explorer` variable properly. The condition did not care about if we are in a nested list of VMs/Templates. And if we are, usually `@display` is set to `'vms'` or `'instances'`, so I used this variable for setting `@explorer` properly while making/applying changes in  in _Comparison Sections_. And we need `@explorer` to be set properly because of …
=> Display Cancel after applying changes in non-explorer Compare screen

app/helpers/container_build_helper/textual_summary.rb, app/helpers/textual_multilabel.rb
* TextualSummary: make "Build Instances" wide.
* Container build: sort instances in SQL.
After:
=> Conteiner build TextualSummary fixes.

app/helpers/container_build_helper/textual_summary.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6572
There was HTML code in the _Build Instances_ table in textual summary of selected _Container Build_. I've replaced `link_to` by `value.link` + `value.value` in this PR. Making the link look like a link wil be done in a follow up PR (in react-ui-components repo).
---
**Before:**
**After:**
=> Display name of Container Pod instead of HTML in Container Build's Textual summary

app/controllers/floating_ip_controller.rb, spec/controllers/floating_ip_controller_spec.rb
Regarding my recent changes in [_CloudSubnetController_](https://github.com/ManageIQ/manageiq-ui-classic/pull/6488) and some more controllers, I've decided to make small changes also in _FloatingIpController_ and its specs.
In this PR, I'm also adding new tests regarding `button` method, for example for proper calling `tag` method while tagging selected Floating IP or for redirecting to `new` or `edit` methods while adding/editing a Floating IP.
And with `super` we end up in the `button` method in [_GenericButtonMixin_](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/generic_button_mixin.rb#L43).
**How to test:**
Go to _Networks > Floating IPs_ and check if all the actions from the toolbar work.
=> Refactor FloatingIpController and its specs

app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb, app/helpers/application_helper/toolbar/vm_clouds_center.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1738584
Go to:
Compute -> Clouds -> Instances -> check one or more -> toolbar Power -> click Resume
Before:
Nothing happens in UI but there's an error in log
```ruby
FATAL -- : Error caught: [ActionController::RoutingError] invalid button action
/ManageIQ/manageiq-ui-classic/app/controllers/application_controller/explorer.rb:81:in `x_button'
```
After: **no Resume button**
Removing because:
- I didn't find any mention of `resume` with 
` VmOrTemplate.descendants.select{ |x| x.instance_methods.include?(:resume)}.count`, `VmOrTemplate.descendants.select{ |x| x.instance_methods.include?(:raw_resume)}.count`, ` VmOrTemplate.descendants.select{ |x| x.methods.include?(:resume)}.count` and ` VmOrTemplate.descendants.select{ |x| …
=> Delete Resume button for VMs and Instances

app/controllers/application_controller/miq_request_methods.rb, spec/controllers/application_controller/report_data_spec.rb, spec/support/report_helper.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1789153
Followup to https://github.com/ManageIQ/manageiq/pull/19701
At the very least, we know MiqExpression objects are in the YAML but other
custom classes could be in the YAML so we need to use YAML.load to return to the
prior behavior.
=> Use YAML.load to load classes beyond the basic types

app/controllers/miq_ae_tools_controller.rb, app/services/git_based_domain_import_service.rb, spec/controllers/miq_ae_tools_controller_spec.rb, spec/services/git_based_domain_import_service_spec.rb
Description
---------------
Refactoring the automate import error messages logic to let the backend produce them. Since the error message creation has been split between UI and backend, we are now moving it into the backend where it belongs.
This PR is related to https://github.com/ManageIQ/manageiq-automation_engine/pull/395
=> Refactoring automate import error messages.

app/controllers/application_controller/miq_request_methods.rb, app/controllers/application_controller/performance.rb, app/controllers/application_controller/timelines.rb, app/presenters/menu/yaml_loader.rb, app/services/charts_layout_service.rb, app/views/layouts/_perf_options.html.haml, spec/controllers/application_controller/report_data_spec.rb, spec/other/travis_spec.rb, spec/product/reports_spec.rb, spec/services/charts_layout_service_spec.rb
Followup to: https://github.com/ManageIQ/manageiq-ui-classic/pull/6596
=> Open and close file objects using read to avoid leaking

app/controllers/vm_remote.rb, app/helpers/application_helper/button/vm_native_console.rb, app/helpers/application_helper/toolbar/x_vm_center.rb, config/routes.rb, spec/helpers/application_helper/buttons/vm_native_console_spec.rb
Show native viewer button for redhat providers and allow
connection file to be downloaded after requiring it via task
related to BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1451594
Depends on:
* https://github.com/ManageIQ/manageiq-providers-ovirt/pull/452
* https://github.com/ManageIQ/manageiq/pull/19675
=> Native viewer

app/controllers/application_controller/ci_processing.rb, spec/controllers/application_controller/ci_processing_spec.rb, spec/controllers/resource_pool_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6606
It was not possible to reconfigure VMs displayed in any nested list, error occurred. The core of the problem was calling `reconfigurevms` method which does not exist, instead of `vm_reconfigure` from the `Reconfigure` [module](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/actions/vm_actions/reconfigure.rb#L47).
Originally, I've found the issue while displaying VMs through Resource Pool's textual summary.
**Before:**
**After:**
=> Enable reconfiguring VMs displayed in a nested list

app/controllers/application_controller/tags.rb, app/controllers/pxe_controller.rb, app/controllers/pxe_controller/pxe_servers.rb, app/helpers/application_helper/toolbar/pxe_image_center.rb, app/helpers/application_helper/toolbar/pxe_server_center.rb, app/helpers/application_helper/toolbar/pxe_servers_center.rb, app/helpers/application_helper/toolbar/windows_image_center.rb, app/helpers/pxe_helper/textual_summary.rb, app/views/pxe/_pxe_server_details.html.haml, config/routes.rb, product/views/PxeImage.yaml, product/views/WindowsImage.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1454712
Depends on https://github.com/ManageIQ/manageiq/pull/19612 (merged) and https://github.com/ManageIQ/manageiq/pull/19662 (merged)
Go to: Compute -> Infrastructure -> PXE
Before:
After:
=> Add Tags to PxeServer and its items

app/assets/stylesheets/main.scss
We need the variable definitions before the `import` calls to have all variables set correctly in PF. However, the styling code below the imports should not be overridden by the original code, so I'm making it `!important`. The idea is to eventually move the `import` calls out from `main.scss`, probably into the top-level `application.scss`.
@miq-bot add_label ivanchuk/no
=> Reorder the styling in main.scss, make pre-import styles !important

app/controllers/application_controller/compare.rb, app/controllers/application_controller/report_downloads.rb, app/helpers/optimize_helper.rb, config/routes.rb, spec/controllers/application_controller/compare_spec.rb, spec/controllers/dashboard_controller_spec.rb, spec/controllers/report_controller_spec.rb, spec/controllers/utilization_controller_spec.rb, spec/helpers/report_helper_spec.rb, spec/presenters/tree_builder_report_saved_reports_spec.rb
* when generating the PDF, use existing report resuts
that means separating the TXT/CSV branches from the PDF one
* extract method `report_print_options`
Fixes problem introduced (or surfaced) in:
https://github.com/ManageIQ/manageiq-ui-classic/pull/6367 reported here: https://github.com/ManageIQ/manageiq-ui-classic/issues/6493
When PDF was requested a task was fired to generate a new report result of type 'pdf'. However then the PDF generation is done via browser from HTML markup. For that the newly generated report results where useless so the previous ones where used prior to my change. So the new report result generation was unnecessary and the results where thrown away.
Important change:
* Newly the existing HTML is used, 
* no task is executed, no waiting.
* trying to separate paths …
=> Report results: fix export to PDF.

app/controllers/application_controller/policy_support.rb, spec/controllers/application_controller/policy_support_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6610
There was an issue in non explorer screens, after finishing managing policies of selected items (Resource Pools, Hosts, nested lists of VMs, Instances etc): flash message was not displayed. To display it, we need to put it into `session[:flash_msgs]`, the same as it is in some other places before redirecting.
**Before:**
**After:**
=> Display flash message after managing policies in non explorer screen

app/controllers/application_controller/explorer.rb, app/controllers/infra_networking_controller.rb, app/controllers/mixins/manager_controller_mixin.rb, app/controllers/provider_foreman_controller.rb, spec/controllers/application_controller/explorer_spec.rb, spec/controllers/infra_networking_controller_spec.rb, spec/controllers/mixins/manager_controller_mixin_spec.rb, spec/controllers/provider_foreman_controller_spec.rb, spec/controllers/vm_common_spec.rb
**Fixes BZ:** https://bugzilla.redhat.com/show_bug.cgi?id=1777493
**This PR:**
- prevents one extra calling of `replace_search_box` method in ManagerControllerMixin in `replace_right_cell` method, especially for `provider_foreman` and `automation_manager` controllers - this change fixes appearing Adv Search in _Config > Mgmt > Providers_ accordion which is not supported there, so it does not appear there anymore, and it works for any item in the tree in _Providers_ accordion in the appropriate screen
- adds `replace_search_box` method to `infra_networking` controllers to `update_partials` method where it is missing - according to the removing the method from ManagerControllerMixin => with such changes we avoid adding extra conditions in `replace_right_cell` in ManagerControllerMixin :) …
=> Hide Advanced Search in Config Mgmt Providers screen

app/views/miq_ae_customization/_dialog_sample.html.haml
Automation > Automate > Customization > Service Dialogs,
click a dialog, see right-side detail
before, if the dialog only has dynamic dropdowns, or only required non-dynamic dropdowns, no dropdown would get shown.
That's because they already have the .selectpicker class which hides the %select element, but the call to miqInitSelectPicker never happened outside the non-dynamic non-required branch, never rendering the selectpicker component.
now, all selects (including tags) should render in each case, with :multiple correctly set.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/5279
Cc @d-m-u
=> Dialog sample - fix render dropdowns

app/controllers/ops_controller/settings/upload.rb, spec/controllers/ops_controller/settings/upload_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1792185
This PR simply fixes the bug regarding importing Tags for VMs using a CSV file, introduced [here](https://github.com/ManageIQ/manageiq-ui-classic/pull/3643/files#diff-8d3cbf9c4fd28532293661e4b69b1abdL80-L83).
**Before:**
**After:**
---
**Exact steps to reproduce:**
1. Create a CSV file with tags for a VM, in an appropriate format, see [documentation](https://access.redhat.com/documentation/en-us/red_hat_cloudforms/5.0/html/general_configuration/configuration) and "4.1.1.4.6. Importing Tags for Virtual Machines"
2. Go to _Configuration > Settings_ accordion
3. Click on the region name in accordion
4. Click on _Tags_ tab
5. Go to _Import Tags_ tab, upload the CSV file
=> error:
```
[----] I, [2020-01-22T17:00:33.703791 …
```
=> Allow importing Tags for VM using a CSV file

app/controllers/mixins/generic_button_mixin.rb, app/controllers/resource_pool_controller.rb, spec/controllers/resource_pool_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6617
In this PR, I've simplified `button` method in `resource_pool` controller to use `button` method in `GenericButtonMixin`. With this refactoring, I've achieved to make editing selected VM displayed in a nested list (through Resource Pool's _Relationships_ table) work.
I've added also little changes to `GenericButtonMixin` to keep the original logic regarding renaming VM. This will help also other controllers to use `button` method in the mixin without adding extra conditions in those controllers, regarding renaming VM.
**Before:** (nothing happens)
**After:** (editing form being rendered successfully)
=> Refactor ResourcePool controller, make Edit VM through Resource Pool work

app/controllers/utilization_controller.rb, app/helpers/application_helper/button/miq_capacity.rb, app/helpers/application_helper/button/utilization_download.rb, app/helpers/application_helper/toolbar/miq_capacity_view.rb, spec/helpers/application_helper/buttons/miq_capacity_spec.rb, spec/helpers/application_helper/buttons/utilization_download_spec.rb
Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/6608
**Show toolbar when Report tab selected**
Go to Overview -> Utilization -> select a Provider -> click Report Tab -> No Download button
Before:
After:
**Do Not show toolbar when no data in Report**
Go to Overview -> Utilization -> select a Provider -> click Report Tab -> click another Provider -> click Download button and get an error
Before:
`[----] F, [2020-01-20T16:02:10.608136 #4597:3fe027b4a4b4] FATAL -- : Error caught: [NoMethodError] undefined method '[]' for nil:NilClass
/ManageIQ/manageiq-ui-classic/app/controllers/utilization_controller.rb:232:in 'summ_hashes'
/ManageIQ/manageiq-ui-classic/app/controllers/utilization_controller.rb:74:in 'report_download'`
After:
@miq-bot add_label wip, bug, toolbars, ivanchuk/no
=> Fix toolbar on Reports tab on Overview -> Utilization screen

app/controllers/ops_controller/diagnostics.rb
Now that we use only streaming refresh for vmware there is no longer a
need to reset the vim broker cache.
=> With streaming refresh reset_vim_cache not needed

app/controllers/application_controller/ci_processing.rb, spec/controllers/application_controller/ci_processing_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1782568
There was an issue regarding editing one Host displayed in a nested list, after navigating away from the editing screen with more Hosts selected for editing: multi Host edit screen was displayed instead of the screen for editing one Host we selected.
The problem was caused by not setting `session[:host_items]` properly. The value for the variable was updated/set only if we selected more than one Host in the nested list (`if obj.length > 1`). Now with the simple change in the original condition, `session[:host_items]` is set back to `nil` if we chose only one Host so then the proper screen for editing one Host can be [displayed](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/host_controller.rb#L130). …
=> Update session[:host_items] also if only one Host in a nested list was selected for editing

app/controllers/application_controller/advanced_search.rb, app/controllers/application_controller/filter/expression.rb, spec/controllers/application_controller/advanced_search_spec.rb, spec/controllers/application_controller/filter/expression_spec.rb
**Issue**: https://github.com/ManageIQ/manageiq-ui-classic/issues/6594
This PR fixes the bug in non-explorer screens regarding newly created filters. Such a filter was highlighted in accordion even when it was not applied. This was fixed by not setting `@edit[:expression][:selected]` right after saving the filter, only the `@edit[:expression][:exp_last_loaded]` which can be important for later actions.
Another bug was remaining the filter highlighed in accordion when the filter was cleared (by clicking on the blue "clear" in the title in the page). Again, this was caused by wrong value of `@edit[:expression][:selected]`, setting the value to nil was missing in `adv_search_clear` method.
**Before:**
After saving the new filter but not applying it, the filter is already highlighted in …
=> Make the filter not highlighted in accordion after it was created and not applied

app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/views/catalog/_svccat_tree_show.html.haml, product/views/ServiceTemplate.yaml, spec/controllers/catalog_controller_spec.rb, spec/views/catalog/_svccat_tree_show.html.haml_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6320
**DEPENDS ON:** https://github.com/ManageIQ/manageiq-decorators/pull/26 (merged)
This PR:
- adds a new column _Valid_ in the list view to display whether the Catalog Item/Bundle is valid or not
- displays warning as a flash message in the Catalog Item/Bundle details screen, if the item is invalid
- makes _Order_ button disabled for any invalid items
---
**After:**
_Services > Catalogs > Catalog Items_:
_Services > Catalogs > Service Catalogs_:
_Services > Catalogs > Service Catalogs_, details' screen of a selected Service:
_Services > Catalogs > Catalog Items_,  details' screen of a selected Service:
=> Identify invalid Catalog Items/Bundles in the UI

app/controllers/host_controller.rb, app/helpers/application_helper.rb, app/views/layouts/listnav/_show_list.html.haml, spec/views/layouts/listnav/_show_list.html.haml_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/4615
This PR is supposed to take care about `_show_list` template, to make it readable, and also it fixes the error regarding cloning VMs from a nested list and also one another bug in the template.
**How to reproduce the error:**
1. Go to _Compute → Infrastructure → Hosts / Nodes_
2. Click on some Host to display its summary
3. Click on VMs in _Relationships_ table
4. Select such VMs in the list (checkboxes), that _Clone_ action is not applicable on them
5. Choose _Lifecycle → Clone selected item_
=> error:
```
[----] I, [2020-01-08T16:28:25.647485 #21081:5f6d7e0]  INFO -- :   Rendered /home/hstastna/manageiq/manageiq-ui-classic/app/views/layouts/listnav/_show_list.html.haml (1582.2ms)
[----] I, [2020-01-08T16:28:25.647765 …
```
=> Refactor _show_list template and fix error regarding cloning VMs from a nested list

app/helpers/application_helper/button/zone_delete.rb, spec/helpers/application_helper/buttons/zone_delete_spec.rb
This logic was duplicated, so we can use the version in core
I'm not sure why we were preventing deletion when a zone had schedules, but the zone model has a `dependent_destroy` so I figure we can ignore those.
~~Requires https://github.com/ManageIQ/manageiq/pull/19770~~ Merged
=> Use the backend logic for zone deletion

app/assets/javascripts/components/generic_object/main-custom-button-form.js
This removes 'hosts' 'service_template' 'request' and cleans a code a little bit.
Go to Automate -> Automation -> Generic Objects -> Add a Custom Button and give it some Attributes/Values -> save it -> edit it again -> see that Attributes/Values has some extra values
Before:
After:
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1753237
Continues https://github.com/ManageIQ/manageiq-ui-classic/pull/6322
=> Fix extra attributes in GOD CustomButton edit page

app/assets/javascripts/controllers/tree_view_controller.js, app/assets/javascripts/miq_angular_application.js, app/controllers/generic_object_definition_controller.rb, app/controllers/miq_ae_customization_controller.rb, app/controllers/mixins/breadcrumbs_mixin.rb, app/javascript/components/breadcrumbs/index.js, app/javascript/components/breadcrumbs/index.jsx, app/javascript/components/breadcrumbs/on-click-functions.js, app/javascript/spec/breadcrumbs/breadcrumbs.spec.js, app/javascript/spec/breadcrumbs/on-click-functions.spec.js, app/javascript/spec/helpers/miqAjax.js, app/views/generic_object_definition/_generic_object_definition_form.html.haml, spec/controllers/miq_ae_customization_controller_spec.rb, spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740853
**Description** 
Refactoring
- removes RxJS for calling tree node select (I was trying if we can solve the nonfunctional link by calling this method, however we cannot call `tree_select` outside the explorer view.. :crying_cat_face: )
- fixes missing `x` in the name of the component
Adds options to `breadcrumbs_options`
- `:disable_tree` will disable links to tree nodes (use when the tree is not on the page, you cannot use its links)
- `:to_explorer` (need to be used together with `disable_tree`) which will add a link to explorer (which is set as this variable) to the `[-2]` item of breadcrumbs, so user can return to the explorer (service_dialog editing/creating, GOD editing/adding and probably some more place)
Problem: Tree links …
=> Fix tree breadcrumbs on explorer screen missing the tree

app/javascript/http_api/fetch.js
In https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/37, we are adding a new API endpoint which delivers a binary response (`content-disposition: attachment`) intended for the UI to make available as a file download. Rationale for the decision to handle the file download via the API instead of a UI worker can be found in the relevant discussions at https://github.com/RedHatCloudForms/cfme-migration_analytics/issues/19 and https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/33.
Currently, [the `API` methods provided here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/javascript/http_api/api.js) (which we must use to handle authentication) assume API responses will always be JSON, and [call `response.json()` as part of processing the `fetch()` …
=> Allow non-JSON responses in miqFetch (add `options.skipJsonParsing`)

.gitignore, cypress.json, cypress/integration/ui/login.spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package.json
cc @himdel @chessbyte 
This PR is a basic POC of writing integration tests with [cypress](https://www.cypress.io/).
I chose cypress because I like how it *doesn't* use selenium/phantomjs, but instead spins up a real headless browser and interacts with it directly.  The tooling for it is really good with a live interactive UI with time travel and DOM selector discovery, CLI support, screenshot generation on failure, video generation of the run, and a lot more.  It only supports Chrome (and Chromium/Canary/Electron) right now, but they are very close to getting Firefox.  Even so, for 1st tier testing Chrome should be more than good enough.
In a separate tab, run `bundle exec rails server`, then...
```
$ npm run cypress:run
> manageiq-ui-classic@1.0.0 cypress:run …
```
=> Use cypress for integration tests

app/controllers/ops_controller/settings/common.rb, app/helpers/ops_helper.rb, app/views/ops/_settings_server_tab.html.haml, spec/controllers/ops_controller/settings/common_spec.rb
This PR changes the update logic for a server's zone to handle and display any validation errors one of which was added in https://github.com/ManageIQ/manageiq/pull/19789/commits/7174cc8643f096899c83e2ce3e74d19349c89de4
Additionally, after testing this out, it seemed like not such a great UX so I also disabled the drop-down when we find that it's not possible to change zones and added a title text to inform the user why the box was disabled.
Depends on https://github.com/ManageIQ/manageiq/pull/19789
=> Deal with zones when running in pods

spec/helpers/application_helper/buttons/storage_scan_spec.rb
`.ext_management_systems` was removed from Storage in https://github.com/ManageIQ/manageiq/pull/19754
fixing the specs to use `.ext_management_system` (singular).
Cc @kbrock 
Fixes red travis:
```
1) ApplicationHelper::Button::StorageScan when feature is supported #calculate_properties with valid credentials for this Datastore behaves like an enabled button is expected to be truthy
Failure/Error: expect(subject[:enabled]).to be_truthy
expected: truthy value
got: false
Shared Example Group: "an enabled button" called from ./spec/helpers/application_helper/buttons/storage_scan_spec.rb:35
2) ApplicationHelper::Button::StorageScan when feature is supported #calculate_properties but no EMS has valid credentials for the Datastore behaves like a disabled button is expected to eq "There are no …
```
=> StorageScan button spec - fix spec after .ext_management_systems removal

app/controllers/mixins/ems_common/angular.rb, spec/controllers/ems_cloud_controller_spec.rb, spec/controllers/ems_infra_controller_spec.rb
Core removal PR: https://github.com/ManageIQ/manageiq/pull/19346
see https://github.com/ManageIQ/manageiq/pull/19512
``` ruby
DEPRECATION WARNING: validate_credentials_task is deprecated and
will be removed from ManageIQ K-release (use verify_credentials_task instead)
(called from block (4 levels) in <top (required)> at
spec/models/mixins/authentication_mixin_spec.rb:293)
```
"If you want it solved a different way, just give the word" which word might that be exactly anyway, one wonders
=> Remove deprecated validate_creds_task

app/controllers/mixins/ems_common/angular.rb, spec/controllers/ems_cloud_controller_spec.rb, spec/controllers/ems_infra_controller_spec.rb
This reverts commit 2f00acf9fb8eb900b25a3e78a5091960e51c3f46, reversing changes made to 60a70b2d5ef61711e0fe58c432ee61bce60d88fd.
https://github.com/ManageIQ/manageiq-ui-classic/pull/6664 was merged before the backend was ready, credential validation is broken right now
=> Revert #6664 to fix credential validation

lib/tasks/manageiq/ui_tasks.rake
Now that APP_ROOT is defined, the original code now works properly.
@himdel Please review.  Can you hep me verify that this also doesn't break other workflows?  With this change in place, I can do, from within manageiq-ui-classic, `bundle exec rake update:ui; bundle exec rails s`, and it works.
=> Change update:ui to no longer worry about missing engines

app/javascript/components/async-credentials/async-provider-credentials.jsx, app/javascript/forms/mappers/formsFieldsMapper.jsx
This component is a wrapper around `AsyncCredentials` with a pre-set validation function that in the future will validate the credentials [using the API](https://github.com/ManageIQ/manageiq-api/pull/682).
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
Related bug: https://github.com/ManageIQ/manageiq-ui-classic/issues/6656
=> Introduce a DDF component for provider credentials validation

app/assets/javascripts/remote_consoles/spice.js, app/assets/javascripts/remote_consoles/vnc.js, app/assets/javascripts/remote_consoles/webmks.js
The remote console code is still using the asset pipeline and `// require jquery` won't find the npm package, and loads the `jquery-rails` gem. Switching to the node_modules version.
cc @skateman, @Fryguy
=> remote_consoles - use jquery from npm, not jquery-rails

app/javascript/components/async-credentials/async-credentials.jsx
Without this information, we have no knowledge in the validation function about the depending fields.
@miq-bot add_reviewer @Hyperkid123
=> Send validationDependencies with when validating credentials

app/javascript/components/async-credentials/async-provider-credentials.jsx
The provider validation component doesn't need to send all the data to the API. Especially if there are more than one validation components in a single form, because there's no way to distinguish between which one is being validated. My solution is to just send the fields under the component itself + the explicitly specified dependencies.
=> EMS validation: send only the listed fields to the API

spec/controllers/automation_manager_controller_spec.rb, spec/controllers/provider_foreman_controller_spec.rb, spec/controllers/report_controller_spec.rb
Introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/2383 . 
Tests will be replaced by https://github.com/ManageIQ/manageiq-ui-classic/pull/6672 with `cypress` ones.
Before:
After:
=> Remove pending specs

app/controllers/application_controller.rb, app/controllers/application_controller/performance.rb, app/controllers/application_controller/performance/options.rb
Object defined in the ui-classic codebase can cause loading errors if serialized in the session. The session is being accessed from the API as well and if there's an instance of MiQ running without the ui-classic codebase, the serialized object cannot be deserialized. 
As a solution I'm converting the object's data into a hash and whenever it is loaded, I create a new instance manually. However, I'm not familiar with the area and I have no idea how to test this.
@miq-bot add_reviewer @PanSpagetka 
@miq-bot add_label bug, ivanchuk/no
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6534
=> Do not store Performance::Options instances in the session

cypress/README.md, cypress/fixtures/example.json, cypress/integration/ui/menu.spec.js, cypress/support/commands.js, package.json
Cypress was added in #6646,
this updates it to 4.0,
adds a couple of helpers for navigating around the menus,
and adds a menu spec.
Helpers added here:
* `cy.login()` - logs in, the current implementation is wrong, but works, will replace with cookie & token injection in a separate PR
* `cy.menu('Automation', 'Automate', 'Customization')` - navigate in the menu
* `cy.menuItems()` - returns an object tree parsed from the actual menu items
* `cy.expect_explorer_title(text)` - assertion that we're on an explorer screen with a specific title
* `cy.expect_show_list_title(text)` - assertion that we're on an show_list screen with a specific title
Tests added:
* ensure menu structure is sane, click through a few menu items and validate screen titles, ensure last section url works
* (SKIPped for …
=> Cypress: menu helper

app/javascript/components/workers-form/workers-form.jsx
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1799443
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/5528
1. Navigate to Configuration -> Settings -> (appliance) -> Workers
2. Change `Refresh worker` `Memory threshold` to something else
3. Change `C & U Data Collectors` `Memory threshold` and `Count` to something else
4. Save the changes
5. Refresh the page
Before:
Values stay same as original ones
After:
Values are changed to ones you selected
Just making loaded data same as sent one. See https://github.com/ManageIQ/manageiq-ui-classic/blob/6a179e6a9ec1ee5bc8964d3e4487adf328dc53fb/app/javascript/components/workers-form/workers-form.jsx#L39-L44 and https://github.com/ManageIQ/manageiq-ui-classic/blob/6a179e6a9ec1ee5bc8964d3e4487adf328dc53fb/app/j …
=> Fix saving of ems_refresh_worker and ems_metrics_collector_worker

app/controllers/ops_controller/ops_rbac.rb, app/views/ops/_rbac_group_details.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1784243
before
after
=> Added new Detailed Description field to Group edit/details screen

app/controllers/ops_controller/settings/schedules.rb
The line became extraneous with commit https://github.com/ManageIQ/manageiq-ui-classic/commit/dad7b825281d37a844dfd40e8f552311bda7141a#diff-27e8e9795d5f4a9a5087545e103d4e51R378
=> Remove extraneous line from OpsController::Settings::Schedules

app/controllers/host_aggregate_controller.rb, app/controllers/mixins/ems_common.rb, spec/controllers/host_aggregate_controller_spec.rb, spec/controllers/mixins/ems_common_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6323
**This PR:**
- sets `params[:display]` from `@display` also for Host Aggregates, in the `button` method in _EmsCommon_ mixin
- fixes "wrong" redirect after **editing Host Aggregate** displayed through provider's summary page, we end up in a same page as before the action, when
- clicking on _Cancel_ button in Edit page
- clicking on _Save_ button
- succesful saving of the change
- unable to save changes because of missing credentials 
- fixes "wrong" redirect after **deleting Host Aggregate**
- selected from the list/nested list of Host Aggregates (through provider)
- from textual summary of Host Aggregate
- fixes "wrong" redirect after **adding Host to selected Host Aggregate** displayed through provider's summary …
=> Redirect to proper controller for Edit and other actions on selected Host Aggregate

cypress/README.md, cypress/integration/ui/toolbar.spec.js, cypress/support/commands.js
Adds more cypress helpers:
* `cy.accordion('Service Templates')` - expands the accordion (if not already expanded) and returns it for subsequent find,
* `cy.toolbarItem('Configuration', 'Edit this VM')` - find a toolbar item and returns a promise with details `{id, label, icon, disabled}`
* `cy.toolbar('Configuration', 'Edit this VM')` - clicks a toolbar item
And a test testing a bunch of toolbar items,
and a fix to menu helper to respect the section when an item with same name exists in multiple sections.
=> Cypress - toolbars (and accordion)

app/services/ems_infra_dashboard_service.rb, spec/services/ems_infra_dashboard_service_spec.rb
Affected values are in circle.
before
after
@miq-bot add_label ui
https://bugzilla.redhat.com/show_bug.cgi?id=1776684
=>  Limit metric rollups to just default time profile

app/controllers/miq_ae_class_controller.rb, app/views/miq_ae_class/_method_inputs.html.haml
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1794780
* Load inputs for Ansible* methods.
* Display Hosts for Ansible Tower Job Template detail view.
ping @mzazrivec
=> Load inputs for Ansible* methods.

app/assets/javascripts/components/generic_object/main-custom-button-form.js
If not API will always create a new `ResourceAction`.  Related to https://github.com/ManageIQ/manageiq-api/pull/728
@miq-bot add_label wip, bug, ivanchuk/no
=> Send resource_id via API when editing CustomButton

app/javascript/components/async-credentials/password-field.jsx, app/javascript/components/pxe-servers-form/pxe-server-form.schema.js, app/javascript/forms/mappers/formsFieldsMapper.jsx, app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap, app/javascript/spec/async-credentials/password-field.spec.js, app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
This field is responsible for the passwords in credential validation forms, however, its naming was a little confusing. I needed a couple of days to actually hunt this component down and understand how this whole password hiding thing in the context of validation works.
I don't want others to get into this trap and also I would like to use this component in provider schemas, so I'd like to rename it to something more meaninfgul.
@miq-bot add_label react, enhancement
=> Rename SecretSwitchField to PasswordField in component mappings

app/javascript/components/async-credentials/async-credentials.jsx, app/javascript/components/async-credentials/password-field.jsx, app/javascript/components/pxe-servers-form/pxe-server-form.schema.js, app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap, app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap, app/javascript/spec/async-credentials/password-field.spec.js, app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
When working with the `AsyncCredentials` component in editing mode, it is not enough to set the `edit` prop on the parent component, this value needs to be passed down to the child password component(s). This is very impractical as the schema has to contain a redundant value in a nested structure and it causes trouble with the provider forms.
One solution would be to have parametrized provider forms, which so far I was able to avoid successfully. In order to keep the provider forms as simple as possible, I am proposing to reuse the existing `PasswordContext` to inherit the `edit` prop further to the password component. To make the code a little cleaner, I also rewrote the `Context.Consumer` into a hook.
@miq-bot add_label …
=> Inherit `edit` under the AsyncCredentials using the existing context

app/javascript/components/async-credentials/password-field.jsx
Missed this from https://github.com/ManageIQ/manageiq-ui-classic/pull/6706
=> Drop the obsolete `edit` from PasswordField.defaultProps

app/assets/javascripts/components/generic_object/custom-image.js, app/controllers/picture_controller.rb
In generic object, we allow upload of custom svg images, but the code only matches the old image/svg,
but can't handle image/svg+xml which is what chrome now uses.
Similarly, PicturesController sets the type to image/svg on download, which causes the browser to render a placeholder instead.
Fixing to use svg+xml for mime type, but keep svg as extension.
Cc @Fryguy (assuming that's the way we go with the svg issue)
(This does not deal with the other places which currently don't allow svgs.)
=> Fix SVG upload, render

app/views/miq_request/_prov_field.html.haml, app/views/shared/views/_prov_dialog.html.haml
The user will now be able to select a specific disk format and sparsity
for the disks with validation.
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1726590
Depends on: https://github.com/ManageIQ/manageiq-schema/pull/459
Depends on: https://github.com/ManageIQ/manageiq/pull/19849
Related to: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/453
=> Change disk options in oVirts provisioning dialog

app/assets/javascripts/components/generic_object/main-custom-button-form.js, spec/javascripts/components/generic_object_definition/main-custom-button-form_spec.js
`custom_button.uri_attributes=` saves to `custom_button.resource_action_ae_attributes` with some checks so UI should send the data only via `uri_attributes` otherwise it gets rewritten by API.
Related to https://github.com/ManageIQ/manageiq-api/pull/728 .
=> Use uri_attributes in CustomButton instead of ae_attributes 

.eslintrc.json, app/assets/javascripts/.eslintrc.json, app/javascript/components/async-credentials/async-provider-credentials.jsx, app/javascript/components/pxe-servers-form/pxe-server-form.jsx, app/javascript/components/tree-view/hierarchical-tree-view.jsx, app/javascript/spec/toolbar-actions/toolbar-actions-generic.spec.js
No point in enforcing camelCase when all API properties are underscore_cased.
Disables the [camelcase rule](https://eslint.org/docs/rules/camelcase).
=> eslint: disable camelcase rule

app/controllers/provider_foreman_controller.rb, app/views/provider_foreman/explorer.html.haml
- Render 'layouts/empty' partial when replacing right cell after accordion is switched from "Configured Systems" to "Providers" when there are no Foreman Providers in the database.
- Also render "layouts/empty" partial from explorer view only when active tree is Providers tree, existing code was rendering empty partial when returning back to explorer if "Configured Systems" was the last active accordion.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741310
before
after
=> Render 'layouts/empty' partial correctly.

app/helpers/application_helper/toolbar/physical_chassis_list_center.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741185
This should also fix the issue reported in https://bugzilla.redhat.com/show_bug.cgi?id=1741191
before
after
=> Enable buttons only when 1 or more items are selected from the list

app/javascript/components/async-credentials/password-field.jsx
The google cloud provider has a `helperText` on this field...
@miq-bot add_label enhancement, react
@miq-bot add_reviewer @rvsia
=> Implement helperText on the PasswordField component

app/presenters/menu/default_menu.rb, app/views/support/show.html.haml, config/settings.yml
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6083
=> Use product settings for docs & links

app/controllers/service_controller.rb, spec/controllers/service_controller_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1803947
The first commit in this PR fixes the error occurred after opening _Advanced Search_ in _My Services_ screen again (see the first steps to reproduce in the BZ) and also makes Adv Search/expression editor work properly. The second commit fixes another scenario I've found in Advanced Search:
1. Go to _Services > My Services_
2. Click on some Service **in accordion**
3. Click on _Active/Retired Services_ node in accordion
4. Open _Advanced Search_
---
When accessing the page for the very first time, `explorer` method is called in _ServiceController_, and with this method `@edit` is properly set. Then in `get_node_info` (called by `replace_right_cell` in `explorer`), `session[:edit]` is …
=> Make Advanced Search in Services screen reactive also in other tabs

app/helpers/application_helper/toolbar/miq_groups_center.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1803952
Setting `ApplicationHelper::Button::RbacGroupEdit` for "Edit" button to be enabled/disabled in the toolbar in the list view of _Groups_ works only for toolbar in the details page of a Group. `@record` is required to be set. `disabled?` method checks if the `@record` is read only. However, there isn't any `@record` set while displaying list of Groups so it did not work at all in such a screen.
Fortunately, after clicking on _Edit the selected Group_ in the toolbar `rbac_edit_reset` is called, in `rbac_group_edit` in _OpSController_. This method 'finds' the appropriate record according to the id in `params[:miq_grid_checks]` together with checking if the record is read only, and also sets the appropriate flash message which is …
=> Allow editing Groups from the list view

app/controllers/provider_foreman_controller.rb, app/presenters/tree_builder_configuration_manager.rb, app/presenters/tree_builder_configuration_manager_configured_systems.rb, spec/controllers/provider_foreman_controller_spec.rb
- ConfigurationManager
- ConfiguredSystem
- ConfigurationProfile
=> Display all of the following, not just Foreman

app/controllers/application_controller.rb, app/controllers/application_controller/miq_request_methods.rb, app/controllers/cloud_network_controller.rb, app/controllers/cloud_subnet_controller.rb, app/controllers/cloud_tenant_controller.rb, app/controllers/cloud_volume_backup_controller.rb, app/controllers/cloud_volume_controller.rb, app/controllers/floating_ip_controller.rb, app/controllers/host_aggregate_controller.rb, app/controllers/mixins/generic_form_mixin.rb, app/controllers/network_router_controller.rb, app/controllers/security_group_controller.rb, app/controllers/vm_cloud_controller.rb, spec/controllers/application_controller_spec.rb, spec/controllers/cloud_network_controller_spec.rb, spec/controllers/cloud_subnet_controller_spec.rb, spec/controllers/cloud_tenant_controller_spec.rb, spec/controllers/cloud_volume_backup_controller_spec.rb, spec/controllers/cloud_volume_controller_spec.rb, spec/controllers/floating_ip_controller_spec.rb, spec/controllers/mixins/generic_form_mixin_spec.rb, spec/controllers/network_router_controller_spec.rb, spec/controllers/security_group_controller_spec.rb, spec/controllers/vm_cloud_controller_spec.rb
**Related PR and comment:** https://github.com/ManageIQ/manageiq-ui-classic/pull/6649#issuecomment-587464646
**This PR:**
- adds new `last_screen_url` and uses it instead of `@breacrumbs[-1][:url]` or `@breadcrumbs.last[:url]`
- I used the name `last_screen_url` and not `last_breadcrumbs_url` because of the plans to get rid of usages of `@breadcrumbs`
- updates `cancel_action` and renames it to `flash_and_redirect` (which is more accurate and it is not used only while canceling some actions) in _GenericFormMixin_ module - this fixes the issue in some controllers with displaying (orange) warning flash message instead of successful one after user cancels some action
- I left _VmCloud_ controller as it is with the original `cancel_action` because it differs from what it is in …
=> Use new last_screen_url for redirecting and update cancel_action in GenericFormMixin

spec/shared/controllers/shared_example_for_download_summary_pdf.rb
Within `spec/shared/controllers/shared_example_for_download_summary_pdf.rb` there is this partial defined:
`allow(controller).to receive(:tagdata).and_return(nil)`
However, there's no `tagdata` method defined on any controllers, so if strict partial validation is enabled, the result is an error like this:
```
6) VmCloudController download pdf file request returns 200
Failure/Error: allow(controller).to receive(:tagdata).and_return(nil)
#<VmCloudController:0x00005642f3a63650 @_action_has_layout=true, @_routes=nil ...snip...> does not implement: tagdata
```
There is, however, a method called `get_tagdata`, so I'm assuming that's what was meant here. Perhaps it was changed at some point and this simply wasn't updated. In any case, updating it eliminates about 80 errors overall.
Part of the …
=> Remove invalid tagdata stub

spec/views/dashboard/login.html.haml_spec.rb
With strict partials enabled, we can see that the `view` doesn't implement a `current_tenant` method, nor does the `User` model implement a `mode` method.
Removing these had no effect. The specs still pass.
Part of the cleanup effort at https://github.com/ManageIQ/manageiq-ui-classic/issues/6734
=> Remove invalid partials from login specs that aren't used

spec/services/cloud_topology_service_spec.rb
With strict partials enabled, the current cloud topology service specs will raise this error:
`CloudTopologyService ... does not implement: retrieve_providers`
Removing these partials had no effect, they still pass.
Part of the spec cleanup effort at https://github.com/ManageIQ/manageiq-ui-classic/issues/6734
=> Remove invalid partials from cloud topology service specs

app/controllers/application_controller/advanced_search.rb, app/presenters/tree_builder_ops_rbac_features.rb, app/views/layouts/_adv_search_body.html.haml, app/views/layouts/_adv_search_footer.html.haml, spec/presenters/tree_builder_ops_rbac_features_spec.rb
This PR addresses issues mention in https://github.com/ManageIQ/manageiq-ui-classic/pull/6253
Core PR https://github.com/ManageIQ/manageiq/pull/19916
before any user could add/delete global filters 
after only user can add/delete global filter if they have access to the new feature
user without access to "Add Global Filter"
user with access to "Add Global Filter", have access to "Delete" button and "Global Search" checkbox
=> Allow add/delete of global filters based upon user's allowed features

app/presenters/tree_builder_automate_catalog.rb
The disabled domains should not be displayed in automate entrypoint trees. 
cc @tinaafitz 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740915
=> Do not display disabled domains in automate entrypoint selections

spec/controllers/catalog_controller_spec.rb
This PR removes invalid partials that cause errors if strict partial validation is enabled. Specifically, there is no `ApplicationController.fetch_path` method, nor is there a `tag_edit_build_entries_pulldown` method for the controller.
Removing these had no effect, i.e. the specs still pass.
Part of the cleanup effort at https://github.com/ManageIQ/manageiq-ui-classic/issues/6734
=> Remove invalid partials from catalog controller specs

package.json
patternfly-react [2.39.15](https://github.com/patternfly/patternfly-react/compare/patternfly-react@2.39.14...patternfly-react@2.39.15) is the newest release and causes a production only bug...
VM1387 vendor-b2ef7d1….js:25 Uncaught ReferenceError: Cannot access 'Lc' before initialization
at Module.<anonymous> (VM1387 vendor-b2ef7d1….js:25)
at f (VM1390 runtime-06564b9….js:1)
at VM1387 vendor-b2ef7d…4efb994af989.js:111
at Object.<anonymous> (VM1387 vendor-b2ef7d…4efb994af989.js:111)
at f (VM1390 runtime-06564b9….js:1)
at Module.1145 (VM1389 component-def…a27d403918d91a.js:1)
at f (VM1390 runtime-06564b9….js:1)
at t (VM1390 runtime-06564b9….js:1)
at Array.r [as push] (VM1390 runtime-06564b9….js:1)
at VM1389 component-def…a27d403918d91a.js:1
the file being `VerticalNavItemHelper.js:360`.
This …
=> Set patternfly-react to 2.39.14 exactly

app/presenters/tree_builder_vandt.rb
The `ovirt` provider includes `ExternalDistributedVirtualSwitch` objects in the provider folder hierarchy which causes a crash on the `Providers -> Infrastructure -> VMs and Templates` screen. We don't really want to display these switches in that tree, so by skipping them from the ancestry hiearachy the problem is solved.
@miq-bot add_label bug, jansa/yes?
cc @gekorob please review it
=> Do not include switches into VMs and Templates tree

package.json, yarn.lock
Jansa version of https://github.com/ManageIQ/manageiq-ui-classic/pull/6745,
with `yarn.lock` changes added.
Force patternfly-react 2.39.15 beause 2.39.14 is causing a production-only error... `Cannot access 'Lc' before initialization`
@simaishi I have not seen this in jansa, but it is breaking master builds and the version is the same..
=> [JANSA] Set patternfly-react to 2.39.14 exactly

app/controllers/service_controller.rb, spec/controllers/service_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6708
Calling `listnav_search_selected` in `load_adv_search` in _ServiceController_ caused that `@edit[@expkey][:exp_table]` was changed to the expression which was loaded **before** the new filter was saved. So this is why after saving the new filter, the 'previous' expression was suddenly displayed in _Advanced Search_, not the last created one. Usually in other controllers, `listnav_search_selected` is called in a different situation - when we want to apply some existing filter (or to clear it) and not when we save/create a new filter.
Moreover it is absolutely unnecessary to call the whole `load_adv_search` in _ServiceController_ regarding this situation. But we need the method for applying filters in accordion from from …
=> Display newly saved expression in Advanced Search in My Services

spec/views/miq_request/_prov_vm_grid.html.haml_spec.rb
At the moment within `spec/views/miq_request/_prov_vm_grid.html.haml_spec.rb ` there are several stubbed methods that were inadvertently applied to `Array` instead of to the actual vm they were meant to apply to. With strict partials enabled this will cause failures.
Since an array doesn't appear to be necessary here, I removed it. The specs still pass.
=> Fix vm factory in prov_vm_grid haml spec

spec/helpers/host_helper/textual_summary_spec.rb
At the moment with strict partials enabled you will see several errors like this:
```
1) HostHelper::TextualSummary#textual_group Authentication Status
Failure/Error: allow(self).to receive(:textual_authentications).and_return([])
#<RSpec::ExampleGroups::HostHelperTextualSummary::TextualGroup_8 "Authentication Status" (./spec/shared/helpers/textual_summary_helper_methods.rb:24)> does not implement: textual_authentications
Shared Example Group: "textual_group" called from ./spec/helpers/host_helper/textual_summary_spec.rb:66
```
This is testing module methods, so my solution was to simply include the module into the test itself, since the `before` block is applying partials to `self`.
Normally I would create a dummy class and extend the module on it, but with all these shared examples I …
=> Mixin the TextualSummaryHelper to fix invalid partials

spec/helpers/vm_helper/textual_summary_spec.rb
At the moment with strict partials enabled you will see several errors like this:
```
1) VmHelper::TextualSummary #textual_server
Failure/Error: allow(self).to receive(:textual_key_value_group).and_return([])
#<RSpec::ExampleGroups::VmHelperTextualSummary "#textual_server" (./spec/helpers/vm_helper/textual_summary_spec.rb:2)> does not implement: textual_key_value_group
```
This is testing module methods, so my solution was to simply include the module into the test itself, since the before block is applying partials to self.
Followup to https://github.com/ManageIQ/manageiq-ui-classic/pull/6750, but this one applies to the vm_helper instead of the host_helper.
=> Mixin the TextualSummaryHelper to fix invalid partials, part 2

spec/controllers/ems_physical_infra_controller_spec.rb
Enabling strict partials reveals that the `User` object does not implement a `server_timezone` method.
This PR removes that stub, which had no effect. The specs still pass.
=> Remove invalid partial from EmsPhysicalInfraController specs

spec/controllers/mixins/checked_id_mixin_spec.rb
Currently the `CheckedIdMixin` specs will fail with strict partials enabled because there's no `current_user` defined on the object. As far as I can tell this method isn't required by the mixin, nor used by the specs. Removing them had no effect.
While I was here I refactored the way the object mixed in the module, and removed a gratuitous `send` call.
Part of the cleanup effort brought up at https://github.com/ManageIQ/manageiq-ui-classic/issues/6734
=> Remove invalid partials, refactor unused factories in CheckedIdMixin

app/javascript/components/async-credentials/async-credentials.jsx, app/javascript/components/async-credentials/async-provider-credentials.jsx, app/javascript/components/async-credentials/password-field.jsx, app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap, app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap, app/javascript/spec/async-credentials/async-credentials.spec.js, app/javascript/spec/async-credentials/password-field.spec.js
The `password-field` component depends on the `async-credentials` as a parent component, which means that it can't be used without a validation. However, some providers (openstack) don't implement credential validation for certain endpoints (ssh key).
The binding between the two components is the `PasswordContext`, which be eliminated by *conditionally passing* the `edit` boolean and the `parent` component's name as a prop. I also had to add a test on the existence of the `parent`. By introducing the `validate` prop on the `async-credentials` the component can be extended to be able to render the underlying fields without validation and with the *conditional passing* of the `edit` boolean. 
@miq-bot add_label react
=> Make the password-field component context-free and usable without validation

spec/helpers/cloud_tenant_helper/textual_summary_spec.rb, spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb
At the moment with strict partials enabled you will see several errors like this:
```
1) EmsPhysicalInfraHelper::TextualSummary#textual_group Relationships
Failure/Error: allow(self).to receive(:textual_authentications).and_return([])
#<RSpec::ExampleGroups::EmsPhysicalInfraHelperTextualSummary::TextualGroup_3 "Relationships" (./spec/shared/helpers/textual_summary_helper_methods.rb:24)> does not implement: textual_authentications
Shared Example Group: "textual_group" called from ./spec/helpers/ems_physical_infra_helper/textual_summary_spec.rb:14
```
Followup to #6750, but this one applies to the ems_physical_infra_helper instead of the host_helper.
Edit: Did the same for the cloud tenant helper while I was here.
=> Mixin the TextualSummaryHelper to fix invalid partials, part 3

app/helpers/textual_summary_helper.rb, spec/helpers/ems_cloud_helper/textual_summary_spec.rb
With strict partials enabled you will see failures from the `EmsCloudHelper::TextualSummary` specs like this:
```
1) EmsCloudHelper::TextualSummary#textual_groups textual_group_smart_management Smart management
Failure/Error: allow(self).to receive(:textual_authentications).and_return([])
#<RSpec::ExampleGroups::EmsCloudHelperTextualSummary::TextualGroups::TextualGroupSmartManagement "Smart management" (./spec/shared/helpers/textual_summary_helper_methods.rb:13)> does not implement: textual_authentications
Shared Example Group: "textual_group_smart_management" called from ./spec/helpers/ems_cloud_helper/textual_summary_spec.rb:57
```
~~Here I decided to add an interface method in the `TextualSummary` module. Since there is no internal logic checking for its definition, it should be safe. …
=> Add role_allows? interface to TextualSummaryHelper

app/javascript/components/workers-form/workers-form.jsx, app/javascript/components/workers-form/workers.schema.js, app/javascript/spec/workers-form/workers-form.spec.js
`MiqVimBrokerWorker` was removed in https://github.com/ManageIQ/manageiq-providers-vmware/issues/484
=> removing the setting
Fixes #6758
=> workers-form: remove vim_broker_worker

app/controllers/mixins/actions/vm_actions/reconfigure.rb
This is a proposal to allow the ovirt provider to define available vlans
for the NICs reconfiguration view.
Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/478
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1751151
=> Show also external vlans in nic reconf

app/javascript/forms/data-driven-form.jsx
In some cases the mapper needs to be enhanced with super-exotic stuff that is not usable anywhere else. The linter is complaining about the `PropTypes.object` but I don't know what else could I put there to make it happy.
=> Allow optional custom form field mapping for MiqFormRenderer

app/controllers/ops_controller/ops_rbac.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1813375
This PR corrects the typo and with the fix, it allows adding new and displaying details page of a Group, when there is a Category with **_Show in Console_** option set to **_No_**.
---
**Before:** Trying to add a new group, nothing happens in the UI:
**After:**
=> Correct typo and allow adding new and displaying details page of a Group

app/javascript/forms/data-driven-form.jsx
```
Warning: Failed prop type: The prop `formFieldsMapper.function () { [native code] }` is marked as required in `MiqFormRenderer`, but its value is `undefined`.
in MiqFormRenderer (created by ConnectFunction)
in ConnectFunction (created by WorkersForm)
in div (created by Grid)
in Grid (created by WorkersForm)
in WorkersForm
in Provider
```
introduced in #6769, cc @skateman ,  @Hyperkid123 
No point in validating `formFieldsMapper` in `MiqFormRenderer`, we're just passing this unaltered to DDF FormRender, that's where that validation should happen.
The bug is that all Object field names are strings, so `{ [PropTypes.string]: 123 }` becomes `{ "function () { [native code] }": 123 }`,
that's not a valid proptype.
=> MiqFormRenderer: fix proptype error

app/assets/javascripts/miq_tree.js, app/controllers/application_controller/policy_support.rb, app/presenters/tree_builder_protect.rb, spec/presenters/tree_builder_protect_spec.rb
I'm trying to reduce the number of handler functions in miq_tree.js, this one was kinda trivial. Instead of altering the node's key on the client side, I'm parsing it on the server side. You can test this on any entity that supports policies, e.g. virtual machines. Simply select one and go to `Policy -> Manage Policies` and try to assign or unassign some.
@miq-bot add_label refactoring, technical debt, trees
=> Use onCheckGeneric for handling checked nodes in the policies tree

spec/controllers/mixins/breadcrumbs_mixin_spec.rb
With strict partials enabled some of the breadcrumb mixin specs fail because they're stubbing methods that haven't been defined. ~~Since the mixin appears to require the implementation of these methods anyway, I simply added some empty definitions in the test class. With these in place, the specs then pass.~~
Edit: original plan scrapped, just use real controllers that mixin the BreadcrumbsMixin.
Part of the cleanup effort created at https://github.com/ManageIQ/manageiq-ui-classic/issues/6734
=> Add required interface methods for BreadcrumbsMixin specs

app/controllers/host_controller.rb, spec/controllers/host_controller_spec.rb
**Fixes issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6615
**DEPENDS ON:** https://github.com/ManageIQ/manageiq-ui-classic/pull/6687 (merged)
In this PR, I used new `flash_and_redirect` method (originally `cancel_action` + some little change there) to solve redirection to the proper screen after editing selected Host(s) displayed in a nested list. Originally, I found the issue when displaying Hosts through Cluster's textual summary. Note that `flash_and_redirect` could be used in many more controllers => less code in controllers + proper redirecting in any case. But also note that it relies on what's in `@breadcrumbs`.
Due to using `flash_and_redirect` I could delete some unnecessary lines of the code in _HostController_ and achieved proper redirecting after succcessful …
=> Redirect to proper screen after editing selected Hosts in a nested list

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6613
There was an issue in non-explorer based screens: after search for some name and then clicking on "**X**" in the _Search_ field, nothing happened in the UI together with:
```
No template found for CloudTenantController#adv_search_text_clear, rendering head :no_content.
```
This was due to the missing case for non-explorer screen in `adv_search_text_clear` method. We have to call `javascript_redirect` to update both main div and the title of the page.
Also `@search_text` and `@sb[:search_text]` was not cleared properly. We have to clear it, no matter if we are in explorer or non-explorer screen.
---
**Before:**
**After:**
=> Update the page after clearing Search text, for non-explorer screens

app/assets/javascripts/components/vm_cloud/vm-cloud-add-security-group.js, app/assets/javascripts/components/vm_cloud/vm-cloud-remove-security-group.js
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6786
Warning flash message was displayed after canceling adding/removing Security Group from an Instance. This was inconsistent with displaying flash messages after canceling other actions in this or in all other screens. This very simple PR makes it consistent again.
---
**Before:**
After adding Security Group to an Instance:
After removing Security Group from an Instance:
**After:**
=> Display success flash message after canceling adding/removing Security Group

config/webpack/development.js, config/webpack/production.js, config/webpack/shared.js
Follow-up to/fix of: https://github.com/ManageIQ/manageiq-ui-classic/pull/6784
`stats.errorDetails` [defaults](https://webpack.js.org/configuration/stats/#statserrordetails) to `true`,
`output.pathinfo` [defaults](https://webpack.js.org/configuration/output/#outputpathinfo) to `true` in development mode,
`optimization.minimize` [defaults](https://webpack.js.org/configuration/optimization/#optimizationminimize) to `true` in production mode,
`CompressionPlugin.algorithm` [defaults](https://webpack.js.org/plugins/compression-webpack-plugin/#algorithm) to `gzip`,
`CompressionPlugin.asset` was renamed to `filename`, but [defaults](https://webpack.js.org/plugins/compression-webpack-plugin/#filename) to `[path].gz[query]` as of 2.0 (https://github.com/webpack-contrib/compression-webpack-plugin/re …
=> Webpack - remove settings we no longer need, fix production build

app/assets/javascripts/miq_tree.js, app/controllers/ops_controller/settings/cap_and_u.rb, app/presenters/tree_builder_clusters.rb, app/presenters/tree_builder_datastores.rb, app/presenters/tree_node/node.rb, app/presenters/tree_node/storage.rb, app/views/ops/_settings_cu_collection_tab.html.haml, spec/presenters/tree_builder_clusters_spec.rb, spec/presenters/tree_builder_datastores_spec.rb, spec/views/ops/_settings_cu_collection_tab.html.haml_spec.rb
My primary goal was to be able to use the `miqOnCheckGeneric` on these two trees. For that I had to eliminate the requirement on the posted `tree_name` attribute. I replaced the hash nodes with object-built nodes, which allowed me to use the `TreeBuilder.extract_node_model_and_id` method and determine the tree from the received model. By eliminating the `Check all` checkboxes, the `tree_name` became totally unnecessary and I was able to clean up the code a little. The data structure stored in the session is still too complex, but we can replace this in the future with an API-driven approach which eliminates the need of the session.
Note that there's a positive side-effect that the host nodes are now having their actual icons, not the generic one.
**Before:**
**After:**
cc @brumik this …
=> Clean up the capacity and utilization selection trees 

app/controllers/ops_controller/ops_rbac.rb, app/presenters/tree_builder_belongs_to_vat.rb
When editing a group under `Configuration -> Access control`, the tree on the 3rd tab in Assigned Filters doesn't check the nodes properly after editing a group. The problem is that `EmsFolder` has STI subclasses and the tree doesn't know about them. To avoid this problem, I am testing against all subclasses when determining the checkedness of a node in this tree.
@miq-bot add_label bug, jansa/yes?
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1818005
=> Test against all possible subclasses for checkedness in VAT tree

app/assets/javascripts/miq_tree.js, app/controllers/ops_controller/ops_rbac.rb, app/presenters/tree_builder_belongs_to_hac.rb
The only difference between the old handler and `miqOnCheckGeneric` is the `tree_typ` attribute, which is not really necessary. The trees are available on the `Configuration -> Access Control` screen after editing a group under the 2nd and 3rd tab of `Assigned Filters`.
Note that there's a bug in the area: https://github.com/ManageIQ/manageiq-ui-classic/pull/6800
cc @brumik one more tree doing it with generic :wink: 
@miq-bot add_label cleanup, trees
=> Use miqOnCheckGeneric for handling checks on HAC and VAT trees

app/controllers/ansible_credential_controller.rb, app/controllers/ansible_repository_controller.rb, app/helpers/application_helper/toolbar/ansible_credential_center.rb, app/helpers/application_helper/toolbar/ansible_credentials_center.rb, app/helpers/application_helper/toolbar/ansible_repositories_center.rb, app/helpers/application_helper/toolbar/ansible_repository_center.rb, app/javascript/components/remove-generic-item-modal.jsx, app/javascript/packs/component-definitions-common.js, app/javascript/packs/provider-dialogs-common.js, app/javascript/spec/remove-generic-item-modal/__snapshots__/remove-generic-item-modal.spec.js.snap, app/javascript/spec/remove-generic-item-modal/remove-generic-item-modal.spec.js, spec/controllers/ansible_credential_controller_spec.rb, spec/controllers/ansible_repository_controller_spec.rb
This PR implements a new react / patternfly component to remove misc. (generic) items using rest api. The component renders a modal window with a confirmation text / question and a list of items to be removed.
The PR also modifies the UI code to use the new modal to delete emb. ansible repositories and credentials.
Before:
After:
=> Remove Generic Item Modal

spec/controllers/vm_cloud_controller_spec.rb
Within the specs for `VmCloudController` there are a series of dynamically generated methods that are tested that start with "image_" or "instance_" based on `ApplicationController::Explorer::X_BUTTON_ALLOWED_ACTIONS`.
However, with strict partial validation enabled, about half these fail because the dynamic method in question isn't actually defined, e.g. `image_rename`, `image_drift`, and so on.
This modifies the specs so that it skips the spec if the method isn't actually defined on the controller.
Note that I used `skip` inside the example here because all of my attempts to break out of the loop before the example resulted in `no block given` errors, keeping in mind that Rails has redefined `respond_to` for controllers. If anyone has a better way I'm listening, but this will work at …
=> Skip dynamic vm_cloud specs where the method isn't supported

app/helpers/application_helper/toolbar/x_vm_vmtree_center.rb
I don't really see the point of this button here, you can only edit the tags of a single VM and you can do it much easier without even getting to this page. But feel free to close this PR if you disagree.
**Before:**
**After:**
@miq-bot add_label cleanup
=> Remove edit tags button from the genealogy screen

spec/controllers/vm_or_template_controller_spec.rb
Within the specs for `VmOrTemplateController` there are a series of dynamically generated methods that are tested that start with "image_" or "instance_" based on ApplicationController::Explorer::X_BUTTON_ALLOWED_ACTIONS.
However, with strict partial validation enabled, about half these fail because the dynamic method in question isn't actually defined, e.g. image_rename, image_drift, and so on.
This modifies the specs so that it skips the spec if the method isn't actually defined on the controller.
Continuation of #6738
=> Skip dynamic vm_or_template specs where the method isn't supported

app/helpers/application_helper/page_layouts.rb, spec/controllers/ansible_credential_controller_spec.rb, spec/controllers/ansible_playbook_controller_spec.rb, spec/controllers/ansible_repository_controller_spec.rb, spec/helpers/application_helper/page_layouts_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6765
**Ansible Credentials/Playbooks/Repositories** list screens don't have _Advanced Search_ so the presence of listnav with _"No filters defined"_ in accordion is misleading. This PR removes the listnav from such screens. Note that after clicking on any item in the list, the listnav will be present, as expected.
---
**Before:**
Ansible Credentials screen (similarly for Playbooks/Repositories screens):
**After:**
=> Remove listnav from Ansible Credentials/Playbooks/Repositories list screens

app/assets/javascripts/directives/reconfigure/validateMultiple.js, app/views/vm_common/_reconfigure.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1818799
- Compute -> Infrastructure -> Virtual Machines
- select a VmWare VM
- Configuration -> Reconfigure selected items
- Resize a disk
Before:
After:
- Compute -> Infrastructure -> Virtual Machines
- select a VM
- Configuration -> Reconfigure selected items
- Add a disk
Before:
After:
@miq-bot add_label bug, ivanchuk/no
=> Remove max value for resizing of a disk

app/presenters/tree_builder_alert_profile_assign.rb
With rails 5.2, where clauses will no longer cast Class objects as Strings.
We need to explicitly pass String objects.
Similar to https://github.com/ManageIQ/manageiq/pull/19016
Fixes errors of this variety on rails 5.2 (in a rails 5.1 backward compatible
way):
```
6) TreeBuilderEmsFolders#x_get_tree_roots redhat provider with folders returns with a single root
Failure/Error: obj.merge!(folder.subtree_arranged(:of_type => self.class::ANCESTRY_TYPE))
TypeError:
can't cast Class
```
=> subtree_arranged of_type is a string, not a Class

app/assets/javascripts/directives/reconfigure/validateMultiple.js, app/views/vm_common/_reconfigure.html.haml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1818799
`ivanchuk` version of #6809 
Steps to reproduce: 
- Compute -> Infrastructure -> Virtual Machines
- select a VmWare VM
- Configuration -> Reconfigure selected items
-  Resize a disk
Before:
After:
`ivanchuk` has no space limits for adding a new disk so leaving that as is.
@miq-bot add_label bug, compute/infrastructure
@mzazrivec please have a look, thanks :)
=> [IVANCHUK] Remove max value for resizing of a disk

.travis.yml, Rakefile, manageiq-ui-classic.gemspec, tools/ci/after_install.sh, tools/ci/dead_method_check.sh
Add `debride` to look for dead method. It uses results from `master` as a whitelist so it only points out possibly dead methods that are introduced by a PR. 
Test will always pass as it's up to author/reviewer to decide if it's really a dead method.
It will only run on PRs based on master.
Tested with something like this
```diff
--- a/app/controllers/cloud_tenant_controller.rb
+++ b/app/controllers/cloud_tenant_controller.rb
@@ -172,6 +172,10 @@ class CloudTenantController < ApplicationController
javascript_redirect(:action => "show", :id => tenant_id)
end
+  def dead_method
+    cloud_tenant_form_fields
+  end
+
def cloud_tenant_form_fields
assert_privileges("cloud_tenant_edit")
tenant = find_record_with_rbac(CloudTenant, params[:id])
```
Dead method found:
No dead method:
TODO:
Next …
=> POC Add debride

app/controllers/infra_networking_controller.rb
I haven't found any callsite where these two pieces are being called on the given screen. My guess is that it was copy-pasted and never cleaned up.
@miq-bot add_label cleanup
=> Remove copy-pasted and possibly dead code from Infra Networking

app/presenters/tree_builder_tenants.rb
The `post_check` only makes sense if `three_checks` is set on the tree, this is probably a badly copy-pasted piece of code.
@miq-bot add_label cleanup, trees
=> Remove unnecessary post_check from tenants tree under catalogs

app/presenters/tree_builder.rb, app/presenters/tree_builder_belongs_to_hac.rb
This is the only callsite, there's no need to have it globally for all trees.
@miq-bot add_label cleanup, trees
=> Move TreeBuilder.group_id under TreeBuilderBelongsToHac

app/controllers/mixins/manager_controller_mixin.rb, app/controllers/mixins/vm_show_mixin.rb, app/views/layouts/_header.html.haml
We found out with @h-kataria that this piece of code is no longer used, so we're removing it. Apparently it was related to VM chart context menus, but it got somehow refactored. Also the code has been copy-pasted to other controllers unnecessarily.
Follow-up on https://github.com/ManageIQ/manageiq-ui-classic/pull/6957
@miq-bot add_label cleanup, technical debt
=> Get rid of the no longer used @miq_after_onload

app/helpers/application_helper/toolbar/x_vm_center.rb, app/helpers/application_helper/toolbar/x_vm_cloud_center.rb, app/helpers/application_helper/toolbar/x_vm_snapshot_center.rb
Compute > Cloud/Infra > VMs/Instances - pick a VM
toolbar Configuration > Create a new snapshot for this VM
the button is only accessible from a detail screen, not a list screen,
but `onwhen=>1` requires at least one item be selected in the list screen.
Which makes the button always disabled, fixing.
`onwhen` does not make sense outside list screens (and thus plural toolbars).
(There may be other buttons simiarly affected, this is likely a react toolbar conversion change, created https://github.com/ManageIQ/manageiq-ui-classic/issues/6968.)
Fixes https://github.com/ManageIQ/manageiq/issues/20059
=> Fix snapshot toolbar button always disabled

app/controllers/application_controller.rb, app/controllers/application_controller/ci_processing.rb, app/controllers/catalog_controller.rb, app/controllers/mixins/actions/host_actions/misc.rb, app/controllers/mixins/containers_common_mixin.rb, app/controllers/mixins/ems_common.rb, app/controllers/mixins/ems_common/core.rb, app/controllers/mixins/manager_controller_mixin.rb, app/presenters/tree_builder_automation_manager_configuration_scripts.rb, app/presenters/tree_builder_infra_networking.rb, spec/presenters/tree_builder_spec.rb
There were multiple places (all in `.order` calls) that triggered the following warning
```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as
raw SQL) called with non-attribute argument(s): "lower(name)".  Non-attribute
arguments will be disallowed in Rails 6.0. This method should not be called
with user-provided values, such as request parameters or model attributes.
Known-safe values can be passed by wrapping them in Arel.sql().
```
This fixes that by instead calling to `arel_table[].lower`, which does the same thing, but uses the existing arel interface to do it, which should be safer.  It should fail earlier for non-name columns, and should be safer overall then using `Arel.sql()`.
Links
-----
* Part of the Rails 5.2 effort: …
=> [Rails52] Use arel to fix "Dangerous query method"

spec/controllers/ops_controller_spec.rb, spec/controllers/report_controller_spec.rb
The following two errors were showing up in the specs:
```
DEPRECATION WARNING: The error? predicate is deprecated and will be removed in Rails 6.0. Please use server_error? as provided by Rack::Response::Helpers.
(called from block (3 levels) in <top (required)> at /Users/nicklamuro/code/redhat/manageiq-ui-classic/spec/controllers/report_controller_spec.rb:1397)
```
```
DEPRECATION WARNING: The success? predicate is deprecated and will be removed in Rails 6.0. Please use successful? as provided by Rack::Response::Helpers.
(called from block (2 levels) in <top (required)> at /Users/nicklamuro/code/redhat/manageiq-ui-classic/spec/controllers/ops_controller_spec.rb:245)
```
This fixes those by either calling the correct method, or using a more commonly used method (`have_http_status`) that …
=> [Rails52] Fixes deprecated rack helpers

app/views/catalog/_sandt_tree_show.html.haml, lib/gtl_formatter.rb
To allow for pluggable catalog item types, use the
ServiceTemplate.all_catalog_item_types method instead of the hard coded
set of catalog types.
Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/106
Core PR: https://github.com/ManageIQ/manageiq/pull/20039
=> Don't use ServiceTemplate::CATALOG_ITEM_TYPES

app/presenters/tree_builder_sections.rb, spec/presenters/tree_builder_sections_spec.rb
The checkedness on compare screens is implemented explicitly in a little crazy way and partial checking never worker. So we decided with @brumik to utilize `post_check` on the tree. This allowed me to :scissors: delete :skull: some code and fix the issue.
**Before:**
**After:**
@miq-bot add_label trees, bug, cleanup
=> Simplified checkedness of 🌳🌳 on compare screens, enabled post_check

app/views/layouts/_item.html.haml
Bumped into this randomly while hunting down something else. When you go the `Infrastructure -> Networking` and select a `Switch` in the left side tree, you can access the related `Hosts` through the summary screen. However, this throws an undefined method error on `ext_management_system.name`.
The page to be rendered is being created from a report, more specifically the column headers of a report. So while reporting allows us to reach for fields in further tables using a dotted notation (see above), the `send` method we're using in the view is not capable of doing so.
As a workaround I implemented a chaining send after splitting the column headers. The solution is not ideal but it gets us where we should be. The problem might happen on other pages where we use the same file for rendering …
=> Allow chaining method calls built from report columns in layouts/item

app/controllers/cloud_tenant_controller.rb, spec/controllers/cloud_tenant_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6967
We don't want always to redirect to the dashboard (or textual summary) of selected Tenant (after editing it). We want to end up in the same screen as before the action (Edit). Redirecting to the previous screen url solves the problem, instead of always calling `show` method. And it works universally, no matter where we are - in a list or also dashboard/summary of the Tenant.
`javascript_redirect(previous_breadcrumb_url)` instead of
`javascript_redirect(:action => "show", :id => tenant_id)` - that's the only change here. Everything else remains the same. I just used the existing `flash_and_redirect` method to achieve this. We end up with less code in `update_finish` method + it's working for all of the possible cases. …
=> Redirect to proper screen after succesful update of a Cloud Tenant in a list

app/controllers/cloud_tenant_controller.rb, app/controllers/mixins/ems_common.rb, config/routes.rb, spec/controllers/cloud_tenant_controller_spec.rb, spec/controllers/mixins/ems_common_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6973
There was the logic missing in _EmsCommon_ mixin regarding deleting Cloud Tenants displayed in a nested list. Only `show` method and `render_flash` were called in `button` method, and nothing related to deleting the Tenants.
In this PR, I am also fixing redirecting issue after deleting Cloud Tenants in a nested list. I almost didn't change [other cases for redirecting](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/cloud_tenant_controller.rb#L198-L210) regarding the `@lastaction` because I've found that they're needed just as they are, but with two little exceptions: 
- [this change](https://github.com/ManageIQ/manageiq-ui-classic/pull/6974/files#diff-68512128862e16616d93240055cb3a7dR207) …
=> Delete Cloud Tenants selected in a nested list

app/controllers/mixins/actions/vm_actions/evacuate.rb, app/controllers/mixins/actions/vm_actions/live_migrate.rb, app/controllers/mixins/actions/vm_actions/resize.rb, spec/controllers/mixins/actions/vm_actions/evacuate_spec.rb, spec/controllers/mixins/actions/vm_actions/live_migrate_spec.rb, spec/controllers/mixins/actions/vm_actions/resize_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6959
The first commit fixes wrong redirect if we evacuated Instances displayed in a non-explorer screen (nested list) after we provided the same action on Instances in an explorer screen ( (_Compute > Clouds > Instances_). We need to set `@sb[:explorer]` back to `nil`. It was `nil` before Evacuate action, originally, **even if we were in an explorer screen**.
If we don't set `@sb[:explorer]` back to `nil` right after the Evacuate action, `true` value will be [saved](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller.rb#L1877) in `session[:sandboxes]['vm_cloud'][:explorer]` from `@sb[:explorer]` "forever", and later, when submitting/canceling Evacuate action in non explorer …
=> Redirect to proper screen after reconfiguring, migrating, evacuating Instances in a nested list

app/controllers/cloud_network_controller.rb, app/controllers/cloud_subnet_controller.rb, app/controllers/vm_cloud_controller.rb, spec/controllers/cloud_network_controller_spec.rb, spec/controllers/cloud_subnet_controller_spec.rb, spec/controllers/host_aggregate_controller_spec.rb, spec/controllers/vm_cloud_controller_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6785
There was an issue with displaying an extra flash message from the previous action (attaching/detaching Cloud Volume from an Instance) in the screen of an actual action on an Instance.
The core of the problem was saving flash message to the session, when attaching/detaching Cloud Volume (to `session[:flash_msgs]` when calling `flash_to_session` in `flash_and_redirect`), so the message was kept in the session even when starting performing some other action. Then the message was saved to `@flash_array` from `session[:flash_msgs]` [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller.rb#L1760-L1762) and then it was rendered (see the "Before" screenshots). Clearing …
=> Remove extra flash message after attaching/detaching Cloud Volume from Instance

app/presenters/tree_builder.rb
My rewrite of the algorithm from JS to Ruby wasn't as good as I thought :see_no_evil: `Array#reverse` in Ruby isn't the same as `Array.prototype.reverse` in JS. It's strange how big difference a single character can make :sob: 
https://github.com/ManageIQ/manageiq-ui-classic/pull/6964/files#diff-bff4131de23ce9175827098fd726ca7aL461
=> Fix TreeBuilder#post_check to actually reverse! the nodes

app/assets/javascripts/miq_application.js, app/controllers/ansible_credential_controller.rb, app/controllers/ansible_playbook_controller.rb, app/controllers/ansible_repository_controller.rb, app/controllers/application_controller.rb, app/controllers/miq_policy_controller.rb, app/helpers/application_helper/page_layouts.rb, app/views/layouts/_center_div_no_listnav.html.haml, app/views/layouts/_searchbar.html.haml, config/routes.rb, spec/controllers/ansible_credential_controller_spec.rb, spec/controllers/ansible_playbook_controller_spec.rb, spec/controllers/ansible_repository_controller_spec.rb, spec/controllers/application_controller_spec.rb, spec/controllers/miq_policy_controller_spec.rb, spec/helpers/application_helper/page_layouts_spec.rb, spec/views/layouts/_center_div_no_listnav.html.haml_spec.rb, spec/views/layouts/_searchbar.html.haml_spec.rb
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/6765
This PR:
- renames `adv_search_text_clear` to `search_clear`
-  we will have `search_clear` and `adv_search_clear` now so we will be able to distinguish easily what's related to _Advanced Search_ and what to regular _Search_, no misleading name of the method
- makes small improvements in _searchbar.html.haml_
- it does not make sense to check if the screen supports displaying Adv. Search if we want only Search to be displayed (line 1; and if the same check for displaying Adv Seach is present "later" in the haml), also it does not make sense to check the same conditions twice (conditions in line 1 and 26 were totally the same!)
- also quick search makes sense to be rendered only if there's Advanced Search support
- test …
=> Add ability for displaying Search bar in the screens without listnav

package.json
Incorporates https://github.com/ManageIQ/react-ui-components/pull/178 that is required for https://github.com/ManageIQ/manageiq-ui-classic/pull/6413 to fix the issues related to node icons.
cc @brumik
=> Update react-ui-components to 0.11.68

.eslintrc.json, app/javascript/.eslintrc.json, app/javascript/components/remove-generic-item-modal.jsx
`typeof(treeSelect) == undefined` is always false, typeof returns a string
This lead to buttons without tree_select trying to do tree_select instead of redirect_url.
Cc @mzazrivec, @h-kataria
=> remove-generic-item-modal: fix typeof==undefined bug

app/presenters/menu/default_menu.rb
Now the menu goes...
Overview
Services
**Compute**
**Network** (changed to singular)
**Storage**
**Configuration**
**Automation**
Migration
Control
Monitor
Cc @h-kataria , @Fryguy
=> Menu - sort Providers menu together, singular

app/assets/stylesheets/application.scss, app/assets/stylesheets/fonticon_picker.scss, app/javascript/components/fonticon-picker/icon-list.jsx, app/javascript/components/fonticon-picker/index.jsx, app/javascript/packs/component-definitions-common.js, app/views/shared/buttons/_ab_options_form.html.haml, app/views/shared/buttons/_group_form.html.haml
My original plan was to just copy-paste the component from react-ui-components to be compliant with https://github.com/ManageIQ/manageiq-ui-classic/issues/6716, but there were some missing and broken parts:
* no way to preselect an icon
* icons rendered as component -> ff doesn't support that
* icons organized in a table  :cry: :see_no_evil:  yes you heard that right
* icon fetch from CSS was building a table
* no scrollbar when too many icons, it makes the whole screen scrolling
* modal was too narrow
* kinda complicated iconTypes specification schema
So I addressed these problems, mostly by just moving some stuff from my original angular component.
The custom buttons that require this component are being used in Automate Customization and also in Generic Objects/Catalogs. The solution …
=> Replace angular-based fonticon picker with a react component

app/helpers/application_helper/toolbar_builder.rb
Note: You may need https://github.com/ManageIQ/manageiq-api/pull/812 to create CustomButton correctly
- Automation -> Generic Objects -> Add Custom Button Group to a Generic Object -> Add Custom Buttons to this group or Add just a Custom Button
- Services -> My Services -> click to a Service that has an Instance of that Generic Object
- click on Instances
- click on one Instance
- see buttons 
Before:
After:
@miq-bot add_label wip, bug, jansa/yes
=> Make sure custom button doesn't need to be checked when on summary page

app/javascript/components/fonticon-picker/index.jsx
Updates the fonticon picker component (https://github.com/ManageIQ/manageiq-ui-classic/pull/6985) to react when clicking on the whole element, instead of only the chevron.
For consistency with selects, and general ease of use :)
The problem:
Now clicking the icon also shows the modal.
=> fonticon-picker: show modal when clicking on the icon, not only the chrevon

app/views/shared/views/_prov_dialog.html.haml
This code changed (https://github.com/ManageIQ/manageiq-ui-classic/pull/5774) from conditions like...
- if (@edit && @edit[:new] && @edit[:new][:sysprep_enabled] && @edit[:new][:sysprep_enabled][0] == "fields") || (@options && @options[:sysprep_enabled] && @options[:sysprep_enabled][0] == "fields")
to one assignment...
- edit_or_options = (@edit && @edit[:new] && @edit[:new][:sysprep_enabled]) || (@options && @options[:sysprep_enabled])
...and conditions like...
- if edit_or_options[0] == "fields"
Which then crashes when trying to clone a RHV template, because `edit_or_options` is nil...
Error caught: [ActionView::Template::Error] undefined method `[]' for nil:NilClass
/opt/rh/cfme-gemset/bundler/gems/cfme-ui-classic-d44320707dfe/app/views/shared/views/_prov_dialog.html.haml:195:in …
=> prov_dialog customize - don't fail when no :sysprep_enabled

app/javascript/forms/data-driven-form.jsx
The `buttonsLabels` property is not set in the `MiqFormRenderer` component, so the default button labels come straight from DDF without any i18n. There's a splatted `buttonLabels` prop on the component, but its contents are not caught by the `FormRenderer` component.
I changed the dataflow so the default button labels have now i18n calls and they are being merged with the additional ones coming as props.
@miq-bot add_label i18n, bug, react
=> Merge default button labels properly with the custom ones in DDF

app/assets/stylesheets/patternfly_overrides.scss
Required for field-array stuff which is much wider, we will do the respo differently in the future anyway.
**Before:**
**After:**
This reverts commit 1df8779bdcc6c7b22c804c954050bf8ae807022d from https://github.com/ManageIQ/manageiq-ui-classic/pull/5650
=> Revert "make react forms responsive"

app/javascript/components/firmware-registry/firmware-registry-form.schema.js
When you go to `Compute -> Infrastructure -> Firmware Registries` the form under `Configuration -> Add new Firmware Registry` is broken as the `name˙ now is a required parameter in DDF:
By adding the name on the `sub-form` the problem goes away:
@miq-bot add_label bug, react
=> Add missing name into the Firmware Registry Form schema

app/services/user_validation_service.rb
Displaying a message upon a login attempt when a user's account has been locked:
Parent issue: https://github.com/ManageIQ/manageiq/issues/20043
Depends on: https://github.com/ManageIQ/manageiq/pull/20087
=>  Always display the error message upon authentication from the backend

spec/controllers/dashboard_controller/verify_user_spec.rb
Introduced by https://github.com/ManageIQ/manageiq/pull/20087
Fixes test failure on master:
```
Failed examples:
rspec ./spec/controllers/dashboard_controller/verify_user_spec.rb:73 # DashboardController validate_user fails for an invalid user
rspec ./spec/controllers/dashboard_controller/verify_user_spec.rb:66 # DashboardController validate_user fails for an existing user with wrong password
```
@miq-bot add-label jansa/no
ping @skateman
=> Fix invalid login message

app/helpers/persistent_volume_helper/textual_summary.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7025
How reproducible:
Always
- Log into MIQ UI with non en_US locale
- Navigate to Compute - Containers - Volumes and click on any list item
- `Volume path` and  `Desired access modes` are in English
Before:
After:
It's translated.
@miq-bot add_label bug, internationalization
=> Fix i18n labels in Persistent Volume page

app/controllers/ops_controller/settings/upload.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7019
How reproducible:
Always
- Log into MIQ UI with non en_US locale
- Navigate to Configuration icon - Settings - Custom Logos, and choose .jpg image for Custom Brand Image, click Upload.
- Observe the error message '»自定义品牌« must be a .png file' is partially translated
Before:
After:
It's translated.
@miq-bot add_label internationalization, bug
=> Fix error message for Custom Image

app/views/layouts/_tabs.html.haml
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7023
- Log into MIQ UI with non en_US locale
- Navigate to Storage -> Block Storage -> Volume Types
- Observe `Cloud Volume Types` is in English.
Before:
After:
@miq-bot add_label bug, jansa/no, internationalization
=> Add gettext to title of a tab

app/views/container_project/_show_dashboard.html.haml, app/views/static/pf_charts/line-chart.html.haml, app/views/static/pf_charts/trends-chart.html.haml
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7024
- Log into MIQ UI with non en_US locale
- Navigate to Compute - Containers - Projects and click on any list item.
- `No data available` text is in English for multiple times.
Fixes:
- make cards look the same
- use MIQ pf-empty-chart to make sure `No data available` is traslated
Before:
After:
=> Fix No data available for Container Project

app/controllers/miq_ae_class_controller.rb, app/presenters/tree_builder_automate_catalog.rb, spec/controllers/miq_ae_class_controller_spec.rb, spec/helpers/application_helper/buttons/miq_ae_class_copy_spec.rb, spec/helpers/application_helper/buttons/miq_ae_default_spec.rb, spec/helpers/application_helper/buttons/miq_ae_instance_copy_spec.rb, spec/helpers/application_helper/buttons/miq_ae_spec.rb, spec/helpers/application_helper/toolbar_chooser_spec.rb
New columns `domain_id` and `relative_path` have been added to `MiqAeNamespaces/MiqAeClass/MiqAeInstance/MiqAeMethod` tables.
So namespace can be queried based on these two columns instead of loop thru the namespace fqname.
Part of https://github.com/ManageIQ/manageiq/pull/20050.
cross repo tests: ManageIQ/manageiq-cross_repo-tests#112
ManageIQ/manageiq-automation_engine#410
=> Improve automate namespace query performance.

app/views/layouts/application.html.haml, app/views/stylesheets/_template50.html.haml
big_iframe used to be the layout without menu,
that changed in https://github.com/ManageIQ/manageiq/pull/8114,
therefore we should no longer adjust big_iframe margins as if the menu wasn't there
removing
Cc @skateman
=> Remove obsolete big_iframe logic

app/controllers/mixins/breadcrumbs_mixin.rb, app/controllers/optimization_controller.rb, app/controllers/pxe_controller.rb, app/views/layouts/_breadcrumbs.html.haml, spec/controllers/mixins/breadcrumbs_mixin_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740405
Ivanchuk version of https://github.com/ManageIQ/manageiq-ui-classic/pull/5776
Bug:
All other breadcrumb and links seem to be working correctly, but there's a minor problem in the breadcrumb when you navigate to the page for the first time or from a different page or refresh the page.
There are 2 ways to reproduce - 
1) On fresh navigation to Compute > Infrastructure > PXE, breadcrumb shows `Compute > Infrastructure > PXE > PXE Servers > editing`, notice `editing` at the end.
2) Navigate to the PXE page, select an accordion, for eg "System Image Types` and refresh the page. Breadcrumb shows - `Compute > Infrastructure > PXE > System Image Types > editing`,  notice `editing` at the end.
Before:
After:
@miq-bot …
=> [IVANCHUK] Fix cancel, save and select_tree actions in breadcrumbs and title in PXE menu section

app/helpers/application_helper/navbar.rb
If a second level menu has no visible items for logged in user role, second level menu tab should not be visible on the vertical navbar.
Steps to recreate:
1. Create a new user role, assign this role product features shown in the `Allowed features for new role` screenshot below.
2. Assign newly created role to a user and log in to CF with this user. 
3. Check the vertical navbar, second level menus appear with empty third level menus. 
4. After the fix second level menus with no visible items is not visible in the menus.
Allowed features for new role
before
after
=> Do not display second level menu if that has no visible items.

spec/controllers/ems_container_controller_spec.rb
Fixing the following failure:
``` 
1) EmsContainerController.update_ems_button_detect with route set detects openshift prometheus alert route
Failure/Error: expect(mock_client).to receive(:discover)
(Double "kubeclient").discover(*(any args))
expected: 1 time with any arguments
received: 2 times with any arguments
2) EmsContainerController.update_ems_button_detect with route set tolerates detection exceptions
Failure/Error: expect(mock_client).to receive(:discover)
(Double "kubeclient").discover(*(any args))
expected: 1 time with any arguments
received: 2 times with any arguments
3) EmsContainerController.update_ems_button_detect with route set detects openshift prometheus metric route
Failure/Error: expect(mock_client).to receive(:discover)
(Double "kubeclient").discover(*(any args)) …
```
=> Fix failing EmsContainerControllerSpec

spec/controllers/ems_container_controller_spec.rb
Probably a better fix for https://github.com/ManageIQ/manageiq-ui-classic/pull/7051
=> EmsContainerController: use allows instead of expect

manageiq-ui-classic.gemspec
this is what we're running in schema and I feel like it should be consistent especially since the `5.0.0.1` format makes travis super unhappy, capische? 
honestly I'm not sure the schema one's right, but it'd better anyway that we're at least consistently wrong so... maybe LJ will have a better idea than this
=> maintain consistent rails versions across repos

app/javascript/forms/data-driven-form.jsx, config/webpack/shared.js, jest.config.js
We have our own renderer for DDF and it would be nice to expose it for other rails engines. This would allow me to continue in getting rid of final-form components in [some provider repos](https://github.com/ManageIQ/manageiq-ui-classic/issues/6716#issuecomment-591974680) by replacing them with DDF.
The alias is set to `@@ddf`, so we could load a component like this:
```js
import MiqFormRenderer, { componentTypes, validatorTypes } from "@@ddf";
```
@miq-bot add_label enhancement, react
=> Expose our DDF renderer and constants as an alias for other engines

manageiq-ui-classic.gemspec
Note, ui-classic can't run without manageiq but we're updating it to be consistent.
From:
https://github.com/ManageIQ/manageiq/pull/20188
[CVE-2020-8162] Circumvention of file size limits in ActiveStorage
[CVE-2020-8164] Possible Strong Parameters Bypass in ActionPack
[CVE-2020-8165] Potentially unintended unmarshalling of user-provided objects in MemCacheStore and RedisCacheStore
[CVE-2020-8166] Ability to forge per-form CSRF tokens given a global CSRF token
[CVE-2020-8167] CSRF Vulnerability in rails-ujs
https://weblog.rubyonrails.org/2020/5/18/Rails-5-2-4-3-and-6-0-3-1-have-been-released/
=> Update ui-classic to match manageiq rails version

app/helpers/application_helper/button/cloud_volume_backup_create.rb, app/helpers/application_helper/button/cloud_volume_backup_restore.rb, spec/helpers/application_helper/buttons/cloud_volume_backup_create_spec.rb, spec/helpers/application_helper/buttons/cloud_volume_backup_restore_spec.rb
In some environments `Module.const_defined?("Namespace::CloudVolume")` returns `::CloudVolume` so this check doesn't work.
`Module.const_defined?("ManageIQ::Providers::Amazon::CloudManager::CloudVolume")` returns `true` then invoking `.supports?()` on that class raises a `NameError`.
`String#safe_constantize` is a more reliable way of determining if a class exists.
=> Fix constantizing CloudVolume for disable? check

app/controllers/application_controller/report_downloads.rb
Go to Overview -> Chargeback -> Reports -> select a Report -> click download CSV
Before:
After:
Download starts
Using `report` instead of `@report` like `render_txt` above `render_csv`.
=> Fix csv download

app/controllers/mixins/sandbox.rb, app/presenters/tree_builder.rb
Missed removal of these in https://github.com/ManageIQ/manageiq-ui-classic/pull/7039
=> Removed leftover settings for Chargeback Rates

app/controllers/report_controller/widgets.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1805847
Go to Overview => Reports => Dashboard Widgets => click at a Menu via GTL
Expected result:
Breadcrumbs should be `Overview > Reports > Dashboard Widgets > [name of a menu]`
Actual result:
Breadcrumbs is `Overview > Reports > Dashboard Widgets > Menus`
Before:
After:
It goes for all leaf nodes under `Dashboard Widgets `
@miq-bot add_label bug, ivanchuk/yes, jansa/yes, breadcrumbs
@h-kataria please have a look, thanks :)
=> Fix breadcrumbs for Dashboard Widgets

app/controllers/chargeback_assignment_controller.rb
Go to Overview -> Chargeback -> Assignments -> Storage -> select Selected Datastores -> make a change and `Save`
Before:
It ends with an error
```
FATAL -- : Error caught: [ArgumentError] Received: manageiq::providers::redhat::inframanager::storage, expected one of ["enterprise", "storage", "ext_management_system", "ems_cluster", "tenant", "ems_container"]
/manageiq-ui-classic/app/controllers/chargeback_assignment_controller.rb:286:in `get_cis_all'
manageiq-ui-classic/app/controllers/chargeback_assignment_controller.rb:211:in `cb_assign_set_form_vars'
manageiq-ui-classic/app/controllers/chargeback_assignment_controller.rb:98:in `get_node_info'
manageiq-ui-classic/app/controllers/chargeback_assignment_controller.rb:72:in `cb_assign_update'
```
After:
@lpichler please have a look, thanks :) …
=> Fix Chargeback Assignments for Datastores

package.json, yarn.lock
To fix the failing CI, we need to backport the following 2 PRs:
https://github.com/ManageIQ/manageiq-ui-classic/pull/7051
https://github.com/ManageIQ/manageiq-ui-classic/pull/7052
=> [JANSA] Update ui-components to 1.3.4

app/javascript/components/field-array/field-array-item.jsx, app/javascript/components/field-array/index.jsx, app/javascript/forms/mappers/formFieldsMapper.jsx
In some forms we have a set of key-value pairs, the ones I found were for automate attributes in generic objects. DDF provides a [Field Array](https://data-driven-forms.org/renderer/dynamic-fields#heading-usingfieldarray) component but without implementation for PF3, so I created one for our purposes.
To test this component, use the diff below (feel free to tweak), go to a VM's summary screen and initiate *Set Ownership* from the *Configuration* toolbar button.
```diff
diff --git a/app/javascript/components/set-ownership-form/ownership-form.schema.js b/app/javascript/components/set-ownership-form/ownership-form.schema.js
index 61cbf51b0..394f43ef4 100644
--- a/app/javascript/components/set-ownership-form/ownership-form.schema.js
+++ …
```
=> Implemented FieldArray component and added it to the DDF mapper

app/controllers/ops_controller/settings/common.rb, app/controllers/ops_controller/settings/help_menu.rb, app/helpers/application_helper/navbar.rb, app/helpers/ops_helper.rb, app/presenters/menu/default_menu.rb, app/presenters/menu/item.rb, app/presenters/menu/manager.rb, app/presenters/menu/section.rb, app/views/layouts/_center_div_dashboard_no_listnav.html.haml, app/views/layouts/_center_div_no_listnav.html.haml, app/views/layouts/_center_div_with_listnav.html.haml, app/views/layouts/_content.html.haml, app/views/layouts/_header.html.haml, app/views/layouts/_vertical_navbar.html.haml, app/views/ops/_settings_help_menu_tab.html.haml, spec/presenters/menu/menu_manager_spec.rb
(Split off from #6963 as it was getting too large.)
This should not change anything, especially to do with menus :).
* move menu partial + invocations from every layout to a single header invocation
* moved `compact` from sections and items to the common code
* allowed menu item without rbac - logout can't require rbac
* removed icons from second & 3rd level sections - only first level sections have icons
* split help items so that the future user settings menu can reorder them, and editing still works
Cc @skateman
=> Menu - pre-carbon cleanups

app/stylesheet/application-webpack.scss, app/stylesheet/carbon.scss, package.json
(Split off from https://github.com/ManageIQ/manageiq-ui-classic/pull/6963 as it was getting too large.)
This enables carbon css without affecting anything.
This PR should cause no visual differences at all :).
ui-shell css is needed for the new menu (https://github.com/ManageIQ/manageiq-ui-classic/pull/6963),
not switching to IBM fonts globally because:
* changing patternfly fonts should be easier after https://github.com/ManageIQ/manageiq-ui-classic/pull/5679
* carbon loads the font from `fonts.gstatic.com`, we may need need to use a [custom join function](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/README.md) to change to local urls
also https://github.com/ManageIQ/manageiq-ui-classic/pull/5679 - switching reset stylesheets can wait, and body …
=> Carbon - add carbon scss

app/helpers/reactjs_helper.rb, app/javascript/components/breadcrumbs/index.jsx, app/javascript/miq-component/helpers.js, app/javascript/miq-component/registry.js, app/javascript/spec/miq-component/helpers.spec.js, app/javascript/spec/miq-component/miq-component.spec.js, config/webpack/shared.js
(Split off from #6963 as it was getting too large.)
This allows for overriding react component ids when calling `= react`,
overriding component registry components from plugins via `addReact(name, component, { override: true })`,
adds a webpack plugin to output timestamp of the last build (scss rebuilds take a few seconds),
and converts Breadcrumbs to a functional component, without further changes
Cc @skateman
=> React - override id, component; convert Breadcrumbs to functional

.babelrc.js, package.json
we're using old autoprefixer which depends on browserslist 1.7, which doesn't know "not dead" - updating autoprefixer, and stylelint because that depends on an older version too
then moving our browserslist from babel config to global config,
so that autoprefixer picks it up automatically,
and doesn't generate IE CSS.
Prevents errors when requiring carbon:
(9155:3) IE supports only grid-row with / and span. You should add grid: false option to Autoprefixer and use some JS grid polyfill for full spec support
@ ./app/stylesheet/application-webpack.scss 2:26-264
@ ./app/javascript/packs/application-common.js
cc @skateman
=> autoprefixer, browserslist: update, move to package.json

app/controllers/mixins/manager_controller_mixin.rb
this line was added in https://github.com/ManageIQ/manageiq-ui-classic/pull/6782, should keep the next line that uses `arel_table`
Marking `jansa/no` because https://github.com/ManageIQ/manageiq-ui-classic/pull/6970 is not backported.
=> Removed redundant line of code

app/views/shared/dialogs/_reconfigure_dialog.html.haml
This needs to be tested / go in with https://github.com/ManageIQ/ui-components/pull/440
1. Create a service dialog, have a field in it marked as non-reconfigurable
2. Create a catalog item using the above dialog
3. Order the above created service
4. Once the service is deployed, reconfigure it
Previously, all input fields in the dialog being reconfigure could be edited. This fix adds a `reconfigureMode` flag to the `dialog-user` component, which then enabled / disables the respective inputs accordingly.
@himdel @tinaafitz @billfitzgerald0120 
https://bugzilla.redhat.com/show_bug.cgi?id=1837410
=> Add reconfigureMode parameter to dialog-user

app/controllers/ops_controller/diagnostics.rb
Rails.configuration.database_configuration has no knowledge of db configuration
found in the DATABASE_URL environment variable. We need to use
ActiveRecord::Base.configurations.
Related to: https://github.com/ManageIQ/manageiq/pull/20208
And: https://github.com/ManageIQ/manageiq/pull/15269
=> Use DATABASE_URL friendly AR::Base.configurations

app/views/security_group/new.html.haml
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7022
How reproducible:
Always
- Log into MIQ ui with non en_US locale
- Navigate to Networks - Security Groups - Configuration and click on `Add a new security group`
-  Observe `Network Manager` drop-down menu and mouse hover on `Security Group Name` text box.
- `Nothing selected` and `Please fill out this field.` are in English.
Before:
After:
WON'T FIX:
`Please fill out this field` effects every single required text field and is a build-in browser thing. It should be in a language the browser is set to. Leaving as is.
@miq-bot add_label wip, bug, internationalization
=> Fix i18n security group

app/javascript/forms/mappers/formFieldsMapper.jsx
Found by @himdel in https://github.com/ManageIQ/manageiq-ui-classic/pull/6698#issuecomment-634289384
**Before:**
**After:**
=> Globally set the default placeholder for select fields in DDF

app/views/miq_policy/_action_list.html.haml, app/views/miq_policy/_alert_list.html.haml, app/views/miq_policy/_policy_list.html.haml, config/routes.rb, spec/routing/miq_policy_routing_spec.rb
The `_get_all` routes are no longer used as the `action_url` local variable is not being used in the `layouts/gtl` anymore. There's a callsite to each method though, from `tree_select` methods, so I kept the method definitions. The `action_tag_pressed` method has been probably deleted when we started using the new tagging screen.
=> Remove unused routes from the miq_policy_controller

app/views/service/_svcs_show.html.haml
**ISSUE:**
Users will get error on Ansible playbook screen if they do not have product feature ```miq_task_all_ui```  since MiqTask to get Ansible playbook stdout was created for `system` account
**Solution**: 
Provide userid when creating MiqTask for grabbing stdout output from absible playbook
**BEFORE:**
**AFTER:**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1836125
@miq-bot add-label bug, ivanchuk/yes, jansa/yes
=> MiqTask to get stdout for Ansible should be owned by user who requested view

app/presenters/menu/custom_loader.rb, spec/presenters/menu/custom_loader_spec.rb
instead of relying on initializers calling `register`,
and failing after code reload in development
This changes how plugins register menus:
```diff
diff --git a/lib/manageiq/v2v/engine.rb b/lib/manageiq/v2v/engine.rb
index f725e8de..dd092f7e 100644
--- a/lib/manageiq/v2v/engine.rb
+++ b/lib/manageiq/v2v/engine.rb
@@ -14,14 +14,14 @@ module ManageIQ::V2V
app.config.filter_parameters += %i[conversion_host_ssh_private_key openstack_tls_ca_certs vmware_ssh_private_key]
end
-    initializer 'plugin-migration-menu' do
-      Menu::CustomLoader.register(
+    def self.menu
+      [
Menu::Section.new(:migration, N_("Migration"), 'pficon pficon-migration', [
Menu::Item.new('plans', N_("Migration Plans"), 'migration', {:feature => 'migration', :any => true}, '/migration#/plans'), …
```
=> CustomLoader - load from all Engines' .menu

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js, app/assets/javascripts/controllers/playbook-reusable-code-mixin.js, app/views/layouts/angular/_ansible_form_options_angular.html.haml
1. Attempt to create a Ansible Playbook service
2. Select repository and a playbook
3. Select a machine credential without privilege escalation method
4. Select a different machine credential with privilege escalation method
In both cases (3 & 4) the `Privilege Escalation` switch stays visible & usable. In truth, the switch should be enabled only for machine credentials actually supporting privilege escalation.
When selected a machine credential that supports privilege escalation:
When selected a machine credential that doesn't support privilege escalation:
https://bugzilla.redhat.com/show_bug.cgi?id=1810477
=> Disable privilege escalation when machine credential doesn't support it

spec/routing/service_routing_spec.rb, spec/routing/shared_examples/vm_common_examples.rb, spec/routing/vm_or_template_routing_spec.rb, spec/routing/vm_routing_spec.rb
The method for this route has been removed when we converted it to react, however, the route definition and specs remained. :scissors:
=> Remove the no longer used ownership_field_changed route

app/controllers/mixins/actions/vm_actions/ownership.rb, config/routes.rb
This is no longer necessary since https://github.com/ManageIQ/manageiq-ui-classic/pull/5863
=> Drop the unused ownership_form_fields method/route

app/javascript/forms/input-with-dynamic-prefix.jsx, app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7037
Before:
After:
@miq-bot add_label wip, bug
=> Fix broken select in PXE server form

app/controllers/generic_object_definition_controller.rb, app/helpers/application_helper/page_layouts.rb, app/views/layouts/listnav/_generic_object_definition_show_list_with_treeview.html.haml
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/6997
Go to Automation -> Automate -> Generic Objects
Before:
After:
@miq-bot add_label bug, jansa/no
@h-kataria please have a look. I removed listnav for summary pages that use `show_list` for some reason. And improved breadcrumbs so the navigation works a bit. I'll work on GOD breadcrumbs more in followup PR.
=> Fix missing partial for GOD page

app/controllers/miq_policy_controller/policy_profiles.rb, spec/controllers/miq_policy_controller/policy_profiles_spec.rb
Fix for https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/9367
before
after
cc @chessbyte
=> Fixed `.find` call in Profile remove_member call

app/assets/javascripts/directives/url_validation.js, app/views/ansible_repository/_repository_form.html.haml
This is already allowed in the backend:
https://github.com/ManageIQ/manageiq/blob/cf751304/app/models/git_repository.rb#L12
So this should just be enforcing this in the same fashion on the frontend as we do in the backend.
Links
-----
* Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1845281
* Link to chat in `gitter`: https://gitter.im/ManageIQ/manageiq/ui?at=5ed96f049da05a060a509a2f
* Simlar to what was done previously:  https://github.com/ManageIQ/manageiq-ui-classic/pull/3694
* Info about `file:///` format:  https://en.wikipedia.org/wiki/File_URI_scheme
* Implementation of `isUrl`:  https://github.com/gkaimakas/angular.validators/blob/cc0204498bb57333082b0a70f2fd71beee86db4f/angular.validators.js#L316-L376
Can't enter valid `file:///` …
=> [url_validation.js] Allow for file:// urls

app/views/vm_common/_reconfigure.html.haml
Before
After
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7096
=> Don't render empty cd-rom table in VM reconfigure screen

app/controllers/chargeback_assignment_controller.rb
With this change, direct links such as http://localhost:3000/chargeback_assignment?type=Compute,                       http://localhost:3000/chargeback_assignment?type=Storage should work.
=> Change to support simplified direct link for assignments

app/javascript/react/textual_summary_click.js, app/views/layouts/_empty.html.haml, app/views/shared/views/_alerts_list.html.haml
We only really have external links to documentation and provider UIs,
but better make sure they all have the right `rel` attributes set.
Cc @Fryguy
=> Add noreferrer noopener to external links

config/routes.rb
I am not able to find usage and also do some testing in UI after removal, it seems that it can be removed 👍 
(form_field_changed can be removed because you cannot create or edit key pair)
=> Remove unused routes from auth_key_pair cloud_controller

config/routes.rb, spec/routing/ems_configuration_routing_spec.rb, spec/routing/ems_infra_routing_spec.rb, spec/routing/ems_physical_infra_routing_spec.rb, spec/routing/ops_routing_spec.rb, spec/routing/orchestration_stack_routing_spec.rb, spec/routing/security_group_routing_spec.rb, spec/routing/service_routing_spec.rb, spec/routing/shared_examples/tagging_examples.rb
This is something we forgot to remove when we moved to the tagging react component, it's no longer necessary. Credit for [finding](https://github.com/ManageIQ/manageiq-ui-classic/pull/7113#discussion_r437533003) it goes to @lpichler.
=> Drop the unused tag_edit_form_field_changed route

app/helpers/ems_infra_helper/textual_summary.rb, spec/helpers/ems_infra_helper/textual_summary_spec.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7042
Go to Compute -> Infrastructure -> Providers -> click on one
Before:
After:
=> Add region id to Provider summary

app/javascript/components/async-credentials/async-credentials.jsx
When validating credentials in DDF (not necessary provider forms) there should be a message that the credentials are valid.
=> Display a validation success message upon DDF credential validation

app/controllers/dashboard_controller.rb
There's no check on the group ID when switching groups, basically any group ID can be looked up. However, there's a [validation on the model level](https://github.com/ManageIQ/manageiq/blob/master/app/models/user.rb#L47), so this can't cause privilege escalation. Still, this change makes the code more straightforward and prevent other people from getting jumpscared while reviewing PRs in the area :rofl:
=> Do not allow the users to switch to a group that they don't belong to

app/controllers/ops_controller/ops_rbac.rb
When re-rendering a react/redux-based tree using RJS, the reducers would be added multiple times. In order to prevent this from happening, @brumik [created a safeguard](https://github.com/ManageIQ/manageiq-ui-classic/commit/87f53cc230609215a72e5b0c3b6295da69fc3f34) that doesn't allow to add the reducers on the same tree twice. It relies on the (non)existence of the tree's name in the redux space, which can cause problems if we re-render a tree with the same name but with a different set of reducers. 
There's such [issue](https://github.com/ManageIQ/manageiq-ui-classic/pull/6413#issuecomment-642783675) on the `Access Control -> Roles` screen when first displaying and then editing a role. My quick and easy solution for this problem to rename the tree when not in edit mode. I would rather …
=> Rename the features_tree when not in edit mode under Access Control

app/views/miq_ae_customization/_dialog_sample.html.haml
When creating a service dialog with timepicker, it is possible to select a default date / time for the input. Though when we render the dialog sample screen, we only allow every fifth minute to be selected and rendered.
This change allows to select and render every minute in an hour in the datepicker element.
https://bugzilla.redhat.com/show_bug.cgi?id=1706848
For the above bz to be properly addressed in ivanchuk, we need the following PR https://github.com/ManageIQ/ui-components/pull/373 to be cherry-picked into ivanchuk.
=> Allow to select whole hour in dialog sample screen

app/controllers/dashboard_controller.rb
fix for https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8649
before
after
=> Translate title of entries under Add a Widget button

app/views/dashboard/_widget.html.haml
fix for https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8599
before
after
=> Translate title of Dashboard widgets

spec/presenters/tree_node/vm_or_template_spec.rb
follow-up to ManageIQ/manageiq#20250
Should fix `uninitialized constant VmXen` on UI travis:
https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/349739834#L2470-L2502
=> Remove extra *_xen reference from specs

app/controllers/cloud_tenant_dashboard_controller.rb, app/controllers/container_dashboard_controller.rb, app/controllers/ems_cloud_dashboard_controller.rb, app/controllers/ems_infra_dashboard_controller.rb, app/controllers/ems_physical_infra_dashboard_controller.rb, config/routes.rb
These methods were copy-pasted and they're not used at all.
=> Delete unused *DashboardController#show methods and routes

app/controllers/catalog_controller.rb, app/controllers/consumption_controller.rb, app/controllers/infra_networking_controller.rb, app/controllers/miq_policy_controller.rb, app/controllers/service_controller.rb, app/controllers/storage_controller.rb, app/controllers/vm_cloud_controller.rb, app/controllers/vm_infra_controller.rb, app/controllers/vm_or_template_controller.rb, config/routes.rb
Some dead `index` routes are completely unnecessary, these have been added to the list of skipped routes in the configuration. The other group of these is routed to controllers that can directly map to a model. In order to keep the `url_for_only_path` helper method functioning, these routes have not been removed, but I introduced the missing methods that redirect them to the `show_list` or `explorer` actions. This pattern already existed in our codebase for some controllers.
=> Clean up dead index routes

config/routes.rb, spec/routing/catalog_routing_spec.rb
There is method `identify_catalog` on OpsController but I was not able to find usage of this method as action method for `identify_catalog` route.
=> Remove unused route identify_catalog in OpsController

app/controllers/report_controller/schedules.rb, config/routes.rb, spec/routing/report_routing_spec.rb
I missed some routes from my [previous PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/7123)
The `ReportController#show_saved` has been deleted and it causes a [bug](https://github.com/ManageIQ/manageiq-ui-classic/issues/7126) in e-mails generated from reporting. However, as it is dead, I'm removing it and the bugfix should reintroduce the route in the future.
=> Remove some additional dead routes from the application

config/routes.rb
This is the only remaining dead route which I kept from https://github.com/ManageIQ/manageiq-ui-classic/pull/7131 to demonstrate the correctness of https://github.com/ManageIQ/manageiq-ui-classic/pull/7138
=> Do not mount the index route on ContainerDashboardController

.travis.yml, Rakefile, spec/routes_spec.rb
I created a spec that runs through all routes and checks if the method to be called when the route is accessed exists on the given controller. This test should warn us about remaining routes and possibly dead code when moving our UI towards an API-driven single page application.
Right now it takes a minute to run all the tests, however, the pattern can and will allow us to write other kinds of global tests. These new tests I'm currently working on can run up to 10 minutes, so I just created a separate suite for this in Travis. Locally you can run it using:
```sh
bundle exec rake spec:routes
```
On the CI results you can see that the `spec` suite [ignores](https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/350792788) the new specs, while the `spec:routes` suite …
=> Introducing a new test suite that checks the aliveness of routes

app/controllers/application_controller.rb, app/controllers/vm_common.rb
fixes `ManageIQ::Providers::Google::CloudManager Inst Including Associations (0.1ms - 1rows)
[----] F, [2020-06-17T13:58:28.726000 #394303:ae790] FATAL -- : Error caught: [NoMethodError] undefined method 'all_vms_and_templates'` from https://github.com/ManageIQ/manageiq/issues/20284
broken in https://github.com/ManageIQ/manageiq/pull/20149
@agrare this better?
=> nix the all_vm_or_templates callers

app/controllers/catalog_controller.rb, app/presenters/tree_builder_tenants.rb, spec/controllers/catalog_controller_spec.rb
This enhancement allows for selecting / deselecting whole tenant subtree during catalog item creation and editing. This would mean that the customer would no longer have to select all individual projects & tenants (although that is still possible), but can just select root of the desired tenant subtree.
The presenter change simply modifies the rendered tree to allow for selection / deselection of the while subtree. The controller change automatically adds all descendants & removes all ancestors during addition / deletion.
https://bugzilla.redhat.com/show_bug.cgi?id=1838704
Ivanchuk version of this: https://github.com/ManageIQ/manageiq-ui-classic/pull/7140
=> Catalog Item: allow for selecting / deselecting whole tenant subtree

app/views/report/_form.html.haml, app/views/report/_form_columns.html.haml
Route report#create was removed [here](https://github.com/ManageIQ/manageiq-ui-classic/pull/7123) but is still used in form actions and rails are trying to generate url according to form action.
Reproducer is just open form to create or edit report.
@miq-bot add_label bug, jansa/no
@skateman No sure whether such issue could be also on other places - do you think that there is way how to  create script/spec which detects such places ? (I don't how to exactly recognise forms which doen't use form#action)
=> Remove form action in report editor forms

app/controllers/catalog_controller.rb, app/presenters/tree_builder_tenants.rb, spec/controllers/catalog_controller_spec.rb
This is ivanchuk version of https://github.com/ManageIQ/manageiq-ui-classic/pull/7142
This enhancement allows for selecting / deselecting whole tenant subtree during catalog item creation and editing. This would mean that the customer would no longer have to select all individual projects & tenants (although that is still possible), but can just select root of the desired tenant subtree.
The presenter change simply modifies the rendered tree to allow for selection / deselection of the while subtree. The controller change automatically adds all descendants & removes all ancestors during addition / deletion.
https://bugzilla.redhat.com/show_bug.cgi?id=1838704
=> [IVANCHUK] Allow selecting whole tenant subtree in catalog item creation

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
Not all cloud volumes belong to a StorageManager, most (OpenStack and GCE) belong to the main CloudManager.
Asking for cloud_volume.ext_management_system.parent_manager will fail in these cases because the parent_manager association doesn't exist on the "main" manager class.
Instead we can use delegates to be able to access what is needed from the AWS storage_manager, thus allowing the provider plugin to define how different collections are accessed rather than encoding this in the UI.
Before (GCE):
After (GCE):
After (AWS):
Depends on: https://github.com/ManageIQ/manageiq-providers-amazon/pull/631 https://github.com/ManageIQ/manageiq-providers-openstack/pull/607
=> Don't use the cloud_volume ems.parent_manager

app/controllers/application_controller.rb, app/controllers/application_controller/miq_request_methods.rb, app/controllers/vm_common.rb, app/helpers/hide_partial_helper.rb, app/views/miq_request/_pre_prov.html.haml, app/views/miq_request/pre_prov.html.haml, spec/controllers/application_controller_spec.rb
Fixes #7011
Fixes #6543 
Before:
explorer versions of pre-provisioning (Compute > Infra/Cloud > VMs/Instances .. Lifecycle > Provision)
still have the Continue/Cancel buttons as part of the bottom toolbar,
which collides with paging toolbar when in using lower screen widths
non-explorer versions (Compute > I/C > Providers > click one, Instances/VMs .. Lifecycle > Provision)
have the buttons in the right place,
but don't show the Hide deprecated checkbox, because only the controller is checked now, and it's the wrong one
After:
both versions use the same form buttons, outside the bottom toolbar
hide deprecated works whenever cloud templates are shown
=> Pre-provisioning: fix button collision in explorers and missing hide deprecated in nested

Gemfile
Since we inherit the `Gemfile` from `ManageIQ/manageiq` in this repo, there is now a deprecation warning when running `bundler` v2.1.4:
```
[DEPRECATED] Your Gemfile contains multiple primary sources. Using
`source` more than once without a block is a security risk...
```
This is because there is a duplicate source when evaling the `Gemfile` from `ManageIQ/manageiq`.  Since that one needs to stay, removing this one allows `bundle update` and friends to continue to work without the deprecation warning.
Links
-----
* **Before**: [Example warning on `travis` prior to this fix](https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/354577492#L240)
* **After**: [`travis` run for this PR](https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/354631147#L263-L268) (no deprecation …
=> [Gemfile] Remove "second" source

app/assets/javascripts/controllers/error_modal_controller.js, app/controllers/application_controller.rb
Fixes #485 
When a rails exception occurs during an AJAX request, we try to render the exception screen inside center_div.
Depending on the screen, it may not be there at all, or may be positioned wrong.
This changes the mechanism to cause the error modal to pop up even for old-style ajax requests (it already did that for angular).
It means we no longer show the whole exception_contents layout partial, only the actual error message, but that's where the error is.
For exceptions during full-page render, neither issue is present, so those stay the same:
But for AJAX exceptions:
(Content-type and Status are normally also displayed, but for these responses, it's always 200 OK and javascript.)
=> render_exception: use error modal

app/controllers/vm_common.rb, app/views/layouts/_x_edit_buttons.html.haml
Not having a back button and locked sidebar was causing user to make selection in the tree while on Chargeback Preview screen and running into errors in replace_right_cell call because `@sb[:action]` value was still set to `chargeback`.
Fixes #3678
before
after
=> Added `Back` button and locked sidebar on Chargeback Preview screen.

app/presenters/menu/default_menu.rb, config/settings.yml
Depends on: https://github.com/ManageIQ/manageiq/pull/20320
Fixes: https://github.com/ManageIQ/manageiq-documentation/issues/557
when `Settings.docs.product_documentation_direct_link` is true (default),
the documentation link goes to `Settings.docs.product_documentation_website`
false (and previous behavior) goes to the local PDFs screen in SupportController (which is empty without any local documentation PDFs).
This also moves provider documentation links to core, to keep `Settings.docs` in one place.
Cc @Fryguy
=> help_documentation: use product_documentation_website

app/helpers/application_helper/toolbar/generic_object_definition_button_center.rb, app/helpers/application_helper/toolbar/generic_object_definition_button_group_center.rb
Changed button text in custom button group and custom button toolbar to be consistent with others in same toolbar and to the one that exists in translated files.
before
after
=> Fixed button text to be consistent with others in the toolbar

app/controllers/vm_common.rb, app/helpers/application_helper/page_layouts.rb, app/views/vm_common/_policy_options.html.haml
Go to Cloud Provider summary screen. Click on Instances link, then from the list select one or more Instance(s), Press Policy Simulation button for one or more selected instance(s). On the Policy Simulation screen, Add a Policy Profile and then click on one of the Instances to see results of Policy simulation - Notice missing title on screen and an extra listnav on the left side. This fix removes the extra layout from the screen and adds the title on the Policy simulation result screen. Title was missing when going to the screen thru relationships(non-explorer style screen)
before
after
=> Display title on nested Policy Simulation screen.

app/helpers/application_helper/toolbar/container_template_center.rb
Add checks for the instantiation supports_feature and disable the button if it isn't supported.
Fix for https://github.com/ManageIQ/manageiq-ui-classic/pull/7156
=> Check for container template instantiation support

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js, app/controllers/mixins/ems_common/angular.rb, app/views/layouts/angular/_multi_auth_credentials.html.haml
This enhancement allows to create Service Telemetry Framework (event collection) endpoint for OpenStack cloud provider.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7000
=> [JANSA] Add support for Service Telemetry Framework

app/javascript/components/orchestration-template/orchestration-template-form.schema.js, app/javascript/forms/mappers/formFieldsMapper.jsx
- Added a "Note" field mapping to React forms to be able to show a note on the React forms. This is to eliminate a confusion/issue on Orchestration Template edit form, where user is prompted to select a format yaml/json for the template contents, format type is not saved in the database. Selected format type is applied to show syntax highlighting to help user with better readability of contents while they are entering text in the field.
- Made a change to select format type based upon save content value.
before
after
=> Added a "Note" field mapping to React forms.

app/controllers/mixins/manager_controller_mixin.rb, app/helpers/ems_configuration_helper.rb, app/views/ems_configuration/edit.html.haml, app/views/ems_configuration/new.html.haml
Depends on: https://github.com/ManageIQ/manageiq-providers-foreman/pull/62
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
**Before:**
**After:**
This change will allow us to add any other configuration management provider on this form.
@miq-bot add_label pending core
=> Replace old angular config provider form with the new ProviderForm

app/controllers/generic_object_definition_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1719889
Makes `Generic Objects` part of breadcrumbs clickable so it's same as on master.
Before:
After:
=> [JANSA] Fix GOD breadcrumbs

app/views/miq_policy/_policy_details.html.haml
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/1943
=> Enable / disable policy move buttons as needed

app/views/catalog/_ot_tree_show.html.haml
1. navigate to orchestration template details page, notice the screen contains template content
2. hit browser refresh (full page reload), notice the screen no longer contains template content
Before (after page reload):
After (after page reload):
https://bugzilla.redhat.com/show_bug.cgi?id=1760510
=> Correctly render orch. template after content after page refresh

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js, app/controllers/mixins/ems_common/angular.rb, app/views/layouts/angular/_multi_auth_credentials.html.haml
This enhancement allows to create Service Telemetry Framework (event collection) endpoint for OpenStack cloud provider.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7000
=> [IVANCHUK] Add support for Service Telemetry Framework

app/assets/stylesheets/main.scss
This PR adjusts the masthead background color to match the header image on the right. (The header image is not necessary for the default branding, but has been left in for users who continue to rebrand the header with an image like was used in the previous design.)
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6983
Old
New
=> [IVANCHUK] header fix

app/controllers/ops_controller/ops_rbac.rb, spec/controllers/ops_controller/ops_rbac_spec.rb
set `@sb[:active_rbac_group_tab`] as it may not be set correctly because of lazy loading
Closes https://github.com/ManageIQ/manageiq-ui-classic/issues/5817
- Go to Configuration > Access Control > Groups > Create/Edit a Group
- make sure My Company Tags is set to `Tags based on expression`
- click My Company Tags and other tabs so they no longer fire request `rbac_group_load_tab` (spinner no longer shows up)
- click My Company Tags and select `Specific Tags` for `This user is limited to` 
*Before:*
Console log:
```
miq_debug.self-1351f771c2cd2fab0d83069fd3f62aadbb7effc11a01ed4942f52308793453be.js?body=1:30 TypeError: Cannot read property 'tags' of null
at initialize (reducers.js:76)
at taggingApp (index.js:14)
at combination (redux.js:459)
at dispatch (redux.js:213)
at …
```
=> Fix missing tags on Group form

app/controllers/application_controller.rb
When clicking on a breadcrumb link while in a form without cancelling out of the form, code was setting `object_ids` from previously stored data in `@edit` causing not to load correct records in the list view.
Fixes #5383
=> only set `object_ids` if in a form.

app/helpers/application_helper/button/catalog_item_copy_button.rb, app/helpers/application_helper/toolbar/servicetemplate_center.rb
=> Show hover text correctly on Copy catalog item button

app/services/container_service_mixin.rb, app/services/dashboard_service.rb, spec/services/container_dashboard_service_spec.rb
Fixes #7186
Compute > Containers > Projects
pick a project, switch to dashboard view
Add `dataAvailable` to a couple of places in dashboard services.
Otherwise, the container project dashboard doesn't display anything,
because `loadingDone` is true (no spinner),
`dataAvailable` is not false (no empty message),
or true (no chart).
I suspect the `dataAvailable` logic somehow changed in the other dashboards and this one was never updated, but I don't see the commit. 
@h-kataria any ideas? Or, does this make sense as is?
---
Before:
After:
---
Testing: you can use https://github.com/yaacov/miq-scripts/blob/master/set-miq-metric.rb to generate data, as long as you have at least one container project.
=> Container project dashboard - add missing dataAvailable

app/controllers/cloud_network_controller.rb, app/controllers/cloud_subnet_controller.rb, app/controllers/ems_network_controller.rb, app/controllers/floating_ip_controller.rb, app/controllers/miq_request_controller.rb, app/controllers/mixins/breadcrumbs_mixin.rb, app/controllers/mixins/menu_section.rb, app/controllers/network_port_controller.rb, app/controllers/network_router_controller.rb, app/controllers/network_service_controller.rb, app/controllers/network_topology_controller.rb, app/controllers/security_group_controller.rb, app/controllers/security_policy_controller.rb, app/controllers/security_policy_rule_controller.rb
the Network section was renamed from Networks in #6994, but `breadcrumbs_options` hardcode the section name in all the network controllers.
Adding a helper that uses `menu_section` to determine the right menu section, and use its name, instead of hardcoding the name
(https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10909)
Before:
After:
=> Network controller breadcrumbs: fix menu section name: Networks -> Networks, helper

manageiq-ui-classic.gemspec
more core ext's on 4.1.0
update for update sake
https://github.com/ManageIQ/more_core_extensions/compare/179bf40..e5b4501
- Added Ruby 2.7 support [[#79](https://github.com/ManageIQ/more_core_extensions/pull/79)]
- Added Process#pause, Process#resume, and Process#alive? [[#73](https://github.com/ManageIQ/more_core_extensions/pull/73)]
array added * `#compact_map` - Collect non-nil results from the block
array added `#tabular_sort` - Sorts an Array of Hashes by specific columns
hierarchy added `#descendant_get` - Returns the descendant with a given name
the two breaking changes:
- **BREAKING**: Moved Object#descendant_get to Class#descendant_get [[#75](https://github.com/ManageIQ/more_core_extensions/pull/75)]
- **BREAKING**: Removed deprecated Enumerable#stable_sort_by …
=> bump more core extensions

app/controllers/miq_policy_controller/alerts.rb, app/controllers/miq_policy_controller/policies.rb, app/helpers/application_helper/toolbar/miq_policies_center.rb, app/views/miq_policy/_policy_details.html.haml
@mzazrivec please review if this is the right way to fix these. I have noticed some of these strings are missing from translations
before
after
=> Fixed to translate strings in UI

app/javascript/components/copy-catalog-form/copy-catalog-form.jsx, config/jest.setup.js
Services > Catalogs >> Catalog Items
toolbar Configuration > Copy
After:
This adds the flash message when copying a catalog item.
This is to make it explicit that copying a catalog item will clear the "Display in catalog" checkbox.
(That part happens during `ServiceTemplate::Copy#template_copy` and is intentional.)
Fixes https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10828
=> copy catalog - add info notice about copy not being in catalog by default

spec/presenters/tree_builder_sections_spec.rb
This is to fix the following CI failure:
```
1) TreeBuilderSections TreeBuilderSections sets roots correctly
Failure/Error:
expect(roots).to eq([{:id         => "group_Properties",
:text       => "Properties",
:tip        => "Properties",
:image      => false,
:selectable => false,
:nodes      => [{:name => :_model_, :header => "Filesystem", :group => "Properties"}]}])
expected: [{:id=>"group_Properties", :image=>false, :nodes=>[{:group=>"Properties", :header=>"Filesystem", :name=>:_model_}], :selectable=>false, :text=>"Properties", :tip=>"Properties"}]
got: [{:id=>"group_Properties", :image=>false, :nodes=>[{:group=>"Properties", :header=>"File", :name=>:_model_}], :selectable=>false, :text=>"Properties", :tip=>"Properties"}]
Diff:
@@ -1,6 +1,6 @@ …
```
=> Fix failing tree_builder_sections_spec

app/views/miq_policy/_alert_details.html.haml
@miq-bot add_label bug, jansa/yes, internationalization
=> Add I18N support to expression type in alerts.

app/controllers/firmware_registry_controller.rb, app/presenters/menu/default_menu.rb, spec/presenters/menu/default_menu_spec.rb
=> Moved 'Firmware Registries' under 'Physical Infrastructure' menu

config/routes.rb
I think this is a dead route, just a biproduct of some copy-paste.
=> Delete the unused users route form AutomationManagerController

cypress/integration/ui/menu.spec.js, cypress/support/commands.js
Fixes two issues with the spec:
- `menuItems` was not doing any form of a "wait" before trying to fetch the items
- Fixed invalid Menu navigations (trying to click on a top level menu) after the Carbon style menu changes from https://github.com/ManageIQ/manageiq-ui-classic/pull/6963
This test file should pass now.
Links
-----
* Menu navigation changes (cause some of the failures): https://github.com/ManageIQ/manageiq-ui-classic/pull/6963
=> Fix menu.spec.js

config/routes.rb, spec/routing/host_routing_spec.rb, spec/routing/storage_routing_spec.rb
The definition of these methods expect arguments, which is not possible when you want to have routes.
=> Remove the unused show_association/show_details routes

app/controllers/miq_policy_controller.rb
Fix policy strings like this one.
@miq-bot add_label bug, jansa/yes, internationalization
=> Fix to Policy's I18N strings.

config/routes.rb
Reproducer:
Click on Settings -> Regions (tree) -> Regions(list) - error displayed
caused by [this](https://github.com/ManageIQ/manageiq-ui-classic/pull/7117)  but according to this [comment](https://github.com/ManageIQ/manageiq-ui-classic/pull/7117#issuecomment-644787637)  we should not backport the PR to jansa.
other removed routes from [the PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/7117) or haml can stay removed.
cc @gtanzillo
=> [JANSA] Add missing routes for OpsController actions

lib/tasks/manageiq/ui_tasks.rake
If yarn isn't installed the user gets a vague "yarn failed in #{plugin}"
error which isn't obvious what failed.
We can check that the command exists prior to running yarn and thus
print a helpful error message.
Before:
```
$ rake update:ui
== yarn failed in /home/agrare/.gems/2.7.0/bundler/gems/manageiq-providers-lenovo-c1b52532c712 ==
```
After:
```
$ rake update:ui
== You have to install yarn ==
```
=> Check that yarn is installed when updating

spec/controllers/automation_manager_controller_spec.rb
related to https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/229
name is required, so providing one
Cc @agrare 
---
Fixes travis failure...
https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/364237496#L2495
```
1) AutomationManagerController#edit should save the zone field
Failure/Error: @provider.name       = params[:name]
NoMethodError:
undefined method `sub' for nil:NilClass
```
the name is required and the test was not providing it.
=> Fix failing automation spec - missing name

app/controllers/application_controller.rb, app/controllers/miq_policy_controller.rb, app/controllers/miq_policy_controller/alert_profiles.rb, app/controllers/miq_policy_controller/alerts.rb, app/controllers/miq_policy_controller/conditions.rb, app/controllers/miq_policy_controller/miq_actions.rb, app/controllers/miq_policy_controller/policies.rb, app/controllers/miq_policy_controller/policy_profiles.rb, app/helpers/application_helper/button/condition.rb, app/helpers/application_helper/button/condition_delete.rb, app/helpers/application_helper/button/policy_delete.rb, app/helpers/application_helper/toolbar/condition_center.rb, app/helpers/application_helper/toolbar/miq_action_center.rb, app/helpers/application_helper/toolbar/miq_alert_center.rb, app/helpers/application_helper/toolbar/miq_alert_profile_center.rb, app/helpers/application_helper/toolbar/miq_policy_center.rb, app/helpers/application_helper/toolbar/miq_policy_profile_center.rb, app/javascript/components/remove-generic-item-modal.jsx, app/javascript/spec/remove-generic-item-modal/remove-generic-item-modal.spec.js, config/routes.rb, spec/controllers/miq_policy_controller/alert_profiles_spec.rb, spec/controllers/miq_policy_controller/alerts_spec.rb, spec/helpers/application_helper/buttons/condition_delete_spec.rb, spec/presenters/tree_builder_sections_spec.rb, spec/routing/miq_policy_routing_spec.rb
This changes all deletions in Control > Explorer (alert_profiles, alerts, conditions, miq_actions, policies, policy_profiles)  to use the API.
Continuing @mzazrivec 's effort (https://github.com/ManageIQ/manageiq-ui-classic/pull/6812 and others), this uses `RemoveGenericItemModal` on the UI side.
Fixes https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10722 + https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10521 by not using the uuid in `name`, but preferring the name in `description` when asking for confirmation - added a `display_field` option for `RemoveGenericItemModal` to achieve that.
=> Control > Explorer - use RemoveGenericItemModal + API for deletions

app/assets/javascripts/miq_tree.js
1. Create a role with `Everything > Services > Catalog Explorer > Catalog Items` only
2. Create a user using the above role
3. Create a service dialog and catalog item using the created dialog
4. As the newly created user, navigate to `Services > Catalogs > Catalog Items > [the above created catalog item]`
5. Observe the following error in javascript console:
```
react_devtools_backend.js:2273 TypeError: Reduce of empty array with no initial value
at Array.reduce (<anonymous>)
at miqInitTree (application-8c25e4425d87073edf7151217c873f7544b8598c0754dc3e79329ecb198b661a.js:3)
at eval (eval at globalEval (jquery.js:343), <anonymous>:1:1)
at eval (<anonymous>)
at Function.globalEval (jquery.js:343)
at ye (jquery.js:5291)
at _.fn.init.append (jquery.js:5431)
at _.fn.init.<anonymous> …
```
=> [JANSA] Dont walk empty child nodes for parent check

app/controllers/ops_controller/settings/label_tag_mapping.rb, spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
- We already prefix tag names with the entity type of the mapping. But we don't prefix the corresponding
classification descriptions and that causes a failure on the uniqueness validation of the Classification
- Adding the same prefix to the description prevents this
- The prefix is added before saving and stripped off before displaying in the UI
Worked on this with @lpichler
=> Allow mapping different entity types to the same base category

cypress/integration/ui/searchbox.spec.js
For both specs, they suffered from the menu changes https://github.com/ManageIQ/manageiq-ui-classic/pull/6963 so those have been addressed to use some form of an equivalent.
For the first spec ("is present"), it also had a random "div click" in there that either doesn't make sense any more, is entirely unnecessary, or there is a disconnect between the author of this commit (me) and the original author of the spec.  Regardless, commenting out the line in question allows the spec to pass.
Links
-----
* PR changing menu functionality: https://github.com/ManageIQ/manageiq-ui-classic/pull/6963
=> [search_box.spec.js] Fix failing specs

config/webpack/development.js, config/webpacker.yml
devServer is enabled/disabled by running webpack vs webpack-dev-server
not by commenting or uncommenting the yaml config bit
this makes webpack not fail in development when dev_server config is missing,
and moves the defaults to webpack.
Cc @NickLaMuro
=> webpack - make dev_server config optional

app/views/miq_policy/_policy_details.html.haml
Control > Explorer >> Policies/Policy Profiles
open policy detail, see table of Conditions
when an expression is too long, the nested table in the Scopes/Expression column wraps both the "Expression" column, and the actual expression, leading to weirdly looking text
updated to just use newlines to separate the type from the expression
(Fixes https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/11668)
---
Before:
note the vertical "Expression" text that's *not* part of the regex :)
After:
---
With both scope and expression, before:
After:
=> Policy detail - Conditions - replace nested Scopes/Expressions table with divs

app/helpers/ops_helper.rb, app/views/ops/_settings_authentication_tab.html.haml, spec/helpers/ops_helper_spec.rb, spec/views/ops/_rbac_group_details.html.haml_spec.rb
This PR will disable the option to select options LDAP and LDAPS from the authentication page,
which is how the deprecated MiqLdap is configured.
The plan is to disable the option to select LDAP and LDAPS from the UI first.
Then remove MiqLdap from the back end a release later.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7227
Links
* The associated back end issue is: [20017](https://github.com/ManageIQ/manageiq/issues/20017)
To test navigate to the authentication page, Settings -> Server -> Authentication
Then confirm `LDAP` and `LDAPS` are no longer valid options in the `Mode` pull down.
=> Disable the option to select LDAP and LDAPS

app/views/cloud_volume/_common_new_edit.html.haml
MIQ UI volume create form should not require availability zone as a mandatory field. Openstack API also have this field as optional.
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=1859388
=> Change availability Zones field to non-mandatory

app/helpers/application_helper/toolbar/x_vm_snapshot_center.rb
The snapshot tree isn't updating the number of selected items in the redux store, therefore the `onwhen` parameter disabled the snapshot deletion button. 
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7199
=> Allow unconditional revert/delete of snapshots in the 📸🌳

app/views/automation_manager/_form.html.haml, spec/controllers/automation_manager_controller_spec.rb
As this provider screen is explorer-based, it has some issues with redirects after creating/editing. The redirect after an API call requires a permalink to a given provider, which is not doable here. Therefore, as long as this screen is not de-explorerized, any operation will redirect back to the providers list screen.
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
Depends on: https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/228 https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/229
=> Replace old angular ansible tower form with a react based DDF

app/controllers/chargeback_assignment_controller.rb
Since we stay on the form screen even after pressing Save button on screen, moved call to `set_form_vars` outside case statement, we should set form data for when either of save or reset buttons are pressed. Existing code only did that when Reset was pressed.
Fixes https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/11283
=> Set form data after Reset or Save button are pressed

app/javascript/components/cloud-network-form/cloud-network-form.schema.js, app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
https://bugzilla.redhat.com/show_bug.cgi?id=1862202
=> Add 'geneve' provider network type

app/helpers/application_helper/toolbar/override.rb
Right now, a plugin toolbar override can replace entire ui-classic button groups by accidentally using the same name.
If multiple plugins do that for the same entity, a random plugin would win.
By prefixing button group ids for groups from plugins, each plugin gets a unique namespace within the toolbar,
so it can still add selects and buttons, just not replace existing ones.
(I would like to solve the labeling clashes too, by prefixing plugin buttons with the plugin name, but I don't see a way of doing "class.source_engine", so without guessing from the class name, or explicitly adding the name in each override, I don't see a nice way, so we may need to solve it plugin-side.)
(It might also be nice to merge dropdowns, but not very realistic, as then we would need the buttons to have …
=> Toolbar overrides: don't overwrite existing groups

app/javascript/components/provider-form/index.jsx
When we introduced DDF, the provider name was missed from the flash message when cancelling the edit of a provider.
**Before:**
**After:**
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
Fixes #7244
=> Display the provider's name in the flash when cancelling edit

spec/controllers/application_controller/tree_support_spec.rb, spec/controllers/miq_policy_controller/alert_profiles_spec.rb, spec/controllers/miq_policy_controller/alerts_spec.rb, spec/controllers/miq_policy_controller/miq_actions_spec.rb, spec/controllers/miq_report_controller/trees_spec.rb, spec/controllers/ops_controller/ops_rbac_spec.rb, spec/controllers/ops_controller_spec.rb, spec/controllers/pxe_controller_spec.rb, spec/controllers/report_controller_spec.rb, spec/controllers/service_controller_spec.rb
Needed to allow access to specific features for a logged in user and adjust. In some places needed to make sure to pass in tree name on `tree_select` calls.
Fixing failures in https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/369835476
@Fryguy please take a look.
=> Fixing spec test failures

spec/controllers/miq_policy_controller/alert_profiles_spec.rb
Gave `alert_profile_delete` feature access to logged in user.
Fixing failures in https://github.com/ManageIQ/manageiq-ui-classic/pull/7250#issuecomment-671505536
=> [JANSA] - Fixing spec test failures on Jansa

app/controllers/catalog_controller.rb, app/controllers/miq_ae_class_controller.rb, app/helpers/automate_tree_helper.rb, app/views/catalog/_form_basic_info.html.haml, app/views/miq_ae_class/_copy_objects_form.html.haml, config/routes.rb
2 screens containing input for automate endpoint have been modified so that the input would allow cut & paste of the desired string (automate endpoint). The modified input would also contain two buttons: one for opening the automate tree selector and another button for removing entered text.
Catalog item screen:
Copy automate namespace screen:
https://bugzilla.redhat.com/show_bug.cgi?id=1740397
=> Allow cut & paste in automate entry point input

cypress/integration/ui/gtl.spec.js
The way these specs are written, this is not possible to re-enable these specs at this time.
Once factories are available, then we can consider it.
Links
-----
* Example run on CI here:  https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/150
=> "Fix" gtl.spec.js

cypress/integration/ui/settings.spec.js
Since VMs don't exist (for now) with our default state for specs, use a different screen that doesn't require data to be available.
`Configuration -> Providers` is a perfect candidate for that, since it isn't the default page we land on, and has an enabled menu item by default..
Links
-----
* Example run on CI here:  https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/150
=> Fix settings.spec.js

app/javascript/components/cloud-tenant-form/create-form.schema.js
Strings are so 2019, let's use constants here :laughing: also helps with some DDFv2 issues
=> Use constants for component/validator types in cloud tenant form

app/controllers/tree_controller.rb
Actually we used ancestry instead of parent_id
```
[----] F, [2020-08-07T08:53:02.418285 #9:2aecc843f884] FATAL -- : Error caught: [ActiveRecord::StatementInvalid] PG::UndefinedColumn: ERROR:  column miq_ae_namespaces.parent does not exist
LINE 1: ...spaces" WHERE "miq_ae_namespaces"."name" = $1 AND "miq_ae_na...
^
: SELECT  "miq_ae_namespaces".* FROM "miq_ae_namespaces" WHERE "miq_ae_namespaces"."name" = $1 AND "miq_ae_namespaces"."parent" IS NULL LIMIT $2
/usr/share/gems/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:624:in `exec_params'
/usr/share/gems/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:624:in `block (2 levels) in exec_no_cache'
/usr/share/gems/gems/activesupport-5.1.7/lib/active_support/dependencies/i …
```
=> switch parent to ancestry (miq_ae_namespaces)

app/controllers/ops_controller/settings/common.rb, app/controllers/ops_controller/settings/rhn.rb, spec/controllers/ops_controller/settings/common_spec.rb
This fix is to make sure the `Save` button in Red Hat Updates form will be enabled after successful credentials validation.
Credential validation failed: `Save` button is disabled
Credential validation passed: `Save` button will become enabled
https://bugzilla.redhat.com/show_bug.cgi?id=1740698
=> Enable 'Save' button after successful RHN credentials validation

app/controllers/application_controller/ci_processing.rb, app/controllers/application_controller/compare.rb, app/controllers/cloud_object_store_container_controller.rb, app/controllers/cloud_object_store_object_controller.rb, app/controllers/ems_cluster_controller.rb, app/controllers/ems_infra_controller.rb, app/controllers/ems_storage_controller.rb, app/controllers/host_controller.rb, app/controllers/miq_template_controller.rb, app/controllers/orchestration_stack_controller.rb, app/controllers/resource_pool_controller.rb, app/controllers/service_controller.rb, app/controllers/storage_controller.rb, app/controllers/vm_common.rb, spec/controllers/application_controller/ci_processing_spec.rb, spec/controllers/cloud_object_store_container_spec.rb, spec/controllers/ems_cluster_controller_spec.rb, spec/controllers/ems_infra_controller_spec.rb, spec/controllers/ems_storage_controller_spec.rb, spec/controllers/host_controller_spec.rb, spec/controllers/miq_template_controller_spec.rb, spec/controllers/orchestration_stack_controller_spec.rb, spec/controllers/resource_pool_controller_spec.rb, spec/controllers/service_controller_spec.rb, spec/controllers/storage_controller_spec.rb, spec/controllers/vm_common_spec.rb
This PR is a cherry-pick / backport of the following 2 PRs https://github.com/ManageIQ/manageiq-ui-classic/pull/6316 https://github.com/ManageIQ/manageiq-ui-classic/pull/6224 into ivanchuk. I'm creating a separate PR, because some of the files from 6224 would create a conflict during plain cherry-pick.
One of the nice effects of this backport will be that https://bugzilla.redhat.com/show_bug.cgi?id=1858107 will be fixed (among other bzs probably).
=> [IVANCHUK] Refactor get_rec_cls to get proper record class for various items

app/controllers/application_controller/miq_request_methods.rb
The various provision options set by the MiqVirtProvisionWorkflow class were changed recently from MiqHashStruct types to OpenStruct.  This was causing none of these conditional matchers to hit so the "else" case wasbeing invoked incorrectly.
Introduced by: https://github.com/ManageIQ/manageiq/pull/20374
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7270
=> MiqHashStruct was replaced by OpenStruct in provision workflow

app/views/miq_ae_customization/_dialog_sample.html.haml
Remove reference to unused dialog field button. 
related:
https://github.com/ManageIQ/manageiq/pull/20421 and https://github.com/ManageIQ/manageiq/pull/20459
=> remove reference to unused dialog field type

app/controllers/automation_manager_controller.rb
1. make sure you have no Ansible Tower provider
2. navigate to Ansible Tower explorer
3. switch accordion to `Configured Systems` and then back to `Providers`
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1860033
=> Correctly render add provider screen after accordion switch

app/views/ops/_label_tag_mapping_form.html.haml
Make fields Category and Label consistent in with list of mappings:
Change is in Label Tag Mapping form:
cc @gtanzillo 
=> Rename Category and Label in Label Tag Mapping Screen

app/views/miq_ae_customization/_dialog_sample.html.haml
This change is for service dialog preview screen to honor field sorting parameters of dropdowns & radio buttons:
* sort by key or value
* sort the values either as integers or strings
Needs to go in with https://github.com/ManageIQ/ui-components/pull/445
https://bugzilla.redhat.com/show_bug.cgi?id=1740878
=> Honor sorting options in dialog preview

app/controllers/miq_policy_controller/events.rb, spec/controllers/miq_policy_controller/events_spec.rb
Fixes ManageIQ/manageiq#20405
before
after
@lfu pls review
=> Call `allowed_for_policies` method to avoid infinite loop

app/controllers/mixins/actions/vm_actions/ownership.rb, spec/controllers/mixins/actions/vm_actions/ownership_spec.rb
Templates are not displayed in set ownership screen because report data request uses always `Vm` model.
This change should be ok -` VmOrTemplate.yml` exists.
Changed condition was here before the  initial commit.
(and when just templates are selected then it doesn't displays anything.)
=> Allow to display templates set ownership screen

app/controllers/report_controller.rb
Default sort column is improper in report results screen 
Related yaml for that screen is [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/product/views/MiqReportResult.yaml)
There is [code](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/report_controller/widgets.rb#L223) in method `get_all_widgets ` which set default sort column to `0` (it is first column from column list(`col_order[0]`) of view's yaml) and this default sort column is used also for sorting report results.
So this is probably OK for widget's lists but we want to control default sort column from related yaml of view's list.
so I was thinking about removing [code]([code](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/report_controller/widgets.rb#L223 …
=> Sort report results by default sort column from view's yaml

app/controllers/mixins/actions/vm_actions/ownership.rb, app/controllers/vm_common.rb, spec/controllers/vm_common_spec.rb
There was displayed only "Instance" or "Virtual Machine" regardless real type of resource. In other words it never display "Image" or "Template" in header. 
I added method which return string header according to model of passed record.
Links
-------
=> Fix header in Set Ownership Screen

app/assets/javascripts/controllers/security_group/security_group_form_controller.js, app/assets/javascripts/services/miq_service.js
1. Go to Network > Security Groups > Create a new Security Group
2. See the Network Manager dropdown list.
Before this fix, it would list all available network managers.
With this fix, it would only list network providers that support security group creation.
https://bugzilla.redhat.com/show_bug.cgi?id=1740656
Depends on https://github.com/ManageIQ/manageiq/pull/20482
=> Filter network providers supporting security group creation

app/controllers/mixins/actions/vm_actions/ownership.rb, app/views/shared/views/_ownership.html.haml
When you click on set ownership screen toolbar menu on catalog item with ansible you will get this error:
Issue is that collection name is improperly determined from service template record what this record had was more special) model class(ServiceTemplateAnsibleTower).
I used API yaml configuration to get proper collection name and I added helper method.
=> Use collection name form API yaml configuration in setownership screen 

app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
1. create a user role with access to html5 console: `All VM and Instance Access Rules > VM Access Rules > Operate > Console using HTML5`
2. create a user group and a user using the above role
3. log in as the above user
4. attemt to connect to cloud instance console
Before:
After:
The role identifier for the html5 console feature is `vm_html5_console` and the button identifier in UI needs to match this role identifier, otherwise the feature will never work properly.
https://bugzilla.redhat.com/show_bug.cgi?id=1873418
=> Fix html5 console button identifier

app/assets/stylesheets/patternfly_overrides.scss
popovers need to go over the menu but under the menu overlay.
Prevents `/ems_configuration/new` Username popover (amongst others) from being cut off by the menu.
Before:
After:
Cc @h-kataria
=> Fix popover hiding under menu

config/webpack/production.js
Part of #7289
With this change (based on the Ruby code in #7289) the webpack-modules-manifest.json now looks like this:
```json
[
{
"name": "@babel/runtime",
"license": "MIT",
"version": "7.11.0",
"location": "/Users/jfrey/.gem/ruby/2.6.5/bundler/gems/manageiq-v2v-d17c2571ae48/node_modules/@babel/runtime/package.json"
},
{
"name": "@babel/runtime",
"license": "MIT",
"version": "7.11.2",
"location": "./node_modules/@babel/runtime/package.json"
},
{
"name": "@babel/runtime-corejs2",
"license": "MIT",
"version": "7.11.2",
"location": "./node_modules/@babel/runtime-corejs2/package.json"
},
{
"name": "@carbon/icon-helpers",
"license": "Apache-2.0",
"version": "10.9.0",
"location": "./node_modules/@carbon/icon-helpers/package.json"
},
{
"name": "@carbon/icons-react",
"license": "Apache-2.0", …
```
=> Cross reference the webpack manifest with the actual node_modules

app/javascript/components/pf_aggregate_status_card.jsx
The following warning raised once we tried to implement new features that use the generic PfAggregateStatusCard.
Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s,[object Object], in p (created by PfAggregateStatusCard) in div (created by PfAggregateStatusCard) in div (created by PfAggregateStatusCard) in PfAggregateStatusCard (created by AggregateStatusCard) in div (created by AggregateStatusCard) in div (created by AggregateStatusCard) in AggregateStatusCard in Provider
The error is because key={notification} returns string of notification with the value of …
=> Fix non-unique keys error inside pf_aggregate_status_card

app/controllers/application_controller/explorer.rb
1. Navigate to summary screen of a cloud instance with a snapshot
2. Click on `Snapshots` in the summary screen to view instance's snapshots
3. Switch to `Images` accordion
4. See the following rails error:
```
FATAL -- : Error caught: [NoMethodError] undefined method `supports_snapshot_create?' for nil:NilClass
app/helpers/application_helper/button/vm_snapshot_add.rb:5:in `disabled?'
app/helpers/application_helper/button/basic.rb:54:in `calculate_properties'
app/helpers/application_helper/toolbar_builder.rb:141:in `apply_common_props'
app/helpers/application_helper/toolbar_builder.rb:73:in `toolbar_button'
app/helpers/application_helper/toolbar_builder.rb:148:in `build_normal_button'
app/helpers/application_helper/toolbar_builder.rb:182:in `build_button' …
```
=> Void @sb[:action] before accordion_switch()

app/assets/javascripts/controllers/ops/tenant_quota_form_controller.js, app/helpers/ops_helper/textual_summary.rb
Tenant Quotas are stored as bytes using datatype 'float'. This results in precision loss for values exceeding 931322 GB i.e. 99999723552768 bytes. The maximum precision of the 'float' datatype is 15 digits. When values exceeding 931322 GB are used as Tenant Quotas, the displayed result should be rounded (precision 1) to show the correct number of GB. At the edit page (Manage quotas for Tenant) the number of GB should be rounded too (precision 0).
N.B. The 'gigabyte_human' format is defined as having precision:1 at [manageiq/db/fixtures/miq_report_formats.yml](https://github.com/ManageIQ/manageiq/blob/master/db/fixtures/miq_report_formats.yml).
The 'Tenant Quota' page when having entered 931323 GB Storage Quota:
The 'Manage quotas for Tenant' page when having entered 931323 GB Storage …
=> Round GB Tenant Quota to compensate precision loss

app/views/report/_form_sort.html.haml
Issue: English string occurs in Overview -> Reports -> Reports -> Configuration -> Add a new report -> Summary 
Links 
* [Core Dependency PR - #20537 ](https://github.com/ManageIQ/manageiq/pull/20537)
1. Change language in settings
2. Click Overview -> Reports
3. Click Reports
4. Click Configuration Management -> Virtual Machines -> Account Groups - Linux
5. Click Configuration
6. Click Add a new report
7. Click Availiable Fields and select at one item
8. Click icon
9. Click Formatting
10. Click Summary
11. Select Descending at Sort Order
12. Select Yes at Show Sort Breaks
Original Issue
------------------
English string occured
Result
-----------------------
=> Added gettext calls to MiqReport::GROUPINGS for options select

app/views/miq_policy/_action_details.html.haml
this is rebased and squashed version of #7285  
This is to fix truncation issue for Action type dropdown button width, for longer text selected especially for translations in other languages, text is being truncated.
Click Control-> Explorer
Click Actions-> All Actions
Click Configuration
Click Add a new Action
Select one Action Type
**Expected behavior**
no truncation occurs
**What really happened**
truncation occurs
**Before:**
Text is truncated
**After:**
Button width increased  dynamically and text is not truncated anymore
=> Fixed width of Action type select component width to fix truncation

app/javascript/forms/input-with-dynamic-prefix.jsx, app/javascript/spec/forms/__snapshots__/input-with-dynamic-prefix.spec.js.snap
Fixes: [#9230](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/9230)
Before: 
After:
=> [JANSA] Translated "choose" string in URL selector in PXE server form

app/controllers/generic_object_definition_controller.rb
1. Go to Generic Objects screen
2. Create a new GO class
3. Click on the new class in the left accordion
4. Click on `Generic Objects` breadcrumb link
5. See the new breadcrumb
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1719889
This fix is only for jansa & ivanchuk branches, on master branch the problem has been fixed in 85f78065b78708fc00b0399a5796af4aa4fa64f2
=> [JANSA] Correctly set x_node for generic_object_definition_controller show_list()

app/helpers/configuration_profile_helper/textual_summary.rb
This [enhancement](https://github.com/ManageIQ/manageiq-ui-classic/issues/7313) displays Description and Target Platform for Configuration Profile. This is to make it easier for user to determine which Platform the Configuration Profile can be deployed to.
=> Add description/target platform to Config Profile

app/controllers/mixins/actions/vm_actions/ownership.rb, spec/controllers/mixins/actions/vm_actions/ownership_spec.rb
When `Set Ownership Screen` is opened then `@edit[:objects_ids]` is filled up with objects which are displayed in **Affected Items** section.
When buttons "Save" or "Cancel" are pressed , content of `@edit[:objects_ids]` persist in session and when we return to summary page of Service then `@edit[:objects_ids]` is populated from session and it causes that there is error in `get_view` method.
Source for `Affected Items` list in Set Ownership Screen is now based on [build_target_hash method](https://github.com/ManageIQ/manageiq-ui-classic/blob/1913facee1e86607d95885b609936384e4450c8b/app/controllers/mixins/actions/vm_actions/ownership.rb#L96).
Scenario
1. Go to `Services -> My Service`
2. Find service without VMs (with VMs is don't …
=> Fix issue during return from Set Ownership Screen to summary page of Service

app/helpers/ansible_playbook_helper/textual_summary.rb, app/helpers/ansible_repository_helper/textual_summary.rb
Issue: <CloudForms_GVT>English string occurs on both Repository and Playbooks summary page.  
Found on: Automation -> Ansible -> Repositories -> { Select Repository }
Found on: Automation -> Ansible -> Playbook -> { Select Repository }
Steps to reproduce
------------------------------
1. Click Automation-> Ansible-> Repositories
2. Click one Repository
3. Verify with GVT test areas
Original Issue
------------------------------
English string occurred in both Repositories and Playbooks summaries
Result
--------------------------------
"My Company" is customer data, which cannot be translated.
=> Added gettext calls for Provider Label in playbook and repository views

app/javascript/menu/side-nav-menu-link.jsx
There was no way to access the main menu sections without using the mouse. The problem was the missing `tabindex` property and the lack of the `onKeyDown` didn't allow further expansion of the menu. After this change you should be able to focus on each menu item by hitting <TAB> and expand the menu by hitting <ENTER>.
@kavyanekkalapu delivering this as promised
@himdel there's a minor linting issue in the file that I was not able to figure out, even before my changes
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7253
=> a11y: Make the main menu items accessible using the keyboard

config/webpack/production.js
We previously switched the manifest generator to only output the
packages that were affected, but it's still useful to know which modules
within those packages are actually used. This commit puts back the
modules manifest generator alongside the packages manifest generator.
@himdel Please review. cc @simaishi @bhadrim
=> Include modules manifest

app/javascript/components/async-credentials/async-credentials.jsx, app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap, app/javascript/spec/async-credentials/async-credentials.spec.js
When using a conditional field as a dependency for an `async-credentials` component, the list of registered fields to validate gets updated with a delay. The `FormSpy` listening to all the changes in the form will not catch such change in the schema as it happens during the render. As a solution I moved the `depsValid` variable to the state of the component and I'm updating its value with a delay by using `setTimeout`. The issue was introduced with the DDFv2 update, in the v1 version we used a recursive component for the validation instead of `FormSpy`.
You can reproduce this issue by trying to add an oVirt provider without SSL validation. By default there's a required textarea for the list of trusted CA certificates but after turning off the SSL validation the field disappears. However, …
=> Fix the validation of dependent fields in async credentials component

app/javascript/components/remove-generic-item-modal.jsx
in #7207 a `display_field` prop was added to allow for displaying description instead of name
in #6980 a `transformFn` feature was added with a default implementation that trims the item to id & name
that broke `display_field` because there is no `description` anymore,
merging the 2 features, now the default transform respects display_field
---
Before:
After:
=> RemoveGenericItemModal: fix display_field handling

config/webpack/production.js
@himdel Please review.  We had sorted it originally, but when we switched to generating the packages only it was irrelevant.  So when we added back the modules list it was unsorted.
=> Sort the webpack modules for consistent output

app/controllers/ops_controller/settings/label_tag_mapping.rb, spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb
Tag mappings are used by more than just container providers so this should be more generic
Needed for:
https://github.com/ManageIQ/manageiq/pull/20567
=> Rename ContainerLabelTagMapping to be more generic

app/controllers/vm_common.rb
Labels should be shown for Infra VMs not just Cloud VMs.
https://github.com/ManageIQ/manageiq-providers-vmware/pull/626 adds the collection code
https://github.com/ManageIQ/manageiq-providers-vmware/issues/539
=> Display labels for Infra VMs

app/javascript/forms/data-driven-form.jsx, app/javascript/spec/forms/__snapshots__/data-driven-form.spec.js.snap
The migrating guide to v2 on the DDF website has not been updated with the proper documentation for the button labels. Credit goes to @DavidResende0 for [finding the issue](https://github.com/ManageIQ/manageiq-ui-classic/pull/7324#discussion_r493865416) and @rvsia for explaining me how to set these properly.
**Before:**
**After:**
=> Display the buttons' labels on DDF forms properly

app/javascript/components/async-credentials/edit-password-field.jsx, app/javascript/components/async-credentials/password-field.jsx
@DavidResende0 found out that the `PasswordField` and the underlying `EditPasswordField` components were displaying the `helperText` under the form field instead of having a popover as in any other component.
For now we we don't have a reproducing example in our codebase, but we will [soon](https://github.com/ManageIQ/manageiq-ui-classic/pull/7324). Until then these changes are necessary to test this in the Compute -> Infra -> PXE (edit) form:
```diff
diff --git a/app/javascript/components/pxe-servers-form/pxe-server-form.schema.js b/app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
index 3f290a8485..7a1c33c436 100644
--- a/app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
+++ b/app/javascript/components/pxe-servers-form/pxe-server-form.schema.js
@@ …
```
=> Show the helperText on the password-field component properly

app/helpers/report_helper.rb, app/views/report/_form_consolidate.html.haml, app/views/report/_form_sort.html.haml, app/views/report/_widget_columns.html.haml
English string occurs in Overview - Reports - Reports - Configuration - Add a new report - Consolidation
1. Click Overview -> Reports
2. Click Reports
3. Click Configuration Management -> Virtual Machines -> Account Groups - Linux
4. Click Configuration
5. Click Add a new report
6. Click Available Fields and select at one item
7. Click ![image](https://media.github.ibm.com/user/30329/files/b1fd4b80-9f62-11ea-949b-092afacf868c) icon
8. Click Consolidation
9. Select the fields you just selected at column 1
translated string will occur
English string occurs
=> Fix translation for consolidation column dropdown

app/controllers/application_controller.rb, app/controllers/application_controller/miq_request_methods.rb, app/controllers/application_controller/user_script_file.rb, app/controllers/mixins/vm_show_mixin.rb, app/views/miq_request/_prov_field.html.haml, app/views/shared/views/_prov_dialog.html.haml, app/views/vm_cloud/explorer.html.haml
Adding fields supported by the IBM PVS but missing in the MIQ
New fields added to the IBM Power Virtual Servers provisioning form.
* pull-down fields: "pin_policy, system_type, storage_type"
* multiselect field: "cloud_volumes"
* read-only text field: "user_script_text" on two different UI paths (miq_prov and explorer)
* checkbox field: 'migratable' boolean value
* fileupload: "user_script" for two different UI paths (miq_prov and explorer)
* added "Customization" Tab, which contains the fileupload, file content text-box, and "IP v4" fields.
(the tab was already supported by MIQ)
See API field meanings: https://cloud.ibm.com/apidocs/power-cloud#pcloud-pvminstances-post
See related PR in the IBM Cloud repository: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/19
=> Added new provisioning fields for the "IBM Power Virtual Servers" Provider

app/javascript/components/async-credentials/async-credentials.jsx, app/javascript/components/pxe-servers-form/pxe-server-form.schema.js, app/javascript/spec/async-credentials/__snapshots__/async-credentials.spec.js.snap, app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
There was no way to set the `async-credentials` component to be optional, i.e. always demanding a validation, even if the underlying fields were never touched. The way we were checking this fact was also a little bit buggy and not very effective, so first I did some optimizations around it. Instead of saving the `initialValues` on the first render, I'm directly using the `dirtyFields` in the `FormSpy`. I also exposed an `isRequired` attribute on the component that allows us to set it valid in its initial state.
This change is just half of the solution, all the required `async-provider-credentials` components in the provider schemas should be updated with an `isRequired` attribute if they are not optional.
https://github.com/ManageIQ/manageiq-providers-amazon/pull/653 …
=> Allow the async-credentials component and its children to be not required

app/helpers/configuration_profile_helper/textual_summary.rb
This **enhancement** hides properties that do not contain a value in the **Configuration Profiles** detail page.
**Before:** 
**After:**
=> Hide empty properties for Configuration Profiles

app/helpers/configured_system_helper/textual_summary.rb
This is an enhancement required for https://github.com/ManageIQ/manageiq-providers-ibm_terraform/issues/28. We want to display the vendor for configured systems. This improves user experience and allows the user to determine which vendor/cloud provider the configured system is deployed to.
=> Display vendor for configured systems

app/views/shared/_tree.html.haml
This fix is to make sure the automate entrypoint selection dialog is scrollable if needed. This is jansa & ivanchuk only fix, the problem on current master has been resolved by reimplementing trees using react.
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1880991
=> [JANSA] Add scrollbar to automate entrypoint dialog

app/javascript/components/gtl-view.jsx, app/javascript/components/gtl/DataTable.jsx, app/javascript/components/gtl/StaticGTLView.jsx
Missed handling case where List view has an Order service button. Issue was introduced in REact list view conversion in https://github.com/ManageIQ/manageiq-ui-classic/pull/7188
=> Implemented missing `onItemButtonClick` method for Order Service button

app/views/shared/views/_prov_dialog.html.haml
- IBM Power Virtual Server related change
- in case of IBM PVS provisioning form the
following fields are shown: name, size, diskType, shareable
- types: text, text, text, checkbox (respectively)
Depends:
=> Customized 'volumes' tab for IBM PVS in '_prov_dialog.html.haml'

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js, app/controllers/cloud_volume_controller.rb, app/views/cloud_volume/_common_new_edit.html.haml
Add support for loading IBM Cloud Power Virtual Servers
'CloudVolumeTypes' within the Cloud Volume create forms.
This depends on the backend PR ManageIQ/manageiq-providers-ibm_cloud#53
=> Add IBM PowerVS to Cloud Volume create form

product/views/ConfigurationProfile.yaml
This **enhancement** adds a **Name** column to the Configuration Profile page.
=> Add name to Configuration Profile

app/javascript/components/catalog-form/catalog-form.schema.js, app/javascript/components/code-editor/index.js, app/javascript/components/orchestration-template/orchestration-template-form.schema.js, app/javascript/components/pxe-servers-form/pxe-server-form.schema.js, app/javascript/forms/mappers/componentMapper.jsx, app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap, app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
The `hr` component used to separate form parts has been replaced with the `sub-form` component. If the fields are too close to each other, we should probably update the styling, but IMO they are good as they are. The catalog, the orchestration template and the PXE forms were affected:
**Before:**
**After:**
The `note` component is completely replaceable with the `helperText` attribute on the right component, which was not implemented on the `code-editor` component. The only affected page here is the orchestration templates form.
**Before:**
**After:**
This allows me to remove the `hr` and `note` components from the DDF mapper.
=> Remove exotic DDF components from the componentMapper

app/controllers/ops_controller/settings/common.rb, app/controllers/ops_controller/settings/zones.rb, app/views/ops/_settings_evm_servers_tab.html.haml, app/views/ops/_settings_server_tab.html.haml, app/views/ops/_zone_form.html.haml, spec/controllers/ops_controller/settings/common_spec.rb, spec/controllers/ops_settings_spec.rb, spec/views/ops/_settings_evm_servers_tab.html.haml_spec.rb, spec/views/ops/_zone_form.html.haml_spec.rb
Just following https://github.com/ManageIQ/manageiq/pull/20623 and removing it from here. @Maria-Cordero-ibm if this gets in sooner than yours, it might cause a merge conflict. It should be easy to resolve because you're deleting the stuff I deleted too.
=> Get rid of the NTP servers from the Zone and Server screens

product/views/ManageIQ_Providers_ConfigurationManager.yaml
Fixes https://github.com/ManageIQ/manageiq-providers-ibm_terraform/issues/23 where the Configuration Provider is listed twice in the UI.
=> Fix for Configuration Provider appearing twice

app/controllers/configuration_profile_controller.rb, app/helpers/application_helper/button/configuration_profile_console.rb, app/helpers/application_helper/toolbar/configuration_profile_center.rb, app/helpers/application_helper/toolbar_chooser.rb, config/routes.rb
This **enhancement** adds Access to the IBM Terraform template console
=> Add console link to Configuration Profile

app/views/static/cloud_subnet/cloud-subnet-form.html.haml
In Network > Subnets > Add New Subnet form only show and require 'Cloud
Tenant Placement' field if tenants are defined. The field is already
hidden before selecting a Network Manager. This addition to the 'ng-if'
statement prevents it from appearing if the selected Network Manager has
no available tenants defined.
Form without any Network Manager selected. 'Cloud Tenant Placement' is not visible:
Form with `Openstack::NetworkManager` type Network Manager selected. 'Cloud Tenant Placement' is shown and required:
Form with `IbmCloud::PowerVirtualServers` type Network Manager selected, 'Clout Tenant Placement' is not visible and is not required to submit 'Add' action:
=> Add New Subnet without Cloud Tenant

app/controllers/catalog_controller.rb
This fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6394
Before:
After:
=> Fix breadcrumb and right cell text of order service

spec/helpers/application_helper/buttons/polymorphic_conditional_button_spec.rb
I used focus in order to solve rspec issue in https://github.com/ManageIQ/manageiq-ui-classic/pull/7343 and forgot to remove it.
=> Remove focus tag from polymorphic_conditional_button_spec

app/controllers/application_controller.rb, spec/requests/auth_spec.rb
check_privileges is skipped for logout,
but none of the other before actions are,
and get_global_session_data can still trigger handle_invalid_session,
which would remember logout as start_url,
leading to a (counterproductive) redirect to logout right after logging in.
This may have happened recently :point_up: [September 29, 2020 9:09 PM](https://gitter.im/ManageIQ/manageiq?at=5f73a287aaff36059b6575de), I'm not sure that was caused by this, but it seems possible.
=> /dashboard/logout: don't remember logout as start_url when session invalid

app/controllers/mixins/ems_common.rb, app/helpers/application_helper/page_layouts.rb, app/helpers/application_helper/toolbar/ems_block_storages_center.rb, app/views/ems_block_storage/new.html.haml, app/views/ems_block_storage/show_list.html.haml, app/views/ems_storage/show.html.haml, config/routes.rb
As part of the storage modifications (see #7282 for the entire modifications details. This PR is a partial split from #7282) we added a new functionality and now block storage manager can be added directly. This add-on allow us to add the new storage manager, AutoSDE directly.
Links
in order to successfully implement the new storage functionalities and storage manager type (autosde) we made additional changes in other relevant repositories and opened PR which may be linked to this PR:
- manageiq-schema: https://github.com/ManageIQ/manageiq-schema/pull/505 (all done!) 
- manageiq-provider-autosde: https://github.com/Autosde/manageiq-providers-autosde/
- manageiq-decorators: https://github.com/ManageIQ/manageiq-decorators/pull/33
- manageiq (core) - …
=> Implementing add new block storage manager functionality

app/presenters/menu/default_menu.rb
**Before:**
**After:**
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7394
=> Remove redundant 'Network' prefix from network menu items

app/controllers/application_controller.rb, app/controllers/ems_block_storage_controller.rb, app/controllers/ems_object_storage_controller.rb, app/controllers/ems_storage_controller.rb, app/controllers/mixins/storage_common_mixin.rb, app/helpers/application_helper/toolbar/ems_block_storages_center.rb, app/helpers/application_helper/toolbar/ems_storage_center.rb, app/helpers/ems_storage_helper.rb, app/views/ems_block_storage/edit.html.haml, app/views/ems_storage/_edit_storage.html.haml, app/views/ems_storage/edit.html.haml
As part of the storage modifications (see #7282 for the entire modifications details. This PR is a partial split from #7282) we added the ability to edit storage manager. storage manager can only be edited if it was created directly (see https://github.com/ManageIQ/manageiq-ui-classic/pull/7345 for the new add block storage manager functionality). Storage managers that were added indirectly (e.g. cinder storage manager created indirectly if we add openstack cloud manager) can  NOT be edited from the storage edit button.
Links
in order to successfully implement the new storage functionalities and storage manager type (autosde) we made additional changes in other relevant repositories and opened PR which may be linked to this PR:
- manageiq-schema: …
=> implement edit storage manager functionality

app/javascript/components/tree-view/field.jsx, app/javascript/components/tree-view/helpers.js, app/javascript/components/tree-view/hierarchical-tree-view.jsx, app/javascript/forms/mappers/componentMapper.jsx
```js
{
component: 'tree-view',
name: 'foo',
label: 'Foo',
initialValues: [...],
loadData: () => Promise,
lazyLoadData: node => Promise,
}
```
AFAIK we're not doing lazyload in trees that are inside forms (except automate entrypoint selection), but better safe than sorry I implemented the behavior somehow. If it's undesired we can either change or remove it.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/6841
=> Introducing the TreeView component for DDF without React

config/jest.setup.js
We have the `API` function exposed on `window` globally, but the tests can't deal with that. I hope I'm putting it to the right location...
FYI @Maria-Cordero-ibm
=> Expose the API global in the jest testing context

app/views/shared/views/_prov_dialog.html.haml
When using '%[]' for an array of symbols whitespace is used as a
delimiter, not commas.
Small bug that prevents the 'migratable' checkbox from showing up in provisioning forms. Looks like just a typo when moving to the %i[] notation - https://github.com/ManageIQ/manageiq-ui-classic/pull/7297#discussion_r490223813.
=> Fix provisioning dialog ':migratable' symbol ref

app/views/miq_request/_prov_field.html.haml, app/views/shared/views/_prov_dialog.html.haml
This is implemented to enable attaching a VM to a public network during
provisioning.
=> Add 'public_network' provisioning checkbox field

app/javascript/menu/first-level.jsx, app/javascript/menu/second-level.jsx
There was still a missing `propTypes` for `MenuItem` and no `defaultProps` so I added them. Updated the `href` and `type` attribute to be not required and also the `type` set to `default` as the default value. It was causing me type errors on the second level of `Settings`.
=> Fix propTypes for the MenuItem component

app/helpers/physical_chassis_helper/textual_summary.rb, app/helpers/physical_server_helper/textual_summary.rb, app/helpers/physical_storage_helper/textual_summary.rb, app/helpers/physical_switch_helper/textual_summary.rb
We introduced new storage provider, AutoSDE, which also uses miq physical storages controller. physical storages under autosde dont have all of the information (mostly the asset_detail fields) that currently avaliable under miq physical storage and that cause a crash once we entered into the physical storage summary page. It is allowed to have an empty field but a bug in the code prevented empty fields for asset_detail, and that was fixed in this PR.
links
-------
https://github.com/ManageIQ/manageiq-providers-autosde/pull/25
=> Enabling textual_summary to work with nil asset_detail

app/views/cloud_object_store_container/new.html.haml, app/views/cloud_volume/_common_new_edit.html.haml
Truncation occurs in Storage - Block Storage - Volumes - Add Cloud Volumes
1. Click Storage -> Block Storage -> Volumes
2. In "Cloud Volumes" page
3. Click "Configuration" button
4. Click "Add a new Cloud Volumes" item
5. Select any one in "Storage Manager" drop-down list
Same issue in Storage-->Object Storage-->Object Storage Containers-->Add new, so fixed in both pages.
Select should show full text
=> Fixed width of Storage Manager select component width to fix truncation

app/controllers/catalog_controller.rb, app/views/catalog/_form_basic_info.html.haml, app/views/catalog/_form_ovf_template_options.html.haml, app/views/catalog/_sandt_tree_show.html.haml
This is Ruby/AJAX form similar with some special parameters for OVF Template provisioning.
https://github.com/ManageIQ/manageiq/issues/19718
Depends on https://github.com/ManageIQ/manageiq/pull/20636
@lfu please review/test
//cc @gtanzillo
=> Added UI support to add/edit OVF Template type Catalog Item(s)

app/javascript/menu/main-menu.jsx, app/javascript/menu/menu-collapse.jsx
I added the right `role`, `aria` and `tabindex` values on this element. The highlighting around the element is only visible from one side, because the right side is white and the top-bottom are covered by other elements. I'm not sure how should we fix it, increasing the z-index didn't really help.
**Before:**
**After:**
=> a11y: Make the menu expand/collapse accessible via keyboard

app/javascript/http_api/api.js, app/javascript/http_api/http.js
The functions under the `API` object allowed any URL to be passed to them, analogously the `http` object also allows requests to our API endpoints. This doesn't help the understanding of the separation of the true API endpoints and the endpoints defined in our Rails controllers. As we are moving towards an API-driven single page application, the controller endpoints should slowly disappear and it is easier to track what component is firing what kind of requests if the correct objects are being used for the correct endpoints.
To enforce this as a rule, I created a regexp matching on the methods defined in both objects to allow URLs from only from the API or non-API worlds. So far I couldn't find any example of the wrong usage, so I guess if the tests pass, this change should not break …
=> Throw an error if the API or http objects are being interchanged

app/javascript/spec/http_api.spec.js
Cc @skateman 
URL filtering added in https://github.com/ManageIQ/manageiq-ui-classic/pull/7413,
adding specs .. it was the quickest way to make sure it worked :)
=> http_api: spec for API/http url filters

app/javascript/menu/main-menu.jsx, app/javascript/menu/menu-collapse.jsx
I set an `onKeyDown` event on both menu levels, if the ESC key is pressed, the second level of the menu gets collapsed. I also made the overlay focusable, so if the user goes through the menu, it gets collapsed before the user can enter the main content area.
With the current implementation there's one catch though: if the user expands the second level and starts moving on the menu items with the keyboard backwards (SHIFT+TAB), it can go around and can get to the main content area without collapsing. I have a few ideas about how this could be solved:
* detect if the focus left the browser's active area with `window.onblur` and collapse the menu (alt+tab would also collapse the menu)
* collapse the second level if the user gets back to the first (might make navigation less comfortable)
* …
=> a11y: Allow the user to exit the menu when unfocusing or ESC

app/javascript/components/vm-snapshot-form/vm-snapshot-form.schema.js
Missed this during the DDFv2 conversions :see_no_evil: fixing :pick:
=> Rename the TEXTAREA_FIELD to TEXTAREA in the VM snapshot form

app/controllers/configured_system_controller.rb, app/helpers/application_helper/button/configured_system_console.rb, app/helpers/application_helper/toolbar/configured_system_center.rb, config/routes.rb
This **enhancement** adds a button to Access **Configured System console** 
Corresponding RBAC PR - https://github.com/ManageIQ/manageiq/pull/20686
=> Add access for Configured System console

spec/controllers/mixins/ems_common_spec.rb, spec/presenters/tree_node/ext_management_system_spec.rb
following https://github.com/ManageIQ/manageiq-ui-classic/pull/7354, I added tests for the ability to edit supported block storage manager (storage manager can only be edited if it was created directly)
links
--------
https://github.com/ManageIQ/manageiq-ui-classic/pull/7354
=> Adding RSpecs for edit block storage manager

app/javascript/.eslintrc.json
Cc @skateman 
Before..
```
/home/himdel/manageiq-ui-classic/app/javascript/components/select/index.jsx
6:29  error  Unable to resolve path to module '@@ddf'                         import/no-unresolved
```
now, no error, `@@ddf` is assumed to exist.
=> eslintrc: import/no-unresolved: ignore @@ddf alias

app/views/miq_request/_request_dialog_details.html.haml
1. Create a service dialog, add a Tag control element to it
2. Make sure the selected tag in the above tag control element allows multiple choices
3. Add the above created service dialog to a catalog item (a generic catalog item for example)
4. Order the above created catalog item and select at least two tags in the presented dialog
5. Check the order request details page, see if it contains info about all selected tags
Before
After
https://bugzilla.redhat.com/show_bug.cgi?id=1886887
=> Correctly render multi-tags in request details dialog

app/controllers/mixins/ems_common.rb, app/controllers/physical_storage_controller.rb, app/helpers/application_helper.rb, app/helpers/application_helper/listnav.rb, app/helpers/application_helper/page_layouts.rb, app/helpers/application_helper/toolbar/physical_storages_center.rb, app/helpers/ems_storage_helper/textual_summary.rb, app/javascript/components/physical-storage-form/index.jsx, app/javascript/components/physical-storage-form/physical-storage-form.schema.js, app/javascript/packs/component-definitions-common.js, app/presenters/menu/default_menu.rb, app/views/physical_storage/new.html.haml, config/routes.rb, spec/presenters/menu/default_menu_spec.rb
As part of the storage modifications (see ManageIQ/manageiq-ui-classic#7282 for the entire modifications details.) , we added the ability of directly adding physical storage for supporting storage managers.
=> Implement support for adding physical storages

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js, app/controllers/cloud_volume_controller.rb, app/views/cloud_volume/_common_new_edit.html.haml
As part of the storage modifications (see https://github.com/ManageIQ/manageiq-ui-classic/pull/7282 for the entire modifications details. This PR is a partial split from https://github.com/ManageIQ/manageiq-ui-classic/pull/7282) we modified the new cloud-volume form field to allow selection of storage-resources for relevant cloud volumes. This add-on allow us to add cloud volumes that are managed by the new AutoSDE storage manager.
for example (see image below) if we add cloud volume that managed by autosde storage manager we will get an additional field to fill, storage service (which is populated by storage-resources (pools) retrieved from the autosde manager)
Links
in order to successfully implement the new storage functionalities and storage manager type (autosde) we …
=> Enabling storage-service selection when creating cloud-volume

app/controllers/ops_controller/settings/label_tag_mapping.rb, app/views/ops/_label_tag_mapping_form.html.haml, app/views/ops/_settings_label_tag_mapping_tab.html.haml, app/views/ops/label_tag_mapping/_tag_category.html.haml, spec/controllers/ops_controller/settings/label_tag_mapping_spec.rb, spec/views/ops/_label_tag_mapping_form.html.haml_spec.rb
This PR along with the [core PR](https://github.com/ManageIQ/manageiq/pull/20289) enables the following new functions:
- Allows mapping a label to existing managed tags categories
- Allows mapping labels of all provider types  and resource types to managed tag categories
- As a side effect of the above, it allows referencing mapped managed tag categories and entries in policies, rate assignments, reports, expressions, filters, etc.
The representation of this concept is presented externally in the UI and the supporting code as **All Entities**. Internally, `All Entities` is implemented as a tag category without the `<provider-type>:<resource-type>:` prefix, which is what effectively opens mapping up to regular managed tag categories.
Opening up label mapping to managed tag categories …
=> Allow all providers in tag mapping screen

app/views/report/_form_formatting.html.haml
Found in Overview->Reports->Add a new Report->Formatting
Fixes: [#8665](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8665)
Preview:
=> Marked Strings For Translation in Reports -> Formatting

app/assets/javascripts/controllers/ems_storage_dashboard/heatmap_controller.js, app/controllers/ems_storage_controller.rb, app/controllers/ems_storage_dashboard_controller.rb, app/controllers/mixins/dashboard_view_mixin.rb, app/controllers/mixins/ems_common.rb, app/helpers/application_helper/toolbar/ems_storage_center.rb, app/helpers/ems_storage_helper/textual_summary.rb, app/services/ems_storage_dashboard_service.rb, app/views/ems_storage/_heatmap.html.haml, app/views/ems_storage/_show_block_storage_dashboard.html.haml, app/views/ems_storage/_show_object_storage_dashboard.html.haml, app/views/ems_storage/show_dashboard.html.haml, config/routes.rb, spec/helpers/ems_storage_helper/textual_summary_spec.rb, spec/shared/controllers/shared_examples_for_ems_storage_controller.rb
As part of the storage modifications (see https://github.com/ManageIQ/manageiq-ui-classic/pull/7282 for the entire modifications details. This PR is a partial split from PR-7282) we added dashboard for storage managers. 
The block storage dashboard also contains a new heatmap widget that shows resources/pools capacity
- New block storage manager dashboard
- New Objcet storage mananager dashboard
=> Implementing Dashboard for storage managers

app/controllers/storage_controller.rb
1. Infrastructure > Datastores > Select a datastore > in the summary screen, click on VMs
2. In the rendered list, check a VM
3. Launch Tagging screen
4. Hit `Cancel` button
Before, the `Cancel` or even `Save` button would take you back to the datastore summary screen:
With this fix, the `Cancel` button would take you back to the list of VMs running on that datastore:
https://bugzilla.redhat.com/show_bug.cgi?id=1741115
=> Fix Save & Cancel launched from StorageController (Datastores)

app/javascript/menu/first-level.jsx, app/javascript/menu/group-switcher.jsx, app/javascript/menu/main-menu.jsx, app/javascript/menu/menu-collapse.jsx, app/javascript/menu/search.jsx, app/javascript/menu/side-nav-menu-link.jsx, app/javascript/menu/username.jsx, app/stylesheet/menu.scss
In this PR, Fixed few issues.
- Added icon tooltip for menu list when menu is collapsed
- Added tooltip for search and group name when menu is collapsed
- Added tabindex for search so that search can be focused.
- Fixed bug about not showing userinfo and grouinfo (those two were still in collapsed state)when user tab into leftnav.
- Fixed showing user name info when user tab into side nav.
**Before:**
No tooltips for icons.
**After:**
fyi @skateman @himdel 
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7358
=> Fix leftnav icon tooltip and showing user info in side leftnav nav.

app/helpers/application_helper/form_tags.rb
Before:
After:
I tested it with all currently supported locales as well as the locales that are to be added in the near future (de, en, es, fr, it, ja, ko, pt_BR, zh_CN, zh_TW).
=> Allow i18n in datetimepicker component

app/javascript/forms/data-driven-form.jsx, app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js
By default DDF submits any data with the form that is passed into its `initialValues`. This required us to filter out some of these values when seeding a form with data coming from the API either during the request handling or inside the `onSubmit`. It's not a big deal if you just have a couple of fields, but it can be painful when there are more of them or the schema is dynamic.
To ease this, I am proposing a global solution by filtering these values in a wrapper around the passed `onSubmit` function, so it just gets the right values and it doesn't require to change anything in the existing forms. After this change only those values will be passed to the `onSubmit` function that have a matching field in the form schema. I guess this is the standard HTML behavior, I just couldn't convince …
=> DDF: submit only fields that are registered in the schema

app/javascript/spec/select/select.spec.js
Instead of calling the internal `onChange` by tapping into the `Select` component, I am leveraging [the formApi exposed on a dummy component](https://github.com/data-driven-forms/react-forms/issues/852#issuecomment-714385810).
=> Use formApi to change dropdown value in SelectWithOnChange spec

app/javascript/components/provider-form/editing-context.js, app/javascript/components/provider-form/index.jsx, app/javascript/components/provider-form/protocol-selector.jsx, app/javascript/components/provider-form/provider-credentials.jsx, app/javascript/components/provider-form/validate-provider-credentials.jsx
Fixed the cyclic dependency of `EditingContext` in `ProviderForm` by extracting it into a separate file.
@miq-bot add_label cleanup, react
=> Eliminating cyclic dependency for EditingContext

app/helpers/ansible_credential_helper/textual_summary.rb, app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap, spec/helpers/ansible_credential_helper/textual_summary_spec.rb
The textual summary generation for embedded ansible credential summary screen depends on the `API_FIELDS` constant declared in core. The fields in the constant have been converted to a [DDF schema](https://github.com/ManageIQ/manageiq/pull/20568) as we're [consuming](https://github.com/ManageIQ/manageiq-ui-classic/pull/7324) them using DDF. However, the textual summary generation has not been adjusted, which makes the summary screen generation fail.
I also noticed that the snapshots introduced in the [UI part](https://github.com/ManageIQ/manageiq-ui-classic/pull/7324) were not adjusted to the latest version of DDF, so I am adjusting them too to make travis happy.
=> Adjusted ansible credential textual summary generation

app/javascript/components/provider-form/protocol-selector.jsx, app/javascript/components/select/index.jsx, app/javascript/spec/provider-form/__snapshots__/protocol-selector.spec.js.snap, app/javascript/spec/provider-form/protocol-selector.spec.js
The `ProtocolSelector` component was not leveraging the `onChange` prop of the `SelectWithOnChange`.
This PR adds tests to the `ProtocolSelector` component and refactors it to use `SelectWithOnChange` by setting the `onChange` prop.
The tests use https://github.com/data-driven-forms/react-forms/issues/852#issuecomment-714385810.
@miq-bot add_label refactoring, react
=> Updated ProtocolSelector component to use SelectWithOnChange

app/javascript/menu/item-type.js
Links without a `href` attribute are not focusable. The only one in our menu is the `Settings -> About`, so fixing :wrench:
=> Make the Settings/About focusable by setting its href to #

app/controllers/miq_ae_customization_controller.rb
Found in Automation -> Automate -> Customization -> Buttons -> Add a new Button
Fixes: [#10506](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10506)
Re-writes `miq_ae_customization_controller.rb` so that title strings are translated as a single string as opposed to two strings concatenated together, fixing possible translation issues.
Preview:
=> Edited Controller to Ensure Strings are Translated Correctly

product/views/ConfiguredSystem.yaml
This enhancement adds a Provider column to the Configured Systems page.
=> Add Provider column for Configured Systems

app/javascript/menu/first-level.jsx, app/javascript/menu/main-menu.jsx, app/javascript/menu/second-level.jsx, app/javascript/menu/side-nav-menu-link.jsx
I am forwarding/passing a `ref` to the first element in the secondary menu and calling its focus after something in the first level has been activated. It was necessary to add some `forwardRef` magic around our components, while the ones provided by carbon already had it implemented. 
I wanted to implement the unfocusing symmetrically on the last element in the second level, but there's no `onBlur` prop exposed on the `SideNavMenu` and `SideNavMenuItem` components. So I had to create a focusable `span` element after the second level menu that hides the second level when focused. I know that this is an ugly hack, but I had no better idea :confused:  
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7358
=> Implemented autofocus/blur to access/exit the second level menu

app/helpers/configuration_profile_helper/textual_summary.rb, app/helpers/configured_system_helper/textual_summary.rb, app/helpers/ems_configuration_helper/textual_summary.rb
Icons are missing Configuration profiles, Configured systems, Configuration --> Provider table summaries, Missed icons causing text alignment left.
Before:
After:
=> Fix missed icons in configuration systems table summary

app/stylesheet/carbon.scss, app/stylesheet/menu-colors.scss, app/stylesheet/menu.scss
We need the `g10` theme to have our forms look as they should, but for the menu we need to keep the g90 theme. The searchbar in the menu now became brighter and the focus color became blue, not sure if these can or should be fixed though.
**EDIT: fixed, it should be identical now**
**Before:**
**After:**
=> Set the global Carbon theme to g10 and set g90 for the menu only

app/controllers/ops_controller/settings/schedules.rb
**This is first part of issue** https://github.com/ManageIQ/manageiq/issues/20768
------
PR updates method `build_search_filter_from_params` to be more transferable to core repo.
This supports effort in order to implement [API Endpoint for Schedules](https://github.com/ManageIQ/manageiq-api/issues/893)
@miq-bot refactoring
https://github.com/ManageIQ/manageiq-api/issues/893
=> Extract params from build_search_filter_from_params in schedules

app/helpers/ems_storage_helper/textual_summary.rb
In block storage manager summary page storage systems need to be replaced with physical storages. The reason for the wrong label is duplicate function (textual_physical_storages) inside ems_storage textual_summary page.  
before fix:
after fix:
=> Fix physical storage typo in storage manager summary page

app/controllers/vm_common.rb, app/javascript/components/vm-server-relationship-form/index.jsx, app/javascript/components/vm-server-relationship-form/vm-server-relationship-form.schema.js, app/javascript/spec/vm-server-relationship-form/vm-server-relationship-form.spec.js, app/views/vm_common/_evm_relationship.html.haml, config/routes.rb, spec/controllers/vm_common_spec.rb, spec/routing/shared_examples/vm_common_examples.rb
The form was still using non-API endpoints to fetch data and its redirects after submit/cancel were pointing to dedicated routes. I converted the form into a function component and adjusted it to work with only API endpoints. You can access this form under a VM's summary screen:
=> Make the vm server relationship form fully API driven

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
This new method can build the URL of an API endpoint based on an ActiveRecord model class. It will be useful when determining the target URL for the retirement form submission.
=> Created a helper method to build API URLs from AR classes

app/javascript/components/ansible-credentials-form/index.jsx, app/javascript/components/catalog-form/catalog-form.jsx, app/javascript/components/cloud-network-form/cloud-network-form.jsx, app/javascript/components/cloud-tenant-form/cloud-tenant-form.jsx, app/javascript/components/copy-dashboard-form/copy-dashboard-form.jsx, app/javascript/components/edit-service-form/index.jsx, app/javascript/components/ops-tenant-form/ops-tenant-form.jsx, app/javascript/components/orchestration-template/orcherstration-template-form.js, app/javascript/components/provider-form/index.jsx, app/javascript/components/region-form/index.jsx, app/javascript/components/set-ownership-form/index.jsx, app/javascript/components/vm-server-relationship-form/index.jsx, app/javascript/forms/data-driven-form.jsx, app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap, app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap, app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap, app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap, app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js
The same exact `onReset` is being specified for each DDF instance and they're not doing anything without the `canReset` prop being set to `true`. So it is safe to move all of them to a common location...
=> Move the common onReset attribute from all DDF forms to the parent

app/views/report/_form_columns.html.haml
Issue: Truncation occurs in Overview -> Reports -> Reports -> Configuration -> Add a new report
1. Click Overview -> Reports
2. Click Reports
3. Click Configuration Management -> Virtual Machines -> Account Groups - Linux
4. Click Configuration
5. Click Add a new report
Original Issue
------------------
Truncation occurs
Result
-----------------------
No truncation occurs
=> Added form-control class to fix truncation

spec/controllers/catalog_controller_spec.rb
Similar to what was done in ManageIQ/manageiq@79c28269 which was that instead of trying to assign the provider prior to making the EMS in the factories, default a provider object type as part of the `ext_management_system` child definition, and reference it in the `let(:provider)`.
This is not a problem in Rails 5.2, but does lead to the following error in Rails 6.0
```
1) CatalogController tests that needs all rbac features access #fetch_playbook_details returns playbook service template details for provision & retirement tabs for summary screen
Failure/Error: FactoryBot.create(:automation_manager_ansible_tower, :inventory_root_groups => [inventory_root_group], :provider => FactoryBot.create(:provider_embedded_ansible))
ActiveRecord::HasManyThroughCantAssociateThroughHasOneOrManyReflectio …
```
=> [rails6][catalog_controller_spec.rb] Fix ems let

app/stylesheet/menu.scss
Secondary menu does not display the scrollbar when there are too many items.
This fixes it by ensuring the height is 100% viewport height.
Before:
After:
(https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/15073)
=> menu - ensure secondary menu has a 100% viewport heigh, so that the scrollbar appears when needed

app/controllers/configuration_controller.rb
1. Go to My Settings, switch the locale to some particular language, for example French
2. Save new settings, the page will re-render in French
3. Again in the My Settings screen (now rendered in French), set the locale to global default
4. Save new settings.
Now the page should re-render in whatever locale corresponds to global default, but it always sets to German. It's because we're actually doing:
```ruby
FastGettext.locale = 'default'
```
which is nonsensical and `FastGettext` falls back to first registered locale here (in this case German). We need to use `set_gettext_locale()` routine from `ApplicationController`, which is able to correctly resolve locale to use even in corner-case situations.
=> Correctly switch locale in My Setting

app/views/layouts/_tabs.html.haml
In https://github.com/ManageIQ/manageiq-ui-classic/pull/7035 we applied gettext to `@title`, though this is not correct, becase the content of the variable should already be translated. If it is not, the problem lies elsewhere, most likely `locale/en.yml` needs a proper entry for given table or model.
=> Don't apply gettext to title instance variable

app/controllers/ops_controller/ops_rbac.rb, app/javascript/components/ops-tenant-form/ops-tenant-form.jsx, app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js, config/routes.rb, spec/controllers/ops_controller/ops_rbac_spec.rb
The cache invalidation should be done implicitly when saving a `Tenant` record...
Depends on ~~https://github.com/ManageIQ/manageiq/pull/20708~~ https://github.com/ManageIQ/manageiq/pull/20772
=> Prefer MiqProductFeature cache invalidation explicitly via backend

app/helpers/application_helper/toolbar/physical_storage_center.rb, app/helpers/application_helper/toolbar/physical_storages_center.rb, app/javascript/toolbar-actions/custom-action.js
Adding functionality for deleting supported physical storages via rest-API
links
-----------
the following are related PRs
https://github.com/ManageIQ/manageiq/pull/20713
https://github.com/ManageIQ/manageiq-api/pull/932
https://github.com/ManageIQ/manageiq-providers-autosde/pull/38
=> Implementing remove physical storage

app/controllers/catalog_controller.rb, app/helpers/application_helper/toolbar_chooser.rb, app/presenters/tree_builder_orchestration_templates.rb, product/views/ManageIQ_Providers_Vmware_InfraManager_OrchestrationTemplate.yaml
before
after
This PR addresses issue mentioned in https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/15279
@lfu please test/verify
=> UI changes to add 'OVF Templates' node in Orchestration templates tree

spec/controllers/cloud_tenant_controller_spec.rb
Missed this when I made the form API-driven I guess
=> Drop the spec for the dead CloudTenant#update route

spec/controllers/catalog_controller_spec.rb
This is a follow up to 02e4b85 (aka: https://github.com/ManageIQ/manageiq-ui-classic/pull/7500 ) as the solution provided there, while works for this use case, ended up causing problems in `ManageIQ/manageiq-content`:
https://github.com/ManageIQ/manageiq/pull/20787#issuecomment-726357421
Instead, we use the `:provider_embedded_ansible` factory, and reference the `.automation_manager` from that.  In addition, since a update to the `:inventory_root_groups` was needed, we also modify the record in a `before` statement as well.
This ends up not being as clean as the previous implementation, but makes sure we are using the `EmbeddedAnsible` provider in the form that it would be called when used in the application.
Links
-----
* https://github.com/ManageIQ/manageiq-ui-classic/pull/7500
* …
=> [catalog_controller_spec.rb] Fix ems let... again

app/views/report/_export_custom_reports.html.haml
Issue: 'Available Custom Reports' string should be in single line in KOR
1. Click Overview -> Reports
2. Click Import / Export -> Custom Reports
Original Issue
------------------
'Available Custom Reports' string shows in 2 lines in KOR
Result
-----------------------
'Available Custom Reports' string displayes in single line in KOR
=> Modified custom report layout to fit full string in Korean

app/controllers/mixins/ems_common.rb, app/helpers/application_helper/toolbar/physical_storages_center.rb, app/helpers/application_helper/toolbar_chooser.rb, config/routes.rb
The toolbar is not visible if we enter physical storages page from within block storage dashboard.
before fix:
after fix:
=> Fix physical storage toolbar to work also from block storage dashboard

product/views/ConfiguredSystem.yaml
This PR addresses an issue with the Provider name formatting. When the Provider name contains '.', it was only displaying the last part of the string.
Provider Name: 'Andy.Bob.Cat Configuration Manager' shows up as 'Cat Configuration Manager'
=> Fix formatting for Provider name

app/views/layouts/_tag_edit_items.html.haml
Found in Policy -> Edit Tags (e.g. Services->Catalogs->Orchestration Templates -> Policy ...)
Edits `_tag_edit_items.html.haml` so that strings are not translated separately before being concatenated together, ensuring that the translated string is grammatically correct.
Note: New translations would need to be made for each of these strings.
Preview:
=> Rewrote HAML File to Ensure Strings are Translated Correctly

app/assets/stylesheets/patternfly_overrides.scss
this is for https://github.com/ManageIQ/react-ui-components/pull/184, in this pr removing hover color for clickable rows.
Before:
After:
links are in different color and accessible with keyboard.
@miq-bot add_reviewer @skateman , @h-kataria
=> Fix css for links in table summary page

app/controllers/catalog_controller.rb, app/views/catalog/_form_ovf_template_options.html.haml, app/views/catalog/_sandt_tree_show.html.haml
Added Storage Profiles, Storage, Disk Format, Vlan fields to existing form
https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/15722
Depends on https://github.com/ManageIQ/manageiq-providers-vmware/pull/670 & https://github.com/ManageIQ/manageiq-providers-vmware/pull/671
=> Additional fields added to OVF Template catalog item form

app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap, app/javascript/spec/ansible-credentials-form/ansible-credentials-form.spec.js, app/javascript/spec/automate-import-export-form/import-datastore-via-git.spec.js, app/javascript/spec/copy-dashboard-form/copy-dashboard-form.spec.js, app/javascript/spec/orchestration-template/orchestration-template-form.spec.js
Some of our tests are producing warning because of how we (don't) use the asynchronous handling for components. I am trying to figure out all of them, with more or less success. Here are a few changes that reduce the number of warnings printed into the test output...
=> Eliminate some of the async warnings from our jest tests

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js, app/views/cloud_volume/_common_new_edit.html.haml
If we try to modify cloud volume managed by autosde storage manager we get an exception. 
This PR enables size and name modifications for volumes managed under autosde.
links
--------
https://github.com/ManageIQ/manageiq-providers-autosde/pull/47
=> Fix autosde cloud volume editing

app/helpers/application_helper/toolbar/cloud_volume_snapshot_center.rb
Wrong icon for the delete action, fixing :wrench: 
**Before:**
**After:**
=> Replace the edit icon with a delete on the CV snapshot delete button

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
In this PR, fixed Storage manager dropdown default placeholder text translation.
Before:
After:
=> Fix translation of storage manager select default text

app/controllers/ops_controller/diagnostics.rb, app/views/ops/_diagnostics_database_tab.html.haml, config/routes.rb, spec/routing/ops_routing_spec.rb
There's an option for running the PG vacuum by pressing a button under OPS/Diagnostics/Region/Database which I'm deleting according to https://github.com/ManageIQ/manageiq-ui-classic/issues/6878#issuecomment-739965221
**Before:**
**After:**
=> Drop the DB garbage collection button/handler from the UI

app/controllers/mixins/actions/vm_actions/reconfigure.rb
An error occurred when trying to reconfigure a VM: 'comparison of String with nil failed'. This was caused by the 'sort_by(&:filename)' of the disks while one of the disks has no filename: a cdrom device without a cd mounted. This issue can be solved by replacing 'sort_by(&:filename)' with 'order(:filename)'.
Rails console output 
> Vm.find_by(name: 'NCTVC-NLHAA1-002').hardware.disks.first
=> #<Disk id: 100183, device_name: "Hard disk 1", device_type: "disk", location: "0:0", filename: "[PV-SP-HA12] NCTVC-NLHAA1-002/NCTVC-...", hardware_id: 21389, mode: "persistent", controller_type: "scsi", size: 10842275840, free_space: nil, size_on_disk: nil, present: true, start_connected: true, auto_detect: nil, created_on: "2020-12-04 09:35:50", updated_on: …
=> Replace 'sort_by' with 'order' to prevent error

app/controllers/mixins/actions/vm_actions/retire.rb
Missed from https://github.com/ManageIQ/manageiq-ui-classic/pull/7518 the `@edit` is no longer available, so setting its value causes errors :scissors: :fire:
=> Clean up session variable from the orchestration stack retirement

app/controllers/application_controller.rb, app/javascript/components/gtl-view.jsx
These issues were introduced with react conversion of list views, 3 issues were fixed
- Infinite spinner when clicking on a saved reports item from the right side in Reports accordion on Saved Reports tab. Call to expand tree was not being called.
- Incorrect tree node id is fixed when clicking on an item on the right side of Saved Reports accordion, this was loading the correct contents but not selecting an item in the tree.
- Tree on the left was not getting expanded to show/select node as selected in tree when selecting a Widget from the list on the right side in Dashboard Widgets accordion.
before
after
@gtanzillo this should fix the issue you reported with Saved report selection from Reports accordion. Please test.
=> Fixed tree selection issues with screens in Reports explorer

app/views/chargeback_rate/_cb_rate_show.html.haml
Found in Overview->Chargeback->Rates
Related to: ManageIQ/manageiq#20780
Fixes: [#10150](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10150)
Preview:
=> Marked Strings for Translation in Chargeback -> Rates

app/javascript/components/dashboard_toolbar.jsx, app/javascript/components/topology_toolbar.jsx, app/javascript/spec/toolbar/__snapshots__/dashboard_toolbar.spec.jsx.snap, app/javascript/spec/toolbar/__snapshots__/topology_toolbar.spec.jsx.snap, app/stylesheet/toolbar.scss
This PR fixes dashboard toolbar A11y, moving PF component to carbon, fixing scroll issue for long list of items in dropdown.
Before:
component is using patternfly components, A11y is not working, when we scroll with keyboard, screen is broken like second picture.
After:
@miq-bot add_reviewer @himdel , @skateman
=> Change dashboard toolbar to carbon and fix A11y

app/controllers/application_controller.rb, app/controllers/vm_common.rb
this change broke the list of vms loaded under folders
(broken in https://github.com/ManageIQ/manageiq-ui-classic/pull/7136 and https://github.com/ManageIQ/manageiq/pull/20149 originally)
thanks himdel
incoming core pr to address the needed core alias:
requires https://github.com/ManageIQ/manageiq/pull/20903
=> revert rename of all_vms_and_templates 

app/controllers/miq_policy_controller.rb
Found in Control -> Policies
Rewrites `miq_policy_controller.rb` so that titles are translated as a single string as opposed to separate strings concatenated together ensuring translations remain grammatically correct.
Preview:
=> Rewrote Policy Controller to Ensure Strings are Translated Correctly

spec/config/routes.pending.yml
Some of the routes after kasparov have been removed, so the list of pending routes should be adjusted accordingly.
@Fryguy as the pending tests are expected to fail, RSpec actually makes the CI red if they don't. I think this is a more than welcome side effect that will signalize us routes that have detectable RBAC enforcement but they are on the false positives list.
=> [KASPAROV] Adjusted RBAC enforcement checks for Kasparov

app/presenters/menu/default_menu.rb
This seems like introduces rubocop errors, but it really just fixes rubocop for the whole project. Without this it would crash and won't even check other files:
```
app/presenters/menu/default_menu.rb: Metrics/LineLength has the wrong namespace - should be Layout
/tmp/d20210111-6-1qai503/config/routes.rb: Warning: no department given for MultilineOperationIndentation. Run `rubocop -a --only Migration/DepartmentName` to fix.
```
=> Remove the disablement of the Metrics/LineLength cop from the menu

config/routes.rb
Fixes: 
```
/tmp/d20210112-7-1dv0cl0/config/routes.rb: Warning: no department given for MultilineOperationIndentation. Run `rubocop -a --only Migration/DepartmentName` to fix.
```
=> Added some missing departments into the rubocop overrides

app/presenters/tree_builder_report_dashboards.rb
Couple changes to fix ordering this list:
There are also other changes which lead to simplification of method `x_get_tree_g_kids`:
1. Use `MiqWidgetSet#ordered_widget_sets`.
2. Remove useless `copy_array`
3. **Fix: Sort MiqWidgetSets according to MiqGroup#dashboard_order**
@miq-bot add_label refactoring, bug
=> Sort MiqWidgetSets according to MiqGroup#dashboard_order in tree

spec/routes_spec.rb
As @Fryguy requested, I'm making the error messages a little bit more descriptive...
=> Make the RBAC spec's error and false positive messages meaningful

spec/shared/controllers/shared_storage_manager_context.rb
The SwiftManager is now subclassed under the ManageIQ::Providers::Openstack::StorageManager class, this exact class name check was causing swift managers to be assigned to the `@cinder_manager` ivar
Fixes https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/471734344#L2753-L2766
=> Fix the SwiftManager subclass type check in shared_storage_manager_context

spec/controllers/application_controller/compare_spec.rb, spec/controllers/dashboard_controller_spec.rb, spec/controllers/report_controller_spec.rb, spec/presenters/tree_builder_report_saved_reports_spec.rb
So this was a bit of a doosey, and not at all made longer by the fact that `userid` definitely thought we had a race condition with the _**`id`**_ column... and not the **"user name"** column...
_... he says sarcastically..._
Detailed Explaination
---------------------
When used in conjunction with the :user factory, if this is the first spec to be run that creates a user, or the sequence for FactoryBot is somehow reset (unlikely), this can cause a error with the `userid` field since they are case sensitive[[2](https://github.com/NickLaMuro/manageiq/blob/769dd2d0c96b8b46bed73a22abf1241eefc2f726/app/models/user.rb#L45)].  Meaning the following:
- "User1"
- "user1"
Are considered the same id.  The format for `FactoryBot.create(:user)` (defined in ManageIQ/manageiq) is …
=> [spec] Fix create_user_with_group errors

app/controllers/application_controller/filter.rb, app/controllers/application_controller/filter/expression.rb, spec/controllers/application_controller/filter/expression_spec.rb
when editing a policy condition we can hit this: 
```
"There is an error in the selected expression element, perhaps it was imported or edited manually.
This element should be removed and recreated or you can report the error to your CFME administrator.
Error details: undefined method `include?' for nil:NilClass"
```
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1914944
this was reported on five 11
@yrudman please review
by commit: 
1) switch the order of the first/to_s call to get this to run at a minimum
2) two tests showing the two current failures when the datetime formatting takes a nil 
3) updated tests and added presence checks
=> fix error in policy condition edit: no include? for nil

app/javascript/components/gtl-view.jsx
unSelectAll tried to dispatch an event, but it's being called from a reducer,
so doing the reduction directly
and making sure `state.rows` is never set to `false` when unselecting
---
This should fix an issue found in https://github.com/ManageIQ/manageiq-ui-classic/pull/7567#issuecomment-762091985 ,
`ReferenceError: dispatch is not defined` (in `unSelectAll`, `gtlReducer`)
=> gtl unSelectAll - fix missing dispatch, call reduceSelectedItem directly

app/helpers/ems_storage_helper/textual_summary.rb, app/services/ems_storage_dashboard_service.rb, spec/helpers/ems_storage_helper/textual_summary_spec.rb
Host Initiators (AKA physical storage hosts) are virtual entities that only exists as a set of definitions within the `PhysicalStorage' and hold the information about consumers/hosts that use (defined) the physical storage.
This PR includes the work for adding host initiators to block storage dashboard and summary page
Host-initiators example data
---------
Below are diagrams that shows how we'd represent rather standard scenario. 
All items in white are already part of miq:
We have a single IRL storage-system Called SVC Storage 1.
It has 2 storage pools: Pool1 and Pool2.
Pool1 has two volumes: Volume1 and Volume2.
All items in blue are changes done in this PR:
The Physical Storage has a single host-initiator defined in it. It has been defined with two addresses: iqn-addr-1, and …
=> Adding host_initiators for block-storage-dashboard

spec/controllers/dashboard_controller_spec.rb, spec/controllers/miq_report_controller/dashboards_spec.rb, spec/controllers/miq_report_controller/trees_spec.rb, spec/controllers/report_controller_spec.rb
Continuation of https://github.com/ManageIQ/manageiq-ui-classic/pull/7593,
where all changes from https://github.com/ManageIQ/manageiq-ui-classic/pull/7593 were added and
in addition other fixes added to fix specs.
cc @kbrock 
Needs core PR: https://github.com/ManageIQ/manageiq/pull/20972
-  https://github.com/ManageIQ/manageiq-ui-classic/pull/7593 can be replaced with this PR
=> Fix specs related to widget set factories

app/controllers/cloud_object_store_container_controller.rb
`Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1
=> rename parent to module_parent

app/controllers/application_controller.rb
Fixes the following deprecation warning (found in specs):
```
DEPRECATION WARNING: ActionDispatch::Http::ParameterFilter is deprecated and will be removed from Rails 6.1.  Use ActiveSupport::ParameterFilter instead.
(called from filter_config at /Users/nicklamuro/code/redhat/manageiq-ui-classic/app/controllers/application_controller.rb:558)
```
Caused by upgrading to [Rails 6.0](https://github.com/ManageIQ/manageiq/issues/19977)
Links
-----
* https://github.com/ManageIQ/manageiq/issues/19977
=> [rails6] Use ActiveSupport::ParameterFilter

app/controllers/application_controller/report_downloads.rb, spec/controllers/application_controller/compare_spec.rb, spec/controllers/application_controller/report_downloads_spec.rb
Fixes the following Deprecation warnings:
```
DEPRECATION WARNING: Rendering layouts from an absolute path is deprecated.
(called from render_pdf_internal_rr at /home/travis/build/ManageIQ/manageiq-ui-classic/app/controllers/application_controller/report_downloads.rb:47)
DEPRECATION WARNING: Rendering layouts from an absolute path is deprecated.
(called from print_report at /Users/nicklamuro/code/redhat/manageiq-ui-classic/app/controllers/application_controller/report_downloads.rb:124)
DEPRECATION WARNING: Rendering layouts from an absolute path is deprecated.
(called from set_summary_pdf_data at /home/travis/build/ManageIQ/manageiq-ui-classic/app/controllers/application_controller/report_downloads.rb:234)
```
Caused by the [Rails 6.0 …
=> [rails6] Use relative paths for layouts

app/assets/stylesheets/list_view.scss, app/javascript/components/gtl/DataTable.jsx
Adds a `white-space: nowrap;` property to table headers to ensure that the titles of columns remain on one line without affecting the tables body regardless of locale.
Preview (Overview -> Saved Reports ):
=> Prevented Text-Wrapping in Column Titles (CSS)

app/views/layouts/print/textual_summary.html.haml
main_configuration_profile doesn't exist since #6782 (dd14060)
and the other 2 files only exist in their automation_manager/ version now
=> print/textual_summary: remove provider_foreman code

app/javascript/components/topology_toolbar.jsx, app/javascript/spec/toolbar/__snapshots__/topology_toolbar.spec.jsx.snap, app/stylesheet/toolbar.scss
This is to fix search alignment in topology toolbar, i tried to match search field with other searches in MIQ. 
Before:
After:
=> Fix search alignment in topology toolbar

spec/config/routes.pending.yml
Someone probably introduced the right feature, so this can go away. Also fixes the broken master ...
=> Drop the MiqEventController#report_data from the pending route specs

app/controllers/report_controller/reports/editor.rb, app/views/report/_form_filter_chargeback.html.haml, spec/controllers/miq_report_controller/reports/editor_spec.rb
This is for Chargeback Vms and Chargeback Container Projects report.
Before
After
Backward compatibility is supported.
cc @gtanzillo 
=> Allow filtering by multiple tags in chargeback report editor

app/views/ems_storage/edit.html.haml, config/routes.rb
Followup on https://github.com/ManageIQ/manageiq-ui-classic/pull/7607 these routes are not accessible from the UI
=> Drop dead routes related to EMS storage

app/assets/stylesheets/patternfly_overrides.scss
Found in Services -> Workloads -> VMs and Instances
Fixes: [#10465](https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/10465) (2nd issue)
Preview:
=> Modified CSS So That Text Wrapping Does Not Occur

app/controllers/report_controller/reports/editor.rb, app/views/report/_form_filter_chargeback.html.haml, spec/controllers/miq_report_controller/reports/editor_spec.rb
This is for Chargeback Vms and Chargeback Container Projects report.
Before
After
- part of ManageIQ/manageiq#20689
- similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/7614
cc @gtanzillo
=> Support grouping by multiple tag categories in chargeback editor

app/controllers/configuration_controller.rb
When rendering `ui_4.html.haml` which is accessible from `Settings -> My Settings -> Time Profiles`, the view expects the `@tabs` variable to be preseeded with data. When deleting a time profile, this variable is just `nil` which causes issues with the page to get rendered after the deletion.
=> Build the tabs after deleting a time profile

app/helpers/configured_system_helper/textual_summary.rb, app/helpers/term_of_service_helper.rb, app/views/report/_form_filter_chargeback.html.haml
Ui enhancements - implements https://github.com/ManageIQ/manageiq-providers-ibm_terraform/issues/55
- Expose cpu/memory information for Configured Systems (related backend change - https://github.com/ManageIQ/manageiq/pull/21045)
- updated **Show Costs by** options for Chargeback for Configured Systems
- added option to assign tags for Configured Systems
=> Support Chargeback for configured systems

app/helpers/application_helper/toolbar_builder.rb
Fixes various warnings of this variety:
app/models/file_depot_ftp.rb:128: warning: URI.escape is obsolete
app/models/mixins/file_depot_mixin.rb:42: warning: URI.escape is obsolete
From: https://github.com/ManageIQ/manageiq/pull/21036
Related: https://github.com/ManageIQ/manageiq/issues/19678
=> Use URI::DEFAULT_PARSER escape/unescape to avoid ruby 2.7 warnings

app/javascript/components/select/index.jsx
The `includeEmpty` was not implemented for select components without a `loadOptions` attribute, so fixing it now. This will allow us to have the same placeholder-logic for dropdowns in Carbon as we had in PF3.
=> Allow the includeEmpty attribute for select with static options

spec/routes_spec.rb
running `rake spec:routes` emits a Kernel.warn for every false positive (about 1300 messages) ([example](https://travis-ci.com/github/ManageIQ/manageiq-ui-classic/jobs/480758459#L2103))
WARNING: ignoring the provided expectation message argument (false) since it is not a string or a proc.
that's because `!fp && error_message` returns false or the string, and false is warned about.
Since Proc is also an option, wrapping in a proc, which prevents the warning.
Cc @skateman
=> routes_spec - silence WARNING about false message

app/controllers/cloud_volume_controller.rb, app/helpers/application_helper/toolbar/cloud_volume_center.rb, app/helpers/application_helper/toolbar/cloud_volumes_center.rb, app/javascript/components/remove-generic-item-modal.jsx, app/javascript/spec/remove-generic-item-modal/remove-generic-item-modal.spec.js, config/routes.rb
This PR changes the regular delete button of cloud-volume to a modal which allows picking between forced and non-forced option.
Part of https://github.com/ManageIQ/manageiq/issues/21055
Depends on:
=>  Safe delete for cloud-volume

app/controllers/mixins/actions/host_actions/misc.rb
Depends:
Fixes https://github.com/ManageIQ/manageiq-providers-openstack/issues/98
=> Replace Host.validate_destroy with supports feature

app/controllers/automation_manager_configured_system_controller.rb, app/controllers/automation_manager_controller.rb, app/controllers/mixins/sandbox.rb, app/helpers/application_helper.rb, app/helpers/application_helper/listnav.rb, app/helpers/application_helper/page_layouts.rb, app/helpers/application_helper/toolbar/automation_manager_configured_system_center.rb, app/helpers/application_helper/toolbar/automation_manager_configured_systems_center.rb, app/helpers/automation_manager_configured_system_helper.rb, app/presenters/menu/default_menu.rb, app/presenters/tree_builder.rb, app/views/automation_manager_configured_system/show.html.haml, app/views/automation_manager_configured_system/show_list.html.haml, config/routes.rb, spec/config/routes.pending.yml, spec/controllers/automation_manager_controller_spec.rb
De-explorized Configured Systems, Added new second level "Configured Systems" under Automation/Ansible Tower
Dependent core [PR](https://github.com/ManageIQ/manageiq/pull/21076)
Cross repo [PR](https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/333)
before
after
=> Moved Configured Systems out of Ansible Tower Explorer

app/stylesheet/application-webpack.scss, app/stylesheet/ddf_override.scss
Temporary fix that adds a margin to the bottom of react forms so buttons aren't right up against the bottom of the page
Before:
After:
=> Added Margin to the Bottom of React Forms

app/assets/stylesheets/patternfly_overrides.scss, app/controllers/application_controller/compare.rb, app/helpers/application_helper/listnav.rb, app/views/layouts/_center_div_with_listnav.html.haml, app/views/layouts/_compare.html.haml, app/views/layouts/_content.html.haml, app/views/layouts/listnav/_compare_sections.html.haml, spec/helpers/application_helper_spec.rb
Issue : https://github.com/ManageIQ/manageiq-ui-classic/issues/7364
Before:
Clickable links in compare and drift screens are not accessible by keyboard (TAB and ENTER)
After:
=> Fix keyboard accessibility for compare and drift screens

app/helpers/application_helper/button/generic_feature_button_with_disable.rb, spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb
`SupportsFeatureMixin::UnknownFeatureError` removed in https://github.com/ManageIQ/manageiq/pull/21046
=> Rework to not use SupportsFeatureMixin::UnknownFeatureError

app/javascript/menu/search.jsx
Issue: PlaceHolderText prop is changed in carbon, so need to update it to placeholder.
=> Fix placeholder prop console error

app/helpers/application_helper/toolbar/drift_center.rb, app/helpers/application_helper/toolbar/summary_center.rb, app/helpers/application_helper/toolbar/summary_center_restful.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
This PR removes the eval code from the Toolbar Builder by using procs instead of the eval of Strings.  Additionally, once the eval went away, there was no longer a need for the view_binding, so that was removed too.
Fixes #2049
=> Change url_parms to accepts Procs instead of eval of Strings

app/helpers/application_helper/button/delete_server.rb, app/helpers/application_helper/button/role_suspend.rb
Because lines were split in the code, they were getting put in the message catalog as:
"Activate the %{server_role_description} Role on another Server to \\\nsuspend it on %{server_name} [%{server_id}]"
"Server %{server_name} [%{server_id}] can only be deleted if it is stopped or \\\nhas not responded for a while"
=> Fix i18n message

app/javascript/components/breadcrumbs/notifications-toggle.jsx, app/javascript/components/notification-drawer/helpers.js
Fixed syntax, this was not causing any issue with previous version of ruby, but started throwing a JS error after upgrading to ruby 2.6.6
Error in web console, breadcrumbs bar and notification drawer were not getting loaded in UI
Following occurrences were using correct syntax
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/javascript/components/remove-catalog-item-modal.jsx#L107-L108
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/javascript/components/remove-catalog-item-modal.jsx#L125-L126
=> Fixed i18n `n__` call syntax.

product/views/ConfigurationProfile.yaml, product/views/ConfiguredSystem.yaml
This is an enhancement to add the vendor to configured systems and target platform to the configuration profile list:
=> Add vendor to configured systems and target platform to configuration profiles

app/javascript/components/breadcrumbs/notifications-toggle.jsx, app/javascript/components/notification-drawer/helpers.js
Reverts ManageIQ/manageiq-ui-classic#7677
Reverting this PR as this is not the correct fix, issue is actually introduced by https://github.com/ManageIQ/manageiq/pull/21115 https://github.com/ManageIQ/manageiq-ui-classic/pull/7668 will create a new PR with a fix to those files
=> Revert "Fixed i18n `n__` call syntax."

app/controllers/cloud_volume_controller.rb, app/controllers/host_initiator_controller.rb, app/helpers/cloud_volume_helper/textual_summary.rb, app/helpers/host_initiator_helper/textual_summary.rb, app/views/cloud_volume/show.html.haml, app/views/host_initiator/show.html.haml, spec/helpers/cloud_volume_helper/textual_summary_spec.rb
We have recently added HostVolumeMapping which binds instances of CloudVolume to Instance of HostInitiator. So each CloudVolume could have multiple HostInitiators, and each HostInitiator could have multiple CloudVolumes.
These 2 PRs add the mapped HostInitiators to the CloudVolume view and CloudVolumes to HostInitiators view.
I'd like to back-port these changes to Lasker.
Addition to host-initiator view
Clicking the button from the host-initiator shows the mapped volumes
Addition to the cloud-volume view
Clicking the button on the cloud-volume view shows the mapped host-initiatords
Relies on https://github.com/ManageIQ/manageiq/pull/21084
=> Added GUI cross-ref between host-initiator and cloud-volume.

app/views/catalog/_ot_tree_show.html.haml, product/views/OrchestrationTemplate.yaml
Found in Services->Catalogs->Orchestration Templates
Related to: https://github.com/ManageIQ/manageiq/pull/20817
Preview:
- English
- French
=> Formatted Date and Time for Different Locales

app/javascript/components/async-credentials/edit-password-field.jsx, app/javascript/components/async-credentials/password-field.jsx, app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap, app/javascript/spec/async-credentials/edit-password-field.spec.js
Modifies `edit-password-field.jsx` to support Text Areas
Fixes: #7647
=> Add Text Area Functionality to edit-password-field

app/views/catalog/_ot_tree_show.html.haml, product/views/OrchestrationTemplate.yaml
Reverts ManageIQ/manageiq-ui-classic#7507
@fryguy can you merge this, i was not aware that #7507 was dependent on core PR, the comment on the PR was not clear and pending core label was missing
=> Revert "Formatted Date and Time for Different Locales"

app/helpers/application_helper/toolbar/miq_policies_center.rb
Issue:
In english, Add a New Policy Button is in chinese
After:
=>  Fix translation for Add a New Policy Button

app/helpers/application_helper/toolbar/miq_policy_set_center.rb, app/helpers/application_helper/toolbar/miq_policy_sets_center.rb
Failed to delete the policy profile.
1.  Click Control->policy profiles
2. Create one new profile
3. Check on new profile you created
4. Click Configuration -> Delete policy profiles
5. Verify profile can be deleted successfully
profile can be deleted successfully and page is redirected to profile list page.
After delete page was redirected to system error page.
=> Fixed policy profile delete button to redirect to show_list.

app/views/condition/_form.html.haml
English string in Control -> Condditions page in non-English locale
String should be translated in every native locale
Please check the attachment for details
1. Click Control -> Conditions
2. Click configuration-> add a new condition
Need to display translation string correct
Before:
After:
=> Fix translation in Add condition page

app/controllers/miq_policy_controller.rb, app/controllers/miq_policy_set_controller.rb
**Issue:** : breadcrumb is broken for Add /Edit Policy and  Add /Edit Policy Profiles
**Before:**
**After:**
@miq-bot assign @DavidResende0  
@miq-bot add_reviewer @DavidResende0 , @Fryguy
=> Fix breadcrumb for Add /Edit policies and policy profiles

app/controllers/application_controller.rb, app/controllers/miq_task_controller.rb, app/helpers/application_helper.rb, app/javascript/components/gtl/DataTable.jsx, app/stylesheet/application-webpack.scss, app/stylesheet/data-table.scss
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7683 and able to click on non clickable rows in table
As a part of this pr, fixed https://github.com/ManageIQ/manageiq-ui-classic/issues/7683 and removed pointer/blue color on hover in non clickable rows, this will reduce confusion to users.
**Before:**
**After:**
@miq-bot  assign @Fryguy 
=> Fix settings--> tasks table rows

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
This change takes advantage of ActiveRecord knowing that an incoming
integer cannot be larger than a bigint.  ActiveRecord will construct the
query in a way that prevents the query from returning any records, which
makes sense for oversized ids
Fixes #7692
=> Handle incoming numerics for id that are bigger than a bigint

app/assets/stylesheets/patternfly_overrides.scss, app/views/report/_form.html.haml, app/views/report/_form_chart.html.haml, app/views/report/_form_columns.html.haml, app/views/report/_form_consolidate.html.haml, app/views/report/_form_filter.html.haml, app/views/report/_form_formatting.html.haml, app/views/report/_form_sort.html.haml
Found in: Overview->Reports->Add a new Report->Columns
Fixes: https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/18234
Before:
After:
=> Modified CSS to Prevent Text Wrapping in Certain Locales

app/controllers/network_router_controller.rb
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/1602
Changes the creation dialog to emphasize the fact that Network Router creation must be queued and is not created instantly
=> Changed "Created New Network Router" Dialog

app/controllers/application_controller/miq_request_methods.rb, app/controllers/application_controller/report_data_additional_options.rb, app/javascript/components/gtl-view.jsx, app/javascript/components/gtl/DataTable.jsx, app/javascript/components/gtl/StaticGTLView.jsx
**Issue:**
1)  In Compute-->Instances-->Instances by provider-->Lifecycle-->Provision Instances, when loading the page initially, pagination is missing on table.
2) In same page, once select/deselect check box happens, click on any image, continue button is still disabled.
**Before:**
**After**
@miq-bot add_reviewer @Fryguy @DavidResende
=> Fix provision instance table and deprecated checkbox

app/javascript/components/cloud-volume-form/index.jsx
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7712
**Before**
**After:**
API PR:https://github.com/ManageIQ/manageiq-api/pull/1028
@miq-bot add-reviewer @Fryguy 
@miq-bot add-label  lasker/yes?
=> Fix edit cloud volume api call and pass record id

package.json
Updated the Carbon Component Mapper to version 2.24.3 to add this fix to ManageIQ: https://github.com/data-driven-forms/react-forms/pull/1042
Part of the Fix for: https://github.com/ManageIQ/manageiq-ui-classic/issues/7713
Before:
After:
=> Updated Carbon Component Mapper

app/views/cloud_tenant/_show_dashboard.html.haml
**Issue:** https://github.com/ManageIQ/manageiq-ui-classic/issues/7625
Part of https://github.com/ManageIQ/manageiq-ui-classic/pull/7658/files 
I missed converting cloud tenant dashboards charts to carbon in above pr.
**Before:**
**After:**
=> Convert cloud tenant charts to carbon

app/controllers/ops_controller/settings/zones.rb, app/views/ops/_zone_form.html.haml, spec/controllers/ops_controller/settings/zones_spec.rb
Removes Auth on Zones from both the form view and the controller in the UI.  Still allows them to be added via that `rails console`, but removes the feature from the UI, with the intent to possibly remove from the product all together in a future release.
~~Note:  Documentation should probably also be updated to remove mentioning this.~~ See **Links** below for docs PR.
Also, this "addresses" https://github.com/ManageIQ/manageiq-api/issues/898 by simply not making it a requirement to fix any more.  Also should simplify https://github.com/ManageIQ/manageiq-ui-classic/issues/6917
Links
-----
* Addresses https://github.com/ManageIQ/manageiq-api/issues/898
* Related:  https://github.com/ManageIQ/manageiq-ui-classic/issues/6917
* Docs PR: …
=> [ops_controller/settings/zones.rb] Soft delete auth

app/stylesheet/menu.scss
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7731
Before:
After:
@miq-bot assign @kavyanekkalapu 
=> Fix background color of navbar items on hover

app/javascript/components/workers-form/workers-form.jsx, app/javascript/spec/workers-form/workers-form.spec.js
The existing code was checking only the worker's value and falling back to
queue_worker_base but not falling back to the worker_base if the other two
locations had no value.
This causes the select's value to be the first item in the select, which is 200 MB.
If you as a user try to change some other unrelated value and then save, all
of these "incorrect" 200 MB values get saved instead of the correct value
inherited from worker_base.
For example, smart_proxy_worker was correct because that worker class specified a
memory_threshold.  Reporting, C & U processor and collector, Generic, and
Priority workers were all showing 200 MB in the select because that's the first
entry in the select and because the default of 1.gigabyte was coming from
worker_base and no value was coming from …
=> Handle queue workers inheriting values from worker_base: fix incorrect count and memory threshold values on workers tab

app/javascript/components/tree-view/redux.jsx, app/javascript/oldjs/controllers/buttons/button_group_controller.js, app/views/layouts/angular/_x_edit_buttons_angular.html.haml
Issue: https://github.com/ManageIQ/manageiq/issues/21083
Here issue is, when we change something in the tenants tree, save button is not getting enabled (check before screenshot).
**rootcause:** There are two causes in this issue
-  Tree is a react componet where as rest of the form is angular, so angular form is not getting know when the tree is dirty.
- There is code in app/presenters/tree_builder_tenants.rb which has some conditions to execute, there is a delay in executing those functions and react component code is getting called before that code executes, To fix this, i am calling react reducer code when there is data change in the tree.
**Before:**
**After:**
=> Fix tenants tree in Edit catalog item

app/controllers/application_controller.rb, app/controllers/infra_networking_controller.rb, app/controllers/storage_controller.rb, app/controllers/vm_common.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7711
In this issue, when search text is present, click on `Add New` gives title with search which is wrong. In this pr, added to show search title only when it is not in a form.
**Before**
**After**
 @miq-bot add_reviewer @Fryguy , @DavidResende0
=> Fix right hand side title when search text present

app/controllers/ops_controller/settings/tags.rb
Fixed a bug where the description instead of the name was being displayed in the category add success message.
Before:
After:
=> Fixed bug of description appearing instead of name in category creation success message

config/routes.rb
Git Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7742
Fixed the download buttons for the automation configured systems.
Before:
@miq-bot assign @kavyanekkalapu 
=> Fixed download buttons for automation-configured systems

app/controllers/cloud_object_store_container_controller.rb, app/controllers/miq_policy_controller/events.rb, app/controllers/miq_policy_controller/policies.rb, app/controllers/miq_policy_set_controller.rb, app/controllers/pxe_controller/iso_datastores.rb, app/controllers/security_policy_rule_controller.rb, app/helpers/application_helper.rb, app/helpers/application_helper/button/miq_action_modify.rb, app/helpers/application_helper/toolbar/miq_policy_center.rb, app/helpers/application_helper/toolbar/saved_reports_center.rb, app/presenters/menu/default_menu.rb, spec/config/routes.pending.yml, spec/controllers/ems_storage_controller_spec.rb, spec/controllers/miq_ae_customization_controller_spec.rb, spec/controllers/miq_alert_controller_spec.rb, spec/controllers/miq_report_controller/dashboards_spec.rb, spec/controllers/pxe_controller_spec.rb, spec/controllers/vm_common_spec.rb, spec/routes_spec.rb
* Change UI frontend method `role_allows?` to verify the product feature being checked exists so we can find typo'd/renamed feature identifiers.  
* Fix assert_privileges calls to use the correct identifier
* Change the routes_spec to show us the failures in the event of an unexpected exception
* Raises an error in non-production when the database is seemingly seeded with features but still missing the requested feature.  This very gracefully allows tests that assume super admin feature list ("everything") to bypass the above check.  We will need to change existing specs to properly seed the features they need to they can test as non-admin users with only the features they need.
* Fix tests that partially seed features to see all of the needed ones
=> Fix broken privilege assertions - raise errors in non-production on future broken feature assertions

app/javascript/components/aggregate_status_card.jsx
Issue: Right now, broken notification is displaying when status is not defined.
**Before:**
**After:**
=> Notification should not display when last refresh data is unavailable

app/views/miq_request/_prov_dialog_volume_fieldset.html.haml
Fixed the issue of no information being displayed for the provision instances volume info icon.
Before:
After:
=> Fixed the missing information for volume info icon

app/views/layouts/_center_div_no_listnav.html.haml
**Issue:** Right now , BG color of react forms (mostly edit forms) is not correct when opened from dashboard, all the filels and BG color are same , making it same as forms opened from table view.
**Before**
**After**
@miq-bot add_reviewer @Fryguy, @DavidResende0 
=> Fix BG color of  react form when opened from dashboard view.

app/controllers/miq_request_controller.rb
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7718
Fixed issue of request page buttons missing when opening a request link directly and then signing in.
Before:
After:
=> Fixed missing request page buttons

app/controllers/cloud_object_store_container_controller.rb, app/controllers/miq_policy_controller/events.rb, app/controllers/miq_policy_controller/policies.rb, app/controllers/miq_policy_set_controller.rb, app/controllers/pxe_controller/iso_datastores.rb, app/controllers/security_policy_rule_controller.rb, app/helpers/application_helper.rb, app/helpers/application_helper/button/miq_action_modify.rb, app/helpers/application_helper/toolbar/miq_policy_center.rb, app/helpers/application_helper/toolbar/saved_reports_center.rb, spec/config/routes.pending.yml, spec/controllers/automation_manager_controller_spec.rb, spec/controllers/ems_storage_controller_spec.rb, spec/controllers/miq_ae_customization_controller_spec.rb, spec/controllers/miq_alert_controller_spec.rb, spec/controllers/miq_report_controller/dashboards_spec.rb, spec/controllers/pxe_controller_spec.rb, spec/controllers/vm_common_spec.rb, spec/routes_spec.rb
Manual backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/7740 WITHOUT https://github.com/ManageIQ/manageiq-ui-classic/pull/7740/commits/ca4fec8b68635095b3749cd48ab69d2ce9317028 since https://github.com/ManageIQ/manageiq/pull/21108 was MASTER only and `ems_automation_manager_show_list` doesn't exist on lasker BUT `automation_manager` does [exist](https://github.com/ManageIQ/manageiq/blob/lasker/db/fixtures/miq_product_features.yml#L5115) so the existing [code](https://github.com/ManageIQ/manageiq-ui-classic/blob/lasker/app/presenters/menu/default_menu.rb#L258) is fine and  that commit is NOT needed on lasker.
EDIT:
I added 2 simple lasker only test fixes and 1 application_helper fix that makes it so tests don't have to be so strict to creating features they use in the tests.
=> [LASKER] Manual backport 7740

app/assets/stylesheets/patternfly_overrides.scss
=> Fix page layout for Automate-->Simulation page

app/views/miq_request/_prov_field.html.haml, app/views/shared/views/_prov_dialog.html.haml
CPU and Memory hot-add/remove is a feature of the vmware provider which can be configured when a VM is created.  Add support for these checkboxes in the provision dialogs.
Depends:
=> Add support for cpu/memory hot add in provisioning

app/controllers/guest_device_controller.rb, app/controllers/physical_network_port_controller.rb
The only reason to override this method is if your controller doesn't follow the convention.  Since these two controllers both follow the convention of `model + 'Controller'`, we can let the [superclass handle it](https://github.com/ManageIQ/manageiq-ui-classic/blob/96fc53321edaab4a5b3dc41b13966577bdffd90f/app/controllers/application_controller.rb#L145-L149)
For example (current master):
```
irb(main):001:0> PhysicalNetworkPortController.method(:model).source_location
=> ["/Users/joerafaniello/.gem/ruby/2.6.6/bundler/gems/manageiq-ui-classic-96fc53321eda/app/controllers/physical_network_port_controller.rb", 11]
irb(main):002:0> PhysicalNetworkPortController.method(:model).super_method.source_location
=> ["/Users/joerafaniello/.gem/ruby/2.6.6/bundler/gems/manageiq-ui-classic-96fc53321eda/ap …
```
=> Remove unnecessary method

spec/controllers/cloud_subnet_controller_spec.rb
- This is to account for a recent change in core to change the queued method name for deleting subnets
See:
https://github.com/ManageIQ/manageiq/pull/21307
=> Fixed delete subnet queued method name

app/controllers/miq_policy_controller/policies.rb
Fixed error that would occur when the add policy form was edited.
Before: 
After:
=> Fixed error for  adding policies

app/controllers/application_controller/advanced_search.rb
Error occurs when clicking cancel on the template editor form.
=> Fixed error for cancel button in template editor
