ManageIQ/manageiq-ui-classic

README.md
depends on https://github.com/ManageIQ/guides/pull/173
=> Add a link to guides/ updating instructions

spec/controllers/ems_cloud_controller_spec.rb, spec/controllers/orchestration_stack_controller_spec.rb, spec/shared/presenters/tree_node/common.rb, spec/shared/presenters/tree_node/server_roles.rb
* Move shared/presenters from main repo
* Stub web request in ems_cloud_controller_spec
* Adjust fixture path in orchestration_stack_controller_spec
=> Fixes for specs

tools/ci/before_install.sh
Without this line test are using the gem and not the new code :-(
=> Use the testing gem when running travic tests

app/controllers/mixins/containers_common_mixin.rb, spec/controllers/container_image_controller_spec.rb
This is a migration of https://github.com/ManageIQ/manageiq/pull/13075
=> Rescue failed container annotation attempts

app/helpers/application_helper/toolbar/diagnostics_region_center.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1406806
=> Fix placeholder names in diagnostics_region_center toolbar

Gemfile, manageiq-ui-classic.gemspec, tools/ci/before_install.sh
Unfortunately codeclimate needs to remain in the Gemfile... #1
=> Specify the dependencies in the gemspec instead of the Gemfile

.travis.yml, Gemfile, manageiq-ui-classic.gemspec, tools/ci/before_install.sh, tools/ci/setup_js_env.sh
This PR replaces #35, #43, and #49 with something a little cleaner and removes some no-longer-needed hacks.
@bdunne Please review.
=> Cleanup testing dependencies

app/controllers/application_controller/tree_support.rb, app/controllers/ops_controller/ops_rbac.rb, app/helpers/application_helper.rb, app/helpers/application_helper/button/ab_group_reorder.rb, app/helpers/application_helper/button/basic.rb, app/helpers/application_helper/button/miq_action_modify.rb, app/helpers/application_helper/toolbar_chooser.rb, app/helpers/automate_tree_helper.rb
Move the helper method to helpers.
Use the helper method, where possible.
=> Use parse_nodetype_and_id where possible.

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb
Use the same variable in dashboard as used elsewhere.
=> One less place to store report results id.

app/controllers/chargeback_controller.rb, app/controllers/miq_ae_customization_controller/dialogs.rb, app/controllers/miq_ae_customization_controller/old_dialogs.rb, app/controllers/ops_controller/db.rb, app/controllers/ops_controller/diagnostics.rb, app/controllers/ops_controller/ops_rbac.rb, app/controllers/ops_controller/settings/analysis_profiles.rb, app/controllers/ops_controller/settings/ldap.rb, app/controllers/ops_controller/settings/schedules.rb, app/controllers/pxe_controller/iso_datastores.rb, app/controllers/pxe_controller/pxe_customization_templates.rb, app/controllers/pxe_controller/pxe_image_types.rb, app/controllers/pxe_controller/pxe_servers.rb, app/controllers/storage_controller/storage_d.rb, app/controllers/storage_controller/storage_pod.rb, app/helpers/application_helper.rb
To be merged after: https://github.com/ManageIQ/manageiq-ui-classic/pull/50
=> Extract method update_gtl_div and use it.

app/presenters/tree_builder_tags.rb
After reviewing these changes for euwe / manageiq/manageiq#13308, a few improvements
were found. Bringing these back into master
followup to #83
=> TreeBuilderTag#selected_entry_value

app/services/ui_service_mixin.rb
@martinpovolny No reason for this to stay on the main repo side
=> Move UiServiceMixin from main repo to manageiq-ui-classic

app/assets/javascripts/controllers/cloud_subnet/cloud_subnet_form_controller.js, app/controllers/cloud_subnet_controller.rb, app/views/cloud_subnet/new.html.haml, config/routes.rb
Dynamically filters the network list available for creating a subnet
upon the selection of the network providers.
https://bugzilla.redhat.com/show_bug.cgi?id=1394289
=> Cloud Subnet: Filtering networks by ems_id

app/controllers/chargeback_controller.rb, app/controllers/miq_ae_customization_controller/dialogs.rb, app/controllers/miq_ae_customization_controller/old_dialogs.rb, app/controllers/miq_policy_controller.rb, app/controllers/ops_controller/db.rb, app/controllers/ops_controller/diagnostics.rb, app/controllers/ops_controller/ops_rbac.rb, app/controllers/ops_controller/settings/analysis_profiles.rb, app/controllers/ops_controller/settings/ldap.rb, app/controllers/ops_controller/settings/schedules.rb, app/controllers/pxe_controller/iso_datastores.rb, app/controllers/pxe_controller/pxe_customization_templates.rb, app/controllers/pxe_controller/pxe_image_types.rb, app/controllers/pxe_controller/pxe_servers.rb, app/controllers/storage_controller/storage_d.rb, app/controllers/storage_controller/storage_pod.rb, app/helpers/application_helper.rb
Actually it need to be like this as `&page=X` is part of url frequently.
This matches the original code.
Sorry :-(
Ping @himdel : please, merge
Testing: try list of items such as Cloud Subnets, then click a single item and then click the breadcrumb for the previous page.
=> Moved params[:page] test to the correct helper method.

app/presenters/menu/default_menu.rb
We can just as well use plain `N_()` here and make things easier.
=> Get rid of deferred_ui_lookup()

app/controllers/ops_controller/ops_rbac.rb, spec/controllers/ops_controller_spec.rb
@evertmulder, this includes your fix and also fixes the jenkins failure.
Thanks a lot for your contribution!
/cc @mzazrivec @martinpovolny
=> Fix for #13291, Tenant admin can escalate rights

app/views/miq_policy/_rsop_form.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1404273
=> Updated text string for consistency

app/controllers/generic_object_controller.rb, app/controllers/miq_ae_class_controller.rb, app/controllers/miq_ae_customization_controller.rb, app/controllers/miq_ae_tools_controller.rb, app/controllers/miq_request_controller.rb, app/presenters/menu/default_menu.rb
Moved original sub tabs under "Automate" main tab 1 level down to "Automation / Automate" tabs
https://www.pivotaltracker.com/n/projects/1937457/stories/137618573
before
after
=> Moved Automate tabs down 1 level to "Automation / Automate"

app/controllers/miq_ae_class_controller.rb, app/helpers/miq_ae_class_helper.rb
Because it was said, we want to use ERB::Util everywhere.
=> Use ERB::Util.html_escape instead of CGI.escapeHTML

app/helpers/application_helper/button/ontap.rb, app/helpers/application_helper/button/ontap_logical_disk_perf.rb, app/helpers/application_helper/button/ontap_logical_disk_statistics.rb, app/helpers/application_helper/toolbar/ontap_file_share_center.rb, app/helpers/application_helper/toolbar/ontap_logical_disk_center.rb, app/helpers/application_helper/toolbar/ontap_storage_system_center.rb, app/helpers/application_helper/toolbar/ontap_storage_volume_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/ontap_logical_disk_perf_spec.rb, spec/helpers/application_helper/buttons/ontap_logical_disk_statistics_spec.rb, spec/helpers/application_helper/buttons/ontap_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
| --- | --- |
| ontap_storage_system_statistics, ontap_storage_volume_statistics, ontap_file_share_statistics | Ontap < Basic |
| ontap_logical_disk_perf | OntapLogicalDiskPerf < Basic |
| ontap_logical_disk_statistics | OntapLogicalDiskStatistics < Ontap |
**TODO:** find the buttons in UI.
Parent issue: #6259
Related issue: #6554
Pivotal Tracker: https://www.pivotaltracker.com/story/show/135544583
Original PR: https://github.com/ManageIQ/manageiq/pull/13109
=> Toolbar refactoring: Ontap buttons

app/assets/javascripts/controllers/ems_infra_dashboard/util/infra-charts-mixin.js, app/services/ems_infra_dashboard_service.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1389476
before:
after:
=> Added missing units on Heatmap tooltip

app/views/miq_policy/_event_details.html.haml, app/views/ops/_ap_form_nteventlog.html.haml, app/views/pxe/_pxe_server_details.html.haml, app/views/report/_form_sort.html.haml, app/views/vm_common/console_vmrc.html.haml
..because it is most definitely dead, no point in keeping it in the code base.
=> Remove code under `if false`

app/assets/javascripts/miq_tree.js, app/controllers/vm_common.rb, app/presenters/tree_builder_genealogy.rb, app/views/vm_common/_vmtree.html.haml, config/routes.rb, spec/presenters/tree_builder_genealogy_spec.rb
https://www.pivotaltracker.com/n/projects/1613907/stories/129518747
Compute -> Infrastructure -> Virtual Machines -> choose one -> Show parent and child VMs
@miq-bot add_label wip, technical debt
TODO:
=> Convert Genealogy Tree

app/controllers/availability_zone_controller.rb, app/controllers/cloud_object_store_object_controller.rb, app/controllers/cloud_tenant_controller.rb, app/controllers/cloud_volume_controller.rb, app/controllers/configuration_job_controller.rb, app/controllers/ems_common.rb, app/controllers/host_aggregate_controller.rb, app/controllers/infra_networking_controller.rb, app/controllers/mixins/containers_common_mixin.rb, app/controllers/mixins/generic_session_mixin.rb, app/controllers/orchestration_stack_controller.rb, app/controllers/provider_foreman_controller.rb, app/controllers/storage_manager_controller.rb
@jzigmund, @hayesr : please, review
=> Use GenericSessionMixin.

app/controllers/miq_policy_controller/alert_profiles.rb, locale/en/ManageIQ_UI_Classic.po
https://bugzilla.redhat.com/show_bug.cgi?id=1415184
=> Typo fix in alert profile assignment flash message

app/assets/javascripts/controllers/generic_object/generic_object_definition_controller.js, app/assets/javascripts/services/generic_object_subscription_service.js, app/controllers/generic_object_controller.rb, app/helpers/application_helper/toolbar/generic_object_definition.rb, config/routes.rb, spec/controllers/generic_object_controller_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb, spec/javascripts/controllers/generic_object/generic_object_definition_controller_spec.js, spec/javascripts/services/generic_object_subscription_service_spec.js
This has been converted from https://github.com/ManageIQ/manageiq/pull/12102.
=> Add delete functionality for generic object UI

app/views/storage/_storage_pod_folders.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1408523
=> Fix link to display Datastore Clusters

app/helpers/application_helper/button/availability_zone_performance.rb, app/helpers/application_helper/button/availability_zone_timeline.rb, app/helpers/application_helper/toolbar/availability_zone_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/availability_zone_performance_spec.rb, spec/helpers/application_helper/buttons/availability_zone_timeline_spec.rb
Move code from `disable_button` method to separate classes.
=> Availability zones butons

app/controllers/application_controller/miq_request_methods.rb, app/controllers/ops_controller/rbac_tree.rb, app/helpers/host_helper/textual_summary.rb, app/presenters/tree_builder_alert_profile.rb, app/presenters/tree_builder_buttons.rb, app/presenters/tree_builder_condition.rb, app/presenters/tree_builder_policy.rb, app/presenters/tree_builder_protect.rb, app/presenters/tree_node/miq_action.rb, app/presenters/tree_node/miq_policy.rb, app/presenters/tree_node/miq_widget.rb, spec/controllers/application_controller/explorer_spec.rb, spec/presenters/tree_builder_protect_spec.rb, spec/presenters/tree_node/miq_action_spec.rb, spec/presenters/tree_node/miq_policy_spec.rb, spec/presenters/tree_node/miq_widget_spec.rb
https://www.pivotaltracker.com/n/projects/1613907/stories/129462395
=> automate and policy tree icon conversion

CHANGELOG.md
First version of Changelog for this repository
[skip ci]
=> Changelog Sprint 52

spec/controllers/chargeback_controller_spec.rb
If not merged today, bad things 🔨 💥 happen after Manageiq/manageiq#13615 is merged.
But feel no pressure. Peace. ☮️ 
@miq-bot add_label chargeback, test
=> Specs: Chargeback seeds are now divided

app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
Similar to #227 but for SniaLocalFileSystemStatistics.
=> Remove SniaLocalFileSystemStatistics button cases

app/helpers/application_helper/button/miq_alert_delete.rb, app/helpers/application_helper/toolbar/miq_alert_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/miq_alert_delete_spec.rb
Move code from disable_button method to separate classes.
=> Alert buttons

app/helpers/application_helper/button/miq_request_delete.rb, app/helpers/application_helper/toolbar/miq_request_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/miq_request_delete_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
Move code from disable_button method to separate classes.
=> Miq request buttons

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Eventually there will to be moved to decorators or somewhere else ... FYI @epwinchell
=> Add support for fonticons in `ApplicationHelper#listicon_image_tag`

app/helpers/application_helper/button/ems_cluster_performance.rb, app/helpers/application_helper/button/ems_cluster_timeline.rb, app/helpers/application_helper/toolbar/ems_cluster_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/ems_cluster_performance_spec.rb, spec/helpers/application_helper/buttons/ems_cluster_timeline_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
Move code from disable_button method to separate classes.
=> Ems cluster buttons

app/presenters/tree_builder_templates_images_filter.rb, app/presenters/tree_builder_vms_instances_filter.rb
Services -> Workload -> choose any VM -> try to select selected node in tree to get back at list of VMs
Before: Cannot reselect node in tree
After: Can reselect node in tree.
Closes #291 
@himdel please review :)
=> Allow reselection of node for Workload tree

app/controllers/ops_controller.rb, app/helpers/application_helper.rb, app/helpers/application_helper/toolbar_builder.rb, app/views/dashboard/_widget.html.haml, app/views/layouts/_perf_options.html.haml, app/views/shared/views/_retire.html.haml
@h-kataria, @romanblanco : please, review
=> Fix misssing "w" in "%w(".

app/views/dashboard/login.html.haml
=> Remove extra interpolation.

app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js
While the intentions were good -- to address a couple of Code Climate errors in this commit: c847b8582a060d3fdfbdda7be1b5f35e396099f6, a bug seems to have snuck in unfortunately.
Fixes #320
=> Fix the VM reconfigure UI form broken as a result of a recent refactor

app/views/miq_request/_prov_field.html.haml
See https://github.com/ManageIQ/manageiq-ui-classic/issues/331
=> Fix for error in displaying HW tab

app/views/layouts/_paging_bar.html.haml, app/views/layouts/_saved_report_paging_bar.html.haml, app/views/layouts/_x_pagingcontrols.html.haml
Fixes: #62
Reaction on issue #62. Duplicated code was moved to another partial.
@martinpovolny or @mzazrivec, please review. I've checked in UI, seems to work fine.
=> Deduplicated the code for bottom paging bar

app/controllers/container_image_controller.rb, app/controllers/container_image_registry_controller.rb, app/controllers/container_replicator_controller.rb
=> Remove forgotton comments.

app/views/shared/summary/_textual.html.haml
Added missing tbody tag
https://bugzilla.redhat.com/show_bug.cgi?id=1420189
=> Fix Stack Template Details screen styling

app/views/layouts/_adv_search_footer.html.haml, app/views/layouts/_user_input_filter.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1380430
- removed three dots from strings (`...`)
- added alt-text to the disabled buttons
@dclarizio can you review?
=> Added alt-text to Advanced Search buttons

app/helpers/application_helper/button/miq_action_delete.rb, app/helpers/application_helper/button/miq_action_edit.rb, app/helpers/application_helper/button/miq_action_modify.rb, app/helpers/application_helper/toolbar/miq_action_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/miq_action_delete_spec.rb, spec/helpers/application_helper/buttons/miq_action_edit_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
Move code from disable_button method to separate classes.
=> Miq action buttons

app/controllers/ems_cluster_controller.rb, app/controllers/host_controller.rb, app/controllers/storage_controller.rb, app/controllers/vm_common.rb
Deleted as part of https://github.com/ManageIQ/manageiq-ui-classic/pull/204
=> Delete ::Settings.product.storage in textual_group_list

CHANGELOG.md
=> Changelog 54

.travis.yml, tools/ci/after_install.sh
Test printing Gemfile.lock as it could be useful for troubleshooting.
=> Print Gem versions after Travis runs

app/controllers/ansible_playbook_controller.rb, app/controllers/ansible_repository_controller.rb, app/decorators/configuration_script_source_decorator.rb, app/decorators/manageiq/providers/ansible_tower/automation_manager/playbook_decorator.rb, app/helpers/ansible_playbook_helper.rb, app/helpers/ansible_playbook_helper/textual_summary.rb, app/helpers/ansible_repository_helper.rb, app/helpers/ansible_repository_helper/textual_summary.rb, app/helpers/application_helper.rb, app/helpers/quadicon_helper.rb, app/presenters/menu/default_menu.rb, app/views/ansible_playbook/show.html.haml, app/views/ansible_playbook/show_list.html.haml, app/views/ansible_repository/show.html.haml, app/views/ansible_repository/show_list.html.haml, config/routes.rb
New screens:
New menu section for Ansible:
Playbook list:
Playbook details:
Repository list:
Repository details:
Playbooks within a repository:
Pending core changes in https://github.com/ManageIQ/manageiq/pull/13731 and https://github.com/ManageIQ/manageiq/pull/13799
=> UI for Ansible Tower Playbooks & Repositories

app/helpers/application_helper/import_export_helper.rb, app/views/miq_ae_customization/_dialog_import_export.html.haml, app/views/report/_export_widgets.html.haml, spec/helpers/application_helper/import_export_helper_spec.rb
This fixes https://github.com/ManageIQ/manageiq/issues/13792 and needs to be combined with [this main repo PR](https://github.com/ManageIQ/manageiq/pull/13871).
=> Fix for ImportFileUpload model is tightly coupled to UI

app/helpers/application_helper/import_export_helper.rb, spec/helpers/application_helper/import_export_helper_spec.rb
=> Fix image paths in ImportExportHelper.

app/controllers/availability_zone_controller.rb, app/controllers/ems_cluster_controller.rb, app/controllers/ems_common.rb, app/controllers/host_aggregate_controller.rb, app/controllers/host_controller.rb, app/controllers/mixins/containers_common_mixin.rb, app/controllers/mixins/generic_show_mixin.rb, app/controllers/mixins/more_show_actions.rb, spec/controllers/container_image_registry_controller_spec.rb, spec/controllers/container_node_controller_spec.rb, spec/controllers/container_project_controller_spec.rb, spec/controllers/container_replicator_controller_spec.rb, spec/controllers/container_route_controller_spec.rb
Make the container show methods follow the same pattern as other places (using GenericShowMixin).
Will allow me to extend #176 to container controllers.
=> Deduplicate show methods using mixins.

app/controllers/miq_ae_tools_controller.rb, app/services/automate_import_json_serializer_service.rb, spec/controllers/miq_ae_tools_controller_spec.rb, spec/services/automate_import_json_serializer_service_spec.rb
This fixes https://github.com/ManageIQ/manageiq/issues/13793 and needs to be combined with [this main repo PR](https://github.com/ManageIQ/manageiq/pull/13872).
=> Fix for AutomateImportJsonSerializer model is tightly coupled to UI

app/views/shared/views/ems_common/angular/_form.html.haml
This is a follow-up to: https://github.com/ManageIQ/manageiq/pull/12259
https://bugzilla.redhat.com/show_bug.cgi?id=1395866
Old
New
Old
New
=> Correct inconsistent provider input field lengths

app/views/availability_zone/show.html.haml, app/views/cloud_object_store_container/show.html.haml, app/views/cloud_object_store_object/show.html.haml, app/views/cloud_volume_backup/show.html.haml, app/views/cloud_volume_snapshot/show.html.haml, app/views/container_build/show.html.haml, app/views/container_group/show.html.haml, app/views/container_image/show.html.haml, app/views/container_image_registry/show.html.haml, app/views/container_node/show.html.haml, app/views/container_project/show.html.haml, app/views/container_replicator/show.html.haml, app/views/container_route/show.html.haml, app/views/container_service/show.html.haml, app/views/container_template/show.html.haml, app/views/ems_cluster/show.html.haml, app/views/host/show.html.haml, app/views/host_aggregate/show.html.haml, app/views/infra_networking/show.html.haml, app/views/middleware_datasource/show.html.haml, app/views/middleware_deployment/show.html.haml, app/views/middleware_domain/show.html.haml, app/views/middleware_messaging/show.html.haml, app/views/middleware_server/show.html.haml, app/views/middleware_server_group/show.html.haml, app/views/miq_template/show.html.haml, app/views/persistent_volume/show.html.haml, app/views/resource_pool/show.html.haml, app/views/storage/show.html.haml, app/views/storage_manager/show.html.haml
This is a bit risky but necessary fix.
* resolves hakiri issues,
* makes sure we know what we render
needed to progress with #176
=> Replace "render => @showtype" with explicit partial name.

app/views/miq_policy/_action_options.html.haml
Follow up for https://github.com/ManageIQ/manageiq-ui-classic/pull/399
=> Update labels for playbook catalog  action

app/helpers/application_helper/button/host_check_compliance.rb, app/helpers/application_helper/button/host_miq_request_new.rb, app/helpers/application_helper/button/host_performance.rb, app/helpers/application_helper/button/host_timeline.rb, app/helpers/application_helper/toolbar/host_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/host_check_compliance_spec.rb, spec/helpers/application_helper/buttons/host_miq_request_new_spec.rb, spec/helpers/application_helper/buttons/host_performance_spec.rb, spec/helpers/application_helper/buttons/host_timeline_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
Refactor Move code from `disable_button` method to separate classes.
=> Host buttons

app/controllers/application_controller/compare.rb
Some methods were not used and some of them were on the wrong place **before** the `private`.
=> Removed dead code, reorganized private methods in compare mixin

app/helpers/application_helper/button/availability_zone_performance.rb, app/helpers/application_helper/button/availability_zone_timeline.rb, app/helpers/application_helper/button/ems_cluster_performance.rb, app/helpers/application_helper/button/ems_cluster_timeline.rb, app/helpers/application_helper/button/host_check_compliance.rb, app/helpers/application_helper/button/host_miq_request_new.rb, app/helpers/application_helper/button/host_performance.rb, app/helpers/application_helper/button/host_timeline.rb, app/helpers/application_helper/button/miq_action_delete.rb, app/helpers/application_helper/button/miq_action_edit.rb, app/helpers/application_helper/button/miq_alert_delete.rb, app/helpers/application_helper/button/miq_request_delete.rb
Same mistakes corrected again.
Related PR: https://github.com/ManageIQ/manageiq/pull/12416
/cc @martinpovolny
=> Fix incorrect localization in instance methods across button classes

app/controllers/application_controller/compare.rb
Oops, forgot to remove it in #434
=> Removed unused compared_squash from compare mixin

app/helpers/application_helper/button/vm_snapshot_add.rb, app/helpers/application_helper/button/vm_snapshot_revert.rb, spec/helpers/application_helper/buttons/vm_snapshot_add_spec.rb, spec/helpers/application_helper/buttons/vm_snapshot_revert_spec.rb
includes https://github.com/ManageIQ/manageiq-ui-classic/pull/437
needs https://github.com/ManageIQ/manageiq/pull/14014 to be merged
adjusts refactoring changes in PR ManageIQ/manageiq#13992
specs pass locally
=> Fix supports snapshots messages

app/helpers/cloud_tenant_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1422590
=> Removed duplicate security group listing in cloud tenant table

config/routes.rb, spec/routing/vm_infra_routing_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1410376
=> Add missing route

app/views/catalog/_st_angular_form.html.haml, app/views/layouts/angular/_ansible_form_options_angular.html.haml
Added live search to drop downs that are expected to have long list of values
https://www.pivotaltracker.com/story/show/140334553
screenshot:
@gmcculloug please review.
=> Added live search to drop downs

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
Fixed condition to only check for playbook type when adding/editing Catalog Items.
https://bugzilla.redhat.com/show_bug.cgi?id=1426486
=> Fixed condition.

app/helpers/application_helper/button/view_dashboard.rb, app/helpers/application_helper/toolbar/dashboard_summary_toggle_view.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/view_dashboard_spec.rb
| --- | --- |
| view_dashboard | ViewDashboard < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140577981
=> Toolbar refactoring #disable_button: ViewDashboard

app/views/layouts/_user_input_filter.html.haml
fixing https://bugzilla.redhat.com/show_bug.cgi?id=1421706
Fix error when creating filter in Networks -> Networks -> Advanced search
and choosing Field - Cloud Network: active (user will input the value).
The bug is in some more places and this commit fixes them all.
=> Fix error when creating filter in Networks page

app/views/layouts/_user_input_filter.html.haml
@h-kataria, reaction on https://github.com/ManageIQ/manageiq-ui-classic/issues/499#issuecomment-282818977
=> Corrected button label for submiting users input

app/helpers/application_helper/button/view.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/view_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
| Toolbar button ids | Toolbar button classes edited |
| --- | --- |
| view_grid, view_tile, view_list | View < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140577871
=> Toolbar refactoring #disable_button: gtl buttons

app/assets/stylesheets/container_providers_dashboard.scss
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1416185
=> Fix overlapping in Container Image summary screen

lib/report_formatter/html.rb
@miq-bot add_label technical debt, ui
Reading again and again and I still confused.
=> Remove comments, they are not that useful

app/controllers/mixins/generic_show_mixin.rb, app/controllers/resource_pool_controller.rb, spec/controllers/resource_pool_controller_spec.rb
This is recreated PR for new UI repo - original PR https://github.com/ManageIQ/manageiq/pull/13066
Also it contains changes according to previous review on original PR.
Part of Pivotal story: https://www.pivotaltracker.com/story/show/135050941
=> ResourcePool controller is using GenericShowMixin

spec/support/report_helper.rb
Move Report helper from Core to UI classic  repo.
Here I remove file from core repo:
https://github.com/ManageIQ/manageiq/pull/14133
=> Move Report helper to UI repo

app/views/layouts/listnav/_show_list.html.haml
introduced by #522, `.is_zero?` doesn't seem to exists, assuming it was meant to be `.zero?` 
Ping @martinpovolny ;)
=> app/views/layouts/listnav/_show_list.html.haml - fix is_zero? to zero?

app/helpers/application_helper/button/orchestration_stack_retire_now.rb, app/helpers/application_helper/toolbar/orchestration_stack_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/orchestration_stack_retire_now_spec.rb
| --- | --- |
| orchestration_stack_retire_now | OrchestrationStackRetireNow < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140768465
=> Toolbar refactoring #disable_button: OrchestrationStack

app/controllers/miq_ae_customization_controller/dialogs.rb, app/helpers/application_helper/dialogs.rb, app/views/miq_ae_customization/_dialog_field_form.html.haml, app/views/miq_ae_customization/_dialog_field_form_non_dynamic_options.html.haml, app/views/miq_ae_customization/_dialog_sample.html.haml, app/views/shared/dialogs/_dialog_field_drop_down_list.html.haml, spec/controllers/miq_ae_customization_controller/dialogs_spec.rb, spec/helpers/application_helper/dialogs_spec.rb
UI side of https://github.com/ManageIQ/manageiq/pull/10270
=> Multiselect

app/helpers/application_helper/button/collect_logs.rb, app/helpers/application_helper/button/diagnostics_logs.rb, app/helpers/application_helper/button/logs.rb, app/helpers/application_helper/button/restart_workers.rb, app/helpers/application_helper/toolbar/diagnostics_server_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/collect_logs_spec.rb, spec/helpers/application_helper/buttons/restart_workers_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
| --- | --- |
| restart_workers | RestartWorkers < RefreshWorkers |
| collect_logs, collect_current_logs | CollectLogs < DiagnosticsLogs |
**Toolbar button classes renamed:**
| From | To |
| --- | --- |
| CollectLogs | Logs |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140768365
=> Toolbar refactoring #disable_button: MiqServer

app/helpers/ems_infra_helper/textual_summary.rb
Remove unused methods, they are not listed for rendering,
when I list them, they break. So removing.
=> Remove unused methods

app/views/ems_container/ad_hoc/_list_view_form.html.haml
Fix caps in titles
**Screenshot**
=> Fix caps in titles

app/controllers/application_controller.rb, app/controllers/application_controller/performance.rb, app/controllers/application_controller/performance/options.rb, app/views/layouts/_perf_options.html.haml, spec/helpers/application_helper/buttons/template_refresh_spec.rb, spec/views/availability_zone/show.html.haml_spec.rb, spec/views/host/_show.html.haml_spec.rb
This is an ongoing effort, but can be merged any time as you see a fit.
The motivation was to understand the Performance mixin better, that way we may more easily identify dead codes in MiqReport and charts.
=> Cleanup in ApplicationController/Performance

lib/report_formatter/html.rb
Re-use existing method on MiqReport.
Depends on https://github.com/ManageIQ/manageiq/pull/14130
@miq-bot add_label refactoring, ui, reporting, euwe/no
=> Reuse build_html_col in the ui [2/2] 

lib/report_formatter/html.rb
Re-use. DRY.
@miq-bot add_label ui, technical debt, wip
=> Reuse build_group_html_rows in the ui [1/1]

app/controllers/ems_common.rb, app/controllers/mixins/generic_show_mixin.rb
One more step to unify the #show handling.
=> Replace EmsCommon #show with GenericShowMixin

spec/helpers/application_helper/buttons/container_timeline_spec.rb, spec/helpers/application_helper/buttons/vm_timeline_spec.rb, spec/support/examples_group/shared_examples_for_timeline_buttons.rb
@romanblanco could you review and approve these changes, please? It would make slimmer 2 or 3 of my `#disable_button` refactoring PRs.
=> Refactor shared examples for timeline buttons

app/helpers/application_helper/button/ap_delete.rb, app/helpers/application_helper/button/ap_edit.rb, app/helpers/application_helper/toolbar/scan_profile_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/ap_delete_spec.rb, spec/helpers/application_helper/buttons/ap_edit_spec.rb, spec/support/examples_group/shared_examples_for_analysis_profile_action_buttons.rb
| --- | --- |
| ap_delete | ApDelete < Basic |
| ap_edit | ApEdit < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140768547
Pending: https://github.com/ManageIQ/manageiq/pull/14125
=> Toolbar refactoring #disable_button: ScanItemSet

app/helpers/application_helper/button/rbac_tenant_delete.rb, app/helpers/application_helper/toolbar/tenant_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/rbac_tenant_delete_spec.rb
| --- | --- |
| rbac_tenant_delete | RbacTenantDelete < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140768753
=> Toolbar refactoring #disable_button: Tenant

app/helpers/application_helper/button/ems_storage_timeline.rb, app/helpers/application_helper/toolbar/ems_storage_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/ems_storage_timeline_spec.rb
| Toolbar button ids | Toolbar button classes assigned |
| --- | --- |
| ems_storage_monitoring_choice | EmsStorageTimeline < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140769467
=> Toolbar refactoring #disable_button: EmsStorageMonitoringChoice

app/helpers/application_helper/button/zone_collect_logs.rb, app/helpers/application_helper/button/zone_delete.rb, app/helpers/application_helper/toolbar/diagnostics_zone_center.rb, app/helpers/application_helper/toolbar/zone_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/zone_collect_logs_spec.rb, spec/helpers/application_helper/buttons/zone_delete_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
| --- | --- |
| zone_collect_logs, zone_collect_current_logs | ZoneCollectLogs < Basic |
| zone_delete | ZoneDelete < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140577955
=> Toolbar refactoring #disable_button: Zone

app/helpers/application_helper/button/storage_delete.rb, app/helpers/application_helper/button/storage_perf.rb, app/helpers/application_helper/button/storage_scan.rb, app/helpers/application_helper/toolbar/storage_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/storage_delete_spec.rb, spec/helpers/application_helper/buttons/storage_perf_spec.rb, spec/helpers/application_helper/buttons/storage_scan_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
| Toolbar button ids | Toolbar button classes created/assigned |
| --- | --- |
| storage_perf | StoragePerf < Basic |
| storage_delete | StorageDelete < Basic |
| storage_scan | GenericFeatureButtonWithDisable < GenericFeatureButton |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140768709
Pending: https://github.com/ManageIQ/manageiq/pull/14131
=> Toolbar refactoring #disable_button: Storage

app/helpers/application_helper/button/customization_template_new.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/ab_button_new_spec.rb, spec/helpers/application_helper/buttons/customization_template_new_spec.rb, spec/helpers/application_helper/buttons/widget_new_spec.rb, spec/support/examples_group/shared_examples_for_new_or_discover_button.rb
| Toolbar button ids | Toolbar button classes edited |
| --- | --- |
| customization_template_new | CustomizationTemplateNew < CustomizationTemplate |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140769075
=> Toolbar refactoring #disable_button: CustomizationTemplateNew

app/helpers/application_helper/button/vm_console.rb, app/helpers/application_helper/button/vm_vnc_console.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/vm_vnc_console_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb, spec/support/examples_group/shared_examples_for_vm_console.rb
| Toolbar button ids | Toolbar button classes edited |
| --- | --- |
| vm_vnc_console | VmVncConsole < VmConsole |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140578397
=> Toolbar refactoring #disable_button: VmVncConsole

app/helpers/application_helper/button/rbac_group_delete.rb, app/helpers/application_helper/button/rbac_group_edit.rb, app/helpers/application_helper/toolbar/miq_group_center.rb, app/helpers/application_helper/toolbar/miq_groups_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/rbac_group_delete_spec.rb, spec/helpers/application_helper/buttons/rbac_group_edit_spec.rb, spec/support/examples_group/shared_examples_for_rbac_group_buttons.rb
| --- | --- |
| rbac_group_edit | RbacGroupEdit < Basic |
| rbac_group_delete | RbacGroupDelete < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140768335
=> Toolbar refactoring #disable_button: MiqGroup

app/assets/images/svg/vendor-openshift_enterprise.svg, app/controllers/ems_common.rb, app/decorators/manageiq/providers/openshift_enterprise/container_manager_decorator.rb, app/services/ui_service_mixin.rb, spec/javascripts/fixtures/json/container_topology_response.json, spec/javascripts/fixtures/json/middleware_topology_response.json, spec/presenters/tree_node/ext_management_system_spec.rb, spec/services/container_dashboard_service_spec.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1425216
Completes https://github.com/ManageIQ/manageiq/pull/13908
@simon3z @zgalor 
@miq-bot add_label providers/containers
=> Remove the Openshift Container Platform(OpenshiftEnterprise) Provider

app/helpers/application_helper/button/db_new.rb, app/helpers/application_helper/toolbar/miq_widget_sets_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/db_new_spec.rb
| --- | --- |
| db_new | DbNew < ButtonNewDiscover |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140769273
=> Toolbar refactoring #disable_button: DbNew

app/helpers/application_helper/button/report_only.rb, app/helpers/application_helper/toolbar/saved_report_center.rb, app/helpers/application_helper/toolbar/saved_reports_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/report_only_spec.rb
| --- | --- |
| report_only | ReportOnly < RenderReport |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140769435
Pending: https://github.com/ManageIQ/manageiq/pull/14218
=> Toolbar refactoring #disable_button: MiqReportResult

app/helpers/application_helper/button/rbac_user_copy.rb, app/helpers/application_helper/button/rbac_user_delete.rb, app/helpers/application_helper/toolbar/user_center.rb, app/helpers/application_helper/toolbar_builder.rb, spec/helpers/application_helper/buttons/rbac_user_copy_spec.rb, spec/helpers/application_helper/buttons/rbac_user_delete_spec.rb
| --- | --- |
| rbac_user_copy | RbacUserCopy < Basic |
| rbac_user_delete | RbacUserDelete < Basic |
Pivotal Tracker: https://www.pivotaltracker.com/story/show/140768779
=> Toolbar refactoring #disable_button: User

app/views/layouts/_list_grid.html.haml
This change was missed in: https://github.com/ManageIQ/manageiq-ui-classic/pull/534
https://www.pivotaltracker.com/n/projects/1613907/stories/129462395
=> Replace custom “narrow” table class with “table-view-pf-select”

app/views/vm_common/_form.html.haml
:heart: QE :heart: wants an ID, :heart: QE :heart:  gets an ID
https://bugzilla.redhat.com/show_bug.cgi?id=1414480
=> Add an id for the child VM selection table to ease test automation

app/controllers/application_controller/performance.rb, app/controllers/application_controller/performance/options.rb
I've made a few small changes while debugging code in this area.
=> Making performance controller methods more readable

app/presenters/tree_builder_automate_simulation_results.rb
Removes a lot of duplicate code as we created a bunch of new decorators in #624 
@miq-bot add_label refactoring, euwe/no
=> Use decorators for automate simulation results nodes where possible

app/controllers/catalog_controller.rb
=> Fixed class names to get objects using EmbeddedAnsible tower.

app/assets/javascripts/miq_application.js
=> Remove unnecessary console.log from charts JS

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
Reset values in Remove Resources drop down when Repository drop down values is changed to none.
https://www.pivotaltracker.com/story/show/141238703
@dclarizio @gmcculloug @tinaafitz please review the label change and resetting of Remove resources drop down when user deselects Repository drop down value.
=> Label changes on Remove Resources drop down

config/routes.rb
CVE-2017-2653
https://bugzilla.redhat.com/1432174
=> Remove unused delete routes

app/controllers/ops_controller/settings/schedules.rb, spec/controllers/ops_controller/settings/schedules_spec.rb
Before (`Action` is shown as `Nothing selected` & Filter is incorrect)
After(`Action` is shown as `Container Image Compliance Check` & Filter/Filter value is shown correct)
https://bugzilla.redhat.com/show_bug.cgi?id=1402939
=> Fix filter values that are set for `container_image_check_compliance` action type

app/helpers/application_helper.rb
Issue was introduced in PR #638, conditions are correct, just the class should be in other branch
=> Corrected class for items with link in textual summary

app/controllers/service_controller.rb
@tinaafitz @gmcculloug please review.
before:
after:
=> Added Lifecycle box on Playbook Service summary screen

app/views/layouts/angular/_ansible_form_options_angular.html.haml
@gmcculloug please review
before:
after:
=> Changes to Credential drop down labels, from plural to singular

app/assets/images/svg/os-centos.svg
=> Fix Centos image dimensions

app/controllers/report_controller/reports/editor.rb
UI part of https://github.com/ManageIQ/manageiq/pull/14391
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1416220
@lpichler Please review
cc @simon3z
=> Add a 'Labels' prefix to custom attribute column in reports

app/controllers/mixins/custom_buttons.rb, app/presenters/custom_buttons_mixin.rb, app/presenters/tree_builder_buttons.rb, app/presenters/tree_builder_catalogs_class.rb
```ruby
[6] pry(#<TreeBuilderCatalogItems>)> (object[:set_data] && object[:set_data][:button_order])
=> [10000000000004]
[7] pry(#<TreeBuilderCatalogItems>)> !!(object[:set_data] && object[:set_data][:button_order])
=> true
[8] pry(#<TreeBuilderCatalogItems>)> !!(object[:set_data] && nil)
=> false
```
Also, the method name is not really clear to me, I'd change it to something more meaningfull, but not sure what it should be
=> Make method 'button_order?' return boolean

app/controllers/application_controller/filter.rb, app/controllers/application_controller/filter/subst_mixin.rb
It is only used in the controllers.
I want to get a rid of it slowly, but I need it in the ui repo first.
=> Move FilterSubstMixin from core to UI repo

app/assets/javascripts/controllers/live_metrics/ad_hoc_metrics_controller.js, app/assets/javascripts/controllers/live_metrics/util/metrics-http-factory.js, app/assets/javascripts/controllers/live_metrics/util/metrics-parse-url-factroy.js, app/assets/stylesheets/metrics.scss, app/services/hawkular_proxy_service.rb, app/views/ems_container/ad_hoc/_chart_view_form.html.haml, app/views/ems_container/ad_hoc/_list_view_form.html.haml, spec/javascripts/controllers/container_live_dashboard/container_live_dashboard_controller_spec.js
Compute > Containers > Providers - pick a provider - toolbar Monitoring > Ad hoc Metrics
Add pagination to the ad-hoc metrics list view
**Screenshot**
=> Add pagination to the ad-hoc page

app/views/shared/views/ems_common/angular/_form.html.haml
Simple text change.
https://bugzilla.redhat.com/show_bug.cgi?id=1431750
=> Update 'Project' to 'Project ID' when adding GCE Provider

app/controllers/ansible_credential_controller.rb, app/helpers/ansible_credential_helper/textual_summary.rb
=> Extended textual summary for ansible credentials

app/controllers/ansible_repository_controller.rb, app/helpers/ansible_repository_helper/textual_summary.rb
=> Extended options in Ansible Repository textual summary

app/views/compare.haml
#As I worked on https://github.com/ManageIQ/manageiq-ui-classic/pull/773 I noticed not working delete column, in web console saw error missing main_div there.
https://bugzilla.redhat.com/show_bug.cgi?id=1428946
=> Added missing main_div - fixed functions on hosts comparison

app/views/shared/dialogs/_dialog_field.html.haml
Just like it says on the tin. 
Depends on https://github.com/ManageIQ/manageiq/pull/14382
=> Fixes tag control multiselect

app/helpers/application_helper/button/cockpit_console.rb, app/helpers/application_helper/toolbar/container_node_center.rb, app/helpers/application_helper/toolbar/x_vm_center.rb, spec/helpers/application_helper/buttons/cockpit_console_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1420824
=> Enable Web Console button when VM power state is 'on'

app/helpers/automation_manager_helper.rb, app/helpers/ops_helper/textual_summary.rb, app/helpers/provider_foreman_helper.rb, app/helpers/textual_listview.rb, app/views/automation_manager/_configuration_script.html.haml, app/views/layouts/_textual_groups_raw.html.haml, app/views/ops/_rbac_tenant_details.html.haml, app/views/provider_foreman/_configuration_script.html.haml, app/views/shared/summary/_textual_listview.html.haml
Add one more textual summary formating option lost with recent textual summary refactoring.
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1432239
=> Db summary textual

app/controllers/vm_common.rb
By simplifying the logic of vm_common#tree_select we can remove a
dangerous variant of identify_record that relied on testing
@unauthorized for detection of RBAC denied access case.
=> Simplify logic of vm_common#tree_select removing identify_record.

app/controllers/catalog_controller.rb
Services -> Catalogs -> Catalog Items -> Select services in Catalog -> Remove Catalog Items
=> Check Catalog Items selected for deletion for RBAC

app/helpers/application_helper/button/cloud_network_new.rb, app/helpers/application_helper/toolbar/cloud_network_center.rb, app/helpers/application_helper/toolbar/cloud_networks_center.rb, spec/helpers/application_helper/buttons/cloud_network_new_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1403152
Depends on https://github.com/ManageIQ/manageiq/pull/14280
=> Disable cloud network buttons if no provider supports it

app/controllers/ansible_credential_controller.rb
Use id of the database record instead.
=> Don't use params[:id] directly

app/controllers/miq_task_controller.rb, app/controllers/mixins/generic_session_mixin.rb, app/controllers/ops_controller.rb
Removes duplicate sessions assignments between MiqTaskController and GenericSessionMixin
=> MiqTaskController: include GenericSessionMixin

config/routes.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1436721
=> Add missing openstack infra scaling routes

app/controllers/container_build_controller.rb, app/controllers/container_group_controller.rb, app/controllers/mixins/generic_show_mixin.rb
ping @simon3z, @h-kataria 
fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1429187
=> Container show fixes

app/controllers/application_controller/buttons.rb, app/controllers/catalog_controller.rb
As discussed in https://github.com/ManageIQ/manageiq-ui-classic/pull/817#issuecomment-290203066
=> Revert of PR #817

spec/presenters/tree_builder_protect_spec.rb
Fixes the broken master, introduced by: https://github.com/ManageIQ/manageiq/pull/14519
@isimluk :beers: 
=> Create valid MiqPolicy when testing TreeBuilderProtect

app/assets/javascripts/controllers/live_metrics/ad_hoc_metrics_controller.js, app/assets/javascripts/controllers/live_metrics/util/metrics-http-factory.js, app/assets/stylesheets/metrics.scss, app/views/ems_container/ad_hoc/_list_view_form.html.haml, spec/javascripts/fixtures/json/container_live_dashboard_metrics_response.json
Fix pagination spelling
_Empty pagination:_
_First page:_
_Forth page:_
=> Fix pagination spelling

app/controllers/application_controller/ci_processing.rb
@romanblanco , @PanSpagetka : please, review, test
=>  Add RBAC checking to process_elements.

app/controllers/application_controller.rb
Add `find_checked_records_with_rbac` function which return array of selected records
=> Add fetch_checked_items function

app/helpers/miq_ae_class_helper.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1437158
=> Add support for fixnum in ae_field_fonticon

spec/helpers/application_helper/buttons/host_introspect_provide_spec.rb, spec/helpers/application_helper/buttons/host_manageable_spec.rb
For the test examples it's not needed. Found when worked on https://github.com/ManageIQ/manageiq-ui-classic/pull/752
=> Removed unnecessary traits usage

spec/controllers/chargeback_controller_spec.rb
Fixes specs for https://github.com/ManageIQ/manageiq/pull/13960
Please merge BEFORE https://github.com/ManageIQ/manageiq/pull/13960
@miq-bot add_label refactoring, test, fine/no, euwe/no
=> specs: prepare for some chargeback_rate_detail db columns to disapear

app/controllers/application_controller/ci_processing.rb
only one line down, but less dense code
=> CiProcessing style fixes and small refactoring

app/assets/javascripts/controllers/provider_foreman/provider_foreman_form_controller.js, app/controllers/automation_manager_controller.rb, app/controllers/mixins/manager_controller_mixin.rb, app/controllers/provider_foreman_controller.rb, app/views/provider_foreman/_form.html.haml
Managers: Remove #model_to_name, use class method instead.
ping @mzazrivec, @lgalis
=> Deduplicate automation/foreman.

app/controllers/application_controller/compare.rb
Add RBAC check to actions in `compare.rb` controller.
=> Fix RBAC in compare

config/routes.rb
Added routes to download pdf on summary show page(s).
https://bugzilla.redhat.com/show_bug.cgi?id=1435101
=> Add missing routes for some Network resources

app/controllers/ops_controller/ops_rbac.rb
@martinpovolny ping, same case as in #907
=> Removed redundant test from 'params' presence in RBAC delete method

app/controllers/ops_controller/ops_rbac.rb
https://www.pivotaltracker.com/story/show/143054567
=> Added RBAC check to finding checked items in Ops RBAC controller

bin/setup, bin/update, tools/ci/before_install.sh
Update setup and update scripts to be consistent with the other plugin repos.
Backport PR for https://github.com/ManageIQ/manageiq-ui-classic/pull/858
=> [FINE] Fine update setup scripts

bin/setup, bin/update, tools/ci/before_install.sh
Update setup and update scripts to be consistent with the other plugin repos.
=> Update setup scripts

app/presenters/tree_builder_automation_manager_configured_systems.rb, app/presenters/tree_builder_configuration_manager_configured_systems.rb, app/presenters/tree_builder_configured_systems.rb
It seems like this code was copy-pasted without any additional refactoring.
=> Move the common code from ConfiguredSystems trees to a superclass

app/controllers/mixins/checked_id_mixin.rb, app/controllers/ops_controller/settings/ldap.rb
LdapDomain and LdapRegion don't participate in RBAC (yet).
Better safe than sorry.
https://www.pivotaltracker.com/story/show/143054567
=> Add RBAC check to LdapDomain and LdapRegion.

app/controllers/mixins/checked_id_mixin.rb
ping @mzazrivec, @romanblanco 
thx!
=> Fix misplaced and misaligned methods.

app/controllers/miq_request_controller.rb
Include session generic session mixin into miq request controller
=> MiqRequestController- use GenericSessionMixin

app/assets/javascripts/controllers/middleware_datasource/middleware_datasource_controller.js, app/assets/javascripts/controllers/middleware_datasource/middleware_datasource_service.js, app/assets/javascripts/controllers/middleware_server/middleware_server_controller.js
This is a follow-on PR to #876 that addresses the CodeClimate duplicate code warning messages.
It is a separate PR because it also touches more code than just fixing #876. This just makes it optional to take as we around code release time.
So #876 is a prerequisite for this PR.
=> Codeclimate dup Refactoring for JDBC Driver Defaults

app/views/miq_policy/_form_expression.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1435113
=> Changed text to flash message in Expression editor

app/controllers/mixins/chargeback_preview.rb
In cases where there are no metrics available -> notify user and build chargeback based on allocation.
This feels quite useful for fine/yes, (not sure if a bugzilla is needed)
=> Chargeback preview should fallback to just allocation data, when C&U N/A

app/helpers/application_helper/toolbar_chooser.rb
No point, and harder to search for..
Cc @martinpovolny
=> Don't use "#{@layout}_view_tb" when @layout is always container_project

app/controllers/provider_foreman_controller.rb
=> Fix RBAC for foreman

spec/controllers/ops_controller_spec.rb
Add specs for buttons. 
https://github.com/ManageIQ/manageiq-ui-classic/issues/988
=> Add specs for RBAC group add

app/assets/javascripts/controllers/ansible_credentials/ansible_credentials_form_controller.js
getCredentialFormData is called when the request for form data (edit) succeeds.
But, that function is using `vm.credential_options` which are filled only after the OPTION request succeeds.
Wait for the promise before touching `credential_options`.
Cc @mzazrivec
=> AnsibleCredentials - getCredentialFormData - wait for request before touching credential_options

app/controllers/ems_common.rb
This fix is needed when clicking on 'routers' from a relationships table
https://bugzilla.redhat.com/show_bug.cgi?id=1440166
=> fix network router config options

app/views/service/_service_form.html.haml
Services --> select a service --> click edit.
=> Remove duplicate flash_msg_div from service form.

bower.json, manageiq-ui-classic.gemspec
@NickLaMuro here you go :wink:
=> Update PatternFly to v3.23.1

locale/ManageIQ_UI_Classic.pot
The updated catalog contains fixes for some problems discovered by translators.
=> [FINE] Update gettext catalog for fine

app/controllers/ems_cluster_controller.rb, app/views/ems_cluster/show.html.haml, app/views/layouts/listnav/_ems_cluster.html.haml
Pivotal task: https://www.pivotaltracker.com/story/show/139465749
=> Refactor EmsClusterController#show to use GenericShowMixin

app/assets/javascripts/miq_tree.js, app/views/ops/_rbac_group_details.html.haml, app/views/ops/_rbac_role_details.html.haml, app/views/ops/_rbac_user_details.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1416363
=> Fix Group/Role name links on User Details page

app/decorators/service_template_ansible_tower_decorator.rb, app/decorators/service_template_catalog_decorator.rb, app/decorators/service_template_decorator.rb, spec/presenters/tree_node/service_template_catalog_spec.rb, spec/presenters/tree_node/service_template_spec.rb
**Before:**
**After:**
Closes #1026
https://bugzilla.redhat.com/show_bug.cgi?id=1439779
=> Set the catalog and item/bundle icons correctly

CHANGELOG.md
Updated.
Move items unreleased in Fine Beta to top.
[skip ci]
=> Changelog Fine Beta Release

app/presenters/tree_builder_report_roles.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1443502
=> Fix typo in Edit Report Menus tree

app/helpers/application_helper/title.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1441966
=> Fix title for embedded ansible playbooks

spec/controllers/pxe_controller_spec.rb
Added test to pxe_controller_spec.rb. Test request on tree_select action with root node. 
@himdel please review :)
=> Testing if tree select render the correct view

app/controllers/cloud_subnet_controller.rb
Add RBAC for deleting Cloud subnets
=> Add RBAC for deleting Cloud subnets

spec/helpers/report_helper/editor_spec.rb
/cc @gtanzillo @dclarizio 
Specs for https://github.com/ManageIQ/manageiq-ui-classic/pull/1077
=> Specs for ReportHelper#cb_entities_by_provider_id

app/controllers/service_controller.rb
=> Fix RBAC for Service Edit

app/controllers/cloud_volume_controller.rb
removing remnants I've found in PR https://github.com/ManageIQ/manageiq-ui-classic/pull/770
=> Removed authorization exception handling in Cloud Volume controller

app/helpers/configuration_job_helper/textual_summary.rb, app/views/automation_manager/explorer.html.haml, app/views/layouts/listnav/_configuration_job.html.haml, spec/helpers/configuration_job_helper/textual_summary_spec.rb
Fix links to parent provider from Job summary page
https://bugzilla.redhat.com/show_bug.cgi?id=1435280
=> Fix links to parent provider from Job summary page

app/helpers/service_helper/textual_summary.rb, spec/helpers/service_helper/textual_summary_spec.rb
This PR and https://github.com/ManageIQ/manageiq/pull/14834 are both required for this BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1435294
=> Fix textual provider svg and controller for ansible job

app/helpers/ansible_repository_helper/textual_summary.rb
@miq-bot add_label automation/ansible, fine/yes, euwe/no, enhancement
https://www.pivotaltracker.com/story/show/143133279
Before:
After (with dummy data):
@mzazrivec please review, thanks :)
=> Add status to Repository Properties

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
https://bugzilla.redhat.com/show_bug.cgi?id=1444831
@lgalis please test/review
=> Check whether form is pristine after deleting extra var during edit

app/controllers/mixins/containers_common_mixin.rb
Add RBAC for Containers Images Scan/Check compliance
=> Add RBAC for Containers Images Scan/Check compliance

app/services/git_repository_service.rb, spec/services/git_repository_service_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1445522
We should be using the :default authentication type
=> Incorrect authentication_type being used

app/controllers/availability_zone_controller.rb, app/views/availability_zone/show.html.haml
Pivotal task: https://www.pivotaltracker.com/story/show/143656403
=> Refactor AvailabilityZoneController#show to use GenericShowMixin

CHANGELOG.md
123 PRs
some not back ported and are listed in Sprint 59 section
[skip ci]
=> Changelog 59 Beta-2

app/assets/javascripts/controllers/security_group/security_group_form_controller.js, app/controllers/security_group_controller.rb, config/routes.rb
Uses REST API call instead of controller router/action
https://github.com/ManageIQ/manageiq-ui-classic/issues/737
=> Network provider: Security groups use API

app/assets/javascripts/controllers/ownership/ownership_form_controller.js, app/views/shared/views/_ownership.html.haml, spec/javascripts/controllers/ownership/ownership_form_controller_spec.js
Changed scopes to vm, repair broken tests
=> Changed scope to vm + tests

app/services/cloud_topology_service.rb, app/services/container_project_topology_service.rb, app/services/container_topology_service.rb, app/services/infra_topology_service.rb, app/services/middleware_topology_service.rb, app/services/network_topology_service.rb, app/services/physical_infra_topology_service.rb, app/services/topology_service.rb, spec/services/cloud_topology_service_spec.rb, spec/services/container_topology_service_spec.rb, spec/services/infra_topology_service_spec.rb, spec/services/middleware_topology_service_spec.rb, spec/services/network_topology_service_spec.rb, spec/services/topology_service_spec.rb
Refactoring a lot of things in a single step + adjusting styling + specs :wink: 
Pivotal story: https://www.pivotaltracker.com/story/show/143239019
=> Topology services refactoring: initialize, build_kinds, provider_class

app/controllers/host_controller.rb, app/controllers/mixins/generic_show_mixin.rb, app/views/host/_config.html.haml, app/views/host/show.html.haml
Pivotal task https://www.pivotaltracker.com/story/show/139383401
=> Refactor HostController#show to use GenericShowMixin

spec/support/view_helper.rb
`show_element` & `hide_element` are never used
`set_element_visibility` is only ever called from those 2
=> spec..view_helper - remove dead code

app/assets/javascripts/controllers/cloud_network/cloud_network_form_controller.js, app/controllers/cloud_network_controller.rb, config/routes.rb
Uses REST API call instead of controller router/action
https://github.com/ManageIQ/manageiq-ui-classic/issues/737
=> Network provider: Cloud networks use API

app/assets/javascripts/miq_tree.js, app/controllers/application_controller/miq_request_methods.rb, app/views/miq_request/_prov_field.html.haml, app/views/shared/views/_prov_dialog.html.haml
Pivotal story: https://www.pivotaltracker.com/story/show/123573971
Approved by @gmcculloug
=> Remove the unused ldap_ous_tree

app/assets/javascripts/controllers/cloud_tenant/cloud_tenant_form_controller.js, app/assets/javascripts/directives/checkchange.js, app/assets/javascripts/directives/form_changed.js, app/views/ansible_credential/_credential_form.html.haml, app/views/ansible_repository/_repository_form.html.haml, app/views/auth_key_pair_cloud/_form.html.haml, app/views/cloud_tenant/edit.html.haml, app/views/cloud_tenant/new.html.haml, app/views/configuration/_timeprofile_form.html.haml
Instead of checking individual inputs for change check whole form for changes. started on Ansible Credentials as example.
@miq-bot add_label wip, angular dialog, refactoring
=> Replace checkchange with form-changed

app/services/topology_service.rb
This is a more readable approach with less lines of code. Tested using `Benchmark.measure` got a slightly better performance when the DB records are cached.
Pivotal story: https://www.pivotaltracker.com/story/show/143239019
=> Rewrite the topology building algorithm to be non-recursive

app/controllers/orchestration_stack_controller.rb, app/helpers/application_helper.rb, app/views/layouts/listnav/_orchestration_stack.html.haml, app/views/orchestration_stack/show.html.haml, spec/helpers/application_helper_spec.rb, spec/views/layouts/listnav/_cloud_network.html.haml_spec.rb, spec/views/layouts/listnav/_cloud_subnet.html.haml_spec.rb, spec/views/layouts/listnav/_load_balancer.html.haml_spec.rb, spec/views/layouts/listnav/_network_router.html.haml_spec.rb, spec/views/layouts/listnav/_security_group.html.haml_spec.rb
Pivotal task: https://www.pivotaltracker.com/story/show/143667553
=> Refactoring OrchestrationStackController#show to use GenericShowMixin

app/helpers/service_helper/textual_summary.rb
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1444092
=> Show VMware credential in service provisioning summary

app/controllers/storage_manager_controller.rb
❗️ The `StorageManager` class is missing in `CLASSES_THAT_PARTICIPATE_IN_RBAC` list
_I'm still trying to find and test it in UI_ :
- described in https://github.com/ManageIQ/manageiq/pull/11626#issue-180373217)
- added in https://github.com/ManageIQ/manageiq/pull/11626/files#diff-287b57e549176adfc9c648a6be67c4a7R166
- removed in 
- https://github.com/ManageIQ/manageiq/commit/acf224afb3d4473f5271e8d87646506f02cf757b#diff-287b57e549176adfc9c648a6be67c4a7L145
- https://github.com/ManageIQ/manageiq/pull/12701
=> Added RBAC check for Storage Manager

app/assets/stylesheets/metrics.scss
Fix a layout regression to the Ad Hoc page.
Fix
Bug
=> Fix regressions in ad hoc page layout

app/views/ops/_ap_show.html.haml, app/views/ops/_aps_list.html.haml, app/views/ops/_schedule_show.html.haml, app/views/ops/_schedules_list.html.haml, app/views/ops/_settings_custom_logos_tab.html.haml
Similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/1065
Please, see individual commits.
=> Fix some duplicate DOM ids under ops.

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
Add RBAC check to actions in `application_controller.rb`
=> Add RBAC check for Application Controller

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js, spec/javascripts/controllers/catalog/catalog_item_form_controller_spec.js
https://bugzilla.redhat.com/show_bug.cgi?id=1447058
@bzwei please test.
=> send extra_vars & hosts values only when retirement playbook is selected

app/services/topology_service.rb
Conflict resolver PR for #1221
=> [FINE] Do not fail if the method is not defined on the topology graph

app/helpers/physical_server_helper/textual_summary.rb
This PR contains:
- Textual Summary for Physical Server
depends on #1162
=> Physical Server textual summary

app/presenters/tree_builder_report_saved_reports.rb
The page `/reports/explorer` uses many builders, but this PR is only focused on one.
`TreeBuilderSavedReports` is simple:
- The root nodes are `MiqReport` records that have results.
- The child nodes are `MiqReportResult` records.
**Note:** By definition, all root nodes will have children.
Trees need to know if they should display an "expand" wingding.
A `count(*)` was asked from each root node.
When asked, "Does this root node have children?" just answer `yes`.
That removes an N+1 (number of report nodes) queries.
The query to filter root nodes was moved from `MiqReport` to the builder, simplified, and then converted to a `pluck`.
|     ms |query | query ms |     rows |`comments`
|    ---:|  ---:|   ---:|      ---:| ---
|  636.1 |  148 | 354.1 |      565 |before
|  272.1 |   51 | 106.6 | …
=> TreeBuilderSavedReports reduce queries

app/controllers/application_controller/ci_processing.rb, app/controllers/mixins/explorer_show.rb
Further splitting ci_processing identifying overlap with `GenericShowMixin` to be addressed in future steps.
=> Cut out ci_processing that basically do that same as the generic_show_mixin

app/services/alerts_service.rb
=> Remove the obsolete AlertService as it has no references

app/controllers/application_controller/tags.rb
Reverts ManageIQ/manageiq-ui-classic#1034
It will be better to revert and redo the PR.
=> Revert "Added RBAC check for tag editing"

app/helpers/application_helper/toolbar/ems_containers_center.rb
=> Make add container provider button title consistent with the others

spec/controllers/ansible_playbook_controller_spec.rb
Basic tests for ansible playbook controller. 
=> Tests for ansible playbook controller

app/assets/javascripts/controllers/topology/cloud_topology_controller.js, app/assets/javascripts/controllers/topology/container_topology_controller.js, app/assets/javascripts/controllers/topology/infra_topology_controller.js, app/assets/javascripts/controllers/topology/middleware_topology_controller.js, app/assets/javascripts/controllers/topology/network_topology_controller.js, app/assets/javascripts/controllers/topology/physical_infra_topology_controller.js, app/assets/javascripts/services/topology_service.js
Pivotal story: https://www.pivotaltracker.com/story/show/143239019
=> Move the copy-pasted show_hide_names to the common topologyService

spec/controllers/ansible_repository_controller_spec.rb
=> Created tests for ansible_repository_controller

app/services/network_topology_service.rb
It's fixing GH Issue https://github.com/ManageIQ/manageiq-ui-classic/issues/1275
Fixes #1275
=> Fix error on network topology, when VM's power state is nil

app/views/cloud_object_store_container/new.html.haml, app/views/cloud_volume/_common_new_edit.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1448050
=> Fix angular ID selects

spec/controllers/ansible_credential_controller_spec.rb
Added test ansible_credential_controller_spec.rb.
=> Adding test for credentials

app/helpers/physical_server_helper.rb
This Pull Request adds Physical Server helper file and its refference to physical server textual summary.
=> Implements Physical Server Helper.

app/controllers/cloud_tenant_controller.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1448843
before
after
@lgalis please test/review
=> Fixed typo in flash message.

app/assets/javascripts/controllers/cloud_tenant/cloud_tenant_form_controller.js, app/views/cloud_tenant/edit.html.haml, app/views/cloud_tenant/new.html.haml, spec/javascripts/controllers/cloud/cloud_tenant_form_controller_spec.js
=> Controller as vm (Tenants models)

app/assets/javascripts/controllers/automation_manager/automation_manager_form_controller.js, app/views/automation_manager/_form.html.haml, spec/javascripts/controllers/automation_manager/automation_manager_form_controller_spec.js
=> AutomationManagerFormController as vm angular upgrade

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
https://bugzilla.redhat.com/show_bug.cgi?id=1449020
before
after
=> Fixed to also copy 'Escalate Privilege' when Copying provisioning tab

spec/services/topology_service_spec.rb
https://www.pivotaltracker.com/story/show/143239019
@miq-bot add_label test, fine/no
=> Add some new tests for the TopologyService

app/assets/javascripts/controllers/toolbar_controller.js, app/controllers/application_controller/automate.rb, app/controllers/application_controller/ci_processing.rb, app/controllers/configuration_controller.rb, app/controllers/infra_networking_controller.rb, app/controllers/miq_ae_class_controller.rb, app/controllers/miq_ae_customization_controller.rb, app/controllers/miq_capacity_controller.rb, app/controllers/miq_policy_controller/rsop.rb, app/controllers/miq_request_controller.rb, app/controllers/mixins/explorer_show.rb, app/controllers/ops_controller.rb, app/controllers/ops_controller/diagnostics.rb, app/controllers/orchestration_stack_controller.rb, app/controllers/vm_common.rb, app/helpers/application_helper.rb, app/helpers/application_helper/toolbar_builder.rb, app/helpers/application_helper/toolbar_chooser.rb, app/views/ops/explorer.html.haml, spec/controllers/ops_controller_spec.rb, spec/controllers/vm_common_spec.rb, spec/helpers/application_helper/toolbar_chooser_spec.rb, spec/helpers/application_helper_spec.rb
~depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/1237~
A detailed explanation is provided in the commit messages, please read.
=> Javascript toolbar reloads

app/controllers/service_controller.rb
Included GenericSessionMixin into the controller. Not many things were needed to be modified, so only lines which were duplicates with the mixin were modified.
=> ServiceController -> Added GenericSessionMixin include.

app/controllers/application_controller/tags.rb
=> Added RBAC check for tag editing

app/controllers/mixins/actions/vm_actions/retire.rb, spec/controllers/vm_infra_controller_spec.rb
Refactor retire little bit
ping @martinpovolny 
epic https://www.pivotaltracker.com/epic/show/3538165
=> Refactor retire little bit

app/controllers/cloud_volume_controller.rb, app/views/cloud_volume/show.html.haml
Add GenericShowMixin to CloudVolumeController.
How to test: Go to Storage -> Block -> Storage -> Volumes
https://www.pivotaltracker.com/story/show/141821929
=> Add GenericShowMixin to CloudVolumeController

app/assets/javascripts/controllers/retirement/retirement_form_controller.js, app/views/shared/views/_retire.html.haml, spec/javascripts/controllers/retirement/retirement_form_controller_spec.js
replacing scope with vm syntax in Retirement Form Ctrl and _retire.html
=> Replace scope with vm in RetirementFormCtrl

app/helpers/ems_cluster_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1451844
=> Fix ems cluster multilink

app/controllers/application_controller/explorer.rb, app/controllers/vm_infra_controller.rb, app/helpers/application_helper/button/transform_vm_button.rb, app/helpers/application_helper/toolbar/x_vm_center.rb, app/services/dialog_import_service.rb
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1404920
Depends on https://github.com/ManageIQ/manageiq-providers-ovirt/pull/21
=> Add Transform VM (v2v) Button

app/controllers/miq_ae_class_controller.rb
Delete useless lines in miq_ae_class_controller.rb, using GenericSessionMixin now.
=> miq_ae_class_controller.rb - use GenericSessionMixin

app/controllers/cloud_volume_controller.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1451788
=> fix incremental parameter processing

app/controllers/configuration_job_controller.rb
Add GenericShowMixin to Configuration Job controller.
Automation -> Ansible Tower -> Jobs
=> Add GenericShowMixin to Configuration Job controller

app/controllers/cloud_object_store_object_controller.rb
Add GenericShowMixin to CloudObjectStoreObjectController.
Storage -> ObjectStorage ->  Object Store Object
@romanblanco
=> Add GenericShowMixin to CloudObjectStoreObject

app/controllers/application_controller/ci_processing.rb, app/controllers/host_aggregate_controller.rb, app/controllers/infra_networking_controller.rb, app/controllers/mixins/explorer_show.rb, app/controllers/mixins/generic_show_mixin.rb, app/controllers/vm_common.rb
resolves part of https://github.com/ManageIQ/manageiq-ui-classic/issues/1242
=> Remove pagination handling code

app/controllers/mixins/explorer_show.rb
Cleanup the ExplorerShow mixin a bit.
=> Explorer show cleanup

lib/manageiq/ui/classic/engine.rb, manageiq-ui-classic.gemspec
@NickLaMuro @himdel does this make sense?
Uglifier is not really a concern of the core application.
=> Uglifier is a concern of the ui-classic repo, I think

app/helpers/application_helper.rb, config/routes.rb
=> Add quick search and Advanced search to Physical Servers

lib/manageiq-ui-classic.rb, lib/manageiq/ui/classic/engine.rb
@himdel please review (I didn't realize we had a central place for the requires...moving it to be consistent)
=> Centralize the engine requires to one place, engine.rb

lib/manageiq/ui/classic/engine.rb
Fixes a 'Uglifier' NameError in container builds.
Followup to #1415
=> We need uglifier in production

app/helpers/application_helper/toolbar/container_node_center.rb, app/helpers/application_helper/toolbar/x_vm_center.rb, app/helpers/application_helper/toolbar/x_vm_cloud_center.rb
VM before:
VM after:
Instance before:
Instance after:
Container Node before:
Container Node after:
@miq-bot add_labels bug, compute/infrastructure, compute/cloud, compute/containers
https://bugzilla.redhat.com/show_bug.cgi?id=1441321
=> Rename 'Web Console' to 'Cockpit Console'

app/controllers/vm_common.rb
fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/1421
=> Remove forgotton javascript to show toolbar.

app/controllers/mixins/ems_common_angular.rb
discussed in https://github.com/ManageIQ/manageiq-ui-classic/pull/1205#issuecomment-300594747
=> Remove provider id

app/assets/stylesheets/metrics.scss
In https://github.com/ManageIQ/manageiq-ui-classic/pull/1364 I introduced a regression in filter menu.
This PR fixes the dropdown menu cut-off.
Bug
Fix
=> Fix filter menu dropdown cutoff

app/controllers/application_controller.rb, app/controllers/miq_request_controller.rb, app/helpers/application_helper/page_layouts.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1450002
- Add pagination
- All buttons on pagination bar work
- No pagination bar for single request page (TODO)
Before:
After:
@miq_bot add_label bug, GTLs, wip
=> Add pagination to Service -> Requests

app/helpers/network_router_helper/textual_summary.rb, app/helpers/textual_mixins/textual_ems_network.rb
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1448452
=> Fix missing translations in network router summary

.github/PULL_REQUEST_TEMPLATE.md
waiting for https://github.com/ManageIQ/guides/pull/210
=> Added reference to reviewers guidelines to the Pull Request template

app/assets/stylesheets/main.scss
Depends on: https://github.com/ManageIQ/manageiq/pull/15254
@miq-bot add_label pending core, enhancement, graphics
@miq-bot assign @epwinchell
=> Introducing the font-fabulous gem

app/assets/javascripts/controllers/ops/tenant_quota_form_controller.js, app/views/ops/_tenant_quota_form.html.haml, spec/javascripts/controllers/ops/tenant_quota_form_controller_spec.js
Refactor Tenant_quota controller and form to use controllerAs
Links
https://www.pivotaltracker.com/n/projects/1613907/stories/143026023
=> Tenant_quota controller and form to use controllerAs

app/controllers/storage_controller.rb, app/views/storage/show.html.haml
Modify Storage Controller to use GenericShowMixin.
Compute -> Infrastructure -> Datastore
=> Storage controller GenericShowMixin

locale/fr/ManageIQ_UI_Classic.po
There were some fixes in French translation for fine.
=> [FINE] Update French translation for fine

app/controllers/ops_controller/ops_rbac.rb, spec/controllers/ops_controller/ops_rbac_spec.rb
Fix reset button action for tenant tagging
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1442679
=> Fix reset button action for tenant tagging

app/services/container_dashboard_service.rb, spec/services/container_dashboard_service_spec.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1439671
Depends on https://github.com/ManageIQ/manageiq/pull/14857
In Containers dashboard, Node heatmaps should have one square per node for all time intervals including realtime: 
before:
=> Containers Dashboard: Show one square per node in realtime heatmaps

app/controllers/host_aggregate_controller.rb, app/views/host_aggregate/show.html.haml
Marking the PR as WIP - need data to fully test the changes
Pivotal task: https://www.pivotaltracker.com/story/show/144091687
=> Refactoring HostAggregateCtrl#show to use GenericShowMixin

product/views/PhysicalServer.yaml
=> Add format to physical server report

product/views/PhysicalServer.yaml
=> Add more columns to display Physical Server details

spec/services/infra_topology_service_spec.rb
Fixed broken spec test on Fine caused by backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/1404
Code has been refactored on master so it wasn't an issue on master.
cc @simaishi
=> [FINE] - Fixed broken spec test

app/assets/javascripts/controllers/reconfigure/reconfigure_form_controller.js, app/views/vm_common/_reconfigure.html.haml, spec/javascripts/controllers/reconfigure/reconfigure_form_controller_spec.js
Refactor Vm reconfigure form and controller to use ControllerAs
Links
https://www.pivotaltracker.com/story/show/143025941
=> Refactor Vm reconfigure form and controller to use ControllerAs

app/assets/javascripts/controllers/ops/tenant_form_controller.js, app/views/ops/_tenant_form.html.haml, spec/javascripts/controllers/ops/tenant_form_controller_spec.js
Refactor Tenant form and controller to use ControllerAs
Links
https://www.pivotaltracker.com/story/show/143025999
=> Refactor Tenant form and controller to use ControllerAs

app/assets/javascripts/controllers/orchestration_template/orchestration_template_copy_controller.js, app/views/orchestration_stack/_copy_orchestration_template.html.haml, spec/javascripts/controllers/orchestration_template/orchestration_template_copy_controller_spec.js
Refactor the orchestration template copy controller and form to use controlleras
Links 
----------
https://www.pivotaltracker.com/story/show/143025897
=> Refactor the orchestration template copy controller and form to use controlleras

app/controllers/host_controller.rb, app/controllers/mixins/ems_common_angular.rb
Provider / Host edit: if we're starting the edit from the list, we should also redirect to the list
after save. If we're starting the edit from summary screen, we should also redirect to
the summary screen.
https://bugzilla.redhat.com/show_bug.cgi?id=1458433
=> Fix incorrect redirection after provider / host edit

app/helpers/ems_cinder_helper/textual_summary.rb, app/helpers/ems_cloud_helper/textual_summary.rb, app/helpers/ems_container_helper/textual_summary.rb, app/helpers/ems_datawarehouse_helper/textual_summary.rb, app/helpers/ems_infra_helper/textual_summary.rb, app/helpers/ems_middleware_helper/textual_summary.rb, app/helpers/ems_network_helper/textual_summary.rb, app/helpers/ems_physical_infra_helper/textual_summary.rb, app/helpers/ems_storage_helper/textual_summary.rb, app/helpers/ems_swift_helper/textual_summary.rb, app/helpers/textual_mixins/textual_refresh_status.rb
Before:
After:
https://bugzilla.redhat.com/show_bug.cgi?id=1452391
=> Show last refresh time & date in provider summary screen

app/controllers/ops_controller/rbac_tree.rb
Permissions may be not be displayed as “checked” because they are stored as “everything under” features which might not have a corresponding node in the tree.
This change
* Checks Menu::Items for when their feature parent is checked.
* Consolidates the counting of children
I intended to use `post_check` from #1057 but doing so caused JS errors. I don't believe it would have a significant impact on code or performance, so it's not currently in this change.
**Addresses Fine BZs like these**
https://bugzilla.redhat.com/show_bug.cgi?id=1442796
https://bugzilla.redhat.com/show_bug.cgi?id=1442719
https://bugzilla.redhat.com/show_bug.cgi?id=1411831
https://bugzilla.redhat.com/show_bug.cgi?id=1348623
=> [FINE] Fix node selection in RBAC Tree

app/assets/javascripts/controllers/security_group/security_group_form_controller.js, app/views/security_group/_common_new_edit.html.haml, app/views/security_group/edit.html.haml, app/views/security_group/new.html.haml
Refactor network security groups using this instead of $scope.
Also makes the fields options more consistent.
=> Network security groups refactor with this

app/controllers/mixins/actions/vm_actions/reconfigure.rb, app/controllers/mixins/actions/vm_actions/right_size.rb, spec/controllers/vm_infra_controller_spec.rb
Refactor `reconfigure` mixin 
Compute -> Infra -> VM
=> Reconfigure mixin refactor

spec/controllers/middleware_server_controller_spec.rb, spec/controllers/middleware_server_group_controller_spec.rb
Fix specs currently failing in master. 
@himdel @martinpovolny
=> Fix feed set to empty string

app/controllers/application_controller/policy_support.rb, app/controllers/mixins/actions/vm_actions/policy_simulation.rb
=> Policy mixin refactor

app/presenters/menu/default_menu.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1461162
before:
after:
=> Fixed parameters being passed in to rbac features check.

app/assets/javascripts/controllers/security_group/security_group_form_controller.js, app/controllers/security_group_controller.rb, app/views/security_group/_common_new_edit.html.haml, app/views/security_group/_fw_rules.haml, app/views/security_group/edit.html.haml, app/views/security_group/new.html.haml, spec/controllers/security_group_controller_spec.rb
=> CRUD for security group rules 

app/controllers/miq_ae_class_controller.rb
Fix RBAC in automate controller
https://www.pivotaltracker.com/story/show/143312753
Automation -> Automate -> Explorer
EDIT: Automate classes are not supported by RBAC, so this PR could be useful once we add them to RBAC.
=> Fix RBAC in automate controller

app/controllers/application_controller/buttons.rb, app/views/shared/buttons/_ab_form.html.haml, app/views/shared/buttons/_ab_show.html.haml
add UI for https://github.com/ManageIQ/manageiq/pull/14930
follow up for https://github.com/ManageIQ/manageiq-ui-classic/pull/796
=> Custom button submit all

app/controllers/mixins/actions/vm_actions/right_size.rb, app/controllers/vm_common.rb, spec/controllers/ems_infra_controller_spec.rb, spec/controllers/vm_or_template_controller_spec.rb
Add RBAC check for Right Size Recommendation.
I guess this should be backported too.
=> Add RBAC check for Right Size Recommendation

app/controllers/mixins/actions/vm_actions/live_migrate.rb
Change RBAC in live migrate, use recommended method to check RBAC.
=> Change RBAC in live migrate

app/assets/stylesheets/main.scss
Merge together with: https://github.com/ManageIQ/font-fabulous/pull/30
@miq-bot add_label graphics, fine/no
@miq-bot assign @epwinchell
=> Load font-fabulous the same way as patternfly-sass is loaded

app/helpers/application_helper.rb, app/helpers/quadicon_helper.rb
Move db_for_quadicon to QuadiconHelper, it's only user.
=> Move db_for_quadicon to QuadiconHelper, it's only user.

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js, app/controllers/cloud_volume_controller.rb, app/views/cloud_volume/backup_new.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1403797
=> add force option to cloud volume create form

app/controllers/mixins/actions/vm_actions/evacuate.rb, spec/controllers/vm_cloud_controller_spec.rb
=> Evacuate refactor

app/assets/javascripts/controllers/cloud_subnet/cloud_subnet_form_controller.js, app/controllers/cloud_subnet_controller.rb, app/views/cloud_subnet/new.html.haml
Uses REST API call instead of controller router/actions
https://github.com/ManageIQ/manageiq-ui-classic/issues/737
=> Network provider: Cloud subnets use API

app/assets/javascripts/remote_consoles/vnc.js
@miq-bot add_labels bug, compute/infrastructure, blocker
https://bugzilla.redhat.com/show_bug.cgi?id=1464152
=> Fix VNC console connection to Windows VMs and Ctrl-Alt-Del button

app/views/layouts/_user_input_filter.html.haml, spec/views/layouts/_user_input_filter.html.haml_spec.rb
Use a dropdown for a boolean user input field in Advanced Search
https://bugzilla.redhat.com/show_bug.cgi?id=1429532
=> Use a dropdown for a boolean user input field in Advanced Search

app/controllers/mixins/actions/vm_actions/disassociate_floating_ip.rb
Disassociate Floating IP refactoring
Compute -> Cloud -> Instances -> select Instance -> Configuration -> Disassociate Floating IP
=> Disassociate Floating IP refactoring

bower.json
https://github.com/ManageIQ/ui-components/issues/81
https://github.com/ManageIQ/ui-components/pull/83
=> Load ui-components from its bower-dev branch

app/controllers/application_controller/buttons.rb
=> Fixed issue with custom button editing

app/assets/javascripts/controllers/service/service_form_controller.js, app/views/service/_service_form.html.haml, spec/javascripts/controllers/service/service_form_controller_spec.js
Services > My Services .. toolbar Configuration > Edit Selected Service
Refactoring to controller as vm
=> Service form controller as

app/controllers/miq_request_controller.rb, spec/controllers/miq_request_controller_spec.rb
When replication set-up we may have 2 users with the same userid in global region: one created manually and other created by replication. Requests created in global region for remote user have remote user's id in requester_id column.
**Issue**:
Requests created in global region for remote user were visible for user in remote region but not visible in Global region.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1464610
**Solution**:
Allow all users who have the same userid as one assign to request to see this request
@miq-bot add-label bug, blocker, requests, fine/yes
\cc @gtanzillo @dclarizio @h-kataria 
PR with screenshots of manual testing on `fine` branch: https://github.com/ManageIQ/manageiq-ui-classic/pull/1710
=> Make request visible to all users who have the same userid as requester

app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb
Associate Floating IP refactoring
Select some Openstack Instance -> Associate Floating IP
=> Associate Floating IP refactoring

app/views/chargeback/_cb_rate_show.html.haml
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/1079
@lpichler @gtanzillo @isimluk Please review
=> UI Fix for ChargeableField in chargeback editor

app/presenters/tree_builder.rb
Pivotal story: https://www.pivotaltracker.com/story/show/149153823
@miq-bot add_label trees, refactoring, fine/no
@miq-bot assign @ZitaNemeckova
=> Rename the TreeNode `isLazy` attribute to `lazyLoad` for all nodes

app/controllers/floating_ip_controller.rb
Allows only providers supporting create/update features using SupportFeatureMixin
Adds GenericFormMixin
=> Filter actions using 

app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js
Renders info about iops and encrypted attributes for cloud volume when editing.
=> Render iops and encrypted for cloud volume edit form

app/helpers/application_helper/dialogs.rb, spec/helpers/application_helper/dialogs_spec.rb
Convert dropdown value to string before split for display value
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1470068
=> Convert dropdown value to string before split for display value

app/assets/javascripts/controllers/ansible_repository/repository_form_controller.js, spec/javascripts/controllers/ansible_repository/ansible_repository_form_controller_spec.js
Add js specs to Ansible Repository Form.
@miq-bot add_label test, angular dialogs
@miq-bot remove_label wip
=> Add js tests for ansible_repository_form

app/controllers/application_controller/ci_processing.rb, app/controllers/cloud_volume_controller.rb, app/controllers/mixins/generic_button_mixin.rb
A step in cleaning up the button actions. Extracting methods, generalizing, trying to find some reusable parts and patterns.
=> Button actions cleanup

app/views/layouts/remote_console.html.haml
@miq-bot add_labels compute/infrastructure, compute/cloud, fine/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1454912
=> Fix full screen button for Firefox in remote consoles

app/controllers/mixins/manager_controller_mixin.rb, spec/controllers/provider_foreman_controller_spec.rb
Save verify flag for foreman provider
Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1452201
=> Save verify flag for foreman provider

app/decorators/generic_object_definition_decorator.rb
=> fonticon and fileicon for Generic Object Definition records

app/helpers/application_helper.rb
Allows setting listnav partial directly from a controller:
```
class DemoController < ApplicationController                                                        
....
def listnav_filename                                                                              
'demo'                                                                                          
end    
...
end
```
=> Allow listnav_filename to be directly set by a controller.

app/controllers/application_controller/filter.rb, config/routes.rb
Small cleanups to the expression editor.
=> Expression editor cleanups.

app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
After creating a new dialog, the new box will be already there
=> Create a box in new dialog automatically

app/controllers/cloud_network_controller.rb
a fine version of https://github.com/ManageIQ/manageiq-ui-classic/pull/1474
cc @simaishi 
cc @martinpovolny @himdel 
@miq-bot add_label fine/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1463422
=> [FINE] Use matching descendants for cloud networks fine

app/assets/javascripts/controllers/live_metrics/ad_hoc_metrics_controller.js, app/assets/javascripts/controllers/live_metrics/util/metrics-http-factory.js, app/assets/javascripts/controllers/live_metrics/util/metrics-utils-factory.js, app/assets/stylesheets/metrics.scss, app/views/ems_container/ad_hoc/_chart_view_form.html.haml, spec/javascripts/controllers/container_live_dashboard/container_live_dashboard_controller_spec.js
a. Back-port of #1367 to fine
b. Back-port of #1447 to fine
c. Fix css regressions created by partial backporting
Replaces: https://github.com/ManageIQ/manageiq-ui-classic/pull/1571
=> [FINE] Fix units bug and add differential

app/helpers/textual_mixins/vm_common.rb, app/helpers/vm_cloud_helper/textual_summary.rb, app/helpers/vm_helper/textual_summary.rb
* Extract 2 helper methods.
* Share duplicit code.
=> Deduplicate vm textual summary

app/controllers/application_controller.rb, app/controllers/application_controller/advanced_search.rb, app/controllers/vm_common.rb, app/helpers/application_helper.rb, spec/controllers/application_controller/report_data_spec.rb
Fixes and follow up work for https://github.com/ManageIQ/manageiq-ui-classic/pull/1823
@h-kataria , @lpichler
=> Advanced search button cleanup step 2.

lib/report_formatter/timeline.rb, spec/lib/report_formater/timeline_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1475782
=> Fixed code to only set data/headers if column exists in Report col headers.

app/controllers/catalog_controller.rb, app/helpers/quadicon_helper.rb, app/views/layouts/_tag_edit_items.html.haml
Change method to load  also data from associated resources. The bug appears only on fine/euwe branches, not in master, as there is used angular/gtl
https://bugzilla.redhat.com/show_bug.cgi?id=1439650
=> [FINE] Change 'list' to 'grid icon' for Catalog Item Tagging screen

app/assets/javascripts/miq_application.js
https://bugzilla.redhat.com/show_bug.cgi?id=1474096
=> Make tooltip precision for CU chart constistent with Y axis labels

spec/controllers/miq_ae_class_controller_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1477037
Fixes spec test failure on Fine caused by backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/1814
@dclarizio please review/merge
cc @simaishi
=> Fixes spec test failure on Fine branch.

app/views/miq_ae_class/_method_inputs.html.haml
Save, Reset and Cancel actions for Automation Method Edit page.
https://bugzilla.redhat.com/show_bug.cgi?id=1478113
Screen shots prior to fix:
===========================
Screen shots post fix:
=> Delete duplicate flash message for Automation Method Edit page actions

app/helpers/application_helper/toolbar_builder.rb
@miq-bot assign  @martinpovolny
=> Get available CustomButtons with visible_for_current_user for toolbars

app/assets/javascripts/controllers/cloud_network/cloud_network_form_controller.js, app/views/cloud_network/_common_new_edit.html.haml, app/views/cloud_network/edit.html.haml, app/views/cloud_network/new.html.haml
Refactor cloud network to use `this` instead of `$scope`.
=> Cloud Network: Javascript not using  $scope

app/assets/javascripts/remote_consoles/spice.js
Removing IE10 specific file since IE10 support is being dropped.
=> Remove IE10 specific Spice file

app/controllers/mixins/actions/host_actions/discover.rb, app/helpers/application_helper/discover.rb, app/views/ems_physical_infra/discover.html.haml
This Pull Request adds the port input to MiQ UI and set enqueue to Lenovo Provider discover feature.
Depends on https://github.com/ManageIQ/manageiq/pull/15681
=> Change discover to make lenovo provider discovery

app/assets/javascripts/controllers/ansible_repository/repository_form_controller.js
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/1230 which is fine/yes.
@miq-bot add_label fine/yes, bug
Automation -> Ansible -> Repositories -> Try to edit any repo
Before: `{"error":{"kind":"bad_request","message":"Invalid attributes specified: scm_branch:","klass":"Api::BadRequestError"}}`
After: It works.
@himdel please have a look :)
=> Remove extra :

app/assets/javascripts/miq_tree.js
=> Add additional escaping when building node check/click URLs

app/assets/javascripts/controllers/automation_manager/automation_manager_form_controller.js, app/assets/javascripts/controllers/provider_foreman/provider_foreman_form_controller.js, app/assets/javascripts/directives/validation/reset_validation_status.js, app/assets/javascripts/directives/validation/validation_status.js, app/assets/javascripts/services/configuration_manager_service/configuration_manager_service.js, app/assets/javascripts/services/miq_service.js, app/controllers/application_controller.rb, app/controllers/automation_manager_controller.rb, app/controllers/mixins/ems_common_angular.rb, app/controllers/mixins/generic_form_mixin.rb, app/controllers/mixins/manager_controller_mixin.rb, app/controllers/provider_foreman_controller.rb, app/views/automation_manager/_form.html.haml, app/views/layouts/angular-bootstrap/_auth_credentials_angular_bootstrap.html.haml, app/views/layouts/angular/_form_buttons_verify_angular.html.haml, app/views/provider_foreman/_form.html.haml, spec/controllers/automation_manager_controller_spec.rb, spec/controllers/provider_foreman_controller_spec.rb, spec/javascripts/controllers/automation_manager/automation_manager_form_controller_spec.js, spec/javascripts/controllers/provider_foreman/provider_foreman_form_controller_spec.js, spec/javascripts/directives/validation/validation_status_spec.js, spec/views/host/_form.html.haml_spec.rb
Changes to mandate validation for Ansible and Foreman Providers prior to a Save operation
https://bugzilla.redhat.com/show_bug.cgi?id=1475292
=> Add Validation as a requirement prior to a Save for Ansible and Foreman Providers

CHANGELOG.md
Updating changelog for sprint 67
=> Update for sprint 67

app/assets/javascripts/components/widget-chart.js, app/controllers/dashboard_controller.rb, app/views/dashboard/_widget.html.haml, app/views/dashboard/_widget_chart.html.haml, config/routes.rb
@miq-bot add_label wip, dashboards, fine/no
https://www.pivotaltracker.com/story/show/147760695
Cloud Intel -> Dashboard -> widget with chart
Before/After: Behavior and graphics will be same.
=> Add widget-chart component and method to get data

app/controllers/application_controller/filter.rb
Just split some large methods into more smaller ones.
=> Advanced search, expression editor: split some methods.

CHANGELOG.md
Added Fine-3 and Fine-2 sections
Removed released PRs from unreleased items.
[skip ci]
=> Changelog Fine-3 and Fine-2 Rollups

app/assets/javascripts/controllers/alerts/alerts_list_controller.js, app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js, app/assets/javascripts/controllers/cloud_volume/cloud_volume_form_controller.js, app/assets/javascripts/controllers/container_dashboard/container_dashboard_controller.js
Fixes some of the top "F" from here:
https://codeclimate.com/github/ManageIQ/manageiq-ui-classic/code?q=rating%3AF
=> Fix some javascript linter issues and undeclared variables.

app/assets/javascripts/controllers/ems_infra_dashboard/util/infra-charts-mixin.js, app/assets/javascripts/miq_application.js, app/assets/javascripts/miq_global.js
Fixes some of the top "F" from here:
https://codeclimate.com/github/ManageIQ/manageiq-ui-classic/code?q=rating%3AF
=> Fix some javascript linter issues.

app/controllers/application_controller.rb, app/controllers/application_controller/session_size.rb, app/controllers/mixins/controller_constants.rb
* extract session size related code to a mixin
* deduplicate a bit
* cleanup style a bit
=> Extract session size related code to a mixin

app/controllers/application_controller/compare.rb, app/controllers/configuration_job_controller.rb, app/controllers/ems_cluster_controller.rb, app/controllers/ems_common.rb, app/controllers/orchestration_stack_controller.rb, app/controllers/storage_controller.rb, app/controllers/storage_controller/storage_d.rb, app/controllers/storage_controller/storage_pod.rb
One more step to unify the button handling code.
=> Deduplicate using check_if_button_is_implemented.

app/assets/javascripts/miq_browser_detect.js
just that
@ZitaNemeckova, @skateman, @romanblanco : review, please?
=> Fix style issues in miq_browser_detect.js.

app/assets/javascripts/controllers/container_dashboard/util/charts-mixin.js, app/assets/javascripts/controllers/container_deployment/wizard/wizard-step-directive.js, app/assets/javascripts/miq_c3_config.js, app/assets/javascripts/miq_explorer.js
Just that.
ping @ZitaNemeckova, @romanblanco, @skateman
=> Fix javascript styling issues.

app/controllers/report_controller/widgets.rb, app/helpers/ui_constants.rb
Remove useless comments e.g. code in comment.
=> Remove useless comments

app/assets/javascripts/miq_tree.js, app/assets/javascripts/services/alerts_center_service.js, app/assets/javascripts/services/catalog/catalog_item_data.js, app/assets/javascripts/services/configuration_manager_service/configuration_manager_service.js, app/assets/javascripts/services/event_notifications_service.js, app/assets/javascripts/services/miq_db_backup_service.js, app/assets/javascripts/services/miq_service.js, app/assets/javascripts/services/post_service.js, app/assets/javascripts/services/timer_option_service.js, app/assets/javascripts/services/topology_service.js
Run linter on some js files to fix some linter errors
=> fix linting errors

app/assets/javascripts/controllers/report_data_controller.js, app/assets/stylesheets/patternfly_overrides.scss, app/views/layouts/_center_div_no_listnav.html.haml, app/views/layouts/_center_div_with_listnav.html.haml, app/views/layouts/_content.html.haml
Classic UI-specific styling updates to accompany new responsive pagination in UI-Components
Depends on: https://github.com/ManageIQ/ui-components/pull/103
https://www.pivotaltracker.com/n/projects/1613907/stories/146518283
=> Styling updates to accompany new pagination

app/controllers/application_controller.rb
just that
ping @mzazrivec, @h-kataria
=> ApplicationController: style cleanups.

app/controllers/storage_controller.rb
Just style fixes.
Ping @mzazrivec, @h-kataria
=> StorageController: style fixes.

app/helpers/application_helper/toolbar/diagnostics_region_center.rb, app/helpers/application_helper/toolbar/diagnostics_zone_center.rb, app/helpers/application_helper/toolbar/server_mixin.rb
Deduplicate definition of 2 toolbars by extracting a method.
=> Toolbars: extract method server_role_string_proc.

app/controllers/miq_policy_controller/alert_profiles.rb
* extract methods
* simplify flash messages
* fix Rubocop issues
=> Alert Profile edit: style fixes and refactoring

app/helpers/ems_infra_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1394799
=> Add link to network manager for infra providers

app/helpers/quadicon_helper.rb
* simplify and hash creation
* deduplicate by extracting a method
ping @mzazrivec, @h-kataria
=> Quadicon helper style fixes

app/helpers/application_helper/button/transform_vm_button.rb
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1473180
=> v2v: Disable VM transform button when op not possible

app/assets/javascripts/controllers/toolbar_controller.js
Minor style fixes.
Review, please, @skateman, @ZitaNemeckova  ?
=> ToolbarController style fixes.

app/helpers/application_helper.rb
3 simple style fixes
ping @mzazrivec, @h-kataria, @skateman
=> Application helper minor style

app/controllers/infra_networking_controller.rb, app/controllers/mixins/find_record.rb, app/controllers/mixins/manager_controller_mixin.rb, app/controllers/storage_controller.rb
Just that.
ping @mzazrivec, @h-kataria
=> Extract find_record into a mixin. Deduplicate.

app/controllers/planning_controller.rb, app/controllers/vm_common.rb
=> Some more style fixes

app/assets/javascripts/controllers/report_data_controller.js, app/assets/javascripts/controllers/toolbar_controller.js
just fix a typo
ping @himdel, @karelhala
=> Toolbars: fix a typo.

app/services/container_project_dashboard_service.rb, app/views/container_project/show.html.haml
I missed this after testing the code refactor of the backend service in https://github.com/ManageIQ/manageiq-ui-classic/pull/1527
@himdel  Please review
cc @simon3z
=> fix container projects dashboard metrics and container view

app/controllers/network_router_controller.rb
One quick style fixing pass through the file. It would benefit from more love.
* cleanup flash messages
* `simplify get_networks_by_ems` and `get_subnets_by_network`
* `find_by_*` replacement
* spaces and formatting
ping @gildub, @sseago
=> Network Router controller: style fixes.

app/presenters/menu/default_menu.rb
Being discussed in https://github.com/ManageIQ/manageiq/pull/14976
=> Take monitoring out of prototype

app/views/report/_form_expression_buttons.html.haml, app/views/report/_form_filter.html.haml
=> Report filter form deduplication

app/controllers/ops_controller/ops_rbac.rb
=> Ops RBAC style

app/controllers/ops_controller/ops_rbac.rb
Small refactoring of `rbac_edit_save_or_add `method for proper
setting the record variables using the result of validation.
This small refactoring is related to https://github.com/ManageIQ/manageiq-ui-classic/pull/1752
but it does not depend on it.
=> Small refactoring of rbac_edit_save_or_add method

app/controllers/application_controller.rb, app/controllers/application_controller/buttons.rb, app/controllers/catalog_controller.rb, app/controllers/cloud_volume_controller.rb, app/controllers/pxe_controller/pxe_servers.rb, app/controllers/report_controller/widgets.rb, app/helpers/params_helper.rb
Trying to simplify `param` processing by extracting a method to handle the most common case.
=> Extract method copy_params_if_set to simplify param processing.

spec/lib/report_formater/c3_formatter_spec.rb
Verifying fix in https://github.com/ManageIQ/manageiq-ui-classic/pull/2070
https://bugzilla.redhat.com/show_bug.cgi?id=1487397
@martinpovolny please review/merge
=> Spec test to verify correct labels are set

app/controllers/miq_ae_class_controller.rb
* remove find_by_* calls
* cleanup button up/down handling
=> MiqAeClassController cleanup and refactoring

app/assets/javascripts/controllers/cloud_volume_backup/cloud_volume_backup_form_controller.js, app/controllers/cloud_volume_backup_controller.rb, app/helpers/application_helper/toolbar/cloud_volume_backup_center.rb, app/helpers/application_helper/toolbar/cloud_volume_backups_center.rb, app/views/cloud_volume_backup/volume_select.html.haml, config/routes.rb
UI for cloud volume restore and delete actions.
=> UI for cloud volume backup restore, delete

app/views/layouts/_tag_edit_cat_tags.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1488004
Old
New
=> Add live search to value dropdown on tag edit screen

app/helpers/application_helper/toolbar/basic.rb, app/helpers/application_helper/toolbar/miq_ae_method_center.rb, app/helpers/application_helper/toolbar/miq_ae_methods_center.rb, app/helpers/application_helper/toolbar/vm_clouds_center.rb, app/helpers/application_helper/toolbar/vm_infras_center.rb, app/helpers/application_helper/toolbar/vms_center.rb
Simplify toolbar definition if title and text are the same.
Plus a couple of toolbars updated as an example of usage.
=> Toolbar same text title

app/assets/javascripts/controllers/topology/container_topology_controller.js, app/views/container_topology/show.html.haml, spec/javascripts/controllers/containers/container_topology_controller_spec.js
Continuing with refactoring remaining topology controllers (as in [#1898](https://github.com/ManageIQ/manageiq-ui-classic/pull/1898))
=> Refactoring container topology as vm

app/assets/javascripts/controllers/topology/physical_infra_topology_controller.js, app/views/physical_infra_topology/show.html.haml
Continuing with refactoring remaining topology controllers (as in [#1898](https://github.com/ManageIQ/manageiq-ui-classic/pull/1898))
=> Refactoring physical infra topology controller as vm

app/views/report/_form_styling.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1486714
Old
New
=> Fix table cell issue on report styling tab

app/assets/javascripts/controllers/topology/infra_topology_controller.js, app/views/infra_topology/show.html.haml, spec/javascripts/controllers/infra/infra_topology_controller_spec.js
Continuing with refactoring remaining topology controllers (as in [#1898](https://github.com/ManageIQ/manageiq-ui-classic/pull/1898))
=> Refactoring infra topology controller as vm

app/views/miq_policy/_condition_details.html.haml, app/views/miq_policy/_form_expression.html.haml, app/views/miq_policy/_form_scope.html.haml
This PR standardizes all items into the form-horizontal layout and relabels items for clarity.
Relates to: https://github.com/ManageIQ/manageiq-ui-classic/pull/1939
Old
New
=> Restyle Condition Edit Screen

app/controllers/container_node_controller.rb, app/services/container_dashboard_service.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1460401
Depends on: https://github.com/ManageIQ/manageiq/pull/15351 - Merged
Related issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/1526
=> Hide Archived Container Nodes

app/assets/javascripts/controllers/container_dashboard/container_dashboard_controller.js, app/assets/javascripts/controllers/container_dashboard/container_project_dashboard_controller.js, app/assets/javascripts/controllers/ems_infra_dashboard/ems_infra_dashboard_controller.js, app/assets/javascripts/services/dashboard_service.js
Followup to https://github.com/ManageIQ/manageiq-ui-classic/pull/1527#issuecomment-325646698
@himdel @h-kataria  Please review.
=> Refactor data fetching from angular dashboard controllers

app/presenters/tree_builder_service_catalog.rb, spec/presenters/tree_builder_service_catalog_spec.rb
#Links 
https://bugzilla.redhat.com/show_bug.cgi?id=1488141
Before:
After:
=> Fix display for catalog items in service catalog tree

app/views/miq_policy/_action_details.html.haml
Before:
After:
Links
* https://github.com/ManageIQ/manageiq/issues/8502
Control -> Actions -> Select an action
@epwinchell please review
=> Removed fieldset tags in Policy Actions template

app/controllers/application_controller.rb
=> report_data: move some exceptions to a common place.

app/views/catalog/_ot_tree_show.html.haml
Catalogs -> Orchestration Templates -> [ot]
=> Fix duplicate main_div element in orchestration template details screen

app/views/ops/_diagnostics_workers_tab.html.haml
Configuration -> Diagnostics -> Server -> Workers tab
=> Fix duplicate main_div elements in server diagnostics workers tab

app/views/ops/_diagnostics_server_list_tab.html.haml
Configuration -> Diagnostics -> Zone -> Server  tab
=> Fix duplicate main_div elements in zone diagnostics server tab

app/controllers/application_controller/buttons.rb, app/controllers/catalog_controller.rb, app/controllers/report_controller/menus.rb
change ifs to case, remove unnecessary methods
=> Style fixes for button up/down/left/right/.. code.

app/controllers/application_controller/ci_processing.rb
=> Replace find_by_* calls in ci_processing.

bin/update
(Same issue as we saw over in https://github.com/ManageIQ/manageiq-api/pull/54)
=> Update plugins in bin/update

CHANGELOG.md
=>  Sprint 69 changelog update

app/views/catalog/_form_resources_info.html.haml, app/views/catalog/_sandt_tree_show.html.haml, app/views/chargeback/_cb_assignments.html.haml, app/views/miq_ae_customization/_field_value_entry.html.haml, app/views/ops/_ap_form_file.html.haml, app/views/ops/_ap_form_nteventlog.html.haml, app/views/ops/_ap_form_registry.html.haml, app/views/ops/_classification_entry.html.haml, app/views/ops/_ldap_server_entry.html.haml, app/views/ops/_settings_co_categories_tab.html.haml, app/views/ops/_settings_label_tag_mapping_tab.html.haml
Configuration -> Analysis Profile -> Select a profile -> Edit
=> Fix duplicated element ids on analysis profile edit page

app/controllers/application_controller/buttons.rb, spec/controllers/application_controller/buttons_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1486718
after fix:
@lgalis please test/review.
=> Added condition to check for blank? before calling strip method.

app/assets/javascripts/controllers/middleware_server/middleware_server_controller.js
In JDR reports table avoid "Unexpected Error" when the delete button is clicked multiple times.
Fixes https://github.com/ManageIQ/manageiq-providers-hawkular/issues/56
=> Disable delete button when clicked

spec/controllers/generic_object_controller_spec.rb
Add a generic object definition for the show_list spec
=> Fix failing spec for the generic object show_list 

app/controllers/miq_policy_controller/alert_profiles.rb, spec/controllers/miq_policy_controller/alert_profiles_spec.rb
* Add a specs for a regression introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/2026
* Fix the regression 
ping @israel-hdez, @mzazrivec 
Thx!
=> Fix a typo in alert profiles deletion

app/assets/javascripts/components/generic_object/generic-object-definition-component.js, app/assets/javascripts/components/generic_object/generic-object-table-component.js, app/controllers/generic_object_definition_controller.rb, app/helpers/application_helper/button/generic_object_definition.rb, app/helpers/application_helper/toolbar/generic_object_definition_center.rb, app/helpers/application_helper/toolbar/generic_object_definitions_center.rb, app/views/generic_object_definition/_generic_object_definition_form.html.haml, app/views/generic_object_definition/edit.html.haml, app/views/generic_object_definition/new.html.haml, app/views/static/generic_object/generic_object_definition.html.haml, app/views/static/generic_object/generic_object_table.html.haml, config/routes.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
The C-R-U for Generic Object Definitions UI.
Depends on the API PR: https://github.com/ManageIQ/manageiq-api/pull/42
=> Generic Object Definitions UI - CRU

app/controllers/application_controller.rb, app/controllers/application_controller/performance.rb, app/controllers/report_controller/dashboards.rb
=> Replace some find_by_* calls.

app/helpers/storage_helper/textual_summary.rb, spec/helpers/storage_helper/textual_summary_spec.rb
=> Extract method textual_format_used_space.

spec/controllers/cloud_network_controller_spec.rb, spec/controllers/cloud_subnet_controller_spec.rb, spec/controllers/floating_ip_controller_spec.rb, spec/controllers/network_router_controller_spec.rb, spec/controllers/ops_controller_spec.rb, spec/controllers/security_group_controller_spec.rb, spec/presenters/tree_node/hash_spec.rb, spec/shared/controllers/shared_examples_for_ems_network_controller.rb
These create a lot of noise in the test report, so I've fixed one that was broken and removed some others that go back to before 2017.
=> Either fix or remove pending specs

spec/controllers/application_controller/ci_processing_spec.rb
Spec test to support changes in https://github.com/ManageIQ/manageiq/pull/16111
https://bugzilla.redhat.com/show_bug.cgi?id=1497113
@dclarizio please review, this can be merged after https://github.com/ManageIQ/manageiq/pull/16111
=> Spec test to verify delete button in initiated for selected objects

spec/controllers/ems_infra_controller_spec.rb
Fix broken tests
Caused by ManageIQ/manageiq#15929 and
ManageIQ/manageiq-providers-ovirt#90
=> Fix broken tests

app/views/shared/views/_retire.html.haml
There's already a %div.form-group one level above
=> Remove extraneous %div.form-group from _retire.haml

spec/controllers/orchestration_stack_controller_spec.rb
Reenable two tests that were skipped in #2279
=> Fix build failure due to orchestration template rename - round 2

app/controllers/middleware_server_controller.rb, spec/controllers/middleware_server_controller_spec.rb
Fixes https://github.com/ManageIQ/manageiq-providers-hawkular/issues/58
=> Fix downloading of already removed JDR report

app/controllers/miq_ae_class_controller.rb
@syncrou @tinaafitz please review/test
=> Fixed code to allow saving playbook method without inputs

app/controllers/ops_controller/ops_rbac.rb
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/2322
=> Fix flash messages for new user creation w/o selected group.

app/helpers/application_helper/toolbar/physical_server_center.rb, app/helpers/application_helper/toolbar/physical_servers_center.rb
Adds configuration buttons to the physical server list and physical server show pages.
=> Adds configuration buttons to physical server toolbar

app/presenters/tree_builder_buttons.rb
Rename:
Pod > Container Pod
Projet> Container Project
Switch> Virtual Infra Switch
Changes requested in https://github.com/ManageIQ/manageiq-ui-classic/pull/1912
After:
@miq-bot add_label enhancement, euwe/no, automation/automate
=> Rename nodes in TreeBuilderButtons

.github/CODEOWNERS
=> Adding topology services to the CODEOWNERS file

app/controllers/application_controller/miq_request_methods.rb, app/controllers/miq_request_controller.rb, app/helpers/application_helper/page_layouts.rb
Somehow this did not get fixed in 
https://github.com/ManageIQ/manageiq-ui-classic/pull/1915
althought I'd swear it did work :-(
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1479385
@h-kataria: please, review, test.
=> Request menu item highlight fixes

app/controllers/ops_controller/db.rb
=> OPS controller, databases: minor style fixes.

app/controllers/miq_policy_controller/policies.rb
Please, review the commits one by one.
* split and cleanup the method
* fix double flash
https://bugzilla.redhat.com/show_bug.cgi?id=1501153
=> Policy edit: fix double flash.

app/controllers/application_controller/miq_request_methods.rb
Use the session not URL params to pass flash message through a redirect.
https://bugzilla.redhat.com/show_bug.cgi?id=1475303
=> Provisioning: Use session to pass flash message.

app/controllers/mixins/actions/host_actions/misc.rb, spec/controllers/application_controller/ci_processing_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1502531
@martinpovolny please review.
=> Fixed to pass in parameter to method call

app/controllers/miq_ae_class_controller.rb, app/views/miq_ae_class/_method_form.html.haml, app/views/miq_ae_class/_method_inputs.html.haml
Issue #2423
@gmcculloug please review/test
before:
after:
=> Made Embedded Method option only available for Inline type methods

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js
https://bugzilla.redhat.com/show_bug.cgi?id=1503438
=> Added call to turn spinner off after Copying Provisioning fields.

CHANGELOG.md
=> Updates for Sprint 71

manageiq-ui-classic.gemspec
For https://github.com/ManageIQ/manageiq/issues/15036
=> Allow Rails 5.1

app/assets/javascripts/components/verify-button.js
=> Remove trailing comma syntax error

app/controllers/mixins/actions/vm_actions/ownership.rb, app/controllers/service_controller.rb
1. My Services screen, select a service from the list
2. Configuration -> Set Ownership
https://bugzilla.redhat.com/show_bug.cgi?id=1498241
=> My Services: correctly render flash array

spec/controllers/dashboard_controller_spec.rb
to go together with https://github.com/ManageIQ/manageiq/pull/16273
=> Rename feature containers to container to match changes in core.

app/controllers/vm_common.rb
When you have two providers added say one cloud and one infra and when you try edit a infra vm, the parent vm and child selection drop down list all the cloud provider vm's also.
Vice versa while editing cloud instance too.
Expected results:
Only vm's related to respected provider should be displayed.
@lpichler I see you are the last person to edit that code. In https://github.com/ManageIQ/manageiq-ui-classic/pull/927
Do you know if it makes sense to restrict it like that?
Otoh, the [original code](https://github.com/ManageIQ/manageiq-ui-classic/blame/6a51ce6e5747e082525c7ce42dfed8594845c934/app/controllers/vm_common.rb#L1410) is super old - so maybe there was only Vmware back then...
@dclarizio any idea who could review that from a use case perspective? Should we restrict it that way? …
=> only display VmOrTemplate as choice for relationships that belong to the same provider

app/controllers/mixins/ems_common_angular.rb, spec/controllers/ems_cloud_controller_spec.rb
Dependent on https://github.com/ManageIQ/manageiq-providers-ovirt/pull/87
This PR is a follow-up to #1580 and validates infra provider credentials on the queue.
@miq-bot add_label wip, compute/infrastructure, bug
=> Validate infra providers on the queue

app/controllers/mixins/actions/vm_actions/resize.rb, app/views/miq_request/_reconfigure_show.html.haml, spec/controllers/miq_request_controller_spec.rb, spec/controllers/vm_cloud_controller_spec.rb, spec/helpers/application_helper/buttons/miq_request_approval_spec.rb, spec/helpers/application_helper/buttons/miq_request_copy_spec.rb, spec/helpers/application_helper/buttons/miq_request_edit_spec.rb
Depends on core PR https://github.com/ManageIQ/manageiq/pull/16044
=> Use approval workflow for instance resize operation

app/controllers/ems_cloud_controller.rb, app/views/ems_cloud/sync_users.html.haml, spec/controllers/ems_cloud_controller_spec.rb
new_users calls the OpenStack API and shouldn't be
invoked from the UI.
=> Remove call to new_users

app/helpers/application_helper/toolbar/service/vmdb_mixin.rb, app/helpers/application_helper/toolbar/service_center.rb
@Loicavenel As requested in https://github.com/ManageIQ/manageiq-ui-classic/pull/1669
=> Fix remove service toolbar text

app/controllers/configuration_controller.rb, app/helpers/application_helper/title.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1505470
Closes https://github.com/ManageIQ/manageiq-ui-classic/pull/2510
=> Fix title / tooltip for "My Settings" screen (consistency)

app/assets/javascripts/controllers/report_data_controller.js, app/controllers/application_controller.rb, app/controllers/application_controller/ci_processing.rb, app/controllers/application_controller/report_data_additional_options.rb, app/controllers/mixins/generic_show_mixin.rb, app/controllers/ops_controller/ops_rbac.rb, app/controllers/provider_foreman_controller.rb, app/helpers/application_helper.rb, app/views/layouts/angular/_gtl.html.haml, app/views/miq_policy/_action_list.html.haml, app/views/miq_policy/_alert_list.html.haml, app/views/miq_policy/_policy_list.html.haml, app/views/report/_report_saved_reports.html.haml, app/views/report/_savedreports_list.html.haml, app/views/report/_schedule_list.html.haml, app/views/report/_widget_list.html.haml, spec/controllers/application_controller/report_data_spec.rb, spec/controllers/automation_manager_controller_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/ems_cloud_controller_spec.rb, spec/controllers/infra_network_controller_spec.rb, spec/controllers/miq_request_controller_spec.rb, spec/controllers/ops_controller/ops_rbac_spec.rb, spec/controllers/orchestration_stack_controller_spec.rb, spec/controllers/provider_foreman_controller_spec.rb, spec/controllers/report_controller_spec.rb, spec/controllers/storage_controller_spec.rb, spec/controllers/vm_or_template_controller_spec.rb, spec/support/controller_helper.rb
Taking over https://github.com/ManageIQ/manageiq-ui-classic/pull/2335
=> GTL: pass options through preventing double call to reporting backend

app/javascript/packs/application-common.js
I assume this should not be part of a release :-)
=> removes Hello World from Webpacker log message.

app/assets/javascripts/controllers/report_data_controller.js
After clicking on server inside configuration -> diagnostics -> zone -> Servers (tab) -> clicking on server will select correct server in tree.
https://bugzilla.redhat.com/show_bug.cgi?id=1502594
=> Use showURL with id of tree for servers

spec/controllers/miq_request_controller_spec.rb
Otherwise the test fails every time a new subclass is created
=> Update spec to use constant it is testing instead of an array of strings

app/assets/javascripts/miq_qe.js
QE team asked about improving report data JS API with couple of new functions
1) (stores) `sendDataWithRx({controller: 'reportDataController', action: 'query', data: [{name: 'someName'}]})` - will query over all items with specific filter. Can return multiple values
2) (stores) `sendDataWithRx({controller: 'reportDataController', action: 'pagination_range'})` - will store information about current page. Object will look like:
```javascript
{
start: 1,
end: 20,
total: 139,
pageCount: 10
}
```
When filtering over items, fetching all items each record will now have `gtlType` property of type string to show which type of GTL (grid, tile or list) is used.
Simplest query can look like this: `sendDataWithRx({controller: 'reportDataController', action: 'query', data: [{name: 'someName'}]})` which …
=> Improve report data JS API with two new functions and add info about GTL type

app/controllers/application_controller/ci_processing.rb, app/controllers/vm_common.rb, spec/controllers/ems_infra_controller_spec.rb, spec/controllers/vm_or_template_controller_spec.rb
=> [FINE] Add RBAC to Right Size recommendation

app/views/miq_ae_class/_inputs.html.haml, app/views/miq_ae_class/_method_form.html.haml
Fixes #2535
https://bugzilla.redhat.com/show_bug.cgi?id=1508643
before fix:
after fix:
@mkanoor please test
=> Fixed visibility of Input Params div on non-ansible method form.

app/controllers/host_controller.rb
Depends on https://github.com/ManageIQ/manageiq/pull/16347
=> Move net-ssh dependency to manageiq-gems-pending

app/views/service/_svcs_show.html.haml
=> Move GTL below bootstrapping sanitizeRender

app/controllers/middleware_server_controller.rb, app/helpers/application_helper/toolbar/middleware_server_center.rb, app/helpers/application_helper/toolbar/middleware_servers_center.rb, app/helpers/middleware_server_helper.rb, app/views/middleware_server/show.html.haml, config/routes.rb
* adds new section inside server detail with compliance check history
* enables to run compliance test for MW server
* adds new screen with compliance history
=> Enable compliance check for MW server 

app/views/miq_ae_class/_angular_method_form.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1508915
@mkanoor @tinaafitz please review.
before:
after:
=> Make Display Name not required to be consistent with non-ansible forms

.rspec, .rspec_ci, spec/controllers/generic_object_definition_controller_spec.rb, spec/spec_helper.rb
Leverage what is already in manageiq's spec_helper
=> Updates to spec_helper

app/controllers/vm_cloud_controller.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1461164
=> Fix variable interpolation in volume attach/detach messages

.github/CODEOWNERS
=> Codeowners: adding martinpovolny for some files.

app/views/miq_request/_prov_dialog_volume_fieldset.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1509950
Old
New
=>  Provision instance volume tab styling fix

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
- Simplify existence checks (`!something.nil?`)
- Prefer to `return` early
- Remove unnecessary assignment to variable
- Add tests for this method
=> Simplify ApplicationHelper#model_to_report_data

app/controllers/application_controller.rb, app/helpers/application_helper.rb, spec/controllers/application_controller/report_data_spec.rb, spec/controllers/application_controller_spec.rb
This method looked like a good candidate for simplification, also added some tests for it
=> Cleanup ApplicationController#process_params_model_view

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js, app/views/layouts/angular/_ansible_form_options_angular.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1509353
@tinaafitz can you please test/verify this fix.
before:
after:
=> Fixed a JS method call in view, and added uniq key validation check.

app/assets/javascripts/controllers/ops/log_collection_form_controller.js, app/views/ops/_log_collection.html.haml, spec/javascripts/controllers/ops/log_collection_form_controller_spec.js
user > Configuration .. Diagnositcs accord .. click on a Zone, tab Collect Logs, toolbar Edit
Refactoring controller as vm
I am currently waiting for #2063
=> logCollectionFormController AS vm

app/assets/stylesheets/patternfly_overrides.scss, app/views/layouts/_x_dialog_buttons.html.haml, app/views/layouts/_x_edit_buttons.html.haml, app/views/layouts/_x_form_buttons.html.haml, app/views/layouts/angular/_paging_div_buttons.html.haml, app/views/vm_common/_right_size.html.haml
Reverts ManageIQ/manageiq-ui-classic#2618
Reverting this PR to fix missing form buttons on several forms.
https://bugzilla.redhat.com/show_bug.cgi?id=1511340
https://bugzilla.redhat.com/show_bug.cgi?id=1510911
https://bugzilla.redhat.com/show_bug.cgi?id=1511192
https://bugzilla.redhat.com/show_bug.cgi?id=1511188
https://bugzilla.redhat.com/show_bug.cgi?id=1510650
https://bugzilla.redhat.com/show_bug.cgi?id=1511325
https://bugzilla.redhat.com/show_bug.cgi?id=1511542
=> Revert "form button styling clean up"

.travis.yml
- Current appliance Ruby version is 2.3.1
- Current dev supported version is 2.4.2
=> Adjust Travis Rubies

app/helpers/application_helper/page_layouts.rb
There is an error loading the new provider page.
=> Fix error in new provider page

CHANGELOG.md
=> [Changelog] Fix url for PR

app/controllers/catalog_controller.rb
Fix a crash in Services --> Catalogs  -->  Catalog Items --> Unassigned
https://bugzilla.redhat.com/show_bug.cgi?id=1509159
https://bugzilla.redhat.com/show_bug.cgi?id=1512114
Depends on core: https://github.com/ManageIQ/manageiq/pull/16445
=> Catalog unassigned

app/assets/javascripts/controllers/catalog/catalog_item_form_controller.js, app/assets/javascripts/controllers/playbook-reusable-code-mixin.js, app/views/catalog/_st_angular_form.html.haml
- Fixed code to initialize Catalog Drop down properly when Item was initially in the Unassinged folder.
- Also fixed code to be able to move Catalog Item to Unassigned folder during edit.
https://bugzilla.redhat.com/show_bug.cgi?id=1511875
=> Fixed Catalog drop-down issues.

app/helpers/application_helper/button/cockpit_console.rb
Added a ? that was mistakenly removed. 
@miq-bot add_labels bug
https://bugzilla.redhat.com/show_bug.cgi?id=1512754
=> [FINE] Fix travis

app/controllers/cloud_volume_snapshot_controller.rb
Fix based_volumes sublist
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1496930
=> [FINE] Fix based_volumes sublist

app/assets/stylesheets/topology.css
Styling fix for Topology legend in IE11+
https://bugzilla.redhat.com/show_bug.cgi?id=1458929
Old
New
=> [FINE] Topology legend fix for IE 11+

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
Spec test to verify fix in https://github.com/ManageIQ/manageiq-ui-classic/pull/2790
https://bugzilla.redhat.com/show_bug.cgi?id=1514593
=> Spec test to verify a fix in PR 2790

app/controllers/application_controller.rb, app/controllers/application_controller/ci_processing.rb, app/controllers/application_controller/filter.rb, app/controllers/ems_common.rb, app/controllers/miq_ae_tools_controller.rb, app/controllers/miq_policy_controller.rb, app/controllers/miq_task_controller.rb, app/controllers/mixins/actions/host_actions/misc.rb, app/controllers/ops_controller/diagnostics.rb, app/controllers/ops_controller/settings/common.rb, app/controllers/ops_controller/settings/upload.rb, app/controllers/vm_common.rb, app/helpers/application_helper.rb, app/helpers/application_helper/title.rb, app/presenters/tree_builder_ops_diagnostics.rb, app/presenters/tree_builder_ops_rbac.rb, app/presenters/tree_builder_ops_settings.rb, app/presenters/tree_builder_utilization.rb, app/services/user_validation_service.rb, app/views/layouts/_x_edit_buttons.html.haml, app/views/layouts/application.html.haml, app/views/layouts/remote_console.html.haml, app/views/ops/_all_tabs.html.haml, app/views/ops/rhn/_server_table.html.haml, app/views/vm_common/console_webmks.html.haml, spec/controllers/application_controller/ci_processing_spec.rb, spec/controllers/ops_controller/diagnostics_spec.rb, spec/controllers/vm_infra_controller_spec.rb, spec/helpers/application_helper/title_spec.rb
Since PR https://github.com/ManageIQ/manageiq/pull/16409
we now have a method for product name.
=> Use VMDB::Appliance.PRODUCT_NAME not i18n method.

app/services/user_validation_service.rb
Adding some documentation to user_validation_service to prevent further confusion 😢 
cc @himdel @cben
=> Adding some documentation to user_validation_service

bower.json
Update ui-components to 1.0.1 in Gaprindashvili.
Cc @romanblanco
=> [GAPRINDASHVILI] Update manageiq-ui-components to 1.0.1

app/assets/javascripts/components/generic_object/main-custom-button-group-form-component.js
Add the `group_index` value to new Button Group records
~Requires https://github.com/ManageIQ/manageiq-api/pull/210~
https://bugzilla.redhat.com/show_bug.cgi?id=1512979
=> Add `group_index` to new Button Group records

spec/controllers/auth_key_pair_cloud_controller_spec.rb
I heard some rumors that @martinpovolny will pay for my :beers: if I write enough tests :wink:
=> Add spec for checking lastaction in the AuthKeyPairController 🌭

app/assets/javascripts/controllers/ems_common/ems_common_form_controller.js, app/controllers/mixins/ems_common_angular.rb, app/helpers/textual_summary_helper.rb, app/views/layouts/angular/_multi_auth_credentials.html.haml
Conflict-resolving cherry pick from https://github.com/ManageIQ/manageiq-ui-classic/pull/2587
@himdel you helped me in upstream with some magic to make the VMRC tab optional. Can you do the same here? :wink: 
(cherry picked from commit 10a58852d8707785f5ea11c63daaa50bd6e72962)
=> [FINE] Add a new tab for separate VMRC console credentials for vmware infra

app/controllers/miq_policy_controller/alerts.rb, spec/controllers/miq_policy_controller/alerts_spec.rb
Control -> Explorer -> Alerts -> Select an Alert -> Edit the selected Alert -> Cancel the edit
Currently, an error occurs. With the fix, the error should go away.
https://bugzilla.redhat.com/show_bug.cgi?id=1518225
=> Fix placeholder in MiqPolicyController

app/controllers/generic_object_controller.rb
=> GenericObjectController: simplify display_methods()

app/controllers/ems_physical_infra_controller.rb
=> EmsPhysicalInfraController: remove unused log_and_flash_message()

app/controllers/application_controller.rb, app/controllers/report_controller.rb, app/controllers/report_controller/menus.rb, spec/controllers/miq_report_controller/trees_spec.rb, spec/controllers/report_controller/menu_spec.rb, spec/controllers/report_controller_spec.rb
Also fixed saving of reports menus for a selected group that broke with changes in https://github.com/ManageIQ/manageiq/pull/16142
https://bugzilla.redhat.com/show_bug.cgi?id=1517073
before:
after:
=> Fixed code to show Custom reports in Available Reports in menu editor

app/controllers/storage_controller.rb
This PR is mainly to fix CI error caused by cherry-pick of https://github.com/ManageIQ/manageiq-ui-classic/pull/2838 into gaprindashvili branch.
=> [Gaprindashvili] Fix title in datastore list

app/controllers/automation_manager_controller.rb, app/controllers/provider_foreman_controller.rb, app/helpers/application_helper/toolbar/configured_system/automation/policy_mixin.rb, app/helpers/application_helper/toolbar/configured_system/foreman/lifecycle_mixin.rb, app/helpers/application_helper/toolbar/configured_system/foreman/policy_mixin.rb, app/helpers/application_helper/toolbar/x_automation_manager_ansible_tower_configured_system_center.rb
* Buttons don't need the text and title argument if they equal.
* Fixed odd number of spaces in a button definition.
* Allign case statements.
* Use ApplicationController::Feature similar to other places.
* Address some more Rubocop issues.
FYI: @lgalis
=> Foreman and Ansible controller style fixes.

bower-locker.bower.json, bower.json
This updates manageiq-ui-components to 1.0.2.
Gaprindashvili only :).
=> [GAPRINDASHVILI] Update manageiq-ui-components to 1.0.2

app/controllers/auth_key_pair_cloud_controller.rb, spec/controllers/auth_key_pair_cloud_controller_spec.rb, spec/support/controller_helper.rb
1. Go to Compute --> Cloud --> Key Pairs
1. switch between GTL modes
1. Observer the quadicons (not) shown
1. ~~specs~~
https://bugzilla.redhat.com/show_bug.cgi?id=1514102
=> Fix quadicon display in Auth Key Pairs.

spec/controllers/vm_controller_spec.rb
specs for: https://github.com/ManageIQ/manageiq-ui-classic/pull/2891
This PR is expected do fail in CI until #2891 is merged.
Ping @mansam
=> Add spec for live_migrate called outside explorers.

spec/helpers/application_helper/buttons/middleware_standalone_server_action_spec.rb
Add test coverage for delegated methods (mutability and in_domain) used when calculating visibility in the `MiddlewareStandaloneServerAction`.
When entity is expected to be visible and the properties are delegated, test that it really happens.
Depends on: https://github.com/ManageIQ/manageiq/pull/16611
=> Add test for MW delegated visibility

app/helpers/cloud_subnet_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1525537
=> cloud_subnet_helper textual summary: make labels translatable

app/controllers/vm_common.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1525554
=> Add missing gettext into vm_common.rb

app/helpers/service_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1495254
=> service_helper: make labels translatable

app/helpers/container_build_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1496141
=> container_build_helper: make label translatable

app/helpers/container_group_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1496130
=> ems_container_helper: make labels translatable

app/helpers/ems_cloud_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1495574
=> EmsCloudHelper: make labels translatable

app/helpers/ems_storage_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1497074
=> Storage: make labels translatable

app/helpers/middleware_server_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1496818
=> MW Server Summary: make version field translatable

spec/shared/helpers/application_helper_buttons.rb
Cleanup PR for core: https://github.com/ManageIQ/manageiq/pull/16661
=> Move ApplicationHelper shared examples to UI repo

app/controllers/report_controller/reports.rb
Deleted dead method miq_report_save from report_controller/reports.rb
Review please @himdel
=> Removed dead method miq_report_save

app/controllers/mixins/compressed_ids.rb, app/controllers/pxe_controller/pxe_image_types.rb
dead methods deleted
pxe_image_type_tree_select
cid?
=> Dead methods pxe_image_type_tree_select + cid? deleted

app/controllers/ops_controller/settings.rb
I have removed dead method user_make_subbarrays from file ops_controller/settings.rb.
=> remove dead method user_make_subbarrays

spec/controllers/vm_infra_controller_spec.rb
Simple style fixes.
Ping @h-kataria
=> VmInfraController spec style fixes.

app/controllers/application_controller/timelines/options.rb, app/controllers/ems_swift_controller.rb
Deleted methods: 
fltr    in file: options.rb
ems_swift_form_fields    in file: ems_swift_controller.rb
build_filter    inf file: options.rb
=> Deleting unused methods

app/controllers/pxe_controller/pxe_image_types.rb
Minor style fixed following https://github.com/ManageIQ/manageiq-ui-classic/pull/2943
=> PxeImageTypes: minor style fixes.

app/controllers/pxe_controller/pxe_servers.rb
=> Deleted dead method identify_pxe_server in pxe_server.rb

app/controllers/application_controller/buttons.rb
Remove dead function ab_create_update.
=> remove dead function ab_create_update

app/controllers/configuration_job_controller.rb
Deleting dead method ems_path from configuration_job_controller
ping @himdel
=> deleting dead method from configuration_job_controller

app/controllers/application_controller/policy_support.rb
Deleting unused method 
app/controllers/application_controller/policy_support.rb :130-150
=> Deleting dead profile_toggle method app/controllers/application_controller/policy_support.rb

app/controllers/storage_controller.rb
removal of dead method show_new in app/controllers/storage_controller.rb on lines 39-52.
=> removed dead method show_new in app/controllers/storage_controller.rb

app/controllers/ems_common.rb, app/controllers/mixins/vm_show_mixin.rb
Removed dead methods any_blank_fields? and generate_breadcrumb
=> Deleting dead methods

app/controllers/ems_cluster_controller.rb
Removed dead method hosts_subsets from file ems_cluster_controller.rb
=> remove dead method hosts_subsets

app/controllers/miq_ae_customization_controller/dialogs.rb
Removed dead method field_value_new_cat.
=> Removed dead method field_value_new_cat in dialogs

app/controllers/application_controller.rb
Removed dead method init_server_options in file application_controller.rb
=> Removed dead method init_server_options in file application_controller.rb

app/controllers/ems_common.rb, app/controllers/miq_ae_customization_controller/old_dialogs.rb
=> Remove methods

app/assets/javascripts/miq_c3.js
Just minor style fixes here. There are more in this file, fixing just what is obvious.
ping @PanSpagetka, @himdel
=> Minor style fixes in miq_c3.

app/controllers/application_controller/advanced_search.rb, app/controllers/application_controller/filter.rb
Extract duplicate code into a separate method.
=> Deduplicate advanced search.

app/controllers/mixins/actions/vm_actions/associate_floating_ip.rb, app/controllers/mixins/actions/vm_actions/disassociate_floating_ip.rb
Allows proper floating_ip association
https://bugzilla.redhat.com/show_bug.cgi?id=1521061
=> VM: Filter floating_ip address

bower-locker.bower.json, bower.json
This updates ui-components to 1.0.3 for gaprindashvili.
=> [GAPRINDASHVILI] bower - update manageiq-ui-components to 1.0.3

app/controllers/dashboard_controller.rb
Style fixes:
* replace deprecated `find_by_*` with `find/find_by(/exists?`
* extract a method `widget_minimized?`
* whitespace fixes
=> DashboardController: style fixes.

app/controllers/miq_policy_controller.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1525460
=> Make the "Policy" word translatable by putting it into a gettext fn.

app/views/ops/_rbac_user_details.html.haml
=> User edit: fix styling for selected user groups

app/assets/javascripts/remote_console.js
Fixed typos in method calls.
@miq-bot add_labels bug, blocker, consoles
https://bugzilla.redhat.com/show_bug.cgi?id=1520105
=> Fix typos in fullscreen method calls for IE11

app/controllers/application_controller/policy_support.rb, app/controllers/application_controller/tree_support.rb, app/controllers/miq_policy_controller.rb, app/decorators/miq_policy_decorator.rb, app/presenters/tree_builder_condition.rb, app/presenters/tree_builder_policy.rb, app/presenters/tree_builder_protect.rb, app/views/miq_policy/_policy_folders.html.haml
Reverts ManageIQ/manageiq-ui-classic#2436
=> Revert "Enable MW Compliance and Control policies"

app/controllers/application_controller.rb, app/controllers/mixins/vm_show_mixin.rb, app/controllers/report_controller.rb, app/controllers/vm_cloud_controller.rb, app/controllers/vm_infra_controller.rb, app/controllers/vm_or_template_controller.rb
Cleanups some of the explorer-style functionality.
=> Explorer cleanups

app/controllers/application_controller.rb
called only from pending specs.
=> Remove unused remove_init_report_data.

app/controllers/infra_networking_controller.rb
=> Deleted method dvswitches_list in file infra_networking_controller.rb in line 254-261.

app/controllers/vm_common.rb
=> Deleted dead method from app/controllers/vm_common.rb

app/controllers/ems_cinder_controller.rb, app/controllers/miq_ae_customization_controller.rb
Removal of dead methods dialog_import_export_tree, ems_cinder_form_fields
=> Deletion of dead methods (dialog_import_export_tree, ems_cinder_form_fields)

app/controllers/dashboard_controller.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1525931
=> Apply gettext on widget menu items after minimizing

app/controllers/ops_controller/ops_rbac.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1525922
=> Fix right cell text on user/group/role add/edit page

app/views/cloud_subnet/new.html.haml
Indent h3 tag for "Placement" label
https://bugzilla.redhat.com/show_bug.cgi?id=1529078
Old
New
=> Fix 'Add Subnet' styling

app/controllers/application_controller/report_data_additional_options.rb, spec/shared/controllers/shared_examples_for_ems_block_storage_controller.rb, spec/shared/controllers/shared_examples_for_ems_object_storage_controller.rb
Add supported_features_filter to report_data additional_options list
Links 
-------
https://bugzilla.redhat.com/show_bug.cgi?id=1489143
After:
=> Add supported_features_filter to report_data additional_options list

app/controllers/application_controller/buttons.rb, app/views/shared/buttons/_ab_advanced_form.html.haml, app/views/shared/buttons/_ab_form.html.haml, spec/controllers/application_controller/buttons_spec.rb
Set active tab when editing a custom button details
Links
--------
https://bugzilla.redhat.com/show_bug.cgi?id=1501051
=> Set active tab when editing a custom button details

app/assets/javascripts/services/topology_service.js
In topology screens, the search is in the toolbar, separated from the angular app running the topology.
The 2 communicate using RxJs but after the recent refactorings, we stopped triggering the angular digest cycle when receiving such a message - wrapping in `$timeout` to compensate.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1527846
=> TopologyService - trigger angular change detection when searching/resetting

bower-locker.bower.json, bower.json
This updates ui-components to 1.0.4 for gaprindashvili.
=> [GAPRINDASHVILI] bower - update manageiq-ui-components to 1.0.4

app/assets/javascripts/controllers/dialog_editor/dialog_editor_controller.js
Corrected format for buttons attribute for Service Dialogs
response to comment https://github.com/ManageIQ/manageiq-ui-classic/pull/2986#issuecomment-355355390
=> Corrected format for buttons attribute in Service Dialogs

app/controllers/miq_request_controller.rb
Refactor button press handling in MiqRequest controller.
* straighten the twisted logic
* remove dead code
* simplify flash message display
Style fixes in the last commit.
* flash message passing throught `params`
=> Cleanup MiqRequestButton handling

app/controllers/auth_key_pair_cloud_controller.rb, app/views/auth_key_pair_cloud/show.html.haml
To be rebased.
* decuplicate button press handling
* remove dead code from view
=> Auth key pair button

bower-locker.bower.json, bower.json
This updates ui-components to 1.0.5 for gaprindashvili.
=> [GAPRINDASHVILI] bower - update manageiq-ui-components to 1.0.5

app/controllers/miq_policy_controller.rb
Problem introduced in https://github.com/ManageIQ/manageiq-ui-classic/pull/3113
https://bugzilla.redhat.com/show_bug.cgi?id=1531468
=> Add missing "Policy" word

app/helpers/application_helper/title.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1526553
=> Add missing page titles

app/views/ops/_rbac_role_details.html.haml
Depends on https://github.com/ManageIQ/manageiq/pull/16752
https://bugzilla.redhat.com/show_bug.cgi?id=1526440
=> Add missing gettext into user role screen

app/helpers/container_image_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1533093
=> Make labels translatable in container image textual summary

app/views/planning/_planning_options.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1533058
=> Add missing gettext into planning/_planning_options.html.haml

config/locale_task_config.yaml
This is a UI friend for https://github.com/ManageIQ/manageiq/pull/16735 and should be merged together.
=> Configurable yaml string extraction

app/controllers/application_controller.rb, app/controllers/report_controller.rb, spec/controllers/report_controller_spec.rb
Conflict-resolving PR for #3190
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1532654
ping @simaishi
=> [GAPRINDASHVILI] Add both custom reports and custom report menu items to report menu

app/assets/javascripts/miq_timeline.js
https://bugzilla.redhat.com/show_bug.cgi?id=1533063
=> Add missing gettext into miq_timeline.js

spec/presenters/tree_builder_ops_rbac_features_spec.rb
This fixes build failures at https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/328151285
https://bugzilla.redhat.com/show_bug.cgi?id=1533391
=> Removed mdl from the list in spec test

app/controllers/storage_controller.rb
@miq-bot add_labels bug, blocker, wip, pending core
https://bugzilla.redhat.com/show_bug.cgi?id=1529269
=> [GAPRINDASHVILI] Fix exception when clicking on relationship table entries

config/routes.rb
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535409
=> Container node: add dialog_load and related routes.

bower-locker.bower.json, bower.json
This updates ui-components to 1.0.6 for gaprindashvili.
=> [GAPRINDASHVILI] bower - update manageiq-ui-components to 1.0.6

manageiq-ui-classic.gemspec
=> Update patternfly to 3.37.0

app/controllers/application_controller/performance.rb
Divide perf menu click into methods
=> Divide perf_menu_click_into methods

spec/controllers/report_controller_spec.rb
Fixes issue 11 found in https://github.com/ManageIQ/manageiq/pull/16768#issuecomment-357765761
=> Prefer FactoryGirl.build over .build_stubbed

bower-locker.bower.json, bower.json
This updates ui-components to 1.0.7 for gaprindashvili.
=> [GAPRINDASHVILI] bower - update manageiq-ui-components to 1.0.7

app/helpers/container_image_helper/textual_summary.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536416
=> Container Image textual summary - handle nil entrypoints

app/helpers/application_helper/toolbar/generic_object_definition_button_center.rb
Before:
After:
1. Navigate to Automation > Automate > Generic Object
2. Add Generic Object Class
3. In this class, add custom button
4. Select the button in the tree
=> Changed an icon for toolbar button

app/controllers/report_controller/widgets.rb, spec/controllers/report_controller/widget_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536482
Comes from https://github.com/ManageIQ/manageiq-ui-classic/pull/2905 ..
@h-kataria can you review please?
Cc @skateman (because https://github.com/ManageIQ/manageiq-ui-classic/issues/3245)
=> Show custom reports when creating a new report widget

app/assets/javascripts/controllers/report_data_controller.js, spec/javascripts/controllers/report_data_controller_spec.js
1. Find any screen with GTL
2. switch to non-English locale
3. make sure header sorting works
This needs to be merged with https://github.com/ManageIQ/ui-components/pull/236
https://bugzilla.redhat.com/show_bug.cgi?id=1536964
=> Use header_text for localized table / sort headers

locale/es/ManageIQ_UI_Classic.po, locale/fr/ManageIQ_UI_Classic.po, locale/ja/ManageIQ_UI_Classic.po, locale/pt_BR/ManageIQ_UI_Classic.po, locale/zh_CN/ManageIQ_UI_Classic.po
This PR contains final translation fixes / polishing for Gaprindashvili GA.
=> [GAPRINDASHVILI] Final translations for gaprindashvili

bower-locker.bower.json, bower.json
This updates ui-components to 1.0.8 for gaprindashvili.
=> [GAPRINDASHVILI] bower - update manageiq-ui-components to 1.0.8

app/assets/javascripts/miq_application.js
Clean chart data function. Extract pieces into separate functions.
=> Clean chart data function

app/helpers/host_helper/textual_summary.rb
Additional fix for https://bugzilla.redhat.com/show_bug.cgi?id=1394799
=> Add link to network manager for infra nodes

app/views/vm_common/_reconfigure.html.haml
=> Fix typo in message

app/views/ops/_schedule_form_timer.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1538117
=> Add missing gettext to _schedule_form_timer.html.haml

spec/controllers/service_controller_spec.rb
These tests are related to my fix in https://github.com/ManageIQ/manageiq-ui-classic/pull/3255
=> Add spec tests to check applying filter from Adv Search in My Services

app/controllers/miq_request_controller.rb
Cleanup and deduplicate the code a bit.
Fixes a number of "duplicate DOM ID" messages.
Overall the screen is strange, probably a UX refresh + rewrite on the client would be needed. But having less and cleaner code will help with further work here.
=> MiqTask cleanups

app/controllers/cloud_subnet_controller.rb, app/controllers/cloud_tenant_controller.rb, app/controllers/host_aggregate_controller.rb
fine version of https://github.com/ManageIQ/manageiq-ui-classic/pull/3179
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1538350
=> [FINE] Add rbac checks for cloud new screens

app/assets/javascripts/miq_application.js, spec/javascripts/miq_application_spec.js
without that `done`, this was a synchronous test with 0 expects (because they all happened asynchronously (ie. never), outside a test context)
the rest just makes it work :)
Cc @mzazrivec, @ohadlevy
=> miq_application_spec - fix "login failed" spec to run the expects

manageiq-ui-classic.gemspec
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1536007
@hstastna @Hyperkid123 please click this through a little bit, thanks :beers: 
=> Update PatternFly to 3.38.0

app/assets/stylesheets/patternfly_overrides.scss
This PR organizes the CSS/SCSS declarations alphabetically.
=> styling cleanup

bower-locker.bower.json, bower.json
Update manageiq-ui-components to 1.0.9 for gaprindashvili.
The new release contains:
https://github.com/ManageIQ/ui-components/pull/246
https://github.com/ManageIQ/ui-components/pull/247
https://github.com/ManageIQ/ui-components/pull/248
=> [GAPRINDASHVILI] Update manageiq-ui-components to 1.0.9 for gaprindashvili

app/assets/javascripts/miq_application.js, spec/javascripts/miq_application_spec.js
https://bugzilla.redhat.com/show_bug.cgi?id=1540148
=> Set focus on username input after unsuccessful login

bower-locker.bower.json, bower.json
Updating ui-components to 1.0.11.
Changes:
* https://github.com/ManageIQ/ui-components/pull/249
* https://github.com/ManageIQ/ui-components/pull/250
=> [GAPRINDASHVILI] Update ui-components to 1.0.11 for gaprindashvili

bower-locker.bower.json, bower.json
Updating ui-components to 1.0.12.
Changes:
* https://github.com/ManageIQ/ui-components/pull/251
=> [GAPRINDASHVILI] Upgrade gaprindashvili to ui-components 1.0.12

bower-locker.bower.json, bower.json
Update gaprindashvili to ui-components 1.0.13
Contains:
* https://github.com/ManageIQ/ui-components/pull/253
=> [GAPRINDASHVILI] Update gaprindashvili to ui-components 1.0.13

.scrutinizer.yml
Disable scrutinizer tests. (Until I fix the db setup.)
=> Scrutinizer: disable tests.

app/controllers/ems_common.rb, app/helpers/ems_storage_helper/textual_summary.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1519292
Added a link to volume backups on the storage provider page
=> BZ1519292: link to volume backups from storage provider page

app/assets/javascripts/remote_consoles/spice.js, bower.json
Depends on https://github.com/himdel/spice-html5-bower/pull/1
@miq-bot add_labels bug, compute/infrastructure
https://bugzilla.redhat.com/show_bug.cgi?id=1491387
=> Fix CTRL-ALT-DEL button on Spice consoles

.scrutinizer.yml
@martinpovolny this is the thing you promised to fix on monday or tuesday :trollface:
=> Fix issues with scrutinizer to at least make it green

app/decorators/ext_management_system_decorator.rb, app/decorators/host_decorator.rb, app/decorators/manageiq/providers/cloud_manager_decorator.rb, app/decorators/manageiq/providers/container_manager_decorator.rb, app/decorators/manageiq/providers/hawkular/middleware_manager_decorator.rb, app/decorators/manageiq/providers/infra_manager_decorator.rb, app/decorators/manageiq/providers/physical_infra_manager_decorator.rb, app/decorators/miq_template_decorator.rb, app/decorators/physical_server_decorator.rb, app/decorators/storage_decorator.rb, app/decorators/vm_or_template_decorator.rb, app/helpers/quadicon_helper.rb, app/helpers/quadicon_helper/decorator.rb, lib/miq_decorator.rb, spec/helpers/quadicon_helper_spec.rb
This PR adds decorators for all remaining items which were using quadicon helper
* ### Physical server
* ### Host
* ### Storage
* ### Resource pool
* ### VmOrTemplate
This PR also introduces new method for simpler creation of basic quadicon HTML to separate quadicon and URL generation. Can be later removed, when we have quadicons generated with JSON.
None
This PR address second point of https://github.com/ManageIQ/manageiq-ui-classic/issues/3076
=> Quadicon as decorators for all items using quadicons

app/controllers/application_controller/policy_support.rb, app/controllers/application_controller/tree_support.rb, app/controllers/miq_policy_controller.rb, app/controllers/mixins/containers_common_mixin.rb, app/decorators/miq_policy_decorator.rb, app/helpers/term_of_service_helper.rb, app/presenters/tree_builder_condition.rb, app/presenters/tree_builder_policy.rb, app/presenters/tree_builder_protect.rb, app/views/miq_policy/_policy_folders.html.haml
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1469138
Completes:
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/226
https://github.com/ManageIQ/manageiq/pull/16903
@miq-bot add_label compute/containers, wip 
@moolitayer @cben @nimrodshn @yaacov 
cc @oourfali
=> Allow control policies for container projects

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
Add Rbac filtering to the catalog bundle resource list
Links 
--------
https://bugzilla.redhat.com/show_bug.cgi?id=1541304
Before:
After:
=> Add Rbac filtering to the catalog bundle resource list

app/helpers/application_helper/toolbar/cloud_tenants_center.rb
@miq-bot add_labels bug, compute/cloud, fine/yes, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1495829
=> Update icons used in Cloud Tenants for consistency

app/helpers/application_helper/button/vm_vnc_console.rb, app/helpers/application_helper/button/vm_webmks_console.rb, spec/helpers/application_helper/buttons/vm_vnc_console_spec.rb, spec/helpers/application_helper/buttons/vm_webmks_console_spec.rb
Added a check for a nil Host.
@miq-bot add_labels bug, compute/infrastructure, fine/yes, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1548073
=> Fix nil:nilClass error on VM summary

app/views/ops/_settings_cu_collection_tab.html.haml
This PR fixes an issue where content was indented inside an H3 tag. It also adds missing form-horizontal class divs.
https://bugzilla.redhat.com/show_bug.cgi?id=1548118
Old
New
=> Fix Cap & U Collection tab styling

app/assets/javascripts/controllers/ems_infra_dashboard/aggregate_status_card_controller.js
=> Add gettext to aggregateStatusCardController status card titles

.gitignore
=> Add VIM swap files to gitignore.

package.json
Temporarily fixing the issue introduced in https://github.com/ManageIQ/manageiq-graphql/pull/44
=> Fix travis issues with manageiq-graphql by updating deps

app/decorators/manageiq/providers/cloud_manager_decorator.rb
=> Do not inherit CloudManagerDecorator from EMS decorator

spec/controllers/miq_ae_class_controller_spec.rb
Fixes spec test failure cause by backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/3323/ need to use compressed id on Gaprindashvili branch
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1552741
=> [Gaprindashvili] - Spec test failure fix.

locale/ja/ManageIQ_UI_Classic.po, locale/zh_CN/ManageIQ_UI_Classic.po
Some more updates for gaprindashvili release from our translators.
=> [GAPRINDASHVILI] Update japanese & chinese translations for gaprindashvili

bower-locker.bower.json, bower.json
Contains:
https://github.com/ManageIQ/ui-components/pull/258
https://github.com/ManageIQ/ui-components/pull/265
=> [GAPRINDASHVILI] Update manageiq-ui-components to 1.0.16 for gaprindashvili

config/routes.rb
Bug fix
=====
This PR fixes the error described here https://bugzilla.redhat.com/show_bug.cgi?id=1552609
=> Fixing error while try to download the physical server summary as PDF

app/helpers/application_helper/toolbar/ems_physical_infras_center.rb
Bug Fix
=====
This PR fixes the error described here https://bugzilla.redhat.com/show_bug.cgi?id=1525116
=> Fix name of 'Physical Infrastructure Providers' on the Physical Infrastructure Providers page

app/controllers/ansible_playbook_controller.rb, app/controllers/application_controller.rb, app/helpers/ansible_playbook_helper/textual_summary.rb, app/helpers/application_helper/toolbar/ansible_playbook_center.rb, app/helpers/application_helper/toolbar/ansible_playbooks_center.rb, config/routes.rb, spec/controllers/ansible_playbook_controller_spec.rb
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=1526218
**Needs to merge with:** https://github.com/ManageIQ/manageiq/pull/17099
---
**Done:**
- add toolbar and _Policy_ button to access tagging in _Automation > Ansible > Playbooks_
(_Policy > Edit Tags_)
- add `tagging_edit` and `tag_edit_form_field_changed` to routes to enable tagging for Ansible Playbooks or for proper rendering of tagging screen
- add `button` method and calling `tag` method to the method, in ansible playbook controller
- display tags in the table in summary page of any playbook
- make tagging work also from summary page of any playbook
- add a spec test for `button` method in ansible playbook controller + fix an existing one
- check if RBAC works
**Before:**
**After:**
**Note:**
_How to check RBAC support_ …
=> Add RBAC and Tagging Support to Ansible Playbooks

app/controllers/application_controller/policy_support.rb
Backporting #3524 to gaprindashvili branch.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1554839
=> [GAPRINDASHVILI] Show policy status when running policy simulation

bower-locker.bower.json, bower.json
Update gaprindashvili to manageiq-ui-components 1.0.18
Contains: https://github.com/ManageIQ/ui-components/pull/266
Cc @gmcculloug , @eclarizio
=> [GAPRINDASHVILI] Update gaprindashvili to manageiq-ui-components 1.0.18

app/assets/javascripts/application.js, app/assets/stylesheets/pdf/_patternfly.scss.erb
Fun time when creating a new development setup without this one :wink: @himdel
=> Consume patternfly.js through rubygems instead of bower

app/controllers/ems_common.rb, spec/controllers/ems_common_controller_spec.rb
Fix for Cloud image tagging from a list
Links 
----------
https://bugzilla.redhat.com/show_bug.cgi?id=1501783
1. Select one Cloud Provider 
2. Display images and try tagging for a one or more selected ones
=> Fix for Cloud image tagging from a list

product/views/ManageIQ_Providers_EmbeddedAutomationManager_ConfigurationScriptSource.yaml
Change column title from "Updated on" to "Last refresh"
Screenshots:
Before:
After:
This column change after clicking on Refresh button:
Links
https://bugzilla.redhat.com/show_bug.cgi?id=1536144
Related PRs
https://github.com/ManageIQ/manageiq/pull/17026
https://github.com/ManageIQ/manageiq-schema/pull/172
https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/59
=> Change column title from "Updated on" to "Last refresh"

app/views/vm_common/_reconfigure.html.haml
Add a header title for the Unit column
Links 
---------
https://bugzilla.redhat.com/show_bug.cgi?id=1524960
Before:
After:
=> Add a column title for the Disk size Unit

app/presenters/tree_builder.rb
Removing an unused line added in https://github.com/ManageIQ/manageiq-ui-classic/pull/2213
Links 
----------
https://bugzilla.redhat.com/show_bug.cgi?id=1492216
https://github.com/ManageIQ/manageiq-ui-classic/pull/2213
=> Follow up for Restore delete server 

app/controllers/report_controller/reports/editor.rb
@miq-bot add_label enhancement, chargeback
=> Offer rate columns in chargeback report

bower-locker.bower.json, bower.json
Replacement for
#3663
ManageIQ/ui-components#269
ManageIQ/ui-components#270
ManageIQ/ui-components#271
plus
ManageIQ/ui-components#272
=> [GAPRINDASHVILI] ui-components: update to 1.0.20

bower-locker.bower.json, bower.json
ManageIQ/ui-components#269
ManageIQ/ui-components#270
ManageIQ/ui-components#271
Cc @chalettu, @eclarizio, @romanblanco
=> [GAPRINDASHVILI] ui-components: update to 1.0.19

app/views/shared/dialogs/_dialog_user.html.haml
This PR moves the form buttons inside the column containing the other elements
https://bugzilla.redhat.com/show_bug.cgi?id=1553697
Old
New
=> Correct positioning of dialog form buttons

app/controllers/miq_policy_controller.rb
Please, read the commit messages.
Testing: Controll --> Explorer ---> Policies Profiles --> get to an event in the tree --> Edit an event
Before (and after):
=> MiqPolicy: cleanup handle_selection_buttons a bit.

bower-locker.bower.json, bower.json
Update ui-components to 1.0.21.
Contains https://github.com/ManageIQ/ui-components/pull/275
@miq-bot add_label blocker, dependencies
@miq-bot assign simaishi
=> [GAPRINDASHVILI] update ui-components to 1.0.21

app/controllers/report_controller/dashboards.rb
caused by ManageIQ/manageiq-ui-classic#2201
cc @gtanzillo 
https://bugzilla.redhat.com/show_bug.cgi?id=1563828
=> Fix query to fetch more widgets

app/assets/javascripts/components/ae_resolve_options/ae-resolve-options-component.js, app/assets/javascripts/controllers/schedule/schedule_form_controller.js, app/views/ops/_schedule_form_filter.html.haml, app/views/static/ae_resolve_options/ae-resolve-options-component.html.haml
This PR replaces partial for scheduleForm #2766 with angular component.
Configuration -> Settings -> Schedules ->Configuration -> Add new Schedule / Edit the selected Schedule
select action: `Automation Task`
parts of the component
- Object Details
- Object Attribute
- Attribute/Value Parts
partial `app/views/layouts/angular-bootstrap/_ae_resolve_options.html.haml`
partial is not used anywhere so i have removed it
=> Ae resolve options component

bower.json
When running a `bin/update` these changes are automatically added.
=> Update bower.json resolutions with bootstrap-switch

app/assets/javascripts/controllers/automation_manager/automation_manager_form_controller.js, app/assets/javascripts/controllers/provider_foreman/provider_foreman_form_controller.js, app/assets/javascripts/directives/form_changed.js, app/assets/javascripts/directives/validation/reset_validation_status.js, app/assets/javascripts/directives/validation/validation_status.js, app/assets/javascripts/services/configuration_manager_service/configuration_manager_service.js, app/assets/javascripts/services/miq_service.js, app/controllers/application_controller.rb, app/controllers/automation_manager_controller.rb, app/controllers/mixins/ems_common_angular.rb, app/controllers/mixins/generic_form_mixin.rb, app/controllers/mixins/manager_controller_mixin.rb, app/controllers/provider_foreman_controller.rb, app/views/automation_manager/_form.html.haml, app/views/layouts/angular-bootstrap/_auth_credentials_angular_bootstrap.html.haml, app/views/layouts/angular/_form_buttons_verify_angular.html.haml, app/views/provider_foreman/_form.html.haml, spec/controllers/automation_manager_controller_spec.rb, spec/controllers/provider_foreman_controller_spec.rb, spec/javascripts/controllers/automation_manager/automation_manager_form_controller_spec.js, spec/javascripts/controllers/provider_foreman/provider_foreman_form_controller_spec.js, spec/javascripts/directives/validation/validation_status_spec.js, spec/views/host/_form.html.haml_spec.rb
Upstream PR - https://github.com/ManageIQ/manageiq-ui-classic/pull/1850
Fine BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1496902
=> [FINE] Add Validation as a requirement prior to a Save for Ansible and Foreman Providers 

bower-locker.bower.json, bower.json
Contains: https://github.com/ManageIQ/ui-components/pull/278
=> [GAPRINDASHVILI] Update ui-components to 1.0.22 for gaprindashvili

app/controllers/service_controller.rb, spec/controllers/service_controller_spec.rb
Add custom attributes to playbook summary 
Links
----------
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1568073
=> Add custom attributes to playbook summary

bower-locker.bower.json, bower.json
https://github.com/ManageIQ/ui-components/pull/279
=> [GAPRINDASHVILI] Update manageiq-ui-components to 1.0.23 for gaprindashvili

.github/CODEOWNERS
[ci skip]
@miq-bot add_label developer, gaprindashvili/no
=> Adding myself as a code owner for the app/decorators folder

app/decorators/miq_template_decorator.rb, app/helpers/quadicon_helper.rb
@skateman :hearts: consistency
@miq-bot add_label refactoring, gaprindashvili/no
=> Use the QuadiconHelper.machine_state for miq_template too

spec/controllers/miq_report_controller/dashboards_spec.rb
@miq-bot assign @gtanzillo 
origin fix
https://github.com/ManageIQ/manageiq-ui-classic/pull/3723
=> Add specs for saving widgets for #3723

bower.json
* https://github.com/ManageIQ/ui-components/pull/282 (for [BZ 1571989](https://bugzilla.redhat.com/show_bug.cgi?id=1571989))
* https://github.com/ManageIQ/ui-components/pull/286 (for [BZ 1571976](https://bugzilla.redhat.com/show_bug.cgi?id=1571976))
=> [GAPRINDASHVILI] Update ui-components to 1.0.24 for gaprindashvili

app/controllers/ems_common.rb, app/controllers/mixins/ems_common_angular.rb, app/helpers/application_helper/toolbar_chooser.rb, spec/controllers/ems_infra_controller_spec.rb
Add specs for https://github.com/ManageIQ/manageiq-ui-classic/pull/3827
=> Timeline menu specs

app/controllers/application_controller/performance.rb
Cleanup style issues in performance a bit.
=> Performance: style fixes.

app/helpers/quadicon_helper.rb
This should improve the code quality a little bit :sparkles: 
@miq-bot add_label refactoring, gaprindashvili/no
=> Extract QuadiconHelper.machine_state case to a hash and freeze it

app/controllers/report_controller/reports/editor.rb, app/helpers/report_helper/editor.rb, spec/controllers/miq_report_controller/reports/editor_spec.rb, spec/controllers/ops_controller/ops_rbac_spec.rb, spec/controllers/ops_controller_spec.rb, spec/helpers/application_helper/views_shared_spec.rb, spec/presenters/tree_builder_ops_rbac_spec.rb
Fine version of https://github.com/ManageIQ/manageiq-ui-classic/pull/3494
Reason for WIP:
Needed backend FINE PR:
https://github.com/ManageIQ/manageiq-ui-classic/pull/3494 (main fix for BZ)
https://github.com/ManageIQ/manageiq-ui-classic/pull/3533 (fix for broken specs)
@miq-bot assign @simaishi 
cc @mzazrivec
=> [FINE] Add rbac to report definition on users and tenants

bower.json
* https://github.com/ManageIQ/ui-components/pull/291 (for [BZ 1570613](https://bugzilla.redhat.com/show_bug.cgi?id=1570613))
* https://github.com/ManageIQ/ui-components/pull/292 (for [BZ 1569472](https://bugzilla.redhat.com/show_bug.cgi?id=1569472))
=> [GAPRINDASHVILI] Update ui-components to 1.0.25 for gaprindashvili

bower-locker.bower.json, bower.json
https://github.com/ManageIQ/ui-components/pull/262
=> [GAPRINDASHVILI] Update ui-components to 1.0.26 for gaprindashvili

app/controllers/dashboard_controller.rb
Style fixes. Please, review carefully. Thx!
=> Dashboard controller style fixes.

app/controllers/miq_policy_controller.rb
Just style fixes.
Please, review carefully.
=> Policy controller style fixes.

app/controllers/application_controller.rb, app/helpers/application_helper/toolbar_builder.rb, app/helpers/application_helper/toolbar_chooser.rb, app/helpers/configuration_helper/configuration_view_helper.rb, spec/controllers/vm_cloud_controller_spec.rb, spec/controllers/vm_infra_controller_spec.rb, spec/helpers/application_helper/toolbar_builder_spec.rb
=> Remove ancient code that was able to set multiple tree sizes

app/controllers/miq_ae_customization_controller/dialogs.rb
just style fixes, please read carefully.
=> Customization dialogs: style fixes.

app/controllers/mixins/actions/host_actions/discover.rb
* do not pass flash in params
* fix some style issues
=> Discover: do no pass flash in params. Fix style.

app/controllers/catalog_controller.rb, app/controllers/mixins/checked_id_mixin.rb, spec/controllers/catalog_controller_spec.rb
Description: catalog_controller.rb -> method ot_remove_submit code refactoring 
Parent issue: #1134
code review:
comment: @miq_bot add_label rbac
@miq_bot add_label refactoring
=> Replace old methods by new in catalog controller

app/controllers/floating_ip_controller.rb, spec/controllers/floating_ip_controller_spec.rb
Description:  floating_ip_controller.rb -> method delete_floating_ips code refactoring and floating_ip_controller_spec.rb -> describe "#delete_floating_ips" creation of test  
code review: @VratislavHais
=> Floating ip controller

.codeclimate.yml
=> Ask Codeclimate to not complain about duplication in decorators

app/controllers/configuration_controller.rb
Just style fixes. Please, read carefully.
=> Configuration controller style fixes.

app/controllers/application_controller/compare.rb
Just style fixes. Please, review carefully.
=> Compare: style fixes.

manageiq-ui-classic.gemspec
=> Update patternfly to version 3.46

app/controllers/report_controller/schedules.rb, spec/controllers/report_controller/schedules_spec.rb
Tested successfully with no errors
Please review @KrecekDaniel
=> Rbac refactoring - Report controller schedules

app/controllers/auth_key_pair_cloud_controller.rb, app/helpers/application_helper/button/auth_key_pair_cloud_download.rb, app/helpers/application_helper/toolbar/auth_key_pair_cloud_center.rb, config/routes.rb, spec/helpers/application_helper/buttons/auth_key_pair_cloud_download_spec.rb
Implements https://bugzilla.redhat.com/show_bug.cgi?id=1490979
=> Allow downloading of AuthKeyPair private keys if they are available

app/assets/javascripts/controllers/retirement/retirement_form_controller.js, app/assets/javascripts/directives/datetimepicker.js
Nonetheless, the retirement time will still be saved as UTC.
https://bugzilla.redhat.com/show_bug.cgi?id=1565128
=> Display browser local time in retirement form

lib/report_formatter/chart_common.rb
Fix Categories order for Reporting charts. Chart were sorted only by values(Y), now they will be sorted by categories labels(X)
https://bugzilla.redhat.com/show_bug.cgi?id=1578959
Create report which contains chart based on Counts not Values.
=> Fix Categories order for Reporting charts

README.md
Add Scrutinizer code quality badge:
[![Scrutinizer](https://scrutinizer-ci.com/g/ManageIQ/manageiq-ui-classic/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/ManageIQ/manageiq-ui-classic/?branch=master)
=> Add Scrutinizer code quality badge.

README.md
=> Remove gemnasium link from the README.md as it got discontinued

app/controllers/mixins/generic_show_mixin.rb, app/controllers/mixins/vm_show_mixin.rb, app/controllers/vm_common.rb
:scissors: :toilet: :fire: :tada: 
=> Remove summary_only conditions from controllers as it is unused

app/controllers/application_controller.rb, app/controllers/ems_physical_infra_controller.rb, spec/controllers/report_controller/schedules_spec.rb
* test chart click-through
* test miq task filtering
* test job filtering 
* test physical server listing with hosts
* there was an exception for physical server that seems useless, remove it! (have no data to test that properly)
* there was an exception for MiqRequest and that should not be needed any more
* there was an exception for Tasks, and that should go through scopes
* search goes through the session
* advanced search (filtering) goes throught the session
=> Report data cleanup

app/views/cloud_volume/_common_new_edit.html.haml
https://bugzilla.redhat.com/show_bug.cgi?id=1570570
Second PR for this bug, since the earlier fix had a typo
that didn't show up in local testing.
=> bz 1570570: Fix typo in earlier commit
