ManageIQ/manageiq-ui-classic

app/javascript/oldjs/controllers/ansible_repository/repository_form_controller.js
app/views/ansible_repository/_repository_form.html.haml

Requires:  https://github.com/ManageIQ/manageiq/pull/21298
Adds `verify_ssl` checkbox for the `EmbeddedAnsible` repository form.  On the backend, this actually ends up saving the field on not the `ConfigurationScriptSource`, but the associated `GitRepository` object, but that is mostly a backend concern that is not visiable on the client side.
Screenshots
-----------
TODO
----
Merge the following:
* Go to:  Automation -> EmbeddedAnsible -> Repositories
* Add a new repo, and ensure that `Verify SSL` is checked
* Optional:  If running locally, ensure that you are using `simulate_queue_worker`
* Once saved, edit the new record, and ensure that `verify_ssl` is checked
* Uncheck the record, and save.
* Once saved, edit the record again to confirm the …

[EmbeddedAnsible] verify_ssl field on repository

---

config/routes.rb
spec/config/routes.pending.yml

Click on Storage -> Storages -> <Select on any existing Physical Storage">, The breadcrumb link shows the following Navigation LInk as shown below:
Compute–> Physical Infrastructure–> +*Storages*+ --> GTSFS9150A (Summary)
But clicking on the storage link throws a page not found error..

fix broken breadcrumb url for physical_storage

---

app/controllers/application_controller.rb
app/controllers/application_controller/ci_processing.rb
app/controllers/application_controller/report_data_additional_options.rb
app/controllers/vm_common.rb
app/helpers/application_helper.rb
app/javascript/components/gtl-view.jsx
app/javascript/components/gtl/DataTable.jsx
app/javascript/oldjs/miq_application.js

User will be able to select multiple rows from a data table across the various pages of the data table.
Previously, the data table would deselect rows when the user switched pages.
Note: User selected rows do not persist across pages. 
https://user-images.githubusercontent.com/29209973/123815814-caa60680-d8c4-11eb-9c17-11588fc7a18f.mov
Note: After comparing rows, when returning to the main table all rows have been deselected. 
https://user-images.githubusercontent.com/29209973/123815885-da254f80-d8c4-11eb-8dc2-6e5a6d1bdf16.mov
Note: User selected rows DO persist across pages and across changing pagination size. 
https://user-images.githubusercontent.com/29209973/123816123-0d67de80-d8c5-11eb-95a7-a48d0384b48b.mov
Note: This behavior is still a work in progress. 
After comparing rows, when …

Fix rows selection across multiple pages in table view

---

app/controllers/miq_action_controller.rb
app/views/miq_action/show.html.haml

Fixed issue which secondary data for Run Ansible Playbook Action does not show up in action summary page
**Before:**
Only shows Basic Information
**After:** 
Show both Basic Information and Run Ansible Playbook Information

Show Secondary Data for Run Ansible Playbook Action

---

app/javascript/forms/helper-text-block.jsx
app/javascript/spec/async-credentials/async-credentials.spec.js

In providers screen, when validate is clicked, if api call is giving error, it is not displaying. It is supposed to display, but css is stopping from showing, fixed it in this pr.
**Before**
**After**

Fix validation error message display in providers screen

---

app/helpers/flavor_helper/textual_summary.rb
spec/helpers/flavor_helper/textual_summary_spec.rb

The flavor model's cpu attributes had vague meanings leading to
confusion, and also were different from the hardware model's cpu
attributes used by VMs and Hosts.
The `#cpus` property was used as the "total vcpus/cores" where
`#cpu_cores` was typically used as "sockets" despite the name.
Depends on:
https://github.com/ManageIQ/manageiq/issues/21192

Rename Flavors cpus -> total_cpu_cores and add cpu_sockets

---

app/javascript/components/gtl/DataTable.jsx
lib/gtl_formatter.rb
product/views/ManageIQ_Providers_InfraManager_Template.yaml
product/views/ManageIQ_Providers_InfraManager_Vm.yaml
product/views/VmOrTemplate.yaml
spec/controllers/application_controller/report_data_spec.rb

Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7772
**Before**
**After**

Add operating system and background icon for powerstate in vms table

---

spec/helpers/application_helper/buttons/widget_generate_content_spec.rb

**Requires** https://github.com/ManageIQ/manageiq/pull/21241
Updates the record generation code so it properly adds a member to the set after the `ActsAsMiqSet` changes.
Links
-----
* https://github.com/ManageIQ/manageiq/pull/21241
* https://github.com/ManageIQ/manageiq/issues/21246

[widget_generate_content_spec.rb] Fix let(:record)

---

app/helpers/configuration_script_helper.rb
app/views/configuration_script/show.html.haml

When selecting a row from a data table, if the row is nil these changes will ensure that the exception is caught and the details will be shown (even if there are none because it is nil).
Fixes [#7745](https://github.com/ManageIQ/manageiq-ui-classic/issues/7745)
@miq-bot assign @kavyanekkalapu 
@miq-bot add_reviewer @kavyanekkalapu 

Resolving nil UI exception

---

app/presenters/custom_buttons_mixin.rb

Now that `acts_as_miq_set` doesn't use `RelationshipMixin`, `.parent` is no longer a valid method.
This fixes that by doing something similar that was done in `CustomActionsMixin` in core:
https://github.com/ManageIQ/manageiq/commit/01443d25
Links
-----
* FIXUP followup for https://github.com/ManageIQ/manageiq/issues/21246#issuecomment-881699321
* Login
* Go to `Automation -> Embedded Automate -> Custimization`
* With this patch, confirm the page loads
(will raise an error when it doesn't)
To apply the patch, you can do the following to your local `manageiq-ui-classic` repo:
```console
$ git apply <(curl -L https://github.com/ManageIQ/manageiq-ui-classic/pull/7791.patch)
```

[custom_buttons_mixin.rb] Fix for MiqSet change

---

app/stylesheet/charts.scss
package.json

Remove dom-to-image package as it is added as dependency from carbon charts 0.41.84 version, also fixed charts css after recent updated to charts package.
**Before:**
**After:**
@miq_bot add_reviewer @Fryguy

Remove dom-to-image package and fix charts css

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js

CHAP user and secret must be mandatory when CHAP authentication is selected

Changed CHAP authentication validation

---

app/controllers/miq_ae_customization_controller.rb

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7021

Fixed error message persists across customization  explorer modules

---

package.json

Carbon charts 0.41.91 on wards seeing fonts issues in Manageiq UI, so for now locking to 0.41.90 until we figure out the root cause fully.
**Before**
**After**

Lock carbon charts version to fix fonts issue

---

app/controllers/application_controller/buttons.rb
app/controllers/miq_ae_customization_controller/custom_buttons.rb

**Before:**
**After:**
@miq_bit assign @NickLaMuro 
@miq_bot Add_reviewer @NickLaMuro

Fix for miq_set_change for custom button create

---

package.json

Fonts issue is fixed in below prs, so reverted the locking the carbon charts version.
https://github.com/carbon-design-system/carbon-charts/pull/1095
https://github.com/carbon-design-system/carbon-charts/pull/1096
**After:**

Revert carbon charts change for fonts issue

---

app/controllers/application_controller/ci_processing.rb
app/javascript/components/gtl-view.jsx

In Configuration Management--> Providers, Refresh Relationships and Providers functionality is broken, Once the Button is clicked, providers are disappearing.
**Before**
**After**
@miq_bot add_reviewer @agrare

Fix Refresh and powerstate of configuration provider

---

app/javascript/packs/provider-dialogs-common.js
app/javascript/provider-dialogs/modal.js

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7784
This will provide ability add a custom function on close in provider dialogs. Default close function will execute after custonm function. 
@miq-bot Add-label enhancement

Ability to add custom close function to modal

---

app/controllers/miq_alert_controller.rb

In Control--> Alerts, Add/Edit page have same title.
**Before:**
add a new alert:
edit an alert:
**After:**
add a new alert:
edit an alert:

Add Different Titles for Alert Page New/Edit 

---

app/controllers/miq_action_controller.rb

In Control--> Actions, Add/Edit page have same title
**Before:**
add a new action:
edit an action:
**After:**
add a new action:
edit an action:

Add Different Title Name for Action Form When Add/Edit

---

app/controllers/application_controller/ci_processing.rb

Raising this pr https://github.com/ManageIQ/manageiq-ui-classic/pull/7811 for Lasker

[LASKER] Fix refresh powerstate  action for configuration managers

---

app/javascript/components/cloud-volume-form/index.jsx

This PR is part of PRs that solve Autosde cloud volume editing
before:
- storage manager name is not selected and also disabled, so it's impossible to edit the volume since name is mandatory
- storage pool is not selected. storage pool should be pre-selected and disabled since it cannot be changed
after:
In order to enable autosde cloud volume editing we need to pass info about the selected cloud volume.
I therefor passed the recordID to the cloud_volume api 
Links
https://github.com/ManageIQ/manageiq-api/pull/1056
https://github.com/ManageIQ/manageiq-providers-autosde/pull/72

Add recordID info to params passed to cloud_volumes api

---

product/views/HostInitiator.yaml

two fields were added to host initiators listing page:
- status
- host_cluster_name
links
--------
https://github.com/ManageIQ/manageiq-providers-autosde/pull/73 - need to be merged before this PR
https://github.com/ManageIQ/manageiq-schema/pull/594 - need to be merged before this PR

Add status and host_cluster_name to host_initiators table

---

manageiq-ui-classic.gemspec

Lockdown execjs to 2.7.0
It's unclear why but the change to make node wait for STDOUT to flush before
exiting seems to be causing ExecJS.compile to exit 1 with "ok" in some
environments for some files.
https://github.com/rails/execjs/commit/a6abf130c721ca6ec05cfc7ed79cf2e87a7dcc35
See https://github.com/rails/execjs/issues 105
Note, 2.8.0 seems to be ok but since 2.7.0 is the version we were using for a while, we're going back to that for now.

Lockdown execjs to 2.7.0

---

app/helpers/cloud_volume_helper/textual_summary.rb
product/views/CloudVolume.yaml
spec/helpers/cloud_volume_helper/textual_summary_spec.rb

added columns and props for the health state of cloud volume
this PR depends on https://github.com/ManageIQ/manageiq-schema/pull/598

added columns and props for health state of cloud volume

---

app/helpers/application_helper.rb

This GitHub [search](https://github.com/ManageIQ/manageiq-ui-classic/search?q=type_has_quadicon&type=code) shows no callers

Remove unused ApplicationHelper#type_has_quadicon method

---

lib/manageiq/ui/classic/engine.rb
manageiq-ui-classic.gemspec

We have removed all coffee script files
see  eb4bfaadbbf244a5c6a4d49a7f5bc95a1d9f1aa7
This is removing the dependency
@kavyanekkalapu thanks for the help with tracking down some of these dependencies
uglifier and ruby sass are the next on the docket but those look like they are still hanging on
/cc @Fryguy

No more coffee (gem) for rails

---

app/controllers/application_controller/ci_processing.rb
spec/controllers/application_controller/ci_processing_spec.rb

Ultimate goal is to delete the entire method, but maybe it makes sense to trim it down first until all the lists are empty (thus making this method meaningless).
The untestable items are:

Trim ApplicationController::CiProcessing#testable_action method

---

app/controllers/mixins/ems_common.rb

Issue: [7787](https://github.com/ManageIQ/manageiq-ui-classic/issues/7787)
**Before:** 
**After:** 
**Depends on:** 

Fix IBM storageManager id for Cloud Volume Form

---

app/controllers/application_controller.rb

This method is only called with "clone", "migrate" and "publish".
All of these are now supported via SupportsFeatureMixin

Simplified logic in ApplicationController#task_supported method to *always* use SupportsFeatureMixin

---

app/controllers/catalog_controller.rb
app/views/catalog/_form_ovf_template_options.html.haml
app/views/catalog/_sandt_tree_show.html.haml
spec/controllers/catalog_controller_spec.rb

Introduces the Datacenter field and calls the `refresh_field_values` method anytime a dialog field is selected which synchronizes the fields, filtering out unrelated dialogs.
Related to: https://github.com/ManageIQ/manageiq/pull/20895 and https://github.com/ManageIQ/manageiq-providers-vmware/pull/680
Before: 
After:

Ensured Related Dialog Fields are Synchronized when Adding a New OVF Service Template

---

manageiq-ui-classic.gemspec

ExecJS 2.8.1 requires uglifier 4.2.0 to defer uglifier asset compilation until asset
compilation time, see: https://github.com/rails/execjs/issues/105
Trying to compile the uglfier assets in production mode in an environment with
dynatrace was causing conflicts with the execjs node runtime and the dynatrace
reporting mechanism.  We should be able to avoid this entirely if we only call
out to node for asset compilation when we do explicit asset compilation at build
time in a controlled environment without dynatrace instead of at runtime, which
we cannot control.

Latest uglifier, 4.2.0 prevents runtime uglifier asset compilation

---

app/views/chargeback_assignment/_compute_assignments.html.haml

Issue: In chargeback page assignments page, In any language other than English, When user selected option in `Assign to `  dropdown, below contents are not refreshing.
**Before**
**After**

Fix Chargeback assignments compute page translations.

---

app/javascript/components/breadcrumbs/breadcrumbs.jsx
app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
app/stylesheet/application-webpack.scss
app/stylesheet/breadcrumbs.scss
app/stylesheet/notifications.scss

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7845
Before
After

 breadcrumbs changed from pattern-fly to carbon

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js
app/javascript/components/physical-storage-form/physical-storage-form.schema.js
app/javascript/components/volume-mapping-form/volume-mapping-form.schema.js

This set of PRs is meant to limit some operations so that they can only be performed on EMSs that support them.
The operations in question all have to do with block-storage managers.
- Add a new storage-system to the EMS
- Add a new host-initiator to the EMS
- Add a new volume-mapping
Currently the only manger that supports these operations is the manageiq-providers-autosde. But there's nothing to stop users from trying to perform these operations on other block-storage managers, such as Cinder.
So we add features to represent these operations, and we filter by them in the UI-forms for the operations. 
Related PRs
https://github.com/ManageIQ/manageiq/pull/21387
https://github.com/ManageIQ/manageiq-ui-classic/pull/7837
https://github.com/ManageIQ/manageiq-providers-autosde/pull/77
The …

added new supported items to EMS

---

app/controllers/application_controller/buttons.rb
app/controllers/catalog_controller.rb
app/controllers/miq_ae_customization_controller.rb
app/javascript/components/button-group/helper.js
app/javascript/components/button-group/index.jsx
app/views/shared/buttons/_group_form.html.haml

When the button group form page is accessed from **Services / Catelogs / Catelogs Items > Configuration > Add New Button Group**, and when the **Cancel** button in the form is clicked -
**Before**
Back event does not work as expected.
**After**
URL dosen't change and goes back to previous page.

Button group form cancel event changes

---

app/helpers/cloud_volume_helper/textual_summary.rb
app/helpers/host_initiator_helper/textual_summary.rb

Trying to get into cloud-volume summary results with the following error:
`role_allows? no feature was found with identifier: ["host_initiators_show_list"]. Correct the identifier or add it to miq_product_features.yml. [cloud_volume/show]`
we get similar error for host-initiators summary:
`role_allows? no feature was found with identifier: ["cloud_volumes_show_list"]. Correct the identifier or add it to miq_product_features.yml. [host_initiator/show]`

Fix textual summary for cloud-volumes and host-initiators

---

app/javascript/components/retirement-form/index.jsx

Fixed an issue with the date select on the Set Retire Date form sending the date to the api in an array when the backend expects a string.

Fix date select in retirement form.

---

app/controllers/mixins/ems_common.rb
app/controllers/physical_storage_controller.rb
app/helpers/application_helper/toolbar/physical_storage_center.rb
app/helpers/application_helper/toolbar/physical_storages_center.rb
app/javascript/components/physical-storage-form/index.jsx
app/javascript/components/physical-storage-form/physical-storage-form.schema.js
app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap
app/javascript/spec/physical-storage-form/physical-storage-form.spec.js
app/views/physical_storage/edit.html.haml
app/views/physical_storage/new.html.haml
config/routes.rb

This PR add new feature for physical-storages, the ability to edit an existing physical-storage. We can change the storage name and/or the storage credentials (management-ip, user and password)
links
-----
https://github.com/ManageIQ/manageiq-providers-autosde/pull/76
https://github.com/ManageIQ/manageiq-api/pull/1066

New feature - Editing physical storage

---

app/javascript/menu/item-type.js

Go to Setting > ManageIQ.org will put the MIQ page in loading state forever.
**STR:**
- Lets start from the Overview page
- Click on Go to Settings > ManageIQ.org , this will open support link in new tab.
- Click on MIQ tab, now overview page is showing loading symbol.
**Before**
**After**

Fix loading symbol for doc link click.

---

app/javascript/components/retirement-form/retirement-form.schema.js
app/javascript/menu/item-type.js

**Steps to Reproduce**
- Select a cloud vm and from Lifecycle down select "Set Retirement Dates"
- On the Retire VMs and Instances page, select "Time Delay from Now" on the "Enter Retire Date as" field.
- From the Time Delay section, you can change the all the field to a negative number
**Before**
**After**

Fix negative value in  vm retire form

---

app/presenters/menu/item.rb

ruby is complaining
```
app/presenters/menu/item.rb:38: warning: Using the last argument as keyword parameters is deprecated;
maybe ** should be added to the call
app/helpers/application_helper.rb:99: warning: The called method `role_allows?' is defined here
```

remove kwargs warning for menu item

---

app/javascript/components/catalog-form/catalog-form.jsx
app/javascript/components/cloud-network-form/cloud-network-form.jsx
app/javascript/components/cloud-tenant-form/index.jsx
app/javascript/components/copy-catalog-form/copy-catalog-form.jsx
app/javascript/components/copy-dashboard-form/copy-dashboard-form.jsx
app/javascript/components/edit-service-form/index.jsx
app/javascript/components/firmware-registry/firmware-registry-form.jsx
app/javascript/components/flavor-form/index.jsx
app/javascript/components/orchestration-template/orcherstration-template-form.js
app/javascript/components/pxe-servers-form/pxe-server-form.jsx
app/javascript/components/region-form/index.jsx
app/javascript/components/remove-catalog-item-modal.jsx
app/javascript/components/remove-generic-item-modal.jsx
app/javascript/components/service-dialog-from-form/service-dialog-from.jsx
app/javascript/components/set-ownership-form/index.jsx
app/javascript/components/taggingWrapper.jsx
app/javascript/components/vm-server-relationship-form/index.jsx
app/javascript/components/vm-snapshot-form/vm-snapshot-form.jsx
app/javascript/components/workers-form/workers-form.jsx
app/javascript/spec/catalog-form/__snapshots__/catalog-form.spec.js.snap
app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
app/javascript/spec/cloud-tenant-form/__snapshots__/cloud-tenant-form.spec.js.snap
app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap
app/javascript/spec/pxe-servers-form/__snapshots__/pxe-server-form.spec.js.snap
app/javascript/tagging/components/Tagging/Tagging.js
app/javascript/tagging/components/TaggingWithButtons/TaggingWithButtons.jsx
app/javascript/tagging/tests/__snapshots__/tagging.test.js.snap
app/stylesheet/ddf_override.scss

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/7847
Converted the patternfly-react Spinner and Grid components to carbon-components-react.
Before:
After:

Converted spinner and grid from patternfly to carbon react

---

app/views/container_project/show.html.haml
app/views/shared/views/ems_common/_show.html.haml

According to https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-raw-file, this ~would never work~ is deprecated.  Spotted while reviewing Travis runs.
An example: `DEPRECATION WARNING: render file: should be given the absolute path to a file (called from ___sers_oleg__rojects__anage___manageiq_ui_classic_app_views_shared_views_ems_common__show_html_haml__2976362415708902536_70183127350080 at /Users/oleg/Projects/ManageIQ/manageiq-ui-classic/app/views/shared/views/ems_common/_show.html.haml:36)`

Fix render :file to :template

---

app/controllers/mixins/generic_button_mixin.rb

SupportsFeatureMixin::QUERYABLE_FEATURES was removed in https://github.com/ManageIQ/manageiq/pull/21046

Stop using SupportsFeatureMixin::QUERYABLE_FEATURES

---

app/javascript/components/service-request-default/index.jsx

Currently, when you press `Reset` on Master, the values in the Data Table rows will not reset, they will remain filtered according to the prior user selected filters.

Fixing onReset functionality for Services > Requests Page

---

app/javascript/menu/item-type.js

This is originally fixed in https://github.com/ManageIQ/manageiq-ui-classic/pull/7864.
Somehow changes were overwritten in https://github.com/ManageIQ/manageiq-ui-classic/pull/7865( Note: it is not showing in files changed). so doing these changes again to fix bug.

Fix doc link loading symbol.

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js

Adding host initiator ability: create new host-initiator with  multiple wwpn for FC port
before:
after:
links
------
https://github.com/ManageIQ/manageiq-providers-autosde/pull/81

Add support for creating multiple host initiators wwpn

---

app/controllers/application_controller/tags.rb
spec/controllers/application_controller/tags_spec.rb

Fixes editing of tags, where instead of passing in the proper adds and deletes, all tags were passed in as deletes and adds, and only because adding comes after deleting did this work previously, but at the cost of performance.
By ensuring we are doing array subtraction with the same types, it fixes the `:add_ids` and `:delete_ids` from being incorrect and causing a surge of ActiveRecord queries when it isn't necessary.
Links
-----
* Addresses https://github.com/ManageIQ/manageiq/issues/21444
I have some scripts that I used to validate this change, but I need to update them to work against a fresh DB.  Will update this section with a link to a gist when I am able to put those together.

[ApplicationController::Tags] Fix bulk_reassignment

---

app/javascript/components/taggingWrapper.jsx

**Issue:** In provision vm screen, for category that should allow multi tag assignments, it is allowing only one.
**Before**
**After**

Fix provision screen multi tags assignment

---

app/controllers/miq_request_controller.rb
app/javascript/components/taggingWrapper.jsx
app/javascript/pf-select/pf-select.jsx
app/javascript/tagging/components/InnerComponents/CategoryModifier.js
app/javascript/tagging/components/InnerComponents/Tag.js
app/javascript/tagging/components/InnerComponents/TagCategory.js
app/javascript/tagging/components/InnerComponents/TagSelector.js
app/javascript/tagging/components/InnerComponents/TagView.js
app/javascript/tagging/components/InnerComponents/ValueModifier.js
app/javascript/tagging/components/InnerComponents/ValueSelector.js
app/javascript/tagging/components/Tagging/Tagging.js
app/javascript/tagging/tests/__snapshots__/category.modifier.test.js.snap
app/javascript/tagging/tests/__snapshots__/tag.category.test.js.snap
app/javascript/tagging/tests/__snapshots__/tag.modifier.test.js.snap
app/javascript/tagging/tests/__snapshots__/tag.selector.test.js.snap
app/javascript/tagging/tests/__snapshots__/tag.test.js.snap
app/javascript/tagging/tests/__snapshots__/tag.view.test.js.snap
app/javascript/tagging/tests/__snapshots__/tagging.test.js.snap
app/javascript/tagging/tests/__snapshots__/value.modifier.test.js.snap
app/javascript/tagging/tests/__snapshots__/value.selector.test.js.snap
app/views/miq_request/_prov_field.html.haml
app/views/shared/views/_prov_dialog.html.haml

The `Purpose Tag` in the Service Request page should not be editable by users. 
If a user changes the values in the dropdown to try and add more tags the edit will be aborted with error. Additionally users shouldn't be able to edit it in the first place. 
Drop down is disabled and so is the `x` to remove tags. 
With Tags
No Tags

User should not be able to edit Purpose Tags from Service / Request page

---

app/stylesheet/quadicon.scss

@kavyanekkalapu Please review.
Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/7838#issuecomment-955028478
Separately, do we even use the quadicon anymore?  Wondering if we can kill this file entirely.

Prefer math.div over / for division due to deprecation

---

app/javascript/components/retirement-form/helper.js
app/javascript/components/retirement-form/index.jsx
app/javascript/components/retirement-form/retirement-form.schema.js
app/stylesheet/ddf_override.scss

Fixes the issue of users being able to submit the retire form with a date in the past selected.

Fix issue allowing users to select previous dates on retire form

---

app/javascript/components/retirement-form/retirement-form.schema.js

Made retire form error string more informative

---

app/javascript/components/retirement-form/index.jsx

Fixed a bug with removing the retirement date of multiple vms at once.
**Before:**
**After:**

Fixed bug with removing retirement date for multiple instances

---

.stylelintrc
package.json
yarn.lock

This fixes about 18 warnings that center around at-rules that are scss
specific.
@kavyanekkalapu Please review.

Add stylelint-scss

---

app/javascript/components/generic-objects-form/helper.js
app/javascript/components/generic-objects-form/index.jsx

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/7951
The generic objects form would not submit unless it had at least 1 of each attribute, association and method. This issue is fixed and the form can now be submitted with 0 attributes, associations or methods.
Before:
After:
https://user-images.githubusercontent.com/32444791/141196145-0f94dc5f-b1a5-4db8-a251-57cef68b15f4.mov

Fixed generic objects form submit bug

---

lib/gtl_formatter.rb

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7962
**Before**
**After**

Fix vms table os  column image

---

app/views/layouts/_center_div_with_listnav.html.haml

Issue caused by https://github.com/ManageIQ/manageiq-ui-classic/pull/7953
**Before** 
Filter is not working.
**After**

Fix generic objects view filter

---

app/controllers/application_controller/timelines/options.rb

Broken by https://github.com/ManageIQ/manageiq/pull/21569
The constant was defined in the base class, but was actually an EmsEvent concern
so this was moved to a method for subclasses to override.

Use the group_levels method since the constant was removed

---

app/helpers/application_helper.rb
app/helpers/orchestration_stack_helper/textual_summary.rb

This was deprecated in 2016, removing the last call to the old format
pulled this out of https://github.com/ManageIQ/manageiq-ui-classic/pull/7949
@fryguy you already reviewed this [here](https://github.com/ManageIQ/manageiq-ui-classic/pull/7949#discussion_r744937247). pulling out since it is not role related

drop role_allows helper

---

app/controllers/host_initiator_group_controller.rb

MIQ team have found an incorrect text in one of our breadcrumbs:
https://github.com/ManageIQ/manageiq-ui-classic/pull/7881#issuecomment-965272731
The section is Host Initiator Groups. The bread crumb incorrectly says Hosts Cluster Initiators.

setting host-initiator-groups breadcrumb to Host Initiator Groups

---

app/javascript/components/fonticon-picker/index.jsx
app/javascript/spec/async-credentials/edit-password-field.spec.js

**$ git grep patternfly-react**
```
app/javascript/components/fonticon-picker/index.jsx:6:} from 'patternfly-react';
app/javascript/spec/async-credentials/edit-password-field.spec.js:4:import { HelpBlock } from 'patternfly-react';
config/webpack/shared.js:33:  'patternfly-react',
package.json:85:    "patternfly-react": "2.39.14",
yarn.lock:13851:    patternfly-react: 2.39.14
yarn.lock:16170:"patternfly-react@npm:2.39.14":
yarn.lock:16172:  resolution: "patternfly-react@npm:2.39.14"
```
Below items are handled in PR https://github.com/ManageIQ/manageiq-ui-classic/pull/7967
```
app/javascript/components/data-tables/gtl/utils.js:9:} from 'patternfly-react';
app/javascript/components/report-data-table.jsx:17:} from 'patternfly-react';
app/javascript/spec/report-data-table.spec.js:5:import { …
```

Remove patternfly-react references in button form and test files.

---

app/controllers/host_aggregate_controller.rb
app/helpers/application_helper/button/auth_key_pair_cloud_create.rb
app/helpers/application_helper/button/new_host_aggregate.rb

Cleanup the `.descendants.select { |klass| klass.supports?(:create) }` calls to use the new  `providers_supporting` call added to SupportsFeatureMixin.
Depends on:

Use `.providers_supporting` from SupportsFeatureMixin

---

app/controllers/ops_controller/ops_rbac.rb
app/helpers/application_helper.rb
spec/helpers/application_helper/buttons/catalog_item_button_spec.rb

Depends upon:
For ruby 3.0, we need to be more explicit around keyword args.
Also following through on comment from [authorizer.rb](https://github.com/ManageIQ/manageiq/blob/a0625967a209c2abce9870af72f58700c5c8abfd/lib/rbac/authorizer.rb#L18-L21)
> The 'identifiers' option comes from the former User#role_allows_any? API
> It should be noted that there may be only ONE caller using 'identifiers'
> in Menu::Section, so this option may be changed shortly.
The code passed in multiple features via `identifiers: []`. If `identifiers` goes away,
then `Rbac.role_allows?` needs to accept `features: []`. The required PR in core makes this change
so we can avoid the `:identifiers` parameter.
What was done:
- convert hash syntax to kwargs (ruby 3.0)
- remove call to `User#role_allows_any?` and go …

KWArgs Role

---

app/javascript/components/volume-mapping-form/index.jsx
app/javascript/components/volume-mapping-form/volume-mapping-form.schema.js

Part of https://github.com/ManageIQ/manageiq-providers-autosde/issues/116
Needs to be merged after https://github.com/ManageIQ/manageiq-providers-autosde/pull/117
When creating a volume mapping the user can now either map to a Host Initiator as before or to a group.

Volume mapping can now be done for Host Initiator Groups

---

app/javascript/components/data-tables/button-group-list/helper.js
app/javascript/components/data-tables/button-list/helper.js
app/javascript/components/data-tables/db-list/helper.js
app/javascript/components/data-tables/gtl/DataTable.jsx
app/javascript/components/data-tables/optimization/helper.js
app/javascript/components/data-tables/reports/helper.js
app/javascript/components/data-tables/role-list/helper.js
app/javascript/components/miq-data-table/helper.js
app/javascript/components/miq-data-table/index.jsx
app/javascript/components/miq-data-table/miq-table-cell.jsx
app/javascript/spec/miq-data-table/__snapshots__/miq-data-table.spec.js.snap
app/javascript/spec/miq-data-table/data.js

Table cells which have icons only are combined with the next cell.
**1. Catalog Items**
Before
After
**2. Button groups list**
Before
After
**3. Button list**
Before
After
**4. Reports**
Before
After
**5. Report / select-an-Item**
Before
After
**6. Report / select-an-item / select-an-item**
Before
After
**7. Reports / Edit Report Menu**
Before
After
**8. Reports / Dashboard**
Before
After
**9. Reports / Dashboard / All Groups**
Before
After
**10. Reports / Dashboard / All Groups / select-an-item**
Before
After

Combine icon cell with name cell of data tables

---

app/helpers/textual_listview.rb
app/javascript/react/table_list_view_wrapper.js

Fixes: https://github.com/ManageIQ/manageiq/issues/21626
Added nil check to prevent error when the template summary page encounters a template with no variables.
Template page with variables:
New template page for templates with no variables:

Fixed values_at bug

---

app/views/layouts/_x_adv_searchbox.html.haml

Search bar was visible in few summary pages.
**Before**
**After**

Hide search bar in summary page

---

app/views/layouts/_searchbar.html.haml

Searchbox was visible in summary page 
Before
After

Hiding search box in summary pages

---

app/javascript/oldjs/i18n.js
app/javascript/oldjs/jquery_overrides.js
app/javascript/oldjs/miq_application.js

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8008
For WEBMKS, We are directly calling i18n.js without calling oldjs/application.js ( https://github.com/ManageIQ/manageiq-ui-classic/blob/83070ce0a3b7db143f9ea5ffa7ff9f37b5ce4f45/app/javascript/packs/remote_consoles_vnc.js#L3) 

Add miq_global.js dependency for ManageIQ variable.

---

app/javascript/components/physical-storage-form/physical-storage-form.schema.js
app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap

some fields are missing **only in Morphy version (Not in master)** when trying to create new physical storage.
in M release
-------------
expected / in master
------------------------
the problem with the new physical storage form is because one of the variables used is not initialized correctly.
we have an hidden text field in the form that use to determine if we are in edit mode or new mode. the default value of the field is empty string, and in edit mode it set to 'yes'. for some reasone in the M release the default value (empty string) is not set correctly, and the fix for that is adding to that field the following attribute: initialValue: ''
I dont know why the default value is not working like we expect in the M release. in the master branch it works like expected (empty text fields …

fixing edit hidden field initial value

---

app/javascript/components/miq-data-table/index.jsx

When we select a row in Provision instance, the row background will now be highlighted.
Before
After

Fix row highlight in provision instance

---

app/stylesheet/miq-data-table.scss

Added some padding to bottom of the time profile reports table.
Before:
After:

Added space under time profile reports

---

app/javascript/components/volume-mapping-form/volume-mapping-form.schema.js

Volume can't be mapped to an empty host-initiator-group (host-cluster). In this PR I did the required changes so only optional host-initiator-groups are listed when mapping a new volume to an host-initiator-group. 
Empty host-initiator-groups are therefore not listed.
in the images below you can see that empty host-initiator-groups are not listed in the selection field:

show only relevant info in host-init-group field under volume-mapping

---

app/presenters/tree_node/node.rb

Always send the object if a block is given to set_attribute
set_attribute used to send more arguments (object, parent_id, options, etc) to
the instance_exec.  It has been simplified to only pass object and parent_id but
we only ever use the object.
Because of 2.7/3.0 differences described below, we can further simplify this and
just send the object if a block is given.  For blocks that take no arguments, it is
simply unused.
In ruby 3.0, Symbol#to_proc returns a lambda with different arity than ruby 2.7.
Note, an arity of -1 means that all parameters are optional.
An arity of -2 means that 1 parameter is required and any other parameters are
optional.
See: https://ruby-doc.org/core-3.0.0/Proc.html#method-i-arity
Since ruby 2.7's arity on Symbol#to_proc looks wrong, it's better to not even …

Only send arguments to the receiver if the block accepts them

---

app/views/ems_storage/edit.html.haml

In Morphy, trying to edit storage manager from the dashboard results with the following error:
EmsStorageController#edit is missing a template for request formats: text/html [ems_storage/edit]
Note! It works OK in master/latest, and also works ok in morphy for other providers (tested on vmware), except for an additional issue which describes in section 2 below.
before
--
after
--
if we try to edit from the storage list page it works ok
links 
-----
https://github.com/ManageIQ/manageiq-ui-classic/issues/8020

[morphy] Fix edit ems storage

---

app/javascript/components/dashboard-charts/emptyChart.js
app/javascript/components/dashboard-charts/index.jsx

Carbon empty chart is confusing. It seems data is not loaded properly in chart.
**Before**
**After**

Fix dashboard empty chart

---

app/controllers/host_controller.rb

Fixed the breadcrumb and title for the edit infrastructure hosts page.
Before:
After:

Fixed infrastructure hosts breadcrumbs

---

manageiq-ui-classic.gemspec

This will allow rails 6.1 and 6.0 but still should be governed by what the default is in core so this is just relaxing requirements.  Or should be.

Allow rails 6.1/6.0

---

app/views/miq_request/_prov_dialog_volume_fieldset.html.haml

Changed line of code that was only displaying volume data if both name & size fields were populated even though the data was there in `@edit` hash.
fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/7400
/cc @iv1111 please test, validation for these fields should be done by backend.

Display all added/saved volume data in UI.

---

app/views/miq_request/_prov_dialog_volume_fieldset.html.haml

If a boolean field is checked, unchecked and then checked again,
then its value is set to 'null' *string*. A string however
evaluates to a 'true' value and thus the checkbox gets a sticky
'checked' state

Fix volumes boolean fields in '_prov_dialog_volume_fieldset.html.haml'

---

app/javascript/angular/dashboard/widget-wrapper.js
app/views/dashboard/_widget.html.haml

Users where able to drag and drop widgets in the dashboard regardless if they had the dashboard view or add role.
When users with only view permissions tried to do this, an error would appear on screen which told them they didn't have
the correct permissions. With this change users with only the view rights will not be able to move widgets.

Prevent drag drop widgets with dashboard_view role

---

app/stylesheet/miq-data-table.scss

Custom reports table widgets from dashboard when displayed in Full screen
Before
After

Fix style for full screen dashboard custom report

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
app/javascript/components/cloud-volume-form/index.jsx

Removed unnecessary code from the files for the cloud volume form. Also updated the form so that it will clear the page from all provider fields when the user selects no storage manager. Also, added a load symbol while the form is loading in provider fields.
Before:
After:

Fix cloud volume form

---

app/javascript/components/data-tables/report-data-table/report-data-table.jsx
app/javascript/spec/report-data-table.spec.js

When you Run the Queue to have a Chargeback report and the report comes when you go inside the report you Search for a word that is not under that report a No records found will show up. But to continue searching there was no back button to perform a new search.
Before
After

Fix toolbar reset for chargeback reports

---

app/helpers/application_helper/button/button_template_clone.rb
app/helpers/application_helper/toolbar/template_infras_center.rb

Template cloning is not yet implemented in IBM Power HMC infrastructure provider, so disabling it.
Before:
After:

Disable template cloning for IBM Power HMC infrastructure provider

---

app/helpers/miq_ae_class_helper.rb

Console error when we open the properties tab under Automation module
Before
After

Fix automation structured list

---

app/javascript/components/performance-charts/areaChart.js
app/javascript/components/performance-charts/index.jsx
app/javascript/components/performance-charts/lineChart.js
app/stylesheet/charts.scss
app/views/layouts/_perf_chart_js.html.haml

Fixed performance chart titles for utilization charts tabular representation.
Before:
After:

Fix performance charts titles

---

app/javascript/components/cloud-network-form/cloud-network-form.jsx
app/javascript/components/cloud-network-form/cloud-network-form.schema.js
app/javascript/components/cloud-volume-form/index.jsx
app/javascript/components/network-floatingIPs-form/index.jsx
app/javascript/components/network-floatingIPs-form/network-floatingIPs-form.schema.js
app/javascript/components/network-security-groups-form/index.jsx
app/javascript/components/network-security-groups-form/network-security-groups-form.schema.js
app/javascript/components/routers-form/RoutersForm.schema.js
app/javascript/components/routers-form/index.jsx
app/javascript/components/subnet-form/index.jsx
app/javascript/components/subnet-form/subnet-form.schema.js
app/javascript/spec/cloud-network-form/__snapshots__/cloud-network-form.spec.js.snap
app/javascript/spec/network-floating-ip-form/__snapshots__/network-floating-ip-form.spec.js.snap
app/javascript/spec/network-router-form/__snapshots__/network-router-form.spec.js.snap
app/javascript/spec/network-security-groups-form/__snapshots__/network-security-groups-form.spec.js.snap
app/javascript/spec/subnet-form/__snapshots__/subnet-form.spec.js.snap
app/stylesheet/ddf_override.scss

Used validation to check for an empty network manager field in forms that use emptySchema. Previously used a plain text component to warn the user but could not visually disable the save button. This is changed to instead use validation which warns the user and disables the button as well. Also, fixes the emptySchema on the floating IPs form.
Before:
After:

Added validation to forms with emptySchema

---

product/views/ManageIQ_Providers_CloudManager_Template.yaml
product/views/ManageIQ_Providers_CloudManager_Vm.yaml
product/views/SecurityGroup.yaml

Fix for Providers column inconsistency issue in table header
**1.Instances - Provider to Cloud Provider**
Before
After
**2.Images - Provider to Cloud Provider**
Before
After
**3.Security Group - Cloud Provider to Network Provider**
Before
After

Fix Providers column inconsistency issue in table header

---

app/controllers/application_controller/miq_request_methods.rb
spec/controllers/application_controller/miq_request_methods_spec.rb

When check/uncheck 'Hide deprecated' checkbox, the column headers were changed
Before
After

Fix provision show/hide deprecate column mismatch

---

app/views/ops/_all_tabs.html.haml

In podified env, we are not allowing user to upload custom logos. So, hiding custom logos tab in this issue
**Before**
**After**

Hide custom logos upload tab for podified env

---

app/javascript/components/provider-dashboard-charts/pod-trend-charts/podsAreaChart.js
app/javascript/components/provider-dashboard-charts/recent-host-chart/hostLineChart.js
app/javascript/components/provider-dashboard-charts/recent-vm-chart/index.js
app/javascript/components/provider-dashboard-charts/recent-vm-chart/vmAreaChart.js
app/javascript/components/provider-dashboard-charts/usage-network-image-charts/index.js
app/javascript/components/provider-dashboard-charts/usage-network-image-charts/usageAreaChart.js
app/services/ems_dashboard_service.rb

**Before**
title is undefined and data is not in order
**After**

Fix provider dashboard charts title and sort order

---

app/controllers/pxe_controller/iso_datastores.rb
app/helpers/application_helper/button/iso_datastore_new.rb

- enable button check for iso_datastores now uses the supports feature
- part of the work to split oVirt provider
Depends on: 
- https://github.com/ManageIQ/manageiq/pull/21726
- https://github.com/ManageIQ/manageiq-providers-ovirt/pull/596

Add supports iso_datastore checks

---

app/stylesheet/legacy/patternfly_overrides.scss

the alignment of the divider line in chart panel is off
**Before**
**After**

Fix dashboard charts footer css

---

app/stylesheet/legacy/patternfly_overrides.scss

When zoom in , advanced search modal is hiding under left nav.
**Before**
**After**
zoom in screenshot

Fix advanced search modal css

---

app/views/condition/_form.html.haml

**Before**
In the condition's new form page, after entering the value in the **Description** field and then changing the **Applies to** drop down field, the description field will be cleared.
**After**

Fix Conditions description clear issue when dropdown value changes

---

app/controllers/vm_common.rb
app/helpers/application_helper/page_layouts.rb
app/views/vm/edit.html.haml

Bug-> if we try edit instance from zones summary page, it is giving error.
**Steps to reproduce the behavior:**
- Select Availability Zones from compute-->clouds
- click a zone with instances
- Select Instances
- Click the box of the Instance
- Configuration -> Edit Selected Item
**Before**
**After**

Fix instance edit page from availability zone summary

---

app/views/ops/_logs_selected.html.haml

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8135

show zone collect logs

---

app/helpers/application_helper/button/host_initiator_group_new.rb
app/helpers/application_helper/button/host_initiator_new.rb

We can delegate the lookup of the correct provider `HostInitiator` and `HostInitiatorGroup` constants to `class_by_ems` and avoid some constantizing.

Use class_by_ems to access correct provider class

---

app/javascript/components/remove-generic-item-modal.jsx

Deleting a volume works only from the volume listing page. If going from storage manager dashboard we get error:
```
URL https://9.151.190.43/api/cloud_volumes/3/?attributes=supports_safe_delete
Status 404 Not Found
Content-Type application/json; charset=utf-8
Data {"error":{"kind":"not_found","message":"Couldn't find CloudVolume with 'id'=3","klass":"ActiveRecord::RecordNotFound"}}
```
going to the volume listing page from the storage dashboard pass the storage provider recordId (see the url in the images below) and therefore it cause error since the code expected that if a recordId pass its the volume recordId.
The correct way is to check the gridChecks first and use its value if exists. only if the gridCheck is empty use the recordId which must be supllied in that case and must be the …

populate itemIds with gridchecks values if such values exists

---

app/javascript/components/provider-dashboard-charts/helpers.js

**Before**
**Bug:** Provider dashboard is showing previous than created date.
**Before**
**After**

fix date format in provider dashboard charts

---

app/helpers/application_helper/toolbar/template_clouds_center.rb
app/helpers/application_helper/toolbar/x_template_cloud_center.rb

We cannot do Right-Size for images. So, removing that button from toolbar.
core pr-> https://github.com/ManageIQ/manageiq/pull/21752
**Before**
**After**

Remove image Right-Size button from toolbar

---

app/javascript/components/async-credentials/async-credentials.jsx

Issue: If a user edits a provider region, verification is _not_ required and the validate button is not activated. It should be activated and verification should be required.

Validate provider fields in edit form.

---

app/controllers/dashboard_controller.rb

Fixed dashboard widget remove. When trying to remove a dashboard widget clicking remove does not actually remove the widget. This fix allows results in the widget being removed from the dashboard after clicking remove widget.

Fixed dashboard widget remove

---

package.json
yarn.lock

Upgraded carbon charts and carbon-charts react versions in order to fix missing toolbar for the pie chart.
Before:
After:

Updated carbon charts version

---

app/views/dashboard/login.html.haml
spec/views/dashboard/login.html.haml_spec.rb

put a form around the login form.
I only tested this with database authentication. using an enter to submit.
I did not bother adding an action to the form, since it is mostly driven by javascript anyway
fixes:
```
[DOM] Password field is not contained in a form:
```
This does not fix any errors, I just noticed this warning in my chrome console.
Since 2015 this has not been a form. I do not know if there is a technological reason that this would not be a form.

put the login into a form

---

app/views/cloud_tenant/_show_dashboard.html.haml
app/views/ems_cloud/_show_dashboard.html.haml
app/views/ems_physical_infra/_show_dashboard.html.haml
app/views/physical_infra_overview/show.html.haml

**Issue:** Part of https://github.com/ManageIQ/manageiq-ui-classic/issues/7603
We already converted the components of this page to react. So, we don't need miq_bootstrap anymore to render these pages.
@miq-bot add-label technical_debt

Remove miq_bootstrap from react pages

---

app/controllers/dashboard_controller.rb
app/controllers/report_controller/dashboards.rb
app/helpers/dashboard_helper.rb
app/javascript/oldjs/miq_application.js
spec/controllers/dashboard_controller_spec.rb
spec/controllers/miq_report_controller/dashboards_spec.rb

Removing col3 reference from dashboard since it is not used anymore
Related PR- https://github.com/ManageIQ/manageiq-schema/pull/641

Remove col3 reference from dashboard

---

app/javascript/components/ansible-repository-form/ansible-repository-form.schema.js
app/javascript/components/ansible-repository-form/helpers.jsx
app/javascript/spec/ansible-repository-form/helpers.spec.js

Fixes https://github.com/ManageIQ/manageiq/issues/21700
Related to https://github.com/ManageIQ/manageiq/issues/21700 and https://github.com/ManageIQ/manageiq-ui-classic/pull/8157

Adding ssh and url check for ansible repository form

---

app/views/configuration/timeprofile_edit.html.haml

Fixed an error preventing the add new time profile page from loading.
Before:
After:

Fixed add new time profile error

---

spec/config/routes.pending.yml

**Issue**
Follow up of https://github.com/ManageIQ/manageiq-ui-classic/pull/8177. interestingly test cases failed in the original pr until i added this route. Now in master. testcases are failing once all prs for native console got merged.
```
Finished in 4 minutes 25.1 seconds (files took 12.54 seconds to load)
6224 examples, 1 failure, 1238 pending
Failed examples:
rspec './spec/routes_spec.rb[1:42:24:2:1]' # Application routes EmsCloudController#launch_console RBAC check is enforced
Randomized with seed 10116
```

fix console route testcases

---

app/helpers/gtl_helper.rb
app/javascript/components/gtl-view.jsx

Fixes [#7795](https://github.com/ManageIQ/manageiq-ui-classic/issues/7795).

Remove double flash message

---

app/controllers/ems_infra_controller.rb
app/helpers/application_helper/toolbar/ems_infra_center.rb
config/routes.rb
spec/controllers/ems_infra_controller_spec.rb

Follow-up to https://github.com/ManageIQ/manageiq-ui-classic/pull/8177 adding for ems_infra providers.

Add native_console button for ems_infra providers

---

lib/gtl_formatter.rb

This does not depend upon another PR, but it will not be exercisable without core PR:
This does not change the view of the screen.
If a report is sorting by a ruby field (and the values are cached),
the `record` will not have all the attributes and an error is thrown.
We noticed this when sorting by `power_state` and either toggling the `power_state` ascend/descend for sort, or viewing the next (i.e.: second) page.
The fix is to access the `row` data instead of the `record` data. They have the same value but `row` always has the value. If you notice, all other gtl filters use `row[col]` to get the current value.
This fixes a bug introduced in b1a5e86c013e44
```
[----] F, [2022-03-23T18:05:15.645121 #87884:b9244] FATAL -- : Error caught:
[ActiveModel::MissingAttributeError] missing …
```

fix sort columns

---

app/presenters/menu/custom_loader.rb
app/presenters/menu/manager.rb
app/presenters/menu/yaml_loader.rb
spec/presenters/menu/custom_loader_spec.rb
spec/presenters/menu/custom_menu_loader_spec.rb
spec/presenters/menu/menu_manager_spec.rb

Depends:
All this data is stored in the menu manager
No reason to have separate caches nor a singleton
This is in an effort to remove a few Singleton classes
Related to https://github.com/ManageIQ/manageiq/pull/21770

Remove caching from menu manager custom loaders

---

app/views/physical_chassis/show.html.haml

Parent Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7603
Removed unused angular code from physical chassis haml files.
@miq-bot add-label cleanup

Remove angular code from physical chassis

---

app/javascript/components/service-detail-stdout/index.js

Fix missing header text ('Standard Output') added in this PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/8209
Before:
After:

Fix missing text in services page

---

app/views/shared/views/ems_common/_show.html.haml

Issue: Part of https://github.com/ManageIQ/manageiq-ui-classic/issues/7603
Remove unused angular code in ems common file. Similar to PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/8201
@miq-bot add-label technical debt

Remove angular code from ems common file

---

app/views/physical_storage/show.html.haml
app/views/physical_storage/show_list.html.haml

Issue: Part of https://github.com/ManageIQ/manageiq-ui-classic/issues/7603
Remove unused angular code in physical storage files. Similar to PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/8201
@miq-bot add-label technical debt

Removed angular code from physical storage files

---

app/javascript/components/miq-structured-list/index.jsx
app/javascript/react/textual_summary_wrapper.jsx
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/textual_summary.test.js.snap
app/stylesheet/miq-structured-list.scss

Before
After
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8210

 Fix missing PDF content for summary pages

---

app/javascript/components/fonticon-picker/icon-list.jsx
app/javascript/components/fonticon-picker/icon-modal.jsx
app/javascript/components/fonticon-picker/index.jsx

Fixed console errors for the icon picker component found on the add/edit button group form.
Fixed key error for the icon picker component:
Fixing the above error leads to this error being displayed from a separate issue when changing tabs in the icon picker component. This error is also fixed.

Fixed icon picker console errors

---

app/controllers/application_controller/ci_processing.rb
app/controllers/host_controller.rb

Getting an error when the cloud tenants link is clicked from host summary.
Before
After

Fix for displaying host summary's cloud-tenants page

---

app/controllers/service_controller.rb
spec/controllers/service_controller_spec.rb

Fixed bugs preventing the services -> my services page from loading.
Before:
After:
These lines were added in pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/6709 but after testing with these lines removed the issue mentioned in this pr no longer exists and the advanced search is still functional.

Fixed services page bug

---

app/javascript/components/subnet-form/subnet-form.schema.js

Fixes an issue introduced in this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/7815 causing missing fields in the subnet form.
Before:
After:

Fixed missing fields bug in subnet edit form

---

app/controllers/miq_ae_customization_controller/custom_buttons.rb

Fixed the unassigned buttons table list as it was displaying the assigned buttons instead.
Before:
The 2 buttons are assigned to 04test as is seen in the left nav but are displayed under the "Unassigned Buttons" table.
After:
Now the buttons are correctly displayed in the table.

Fixed unassigned buttons table list

---

app/controllers/ems_automation_controller.rb
app/controllers/miq_ae_class_controller.rb
app/controllers/restful_redirect_controller.rb
app/helpers/application_helper.rb
app/presenters/tree_builder.rb
app/presenters/tree_node/node.rb
product/views/ManageIQ_Providers_ExternalAutomationManager.yaml

Fixes https://github.com/ManageIQ/manageiq/issues/21743
Renamed automation managers yaml so that it shows all providers instead of ansible tower.
dependency pr- > https://github.com/ManageIQ/manageiq/pull/21740
**Before**
**After**

Rename automation managers file

---

app/controllers/application_controller.rb
app/stylesheet/carbon.scss
app/views/layouts/application.html.haml

Fix charts download  PNG/JPG issue

---

spec/controllers/cloud_volume_snapshot_controller_spec.rb

Sorry, forgot to include this with the others
part of: https://github.com/ManageIQ/manageiq-api/pull/1134
```
Failures:
1) CloudVolumeSnapshotController#delete #delete queues the delete action
Failure/Error: snapshot.delete_snapshot_queue(session[:userid])
#<MiqTask (class)> received :generic_action_with_callback with unexpected arguments
[...]
rspec ./spec/controllers/cloud_volume_snapshot_controller_spec.rb:76 # CloudVolumeSnapshotController#delete #delete queues the delete action
```

move cloud volume snapshot from provider to core

---

app/javascript/components/subnet-form/index.jsx
app/javascript/components/subnet-form/subnet-form.schema.js
app/javascript/spec/subnet-form/subnet-form.spec.js

Depends on: https://github.com/ManageIQ/manageiq-api/pull/1148, https://github.com/ManageIQ/manageiq-providers-openstack/pull/792
Refactored the cloud subnet edit form to use params for edit instead of using params for create and disabling the fields.
@miq-bot add-label refactoring

Refactored subnet edit form to use params for edit

---

cypress/support/index.js

This bug was introduced in #7257.
@kavyanekkalapu Please review.  Most of the cypress tests still fail, but at least it is runnable now, and also login now passes.

Fix initialization of cypress

---

app/javascript/components/cloud-object-store-container-form/index.jsx
app/javascript/spec/cloud-object-store-container-form/cloud-object-store-container-form.spec.js

The emsType and parent_emstype are not used in the api or provider code so they are removed from the form submit function and its spec test. Both api calls are successful and hit the no credentials defined on their respective provider functions.
Before and after functionality is same after this change.
Before:
After:

Removed emstype and parent ems type from cloud object store container

---

app/javascript/components/volume-mapping-form/volume-mapping-form.schema.js

The keys values of physical_storage, cloud_volume host_initiator and host_initiator_group fields could be the same in some senarios and this cause bugs in the form rendering.
I set the keys correctly, and also fix the conditions to make sure all is working correctly.
before
-------
https://user-images.githubusercontent.com/53213107/165698540-93cfe5a2-3724-42b2-a73b-5883a8d8dfb2.mp4
after
-----
https://user-images.githubusercontent.com/53213107/165697444-aef4748d-63ae-4be9-bca8-5795cd183875.mp4

fix Define New volume Mapping form

---

app/helpers/application_helper/toolbar/host_initiator_center.rb
app/helpers/application_helper/toolbar/host_initiators_center.rb

This PR add new feature for host-initiators (storage), the ability to **delete an existing host-initiator**.
Links
* https://github.com/ManageIQ/manageiq/pull/21845
* https://github.com/ManageIQ/manageiq-providers-autosde/pull/147
* https://github.com/ManageIQ/manageiq-api/pull/1157

del host initiator

---

app/controllers/cloud_volume_controller.rb
app/javascript/components/cloud-volume-form/attach-detach-cloud-volume-form.jsx
app/javascript/components/cloud-volume-form/attach-detach-cloud-volume.schema.js
app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
app/javascript/spec/cloud-volume-form/attach-detach-cloud-volume-form.spec.js

Implements `option_action=attach` from https://github.com/ManageIQ/manageiq-api/pull/1147
Implements `attach` vs `attach_volume` renaming from https://github.com/ManageIQ/manageiq/pull/21841
Part of fixing attach / detach from [7603](https://github.com/ManageIQ/manageiq-ui-classic/issues/7603#event-6292073380). Spiritual successor to https://github.com/ManageIQ/manageiq-ui-classic/pull/8205
Depends on schema to be implemented in providers that support `attach` 
Attach
Detach

Upgrading Attach/Detach functionality

---

app/javascript/components/miq-pagination.jsx

Fixed translation marked strings created in this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8258
@miq-bot add_reviewer @jeffibm @Fryguy 
@miq-bot assign @jeffibm @Fryguy 

Fixed translation functions on pagination strings

---

lib/tasks/manageiq/ui_tasks.rake

Build with yarn 3 on IBM Z fails , so this change switches to yarn 1.22.18 only for Z builds to overcome the issue

changes for s390x

---

app/javascript/components/workers-form/workers-form.jsx
app/javascript/components/workers-form/workers.schema.js

Most other workers have the ability of changing the count and memory threshold via the Settings / Workers tab but the UI worker only has count.
Before:
After:

Allow changing UI worker memory threshold on UI

---

app/controllers/physical_server_controller.rb
app/helpers/physical_server_helper/textual_summary.rb
product/views/PhysicalServer.yaml

This PR adds additional info, related to server profiles, to the list of physical servers as well as to the server details page. This is specific to Cisco Intersight provider, so it may be better to have it as customization, just not sure how best to do it.
Screenshots below show the effect of this change.
List of servers:
Server details:

Server profile details

---

product/views/PhysicalServer.yaml
product/views/PhysicalStorage.yaml
product/views/Storage.yaml

- PhysicalServer/PhysicalStorage
- fix includes to properly identify associations and fix N+1
- Storage
- change ems to ems.name
- ~~Vm/Templates: remove the unneeded os_image_name column~~
- ~~PhysicalStorage: remove invalid attribute `power_state` from the view~~
A few more details are in the individual commits
There is also an associated fix: https://github.com/ManageIQ/manageiq/pull/21781
---
Although `PhysicalStorage#power_state` looks like an error, the page seems to be working fine, leaving it alone
Here is what I found:
- pr to add `power_state` to the switch: https://github.com/ManageIQ/manageiq-schema/pull/160
- pr to add 'power_state` to the server: https://github.com/ManageIQ/manageiq-schema/commit/8e95341be28e5d33662c51c17a055573b0641b6a
- No pr to add `power_state` to the …

Fix View yaml to point to valid fields

---

app/javascript/components/provider-form/index.jsx

Fixes: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/issues/371
Fixed an issue where the authentication values were not being sent as part of the API post / patch data for the edit provider form for the IBM Cloud VPC provider. The issue involves this line:
`const authentications = Object.keys(_authentications).map((key) => ({ authtype: key, ..._authentications[key] }));`
This line takes all the fields from the Default Endpoints tab and pulls them out to add the to data object that is submitted to the API. This process however will ignore any credentials fields since those are handled by the validation button separately. This means that since the IBM Cloud VPC provider only has a credentials field the `_authentications` object is empty and therefore the resulting …

Fixed IBM Cloud edit provider authentication issue

---

app/controllers/cloud_object_store_container_controller.rb
app/controllers/mixins/actions/host_actions/misc.rb
app/helpers/application_helper.rb
app/helpers/application_helper/button/generic_feature_button_with_disable.rb
app/helpers/application_helper/button/host_feature_button.rb
app/helpers/application_helper/button/host_feature_button_with_disable.rb
spec/controllers/storage_controller_spec.rb
spec/helpers/application_helper/buttons/generic_feature_button_spec.rb
spec/helpers/application_helper/buttons/host_feature_button_spec.rb
spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb

- convert is_available? to supports?
- convert supports_#{feature} to supports?(:feature)

move AvailabilityMixin over to SupportsFeatureMixin

---

app/javascript/components/remove-generic-item-modal.jsx

the following warning is shown when calling RemoveGenericItemModal (e.g. when deleting volumes):
```
Warning: A component is changing an uncontrolled input of type %s to be controlled. 
Input elements should not switch from uncontrolled to controlled (or vice versa). 
Decide between using a controlled or uncontrolled input element for the lifetime of 
the component. 
More info: https://fb.me/react-controlled-components%s,checkbox, in input
(created by RemoveGenericItemModal) in label (created by RemoveGenericItemModal)
in div (created by ModalBody) in ModalBody (created by RemoveGenericItemModal)
in RemoveGenericItemModal (created by Connect(RemoveGenericItemModal))
in Connect(RemoveGenericItemModal) (created by inner) 
in inner in div (created by ModalBody)
in ModalBody
in div (created …
```

Fix RemoveGenericItemModal Controlled Component Warning

---

spec/controllers/miq_ae_class_controller_spec.rb

we end up doing a couple of lookups if id is passed in.
No reason to not pass in the parent since that is already in memory
... cleaning up stashes (thing this was 4 years old)

use parent for creating namespaces instead of parent_id

---

app/controllers/application_controller/report_downloads.rb
app/controllers/vm_common.rb
app/stylesheet/legacy/compare_drift.scss
app/views/layouts/print.html.haml
app/views/shared/_compare_header_expanded.html.haml
app/views/shared/_quadicon.html.haml

Removed angular quadicon code as it was not actually being rendered anywhere.
Examples:
Before:
After:
@miq-bot add-label technical debt

Remove angular quadicon code

---

app/controllers/application_controller/ci_processing.rb
app/controllers/mixins/actions/vm_actions/reconfigure.rb
app/views/vm_common/_reconfigure.html.haml
spec/controllers/application_controller/ci_processing_spec.rb
spec/controllers/cloud_object_store_container_spec.rb
spec/controllers/cloud_object_store_object_spec.rb
spec/controllers/security_group_controller_spec.rb
spec/controllers/storage_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb
spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb
spec/helpers/application_helper/buttons/ems_timeline_spec.rb
spec/helpers/application_helper/buttons/generic_feature_button_spec.rb
spec/helpers/application_helper/buttons/host_feature_button_spec.rb
spec/helpers/application_helper/buttons/instance_associate_floating_ip_spec.rb
spec/helpers/application_helper/buttons/instance_disassociate_floating_ip_spec.rb
spec/helpers/application_helper/buttons/instance_reset_spec.rb
spec/helpers/application_helper/buttons/storage_scan_spec.rb
spec/helpers/application_helper/buttons/vm_instance_template_scan_spec.rb
spec/helpers/application_helper/buttons/vm_retire_now_spec.rb
spec/helpers/application_helper/buttons/vm_retire_spec.rb
spec/helpers/application_helper/buttons/vm_snapshot_remove_one_spec.rb
spec/helpers/application_helper/buttons/volume_attach_spec.rb
spec/helpers/application_helper/buttons/volume_detach_spec.rb
spec/spec_helper.rb
spec/support/examples_group/shared_examples_for_generic_feature_buttons.rb

Depends: (built upon)
The goals:
- use `stub_supports` instead of `allow().to receive(:supports)`
- convert any remaining `supports_feature` to `supports?(:feature)`
Extras (please share if you don't like):
- made `stub_supports` part of the standard specs
- ~~moved the individual ui helpers like `supports_reconfigure_disks` to just an `item_supports(:feature)` mechanism.~~

SupportsFeatureMixin use stub_supports

---

app/views/static/recent-resource.html.haml

Parent Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7603
The recent resource haml file was introduced in this commit: https://github.com/ManageIQ/manageiq-ui-classic/commit/848d778b3bf48cfd61dd68f004fb03149af21a83
The recent resource javascript component has been removed since and this haml file is now not used or called anywhere so it can be removed.
The dashboard page looks the same after removing this haml file.
@miq-bot add-label technical debt

Remove recent resource haml file

---

app/javascript/components/miq-pagination.jsx

Fixed string translation markings for table pagination. While testing I found that the strings inside of the function n__ were not being translated by this function so I added the string translation to the individual strings inside of the function to translate.
Test Strings:
Before: n__(`page`, `pages`, total);
After:  n__(__(`page`), __(`pages`), total);
@miq-bot add_reviewer @jeffibm 

Fixed pagination translations

---

app/views/catalog/_sandt_tree_show.html.haml

Fixes an issue where the catalog name is not displayed for a catalog item that has "Display in Catalog" unchecked.
Before:
After:

Fixed catalog item summary page

---

app/controllers/application_controller/miq_request_methods.rb
app/views/miq_request/_pre_prov.html.haml
spec/controllers/application_controller/miq_request_methods_spec.rb

Compute -> Infrastructure -> Providers -> Select VMWare provider -> Click on VMs -> Click on 'Lifecycle' -> Select 'Provision VMs'
**Before**
1. Was loading the ProvisionCloudTemplates.yaml
2. Checkbox to Show/Hide deprecated is displayed
3. There are no VMWare templates in the 'Provision Requests based on the selected Template ' table.
**After**
1. Loading ProvisionInfraTemplates.yaml
2. Checkbox to Show/Hide deprecated is not displayed
3. VMWare templates are displayed
@miq-bot add-reviewer @Fryguy 
@miq-bot add-reviewer @GilbertCherrie  

Fixed no VMWare templates in Provision Requests

---

app/stylesheet/miq-data-table.scss

Translated labels are vertically aligned in data table headers
**1. Chinese**
Before
After
**2. Japanese**
Before
After
@miq-bot add-label technical_debt

Fix vertical label for translated strings for data table

---

spec/services/charts_layout_service_spec.rb

The Host charts were updated to use applies_to_method similar to VMs, the specs must be updated accordingly
Introduced by https://github.com/ManageIQ/manageiq/pull/21909

Test host charts with various applies_to_method

---

app/stylesheet/notifications.scss

Some elements from the Adding/Editing a new Service Catalog Item page overlap Notifications.
Before
After

Fix service catalog form elements overlap with notifications

---

app/javascript/components/provider-form/index.jsx

This UI code supports the changes made to the red hat virtualization infrastructure provider form in this pr: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/606.
Depends on: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/606
Allows for the metric and keypair tabs to be enabled when there is metric and keypair data available and if empty keeps them disabled by default in order to prevent a bug that does not allow users to submit the add provider form.

Supports changes to rhv provider form

---

app/controllers/host_initiator_group_controller.rb
app/controllers/physical_storage_controller.rb
app/controllers/storage_resource_controller.rb

Fixed missing translations for the Physical Storages, Host Initiator Groups and Storage Resources titles and Storage Resources breadcrumbs.
Before:
After:
@miq-bot add_reviewer @jrafanie 

Fixed missing title/breadcrumb translations

---

package.json
yarn.lock

Upgrading the version of the charts to fix a security vulnerability issue
Before
After

[WIP] Upgrade charts version to 0.58.0

---

app/javascript/components/flavor-form/flavor-form.schema.js
app/javascript/spec/flavor-form/__snapshots__/flavor-form.spec.js.snap

Fixed a bug in the flavors form where using isSearchable was causing the emsID to be set to an object with `{label: ..., value: ...}` and this emsID object was being used in an API call causing an error since the API is just expecting the emsID as a value. By adding the simpleValue prop it allows only the value to be returned causing the correct API calls.
Before:
After:

Fixed flavors form

---

app/javascript/components/provider-form/index.jsx

Reverts #8312 which added code to the core UI in which to handle Ovirt specific logic which should be handled in the ovirt provider plugin itself.
Depends on:

Remove special UI code to handle Ovirt metrics/keypair selectors

---

app/javascript/forms/mappers/validatorMapper.jsx
app/javascript/spec/generic-objects-form/__snapshots__/generic-objects-form.spec.js.snap

Fixed a bug where the file size validation was not correctly being checked causing the error to always be shown and preventing the user from submitting the form.
Before:
After:

Fixed file size validation bug

---

app/javascript/components/copy-dashboard-form/copy-dashboard-form.schema.js

Fixed a bug in the copy dashboard form where the selected object was being sent to the submit instead of just the value. This was due to the `isSearchable` prop but is fixed by using `simpleValue: true`.
Before:
After:

Fixed copy dashboard form bug

---

app/javascript/components/generic-objects-form/generic-objects-form.schema.js
app/javascript/components/generic-objects-form/index.jsx
app/javascript/spec/generic-objects-form/__snapshots__/generic-objects-form.spec.js.snap

Changed the generic object form to use the `simpleValue: true` prop to simplify the submitting code as `simpleValue` ensures the select will return just the value instead of the selected option object.
By making this change it caused an issue with the initialValues not being correctly displayed so the `loadOptions` had to be changed to `options` and other changes had to be made to support this.

Refactored generic object form to use simple value for searchable field

---

app/helpers/application_helper.rb

*Development Only*
On every request, we check every miq_product_feature lookup against the database.
This helps us ensure the developer is using a valid feature.
The problem is these features get looked up a lot.
And they often are a recursive lookup when finding the parent feature.
So on the dashboard, there are around 50 lookups with a wall of
text with 215 more => around 265 database lookups.
Good news: most of these lookups are cached, but pages are added to the log
making them hard to read.
```
[----] D, [2022-06-27T18:20:37.786066 #57148:13f24] DEBUG -- :   CACHE  (0.0ms)  SELECT COUNT(*) FROM "miq_product_features" WHERE "miq_product_features"."identifier" = $1  [["identifier", "dashboard_view"]]
```
Since the identifiers are cached in MiqProduceFeature we are instead using the …

remove db checks on every request and use in memory cache (dev only)

---

.github/workflows/ci.yaml

Occasionally setup-ruby will hang while downloading the package and run until it is manually canceled, holding up other workflows from running in the process.
On average this job runs in under 2min30sec so if it is taking more than the timeout it is extremely likely to be hung.

Add a timeout for the setup-ruby job in ci.yaml

---

app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
app/services/ems_storage_dashboard_service.rb

Resource pool widget under storage manager dashboard was broken (probably because of the move from angular to react).
This is the fix.
Before
----
After
----

Fix storage resource heatmap

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js

Warning popup appear when opening new host-init form> select Port type:**FC** > Press **Add** (under **Custom manually entered WWPNs**):
```
Warning: Failed prop type: The prop `labelText` is marked as required in `TextInput`, but its value is `undefined`. in TextInput (created by TextField) in TextField (created by SingleField) in FormFieldHideWrapper (created by SingleField) in FormConditionWrapper (created by SingleField) in SingleField in div in Unknown in Unknown (created by FieldArray) in div (created by FieldArray) in FieldArray (created by FieldArray) in fieldset (created by FormGroup) in FormGroup (created by FieldArray) in FieldArray (created by SingleField) in FormFieldHideWrapper (created by SingleField) in Unknown in Unknown (created by ConditionTriggerWrapper) in …
```

add missing label for custom wwpn

---

app/controllers/vm_remote.rb
app/helpers/application_helper/toolbar/cloud/instance_operations_button_group_mixin.rb
config/routes.rb
spec/config/routes.pending.yml

This term "native console" is confusing in the code base at this time. Cloud/Infra managers can open their "native console" that points to their respective provider instance page in the Cloud. In the same spirit, I'm trying to use this "native console" route and its little `MiqTask` based workflow to prepare and open the VM's page on IBM Cloud, though Ovirt seems to open its special console viewer through the same route. 
Hence, [WIP]. I know the current implementation in this PR is pretty hacky, and would love to get a clearer understanding of what's going on here, and to contribute for clarify however I can. Guidance please.
Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>
Provider PR: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/396

Adding "Management Console" access for a PowerVS VM

---

app/controllers/miq_policy_rsop_controller.rb
app/views/miq_policy_rsop/_rsop_form.html.haml

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8291
For this particular set of drop-downs, the value of the default `<Choose>` was set to the string `"<Choose>"` instead of `nil`. This caused mismatched font colors and is inconsistent with the rest of the codebase. 
Note the mismatched colors of `<Choose>`

Updating default value of <Choose> to be nil in drop-downs

---

app/controllers/mixins/ems_common.rb

This was removed in https://github.com/ManageIQ/manageiq-ui-classic/pull/8093
But there were a few stragglers remaining.
Also of interest:
There are a few references to `adhoc` (one word), either as a table column or purging results, but those are all reporting centric.

remove remaining ad_hoc_references

---

app/javascript/components/physical-storage-form/editing-context.js
app/javascript/components/physical-storage-form/index.jsx
app/javascript/components/physical-storage-form/physical-storage-form.schema.js
app/javascript/components/physical-storage-form/validate-storage-credentials.jsx
app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap

We implemented a 'validate-storage' rest API on the AutoSDE side to have the ability to validate the storage system credentials before we send the creation task to the queue. With this feature, we're saving time and can change the credentials (if there are provided some invalid parameters) without waiting for the response of the queued task.
I implemented the validate button on the attaching storage system page. So we can press the button and validate that the provided parameters are valid. If they are valid, AutoSDE saved this validation request and when we'll press the submit button, the queue task will not validate another time but just take the object that has been created by the previous validation request.
https://github.com/ManageIQ/manageiq/pull/21882 …

implemented validation storage system button

---

package.json
yarn.lock

Upgrading `carbon-components` package from `10.46.0` to `10.56.0` to fix a security vulnerability issue
The` yarn.lock` file already had the new version -` 10.56.0`
Fixes - https://github.com/ManageIQ/manageiq-ui-classic/issues/8324

Update carbon-components package

---

app/helpers/application_helper/toolbar/x_vm_center.rb
app/javascript/components/data-tables/report-data-table/report-data-table.jsx
app/javascript/spec/report-data-table.spec.js

**Before**
Was able to click "Chargeback Preview" even if the performance (capacity and utilization) data is available, which resulted in 
server error (API) 
**After**
Links "`Monitoring/Chargeback Preview`" are disabled if corresponding records are not available
@miq-bot add-reviewer @agrare 
@miq-bot add-reviewer @jrafanie  

Fix chargeback preview server error

---

app/controllers/chargeback_rate_controller.rb

Submits `@rate[:id]` instead of `params[:id]` to the `javascript_redirect` function to ensure that the chargeback rate's id is correctly submitted (`params[:id]` is not set when a new rate is created which caused issues when copying a chargeback rate from the details page).
Before:
After:

Fixes Missing Id Error When Copying a Chargeback Rate

---

spec/helpers/application_helper/buttons/vm_snapshot_add_spec.rb
spec/helpers/application_helper/buttons/vm_snapshot_revert_spec.rb

The snapshot supports is now returning the default not supported message
Changed the test to reflect this
Goes with https://github.com/ManageIQ/manageiq/pull/21917 (since that is the PR that defaults the error message

change snapshot error to default error

---

app/helpers/application_helper/button/button_template_clone.rb
app/helpers/application_helper/toolbar/template_infras_center.rb

Re-enable Template Clone UI menu button from the template list view of the ibm_power_hmc provider now that Template Clone was implemented in that provider.
Example URL of affected web page :
http://1.2.3.4:3000/ems_infra/2?display=miq_templates#/
Links
* PR being reverted https://github.com/ManageIQ/manageiq-ui-classic/pull/8108
* PR adding Template Clone support https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/68

Re-enable Template Clone UI button for ibm_power_hmc provider

---

spec/controllers/application_controller/tags_spec.rb

Fix for a sporadic test failure in the tags_spec https://github.com/ManageIQ/manageiq-ui-classic/runs/7467314232?check_suite_focus=true#step:8:535
```
#<Classification(id: integer, description: text, icon: string, read_only: boolean, syntax: string, single_value: boolean, example_text: text, tag_id: integer, parent_id: integer, show: boolean, default: boolean, perf_by_tag: boolean, href_slug: string, region_number: integer, region_description: string, name: string, ns: string) (class)> received :bulk_reassignment with unexpected arguments
expected: ({:add_ids=>[69000000000208, 69000000000212], :delete_ids=>[69000000000207, 69000000000211], :model=>"Host", :object_ids=>[69000000000125]})
got: ({:add_ids=>[69000000000208, 69000000000212], :delete_ids=>[69000000000211, 69000000000207], …
```

Use array_including to fix sporadic tags failure

---

app/stylesheet/charts.scss

Fixes for - https://github.ibm.com/katamari/dev-issue-tracking/issues/25330
**Safari**
Before
After
1. The overlapping of labels is solved by making the card design similar to the dashboard charts.
2. The issue for Click events to minimize the expanded charts are present within the carbon charts themselves. 
3. Legends are now visible
**Firefox**
Before - 
After - Legends are now visible

Fix Provider charts style

---

app/javascript/components/miq-data-table/miq-table-cell.jsx

Issue - https://github.ibm.com/katamari/dev-issue-tracking/issues/26497
Removing the `image` when `text` is not available
Before
After

Remove image when no text is available in data tables

---

app/javascript/components/button-group/helper.js
app/javascript/components/button-group/index.jsx

Fixed catalog items button group form bug where the unassigned buttons list in the dual select field was empty due to the form not loading the button list correctly.
Before:
After:

Fixed catalog items button group form

---

spec/controllers/tree_controller_spec.rb

rails 6.1 includes character encoding for the content_type
The distinction between the two does not seem relevant
```
expected: "application/json"
got: "application/json; charset=utf-8"
```
Instead, just match the content type allowing either definition

support character encoding in content_type

---

app/helpers/cloud_database_helper/textual_summary.rb
app/helpers/cloud_network_helper/textual_summary.rb
app/helpers/security_group_helper/textual_summary.rb

Certain strings were not being translated within the code so we're exporting them here. 
BEFORE
AFTER
BEFORE 
AFTER
BEFORE
AFTER

Translations for strings in textual_summary.rb

---

app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
app/javascript/components/provider-dashboard-charts/helpers.js

new clean branch for PR after review of:
https://github.com/ManageIQ/manageiq-ui-classic/pull/8365#
changes:
`helpers.getHeatMapData`: 
- now checks both for `data` existence and validity, and returns an empty array if false.
- improved function structure.
`HeatMapChartGraph.js`:
- `heatData1/2` are no longer necessary due to the above, `getHeatMapData` is passed `data[datapoint1/2]`.
- improved syntax at `heatmapCpuTooltip`
-=-=-
bug description:
when invalid data is sent to the HeatMapChartGraph, for instance due to connection problems in the backend, a broken chart is rendered instead of an empty one.
This is because the data is not null, but is invalid.
to reproduce the bug on the master branch: assign heatData1 with a dummy non-empty array, for instance [1, 2, 3]
bug reproduction: …

HeatmapChartGraph: show an empty chart when data is not null but undefined - new PR

---

app/helpers/provision_customize_helper.rb
app/views/shared/views/_prov_dialog.html.haml

- part of the work to split oVirt provider
Related to:
- https://github.com/ManageIQ/manageiq-providers-ovirt/pull/595
@miq-bot assign @agrare

Switch Redhat references to oVirt

---

app/helpers/ems_storage_helper/textual_summary.rb

The 'description' instance method is not defined in the base
StorageManager class, or in
ManageIQ::Providers::IbmCloud::ObjectStorage::StorageManager.
As far as I can tell this is the only place it is used.
Setting the "Region" label directly to the 'provider_region' value
removes the dependency on defining a 'description' instance method (and
seems more relevant).
Before:
After:

Set ems storage "Region" label to provider_region

---

app/controllers/mixins/actions/vm_actions/ownership.rb

I found an old `require 'byebug'` that was left behind.

Remove byebug require

---

app/controllers/application_controller.rb
app/controllers/vm_common.rb

If the provision type is "clone" set the request type to clone_to_vm or clone_to_template based on the source object being cloned.
TODO:
The `Clone Virtual Machine` comes from https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/vm_common.rb#L1208 which is using the source controller to lookup the string.
Before:
After:

Set clone request_type based on the source object type

---

app/javascript/components/remove-catalog-item-modal.jsx
app/javascript/components/vm-edit-form/vm-edit-form.schema.js
app/javascript/forms/form-buttons.jsx
app/javascript/forms/miq-button.jsx
app/stylesheet/ddf_override.scss
app/stylesheet/menu.scss

A collection of various fixes to the UI
To reproduce: Compute > Clouds > Instances > Select one instance > Configuration - Edit this Instance
To reproduce: Services > Catalogs > Catalog Items - Unassigned > Select one Catalog Item > Configuration - Delete Catalog Item
To reproduce: Compute > Clouds > Providers > Click Configuration - Add a new Cloud Provider > Select IBM PowerVC from the Type dropdown list

CSS Enhancements

---

app/views/shared/views/_prov_dialog.html.haml

Add a public_network option to the environment tab
Dependent:
* https://github.com/ManageIQ/manageiq/pull/22020
* https://github.com/ManageIQ/manageiq-providers-google/pull/232
https://github.com/ManageIQ/manageiq-providers-google/issues/231

Add public_network option to GCE provisioning

---

app/controllers/service_controller.rb

Fixed a typo for the services ownership title that was added in pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8229.

Fixed typo for services ownership title

---

app/controllers/catalog_controller.rb
app/views/catalog/_form_basic_info.html.haml
app/views/catalog/_sandt_tree_show.html.haml
app/views/service/_svcs_show.html.haml

- added the ability choose AWX catalog items and select job templates to be used in service provisioning
Depends on:
Screenshots:

AWX template support for catalog

---

app/controllers/miq_task_controller.rb

Fixed a bug where delete all is clicked for an empty tasks table.
Before:
After:

Fix tasks delete all bug

---

app/javascript/components/button-group/helper.js
app/javascript/components/button-group/index.jsx

Fix issue with button group form where group_index value was not being submitted to the API causing bugs with the toolbar when the toolbar tries to load in the custom buttons.
Before:
After:

Fix button group form missing group_index on submit

---

app/javascript/components/async-credentials/password-field.jsx
app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap

Removed a line added in this commit: https://github.com/ManageIQ/manageiq-ui-classic/commit/efb863b9221d07919b873430528e0bf02f439b9b that was preventing the provider / credential forms from rendering a text area box and instead always rendering the `edit-password-field` component as a password field with `*` placeholder characters.
Before:
After:
@miq-bot add_reviewer @DavidResende0 
@miq-bot add_reviewer @MelsHyrule 

Fixed private key field for provider forms

---

app/views/report/_form_formatting.html.haml

Found a bug in Editing Reports > Formatting, where the column format drop-downs would use the labels as their values, causing an error.
1. Go to Overview > Reports > Reports
2. Configuration > Edit this Report
3. Formatting > Specify Column Headers and Formats
4. Change any Format column
5. Save and Queue the report
6. Once done go to Saved Reports, find the report you queued up and click it, you should see the error below. 
@miq-bot add-reviewer @jeffibm 

Fixing dropdown values

---

spec/controllers/ops_controller/settings/schedules_spec.rb

Fixes a sporadic test failure where this one test runs first, skips setting the
depot correctly to the Smb depot double and this results in
test failures in both tests:
```
1) OpsController#build_uri_settings uses params[:log_password] for validation if one exists
Failure/Error: raise _("Invalid or unsupported file depot type.") if type.nil?
RuntimeError:
Invalid or unsupported file depot type.
2) OpsController#build_uri_settings uses the stored password for validation if params[:log_password] does not exist
Failure/Error: raise _("Invalid or unsupported file depot type.") if type.nil?
RuntimeError:
Invalid or unsupported file depot type.
```

Fix typo preventing usage of the correct double

---

app/stylesheet/miq-structured-list.scss

Removed additional padding for images in summary pages
Before
After

Fix images padding in summary pages

---

spec/javascripts/support/jasmine_helper.rb

Fixes this error on 6.1 jasmine specs: `TEST_SUITE=spec:javascript bundle exec rake`
```
#<ArgumentError: wrong number of arguments (given 0, expected 3)>
/Users/joerafaniello/.gem/ruby/2.7.5/gems/actionview-6.1.6.1/lib/action_view/base.rb:230:in `initialize'
/Users/joerafaniello/Code/manageiq-ui-classic/spec/javascripts/support/jasmine_helper.rb:18:in `new'
/Users/joerafaniello/Code/manageiq-ui-classic/spec/javascripts/support/jasmine_helper.rb:18:in `call'
/Users/joerafaniello/.gem/ruby/2.7.5/gems/rack-2.2.4/lib/rack/urlmap.rb:74:in `block in call'
```
Note, this is a rails 6.1+ only change discovered by but not caused by https://github.com/ManageIQ/manageiq-ui-classic/pull/8408.  This was broken with rails 6.1 but didn't get detected in cross repo.
I've added this to …

Rails 6.1: ActionView::Base new now has 3 required arguments

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js

Modified the IQN component in host_initiator_form, to support multiple IQNs to be added at once (as it was in the WWPN component). The change will be also reflected in a PR in the autosde_providers repo: 
https://github.com/ManageIQ/manageiq-providers-autosde/pull/160
The IQN details will now be passed as an array, not as a text field.
Add/Remove buttons were added.
when selecting ISCSI as the port type, this will appear:
clicking add will open a text field:
multiple fields can be added and removed, when submitting the form, the strings will be passed as an array

modified host initiator form to accept multiple iqns

---

app/javascript/components/search-bar/index.jsx
app/javascript/http_api/http.js

`app/javascript/http_api/http.nonApiOnly(url)` makes sure that the url is not an API endpoint, and has a mirror function in `app/javascript/http_api/api.apiOnly(url)` which makes sure that the url **is** an api endpoint. 
For some reason, `http.nonApiOnly` was not written similar to `api.apiOnly`, which caused a `TypeError`. 
After fixing the error, it appeared that the regex used in `http.nonApiOnly` was different from the one in `api.apiOnly `, which caused a false assessment of http-urls as api urls, and raised an error.
after the fix, `http.nonApiOnly` now correctly mirrors `api.apiOnly`.
before fixing TypeError:
after fixing TypeError, before fixing false negative
after fixing false api error:

errors when using searchbar

---

app/controllers/application_controller/ci_processing.rb

part of https://github.com/ManageIQ/manageiq/issues/21179
removing a comment reference to `AvailabilityMixin`

rename Vm Operation context

---

app/stylesheet/ddf_override.scss

Modifies css to prevent the dual-list-select buttons from overlapping with the rest of the component
Before:
After:

Fixes Component Overlapping in Service -> Catalog Form

---

app/helpers/cloud_volume_helper/textual_summary.rb
spec/helpers/cloud_volume_helper/textual_summary_spec.rb

The Volume detail page shows to which storage it belongs and a lot of other properties.
I added to the Relationships detail the Storage Resource it belongs to (which its respective link).

add storage resource to volume Relationships

---

app/stylesheet/dashboard.scss

Issue - https://github.ibm.com/katamari/dev-issue-tracking/issues/33679
Fix for tables in the dashboard page when scaled.
Before
After

Fix dashboard widget tables scaling

---

app/controllers/miq_ae_customization_controller.rb

Adds `old_dialogs_new`, `old_dialogs_edit`, and `old_dialogs_copy` to list of actions so that save/cancel/reset buttons appear in these forms.
Before:
After:
@miq-bot add-label bug, oparin/yes?
@miq-bot add-reviewer @MelsHyrule, @GilbertCherrie

Modified Allowed Function to Include Provision Dialog Forms

---

app/controllers/physical_storage_controller.rb

when I press on `Attach a new storage system` from physical-storage page(physical_storage/show_list#) the redirect not working and its stay in same page. The **new physical-storage page** look fine when I open it directly (physical_storage/new#).
Then I found that the `physical_storage_timeline` redirect was created in wrong place so I remove `button` function and put the `physical_storage_timeline` in `specific_buttons`

Put `physical_storage_timeline` redirect in `specific_buttons`

---

app/controllers/application_controller/advanced_search.rb
app/controllers/application_controller/buttons.rb
app/controllers/application_controller/ci_processing.rb
app/controllers/catalog_controller.rb
app/controllers/chargeback_rate_controller.rb
app/controllers/condition_controller.rb
app/controllers/host_controller.rb
app/controllers/miq_ae_class_controller.rb
app/controllers/miq_ae_customization_controller/old_dialogs.rb
app/controllers/miq_alert_controller.rb
app/controllers/miq_policy_controller/policies.rb
app/controllers/mixins/manager_controller_mixin.rb
app/controllers/ops_controller/ops_rbac.rb
app/controllers/ops_controller/settings/analysis_profiles.rb
app/controllers/ops_controller/settings/label_tag_mapping.rb
app/controllers/ops_controller/settings/tags.rb
app/controllers/ops_controller/settings/upload.rb
app/controllers/ops_controller/settings/zones.rb
app/controllers/pxe_controller/pxe_servers.rb
app/controllers/report_controller/dashboards.rb
app/controllers/report_controller/menus.rb
app/controllers/report_controller/reports/editor.rb
app/controllers/report_controller/schedules.rb
app/controllers/report_controller/widgets.rb

Fixes this warning in several places in the test suite:
```
In Rails 6.1, `errors` is an array of Error objects,
therefore it should be accessed by a block with a single block
parameter like this:
person.errors.each do |error|
attribute = error.attribute
message = error.message
end
You are passing a block expecting two parameters,
so the old hash behavior is simulated. As this is deprecated,
this will result in an ArgumentError in Rails 7.0.
```

Fix rails 6.1 errors is now array warnings

---

app/javascript/menu/search-results.jsx

Navigation main menu search was returning the wrong number of results before.
**Search string: overview**
Before - 11
After - 10
**Search string: about**
Before - 2
After - 1
**Search string: physical**
Before - 9
After - 8
**Search string: storage**
Before - 17
After - 13

Fix main menu search error

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js
app/javascript/components/host-initiator-form/index.jsx

When creating a new host initiator, and choosing ISCSI port type, the add button wouldn't get enabled when entering a IQN.
And when choosing FC, adding a custom WWPN would enable the add button but it didn't have any validation.
I added validation for both IQN and WWPN (which also fixes the bug that was at the beginning).
Wwpn is valid only when it has 16 characters.
Iqn is valid in a format like this: iqn.yyyy-mm.naming-authority:unique name, it only allows characters a-z, 0-9, '-', '.', ':' and with a 223 characters max length.

validate iqn and wwpn according to rules

---

app/javascript/components/async-credentials/password-field.jsx
app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap

`componentClass` prop in `PasswordField` caused an error, since React didn't expect this DOM element attribute to be `camelCase`, but rather lowercase (`componentclass`).
before:
after - no error:

`componentClass` prop in `PasswordField` caused an error

---

app/javascript/components/provider-dashboard-charts/charts_config.js
app/javascript/components/provider-dashboard-charts/pod-trend-charts/podsAreaChart.js
app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationDonutChart.js
app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationMemoryDonutChart.js
app/javascript/components/provider-dashboard-charts/recent-host-chart/hostLineChart.js
app/javascript/components/provider-dashboard-charts/recent-vm-chart/vmAreaChart.js
app/javascript/components/provider-dashboard-charts/servers-pie-chart/serversAvailablePieChart.js
app/javascript/components/provider-dashboard-charts/servers-pie-chart/serversHealthPieChart.js
app/javascript/components/provider-dashboard-charts/usage-network-image-charts/usageAreaChart.js
app/stylesheet/charts.scss
app/stylesheet/cloud-container-projects-dashboard.scss
app/views/ems_infra/_show_dashboard.html.haml

This pr mainly fixes three different issues related to the provider dashboard pages (cloud, containers, infrastructure, and physical infrastructure) as well as one issue related to the containers -> projects page:
**Issue 1: "Recent VMs" chart displays both recent vms and recent templates, so chart title was changed to "Recent VMs and Templates"**
**Issue 2: Provider dashboard charts not being displayed correctly (found in all provider dashboards)**
Before:
After:
**Issue 3: "Hourly Node Utilization Trend" chart not displaying in Containers -> Provider Dashboard**
Before:
After:
**Issue 4: Fixed UI issues in Containers -> Projects page and updated "Pod Creation and Deletion Trends" Chart to match other Provider dashboard charts**
Before:
After:
@miq-bot add-label bug, oparin/yes?
@miq-bot …

Fixed Various UI Issues Related to the Provider Dashboard Charts

---

spec/controllers/cloud_network_controller_spec.rb
spec/controllers/cloud_subnet_controller_spec.rb

- part of the effort to move provider-specific code out of core repositories
@miq-bot add_labels refactoring, test
@miq-bot assign @agrare

Generalize cloud network factories

---

app/views/ems_container/_show_dashboard.html.haml

Found in Compute -> Containers -> Overview
Before:
After:

Added @record.id Check to Prevent Undefined Error

---

app/presenters/menu/default_menu.rb

When the `Application Settings` was moved from the header to the left nav, few users are missing the link and expecting it higher in the list.
Fixes for - https://github.ibm.com/katamari/dev-issue-tracking/issues/24855
Before
After
@miq-bot assign @Fryguy 

Move application settings link upwards in sub menu

---

app/controllers/application_controller.rb
app/controllers/report_controller/saved_reports.rb

Ensures that Saved Reports that get deleted are removed from `params[:miq_grid_checks]` in order to prevent an error if the user decides to delete more reports (attempts to delete the already deleted reports alongside newly selected reports)
@miq-bot add-label bug, oparin/yes?

Deleted Reports Still Counting as Being Selected in Saved Reports

---

app/services/ems_storage_dashboard_service.rb

It was added in a just merged PR:
https://github.com/ManageIQ/manageiq-ui-classic/pull/8429
There is no need for interpolation here.
Fixes a brakeman warning:
https://github.com/ManageIQ/manageiq/actions/runs/3091508041/jobs/5001665151#step:8:8013
```
Confidence: Medium
Category: SQL Injection
Check: SQL
Message: Possible SQL injection
Code: EmsEvent.where("ems_id=#{@ems_id}")
File: ../../.gem/ruby/2.7.6/bundler/gems/manageiq-ui-classic-dd7330eae02e/app/services/ems_storage_dashboard_service.rb
Line: 102
```

Remove needless string interpolation

---

app/helpers/application_helper.rb

Added `MiqProvision` to the `db_to_controller` function to prevent a no matching routes error when viewing the provisioned vms from a Request
Before: 
After: 
@miq-bot add-reviewer @MelsHyrule, @jeffibm

Fixed No Route Matches Error in Services Requests

---

app/controllers/application_controller/compare.rb
spec/controllers/application_controller/compare_spec.rb

Issue- https://github.ibm.com/katamari/dev-issue-tracking/issues/33921
**1.** The Compare selected VMs button does not process the last selected item from the tree.
Before
After
No fixes were made here in this PR as this issue was fixed when the page was converted to react data table
**2.** The last item from the tree was not getting selected for comparison
Before
After

Fix missing selected items during compare

---

app/javascript/components/carbon-charts/stackBarChart.js
app/services/ems_storage_dashboard_service.rb

related to PR #8429
This PR is about the new widget added to the storage system manager page , that shows the event on a graph (per storage system) that show the distribution between fix and unfixed event.

Gal/311498 visualize events to physical storage page  

---

app/helpers/application_helper/toolbar/ems_infra_center.rb

The tooltip says "cloud provider" even though this is an infrastructure provider.

fix tooltip for native console in infra provider

---

app/helpers/application_helper/toolbar/hosts_center.rb

Issue : https://github.com/ManageIQ/manageiq-ui-classic/issues/8465
Power on, Power Off and Reset buttons are enabled even if no items were selected
Before
After
@miq-bot add-reviewer @Fryguy 

Fix infrastructure hosts power menu selection

---

app/helpers/application_helper/toolbar/x_vm_center.rb
config/routes.rb

Add a button to show the Management Console under Access on Infrastructure VMs
Related:
* https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/86

Add Management Console to Infra VMs

---

app/helpers/catalog_helper.rb
app/helpers/request_info_helper.rb
app/javascript/components/miq-custom-tab/index.jsx
app/javascript/spec/miq-custom-tab/__snapshots__/miq-custom-tab.spec.js.snap
app/javascript/spec/miq-custom-tab/miq-custom-tab.spec.js
app/stylesheet/application-webpack.scss
app/stylesheet/catalog-custom-component.scss
app/views/catalog/_sandt_tree_custom_image_form.html.haml
app/views/catalog/_sandt_tree_request.html.haml
app/views/catalog/_sandt_tree_show.html.haml
app/views/miq_request/_prov_wf.html.haml

The tabs under the catalog summary's Request Info tabs (Catalog, Environments, Properties, Customize, Schedule) converted from HAML to React 
Before
After

Convert catalog summary request-info tabs from HAML to react

---

.gitattributes

This suppresses git grep/diff or any of the patch(-p) commands (add/checkout/stash/etc) from showing possibly enormous json blobs.
This was done because it's seldom useful to see these enormous json blobs when looking at git grep or even git diff.
You can still tell git diff to treat it as text using `git diff --text`.
```
manageiq-ui-classic % git grep Resides
app/javascript/oldjs/locale/de.json:{"domain":"app","locale_data":{"app":{"":{"Generated-By":"Globalization Pipeline","Project-Id-Version":"manageiq 1.0.0","Report-Msgid-Bugs-To":"","POT-Creation-Date":"2022-08-09 08:49-0400","PO-Revision-Date":"2022-08-09 08:49-0400","Last-Translator":"FULL NAME <EMAIL@ADDRESS>","Language-Team":"LANGUAGE <LL@li.org>","Language":"de","MIME-Version":"1.0","Content-Type":"text/plain; …
```

Treat our locale json files as binary in git

---

app/controllers/application_controller.rb

Added safe navigation operator (`&.`) so that we check if `params[:miq_grid_checks]` nil before calling  `split` or `delete`.
Related to changes made here https://github.com/ManageIQ/manageiq-ui-classic/pull/8448

Safe delete saved reports

---

app/stylesheet/dashboard.scss

In Firefox, the legend items were not visible in fullscreen
Issue : https://github.ibm.com/katamari/dev-issue-tracking/issues/36853
Before
After

Fix dashboard chart legend items in fullscreen in Firefox

---

app/controllers/mixins/ems_common.rb
app/controllers/placement_group_controller.rb
app/controllers/vm_common.rb
app/helpers/application_helper.rb
app/helpers/application_helper/listnav.rb
app/helpers/application_helper/page_layouts.rb
app/helpers/application_helper/toolbar/placement_group_center.rb
app/helpers/application_helper/toolbar/placement_groups_center.rb
app/helpers/application_helper/toolbar_chooser.rb
app/helpers/ems_cloud_helper/textual_summary.rb
app/helpers/placement_group.rb
app/helpers/placement_group_helper.rb
app/helpers/placement_group_helper/textual_summary.rb
app/helpers/vm_helper/textual_summary.rb
app/presenters/menu/default_menu.rb
app/views/miq_request/_prov_field.html.haml
app/views/placement_group/show.html.haml
app/views/placement_group/show_list.html.haml
app/views/shared/views/_prov_dialog.html.haml
config/routes.rb
product/views/PlacementGroup.yaml
product/views/PlacementGroup.yml
spec/config/routes.pending.yml
spec/helpers/ems_cloud_helper/textual_summary_spec.rb
spec/helpers/placement_group_helper/textual_summary_spec.rb
spec/helpers/vm_helper/textual_summary_spec.rb
spec/routing/placement_group_routing_spec.rb

These files are for Server Placement Group.
This is a dependent PR for adding and enabling Server Placement Group as Menu in the Core
1. Manageiq schema changes.
https://github.com/ManageIQ/manageiq-schema/pull/644
2. Server Placement Group in ManageIQ User Interface.
https://github.com/ManageIQ/manageiq-ui-classic/pull/8214
3. PowerVS changes.
https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/363
4. ManageIQ Core changes
https://github.com/ManageIQ/manageiq/pull/21807

Server Placement Group

---

app/presenters/menu/default_menu.rb

https://github.com/ManageIQ/manageiq/pull/22156 added more standard placement_group_list, _show_list, and _view features but there was still a reference to the previous placement_group_view feature left over.

Fix reference to old placement_group_list feature

---

app/helpers/vm_helper/textual_summary.rb

I missed this during local testing of #8214 - the VM textual summary method for placement group is broken (must have been changed in a refactor somewhere along the way of that PR).
fyi @agrare and @jeffibm

Fix VM textual summary for placement group

---

lib/manageiq/ui/classic/engine.rb
manageiq-ui-classic.gemspec

Note, this is needed to fix #8300 on morphy since #7834 was merged on master after morphy so it's in najdorf.
From 27403b0b24c:
No more coffee for ruby
We have removed all coffee script files
This is removing the dependency

[MORPHY] Manually backport #7834

---

app/helpers/vm_cloud_helper.rb

This PR is related to a partial fix for https://github.com/ManageIQ/manageiq-ui-classic/pull/8458#
**Before**
Compute / Cloud / Instance / All Instances / Lifecycle / provision instances / (Pick one to provision)
The error pops up
**After**
The previous error will be fixed. but it generates a different error.
@miq-bot add-reviewer @agrare 

Fix lifecycle provision of template

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js

The WWPN address added to a host initiator should be a hexadecimal expression. Up till now it's only validating its length to be 16 characters, but not to be hexadecimal necessarily:
After fixing this:

add validation to wwpn to be hexadecimal

---

app/javascript/components/async-credentials/password-field.jsx
app/javascript/spec/async-credentials/__snapshots__/password-field.spec.js.snap

https://github.com/ManageIQ/manageiq-ui-classic/pull/8432 inadvertently broke all text-area password-fields, reverting them to regular text-fields, which recreated the following issue https://github.com/ManageIQ/manageiq-ui-classic/issues/7647. This fix resolves both issues.

Fixes Password Field so it is Correctly Rendered as a Text Area

---

app/javascript/components/physical-storage-form/validate-storage-credentials.jsx

When opening the page of "Add New Physical Storages", we encountered this error in the console:
The reason is because in the proptypes definition below we had defined the name of the variable instead of the parameter, and then it expected it to be required as defined in the async-credentials page. So I just changed the name there (and also changed name of the variable for uniformity reasons, as it is in validate-provider-credentials.jsx).

change name of variable according to proptypes definition

---

app/controllers/container_dashboard_controller.rb

Compute / Containers / Overview / Container Dashboard
**Before**
When clicking on the Overview link in breadcrumb it redirects to error page as it goes to an invalid route ` /container_dashboard`
**After**
Now redirecting to ` /container_dashboard/show`

Fix container-dashboard's overview's breadcrumb link

---

app/stylesheet/miq-data-table.scss
app/views/miq_request/_pre_prov.html.haml

On the IM UI, navigated to Cloud > Instances. After an item in the "Instances by Provider" tree is selected, a few instances appeared in the right pane.
**Before**
The continue and cancel button were displayed at the bottom of the table confusing the user only to click the row and not click on the continue
**After**
The continue and cancel buttons are always visible.

Always display the Provision instance action buttons at the bottom

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js

added a host initiator group field to host initiator form, which enables choosing an existing host group from the specified storage system, or choose None for no group.
this also requires a change in the provider plug-in:
https://github.com/ManageIQ/manageiq-providers-autosde/pull/186
the new field:

choose host initiator group on host creation

---

app/helpers/application_helper/button/physical_server_console.rb
app/helpers/application_helper/toolbar/physical_server_center.rb

Issue
[Najdorf / Physical Server Remote Console not working #22210](https://github.com/ManageIQ/manageiq/issues/22210)
Related PR's
[manageiq - Add PhysicalServer remote console supports feature #22211](https://github.com/ManageIQ/manageiq/pull/22211)
[manageiq-providers-lenovo - Add supports :console to PhysicalServers #379](https://github.com/ManageIQ/manageiq-providers-lenovo/pull/379)

Show/hide Physical Server Console button in Physical Infrastructure Servers Summary

---

package.json
yarn.lock

Upgrading dependency `nwsapi` to ^2.2.1 per information found in [Snyk Vulnerability Database](https://security.snyk.io/vuln/SNYK-JS-NWSAPI-2841516)

Upgrading nwsapi to ^2.2.1

---

app/javascript/components/miq-data-table/miq-table-cell.jsx
app/javascript/components/tenant-quota-form/helper.js
app/javascript/spec/tenant-quota-form/__snapshots__/tenant-quota-form.spec.js.snap
app/stylesheet/miq-data-table.scss

Related: https://github.com/ManageIQ/manageiq/pull/22220
Marks the On/Off toggle labels for translation from the quota table in the Manage Quotas Form. Also added a minor css change to prevent text overlap.
Before:
After:

Marked String for Translation in Tenant->Manage Quotas

---

app/javascript/components/timeline-options/timeline-options.jsx

Exporting strings in the Timeline Form page
These screenshots are from `Compute > Infrastructure > Hosts > Timelines for Host "aramis"`
NOTE: The reason the `Success` and `Failure` labels show as translated but `Both` does not is because these strings have been previously translated and such they can be replaced with the localized string. `Both` has not had this treatment yet. 
@miq-bot add-label internationalization

Exporting labels from the timeline form

---

app/controllers/ops_controller.rb
app/helpers/application_helper/button/servers_delete_server.rb
app/helpers/application_helper/toolbar/diagnostics_region_center.rb
app/helpers/application_helper/toolbar/diagnostics_zone_center.rb
app/javascript/components/remove-generic-item-modal.jsx

Related: https://github.com/ManageIQ/manageiq/pull/22229
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8459
Adds a delete server button to the server tab in the Diagnostic->Zone/Region pages.
@Fryguy, @jrafanie

Add Delete Server Button to Zone and Region Server Tab

---

config/routes.rb

Fixing routes error in advanced search in the Configured Systems page.

Fixed Configured Systems page advanced search

---

app/helpers/host_helper.rb
app/helpers/textual_mixins/textual_devices.rb
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/simple_table.js

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8477
Note the `&amp;` and trailing comma with whitepaces `, `
NOTE: Changes will also affect the following pages
Compute / Infrastructure / Host / [Select and item]
- Properties > Devices
- Properties > Operating System
- Properties > VMM Information
@miq-bot add-reviewer @jeffibm 

Fixing host device page display

---

app/controllers/cloud_network_controller.rb
app/controllers/floating_ip_controller.rb
app/controllers/security_group_controller.rb
app/helpers/application_helper/button/cloud_network_new.rb
app/helpers/application_helper/button/cloud_subnet_new.rb
app/helpers/application_helper/button/floating_ip_new.rb
app/helpers/application_helper/button/network_router_new.rb
app/helpers/application_helper/button/network_service_entry_new.rb
app/helpers/application_helper/button/network_service_new.rb
app/helpers/application_helper/button/security_group_new.rb
app/helpers/application_helper/button/security_policy_new.rb
app/helpers/application_helper/button/security_policy_rule_new.rb

Morphy direct backport of https://github.com/ManageIQ/manageiq-ui-classic/pull/8447
(cherry picked from commit 21e9653c7386b292976e01f72fac3f6eacb84dd6)
On master these were changed to `.supports?(:create)` from `.supports_create` earlier, but I left these as `&.supports_create?` to minimize the changes to only what this PR was doing (adding `&.` to handle the `nil` return possibility)

[MORPHY] Handle nil return from class_by_ems

---

app/views/ops/_all_tabs.html.haml

4 logs tabs will be hidden in podified
1. Production Logs
2. Audit Logs
3. IA:IM Logs
4. Collect Logs
**Logs will not be displayed for Podified environments**
**Logs will be displayed for other environments**

Hide logs for podified environment

---

app/controllers/application_controller/explorer.rb

**Before**
Unable to publish VM in Template. `Can't access records without an id` error is displayed.
Note -
- This is only an issue from the `Compute / Infrastructure / Virtual Machines` menu, breadcrumb path `Compute / Infrastructure / Virtual Machines / VMs & Templates / All VMs & Templates.`
- If we go to the provider and select VMs we can publish to a template from both the list view and the VM details page.
**After**
- The selected checkbox value was being accessed as `params[:id]` was available in the `x_node` variable.

Fix No record id available for Publishing VM to template

---

app/controllers/ops_controller/diagnostics.rb

Replacement of `Vmdb::Loggers.contents` with `Systemd::Journal` on appliances
TODO:

Replace `Vmdb::Loggers.contents` with `Systemd::Journal`

---

app/presenters/tree_builder_servers_by_role.rb

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8460
Found in: Settings->Application Settings->Diagnostics->Servers By Roles
Fixes an issue where the Servers By Roles page was displaying all servers assigned to a role as opposed to only the servers belonging to the selected zone. Also changes the Servers By Roles page to display all roles regardless of whether or not they have a server assigned to them, which prevents the `ServersByRole` tree from being an empty object, causing an undefined method error.
**Before:**
When there are no servers assigned to any roles:
When there is a least one server assigned to a role (EVM[16] does not belong to this zone): 
**After:**
When there are no servers assigned to any roles:
When there is a least one server assigned to a role:
@miq-bot …

Modified Servers By Role Tree to Prevent Undefined Method Error

---

app/javascript/components/tenant-quota-form/helper.js
app/javascript/components/tenant-quota-form/index.jsx

Found in: Application Settings->Access Control->Tenants->Manage Quotas
Separates the Disabled logic for the Save/Reset buttons to allow for situations where only one of the two buttons should be clickable (previously the user wouldn't be able to reset the form if they entered invalid data for example). Also adds some additional logic that prevents the user from submitting a blank value (blank value didn't effect data sent to api but was potentially confusing for the user).
Note: The text inputs used in the form are numerical and only allow numbers to be entered. However, the letter `e` can be entered because the text input allows the use of engineering notation (i.e. 2e3 = 2000). When entering just `e` or an invalid notation using `e`, the text inputs treat that as a blank, which meant it …

Modified Save/Reset Buttons "Disabled" Logic

---

app/controllers/miq_policy_controller/events.rb
app/controllers/miq_policy_controller/policies.rb
app/helpers/application_helper/toolbar/miq_policies_center.rb

Found in: Control->Policies
Adds some missing buttons found in the `miq_policy/show` page to `show_list` page.
Before:
After:
@miq-bot add-reviewer @MelsHyrule, @jeffibm
@Fryguy

Added Missing Buttons to miq_policy/show_list

---

app/presenters/tree_builder_servers_by_role.rb
app/views/ops/_diagnostics_servers_roles_tab.html.haml

Found in: Settings->Application Settings->Diagnostics->Servers By Roles
Adds a banner to the Server By Roles Page when there are no servers assigned to any roles. Also partially undoes a change made in https://github.com/ManageIQ/manageiq-ui-classic/pull/8541 by returning the filtering logic that prevented unassigned roles from being displayed.
Before:
After:
@miq-bot add-reviewer @MelsHyrule, @jeffibm
@Fryguy

Add Banner to Server By Roles Page

---

app/javascript/components/dashboard_toolbar.jsx

**Before**
After clicking on the tabs and resetting the widgets redirects to a undefined url
`ActionController::RoutingError (No route matches [POST] "/dashboard/change_tab/reset_widgets"): 
`
**After**
The dashboard page is loaded after the `reset_widget` action
Note : similar case with `widget_add` action
Fixes #8550

Fix dashboard toolbar urls

---

app/helpers/chargeback_rate_helper.rb
app/javascript/spec/miq-data-table/__snapshots__/miq-data-table.spec.js.snap
app/javascript/spec/miq-data-table/data.js
app/javascript/spec/miq-data-table/miq-data-table.spec.js

For the issue:- https://github.com/ManageIQ/manageiq-ui-classic/issues/8526
Before: 
After:
Chargeback Rate initial PR: [https://github.com/ManageIQ/manageiq-ui-classic/pull/8012/files](https://github.com/ManageIQ/manageiq-ui-classic/pull/8012/files)

Remove escape characters from Chargeback Rate helper

---

config/routes.rb
spec/config/routes.pending.yml

Triggering a custom dialog from an object type in the `Physical Infrastructure` section fails with an error.
Example error when clicking a custom button from a **Physical Infrastructure Provider**:
```
FATAL -- development: Error caught: [ActionController::UrlGenerationError] No route matches {:action=>"dialog_load", :controller=>"ems_physical_infra", :dialog_locals=>{:resource_action_id=>183, :target_id=>2, :target_type=>"ext_management_system", :real_target_type=>"ExtManagementSystem", :dialog_id=>3, :api_submit_endpoint=>"/api/providers/2", :api_action=>"Create Incident", :finish_submit_endpoint=>"/ems_infra", :cancel_endpoint=>"/ems_infra", :open_url=>false}, :id=>"2"}
```
This fixes the described error by adding the missing `ems_physical_infra -> dialog_load` route.
This refers to …

Add 'dialog_load' to ems_physical_infra in routes

---

app/views/catalog/_st_angular_form.html.haml

**Before** 
No change in tab contents when the `Provision` and `Retirement` tabs are selected, hence making it unable to save
**After**
Able to change the tab contents and save the form
https://user-images.githubusercontent.com/87487049/202419787-5601a258-6969-427e-993f-64d7cc545bde.mov

Fix for Service catalog item for Ansible Playbook tabs change

---

app/helpers/miq_ae_class_helper.rb
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/miq_ae_class_list.js

For the issue:- https://github.com/ManageIQ/manageiq-ui-classic/issues/8526
Before:-
After:-
Testing/QA 
Spec changes for the [MiqStructuredList](https://github.com/ManageIQ/manageiq-ui-classic/blob/f49cad584207bab59a3135c07c5367f362e3ca94/app/javascript/spec/miq-structured-list/miq-structured-list.spec.js#L68) will cover this change also.

Remove escape characters from Miq ae class helper

---

app/helpers/miq_policy_helper.rb
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/miq_ae_policy_list.js

For the issue:- https://github.com/ManageIQ/manageiq-ui-classic/issues/8526
Before:-
After:-
Testing/QA
Spec changes for the [MiqStructuredList](https://github.com/ManageIQ/manageiq-ui-classic/blob/f49cad584207bab59a3135c07c5367f362e3ca94/app/javascript/spec/miq-structured-list/miq-structured-list.spec.js#L68) will cover this change also.

Remove escape characters from Miq policy helper

---

app/controllers/service_controller.rb
app/views/service/show.html.haml

When the services page was de-explorised, the `explorer.html.haml` page was removed during https://github.com/ManageIQ/manageiq-ui-classic/pull/8229
The `Details, Provisioning, Retirement, Job` tabs were used in the removed page.
This PR brings back the removed tabs.
**Details and Jobs** 
Before (in morphy)
After
**No Tabs**
Before
After
**Details and Provisioning**
Before
After
**No Tabs - VM's list**
Before
After

Bring back the tabs in service page

---

app/helpers/miq_alert_helper.rb
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/miq_alert_list.js

Remove escape characters from miq alert helper

---

app/helpers/miq_policy_set_helper.rb
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/miq_policy_set_list.js

Remove escape characters from miq policy set helper

---

app/controllers/application_controller/buttons.rb
app/controllers/physical_chassis_controller.rb
app/controllers/physical_rack_controller.rb
app/controllers/physical_server_controller.rb
app/controllers/physical_storage_controller.rb
app/controllers/physical_switch_controller.rb
app/helpers/application_helper/toolbar/mixins/custom_button_toolbar_mixin.rb
config/routes.rb
spec/config/routes.pending.yml

Currently it is not possible to create custom buttons or actions for **_Physical Server, Physical Chassis, Physical Storage, Physical Switch and Physical Rack_**.
To enable them, ui had to be updated and api and core accordingly.
*NOTE*:  `Switch` class has been removed from the button's `BASE_EXPLORER_CLASSES` as those classes require `replace_right_cell` defined, which Switch does not have.
*Edit: Added screenshots of UI*
**_Refers to_**: 
-  [ManageIQ/manageiq-providers-cisco_intersight/issues/76](https://github.com/ManageIQ/manageiq-providers-cisco_intersight/issues/76)
**_Depends on_**: 
- [ManageIQ/manageiq/pull/22263](https://github.com/ManageIQ/manageiq/pull/22263)
- [ManageIQ/manageiq-api/pull/1189](https://github.com/ManageIQ/manageiq-api/pull/1189)
| ![Screenshot from …

Custom buttons and actions for Physical Infrastructure Objects

---

app/javascript/components/timeline-options/timeline-options.jsx
app/javascript/spec/timeline-options-form/__snapshots__/timeline-options-form.spec.js.snap
app/javascript/spec/timeline-options-form/timeline-options-form.spec.js

Found in: Summary->Monitoring->Timelines
Removed the reset button and renamed the save button to _Apply_, in order to better match the original form.
Before: 
After:

Updated React Timeline Form to Closer Match Old Form

---

app/views/miq_request/_prov_field.html.haml
app/views/shared/views/_prov_dialog.html.haml

add the field to the necessary `haml`s
Depends on

add customizable disk_size to vm post-provision 

---

app/helpers/report_helper/report_information_helper.rb
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/report_information_list.js

Remove escape characters from report information helper

---

app/javascript/components/timeline-options/timeline-options-simple.schema.js
app/javascript/spec/timeline-options-form/__snapshots__/timeline-options-form.spec.js.snap
app/stylesheet/ddf_override.scss

This pr mostly just introduces some css changes to the timeline form. It also removes the `required` validation from the date pickers since the timeline code is capable of defaulting to the last 2 weeks if no dates are selected or defaulting to 2 weeks ahead/behind if only one date is selected.
@MelsHyrule, @jeffibm, the css changes are just a suggestion and can be removed/adjusted if we feel they're unnecessary.
Before:
After:

Potential Timeline Form Improvements

---

app/helpers/report_helper/report_schedule_helper.rb
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/report_schedule_list.js

Remove escape character from report schedule helper

---

package.json
yarn.lock

Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/8566

Bump decode-uri-component from 0.2.0 to 0.2.2

---

package.json
yarn.lock

Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/8569 and https://github.com/ManageIQ/manageiq-ui-classic/pull/8573
In digging to find the best way to upgrade the `qs` package per the issue dependabot opened (https://github.com/ManageIQ/manageiq-ui-classic/pull/8569) I found that it could be resolved by bumping the cypress, jest and jest-cli packages who all made use of `qs`. 
Additionally in the the previous PR (https://github.com/ManageIQ/manageiq-ui-classic/pull/8573) the selective dependency resolutions bracket, see: https://github.com/ManageIQ/manageiq-ui-classic/blob/4566cde88dde2ed2bd4a7a3104a78d187eefa3d0/package.json#L179-L186 would override the import of `"qs@npm:6.9.7"` which is needed by `"webpack-dev-server@npm:~4.9.0"`.
@miq-bot …

Bumping cypress jest and jest-cli

---

app/helpers/textual_mixins/textual_refresh_status.rb
spec/helpers/textual_mixins/textual_refresh_status_spec.rb

Issue - https://github.com/ManageIQ/manageiq-ui-classic/issues/8558
**Before**
**After**
When `status=error`, then displays an **Error** message
When `status=success`, `time > than 2 days ago` then stale=true and displays **Warning** message
When `status=success`, `time < 2 days ago` then notifications will not be displayed

Change provider status notification type

---

package.json
yarn.lock

For resolving https://github.com/ManageIQ/manageiq-ui-service/pull/1820
The `express` dependency is brought in by `webpack-dev-server`.
---
- "express@npm:^4.17.3"
Because this import is a dependency of `webpack-dev-server` it has this lower than we'd like import requirement. 
```
"webpack-dev-server@npm:~4.9.3":
version: 4.9.3
resolution: "webpack-dev-server@npm:4.9.3"
dependencies:
express: ^4.17.3
```
This can be forcefully overcome by adding a line to the package.json file under "resolutions" and have the import be `"express@npm:^4.18.2"`
---
- "@types/express@npm:*, @types/express@npm:^4.17.13"
These are still express dependencies being imported by `webpack-dev-server`. They are just much more deeply buried dependencies:
```
➜  manageiq-ui-classic git:(bumping-webpack-dev-server) ✗ …
```

Upgrading webpack-dev-server to ~4.9.3

---

app/controllers/physical_storage_controller.rb

After the pr:
https://github.com/ManageIQ/manageiq-ui-classic/pull/8545
we notice that the button to create new physical storage does not trigger the redirect to the form.
I have added a call to the super of the button function if in the parameters it is not "custom_button"

run super if it's not custom_button

---

app/controllers/catalog_controller.rb
app/views/catalog/_form_basic_info.html.haml
app/views/catalog/_form_server_profile_template_options.html.haml

I added the server profile template field to the catalog item dialog if the cisco intersight catalog item type has been selected.
It will add the option for the administrator to create a service catalog item that will use the server profile template that the administrator selects instead of the choice of the regular user. 
**Before**
**After**
**Related pr**
https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/83

Cisco catalog item form

---

app/helpers/request_info_helper.rb

Fixes a bug that was causing a "no implicit conversion of Hash into Array" error when selecting the Environment tab while trying to provision a vm.
Before:
After:

VM Provision Environment Tab Fix

---

package.json
yarn.lock

Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8435
Updating versions for `eonasdan-bootstrap-datetimepicker` and `patternfly` as these are packages with moment-timezone as a dependency. They both bring in versions `^0.4.1` and `^0.4.0` of `moment-timezone` which has a High Severity Vulnerability. We've used the yarn.lock resolution field to bump all imported versions of `moment-timezone` to `~0.5.40`
Additional details about this PR can be found [here](https://github.com/ManageIQ/manageiq-ui-classic/issues/8435#issuecomment-1374045151).

Removing moment-timezone-0.4.1 and bumping moment-timezone to 0.5.40

---

app/controllers/mixins/ems_common.rb
app/services/ems_storage_dashboard_service.rb

and also changed volume mappings' icon
before:
after:
clicking the new cube successfully leads here:
**resolved**:
but when pressing the new link of host initiator groups, I get:
the error is raised in `app/views/shared/views/ems_common/_show.html.haml`. 
to my understanding, it was supposed to render according to lines 9-10 but seems like arr.include?(@display) returns `false`, even though `HostInitiatorGroupController.display_methods` references `cloud_volumes`.
adding `host_initiator_groups` to `CloudVolumeController.display_methods` didn't help..
and so it goes to lines 26-27
any idea why?

add host initiator groups to ems storage dashboard

---

app/helpers/storage_resource_helper/textual_summary.rb

Added enabled capabilities list in the textual summery page. 
related pr:
https://github.com/ManageIQ/manageiq-providers-autosde/pull/195
https://github.com/ManageIQ/manageiq-schema/pull/677

List resource capabilities in summary page

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
app/javascript/components/cloud-volume-form/index.jsx

filter services and resources by capabilities on volume create:
- Basic: filter services by required capabilities and choose an existing service from the filtered list.
- Advanced: choose a name for a new service, filter resources by required capabilities, and choose resources to attach to the new service from the filtered list. the new volume(s) will be created for the new service, on one of the attached resources.
- although changes were made to the general `cloud-volume-form.schema.js`, they will only appear for storage_manager volumes, due to a data-driven-form condition on receiving a `required_capabilities` field, which is only provided in `app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb`. see related PR in providers-autosde: …

storage manager volume create: basic and advanced modes

---

app/controllers/ops_controller/settings/schedules.rb

Before
---------
After
---------
It should be removed with the 'move database backup task'.
Links
https://github.com/ManageIQ/manageiq-ui-classic/pull/7943
Settings-> Application Settings -> schedules (from explorer)

Schedule edit bug fix

---

app/controllers/application_controller.rb

This is a continuation for 040029066e61dcde2cedbe77a4ffd799d7f6eacb
If the id that comes in is bigger than a valid id, then don't look it up by id.
This is for a few reasons:
- Postgres gets stage fright if the id coming in is too big, throwing an exception
- No need to add an OR clause for something that will never match
- Just looking up by the numeric will force the query to sequential table scan
This also helps us with a CVE (actually a potential DOS and not a real one) So it closes the gap and removes any questions / debates
- https://github.com/ManageIQ/manageiq-ui-classic/issues/7692
- https://github.com/ManageIQ/manageiq-ui-classic/pull/7702
- https://github.com/ManageIQ/manageiq/pull/22321
- https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapter …

handle ids that are bigger than bigint

---

app/controllers/mixins/ems_common.rb
app/helpers/application_helper/toolbar/host_initiator_group_center.rb
app/helpers/application_helper/toolbar/host_initiator_groups_center.rb
app/helpers/application_helper/toolbar_chooser.rb
app/helpers/ems_storage_helper/textual_summary.rb
app/presenters/menu/default_menu.rb
app/services/ems_storage_dashboard_service.rb
spec/helpers/ems_storage_helper/textual_summary_spec.rb

host initiator groups were added to the ems storage dashboard on PR https://github.com/ManageIQ/manageiq-ui-classic/pull/8593 but turns out there were further changes needed to enable the configuration toolbar button and to redirect the "new" action properly.
related PR in decorators repo:
https://github.com/ManageIQ/manageiq-decorators/pull/84
---
**before:**
---
**after:**
-
-

fixes for host initiator groups

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
app/javascript/helpers/validate-names.js

added validation to volume and service names, preventing from passing names that are already in use (which causes failure in the backend).
the validating function was added to a separate module in dir helpers, so we can import it in other schemas in the future.
**before**:
request is sent to the backend and fails there, causing unnecessary confusion for the user and work for the backend:
**after**:
the validators prevent the user from sending exiting names:
vs:

added validation to volume and service names

---

app/controllers/physical_storage_controller.rb
app/helpers/application_helper/toolbar/physical_storages_center.rb

The refresh button on the physical storage list page doesn't work.
I made change to call the refresh of the storage manager that connected to this physical storage.
The refresh button will be enabled when one physical storage is selected.

fix refresh ems storage manager for physical storage refresh button

---

app/javascript/angular/dashboard/widget-wrapper.js

**Before** 
Go to Overview > Dashboard
Refresh a widget. e.g. Vendor and Guest OS Chart
Browser console error after the refresh action
After the chart is refreshed, zoom in. The spinner will not disappear and zoom-in action is not completed.
Note: Refresh the page and clicking the zoom-in button will not throw an error
**After**
Able to zoom after refresh
https://user-images.githubusercontent.com/87487049/203041760-25a3bba5-9e1e-414a-9be8-69721be6cfe1.mov

[MORPHY] Fix dashboard widget refresh and zoom

---

app/controllers/application_controller.rb
app/controllers/application_controller/tags.rb
app/views/service/show.html.haml

**Before**
Steps to replicate the error
1. Go to Services / My Services
2. Click on a Service (you will get a Service's summary page)
3. Select Policy / Edit Tags
4. Add or Delete any tag
5. Click the Save / Cancel button
6. Goes to the **Services list** page and displays an error '**`Cannot access records with id`**'
**After**
Case 1
1. Go to Services / My Services
2. Click on a service (row) to view the summary page
3. Select Policy / Edit Tags
4. Add or Delete any tags
5. Click the Save / Cancel button
6. Redirects to the **Service Summary** page
Case 2
1. Go to Services / My Services
2. Click on multiple checkboxes to select multiple services
3. Select Policy / Edit Tags
4.  Add or Delete any tags
5. Click the Save / Cancel button
6. Redirects to the **Service List** page

Fix editing of tags for a service

---

app/views/miq_request/_prov_field.html.haml
app/views/shared/views/_prov_dialog.html.haml

Connected to https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/435

Add shared processor pool field option to provision form

---

app/views/host/_form.html.haml

part of https://github.com/ManageIQ/manageiq/pull/22334
it is currently an empty array. So removing this does not change the ui

remove host_os_create_types

---

app/controllers/application_controller.rb

* Drop the redundant action logging
* Add the session identifier to track requests made by the same user session
This now looks like this:
```
{"@timestamp":"2023-02-03T12:45:08.946675","pid":18362,"tid":"13e34","service":"audit","level":"info","message":"<AuditSuccess> Username [admin], Role [EvmRole-super_administrator], Session [6e91919b45f83463a6c541c987eda99f], Request [66bd4bde-cd07-4cfe-b9ed-1fbbfa3bb737], Method [GET], Path [/dashboard/widget_report_data/17] "}
{"@timestamp":"2023-02-03T12:45:08.947114","pid":18362,"tid":"13e34","service":"audit","level":"info","message":"<AuditSuccess> Username [admin], Role [EvmRole-super_administrator], Session [6e91919b45f83463a6c541c987eda99f], Request [66bd4bde-cd07-4cfe-b9ed-1fbbfa3bb737], Method [GET], Path …
```

Add session id logging

---

product/views/CloudVolume.yaml

Edited the column order and added another column to specify the physical storage the volume is connected to. 
Before:
After:
Can we create a file that will override this table for our provider? 
That will be better for us, as some columns are not necessary for our provider

Add physical storage column to volumes list

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js

Volume's names are accepting any string.
...while the requirements should be that it may contain letters, numbers, spaces, periods, dashes and underscores, it must not begin or end with a space, and it must begin with a letter or an underscore.

validate name in volumes

---

app/stylesheet/legacy/patternfly_overrides.scss
app/views/layouts/_center_div_no_listnav.html.haml
app/views/miq_policy_export/_export.html.haml

Before
After
Note
- Few **violations** and **recommendations** will be fixed when the [PR#8611](https://github.com/ManageIQ/manageiq-ui-classic/pull/8611) will be merged
- 2 of the violations are related to the file-chooser input field. "_Label text is located after its associated text input or <select> element_" will be fixed when we convert this page from HAML form to react form. It cannot be fixed now because we do not have control over the code for this file-import tag.

Fix Policies accessibility violations

---

app/controllers/vm_common.rb

Compute / Cloud / Instances / Images
Select 2 items to compare
**Before**
Additional (Previous selection) items appear in the compare page
https://user-images.githubusercontent.com/87487049/216001891-3379108e-d0a5-44f1-a0fd-8a3ac1b4e030.mov
**After**
https://user-images.githubusercontent.com/87487049/216002107-d3c55ef9-3360-469c-a8ee-95ea562a1729.mov

Fix selected items during compare

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js

1.
in basic mode of volume create, the user must choose an existing service. currently, the first service on the list is presented in the box as a default, but is not actually saved as the value, so the "add" button remains disabled, until a service is manually selected. If that first service is the desired one, the user must manually choose another and then re-select the first.
this fix adds 'Choose' to the top of the list, so it's clear that one must manually select a service.   
2.
in advanced mode, if the required capabilities don't match any resource, the resource multi-selection box currently remains on 'Choose' with no options, and the field description text explains that this means that no resources were found.
this fix adds the explanation inside the selection box, which is …

Fixes in volume create

---

app/controllers/mixins/ems_common.rb
app/controllers/storage_resource_controller.rb
app/controllers/storage_service_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/button/storage_service_new.rb
app/helpers/application_helper/listnav.rb
app/helpers/application_helper/page_layouts.rb
app/helpers/application_helper/toolbar/storage_service_center.rb
app/helpers/application_helper/toolbar/storage_services_center.rb
app/helpers/application_helper/toolbar_chooser.rb
app/helpers/cloud_volume_helper/textual_summary.rb
app/helpers/ems_storage_helper/textual_summary.rb
app/helpers/storage_resource_helper/textual_summary.rb
app/helpers/storage_service_helper.rb
app/helpers/storage_service_helper/textual_summary.rb
app/javascript/components/storage-service-form/index.jsx
app/javascript/components/storage-service-form/storage-service-form.schema.js
app/javascript/helpers/load-capabilities.js
app/javascript/packs/component-definitions-common.js
app/presenters/menu/default_menu.rb
app/services/ems_storage_dashboard_service.rb
app/views/storage_service/new.html.erb
app/views/storage_service/show.html.haml
app/views/storage_service/show_list.html.haml
config/routes.rb
product/views/StorageService.yaml
spec/config/routes.pending.yml
spec/helpers/cloud_volume_helper/textual_summary_spec.rb
spec/helpers/ems_storage_helper/textual_summary_spec.rb
spec/presenters/menu/default_menu_spec.rb

see issue https://github.com/ManageIQ/manageiq-ui-classic/issues/8616
also, this PR includes changes based on enhancements from PR #8631, and adds service_storage related enhancements.
this will probably require a rebase once #8631 is merged

storage service endpoint

---

app/controllers/application_controller.rb

We are not using the attributes portion of Rbac.search() So there is no need to calculate the record counts
Also, passing in the ids will bring back all records and we will also sort them to put them in the order of the ids passed in.
Converting to a sql count cuts the query down to only bringing back the ids (if we fetch these records again later, then we may have incurred an extra query here)
Now, in the end, I would like to drop assert_rbac all together. It is only used in a few places and they are relatively simple to remove, but I didn't want to add the testing effort at this time.

Convert assert_rbac from Rbac.search to Rbac.filtered

---

app/views/miq_request/_request.html.haml

Found in Services -> Requests -> Summary Page
Makes a slight modification to the way the request logs are passed to the react data table in order to make the code easier to understand at first glance. Functionally identical to old code.

Edited _request.haml to Make Code Clearer

---

app/presenters/menu/default_menu.rb
config/routes.rb

This change is required for the 3.7 release since the OpenStack update no longer supports this.
Through this PR, we are only hiding the monitor menu and removing the URLs from the system. Related code for this feature will be removed in a future PR.
Before
---------
After
---------

Hide Monitor menu

---

app/javascript/components/dashboard-widgets/widget-wrapper/index.jsx

**Before**
When space is available to render the menu, it works as expected
but, when no space is available at the bottom of the page(for minimised widgets), the menu disappears.
**After**
When space is available to render the menu, it works as expected - (no change here)
but, when no space is available at the bottom of the page, the menu renders to the top.

Fix dashboard widget overflow menu list visibility

---

spec/javascripts/support/jasmine_helper.rb

Recent versions of Chrome introduced a new headless mode[^1]. The old headless mode is still the default, but it seems they broke the old mode such that the /json endpoint of the devtools (which should return a JSON payload with info about the instance) returns an empty payload[^2]. This commit switches to the new headless mode, where that data is correct.
Note that in local testing, the new headless mode cannot run simultaneously as other Chrome instances, so you need to close any Chrome instance before running the specs. This will not be necessary in CI.
[^1]: https://developer.chrome.com/articles/new-headless/
[^2]: https://bugs.chromium.org/p/chromium/issues/detail?id=1418675

Fix javascript specs by moving to new Chrome headless mode

---

spec/javascripts/support/jasmine_helper.rb

This PR also partially reverts 5307f609 (#8610) to restore google-chrome-beta, but still allowing things to work when google-chrome-beta is not installed by falling back to the default behavior.
Followup to #8663

Add handling of older Chrome versions in jasmine specs

---

app/controllers/application_controller.rb
app/controllers/host_controller.rb
app/controllers/miq_ae_class_controller.rb
app/controllers/ops_controller.rb
app/controllers/ops_controller/ops_rbac.rb
app/controllers/ops_controller/settings/analysis_profiles.rb
app/controllers/ops_controller/settings/common.rb
app/controllers/ops_controller/settings/schedules.rb
spec/controllers/application_controller/build_audit_spec.rb
spec/controllers/ops_controller_spec.rb

This commit refactors a lot of duplication and redundancy around the build_audit_* methods as well as multiple implementations of password masking. Instead it reuses password masking from
Vmdb::Settings.mask_passwords!. Additionally it removes all special cases for auditing and moves those into a single set of auditing methods.
Depends on https://github.com/ManageIQ/manageiq/pull/22372 which changes Vmdb::Settings.mask_passwords! to do partial matching and includes all matching patterns defined in the old custom implementations here.

Refactor build_audit_* methods and reuse password masking from core

---

app/javascript/components/miq-structured-list/index.jsx
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/textual_summary.test.js.snap

Found a bug that the `Link` carbon component was not properly redirect users to the linked url when clicked. We has been using an `onClick` event rather than `href` per the [documentation](https://react.carbondesignsystem.com/?path=/story/components-link--default).

Link component redirects correctly now

---

app/services/container_service_mixin.rb

For metrics, when we have a `where` clause on `timetamp` we also order by `timestamp`. (trend. not 100%. thinking it should be 100%)
Typically the records come back from the database in inserted order (read: ordered by timestamp), so this tends to be in the right order.
A sporadic test found this issue:
spec/services/container_dashboard_service_spec.rb:460
```
1) ContainerDashboardService network trends show daily hourly network trends from last 24 hours only
Failure/Error:
expect(hourly_network_trends).to eq(
:dataAvailable => true,
:xData => [previous_date.beginning_of_hour.utc, current_date.beginning_of_hour.utc],
:yData => [2000, 2500]
)
expected: {:dataAvailable=>true, :xData=>[2023-02-28 11:00:00.000000000 +0000, 2023-02-28 12:00:00.000000000 +0000], :yData=>[2000, 2500]}
got: …
```

Order Container#hourly_metrics for widgets

---

app/javascript/components/ems_container_dashboard/helper.js
app/javascript/components/ems_container_dashboard/index.js
app/services/container_dashboard_service.rb

**Before**
Earlier, we removed the alerts module and its routes.
The Provider dashboard page had a route referring to the alerts module.
**After**
Removing the alerts block and its associated changes seems to fix the error.

Fix for provider dashboard page where items were not being loaded

---

app/helpers/chargeback_report_helper.rb

**Before**
- Recently, we converted the string tables to carbon tables for reports and dashboards.
- For this, we introduced a helper module which was included in various helper files.
- The file used to render the list here used a method from the new module which was not included in the chargeback reports module, causing the error.
**After**
- Including the helper methods seems to fix this issue

Fix for chargeback saved reports with undefined method

---

app/javascript/components/host-initiator-form/host-initiator-form.schema.js

Up to now, the length of the name of host initiator group was unlimited.
We're now limiting it to 15 characters.

host initiator name length validation

---

app/javascript/components/service-request-default/index.jsx
app/javascript/components/service-request-default/service-request-default.schema.js
app/javascript/spec/service-request-default-form/__snapshots__/service-request-default-form.spec.js.snap
app/javascript/spec/service-request-default-form/dummy-data.js
app/javascript/spec/service-request-default-form/service-request-default-form.spec.js

The `users` dropdown was incorrectly only every showing one option despite multiple being available for it to use. Additionally there were no tests associated to the page so I included some. 
In fixing the dropdown found a bug where the `Apply` button was not actually filtering by the user selected `Requester` option. Implemented that logic and fixed it. 
@miq-bot add-reviewer @jrafanie

Fixed users dropdown + adds spec tests

---

app/javascript/menu/group-switcher.jsx
app/stylesheet/menu.scss

Before
After
Suggestion: change this to the OverflowMenu component, we can remove the additional CSS.

Fix group switching dropdown visibility

---

app/javascript/components/miq-structured-list/index.jsx
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/textual_summary.test.js.snap

Follow up to https://github.com/ManageIQ/manageiq-ui-classic/pull/8667#issuecomment-1463475127. Reintroducing the `onClick` parameter so the `Link` component can work as intended. 
Bug was discovered and fixed across the following pages:

Fixing Link Component

---

app/javascript/components/tree-view/redux.jsx
app/javascript/oldjs/miq_tree.js
app/stylesheet/tree.scss

**Before**
- Select 2 items to compare
- Compare buttons are disabled since the first selected item is not saved for comparison.
- Therefore, Select 3 items
- Now, only 2 of the selected items are displayed for comparison.
- Now the compare buttons will be enabled.
**After**
- Select (2 or) 3 items.
- Compare buttons will be enabled.
- The selected 3 items are displayed for comparison.
Note:
- Had made style improvements in the tree.
- Had fixed a react prop type error displayed in the browser console.

Fix for selected item missing in genealogy compare selector

---

app/controllers/application_controller.rb

When discussing #8685, I happened to luckily find the default error handler.  It wasn't obvious.  This change moves it near the top of the file and adds an obvious banner before it.
cc @jeffibm @MelsHyrule @DavidResende0

Add big banner around the app controller default error handler

---

app/controllers/configuration_controller.rb
spec/config/routes.pending.yml

Continuation of https://github.com/ManageIQ/manageiq-ui-classic/pull/8685
Before
After

Fix forbidden page notifications for configurations page

---

app/helpers/settings_schedule_helper.rb

Follow upto https://github.com/ManageIQ/manageiq-ui-classic/pull/8686#discussion_r1134524503 .  converted the backticks to single quotes to fix the security issue

changing backticks to single quotes

---

app/views/service/show.html.haml

Returns a change that was undone in #8596 that was causing the tabs in the service summary page to not display correctly.
Before:
After:

Correct Missing Service Summary Tabs

---

app/stylesheet/miq-structured-list.scss

Fix summary label wrapping for long text without spaces

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
app/javascript/components/physical-storage-form/index.jsx
app/javascript/components/physical-storage-form/physical-storage-form.schema.js
app/javascript/components/storage-service-form/storage-service-form.schema.js
app/javascript/helpers/storage_manager/filter-by-capabilities-utils.js
app/javascript/helpers/storage_manager/filter-service-by-capabilities.js
app/javascript/helpers/storage_manager/load-provider-capabilities.js
app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap
app/javascript/spec/physical-storage-form/physical-storage-form.spec.js

This followup pr's after the pr's of the Schema and Api repos. 
This enhancement to the storage manager add the option for creating a new physical storage with enabled capabilities (default or custom)
Related Pr: (need to be merge together)

Create physical storage with capabilities

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
app/javascript/components/storage-service-form/index.jsx
app/javascript/components/storage-service-form/storage-service-form.schema.js

**this is based on changes from PR #8656 and will be rebased on master after that PR is merged**
before:
no field for attaching resources
after:
after selecting capabilities, a multi-select field of resources appears, offering resources filtered by the selected capabilities.

Select storage resources to attach in storage service create

---

app/javascript/components/host-initiator-group-form/host-initiator-group-form.schema.js
app/javascript/components/provider-form/index.jsx
app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap

**_provider_** with existing name failed on form submission, blocking that on field validation makes for a better UI:
**before:**
**after:**
---
**_host initiator group_** with existing name failed in backend, better to block in the UI as well:
**before:**
(task failure msg seems to have picked up a bug, will fix this in a different PR)
**after:**

added name validation to provider and host initiator group forms

---

app/javascript/menu/search.jsx

Changes the legend on the search bar in the nav menu to only display when the menu is expanded in order to prevent the `Choose a Filter` text from getting squished when the menu is condensed.
Before:
<div style="display:flex">
</div>
After:
<div style="display:flex">
</div>

Fixed Text Overlap in NavMenu Search Bar

---

app/javascript/components/timeline-options/timeline-helper.js

Timeline data was looping back and forth.

Sorting timeline data by date

---

app/controllers/application_controller/timelines.rb

Removing the `No events available for this timeline` timeline page flash as it can cause confusion for the users. 
Currently the pop up will only appear when the timeline page loads in and there are no available events (meaning it is displaying the correct behavior). However because of the dynamic nature of `events`, an event can load in moments after seeing this message and so the user even after seeing the message can use the form and search and see new events, hence the message stops being accurate. 

Removing flash message

---

app/controllers/service_controller.rb
spec/controllers/service_controller_spec.rb

If you retire a service via the UI
This calls `ServiceController#service_retire_now`
```
Started POST "/service/button/1?pressed=service_retire_now" for 127.0.0.1 at 2023-03-22 11:14:00 -0400
Parameters: {"pressed"=>"service_retire_now", "id"=>"1"}
```
This is aliased in the `CiProcessing` mixin as `retirevms_now`: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller/ci_processing.rb#L389
This ends up calling `generic_button_operation` and finding the record based on `record_class`: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/application_controller/ci_processing.rb#L603-L604
`record_class` defaults to `VmOrTemplate` in `CiProcessing`: https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/app …

Fix for `Service#service_retire_now` retiring VMs

---

app/javascript/components/cloud-volume-form/clone-cloud-volume-form.jsx
app/javascript/components/cloud-volume-form/clone-cloud-volume.schema.js

Added name validation to the clone volume 'name' field, so cloning will be prevented if the volume name already exists. 
This is a validation necessary for our provider, but I assumed it is needed for all providers, please let me know if this is not the case.
AutoSDE provider PR: https://github.com/ManageIQ/manageiq-providers-autosde/pull/215

added name validation to name field

---

app/views/miq_request/_request_dialog_details.html.haml
spec/views/miq_request/_request_dialog_details.html.haml_spec.rb

Before
________
After
__________
Issue throws when the custom dialogue has an integer value selected for a single select box.

Request dialog form bug fix

---

bin/webpack

After upgrading to node 18 we get the below error during webpack compile
```
this[kHandle] = new _Hash(algorithm, xofLen);
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
at module.exports (/home/runner/work/manageiq-ui-classic/manageiq-ui-classic/node_modules/webpack/lib/util/createHash.js:135:53)
at NormalModule._initBuildHash (/home/runner/work/manageiq-ui-classic/manageiq-ui-classic/node_modules/webpack/lib/NormalModule.js:417:16)
at handleParseError (/home/runner/work/manageiq-ui-classic/manageiq-ui-classic/node_modules/webpack/lib/NormalModule.js:471:10)
at /home/runner/work/manageiq-ui-classic/manageiq-ui-classic/node_modules/webpack/lib/NormalModule.js:503:5
at …
```

Add --openssl-legacy-provider to NODE_OPTIONS

---

app/javascript/components/ansible-credentials-form/index.jsx
app/javascript/components/ansible-repository-form/index.jsx
app/javascript/spec/ansible-credentials-form/ansible-credentials-form.spec.js

Now that there are 2 EmbeddedAutomationManagers we can't just assume that EmbeddedAnsible::AutomationManager == EmbeddedAutomationManager
**Automation / Ansible / Repositories**
Before
After
**Automation / Ansible / Credentials /** 
Before
After

Fix EmbeddedAnsible Repositories/Credentials

---

app/helpers/ops_helper.rb
app/helpers/ops_helper/group_rbac_details_helper.rb
app/views/ops/_rbac_group_details.html.haml

Before:
After:
Converted summary logic for view part only, Here the rbac_tag_box haml file at the end is not converted. It has been done by Dinesh in the PR https://github.com/ManageIQ/manageiq-ui-classic/pull/8717
Will integrate rbac_tag_box here after Dinesh's PR got merged.

Rbac Group summary conversion from HAML to React

---

app/javascript/components/cloud-volume-form/cloud-volume-form.schema.js
app/javascript/components/cloud-volume-form/index.jsx
app/javascript/helpers/storage_manager/filter-by-capabilities-utils.js
app/javascript/helpers/storage_manager/filter-resources-by-capabilities.js
app/javascript/helpers/storage_manager/filter-service-by-capabilities.js

each capability for filtering services and resources in volume create basic/advanced now has its own single-select field for n/a, true or false.
this prevents users from selecting conflicting capabilities (compression true and compression false) and enables to select the N/A option for a specific capability (or for all of them).
PR in providers repo:
**before:**
**after:**

split volume create capabilities to separate single select fields

---

app/helpers/request_info_helper.rb

**Before**
- Go Compute > Infrastructure > Virtual Machines > VMs & Templates page.
- Select a VM template. 
- Click Life Cycle and select Provision VMs.
- Click on the VM template again and click Continue.
- Fill in the values in the fields under Catalog, Environment, Hardware, Network tab.
- Under Customize tab, select Specification the the drop-down list but got the following.
**After**
Customise tabs are now displayed 
Note: similar fix made for `VM's, Host, PxeImage, IsoImage, WindowImage, Datastore, and Templates`

Fix for customized tab returning nil error while vm provisioning

---

app/javascript/components/storage-service-form/index.jsx
app/javascript/components/storage-service-form/storage-service-form.schema.js

part of issue:
co-dependent on the provider-pr there (already merged)
before this change, capabilities were fetched from within the schema, and presented to the user as a multi-select field with all possible capability values, including conflicting ones (e.g. both "True" and "False" for "Compression").
after this change, the capabilities are generated from the autosde provider `storage_service` model one-by-one as single-select field. this makes more sense both in terms of ui and of architecture.
**before:**
**after:**
here also showing the Storage Resources multi-selection field:
-=-=-
but I get a react bug regarding a `resolveProps`
which I don't get in the volume form:
**edit:**
I seem to have found a solution - deleting the `resolveProps` property off of the schema field before …

split service create capabilities to separate single select fields 

---

app/helpers/application_helper/button/vm_management_console.rb
app/helpers/application_helper/toolbar/x_vm_center.rb

This change ensures that only vms belonging to a `IbmPowerHmc` Provider will have the Management Console button under the Access dropdown
Before:
After:

Added new Button Class to Ensure "Management Console" Button Only Appears When it Should

---

app/javascript/components/provider-dashboard-charts/heat-map-chart/HeatMapChartGraph.js
app/javascript/components/provider-dashboard-charts/heat-map-chart/index.js
app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/index.js
app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationDonutChart.js
app/javascript/components/provider-dashboard-charts/provider-dashboard-utilization-chart/utilizationMemoryDonutChart.js

**Normal Screen - Global Utilization - CPU**
After
**Full Screen - Global Utilization - CPU**
Before
After
**Normal Screen - Global Utilization - Memory**
Before
After
**Fullscreen- Global Utilization - Memory**
After
**Normal Screen - Cluster Utilization -CPU**
Before
After
**Fullscreen - Cluster Utilization -CPU**
Before
After
**Normal Screen - Cluster Utilization - Memory**
Before
After
**Fullscreen - Cluster Utilization - Memory**
Before
After

Fix undefined name for infrastructure metric tables

---

app/presenters/tree_builder_automate_catalog.rb

This was happening for trees that had classes and folders at the same level
/cc @DavidResende0

Fix filter_ae_objects to allow multiple classes to pass through

---

bin/webpack

HACK: Check if --openssl-legacy-provider flag is available and use it.
If nodejs is compiled with openssl 3, then this flag is available
If nodejs is compiled with openssl 1.1, then this flag is not available
and will fail if we hardcode it into NODE_OPTIONS
This can be removed once we upgrade webpack as then we don't need the
flag anymore.

Fix issue where openssl-legacy-provider option is not always available 

---

app/helpers/utilization_helper.rb
app/javascript/components/miq-custom-tab/index.jsx
app/stylesheet/miq-custom-tab.scss
app/views/catalog/_form.html.haml
app/views/catalog/_sandt_tree_show.html.haml
app/views/catalog/_st_angular_form.html.haml
app/views/layouts/_content.html.haml
app/views/miq_request/_prov_wf.html.haml
app/views/utilization/_utilization_tabs.html.haml

**Tabs conversion**
Before
Tab Panels fields were not selectable using the keyboard
After
Tab Panels fields can be selected using the keyboard
**Accessibility violations fixes**
Before
After

Fix Utilisation accessibility violation and tabs conversion from HAML to React

---

app/javascript/menu/main-menu.jsx

Changed open/hide menu to force close the menu when toggled when currently set to open. (Note this change only affects downstream ui, since the hide menu toggle is a different button upstream)
Before:
https://user-images.githubusercontent.com/64800041/235228551-94bbcb0f-cbd6-4999-b640-107758431b31.mov
After:
https://user-images.githubusercontent.com/64800041/235228616-26c8c04f-f6c5-42f0-94ad-4da89ebee1bf.mov

Changed Button To Force Menu to Collapse on Click

---

lib/gtl_formatter.rb

Use fa-unplugged as an icon indicating non operational machine state
This state was introduced before 2015
I could not find any other states in the providers that were not already in the list of states in the ui helper.
Of note
- [OpenStack](https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/cloud_manager/vm.rb#L27) links `error` to `non_operational`.
- [ibm power hmc](https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/blob/master/app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb#L72) links `error` to `unknown`
- [kubevirt](https://github.com/kbrock/manageiq-providers-kubevirt/blob/master/app/models/manageiq/providers/kubevirt/infra_manager/vm.rb#L10) links `Failed` to `off`
---
I was not able to reproduce …

add icon for non_operational

---

app/javascript/components/async-action-button.jsx
app/javascript/components/storage-service-form/get-compliant-resources.jsx
app/javascript/components/storage-service-form/index.jsx
app/javascript/components/storage-service-form/storage-service-form.schema.js

issue: #8749 
added a button in service edit mode which enables the user to check what currently attached resources will comply with the selected capabilities.
this includes a new async-action-button.jsx which is based on async-credentials.jsx, and enables sending an async request to the provider's backend and display the resolved results (or an error message if needed).
if there's a way to beautify the returning string, or even render it in a table, it could be a great improvement.
the enhancement is based on the yet to be merged https://github.com/ManageIQ/manageiq-ui-classic/issues/8728, and should be rebased on master after that issue is merged.
https://user-images.githubusercontent.com/106743023/230888143-5709af13-8461-4b62-89cc-d40ff4c47dae.mov

storage service edit mode: check which attached resources are compliant to selected capabilities

---

app/helpers/application_helper/toolbar/cloud_volume_snapshot_center.rb
app/helpers/application_helper/toolbar/cloud_volume_snapshots_center.rb
app/helpers/application_helper/toolbar_chooser.rb
app/services/ems_storage_dashboard_service.rb

We have developed an integration with a new resource type - "cloud volume snapshot" on the Autosde side. Now, we can provide a list of snapshots from the attached physical storage, create a new one based on a particular volume object and delete it - by using the Autosde rest endpoint (The Autosde GEM is already updated with these new features).
Following these new features, I have added to our (MIQ Autosde provider) collector and refresher to pull snapshots from Autosde and show them in the right place - Cloud Volume Snapshots. I also added the counter component to the provider dashboard.
List page:
Snapshot summary page:
Dashboard:
Create snapshot from cloud volume:
1.
2.
Delete button exists as well at the snapshots page
- https://github.com/ManageIQ/manageiq/pull/22359
- …

Implement cloud snapshot collector, list page, create & delete methods

---

lib/gtl_formatter.rb

the summary page uses fa-exclamation
Following suite
fixes #8776
@agrare I like the idea of changing the provider to return `error` instead.
https://github.com/ManageIQ/manageiq-ui-classic/pull/8776#issuecomment-1531875827

update non_operational to match other non_operational status

---

app/helpers/ops_helper/textual_summary.rb
app/javascript/components/miq-structured-list/index.jsx
app/javascript/components/textual_summary/table_list_view.jsx
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
app/views/ops/_rbac_tenant_details.html.haml

Before
unable to view the tenant quota details
After
- Modified the keyword from `total` to `total_quota` to match header and its row-cell item
- Adjusted the width of the Tenant Quota block to screen width (lg-10 to lg-12)
- Modified the **TableListView** component to prepare the data necessary for the **MiqStructuredList**
- Added border to the mode `table_list_view`

Fix quota list visibility for tenants

---

app/controllers/ops_controller/settings/common.rb

I'm cleaning up old branches.
I noticed these 3 spots that iterates over errors and still treat errors as 2 fields instead of 1.
@jrafanie do you remember when we made these changes?
Do you know if we intentionally didn't convert these?
(or if I'm confused about this)
- ref: https://github.com/ManageIQ/manageiq-ui-classic/pull/8408

iterator errors as an array (6.1.3.1 change)

---

app/stylesheet/miq-custom-tab.scss
app/views/miq_request/_prov_wf.html.haml

Fix for missing tab contents while adding service catalog item and provisioning instance

---

app/controllers/mixins/breadcrumbs_mixin.rb
app/helpers/request_details_helper.rb
app/views/layouts/_tabs.html.haml

Depends On: https://github.com/ManageIQ/manageiq/pull/22506
Found in: Services -> Requests -> Select Request From List
Marks strings for translation in the Request Details page. Most of these strings used to be marked prior to the recent form conversion.
Before:
After:

Mark Strings in Request Details for Translation

---

spec/controllers/container_controller_spec.rb
spec/controllers/container_node_controller_spec.rb

After [1] below, the event_where_clause logic has been implemented in the ems_event_filter and miq_event_filter and expectations around proper associations are enforced.
[1] https://github.com/ManageIQ/manageiq/pull/22388

Container and container node timelines require ems

---

app/views/layouts/_tabs.html.haml
cypress.config.js
cypress/e2e/ui/menu.cy.js
cypress/support/e2e.js

Firefox throws more errors than chrome does while cypress testing. These are either subscription undefined error (same as chrome but different error message) or network/abort errors related to loading a new page before the previous page and its API calls are finished loading. Added extra error handling to ensure these errors don't cause cypress tests to fail in firefox.
Should be merged after this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8813

Fix cypress tests for firefox

---

spec/javascripts/support/jasmine_helper.rb

Since the underlying shell used by system can be different, prefer a portable version of redirection as &> is shell specific.
@agrare Please review.

Change redirects to be portable

---

app/javascript/components/miq-structured-list/index.jsx
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/multilink_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/simple_table.test.js.snap
app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap
app/stylesheet/miq-structured-list.scss

Enhance the MiqStructuredList for summary pages

---

app/javascript/components/miq-data-table/miq-table-cell.jsx
app/stylesheet/miq-data-table.scss

**1. Datastores**
Before
After
-----------------------------------------------------------
**2. Automation Managers**
Before
After
-----------------------------------------------------------
**3. Service Requests**
Before
After
-----------------------------------------------------------
**4. Containers**
Before
After
-----------------------------------------------------------
**5. Container Images**
Before
After
-----------------------------------------------------------
**6. Instances by Providers**
Before
After
Please not that icons and images are slightly smaller than before

Fix text truncation in data tables

---

cypress/support/commands/menu.js

Fixed menu item tests that were failing due to navigating to a page within the same submenu. For example: Compute > Infrastructure > Providers and then trying to navigate Compute > Infrastructure > Clusters causes the menu item to disappear and the test to fail.

Fixed empty db menu tests

---

app/controllers/dashboard_controller.rb

The auth_error incorrectly said "Overview / Timelines" before this fix.
Before:
After:
@jeffibm or @DavidResende0 Please review.

Fix page title on auth_error screen

---

app/helpers/application_helper/button/embedded_workflow.rb

Adds a button helper similar to `app/helpers/application_helper/button/embedded_ansible.rb` for use in the embedded workflow credential and repository show/show_list pages

Added Button Helper For Embedded Workflows

---

app/javascript/components/pf_aggregate_status_card.jsx

Fixed a bug with the physical providers overview page occurring when the page is loaded with no providers.
Before:
After:

Fixed physical providers empty page

---

app/controllers/miq_request_controller.rb

Fixed an issue where the request refresh button does not actually refresh the content on the page.
Create a request:
After clicking the refresh button (no change):
After clicking the refresh button with this fix:
@miq-bot add_reviewer @DavidResende0
@miq-bot assign @DavidResende0 

Fix the request refresh button

---

app/stylesheet/legacy/dialog_fields.scss

Order Service page
**Before**
The Dropdown option list goes under the header and the search box is not visible.
**After**
The Dropdown option stays over the header and the search box is visible.
Note: connect `bluecf-customization` to see the header.

Fix dropdown options that overlaps with header

---

app/javascript/components/storage-service-form/get-compliant-resources.jsx

changed `reject` to another `resolve` since otherwise the form can't be submitted. 
A negative answer in the compliance check shouldn't block submission, only serve as a warning.
**before:**
changing capability `compression` to `True` produces a rejection on the compliance check, and form submission is blocked even when a resource which supports that capability is selected. 
**after:**
the failed check returns a warning and not an error/rejection, so when a supporting resource is selected, the form can be submitted.

failure in resource compliance check in storage service update shouldn't block form submission 

---

app/helpers/application_helper/toolbar/ansible_repository_center.rb

Ansible repository refresh button was disabled on the summary page. This pr fixes the issue and enables the button.
Before:
After:
@miq-bot add_reviewer @agrare 

Fixed ansible repository refresh buttons

---

app/controllers/workflow_controller.rb
app/controllers/workflow_repository_controller.rb

This PR wrap prototype checks around the workflows and workflow_repositories controllers.  Note that setting the prototype flag still requires restarting the worker - I haven't found a way to do that yet because it requires reloading the menu and we don't seem to have a hook for that just yet, so I wanted to just get this base functionality in first.
Part of #8715 
@DavidResende0 Please review.

Mark workflow controllers as prototype

---

spec/controllers/workflow_repository_controller_spec.rb

Fixed workflow repository specs that were failing due to auth/permission errors.
@miq-bot add_reviewer @agrare 

Fixed workflow repository specs

---

app/javascript/components/settings-category-form/schema.js
app/javascript/spec/settings-category-form/__snapshots__/settings-category-form.spec.js.snap

Found in: Application Settings -> Settings -> Region -> Tags -> Add Category
Before:
After:

Mark Switch Labels for Translation in Settings-Category Form

---

cypress/e2e/ui/login.cy.js

Fixed cypress logout test. The API call that was being intercepted was incorrect. Changed to intercept the right call and also changed the expected status code. This allows the test cases to pass on all of Chrome, Edge, and Firefox.

Fixed cypress logout test

---

app/controllers/vm_common.rb

Before
-----------
After
------------
Click Compute -> Clouds -> Instances page. Select Instances from Explorer and apply a filter. Go to the Instances by the provider. The data table shows the filtered instances but the filter title and clear option are missing.

Filter effect text and clear option missing in sub listing pages

---

cypress.config.js

This is for CI purposes, where these extra videos take up space, and
aren't needed when trying to debug failures. Additionally, this commit
removes the video compression since it takes time, and we are going to
delete 90%+ of the videos anyway.
~~WIP because I just added in the CI env var check and want to verify that works first.~~ It works: https://github.com/Fryguy/manageiq-cypress-tests/actions/runs/5614492505

Delete the cypress videos for passing tests on CI

---

app/controllers/catalog_controller.rb
app/controllers/mixins/automation_mixin.rb
app/helpers/miq_ae_customization_helper.rb
app/javascript/oldjs/controllers/dialog_editor/dialog_editor_controller.js
app/javascript/oldjs/services/dialog_editor_http_service.js
app/views/miq_ae_customization/editor.html.haml
package.json
yarn.lock

Related PR - 
**After**
The automation Type Field introduced
Can select Embedded Workflow from the select-box
Opens up a dialog box when we click on the workflow load-balancer icon
Select an item from the list to see the selected item in the embedded_workflow's field

Introducing embedded_workflow to dynamic select box in service dialogs

---

config/routes.rb
spec/config/routes.pending.yml

Adds the missing advanced search routes to the Configuration Profiles page.
Before:
After:

Add Missing Routes to Configuration Profiles

---

app/controllers/catalog_controller.rb
app/controllers/mixins/automation_mixin.rb
app/helpers/automate_tree_helper.rb
app/helpers/catalog_helper.rb
app/javascript/components/workflows/helper.js
app/javascript/components/workflows/workflow-entry-points.jsx
app/javascript/oldjs/miq_application.js
app/javascript/packs/component-definitions-common.js
app/stylesheet/miq-data-table.scss
app/views/catalog/_embedded_workflows_modal.html.haml
app/views/catalog/_entry_point_selector.html.haml
app/views/catalog/_form_basic_info.html.haml
app/views/catalog/_provision_entry_point.html.haml
app/views/catalog/_reconfigure_entry_point.html.haml
app/views/catalog/_retire_entry_point.html.haml
config/routes.rb
spec/config/routes.pending.yml
spec/controllers/catalog_controller_spec.rb

Before
* `Provisioning Entry Point `is mandatory, has a default value
* `Reconfigure Entry Point` is optional, and does not have a default value
* `Retirement Entry Point `is optional, has a default value
After
**Service Catalog item**
1. Go to Add a new Service Catalog item Form
2. `Provision Entry Point, Reconfigure Entry Point, Retirement Entry Point's `input changed to Drop down list
3. Drop-down options are `Embedded Automate & Embedded Workflows`
4. When one item is selected, the corresponding input field appears
5. When you click on the input field, a new modal box appears for embedded workflows. The old modal will appear for embedded automated
6. When we select one of the items in the list, the name appears on the input field of

Adding embedded workflows to service catalog item

---

app/javascript/components/performance-charts/groupChart.js
app/javascript/components/performance-charts/index.jsx

Fixed utilization `Selected Day Percent Utilization` chart.
Before:
After:

Fix utilization chart

---

config/routes.rb
spec/config/routes.pending.yml

Same PR as https://github.com/ManageIQ/manageiq-ui-classic/pull/8862 but for Morphy. Solves the backport conflict.

[MORPHY] Add Missing Routes to Configuration Profiles

---

lib/tasks/manageiq/ui_tasks.rake

Without this it allows packages to be updated.  Not only is that not what we want for production builds, but upgrading from es-abstract 1.21 to 1.22 breaks us right now.
```
ERROR in ./node_modules/es-abstract/2015/Canonicalize.js Module not found: Error: Can't resolve '../helpers/caseFolding' in '/root/BUILD/infrastructure-management-gemset-16.0.0/bundler/gems/bluecf-ui-classic-2ea695ae0f41/node_modules/es-abstract/2015'
@ ./node_modules/es-abstract/2015/Canonicalize.js 15:18-51
@ ./node_modules/es-abstract/es2015.js
@ ./node_modules/es-abstract/es6.js
@ ./node_modules/array-includes/index.js
@ multi es6-shim array-includes whatwg-fetch core-js/stable regenerator-runtime/runtime
webpack: done 2023-07-29T02:42:38.451Z
```

Ensure yarn.lock is not updated by yarn install

---

app/controllers/host_controller.rb
app/helpers/application_helper/button/host_edit.rb
app/helpers/application_helper/toolbar/host_center.rb
spec/controllers/host_controller_spec.rb

Adds a check to the Host controller that ensures that a host is able to be edited/updated before proceeding to the Host Edit Form. Also disables the Edit button in the `show` page when the above condition is met.
**Before:**
**After:**
Single Host Edit
Multi-Host Edit
`show` page

Added supports?(:update) check to Host Edit Form

---

app/stylesheet/miq-data-table.scss

Removed the justify alignment style for cells with multiple lines
**Before**
**After**
Notable changes on the column `Description` and` Last Message`

Fix data-tables cell text alignment

---

lib/tasks/manageiq/ui_tasks.rake

This reverts commit 56580941034d50a422e227c4abe2e00b4a20856c.
Followup from https://github.com/ManageIQ/manageiq-ui-classic/pull/8882#discussion_r1281182335

Revert "Ensure engines lock down es-abstract"

---

app/presenters/menu/manager.rb
spec/presenters/menu/menu_manager_spec.rb

This method will allow for reloading the menu as Settings change.
@agrare Please review.
This is technically part of the Workflows work in #8715, since I want the prototype settings change to call this (but it will be a core change for that).

Add Menu::Manager.reload method

---

app/controllers/report_controller/reports/editor.rb
app/views/report/_form_chart.html.haml
spec/controllers/report_controller_spec.rb

Depends on
Proposing to make the "chart top values" (currently hardcoded to 10) externalized to `settings.yaml` and thus customizable. It'd read the below setting, if present, and use it. If this is good, I'm happy to create a PR for the Core with the default value (10).
```
:reporting
:chart_top_values: 20
```
This controls how long/big this dropdown goes;

Customizable chart top values (dropdown choices)

---

app/stylesheet/miq-structured-list.scss

Notable changes in `Smart Management` box
Before
After

Fix for the subrow items in summary pages

---

cypress.config.js
cypress/e2e/ui/searchbox.cy.js

Fixed lint errors in the cypress config file and added a default view port for all tests as well as removed the viewport line from the searchbox test file.

Fix cypress config file

---

app/javascript/components/reconfigure-vm-form/reconfigure-form-fields.js
app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap

`Memory Type` changed to `Unit`
Before
After

Rename memory labels in reconfigure form

---

app/javascript/components/notification-message.jsx
app/javascript/helpers/notification-types.js
app/javascript/spec/notification-message/__snapshots__/notification-message.spec.js.snap
app/javascript/spec/notification-message/notification-message.spec.js
app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap

Before
- A few icons were not being rendered in the **`NotificationMessage`** component
- Also, the error notification was not available.
After

Refactor NotificationMessage component

---

app/controllers/ops_controller/ops_rbac.rb

The params[:id] is used to identify a particular tenant and allow
different access controls for different tenants. The view to list the
tenants uses params[:id] = 'xx-tn', which breaks the role_allows? method
with a '[RuntimeError] role_allows? no feature was found with
identifier: ["rbac_tenant_manage_quotas_tenant_tn"].' message.
The base "rbac_tenant_manage_quotas_tenant" feature is sufficient, so
adding an extra conditional to skip the whole id parsing allows viewing
the list of tenants.
Before:
After:
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8895

Fix Configuration>Access Control>Tenants list view

---

package.json
yarn.lock

This commit builds on top of #8906 to add more package lockdowns in order to prevent es-abstract 1.22 from being installed in the s390x environment since that env has problems with it when run under yarn 1
(Reminder that we need yarn 1 for the time-being because builds on yarn 3 hang on s390x, however yarn 1 ignores the lockfile and installs the latest version regardless, which sometimes brings in packages that are problematic; in this case es-abstract 1.22)
@jrafanie @bdunne Please review. (Related to ManageIQ/manageiq-ui-service#1861)
This is the yarn1 diff showing that es-abstract 1.22 has been removed for s390x:
```diff
@ yarn.lock:2607 @ array-flatten@^2.1.2:
resolved "https://registry.yarnpkg.com/array-flatten/-/array-flatten-2.1.2.tgz#24ef80a28c1a893617e2149b0c6d0d788293b099" …
```

More s390x lockdowns

---

app/controllers/ops_controller.rb
app/controllers/ops_controller/diagnostics.rb
app/javascript/components/c-and-u-collections-form/helper.js
app/javascript/components/c-and-u-collections-form/index.jsx
app/javascript/components/c-and-u-collections-form/schema.js
app/javascript/packs/component-definitions-common.js
app/javascript/spec/c-and-u-collections-form/__snapshots__/c-and-u-collections-form.spec.js.snap
app/javascript/spec/c-and-u-collections-form/c-and-u-collections-form.spec.js
app/views/ops/_diagnostics_cu_repair_tab.html.erb

old PR - https://github.com/ManageIQ/manageiq-ui-classic/pull/8791
BEFORE
AFTER

C and U collection form conversion from HAML to React

---

app/views/layouts/remote_console.html.haml

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8419
The changes made in https://github.com/ManageIQ/manageiq-ui-classic/pull/7838 made it so that the html5 web consoles no longer had their css stylings applied in the ui making them borderline unusable. This should reapply the css to the remote console ui.
Before:
After:

Fixed Missing Styling for Remote Consoles

---

app/javascript/oldjs/services/dialog_editor_http_service.js
package.json
yarn.lock

Before
After
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/8900
Dependent PR - https://github.com/ManageIQ/ui-components/pull/481
To Test in local -
ui-components 1.5.1 is available with the changes
-or-
Link your local ui-components in classic package.json with the local path instead of version
run `yarn build` in ui-components
run `yarn` in ui-classic

Prefix workflows list with repository

---

app/controllers/catalog_controller.rb

Fixed permission errors that occur with the Service > Catalogs page.
When creating a user with a role that only has permissions for each specific tab of the Catalog explorer you run into permission errors.
Before:
Using a user account with a role that only has permissions for catalog items and clicking on the catalog items table produces this error:
Using a user account with a role that only has permissions for service catalogs and clicking on the service catalogs table produces this error:
Using a user account with a role that only has permissions for catalogs and clicking on the catalogs table produces this error:
After:
Using a user account with a role that only has permissions for catalog items and clicking on the catalog items table produces this summary page:
Using a user account …

Fixed service catalog permission errors

---

app/javascript/components/ansible-credentials-form/index.jsx

**Credential type: Azure**
Before - Subscription ID, Tenant Id, Client Id is missing
After
**Credential type: Google Compute Engine**
Before - Project is missing
After

Fix for displaying ansible credential info

---

app/views/catalog/_provision_entry_point.html.haml
app/views/catalog/_reconfigure_entry_point.html.haml
app/views/catalog/_retire_entry_point.html.haml

Fix for
```
Failure/Error: = text_field_tag("fqname",
ActionView::Template::Error:
undefined method `camelize' for nil:NilClass
```
It appears to have started failing here https://github.com/ManageIQ/manageiq-ui-classic/actions/runs/6343793822/job/17261288587#step:8:688
I tried checking out the last green UI commit paired with a core commit from the same time and the test is still failing.

Fix .camelize after a &. safe navigation

---

app/helpers/miq_request_helper.rb
app/javascript/components/request-workflow-status/data.js
app/javascript/components/request-workflow-status/index.jsx
app/javascript/components/request-workflow-status/request-workflow-status-item.jsx
app/javascript/packs/component-definitions-common.js
app/stylesheet/application-webpack.scss
app/stylesheet/workflows.scss
app/views/miq_request/_request.html.haml
app/views/miq_request/_st_prov_show.html.haml

Note: Using dummy data
Related PR-
NotificationMessage components issues have been solved here - https://github.com/ManageIQ/manageiq-ui-classic/pull/8894

Introducing workflow status list in request's show page

---

app/controllers/chargeback_assignment_controller.rb

Fixed the missing translation for the 'Chargeback Assignments' title on the Overview > Chargeback > Assignments page Storage tab.
Before:
After:

Fixed chargeback rates title missing translation

---

app/javascript/components/data-tables/optimization/helper.js

Fixed the optimization table on the Overview > Optimization page missing translations for the 'Queue Report' button.
Before:
After:

Fixed optimization table translations

---

app/javascript/components/miq-alert-set-form/miq-alert-set-form.schema.js
app/javascript/spec/miq-alert-set-form/__snapshots__/miq-alert-set-form.spec.js.snap

Displaying the database length limit in the ui
(Just trying to get pen tests fixed)
I thought the model's values would be displayed in the UI.
Looks like this is manually entered in 2 places
https://github.com/ManageIQ/manageiq/pull/21921
These limits are arbitrary. We changed a limit of 50 to 100 and then to 255
The UI was not fixed. So testers trying 70 (larger than 50) thought that no limit took place
This fixes the UI so testers can ensure the limits are met

Change ui to display max alert description length

---

app/helpers/request_info_helper.rb

Issue was introduced by this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8517.
Fixed an issue where the VM Provision custom specifications table was not displaying data correctly.
Before:
After:
Fixes https://github.com/ManageIQ/manageiq/issues/22746

Fixed provision custom specifications table

---

app/helpers/request_info_helper.rb

We were checking two different keys in the `data` hash, first was simply a typo.  The result was that there were never any customization_templates being displayed.
Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/8748/files#diff-49fa91f9c8b1007440a2abba8b2c7e63b6d0deadc75fdf28b8b894216e59a065R152
Before:
After:
Fixes https://github.com/ManageIQ/manageiq/issues/22746

Fix missing customization_templates list

---

app/javascript/components/miq-data-table/miq-table-cell.jsx
app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap

Fixed console log warnings for miq table cell button size.
Before:
After:

Fixed console warning for miq table cell button size

---

app/controllers/ops_controller/settings/upload.rb
spec/controllers/ops_controller/settings/data/test.txt.ico
spec/controllers/ops_controller/settings/data/test.txt.png
spec/controllers/ops_controller/settings/upload_spec.rb

Added more validation to the Settings > Application Settings > Custom Logos upload functionality. Added more checks to ensure validity of logo files being uploaded.

Added better logo file validation

---

app/javascript/components/workflow-credential-mapping-form/workflow-credential-mapping-form.schema.js
app/javascript/spec/workflow-credential-mapping-form/__snapshots__/workflow-credential-mapping-form.spec.js.snap

I named/labeled one of the custom components created in the credential mapper form 'test' during development and then forgot to update it after since neither it's name or label appears in the form itself. This change gives the component a proper name and also adds some ids to components that didn't have any (No changes to form behaviour/functionality). Also updated the specs to match.

Updated Component Names/Ids in Credential Mapper Form

---

app/javascript/components/toast-list/toast-item.jsx
app/javascript/components/toast-list/toast-list.jsx
app/javascript/miq-redux/notification-reducer.js
app/javascript/spec/toast-list/__snapshots__/toast-list.spec.js.snap

Not every toast notification was rendered. only the recent 3 will be rendered.
**Before**
- 7/10 toast notifications were not being rendered.
- The `timeout` props were just hiding the `toastNotification` using the carbon component feature.
- The close button will mark the notification as read by removing the notification from the array + API call (no change here)
https://github.com/ManageIQ/manageiq-ui-classic/assets/87487049/be504c55-ee43-489a-8893-efea13eb12a0
**After**
- This PR renders 3 notifications at a time, till all are displayed
- All `toastNotification` will be displayed with a timeout feature.
- When timed-out, the notification will be marked as read and the notification will be removed from the list
https://github.com/ManageIQ/manageiq-ui-classic/assets/87487049/0bef7bd3-0fcf …

Fix for missing toast notifications

---

app/javascript/components/miq-data-table/index.jsx
app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap
app/javascript/spec/tenant-quota-form/__snapshots__/tenant-quota-form.spec.js.snap
app/javascript/spec/workflow-credential-mapping-form/__snapshots__/workflow-credential-mapping-form.spec.js.snap

Fixed table header accessibility issues for column headers without any text.
Before:
After:

Fix table header accessibility issues

---

app/helpers/application_helper.rb
app/helpers/application_helper/listnav.rb
app/views/layouts/listnav/_explorer.html.haml
spec/helpers/application_helper_spec.rb

Fixed explorer tree accessibility violations to reduce the number of violations that appear when running the accessibility scan  on pages that have an explorer tree.
Before:
After:

Fixed explorer tree accessibility violations

---

app/views/ops/_settings_authentication_tab.html.haml

Fixed most accessibility issues with the Server Settings Authentication Page. Some of remaining violations need to be fixed by converting the page to react which can be done in a follow up PR. The rest of the violations are due to the explorer screen which will exist on every page that has the explorer tree and will not be fixed until all the explorer pages are removed.
Before:
After:

Fixed accessibility issues with the server settings authentication page

---

app/javascript/components/host-edit-form/host-edit-form.jsx

The Host Edit form lets you edit either a single host or multiple at a time. This lead to a bug when submitting the payload where the form was calling `/api/hosts/{id}` but submitting edits to one or more hosts In the payload. The payload also included the id of the hosts inside which caused another error.
This change makes it so that the form just calls `/api/hosts/` instead while still keeping the id in the payload. Also changed the form redirect after submitting, to depend on whether your editing one or more hosts.

Remove Id from Host Endpoint When Submitting Form

---

app/controllers/application_controller/buttons.rb
app/controllers/service_controller.rb
spec/controllers/application_controller/buttons_spec.rb

Before
When we hit the custom buttons from the Service#show page, there was no action.
After
The custom button actions are now working and being redirected to another page...

Fix for custom button action events

---

app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
app/javascript/spec/ansible-credentials-form/__snapshots__/ansible-credentials-form.spec.js.snap
app/javascript/spec/cloud-database-form/__snapshots__/cloud-database-form.spec.js.snap
app/javascript/spec/cloud-object-store-container-form/__snapshots__/cloud-object-store-container-form.spec.js.snap
app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
app/javascript/spec/diagnostics-collect-log-form/__snapshots__/diagnostics-collect-log-form.spec.js.snap
app/javascript/spec/generic-objects-form/__snapshots__/generic-objects-form.spec.js.snap
app/javascript/spec/host-aggregate-form/__snapshots__/host-aggregate-form.spec.js.snap
app/javascript/spec/host-edit-form/__snapshots__/host-edit-form.spec.js.snap
app/javascript/spec/host-initiator-group-form/__snapshots__/host-initiator-group.spec.js.snap
app/javascript/spec/physical-storage-form/__snapshots__/physical-storage-form.spec.js.snap
app/javascript/spec/provider-form/__snapshots__/protocol-selector.spec.js.snap
app/javascript/spec/pxe-customization-template-form/__snapshots__/pxe-customization-template-form.spec.js.snap
app/javascript/spec/pxe-image-type-form/__snapshots__/pxe-image-type-form.spec.js.snap
app/javascript/spec/pxe-iso-datastore-form/__snapshots__/pxe-iso-datastore-form.spec.js.snap
app/javascript/spec/pxe-iso-image-form/__snapshots__/pxe-iso-image-form.spec.js.snap
app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
app/javascript/spec/schedule-form/__snapshots__/schedule-form.spec.js.snap
app/javascript/spec/select/__snapshots__/select.spec.js.snap
app/javascript/spec/service-request-default-form/__snapshots__/service-request-default-form.spec.js.snap
app/javascript/spec/settings-time-profile-form/__snapshots__/settings-time-profile-form.spec.js.snap
app/javascript/spec/vm-floating-ips-form/__snapshots__/vm-floating-ips-form.spec.js.snap
app/javascript/spec/workflow-credential-mapping-form/__snapshots__/workflow-credential-mapping-form.spec.js.snap
app/javascript/spec/workflow-credentials-form/__snapshots__/workflow-credentials-form.spec.js.snap
app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
package.json
yarn.lock

Fix for the issue :  https://github.com/advisories/GHSA-67hx-6x53-jw92
A security vulnerability was reported with the babel/traverse package, which we aren't using directly. As a workaround, we've updated the babel/core package, which will now include the latest version of babel/traverse.

Updated the package babel/core

---

app/controllers/configuration_controller.rb

Depends on 
Fixes ManageIQ/manageiq-ui-classic#8735

Use new dedicated my_settings_view permission

---

app/views/configuration/_timeprofile_form.html.haml

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8966
Fixes an issue of an error screen being presented when trying to copy a new time profile.
Before:
After:

Fix copy time profile error

---

app/controllers/service_controller.rb
app/views/miq_request/_service_reconfigure_show.html.haml
app/views/service/service_reconfigure.html.haml
app/views/shared/dialogs/_reconfigure_dialog.html.haml
config/routes.rb

Continuation Of: https://github.com/ManageIQ/manageiq-ui-classic/pull/8428
Returns the reconfigure service functionality accidentally removed in #8229. Also fixes an issue with the reconfigure service request summary page that was preventing the "Dialog Options" section from displaying correctly.
**Preview:**
Service Summary Page:
Reconfigure Page:
Request Summary Page:
Note: https://github.com/ManageIQ/manageiq-ui-classic/pull/8951 will eventually convert these pages over to react

Fixed Service Reconfigure Form and Request Summary Pages

---

app/helpers/miq_ae_class_helper.rb
app/javascript/components/miq-structured-list/helpers.js
app/javascript/components/miq-structured-list/miq-structured-list-body/value-tags/miq-structured-list-inputs.jsx
app/javascript/components/miq-structured-list/miq-structured-list-body/value-types/miq-structured-list-object.jsx
app/javascript/spec/miq-structured-list/__snapshots__/miq-structured-list.spec.js.snap
app/javascript/spec/miq-structured-list/miq-structured-list.spec.js
app/javascript/spec/textual_summary/data/code_mirror_data.js
app/views/miq_ae_class/_method_inputs.html.haml

Integrate the `CodeMirror` component in the `MiqStructuredList` component.
Note: Edit page will remain the same.
Before
After

Integrating the CodeMirror into MiqStructuredList component.

---

app/controllers/configuration_controller.rb
app/javascript/components/visual-settings-form/index.jsx
app/presenters/menu/default_menu.rb
app/views/configuration/_ui_3.html.haml
app/views/configuration/_ui_4.html.haml
app/views/configuration/show.html.haml

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8970
Fixes various issues with the settings pages and their permissions.
1) My Settings menu item is now not displayed when Settings > View permissions are off.
2) Default Filters tab is now correctly displayed with no authentication error when missing at least 1 of the other Settings > Modify permissions.
3) Time Profiles tab is now correctly displayed with no authentication error when missing at least 1 of the other Settings > Modify permissions.
4) Default Filters tab is now correctly displayed with no error screen when only Settings > View and Settings > Modify > Default Filters permissions are on.
5) Time Profiles tab is now correctly displayed with no error screen when only Settings > View and Settings > Modify > Time …

Fix settings permissions

---

app/controllers/configuration_controller.rb

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8979
Before an error screen is displayed when a user without any Modify permissions for Settings > My Settings visits the My Settings page. Now we display a blank screen instead. This is by design since without any Modify permissions no tabs will be rendered.
Before:
After:

Fix my settings error screen

---

app/views/configuration/_ui_4.html.haml

Fix incorrect settings tab aria-labelledby id caused by this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8956

Fix incorrect settings tab aria-labelledby id

---

app/javascript/components/reconfigure-vm-form/disk-form-fields.js
app/javascript/components/reconfigure-vm-form/reconfigure-form-fields.js
app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap

When trying to add a new disk in the VM reconfigure form, the default values for the Unit and Bootable fields were incorrectly being set to empty strings. This meant that if the user never directly changed these fields it would only look like they were setting them to `GB` and `false` respectively.
Later when submitting the form, these blank values would be set to defaults by the api, which was causing "GB" to be changed to "MB" in the reconfigure request.
This change fixes this.

Default Disk Unit Fix in VM Reconfigure Form

---

app/views/layouts/_perf_charts.html.haml
app/views/utilization/_utilization_options.html.haml

Fix accessibility violations in the Accessibility Assessment Scanner for the Overview > Utilization page. The last remaining violation is due to the explorer tree and will exist until the explorer screens are removed.
Before:
After:

Fix utilization accessibility issues

---

.github/workflows/yarn_lock.yaml
bin/before_install

This PR creates a GitHub Action that will update the yarn.lock weekly.  I ran this locally with `act`, and everything passed except for the pull request bit, but we know that works because it's been done in other repositories.
@jeffibm Please review.

Add GitHub Action to update yarn.lock weekly

---

app/views/ops/_rbac_group_details.html.haml

The Username field was accidentally removed in https://github.com/ManageIQ/manageiq-ui-classic/pull/8723 and was causing a `Username must be entered to perform LDAP Group Look Up` error. This change brings the field back.
Before:
After:

Return Username Field to "LDAP Group Look Up" Section

---

app/javascript/components/miq-structured-list/miq-structured-list-body/value-tags/miq-structured-list-image.jsx

Before - warning message in browser console
After - No warning messages in browser console

Fix warning for image with no title in structured list

---

app/javascript/components/provider-form/helper.js
app/javascript/components/provider-form/index.jsx
app/javascript/components/provider-form/validate-provider-credentials.jsx

The `Hostname` field in the UI has spaces before and after the actual value.
Before - `hostname` has spaces before and after the value
After - Space trimmed from `hostname`

Fix trailing space for hostname in container provider form

---

app/javascript/components/custom-url-tabs/index.jsx

Follow up to PR: #9004
When first logging in there is no initial tab highlighted for the dashboard page. This pr fixes that.
Before:
After:

Fix dashboard initial tab

---

app/controllers/service_controller.rb

This change updates the `"Invalid button action"` string to match with the rest of the ui for consistency (eg. https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/generic_button_mixin.rb#L99).

Updated Flash Message Text for Consistency

---

app/javascript/components/breadcrumbs/index.jsx
app/javascript/components/breadcrumbs/notifications-toggle.jsx
app/javascript/components/notification-drawer/notification-drawer.jsx
app/javascript/components/toast-list/toast-item.jsx
app/javascript/miq-redux/notification-reducer.js
app/javascript/spec/breadcrumbs/__snapshots__/breadcrumbs.spec.js.snap
app/javascript/spec/notification-drawer/__snapshots__/notification-drawer.spec.js.snap
app/javascript/spec/toast-list/__snapshots__/toast-list.spec.js.snap
app/views/layouts/_breadcrumbs.html.haml

Steps to create notifications - https://github.com/ManageIQ/manageiq-ui-classic/pull/8867#issuecomment-1874846804
**Before**
https://github.com/ManageIQ/manageiq-ui-classic/assets/87487049/54615b0d-bdc1-48ec-abd2-41064a3edb11
2 Toasters
**After**
https://github.com/ManageIQ/manageiq-ui-classic/assets/87487049/0851f5e7-7daa-4484-ab1b-426982544228
1 Notification
1 Notification Toaster

Fix duplicate notifications and toasters

---

app/presenters/tree_builder_network.rb
spec/presenters/tree_builder_network_spec.rb

only display vms that are visible to customers
Before
======
After
=====

filter vms displayed in tree lan

---

app/stylesheet/ddf_override.scss

Path: `Service / Catalogs / Catalogs / (Item) / (Add or Edit Catalog)`
Before
After

Style improvements for dual-list component in catalog form

---

app/views/miq_request/_request.html.haml

Addresses: https://github.com/ManageIQ/manageiq-ui-classic/issues/8772
Related Core Pr: https://github.com/ManageIQ/manageiq/pull/22701
Preview:

Added New Feature That Controls Who Can See Request Logs

---

app/javascript/tagging/components/InnerComponents/CategoryModifier.js
app/javascript/tagging/components/InnerComponents/TagModifier.js
app/javascript/tagging/components/InnerComponents/TagView.js
app/javascript/tagging/components/InnerComponents/ValueModifier.js
app/javascript/tagging/components/Tagging/Tagging.js
app/javascript/tagging/components/TaggingWithButtons/TaggingWithButtons.jsx
app/javascript/tagging/tests/__snapshots__/category.modifier.test.js.snap
app/javascript/tagging/tests/__snapshots__/tag.modifier.test.js.snap
app/javascript/tagging/tests/__snapshots__/tag.view.test.js.snap
app/javascript/tagging/tests/__snapshots__/tagging.test.js.snap
app/javascript/tagging/tests/__snapshots__/value.modifier.test.js.snap
app/stylesheet/application-webpack.scss
app/stylesheet/tags.scss

Before
After
When more items are selected, the container displays a scrollbar

Improve taggings-modifier's style in service catalogs

---

app/views/miq_task/show.html.haml

Introduced by: https://github.com/ManageIQ/manageiq-ui-classic/pull/9000
Fixed a bug where the task details page fails to load for non-workflow tasks.
Before:
After:

Fix task details page

---

app/javascript/components/provider-form/helper.js
app/javascript/components/provider-form/index.jsx
app/javascript/spec/provider-form/helper.spec.js

Follow up to https://github.com/ManageIQ/manageiq-ui-classic/pull/9003 which introduced the method `trimFieldValue`, that's being called on (validation and) form submit.
Before introducing `trimFieldValue` method
```
endpoints: [
{
"role": "default",
"security_protocol": "ssl-without-validation",
"hostname": "ocp-master.cfme2.lab.eng.rdu2.redhat.com",
"port": 8443
}
]
```
An object returned after introducing `trimFieldValue`
```
endpoints: {
"0": {
"role": "default",
"security_protocol": "ssl-without-validation",
"hostname": "ocp-master.cfme2.lab.eng.rdu2.redhat.com",
"port": 8443
}
}
```
When endpoints were passed through the trimFieldValue method, they converted from an array into an object, which is not in line with what the API expects. 
This PR modification involves calling the …

Fixed `no implicit conversion of String into Integer` Error when Adding/Editing Container Provider

---

app/views/vm_common/_evm_relationship.html.haml

`@edit[:vm_id]` was removed in https://github.com/ManageIQ/manageiq-ui-classic/pull/7456 but `recordId` was still being set to to it causing a `bad_request` error in the API.
Before:

Updated RecordId in Edit Management Engine Form

---

app/javascript/components/textual_summary/table_list_view.jsx

Removed the simpleRow, clickableRow, and renderRow methods since they haven't been used since https://github.com/ManageIQ/manageiq-ui-classic/pull/7997

Removed Old Methods from table_list_view

---

app/javascript/components/textual_summary/table_list_view.jsx
app/javascript/spec/textual_summary/tests/__snapshots__/table_list_view.test.js.snap

When the `TableListView` in the Tenants summary page was fixed in https://github.com/ManageIQ/manageiq-ui-classic/pull/8779, it broke some of the tables in the other summary pages (e.g. Ansible Tower Template summary page). This change makes it so that headers and rows are handled differently for different TableListViews.
~Also removed the `simpleRow`, `clickableRow`, and `renderRow` methods since they haven't been used since https://github.com/ManageIQ/manageiq-ui-classic/pull/7997~
Edit: Moved to https://github.com/ManageIQ/manageiq-ui-classic/pull/9040 
Before:
After:

Fixed Empty TableListView for Some Summary Pages

---

app/views/dashboard/show.html.haml

Dashboard tabs were converted to React in this PR: #9004 
But the haml file js code used to handle the old tabs functionality was never removed in that PR.

Remove dashboard haml file change tab js code

---

app/javascript/components/dashboard-widgets/widget-remove-modal/index.jsx
app/javascript/components/dashboard-widgets/widget-wrapper/helper.jsx
app/javascript/components/dashboard-widgets/widget-wrapper/index.jsx
app/javascript/spec/widget-wrapper/__snapshots__/widget-wrapper.spec.js.snap

Converted dashboard widget remove modal to React.
Before:
After:

Convert Dashboard Widget Remove Modal to React

---

cypress/README.md
cypress/e2e/ui/Overview/Chargeback/rates.cy.js
cypress/support/commands/gtl.js

Fixed the gtl cypress helper functions and updated their documentation. Also refactored rates.cy.js to use these new gtl helper functions.

Fixed gtl cypress functions and refactor rates.cy.js

---

app/controllers/application_controller/explorer.rb

Fixes this:
```
#: ../app/controllers/application_controller/explorer.rb
msgid "invalid button action"
msgstr ""
```
To use the existing one used elsewhere:
```
#: ../app/controllers/mixins/generic_button_mixin.rb
#: ../app/controllers/service_controller.rb
msgid "Invalid button action"
msgstr ""
```

Normalize string to proper capitalization

---

app/controllers/mixins/actions/vm_actions/reconfigure.rb

Add Rbac to Switch and vlans
This is visible in the vlan dropdown in the reconfigure vm screen

Filter vlans by switch and then lan

---

app/controllers/report_controller.rb

Remove code from the report controller to handle various tabs that do not exist in the UI.
schedules: The schedules pages do not contain any tabs
saved_reports: The saved reports tab is handled in the file: https://github.com/ManageIQ/manageiq-ui-classic/tree/master/app/views/report/_report_list.html.haml
menuEditor: There is no action that exists called menu_edit, meaning this block of tabs code is not actually doing anything.

Remove report tab technical debt

---

app/views/miq_ae_class/_all_tabs.html.haml

When only 1 tab exists the UI will not actually render the tab headers and only display the tab content. This PR removes all these invisible tabs from the Automation / Embedded Automate / Explorer page and only renders the tab content.
These are how the UI pages would look if the tabs were rendered. I duplicated each tab so that it can be seen in the UI:
root-tabs
aen-tabs
aem-tabs
aei-tabs
After deleting the tabs:
root-tabs
aen-tabs
aem-tabs
aei-tabs

Remove invisible ae tabs

---

cypress/README.md
cypress/support/commands/explorer.js
cypress/support/e2e.js

Fix the Cypress explorer helper functions to open a panel in the explorer view. Also, fixed the README.md file to reflect this change.

Fix cypress explorer helper functions

---

cypress/README.md
cypress/e2e/ui/searchbox.cy.js
cypress/support/assertions/expect_search_box.js
cypress/support/e2e.js

Moved the code for the Cypress search box assertions from the Commands folder to the Assertions folder since these functions are checking if something is true rather than returning a Cypress element / performing an action on the UI. Also, updated the Cypress search tests and documentation to reflect these changes.

Fix cypress search box assertions

---

app/helpers/ems_network_helper/textual_summary.rb

Set EMS network "Region" text to the record's '.provider_region' value. The '.description' doesn't have any region information (for example, the VMWare network manager description is always "VMware Cloud Network"). Also, many providers only define a 'description' class method breaking their Network Manager summary page altogether.

Fix EMS network "Region" text

---

app/controllers/catalog_controller.rb
app/controllers/service_controller.rb

This fix also solves the 'stack level too deep' error notification we see on the services summary page sometimes.
Please see the steps to replicate the issue(s)
https://github.com/ManageIQ/manageiq-ui-classic/assets/87487049/d9704165-188f-4ead-a217-ed4e3505a931
Before
After
https://github.com/ManageIQ/manageiq-ui-classic/assets/87487049/bfece834-0d0c-44d7-9196-67ab2c48e291

Fix for the error messages in Request-info tabs in the Service catalog item summary pages

---

cypress/e2e/ui/menu.cy.js

Fixes the task menu cypress test. Due to changes made in this pr: #9045 the menu test for the task page was broken. This PR fixes this test.

Fix tasks menu cypress test

---

app/javascript/components/carbon-charts/groupChart.js
app/javascript/components/carbon-charts/helpers.js
app/javascript/components/dashboard-widgets/dashboard-charts/index.jsx

Depends on: https://github.com/ManageIQ/manageiq/pull/22872
Fixes a bug where the number of nodes per CPU cores chart won't render despite data being contained in the report.
Before:
After:

Fix dashboard missing chart

---

app/controllers/application_controller/miq_request_methods.rb

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9064
When DHCP is selected on the provision form for the IP Address Mode the IP Address Information fields should be disabled.
Before:
After:

Disable ip address fields when dhcp is selected

---

cypress/README.md
cypress/e2e/ui/Overview/Chargeback/rates.cy.js
cypress/support/assertions/expect_rates_table.js
cypress/support/commands/gtl.js
cypress/support/e2e.js

Refactored the chargeback rates cypress tests with a new helper function to make the chargeback rates test file more readable. Accomplished this by adding a new assertion ```expect_rates_table(headers, rows)``` which will verify the rate table values with the headers and rows parameters. Also, added documentation for this assertion to help users to understand how to use this function.

Refactor chargeback rates cypress tests

---

app/javascript/oldjs/miq_debug.css

**Before**
A portion of the debug toast notification is hidden on the right end
**After**
Note: Maybe we can move this component to a react carbon component (Toast notification)

Fix debug toast wrapper style

---

app/javascript/components/ansible-playbook-edit-catalog-form/helper.js

Fix typo in comments for the functions in ansible-playbook catalog form

Fix typo in comments for ansible-playbook catalog form

---

cypress/README.md
cypress/support/assertions/expect_rates_table.js
cypress/support/assertions/expect_text.js
cypress/support/assertions/expect_title.js
cypress/support/commands/explorer.js
cypress/support/commands/gtl.js
cypress/support/commands/login.js
cypress/support/commands/menu.js

Cleaned up the Cypress Readme file documentation for the commands and assertions. Also cleaned up the comments for the command and assertion files to specify the required parameters for each function.

Fixed cypress readme and comments

---

app/helpers/miq_action_helper.rb

The tag data for the Control Actions summary page is formatted by `miq_summary_action_type` in `app/helpers/miq_action_helper.rb`, but never actually sent to the `MiqStructuredList` component. This change fixes that by adding the missing `data[:rows] = rows` line found in the other helper functions.
Before:
After:

Fixed Empty Applied Tag Section in Control Actions Summary Page

---

app/controllers/application_controller/miq_request_methods.rb

this fixes an issue with:
- https://github.com/ManageIQ/manageiq-ui-classic/pull/9063
Reproducer:
- http://localhost:3000/vm_infra/explorer#/
- choose a vm
- Lifecycle > clone a vm
Not sure if this needs to handle `hostname` and/or `linux_host_name` or the name was wrong.
It calls URL http://localhost:3000/vm_infra/prov_field_changed/new
```
Data undefined method `[]=' for nil:NilClass [vm_infra/prov_field_changed]
manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:42:in `prov_field_changed'
```
It also causes another issue on other pages:
```
all_dialogs[:customize][:fields][:hostname][:read_only] = true
^^^^^^^^^^^^^^
manageiq-ui-classic/app/controllers/application_controller/miq_request_methods.rb:42:in `prov_field_changed'
```

fix hostname error

---

app/helpers/miq_ae_customization_helper.rb
app/helpers/shared_helper/ab_list_helper.rb
app/helpers/shared_helper/ab_show_helper.rb
app/views/shared/buttons/_ab_list.html.haml

`Automation/ Automate/ Customization/ Buttons`
- Converted button group page to react
- Added ab_show_helper and renamed ab_list_helper
**Before**
**After**

Button group summary page react conversion.

---

app/javascript/components/action-form/helper.js

Currently there's an issue when editing an Action with it's action type set to `Invoke a Custom Automation` where all attribute/value pairs are displayed as having the same value despite this not being the case. This change corrects that.
Before:
After:

Fixed Incorrect Values Being Displayed When Editing Action

---

app/views/miq_ae_class/_all_tabs.html.haml
app/views/miq_ae_class/_class_methods.html.haml

Automate / Explorer / Datastore / .... / `Methods` Tab > `Configuration` > Add a new method > Select `Inline`
Before
After

Fix duplicate DOM ID warning in automate modal form

---

app/controllers/miq_action_controller.rb
app/helpers/miq_action_helper.rb
app/javascript/components/action-form/action-form.schema.js
app/javascript/components/miq-structured-list/miq-structured-list-body/value-types/miq-structured-list-object.jsx
app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap
app/stylesheet/ddf_override.scss
app/stylesheet/miq-structured-list.scss
app/views/miq_action/show.html.haml

**Control / Actions**
**Edit action breadcrumb**
Before
After
**Attribute/Value pair in forms**
Before
After
**Attribute/Value pair summary**
Before
After

Fix styles for control action summary and form pages

---

config/routes.rb

Fixed events search bar bug.
Before:
After:

Fixed events search bar

---

app/controllers/miq_request_controller.rb
app/javascript/components/service-request-default/index.jsx
app/javascript/components/service-request-default/service-request-default.schema.js
app/javascript/spec/service-request-default-form/__snapshots__/service-request-default-form.spec.js.snap

Save filters for request page in the session so that they are saved when users navigate back to this page after applying their filters.

Save filters for request page in the session

---

app/javascript/components/miq-data-table/miq-table-cell.jsx
app/javascript/spec/reconfigure-vm-form/__snapshots__/reconfigure-vm-form.spec.js.snap
app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap
app/stylesheet/miq-data-table.scss

The size of the buttons in data tables was a bit bigger by default consuming a lot of vertical space before.
Therefore, changing the button size to `small` if no size is specified.
Before
After

Reduce the button size from default to small in data table rows

---

app/javascript/components/container-projects/helper.jsx
app/javascript/components/miq-data-table/miq-table-cell.jsx
app/services/container_project_dashboard_service.rb
app/stylesheet/cloud-container-projects-dashboard.scss

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9066
Adds a redirect to the Pods table in Container Projects that takes the user to a pod's summary page when that pod is clicked in the table. Also added in a small css change that makes it so the table won't go off of the page and instead becomes scrollable inside of it's card/box.
Before:
After:
https://github.com/ManageIQ/manageiq-ui-classic/assets/64800041/12b351ee-a900-443d-bfc2-db632f7fc01f

Added Redirects to Pods Table in Container Projects

---

app/javascript/components/action-form/action-form.schema.js
app/javascript/components/action-form/helper.js
app/javascript/spec/action-form/__snapshots__/action-form.spec.js.snap

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9113
Fix bug where the Control > Action form with Action Type Tag receives an undefined value when users don't select a tag value. This pr adds a placeholder value and makes the field required forcing the user to select a value.
Before:
After:

Fix action form tag bug

---

app/controllers/ops_controller/ops_rbac.rb
app/javascript/components/taggingWrapper.jsx

Fixed a bug where selecting then deselecting all tags from the Group tag form will break the form.
1) Navigate to the Edit Group form
2) Add Tags using the multi select
3) Remove the tags using the multi select
4) This will then break the form
Before:
After:

Fixed bug with deleting group tags

---

app/javascript/tagging/components/InnerComponents/Tag.js
app/javascript/tagging/sass/_tag.scss
app/javascript/tagging/tests/__snapshots__/tag.test.js.snap
app/views/ops/rbac_group/_customer_tags.html.haml

**Before**
**After** - Reused the tags designs (like we have for service catalogs)
**Before** - The assigned filters tags had a close button which dose nothing
**After** - Removed the close button for the tags

Fix assigned filter tag style

---

app/controllers/workflow_credential_controller.rb

Fixed issue with workflow credentials page side nav menu item. When on this page the blue indicator showing what page you are on was missing as well as the sub menu would not be open when on looking at the side nav menu while on this page.
Before:
After:

Fix workflow credentials side menu

---

app/javascript/tagging/components/InnerComponents/ValueModifier.js
app/javascript/tagging/tests/__snapshots__/tag.modifier.test.js.snap
app/javascript/tagging/tests/value.modifier.test.js

`yarn run jest -t 'Tagging modifier' --testPathPattern app/javascript/tagging/tests/tag.selector.test.js`
**Before**
`Warning: Failed prop type: Invalid prop selectedTagValues of type object supplied to ValueModifier, expected an array in ValueModifier`
**After**
```
PASS  app/javascript/tagging/tests/tag.selector.test.js
Tagging modifier
✓ match snapshot (17ms)
✓ should call methods (2ms)
```

Fix TaggingModifier test case

---

app/views/workflow_credential/show.html.haml

Fix link to the repositories table on the workflow credentials page.
Before:
Clicking on the number for the repositories won't load the new page.
After:
Clicking on the number for the repositories loads the table for the repositories linked to this credential.

Fix workflow credentials page link to repositories

---

app/javascript/spec/notification-message/__snapshots__/notification-message.spec.js.snap
app/javascript/spec/notification-message/notification-message.spec.js

`yarn run jest -t 'NotificationMessage component' --testPathPattern app/javascript/spec/notification-message/notification-message.spec.js`
Before
```
PASS  app/javascript/spec/notification-message/notification-message.spec.js
NotificationMessage component
✓ should render error message (40ms)
✓ should render information message (4ms)
✓ should render success message (2ms)
✓ should render warning message (3ms)
✓ invalid type should not render message (3ms)
✓ blank message should not render message (2ms)
✓ unknown error type message should be rendered with blank type (3ms)
✓ unknown error type message should be rendered with no type (3ms)
Warning: Failed prop type: Invalid prop `message` of type `object` supplied to …
```

Fix NotificationMessage test case

---

app/javascript/spec/settings-compan-categories/__snapshots__/settings-company-categories.spec.js.snap
app/javascript/spec/settings-compan-categories/data.js

`yarn run jest -t 'SettingsCompanyCategories component' --testPathPattern app/javascript/spec/settings-compan-categories/settings-company-categories.spec.js`
Before
```
PASS  app/javascript/spec/settings-compan-categories/settings-company-categories.spec.js
SettingsCompanyCategories component
✓ should render a SettingsCompanyCategories component (116ms)
Warning: Failed prop type: Invalid prop `rows[0].id` of type `number` supplied to `DataTable`, expected `string`.
in DataTable (created by MiqDataTable)
in MiqDataTable (created by SettingsCompanyCategories)
in SettingsCompanyCategories (created by WrapperComponent)
in WrapperComponent
```
After
```
PASS  app/javascript/spec/settings-compan-categories/settings-company-categories.spe …
```

Fix SettingsCompanyCategories test case

---

app/controllers/ansible_credential_controller.rb
app/controllers/ansible_repository_controller.rb
app/controllers/application_controller/tags.rb
app/controllers/workflow_credential_controller.rb
app/controllers/workflow_repository_controller.rb
app/helpers/application_helper/toolbar/ansible_repositories_center.rb
app/helpers/application_helper/toolbar/workflow_repositories_center.rb
spec/controllers/workflow_credential_controller_spec.rb

Fixed the embedded ansible and embedded workflow nested list toolbars.
Affected pages:
Embedded Ansible Credentials / Embedded Workflow Credentials page -> Click a credential from the list -> Click the blue number link beside repositories for the linked repositories. This leads to the nested repository list.
Embedded Ansible Repositories / Embedded Workflows Workflows  page -> Click a repository from the list -> Click the blue number link beside playbooks / workflows for the linked playbooks / workflows. This leads to the nested playbooks / workflows list.
Before (Nested Repositories):
Refresh Page button, Refresh Selected Repositories button, Add Repository Button, Edit Repository Button for the nested repository pages previously did nothing.
After (Nested Repositories):
Refresh Page …

Fix embedded page toolbars

---

app/controllers/configuration_script_controller.rb
app/helpers/configuration_script_helper.rb
app/views/configuration_script/show.html.haml

Fixed a bug where the surveys table is not rendering data on the Automation / Ansible Tower / Templates / Summary Page.
Before:
After:

Fixed missing surveys table

---

app/javascript/components/settings-company-tags/index.jsx
app/stylesheet/application-webpack.scss
app/stylesheet/miq-custom-accordion.scss

**Before**
- The two sections are colliding.
**After**
- Both sections are wrapped into accordion container.
- The stylesheet introduced can be reused in other places in the future (like https://github.com/ManageIQ/manageiq-ui-classic/pull/9059 and others)
- Changed the browser confirmation box

Fix company tags style

---

spec/helpers/application_helper/buttons/auth_key_pair_cloud_create_spec.rb

part of:
- ManageIQ/manageiq#22898
dropping old and unnecessary syntax
```
stub_supports(:supports => true)  ==> stub_supports()
stub_supports(:supports => false) ==> stub_supports_not()
```

drop stub_supports :supports

---

app/javascript/spec/zone-form/__snapshots__/zone-form.spec.js.snap
app/javascript/spec/zone-form/zone-form.spec.js

`yarn run jest -t 'zone Form Component' --testPathPattern app/javascript/spec/zone-form/zone-form.spec.js`
Before
```
Warning: Failed prop type: Invalid prop `recordId` of type `number` supplied to `ZoneForm`, expected `string`.
in ZoneForm
PASS  app/javascript/spec/zone-form/zone-form.spec.js
zone Form Component
✓ should render a new Zone form (9ms)
✓ should render editing a zone form (118ms)
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   2 passed, 2 total
Time:        3.996s
```
After
```
PASS  app/javascript/spec/zone-form/zone-form.spec.js
zone Form Component
✓ should render a new Zone form (16ms)
✓ should render editing a zone form (222ms)
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 …
```

Fix ZoneForm test

---

app/javascript/spec/pxe-iso-datastore-form/__snapshots__/pxe-iso-datastore-form.spec.js.snap
app/javascript/spec/pxe-iso-datastore-form/pxe-iso-datastore-form.spec.js

`yarn run jest -t 'Pxe Iso Datastore Form Component' --testPathPattern app/javascript/spec/pxe-iso-datastore-form/pxe-iso-datastore-form.spec.js`
Before
```
Pxe Iso Datastore Form Component
✓ should render adding a new iso datastore (88ms)
Warning: Failed prop type: Invalid prop `emses[0].id` of type `string` supplied to `PxeIsoDatastoreForm`, expected `number`.
in PxeIsoDatastoreForm
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        3.892s
```
After
```
PASS  app/javascript/spec/pxe-iso-datastore-form/pxe-iso-datastore-form.spec.js
Pxe Iso Datastore Form Component
✓ should render adding a new iso datastore (78ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total …
```

Fix PxeIsoDatastoreForm test

---

app/javascript/spec/cloud-volume-actions-form/__snapshots__/cloud-volume-actions-form.spec.js.snap
app/javascript/spec/cloud-volume-actions-form/cloud-volume-actions-form.spec.js

`yarn run jest -t 'Cloud Volume Restore from backup form component' --testPathPattern app/javascript/spec/cloud-volume-actions-form/cloud-volume-actions-form.spec.js`
**Before**
```
PASS  app/javascript/spec/cloud-volume-actions-form/cloud-volume-actions-form.spec.js
Cloud Volume Backup Create form component
○ skipped should render the cloud volume backup create form
○ skipped when adding a new backup of cloud volume
○ skipped should call miqRedirectBack when the create form is cancelled
create form data object has keys containing
○ skipped matches the expected type and object keys of formData
Cloud Volume Restore from backup form component
✓ should render the cloud volume backup restore form (78ms)
✓ when restoring cloud volume from backup (30ms)
✓ should call miqRedirectBack when the …
```

Fix CloudVolumeActions test

---

app/javascript/components/timeline-options/timeline-table.jsx
app/javascript/spec/timeline-options-form/timeline-table.spec.js

Before
```
PASS  app/javascript/spec/timeline-options-form/timeline-table.spec.js
Show Timeline Page
✓ should render empty page (65ms)
✓ should render a table with data (16ms)
Warning: Failed prop type: The prop `rows[0].id` is marked as required in `DataTable`, but its value is `undefined`.
in DataTable (created by MiqDataTable)
in MiqDataTable (created by TimelineTable)
in div (created by TimelineTable)
in TimelineTable
in Provider (created by WrapperComponent)
in WrapperComponent
console.error node_modules/react/cjs/react.development.js:315
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `DataTable`. See https://fb.me/react-warning-keys for more information.
in TableRow (created by …
```

Fix TimelineTable test case

---

app/javascript/spec/settings-label-tag-mapping/__snapshots__/settings-label-tag-mapping.spec.js.snap
app/javascript/spec/settings-label-tag-mapping/data.js

`yarn run jest -t 'SettingsLabelTagMapping component' --testPathPattern app/javascript/spec/settings-label-tag-mapping/settings-label-tag-mapping.spec.js
`
Before
```
PASS  app/javascript/spec/settings-label-tag-mapping/settings-label-tag-mapping.spec.js
SettingsLabelTagMapping component
✓ should render a SettingsLabelTagMapping component without warning (82ms)
✓ should render a SettingsLabelTagMapping component with warning (35ms)
Warning: Failed prop type: Invalid prop `rows[0].id` of type `number` supplied to `DataTable`, expected `string`.
in DataTable (created by MiqDataTable)
in MiqDataTable (created by SettingsLabelTagMapping)
in SettingsLabelTagMapping (created by WrapperComponent)
in WrapperComponent
```
After
```
PASS …
```

Fix SettingsLabelTabMapping for data-tables test case

---

app/helpers/catalog_helper.rb
app/helpers/request_info_helper.rb
app/helpers/utilization_helper.rb
app/javascript/components/miq-custom-tab/helper.js
app/javascript/components/miq-custom-tab/index.jsx
app/javascript/spec/miq-custom-tab/__snapshots__/miq-custom-tab.spec.js.snap
app/javascript/spec/miq-custom-tab/miq-custom-tab.spec.js

`yarn run jest -t 'MiqCustomTab component' --testPathPattern app/javascript/spec/miq-custom-tab/miq-custom-tab.spec.js`
**Before**
The data used in test case had objects like these,  eg: ` { name: 'requester', text: __('Requester') }`
The `text` was returning an object when we marked the string for translation which resulted in invalid prop types.
```
Warning: Failed prop type: Invalid prop `tabLabels[0].text` of type `object` supplied to `MiqCustomTab`, expected `string`.
in MiqCustomTab
```
**After**
- Refactored the component.
- Removed a few helper methods.
- Fixed the test cases.
- Verified that all `MiqCustomTab` is working as expected.
```
PASS  app/javascript/spec/miq-custom-tab/miq-custom-tab.spec.js
MiqCustomTab component
✓ should render tabs for catalog summary page (129ms)
✓ …
```

Fix MiqCustomTab test cases

---

app/javascript/components/ansible-playbook-workflow/index.jsx

`yarn run jest -t 'AnsiblePlaybookWorkflow component' --testPathPattern app/javascript/spec/ansible-playbook-workflow/ansible-playbook-workflow.spec.js`
Before
`Warning: Failed prop type: The prop payload is marked as required in AnsiblePlaybookWorkflow, but its value is undefined in AnsiblePlaybookWorkflow`
After
```
PASS  app/javascript/spec/ansible-playbook-workflow/ansible-playbook-workflow.spec.js
AnsiblePlaybookWorkflow component
✓ should render the AnsiblePlaybookWorkflow with payload (29ms)
✓ should render the AnsiblePlaybookWorkflow without payload and display a notification (164ms)
```

Fix AnsiblePlaybookWorkflow test case

---

app/helpers/auth_key_pair_cloud_helper/textual_summary.rb
app/helpers/resource_pool_helper/textual_summary.rb
lib/gtl_formatter.rb
product/views/Container.yaml
product/views/ManageIQ_Providers_CloudManager_AuthKeyPair.yaml
product/views/PlacementGroup.yaml
product/views/ResourcePool.yaml
product/views/Switch.yaml
spec/helpers/auth_key_pair_cloud_helper/textual_summary_spec.rb
spec/helpers/resource_pool_helper/textual_summary_spec.rb

alt for https://github.com/ManageIQ/manageiq-ui-classic/pull/8798
requires:
changes:
- fixed gtl so it properly passed ems to function displaying ems icons
- Cloud - Placement Groups summary - already had ems_cloud
- Infrastructure - Networking - `Switch` summary - already had provider
- Containers - Container summary - already had provider
resource pools
==============
After
**Container/ containers**

Add icons and provider name to a few screens

---

spec/controllers/application_controller/ci_processing_spec.rb
spec/controllers/cloud_object_store_object_spec.rb
spec/controllers/storage_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb
spec/helpers/application_helper/buttons/vm_retire_now_spec.rb
spec/helpers/application_helper/buttons/vm_retire_spec.rb
spec/helpers/application_helper/buttons/volume_detach_spec.rb

part of:
- https://github.com/ManageIQ/manageiq/pull/22898
No reason to hardcode classes in the specs here
Also, the new `stub_supports` expects specific provider classes to be called out and will not work with a generic reference

stub_supports uses specific class

---

app/javascript/components/miq-structured-list/index.jsx

`yarn run jest -t 'MiqEventDefinitionStructuredList' --testPathPattern app/javascript/spec/miq-event-definition/miq-event-definition.spec.js`
Before
```
PASS  app/javascript/spec/miq-event-definition/miq-event-definition.spec.js
MiqEventDefinitionStructuredList
✓ should render event definition info structured list (10ms)
✓ should render event definition policy structured list (2ms)
Warning: Failed prop type: Invalid prop `title` of type `object` supplied to `MiqStructuredList`, expected `string`.
in MiqStructuredList
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   2 passed, 2 total
Time:        3.778s
```
After
```
PASS  app/javascript/spec/miq-event-definition/miq-event-definition.spec.js …
```

Fix MiqStructuredList test

---

app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js

`yarn run jest -t 'RemoveCatalogItemModal' --testPathPattern app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js`
Before
```
PASS  app/javascript/spec/remove-catalog-item-modal/remove-catalog-item-modal.spec.js
RemoveCatalogItemModal
✓ should correctly set component state for single catalog item (47ms)
✓ should correctly set component state for multiple catalog items (20ms)
✓ should correctly render modal for single catalog item (8ms)
✓ should correctly render modal for multiple catalog items (4ms)
✓ should correctly render modal for duplicate catalog items (3ms)
✓ correctly initializes buttons (6ms)
✓ removeCatalogItems() works correctly (6ms)
Warning: Failed prop type: Invalid prop `recordId` of type …
```

Fix RemoveCatalogItemModal test

---

app/controllers/orchestration_stack_controller.rb
app/helpers/application_helper/button/orchestration_template_orderable.rb
app/helpers/application_helper/button/orchestration_template_view_in_catalog.rb
app/views/orchestration_stack/_stack_orchestration_template.html.haml
spec/controllers/orchestration_stack_controller_spec.rb

Part of bigger:
- https://github.com/ManageIQ/manageiq/issues/21989
depends upon:
This is the second attempt at #9071 
Now that ServiceTemplates and ServiceOrders both offer `supports :order`, dropping `orderable?` and using the standard `supports`.

convert ServiceTemplate.orderable? to supports?(:order)

---

app/helpers/textual_mixins/textual_os_info.rb

If an OS 'name' attribute is not nil then display it in the UI as 'Description'.
Related to: https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/106
Screenshot:

Display OS 'name' as 'Description'

---

app/javascript/components/miq-structured-list/miq-structured-list-body/value-types/miq-structured-list-sub.jsx

`yarn run jest -t 'MultilinkTable' --testPathPattern app/javascript/spec/textual_summary/tests/multilink_table.test.js
`
Before
```
PASS  app/javascript/spec/textual_summary/tests/multilink_table.test.js
MultilinkTable
✓ renders just fine (126ms)
Warning: Failed prop type: The prop `row.subItems` is marked as required in `MiqStructuredListSub`, but its value is `undefined`.
in MiqStructuredListSub (created by MiqStructuredListBodyValue)
in MiqStructuredListBodyValue (created by MiqStructuredListBody)
in div (created by StructuredListRow)
in StructuredListRow (created by FeatureToggle(StructuredListRow))
in FeatureToggle(StructuredListRow) (created by MiqStructuredListBody)
in div (created by StructuredListBody)
in …
```

Fix MiqStructuredListSub test

---

app/javascript/spec/prov-grid/__snapshots__/prov-grid.spec.js.snap
app/javascript/spec/prov-grid/prov-vm-grid-data.js

`yarn run jest -t 'ProvGrid component' --testPathPattern app/javascript/spec/prov-grid/prov-grid.spec.js`
Before
```
PASS  app/javascript/spec/prov-grid/prov-grid.spec.js
ProvGrid component
✓ should render prov_vm_grid table (182ms)
✓ should render prov_host_grid table (73ms)
✓ should render prov_ds_grid table (45ms)
✓ should render prov_iso_img_grid table (17ms)
✓ should render prov_pxe_img_grid table (26ms)
✓ should render prov_template_grid table (34ms)
Warning: Failed prop type: The prop `initialData.field` is marked as required in `ProvGrid`, but its value is `undefined`.
in ProvGrid
Test Suites: 1 passed, 1 total
Tests:       6 passed, 6 total
Snapshots:   6 passed, 6 total
Time:        4.419s
```
After
```
PASS …
```

Fix ProvGrid test

---

app/javascript/spec/service-dialog-from-form/service-dialog-from-form.spec.js

`yarn run jest -t '<ServiceDialogFromOt />' --testPathPattern app/javascript/spec/service-dialog-from-form/service-dialog-from-form.spec.js`
Before
```
Warning: An update to TextField inside a test was not wrapped in act(...).
act(() => {
});
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
in TextField (created by SingleField)
in FormFieldHideWrapper (created by SingleField)
in FormConditionWrapper (created by SingleField)
in SingleField (created by FormRenderer)
in form (created by Form)
in …
```

Fix ServiceDialogFromOt test

---

app/javascript/components/tree-view/selector.jsx
app/javascript/spec/tree-view/__snapshots__/selector.spec.js.snap
app/javascript/spec/tree-view/selector.spec.js

`yarn run jest -t 'TreeSelector component' --testPathPattern app/javascript/spec/tree-view/selector.spec.js
`
**Before**
```
console.warn node_modules/carbon-components-react/lib/internal/warning.js:30
Warning: The iconDescription prop is no longer needed and can be safely removed. This prop will be removed in the next major release of Carbon.
Warning: An update to TreeViewBase inside a test was not wrapped in act(...).
act(() => {
});
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
in …
```

Fix TreeSelector test

---

app/views/miq_request/_prov_field.html.haml

- Go to `Compute / Infrastructure / Virtual Machines / `
- Select a checkbox from the list
- From the Toolbar, Select` Lifecycle / Publish selected VM to a Template`
- Click on the `Purpose` Tab
Before
After

Fix publish virtual-machines purpose tags style

---

app/helpers/settings_schedule_helper.rb

Fixed a bug where the message value was being displayed for both the message and request field on the schedule summary page.
Before:
After:

Fixed schedule summary page request value

---

app/views/miq_request/_request_dialog_details.html.haml

When the request page is displaying a dialog with a tag field that points to a tag value that was deleted or doesn't exist it runs into a UI error. This pr adds a check to see if the value exists to ensure it doesn't run into the error screen.
Before:
After:

Fix request page tags bug

---

app/controllers/ansible_repository_controller.rb
app/controllers/application_controller/tags.rb
app/controllers/workflow_repository_controller.rb
app/helpers/application_helper/toolbar/ansible_repository_center.rb
app/helpers/application_helper/toolbar/workflow_repository_center.rb
app/views/ansible_repository/_output.html.haml
app/views/workflow_repository/_output.html.haml

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8839
To access the Refresh Output Page navigate to Embedded Ansible / Repositories or Embedded Workflows / Repositories page. If a Repository with an error status exists click on it, if not create a repository with a bad URL to get an error status. Then once on the Repository show screen click on the blue text in the Status row that says Error.
On the Refresh Output screen for the Embedded Ansible and Embedded Workflows Repository Pages there is several issues with the toolbar that are fixed by this pr.
Before:
1) Clicking the refresh button displays the Repository page instead of refreshing the Refresh Output page.
2) Clicking Configuration -> Refresh this Repository does not do anything
3) Clicking Policy -> Edit Tags leads …

Fix output page toolbar bugs

---

app/controllers/ansible_credential_controller.rb
app/controllers/ansible_repository_controller.rb
app/controllers/application_controller.rb
app/controllers/workflow_credential_controller.rb
app/controllers/workflow_repository_controller.rb
app/helpers/application_helper/toolbar/ansible_credential_center.rb
app/helpers/application_helper/toolbar/ansible_credentials_center.rb
app/helpers/application_helper/toolbar/ansible_repositories_center.rb
app/helpers/application_helper/toolbar/ansible_repository_center.rb
app/helpers/application_helper/toolbar/workflow_credential_center.rb
app/helpers/application_helper/toolbar/workflow_credentials_center.rb
app/helpers/application_helper/toolbar/workflow_repositories_center.rb
app/helpers/application_helper/toolbar/workflow_repository_center.rb
app/presenters/menu/default_menu.rb
spec/controllers/ansible_credential_controller_spec.rb
spec/controllers/ansible_repository_controller_spec.rb
spec/controllers/workflow_credential_controller_spec.rb
spec/controllers/workflow_repository_controller_spec.rb

Related to: https://github.com/ManageIQ/manageiq/pull/22971
Merge together:

UI changes to use the renamed product features from core #22971

---

app/javascript/components/request-workflow-status/data.js
app/javascript/components/request-workflow-status/request-workflow-status-item.jsx

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9185
Fixes a bug where the Workflow States Table breaks when the workflow item status is "running".
Before:
After:
When the status is running the rows override each other since they have the same id. So made changes to the ids to prevent this and fix the table.

Fix workflow states table

---

app/stylesheet/miq-data-table.scss
app/views/miq_request/_pre_prov.html.haml

Before
After
1. Removed extra title
2. Removed extra space at the top-right corner of the data-table where scroll bar is extended

Remove multiple title for provisioning pages

---

app/javascript/spec/cloud-volume-form/__snapshots__/attach-detach-cloud-volume-form.spec.js.snap
app/javascript/spec/cloud-volume-form/attach-detach-cloud-volume-form.spec.js

`yarn run jest -t 'Attach / Detach form component' --testPathPattern app/javascript/spec/cloud-volume-form/attach-detach-cloud-volume-form.spec.js`
Before
```
PASS  app/javascript/spec/cloud-volume-form/attach-detach-cloud-volume-form.spec.js
Attach / Detach form component
✓ should render form (9ms)
✓ should render Attach Selected Cloud Volume to an Instance form (84ms)
✓ should render Detach Selected Cloud Volume from an Instance form (14ms)
✓ should render Attach Cloud Volume to the Selected Instance form (19ms)
✓ should render Detach Cloud Volume from the Selected Instance form (12ms)
✓ should submit Attach API call (14ms)
✓ should submit Detach API call (17ms)
Warning: An update to AttachDetachCloudVolumeForm inside …
```

Fix AttachDetachCloudVolumeForm test

---

app/javascript/spec/host-edit-form/helper-data.js
app/javascript/spec/host-edit-form/host-edit-form.spec.js

`yarn run jest -t 'Show Edit Host Form Component' --testPathPattern app/javascript/spec/host-edit-form/host-edit-form.spec.js`
Before
```
PASS  app/javascript/spec/host-edit-form/host-edit-form.spec.js
Show Edit Host Form Component
✓ should render form for *one* host (233ms)
✓ should render form for multiple hosts (28ms)
Warning: An update to AsyncCredentials inside a test was not wrapped in act(...).
act(() => {
});
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
in AsyncCredentials …
```

Fix HostEditForm test

---

app/javascript/spec/cloud-object-store-container-form/__snapshots__/cloud-object-store-container-form.spec.js.snap
app/javascript/spec/cloud-object-store-container-form/cloud-object-store-container-form.spec.js

`yarn run jest -t 'Cloud Object Store Container form component' --testPathPattern app/javascript/spec/cloud-object-store-container-form/cloud-object-store-container-form.spec.js`
Before
```
PASS  app/javascript/spec/cloud-object-store-container-form/cloud-object-store-container-form.spec.js
Cloud Object Store Container form component
✓ should render add cloud object store container form (94ms)
✓ should add Openstack cloud object store container (31ms)
✓ should add Amazon cloud object store container (19ms)
Warning: An update to Select inside a test was not wrapped in act(...).
act(() => {
});
/* assert …
```

Fix CloudObjectStoreContainerForm test

---

app/javascript/oldjs/miq_application.js
app/views/automation_manager/_inventory_group.html.haml
app/views/catalog/explorer.html.haml
app/views/layouts/_performance_async.html.haml
app/views/layouts/_tl_show_async.html.haml
app/views/ops/_diagnostics_utilization_tab.html.haml
app/views/ops/explorer.html.haml
app/views/report/explorer.html.haml
app/views/storage/_storage_list.html.haml
app/views/utilization/index.html.haml
app/views/vm_infra/explorer.html.haml
app/views/vm_or_template/explorer.html.haml
spec/views/availability_zone/show.html.haml_spec.rb
spec/views/host/_show.html.haml_spec.rb
spec/views/vm/_show.html.haml_spec.rb

Removing the usage of eval function inside afterOnLoad function.

[MORPHY] Fix Contrast issue No Use Of Eval

---

app/javascript/components/miq-data-table/miq-table-cell.jsx
app/javascript/components/request-workflow-status/data.js
app/stylesheet/miq-data-table.scss

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9189
Adds the current state to the workflow states table. Also, formats the duration time to be displays as a string in days hours minutes seconds format instead of just seconds.
Before:
After:

Add current state to workflow states table and format duration time

---

app/controllers/configuration_script_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/title.rb
app/javascript/oldjs/services/dialog_editor_http_service.js

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/8987
Also needs this pr: https://github.com/ManageIQ/manageiq/pull/23032 to fix the title
Before:
On the Automation / Automation / Templates screen the list is showing Workflow instances in the list.
On the Automation / Embedded Automate / Customization / Create or Edit Service Dialog screen when using a dynamic drop down with embedded workflows it shows ansible repositories in the list.
After:
Workflow instances no longer show up in the Ansible Tower Templates list.
The embedded workflows list on the service dialog for dynamic drop downs now only shows embedded workflow repositories.

Fix ansible tower and embedded workflows lists

---

app/helpers/catalog_helper.rb
app/javascript/components/ansible-playbook-edit-catalog-form/schema.js

Related PR - https://github.com/ManageIQ/manageiq-schema/pull/734
**Before**
- Catalog item > Provisions
- Catalog item > Retirement
In both provisioning and retirement, 'Vault Credentials' were empty and displayed twice.
**After**
- - Catalog item > Provisions
- Catalog item > Retirement
- The duplicate vault credentials column has been eliminated.
**Reason**
```
`#<ServiceTemplateAnsiblePlaybook id: 171, name: "playbook testing", description: "palybook testing", guid: "cfd1d461-cd05-4284-8ce5-6501f6dae4d0", type: "ServiceTemplateAnsiblePlaybook", service_template_id: nil, options: {:config_info=>
{:provision=>{:repository_id=>"39", :playbook_id=>"739", :credential_id=>"173", :vault_credential_id=>"194", :execution_ttl=>"", :log_output=>"always", :verbosity=>"0", :extra_vars=>{}, …
```

Fix for vault credentials in service-catalog's provisioning and retirement summary

---

app/javascript/components/request-workflow-status/data.js

Follow up to pr: #9191 
When the current state is done its value is not removed from the context.State but also exists in the context.StateHistory. This pr prevents this state from rendering in the table as both a past state and current state and instead will only render it as a past state.
Before:
After:

Remove current workflow state if its done

---

app/controllers/guest_device_controller.rb
config/routes.rb

Fixed guest devices summary page. Fixed the issue with the breadcrumbs missing and the print summary button not working.
Before:
After:

Fix guest devices summary page

---

app/controllers/mixins/generic_show_mixin.rb

In the case of the IBM CIC provider, the count of images on the provider dashboard screen was not matching the number of images seen on the list view. This is because the count on the dashboard screen was accounting for `::Openstack::CloudManager::VolumeSnapshotTemplate` and `::Openstack::CloudManager::VolumeTemplate` whereas the list view was not. (CIC is a subclass of Openstack)
It was decided that the count on the dashboard is correct and that the list view should be showing the volume templates.
Before:
After:
@miq-bot add_reviewer @agrare, @kbrock
@miq-bot add_label bug, radjabov/yes?

Show volume templates in image list view

---

app/helpers/configuration_script_helper.rb
app/helpers/textual_table.rb
app/javascript/components/miq-structured-list/index.jsx
app/javascript/components/textual_summary/simple_table.jsx
app/javascript/components/textual_summary/textual_group.jsx
app/stylesheet/miq-structured-list.scss
app/views/configuration_script/show.html.haml

Makes the survey table on the Automation -> Automation -> Template summary page wider so it is more readable.
Before:
After:

Fix survey table readability

---

app/javascript/components/miq-data-table/miq-table-cell.jsx
app/javascript/components/request-workflow-status/data.js
app/stylesheet/miq-data-table.scss

Before
======
Icons were working for Tasks
Icons were only displaying play for all others
After
=====
Icons are displaying for all Tasks

Update Workflow State icons

---

app/helpers/application_helper/toolbar/miq_templates_center.rb
app/helpers/application_helper/toolbar/template_clouds_center.rb
app/helpers/application_helper/toolbar/template_infras_center.rb
app/helpers/application_helper/toolbar/vm_clouds_center.rb
app/helpers/application_helper/toolbar/vm_infras_center.rb
app/helpers/application_helper/toolbar/vms_center.rb
app/helpers/application_helper/toolbar/x_miq_template_center.rb
app/helpers/application_helper/toolbar/x_template_cloud_center.rb
app/helpers/application_helper/toolbar/x_vm_center.rb
app/helpers/application_helper/toolbar/x_vm_cloud_center.rb

Hide the policy simulation button on IM for the vms, templates, instances and images pages. The policy simulation page is currently broken. As we discuss how to progress with this page whether it is to fix the page, redesign and convert the page to react or delete the page all together we will hide the button that leads to this page.

Hide policy simulation button

---

app/helpers/service_helper.rb
app/views/service/_svcs_show.html.haml

Note:
- This PR is targeting the fix for `master` branch.
- PR for Petrosian branch - https://github.com/ManageIQ/manageiq-ui-classic/pull/9209 since there were a lot of code refactoring done at the `MiqStructuredList` component lately.
**Before**
- HAML list was used for child services summary.
- ![image](https://github.com/ManageIQ/manageiq-ui-classic/assets/4242692/73bbb1e1-678c-43d5-b710-04be129b168a)
- Click event on the child services will return an error.
```
[----] I, [2024-06-14T10:42:00.965059 #38561:60784]  INFO -- : Started POST "/service/tree_select/?id=s-132" for ::1 at 2024-06-14 10:42:00 +0530
[----] F, [2024-06-14T10:42:01.109760 #38561:60784] FATAL -- :   
ActionController::RoutingError (No route matches [POST] "/service/tree_select"):
```
**After**
- Converted the child …

Fix child services link

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb

This ensures we prepend our NumberHelper into the existing helper.  Previously, there was a loading order problem where the original rails NumberHelper would be used. 
For rails 7, this load order was causing these types of errors where the original number helper was being used:
```
1) MiqReport::Formatting #format_mhz_to_human_size adds a prefix and suffix to NumberHelper#mhz_to_human_size
Failure/Error: val = ApplicationController.helpers.mhz_to_human_size(val, options[:precision])
NoMethodError:
undefined method `mhz_to_human_size' for #<ActionView::Base:0x000000012e3573c8 @_config=#< {}>, @lookup_context=#<ActionView::LookupContext:0x000000012e357d78 @details_key=nil, @digest_cache=nil, @cache=true, @prefixes=[], @details={:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, …
```

Prepend ActionView::Helpers::NumberHelper with our NumberHelper

---

app/views/miq_request/_request_dialog_details.html.haml

As a follow up to this pr: https://github.com/ManageIQ/manageiq-automation_engine/pull/545 we need to fix the Services > Request summary page since the values are now coming in as an array instead of a string. This pr fixes the request page to show the values properly for single and multi select drop downs and tag control fields.
A catalog was ordered with these values:
Before:
After:

Fix request form automation fields

---

app/controllers/ops_controller/settings/common.rb
spec/views/availability_zone/show.html.haml_spec.rb
spec/views/catalog/_form.html.haml_spec.rb
spec/views/catalog/_sandt_tree_show.html.haml_spec.rb
spec/views/dashboard/login.html.haml_spec.rb
spec/views/ems_cluster/show.html.haml_spec.rb
spec/views/host/_show.html.haml_spec.rb
spec/views/layouts/_center_div_no_listnav.html.haml_spec.rb
spec/views/layouts/_item.html.haml_spec.rb
spec/views/layouts/_searchbar.html.haml_spec.rb
spec/views/layouts/_user_input_filter.html.haml_spec.rb
spec/views/layouts/list_grid.html.haml_spec.rb
spec/views/layouts/perf_charts_js_spec.rb
spec/views/miq_ae_class/_class_fields.html.haml_spec.rb
spec/views/miq_ae_class/_fields_seq_form.html.haml_spec.rb
spec/views/miq_ae_class/_instance_fields.html.haml_spec.rb
spec/views/miq_ae_class/_method_inputs.html.haml_spec.rb
spec/views/miq_ae_class/show.html.haml_spec.rb
spec/views/miq_alert/_show.html.haml_spec.rb
spec/views/ops/_label_tag_mapping_form.html.haml_spec.rb
spec/views/ops/_rbac_tenant_details.html.haml_spec.rb
spec/views/ops/_rbac_user_details.html.haml_spec.rb
spec/views/ops/_settings_cu_collection_tab.html.haml_spec.rb
spec/views/report/_report_list.html.haml_spec.rb
spec/views/report/_widget_form_menu.html.haml_spec.rb
spec/views/shared/buttons/_ab_form.html.haml_spec.rb
spec/views/vm/_show.html.haml_spec.rb

This PR squashes ~40 test failures on rails 7.   There are still 2 more failures but I'll tackle them in a follow up PR to keep this PR easier to review.  This should be backward compatible with rails 6.1
The primary change is:
Resolve ActionView::MissingTemplate errors by specifying template
Rails 7 now raises this error if you don't specify the template correctly.
Specifying templates with "." in the name was deprecated here:
https://www.github.com/rails/rails/pull/39164
The interface they want is without periods and for you to specify the formats
if it's non-standard.  Also, render with no :template, :partial, etc. is also
gone in rails 7.
Somewhat related issued with helpful information can be found here:
https://www.github.com/mileszs/wicked_pdf/issues/1005

Rails 7 compatible changes (part 1)

---

app/controllers/container_group_controller.rb
app/controllers/container_node_controller.rb
app/controllers/container_replicator_controller.rb
app/controllers/container_route_controller.rb
app/controllers/container_service_controller.rb
app/controllers/container_template_controller.rb
app/helpers/container_summary_helper.rb

Add annotations on container summary pages that contain labels, remove custom attributes tab from container nodes summary page
Relevant PRs:
Providers-Kubernetes: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/530
Providers-Openshift: https://github.com/ManageIQ/manageiq-providers-openshift/pull/262
Core ManageIQ: https://github.com/ManageIQ/manageiq/pull/23074
Old:
New:
Cross-Repo Tests:
https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/879 
All passing except for known failing test cases in core ManageIQ

Add annotations on container summary pages that contain labels

---

app/controllers/miq_ae_customization_controller.rb
app/helpers/miq_ae_customization_helper.rb
app/views/miq_ae_customization/_old_dialogs_details.html.haml
cypress/e2e/ui/Automation/Embedded-Automate/customization.cy.js

Convert provision dialog summary form to React
Old:
New:

Convert provision dialog summary form to React

---

package.json
yarn.lock

Update moment-timezone to ~0.5.37.
No code changes required. Similar to this pr on the master branch: https://github.com/ManageIQ/manageiq-ui-classic/pull/8442

[Morphy] Update moment-timezone

---

cypress/support/index.js

Fixed the assertion import on cypress tests
Before:
After:

[Morphy] Fix cypress test assertion imports

---

package.json
yarn.lock

Pin moment-timezone to ~0.5.40 similar to this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/8592 on the master branch.
Follow up to this pr: #9232 since this pr didn't completely get rid of the older moment-timezone version.

[Morphy] Pin moment timezone

---

.yarnrc.yml

@GilbertCherrie Please review.  This will get master back to green for now.  Since this is the same as the other ignores, it just falls in the same bucket until we can fix it.

Ignore the latest bootstrap vulnerability until we can upgrade

---

app/javascript/react/textual_summary_wrapper.jsx

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9218
There is an issue where the textual summary page is being duplicated. This is due to the code:
```
if (props.options) {
document.addEventListener('DOMContentLoaded', () => {
ReactDOM.render(component, document.body.appendChild(document.createElement('div')));
});
}
```
This code is used to generate the print summary screen.
The issue is that currently `if (props.options)` is `true` but props.options is an empty object. So instead of just checking if the object exists we can also check if it contains any data by looking at the length of the `keys` array. This prevents the textual summary from being duplicated.
Before:
In the page elements we see an extra div being rendered at the bottom between the error-modal component and …

Fix textual summary duplication bug

---

.yarnrc.yml

A number of security issues had their npm audit id updated, though I am not sure why.

Update pending yarn npm audit list

---

.yarnrc.yml

Alternative to #9240
Ideally we could use npmAuditIgnoreAdvisories to be aware when new advisories come in, but it turns out the IDs are not stable in that as changes are made to a GHSA, it creates a new ID (See https://github.com/yarnpkg/berry/issues/6438). This churn is difficult to work with. Instead this commit switches to package based, which, while not as granular, is more stable.
@jrafanie Please review.  Note that I have a rake task to generate this list (and the old list), but I want to put that in a separate PR.
cc @GilbertCherrie

Use npmAuditExcludePackages instead of npmAuditIgnoreAdvisories

---

spec/controllers/vm_cloud_controller_spec.rb
spec/controllers/vm_infra_controller_spec.rb

This is ready for review but depends on rails 7.
Note, this will only pass on rails 7 and is included in the core cross repo:
Depends:

Rails7 test fixes

---

app/controllers/ops_controller/settings/common.rb

Drops the rails 6.1 compatibility from:
https://github.com/ManageIQ/manageiq-ui-classic/pull/9215

Use Rails 7 way to set yaml permitted classes

---

lib/manageiq/ui/classic/engine.rb

We were getting the following error in production mode:
```
RAILS_ENV=production bundle exec rake evm:compile_assets
...
rake aborted!
Uglifier::Error: Unexpected token: punc ((). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
```
Note, this change makes all rails processes in production and test load uglifier even if they'll never use it.  This is because we're eager loading it, instead of delay loading it via a symbol.
It sounds like we can possibly resolve this by figuring out which es6 syntax it doesn't like
See https://www.github.com/lautis/uglifier/issues/127

Use uglifier harmony mode to handle es6 syntax with rails 7

---

app/javascript/components/provider-dashboard-charts/charts_config.js

Fixed provider charts tooltip.
Before:
After:

Fix provider charts tooltip

---

lib/manageiq/ui/classic/engine.rb
lib/manageiq/ui/classic/js_compressor.rb

* Allows es6 code that regular Uglifier doesn't support
* Avoids requiring Uglifier in all rails processes at application startup.
* Uglifier requires a js runtime such as node
* JS runtime can continue to be only available in development and for production pre-compilation
This is a better solution than https://github.com/ManageIQ/manageiq-ui-classic/pull/9244
Note, the original es6 workaround suggested by Uglifier is to use this harmony support: https://www.github.com/lautis/uglifier/issues/127
```
joerafaniello@Joes-MBP manageiq % RAILS_ENV=production bin/rails c
UGLIFYING!!  # <--- loading uglifier and node :-(
** WARN: Rails is serving static assets in production mode
Loading production environment (Rails 7.0.8.4)
irb(main):001:0> exit
```
```
joerafaniello@Joes-MBP manageiq % …
```

Wrap the uglifier compressor with harmony support

---

app/helpers/application_helper/button/vm_miq_request_new.rb
spec/helpers/application_helper/buttons/vm_miq_request_new_spec.rb

Found by https://github.com/orgs/ManageIQ/discussions/23147#discussioncomment-10351757
This looks like it was just copied&pasted from [app/helpers/application_helper/button/instance_miq_request_new.rb](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/helpers/application_helper/button/instance_miq_request_new.rb) without updating the EmsCloud => EmsInfra

Fix the VM Infra button checking EmsCloud providers

---

app/helpers/resource_pool_cloud_helper.rb
app/helpers/resource_pool_cloud_helper/textual_summary.rb
app/helpers/resource_pool_infra_helper.rb
spec/config/routes.pending.yml

Introduced by https://github.com/ManageIQ/manageiq-ui-classic/pull/8929
#9060 dropped include_conern

Drop include_concern in ResourcePool Helpers

---

.github/workflows/locale_po_to_json.yaml

This PR adds an adhoc github action to generate the UI json translation files.  
The workflow is:
* generate the English po/pot updates - locale:update_all  (automated in core GHA already twice per month 1st and 15th of the month)
* provide pot file to translators
* get translation po files for the supported languages... commit all po/pots
* Generate the UI json files based on the po files
This PR handles the last step.  In the future, we can detect when new po files get merged and automatically run this task.

Add locale:po_to_json github action

---

.github/workflows/locale_po_to_json.yaml

We're creating a PR using the fork of the bot, not the main repository.
Fixes an issue in the one area in PR #9263 that I couldn't test: creating the PR as the bot.  🤣

Fix a typo in the fork name

---

spec/controllers/mixins/generic_show_mixin_spec.rb

This was causing brakeman to fail, but it's not used.

Remove unused controller stub from spec

---

manageiq-ui-classic.gemspec

This should be safe to use as is since the core application sets the rails version.
This will allow us to test with other versions on master.

Use core minimum but allow 7.0/7.1/7.2 since core sets upper limit

---

app/controllers/miq_ae_tools_controller.rb

Newlines can cause trouble with translations as well as presentation in the UI. This particular string doesn't actually need the newlines, so this commit changes it to just not have them.
Alternative to ManageIQ/manageiq#23213
@jrafanie  please review.

Remove newlines from result message

---

app/stylesheet/quadicon.scss

I don't know if we need the fractions, but this looked like the fix here.
Not sure exactly where to test this.
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($font-size * 2, 3) or calc($font-size * 2 / 3)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
135 │         font-size: $font-size * 2/3;
│                    ^^^^^^^^^^^^^^^^
╵
app/stylesheet/quadicon.scss 135:20  @import
stdin 25:9                           root stylesheet
```

fix scss warning on division

---

app/javascript/oldjs/components/index.js
app/javascript/oldjs/components/sanitize.js

Remove unused miqsanitize angular code. This is code that was added in this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/275 for the service catalog page but is no longer being used there.

Remove unused miqsanitize angular code

---

app/helpers/application_helper/toolbar/service_center.rb
app/views/service/_svcs_show.html.haml

This PR is dependant on https://github.com/ManageIQ/manageiq-providers-embedded_terraform/pull/78
With this change, separate tab added to show standard output from the terraform cli run job.
* Before the changes,  there was no standard output shown.
---
* After the changes,  there are two tabs, one for details, other for standard output from the terraform cli run job.
* Output tab with terraform CLI standard output
---
Additional changes
* Also added is a 'Refresh' button to refresh the page data

Show Terraform Template stack stdout

---

app/javascript/components/terraform-template-catalog-form/terraform-template-catalog-form.schema.js

Depends on:
This PR, make changes for Terraform Template, in New Service Catalog Item page.
* Before this PR changes,  in Provision tab, the user could not create new dialog for terraform template, they could only select existing service dialogs.
* After the changes in PR, in Provision tab, the user can now either choose to use existing service dialog or create new dialog for the terraform template.
* If the user chooses to create new dialog, providing new dialog name, then saves the Service Catalog item, new dialog is created in background.
* The newly dialog created, will have section added for `Terraform Template Variables`,  this section will have textboxes for each 'input' variables from terraform template.  The newly created dialog can be edited by the user according to needs.
In …

Add option to create new dialog for terraform template in service catalog item

---

lib/tasks/manageiq/ui_tasks.rake

In ruby 3.1.*, it was not finding BUNDLER::CLI

Add bundler path

---

app/controllers/application_controller/wait_for_task.rb

kerberos auth requires a wait_for_task under the covers. When we create this task, we store a backup copy of the incoming request params within the session object, so we can restore it later after the task we are waiting for has completed, and that session object is `Marshal.dump`ed into memcached. In Rails 7, Rails changed the ActionController::Parameters object to include some more objects as context, such as the request, and the request internally has an IO object that cannot be dumped. Since we don't actually need the context and instead only need the parameters, we can use `to_unsafe_h` instead of `deep_dup`, to get a copy of those parameters in HashWithIndifferentAccess form. Later when [wait_for_task reconstructs the parameters](https://github.com/ManageIQ/manageiq-ui-classic/blob/c …

Fix issue when using kerberos auth with Rails 7

---

config/initializers/assets.rb
lib/manageiq/ui/classic/engine.rb
manageiq-ui-classic.gemspec

Drop sass rails

---

app/views/miq_ae_class/_class_fields.html.haml

Adds autocomplete attribute to prevent password datatype default values from using password manager values

Fix Chrome autofilling password when editing a schema

---

app/javascript/components/gtl-view.jsx
app/javascript/react/textual_summary_wrapper.jsx
app/stylesheet/legacy/patternfly_overrides.scss

Fixed the explorer title width to use 100% of the width of the row component.
Before:
After:

Fix explorer title width

---

app/controllers/generic_object_controller.rb
app/controllers/mixins/custom_buttons.rb
app/controllers/service_controller.rb
app/helpers/application_helper/toolbar/generic_object_center.rb
app/helpers/application_helper/toolbar/mixins/custom_button_toolbar_mixin.rb
app/helpers/service_helper/textual_summary.rb
app/views/service/show.html.haml

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9255
Fixed generic object embedded table. Also, fixed the toolbar for the embedded generic object table page.
This pr also fixes an issue where custom buttons do not appear on the generic object show page.
Before:
After:

Fix generic object embedded table

---

app/javascript/components/ansible-playbook-edit-catalog-form/helper.js
app/javascript/components/terraform-template-catalog-form/helper.js

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9300
This pr fixes a bug where the key value list component loses focus after each key press. This caused the user to have to reselect the variable field after every key they entered if they wanted to make a variable with a name longer than 1 character. 
Now you can continue to type in the variable field without the field losing focus.

Fix Key Value List Component Typing Bug

---

app/javascript/components/miq-structured-list/miq-structured-list-body/value-tags/miq-structured-list-text.jsx
app/javascript/spec/textual_summary/tests/__snapshots__/tag_group.test.js.snap
app/javascript/spec/textual_summary/tests/tag_group.test.js
app/stylesheet/miq-structured-list.scss

Making tags more readable

---

app/controllers/miq_ae_class_controller.rb
app/javascript/components/miq-ae-class/class-form.schema.js
app/javascript/components/miq-ae-class/index.jsx
app/javascript/packs/component-definitions-common.js
app/javascript/spec/miq-ae-class-form/__snapshots__/miq-ae-class-form.spec.js.snap
app/javascript/spec/miq-ae-class-form/miq-ae-class-form.spec.js
app/views/miq_ae_class/_class_form.html.haml
config/routes.rb
cypress.config.js
cypress/e2e/ui/Automation/Embedded-Automate/Explorer/class.cy.js
spec/controllers/miq_ae_class_controller_spec.rb

Automation / Automate / Explorer / Datastore
Transforms haml forms to react for Add and Edit feature of Automate Class.
Before
After

Transforms haml forms to react for Add and Edit feature of Automate Class

---

app/javascript/components/gtl-view.jsx

Fixed issues with table pagination settings.
1. The 5 items per page option was missing on the table even though the settings page contains this as an option.
2. When selecting an option on the settings page for items per page it wasn't actually being applied to the tables in the UI.
Before:
The default items per page on the settings page was not actually being applied on the tables in the UI.
As seen here the table defaults to 20 items per page even though in the settings it was set to 10.
Also, 5 items per page is not an option here even though it is on the settings page.
After:

Fix table pagination setting

---

.yarnrc.yml

This package is being brought in by patternfly, and we are already at the latest version. We need to upgrade patternfly or replace it completely to be off of this package.
This is related to CVE-2024-6484, however I'm not sure why this changed all of a sudden.
@jrafanie Please review. cc @GilbertCherrie

Exclude bootstrap-sass from yarn audit

---

package.json
yarn.lock

Update package path-to-regexp to ~1.9.0

[Morphy] Update path to regexp

---

app/helpers/security_group_helper/textual_summary.rb
spec/controllers/ems_cloud_controller_spec.rb
spec/controllers/ems_infra_controller_spec.rb

Rails 7.0 was reporting this warning:
DEPRECATION WARNING: Range#to_s(:dash) is deprecated. Please use Range#to_fs(:dash) instead. (called from port_range_helper at /home/runner/work/manageiq-ui-classic/manageiq-ui-classic/app/helpers/security_group_helper/textual_summary.rb:105)
In rails 7.1, the response.body in the redirect is an empty string.

Rails 7.1 / Rails 7.0 compatible changes

---

package.json
yarn.lock

Update tar package to ~6.2.1. Tar is being pulled in from the patternfly-react package. Since we can't udpate this package and removing it involves too many code changes for Morphy we have to use resolutions to update the tar package.

[Morphy] Update tar

---

.yarnrc.yml

No longer needed after the merge of #9322

Remove jquery from the audit exclusion list

---

package.json
yarn.lock

Update semver-regex to ~4.0.3 using resolutions. Needed to use resolutions since this is being pulled in from patternfly-react which we can not update or remove on the Morphy branch.

[Morphy] Update semver regex

---

package.json
yarn.lock

Update marked package to ~4.0.10 using resolutions. The marked package is being pulled in from patternfly-react which we can't update or delete on the Morphy branch without major code changes, so instead we need to update the marked package directly using the resolutions.

[Morphy] Update marked to ~4.0.10

---

package.json
yarn.lock

Update decode-uri-component to ~0.2.1 using resolutions. Need to use resolutions to update this because this is being pulled in from patternfly-react which we can not update or remove on the Morphy branch.

[Morphy] Update decode-uri-component package

---

yarn.lock

Update braces package to 3.0.3 by updating the yarn.lock.

[Morphy] Update braces to 3.0.3

---

package.json
yarn.lock

This handles CVE-2025-26791
@GilbertCherrie Please review.  I did not manually test with this as I'm not sure where we are using dompurify (in fact I thought we dropped it, but maybe not)

Update dompurify to the latest

---

package.json
yarn.lock

Update cross-spawn to ~7.0.5 using resolutions. Older versions of cross-spawn are being pulled in from patternfly-react which we can not update or remove on Morphy so we need to update cross-spawn using the resolutions.

[Morphy] Update cross spawn

---

app/controllers/application_controller/explorer.rb
spec/controllers/vm_cloud_controller_spec.rb

Issue- An internal server error occurs during refresh('Refresh Relationships and Power States') of a provider instance. The error occurs only in cases when refresh is done 'after' a reconfigure ('Reconfigure selected instance') operation on the provider instance.
Observation- This was happening because it was rendering the _resize partial due to a pre-existing value in the @sb[:action].
Steps to reproduce the behavior:
1. Choose instance from AWS provider
2. Configuration -> Reconfigure selected Instance
3. Recheck on the same item from step 1
4. Configure -> Refresh Relationships and Power States
Before the fix - 
After the fix - 

Fixes 500 error occurred during refreshing of a provider instance

---

app/controllers/application_controller/wait_for_task.rb
spec/controllers/application_controller/buttons_spec.rb

The `wait_for_task` mechanism relies upon the session.
Every http request changes the session. So when multiple requests come in, updates to the session can overwrite the changes done by another request.
Example:
Host's display of Cap&U was breaking because hits to notifications were overwriting the session variables. Note: VM's display of Cap&U was working fine because it did not have a hit to notifications (and therefore didn't have this race condition).
Move `wait_for_task` parameters from the session to the url.
- `initiate_wait_for_task` sets `session[:async][:params]` with `action` and `params{}`
- `browser_refresh_task` puts shim into web page
- browser polls `wait_for_task` waiting for task to complete
- when task is complete, `session[:async][:params]` is used to complete action …

Wait for task no longer 

---

app/javascript/components/provider-dashboard-charts/helpers.js

Fixes an issue with the provider dashboard charts where certain time zones for example "BST" were causing the chart components to throw errors. This seems like a bug with the Carbon charts however we can prevent this by simply omitting the `z` in our format function call. Including the `z` doesn't matter in this case because it only adds the time zone string to the formatted time value, however this formatted time string isn't displayed anywhere. This formatted string is passed into the Carbon charts for the chart data and being displayed as a data point, so we don't actually need to include the timezone in our formatted string. This prevents us from running into the error of the chart breaking. 
Before:
After:
Also, as a side effect fix by removing the `z` it actually correctly converts …

Fix provider dashboard charts converted time bug

---

.github/workflows/cypress.yaml

- The app now runs on Ruby 3.1 miniumum
- update-artifacts v3 no longer exists
@GilbertCherrie Please review

Update cypress env

---

yarn.lock

@elsamaryv Please review.
Should remove warning
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```

Update caniuse-lite to remove outdated warning

---

package.json
yarn.lock

Pin the cheerio package version to 1.0.0-rc.12. This is because when the yarn.lock file is being updated it pulls in the latest version of cheerio which is 1.0.0, which causes our github actions specs to fail. After this pr is merged it should allow us to properly update the yarn.lock with the latest dependencies using this pr: #9276

Pin cheerio package version

---

app/helpers/generic_object_helper/textual_summary.rb
app/javascript/components/textual_summary/empty_group.jsx
spec/helpers/generic_object_helper/textual_summary_spec.rb

Convert TextualEmpty table to React.
Before:
After:

Convert textualempty table to react

---

app/views/ops/_settings_authentication_tab.html.haml

Fixed an issue with the Settings / Authentication Form where it isn't saving the correct values for the Provider type option or it won't let you save the form based on the provider type selected.
Before:
After:

Fix settings authentication form provider type ids

---

app/javascript/oldjs/services/miq_service.js
spec/javascripts/services/miq_service_spec.js

Note, these are all callers of miqRESTAjaxButton which takes a dataType.  This function is related to [an issue with an upgrade of jquery from 2.2.4 to 3.7.1](https://github.com/ManageIQ/manageiq-ui-classic/pull/9410)
* validateWithAjax is unused as of 9268a856aaf606fff4399dba688415471910616d
* validateWithREST is unused as of 8efe154e0912337cefcc4b576f2124e77674c2b7
* validateClicked is unused as of 7fe831cb5f48a7039cf4d081856210d9949432b7
* restAjaxButton is unused as of 753534f7d11c6e11b4a4ec88ddec5f994dc192f4
* detectWithRest appears to not be used as of 775acdd8b4c047620c22cb04f7eeed8ab9401739

Remove dead code

---

app/javascript/oldjs/jquery_overrides.js
app/javascript/oldjs/miq_application.js

The jquery upgrade from 2.2.4 to 3.7.1 from 16cf008fda3145184b4709f5d39e8756a241b186 was causing the login page to spin after a 401 unauthorized with sso enabled for kerberos. This happened because our script converter wasn't being run with the newer jquery, therefore we weren't processing the response payload from the 401.  This response payload should ajax update the page with the error, stop the spinner, and show the login fields.
There were some changes in the 2.2.4 to 3.7.1 jquery upgrade  that seems to conflict with our converter, perhaps our converter was being overridden, or maybe we need to override it differently.  Either way, we can avoid this by defining our own converter.
This was recreated locally via:
```ruby
render :inline => …
```

Define a custom script dataType converter, don't override the base one

---

cypress/e2e/ui/Overview/reports.cy.js

Added tests for adding, editing and deleting reports and schedules. @Fryguy This pr along with https://github.com/ManageIQ/manageiq-ui-classic/pull/8892 both require simulate_queue_worker to be enabled in the github actions cypress environment.

Add cypress tests for reports and schedules

---

app/helpers/js_helper.rb
app/javascript/oldjs/.eslintrc.json
app/javascript/oldjs/miq_application.js
app/javascript/oldjs/services/miq_service.js
spec/helpers/js_helper_spec.rb
spec/javascripts/services/miq_service_spec.js

Follow up to #9411...
I went through each function/method, checked if it was called, and verified the last usage was a commit (usually a conversion) that mistakenly didn't remove the dead code, and removed it.
* getProviderTenants is unused as of 1f458eaf4234e1ef7feccff8571a4ba230ba347b
* getCloudNetworksByEms is unused as of e4db01a7fbcf737b01ff84b118bf17368f0addd6
* serializeModel is unused as of 3c0aab7b0fd87a56cf8aee6d57e6e582ba7ba856
* disabledClick is unused as of 6d09bfb6844e75550c2acc3d61ebf2f75b96c4a4
* jqueryRequest is unused as of 807cab9b655067cb735c9c1722432f912c9b244d
* miqAsyncAjaxButton is unused as of 07c32fe7627a1e5df5512ec7ad550c0b84f9a671
* javascript_update_element is unused as of 68c7a5a154ee09523f2eccd4022f07d515d01070
* jquery_pulsate_element is unused as of …

Dead code round 2

---

app/javascript/oldjs/jquery_overrides.js

Define two script converters:
1) script - This is the original converter to evaluate scripts for successful responses.
2) miq_script - Define a duplicate but differently named script converter whose purpose is to evaluate scripts for unsuccessful ajax responses.  jQuery 3.5.0 changed the behavior of the script converter, replacing it with a no-op converter for scripts found in unsuccessful ajax responses. Successful responses would continue to be evaluated as previously. See: https://github.com/jquery/jquery/commit/da3dd85b63c4e3a6a768132c2a83a1a6eec24840
Due to this change starting in 3.5.0, we define a new type of script we can set as the dataType so it's evaluated in the event of unsuccessful responses such as the SSO 401 unauthorized issue we attempted to fix in #9410 and subsequently …

Explain why we have two script text converters

---

app/views/miq_alert/_alert_builtin_exp.html.haml
spec/controllers/miq_alert_controller_spec.rb

Fixes #9386 
When attempting to create an Alert via Control -> Alerts -> Add a new alert, and choosing Event Threshold as the "What to Evaluate", an error message appears as: `Event to Check is required` even when there is a value for the field.

Fixes alert with event threshold

---

app/controllers/configuration_job_controller.rb
app/controllers/orchestration_stack_controller.rb
app/helpers/application_helper.rb
app/views/layouts/_tag_edit_items.html.haml
product/views/ManageIQ_Providers_ExternalAutomationManager_OrchestrationStack.yaml
spec/controllers/configuration_job_controller_spec.rb

The `configuration_job_controller` should show all `ExternalAutomationManager` `OrchestrationStacks` not just `AnsibleTower` ones.

Fix `ConfigurationJobController` using AnsibleTower

---

app/controllers/ops_controller/settings/tags.rb

Fix the Settings Tag Category edit page save button. Before clicking save will not return back to the list screen and throws error `#settings_my_company_categories does not exist in the DOM` in the console.
Before:
After:

Fix Settings Tag Category Edit Page

---

app/controllers/application_controller.rb
app/controllers/application_controller/miq_request_methods.rb
app/controllers/ops_controller/ops_rbac.rb
app/controllers/ops_controller/settings/analysis_profiles.rb
app/controllers/ops_controller/settings/tags.rb
app/controllers/vm_common.rb
app/helpers/js_helper.rb
app/views/configuration/_ui_3.html.haml
app/views/dashboard/oidc_login.html.haml
app/views/dashboard/saml_login.html.haml
app/views/layouts/_protect.html.haml
app/views/layouts/_textual_groups_generic.html.haml
app/views/layouts/listnav/_compare_sections.html.haml
app/views/miq_policy_rsop/_rsop_results.html.haml
app/views/ops/_settings_cu_collection_tab.html.haml
app/views/ops/_smartproxy_affinity.html.haml
app/views/shared/_file_chooser.html.haml
app/views/shared/dialogs/_dialog_user.html.haml
app/views/shared/views/_compliance_history.html.haml
app/views/vm_common/_policies.html.haml

This method was added as a wrapper around the Rails `j` method to handle non-string types. However, this feature was added in the Rails `j` method as of Rails 6.0.0-rc1 in rails/rails@dd0cfb03, and so is redundant.
This commit switches everything to the `j` method to be Rails idiomatic.
@jrafanie @GilbertCherrie Please review.

Drop j_str helper method

---

cypress/e2e/ui/Automation/Embedded-Automate/Explorer/class.cy.js
cypress/e2e/ui/Automation/Embedded-Automate/customization.cy.js
cypress/e2e/ui/Overview/Chargeback/rates.cy.js
cypress/e2e/ui/Overview/reports.cy.js
cypress/e2e/ui/menu.cy.js
cypress/e2e/ui/searchbox.cy.js

* change some waits to using `get` with a timeout and asserting some things are visible
* change some places where notifications / errors are now covering new items in the pages so must use force: true for now
* control alerts searchbox test never passed for me, swapped the logic as I always see a searchbox there
Before:
```
Spec                                              Tests  Passing  Failing  Pending  Skipped
✖  7 of 11 failed (64%)                     06:43      149      137       12        -        -
```
After:
```
✖  5 of 11 failed (45%)                     05:40      149      140        9        -        -
```
Note, I'm using cache_class: true in my configuration below, so it's +3 minutes without that:
```diff --git a/config/environments/development.rb …
```

Cypress fixes around timing and element existance

---

app/controllers/application_controller/wait_for_task.rb

If the `async_interval` is over `1000` and a string then the `async_interval += 250 if async_interval < 5000` will throw an exception.
Fixes https://github.com/ManageIQ/manageiq-ui-classic/issues/9443

Fix wait_for_task comparison of String with 5000

---

app/helpers/catalog_helper.rb
app/javascript/components/terraform-template-catalog-form/terraform-template-catalog-form.schema.js
app/views/catalog/_sandt_tree_show.html.haml

We remove redundant extra_vars, as the extra_vars is not (additionally) needed as input params (unlike in ansible)
For input params, we now have the input params for Terraform Template coming from service dialog. As the service dialog for the Terraform Template now can be dynamically generated from Terraform Template input parameters in UI.
to be added...
to be added...
Fixes https://github.com/ManageIQ/manageiq-providers-embedded_terraform/issues/96

Remove redundant catalog variables (extra_vars) for terraform-template

---

.github/workflows/cypress.yaml
app/javascript/oldjs/application.js

This should allow us to remove a lot of the force: true we had to add for many DOM elements near the top of the page as the notifications could cover these elements and various cypress interactions with covered elements would fail.
Note, we'll need to figure out how to test notifications differently.
Related to changes in https://github.com/ManageIQ/manageiq/pull/23461

Disable miq_debug for cypress for now

---

cypress/e2e/ui/Automation/Embedded-Automate/customization.cy.js

We copy the dialog with the same description but different name. We then select one of the two (copy or original) in the tree. Either the copy or original is now displayed, the assertion on the name could be wrong since we're asserting the name is the "copy" name.
We're in the cleanup code.  We don't really care about these assertions. We now select either of the two "Test Description" dialogs, remove the first, verify the main div is correct, select the second and remove it. There is no need to check the Name field or the CodeMirror-code to confirm the removal was correct.
Note, this was extracted from https://github.com/ManageIQ/manageiq-ui-classic/pull/9452
In this screenshot, you can see the cleanup code AFTER it selects one of the two "Test Description" dialogs.  One is the original, …

Remove incorrect and unneeded assertions

---

app/controllers/application_controller/wait_for_task.rb

I hit this when running the UI tests without a simulate_queue_worker running. I believe this is a bug that can happen where this code path provides an interval of type string.
With no workers running, such as rails server with no simulate queue worker: Go to: Overview->Reports->Reports accordion->Configuration->New Report
Give it a name, title, "base the report on" such as availability zone, add a field such as Ems Ref to the selected fields.  Then, click "preview" tab. Click "generate report preview" button... Before this change, it blows up with:
[TypeError] no implicit conversion of Integer into String
Note, this is a similar change as #9444

Support string interval coming from report preview

---

app/stylesheet/ddf_override.scss
app/views/layouts/_ae_resolve_options.html.haml
app/views/miq_ae_tools/resolve_react.html.haml
app/views/shared/buttons/_ab_form.html.haml

Fix the button form. This was broken by this pr: https://github.com/ManageIQ/manageiq-ui-classic/pull/9202. This pr fixes the button form so it correctly renders and fixes a small styling issue.
Before:
The form buttons are missing and fields are missing on the "Advanced" tab of the button form.
After:

Fix button form

---

app/controllers/ops_controller.rb
app/controllers/ops_controller/settings/common.rb
app/helpers/application_helper.rb
app/javascript/components/ops-tenant-form/ops-tenant-form.jsx
app/javascript/components/ops-tenant-form/ops-tenant-form.schema.js
app/javascript/spec/ansible-edit-catalog-form/mockdata.js
app/javascript/spec/ops-tenant-form/ops-tenant-form.spec.js
app/views/ops/_settings_server_tab.html.haml

Dependent upon:
Before
======
use_config_for_attributes used to not allow editing of the name field
After
=====
Tenant model works just a standard model

Drop Tenant#use_config_for_attributes

---

app/controllers/mixins/actions/vm_actions/reconfigure.rb

For VMs without any host, reconfigure resulted in internal server error `[NoMethodError] undefined method `switches' for nil:NilClass`
Before fix -
After fix - 

Fix error on VM reconfigure when host is nil

---

app/controllers/miq_ae_customization_controller.rb

eThis pr fixes the button group reorder form since it was missing the save / reset / cancel buttons
Before:
After:

Fix button group reorder form buttons

---

.yarnrc.yml

Update the npmauditexclude list. Added angular-sanitize to the list since it is on the latest version and can't be removed since it is used by angular-patternfly

Update npmauditexclude list

---

app/javascript/components/search-bar/index.jsx
app/javascript/spec/search-bar/__snapshots__/search-bar.spec.js.snap

Revert #9367 as it causing an issue with the search bar on explorer pages. When using the search bar on an explorer page it is timing out the user and logging them out. The search bar on non-explorer pages seems to work fine without the form token.

Revert "Fix searchbar formtoken issue"

---

cypress/e2e/ui/Settings/Application-Settings/settings_details_tab.cy.js

These tests are basically the same thing.  If this form were to break, all
these tests would likely fail.  It's probably better to avoid the extra
setup/teardown for each test by consolidating into a single test.
See also:
https://docs.cypress.io/app/core-concepts/best-practices#Creating-Tiny-Tests-With-A-Single-Assertion

Consolidate tests that click rows in the settings details table

---

cypress/fixtures/empty_notifications.json
cypress/fixtures/empty_notifications_expanded.json
cypress/support/commands/stub_notifications.js
cypress/support/commands/throttle_response.js
cypress/support/e2e.js

This PR adds commands to delay and throttle network responses and to stub notifications with empty fixtures.
Neither is enabled by default but an example is provided.  We can enable them at will in tests or in the global beforeEach.
cc @GilbertCherrie @Fryguy

Add cypress commands for throttling and notification stubs

---

app/controllers/application_controller/ci_processing.rb
spec/spec_helper.rb

* Fix AS::Deprecation error around using deprecator or an instance
Similar to https://github.com/ManageIQ/manageiq/pull/23249
* Fix 'Rails 7.1 has deprecated the singular fixture_path'
Rails 7.1 has deprecated the singular fixture_path in favour of an array.You should migrate to plural

Rails 7.2 - Fix breakage and deprecation

---

cypress/README.md
cypress/support/commands/custom_logging_commands.js
cypress/support/commands/toolbar.js
cypress/support/e2e.js

When an invalid toolbar option is provided - `cy.toolbar('Configuration', 'Add a new Timesheet')`, the test would still continue and fail at a later stage
Errors out when the toolbar option is not found:
If a wrong toolbar button name is given - `cy.toolbar('Applications')`, the test continues execution and fails downstream, masking the actual cause:
Errors out when the toolbar button name is not found:
Even when the toolbar button name is incorrect - `cy.toolbar('Applications', 'Add a new Schedule')`, the test continues to look for a matching toolbar option:
Immediately errors out when the toolbar button name is not found, skipping further option matching:
Improved chainability when matches are found, can be used like:
```
cy.toolbar('Configuration').then(() => {
// do something
});
``` …

Fixed toolbar to throw error on wrong option

---

cypress/e2e/ui/Settings/Application-Settings/edit_collect_logs.cy.js

PR that refactors Cypress tests for Collect Logs edit form also include review comments changes from https://github.com/ManageIQ/manageiq-ui-classic/pull/9508
@miq-bot assign @jrafanie

Edit collect logs form cypress refactor

---

app/controllers/ops_controller/settings/schedules.rb

This bug was found by @asirvadAbrahamVarghese
Fix the settings ops toolbar to not display while in the schedule form, similar to the other forms on the ops page.
Before:
After:
Still has the configuration button outside of the form.
No configuration button inside of the form.

Fix the settings ops schedule toolbar

---

app/controllers/miq_task_controller.rb
app/javascript/components/settings-tasks-form/index.jsx
app/views/layouts/_tasks.html.haml

Fix the delete on the tasks page.
Before:
Clicking delete on the task page made it seem like nothing was happening because no flash message would appear. The tasks are not deleted immediately, instead the deletion of the task is queued so it should alert the user of this in a flash message or else it seems like the task is not being deleted.
After:
This pr fixes this issue by alerting the user that the task deletion is queued and will occur.

Fix task page bugs

---

cypress/support/assertions/expect_alerts.js

So far, I’ve seen flash messages rendered inside `flash_msg_div`, but I’ve now observed them appearing without that parent structure.
**Flashs with `flash_msg_div` parent:**
**Flashs without `flash_msg_div` parent:**
@miq-bot assign @jrafanie

Updated selector for flash message

---

app/controllers/ops_controller/ops_rbac.rb
app/helpers/application_helper.rb
cypress/e2e/ui/Settings/Application-Settings/settings_access_control.cy.js

We expect a one to one feature assignment with existing product features.
This doesn't work with dynamic tenant features.
This dynamic tenant feature was only ever implemented for tenant quotas.
Related to:
https://github.com/ManageIQ/manageiq-ui-classic/pull/5123
https://github.com/ManageIQ/manageiq-ui-classic/pull/5129
https://github.com/ManageIQ/manageiq-ui-classic/pull/5142
Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9512
This recreates the issue found in https://github.com/ManageIQ/manageiq-ui-classic/issues/9512

Bypass feature validation for dynamic tenant features

---

app/controllers/catalog_controller.rb

PR fixes the issue mentioned in https://github.com/ManageIQ/manageiq-ui-classic/issues/9526
The problem was diagnosed and resolved with AI assistance, after slight tweaks
```
if automate_tree_needed?
page.replace("basic_info_div", :partial => "form_basic_info")
```
was the culprit here that duplicates "Basic Information" heading when "Display in Catalog" checkbox's onChange gets fired.
Restructuring the code to use an if-elsif chain with`page.replace("basic_info_div"...)` condition moved to the last ensures it's not executed when `params[:display]` is true which prevents the duplicate headings issue.
I was just verifying through these catalog types (others seem to be disabled, possibly due to missing data):
Amazon
Ansible Automation Platform
Ansible Playbook
Azure
Generic
Google
OpenShift …

Resolve duplicate Basic Info heading in create catalog item form

---

app/controllers/application_controller/buttons.rb
cypress.config.js
cypress/e2e/ui/Automation/Embedded-Automate/customization.cy.js

Fixes: https://github.com/ManageIQ/manageiq-ui-classic/issues/9470
This pr fixes an issue where changing the attributes or roles doesn't properly enable/disable the save button on the button form

Fix button form save button validation

---

cypress/README.md
cypress/e2e/ui/Settings/Application-Settings/edit_collect_logs.cy.js
cypress/e2e/ui/Settings/Application-Settings/settings_access_control.cy.js
cypress/support/commands/element_selectors.js

PR to enhance form elements selector commands to make it more readable as discussed in this [thread](https://github.com/ManageIQ/manageiq-ui-classic/pull/9549#discussion_r2285579068)
- renamed commands
- received args as object
- updated docs
- Switching from `input#${inputId}]`, `select#${selectId}]` ==> `input[id="${inputId}"]`, `select[id="${selectId}"]`.
When ids are separated by dots("endpoints.default.hostname"), `input#${inputId}]`, `select#${selectId}]` these selectors fail.
Unless the dots are escaped with double backslashes("endpoints\\.default\\.hostname"). Using attribute selectors avoids this problem.
@miq-bot assign @GilbertCherrie
@miq-bot add-reviewer @elsamaryv 
@miq-bot add-label refactoring

Enhance form element selectors

---

app/controllers/ping_controller.rb
spec/controllers/ping_controller_spec.rb

Use the new ActiveRecord::Base.connectable! method to get at the actual exception and provide better feednback on ping failures
Follow up to
- #9619 
Depends on

Better PingController errors

---

cypress/support/commands/toolbar.js

Unclear what issue occurred when the option was disabled and the command attempted to click it:
~Throws an error if the option is disabled:~ - Refer [comment](https://github.com/ManageIQ/manageiq-ui-classic/pull/9618#issuecomment-3317646786) for the fix result
@miq-bot assign @GilbertCherrie 
@miq-bot add-reviewer @elsamaryv 

Updated to throw an error when the specified toolbar option is disabled

---

cypress/e2e/ui/Settings/Application-Settings/c_and_u_gap_collection.cy.js

CP4AIOPS-18405
Pr that adds cypress tests for C & U Gap Collection form: Settings > Application Settings > Diagnostics > ManageIQ Region > Zone Default Zone > C & U Gap Collection
- Validate form elements
- Validate error with an invalid date range
- Validate Save functionality
@miq-bot assign @GilbertCherrie

Added automated tests with cypress for C & U Gap Collection form

---

.github/workflows/ci.yaml
.github/workflows/cypress.yaml

I noticed that renovate and dependabot PRs run twice because they build they branches in the main repo, and trigger both a push and pull_request event. We only need PR events for them, so we should exclude them.  I want to see how this works, then I plan to blast this out to the other repos.

Ignore push event on bot PRs

---

cypress/e2e/ui/Settings/Application-Settings/tenant.cy.js

CP4AIOPS-16943
Pr that adds cypress tests for Tenants form(Settings -> Application Settings ->Access Control -> Tenants)
- Edit parent tenant
- Add project to parent tenant
- Manage quotas with parent tenant
- Add, edit and delete child tenant
- Add project to child tenant
- Manage quotas with child tenant
@miq-bot assign @elsamaryv 

Added automated tests with cypress for Tenants form

---

cypress/e2e/ui/Settings/Application-Settings/schedule.cy.js

PR to refactor schedule form cypress test
- Use form element selector commands
- Replace `accordionItem` with `selectAccordionItem` command
- Other minor code improvements
@miq-bot assign @GilbertCherrie 
@miq-bot add-label refactoring

Schedule form cypress refactor
